function report = checkpoint()
%IPMTESTS.BASELINE.CHECKPOINT Verify trusted atomic same-grid restart.

fprintf('Running IPM checkpoint/restart verification...\n');
testDirectory = tempname;
mkdir(testDirectory);
directoryCleanup = onCleanup(@()cleanup_directory(testDirectory));

dynamicOptions = dynamic_options();
dynamic = verify_split(dynamicOptions,testDirectory,'dynamic');

highOrderOptions = physical_options();
highOrderOptions.spatialDiscretization = 'high_order';
highOrderOptions.transportScheme = 'weno5_fd';
highOrderOptions.timeIntegrator = 'ssprk54';
highOrderOptions.remeshTransferScheme = 'high_order';
highOrder = verify_split(highOrderOptions,testDirectory,'high_order');
untrustedSuppressed = verify_untrusted_suppressed(testDirectory);

checkpointData = ipm.output.readCheckpoint(dynamic.checkpointFile);
assert(checkpointData.schemaVersion == 4 && ...
    checkpointData.payload.state.config.schemaVersion == 4 && ...
    ~isfield(checkpointData.payload.state,'timeStep') && ...
    ~isfield(checkpointData.payload.state,'rhsCache'), ...
    'ipm:CheckpointSchemaVersion', ...
    ['New checkpoints must carry checkpoint/config schema version 4 and ' ...
    'must not persist derived timestep or RHS-cache state.']);
for legacyVersion = 1:3
    legacyCheckpoint = checkpointData;
    legacyCheckpoint.schemaVersion = legacyVersion;
    assert_throws_with_text(@()ipm.output.readCheckpoint(legacyCheckpoint), ...
        'ipm:CheckpointIncompatibleSchema','no-feedback');
end

serializedDerivedCache = checkpointData;
serializedDerivedCache.payload.state.rhsCache = struct('forged',true);
serializedDerivedCache.signature = ipm.output.checkpointSignature( ...
    serializedDerivedCache.payload);
assert_throws(@()ipm.output.readCheckpoint(serializedDerivedCache), ...
    'ipm:CheckpointDerivedCache');

noncanonicalClock = checkpointData;
noncanonicalClock.payload.state.normalizedTime = ...
    noncanonicalClock.payload.state.normalizedTime+1e-6;
noncanonicalClock.payload.log.history.common.t(end) = ...
    noncanonicalClock.payload.state.normalizedTime;
noncanonicalClock.signature = ipm.output.checkpointSignature( ...
    noncanonicalClock.payload);
assert_throws(@()ipm.output.readCheckpoint(noncanonicalClock), ...
    'ipm:CheckpointCanonicalClock');
nonunitTimeSpeed = checkpointData;
nonunitTimeSpeed.payload.log.history.common.timeSpeed(end) = 0.5;
nonunitTimeSpeed.signature = ipm.output.checkpointSignature( ...
    nonunitTimeSpeed.payload);
assert_throws(@()ipm.output.readCheckpoint(nonunitTimeSpeed), ...
    'ipm:CheckpointCanonicalClock');
noncanonicalRate = checkpointData;
noncanonicalRate.payload.log.history.common.c_l(end) = ...
    noncanonicalRate.payload.log.history.common.c_l(end)+1e-3;
noncanonicalRate.signature = ipm.output.checkpointSignature( ...
    noncanonicalRate.payload);
assert_throws(@()ipm.output.readCheckpoint(noncanonicalRate), ...
    'ipm:CheckpointCanonicalRate');

assert_throws(@()ipm.output.restoreCheckpoint( ...
    checkpointData,struct('cfl',0.2)), ...
    'ipm:CheckpointOverrideNotAllowed');
assert_throws(@()ipm.output.restoreCheckpoint( ...
    checkpointData,struct('maxSteps',1)), ...
    'ipm:CheckpointHorizon');

poisonedDerived = checkpointData;
poisonedDerived.payload.state.rescaling.scalingContract = 'forged';
poisonedDerived.payload.state.rescaling.cOmegaGauge = 'none';
poisonedDerived.payload.state.rescaling.enabled = false;
poisonedDerived.payload.state.rescaling.pinIndex = 1;
poisonedDerived.payload.state.rescaling.originIndex = 1;
poisonedDerived.payload.state.rescaling.injectedDerivedField = 17;
poisonedDerived.signature = ipm.output.checkpointSignature( ...
    poisonedDerived.payload);
[whitelistState,~,~] = ipm.output.restoreCheckpoint(poisonedDerived);
[restoredRhoRate,restoredFlow] = ipm.evolve.flow( ...
    whitelistState.rho,whitelistState.ops,whitelistState.scale);
expectedRestoredCache = ipm.evolve.makeRhsCache( ...
    whitelistState.rho,restoredRhoRate,restoredFlow, ...
    whitelistState.ops,whitelistState.scale);
restoredCacheRebuilt = isfield(whitelistState,'rhsCache') && ...
    isequaln(whitelistState.rhsCache,expectedRestoredCache);
savedReferences = checkpointData.payload.state.rescaling;
[~,expectedPinIndex] = min(abs(whitelistState.ops.x-savedReferences.pinX));
[~,expectedOriginIndex] = min(abs(whitelistState.ops.x));
assert(strcmp(whitelistState.ops.rescaling.scalingContract, ...
    checkpointData.payload.state.config.scaling.scalingContract) && ...
    strcmp(whitelistState.ops.rescaling.cOmegaGauge, ...
    checkpointData.payload.state.config.scaling.cOmegaGauge) && ...
    whitelistState.ops.rescaling.enabled && ...
    whitelistState.ops.rescaling.pinIndex == expectedPinIndex && ...
    whitelistState.ops.rescaling.originIndex == expectedOriginIndex && ...
    ~isfield(whitelistState.ops.rescaling,'injectedDerivedField') && ...
    isequaln(whitelistState.ops.rescaling.pinX,savedReferences.pinX) && ...
    isequaln(whitelistState.ops.rescaling.strainTarget, ...
    savedReferences.strainTarget) && ...
    isequaln(whitelistState.ops.rescaling.referencePeakPoints, ...
        savedReferences.referencePeakPoints) && ...
    isequaln(whitelistState.ops.rescaling.safetyPeakPoints, ...
        savedReferences.safetyPeakPoints) && restoredCacheRebuilt, ...
    'ipm:CheckpointReferenceWhitelist', ...
    ['Checkpoint restore must retain runtime references without letting ' ...
    'stored configuration-derived fields overwrite fresh ops, and must ' ...
    'rebuild rather than deserialize its transient RHS cache.']);
assert(strcmp(whitelistState.timeStep.activeLimiter,'restored') && ...
    all(isnan([whitelistState.timeStep.dt,whitelistState.timeStep.rate, ...
    whitelistState.timeStep.dtCfl,whitelistState.timeStep.realizedCfl])), ...
    'ipm:CheckpointTimestepProvenance', ...
    'Checkpoint restore did not reconstruct empty timestep provenance.');

retiredFeedbackState = checkpointData;
retiredFeedbackState.payload.state.rescaling.maxWidthRateCorrection = 1e9;
retiredFeedbackState.signature = ipm.output.checkpointSignature( ...
    retiredFeedbackState.payload);
assert_throws(@()ipm.output.readCheckpoint(retiredFeedbackState), ...
    'ipm:CheckpointRescaling');

retiredLimiterState = checkpointData;
retiredLimiterState.payload.state.rescaling.maxDynamicRate = 1e9;
retiredLimiterState.signature = ipm.output.checkpointSignature( ...
    retiredLimiterState.payload);
assert_throws(@()ipm.output.readCheckpoint(retiredLimiterState), ...
    'ipm:CheckpointRescaling');

tampered = checkpointData;
tampered.payload.state.x(2) = tampered.payload.state.x(2)+1e-8;
assert_throws(@()ipm.output.readCheckpoint(tampered), ...
    'ipm:CheckpointSignature');

report = struct('dynamic',dynamic,'highOrder',highOrder, ...
    'untrustedSuppressed',untrustedSuppressed, ...
    'tamperRejected',true,'canonicalIdentityRejected',true, ...
    'forbiddenOverrideRejected',true,'legacySchemasRejected',true, ...
    'referenceWhitelistEnforced',true, ...
    'transientRhsCacheRebuilt',restoredCacheRebuilt,'passed',true);
fprintf(['IPM checkpoint/restart verification passed: exact dynamic and ' ...
    'high-order split runs; untrusted terminal state suppressed.\n']);
end

function suppressed = verify_untrusted_suppressed(testDirectory)
options = physical_options();
options.nx = 65;
options.ny = 33;
options.spatialDiscretization = 'high_order';
options.transportScheme = 'weno5_fd';
options.timeIntegrator = 'ssprk54';
options.remeshTransferScheme = 'high_order';
baseFile = fullfile(testDirectory,'untrusted.mat');
options.checkpoint = struct('file',baseFile,'every',1e-12,'atExit',true);
result = ipm.solve(options);
trusted = ipm.output.continuousTrustedPrefix( ...
    ipm.output.trustedMask(result));
files = dir(fullfile(testDirectory,'untrusted_*_step*.mat'));
assert(~trusted(end) && isempty(files), ...
    'ipm:CheckpointUntrustedPersistence', ...
    'An untrusted terminal record produced a restart checkpoint.');
assert_throws(@()ipm.output.checkpointFromResult(result), ...
    'ipm:CheckpointResultTrust');
suppressed = true;
end

function summary = verify_split(options,testDirectory,label)
baseFile = fullfile(testDirectory,[label,'.mat']);
write_sentinel(baseFile);
options.checkpoint = struct('file',baseFile,'every',2e-4,'atExit',false);
uninterrupted = ipm.solve(options);
files = dir(fullfile(testDirectory,[label,'_*_step*.mat']));
assert(~isempty(files),'ipm:CheckpointTestMissing', ...
    'The split run did not produce a checkpoint.');

selectedFile = '';
selectedStep = Inf;
for index = 1:numel(files)
    candidateFile = fullfile(testDirectory,files(index).name);
    candidate = ipm.output.readCheckpoint(candidateFile);
    step = candidate.payload.state.step;
    if step > 0 && step < uninterrupted.state.steps && step < selectedStep
        selectedFile = candidateFile;
        selectedStep = step;
    end
end
assert(~isempty(selectedFile),'ipm:CheckpointTestSplit', ...
    'No interior checkpoint was available for the split run.');
saved = ipm.output.readCheckpoint(selectedFile);
resumed = ipm.solve(struct(),selectedFile);

bridgeTarget = fullfile(testDirectory,[label,'_terminal.mat']);
[~,bridgeFile] = ipm.output.checkpointFromResult( ...
    uninterrupted,bridgeTarget);
bridge = ipm.output.readCheckpoint(bridgeFile);
assert(isequal(bridge.payload.state.rho,uninterrupted.state.rho) && ...
    isequal(bridge.payload.state.x,uninterrupted.grid.x) && ...
    isequal(bridge.payload.state.y,uninterrupted.grid.y) && ...
    bridge.payload.state.step == uninterrupted.state.steps && ...
    bridge.schemaVersion == 4 && ...
    bridge.payload.state.config.schemaVersion == 4 && ...
    bridge.trustedRecord, ...
    'ipm:CheckpointResultBridge', ...
    'Trusted terminal-result conversion lost the terminal state/grid.');
legacyResult = as_schema_three(uninterrupted);
assert(isequaln(ipm.output.validate(legacyResult),legacyResult), ...
    'ipm:CheckpointLegacyResultReadable', ...
    'A schema-3 result must remain readable before bridge rejection.');
assert_throws(@()ipm.output.checkpointFromResult(legacyResult), ...
    'ipm:CheckpointResultConfigVersion');

uninterruptedComparable = rmfield(uninterrupted,'metadata');
resumedComparable = rmfield(resumed,'metadata');
assert(isequaln(uninterruptedComparable,resumedComparable), ...
    'ipm:CheckpointSplitExact', ...
    '%s restart did not reproduce the uninterrupted result exactly.',label);
assert(~uninterrupted.config.output.storeSnapshots && ...
    isempty(uninterrupted.snapshots.rho) && ...
    isempty(saved.payload.log.snapshotRho) && ...
    isequal(size(saved.payload.state.rho), ...
    [numel(saved.payload.state.y),numel(saved.payload.state.x)]), ...
    'ipm:CheckpointSnapshotIndependence', ...
    'storeSnapshots=false lost the standalone checkpoint field/grid pair.');
assert(strcmp(fileread(baseFile),'sentinel'), ...
    'ipm:CheckpointAtomicOverwrite', ...
    'Checkpoint persistence overwrote the requested base artifact.');
assert(saved.payload.cursor.nextOutput > ...
    saved.payload.state.scale.canonicalTime && ...
    saved.payload.cursor.lastCheckpointStep == saved.payload.state.step, ...
    'ipm:CheckpointCursorContract', ...
    'The checkpoint did not preserve its output/cadence cursor.');

extendedTime = options.physicalFinalTime+options.maxDt;
[extendedState,~,~] = ipm.output.restoreCheckpoint(selectedFile, ...
    struct('physicalFinalTime',extendedTime, ...
    'maxSteps',options.maxSteps+2,'verbose',false));
assert(extendedState.config.time.physicalFinalTime == extendedTime && ...
    extendedState.config.time.maxSteps == options.maxSteps+2 && ...
    strcmp(extendedState.timeStep.activeLimiter,'restored') && ...
    strcmp(extendedState.config.transport.transportScheme, ...
    uninterrupted.config.transport.transportScheme), ...
    'ipm:CheckpointResumeWhitelist', ...
    'Allowed horizon overrides changed or lost the frozen numerical tuple.');

summary = struct('checkpointFile',selectedFile,'checkpointStep',selectedStep, ...
    'resultBridgeFile',bridgeFile, ...
    'finalStep',uninterrupted.state.steps, ...
    'historyRecords',numel(uninterrupted.history.common.t), ...
    'exact',true,'storeSnapshots',false);
end

function result = as_schema_three(result)
result.config.schemaVersion = 3;
result.config.scaling = rmfield(result.config.scaling,'scalingContract');
result.config.scaling.adaptiveLengthScaling = false;
result.config.scaling.widthExpansionStrength = 1;
result.config.scaling.widthContractionOnset = 1.35;
result.config.scaling.widthContractionStrength = 28;
result.config.scaling.maxWidthRateCorrection = 16;
end

function options = physical_options()
options = struct('nx',129,'ny',65,'xlim',[-4,4],'ymax',4, ...
    'gridMode','stretched','gridStretch',[1,1], ...
    'gridStretchAutomatic',false,'targetCenterSpacing',[0.05,0.05], ...
    'initialCondition','degenerate','degeneratePower',4, ...
    'rescalingMode','physical','farBoundaryMode','dirichlet_zero', ...
    'physicalFinalTime',4e-4,'maxDt',1e-4,'minDt',1e-12, ...
    'maxSteps',8,'outputEvery',1e-4,'cfl',0.25, ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'gradientStop',1e9,'rangeStopTolerance',0.1, ...
    'oscillationTVTolerance',10,'positiveWallNegativeTolerance',0.99, ...
    'storeSnapshots',false,'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
end

function options = dynamic_options()
options = ipm.config.activeCase();
overrides = physical_options();
overrides.gridStretch = [1.5,1.5];
overrides.initialCondition = 'degenerate_primitive';
overrides.degeneratePower = 8;
overrides.rescalingMode = 'dynamic';
names = fieldnames(overrides);
for index = 1:numel(names)
    options.(names{index}) = overrides.(names{index});
end
end

function assert_throws(action,identifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:CheckpointUnexpectedError', ...
        'Expected %s but received %s.',identifier,exception.identifier);
    return;
end
error('ipm:CheckpointMissingError','Expected error %s.',identifier);
end

function assert_throws_with_text(action,identifier,fragment)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier) && ...
        contains(exception.message,fragment), ...
        'ipm:CheckpointUnexpectedError', ...
        'Expected %s mentioning %s but received %s: %s.', ...
        identifier,fragment,exception.identifier,exception.message);
    return;
end
error('ipm:CheckpointMissingError','Expected error %s.',identifier);
end

function write_sentinel(fileName)
fileId = fopen(fileName,'w');
if fileId < 0
    error('ipm:CheckpointTestFile','Could not create %s.',fileName);
end
cleanup = onCleanup(@()fclose(fileId));
fwrite(fileId,'sentinel','char');
end

function cleanup_directory(directory)
if isfolder(directory)
    try
        rmdir(directory,'s');
    catch exception
        fprintf(2,'IPM warning: could not remove checkpoint test %s: %s\n', ...
            directory,exception.message);
    end
end
end
