function report = config()
%IPMTESTS.BASELINE.CONFIG Fast regressions for option resolution and setup purity.

schema = ipm.config.schema();
optionNames = fieldnames(schema.options);
descriptorFields = {'domain','default','hasDefault','kind','rule', ...
    'allowed','errorId'};
allowedKinds = {'numeric','boolean','enum','initial_condition','path', ...
    'metadata','checkpoint','autonomous_mesh','initial_mesh_observation','custom_coordinate'};
defaultMask = false(size(optionNames));
kindNames = cell(size(optionNames));
for optionIndex = 1:numel(optionNames)
    name = optionNames{optionIndex};
    descriptor = schema.options.(name);
    assert(isstruct(descriptor) && isscalar(descriptor) && ...
        isequal(sort(fieldnames(descriptor)),sort(descriptorFields(:))) && ...
        ischar(descriptor.domain) && ...
        any(strcmp(descriptor.domain,schema.domainNames)) && ...
        islogical(descriptor.hasDefault) && isscalar(descriptor.hasDefault) && ...
        ischar(descriptor.kind) && any(strcmp(descriptor.kind,allowedKinds)) && ...
        ischar(descriptor.rule) && iscell(descriptor.allowed) && ...
        ischar(descriptor.errorId), ...
        'ipm:ConfigSchemaDescriptor', ...
        'Option "%s" has incomplete declarative metadata.',name);
    if strcmp(descriptor.kind,'numeric')
        assert(isfield(schema.rules,descriptor.rule), ...
            'ipm:ConfigSchemaRule', ...
            'Numeric option "%s" refers to an unknown rule.',name);
    end
    defaultMask(optionIndex) = descriptor.hasDefault;
    kindNames{optionIndex} = descriptor.kind;
end
assert(numel(optionNames) == 106 && sum(defaultMask) == 101 && ...
    isequal(sort(optionNames(~defaultMask)), ...
    sort({'checkpoint';'autonomousMesh';'initialMeshObservationFallback';'customX';'customY'})), ...
    'ipm:ConfigSchemaCoverage', ...
    ['The schema must declare 101 defaults, two optional custom axes, ' ...
    'and optional checkpoint/autonomous mesh/initial observation policies once.']);
assert(isequal(schema.domainNames, ...
    {'grid','time','physics','elliptic','transport','scaling', ...
    'remesh','diagnostics','output'}), ...
    'ipm:ConfigSchemaDomains', ...
    'The declarative schema must own the nine grouped domains.');

groupedDefault = ipm.config.resolve(struct());
groupNames = schema.domainNames;
assert(groupedDefault.schemaVersion == 4 && groupedDefault.frozen && ...
    isequal(fieldnames(groupedDefault), ...
    [{'schemaVersion';'frozen'};groupNames(:)]), ...
    'ipm:GroupedConfigDomains', ...
    'The frozen configuration is missing a declared option domain.');
groupedNameSets = cell(numel(groupNames),1);
for groupIndex = 1:numel(groupNames)
    groupName = groupNames{groupIndex};
    assert(isstruct(groupedDefault.(groupName)) && ...
        isscalar(groupedDefault.(groupName)), ...
        'ipm:GroupedConfigDomainType', ...
        'Configuration domain "%s" must be a scalar structure.',groupName);
    groupedNameSets{groupIndex} = fieldnames(groupedDefault.(groupName));
    for fieldIndex = 1:numel(groupedNameSets{groupIndex})
        field = groupedNameSets{groupIndex}{fieldIndex};
        assert(isfield(schema.options,field) && ...
            strcmp(schema.options.(field).domain,groupName), ...
            'ipm:GroupedConfigDomainOwnership', ...
            'Option "%s" is frozen in the wrong domain.',field);
    end
end
groupedNames = vertcat(groupedNameSets{:});
assert(numel(unique(groupedNames)) == numel(groupedNames) && ...
    isequal(sort(groupedNames),sort(optionNames(defaultMask))) && ...
    isequal(cellfun(@numel,groupedNameSets)',[8,8,13,6,5,26,19,5,11]) && ...
    groupedDefault.scaling.omegaGaugeWindowRadius == 0.75 && ...
    strcmp(groupedDefault.scaling.scalingContract, ...
    'exact_gauge_no_feedback_v1') && ...
    groupedDefault.scaling.lengthScaleGain == 1 && ...
    groupedDefault.scaling.widthGaugeGain == 0 && ...
    groupedDefault.scaling.omegaGaugeGain == 0 && ...
    groupedDefault.scaling.travelingWaveGain == 0, ...
    'ipm:GroupedConfigCoverage', ...
    'Grouped configuration domains must cover each resolved option once.');
defaultResolved = flatten_config(groupedDefault,schema);
assert(isstruct(groupedDefault.output.caseMetadata) && ...
    isscalar(groupedDefault.output.caseMetadata) && ...
    ~isfield(ipm.mesh.build(groupedDefault),'caseMetadata'), ...
    'ipm:CaseMetadataBoundary', ...
    'Case metadata must be grouped with output and excluded from operators.');

assert_error(@()ipm.config.resolve([]),'ipm:BadOptions');
assert_error(@()ipm.config.resolve(repmat(struct(),1,2)),'ipm:BadOptions');
assert_error(@()ipm.config.resolve(struct( ...
    'initialCondition','degenerate_density')),'ipm:BadInitialCondition');
anchorSlopeConfig = resolve_values(struct( ...
    'cOmegaGauge','ANCHOR_WALL_SLOPE', ...
    'lengthGauge','TRANSPORT_ANCHOR'));
quadraticPeakConfig = resolve_values(struct( ...
    'cOmegaGauge','WALL_OMEGA_QUADRATIC_PEAK'));
anchorWindowConfig = resolve_values(struct( ...
    'cOmegaGauge','ANCHOR_WALL_WINDOW_L2', ...
    'lengthGauge','TRANSPORT_ANCHOR', ...
    'omegaGaugeWindowRadius',0.5));
anchorTemplateConfig = resolve_values(struct( ...
    'cOmegaGauge','ANCHOR_WALL_TEMPLATE_PROJECTION', ...
    'lengthGauge','TRANSPORT_ANCHOR','adaptiveRemesh',false));
anchorBulkConfig = resolve_values(struct( ...
    'cOmegaGauge','ANCHOR_BULK_GRADIENT_L2', ...
    'lengthGauge','TRANSPORT_ANCHOR'));
anchorL4Config = resolve_values(struct( ...
    'cOmegaGauge','ANCHOR_WALL_WINDOW_L4', ...
    'lengthGauge','TRANSPORT_ANCHOR'));
assert(strcmp(anchorSlopeConfig.cOmegaGauge,'anchor_wall_slope') && ...
    strcmp(quadraticPeakConfig.cOmegaGauge, ...
        'wall_omega_quadratic_peak') && ...
    strcmp(anchorWindowConfig.cOmegaGauge,'anchor_wall_window_l2') && ...
    strcmp(anchorTemplateConfig.cOmegaGauge, ...
    'anchor_wall_template_projection') && ...
    strcmp(anchorBulkConfig.cOmegaGauge,'anchor_bulk_gradient_l2') && ...
    strcmp(anchorL4Config.cOmegaGauge,'anchor_wall_window_l4') && ...
    anchorWindowConfig.omegaGaugeWindowRadius == 0.5, ...
    'ipm:ConfigAnchorWallGaugeNormalization', ...
    'The anchor-wall c_omega gauge names were not normalized.');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_wall_slope','lengthGauge','local_strain')), ...
    'ipm:AnchorWallGaugeRequiresTransportAnchor');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_wall_strain', ...
    'lengthGauge','transport_anchor')), ...
    'ipm:RetiredCOmegaGauge');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_wall_window_l2', ...
    'lengthGauge','local_strain')), ...
    'ipm:AnchorWallGaugeRequiresTransportAnchor');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_wall_window_l2', ...
    'lengthGauge','transport_anchor','transportAnchorX',1.1)), ...
    'ipm:OmegaGaugeWindowAnchor');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_wall_window_l2', ...
    'lengthGauge','transport_anchor','omegaGaugeWindowRadius',1)), ...
    'ipm:OmegaGaugeWindowDomain');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_bulk_gradient_l2', ...
    'lengthGauge','transport_anchor','ymax',0.5, ...
    'omegaGaugeWindowRadius',0.5)), ...
    'ipm:OmegaGaugeWindowDomain');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_wall_template_projection', ...
    'lengthGauge','transport_anchor','adaptiveRemesh',true)), ...
    'ipm:TemplateGaugeRequiresFixedMesh');

retiredScalingOptions = {'maxDynamicRate','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
for retiredIndex = 1:numel(retiredScalingOptions)
    retiredName = retiredScalingOptions{retiredIndex};
    assert_error(@()resolve_values(struct(retiredName,0)), ...
        'ipm:UnknownOption');
end
assert_any_error(@()resolve_values(struct('lengthScaleGain',1+eps)), ...
    'lengthScaleGain');
assert_any_error(@()resolve_values(struct('widthGaugeGain',realmin)), ...
    'widthGaugeGain');
assert_any_error(@()resolve_values(struct('omegaGaugeGain',realmin)), ...
    'omegaGaugeGain');
assert_any_error(@()resolve_values(struct('travelingWaveGain',realmin)), ...
    'travelingWaveGain');
assert_error(@()resolve_values(struct( ...
    'cOmegaGauge','anchor_wall_window_l2', ...
    'lengthGauge','transport_anchor','xlim',[-1.5,1.5], ...
    'omegaGaugeWindowRadius',0.5)), ...
    'ipm:OmegaGaugeWindowDomain');

caseMetadata = struct('family','bessel_two_scale','mu',1.25);
metadataResolved = resolve_values(struct('caseMetadata',caseMetadata));
assert(isequal(metadataResolved.caseMetadata,caseMetadata), ...
    'ipm:CaseMetadataRoundTrip', ...
    'Structured case metadata did not survive option resolution.');
assert_error(@()resolve_values(struct('caseMetadata',[])), ...
    'ipm:BadCaseMetadata');
checkpointPolicy = struct('file','result/test_checkpoint.mat', ...
    'every',0.25,'atExit',false);
checkpointResolved = resolve_values(struct('checkpoint',checkpointPolicy));
assert(checkpointResolved.checkpoint.enabled && ...
    strcmp(checkpointResolved.checkpoint.file,checkpointPolicy.file) && ...
    checkpointResolved.checkpoint.every == checkpointPolicy.every && ...
    ~checkpointResolved.checkpoint.atExit, ...
    'ipm:CheckpointPolicyRoundTrip', ...
    'The optional checkpoint policy did not normalize correctly.');
assert_error(@()resolve_values(struct( ...
    'checkpoint',struct('file','x.mat','every',0))), ...
    'ipm:BadCheckpointPolicy');
assert_error(@()resolve_values(struct( ...
    'checkpoint',struct('unexpected',1))), ...
    'ipm:BadCheckpointPolicy');

mixedCase = resolve_values(struct( ...
    'gridMode','UNIFORM','farBoundaryMode',"GREEN", ...
    'transportBoundaryMode','OPEN','transportScheme','MUSCL_MINMOD', ...
    'spatialDiscretization','LEGACY_SECOND_ORDER', ...
    'timeIntegrator','SSPRK3', ...
    'wallTransportMode','CONSERVATIVE_FLUX', ...
    'symmetryMode','DOUBLE_ODD_OMEGA', ...
    'remeshReferenceMode','ORIGINAL','remeshTransferScheme','PCHIP', ...
    'remeshAxisProfile','NESTED', ...
    'rescalingMode','PHYSICAL','dynamicScaleGeometry','ISOTROPIC', ...
    'anisotropicGaugeMode','FIXED','anisotropicPoissonSolver','DIRECT', ...
    'cOmegaGauge','WALL_OMEGA_PEAK', ...
    'lengthGauge','OMEGA_PEAK_LOCATION', ...
    'initialCondition','DEGENERATE'));
normalizedNames = [optionNames(strcmp(kindNames,'enum'));{'initialCondition'}];
for nameIndex = 1:numel(normalizedNames)
    value = mixedCase.(normalizedNames{nameIndex});
    assert(ischar(value) && strcmp(value,lower(value)), ...
        'ipm:EnumNormalization', ...
        'Option "%s" was not normalized to canonical lower-case text.', ...
        normalizedNames{nameIndex});
end
functionCondition = @(x,y)x+0*y;
functionResolved = resolve_values(struct( ...
    'initialCondition',functionCondition));
assert(isequal(functionResolved.initialCondition,functionCondition), ...
    'ipm:InitialFunctionHandle', ...
    'A scalar initial-condition function handle was not preserved.');
signGateDisabled = resolve_values(struct( ...
    'positiveWallNegativeTolerance',Inf));
assert(isinf(signGateDisabled.positiveWallNegativeTolerance), ...
    'ipm:SignGateDisable', ...
    'An infinite tolerance must disable the optional positive-wall sign gate.');

booleanNames = optionNames(strcmp(kindNames,'boolean'));
booleanOverrides = struct();
for nameIndex = 1:numel(booleanNames)
    booleanOverrides.(booleanNames{nameIndex}) = mod(nameIndex,2);
end
booleanResolved = resolve_values(booleanOverrides);
for nameIndex = 1:numel(booleanNames)
    assert(islogical(booleanResolved.(booleanNames{nameIndex})) && ...
        isscalar(booleanResolved.(booleanNames{nameIndex})), ...
        'ipm:BooleanNormalization', ...
        'Option "%s" was not normalized to scalar logical.', ...
        booleanNames{nameIndex});
    assert_error(@()resolve_values(struct( ...
        booleanNames{nameIndex},2)),'ipm:BadBoolean');
end

% Every default field must reject a deliberately invalid value.  This is a
% compact completeness guard for the flat public contract, not just a
% sample of the most frequently changed options.
defaultNames = fieldnames(defaultResolved);
enumNames = normalizedNames;
for nameIndex = 1:numel(defaultNames)
    name = defaultNames{nameIndex};
    invalid = defaultResolved;
    if any(strcmp(name,enumNames))
        invalid.(name) = '__invalid__';
    elseif any(strcmp(name,booleanNames))
        invalid.(name) = 2;
    elseif any(strcmp(name,{'resultFile','videoFile'}))
        invalid.(name) = 42;
    elseif strcmp(name,'xlim')
        invalid.(name) = [NaN,NaN];
    elseif strcmp(name,'caseMetadata')
        invalid.(name) = [];
    else
        invalid.(name) = NaN;
    end
    if strcmp(name,'gridStretch')
        invalid.gridStretchAutomatic = false;
    end
    descriptor = schema.options.(name);
    if isempty(descriptor.errorId)
        assert_any_error(@()resolve_values(invalid),name);
    else
        assert_error(@()resolve_values(invalid),descriptor.errorId);
    end
end

assert_error(@()resolve_values(struct('customX',linspace(-1,1,1025))), ...
    'ipm:CustomGridPair');
assert_error(@()resolve_values(struct('customY',linspace(0,1,513))), ...
    'ipm:CustomGridPair');
customX = [-4,-2,-1,-0.4,1e-16,0.4,1,2,4+2*eps(4)];
customY = [0,0.01,0.04,0.1,0.25,0.5,1,2,3]';
customResolved = resolve_values(struct('nx',9,'ny',9, ...
    'xlim',[100,200],'ymax',100,'customX',customX,'customY',customY));
assert(isequal(customResolved.xlim, ...
    customResolved.customX([1,end])) && ...
    customResolved.ymax == 3 && customResolved.customY(1) == 0 && ...
    customResolved.customX(5) == 0 && ...
    isequal(customResolved.customX,-fliplr(customResolved.customX)), ...
    'ipm:CustomGridDomainSource', ...
    'Custom coordinates were not frozen as the canonical physical domain.');
assert_error(@()resolve_values(struct('nx',9,'ny',9, ...
    'customX',linspace(-1,1,9),'customY',linspace(0.01,1,9))), ...
    'ipm:CustomGridWall');
asymmetricX = [-4,-2,-1,-0.4,0,0.4,1,2,4.1];
assert_error(@()resolve_values(struct('nx',9,'ny',9, ...
    'customX',asymmetricX,'customY',customY)), ...
    'ipm:CustomGridSymmetry');
halfPlaneCustom = resolve_values(struct('nx',9,'ny',9, ...
    'symmetryMode','half_plane','customX',asymmetricX,'customY',customY));
assert(isequal(halfPlaneCustom.xlim,asymmetricX([1,end])) && ...
    halfPlaneCustom.ymax == customY(end), ...
    'ipm:HalfPlaneCustomDomain', ...
    'A valid asymmetric half-plane custom grid was not accepted.');

activeOverrides = ipm.config.activeCase();
activeResolved = resolve_values(activeOverrides);
assert(strcmp(activeResolved.initialCondition,'degenerate_primitive') && ...
    activeResolved.degeneratePower == 8 && ...
    strcmp(activeResolved.rescalingMode,'dynamic') && ...
    strcmp(activeResolved.dynamicScaleGeometry,'isotropic') && ...
    strcmp(activeResolved.cOmegaGauge,'wall_omega_peak') && ...
    isinf(activeResolved.finalTime) && ...
    activeResolved.physicalFinalTime == 2 && ...
    strcmp(activeResolved.resultFile,fullfile('result','production', ...
    'ipm_double_odd_dynamic.mat')), ...
    'ipm:ConfigActiveCase', ...
    'The maintained no-argument configuration no longer resolves as expected.');

implicitHalfPlane = resolve_values(struct( ...
    'symmetryMode','half_plane'));
explicitHalfPlane = resolve_values(struct( ...
    'symmetryMode','half_plane','lengthGauge','wall_density_width'));
assert(strcmp(implicitHalfPlane.lengthGauge,'local_strain') && ...
    strcmp(explicitHalfPlane.lengthGauge,'wall_density_width'), ...
    'ipm:ConfigLengthGaugeExplicitness', ...
    'Half-plane implicit or explicit length-gauge resolution changed.');

implicitAnisotropic = resolve_values(struct( ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic'));
explicitAnisotropic = resolve_values(struct( ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic', ...
    'adaptiveRemesh',true));
assert(~implicitAnisotropic.adaptiveRemesh && ...
    explicitAnisotropic.adaptiveRemesh && ...
    strcmp(implicitAnisotropic.anisotropicGaugeMode,'fixed'), ...
    'ipm:ConfigAnisotropicRemeshExplicitness', ...
    'Anisotropic implicit or explicit remesh resolution changed.');
peakTranslation = resolve_values(struct( ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic', ...
    'symmetryMode','half_plane','anisotropicGaugeMode','peak_translation'));
assert(strcmp(peakTranslation.anisotropicGaugeMode,'peak_translation'), ...
    'ipm:ConfigPeakTranslationSupport', ...
    'The supported half-plane peak-translation gauge was rejected.');
assert(strcmp(defaultResolved.spatialDiscretization,'legacy_second_order') && ...
    strcmp(defaultResolved.timeIntegrator,'ssprk3') && ...
    strcmp(defaultResolved.remeshTransferScheme,'pchip'), ...
    'ipm:SecondOrderDefaultContract', ...
    'Adding high-order paths changed a maintained second-order default.');
highOrderConfig = ipm.config.resolve(struct( ...
    'spatialDiscretization','HIGH_ORDER', ...
    'transportScheme','WENO5_FD','timeIntegrator','SSPRK54', ...
    'remeshTransferScheme','HIGH_ORDER'));
assert(highOrderConfig.schemaVersion == 4 && ...
    strcmp(highOrderConfig.transport.spatialDiscretization,'high_order') && ...
    strcmp(highOrderConfig.transport.transportScheme,'weno5_fd') && ...
    strcmp(highOrderConfig.time.timeIntegrator,'ssprk54') && ...
    strcmp(highOrderConfig.remesh.remeshTransferScheme,'high_order'), ...
    'ipm:HighOrderGroupedConfig', ...
    'A valid fourth-order tuple was not normalized into the grouped config.');
sixthOrderConfig = ipm.config.resolve(ipm.config.sixthOrder());
assert(sixthOrderConfig.schemaVersion == 4 && ...
    strcmp(sixthOrderConfig.transport.spatialDiscretization, ...
    'sixth_order') && ...
    strcmp(sixthOrderConfig.transport.transportScheme,'weno7_fd') && ...
    strcmp(sixthOrderConfig.time.timeIntegrator,'rk6') && ...
    strcmp(sixthOrderConfig.remesh.remeshTransferScheme, ...
    'sixth_order') && ...
    strcmp(sixthOrderConfig.grid.gridMode,'uniform') && ...
    ~sixthOrderConfig.grid.gridStretchAutomatic && ...
    isequal(sixthOrderConfig.grid.gridStretch,[0,0]), ...
    'ipm:SixthOrderGroupedConfig', ...
    'The explicit sixth-order feature tuple did not resolve atomically.');
assert_error(@()resolve_values(struct('transportScheme','weno5_fd')), ...
    'ipm:WenoFdRequiresHighOrder');
assert_error(@()resolve_values(struct('remeshTransferScheme','high_order')), ...
    'ipm:HighOrderRemeshRequiresHighOrder');
assert_error(@()resolve_values(struct('transportScheme','weno7_fd')), ...
    'ipm:Weno7RequiresSixthOrder');
assert_error(@()resolve_values(struct('timeIntegrator','rk6')), ...
    'ipm:Rk6RequiresSixthOrder');
assert_error(@()resolve_values(struct( ...
    'remeshTransferScheme','sixth_order')), ...
    'ipm:SixthOrderRemeshRequiresSixthOrder');
assert_error(@()resolve_values(struct( ...
    'spatialDiscretization','sixth_order')), ...
    'ipm:SixthOrderTransport');
assert_error(@()resolve_values(struct( ...
    'spatialDiscretization','sixth_order', ...
    'transportScheme','weno7_fd')), ...
    'ipm:SixthOrderTimeIntegrator');
assert_error(@()resolve_values(struct( ...
    'spatialDiscretization','sixth_order', ...
    'transportScheme','weno7_fd','timeIntegrator','rk6')), ...
    'ipm:SixthOrderRemesh');
assert_error(@()resolve_values(struct( ...
    'spatialDiscretization','high_order','rescalingMode','dynamic', ...
    'dynamicScaleGeometry','anisotropic', ...
    'anisotropicPoissonSolver','pcg')), ...
    'ipm:HighOrderPoissonSolver');
unsupportedAutomaticMessage = assert_error(@()resolve_values(struct( ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic', ...
    'anisotropicGaugeMode','triangular')), ...
    'ipm:BadAnisotropicGaugeMode');
unsupportedFixedFrameMessage = assert_error(@()resolve_values(struct( ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic', ...
    'anisotropicGaugeMode','triangular_fixed_cr')), ...
    'ipm:BadAnisotropicGaugeMode');
assert(contains(unsupportedAutomaticMessage,'''fixed''') && ...
    contains(unsupportedAutomaticMessage,'''peak_translation''') && ...
    ~contains(lower(unsupportedAutomaticMessage),'triangular') && ...
    strcmp(unsupportedAutomaticMessage,unsupportedFixedFrameMessage), ...
    'ipm:ConfigAnisotropicGaugeErrorContract', ...
    'Unsupported anisotropic gauges do not report the two supported values.');

physicalStop = resolve_values(struct('physicalFinalTime',0.1));
dualStop = resolve_values(struct( ...
    'physicalFinalTime',0.1,'finalTime',2));
assert(isinf(physicalStop.finalTime) && dualStop.finalTime == 2, ...
    'ipm:ConfigFinalTimeExplicitness', ...
    'Physical/canonical final-time explicitness changed.');

implicitPaths = resolve_values(struct('rescalingMode','physical'));
explicitPaths = resolve_values(struct('rescalingMode','physical', ...
    'resultFile','explicit-result.mat','videoFile','explicit-video.mp4'));
assert(strcmp(implicitPaths.resultFile,fullfile('result','production', ...
    'ipm_double_odd_physical.mat')) && ...
    strcmp(implicitPaths.videoFile,fullfile('result','production', ...
    'ipm_double_odd_physical.mp4')) && ...
    strcmp(explicitPaths.resultFile,'explicit-result.mat') && ...
    strcmp(explicitPaths.videoFile,'explicit-video.mp4'), ...
    'ipm:ConfigOutputPathExplicitness', ...
    'Implicit derivation or explicit output-path preservation changed.');

automaticGridOverrides = struct('nx',65,'ny',33, ...
    'xlim',[-16,16],'ymax',16,'targetCenterSpacing',0.05);
automaticGrid = resolve_values(automaticGridOverrides);
resizedAutomaticGridOverrides = automaticGridOverrides;
resizedAutomaticGridOverrides.nx = 129;
resizedAutomaticGridOverrides.ny = 65;
resizedAutomaticGrid = resolve_values(resizedAutomaticGridOverrides);
explicitGrid = resolve_values(struct('nx',65,'ny',33, ...
    'xlim',[-16,16],'ymax',16,'gridStretch',[2,3]));
assert(automaticGrid.gridStretchAutomatic && ...
    resizedAutomaticGrid.gridStretchAutomatic && ...
    max(abs(resizedAutomaticGrid.gridStretch-automaticGrid.gridStretch)) > 0.1 && ...
    ~explicitGrid.gridStretchAutomatic && ...
    isequal(explicitGrid.gridStretch,[2,3]), ...
    'ipm:ConfigGridStretchExplicitness', ...
    'Automatic reuse or explicit grid-stretch resolution changed.');
sixthAutomaticOptions = ipm.config.sixthOrder(struct( ...
    'nx',65,'ny',33,'xlim',[-16,16],'ymax',16, ...
    'gridMode','stretched','gridStretchAutomatic',true, ...
    'targetCenterSpacing',1e-6));
sixthAutomaticGrid = resolve_values(sixthAutomaticOptions);
sixthPolicy = ipm.mesh.sixthOrderPolicy();
sixthStretchCap = [32,32]*log( ...
    sixthPolicy.maximumAdjacentCellRatio);
assert(max(abs(sixthAutomaticGrid.gridStretch-sixthStretchCap)) <= ...
    20*eps(max(sixthStretchCap)) && ...
    isequal(automaticGrid.gridStretch, ...
    resolve_values(automaticGridOverrides).gridStretch), ...
    'ipm:SixthOrderAutomaticStretchCap', ...
    ['Sixth-order automatic stretching was not capped by its private ' ...
    'quality policy, or the legacy automatic path changed.']);

unknownOptionMessage = assert_error(@()resolve_values(struct( ...
    'experimentSentinel',pi)),'ipm:UnknownOption');
assert(contains(unknownOptionMessage,'experimentSentinel'), ...
    'ipm:ConfigUnknownOptionMessage', ...
    'Unknown configuration fields are not rejected by name.');

operatorOverrides = struct('nx',33,'ny',17,'xlim',[-3,3], ...
    'ymax',3,'gridMode','stretched','gridStretch',[2,2], ...
    'transportScheme','weno5_nonuniform', ...
    'farBoundaryMode','dirichlet_zero','saveResults',false, ...
    'makePlots',false,'verbose',false);
operatorConfig = ipm.config.resolve(operatorOverrides);
resolvedOps = ipm.mesh.build(operatorConfig);
operatorFields = {'x','y','baseX','baseY','dx','dy','dxFaces','dyFaces', ...
    'X','Y','Dx','Dy','A','Tx','Ty','hx','hy','weights', ...
    'integrationWeights','poisson', ...
    'poissonWeights','poissonBoundary', ...
    'farBoundaryMode','transportBoundaryMode','transportScheme', ...
    'spatialDiscretization', ...
    'wallTransportMode','wenoEpsilon','wenoX','wenoY','symmetryMode', ...
    'greenSourceTolerance','greenMaxSources','nx','ny','remeshCount', ...
    'rescalingMode','dynamicScaleGeometry', ...
    'anisotropicPoisson','rescaling'};
assert(isequal(sort(fieldnames(resolvedOps)),sort(operatorFields(:))), ...
    'ipm:UnexpectedOperatorContract', ...
    'The numerical-operator contract contains an unexpected field.');
poissonRightHandSide = sin((1:numel(resolvedOps.poissonWeights))');
resolvedPoissonSolution = resolvedOps.poisson\poissonRightHandSide;
weightedOperator = spdiags(resolvedOps.poissonWeights,0, ...
    numel(resolvedOps.poissonWeights),numel(resolvedOps.poissonWeights)) * ...
    resolvedOps.A;
weightedOperator = (weightedOperator+weightedOperator')/2;
oraclePoissonSolution = weightedOperator\poissonRightHandSide;
poissonDifference = norm( ...
    resolvedPoissonSolution-oraclePoissonSolution,inf);
poissonTolerance = 10*eps(max(1,norm(oraclePoissonSolution,inf)));
assert(poissonDifference <= poissonTolerance, ...
    'ipm:ResolvedPoissonOracle', ...
    'The cached pure-builder factorization differs from its matrix oracle.');

sourcePath = which('ipm.mesh.build');
pureBuilderSource = fileread(sourcePath);
assert(isempty(regexp(pureBuilderSource, ...
    'ipm\.config\.(schema|resolve)\s*\(','once')), ...
    'ipm:ResolvedBuilderPurity', ...
    'The pure operator builder performs option resolution.');
remeshSource = fileread(which('ipm.remesh.adapt'));
remeshProposalSource = fileread(which('ipm.remesh.propose'));
remeshTransferSource = fileread(which('ipm.remesh.transfer'));
assert(~isempty(regexp(remeshSource, ...
    'ipm\.remesh\.propose\s*\(','once')) && ...
    ~isempty(regexp(remeshSource,'ipm\.remesh\.transfer\s*\(','once')) && ...
    ~isempty(regexp(remeshSource,'ipm\.remesh\.validate\s*\(','once')) && ...
    ~isempty(regexp(remeshSource,'for\s+retry\s*=\s*0:8','once')) && ...
    ~isempty(regexp(remeshProposalSource,'0\.8\^retry','once')) && ...
    ~isempty(regexp(remeshTransferSource, ...
    'ipm\.mesh\.build\s*\(','once')) && ...
    numel(regexp(remeshSource,'\n','match')) < 150, ...
    'ipm:RemeshResolvedBuilderBoundary', ...
    'Adaptive remeshing lost its compact propose-transfer-validate path.');

initializationOverrides = struct('nx',65,'ny',33,'xlim',[-4,4], ...
    'ymax',4,'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'rescalingMode','dynamic','lengthGauge','transport_anchor', ...
    'transportAnchorX',1,'lengthScaleGain',1, ...
    'cOmegaGauge','wall_omega_peak','peakTrackingWidthFactor',2.75, ...
    'farBoundaryMode','dirichlet_zero','saveResults',false, ...
    'makePlots',false,'verbose',false);
initializationConfig = ipm.config.resolve(initializationOverrides);
initializationOps = ipm.mesh.build(initializationConfig);
initializationOps.rescaling.configurationSentinel = sqrt(2);
initializationRho = ipm.field.initialDensity( ...
    initializationOps,initializationConfig.physics);
initializedOnce = ipm.evolve.initializeScaling(initializationRho,initializationOps);
initializedTwice = ipm.evolve.initializeScaling(initializationRho,initializedOnce);
assert(initializedOnce.rescaling.peakTrackingWidthFactor == 2.75 && ...
    initializedOnce.rescaling.configurationSentinel == sqrt(2), ...
    'ipm:RescalingConfigurationPreservation', ...
    'Rescaling initialization discarded frozen configuration fields.');
assert_struct_equal(initializedOnce.rescaling,initializedTwice.rescaling, ...
    'ipm:RepeatedRescalingInitialization', ...
    'Repeated initialization with the same field changed rescaling state.');
anchorInitializationOverrides = initializationOverrides;
anchorInitializationOverrides.cOmegaGauge = 'anchor_wall_slope';
anchorInitializationConfig = ipm.config.resolve(anchorInitializationOverrides);
anchorInitializationOps = ipm.mesh.build(anchorInitializationConfig);
anchorInitializationRho = ipm.field.initialDensity( ...
    anchorInitializationOps,anchorInitializationConfig.physics);
anchorInitializedOnce = ipm.evolve.initializeScaling( ...
    anchorInitializationRho,anchorInitializationOps);
anchorInitializedTwice = ipm.evolve.initializeScaling( ...
    anchorInitializationRho,anchorInitializedOnce);
assert(isfinite(anchorInitializedOnce.rescaling.referenceAnchorWallSlope) && ...
    anchorInitializedOnce.rescaling.referenceAnchorWallSlope ~= 0 && ...
    isequal(anchorInitializedOnce.rescaling.referenceAnchorWallSlope, ...
    anchorInitializedTwice.rescaling.referenceAnchorWallSlope), ...
    'ipm:AnchorWallReferenceInitialization', ...
    'The frozen reference anchor-wall slope was not initialized repeatably.');
windowInitializationOverrides = initializationOverrides;
windowInitializationOverrides.cOmegaGauge = 'anchor_wall_window_l2';
windowInitializationConfig = ipm.config.resolve(windowInitializationOverrides);
windowInitializationOps = ipm.mesh.build(windowInitializationConfig);
windowInitializationRho = ipm.field.initialDensity( ...
    windowInitializationOps,windowInitializationConfig.physics);
windowInitializedOnce = ipm.evolve.initializeScaling( ...
    windowInitializationRho,windowInitializationOps);
windowInitializedTwice = ipm.evolve.initializeScaling( ...
    windowInitializationRho,windowInitializedOnce);
assert(isfinite( ...
    windowInitializedOnce.rescaling.referenceAnchorWallWindowValue) && ...
    windowInitializedOnce.rescaling.referenceAnchorWallWindowValue > 0 && ...
    isequal(windowInitializedOnce.rescaling.referenceAnchorWallWindowValue, ...
    windowInitializedTwice.rescaling.referenceAnchorWallWindowValue), ...
    'ipm:AnchorWallWindowReferenceInitialization', ...
    ['The frozen reference anchor-wall window L2 value was not ' ...
    'initialized repeatably.']);

report = struct('defaultFieldCount',numel(fieldnames(defaultResolved)), ...
    'activeInitialCondition',activeResolved.initialCondition, ...
    'pureBuilderFieldCount',numel(operatorFields), ...
    'poissonDifference',poissonDifference, ...
    'repeatedInitializationFieldCount', ...
        numel(fieldnames(initializedOnce.rescaling)));
report.autonomousMesh = ipmtests.baseline.autonomousMeshConfig();
if nargout == 0
    fprintf(['IPM configuration verification passed: %d defaults, ' ...
        '%d operator fields, repeated init %d fields.\n'], ...
        report.defaultFieldCount,report.pureBuilderFieldCount, ...
        report.repeatedInitializationFieldCount);
end
end

function values = resolve_values(overrides)
schema = ipm.config.schema();
values = flatten_config(ipm.config.resolve(overrides),schema);
end

function values = flatten_config(config,schema)
values = struct();
for domainIndex = 1:numel(schema.domainNames)
    domain = config.(schema.domainNames{domainIndex});
    names = fieldnames(domain);
    for nameIndex = 1:numel(names)
        values.(names{nameIndex}) = domain.(names{nameIndex});
    end
end
end

function assert_struct_equal(actual,expected,identifier,message)
assert(isequaln(orderfields(actual),orderfields(expected)),identifier,message);
end

function message = assert_error(action,expectedIdentifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,expectedIdentifier), ...
        'ipm:UnexpectedConfigError', ...
        'Expected "%s" but received "%s".', ...
        expectedIdentifier,exception.identifier);
    message = exception.message;
    return;
end
error('ipm:MissingConfigError', ...
    'Expected configuration error "%s" was not raised.',expectedIdentifier);
end

function assert_any_error(action,optionName)
try
    action();
catch
    return;
end
error('ipm:MissingOptionValidation', ...
    'Invalid value for option "%s" was accepted.',optionName);
end
