function report = grid()
%IPMTESTS.BASELINE.GRID Verify grid reuse and exact initial-data contracts.

fprintf('Running IPM grid verification...\n');
automaticGridOverrides = struct('nx',65,'ny',33, ...
    'xlim',[-16,16],'ymax',16,'targetCenterSpacing',0.05);
automaticGridConfig = ipm.config.resolve(automaticGridOverrides);
regriddedOverrides = automaticGridOverrides;
regriddedOverrides.nx = 129;
regriddedOverrides.ny = 65;
regriddedConfig = ipm.config.resolve(regriddedOverrides);
explicitGridConfig = ipm.config.resolve(struct('nx',65,'ny',33, ...
    'xlim',[-16,16],'ymax',16,'gridStretch',[2,3]));
physicalStopConfig = ipm.config.resolve(struct('physicalFinalTime',0.1));
activeCaseConfig = ipm.config.resolve(ipm.config.activeCase());

degenerateConfig = ipm.config.resolve(struct('nx',17,'ny',9, ...
    'xlim',[-2,2],'ymax',2,'initialCondition','degenerate', ...
    'degeneratePower',4));
degenerateOps = ipm.mesh.build(degenerateConfig);
degenerateRho = ipm.field.initialDensity( ...
    degenerateOps,degenerateConfig.physics);
degenerateAbsoluteX = abs(degenerateOps.X);
degenerateExact = degenerateAbsoluteX.^4 ./ ...
    (1+degenerateAbsoluteX.^4+degenerateOps.Y.^4);
degenerateError = max(abs(degenerateRho-degenerateExact),[],'all');
degenerateWallAbsoluteX = abs(degenerateOps.x);
degenerateWallExact = degenerateWallAbsoluteX.^4 ./ ...
    (1+degenerateWallAbsoluteX.^4);
degenerateWallError = max(abs( ...
    degenerateRho(1,:)-degenerateWallExact),[],'all');
degenerateDenominator = 1+degenerateAbsoluteX.^4+degenerateOps.Y.^4;
omegaExact = 4*sign(degenerateOps.X).*degenerateAbsoluteX.^3 .* ...
    (1+degenerateOps.Y.^4)./degenerateDenominator.^2;
degenerateOmegaError = weighted_l2( ...
    degenerateRho*degenerateOps.Dx'-omegaExact,degenerateOps);

k8Config = ipm.config.resolve(struct('nx',33,'ny',17,'xlim',[-3,3], ...
    'ymax',3,'initialCondition','degenerate','degeneratePower',8));
k8Ops = ipm.mesh.build(k8Config);
k8Rho = ipm.field.initialDensity(k8Ops,k8Config.physics);
k8AbsoluteX = abs(k8Ops.X);
k8Denominator = 1+k8AbsoluteX.^8+k8Ops.Y.^8;
k8Exact = k8AbsoluteX.^8./k8Denominator;
k8ExactError = max(abs(k8Rho-k8Exact),[],'all');
k8OmegaExact = 8*sign(k8Ops.X).*k8AbsoluteX.^7 .* ...
    (1+k8Ops.Y.^8)./k8Denominator.^2;
k8PositiveMask = k8Ops.X > 0;
k8PositiveMinimum = min(k8OmegaExact(k8PositiveMask));
k8WallPeakXExact = (7/9)^(1/8);
k8WallPeakExact = (81/32)*(7/9)^(7/8);

k8PrimitiveConfig = ipm.config.resolve(struct('nx',33,'ny',17, ...
    'xlim',[-3,3],'ymax',3,'initialCondition','degenerate_primitive', ...
    'degeneratePower',8));
k8PrimitiveOps = ipm.mesh.build(k8PrimitiveConfig);
k8PrimitiveRho = ipm.field.initialDensity( ...
    k8PrimitiveOps,k8PrimitiveConfig.physics);
k8PrimitiveAbsoluteX = abs(k8PrimitiveOps.X);
k8PrimitiveDenominator = ...
    1+k8PrimitiveAbsoluteX.^8+k8PrimitiveOps.Y.^8;
k8PrimitiveExact = log1p(k8PrimitiveAbsoluteX.^8./ ...
    (1+k8PrimitiveOps.Y.^8))/8;
k8PrimitiveExactError = max(abs(k8PrimitiveRho-k8PrimitiveExact),[],'all');
k8PrimitiveOmegaExact = sign(k8PrimitiveOps.X).* ...
    k8PrimitiveAbsoluteX.^7./k8PrimitiveDenominator;
k8PrimitivePositiveMask = k8PrimitiveOps.X > 0;
k8PrimitivePositiveMinimum = min( ...
    k8PrimitiveOmegaExact(k8PrimitivePositiveMask));
k8PrimitiveWallPeakXExact = 7^(1/8);
k8PrimitiveWallPeakExact = 7^(7/8)/8;

report.automaticRegridStretch = regriddedConfig.grid.gridStretch;
report.activeInitialCondition = activeCaseConfig.physics.initialCondition;
report.activeDegeneratePower = activeCaseConfig.physics.degeneratePower;
report.activeCOmegaGauge = activeCaseConfig.scaling.cOmegaGauge;
report.activeRescalingMode = activeCaseConfig.scaling.rescalingMode;
report.activeTransportScheme = activeCaseConfig.transport.transportScheme;
report.degenerateInitialDataError = degenerateError;
report.degenerateWallTraceError = degenerateWallError;
report.degenerateOmegaL2Error = degenerateOmegaError;
report.k8InitialDataError = k8ExactError;
report.k8PositiveOmegaMinimum = k8PositiveMinimum;
report.k8WallPeakXExact = k8WallPeakXExact;
report.k8WallPeakExact = k8WallPeakExact;
report.k8PrimitiveInitialDataError = k8PrimitiveExactError;
report.k8PrimitivePositiveOmegaMinimum = k8PrimitivePositiveMinimum;
report.k8PrimitiveWallPeakXExact = k8PrimitiveWallPeakXExact;
report.k8PrimitiveWallPeakExact = k8PrimitiveWallPeakExact;

assert(automaticGridConfig.grid.gridStretchAutomatic && ...
    regriddedConfig.grid.gridStretchAutomatic && ...
    max(abs(regriddedConfig.grid.gridStretch- ...
        automaticGridConfig.grid.gridStretch)) > 0.1 && ...
    ~explicitGridConfig.grid.gridStretchAutomatic && ...
    max(abs(explicitGridConfig.grid.gridStretch-[2,3])) < 1e-14 && ...
    isinf(physicalStopConfig.time.finalTime), ...
    'ipm:AutomaticGridReuse', ...
    'Automatic grid stretching or physical-time option reuse is inconsistent.');
assert(strcmp(activeCaseConfig.physics.initialCondition, ...
        'degenerate_primitive') && ...
    activeCaseConfig.physics.degeneratePower == 8 && ...
    strcmp(activeCaseConfig.scaling.rescalingMode,'dynamic') && ...
    strcmp(activeCaseConfig.scaling.lengthGauge,'transport_anchor') && ...
    activeCaseConfig.scaling.transportAnchorX == 1 && ...
    strcmp(activeCaseConfig.scaling.cOmegaGauge,'wall_omega_peak') && ...
    strcmp(activeCaseConfig.transport.transportScheme,'weno5_nonuniform') && ...
    activeCaseConfig.grid.nx == 513 && activeCaseConfig.grid.ny == 257 && ...
    isequal(activeCaseConfig.grid.xlim,[-1e5,1e5]) && ...
    activeCaseConfig.grid.ymax == 1e5 && ...
    activeCaseConfig.scaling.targetPeakPoints == 64 && ...
    isequal(activeCaseConfig.scaling.targetLevelPoints,[96,64,48]) && ...
    activeCaseConfig.time.maxDt == 1e-2 && ...
    activeCaseConfig.time.physicalFinalTime == 2 && ...
    activeCaseConfig.scaling.lengthScaleGain == 1 && ...
    strcmp(activeCaseConfig.scaling.scalingContract, ...
    'exact_gauge_no_feedback_v1') && ...
    activeCaseConfig.scaling.widthGaugeGain == 0 && ...
    activeCaseConfig.scaling.omegaGaugeGain == 0 && ...
    activeCaseConfig.scaling.travelingWaveGain == 0 && ...
    ~isfield(activeCaseConfig.scaling,'maxDynamicRate') && ...
    ~isfield(activeCaseConfig.scaling,'adaptiveLengthScaling') && ...
    ~isfield(activeCaseConfig.scaling,'maxWidthRateCorrection') && ...
    activeCaseConfig.remesh.remeshMaximumCellRatio == 1.5, ...
    'ipm:ActiveCase', ...
    'The no-argument ipm.solve case drifted from the maintained configuration.');
assert(degenerateError == 0,'ipm:DegenerateInitialData', ...
    'Degenerate initial data does not match its defining formula.');
assert(degenerateWallError == 0 && any(degenerateRho(1,:) ~= 0), ...
    'ipm:DegenerateWallTrace', ...
    'Rational density must not be forced to zero on x_2=0 for x_1>0.');
assert(k8ExactError == 0 && k8PositiveMinimum > 0 && ...
    abs(k8WallPeakXExact-0.969073999111395) < 1e-14 && ...
    abs(k8WallPeakExact-2.031578601639576) < 1e-13, ...
    'ipm:K8StrongTailInitialData', ...
    'The comparison k=8 rational datum lost its exact formula, sign, or wall peak.');
assert(k8PrimitiveExactError == 0 && k8PrimitivePositiveMinimum > 0 && ...
    abs(k8PrimitiveWallPeakXExact-1.275373106858454) < 1e-14 && ...
    abs(k8PrimitiveWallPeakExact-0.686073742103071) < 1e-14, ...
    'ipm:K8InverseTailInitialData', ...
    'The active k=8 inverse-tail datum lost its exact formula, sign, or wall peak.');
assert(max(abs(degenerateRho-fliplr(degenerateRho)),[],'all') < 1e-14, ...
    'ipm:DegenerateSymmetry', ...
    'Double-odd omega mode requires an x_1-even upper density trace.');

fprintf('  automatic regrid stretch: %.6g %.6g\n', ...
    regriddedConfig.grid.gridStretch);
fprintf('  degenerate initial-data error: %.3e\n',degenerateError);
fprintf('  degenerate wall-trace error: %.3e\n',degenerateWallError);
fprintf('  degenerate omega L2 error: %.3e\n',degenerateOmegaError);
fprintf(['  k=8 exact error/min positive omega/peak: ' ...
    '%.3e, %.3e, (%.9f, %.9f)\n'],k8ExactError,k8PositiveMinimum, ...
    k8WallPeakXExact,k8WallPeakExact);
fprintf(['  k=8 inverse-tail error/min positive omega/peak: ' ...
    '%.3e, %.3e, (%.9f, %.9f)\n'], ...
    k8PrimitiveExactError,k8PrimitivePositiveMinimum, ...
    k8PrimitiveWallPeakXExact,k8PrimitiveWallPeakExact);
fprintf('IPM grid verification passed.\n');
end

function value = weighted_l2(field,ops)
value = sqrt(sum(field.^2.*ops.weights,'all'));
end
