function report = integration()
%IPMTESTS.BASELINE.INTEGRATION Verify short end-to-end and result-schema contracts.

fprintf('Running IPM integration verification...\n');
physicalConfig = ipm.config.resolve(struct( ...
    'nx',65,'ny',33,'xlim',[-4,4],'ymax',4, ...
    'rescalingMode','physical','saveResults',false, ...
    'makePlots',false,'verbose',false,'transportBoundaryMode','closed'));
physicalOps = ipm.mesh.build(physicalConfig);
physicalRho = exp(-(physicalOps.X.^2+(physicalOps.Y-1.2).^2));
[~,physicalFlow] = ipm.evolve.rhs(physicalRho,physicalOps);

initialRemeshOpts = struct('nx',513,'ny',257, ...
    'xlim',[-64,64],'ymax',32, ...
    'targetCenterSpacing',[0.01,0.01], ...
    'initialCondition','ccf_heavy_tail','ccfTailRegularization',0.08, ...
    'initialAnalyticRemesh',true,'remeshSafetyTrigger',0.65, ...
    'remeshTargetSafety',0.35,'physicalFinalTime',1e-4, ...
    'maxDt',1e-4,'outputEvery',5e-5,'storeSnapshots',true, ...
    'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
initialRemeshResult = ipm.solve(initialRemeshOpts);
assert(initialRemeshResult.schemaVersion == 2 && ...
    all(isfield(initialRemeshResult.history, ...
        {'common','gauge','mesh','anisotropic'})), ...
    'ipm:IntegrationResultSchema', ...
    'The integration run did not return the grouped version-2 schema.');

fitTimes = linspace(0,0.9,91)';
powerFit = ipm.diagnostics.blowupFit(fitTimes,(1-fitTimes).^(-2));
exponentialFit = ipm.diagnostics.blowupFit(fitTimes,exp(3*fitTimes));
growthCoordinate = linspace(0,1,401)';
uniformGrowthTime = 2*growthCoordinate;
denseLateGrowthTime = 2*(1-(1-growthCoordinate).^3);
uniformGrowthFits = synthetic_growth_fits(uniformGrowthTime);
denseLateGrowthFits = synthetic_growth_fits(denseLateGrowthTime);
invalidGrowthTime = uniformGrowthTime;
invalidGrowthTime(200) = NaN;
invalidGrowthRejected = false;
try
    ipm.diagnostics.maximumGrowthRateFit( ...
        invalidGrowthTime,exp(1.7*uniformGrowthTime));
catch exception
    invalidGrowthRejected = strcmp( ...
        exception.identifier,'ipm:MaximumGrowthRateValues');
end
canonicalCoordinate = linspace(0,1,401)';
canonicalTau = 4*(1-(1-canonicalCoordinate).^3);
canonicalLinearFit = ipm.diagnostics.canonicalMaximumGrowthFit( ...
    canonicalTau,2*(1+canonicalTau));
canonicalExponentialFit = ipm.diagnostics.canonicalMaximumGrowthFit( ...
    canonicalTau,3*exp(0.8*canonicalTau));
canonicalCurvedFit = ipm.diagnostics.canonicalMaximumGrowthFit( ...
    canonicalTau,exp(0.5*canonicalTau+0.3*canonicalTau.^2));
invalidCanonicalTau = canonicalTau;
invalidCanonicalTau(200) = invalidCanonicalTau(199);
invalidCanonicalTauRejected = false;
try
    ipm.diagnostics.canonicalMaximumGrowthFit( ...
        invalidCanonicalTau,exp(canonicalTau));
catch exception
    invalidCanonicalTauRejected = strcmp( ...
        exception.identifier,'ipm:CanonicalMaximumGrowthTau');
end
invalidCanonicalMaximum = exp(canonicalTau);
invalidCanonicalMaximum(200) = 0;
invalidCanonicalMaximumRejected = false;
try
    ipm.diagnostics.canonicalMaximumGrowthFit( ...
        canonicalTau,invalidCanonicalMaximum);
catch exception
    invalidCanonicalMaximumRejected = strcmp( ...
        exception.identifier,'ipm:CanonicalMaximumGrowthValues');
end
comparisonX = linspace(-2,2,17);
comparisonY = linspace(0,2,9)';
[comparisonGridX,comparisonGridY] = meshgrid(comparisonX,comparisonY);
comparisonField = exp(-(comparisonGridX.^2+comparisonGridY.^2));
comparisonHistory = struct('physicalTrackedWallOmegaPeak',1, ...
    'physicalTrackedWallPeakWidth',0.5);
comparisonReference = struct('comovingPhysicalX',comparisonX, ...
    'physicalY',comparisonY,'physicalRho',comparisonField, ...
    'physicalOmega',comparisonField,'physicalTrackedPeakX',0, ...
    'history',comparisonHistory);
comparisonCandidate = comparisonReference;
comparisonCandidate.physicalTrackedPeakX = 0.75;
alignedComparison = ipm.output.compare(comparisonReference, ...
    comparisonCandidate,[-1,1,1]);

report.physicalRates = [physicalFlow.c_l,physicalFlow.c_omega,physicalFlow.c_r];
report.syntheticPowerFit = powerFit;
report.syntheticExponentialFit = exponentialFit;
report.uniformGrowthFits = uniformGrowthFits;
report.denseLateGrowthFits = denseLateGrowthFits;
report.invalidGrowthRejected = invalidGrowthRejected;
report.canonicalLinearFit = canonicalLinearFit;
report.canonicalExponentialFit = canonicalExponentialFit;
report.canonicalCurvedFit = canonicalCurvedFit;
report.invalidCanonicalTauRejected = invalidCanonicalTauRejected;
report.invalidCanonicalMaximumRejected = invalidCanonicalMaximumRejected;
report.syntheticAlignedComparison = alignedComparison;
report.initialAnalyticRemeshCount = initialRemeshResult.grid.remeshCount;
report.initialAnalyticRemeshSymmetry = max(abs( ...
    initialRemeshResult.state.rho- ...
    fliplr(initialRemeshResult.state.rho)),[],'all');
report.finalHistoryTimeError = abs( ...
    initialRemeshResult.state.physicalTime - ...
    initialRemeshResult.history.common.physicalTime(end));
report.snapshotGridCount = numel(initialRemeshResult.snapshots.x);
report.snapshotFieldCount = numel(initialRemeshResult.snapshots.rho);
report.snapshotGridShapeValid = all(cellfun( ...
    @(field,x,y) isequal(size(field),[numel(y),numel(x)]), ...
    initialRemeshResult.snapshots.rho,initialRemeshResult.snapshots.x, ...
    initialRemeshResult.snapshots.y));
report.snapshotFinalGridError = max([max(abs( ...
    initialRemeshResult.snapshots.x{end}- ...
    initialRemeshResult.grid.x),[],'all'), ...
    max(abs(initialRemeshResult.snapshots.y{end}- ...
    initialRemeshResult.grid.y),[],'all')]);

assert(physicalFlow.c_l == 0 && physicalFlow.c_omega == 0 && ...
    physicalFlow.c_r == 0, ...
    'ipm:PhysicalScaling', ...
    'Physical mode must not contain a c_l, c_omega, or c_r term.');
assert(initialRemeshResult.grid.remeshCount >= 1 && ...
    report.initialAnalyticRemeshSymmetry < 1e-12, ...
    'ipm:InitialAnalyticRemesh', ...
    'Analytic initial remeshing did not execute or preserve paired symmetry.');
assert(report.finalHistoryTimeError < 1e-13, ...
    'ipm:FinalHistoryState', ...
    'The saved history omitted the actual terminal physical state.');
assert(report.snapshotGridCount == report.snapshotFieldCount && ...
    report.snapshotGridCount == ...
        numel(initialRemeshResult.snapshots.physicalTime) && ...
    report.snapshotGridShapeValid && report.snapshotFinalGridError < 1e-14, ...
    'ipm:SnapshotGridMetadata', ...
    'Stored fields no longer carry a matching per-snapshot adaptive grid.');
assert(powerFit.candidate && abs(powerFit.T-1) < 0.02 && ...
    abs(powerFit.p-2) < 0.05 && ~powerFit.powerProfileBoundaryHit && ...
    ~exponentialFit.candidate && ...
    exponentialFit.powerProfileBoundaryHit, ...
    'ipm:BlowupFit', ...
    'The diagnostic did not distinguish synthetic power-law and exponential growth.');
assert(strcmp(uniformGrowthFits.exponential.consensusModel,'exponential') && ...
    strcmp(denseLateGrowthFits.exponential.consensusModel,'exponential') && ...
    max(abs(uniformGrowthFits.exponential.finalRate-1.7)) < 1e-8 && ...
    max(abs(denseLateGrowthFits.exponential.finalRate-1.7)) < 1e-8, ...
    'ipm:MaximumGrowthRateExponential', ...
    'The logarithmic-rate diagnostic did not recover exact exponential growth.');
assert(strcmp(uniformGrowthFits.power.consensusModel, ...
        'finite_time_power') && ...
    strcmp(denseLateGrowthFits.power.consensusModel, ...
        'finite_time_power') && ...
    growth_power_error(uniformGrowthFits.power,2.2,1.2) < 1e-4 && ...
    growth_power_error(denseLateGrowthFits.power,2.2,1.2) < 1e-4, ...
    'ipm:MaximumGrowthRatePower', ...
    'The logarithmic-rate diagnostic did not recover exact power-law growth.');
assert(strcmp(uniformGrowthFits.doubleExponential.consensusModel, ...
        'double_exponential') && ...
    strcmp(denseLateGrowthFits.doubleExponential.consensusModel, ...
        'double_exponential') && ...
    abs(uniformGrowthFits.doubleExponential.windows(end). ...
        doubleExponential.parameters.kappa-0.8) < 1e-4 && ...
    abs(denseLateGrowthFits.doubleExponential.windows(end). ...
        doubleExponential.parameters.kappa-0.8) < 1e-4 && ...
    invalidGrowthRejected, ...
    'ipm:MaximumGrowthRateDoubleExponential', ...
    ['The logarithmic-rate diagnostic did not recover double-exponential ' ...
    'growth or reject a discontinuous invalid history.']);
canonicalLinearWindow = canonicalLinearFit.windows(end);
canonicalExponentialWindow = canonicalExponentialFit.windows(end);
canonicalCurvedWindow = canonicalCurvedFit.windows(end);
expectedWindowLinearK = 1/(1+canonicalLinearWindow.startCanonicalTau);
assert(canonicalLinearFit.modelConsensus && ...
    strcmp(canonicalLinearFit.consensusModel,'linear_maximum') && ...
    all(strcmp({canonicalLinearFit.windows.modelDecision}, ...
        'linear_maximum')) && ...
    all([canonicalLinearFit.windows.inputSamplingStable]) && ...
    abs(canonicalLinearWindow.linearMaximum.parameters.k - ...
        expectedWindowLinearK) < 1e-4, ...
    'ipm:CanonicalMaximumGrowthLinear', ...
    ['The canonical-tau diagnostic did not recover exact linear maximum ' ...
    'growth under nonuniform input sampling.']);
assert(canonicalExponentialFit.modelConsensus && ...
    strcmp(canonicalExponentialFit.consensusModel, ...
        'exponential_maximum') && ...
    all(strcmp({canonicalExponentialFit.windows.modelDecision}, ...
        'exponential_maximum')) && ...
    all([canonicalExponentialFit.windows.inputSamplingStable]) && ...
    abs(canonicalExponentialWindow.exponentialMaximum.parameters.lambda - ...
        0.8) < 1e-10 && ...
    max(abs(canonicalExponentialFit.finalCanonicalRate-0.8)) < 1e-8, ...
    'ipm:CanonicalMaximumGrowthExponential', ...
    ['The canonical-tau diagnostic did not recover exact exponential ' ...
    'maximum growth or its logarithmic rate.']);
assert(canonicalCurvedFit.curvatureGuardTriggered && ...
    canonicalCurvedWindow.curvatureGuardTriggered && ...
    strcmp(canonicalCurvedWindow.modelDecision, ...
        'curved_nonasymptotic') && ...
    ~canonicalCurvedFit.modelConsensus && ...
    invalidCanonicalTauRejected && invalidCanonicalMaximumRejected, ...
    'ipm:CanonicalMaximumGrowthCurvatureGuard', ...
    ['The canonical-tau diagnostic forced a linear/exponential choice for ' ...
    'significantly curved growth or accepted invalid input.']);
assert(alignedComparison.rhoRelativeL2 < 1e-14 && ...
    alignedComparison.omegaRelativeL2 < 1e-14 && ...
    abs(alignedComparison.labPeakShift-0.75) < 1e-14, ...
    'ipm:AlignedComparison', ...
    'Peak-aligned comparison mixed laboratory translation into shape error.');

fprintf('  analytic initial remesh count: %d\n', ...
    initialRemeshResult.grid.remeshCount);
fprintf('  terminal history-time error: %.3e\n', ...
    report.finalHistoryTimeError);
fprintf('  stored snapshot/grid pairs: %d\n',report.snapshotGridCount);
fprintf('IPM integration verification passed.\n');
end

function fits = synthetic_growth_fits(t)
fits = struct();
fits.exponential = ipm.diagnostics.maximumGrowthRateFit( ...
    t,exp(1.7*t));
fits.power = ipm.diagnostics.maximumGrowthRateFit( ...
    t,(2.2-t).^(-1.2));
fits.doubleExponential = ipm.diagnostics.maximumGrowthRateFit( ...
    t,exp((0.4/0.8)*(exp(0.8*t)-1)));
end

function value = growth_power_error(fit,terminalTime,power)
model = fit.windows(end).powerLaw;
value = max(abs([model.parameters.T-terminalTime, ...
    model.parameters.p-power]));
end
