function report = numericCore()
%IPMTESTS.BASELINE.NUMERICCORE Focused isotropic/anisotropic core regressions.

[isotropicMagnitude,isotropicRates] = ...
    ipm.evolve.rateMagnitude([10,8,0],1);
assert(isequal(isotropicMagnitude,10) && ...
    isequal(isotropicRates,[10;8;0]), ...
    'ipm:NumericCoreIsotropicRateMagnitude', ...
    'The isotropic rate-vector diagnostic changed.');
[anisotropicMagnitude,anisotropicRates] = ...
    ipm.evolve.rateMagnitude([10,4,8,3],2);
assert(anisotropicMagnitude == 10 && ...
    isequal(anisotropicRates,[10;4;8;1.5]), ...
    'ipm:NumericCoreAnisotropicRateMagnitude', ...
    'The anisotropic translation normalization is incorrect.');
timestepProvenanceError = timestep_provenance_check();
assert(timestepProvenanceError == 0, ...
    'ipm:NumericCoreTimestepProvenance', ...
    'Timestep selection lost its limiter provenance or mapped CFL rate.');

baseOverrides = struct( ...
    'nx',17,'ny',13,'xlim',[-2,2],'ymax',2, ...
    'gridMode','uniform','gridStretch',0, ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportScheme','muscl_minmod','symmetryMode','half_plane', ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false);
baseConfig = ipm.config.resolve(baseOverrides);
ops = ipm.mesh.build(baseConfig);
rho = exp(-ops.X.^2-0.7*(ops.Y-0.8).^2);
legacyWeightFallback = isequaln(ops.integrationWeights,ops.weights);
assert(legacyWeightFallback, ...
    'ipm:NumericCoreIntegrationWeightFallback', ...
    'The maintained second-order integration weights no longer pass through exactly.');

[psiLegacy,legacyInterior] = legacy_poisson(rho*ops.Dx',ops);
[psiDefault,defaultInterior] = ipm.field.poisson(rho*ops.Dx',ops);
[psiCurrent,currentInterior,~,isotropicSolveInfo] = ...
    ipm.field.poisson(rho*ops.Dx',ops,1);
assert(isequaln(psiDefault,psiCurrent) && ...
    isequaln(defaultInterior,currentInterior) && ...
    isequaln(psiCurrent,psiLegacy) && isequaln(currentInterior,legacyInterior), ...
    'ipm:NumericCorePoissonZeroRegression', ...
    'kappa=1 no longer follows the maintained Poisson arithmetic.');
[u1Legacy,u2Legacy,sourceLegacy] = legacy_velocity(rho,ops);
[u1Current,u2Current,~,sourceCurrent,~,velocitySolveInfo] = ...
    ipm.field.velocity(rho,ops,1);
assert(isequaln(u1Current,u1Legacy) && isequaln(u2Current,u2Legacy) && ...
    isequaln(sourceCurrent,sourceLegacy), ...
    'ipm:NumericCoreVelocityZeroRegression', ...
    'kappa=1 no longer follows the maintained velocity arithmetic.');
assert(isotropicSolveInfo.kappa == 1 && velocitySolveInfo.kappa == 1, ...
    'ipm:NumericCoreIsotropicSolveInfo', ...
    'The common Poisson solve metadata lost the isotropic aspect.');
[physicalRhs,physicalFlow] = ipm.evolve.rhs(rho,ops);
[legacyPhysicalRhs,legacyTransportForm] = ipm.field.transport( ...
    rho,u1Legacy,u2Legacy,ops,ops.transportBoundaryMode);
assert(isequaln(physicalRhs,legacyPhysicalRhs) && ...
    legacyTransportForm.bulkConservative && ...
    ~legacyTransportForm.advectiveWall && ...
    isequaln(physicalFlow.u1,u1Legacy) && ...
    isequaln(physicalFlow.u2,u2Legacy), ...
    'ipm:NumericCoreRhsZeroRegression', ...
    'The physical isotropic RHS changed under common transport assembly.');

greenConfig = baseConfig;
greenConfig.elliptic.farBoundaryMode = 'green';
greenConfig.elliptic.greenSourceTolerance = 0.5;
greenConfig.elliptic.greenMaxSources = 10000;
greenOps = ipm.mesh.build(greenConfig);
source = zeros(greenOps.ny,greenOps.nx);
sourceRow = 5;
sourceColumn = 11;
source(sourceRow,sourceColumn) = ...
    1/greenOps.weights(sourceRow,sourceColumn);
isotropicBoundary = ipm.field.greenBoundary(source,greenOps);
explicitUnitBoundary = ipm.field.greenBoundary(source,greenOps,1);
legacyBoundary = single_source_green_boundary( ...
    source,greenOps,sourceRow,sourceColumn,1);
assert(isequaln(isotropicBoundary,explicitUnitBoundary) && ...
    boundary_error(isotropicBoundary,legacyBoundary) < 5e-15, ...
    'ipm:NumericCoreGreenZeroRegression', ...
    'kappa=1 Green data changed or disagree with the Euclidean oracle.');
kappa = 2.3;
metricBoundary = ipm.field.greenBoundary(source,greenOps,kappa);
metricOracle = single_source_green_boundary( ...
    source,greenOps,sourceRow,sourceColumn,kappa);
greenMetricError = boundary_error(metricBoundary,metricOracle);
assert(greenMetricError < 5e-15 && all(metricBoundary.bottom == 0), ...
    'ipm:NumericCoreGreenMetric', ...
    'The determinant-one anisotropic Green metric is inconsistent.');

[A,weightedA] = ipm.field.poissonOperator(ops,kappa);
nyi = ops.ny-2;
nxi = ops.nx-2;
operatorOracle = (1/kappa)*kron(ops.Tx,speye(nyi))+ ...
    kappa*kron(speye(nxi),ops.Ty);
operatorError = norm(A-operatorOracle,inf);
weightedSymmetryError = norm(weightedA-weightedA',inf) / ...
    max(norm(weightedA,inf),eps);
assert(operatorError == 0 && weightedSymmetryError < 5e-15, ...
    'ipm:NumericCoreAnisotropicOperator', ...
    'The anisotropic Kronecker operator or weighted symmetry is incorrect.');

psiExact = sin(pi*(ops.X-ops.x(1))/(ops.x(end)-ops.x(1))) .* ...
    sin(pi*ops.Y/ops.y(end));
psiExact([1,end],:) = 0;
psiExact(:,[1,end]) = 0;
manufacturedSource = zeros(ops.ny,ops.nx);
manufacturedSource(2:end-1,2:end-1) = reshape( ...
    A*reshape(psiExact(2:end-1,2:end-1),[],1),nyi,nxi);
directOps = ops;
directOps.anisotropicPoisson.solver = 'direct';
[psiDirect,~,~,directInfo] = ...
    ipm.field.poisson(manufacturedSource,directOps,kappa);
directError = max(abs(psiDirect-psiExact),[],'all');
pcgOps = ops;
pcgOps.anisotropicPoisson.solver = 'pcg';
pcgOps.anisotropicPoisson.tolerance = 1e-11;
pcgOps.anisotropicPoisson.maxIterations = 400;
[psiPcg,~,~,pcgInfo] = ipm.field.poisson(manufacturedSource,pcgOps,kappa);
pcgError = max(abs(psiPcg-psiExact),[],'all');
directPcgDifference = max(abs(psiDirect-psiPcg),[],'all');
assert(directError < 5e-12 && pcgError < 5e-10 && ...
    directPcgDifference < 5e-10 && directInfo.flag == 0 && ...
    pcgInfo.flag == 0, ...
    'ipm:NumericCoreAnisotropicPoisson', ...
    'The direct or PCG anisotropic Poisson solve is inaccurate.');

[assemblyRhs,assemblyBase,transportU1,transportU2,sourceCoefficient] = ...
    ipm.evolve.assembleRhs(rho,u1Current,u2Current, ...
    0.3,-0.2,0.07,0.04,ops);
expectedTransportU1 = u1Current+0.3*ops.X+0.04;
expectedTransportU2 = u2Current-0.2*ops.Y;
expectedSpatialSource = 0.3+(-0.2);
expectedBase = ipm.field.transport( ...
    rho,expectedTransportU1,expectedTransportU2,ops,'open') + ...
    expectedSpatialSource*rho;
expectedAssembly = expectedBase+0.07*rho;
assemblyError = max(abs(assemblyRhs-expectedAssembly),[],'all');
assert(assemblyError == 0 && isequaln(assemblyBase,expectedBase) && ...
    isequaln(transportU1,expectedTransportU1) && ...
    isequaln(transportU2,expectedTransportU2) && ...
    abs(sourceCoefficient-0.17) < 5e-16, ...
    'ipm:NumericCoreTransportAssembly', ...
    'The common rescaled transport/source assembly is inconsistent.');

isotropicRate = 0.3;
[isotropicAssembly,isotropicBase] = ipm.evolve.assembleRhs( ...
    rho,u1Current,u2Current,isotropicRate,isotropicRate,0.07,0.04,ops);
isotropicU1 = u1Current+isotropicRate*ops.X+0.04;
isotropicU2 = u2Current+isotropicRate*ops.Y;
legacyIsotropicBase = ipm.field.transport( ...
    rho,isotropicU1,isotropicU2,ops,'open')+2*isotropicRate*rho;
legacyIsotropicAssembly = legacyIsotropicBase+0.07*rho;
assert(isequaln(isotropicBase,legacyIsotropicBase) && ...
    isequaln(isotropicAssembly,legacyIsotropicAssembly), ...
    'ipm:NumericCoreIsotropicAssemblyGrouping', ...
    'The common assembler changed the maintained isotropic grouping.');

[wallTraceError,wallInteriorError,wallSourceError] = ...
    wall_transport_check(ops);
assert(wallTraceError < 5e-14 && wallInteriorError == 0 && ...
    wallSourceError < 5e-14, ...
    'ipm:NumericCoreWallTransport', ...
    'The advective wall trace or its rescaled source split is inconsistent.');

[aspectOneRhsError,aspectOneVelocityError,aspectOnePoissonError] = ...
    aspect_one_rhs_check(baseOverrides);
assert(aspectOneRhsError == 0 && aspectOneVelocityError == 0 && ...
    aspectOnePoissonError == 0, ...
    'ipm:NumericCoreAspectOneRhs', ...
    'Aspect-one anisotropic evolution differs from the isotropic RHS path.');

gaugeFormulaError = isotropic_gauge_formula_check();
assert(gaugeFormulaError == 0, ...
    'ipm:NumericCoreIsotropicGauge', ...
    'The tracking/gauge path changed the maintained isotropic formulas.');

[stageError,stageAspectError,stageSourceError] = fixed_rate_ssprk_check();
assert(stageError < 5e-13 && stageAspectError < 5e-15 && ...
    stageSourceError < 5e-15, ...
    'ipm:NumericCoreStageAspect', ...
    'Fixed-rate SSPRK3 lost its stage-local aspect or source contract.');

dispatcherError = default_dispatcher_check(baseOverrides);
assert(dispatcherError == 0, ...
    'ipm:NumericCoreDefaultTimeDispatcher', ...
    ['The default lifecycle dispatcher no longer reproduces a direct ' ...
    'SSPRK3 step exactly.']);

rhsCache = rhs_cache_check(rho,ops);
assert(all(rhsCache.exact) && all(rhsCache.firstStepEvaluations == ...
        rhsCache.stageCounts+1) && ...
    all(rhsCache.cachedSecondStepEvaluations == rhsCache.stageCounts) && ...
    all(rhsCache.uncachedSecondStepEvaluations == ...
        rhsCache.stageCounts+1) && ...
    all(rhsCache.cachedSecondStepEvaluations+1 == ...
        rhsCache.uncachedSecondStepEvaluations) && ...
    rhsCache.initialAcceptedStateHit && rhsCache.staleGridRejected && ...
    all(rhsCache.anisotropicExact), ...
    'ipm:NumericCoreRhsCache', ...
    ['Every explicit RK method must reuse exactly one accepted-state ' ...
    'first-stage RHS without changing its field, flow, or scale.']);
runtimeRemeshCache = runtime_remesh_cache_check();
assert(runtimeRemeshCache, ...
    'ipm:NumericCoreRemeshRhsCache', ...
    ['An accepted runtime remesh must rebuild the transient RHS cache ' ...
    'on the new grid.']);

report = struct('isotropicRateMagnitude',isotropicMagnitude, ...
    'anisotropicRateMagnitude',anisotropicMagnitude, ...
    'greenMetricError',greenMetricError,'operatorError',operatorError, ...
    'weightedSymmetryError',weightedSymmetryError, ...
    'directPoissonError',directError,'pcgPoissonError',pcgError, ...
    'directPcgDifference',directPcgDifference, ...
    'pcgIterations',pcgInfo.iterations,'assemblyError',assemblyError, ...
    'wallTraceError',wallTraceError,'wallInteriorError',wallInteriorError, ...
    'wallSourceError',wallSourceError,'aspectOneRhsError',aspectOneRhsError, ...
    'aspectOneVelocityError',aspectOneVelocityError, ...
    'aspectOnePoissonError',aspectOnePoissonError, ...
    'gaugeFormulaError',gaugeFormulaError, ...
    'stageError',stageError,'stageAspectError',stageAspectError, ...
    'stageSourceError',stageSourceError, ...
    'timestepProvenanceError',timestepProvenanceError, ...
    'legacyWeightFallback',legacyWeightFallback, ...
    'dispatcherError',dispatcherError,'rhsCache',rhsCache, ...
    'runtimeRemeshCache',runtimeRemeshCache);
fprintf(['Numeric-core verification: Green %.3e, operator %.3e, ' ...
    'direct/PCG %.3e/%.3e, SSPRK %.3e.\n'], ...
    greenMetricError,operatorError,directError,pcgError,stageError);
end

function passed = runtime_remesh_cache_check()
options = struct('nx',65,'ny',33,'xlim',[-4,4],'ymax',4, ...
    'initialCondition','degenerate','degeneratePower',4, ...
    'symmetryMode','half_plane','rescalingMode','dynamic', ...
    'adaptiveRemesh',true,'initialAnalyticRemesh',false, ...
    'remeshSafetyTrigger',0.05,'remeshTargetSafety',0.025, ...
    'remeshMaximumCellRatio',10,'maxRemeshes',2, ...
    'physicalFinalTime',1e-4,'maxDt',1e-4, ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false);
state = ipm.evolve.initialize(options);
oldRemeshCount = state.ops.remeshCount;
[state,stopReason] = ipm.evolve.advance(state);
[~,~,~,~,evaluationInfo] = ipm.evolve.stepSsprk3( ...
    state.rho,1e-5,state.ops,state.scale,state.rhsCache);
passed = isempty(stopReason) && state.ops.remeshCount > oldRemeshCount && ...
    isequal(state.rhsCache.x,state.ops.x) && ...
    isequal(state.rhsCache.y,state.ops.y) && ...
    state.rhsCache.remeshCount == state.ops.remeshCount && ...
    evaluationInfo.initialStageCacheHit;
end

function report = rhs_cache_check(rho,ops)
dt = 1e-4;
scale = ipm.evolve.initialScale(ops);
methods = {@ipm.evolve.stepSsprk3,@ipm.evolve.stepSsprk54, ...
    @ipm.evolve.stepRk6};
methodNames = {'ssprk3','ssprk54','rk6'};
count = numel(methods);
stageCounts = zeros(1,count);
firstStepEvaluations = zeros(1,count);
cachedSecondStepEvaluations = zeros(1,count);
uncachedSecondStepEvaluations = zeros(1,count);
exact = false(1,count);
for index = 1:count
    method = methods{index};
    [rhoOne,~,scaleOne,cacheOne,firstInfo] = ...
        method(rho,dt,ops,scale);
    [rhoCached,flowCached,scaleCached,cacheCached,cachedInfo] = ...
        method(rhoOne,dt,ops,scaleOne,cacheOne);
    [rhoUncached,flowUncached,scaleUncached,cacheUncached, ...
        uncachedInfo] = method(rhoOne,dt,ops,scaleOne);
    stageCounts(index) = firstInfo.stageCount;
    firstStepEvaluations(index) = firstInfo.rhsEvaluations;
    cachedSecondStepEvaluations(index) = cachedInfo.rhsEvaluations;
    uncachedSecondStepEvaluations(index) = uncachedInfo.rhsEvaluations;
    exact(index) = ~firstInfo.initialStageCacheHit && ...
        cachedInfo.initialStageCacheHit && ...
        ~uncachedInfo.initialStageCacheHit && ...
        isequaln(rhoCached,rhoUncached) && ...
        isequaln(flowCached,flowUncached) && ...
        isequaln(scaleCached,scaleUncached) && ...
        isequaln(cacheCached,cacheUncached);
end

[initialRhoRate,initialFlow] = ipm.evolve.flow(rho,ops,scale);
initialCache = ipm.evolve.makeRhsCache( ...
    rho,initialRhoRate,initialFlow,ops,scale);
[rhoInitialCached,flowInitialCached,scaleInitialCached,~,initialInfo] = ...
    ipm.evolve.stepSsprk3(rho,dt,ops,scale,initialCache);
[rhoInitialPlain,flowInitialPlain,scaleInitialPlain] = ...
    ipm.evolve.stepSsprk3(rho,dt,ops,scale);
initialAcceptedStateHit = initialInfo.initialStageCacheHit && ...
    isequaln(rhoInitialCached,rhoInitialPlain) && ...
    isequaln(flowInitialCached,flowInitialPlain) && ...
    isequaln(scaleInitialCached,scaleInitialPlain);

staleOps = ops;
staleOps.remeshCount = ops.remeshCount+1;
[rhoStale,flowStale,scaleStale,~,staleInfo] = ...
    ipm.evolve.stepSsprk3(rho,dt,staleOps,scale,initialCache);
[rhoStalePlain,flowStalePlain,scaleStalePlain] = ...
    ipm.evolve.stepSsprk3(rho,dt,staleOps,scale);
staleGridRejected = ~staleInfo.initialStageCacheHit && ...
    isequaln(rhoStale,rhoStalePlain) && ...
    isequaln(flowStale,flowStalePlain) && ...
    isequaln(scaleStale,scaleStalePlain);

anisotropicOptions = struct('nx',17,'ny',13,'xlim',[-2,2], ...
    'ymax',2,'gridMode','uniform','gridStretch',0, ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportScheme','muscl_minmod','symmetryMode','half_plane', ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic', ...
    'anisotropicGaugeMode','fixed','anisotropicFixedCX',0.35, ...
    'anisotropicFixedCY',-0.2,'anisotropicFixedCOmega',0.1, ...
    'anisotropicFixedCR',0.05,'initialCondition','degenerate', ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false);
anisotropicState = ipm.evolve.initialize(anisotropicOptions);
anisotropicExact = false(1,count);
for index = 1:count
    method = methods{index};
    [rhoCached,flowCached,scaleCached,~,cachedInfo] = method( ...
        anisotropicState.rho,dt,anisotropicState.ops, ...
        anisotropicState.scale,anisotropicState.rhsCache);
    [rhoUncached,flowUncached,scaleUncached] = method( ...
        anisotropicState.rho,dt,anisotropicState.ops, ...
        anisotropicState.scale);
    anisotropicExact(index) = cachedInfo.initialStageCacheHit && ...
        isequaln(rhoCached,rhoUncached) && ...
        isequaln(flowCached,flowUncached) && ...
        isequaln(scaleCached,scaleUncached);
end

report = struct('methods',{methodNames},'stageCounts',stageCounts, ...
    'firstStepEvaluations',firstStepEvaluations, ...
    'cachedSecondStepEvaluations',cachedSecondStepEvaluations, ...
    'uncachedSecondStepEvaluations',uncachedSecondStepEvaluations, ...
    'exact',exact,'initialAcceptedStateHit',initialAcceptedStateHit, ...
    'staleGridRejected',staleGridRejected, ...
    'anisotropicExact',anisotropicExact);
end

function errorValue = timestep_provenance_check()
flow = struct('transportU1',[4,1;2,0], ...
    'transportU2',[4,0;0,0]);
ops = struct('spatialDiscretization','high_order','hx',2,'hy',4);
scale = struct('logC_l',0,'logC_omega',0, ...
    'canonicalTime',0.25,'physicalTime',0.5);
time = struct('cfl',0.3,'maxDt',0.2,'minDt',1e-12, ...
    'finalTime',10,'physicalFinalTime',10);
[dt,stopReason,details] = ipm.evolve.selectTimestep(flow,scale,ops,time);
expectedNames = {'dt';'rate';'dtCfl';'maxDtLimit';'canonicalLimit'; ...
    'physicalLimit';'physicalClockSpeed';'realizedCfl';'activeLimiter'};
checks = [ ...
    isempty(stopReason), ...
    isequal(fieldnames(details),expectedNames), ...
    details.rate == 3, ...
    details.dtCfl == time.cfl/details.rate, ...
    dt == details.dt && details.dt == details.dtCfl, ...
    details.maxDtLimit == time.maxDt, ...
    details.canonicalLimit == time.finalTime-scale.canonicalTime, ...
    details.physicalLimit == ...
        (time.physicalFinalTime-scale.physicalTime), ...
    details.physicalClockSpeed == 1, ...
    details.realizedCfl == details.dt*details.rate, ...
    strcmp(details.activeLimiter,'cfl')];

slowFlow = flow;
slowFlow.transportU1 = 0.5*ones(size(flow.transportU1));
slowFlow.transportU2 = zeros(size(flow.transportU2));
[~,~,maxDtDetails] = ...
    ipm.evolve.selectTimestep(slowFlow,scale,ops,time);
checks(end+1) = strcmp(maxDtDetails.activeLimiter,'max_dt') && ...
    maxDtDetails.dt == time.maxDt;

canonicalTime = time;
canonicalTime.finalTime = scale.canonicalTime+0.05;
[~,~,canonicalDetails] = ...
    ipm.evolve.selectTimestep(slowFlow,scale,ops,canonicalTime);
checks(end+1) = strcmp( ...
    canonicalDetails.activeLimiter,'canonical_final_time') && ...
    canonicalDetails.dt == canonicalDetails.canonicalLimit;

physicalScale = scale;
physicalScale.logC_omega = log(2);
physicalTime = time;
physicalTime.physicalFinalTime = physicalScale.physicalTime+0.1;
[~,~,physicalDetails] = ...
    ipm.evolve.selectTimestep(slowFlow,physicalScale,ops,physicalTime);
checks(end+1) = strcmp( ...
    physicalDetails.activeLimiter,'physical_final_time') && ...
    physicalDetails.dt == physicalDetails.physicalLimit && ...
    physicalDetails.physicalClockSpeed == ...
        exp(physicalScale.logC_omega-physicalScale.logC_l);

zeroFlow = slowFlow;
zeroFlow.transportU1(:) = 0;
[~,~,zeroDetails] = ...
    ipm.evolve.selectTimestep(zeroFlow,scale,ops,time);
checks(end+1) = zeroDetails.rate == 0 && ...
    zeroDetails.dtCfl == time.maxDt && ...
    zeroDetails.realizedCfl == 0 && ...
    strcmp(zeroDetails.activeLimiter,'max_dt');

mappedOps = struct('spatialDiscretization','sixth_order', ...
    'transportSpacingX',1,'transportSpacingY',2, ...
    'hx',100,'hy',100);
mappedFlow = struct('transportU1',3,'transportU2',2);
[~,~,mappedDetails] = ...
    ipm.evolve.selectTimestep(mappedFlow,scale,mappedOps,time);
checks(end+1) = mappedDetails.rate == 4 && ...
    mappedDetails.dtCfl == time.cfl/4 && ...
    strcmp(mappedDetails.activeLimiter,'cfl');

placeholder = ipm.evolve.emptyTimestep(time,scale,'restored');
checks(end+1) = isequal(fieldnames(placeholder),expectedNames) && ...
    all(isnan([placeholder.dt,placeholder.rate,placeholder.dtCfl, ...
        placeholder.realizedCfl])) && ...
    placeholder.maxDtLimit == time.maxDt && ...
    strcmp(placeholder.activeLimiter,'restored');
errorValue = double(~all(checks));
end

function errorValue = default_dispatcher_check(baseOverrides)
options = baseOverrides;
options.adaptiveRemesh = false;
options.initialAnalyticRemesh = false;
options.maxDt = 1e-4;
options.minDt = 1e-12;
state = ipm.evolve.initialize(options);
[dt,stopReason,timeStep] = ipm.evolve.selectTimestep( ...
    state.flow,state.scale,state.ops,state.config.time);
assert(isempty(stopReason), ...
    'ipm:NumericCoreDefaultDispatcherStepSelection', ...
    'The default dispatcher fixture could not select a time step.');
[rhoDirect,flowDirect,scaleDirect] = ipm.evolve.stepSsprk3( ...
    state.rho,dt,state.ops,state.scale);
[advanced,advanceStopReason] = ipm.evolve.advance(state);
sameState = isequaln(advanced.rho,rhoDirect) && ...
    isequaln(advanced.flow,flowDirect) && ...
    isequaln(advanced.scale,scaleDirect) && ...
    isequaln(advanced.timeStep,timeStep) && ...
    strcmp(state.timeStep.activeLimiter,'initial') && ...
    all(isnan([state.timeStep.dt,state.timeStep.rate, ...
        state.timeStep.dtCfl,state.timeStep.realizedCfl])) && ...
    advanced.normalizedTime == dt && advanced.step == 1 && ...
    isempty(advanceStopReason);
errorValue = double(~sameState);
end

function [psi,interiorRhs] = legacy_poisson(source,ops)
boundary = ipm.field.greenBoundary(source,ops);
psi = zeros(ops.ny,ops.nx);
psi(:,1) = boundary.left;
psi(:,end) = boundary.right;
psi(1,:) = boundary.bottom;
psi(end,:) = boundary.top;
rhs = source(2:end-1,2:end-1);
rhs(:,1) = rhs(:,1)-ops.poissonBoundary.x(1)*boundary.left(2:end-1);
rhs(:,end) = rhs(:,end)- ...
    ops.poissonBoundary.x(2)*boundary.right(2:end-1);
rhs(1,:) = rhs(1,:)-ops.poissonBoundary.y(1)*boundary.bottom(2:end-1);
rhs(end,:) = rhs(end,:)-ops.poissonBoundary.y(2)*boundary.top(2:end-1);
weightedRhs = ops.poissonWeights.*rhs(:);
psi(2:end-1,2:end-1) = reshape( ...
    ops.poisson\weightedRhs,ops.ny-2,ops.nx-2);
interiorRhs = rhs;
end

function [u1,u2,source] = legacy_velocity(rho,ops)
source = rho*ops.Dx';
psi = legacy_poisson(source,ops);
u1 = -(ops.Dy*psi);
u2 = psi*ops.Dx';
u2(1,:) = 0;
end

function boundary = single_source_green_boundary( ...
        source,ops,sourceRow,sourceColumn,kappa)
sourceX = ops.x(sourceColumn);
sourceY = ops.y(sourceRow);
strength = source(sourceRow,sourceColumn)* ...
    ops.weights(sourceRow,sourceColumn);
boundary = struct( ...
    'left',metric_green(ops.x(1)*ones(ops.ny,1),ops.y, ...
        sourceX,sourceY,strength,kappa), ...
    'right',metric_green(ops.x(end)*ones(ops.ny,1),ops.y, ...
        sourceX,sourceY,strength,kappa), ...
    'bottom',zeros(1,ops.nx), ...
    'top',metric_green(ops.x',ops.y(end)*ones(ops.nx,1), ...
        sourceX,sourceY,strength,kappa)');
end

function value = metric_green(targetX,targetY,sourceX,sourceY,strength,kappa)
directSquared = kappa*(targetX-sourceX).^2+ ...
    (targetY-sourceY).^2/kappa;
imageSquared = kappa*(targetX-sourceX).^2+ ...
    (targetY+sourceY).^2/kappa;
value = log(imageSquared./directSquared)/(4*pi)*strength;
end

function value = boundary_error(first,second)
value = max([max(abs(first.left-second.left)), ...
    max(abs(first.right-second.right)), ...
    max(abs(first.bottom-second.bottom)), ...
    max(abs(first.top-second.top))]);
end

function [traceError,interiorError,sourceError] = wall_transport_check(ops)
wallOps = ops;
wallOps.wallTransportMode = 'advective_upwind';
rho = 1+0.1*ops.X;
u1 = 0.4*ones(size(rho));
u2 = zeros(size(rho));
traceRhs = ipm.field.transport(rho,u1,u2,wallOps,'open');
expectedTrace = -0.04*ones(1,ops.nx-4);
traceError = max(abs(traceRhs(1,3:end-2)-expectedTrace));

variableU1 = repmat(0.3+0.1*ops.x,ops.ny,1);
constantRho = ones(size(rho));
advectiveRhs = ipm.field.transport( ...
    constantRho,variableU1,u2,wallOps,'open');
conservativeRhs = ipm.field.transport( ...
    constantRho,variableU1,u2,ops,'open');
traceError = max([traceError,max(abs(advectiveRhs(1,:)))]);
interiorError = max(abs( ...
    advectiveRhs(2:end,:)-conservativeRhs(2:end,:)),[],'all');
assert(max(abs(conservativeRhs(1,3:end-2))) > 1e-3, ...
    'ipm:NumericCoreWallModeExercise', ...
    'The wall-mode test does not distinguish advective and conservative rows.');

[rescaledRhs,rescaledBase] = ipm.evolve.assembleRhs( ...
    constantRho,zeros(size(rho)),zeros(size(rho)), ...
    0.3,-0.2,0.07,0,wallOps,'open');
sourceError = max([max(abs(rescaledBase(1,:))), ...
    max(abs(rescaledRhs(1,:)-0.07))]);
end

function [rhsError,velocityError,poissonError] = ...
    aspect_one_rhs_check(baseOverrides)
anisotropicOverrides = baseOverrides;
anisotropicOverrides.rescalingMode = 'dynamic';
anisotropicOverrides.dynamicScaleGeometry = 'anisotropic';
anisotropicOverrides.anisotropicGaugeMode = 'fixed';
anisotropicOverrides.anisotropicFixedCX = 0;
anisotropicOverrides.anisotropicFixedCY = 0;
anisotropicOverrides.anisotropicFixedCOmega = 0;
anisotropicOverrides.anisotropicFixedCR = 0;
anisotropicOverrides.adaptiveRemesh = false;
anisotropicConfig = ipm.config.resolve(anisotropicOverrides);
anisotropicOps = ipm.mesh.build(anisotropicConfig);
rho = exp(-(anisotropicOps.X-0.8).^2- ...
    0.7*(anisotropicOps.Y-0.8).^2);
anisotropicOps = ipm.evolve.initializeScaling(rho,anisotropicOps);
isotropicOps = anisotropicOps;
isotropicOps.dynamicScaleGeometry = 'isotropic';
isotropicOps.rescaling.enabled = false;
scale = struct('logC_l',0,'logC_x',0,'logC_y',0, ...
    'logC_omega',0,'physicalTime',0,'X_shift',0,'canonicalTime',0);
[isotropicRhs,isotropicFlow] = ipm.evolve.rhs(rho,isotropicOps);
[anisotropicRhs,anisotropicFlow] = ipm.evolve.rhs(rho,anisotropicOps,scale);
rhsError = max(abs(isotropicRhs-anisotropicRhs),[],'all');
velocityError = max([max(abs( ...
    isotropicFlow.u1-anisotropicFlow.u1),[],'all'), ...
    max(abs(isotropicFlow.u2-anisotropicFlow.u2),[],'all')]);
poissonError = max(abs( ...
    isotropicFlow.psi-anisotropicFlow.psi),[],'all');
end

function formulaError = isotropic_gauge_formula_check()
userOpts = struct('nx',33,'ny',17,'xlim',[-4,4],'ymax',4, ...
    'gridMode','uniform','gridStretch',0, ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportScheme','muscl_minmod', ...
    'symmetryMode','double_odd_omega', ...
    'rescalingMode','dynamic','dynamicScaleGeometry','isotropic', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','none','adaptiveRemesh',false, ...
    'initialCondition','degenerate','saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false);
config = ipm.config.resolve(userOpts);
ops = ipm.mesh.build(config);
rho = ipm.field.initialDensity(ops,config.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
[u1,u2,psi,source,poissonResidual,poissonSolveInfo] = ...
    ipm.field.velocity(rho,ops);
flow = struct('u1',u1,'u2',u2,'psi',psi,'source',source, ...
    'poissonResidual',poissonResidual, ...
    'poissonSolveInfo',poissonSolveInfo);
physicalRhs = ipm.field.transport( ...
    rho,u1,u2,ops,ops.transportBoundaryMode);
tracking = ipm.diagnostics.trackFeatures(rho,physicalRhs,flow,ops);
[cL,cOmega,cR,baseRhs,details] = ...
    ipm.evolve.isotropicGauge(rho,physicalRhs,flow,ops,tracking);

r = ops.rescaling;
anchorU1 = interp1(ops.x,u1(1,:),r.transportAnchorX,'linear');
expectedNominal = -anchorU1/r.transportAnchorX;
expectedCL = expectedNominal;
expectedCR = 0;
expectedTransportU1 = u1+expectedCL*ops.X+expectedCR;
expectedTransportU2 = u2+expectedCL*ops.Y;
expectedBase = ipm.field.transport( ...
    rho,expectedTransportU1,expectedTransportU2,ops,'open') + ...
    2*expectedCL*rho;
expectedLengthResidual = ...
    anchorU1+expectedNominal*r.transportAnchorX;
formulaError = max([abs(cL-expectedCL),abs(cOmega),abs(cR-expectedCR), ...
    max(abs(baseRhs-expectedBase),[],'all'), ...
    abs(details.c_lNominal-expectedNominal), ...
    abs(details.lengthGaugeStrain-r.transportAnchorX), ...
    abs(details.lengthGaugeResidual-expectedLengthResidual), ...
    abs(details.widthCorrection),abs(details.omegaGaugeResidual)]);
end

function [stageError,aspectError,sourceError] = fixed_rate_ssprk_check()
userOpts = struct('nx',33,'ny',17,'xlim',[-4,4],'ymax',4, ...
    'gridMode','uniform','gridStretch',0, ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportScheme','muscl_minmod','symmetryMode','half_plane', ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic', ...
    'anisotropicGaugeMode','fixed','anisotropicFixedCX',0.35, ...
    'anisotropicFixedCY',-0.2,'anisotropicFixedCOmega',0.1, ...
    'anisotropicFixedCR',0.05, ...
    'initialCondition','degenerate','adaptiveRemesh',false, ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false);
config = ipm.config.resolve(userOpts);
ops = ipm.mesh.build(config);
rho = ipm.field.initialDensity(ops,config.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
scale = struct('logC_l',0,'logC_x',0,'logC_y',0, ...
    'logC_omega',0,'physicalTime',0,'X_shift',0,'canonicalTime',0);
dt = 0.02;
[rhoActual,flowActual,scaleActual] = ...
    ipm.evolve.stepSsprk3(rho,dt,ops,scale);
[rhoOracle,~,scaleOracle] = anisotropic_step_oracle(rho,dt,ops,scale);
stageError = max(abs(rhoActual-rhoOracle),[],'all');
stageError = max([stageError,abs(scaleActual.logC_l-scaleOracle.logC_l), ...
    abs(scaleActual.logC_y-scaleOracle.logC_y), ...
    abs(scaleActual.logC_omega-scaleOracle.logC_omega), ...
    abs(scaleActual.physicalTime-scaleOracle.physicalTime), ...
    abs(scaleActual.X_shift-scaleOracle.X_shift), ...
    abs(scaleActual.canonicalTime-scaleOracle.canonicalTime)]);
expectedAspect = exp(scaleActual.logC_y-scaleActual.logC_l);
aspectError = max([abs(flowActual.aspect-expectedAspect), ...
    abs(flowActual.poissonSolveInfo.kappa-expectedAspect)]);
sourceError = abs(flowActual.canonicalConservativeSource-( ...
    config.scaling.anisotropicFixedCX+ ...
    config.scaling.anisotropicFixedCY+ ...
    config.scaling.anisotropicFixedCOmega));
end

function [rhoNew,flow,scaleNew] = ...
    anisotropic_step_oracle(rho,dt,ops,scale)
z = pack_scale(scale);
[k1,flow1] = ipm.evolve.rhs(rho,ops,unpack_scale(z));
q1 = rho+dt*k1;
z1 = z+dt*scale_rate(z,flow1);
[k2,flow2] = ipm.evolve.rhs(q1,ops,unpack_scale(z1));
q2 = 0.75*rho+0.25*(q1+dt*k2);
z2 = 0.75*z+0.25*(z1+dt*scale_rate(z1,flow2));
[k3,flow3] = ipm.evolve.rhs(q2,ops,unpack_scale(z2));
rhoNew = (rho+2*(q2+dt*k3))/3;
zNew = (z+2*(z2+dt*scale_rate(z2,flow3)))/3;
scaleNew = unpack_scale(zNew);
[~,flow] = ipm.evolve.rhs(rhoNew,ops,scaleNew);
end

function z = pack_scale(scale)
z = [scale.logC_l;scale.logC_y;scale.logC_omega;scale.physicalTime; ...
    scale.X_shift;scale.canonicalTime];
end

function scale = unpack_scale(z)
scale = struct('logC_l',z(1),'logC_x',z(1),'logC_y',z(2), ...
    'logC_omega',z(3),'physicalTime',z(4),'X_shift',z(5), ...
    'canonicalTime',z(6));
end

function dz = scale_rate(z,flow)
dz = [flow.c_x;flow.c_y;flow.c_omega; ...
    flow.timeSpeed*exp(z(3)-z(1)); ...
    flow.c_x*z(5)+flow.c_r;flow.timeSpeed];
end
