function report = output()
%IPMTESTS.BASELINE.OUTPUT Verify collision-free persistence and manifest metadata.

fitTau = 12*((0:40)'/40).^1.4;
constantCL = 0.5327*ones(size(fitTau));
constantCOmega = 0.2655*ones(size(fitTau));
constantRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau,constantCL,constantCOmega);
constantWindows = constantRates.windows;
assert(constantRates.valid && constantRates.provisionalStable && ...
    constantRates.ratioDiagnosticsStable && ...
    constantRates.criteriaVersion == 3 && ...
    ~constantRates.selectedRateProvenanceAvailable && ...
    ~constantRates.empiricalRateConvergenceEligible && ...
    ~constantRates.zeroAwareProvisionalStable && ...
    strcmp(constantRates.interpretation, ...
        'diagnostic_only_requires_box_time_grid_refinement') && ...
    max(abs(constantRates.cOmegaOverCL-0.2655/0.5327)) < 1e-14 && ...
    max(abs([constantWindows.startCanonicalTau] - ...
        fitTau(end)*(1-constantRates.windowFractions))) < 1e-13 && ...
    constantRates.seriesSummary.cL.maximumAbsoluteRelativeTrend < 1e-13 && ...
    constantRates.seriesSummary.cOmega.relativeWindowMeanSpread < 1e-13, ...
    'ipm:OutputGaugeRateConstant', ...
    ['A constant gauge-rate history must pass all fixed nested-tail ' ...
    'convergence diagnostics.']);
driftingCL = 0.45*(1+0.12*fitTau/fitTau(end));
driftingCOmega = 0.24*(1+0.08*fitTau/fitTau(end));
driftingRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau,driftingCL,driftingCOmega);
assert(driftingRates.valid && ~driftingRates.provisionalStable && ...
    driftingRates.seriesSummary.cL.maximumAbsoluteRelativeTrend > 0.01 && ...
    driftingRates.seriesSummary.cOmega.maximumAbsoluteRelativeTrend > 0.01, ...
    'ipm:OutputGaugeRateDrift', ...
    'A persistent gauge-rate drift must fail the fixed one-percent gate.');
oscillatoryTau = linspace(0,12,401)';
oscillatoryPhase = 2*pi*40*oscillatoryTau/oscillatoryTau(end);
oscillatoryCL = 0.5*(1+0.2*cos(oscillatoryPhase));
oscillatoryCOmega = 0.25*(1+0.2*cos(oscillatoryPhase));
oscillatoryRates = ipm.diagnostics.gaugeRateConvergence( ...
    oscillatoryTau,oscillatoryCL,oscillatoryCOmega);
assert(oscillatoryRates.valid && ...
    ~oscillatoryRates.provisionalStable && ...
    oscillatoryRates.seriesSummary.cL.trendWithinTolerance && ...
    oscillatoryRates.seriesSummary.cL.windowMeanSpreadWithinTolerance && ...
    ~oscillatoryRates.seriesSummary.cL.detrendedRmsWithinTolerance && ...
    oscillatoryRates.seriesSummary.cL.maximumRelativeDetrendedRms > 0.1, ...
    'ipm:OutputGaugeRateOscillation', ...
    ['A zero-drift oscillatory gauge rate must fail the one-percent ' ...
    'detrended-RMS gate.']);
zeroCOmega = zeros(size(fitTau));
unknownZeroRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau,constantCL,zeroCOmega);
nonprescribedZeroRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau,constantCL,zeroCOmega, ...
    struct('selectedRatePrescribed',false));
prescribedZeroRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau,constantCL,zeroCOmega, ...
    struct('selectedRatePrescribed',true));
assert(~unknownZeroRates.valid && ...
    unknownZeroRates.cOmegaZeroLimitStable && ...
    ~unknownZeroRates.empiricalRateConvergenceEligible && ...
    ~unknownZeroRates.zeroAwareProvisionalStable && ...
    nonprescribedZeroRates.cOmegaZeroLimit.valid && ...
    nonprescribedZeroRates.cOmegaZeroLimitStable && ...
    nonprescribedZeroRates.empiricalRateConvergenceEligible && ...
    nonprescribedZeroRates.zeroAwareProvisionalStable && ...
    max(nonprescribedZeroRates.cOmegaZeroLimit. ...
        windowMaximumAbsoluteValues) == 0 && ...
    prescribedZeroRates.selectedRatePrescribed && ...
    ~prescribedZeroRates.empiricalRateConvergenceEligible && ...
    ~prescribedZeroRates.zeroAwareProvisionalStable, ...
    'ipm:OutputGaugeRateExactZero', ...
    ['An exact c_omega=0 history may pass the numerical zero-limit gate, ' ...
    'but only explicit non-prescribed provenance makes it empirically ' ...
    'eligible.']);
slowZeroRatio = 0.009*exp(-0.5*fitTau/fitTau(end));
slowZeroRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau,constantCL,constantCL.*slowZeroRatio, ...
    struct('selectedRatePrescribed',false));
assert(slowZeroRates.cOmegaZeroLimitStable && ...
    slowZeroRates.zeroAwareProvisionalStable && ...
    slowZeroRates.cOmegaZeroLimit.maximumAbsoluteValue < 0.01 && ...
    slowZeroRates.cOmegaZeroLimit.maximumAbsoluteTrendSpan < 0.01 && ...
    slowZeroRates.cOmegaZeroLimit.maximumDetrendedRms < 0.01 && ...
    slowZeroRates.cOmegaZeroLimit.windowMeanSpread < 0.01, ...
    'ipm:OutputGaugeRateSlowZeroLimit', ...
    ['A slowly decreasing, uniformly one-percent c_omega/c_l tail must ' ...
    'pass every preregistered absolute zero-limit gate.']);
crossingRatio = 0.04*(fitTau/fitTau(end)-0.7);
crossingRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau,constantCL,constantCL.*crossingRatio, ...
    struct('selectedRatePrescribed',false));
assert(~crossingRates.cOmegaZeroLimitStable && ...
    ~crossingRates.zeroAwareProvisionalStable && ...
    ~crossingRates.cOmegaZeroLimit.levelWithinTolerance && ...
    ~crossingRates.cOmegaZeroLimit.trendWithinTolerance, ...
    'ipm:OutputGaugeRateCrossingZero', ...
    ['Crossing zero must not conceal a dimensionless level or trend that ' ...
    'exceeds the one-percent zero-limit gate.']);
shortRates = ipm.diagnostics.gaugeRateConvergence( ...
    fitTau(1:15),constantCL(1:15),constantCOmega(1:15));
nonmonotoneTau = fitTau(1:16);
nonmonotoneTau(end) = nonmonotoneTau(end-1);
nonmonotoneRates = ipm.diagnostics.gaugeRateConvergence( ...
    nonmonotoneTau,constantCL(1:16),constantCOmega(1:16));
zeroCLRates = ipm.diagnostics.gaugeRateConvergence( ...
    linspace(0,1,20)',zeros(20,1),ones(20,1));
zeroBothRates = ipm.diagnostics.gaugeRateConvergence( ...
    linspace(0,1,20)',zeros(20,1),zeros(20,1), ...
    struct('selectedRatePrescribed',false));
assert(~shortRates.valid && ...
    strcmp(shortRates.validityReason,'insufficient_points') && ...
    ~nonmonotoneRates.valid && strcmp(nonmonotoneRates.validityReason, ...
        'canonical_tau_not_strictly_increasing') && ...
    ~zeroCLRates.valid && strcmp(zeroCLRates.validityReason, ...
        'relative_statistics_undefined') && ...
    ~zeroBothRates.ratiosAvailable && ...
    ~zeroBothRates.cLNonzeroAndStable && ...
    ~zeroBothRates.cOmegaZeroLimitStable && ...
    ~zeroBothRates.zeroAwareProvisionalStable, ...
    'ipm:OutputGaugeRateValidity', ...
    ['Gauge-rate convergence requires at least 16 records, strictly ' ...
    'increasing canonical tau, and finite relative statistics; a zero ' ...
    'c_l also invalidates the dimensionless zero-limit branch.']);

testDirectory = tempname;
mkdir(testDirectory);
directoryCleanup = onCleanup(@()cleanup_directory(testDirectory));

requestedResult = fullfile(testDirectory,'protected.mat');
requestedVideo = fullfile(testDirectory,'protected.mp4');
write_sentinel(requestedResult);
write_sentinel(requestedVideo);
opts = struct('nx',33,'ny',17,'xlim',[-4,4],'ymax',4, ...
    'initialCondition','degenerate','degeneratePower',4, ...
    'rescalingMode','physical','farBoundaryMode','dirichlet_zero', ...
    'physicalFinalTime',1e-4,'maxDt',1e-4,'minDt',1e-12, ...
    'maxSteps',2,'outputEvery',1e-4,'adaptiveRemesh',false, ...
    'initialAnalyticRemesh',false,'storeSnapshots',false, ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false, ...
    'resultFile',requestedResult,'videoFile',requestedVideo, ...
    'caseMetadata',struct('name','output-verification'));
result = ipm.solve(opts);
fitOpts = opts;
fitOpts.nx = 65;
fitOpts.ny = 33;
fitOpts.initialCondition = 'degenerate_primitive';
fitOpts.symmetryMode = 'double_odd_omega';
fitOpts.physicalFinalTime = 1.6e-3;
fitOpts.maxSteps = 20;
% This fixture exercises result wiring rather than wall-oscillation
% detection; retain the positive-wall check but make the TV gate inactive.
fitOpts.oscillationTVTolerance = 1e12;
fitResult = ipm.solve(fitOpts);
quadraticOpts = fitOpts;
quadraticOpts.rescalingMode = 'dynamic';
quadraticOpts.dynamicScaleGeometry = 'isotropic';
quadraticOpts.lengthGauge = 'transport_anchor';
quadraticOpts.transportAnchorX = 1;
quadraticOpts.cOmegaGauge = 'wall_omega_quadratic_peak';
quadraticOpts.spatialDiscretization = 'high_order';
quadraticOpts.transportScheme = 'weno5_fd';
quadraticOpts.timeIntegrator = 'ssprk54';
quadraticOpts.remeshTransferScheme = 'high_order';
quadraticOpts.physicalFinalTime = 1e-4;
quadraticOpts.finalTime = 1e-3;
quadraticOpts.maxSteps = 2;
quadraticOpts.outputEvery = 1e-4;
quadraticResult = ipm.solve(quadraticOpts);
quadraticCommon = quadraticResult.history.common;
quadraticGauge = quadraticResult.history.gauge;
quadraticPeak = quadraticGauge.omegaGaugeQuadraticPeakValue;
quadraticKappa = quadraticCommon.canonicalCL - ...
    quadraticCommon.canonicalCOmega;
expectedPhysicalPeak = quadraticCommon.C_l ./ ...
    quadraticCommon.C_omega .* quadraticPeak;
quadraticTelemetry = quadraticResult.fit.quadraticPeakTelemetry;
quadraticTrusted = ipm.output.continuousTrustedPrefix( ...
    ipm.output.trustedMask(quadraticResult.history,quadraticResult.config));
telemetryNames = {'physicalQuadraticPeak', ...
    'inversePhysicalQuadraticPeak','quadraticInverseSlopeAlgebraic', ...
    'quadraticLocalTerminalTime', ...
    'rescaledRhoXInfToQuadraticPeak'};
missingTelemetryResult = refinalize_quadratic_history( ...
    quadraticResult,telemetryNames,'missing');
nanTelemetryResult = refinalize_quadratic_history( ...
    quadraticResult,telemetryNames,'nan');
missingTelemetry = missingTelemetryResult.fit.quadraticPeakTelemetry;
nanTelemetry = nanTelemetryResult.fit.quadraticPeakTelemetry;
assert(all(isfield(quadraticCommon,telemetryNames)) && ...
    all(quadraticKappa > 0) && ...
    max(abs(quadraticCommon.physicalQuadraticPeak - ...
        expectedPhysicalPeak)) < 1e-12 && ...
    max(abs(quadraticCommon.inversePhysicalQuadraticPeak - ...
        1./expectedPhysicalPeak)) < 1e-12 && ...
    max(abs(quadraticCommon.quadraticInverseSlopeAlgebraic + ...
        quadraticKappa./quadraticPeak)) < 1e-12 && ...
    max(abs(quadraticCommon.quadraticLocalTerminalTime - ...
        (quadraticCommon.physicalTime + quadraticPeak ./ ...
        (quadraticKappa.*expectedPhysicalPeak)))) < 1e-12 && ...
    max(abs(quadraticCommon.rescaledRhoXInfToQuadraticPeak - ...
        quadraticCommon.rhoXInf./quadraticPeak)) < 1e-12 && ...
    quadraticTelemetry.inputAvailable && ...
    quadraticTelemetry.validRecords == nnz(quadraticTrusted) && ...
    isequal(quadraticTelemetry.physicalQuadraticPeak, ...
        quadraticCommon.physicalQuadraticPeak(quadraticTrusted)) && ...
    ~quadraticTelemetry.empiricalClassificationPerformed && ...
    strcmp(quadraticTelemetry.interpretation, ...
        'algebraic_identity_telemetry_only_no_empirical_blowup_claim') && ...
    missingTelemetry.inputAvailable && nanTelemetry.inputAvailable && ...
    missingTelemetry.reconstructedRecords == ...
        missingTelemetry.trustedRecords && ...
    nanTelemetry.reconstructedRecords == nanTelemetry.trustedRecords && ...
    strcmp(missingTelemetry.source, ...
        'reconstructed_from_schema4_history') && ...
    strcmp(nanTelemetry.source,'reconstructed_from_schema4_history') && ...
    isequal(missingTelemetry.physicalQuadraticPeak, ...
        quadraticTelemetry.physicalQuadraticPeak) && ...
    isequal(nanTelemetry.quadraticLocalTerminalTime, ...
        quadraticTelemetry.quadraticLocalTerminalTime) && ...
    all(isnan(result.history.common.physicalQuadraticPeak)) && ...
    ~result.fit.quadraticPeakTelemetry.inputAvailable, ...
    'ipm:OutputQuadraticPeakTelemetry', ...
    ['Quadratic-peak growth fields must be algebraic read-only telemetry; ' ...
    'nonquadratic histories must retain explicit NaN sentinels.']);
fitTrusted = ipm.output.continuousTrustedPrefix( ...
    ipm.output.trustedMask(fitResult.history,fitResult.config));
fitMaximum = fitResult.history.common.physicalRhoXInf(fitTrusted);
fitPhysicalTime = fitResult.history.common.physicalTime(fitTrusted);
fitCanonicalTau = fitResult.history.common.canonicalTau(fitTrusted);
assert(isequal(ipm.output.continuousTrustedPrefix( ...
    [true,true,false,true]),[true,true,false,false]) && ...
    isequal(ipm.output.continuousTrustedPrefix( ...
    [false,true]),[false,false]) && ...
    isequal(ipm.output.continuousTrustedPrefix( ...
    [true;true]),[true;true]) && ...
    result.fit.continuousTrustedPrefix && ...
    result.fit.trustedRecords <= result.fit.rawTrustedRecords, ...
    'ipm:OutputTrustedPrefix', ...
    'Blow-up fits must use the continuous prefix before the first failure.');
assert(all(isfield(fitResult.fit, ...
        {'candidate','maximumGrowthRate','canonicalMaximumGrowth', ...
        'gaugeRateConvergence'})) && ...
    fitResult.fit.maximumGrowthRate.valid && ...
    fitResult.fit.canonicalMaximumGrowth.valid && ...
    strcmp(fitResult.fit.maximumGrowthRate.observable, ...
        'physicalRhoXInf') && ...
    strcmp(fitResult.fit.canonicalMaximumGrowth.observable, ...
        'physicalRhoXInf') && ...
    fitResult.fit.maximumGrowthRate.inputAvailable && ...
    fitResult.fit.canonicalMaximumGrowth.inputAvailable && ...
    fitResult.fit.maximumGrowthRate.trustedRecords == nnz(fitTrusted) && ...
    fitResult.fit.canonicalMaximumGrowth.trustedRecords == ...
        nnz(fitTrusted) && ...
    isequal(fitResult.fit.maximumGrowthRate.maximum,fitMaximum(:)) && ...
    isequal(fitResult.fit.maximumGrowthRate.time,fitPhysicalTime(:)) && ...
    isequal(fitResult.fit.canonicalMaximumGrowth.maximum,fitMaximum(:)) && ...
    isequal(fitResult.fit.canonicalMaximumGrowth.canonicalTau, ...
        fitCanonicalTau(:)) && ...
    strcmp(fitResult.fit.gaugeRateConvergence.observable, ...
        'c_l_and_c_omega') && ...
    fitResult.fit.gaugeRateConvergence.inputAvailable && ...
    fitResult.fit.gaugeRateConvergence.continuousTrustedPrefix && ...
    fitResult.fit.gaugeRateConvergence.trustedRecords == nnz(fitTrusted) && ...
    fitResult.fit.gaugeRateConvergence.selectedRateProvenanceAvailable && ...
    fitResult.fit.gaugeRateConvergence.selectedRatePrescribed && ...
    ~fitResult.fit.gaugeRateConvergence. ...
        empiricalRateConvergenceEligible && ...
    isequal(fitResult.fit.gaugeRateConvergence.canonicalTau, ...
        fitCanonicalTau(:)) && ...
    isequal(fitResult.fit.gaugeRateConvergence.cL, ...
        fitResult.history.common.c_l(fitTrusted)) && ...
    isequal(fitResult.fit.gaugeRateConvergence.cOmega, ...
        fitResult.history.common.c_omega(fitTrusted)), ...
    'ipm:OutputMaximumGrowthFits', ...
    ['Finalization must retain the legacy blowupFit fields and append both ' ...
    'trusted physicalRhoXInf growth diagnostics plus gauge-rate tails.']);
assert(result.config.frozen && ...
    strcmp(result.config.output.resultFile,requestedResult) && ...
    strcmp(result.config.output.videoFile,requestedVideo) && ...
    strlength(result.metadata.resultFile) == 0 && ...
    strlength(result.metadata.videoFile) == 0, ...
    'ipm:OutputFrozenConfig', ...
    ['Disabled persistence must preserve requested paths in the frozen ' ...
    'configuration without reporting nonexistent actual artifacts.']);
gaugeContract = result.metadata.gaugeContract;
timestepHistory = result.history.common;
assert(gaugeContract.schemaVersion == 2 && ...
    strcmp(gaugeContract.clock,'canonical_tau_direct') && ...
    gaugeContract.timeSpeed == 1 && ...
    strcmp(gaugeContract.feedback.rateLimiter,'absent') && ...
    all(isfield(timestepHistory,{'acceptedCanonicalDt','transportRate', ...
        'cflDtLimit','maximumDtLimit','canonicalEndpointDtLimit', ...
        'physicalEndpointDtLimit','physicalClockSpeed','realizedCfl', ...
        'timestepActiveLimiter','amplitudeSourceStep', ...
        'conservativeSourceStep','physicalDomainXMinimum', ...
        'physicalDomainXMaximum','physicalDomainXRadius', ...
        'physicalDomainYMaximum','physicalMinimumDx', ...
        'physicalMinimumDy'})) && ...
    ismissing(timestepHistory.acceptedCanonicalDt(1)) && ...
    timestepHistory.acceptedCanonicalDt(end) > 0 && ...
    timestepHistory.realizedCfl(end) >= 0 && ...
    timestepHistory.timestepActiveLimiter(1) == "initial" && ...
    numel(timestepHistory.timestepActiveLimiter) == ...
        numel(timestepHistory.t) && ...
    timestepHistory.physicalDomainXMinimum(1) == opts.xlim(1) && ...
    timestepHistory.physicalDomainXMaximum(1) == opts.xlim(2) && ...
    timestepHistory.physicalDomainYMaximum(1) == opts.ymax, ...
    'ipm:OutputGaugeAndTimestepProvenance', ...
    ['Saved results must describe the exact gauge contract, accepted CFL ' ...
    'limiter, source step scales, and actual physical domain coverage.']);

reservationOpts = opts;
reservationOpts.saveResults = true;
reservationOpts.writeVideo = true;
reservationConfig = ipm.config.resolve(reservationOpts);
reservationOps = ipm.mesh.build(reservationConfig);
reservedMetadata = ipm.output.initializeMetadata( ...
    reservationConfig,reservationOps);
reservedResultFile = char(reservedMetadata.resultFile);
reservedVideoFile = char(reservedMetadata.videoFile);
assert(strcmp(reservationConfig.output.resultFile,requestedResult) && ...
    strcmp(reservationConfig.output.videoFile,requestedVideo) && ...
    ~strcmp(reservedResultFile,requestedResult) && ...
    ~strcmp(reservedVideoFile,requestedVideo) && ...
    ~strcmp(reservedResultFile,reservedVideoFile), ...
    'ipm:OutputMetadataReservation', ...
    ['Output initialization must retain requested config paths while ' ...
    'placing collision-free actual paths in run metadata.']);

writeOutput = result.config.output;
writeOutput.saveResults = true;
first = ipm.output.write(result,writeOutput);
second = ipm.output.write(result,writeOutput);
firstFile = char(first.metadata.resultFile);
secondFile = char(second.metadata.resultFile);

assert(strcmp(fileread(requestedResult),'sentinel') && ...
    strcmp(fileread(requestedVideo),'sentinel') && ...
    ~strcmp(firstFile,requestedResult) && ~strcmp(secondFile,requestedResult) && ...
    ~strcmp(firstFile,secondFile) && isfile(firstFile) && isfile(secondFile), ...
    'ipm:OutputOverwrite', ...
    'Result persistence overwrote or reused an existing artifact path.');
assert(isequaln(first.config,result.config) && ...
    isequaln(second.config,result.config) && ...
    strcmp(first.config.output.resultFile,requestedResult) && ...
    strcmp(first.config.output.videoFile,requestedVideo), ...
    'ipm:OutputConfigMutation', ...
    ['Persistence must report actual artifact paths through metadata ' ...
    'without rewriting the frozen requested configuration.']);
loaded = load(firstFile,'result');
validated = ipm.output.validate(loaded.result);
assert(validated.schemaVersion == 2 && isequaln(validated,loaded.result) && ...
    validated.config.schemaVersion == 4 && ...
    strcmp(char(validated.metadata.resultFile),firstFile) && ...
    strcmp(validated.config.output.resultFile,requestedResult) && ...
    strcmp(validated.config.output.videoFile,requestedVideo) && ...
    isequal(validated.metadata.caseMetadata,opts.caseMetadata), ...
    'ipm:OutputMetadata', ...
    'The saved result does not contain its actual path or case metadata.');
retiredFeedback = {'maxDynamicRate','adaptiveLengthScaling', ...
    'widthExpansionStrength', ...
    'widthContractionOnset','widthContractionStrength', ...
    'maxWidthRateCorrection'};
assert(strcmp(validated.config.scaling.scalingContract, ...
    'exact_gauge_no_feedback_v1') && ...
    validated.config.scaling.lengthScaleGain == 1 && ...
    validated.config.scaling.widthGaugeGain == 0 && ...
    validated.config.scaling.omegaGaugeGain == 0 && ...
    validated.config.scaling.travelingWaveGain == 0 && ...
    ~any(isfield(validated.config.scaling,retiredFeedback)), ...
    'ipm:OutputNoFeedbackContract', ...
    'The frozen schema-4 result does not satisfy the no-feedback contract.');

noncanonicalClock = result;
noncanonicalClock.history.common.canonicalTau(end) = ...
    noncanonicalClock.history.common.canonicalTau(end)+1e-6;
noncanonicalClock.state.canonicalTime = ...
    noncanonicalClock.history.common.canonicalTau(end);
assert_throws(@()ipm.output.validate(noncanonicalClock), ...
    'ipm:ResultCanonicalClock');
nonunitTimeSpeed = result;
nonunitTimeSpeed.history.common.timeSpeed(end) = 0.5;
assert_throws(@()ipm.output.validate(nonunitTimeSpeed), ...
    'ipm:ResultCanonicalClock');
noncanonicalRate = result;
noncanonicalRate.history.common.c_l(end) = ...
    noncanonicalRate.history.common.c_l(end)+1e-3;
assert_throws(@()ipm.output.validate(noncanonicalRate), ...
    'ipm:ResultCanonicalRate');

legacyV3ConfigResult = as_schema_three(result);
assert(isequaln(ipm.output.validate(legacyV3ConfigResult), ...
    legacyV3ConfigResult), ...
    'ipm:OutputConfigV3Compatibility', ...
    'A valid historical feedback-capable configuration schema 3 was rejected.');
futureGauges = {'anchor_wall_template_projection', ...
    'anchor_bulk_gradient_l2','anchor_wall_window_l4', ...
    'wall_omega_quadratic_peak'};
for futureGaugeIndex = 1:numel(futureGauges)
    impossibleLegacyFutureGauge = legacyV3ConfigResult;
    impossibleLegacyFutureGauge.config.scaling.cOmegaGauge = ...
        futureGauges{futureGaugeIndex};
    assert_throws(@()ipm.output.validate(impossibleLegacyFutureGauge), ...
        'ipm:ResultConfig');
end

legacyV2ConfigResult = legacyV3ConfigResult;
legacyV2ConfigResult.config.schemaVersion = 2;
if isfield(legacyV2ConfigResult.config.scaling,'omegaGaugeWindowRadius')
    legacyV2ConfigResult.config.scaling = rmfield( ...
        legacyV2ConfigResult.config.scaling,'omegaGaugeWindowRadius');
end
legacyV2ConfigResult.config.scaling.maxDynamicRate = 2;
legacyV2ConfigResult.history.common.timeSpeed(:) = 0.5;
legacyV2ConfigResult.history.common.t = ...
    0.5*legacyV2ConfigResult.history.common.canonicalTau;
legacyV2ConfigResult.state.normalizedTime = ...
    legacyV2ConfigResult.history.common.t(end);
assert(isequaln(ipm.output.validate(legacyV2ConfigResult), ...
    legacyV2ConfigResult), ...
    'ipm:OutputConfigV2Compatibility', ...
    'A valid legacy maxDynamicRate configuration schema 2 was rejected.');
invalidLegacyRate = legacyV2ConfigResult;
invalidLegacyRate.config.scaling.maxDynamicRate = Inf;
assert_throws(@()ipm.output.validate(invalidLegacyRate), ...
    'ipm:ResultConfig');
impossibleLegacyWindowGauge = legacyV2ConfigResult;
impossibleLegacyWindowGauge.config.scaling.cOmegaGauge = ...
    'anchor_wall_window_l2';
assert_throws(@()ipm.output.validate(impossibleLegacyWindowGauge), ...
    'ipm:ResultConfig');

legacyConfigResult = legacyV2ConfigResult;
legacyConfigResult.config.schemaVersion = 1;
legacyConfigResult.config.time = rmfield( ...
    legacyConfigResult.config.time,'timeIntegrator');
legacyConfigResult.config.transport = rmfield( ...
    legacyConfigResult.config.transport,'spatialDiscretization');
legacyConfigResult.config.remesh = rmfield( ...
    legacyConfigResult.config.remesh,'remeshTransferScheme');
assert(isequaln(ipm.output.validate(legacyConfigResult),legacyConfigResult), ...
    'ipm:OutputConfigV1Compatibility', ...
    'A valid pre-high-order configuration schema 1 result was rejected.');
misversionedConfig = result;
misversionedConfig.config.schemaVersion = 1;
assert_throws(@()ipm.output.validate(misversionedConfig), ...
    'ipm:ResultConfig');
invalidSelector = result;
invalidSelector.config.time.timeIntegrator = 'bogus';
assert_throws(@()ipm.output.validate(invalidSelector), ...
    'ipm:ResultConfig');
invalidTuple = result;
invalidTuple.config.transport.transportScheme = 'weno5_fd';
assert_throws(@()ipm.output.validate(invalidTuple), ...
    'ipm:ResultConfig');
invalidRemeshTuple = result;
invalidRemeshTuple.config.remesh.remeshTransferScheme = 'high_order';
assert_throws(@()ipm.output.validate(invalidRemeshTuple), ...
    'ipm:ResultConfig');
sixthTuple = result;
sixthTuple.config.transport.spatialDiscretization = 'sixth_order';
sixthTuple.config.transport.transportScheme = 'weno7_fd';
sixthTuple.config.time.timeIntegrator = 'rk6';
sixthTuple.config.remesh.remeshTransferScheme = 'sixth_order';
assert(isequaln(ipm.output.validate(sixthTuple),sixthTuple), ...
    'ipm:OutputSixthOrderTuple', ...
    'A complete persisted sixth-order selector tuple was rejected.');
invalidSixthTuple = sixthTuple;
invalidSixthTuple.config.time.timeIntegrator = 'ssprk54';
assert_throws(@()ipm.output.validate(invalidSixthTuple), ...
    'ipm:ResultConfig');
invalidPoissonTuple = result;
invalidPoissonTuple.config.transport.spatialDiscretization = 'high_order';
invalidPoissonTuple.config.scaling.dynamicScaleGeometry = 'anisotropic';
invalidPoissonTuple.config.elliptic.anisotropicPoissonSolver = 'pcg';
assert_throws(@()ipm.output.validate(invalidPoissonTuple), ...
    'ipm:ResultConfig');
legacyHighOrderImpostor = legacyConfigResult;
legacyHighOrderImpostor.config.transport.transportScheme = 'weno5_fd';
assert_throws(@()ipm.output.validate(legacyHighOrderImpostor), ...
    'ipm:ResultConfig');

missingVersion = rmfield(result,'schemaVersion');
schemaOne = result;
schemaOne.schemaVersion = 1;
otherVersion = result;
otherVersion.schemaVersion = 3;
assert_schema_rejected(@()ipm.output.validate(missingVersion));
assert_schema_rejected(@()ipm.output.validate(schemaOne));
assert_schema_rejected(@()ipm.output.validate(otherVersion));
assert_schema_rejected(@()ipm.output.validateV2(missingVersion));
assert_schema_rejected(@()ipm.output.validateV2(schemaOne));

flatConfig = result;
flatConfig.config = struct('rescalingMode','physical');
assert_throws(@()ipm.output.validate(flatConfig),'ipm:ResultConfig');
missingConfigField = result;
missingConfigField.config.scaling = rmfield( ...
    missingConfigField.config.scaling,'rescalingMode');
assert_throws(@()ipm.output.validate(missingConfigField), ...
    'ipm:ResultMissingField');
unexpectedConfigField = result;
unexpectedConfigField.config.time.legacyFinalTime = 1;
assert_throws(@()ipm.output.validate(unexpectedConfigField), ...
    'ipm:ResultConfig');
legacyFieldInCurrentConfig = result;
legacyFieldInCurrentConfig.config.scaling.maxDynamicRate = 2;
assert_throws(@()ipm.output.validate(legacyFieldInCurrentConfig), ...
    'ipm:ResultConfig');
retiredFeedbackInCurrentConfig = result;
retiredFeedbackInCurrentConfig.config.scaling.adaptiveLengthScaling = false;
assert_throws(@()ipm.output.validate(retiredFeedbackInCurrentConfig), ...
    'ipm:ResultConfig');
wrongNoFeedbackSentinel = result;
wrongNoFeedbackSentinel.config.scaling.omegaGaugeGain = eps;
assert_throws(@()ipm.output.validate(wrongNoFeedbackSentinel), ...
    'ipm:ResultConfig');
wrongScalingContract = result;
wrongScalingContract.config.scaling.scalingContract = 'legacy_feedback';
assert_throws(@()ipm.output.validate(wrongScalingContract), ...
    'ipm:ResultConfig');
remeshedTemplateGauge = result;
remeshedTemplateGauge.config.scaling.cOmegaGauge = ...
    'anchor_wall_template_projection';
remeshedTemplateGauge.config.scaling.lengthGauge = 'transport_anchor';
remeshedTemplateGauge.config.scaling.transportAnchorX = 1;
remeshedTemplateGauge.config.remesh.adaptiveRemesh = true;
assert_throws(@()ipm.output.validate(remeshedTemplateGauge), ...
    'ipm:ResultConfig');
approximateGaugeInCurrentConfig = result;
approximateGaugeInCurrentConfig.config.scaling.cOmegaGauge = ...
    'anchor_wall_strain';
approximateGaugeInCurrentConfig.config.scaling.lengthGauge = ...
    'transport_anchor';
assert_throws(@()ipm.output.validate(approximateGaugeInCurrentConfig), ...
    'ipm:ResultConfig');
customConfig = result;
customConfig.config.grid.customX = result.grid.x;
customConfig.config.grid.customY = result.grid.y;
assert(isequaln(ipm.output.validate(customConfig),customConfig), ...
    'ipm:OutputCustomConfigPair', ...
    'A paired optional custom grid was rejected by result validation.');
orphanCustomConfig = customConfig;
orphanCustomConfig.config.grid = rmfield( ...
    orphanCustomConfig.config.grid,'customY');
assert_throws(@()ipm.output.validate(orphanCustomConfig), ...
    'ipm:ResultConfig');
earlyV2 = result;
earlyV2.history.anisotropic.mode = "fixed";
assert_throws(@()ipm.output.validate(earlyV2),'ipm:ResultHistoryField');
duplicateHistory = result;
duplicateHistory.history.gauge.t = duplicateHistory.history.common.t;
assert_throws(@()ipm.output.validate(duplicateHistory), ...
    'ipm:HistoryDuplicateField');

missingVersionFile = fullfile(testDirectory,'missing-version.mat');
schemaOneFile = fullfile(testDirectory,'schema-one.mat');
legacyAliasFile = fullfile(testDirectory,'legacy-alias.mat');
write_result_payload(missingVersionFile,missingVersion);
write_result_payload(schemaOneFile,schemaOne);
write_legacy_alias(legacyAliasFile,schemaOne);
assert_schema_rejected(@()ipm.output.validate(missingVersionFile));
assert_schema_rejected(@()ipm.output.validate(schemaOneFile));
assert_throws(@()ipm.output.validate(legacyAliasFile), ...
    'ipm:ResultFileContract');

manifestFile = fullfile(testDirectory,'manifest.jsonl');
manifestLines = splitlines(string(strtrim(fileread(manifestFile))));
assert(numel(manifestLines) == 2, ...
    'ipm:OutputManifestCount', ...
    'Each successful save must append exactly one manifest record.');
lastRecord = jsondecode(manifestLines(end));
assert(strcmp(lastRecord.caseId,result.metadata.caseId) && ...
    strcmp(lastRecord.resultFile,secondFile), ...
    'ipm:OutputManifestMetadata', ...
    'The manifest does not identify the saved result and actual path.');

assert(~isfile(reservedVideoFile), ...
    'ipm:OutputVideoOverwrite', ...
    'Video path selection did not preserve an existing artifact.');

report = struct('requestedPreserved',true,'manifestRecords',2, ...
    'firstResultFile',string(firstFile),'secondResultFile',string(secondFile), ...
    'reservedResultFile',string(reservedResultFile), ...
    'videoFile',string(reservedVideoFile), ...
    'canonicalIdentityRejected',true, ...
    'legacyClockCompatibilityPreserved',true, ...
    'schemaThreeAnalysisPreserved',true,'noFeedbackEnforced',true, ...
    'maximumGrowthFitsAttached',true,'gaugeRateConvergenceAttached',true, ...
    'quadraticPeakTelemetryAttached',true);
fprintf('IPM output verification passed: protected artifact preserved, 2 manifests.\n');
end

function result = as_schema_three(result)
result.config.schemaVersion = 3;
result.config.scaling = rmfield(result.config.scaling,'scalingContract');
result.config.scaling.adaptiveLengthScaling = false;
result.config.scaling.widthExpansionStrength = 1;
result.config.scaling.widthContractionOnset = 1.35;
result.config.scaling.widthContractionStrength = 28;
result.config.scaling.maxWidthRateCorrection = 16;
end

function rebuilt = refinalize_quadratic_history(result,names,mode)
outputLog = ipm.output.initializeLog();
outputLog.history = result.history;
switch mode
    case 'missing'
        outputLog.history.common = rmfield(outputLog.history.common,names);
    case 'nan'
        for index = 1:numel(names)
            outputLog.history.common.(names{index})(:) = NaN;
        end
end
ops = ipm.mesh.build(result.config);
state = struct( ...
    'rho',result.state.rho, ...
    'flow',struct('psi',result.state.psi,'source',result.state.omega, ...
        'u1',result.state.velocity.x,'u2',result.state.velocity.y, ...
        'trackedPeakX',result.grid.trackedPeakX, ...
        'poissonSolveInfo',result.elliptic.solveInfo), ...
    'scale',struct('logC_l',log(result.scale.Cx), ...
        'logC_omega',log(result.scale.Comega), ...
        'physicalTime',result.state.physicalTime, ...
        'X_shift',result.scale.Xshift, ...
        'canonicalTime',result.state.canonicalTime), ...
    'ops',ops,'config',result.config, ...
    'normalizedTime',result.state.normalizedTime, ...
    'step',result.state.steps,'runMetadata',result.metadata);
rebuilt = ipm.output.finalize(state,outputLog,result.state.stopReason);
end

function assert_schema_rejected(action)
try
    action();
catch exception
    assert(strcmp(exception.identifier,'ipm:ResultSchemaVersion') && ...
        contains(exception.message,'schemaVersion=2'), ...
        'ipm:OutputSchemaError', ...
        'Expected a clear schemaVersion=2 rejection, received %s: %s.', ...
        exception.identifier,exception.message);
    return;
end
error('ipm:OutputSchemaAcceptance', ...
    'A legacy, unversioned, or unsupported result schema was accepted.');
end

function assert_throws(action,identifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:OutputUnexpectedError', ...
        'Expected %s but received %s.',identifier,exception.identifier);
    return;
end
error('ipm:OutputMissingError','Expected error %s was not raised.',identifier);
end

function write_result_payload(fileName,value)
result = value;
save(fileName,'result');
end

function write_legacy_alias(fileName,value)
d = value;
save(fileName,'d');
end

function write_sentinel(fileName)
fileId = fopen(fileName,'w');
if fileId < 0
    error('ipm:OutputTestFile','Could not create %s.',fileName);
end
cleanup = onCleanup(@()fclose(fileId));
fwrite(fileId,'sentinel','char');
end

function cleanup_directory(directory)
if isfolder(directory)
    try
        rmdir(directory,'s');
    catch exception
        fprintf(2,'IPM warning: could not remove test directory %s: %s\n', ...
            directory,exception.message);
    end
end
end
