function report = remesh()
%IPMTESTS.BASELINE.REMESH Verify adaptive-axis and conservative remesh contracts.

fprintf('Running IPM remesh verification...\n');
anchoredAxisOpts = ipm.config.resolve(struct('nx',257,'ny',129, ...
    'xlim',[-20,20],'ymax',10,'remeshOuterAnchorFactor',3, ...
    'remeshMaximumCellRatio',10));
anchoredBaseAxis = linspace(-20,20,257);
anchoredBounds = [0.5,2.0;0.8,1.5;1.0,1.2];
[anchoredAxis,anchoredAxisInfo] = ipm.remesh.axis(anchoredBaseAxis, ...
    anchoredBounds,1.1,[30,18,8],1e-4,anchoredAxisOpts.remesh,true);
anchoredFarMask = abs(anchoredBaseAxis) >= 18;
anchoredFarDefect = max(abs( ...
    anchoredAxis(anchoredFarMask)-anchoredBaseAxis(anchoredFarMask)));
incrementalAxisOpts = anchoredAxisOpts;
incrementalAxisOpts.remesh.remeshMaximumCellRatio = 2;
[incrementalAxis,incrementalAxisInfo] = ipm.remesh.axis( ...
    anchoredBaseAxis,anchoredBounds,1.1,[100,60,20],1e-4, ...
    incrementalAxisOpts.remesh,true);
incrementalAxisChange = max(abs(incrementalAxis-anchoredBaseAxis));
transitionAxisOpts = anchoredAxisOpts;
transitionAxisOpts.remesh.remeshReferenceMode = 'current';
transitionAxisOpts.remesh.remeshMaximumCellRatio = 8;
[transitionAxis,transitionAxisInfo] = ipm.remesh.axis(anchoredAxis, ...
    anchoredBounds,1.1,[60,36,16],1e-4, ...
    transitionAxisOpts.remesh,true);
transitionFarDefect = max(abs(transitionAxis(anchoredFarMask)- ...
    anchoredAxis(anchoredFarMask)));
latticeAxisOpts = anchoredAxisOpts;
latticeAxisOpts.remesh.remeshAxisProfile = 'lattice';
latticeAxisOpts.remesh.remeshBridgeFloor = 0.005;
latticeAxisOpts.remesh.remeshBridgePower = 4;
[latticeAxis,latticeAxisInfo] = ipm.remesh.axis(anchoredBaseAxis, ...
    anchoredBounds,1.1,[60,36,16],1e-4,latticeAxisOpts.remesh,true);
latticeGlobalRatio = max(diff(latticeAxis))/min(diff(latticeAxis));
strictLatticeOpts = latticeAxisOpts;
strictLatticeOpts.remesh.remeshMaximumCellRatio = 1.5;
[strictLatticeAxis,strictLatticeInfo] = ipm.remesh.axis( ...
    anchoredBaseAxis,anchoredBounds,1.1,[60,36,16],1e-4, ...
    strictLatticeOpts.remesh,true);
strictLatticeChange = max(abs(strictLatticeAxis-anchoredBaseAxis));
wideGridOpts = ipm.config.resolve(struct('nx',513,'ny',257, ...
    'xlim',[-1000,1000],'ymax',1000, ...
    'targetCenterSpacing',[0.01,0.01]));
wideGridOps = ipm.mesh.build(wideGridOpts);
wideGridAdjacentRatio = max(max( ...
    wideGridOps.dxFaces(2:end)./wideGridOps.dxFaces(1:end-1), ...
    wideGridOps.dxFaces(1:end-1)./wideGridOps.dxFaces(2:end)));
wideGridGlobalRatio = max(wideGridOps.dxFaces)/min(wideGridOps.dxFaces);

dynamicOverrides = struct('nx',65,'ny',33,'xlim',[-4,4], ...
    'ymax',4,'initialCondition','degenerate','degeneratePower',4, ...
    'symmetryMode','half_plane', ...
    'rescalingMode','dynamic','saveResults',false, ...
    'makePlots',false,'verbose',false);
dynamicOpts = ipm.config.resolve(dynamicOverrides);
dynamicOps = ipm.mesh.build(dynamicOpts);
dynamicRho = ipm.field.initialDensity(dynamicOps,dynamicOpts.physics);
dynamicOps = ipm.evolve.initializeScaling(dynamicRho,dynamicOps);
[~,dynamicFlow] = ipm.evolve.rhs(dynamicRho,dynamicOps);
remeshOpsFixture = dynamicOps;
remeshMetrics = ipm.diagnostics.peakResolution(max(dynamicFlow.source(1,:),0), ...
    dynamicOps.x,dynamicOps.rescaling.adaptiveLevels);
remeshOpsFixture.rescaling.safetyPeakPoints = remeshMetrics.areaPoints(1);
remeshOpsFixture.rescaling.safetyLevelPoints = remeshMetrics.gridPoints;
remeshOpsFixture.rescaling.adaptiveTargetLevelPoints = ...
    2*remeshMetrics.gridPoints;
remeshFixtureOpts = dynamicOpts;
remeshFixtureOpts.remesh.remeshMaximumCellRatio = 10;
remeshFixtureConfigBefore = remeshFixtureOpts;
[remeshFixtureProposal,~] = ipm.remesh.propose( ...
    remeshOpsFixture,dynamicFlow,remeshFixtureOpts,0,[]);
[~,proposalTransferOps] = ipm.remesh.transfer( ...
    dynamicRho,remeshOpsFixture,remeshFixtureOpts,remeshFixtureProposal);
proposalGridDefect = max([ ...
    max(abs(proposalTransferOps.x-remeshFixtureProposal.x)), ...
    max(abs(proposalTransferOps.y-remeshFixtureProposal.y))]);
proposalBaseDefect = max([ ...
    max(abs(proposalTransferOps.baseX-remeshOpsFixture.baseX)), ...
    max(abs(proposalTransferOps.baseY-remeshOpsFixture.baseY))]);
[remeshedRho,remeshedOps,remeshInfo] = ipm.remesh.adapt( ...
    dynamicRho,remeshOpsFixture,dynamicFlow,remeshFixtureOpts);
[~,remeshedFlow] = ipm.evolve.rhs(remeshedRho,remeshedOps);
[~,repeatedRemeshOps,repeatedRemeshInfo] = ipm.remesh.adapt( ...
    remeshedRho,remeshedOps,remeshedFlow,remeshFixtureOpts);
remeshCompoundingError = max(abs(repeatedRemeshOps.x-remeshedOps.x));
remeshQuadratic = remeshedOps.X.^2+0.5*remeshedOps.Y.^2;
remeshDerivativeError = max(abs( ...
    remeshQuadratic*remeshedOps.Dx'-2*remeshedOps.X),[],'all');
remeshDerivativeError = max(remeshDerivativeError,max(abs( ...
    remeshedOps.Dy*remeshQuadratic-remeshedOps.Y),[],'all'));
remeshRangeViolation = max([min(dynamicRho,[],'all')- ...
    min(remeshedRho,[],'all'),max(remeshedRho,[],'all')- ...
    max(dynamicRho,[],'all'),0]);
remeshRowMassError = max(abs( ...
    remeshedRho*remeshedOps.hx'-dynamicRho*dynamicOps.hx'));
cappedRemeshOpsFixture = remeshOpsFixture;
cappedRemeshOpsFixture.rescaling.safetyLevelPoints = ...
    5*remeshMetrics.gridPoints;
cappedRemeshOpsFixture.rescaling.adaptiveTargetLevelPoints = ...
    10*remeshMetrics.gridPoints;
cappedRemeshOpts = dynamicOpts;
cappedRemeshOpts.remesh.remeshMinimumSpacingFactor = 0.5;
cappedRemeshOpts.remesh.remeshMaximumCellRatio = 10;
[~,cappedRemeshOps,cappedRemeshInfo] = ipm.remesh.adapt( ...
    dynamicRho,cappedRemeshOpsFixture,dynamicFlow,cappedRemeshOpts);
cappedRemeshMinimumSpacing = min(diff(cappedRemeshOps.x));
coreRejectFlow = dynamicFlow;
coreRejectFlow.coreGridPoints = 1e6;
[~,coreRejectOps,coreRejectInfo] = ipm.remesh.adapt( ...
    dynamicRho,remeshOpsFixture,coreRejectFlow,remeshFixtureOpts);

symmetricOverrides = dynamicOverrides;
symmetricOverrides.symmetryMode = 'double_odd_omega';
symmetricOverrides.lengthGauge = 'omega_peak_location';
symmetricOpts = ipm.config.resolve(symmetricOverrides);
symmetricOps = ipm.mesh.build(symmetricOpts);
symmetricRho = ipm.field.initialDensity(symmetricOps,symmetricOpts.physics);
symmetricOps = ipm.evolve.initializeScaling(symmetricRho,symmetricOps);
[~,symmetricFlow] = ipm.evolve.rhs(symmetricRho,symmetricOps);
symmetricRemeshOpsFixture = symmetricOps;
symmetricRemeshMetrics = ipm.diagnostics.peakResolution( ...
    max(symmetricFlow.source(1,:),0),symmetricOps.x, ...
    symmetricOps.rescaling.adaptiveLevels);
symmetricRemeshOpsFixture.rescaling.safetyPeakPoints = ...
    symmetricRemeshMetrics.areaPoints(1);
symmetricRemeshOpsFixture.rescaling.safetyLevelPoints = ...
    symmetricRemeshMetrics.gridPoints;
symmetricRemeshOpsFixture.rescaling.adaptiveTargetLevelPoints = ...
    2*symmetricRemeshMetrics.gridPoints;
symmetricRemeshOpts = symmetricOpts;
symmetricRemeshOpts.remesh.remeshMaximumCellRatio = 10;
[symmetricRemeshRho,symmetricRemeshOps,symmetricRemeshInfo] = ...
    ipm.remesh.adapt(symmetricRho,symmetricRemeshOpsFixture, ...
    symmetricFlow,symmetricRemeshOpts);
symmetricRemeshDefect = max([ ...
    max(abs(symmetricRemeshOps.x+fliplr(symmetricRemeshOps.x))), ...
    max(abs(symmetricRemeshRho-fliplr(symmetricRemeshRho)),[],'all')]);

physicalOverrides = symmetricOverrides;
physicalOverrides.rescalingMode = 'physical';
physicalOverrides.nx = 129;
physicalOverrides.ny = 65;
physicalOverrides.xlim = [-16,16];
physicalOverrides.ymax = 16;
physicalOverrides.targetCenterSpacing = [0.05,0.05];
physicalOverrides.gridStretchAutomatic = true;
physicalOverrides.remeshMinimumSpacingFactor = 0.01;
physicalOverrides.remeshConcentration = 30;
physicalOpts = ipm.config.resolve(physicalOverrides);
physicalOps = ipm.mesh.build(physicalOpts);
physicalRho = ipm.field.initialDensity(physicalOps,physicalOpts.physics);
physicalOps = ipm.evolve.initializeScaling(physicalRho,physicalOps);
[~,physicalFlow] = ipm.evolve.rhs(physicalRho,physicalOps);
physicalYRemeshOps = physicalOps;
physicalYRemeshOps.rescaling.safetyPeakPoints = 0;
physicalYRemeshOps.rescaling.safetyLevelPoints(:) = 0;
physicalYRemeshOps.rescaling.safetyVerticalPeakPoints = ...
    physicalFlow.verticalPeakGridPoints;
physicalYRemeshOps.rescaling.safetyVerticalLevelPoints = [ ...
    physicalFlow.verticalSupportGridPoints, ...
    mean([physicalFlow.verticalSupportGridPoints, ...
    physicalFlow.verticalCoreGridPoints]), ...
    physicalFlow.verticalCoreGridPoints];
physicalYRemeshOps.rescaling.adaptiveTargetVerticalLevelPoints = ...
    2*physicalYRemeshOps.rescaling.safetyVerticalLevelPoints;
physicalYRemeshOpts = physicalOpts;
physicalYRemeshOpts.remesh.remeshMaximumCellRatio = 10;
[physicalYRemeshRho,physicalYRemeshOps,physicalYRemeshInfo] = ...
    ipm.remesh.adapt(physicalRho,physicalYRemeshOps, ...
    physicalFlow,physicalYRemeshOpts);
[~,physicalYRemeshFlowNew] = ipm.evolve.rhs( ...
    physicalYRemeshRho,physicalYRemeshOps);
physicalRemeshOldGrad = max(hypot( ...
    physicalRho*physicalOps.Dx',physicalOps.Dy*physicalRho),[],'all');
physicalRemeshNewGrad = max(hypot( ...
    physicalYRemeshRho*physicalYRemeshOps.Dx', ...
    physicalYRemeshOps.Dy*physicalYRemeshRho),[],'all');
physicalRemeshGradientRatio = physicalRemeshNewGrad / ...
    max(physicalRemeshOldGrad,eps);
physicalRemeshMassError = abs( ...
    sum(physicalYRemeshRho.*physicalYRemeshOps.weights,'all')- ...
    sum(physicalRho.*physicalOps.weights,'all')) / ...
    max(abs(sum(physicalRho.*physicalOps.weights,'all')),eps);
physicalRemeshWallError = max(abs(physicalYRemeshRho(1,:)- ...
    interp1(physicalOps.x,physicalRho(1,:),physicalYRemeshOps.x,'pchip')));
physicalRateMaximum = max(abs([physicalFlow.c_l,physicalFlow.c_omega, ...
    physicalFlow.c_r, ...
    physicalYRemeshFlowNew.c_l,physicalYRemeshFlowNew.c_omega, ...
    physicalYRemeshFlowNew.c_r]));

report.anchoredAxisFarDefect = anchoredFarDefect;
report.anchoredAxisTargetReached = anchoredAxisInfo.targetReached;
report.incrementalAxisAmplitude = incrementalAxisInfo.amplitude;
report.incrementalAxisTargetReached = incrementalAxisInfo.targetReached;
report.incrementalAxisChange = incrementalAxisChange;
report.latticeAxisCounts = latticeAxisInfo.counts;
report.latticeAxisAdjacentRatio = latticeAxisInfo.maximumCellRatio;
report.latticeAxisGlobalRatio = latticeGlobalRatio;
report.strictLatticeAmplitude = strictLatticeInfo.amplitude;
report.strictLatticeAdjacentRatio = strictLatticeInfo.maximumCellRatio;
report.strictLatticeChange = strictLatticeChange;
report.wideGridAdjacentRatio = wideGridAdjacentRatio;
report.wideGridGlobalRatio = wideGridGlobalRatio;
report.remeshOldPeakSpacing = remeshInfo.oldPeakSpacing;
report.remeshNewPeakSpacing = remeshInfo.newPeakSpacing;
report.remeshDerivativeError = remeshDerivativeError;
report.remeshRangeViolation = remeshRangeViolation;
report.remeshRowMassError = remeshRowMassError;
report.remeshCompoundingError = remeshCompoundingError;
report.proposalGridDefect = proposalGridDefect;
report.proposalBaseDefect = proposalBaseDefect;
report.cappedRemeshMinimumSpacing = cappedRemeshMinimumSpacing;
report.symmetricRemeshDefect = symmetricRemeshDefect;
report.physicalRemeshMassError = physicalRemeshMassError;
report.physicalRemeshWallError = physicalRemeshWallError;
report.physicalRemeshGradientRatio = physicalRemeshGradientRatio;

assert(anchoredFarDefect < 1e-14 && anchoredAxisInfo.targetReached, ...
    'ipm:AnchoredAdaptiveAxis', ...
    'The local adaptive axis changed the anchored far grid or missed targets.');
assert(incrementalAxisInfo.amplitude > 0 && ...
    ~incrementalAxisInfo.targetReached && incrementalAxisChange > 0 && ...
    incrementalAxisInfo.maximumCellRatio <= 2*(1+1e-10), ...
    'ipm:IncrementalAdaptiveAxis', ...
    'The constrained monitor failed to retain its best valid improvement.');
assert(transitionAxisInfo.amplitude > 0 && transitionFarDefect < 1e-14 && ...
    transitionAxisInfo.maximumCellRatio <= 8*(1+1e-10) && ...
    transitionAxisInfo.counts(end) > anchoredAxisInfo.counts(end), ...
    'ipm:AdaptiveTransitionSmoothing', ...
    'Current-grid transition smoothing lost the far anchor or ratio reserve.');
assert(latticeAxisInfo.targetReached && ...
    all(latticeAxisInfo.counts >= [60,36,16]-1e-8) && ...
    latticeAxisInfo.maximumCellRatio <= 8*(1+1e-10) && ...
    latticeAxisInfo.counts(end) > anchoredAxisInfo.counts(end) && ...
    wideGridAdjacentRatio < 1.1 && wideGridGlobalRatio > 1e3, ...
    'ipm:LatticeAxisConcentration', ...
    ['The legacy-inspired flat-core profile did not enlarge the core, or ' ...
    'a global grid-ratio constraint leaked into the grid contract.']);
assert(strictLatticeInfo.amplitude > 0 && ...
    ~strictLatticeInfo.targetReached && strictLatticeChange > 0 && ...
    strictLatticeInfo.maximumCellRatio <= 1.5*(1+1e-10), ...
    'ipm:StrictLatticeFallback', ...
    ['A count-satisfying but ratio-invalid lattice trial discarded the ' ...
    'strongest valid sub-target deformation.']);
fprintf(['  symmetric remesh applied=%d defect=%.3e ratio=%.3f ' ...
    'amp=%.3g dx=%.3e->%.3e core=%.2f->%.2f counts=%s targets=%s\n'], ...
    symmetricRemeshInfo.applied,symmetricRemeshDefect, ...
    symmetricRemeshInfo.xMaximumCellRatio, ...
    symmetricRemeshInfo.xAmplitude,symmetricRemeshInfo.oldPeakSpacing, ...
    symmetricRemeshInfo.newPeakSpacing, ...
    symmetricRemeshInfo.oldCoreGridPoints, ...
    symmetricRemeshInfo.newCoreGridPoints, ...
    sprintf('%.2f ',symmetricRemeshInfo.xPredictedCounts), ...
    sprintf('%.2f ',symmetricRemeshInfo.xTargetCounts));
assert(symmetricRemeshInfo.applied && symmetricRemeshDefect < 1e-12, ...
    'ipm:SymmetricRemesh', ...
    'Adaptive redistribution did not preserve paired x_1 symmetry.');
assert(all(diff(remeshedOps.x) > 0) && min(abs(remeshedOps.x)) == 0 && ...
    remeshedOps.remeshCount == 1 && remeshInfo.applied && ...
    ~repeatedRemeshInfo.applied && repeatedRemeshOps.remeshCount == 1 && ...
    remeshInfo.newPeakSpacing < remeshInfo.oldPeakSpacing && ...
    remeshRangeViolation <= 10*eps && remeshDerivativeError < 1e-10 && ...
    remeshRowMassError < 1e-11 && ...
    remeshCompoundingError < 10*eps && ...
    proposalGridDefect < 10*eps && proposalBaseDefect < 10*eps && ...
    isequaln(remeshFixtureOpts,remeshFixtureConfigBefore) && ...
    cappedRemeshMinimumSpacing >= cappedRemeshInfo.minimumSpacing-1e-12 && ...
    ~coreRejectInfo.applied && coreRejectOps.remeshCount == 0, ...
    'ipm:AdaptiveRemesh', ...
    'Adaptive redistribution did not preserve its grid/data/operator contracts.');
fprintf(['  physical wall-normal remesh applied=%d, ' ...
    'dy %.3e->%.3e, core %.3f->%.3f, mass/wall %.3e/%.3e, ' ...
    'grad ratio %.3f\n'], ...
    physicalYRemeshInfo.applied, ...
    physicalYRemeshInfo.oldWallSpacing,physicalYRemeshInfo.newWallSpacing, ...
    physicalFlow.verticalCoreGridPoints, ...
    physicalYRemeshFlowNew.verticalCoreGridPoints,physicalRemeshMassError, ...
    physicalRemeshWallError,physicalRemeshGradientRatio);
assert(physicalRateMaximum == 0 && physicalYRemeshInfo.applied && ...
    physicalYRemeshInfo.newWallSpacing < physicalYRemeshInfo.oldWallSpacing && ...
    physicalRemeshMassError < 5e-2 && physicalRemeshWallError < 1e-12 && ...
    physicalRemeshGradientRatio < 2 && ...
    physicalYRemeshFlowNew.verticalCoreGridPoints >= ...
        0.98*physicalFlow.verticalCoreGridPoints, ...
    'ipm:PhysicalAdaptiveRemesh', ...
    'Physical two-axis remeshing or the exact zero-c contract failed.');

fprintf('  remesh peak spacing old/new: %.3e, %.3e\n', ...
    remeshInfo.oldPeakSpacing,remeshInfo.newPeakSpacing);
fprintf('  remesh derivative/range/row-mass errors: %.3e, %.3e, %.3e\n', ...
    remeshDerivativeError,remeshRangeViolation,remeshRowMassError);
fprintf('  repeated-remesh grid change: %.3e\n',remeshCompoundingError);
fprintf('IPM remesh verification passed.\n');
end
