function report = scaling()
%IPMTESTS.BASELINE.SCALING Verify dynamic clocks, gauges, and rescaled assembly.

fprintf('Running IPM scaling verification...\n');
physicalOpts = ipm.config.resolve(struct( ...
    'nx',65,'ny',33,'xlim',[-4,4],'ymax',4, ...
    'rescalingMode','physical','saveResults',false, ...
    'makePlots',false,'verbose',false,'transportBoundaryMode','closed'));
physicalOps = ipm.mesh.build(physicalOpts);
constantRho = 2.5*ones(physicalOps.ny,physicalOps.nx);
[constantRhs,constantFlow] = ipm.evolve.rhs(constantRho,physicalOps);
scalingRate = 0.7;
constantScalingRhs = ipm.field.transport(constantRho, ...
    scalingRate*physicalOps.X,scalingRate*physicalOps.Y, ...
    physicalOps,'open') + 2*scalingRate*constantRho;

peakResolution = ipm.diagnostics.peakResolution([0,0.6,1,0.6,0,0.8,0], ...
    [0,1,2,4,7,11,16],0.5);
profileValues = [-1;0.6;1;0.6;0;0.8;0];
profileAxis = [0,1,2,4,7,11,16];
profileMeasurement = ipm.diagnostics.measureFeatures( ...
    profileValues,profileAxis,0.5,[]);
profileMask = logical([0,0,0,0,1,1,1]);
maskedProfileMeasurement = ipm.diagnostics.measureFeatures( ...
    profileValues,profileAxis,0.5,profileMask);
subgridPeakLocation = ipm.diagnostics.peakLocation(2-([0,1,3]-1.4).^2,[0,1,3],2);
[unlimitedRateMagnitude,normalizedRates] = ...
    ipm.evolve.rateMagnitude([10,8,0],1);

dynamicOpts = ipm.config.resolve(struct('nx',65,'ny',33,'xlim',[-4,4], ...
    'ymax',4,'initialCondition','degenerate','degeneratePower',4, ...
    'symmetryMode','half_plane', ...
    'rescalingMode','dynamic','saveResults',false, ...
    'makePlots',false,'verbose',false));
dynamicOps = ipm.mesh.build(dynamicOpts);
dynamicRho = ipm.field.initialDensity(dynamicOps,dynamicOpts.physics);
dynamicOps = ipm.evolve.initializeScaling(dynamicRho,dynamicOps);
[dynamicRhs,dynamicFlow] = ipm.evolve.rhs(dynamicRho,dynamicOps);
peakPhaseOpts = dynamicOpts;
peakPhaseOpts.scaling.lengthGauge = 'omega_peak_location';
peakPhaseOps = ipm.mesh.build(peakPhaseOpts);
peakPhaseRho = ipm.field.initialDensity( ...
    peakPhaseOps,peakPhaseOpts.physics);
peakPhaseOps = ipm.evolve.initializeScaling(peakPhaseRho,peakPhaseOps);
[~,peakPhaseFlow] = ipm.evolve.rhs(peakPhaseRho,peakPhaseOps);
peakPhaseContract = ipm.evolve.gaugeContract( ...
    peakPhaseOpts,peakPhaseOps);
dynamicScale0 = struct('logC_l',0,'logC_omega',0, ...
    'physicalTime',0,'X_shift',0,'canonicalTime',0);
dynamicState0 = struct('rho',peakPhaseRho,'flow',peakPhaseFlow, ...
    'scale',dynamicScale0,'ops',peakPhaseOps,'config',peakPhaseOpts, ...
    'mass0',sum(peakPhaseRho.*peakPhaseOps.weights,'all'),'rhoRange0', ...
    [min(peakPhaseRho,[],'all'),max(peakPhaseRho,[],'all')], ...
    'normalizedTime',0,'step',0);
[dynamicRecord,~] = ipm.output.record( ...
    ipm.output.initializeLog(),dynamicState0);
peakPhaseHistoryFields = {'peakLocationRhoXX', ...
    'peakLocationRhoXXScale','peakLocationPhaseDefect', ...
    'peakLocationResponseCondition','peakLocationFullPhaseResidual', ...
    'peakLocationNormalizedFullPhaseResidual'};
peakPhaseHistoryComplete = all(isfield( ...
    dynamicRecord.history.gauge,peakPhaseHistoryFields));
dynamicDiagnostics = ipm.diagnostics.measure(dynamicRho,dynamicFlow,dynamicOps, ...
    sum(dynamicRho.*dynamicOps.weights,'all'));

symmetricOpts = dynamicOpts;
symmetricOpts.physics.symmetryMode = 'double_odd_omega';
symmetricOpts.scaling.lengthGauge = 'omega_peak_location';
anchorOpts = symmetricOpts;
anchorOpts.scaling.lengthGauge = 'transport_anchor';
anchorOpts.scaling.transportAnchorX = 1;
anchorOpts.scaling.lengthScaleGain = 1;
anchorOpts.physics.initialCondition = 'degenerate_primitive';
anchorOpts.physics.degeneratePower = 8;
anchorOpts.scaling.cOmegaGauge = 'wall_omega_peak';
anchorOps = ipm.mesh.build(anchorOpts);
anchorRho = ipm.field.initialDensity(anchorOps,anchorOpts.physics);
anchorOps = ipm.evolve.initializeScaling(anchorRho,anchorOps);
[~,anchorFlow] = ipm.evolve.rhs(anchorRho,anchorOps);
anchorCanonicalVelocity = interp1(anchorOps.x,anchorFlow.u1(1,:), ...
    anchorOpts.scaling.transportAnchorX,'linear') + ...
    anchorFlow.canonicalCL*anchorOpts.scaling.transportAnchorX + ...
    anchorFlow.canonicalCR;
anchorCanonicalWallVelocity = anchorFlow.u1(1,:) + ...
    anchorFlow.canonicalCL*anchorOps.x + anchorFlow.canonicalCR;
anchorCanonicalSlope = interp1(anchorOps.x, ...
    anchorCanonicalWallVelocity*anchorOps.Dx', ...
    anchorOpts.scaling.transportAnchorX,'linear');
anchorBoundedVelocity = interp1(anchorOps.x, ...
    anchorFlow.transportU1(1,:),anchorOpts.scaling.transportAnchorX,'linear');
anchorScale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
[~,anchorFlowAfter,anchorScaleAfter] = ipm.evolve.stepSsprk3( ...
    anchorRho,1e-4,anchorOps,anchorScale);
anchorVelocityAfter = interp1(anchorOps.x, ...
    anchorFlowAfter.transportU1(1,:), ...
    anchorOpts.scaling.transportAnchorX,'linear');
anchorSlopeGauge = anchor_wall_gauge_check(anchorOpts);
quadraticPeakGauge = quadratic_peak_gauge_check(anchorOpts);
anchorWindowGauge = anchor_wall_window_check( ...
    anchorOpts,'anchor_wall_window_l2',2);
anchorWindowL4Gauge = anchor_wall_window_check( ...
    anchorOpts,'anchor_wall_window_l4',4);
anchorTemplateGauge = anchor_wall_template_check(anchorOpts);
anchorBulkGauge = anchor_bulk_gradient_check(anchorOpts);
anchorConditionGuarded = anchor_wall_condition_guarded( ...
    anchorOpts,'anchor_wall_slope');
anchorWindowGuarded = anchor_wall_window_l2_guarded(anchorOpts);

widthLengthOpts = dynamicOpts;
widthLengthOpts.scaling.lengthGauge = 'wall_density_width';
widthLengthOps = ipm.mesh.build(widthLengthOpts);
widthLengthRho = ipm.field.initialDensity(widthLengthOps,widthLengthOpts.physics);
widthLengthOps = ipm.evolve.initializeScaling(widthLengthRho,widthLengthOps);
[~,widthLengthFlow] = ipm.evolve.rhs(widthLengthRho,widthLengthOps);
widthLengthContract = ipm.evolve.gaugeContract( ...
    widthLengthOpts,widthLengthOps);

omegaWidthOpts = dynamicOpts;
omegaWidthOpts.scaling.lengthGauge = 'wall_omega_width';
omegaWidthOps = ipm.mesh.build(omegaWidthOpts);
omegaWidthRho = ipm.field.initialDensity(omegaWidthOps,omegaWidthOpts.physics);
omegaWidthOps = ipm.evolve.initializeScaling(omegaWidthRho,omegaWidthOps);
[~,omegaWidthFlow] = ipm.evolve.rhs(omegaWidthRho,omegaWidthOps);
omegaWidthContract = ipm.evolve.gaugeContract( ...
    omegaWidthOpts,omegaWidthOps);

[~,dynamicWallPeakIndex] = max(dynamicFlow.source(1,:));
dynamicPeakLocation = ipm.diagnostics.peakLocation(max(dynamicFlow.source(1,:),0), ...
    dynamicOps.x,dynamicWallPeakIndex);
dynamicPinOffset = dynamicPeakLocation-dynamicOps.rescaling.pinX;

clockScale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
[~,clockFlow,clockScaleNew] = ipm.evolve.stepSsprk3( ...
    dynamicRho,1e-3,dynamicOps,clockScale);

dynamicRhoX = dynamicRho*dynamicOps.Dx';
dynamicRhoY = dynamicOps.Dy*dynamicRho;
dynamicRhsX = dynamicRhs*dynamicOps.Dx';
dynamicRhsY = dynamicOps.Dy*dynamicRhs;
physicalDynamicOps = dynamicOps;
physicalDynamicOps.rescaling.enabled = false;
[expectedPhysicalRhs,~] = ipm.evolve.rhs(dynamicRho,physicalDynamicOps);
dynamicFluxResidual = rescaled_flux_residual(dynamicRhs,dynamicRho, ...
    dynamicFlow,dynamicOps);
shiftedFlow = dynamicFlow;
shiftedFlow.u1 = shiftedFlow.u1+7;
shiftedTracking = ipm.diagnostics.trackFeatures( ...
    dynamicRho,expectedPhysicalRhs,shiftedFlow,dynamicOps);
[shiftedCL,shiftedCOmega,shiftedCR] = ipm.evolve.isotropicGauge( ...
    dynamicRho,expectedPhysicalRhs,shiftedFlow,dynamicOps,shiftedTracking);

diagnosticOnlyTracking = ipm.diagnostics.trackFeatures( ...
    dynamicRho,expectedPhysicalRhs,dynamicFlow,dynamicOps);
[diagnosticCL,diagnosticCOmega,diagnosticCR] = ...
    ipm.evolve.isotropicGauge(dynamicRho,expectedPhysicalRhs, ...
    dynamicFlow,dynamicOps,diagnosticOnlyTracking);
perturbedTracking = diagnosticOnlyTracking;
perturbedTracking.resolutionFactor = 1e9;
perturbedTracking.safetyFactor = 1e9;
perturbedTracking.peakExpansionRatio = 1e9;
[perturbedCL,perturbedCOmega,perturbedCR] = ...
    ipm.evolve.isotropicGauge(dynamicRho,expectedPhysicalRhs, ...
    dynamicFlow,dynamicOps,perturbedTracking);
diagnosticRateIndependenceError = max(abs( ...
    [perturbedCL,perturbedCOmega,perturbedCR] - ...
    [diagnosticCL,diagnosticCOmega,diagnosticCR]));

amplitudeFactor = 3;
translatedRho = interp2(dynamicOps.X,dynamicOps.Y,dynamicRho, ...
    dynamicOps.X-0.1,dynamicOps.Y,'linear',0);
[translatedRhs,translatedFlow] = ipm.evolve.rhs(translatedRho,dynamicOps);
[scaledTranslatedRhs,scaledTranslatedFlow] = ipm.evolve.rhs( ...
    amplitudeFactor*translatedRho,dynamicOps);
amplitudeGaugeRateError = max(abs([ ...
    scaledTranslatedFlow.canonicalCL, ...
    scaledTranslatedFlow.canonicalCOmega, ...
    scaledTranslatedFlow.canonicalCR]-amplitudeFactor*[ ...
    translatedFlow.canonicalCL,translatedFlow.canonicalCOmega, ...
    translatedFlow.canonicalCR]));
amplitudeGaugeRhsError = weighted_l2( ...
    scaledTranslatedRhs/scaledTranslatedFlow.timeSpeed- ...
    amplitudeFactor^2*translatedRhs/translatedFlow.timeSpeed, ...
    dynamicOps) / max(weighted_l2(amplitudeFactor^2* ...
    translatedRhs/translatedFlow.timeSpeed,dynamicOps),eps);

recoveredPhysicalOmegaRate = expectedPhysicalRhs*dynamicOps.Dx';
dynamicPeakIndex = dynamicOps.rescaling.pinIndex;
initialPhysicalOmegaPeakRate = recoveredPhysicalOmegaRate(1,dynamicPeakIndex);
initialRescaledOmegaPeakRate = dynamicRhsX(1,dynamicPeakIndex);
initialReconstructedOmegaPeakRate = initialRescaledOmegaPeakRate + ...
    (dynamicFlow.c_l-dynamicFlow.c_omega)* ...
    dynamicFlow.source(1,dynamicPeakIndex);
dynamicGradientEnergyRate = 2*sum((dynamicRhoX.*dynamicRhsX + ...
    dynamicRhoY.*dynamicRhsY).*dynamicOps.weights,'all');
dynamicGradientEnergy = sum((dynamicRhoX.^2+dynamicRhoY.^2) .* ...
    dynamicOps.weights,'all');
dynamicGradientEnergyRateRelative = dynamicGradientEnergyRate / ...
    max(dynamicGradientEnergy,eps);

energyOpts = dynamicOpts;
energyOpts.scaling.cOmegaGauge = 'gradient_energy';
energyOps = ipm.mesh.build(energyOpts);
energyRho = ipm.field.initialDensity(energyOps,energyOpts.physics);
energyOps = ipm.evolve.initializeScaling(energyRho,energyOps);
[energyRhs,energyFlow] = ipm.evolve.rhs(energyRho,energyOps);
energyRhoX = energyRho*energyOps.Dx';
energyRhoY = energyOps.Dy*energyRho;
energyRhsX = energyRhs*energyOps.Dx';
energyRhsY = energyOps.Dy*energyRhs;
energyBaseRhs = energyRhs-energyFlow.c_omega*energyRho;
energyBaseRhsX = energyBaseRhs*energyOps.Dx';
energyBaseRhsY = energyOps.Dy*energyBaseRhs;
energyWeights = energyOps.integrationWeights;
expectedEnergyComponents = [ ...
    sum(energyRhoX.^2.*energyWeights,'all'), ...
    sum(energyRhoY.^2.*energyWeights,'all')];
expectedForcingComponents = [ ...
    sum(energyRhoX.*energyBaseRhsX.*energyWeights,'all'), ...
    sum(energyRhoY.*energyBaseRhsY.*energyWeights,'all')];
expectedGaugeForcing = sum((energyRhoX.*energyBaseRhsX + ...
    energyRhoY.*energyBaseRhsY).*energyWeights,'all');
expectedAbsoluteForcing = sum(abs(energyRhoX.*energyBaseRhsX + ...
    energyRhoY.*energyBaseRhsY).*energyWeights,'all');
energyGaugeRate = 2*sum((energyRhoX.*energyRhsX + ...
    energyRhoY.*energyRhsY).*energyOps.weights,'all');
energyGaugeRateRelative = energyGaugeRate/max(energyFlow.omegaGaugeEnergy,eps);
energyFluxResidual = rescaled_flux_residual(energyRhs,energyRho, ...
    energyFlow,energyOps);
energyScale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
energyState = struct('rho',energyRho,'flow',energyFlow, ...
    'scale',energyScale,'ops',energyOps,'config',energyOpts, ...
    'mass0',sum(energyRho.*energyWeights,'all'),'rhoRange0', ...
    [min(energyRho,[],'all'),max(energyRho,[],'all')], ...
    'normalizedTime',0,'step',0);
[energyRecord,~] = ipm.output.record( ...
    ipm.output.initializeLog(),energyState);
energyGaugeHistory = energyRecord.history.gauge;
nonfiniteEnergyOps = energyOps;
nonfiniteEnergyOps.integrationWeights(1,1) = Inf;
nonfiniteEnergyGaugeRejected = false;
try
    ipm.evolve.rhs(energyRho,nonfiniteEnergyOps);
catch exception
    nonfiniteEnergyGaugeRejected = strcmp( ...
        exception.identifier,'ipm:DegenerateNormalization') && ...
        contains(exception.message,'not finite');
end

noneOpts = dynamicOpts;
noneOpts.scaling.cOmegaGauge = 'none';
noneOps = ipm.mesh.build(noneOpts);
noneRho = ipm.field.initialDensity(noneOps,noneOpts.physics);
noneOps = ipm.evolve.initializeScaling(noneRho,noneOps);
[noneRhs,noneFlow] = ipm.evolve.rhs(noneRho,noneOps);
noneFluxResidual = rescaled_flux_residual(noneRhs,noneRho,noneFlow,noneOps);
noneCounterfactualCOmega = -noneFlow.omegaGaugeQuadraticForcing / ...
    noneFlow.omegaGaugeQuadraticPeakValue;

legacyOpts = dynamicOpts;
legacyOpts.scaling.cOmegaGauge = 'strain_point';
legacyOps = ipm.mesh.build(legacyOpts);
legacyRho = ipm.field.initialDensity(legacyOps,legacyOpts.physics);
legacyOps = ipm.evolve.initializeScaling(legacyRho,legacyOps);
[legacyRhs,legacyFlow] = ipm.evolve.rhs(legacyRho,legacyOps);
[legacyU1Rate,~] = ipm.field.velocity(legacyRhs,legacyOps);
legacyStrainRate = legacyU1Rate*legacyOps.Dx';
legacyStrainRate = legacyStrainRate(1,legacyOps.rescaling.originIndex);

report.constantStateRhsInf = max(abs(constantRhs),[],'all');
report.constantStateVelocityInf = max( ...
    hypot(constantFlow.u1,constantFlow.u2),[],'all');
report.constantScalingRhsInf = max(abs(constantScalingRhs),[],'all');
report.connectedPeakGridPoints = peakResolution.gridPoints;
report.connectedPeakAreaPoints = peakResolution.areaPoints;
report.connectedPeakWidth = peakResolution.widths;
report.profileMeasurementPeakIndex = profileMeasurement.peakIndex;
report.maskedProfileMeasurementPeakIndex = ...
    maskedProfileMeasurement.peakIndex;
report.subgridPeakLocation = subgridPeakLocation;
report.unlimitedRateMagnitude = unlimitedRateMagnitude;
report.normalizedRates = normalizedRates;
report.dynamicCL = dynamicFlow.c_l;
report.dynamicCLNominal = dynamicFlow.c_lNominal;
report.dynamicCanonicalCLNominal = dynamicFlow.canonicalCLNominal;
report.dynamicLengthScaleGain = dynamicFlow.lengthScaleGain;
report.dynamicWidthCorrection = dynamicFlow.widthCorrection;
report.dynamicWidthRateScale = dynamicFlow.widthRateScale;
report.dynamicWidthControlMode = dynamicFlow.widthControlMode;
report.dynamicPeakGridPoints = dynamicFlow.peakGridPoints;
report.dynamicTargetPeakGridPoints = dynamicFlow.targetPeakGridPoints;
report.dynamicTargetSupportGridPoints = dynamicFlow.targetSupportGridPoints;
report.dynamicTargetCoreGridPoints = dynamicFlow.targetCoreGridPoints;
report.dynamicPeakExpansionRatio = dynamicFlow.peakExpansionRatio;
report.dynamicSafetyFactor = dynamicFlow.safetyFactor;
report.dynamicTrackedWallPeak = dynamicFlow.trackedWallPeak;
report.dynamicTrackedWallPeakWidth = dynamicFlow.trackedWallPeakWidth;
report.transportAnchorCanonicalVelocity = anchorCanonicalVelocity;
report.transportAnchorCanonicalSlope = anchorCanonicalSlope;
report.transportAnchorVelocity = anchorBoundedVelocity;
report.transportAnchorVelocityAfterStep = anchorVelocityAfter;
report.anchorWallSlopeGauge = anchorSlopeGauge;
report.quadraticWallOmegaPeakGauge = quadraticPeakGauge;
report.anchorWallWindowL2Gauge = anchorWindowGauge;
report.anchorWallWindowL4Gauge = anchorWindowL4Gauge;
report.anchorWallTemplateGauge = anchorTemplateGauge;
report.anchorBulkGradientGauge = anchorBulkGauge;
report.anchorWallConditionGuarded = anchorConditionGuarded;
report.anchorWallWindowL2Guarded = anchorWindowGuarded;
report.wallDensityWidthGaugeCL = widthLengthFlow.c_l;
report.wallDensityWidthGaugeResidual = widthLengthFlow.lengthGaugeResidual;
report.wallDensityCrossingConditions = [ ...
    widthLengthFlow.wallDensityLowerCondition, ...
    widthLengthFlow.wallDensityUpperCondition];
report.wallOmegaWidthGaugeCL = omegaWidthFlow.c_l;
report.wallOmegaWidthGaugeResidual = omegaWidthFlow.lengthGaugeResidual;
report.wallOmegaWidthGaugeWidth = omegaWidthFlow.lengthGaugeStrain;
report.dynamicCOmega = dynamicFlow.c_omega;
report.dynamicCR = dynamicFlow.c_r;
report.dynamicCanonicalCL = dynamicFlow.canonicalCL;
report.dynamicCanonicalCOmega = dynamicFlow.canonicalCOmega;
report.dynamicCanonicalCR = dynamicFlow.canonicalCR;
report.dynamicTimeSpeed = dynamicFlow.timeSpeed;
report.dynamicCanonicalRateMagnitude = dynamicFlow.canonicalRateMagnitude;
report.dynamicPinVelocity = dynamicFlow.pinTransportVelocity;
report.dynamicPinGaugeResidual = dynamicFlow.pinGaugeResidual;
report.dynamicPeakTransportVelocity = dynamicFlow.peakTransportVelocity;
report.dynamicTravelingWaveResidual = dynamicFlow.travelingWaveResidual;
report.dynamicTrackedPeakOffset = dynamicFlow.trackedPeakOffset;
report.dynamicLengthGaugeStrain = dynamicFlow.lengthGaugeStrain;
report.dynamicLengthGaugeResidual = dynamicFlow.lengthGaugeResidual;
report.shiftedFrameRates = [shiftedCL,shiftedCOmega,shiftedCR];
report.diagnosticRateIndependenceError = diagnosticRateIndependenceError;
report.amplitudeGaugeRateError = amplitudeGaugeRateError;
report.amplitudeGaugeRhsError = amplitudeGaugeRhsError;
report.dynamicInitialPinOffset = dynamicPinOffset;
report.clockTimeSpeed = clockFlow.timeSpeed;
report.clockCanonicalIncrement = clockScaleNew.canonicalTime;
report.clockPhysicalIncrement = clockScaleNew.physicalTime;
report.dynamicInitialWallPeakWidth = dynamicDiagnostics.wallPeakWidth;
report.dynamicStrainError = dynamicFlow.strainError;
report.dynamicStrainRateResidual = dynamicFlow.strainRateResidual;
report.dynamicStrainCondition = dynamicFlow.strainCondition;
report.dynamicOmegaGaugeEnergy = dynamicFlow.omegaGaugeEnergy;
report.dynamicOmegaGaugeResidual = dynamicFlow.omegaGaugeResidual;
report.dynamicOmegaPeakRateResidual = dynamicFlow.omegaPeakRateResidual;
report.dynamicOmegaGaugePeakX = dynamicFlow.omegaGaugePeakX;
report.dynamicOmegaGaugePeakCondition = dynamicFlow.omegaGaugePeakCondition;
report.dynamicGradientEnergyRateRelative = dynamicGradientEnergyRateRelative;
report.dynamicFluxResidual = dynamicFluxResidual;
report.energyGaugeCOmega = energyFlow.c_omega;
report.energyGaugeResidual = energyFlow.omegaGaugeResidual;
report.energyGaugeGradientRateRelative = energyGaugeRateRelative;
report.energyGaugeEnergyComponents = [energyFlow.omegaGaugeEnergyX, ...
    energyFlow.omegaGaugeEnergyY];
report.energyGaugeForcingComponents = [energyFlow.omegaGaugeForcingX, ...
    energyFlow.omegaGaugeForcingY];
report.energyGaugeForcing = energyFlow.omegaGaugeForcing;
report.energyGaugeAbsoluteForcing = ...
    energyFlow.omegaGaugeAbsoluteForcing;
report.energyGaugeForcingCancellationRatio = ...
    energyFlow.omegaGaugeForcingCancellationRatio;
report.nonfiniteEnergyGaugeRejected = nonfiniteEnergyGaugeRejected;
report.energyFluxResidual = energyFluxResidual;
report.noneGaugeCOmega = noneFlow.c_omega;
report.noneFluxResidual = noneFluxResidual;
report.initialPhysicalOmegaPeakRate = initialPhysicalOmegaPeakRate;
report.initialRescaledOmegaPeakRate = initialRescaledOmegaPeakRate;
report.initialReconstructedOmegaPeakRate = initialReconstructedOmegaPeakRate;
report.dynamicGradientEnergyFractions = [ ...
    dynamicDiagnostics.gradientInnerFraction, ...
    dynamicDiagnostics.gradientNearFraction, ...
    dynamicDiagnostics.gradientOuterFraction];
report.dynamicGradientEffectiveLength = ...
    dynamicDiagnostics.gradientEffectiveLength;
report.legacyPointStrainCOmega = legacyFlow.c_omega;
report.legacyPointStrainCondition = legacyFlow.strainCondition;
report.legacyPointStrainRateResidual = legacyStrainRate;

assert(report.constantStateRhsInf < 1e-12 && ...
    report.constantStateVelocityInf < 1e-12, ...
    'ipm:ConstantState','A constant density must remain at rest.');
assert(report.constantScalingRhsInf < 1e-11, ...
    'ipm:ScalingConstantState', ...
    'Open conservative dilation plus 2*c_l*R did not preserve a constant state.');
assert(abs(peakResolution.gridPoints-7/3) < 1e-13 && ...
    abs(peakResolution.areaPoints-107/60) < 1e-13 && ...
    abs(peakResolution.widths-11/3) < 1e-13, ...
    'ipm:ConnectedPeakResolution', ...
    'Adaptive resolution incorrectly counted a separated secondary peak.');
assert(isequal(profileMeasurement.feature, ...
        [0,0.6,1,0.6,0,0.8,0]) && ...
    isequaln(rmfield(profileMeasurement,'feature'),peakResolution) && ...
    isequal(maskedProfileMeasurement.feature,[0,0,0,0,0,0.8,0]) && ...
    maskedProfileMeasurement.peak == 0.8 && ...
    maskedProfileMeasurement.peakIndex == 6, ...
    'ipm:FeatureMeasurement', ...
    'Feature measurement did not preserve profile clamping or masking.');
assert(abs(subgridPeakLocation-1.4) < 1e-13, ...
    'ipm:SubgridPeakLocation', ...
    'Quadratic subgrid peak localization is inaccurate.');
assert(abs(unlimitedRateMagnitude-10) < 1e-13 && ...
    isequal(normalizedRates,[10;8;0]), ...
    'ipm:RateMagnitude', ...
    'The scaling-rate diagnostic changed the supplied rate vector.');
assert(clockFlow.timeSpeed == 1 && ...
    abs(clockScaleNew.canonicalTime-1e-3) < 10*eps && ...
    clockScaleNew.physicalTime > 0, ...
    'ipm:CanonicalClock', ...
    'The canonical clock is not the unmodified integration clock.');
assert(max(abs([anchorCanonicalVelocity,anchorBoundedVelocity, ...
        anchorVelocityAfter,anchorFlow.canonicalTransportAnchorVelocity, ...
        anchorFlow.transportAnchorVelocity,anchorFlowAfter.canonicalCR, ...
        anchorFlowAfter.c_r,anchorScaleAfter.X_shift])) < 1e-11 && ...
    anchorCanonicalSlope < 0 && ...
    anchorFlow.transportAnchorX == anchorOpts.scaling.transportAnchorX && ...
    anchorFlowAfter.transportAnchorX == ...
        anchorOpts.scaling.transportAnchorX, ...
    'ipm:TransportAnchorGauge', ...
    'The fixed x=1 combined-velocity anchor was not preserved.');
assert(anchorSlopeGauge.formulaError < 1e-12 && ...
    anchorSlopeGauge.rateResidual < 1e-12 && ...
    anchorSlopeGauge.recordedResidualError < 1e-12 && ...
    anchorSlopeGauge.amplitudeRateError < 1e-11 && ...
    anchorSlopeGauge.amplitudeRhsError < 1e-11 && ...
    anchorSlopeGauge.amplitudeNormalizedResidualMagnitude < 1e-12 && ...
    anchorSlopeGauge.amplitudeNormalizedResidualSpread < 1e-12 && ...
    anchorSlopeGauge.shortStepRelativeSlopeDrift < 1e-9 && ...
    anchorSlopeGauge.condition > ...
        anchorOpts.scaling.pointStrainConditionFloor && ...
    anchorSlopeGauge.historyFieldsPresent && ...
    anchorSlopeGauge.referencePreserved && ...
    anchorSlopeGauge.shortStepFinite && anchorConditionGuarded, ...
    'ipm:AnchorWallSlopeGauge', ...
    'The exact anchor-wall slope c_omega gauge regression failed.');
assert(quadraticPeakGauge.formulaError < 1e-12 && ...
    quadraticPeakGauge.rateResidual < 1e-12 && ...
    quadraticPeakGauge.residualReconstructionError < 1e-12 && ...
    quadraticPeakGauge.recordedResidualError < 1e-12 && ...
    quadraticPeakGauge.amplitudeRateError < 1e-11 && ...
    quadraticPeakGauge.amplitudeRhsError < 1e-11 && ...
    quadraticPeakGauge.shortStepRelativePeakDrift < 1e-9 && ...
    quadraticPeakGauge.curvature < 0 && ...
    quadraticPeakGauge.curvatureCondition > 0 && ...
    quadraticPeakGauge.weightCondition > 0 && ...
    quadraticPeakGauge.vertexInteriorFraction > 0 && ...
    quadraticPeakGauge.activeNodeMargin >= 0 && ...
    quadraticPeakGauge.weightSumError < 1e-13 && ...
    quadraticPeakGauge.envelopeDerivativeError < 1e-9 && ...
    quadraticPeakGauge.historyFieldsPresent && ...
    quadraticPeakGauge.finalQualityFieldsPresent && ...
    quadraticPeakGauge.contractRecorded && ...
    quadraticPeakGauge.degenerateCasesRejected && ...
    quadraticPeakGauge.shortStepFinite, ...
    'ipm:QuadraticWallOmegaPeakGauge', ...
    'The exact quadratic wall-omega peak c_omega gauge regression failed.');
assert(anchorWindowGauge.formulaError < 1e-12 && ...
    anchorWindowGauge.rateResidual < 1e-12 && ...
    anchorWindowGauge.residualReconstructionError < 1e-12 && ...
    anchorWindowGauge.recordedResidualError < 1e-12 && ...
    anchorWindowGauge.amplitudeRateError < 1e-11 && ...
    anchorWindowGauge.amplitudeRhsError < 1e-11 && ...
    anchorWindowGauge.amplitudeNormalizedResidualMagnitude < 1e-12 && ...
    anchorWindowGauge.amplitudeNormalizedResidualSpread < 1e-12 && ...
    anchorWindowGauge.shortStepRelativeValueDrift < 1e-9 && ...
    anchorWindowGauge.condition > ...
        anchorOpts.scaling.pointStrainConditionFloor && ...
    anchorWindowGauge.energy > 0 && ...
    anchorWindowGauge.historyFieldsPresent && ...
    anchorWindowGauge.finalQualityFieldsPresent && ...
    anchorWindowGauge.referencePreserved && ...
    anchorWindowGauge.shortStepFinite && anchorWindowGuarded, ...
    'ipm:AnchorWallWindowL2Gauge', ...
    'The fixed anchor-wall window L2 c_omega gauge regression failed.');
assert(anchorWindowL4Gauge.formulaError < 1e-12 && ...
    anchorWindowL4Gauge.rateResidual < 1e-12 && ...
    anchorWindowL4Gauge.residualReconstructionError < 1e-12 && ...
    anchorWindowL4Gauge.recordedResidualError < 1e-12 && ...
    anchorWindowL4Gauge.amplitudeRateError < 1e-11 && ...
    anchorWindowL4Gauge.amplitudeRhsError < 1e-11 && ...
    anchorWindowL4Gauge.momentIdentityError < 1e-12 && ...
    anchorWindowL4Gauge.order == 4 && ...
    anchorWindowL4Gauge.historyFieldsPresent && ...
    anchorWindowL4Gauge.referencePreserved && ...
    anchorWindowL4Gauge.shortStepFinite, ...
    'ipm:AnchorWallWindowL4Gauge', ...
    'The fixed anchor-wall window L4 c_omega gauge regression failed.');
assert(anchorTemplateGauge.formulaError < 1e-12 && ...
    anchorTemplateGauge.normalizedRateResidual < 1e-12 && ...
    anchorTemplateGauge.amplitudeRateError < 1e-11 && ...
    anchorTemplateGauge.amplitudeRhsError < 1e-11 && ...
    anchorTemplateGauge.condition > ...
        anchorOpts.scaling.pointStrainConditionFloor && ...
    anchorTemplateGauge.historyFieldsPresent && ...
    anchorTemplateGauge.referencePreserved && ...
    anchorTemplateGauge.shortStepFinite, ...
    'ipm:AnchorWallTemplateGauge', ...
    'The fixed anchor-wall template projection gauge regression failed.');
assert(anchorBulkGauge.formulaError < 1e-12 && ...
    anchorBulkGauge.normalizedRateResidual < 1e-12 && ...
    anchorBulkGauge.amplitudeRateError < 1e-11 && ...
    anchorBulkGauge.amplitudeRhsError < 1e-11 && ...
    anchorBulkGauge.energyIdentityError < 1e-12 && ...
    anchorBulkGauge.condition > ...
        anchorOpts.scaling.pointStrainConditionFloor && ...
    anchorBulkGauge.historyFieldsPresent && ...
    anchorBulkGauge.referencePreserved && ...
    anchorBulkGauge.shortStepFinite, ...
    'ipm:AnchorBulkGradientGauge', ...
    'The fixed anchor-bulk gradient L2 gauge regression failed.');
assert(all(isfinite([dynamicFlow.c_l,dynamicFlow.c_omega])) && ...
    abs(dynamicFlow.pinGaugeResidual) < 1e-11 && ...
    abs(dynamicFlow.lengthGaugeResidual) < 1e-12 && ...
    abs(dynamicFlow.pinTransportVelocity) < 1e-11 && ...
    abs(dynamicFlow.travelingWaveResidual) < 1e-12 && ...
    dynamicFlow.lengthScaleGain == 1 && ...
    dynamicFlow.widthCorrection == 0 && ...
    dynamicFlow.canonicalWidthCorrection == 0 && ...
    dynamicFlow.widthControlMode == 0 && ...
    abs(dynamicFlow.c_l-dynamicFlow.c_lNominal) < 1e-13 && ...
    abs(dynamicFlow.canonicalCL- ...
        dynamicFlow.canonicalCLNominal) < 1e-13 && ...
    dynamicFlow.timeSpeed == 1 && ...
    abs(dynamicFlow.c_l-dynamicFlow.timeSpeed*dynamicFlow.canonicalCL) ...
        < 1e-13 && ...
    abs(dynamicFlow.c_omega-dynamicFlow.timeSpeed* ...
        dynamicFlow.canonicalCOmega) < 1e-13 && ...
    abs(dynamicFlow.c_r-dynamicFlow.timeSpeed*dynamicFlow.canonicalCR) ...
        < 1e-13 && ...
    abs(dynamicFlow.peakExpansionRatio-1) < 1e-13 && ...
    dynamicFlow.resolutionFactor >= 1 && ...
    dynamicFlow.safetyFactor <= 1 && ...
    abs(dynamicPinOffset) < 1e-13 && ...
    abs(shiftedCL-dynamicFlow.canonicalCL) < 1e-11 && ...
    abs(shiftedCOmega-dynamicFlow.canonicalCOmega) < 1e-11 && ...
    abs(shiftedCR-(dynamicFlow.canonicalCR-7)) < 1e-11 && ...
    diagnosticRateIndependenceError == 0 && ...
    amplitudeGaugeRateError < 1e-10 && amplitudeGaugeRhsError < 1e-11 && ...
    abs(dynamicFlow.trackedWallPeak-dynamicDiagnostics.wallPeak) < 1e-13 && ...
    isfinite(dynamicFlow.trackedWallPeakWidth) && ...
    dynamicFlow.trackedWallPeakWidth > 0 && ...
    isfinite(dynamicDiagnostics.wallPeakWidth) && ...
    dynamicDiagnostics.wallPeakWidth > 0 && ...
    abs(dynamicFlow.strainError) < 1e-11 && ...
    dynamicFlow.omegaGaugeEnergy > 0 && ...
    abs(dynamicFlow.omegaGaugeResidual) < 1e-11 && ...
    abs(dynamicFlow.omegaPeakRateResidual) < 1e-11 && ...
    peakPhaseHistoryComplete && ...
    isfinite(peakPhaseFlow.peakLocationPhaseDefect) && ...
    isfinite(peakPhaseFlow.peakLocationResponseCondition) && ...
    peakPhaseFlow.peakLocationResponseCondition > 0 && ...
    isfinite(peakPhaseFlow.peakLocationNormalizedFullPhaseResidual) && ...
    strcmp(peakPhaseContract.length.evaluation, ...
        'quadratic_R_X_peak_then_linear_Dx_field_interpolation') && ...
    peakPhaseContract.length.registeredParameters. ...
        peakTrackingWidthFactor == ...
        peakPhaseOpts.scaling.peakTrackingWidthFactor && ...
    dynamicDiagnostics.gradientEffectiveLength > 0 && ...
    isfinite(initialPhysicalOmegaPeakRate) && ...
    abs(initialRescaledOmegaPeakRate) < 1e-11 && ...
    isfinite(initialReconstructedOmegaPeakRate) && ...
    all(report.dynamicGradientEnergyFractions >= 0) && ...
    abs(sum(report.dynamicGradientEnergyFractions)-1) < 1e-12, ...
    'ipm:DynamicNormalization', ...
    'Dynamic c_l/c_omega normalization conditions are not satisfied.');
assert(isfinite(widthLengthFlow.c_l) && ...
    abs(widthLengthFlow.lengthGaugeResidual) < 1e-12 && ...
    all([widthLengthFlow.wallDensityLowerSlope, ...
        widthLengthFlow.wallDensityUpperSlope] > 0) && ...
    all(report.wallDensityCrossingConditions > 0) && ...
    strcmp(widthLengthContract.length.evaluation, ...
        'piecewise_linear_level_crossings') && ...
    isequal(widthLengthContract.length.registeredParameters. ...
        lengthGaugeLevels,widthLengthOpts.scaling.lengthGaugeLevels), ...
    'ipm:WallDensityWidthGauge', ...
    'The optional wall-density-width length gauge regression failed.');
assert(isfinite(omegaWidthFlow.c_l) && ...
    abs(omegaWidthFlow.lengthGaugeResidual) < 1e-12 && ...
    omegaWidthFlow.lengthGaugeStrain > 0 && ...
    abs(omegaWidthFlow.trackedWallPeakWidth- ...
        omegaWidthFlow.lengthGaugeStrain) < 1e-13 && ...
    omegaWidthFlow.widthControlMode == 0 && ...
    omegaWidthFlow.widthCorrection == 0 && ...
    abs(omegaWidthFlow.c_l-omegaWidthFlow.c_lNominal) < 1e-13 && ...
    strcmp(omegaWidthContract.length.evaluation, ...
        'piecewise_linear_level_crossings') && ...
    omegaWidthContract.length.registeredParameters.selectedWidthLevel == ...
        max(omegaWidthOpts.scaling.adaptiveLevels), ...
    'ipm:WallOmegaWidthGauge', ...
    'The wall-omega-width length gauge regression failed.');
assert(max([dynamicFluxResidual,energyFluxResidual,noneFluxResidual]) ...
    < 1e-12 && noneFlow.c_omega == 0 && ...
    isfinite(noneCounterfactualCOmega) && ...
    noneFlow.omegaGaugeQuadraticRateResidual == ...
        noneFlow.omegaGaugeQuadraticForcing && ...
    noneFlow.omegaGaugeQuadraticRateScale > 0 && ...
    abs(noneFlow.omegaGaugeQuadraticRateResidual / ...
        noneFlow.omegaGaugeQuadraticRateScale) == 1, ...
    'ipm:RescaledFluxAssembly', ...
    ['The open-boundary rescaled RHS or the identity-gauge independent ' ...
    'quadratic diagnostic is inconsistent.']);
assert(isfinite(energyFlow.c_omega) && ...
    abs(energyFlow.omegaGaugeResidual) < 1e-11 && ...
    abs(energyGaugeRateRelative) < 1e-11 && ...
    max(abs(report.energyGaugeEnergyComponents - ...
        expectedEnergyComponents)) < ...
        64*eps(max(expectedEnergyComponents)) && ...
    max(abs(report.energyGaugeForcingComponents - ...
        expectedForcingComponents)) < ...
        64*eps(max(abs(expectedForcingComponents))) && ...
    abs(report.energyGaugeForcing-expectedGaugeForcing) < ...
        64*eps(max(abs(expectedGaugeForcing),1)) && ...
    abs(energyFlow.omegaGaugeEnergy - ...
        sum(expectedEnergyComponents)) < ...
        64*eps(max(energyFlow.omegaGaugeEnergy,1)) && ...
    abs(energyFlow.omegaGaugeForcing - ...
        sum(expectedForcingComponents)) < ...
        64*eps(max(abs(energyFlow.omegaGaugeForcing),1)) && ...
    abs(energyFlow.omegaGaugeAbsoluteForcing - ...
        expectedAbsoluteForcing) < ...
        64*eps(max(abs(expectedAbsoluteForcing),1)) && ...
    abs(energyFlow.omegaGaugeForcingCancellationRatio - ...
        abs(expectedGaugeForcing)/max(expectedAbsoluteForcing,realmin)) ...
        < 16*eps && ...
    energyFlow.omegaGaugeForcingCancellationRatio >= 0 && ...
    energyFlow.omegaGaugeForcingCancellationRatio <= 1+64*eps && ...
    nonfiniteEnergyGaugeRejected && ...
    all(isfield(energyGaugeHistory,{'omegaGaugeEnergyX', ...
        'omegaGaugeEnergyY','omegaGaugeForcingX', ...
        'omegaGaugeForcingY','omegaGaugeForcing', ...
        'omegaGaugeAbsoluteForcing', ...
        'omegaGaugeForcingCancellationRatio', ...
        'cOmegaOverCL','cLMinusCOmegaOverCL'})) && ...
    abs(energyGaugeHistory.cOmegaOverCL - ...
        energyFlow.c_omega/energyFlow.c_l) < 16*eps && ...
    abs(energyGaugeHistory.cLMinusCOmegaOverCL - ...
        (energyFlow.c_l-energyFlow.c_omega)/energyFlow.c_l) < 16*eps, ...
    'ipm:GradientEnergyGauge', ...
    ['The full-gradient c_omega gauge or its read-only component/rate ' ...
    'diagnostics regressed.']);
assert(isfinite(legacyFlow.c_omega) && ...
    legacyFlow.strainCondition > ...
        legacyOpts.scaling.pointStrainConditionFloor && ...
    abs(legacyFlow.strainRateResidual) < 1e-11 && ...
    abs(legacyStrainRate) < 1e-11, ...
    'ipm:LegacyStrainGauge', ...
    'The explicit legacy point-strain gauge regression failed.');

fprintf('  connected peak grid/area points: %.6f, %.6f\n', ...
    peakResolution.gridPoints,peakResolution.areaPoints);
fprintf(['  dynamic c_l=%.6e (nominal %.6e, width correction %.3g), ' ...
    'c_omega=%.6e, c_r=%.6e\n'], ...
    dynamicFlow.c_l,dynamicFlow.c_lNominal,dynamicFlow.widthCorrection, ...
    dynamicFlow.c_omega,dynamicFlow.c_r);
fprintf(['  canonical c_l/c_omega and time speed: ' ...
    '%.6e, %.6e, %.3e\n'],dynamicFlow.canonicalCL, ...
    dynamicFlow.canonicalCOmega,dynamicFlow.timeSpeed);
fprintf('  pin/gradient-energy gauge residuals: %.3e, %.3e\n', ...
    dynamicFlow.pinGaugeResidual,dynamicFlow.omegaGaugeResidual);
fprintf('  wall-density-width c_l/residual: %.3e, %.3e\n', ...
    widthLengthFlow.c_l,widthLengthFlow.lengthGaugeResidual);
fprintf('  wall-omega-width c_l/residual: %.3e, %.3e\n', ...
    omegaWidthFlow.c_l,omegaWidthFlow.lengthGaugeResidual);
fprintf('  amplitude-gauge rate/RHS covariance errors: %.3e, %.3e\n', ...
    amplitudeGaugeRateError,amplitudeGaugeRhsError);
fprintf('  peak/energy/none rescaled-flux residuals: %.3e, %.3e, %.3e\n', ...
    dynamicFluxResidual,energyFluxResidual,noneFluxResidual);
fprintf('  transport-anchor canonical slope: %.9f\n',anchorCanonicalSlope);
fprintf('  anchor-wall slope residual/condition: %.3e, %.3f\n', ...
    anchorSlopeGauge.rateResidual,anchorSlopeGauge.condition);
fprintf('  quadratic wall-omega peak residual/condition: %.3e, %.3f\n', ...
    quadraticPeakGauge.rateResidual, ...
    quadraticPeakGauge.curvatureCondition);
fprintf(['  anchor-wall window L2 residual/condition: ' ...
    '%.3e, %.3f\n'],anchorWindowGauge.rateResidual, ...
    anchorWindowGauge.condition);
fprintf('IPM scaling verification passed.\n');
end

function check = quadratic_peak_gauge_check(options)
options.scaling.cOmegaGauge = 'wall_omega_quadratic_peak';
options.transport.spatialDiscretization = 'high_order';
options.transport.transportScheme = 'weno5_fd';
options.time.timeIntegrator = 'ssprk54';
options.remesh.remeshTransferScheme = 'high_order';
options.remesh.adaptiveRemesh = false;
ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
[rhs,flow] = ipm.evolve.rhs(rho,ops);

trackingMask = abs(ops.x-ops.rescaling.pinX) <= ...
    ops.rescaling.peakTrackingHalfWidth;
trackedWall = max(flow.source(1,:),0);
trackedWall(~trackingMask) = 0;
[~,peakIndex] = max(trackedWall);
peak = ipm.evolve.quadraticPeakFunctional( ...
    flow.source(1,:),ops.x,peakIndex);
baseRhs = rhs-flow.canonicalCOmega*rho;
baseRhsX = baseRhs*ops.Dx';
forcing = sum(peak.weights.*baseRhsX(1,peak.indices));
expected = -forcing/peak.value;
formulaError = abs(flow.canonicalCOmega-expected);
reconstructedResidual = forcing+flow.canonicalCOmega*peak.value;

amplitudeFactor = 3;
[scaledRhs,scaledFlow] = ipm.evolve.rhs(amplitudeFactor*rho,ops);
amplitudeRateError = max(abs([scaledFlow.canonicalCL, ...
    scaledFlow.canonicalCOmega,scaledFlow.canonicalCR] - ...
    amplitudeFactor*[flow.canonicalCL,flow.canonicalCOmega, ...
    flow.canonicalCR]));
amplitudeRhsError = weighted_l2( ...
    scaledRhs-amplitudeFactor^2*rhs,ops) / ...
    max(weighted_l2(amplitudeFactor^2*rhs,ops),eps);

scale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
stepSize = 1e-5;
[rhoAfter,flowAfter,scaleAfter] = ipm.evolve.stepSsprk54( ...
    rho,stepSize,ops,scale);
state = struct('rho',rhoAfter,'flow',flowAfter,'scale',scaleAfter, ...
    'ops',ops,'config',options,'mass0', ...
    sum(rho.*ops.integrationWeights,'all'),'rhoRange0', ...
    [min(rho,[],'all'),max(rho,[],'all')], ...
    'normalizedTime',stepSize,'step',1);
[recorded,~] = ipm.output.record(ipm.output.initializeLog(),state);
requiredHistory = {'omegaGaugeQuadraticPeakX', ...
    'omegaGaugeQuadraticPeakValue','omegaGaugeQuadraticCurvature', ...
    'omegaGaugeQuadraticCurvatureCondition', ...
    'omegaGaugeQuadraticWeightCondition', ...
    'omegaGaugeQuadraticActiveNodeMargin', ...
    'omegaGaugeQuadraticVertexInteriorFraction', ...
    'omegaGaugeQuadraticRelativeSubgridLift', ...
    'omegaGaugeQuadraticRateResidual','omegaGaugeQuadraticRateScale'};
historyFieldsPresent = all(isfield(recorded.history.gauge,requiredHistory));
quality = ipm.diagnostics.finalQuality(recorded.history);
finalQualityFieldsPresent = ...
    isfield(quality,'omegaGaugeQuadraticPeakValue') && ...
    isfield(quality,'omegaGaugeQuadraticCurvatureCondition') && ...
    isfield(quality,'omegaGaugeQuadraticWeightCondition') && ...
    isfield(quality,'omegaGaugeQuadraticActiveNodeMargin') && ...
    isfield(quality,'omegaGaugeQuadraticVertexInteriorFraction') && ...
    isfield(quality,'omegaGaugeQuadraticRateResidual');
contract = ipm.evolve.gaugeContract(options,ops);
contractRecorded = strcmp(contract.amplitude.name, ...
        'wall_omega_quadratic_peak') && ...
    strcmp(contract.amplitude.observable, ...
        'tracked_wall_omega_quadratic_peak') && ...
    strcmp(contract.amplitude.evaluation, ...
        'active_nonuniform_three_node_quadratic_vertex');
degenerateCasesRejected = ...
    quadratic_peak_rejected([1,0,0],[0,1,2],1) && ...
    quadratic_peak_rejected([0,0,0],[0,1,2],2) && ...
    quadratic_peak_rejected([1,0,1],[0,1,2],2);
syntheticX = [0,1,3];
syntheticValues = 2-(syntheticX-1.4).^2;
syntheticRate = [0.7,-0.2,1.1];
syntheticPeak = ipm.evolve.quadraticPeakFunctional( ...
    syntheticValues,syntheticX,2);
perturbation = 1e-5;
plusPeak = ipm.evolve.quadraticPeakFunctional( ...
    syntheticValues+perturbation*syntheticRate,syntheticX,2);
minusPeak = ipm.evolve.quadraticPeakFunctional( ...
    syntheticValues-perturbation*syntheticRate,syntheticX,2);
finiteDifferenceRate = (plusPeak.value-minusPeak.value)/(2*perturbation);
envelopeDerivativeError = abs(finiteDifferenceRate - ...
    sum(syntheticPeak.weights.*syntheticRate));

check = struct( ...
    'formulaError',formulaError, ...
    'rateResidual',abs(flow.omegaGaugeQuadraticRateResidual), ...
    'residualReconstructionError',abs(reconstructedResidual), ...
    'recordedResidualError',abs( ...
        recorded.history.gauge.omegaGaugeQuadraticRateResidual(end) - ...
        flowAfter.omegaGaugeQuadraticRateResidual), ...
    'amplitudeRateError',amplitudeRateError, ...
    'amplitudeRhsError',amplitudeRhsError, ...
    'shortStepRelativePeakDrift',abs( ...
        flowAfter.omegaGaugeQuadraticPeakValue-peak.value)/peak.value, ...
    'curvature',flow.omegaGaugeQuadraticCurvature, ...
    'curvatureCondition',flow.omegaGaugeQuadraticCurvatureCondition, ...
    'weightCondition',flow.omegaGaugeQuadraticWeightCondition, ...
    'activeNodeMargin',flow.omegaGaugeQuadraticActiveNodeMargin, ...
    'vertexInteriorFraction', ...
        flow.omegaGaugeQuadraticVertexInteriorFraction, ...
    'weightSumError',abs(sum(peak.weights)-1), ...
    'envelopeDerivativeError',envelopeDerivativeError, ...
    'historyFieldsPresent',historyFieldsPresent, ...
    'finalQualityFieldsPresent',finalQualityFieldsPresent, ...
    'contractRecorded',contractRecorded, ...
    'degenerateCasesRejected',degenerateCasesRejected, ...
    'shortStepFinite',all(isfinite(rhoAfter),'all') && ...
        all(cellfun(@(value)isnumeric(value) && isscalar(value) && ...
        isfinite(value),struct2cell(scaleAfter))) && ...
        isfinite(flowAfter.canonicalCOmega));
end

function rejected = quadratic_peak_rejected(values,x,peakIndex)
try
    ipm.evolve.quadraticPeakFunctional(values,x,peakIndex);
catch exception
    rejected = strcmp(exception.identifier,'ipm:DegenerateNormalization');
    return;
end
rejected = false;
end

function check = anchor_wall_gauge_check(options)
options.scaling.cOmegaGauge = 'anchor_wall_slope';
options.transport.spatialDiscretization = 'high_order';
options.transport.transportScheme = 'weno5_fd';
options.time.timeIntegrator = 'ssprk54';
options.remesh.remeshTransferScheme = 'high_order';
options.remesh.adaptiveRemesh = false;
ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
[rhs,flow] = ipm.evolve.rhs(rho,ops);

[formulaError,reconstructedResidual] = ...
    anchor_formula_error(rho,rhs,flow,ops);
reference = ops.rescaling.referenceAnchorWallSlope;

amplitudeFactor = 3;
scaledOps = ops;
scaledOps.rescaling.referenceAnchorWallSlope = ...
    amplitudeFactor*reference;
[scaledRhs,scaledFlow] = ipm.evolve.rhs(amplitudeFactor*rho,scaledOps);
amplitudeRateError = max(abs([scaledFlow.canonicalCL, ...
    scaledFlow.canonicalCOmega,scaledFlow.canonicalCR] - ...
    amplitudeFactor*[flow.canonicalCL,flow.canonicalCOmega, ...
    flow.canonicalCR]));
amplitudeRhsError = weighted_l2( ...
    scaledRhs/scaledFlow.timeSpeed-amplitudeFactor^2* ...
    rhs/flow.timeSpeed,ops) / max(weighted_l2( ...
    amplitudeFactor^2*rhs/flow.timeSpeed,ops),eps);
amplitudeSweep = [1e-3,1,1e3];
normalizedResiduals = zeros(size(amplitudeSweep));
for amplitudeIndex = 1:numel(amplitudeSweep)
    sweepFactor = amplitudeSweep(amplitudeIndex);
    sweepOps = ops;
    sweepOps.rescaling.referenceAnchorWallSlope = ...
        sweepFactor*reference;
    [~,sweepFlow] = ipm.evolve.rhs(sweepFactor*rho,sweepOps);
    normalizedResiduals(amplitudeIndex) = sweepFlow.omegaGaugeResidual;
end
normalizedResidualSpread = max(abs( ...
    normalizedResiduals-normalizedResiduals(2)));
normalizedResidualRelativeSpread = normalizedResidualSpread / ...
    max(abs(normalizedResiduals(2)),100*eps);

scale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
stepSize = 1e-5;
[rhoAfter,flowAfter,scaleAfter] = ipm.evolve.stepSsprk54( ...
    rho,stepSize,ops,scale);
state = struct('rho',rhoAfter,'flow',flowAfter,'scale',scaleAfter, ...
    'ops',ops,'config',options,'mass0', ...
    sum(rho.*ops.integrationWeights,'all'),'rhoRange0', ...
    [min(rho,[],'all'),max(rho,[],'all')], ...
    'normalizedTime',stepSize,'step',1);
[recorded,~] = ipm.output.record(ipm.output.initializeLog(),state);
requiredHistory = {'omegaGaugeAnchorX','omegaGaugeAnchorValue', ...
    'omegaGaugeAnchorCondition','omegaGaugeAnchorRateResidual', ...
    'omegaGaugeReferenceAnchorValue'};
historyFieldsPresent = all(isfield(recorded.history.gauge,requiredHistory));
recordedResidualError = abs( ...
    recorded.history.gauge.omegaGaugeAnchorRateResidual(end) - ...
    flowAfter.omegaGaugeAnchorRateResidual);

check = struct('formulaError',formulaError, ...
    'rateResidual',abs(flow.omegaGaugeAnchorRateResidual), ...
    'residualReconstructionError',abs( ...
        flow.omegaGaugeAnchorRateResidual-reconstructedResidual), ...
    'recordedResidualError',recordedResidualError, ...
    'condition',flow.omegaGaugeAnchorCondition, ...
    'amplitudeRateError',amplitudeRateError, ...
    'amplitudeRhsError',amplitudeRhsError, ...
    'amplitudeNormalizedResidualMagnitude', ...
        max(abs(normalizedResiduals)), ...
    'amplitudeNormalizedResidualSpread',normalizedResidualSpread, ...
    'amplitudeNormalizedResidualRelativeSpread', ...
        normalizedResidualRelativeSpread, ...
    'shortStepRelativeSlopeDrift',abs( ...
        flowAfter.omegaGaugeAnchorValue-reference)/abs(reference), ...
    'historyFieldsPresent',historyFieldsPresent, ...
    'referencePreserved', ...
        flow.omegaGaugeReferenceAnchorValue == reference && ...
        flowAfter.omegaGaugeReferenceAnchorValue == reference && ...
        flow.omegaGaugeAnchorX == ops.rescaling.transportAnchorX, ...
    'shortStepFinite',all(isfinite(rhoAfter),'all') && ...
        all(cellfun(@(value)isnumeric(value) && isscalar(value) && ...
        isfinite(value),struct2cell(scaleAfter))) && ...
        isfinite(flowAfter.canonicalCOmega));
end

function check = anchor_wall_window_check(options,gaugeName,momentOrder)
options.scaling.cOmegaGauge = gaugeName;
options.transport.spatialDiscretization = 'high_order';
options.transport.transportScheme = 'weno5_fd';
options.time.timeIntegrator = 'ssprk54';
options.remesh.remeshTransferScheme = 'high_order';
options.remesh.adaptiveRemesh = false;
ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
[rhs,flow] = ipm.evolve.rhs(rho,ops);

[formulaError,reconstructedResidual] = ...
    window_formula_error(rho,rhs,flow,ops,momentOrder);
reference = ops.rescaling.referenceAnchorWallWindowValue;

amplitudeFactor = 3;
scaledOps = ops;
scaledOps.rescaling.referenceAnchorWallWindowValue = ...
    amplitudeFactor*reference;
[scaledRhs,scaledFlow] = ipm.evolve.rhs(amplitudeFactor*rho,scaledOps);
amplitudeRateError = max(abs([scaledFlow.canonicalCL, ...
    scaledFlow.canonicalCOmega,scaledFlow.canonicalCR] - ...
    amplitudeFactor*[flow.canonicalCL,flow.canonicalCOmega, ...
    flow.canonicalCR]));
amplitudeRhsError = weighted_l2( ...
    scaledRhs-amplitudeFactor^2*rhs,ops) / ...
    max(weighted_l2(amplitudeFactor^2*rhs,ops),eps);
amplitudeSweep = [1e-3,1,1e3];
normalizedResiduals = zeros(size(amplitudeSweep));
for amplitudeIndex = 1:numel(amplitudeSweep)
    sweepFactor = amplitudeSweep(amplitudeIndex);
    sweepOps = ops;
    sweepOps.rescaling.referenceAnchorWallWindowValue = ...
        sweepFactor*reference;
    [~,sweepFlow] = ipm.evolve.rhs(sweepFactor*rho,sweepOps);
    normalizedResiduals(amplitudeIndex) = sweepFlow.omegaGaugeResidual;
end
normalizedResidualSpread = max(abs( ...
    normalizedResiduals-normalizedResiduals(2)));

scale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
stepSize = 1e-5;
[rhoAfter,flowAfter,scaleAfter] = ipm.evolve.stepSsprk54( ...
    rho,stepSize,ops,scale);
state = struct('rho',rhoAfter,'flow',flowAfter,'scale',scaleAfter, ...
    'ops',ops,'config',options,'mass0', ...
    sum(rho.*ops.integrationWeights,'all'),'rhoRange0', ...
    [min(rho,[],'all'),max(rho,[],'all')], ...
    'normalizedTime',stepSize,'step',1);
[recorded,~] = ipm.output.record(ipm.output.initializeLog(),state);
requiredHistory = {'omegaGaugeWindowCenter','omegaGaugeWindowRadius', ...
    'omegaGaugeWindowValue','omegaGaugeWindowCondition', ...
    'omegaGaugeWindowEnergy','omegaGaugeWindowRateResidual', ...
    'omegaGaugeReferenceWindowValue','omegaGaugeWindowMomentOrder', ...
    'omegaGaugeWindowMoment','omegaGaugeWindowSupportPoints', ...
    'omegaGaugeWindowRateScale'};
historyFieldsPresent = all(isfield(recorded.history.gauge,requiredHistory));
quality = ipm.diagnostics.finalQuality(recorded.history);
finalQualityFieldsPresent = ...
    isfield(quality,'omegaGaugeWindowCondition') && ...
    isfield(quality,'omegaGaugeWindowRateResidual') && ...
    quality.omegaGaugeWindowCondition == ...
        flowAfter.omegaGaugeWindowCondition && ...
    quality.omegaGaugeWindowRateResidual == ...
        flowAfter.omegaGaugeWindowRateResidual;
recordedResidualError = abs( ...
    recorded.history.gauge.omegaGaugeWindowRateResidual(end) - ...
    flowAfter.omegaGaugeWindowRateResidual);

check = struct('formulaError',formulaError, ...
    'rateResidual',abs(flow.omegaGaugeWindowRateResidual), ...
    'residualReconstructionError',abs( ...
        flow.omegaGaugeWindowRateResidual-reconstructedResidual), ...
    'recordedResidualError',recordedResidualError, ...
    'condition',flow.omegaGaugeWindowCondition, ...
    'energy',flow.omegaGaugeWindowEnergy, ...
    'order',flow.omegaGaugeWindowMomentOrder, ...
    'momentIdentityError',abs(flow.omegaGaugeWindowMoment- ...
        flow.omegaGaugeWindowValue^momentOrder) / ...
        max(flow.omegaGaugeWindowMoment,realmin), ...
    'amplitudeRateError',amplitudeRateError, ...
    'amplitudeRhsError',amplitudeRhsError, ...
    'amplitudeNormalizedResidualMagnitude', ...
        max(abs(normalizedResiduals)), ...
    'amplitudeNormalizedResidualSpread',normalizedResidualSpread, ...
    'shortStepRelativeValueDrift',abs( ...
        flowAfter.omegaGaugeWindowValue-reference)/reference, ...
    'historyFieldsPresent',historyFieldsPresent, ...
    'finalQualityFieldsPresent',finalQualityFieldsPresent, ...
    'referencePreserved', ...
        flow.omegaGaugeReferenceWindowValue == reference && ...
        flowAfter.omegaGaugeReferenceWindowValue == reference && ...
        flow.omegaGaugeWindowCenter == ops.rescaling.transportAnchorX && ...
        flow.omegaGaugeWindowRadius == ...
            ops.rescaling.omegaGaugeWindowRadius && ...
        flow.omegaGaugeWindowMoment == flow.omegaGaugeEnergy, ...
    'shortStepFinite',all(isfinite(rhoAfter),'all') && ...
        all(cellfun(@(value)isnumeric(value) && isscalar(value) && ...
        isfinite(value),struct2cell(scaleAfter))) && ...
        isfinite(flowAfter.canonicalCOmega));
end

function [formulaError,reconstructedResidual] = ...
        window_formula_error(rho,rhs,flow,ops,momentOrder)
baseRhs = rhs-flow.canonicalCOmega*rho;
baseRhsX = baseRhs*ops.Dx';
window = ipm.evolve.wallWindowMoment( ...
    flow.source(1,:),ops,ops.rescaling,momentOrder);
forcing = sum(window.normalizedWeights .* ...
    flow.source(1,:).^(momentOrder-1).*baseRhsX(1,:));
expected = -forcing/window.moment;
formulaError = abs(flow.canonicalCOmega-expected);
reconstructedResidual = forcing + flow.canonicalCOmega*window.moment;
end

function check = anchor_wall_template_check(options)
options.scaling.cOmegaGauge = 'anchor_wall_template_projection';
options.transport.spatialDiscretization = 'high_order';
options.transport.transportScheme = 'weno5_fd';
options.time.timeIntegrator = 'ssprk54';
options.remesh.remeshTransferScheme = 'high_order';
options.remesh.adaptiveRemesh = false;
ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
[rhs,flow] = ipm.evolve.rhs(rho,ops);

geometry = ipm.evolve.wallWindowGeometry(ops,ops.rescaling);
template = ops.rescaling.referenceAnchorWallTemplate;
baseRhs = rhs-flow.canonicalCOmega*rho;
baseRhsX = baseRhs*ops.Dx';
projection = sum(geometry.normalizedWeights.*flow.source(1,:).*template);
forcing = sum(geometry.normalizedWeights.*baseRhsX(1,:).*template);
expected = -forcing/projection;
formulaError = abs(flow.canonicalCOmega-expected);
normalizedRateResidual = abs(flow.omegaGaugeTemplateRateResidual) / ...
    max(flow.omegaGaugeTemplateRateScale,realmin);
reference = ops.rescaling.referenceAnchorWallTemplateProjection;

amplitudeFactor = 3;
scaledOps = ops;
scaledOps.rescaling.referenceAnchorWallTemplateProjection = ...
    amplitudeFactor*reference;
[scaledRhs,scaledFlow] = ipm.evolve.rhs(amplitudeFactor*rho,scaledOps);
amplitudeRateError = max(abs([scaledFlow.canonicalCL, ...
    scaledFlow.canonicalCOmega,scaledFlow.canonicalCR] - ...
    amplitudeFactor*[flow.canonicalCL,flow.canonicalCOmega, ...
    flow.canonicalCR]));
amplitudeRhsError = weighted_l2( ...
    scaledRhs-amplitudeFactor^2*rhs,ops) / ...
    max(weighted_l2(amplitudeFactor^2*rhs,ops),eps);

scale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
stepSize = 1e-5;
[rhoAfter,flowAfter,scaleAfter] = ipm.evolve.stepSsprk54( ...
    rho,stepSize,ops,scale);
state = struct('rho',rhoAfter,'flow',flowAfter,'scale',scaleAfter, ...
    'ops',ops,'config',options,'mass0', ...
    sum(rho.*ops.integrationWeights,'all'),'rhoRange0', ...
    [min(rho,[],'all'),max(rho,[],'all')], ...
    'normalizedTime',stepSize,'step',1);
[recorded,~] = ipm.output.record(ipm.output.initializeLog(),state);
requiredHistory = {'omegaGaugeTemplateCenter', ...
    'omegaGaugeTemplateRadius','omegaGaugeTemplateSupportPoints', ...
    'omegaGaugeTemplateValue','omegaGaugeTemplateCondition', ...
    'omegaGaugeTemplateRateResidual','omegaGaugeTemplateRateScale', ...
    'omegaGaugeReferenceTemplateValue'};
historyFieldsPresent = all(isfield(recorded.history.gauge,requiredHistory));

check = struct('formulaError',formulaError, ...
    'normalizedRateResidual',normalizedRateResidual, ...
    'residualReconstructionError',abs( ...
        flow.omegaGaugeTemplateRateResidual - ...
        (forcing+flow.canonicalCOmega*projection)), ...
    'condition',flow.omegaGaugeTemplateCondition, ...
    'amplitudeRateError',amplitudeRateError, ...
    'amplitudeRhsError',amplitudeRhsError, ...
    'historyFieldsPresent',historyFieldsPresent, ...
    'referencePreserved', ...
        flow.omegaGaugeReferenceTemplateValue == reference && ...
        flowAfter.omegaGaugeReferenceTemplateValue == reference && ...
        flow.omegaGaugeTemplateValue == projection && ...
        flow.omegaGaugeTemplateSupportPoints == geometry.supportPoints, ...
    'shortStepFinite',all(isfinite(rhoAfter),'all') && ...
        all(cellfun(@(value)isnumeric(value) && isscalar(value) && ...
        isfinite(value),struct2cell(scaleAfter))) && ...
        isfinite(flowAfter.canonicalCOmega));
end

function check = anchor_bulk_gradient_check(options)
options.scaling.cOmegaGauge = 'anchor_bulk_gradient_l2';
options.transport.spatialDiscretization = 'high_order';
options.transport.transportScheme = 'weno5_fd';
options.time.timeIntegrator = 'ssprk54';
options.remesh.remeshTransferScheme = 'high_order';
options.remesh.adaptiveRemesh = false;
ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
[rhs,flow] = ipm.evolve.rhs(rho,ops);

rhoY = ops.Dy*rho;
bulk = ipm.evolve.bulkGradientWindow( ...
    flow.source,rhoY,ops,ops.rescaling);
baseRhs = rhs-flow.canonicalCOmega*rho;
baseRhsX = baseRhs*ops.Dx';
baseRhsY = ops.Dy*baseRhs;
forcing = sum(bulk.normalizedWeights.*( ...
    flow.source.*baseRhsX+rhoY.*baseRhsY),'all');
expected = -forcing/bulk.energy;
formulaError = abs(flow.canonicalCOmega-expected);
normalizedRateResidual = abs(flow.omegaGaugeBulkRateResidual) / ...
    max(flow.omegaGaugeBulkRateScale,realmin);
reference = ops.rescaling.referenceAnchorBulkGradientL2;

amplitudeFactor = 3;
scaledOps = ops;
scaledOps.rescaling.referenceAnchorBulkGradientL2 = ...
    amplitudeFactor*reference;
[scaledRhs,scaledFlow] = ipm.evolve.rhs(amplitudeFactor*rho,scaledOps);
amplitudeRateError = max(abs([scaledFlow.canonicalCL, ...
    scaledFlow.canonicalCOmega,scaledFlow.canonicalCR] - ...
    amplitudeFactor*[flow.canonicalCL,flow.canonicalCOmega, ...
    flow.canonicalCR]));
amplitudeRhsError = weighted_l2( ...
    scaledRhs-amplitudeFactor^2*rhs,ops) / ...
    max(weighted_l2(amplitudeFactor^2*rhs,ops),eps);

scale = struct('logC_l',0,'logC_omega',0,'physicalTime',0, ...
    'X_shift',0,'canonicalTime',0);
stepSize = 1e-5;
[rhoAfter,flowAfter,scaleAfter] = ipm.evolve.stepSsprk54( ...
    rho,stepSize,ops,scale);
state = struct('rho',rhoAfter,'flow',flowAfter,'scale',scaleAfter, ...
    'ops',ops,'config',options,'mass0', ...
    sum(rho.*ops.integrationWeights,'all'),'rhoRange0', ...
    [min(rho,[],'all'),max(rho,[],'all')], ...
    'normalizedTime',stepSize,'step',1);
[recorded,~] = ipm.output.record(ipm.output.initializeLog(),state);
requiredHistory = {'omegaGaugeBulkCenterX','omegaGaugeBulkCenterY', ...
    'omegaGaugeBulkRadius','omegaGaugeBulkSupportPointsX', ...
    'omegaGaugeBulkSupportPointsY','omegaGaugeBulkValue', ...
    'omegaGaugeBulkCondition','omegaGaugeBulkEnergy', ...
    'omegaGaugeBulkRateResidual','omegaGaugeBulkRateScale', ...
    'omegaGaugeReferenceBulkValue'};
historyFieldsPresent = all(isfield(recorded.history.gauge,requiredHistory));

check = struct('formulaError',formulaError, ...
    'normalizedRateResidual',normalizedRateResidual, ...
    'residualReconstructionError',abs( ...
        flow.omegaGaugeBulkRateResidual - ...
        (forcing+flow.canonicalCOmega*bulk.energy)), ...
    'condition',flow.omegaGaugeBulkCondition, ...
    'energyIdentityError',abs(flow.omegaGaugeBulkValue^2- ...
        flow.omegaGaugeBulkEnergy) / ...
        max(flow.omegaGaugeBulkEnergy,realmin), ...
    'amplitudeRateError',amplitudeRateError, ...
    'amplitudeRhsError',amplitudeRhsError, ...
    'historyFieldsPresent',historyFieldsPresent, ...
    'referencePreserved', ...
        flow.omegaGaugeReferenceBulkValue == reference && ...
        flowAfter.omegaGaugeReferenceBulkValue == reference && ...
        flow.omegaGaugeBulkSupportPointsX == bulk.supportPointsX && ...
        flow.omegaGaugeBulkSupportPointsY == bulk.supportPointsY, ...
    'shortStepFinite',all(isfinite(rhoAfter),'all') && ...
        all(cellfun(@(value)isnumeric(value) && isscalar(value) && ...
        isfinite(value),struct2cell(scaleAfter))) && ...
        isfinite(flowAfter.canonicalCOmega));
end

function guarded = anchor_wall_window_l2_guarded(options)
options.scaling.cOmegaGauge = 'anchor_wall_window_l2';
narrowOptions = options;
narrowOptions.scaling.omegaGaugeWindowRadius = 0.01;
supportRejected = window_l2_initialization_rejected( ...
    narrowOptions,'ipm:OmegaGaugeWindowSupport');

ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
try
    ipm.evolve.wallWindowL2(zeros(1,ops.nx),ops,ops.rescaling);
catch exception
    degeneracyRejected = ...
        strcmp(exception.identifier,'ipm:DegenerateNormalization');
    guarded = supportRejected && degeneracyRejected;
    return;
end
guarded = false;
end

function rejected = window_l2_initialization_rejected( ...
        options,expectedIdentifier)
ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
try
    ipm.evolve.initializeScaling(rho,ops);
catch exception
    rejected = strcmp(exception.identifier,expectedIdentifier);
    return;
end
rejected = false;
end

function [formulaError,reconstructedResidual] = ...
        anchor_formula_error(rho,rhs,flow,ops)
baseRhs = rhs/flow.timeSpeed-flow.canonicalCOmega*rho;
baseRhsX = baseRhs*ops.Dx';
samples = interp1(ops.x,[flow.source(1,:);baseRhsX(1,:)]', ...
    ops.rescaling.transportAnchorX,'linear');
anchorValue = samples(1);
anchorForcing = samples(2);
expected = -anchorForcing/anchorValue;
formulaError = abs(flow.canonicalCOmega-expected);
reconstructedResidual = flow.timeSpeed*(anchorForcing + ...
    flow.canonicalCOmega*anchorValue);
end

function guarded = anchor_wall_condition_guarded(options,gaugeName)
options.scaling.cOmegaGauge = gaugeName;
relativeOptions = options;
relativeOptions.scaling.pointStrainConditionFloor = 0.99;
absoluteOptions = options;
absoluteOptions.scaling.cOmegaGaugeFloor = 1;
guarded = anchor_wall_initialization_rejected(relativeOptions) && ...
    anchor_wall_initialization_rejected(absoluteOptions);
end

function rejected = anchor_wall_initialization_rejected(options)
ops = ipm.mesh.build(options);
rho = ipm.field.initialDensity(ops,options.physics);
try
    ipm.evolve.initializeScaling(rho,ops);
catch exception
    rejected = strcmp(exception.identifier,'ipm:DegenerateNormalization');
    return;
end
rejected = false;
end

function residual = rescaled_flux_residual(rhs,rho,flow,ops)
transportU1 = flow.u1+flow.canonicalCL*ops.X+flow.canonicalCR;
transportU2 = flow.u2+flow.canonicalCL*ops.Y;
expected = ipm.field.transport(rho,transportU1,transportU2,ops,'open') + ...
    (2*flow.canonicalCL+flow.canonicalCOmega)*rho;
residual = weighted_l2(rhs/flow.timeSpeed-expected,ops) / ...
    max(weighted_l2(expected,ops),eps);
end

function value = weighted_l2(field,ops)
value = sqrt(sum(field.^2.*ops.weights,'all'));
end
