function report = serverInterface()
%IPMTESTS.BASELINE.SERVERINTERFACE Verify the quadrant release contract.

fprintf('Running quadrant server interface verification...\n');
projectRoot = fileparts(fileparts(which('ipm.solve')));
launcher = fullfile(projectRoot,'server','main_quadrant_release.m');
packager = fullfile(projectRoot,'server','package_quadrant_release.sh');
assert(isfile(launcher) && isfile(packager), ...
    'ipm:QuadrantServerFiles','The production server files are missing.');

launcherText = fileread(launcher);
packagerText = fileread(packager);
releaseName = 'ipm_long_time_server_20260915_v3';
releaseRoot = ['/data/user/hd58131/ipm/',releaseName];
requiredLauncher = { ...
    ['releaseRoot=''',releaseRoot,''';'], ...
    '''quadrantOnly'',true', ...
    '''adaptiveRemesh'',true', ...
    '''canonicalFinalTime'',Inf', ...
    '''maximumSteps'',Inf', ...
    '''rhoXStop'',1000', ...
    '''maxRemeshes'',Inf', ...
    '''maxSteps'',settings.maximumSteps', ...
    'mfilename(''fullpath'')'};
for index = 1:numel(requiredLauncher)
    assert(contains(launcherText,requiredLauncher{index}), ...
        'ipm:QuadrantServerContract', ...
        'The server launcher is missing: %s',requiredLauncher{index});
end
assert(~contains(launcherText,'ipm.config.longTimeProfile(') && ...
    contains(packagerText,['release_name="',releaseName,'"']) && ...
    ~contains(packagerText,'research') && ...
    ~contains(packagerText,'cp -R "$project_root/tests"') && ...
    ~contains(packagerText,'cp -R "$project_root/server"'), ...
    'ipm:QuadrantServerPackage', ...
    'The release must remain quadrant-only and omit repository-only trees.');

report = struct('passed',true,'releaseName',releaseName, ...
    'releaseRoot',releaseRoot,'maximumSteps',Inf,'rhoXStop',1000, ...
    'minimalPackage',true);
fprintf('Quadrant server interface verification passed.\n');
end
