function report = serverInterface()
%IPMTESTS.BASELINE.SERVERINTERFACE Verify the portable long-time interface.

fprintf('Running long-time server interface verification...\n');
outputDirectory = fullfile(tempdir,'ipm_long_time_interface_test');
opts = ipm.config.longTimeProfile(struct( ...
    'outputDirectory',outputDirectory));
config = ipm.config.resolve(opts);

assert(config.grid.nx == 321 && config.grid.ny == 161 && ...
    isequal(config.grid.xlim,[-8,8]) && config.grid.ymax == 4 && ...
    strcmp(config.grid.gridMode,'uniform') && ...
    strcmp(config.transport.spatialDiscretization,'high_order') && ...
    strcmp(config.transport.transportScheme,'weno5_fd') && ...
    strcmp(config.time.timeIntegrator,'ssprk54') && ...
    strcmp(config.remesh.remeshTransferScheme,'high_order') && ...
    config.time.finalTime == 16 && config.time.maxSteps == 60000 && ...
    config.remesh.remeshMaximumCellRatio == 2 && ...
    config.remesh.autonomousMesh.version == 4 && ...
    config.remesh.autonomousMesh.nodeFamily.maximumTotalNodes == 310000 && ...
    strcmp(config.scaling.cOmegaGauge,'outer_wall_density_window_l2') && ...
    config.scaling.omegaGaugeWindowRadius == 0.5 && ...
    config.remesh.autonomousMesh.nodeFamily.maximumAcceptedGrowthTransitions == 3 && ...
    isequal(config.remesh.autonomousMesh.nodeFamily.cellFactors, ...
        [1,1;2,1;1,2;2,2;3,1;1,3;3,2;2,3]) && ...
    ~isfield(config.remesh,'initialMeshObservationFallback') && ...
    strcmp(config.output.resultFile,fullfile(outputDirectory,'result.mat')) && ...
    config.output.checkpoint.enabled && ...
    strcmp(config.output.checkpoint.file, ...
        fullfile(outputDirectory,'checkpoint.mat')), ...
    'ipm:ServerInterfaceDefaults', ...
    'The portable long-time defaults or output paths changed.');

large = ipm.config.resolve(ipm.config.longTimeProfile(struct( ...
    'boxHalfWidth',64,'boxHeight',32, ...
    'canonicalFinalTime',12,'maximumAdjacentGridRatio',1.75, ...
    'outputDirectory',outputDirectory)));
assert(large.remesh.initialMeshObservationFallback.enabled && ...
    large.remesh.autonomousMesh.version == 4 && ...
    large.remesh.remeshMaximumCellRatio == 1.75, ...
    'ipm:ServerInterfaceLargeBox', ...
    'The large-box initial observer or grid-ratio option was not resolved.');
legacyGauge = ipm.config.resolve(ipm.config.longTimeProfile(struct( ...
    'amplitudeGauge','wall_omega_quadratic_peak', ...
    'outputDirectory',outputDirectory)));
assert(strcmp(legacyGauge.scaling.cOmegaGauge, ...
    'wall_omega_quadratic_peak'));

expanded = ipm.config.resolve(ipm.config.longTimeProfile(struct( ...
    'autonomousMeshVersion',5,'maximumTotalNodes',1000000, ...
    'outputDirectory',outputDirectory)));
factors=expanded.remesh.autonomousMesh.nodeFamily.cellFactors;
counts=[320*factors(:,1)+1,160*factors(:,2)+1];
assert(expanded.remesh.autonomousMesh.version==5 && ...
    isequal(expanded.remesh.autonomousMesh.nodeFamily.initialNodeCount,[321,161]) && ...
    size(factors,1)==38 && all(prod(counts,2)<=1000000) && ...
    any(all(factors==[4,2],2)) && ...
    strcmp(expanded.remesh.autonomousMesh.axisSearchPolicy.rankingRule, ...
        'minimax_adjacent_ratio_then_quality_margin_then_schedule_and_y'), ...
    'ipm:ServerInterfaceAutoExpansion', ...
    'Version five did not register the deterministic directional resource ladder.');
expandedBox = ipm.config.resolve(ipm.config.longTimeProfile(struct( ...
    'autonomousMeshVersion',5,'maximumTotalNodes',1000000, ...
    'boxHalfWidth',64,'boxHeight',32, ...
    'outputDirectory',outputDirectory)));
assert(expandedBox.remesh.initialMeshObservationFallback.enabled && ...
    expandedBox.remesh.autonomousMesh.version==5, ...
    'ipm:ServerInterfaceV5LargeBox', ...
    'Version five must preserve the original-zero large-box observation fallback.');
autoH8=ipm.config.longTimeProfile(struct( ...
    'autonomousMeshVersion',5,'initialNodeCount','auto', ...
    'outputDirectory',outputDirectory));
autoH256=ipm.config.longTimeProfile(struct( ...
    'autonomousMeshVersion',5,'initialNodeCount','auto', ...
    'boxHalfWidth',256,'boxHeight',128, ...
    'outputDirectory',outputDirectory));
assert(isequal([autoH8.nx,autoH8.ny],[321,161])&& ...
    isequal([autoH256.nx,autoH256.ny],[401,161])&& ...
    strcmp(autoH256.caseMetadata.initialNodeCountSelection, ...
        'analytic_no_LU_preflight_v1')&& ...
    isequal(autoH256.autonomousMesh.nodeFamily.initialNodeCount,[401,161]), ...
    'ipm:ServerInterfaceAutoInitialNodes', ...
    'The original analytic no-LU preflight did not select the registered H256 grid.');

assert_error(@()ipm.config.longTimeProfile(struct('unknown',1)), ...
    'ipm:BadLongTimeProfileSettings');
assert_error(@()ipm.config.longTimeProfile(struct( ...
    'amplitudeGauge','gradient_energy')), ...
    'ipm:BadLongTimeProfileSettings');
assert_error(@()ipm.config.longTimeProfile(struct('initialNodeCount','auto')), ...
    'ipm:BadLongTimeProfileSettings');
assert_any_error(@()ipm.config.longTimeProfile(struct( ...
    'maximumAdjacentGridRatio',1)),'maximumAdjacentGridRatio');
assert_error(@()ipm.config.longTimeProfile(struct( ...
    'maximumTotalNodes',210000)),'ipm:BadLongTimeProfileSettings');

history.common = struct('physicalRangeViolation',0, ...
    'wallPeakLocalMaxima',1,'wallPeakTVRatio',1, ...
    'positiveWallNegativeRatio',0);
history.mesh = struct('maximumCellRatioX',2, ...
    'maximumCellRatioY',1.5);
flow = struct('safetyFactor',NaN);
diagnostics = struct('gradientStop',1e6, ...
    'rangeStopTolerance',5e-3,'oscillationTVTolerance',1.02, ...
    'positiveWallNegativeTolerance',1e-3);
remesh = struct('remeshMaximumCellRatio',2);
reasonAtTwo = ipm.diagnostics.stopPolicy( ...
    history,1,flow,struct(),diagnostics,remesh);
history.mesh.maximumCellRatioX = 2*(1+2e-10);
reasonAboveTwo = ipm.diagnostics.stopPolicy( ...
    history,1,flow,struct(),diagnostics,remesh);
assert(isempty(reasonAtTwo) && strcmp(reasonAboveTwo, ...
    'grid_smoothness_failure'), ...
    'ipm:ServerInterfaceGridRatioStop', ...
    'The maximum-adjacent-grid-ratio stop boundary changed.');

report = struct('passed',true,'autonomousMeshVersion',4, ...
    'expandedAutonomousMeshVersion',5,'expandedRegisteredLevels',size(factors,1), ...
    'expandedLargeBoxObserverEnabled',true, ...
    'autoInitialH8',[autoH8.nx,autoH8.ny], ...
    'autoInitialH256',[autoH256.nx,autoH256.ny], ...
    'maximumAdjacentGridRatio',2,'boundaryAtTwoContinues',true, ...
    'aboveToleranceStops',true,'largeBoxObserverEnabled',true);
fprintf('Long-time server interface verification passed.\n');
end

function assert_error(action,identifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:ServerInterfaceWrongError', ...
        'Expected %s, received %s.',identifier,exception.identifier);
    return;
end
error('ipm:ServerInterfaceMissingError', ...
    'Expected %s, but no error was raised.',identifier);
end

function assert_any_error(action,messageFragment)
try
    action();
catch exception
    assert(contains(exception.message,messageFragment), ...
        'ipm:ServerInterfaceWrongError', ...
        'Expected an error mentioning %s.',messageFragment);
    return;
end
error('ipm:ServerInterfaceMissingError', ...
    'Expected an error mentioning %s, but no error was raised.',messageFragment);
end
