function report = serverInterface()
%IPMTESTS.BASELINE.SERVERINTERFACE Verify the portable long-time interface.

fprintf('Running long-time server interface verification...\n');
outputDirectory = fullfile(tempdir,'ipm_long_time_interface_test');
opts = ipm.config.longTimeProfile(struct( ...
    'outputDirectory',outputDirectory));
config = ipm.config.resolve(opts);

assert(config.grid.nx == 321 && config.grid.ny == 161 && ...
    isequal(config.grid.xlim,[-8,8]) && config.grid.ymax == 4 && ...
    strcmp(config.grid.gridMode,'uniform') && ...
    strcmp(config.transport.spatialDiscretization,'high_order') && ...
    strcmp(config.transport.transportScheme,'weno5_fd') && ...
    strcmp(config.time.timeIntegrator,'ssprk54') && ...
    strcmp(config.remesh.remeshTransferScheme,'high_order') && ...
    config.time.finalTime == 16 && config.time.maxSteps == 60000 && ...
    config.remesh.remeshMaximumCellRatio == 2 && ...
    config.remesh.autonomousMesh.version == 4 && ...
    config.remesh.autonomousMesh.nodeFamily.maximumTotalNodes == 310000 && ...
    config.remesh.autonomousMesh.nodeFamily.maximumAcceptedGrowthTransitions == 3 && ...
    isequal(config.remesh.autonomousMesh.nodeFamily.cellFactors, ...
        [1,1;2,1;1,2;2,2;3,1;1,3;3,2;2,3]) && ...
    ~isfield(config.remesh,'initialMeshObservationFallback') && ...
    strcmp(config.output.resultFile,fullfile(outputDirectory,'result.mat')) && ...
    config.output.checkpoint.enabled && ...
    strcmp(config.output.checkpoint.file, ...
        fullfile(outputDirectory,'checkpoint.mat')), ...
    'ipm:ServerInterfaceDefaults', ...
    'The portable long-time defaults or output paths changed.');

large = ipm.config.resolve(ipm.config.longTimeProfile(struct( ...
    'boxHalfWidth',64,'boxHeight',32, ...
    'canonicalFinalTime',12,'maximumAdjacentGridRatio',1.75, ...
    'outputDirectory',outputDirectory)));
assert(large.remesh.initialMeshObservationFallback.enabled && ...
    large.remesh.autonomousMesh.version == 4 && ...
    large.remesh.remeshMaximumCellRatio == 1.75, ...
    'ipm:ServerInterfaceLargeBox', ...
    'The large-box initial observer or grid-ratio option was not resolved.');

assert_error(@()ipm.config.longTimeProfile(struct('unknown',1)), ...
    'ipm:BadLongTimeProfileSettings');
assert_any_error(@()ipm.config.longTimeProfile(struct( ...
    'maximumAdjacentGridRatio',1)),'maximumAdjacentGridRatio');
assert_error(@()ipm.config.longTimeProfile(struct( ...
    'maximumTotalNodes',210000)),'ipm:BadLongTimeProfileSettings');

history.common = struct('physicalRangeViolation',0, ...
    'wallPeakLocalMaxima',1,'wallPeakTVRatio',1, ...
    'positiveWallNegativeRatio',0);
history.mesh = struct('maximumCellRatioX',2, ...
    'maximumCellRatioY',1.5);
flow = struct('safetyFactor',NaN);
diagnostics = struct('gradientStop',1e6, ...
    'rangeStopTolerance',5e-3,'oscillationTVTolerance',1.02, ...
    'positiveWallNegativeTolerance',1e-3);
remesh = struct('remeshMaximumCellRatio',2);
reasonAtTwo = ipm.diagnostics.stopPolicy( ...
    history,1,flow,struct(),diagnostics,remesh);
history.mesh.maximumCellRatioX = 2*(1+2e-10);
reasonAboveTwo = ipm.diagnostics.stopPolicy( ...
    history,1,flow,struct(),diagnostics,remesh);
assert(isempty(reasonAtTwo) && strcmp(reasonAboveTwo, ...
    'grid_smoothness_failure'), ...
    'ipm:ServerInterfaceGridRatioStop', ...
    'The maximum-adjacent-grid-ratio stop boundary changed.');

report = struct('passed',true,'autonomousMeshVersion',4, ...
    'maximumAdjacentGridRatio',2,'boundaryAtTwoContinues',true, ...
    'aboveToleranceStops',true,'largeBoxObserverEnabled',true);
fprintf('Long-time server interface verification passed.\n');
end

function assert_error(action,identifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:ServerInterfaceWrongError', ...
        'Expected %s, received %s.',identifier,exception.identifier);
    return;
end
error('ipm:ServerInterfaceMissingError', ...
    'Expected %s, but no error was raised.',identifier);
end

function assert_any_error(action,messageFragment)
try
    action();
catch exception
    assert(contains(exception.message,messageFragment), ...
        'ipm:ServerInterfaceWrongError', ...
        'Expected an error mentioning %s.',messageFragment);
    return;
end
error('ipm:ServerInterfaceMissingError', ...
    'Expected an error mentioning %s, but no error was raised.',messageFragment);
end
