function report = smoke()
%IPMTESTS.BASELINE.SMOKE Five solver modes plus two physical-mode edge cases.
%   The checks use in-code invariants instead of binary reference files.

physicalOptions = short_options();
physicalOptions.rescalingMode = 'physical';
physicalOptions.symmetryMode = 'double_odd_omega';
physicalResult = ipm.solve(physicalOptions);
assert_result_contract(physicalResult,'isotropic');
assert_contract_rejections(physicalResult);
assert_completed(physicalResult,physicalOptions.physicalFinalTime, ...
    'ipm:SmokePhysicalCompletion');
physicalSymmetryDefect = even_defect(physicalResult.state.rho);
assert(physicalResult.scale.Cx == 1 && physicalResult.scale.Cy == 1 && ...
    physicalResult.scale.Comega == 1 && ...
    max(abs([physicalResult.scale.rates.cx, ...
        physicalResult.scale.rates.cy,physicalResult.scale.rates.comega, ...
        physicalResult.scale.rates.cr])) == 0, ...
    'ipm:SmokePhysicalScaling', ...
    'Physical smoke mode acquired a nonzero rescaling rate or scale.');
assert(physicalSymmetryDefect < 1e-11 && ...
    physicalResult.history.common.physicalRangeViolation(end) < 1e-4, ...
    'ipm:SmokePhysicalInvariant', ...
    'Physical smoke mode lost even symmetry or its density range.');

activeOptions = overlay_options(ipm.config.activeCase(),short_options());
activeOptions.initialCondition = 'degenerate_primitive';
activeOptions.degeneratePower = 8;
activeOptions.transportScheme = 'weno5_nonuniform';
activeResult = ipm.solve(activeOptions);
assert_result_contract(activeResult,'isotropic');
assert_completed(activeResult,activeOptions.physicalFinalTime, ...
    'ipm:SmokeActiveCompletion');
activeSymmetryDefect = even_defect(activeResult.state.rho);
activeAnchorResidual = max(abs( ...
    activeResult.history.gauge.canonicalTransportAnchorVelocity));
activeAmplitudeResidual = max(abs( ...
    activeResult.history.gauge.omegaGaugeResidual));
assert(strcmp(activeResult.config.physics.initialCondition, ...
        'degenerate_primitive') && ...
    activeResult.config.physics.degeneratePower == 8 && ...
    strcmp(activeResult.config.scaling.lengthGauge,'transport_anchor') && ...
    strcmp(activeResult.config.scaling.cOmegaGauge,'wall_omega_peak') && ...
    strcmp(activeResult.config.transport.transportScheme, ...
        'weno5_nonuniform'), ...
    'ipm:SmokeActiveContract', ...
    'The short active run no longer uses the maintained isotropic gauges.');
assert(activeResult.scale.Cx == activeResult.scale.Cy && ...
    activeResult.scale.aspect == 1 && ...
    activeSymmetryDefect < 1e-10 && activeAnchorResidual < 1e-10 && ...
    activeAmplitudeResidual < 1e-9 && ...
    all(isfinite([activeResult.scale.rates.cx, ...
        activeResult.scale.rates.cy,activeResult.scale.rates.comega, ...
        activeResult.scale.rates.cr])), ...
    'ipm:SmokeActiveInvariant', ...
    'The active isotropic smoke run lost its scale, symmetry, or gauge invariant.');

halfPlaneOptions = short_options();
halfPlaneOptions.rescalingMode = 'dynamic';
halfPlaneOptions.symmetryMode = 'half_plane';
halfPlaneOptions.lengthGauge = 'local_strain';
halfPlaneOptions.cOmegaGauge = 'wall_omega_peak';
halfPlaneResult = ipm.solve(halfPlaneOptions);
assert_result_contract(halfPlaneResult,'isotropic');
assert_completed(halfPlaneResult,halfPlaneOptions.physicalFinalTime, ...
    'ipm:SmokeHalfPlaneCompletion');
comparison = ipm.output.compare( ...
    halfPlaneResult,halfPlaneResult,[-1.5,1.5,1.5]);
assert(comparison.rhoRelativeL2 < 1e-13 && ...
    comparison.omegaRelativeL2 < 1e-13 && ...
    comparison.rhoAbsoluteInf < 1e-13 && ...
    comparison.omegaAbsoluteInf < 1e-13 && ...
    comparison.labPeakShift == 0 && ...
    all(isfinite([halfPlaneResult.scale.rates.cx, ...
        halfPlaneResult.scale.rates.cy, ...
        halfPlaneResult.scale.rates.comega, ...
        halfPlaneResult.scale.rates.cr])), ...
    'ipm:SmokeHalfPlaneComparison', ...
    'The half-plane run failed its peak-aligned self-comparison contract.');

anisotropicOptions = short_options();
anisotropicOptions.rescalingMode = 'dynamic';
anisotropicOptions.dynamicScaleGeometry = 'anisotropic';
anisotropicOptions.symmetryMode = 'half_plane';
anisotropicOptions.anisotropicGaugeMode = 'fixed';
anisotropicOptions.anisotropicFixedCX = 0.07;
anisotropicOptions.anisotropicFixedCY = -0.03;
anisotropicOptions.anisotropicFixedCOmega = 0.02;
anisotropicOptions.anisotropicFixedCR = 0.01;
anisotropicResult = ipm.solve(anisotropicOptions);
assert_result_contract(anisotropicResult,'anisotropic');
assert_completed(anisotropicResult,anisotropicOptions.physicalFinalTime, ...
    'ipm:SmokeAnisotropicCompletion');
expectedLogCx = anisotropicOptions.anisotropicFixedCX* ...
    anisotropicResult.state.canonicalTime;
expectedLogCy = anisotropicOptions.anisotropicFixedCY* ...
    anisotropicResult.state.canonicalTime;
expectedLogCOmega = anisotropicOptions.anisotropicFixedCOmega* ...
    anisotropicResult.state.canonicalTime;
anisotropicScaleError = max(abs([ ...
    log(anisotropicResult.scale.Cx)-expectedLogCx, ...
    log(anisotropicResult.scale.Cy)-expectedLogCy, ...
    log(anisotropicResult.scale.Comega)-expectedLogCOmega]));
expectedSource = anisotropicOptions.anisotropicFixedCX + ...
    anisotropicOptions.anisotropicFixedCY + ...
    anisotropicOptions.anisotropicFixedCOmega;
anisotropicSourceError = abs( ...
    anisotropicResult.scale.canonicalConservativeSource-expectedSource);
assert(abs(anisotropicResult.scale.canonicalRates.cx- ...
        anisotropicOptions.anisotropicFixedCX) < 1e-14 && ...
    abs(anisotropicResult.scale.canonicalRates.cy- ...
        anisotropicOptions.anisotropicFixedCY) < 1e-14 && ...
    abs(anisotropicResult.scale.canonicalRates.comega- ...
        anisotropicOptions.anisotropicFixedCOmega) < 1e-14 && ...
    abs(anisotropicResult.scale.canonicalRates.cr- ...
        anisotropicOptions.anisotropicFixedCR) < 1e-14 && ...
    anisotropicScaleError < 1e-12 && anisotropicSourceError < 1e-14 && ...
    abs(anisotropicResult.scale.aspect-1) > 1e-8 && ...
    abs(anisotropicResult.elliptic.solveInfo.kappa- ...
        anisotropicResult.scale.aspect) < 1e-12, ...
    'ipm:SmokeAnisotropicFixed', ...
    'The fixed anisotropic mode lost its rate, scale, source, or metric contract.');

peakTranslationOptions = short_options();
peakTranslationOptions.rescalingMode = 'dynamic';
peakTranslationOptions.dynamicScaleGeometry = 'anisotropic';
peakTranslationOptions.symmetryMode = 'half_plane';
peakTranslationOptions.anisotropicGaugeMode = 'peak_translation';
peakTranslationOptions.anisotropicFixedCX = 0.07;
peakTranslationOptions.anisotropicFixedCY = -0.03;
peakTranslationOptions.anisotropicFixedCOmega = 0.02;
peakTranslationResult = ipm.solve(peakTranslationOptions);
assert_result_contract(peakTranslationResult,'anisotropic');
assert_completed(peakTranslationResult, ...
    peakTranslationOptions.physicalFinalTime, ...
    'ipm:SmokePeakTranslationCompletion');
peakTranslationResidual = max(abs( ...
    peakTranslationResult.history.anisotropic.peakTranslationResidual));
assert(all(isfinite([peakTranslationResult.scale.rates.cx, ...
        peakTranslationResult.scale.rates.cy, ...
        peakTranslationResult.scale.rates.comega, ...
        peakTranslationResult.scale.rates.cr])) && ...
    abs(peakTranslationResult.scale.aspect-1) > 1e-8 && ...
    peakTranslationResidual < 1e-10 && ...
    all(peakTranslationResult.history.anisotropic.anisotropicGaugeMode == ...
        "peak_translation"), ...
    'ipm:SmokePeakTranslationGauge', ...
    'The peak-translation run lost its finite rates, aspect, mode, or gauge.');

asymmetricOptions = short_options();
asymmetricOptions.rescalingMode = 'physical';
asymmetricOptions.symmetryMode = 'half_plane';
asymmetricOptions.nx = 32;
asymmetricOptions.xlim = [-3.5,4.5];
asymmetricOptions.gridMode = 'uniform';
asymmetricOptions.gridStretch = [0,0];
asymmetricResult = ipm.solve(asymmetricOptions);
assert_result_contract(asymmetricResult,'isotropic');
assert_completed(asymmetricResult,asymmetricOptions.physicalFinalTime, ...
    'ipm:SmokeAsymmetricPhysicalCompletion');
assert(min(abs(asymmetricResult.grid.x)) > ...
        100*eps(max(abs(asymmetricResult.grid.x))) && ...
    all(isfinite(asymmetricResult.state.rho),'all'), ...
    'ipm:SmokeAsymmetricPhysicalGrid', ...
    'Physical mode still depends on an exact origin grid point.');

constantOptions = asymmetricOptions;
constantOptions.initialCondition = @(x,y) ones(size(x))+0*y;
constantOptions.adaptiveRemesh = true;
constantOptions.initialAnalyticRemesh = true;
constantResult = ipm.solve(constantOptions);
assert_result_contract(constantResult,'isotropic');
assert_completed(constantResult,constantOptions.physicalFinalTime, ...
    'ipm:SmokeConstantPhysicalCompletion');
assert(max(abs(constantResult.state.omega),[],'all') < 1e-12 && ...
    constantResult.grid.remeshCount == 0 && ...
    ~isfield(constantResult.history.mesh,'safetyFactor') && ...
    ~isfield(constantResult.quality,'safetyFactor') && ...
    ~isfield(constantResult.quality,'horizontalCorePoints'), ...
    'ipm:SmokeConstantPhysicalGaugeIndependence', ...
    'A peak-free physical run acquired a required gauge contract.');

report = struct( ...
    'physical',run_summary(physicalResult,physicalSymmetryDefect), ...
    'activeIsotropicDynamic',run_summary( ...
        activeResult,activeSymmetryDefect), ...
    'halfPlaneComparison',struct( ...
        'run',run_summary(halfPlaneResult,NaN),'comparison',comparison), ...
    'anisotropicFixed',struct( ...
        'run',run_summary(anisotropicResult,NaN), ...
        'scaleError',anisotropicScaleError, ...
        'sourceError',anisotropicSourceError), ...
    'anisotropicPeakTranslation',struct( ...
        'run',run_summary(peakTranslationResult,NaN), ...
        'residual',peakTranslationResidual), ...
    'asymmetricPhysical',run_summary(asymmetricResult,NaN), ...
    'constantPhysical',run_summary(constantResult,NaN));
report.activeIsotropicDynamic.anchorResidual = activeAnchorResidual;
report.activeIsotropicDynamic.amplitudeResidual = activeAmplitudeResidual;
fprintf(['IPM smoke verification passed: steps physical/active/half-plane/' ...
    'anisotropic-fixed/peak-translation = %d/%d/%d/%d/%d.\n'], ...
    physicalResult.state.steps,activeResult.state.steps, ...
    halfPlaneResult.state.steps,anisotropicResult.state.steps, ...
    peakTranslationResult.state.steps);
fprintf('  physical edge steps asymmetric/peak-free = %d/%d.\n', ...
    asymmetricResult.state.steps,constantResult.state.steps);
end

function opts = short_options()
opts = struct( ...
    'nx',33,'ny',17,'xlim',[-4,4],'ymax',4, ...
    'gridMode','stretched','gridStretch',[1.5,1.5], ...
    'gridStretchAutomatic',false,'targetCenterSpacing',[0.1,0.1], ...
    'initialCondition','degenerate','degeneratePower',4, ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','open','transportScheme','muscl_minmod', ...
    'physicalFinalTime',2e-4,'maxDt',1e-4,'minDt',1e-12, ...
    'maxSteps',8,'outputEvery',1e-4,'cfl',0.25, ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'gradientStop',1e9,'rangeStopTolerance',0.1, ...
    'oscillationTVTolerance',10, ...
    'positiveWallNegativeTolerance',0.99, ...
    'storeSnapshots',true,'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
end

function opts = overlay_options(opts,overrides)
names = fieldnames(overrides);
for index = 1:numel(names)
    opts.(names{index}) = overrides.(names{index});
end
end

function assert_completed(result,targetTime,identifier)
tolerance = 100*eps(max([1,abs(targetTime), ...
    abs(result.state.physicalTime)]));
assert(strcmp(result.state.stopReason,'physical_final_time') && ...
    result.state.steps >= 1 && ...
    abs(result.state.physicalTime-targetTime) <= tolerance, ...
    identifier,'The short run did not reach its requested physical time.');
end

function assert_result_contract(result,geometry)
validated = ipm.output.validate(result);
required = {'metadata','state','grid','scale','physical','history', ...
    'quality','fit','config','elliptic','snapshots'};
assert(validated.schemaVersion == 2 && ...
    isequaln(validated,result) && ...
    validated.config.schemaVersion == 4 && ...
    strcmp(validated.config.transport.spatialDiscretization, ...
        'legacy_second_order') && ...
    strcmp(validated.config.time.timeIntegrator,'ssprk3') && ...
    strcmp(validated.config.remesh.remeshTransferScheme,'pchip') && ...
    all(isfield(result,required)) && ...
    strcmp(result.scale.geometry,geometry) && ...
    all(isfield(result.history, ...
        {'common','gauge','mesh','anisotropic'})), ...
    'ipm:SmokeResultContract', ...
    'A short run no longer returns the common result contract.');
if strcmp(geometry,'anisotropic')
    assert(isfield(validated.history.anisotropic, ...
        'anisotropicGaugeMode') && isequal( ...
        validated.history.anisotropic.anisotropicGaugeMode, ...
        result.history.anisotropic.anisotropicGaugeMode), ...
        'ipm:SmokeAnisotropicHistoryContract', ...
        'The anisotropic gauge mode is missing from grouped history.');
end
expectedSize = [numel(result.grid.y),numel(result.grid.x)];
fields = {result.state.rho,result.state.psi,result.state.omega, ...
    result.state.velocity.x,result.state.velocity.y,result.physical.rho, ...
    result.physical.omega,result.physical.u1,result.physical.u2};
for index = 1:numel(fields)
    value = fields{index};
    assert(isequal(size(value),expectedSize) && all(isfinite(value),'all'), ...
        'ipm:SmokeFiniteField', ...
        'A short run returned a non-finite or incorrectly sized field.');
end
assert(~isempty(result.history.common.physicalTime) && ...
    result.history.common.physicalTime(end) == result.state.physicalTime && ...
    result.history.common.canonicalTau(end) == result.state.canonicalTime && ...
    numel(result.snapshots.rho) == numel(result.snapshots.x) && ...
    numel(result.snapshots.rho) == numel(result.snapshots.y) && ...
    (strcmp(geometry,'anisotropic') || ...
        isempty(fieldnames(result.history.anisotropic))), ...
    'ipm:SmokeHistoryContract', ...
    'A short run lost its terminal history or snapshot-grid metadata.');
trusted = ipm.output.trustedMask(result);
snapshots = ipm.output.snapshotAt(result,'all');
assert(numel(trusted) == numel(result.history.common.physicalTime) && ...
    numel(snapshots) == max(numel(result.snapshots.rho),1), ...
    'ipm:SmokeAnalysisContract', ...
    'Shared validation, trust, or snapshot adapters lost result alignment.');
end

function assert_contract_rejections(result)
withoutSnapshots = result;
withoutSnapshots.snapshots = struct('rho',{{}}, ...
    'normalizedTime',[],'physicalTime',[],'canonicalTime',[], ...
    'x',{{}},'y',{{}});
withoutSnapshots = ipm.output.validate(withoutSnapshots);
terminal = ipm.output.snapshotAt(withoutSnapshots);
assert(isequal(terminal.rho,result.state.rho), ...
    'ipm:SmokeTerminalSnapshot', ...
    'A result without stored snapshots lost its terminal-state fallback.');

missingVersion = rmfield(result,'schemaVersion');
schemaOne = result;
schemaOne.schemaVersion = 1;
schemaThree = result;
schemaThree.schemaVersion = 3;
assert_schema_rejected(@() ipm.output.validate(missingVersion));
assert_schema_rejected(@() ipm.output.validate(schemaOne));
assert_schema_rejected(@() ipm.output.validate(schemaThree));
legacyLike = struct('rho',result.state.rho,'opts',struct(), ...
    'history',struct(),'physicalTime',result.state.physicalTime);
assert_schema_rejected(@() ipm.output.compare(legacyLike,legacyLike));

duplicate = result;
duplicate.history.gauge.t = duplicate.history.common.t;
assert_throws(@() ipm.output.validate(duplicate), ...
    'ipm:HistoryDuplicateField');

mispaired = result;
mispaired.snapshots.x{1} = mispaired.snapshots.x{1}(1:end-1);
assert_throws(@() ipm.output.validate(mispaired), ...
    'ipm:ResultSnapshotSize');

misalignedHistory = result.history;
misalignedHistory.mesh.safetyFactor = ...
    misalignedHistory.mesh.safetyFactor(1:end-1);
assert_throws(@() ipm.output.trustedMask(misalignedHistory,result.config), ...
    'ipm:TrustedMaskLength');

flatHistory = result;
flatHistory.history = result.history.common;
assert_throws(@() ipm.output.validate(flatHistory), ...
    'ipm:ResultMissingField');

flatConfig = result;
flatConfig.config = struct( ...
    'rescalingMode',result.config.scaling.rescalingMode);
assert_throws(@() ipm.output.validate(flatConfig),'ipm:ResultConfig');
end

function assert_schema_rejected(action)
try
    action();
catch exception
    assert(strcmp(exception.identifier,'ipm:ResultSchemaVersion') && ...
        contains(exception.message,'schemaVersion=2'), ...
        'ipm:SmokeSchemaError', ...
        'Expected a clear schemaVersion=2 rejection, received %s: %s.', ...
        exception.identifier,exception.message);
    return;
end
error('ipm:SmokeSchemaAcceptance', ...
    'A legacy, unversioned, or unsupported result schema was accepted.');
end

function assert_throws(action,identifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:SmokeUnexpectedError', ...
        'Expected %s but received %s.',identifier,exception.identifier);
    return;
end
error('ipm:SmokeMissingError','Expected error %s was not raised.',identifier);
end

function value = even_defect(field)
value = max(abs(field-fliplr(field)),[],'all');
end

function summary = run_summary(result,symmetryDefect)
summary = struct('steps',result.state.steps, ...
    'stopReason',result.state.stopReason, ...
    'physicalTime',result.state.physicalTime, ...
    'canonicalTau',result.state.canonicalTime, ...
    'C_x',result.scale.Cx,'C_y',result.scale.Cy, ...
    'C_omega',result.scale.Comega,'aspect',result.scale.aspect, ...
    'remeshCount',result.grid.remeshCount, ...
    'rangeViolation',result.history.common.physicalRangeViolation(end), ...
    'massDrift',result.history.common.physicalMassDrift(end), ...
    'symmetryDefect',symmetryDefect);
end
