function report = physicalConvergence()
%IPMTESTS.FOURTH.PHYSICALCONVERGENCE Unforced global convergence.
%   This gate advances the physical IPM equation through IPM.SOLVE, with no
%   manufactured forcing and no remeshing.  Uniform nested grids and time
%   steps are refined together by a factor of two.  Adjacent-grid
%   restrictions, rather than one finest-grid oracle, measure full-node L2
%   and Linf self-convergence, including every boundary node.

threshold = 3.8;
gridSizes = [17,33,65,129];
stepCounts = [8,16,32,64];
finalTime = 0.04;
roundoffMultiplier = 1e4;

assert(all(gridSizes(2:end) == 2*gridSizes(1:end-1)-1) && ...
    all(stepCounts(2:end) == 2*stepCounts(1:end-1)), ...
    'ipm:PhysicalConvergenceRefinement', ...
    'The physical convergence grids and step counts must halve h and dt.');

fprintf(['Running unforced physical-IPM self-convergence ' ...
    '(required order %.1f)...\n'],threshold);
overallTimer = tic;
levelCount = numel(gridSizes);
solutions = cell(1,levelCount);
grids = cell(1,levelCount);
weights = cell(1,levelCount);
levelRuntime = zeros(1,levelCount);
stepsUsed = zeros(1,levelCount);
massDrift = zeros(1,levelCount);
finalRange = zeros(2,levelCount);
stopReasons = cell(1,levelCount);

for level = 1:levelCount
    options = physical_options( ...
        gridSizes(level),finalTime,stepCounts(level));
    levelTimer = tic;
    result = ipm.solve(options);
    levelRuntime(level) = toc(levelTimer);

    stopReasons{level} = result.state.stopReason;
    stepsUsed(level) = result.state.steps;
    assert(strcmp(stopReasons{level},'final_time'), ...
        'ipm:PhysicalConvergenceEarlyStop', ...
        'The n=%d physical run stopped early with reason ''%s''.', ...
        gridSizes(level),stopReasons{level});
    assert(stepsUsed(level) == stepCounts(level), ...
        'ipm:PhysicalConvergenceTimeRefinement', ...
        ['The n=%d run used %d instead of %d steps; the CFL limiter ' ...
        'therefore invalidated the prescribed simultaneous refinement.'], ...
        gridSizes(level),stepsUsed(level),stepCounts(level));
    assert(abs(result.state.physicalTime-finalTime) <= ...
        1e3*eps(max(1,finalTime)), ...
        'ipm:PhysicalConvergenceClock', ...
        'The n=%d run did not reach the common physical final time.', ...
        gridSizes(level));
    assert(result.grid.remeshCount == 0, ...
        'ipm:PhysicalConvergenceRemesh', ...
        'The n=%d fixed-grid run unexpectedly remeshed.',gridSizes(level));
    assert(all(isfinite(result.state.rho),'all'), ...
        'ipm:PhysicalConvergenceFinite', ...
        'The n=%d final physical density is non-finite.',gridSizes(level));

    solutions{level} = result.state.rho;
    grids{level} = struct('x',result.grid.x,'y',result.grid.y);
    operators = ipm.mesh.build(ipm.config.resolve(options));
    weights{level} = operators.integrationWeights;
    assert(isequal(size(weights{level}),size(solutions{level})) && ...
        all(weights{level} > 0,'all'), ...
        'ipm:PhysicalConvergenceWeights', ...
        'The n=%d all-node high-order norm is unavailable.',gridSizes(level));

    massDrift(level) = result.history.common.massDrift(end);
    finalRange(:,level) = [min(solutions{level},[],'all'); ...
        max(solutions{level},[],'all')];
    fprintf(['  n=%3d, steps=%3d, runtime %.3fs, range ' ...
        '[%.8g, %.8g], mass drift %.3e.\n'], ...
        gridSizes(level),stepsUsed(level),levelRuntime(level), ...
        finalRange(1,level),finalRange(2,level),massDrift(level));
end

metricNames = {'L2','Linf'};
pairCount = levelCount-1;
errors = zeros(numel(metricNames),pairCount);
roundoffFloor = zeros(size(errors));
gridNestingError = zeros(2,pairCount);
for level = 1:pairCount
    coarse = solutions{level};
    restrictedFine = solutions{level+1}(1:2:end,1:2:end);
    assert(isequal(size(coarse),size(restrictedFine)), ...
        'ipm:PhysicalConvergenceRestriction', ...
        'The n=%d and n=%d fields are not exactly nested.', ...
        gridSizes(level),gridSizes(level+1));

    coarseGrid = grids{level};
    fineGrid = grids{level+1};
    gridNestingError(:,level) = [ ...
        max(abs(coarseGrid.x-fineGrid.x(1:2:end))); ...
        max(abs(coarseGrid.y-fineGrid.y(1:2:end)))];
    gridScale = max([1,max(abs(fineGrid.x)),max(abs(fineGrid.y))]);
    assert(all(gridNestingError(:,level) <= 100*eps(gridScale)), ...
        'ipm:PhysicalConvergenceGridNesting', ...
        'The n=%d and n=%d coordinate arrays are not nested.', ...
        gridSizes(level),gridSizes(level+1));

    difference = coarse-restrictedFine;
    errors(:,level) = full_node_norms(difference,weights{level});
    coarseNorms = full_node_norms(coarse,weights{level});
    fineNorms = full_node_norms(restrictedFine,weights{level});
    solutionScale = max([coarseNorms,fineNorms],[],2);
    roundoffFloor(:,level) = roundoffMultiplier * ...
        eps(max(ones(size(solutionScale)),solutionScale));
end

assert(all(isfinite(errors),'all') && all(errors > roundoffFloor,'all'), ...
    'ipm:PhysicalConvergenceRoundoff', ...
    ['Adjacent-grid differences must be finite and remain above the ' ...
    'roundoff floor; errors %s, floors %s.'], ...
    format_matrix(errors),format_matrix(roundoffFloor));
assert(all(diff(errors,1,2) < 0,'all'), ...
    'ipm:PhysicalConvergenceDecrease', ...
    'Physical adjacent-grid differences did not decrease monotonically.');

orders = log2(errors(:,1:end-1)./errors(:,2:end));
assert(all(orders >= threshold,'all'), ...
    'ipm:PhysicalConvergenceOrder', ...
    ['Unforced physical-IPM self-convergence fell below %.1f. ' ...
    'L2/Linf rows: %s.'],threshold,format_matrix(orders));

totalRuntime = toc(overallTimer);
report = struct('threshold',threshold,'gridSizes',gridSizes, ...
    'stepCounts',stepCounts,'dt',finalTime./stepCounts, ...
    'finalTime',finalTime,'metricNames',{metricNames}, ...
    'errors',errors,'orders',orders, ...
    'minimumOrder',min(orders,[],'all'), ...
    'roundoffMultiplier',roundoffMultiplier, ...
    'roundoffFloor',roundoffFloor, ...
    'gridNestingError',gridNestingError, ...
    'normDomain','all nodes including boundaries', ...
    'comparison','adjacent nested restriction; no finest-grid oracle', ...
    'equation','unforced physical IPM', ...
    'entryPoint','ipm.solve','spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','closed','adaptiveRemesh',false, ...
    'stepsUsed',stepsUsed,'stopReasons',{stopReasons}, ...
    'massDrift',massDrift,'finalRange',finalRange, ...
    'levelRuntime',levelRuntime,'totalRuntime',totalRuntime, ...
    'forcing','none','passed',true);

fprintf(['Unforced physical-IPM convergence passed: L2 orders %s; ' ...
    'Linf orders %s; minimum %.3f; total runtime %.3fs.\n'], ...
    format_values(orders(1,:)),format_values(orders(2,:)), ...
    report.minimumOrder,totalRuntime);
end

function options = physical_options(gridSize,finalTime,stepCount)
options = struct('nx',gridSize,'ny',gridSize, ...
    'xlim',[-1,1],'ymax',1,'gridMode','uniform', ...
    'gridStretchAutomatic',false,'gridStretch',[0,0], ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','closed', ...
    'wallTransportMode','conservative_flux', ...
    'symmetryMode','double_odd_omega','rescalingMode','physical', ...
    'initialCondition',@smooth_initial_density, ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'finalTime',finalTime,'physicalFinalTime',Inf, ...
    'maxDt',finalTime/stepCount,'minDt',1e-14,'cfl',0.45, ...
    'maxSteps',stepCount+2,'outputEvery',finalTime, ...
    'storeSnapshots',false,'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
end

function rho = smooth_initial_density(X,Y)
% Smooth even density with positive odd wall source on x>0.
g = Y.*(1-Y);
H = pi^2*g+2;
rho = 2+(H/pi).*cos(pi*(X+1));
end

function values = full_node_norms(field,weights)
weightSum = sum(weights,'all');
weightedSquare = sum(weights.*abs(field).^2,'all');
assert(weightSum > 0 && weightedSquare >= 0, ...
    'ipm:PhysicalConvergenceNorm', ...
    'The high-order all-node weighted norm is not positive.');
values = [sqrt(weightedSquare/weightSum);max(abs(field),[],'all')];
end

function text = format_values(values)
parts = arrayfun(@(value)sprintf('%.6g',value),values(:)', ...
    'UniformOutput',false);
text = strjoin(parts,', ');
end

function text = format_matrix(values)
rows = cell(1,size(values,1));
for row = 1:size(values,1)
    rows{row} = ['[',format_values(values(row,:)),']'];
end
text = strjoin(rows,'; ');
end
