function report = remap()
%IPMTESTS.FOURTH.REMAP Verify the integrated high-order remap contract.
%   The tests cover both directions between uniform and smoothly stretched
%   grids.  Every reported L1/L2/Linf norm includes all nodes, including the
%   one-sided boundary stencils.

fprintf('Running high-order remap verification...\n');
threshold = 3.8;
tailSegmentCount = 2;

%% Algebraic exactness, orientation, and matrix-signal contracts.
domain = [-1.25,1.75];
oldAxis = smooth_axis(43,0.38,domain);
newAxis = flipud(smooth_axis(38,-0.31,domain));
powers = 0:5;
oldPolynomials = oldAxis.^powers;
exactPolynomials = newAxis.^powers;

[columnResult,columnInfo] = ipm.remesh.interpolate( ...
    oldAxis,oldPolynomials,newAxis);
decreasingResult = ipm.remesh.interpolate( ...
    flipud(oldAxis),flipud(oldPolynomials),newAxis);
rowResult = ipm.remesh.interpolate( ...
    oldAxis.',oldPolynomials.',newAxis.',struct('sampleDimension',2));
[conservativePolynomials,polynomialConservationInfo] = ...
    ipm.remesh.interpolate(oldAxis,oldPolynomials,newAxis, ...
    struct('conservation','constant'));
constantRow = ipm.remesh.interpolate( ...
    oldAxis.',3.25*ones(size(oldAxis.')),newAxis.');

exactness = struct( ...
    'degreeFive',max(abs(columnResult-exactPolynomials),[],'all'), ...
    'decreasingAxes',max(abs(decreasingResult-exactPolynomials),[],'all'), ...
    'rowSignals',max(abs(rowResult-exactPolynomials.'),[],'all'), ...
    'conservativeDegreeFive',max(abs( ...
        conservativePolynomials-exactPolynomials),[],'all'), ...
    'constant',max(abs(constantRow-3.25),[],'all'));
exactness.maximum = max(struct2array(exactness));
exactMassDefect = max(abs(polynomialConservationInfo.massDefectAfter));

assert(columnInfo.stencilWidth == 6 && columnInfo.polynomialDegree == 5 && ...
    columnInfo.sampleDimension == 1 && columnInfo.extrapolatedNodeCount == 0, ...
    'ipm:HighOrderRemapMetadata', ...
    'The six-point interpolation metadata contract failed.');
assert(exactness.maximum < 2e-10 && exactMassDefect < 2e-12, ...
    'ipm:HighOrderRemapPolynomialExactness', ...
    'Constants or degree-at-most-five polynomials were not reproduced.');

%% All-node convergence in both remap directions.
nodeCounts = [17,25,33,49,65];
modeNames = {'none','constant'};
directionNames = {'uniform-to-stretched','stretched-to-uniform'};
signalNames = {'exp','sin','polynomial'};
normNames = {'L1','L2','Linf'};
numberOfLevels = numel(nodeCounts);
errors = zeros(numberOfLevels,2,3,3,2);
meshWidths = zeros(numberOfLevels,2);
correctionMagnitudes = zeros(numberOfLevels,2);
for level = 1:numberOfLevels
    numberOfNodes = nodeCounts(level);
    uniformAxis = linspace(-1,1,numberOfNodes).';
    stretchedAxis = sinh(1.15*uniformAxis)/sinh(1.15);
    axes = {uniformAxis,stretchedAxis;stretchedAxis,uniformAxis};
    for direction = 1:2
        sourceAxis = axes{direction,1};
        targetAxis = axes{direction,2};
        sourceValues = test_signals(sourceAxis);
        exactValues = test_signals(targetAxis);
        meshWidths(level,direction) = max(diff(sourceAxis));
        for mode = 1:2
            [interpolated,interpolationInfo] = ipm.remesh.interpolate( ...
                sourceAxis,sourceValues,targetAxis, ...
                struct('conservation',modeNames{mode}));
            for signal = 1:3
                errors(level,direction,signal,:,mode) = all_node_norms( ...
                    targetAxis,interpolated(:,signal)-exactValues(:,signal));
            end
            if mode == 2
                correctionMagnitudes(level,direction) = ...
                    max(abs(interpolationInfo.constantCorrection));
            end
        end
    end
end

orders = zeros(2,3,3,2);
for direction = 1:2
    for signal = 1:3
        for normIndex = 1:3
            for mode = 1:2
                orders(direction,signal,normIndex,mode) = fitted_order( ...
                    meshWidths(:,direction), ...
                    errors(:,direction,signal,normIndex,mode));
            end
        end
    end
end
correctionOrders = [ ...
    fitted_order(meshWidths(:,1),correctionMagnitudes(:,1)), ...
    fitted_order(meshWidths(:,2),correctionMagnitudes(:,2))];
minimumRawOrder = min(orders(:,:,:,1),[],'all');
minimumConservativeOrder = min(orders(:,:,:,2),[],'all');
meshLogRatios = reshape(log(meshWidths(1:end-1,:)./ ...
    meshWidths(2:end,:)),numberOfLevels-1,2,1,1,1);
segmentOrders = log(errors(1:end-1,:,:,:,:)./ ...
    errors(2:end,:,:,:,:))./meshLogRatios;
tailOrders = segmentOrders(end-tailSegmentCount+1:end,:,:,:,:);
minimumRawTailOrder = min(tailOrders(:,:,:,:,1),[],'all');
minimumConservativeTailOrder = min(tailOrders(:,:,:,:,2),[],'all');

for direction = 1:2
    fprintf('  %s all-node orders [raw | conservative]:\n', ...
        directionNames{direction});
    for signal = 1:3
        fprintf('    %-10s  %5.2f %5.2f %5.2f | %5.2f %5.2f %5.2f\n', ...
            signalNames{signal},orders(direction,signal,:,1), ...
            orders(direction,signal,:,2));
    end
end
assert(all(diff(errors,1,1) < 0,'all') && ...
    minimumRawTailOrder >= threshold && ...
    minimumConservativeTailOrder >= threshold, ...
    'ipm:HighOrderRemapConvergence', ...
    ['A remap error failed to decrease monotonically or one of the last ' ...
    'two all-node orders fell below %.1f (raw %.3f, conservative %.3f).'], ...
    threshold,minimumRawTailOrder,minimumConservativeTailOrder);
correctionSegmentOrders = log(correctionMagnitudes(1:end-1,:)./ ...
    correctionMagnitudes(2:end,:))./log(meshWidths(1:end-1,:)./ ...
    meshWidths(2:end,:));
assert(all(diff(correctionMagnitudes,1,1) < 0,'all') && ...
    all(correctionSegmentOrders(end-tailSegmentCount+1:end,:) >= ...
        threshold,'all'), ...
    'ipm:HighOrderRemapCorrectionOrder', ...
    ['The conservative correction was not monotone with both tail orders ' ...
    'at least %.1f.'],threshold);

%% Repeated uniform/stretched round trips.
numberOfCycles = 12;
roundTripErrors = zeros(numberOfLevels,3,3,2);
oneCycleErrors = zeros(numberOfLevels,3,2);
roundTripMassDrift = zeros(numberOfLevels,2);
for level = 1:numberOfLevels
    numberOfNodes = nodeCounts(level);
    uniformAxis = linspace(-1,1,numberOfNodes).';
    stretchedAxis = sinh(1.15*uniformAxis)/sinh(1.15);
    initialValues = test_signals(uniformAxis);
    for mode = 1:2
        values = initialValues;
        initialMass = [];
        for cycle = 1:numberOfCycles
            [stretchedValues,outwardInfo] = ipm.remesh.interpolate( ...
                uniformAxis,values,stretchedAxis, ...
                struct('conservation',modeNames{mode}));
            [values,returnInfo] = ipm.remesh.interpolate( ...
                stretchedAxis,stretchedValues,uniformAxis, ...
                struct('conservation',modeNames{mode}));
            if cycle == 1
                initialMass = outwardInfo.massOld;
                for signal = 1:3
                    oneCycleErrors(level,signal,mode) = max(abs( ...
                        values(:,signal)-initialValues(:,signal)));
                end
            end
        end
        for signal = 1:3
            roundTripErrors(level,signal,:,mode) = all_node_norms( ...
                uniformAxis,values(:,signal)-initialValues(:,signal));
        end
        roundTripMassDrift(level,mode) = max(abs( ...
            returnInfo.massAfterCorrection-initialMass)./ ...
            max(abs(initialMass),1));
    end
end

roundTripOrders = zeros(3,3,2);
for signal = 1:3
    for normIndex = 1:3
        for mode = 1:2
            roundTripOrders(signal,normIndex,mode) = fitted_order( ...
                2./(nodeCounts(:)-1), ...
                roundTripErrors(:,signal,normIndex,mode));
        end
    end
end
roundTripAmplification = squeeze( ...
    roundTripErrors(end,:,3,:))./squeeze(oneCycleErrors(end,:,:));
minimumRoundTripOrder = min(roundTripOrders,[],'all');
maximumRoundTripAmplification = max(roundTripAmplification,[],'all');
roundTripMeshWidths = 2./(nodeCounts(:)-1);
roundTripSegmentOrders = log(roundTripErrors(1:end-1,:,:,:)./ ...
    roundTripErrors(2:end,:,:,:))./reshape(log( ...
        roundTripMeshWidths(1:end-1)./roundTripMeshWidths(2:end)), ...
        numberOfLevels-1,1,1,1);
roundTripTailOrders = roundTripSegmentOrders( ...
    end-tailSegmentCount+1:end,:,:,:);
minimumRoundTripTailOrder = min(roundTripTailOrders,[],'all');
assert(all(diff(roundTripErrors,1,1) < 0,'all') && ...
    minimumRoundTripTailOrder >= threshold && ...
    maximumRoundTripAmplification < 4*numberOfCycles, ...
    'ipm:HighOrderRemapRoundTrip', ...
    ['Repeated remapping was nonmonotone, lost a %.1f tail order, or ' ...
    'amplified errors excessively.'],threshold);
assert(roundTripMassDrift(end,2) < 2e-13, ...
    'ipm:HighOrderRemapRepeatedConservation', ...
    'Conservative round trips accumulated measurable mass drift.');

%% Conservation/range tradeoff for the global constant correction.
tradeOldAxis = linspace(-1,1,19).';
tradeNewAxis = smooth_axis(24,0.67,[-1,1]);
tradeOldValues = exp(1.9*tradeOldAxis);
[tradeRaw,tradeRawInfo] = ipm.remesh.interpolate( ...
    tradeOldAxis,tradeOldValues,tradeNewAxis);
[tradeConservative,tradeConservativeInfo] = ipm.remesh.interpolate( ...
    tradeOldAxis,tradeOldValues,tradeNewAxis,'constant');
tradeExact = exp(1.9*tradeNewAxis);
massScale = max(abs(tradeConservativeInfo.massOld),1);
tradeoff = struct( ...
    'rawLinfError',max(abs(tradeRaw-tradeExact)), ...
    'conservativeLinfError',max(abs(tradeConservative-tradeExact)), ...
    'rawRelativeMassDefect',max(abs( ...
        tradeRawInfo.massDefectAfter))/massScale, ...
    'conservativeRelativeMassDefect',max(abs( ...
        tradeConservativeInfo.massDefectAfter))/massScale, ...
    'rawRangeViolation',max(tradeRawInfo.rangeViolationAfter), ...
    'conservativeRangeViolation',max( ...
        tradeConservativeInfo.rangeViolationAfter), ...
    'constantCorrection',max(abs( ...
        tradeConservativeInfo.constantCorrection)));
assert(tradeoff.conservativeRelativeMassDefect < 2e-14 && ...
    tradeoff.rawRelativeMassDefect > ...
        100*tradeoff.conservativeRelativeMassDefect && ...
    tradeoff.conservativeRangeViolation >= 0.9*tradeoff.constantCorrection, ...
    'ipm:HighOrderRemapTradeoff', ...
    'The global correction did not expose the expected conservation/range tradeoff.');

%% Exercise the integrated tensor remesh path and its wall-trace correction.
integrated = verify_integrated_transfer( ...
    nodeCounts,threshold,tailSegmentCount);

%% Reject an unlimited high-order remap when a discontinuity overshoots.
nonsmoothRejection = verify_nonsmooth_rejection();

report = struct();
report.nodeCounts = nodeCounts;
report.exactness = exactness;
report.exactMassDefect = exactMassDefect;
report.directionNames = directionNames;
report.signalNames = signalNames;
report.normNames = normNames;
report.errors = errors;
report.orders = orders;
report.segmentOrders = segmentOrders;
report.tailOrders = tailOrders;
report.minimumRawOrder = minimumRawOrder;
report.minimumConservativeOrder = minimumConservativeOrder;
report.minimumRawTailOrder = minimumRawTailOrder;
report.minimumConservativeTailOrder = minimumConservativeTailOrder;
report.correctionOrders = correctionOrders;
report.correctionSegmentOrders = correctionSegmentOrders;
report.roundTripCycles = numberOfCycles;
report.roundTripErrors = roundTripErrors;
report.roundTripOrders = roundTripOrders;
report.minimumRoundTripOrder = minimumRoundTripOrder;
report.roundTripSegmentOrders = roundTripSegmentOrders;
report.roundTripTailOrders = roundTripTailOrders;
report.minimumRoundTripTailOrder = minimumRoundTripTailOrder;
report.roundTripAmplification = roundTripAmplification;
report.roundTripMassDrift = roundTripMassDrift;
report.tradeoff = tradeoff;
report.integrated = integrated;
report.nonsmoothRejection = nonsmoothRejection;
report.passed = true;

fprintf('  polynomial/constant maximum exactness error: %.3e\n', ...
    exactness.maximum);
fprintf(['  correction orders uniform->stretched / stretched->uniform: ' ...
    '%.2f / %.2f\n'],correctionOrders);
fprintf(['  %d-cycle finest Linf error raw/conservative: %.3e / %.3e ' ...
    '(max amplification %.2f)\n'],numberOfCycles, ...
    max(roundTripErrors(end,:,3,1),[],'all'), ...
    max(roundTripErrors(end,:,3,2),[],'all'), ...
    maximumRoundTripAmplification);
fprintf(['  mass/range tradeoff raw: mass %.3e, range %.3e; ' ...
    'conservative: mass %.3e, range %.3e (shift %.3e)\n'], ...
    tradeoff.rawRelativeMassDefect,tradeoff.rawRangeViolation, ...
    tradeoff.conservativeRelativeMassDefect, ...
    tradeoff.conservativeRangeViolation,tradeoff.constantCorrection);
fprintf(['  integrated tensor remesh orders L2/Linf/wall: ' ...
    '%.2f / %.2f / %.2f (mass %.3e)\n'],integrated.orders, ...
    max(integrated.massDefects));
fprintf(['  nonsmooth remesh range violation %.3e: rejected before ' ...
    'state installation.\n'],nonsmoothRejection.rangeViolation);
fprintf('High-order remap verification passed.\n');
end

function result = verify_nonsmooth_rejection()
numberOfNodes = 65;
userOptions = struct('nx',numberOfNodes,'ny',numberOfNodes, ...
    'xlim',[-1,1],'ymax',1,'gridMode','uniform','gridStretch',0, ...
    'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
    'remeshTransferScheme','high_order', ...
    'farBoundaryMode','dirichlet_zero','symmetryMode','half_plane', ...
    'rescalingMode','physical','adaptiveRemesh',true, ...
    'rangeStopTolerance',1e-12,'remeshMaximumCellRatio',10, ...
    'remeshMinimumImprovement',0, ...
    'saveResults',false,'makePlots',false,'verbose',false);
config = ipm.config.resolve(userOptions);
ops = ipm.mesh.build(config);
ops.rescaling.pinX = 0;
rho = double(abs(ops.X) <= 0.4 & ops.Y <= 0.6);
referenceX = linspace(-1,1,numberOfNodes);
referenceY = linspace(0,1,numberOfNodes)';
proposal = struct('x',sinh(0.9*referenceX)/sinh(0.9), ...
    'y',sinh(0.7*referenceY)/sinh(0.7), ...
    'xImproved',true,'yImproved',true);
[~,~,metrics] = ipm.remesh.transfer(rho,ops,config,proposal);
flow = struct('coreGridPoints',NaN,'verticalCoreGridPoints',NaN, ...
    'trackedWallPeak',metrics.peak);
context = struct('trackY',true,'xTargets',1,'yTargets',1);
validation = ipm.remesh.validate( ...
    metrics,ops,flow,config,proposal,context,0);
assert(metrics.rangeViolation > config.diagnostics.rangeStopTolerance && ...
    ~validation.rangeSafe && ~validation.accepted, ...
    'ipm:HighOrderNonsmoothRemeshAcceptance', ...
    'An overshooting discontinuous high-order remap was not rejected.');

orchestratorOps = ipm.evolve.initializeScaling(rho,ops);
scale = ipm.evolve.initialScale(orchestratorOps);
[~,orchestratorFlow] = ...
    ipm.evolve.flow(rho,orchestratorOps,scale);
wallMetrics = ipm.diagnostics.peakResolution( ...
    max(orchestratorFlow.source(1,:),0),orchestratorOps.x, ...
    orchestratorOps.rescaling.adaptiveLevels);
orchestratorOps.rescaling.safetyPeakPoints = ...
    wallMetrics.areaPoints(1);
orchestratorOps.rescaling.safetyLevelPoints = wallMetrics.gridPoints;
orchestratorOps.rescaling.adaptiveTargetLevelPoints = ...
    2*wallMetrics.gridPoints;
orchestratorOps.remeshCount = 3;
[initialProposal,~] = ipm.remesh.propose( ...
    orchestratorOps,orchestratorFlow,config,0,[]);
[~,candidateOps,initialMetrics] = ipm.remesh.transfer( ...
    rho,orchestratorOps,config,initialProposal);
[rolledBackRho,rolledBackOps,orchestratorInfo] = ...
    ipm.remesh.adapt( ...
        rho,orchestratorOps,orchestratorFlow,config,1);
rollbackExact = isequaln(rolledBackRho,rho) && ...
    isequaln(rolledBackOps,orchestratorOps);
assert(initialProposal.anyImproved && ...
    candidateOps.remeshCount == orchestratorOps.remeshCount && ...
    initialMetrics.rangeViolation > ...
        config.diagnostics.rangeStopTolerance && ...
    ~orchestratorInfo.applied && rollbackExact, ...
    'ipm:HighOrderNonsmoothRemeshRollback', ...
    ['The adaptive-remesh orchestrator installed a rejected high-order ' ...
    'candidate or failed to restore the exact accepted state.']);
result = struct('rangeViolation',metrics.rangeViolation, ...
    'tolerance',config.diagnostics.rangeStopTolerance, ...
    'accepted',validation.accepted,'rangeSafe',validation.rangeSafe, ...
    'orchestratorApplied',orchestratorInfo.applied, ...
    'rollbackExact',rollbackExact, ...
    'candidateCount',candidateOps.remeshCount, ...
    'initialRequestedAmplitude',initialProposal.xAmplitude, ...
    'initialOrchestratorRangeViolation',initialMetrics.rangeViolation);
end

function result = verify_integrated_transfer( ...
        nodeCounts,threshold,tailSegmentCount)
errors = zeros(numel(nodeCounts),3);
massDefects = zeros(size(nodeCounts));
meshWidths = 2./(nodeCounts-1);
for level = 1:numel(nodeCounts)
    numberOfNodes = nodeCounts(level);
    userOptions = struct('nx',numberOfNodes,'ny',numberOfNodes, ...
        'xlim',[-1,1],'ymax',1,'gridMode','uniform','gridStretch',0, ...
        'spatialDiscretization','high_order', ...
        'transportScheme','weno5_fd', ...
        'remeshTransferScheme','high_order', ...
        'farBoundaryMode','dirichlet_zero','symmetryMode','half_plane', ...
        'rescalingMode','physical','adaptiveRemesh',false, ...
        'saveResults',false,'makePlots',false,'verbose',false);
    config = ipm.config.resolve(userOptions);
    ops = ipm.mesh.build(config);
    rho = remesh_probe(ops.X,ops.Y);
    ops.rescaling.pinX = 0;
    referenceX = linspace(-1,1,numberOfNodes);
    referenceY = linspace(0,1,numberOfNodes)';
    proposal = struct( ...
        'x',sinh(0.8*referenceX)/sinh(0.8), ...
        'y',sinh(0.6*referenceY)/sinh(0.6));
    [transferred,newOps] = ipm.remesh.transfer( ...
        rho,ops,config,proposal);
    exact = remesh_probe(newOps.X,newOps.Y);
    error = transferred-exact;
    errors(level,1) = sqrt(sum(error.^2.* ...
        newOps.integrationWeights,'all'));
    errors(level,2) = max(abs(error),[],'all');
    errors(level,3) = max(abs( ...
        transferred(1,:)-exact(1,:)));
    oldMass = sum(rho.*ops.integrationWeights,'all');
    newMass = sum(transferred.*newOps.integrationWeights,'all');
    massDefects(level) = abs(newMass-oldMass);
end
orders = zeros(1,3);
for metric = 1:3
    orders(metric) = fitted_order(meshWidths,errors(:,metric));
end
segmentOrders = log(errors(1:end-1,:)./errors(2:end,:))./ ...
    log(meshWidths(1:end-1)'./meshWidths(2:end)');
tailOrders = segmentOrders(end-tailSegmentCount+1:end,:);
assert(all(diff(errors,1,1) < 0,'all') && ...
    all(tailOrders >= threshold,'all') && max(massDefects) < 2e-13, ...
    'ipm:HighOrderIntegratedRemesh', ...
    ['The integrated tensor remesh lost monotone %.1f tail convergence ' ...
    'or conservation: fitted orders %.3f %.3f %.3f, mass %.3e.'], ...
    threshold,orders,max(massDefects));
result = struct('nodeCounts',nodeCounts,'meshWidths',meshWidths, ...
    'errors',errors,'orders',orders,'segmentOrders',segmentOrders, ...
    'tailOrders',tailOrders,'massDefects',massDefects);
end

function values = remesh_probe(X,Y)
values = 2+exp(0.4*X).*cos(0.7*Y)+0.1*sin(2*X+Y);
end

function axis = smooth_axis(numberOfNodes,amplitude,domain)
parameter = linspace(0,1,numberOfNodes).';
mapped = parameter+amplitude*sin(2*pi*parameter)/(2*pi);
axis = domain(1)+(domain(2)-domain(1))*mapped;
axis([1,end]) = domain;
end

function values = test_signals(axis)
values = [ ...
    exp(1.7*axis), ...
    sin(5.1*axis)+0.2*cos(2.3*axis), ...
    0.5*axis.^6-0.4*axis.^7+0.7*axis.^9];
end

function norms = all_node_norms(axis,errorValues)
axis = axis(:);
errorValues = errorValues(:);
if axis(1) > axis(end)
    axis = flipud(axis);
    errorValues = flipud(errorValues);
end
weights = zeros(size(axis));
weights([1,end]) = [axis(2)-axis(1),axis(end)-axis(end-1)]/2;
weights(2:end-1) = (axis(3:end)-axis(1:end-2))/2;
domainLength = axis(end)-axis(1);
norms = [ ...
    sum(weights.*abs(errorValues))/domainLength, ...
    sqrt(sum(weights.*abs(errorValues).^2)/domainLength), ...
    max(abs(errorValues))];
end

function order = fitted_order(meshWidth,errorValues)
meshWidth = meshWidth(:);
errorValues = errorValues(:);
assert(all(errorValues > 0 & isfinite(errorValues)), ...
    'ipm:HighOrderRemapOrderData', ...
    'Convergence data must contain finite positive errors.');
fit = polyfit(log(meshWidth),log(errorValues),1);
order = fit(1);
end
