function report = time()
%IPMTESTS.FOURTH.TIME Full-node fourth-order temporal convergence gates.
%   REPORT = IPMTESTS.FOURTH.TIME() verifies the SSPRK(5,4) tableau
%   by step doubling on a nonlinear ODE with a closed-form solution.  It
%   then holds uniform high-order/WENO5-FD grids fixed and measures both a
%   forced nonlinear IPM evolution and the production IPM.EVOLVE.STEPSSPRK54
%   path against finer solutions of the same semidiscrete equations.  The
%   production gates cover nonzero isotropic scales and nonzero
%   anisotropic scales with fixed nonzero rates.  Velocity (and the
%   anisotropic Poisson metric) is recomputed from every evolving stage.
%   The IPM L2 norm uses the high-order quadrature weights at every node;
%   the Linf norm likewise includes every node.

threshold = 3.8;
tailSegmentCount = 2;
roundoffMultiplier = 1e3;
tableau = ipm.evolve.ssprk54Tableau();

fprintf(['Running SSPRK54 temporal verification (last %d orders must be ' ...
    'at least %.1f)...\n'],tailSegmentCount,threshold);
report = struct('threshold',threshold, ...
    'requiredTailSegments',tailSegmentCount, ...
    'roundoffMultiplier',roundoffMultiplier);
report.nonlinearOde = verify_nonlinear_ode( ...
    tableau,threshold,tailSegmentCount,roundoffMultiplier);
report.forcedNonlinearIpm = verify_forced_ipm( ...
    tableau,threshold,tailSegmentCount,roundoffMultiplier);
report.productionIsotropic = verify_production_ipm( ...
    'isotropic',threshold,tailSegmentCount,roundoffMultiplier);
report.productionAnisotropicFixed = verify_production_ipm( ...
    'anisotropic_fixed',threshold,tailSegmentCount,roundoffMultiplier);
report.passed = true;

fprintf(['SSPRK54 temporal verification passed: ODE tail orders %s; ' ...
    'forced IPM L2/Linf tail orders %s; production isotropic and ' ...
    'anisotropic-fixed rho-L2/rho-Linf/scale-Linf tail orders %s / ' ...
    '%s.\n'], ...
    format_values(report.nonlinearOde.tailOrders), ...
    format_values(report.forcedNonlinearIpm.tailOrders), ...
    format_matrix(report.productionIsotropic.tailOrders), ...
    format_matrix(report.productionAnisotropicFixed.tailOrders));
end

function result = verify_nonlinear_ode( ...
    tableau,threshold,tailSegmentCount,roundoffMultiplier)
% y'=1+y^2 has the exact nonlinear solution tan(t+atan(y0)).
initialValue = 0.2;
finalTime = 0.6;
stepCounts = [6,12,24,48];
exact = tan(finalTime+atan(initialValue));
errors = zeros(size(stepCounts));
rhs = @(state,time) 1+state.^2;
for level = 1:numel(stepCounts)
    numerical = advance_fixed_steps( ...
        initialValue,finalTime,stepCounts(level),rhs,tableau);
    errors(level) = abs(numerical-exact);
end
orders = log2(errors(1:end-1)./errors(2:end));
tailOrders = orders(end-tailSegmentCount+1:end);
roundoffFloor = roundoffMultiplier*eps(max(1,abs(exact)));

assert(all(isfinite(errors)) && all(errors > roundoffFloor), ...
    'ipm:SSPRK54OdeRoundoff', ...
    ['Nonlinear ODE errors must be finite and remain above the %.3e ' ...
    'roundoff floor; observed errors: %s.'], ...
    roundoffFloor,format_values(errors));
assert(all(tailOrders >= threshold), ...
    'ipm:SSPRK54OdeTimeOrder', ...
    'Nonlinear ODE SSPRK54 tail orders fell below %.1f: %s.', ...
    threshold,format_values(tailOrders));

result = struct('equation','y'' = 1+y^2', ...
    'exactSolution','tan(t+atan(y0))','initialValue',initialValue, ...
    'finalTime',finalTime,'stepCounts',stepCounts, ...
    'dt',finalTime./stepCounts,'errors',errors,'orders',orders, ...
    'tailOrders',tailOrders,'roundoffFloor',roundoffFloor, ...
    'usesRepositoryTableau',true,'passed',true);
fprintf('  nonlinear exact ODE tail orders: %s.\n', ...
    format_values(tailOrders));
end

function result = verify_forced_ipm( ...
    tableau,threshold,tailSegmentCount,roundoffMultiplier)
gridSize = [13,13];
finalTime = 0.08;
stepCounts = [4,8,16,32];
referenceSteps = 32*stepCounts(end);
referenceCheckSteps = referenceSteps/2;
referenceTolerance = 1e-2;
ops = fixed_uniform_operators(gridSize);
initial = ipmtests.support.mms(ops.X,ops.Y,0);
rhs = @(rho,time) forced_ipm_rhs(rho,time,ops);

reference = advance_fixed_steps( ...
    initial.rho,finalTime,referenceSteps,rhs,tableau);
referenceCheck = advance_fixed_steps( ...
    initial.rho,finalTime,referenceCheckSteps,rhs,tableau);

metricNames = {'L2','Linf'};
errors = zeros(numel(metricNames),numel(stepCounts));
for level = 1:numel(stepCounts)
    numerical = advance_fixed_steps( ...
        initial.rho,finalTime,stepCounts(level),rhs,tableau);
    errors(:,level) = full_node_norms(numerical-reference,ops);
end
orders = log2(errors(:,1:end-1)./errors(:,2:end));
tailOrders = orders(:,end-tailSegmentCount+1:end);

referenceNorms = full_node_norms(reference,ops);
roundoffFloor = roundoffMultiplier*eps(max(1,referenceNorms));
referenceDiscrepancy = full_node_norms(reference-referenceCheck,ops);
referenceAdequacyRatio = referenceDiscrepancy./errors(:,end);

assert(all(isfinite(errors),'all') && all(errors > 0,'all'), ...
    'ipm:SSPRK54IpmFinite', ...
    'Forced nonlinear IPM errors must be finite and positive.');
assert(all(errors(:,end) > roundoffFloor), ...
    'ipm:SSPRK54IpmRoundoff', ...
    ['Finest measured forced-IPM errors reached the roundoff floor. ' ...
    'Errors %s; floors %s.'], ...
    format_values(errors(:,end)),format_values(roundoffFloor));
assert(all(referenceAdequacyRatio <= referenceTolerance), ...
    'ipm:SSPRK54IpmReference', ...
    ['The fine-reference discrepancy is not negligible relative to the ' ...
    'finest measured error: ratios %s (limit %.3e).'], ...
    format_values(referenceAdequacyRatio),referenceTolerance);
assert(all(tailOrders >= threshold,'all'), ...
    'ipm:SSPRK54IpmTimeOrder', ...
    ['Forced nonlinear IPM SSPRK54 tail orders fell below %.1f. ' ...
    'L2/Linf rows: %s.'],threshold,format_matrix(tailOrders));

result = struct('gridSize',gridSize,'gridMode','uniform', ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','finalTime',finalTime, ...
    'stepCounts',stepCounts,'dt',finalTime./stepCounts, ...
    'referenceSteps',referenceSteps, ...
    'referenceDt',finalTime/referenceSteps, ...
    'referenceRefinement',referenceSteps/stepCounts(end), ...
    'referenceCheckSteps',referenceCheckSteps, ...
    'referenceCheckDt',finalTime/referenceCheckSteps, ...
    'referenceDiscrepancy',referenceDiscrepancy, ...
    'referenceAdequacyRatio',referenceAdequacyRatio, ...
    'referenceTolerance',referenceTolerance, ...
    'metricNames',{metricNames},'errors',errors,'orders',orders, ...
    'tailOrders',tailOrders,'roundoffFloor',roundoffFloor, ...
    'normDomain','all nodes', ...
    'l2Weights','ops.integrationWeights', ...
    'stageVelocityRecomputed',true, ...
    'forcing','ipmtests.support.mms','passed',true);
fprintf(['  forced nonlinear IPM tail orders (L2; Linf): %s; ' ...
    'reference/error ratios %s.\n'], ...
    format_matrix(tailOrders),format_values(referenceAdequacyRatio));
end

function result = verify_production_ipm( ...
    productionCase,threshold,tailSegmentCount,roundoffMultiplier)
gridSize = [13,13];
finalTime = 0.1;
stepCounts = [4,8,16,32];
referenceSteps = 16*stepCounts(end);
referenceCheckSteps = referenceSteps/2;
referenceTolerance = 1e-2;
[ops,initialRho,initialScale,caseDetails] = ...
    production_case(productionCase,gridSize);

[~,initialFlow] = ipm.evolve.flow(initialRho,ops,initialScale);
if strcmp(productionCase,'isotropic')
    initialRates = [initialFlow.c_l,initialFlow.c_omega,initialFlow.c_r];
else
    initialRates = [initialFlow.c_x,initialFlow.c_y, ...
        initialFlow.c_omega,initialFlow.c_r];
    fixedRateError = max(abs(initialRates-caseDetails.fixedRates));
    assert(initialFlow.timeSpeed == 1 && fixedRateError < 1e-13, ...
        'ipm:SSPRK54ProductionFixedRates', ...
        ['The anisotropic production gate did not exercise the requested ' ...
        'unbounded fixed-rate branch.']);
end
initialScaleVector = pack_production_scale(initialScale,productionCase);
assert(max(abs(initialRates)) > 1e-6 && ...
    max(abs(initialScaleVector)) > 1e-3, ...
    'ipm:SSPRK54ProductionNonzeroScale', ...
    ['The production temporal gate requires both nonzero scale state ' ...
    'and nonzero scale rates.']);

[referenceRho,referenceScale] = advance_production_steps( ...
    initialRho,initialScale,finalTime,referenceSteps,ops);
[referenceCheckRho,referenceCheckScale] = advance_production_steps( ...
    initialRho,initialScale,finalTime,referenceCheckSteps,ops);

metricNames = {'rhoL2','rhoLinf','scaleLinf'};
errors = zeros(numel(metricNames),numel(stepCounts));
for level = 1:numel(stepCounts)
    [numericalRho,numericalScale] = advance_production_steps( ...
        initialRho,initialScale,finalTime,stepCounts(level),ops);
    errors(:,level) = production_error( ...
        numericalRho,numericalScale,referenceRho,referenceScale, ...
        ops,productionCase);
end
orders = log2(errors(:,1:end-1)./errors(:,2:end));
tailOrders = orders(:,end-tailSegmentCount+1:end);

referenceMagnitudes = [full_node_norms(referenceRho,ops); ...
    max(abs(pack_production_scale(referenceScale,productionCase)))];
roundoffFloor = roundoffMultiplier*eps(max(1,referenceMagnitudes));
referenceDiscrepancy = production_error( ...
    referenceRho,referenceScale,referenceCheckRho,referenceCheckScale, ...
    ops,productionCase);
referenceAdequacyRatio = referenceDiscrepancy./errors(:,end);

assert(all(isfinite(errors),'all') && all(errors > 0,'all'), ...
    'ipm:SSPRK54ProductionFinite', ...
    'Production SSPRK54 errors must be finite and positive.');
assert(all(errors(:,end) > roundoffFloor), ...
    'ipm:SSPRK54ProductionRoundoff', ...
    ['Finest production errors reached the roundoff floor for %s. ' ...
    'Errors %s; floors %s.'],productionCase, ...
    format_values(errors(:,end)),format_values(roundoffFloor));
assert(all(referenceAdequacyRatio <= referenceTolerance), ...
    'ipm:SSPRK54ProductionReference', ...
    ['The fine-reference discrepancy is not negligible for %s: ' ...
    'ratios %s (limit %.3e).'],productionCase, ...
    format_values(referenceAdequacyRatio),referenceTolerance);
assert(all(tailOrders >= threshold,'all'), ...
    'ipm:SSPRK54ProductionTimeOrder', ...
    ['Production SSPRK54 tail orders fell below %.1f for %s. ' ...
    'rho-L2/rho-Linf/scale-Linf rows: %s; errors: %s.'], ...
    threshold,productionCase,format_matrix(tailOrders), ...
    format_matrix(errors));

result = struct('case',productionCase,'gridSize',gridSize, ...
    'gridMode','uniform','spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'usesActualProductionStep',true,'stageVelocityRecomputed',true, ...
    'stageAnisotropicMetricRecomputed', ...
        strcmp(productionCase,'anisotropic_fixed'), ...
    'initialScale',initialScale,'initialRates',initialRates, ...
    'finalTime',finalTime,'stepCounts',stepCounts, ...
    'dt',finalTime./stepCounts,'referenceSteps',referenceSteps, ...
    'referenceDt',finalTime/referenceSteps, ...
    'referenceRefinement',referenceSteps/stepCounts(end), ...
    'referenceCheckSteps',referenceCheckSteps, ...
    'referenceCheckDt',finalTime/referenceCheckSteps, ...
    'referenceDiscrepancy',referenceDiscrepancy, ...
    'referenceAdequacyRatio',referenceAdequacyRatio, ...
    'referenceTolerance',referenceTolerance, ...
    'metricNames',{metricNames},'errors',errors,'orders',orders, ...
    'tailOrders',tailOrders,'roundoffFloor',roundoffFloor, ...
    'normDomain','all nodes','l2Weights','ops.integrationWeights', ...
    'passed',true);
fprintf(['  production %-17s tail orders ' ...
    '(rho L2; rho Linf; scale Linf): %s; reference/error ratios %s.\n'], ...
    productionCase,format_matrix(tailOrders), ...
    format_values(referenceAdequacyRatio));
end

function [ops,rho,scale,details] = production_case(productionCase,gridSize)
options = struct('nx',gridSize(1),'ny',gridSize(2), ...
    'xlim',[-2,2],'ymax',2,'gridMode','uniform', ...
    'gridStretchAutomatic',false,'gridStretch',[0,0], ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','open', ...
    'wallTransportMode','conservative_flux', ...
    'symmetryMode','half_plane','rescalingMode','dynamic', ...
    'initialCondition',@(X,Y)2+exp(-((X-0.55).^2+0.7*Y.^2)), ...
    'adaptiveRemesh',false,'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);

switch productionCase
    case 'isotropic'
        options.dynamicScaleGeometry = 'isotropic';
        options.symmetryMode = 'double_odd_omega';
        options.initialCondition = ...
            @(X,Y)3-2*exp(-(X.^2+0.7*Y.^2));
        options.lengthGauge = 'transport_anchor';
        options.transportAnchorX = 0.75;
        options.cOmegaGauge = 'none';
        scale = struct('logC_l',log(1.18),'logC_omega',log(0.87), ...
            'physicalTime',0.07,'X_shift',0.11,'canonicalTime',0.03);
        details = struct('fixedRates',[]);
    case 'anisotropic_fixed'
        fixedRates = [4,-2,-1,0];
        options.dynamicScaleGeometry = 'anisotropic';
        options.symmetryMode = 'double_odd_omega';
        options.initialCondition = ...
            @(X,Y)3-2*exp(-(X.^2+0.7*Y.^2));
        options.anisotropicGaugeMode = 'fixed';
        options.anisotropicFixedCX = fixedRates(1);
        options.anisotropicFixedCY = fixedRates(2);
        options.anisotropicFixedCOmega = fixedRates(3);
        options.anisotropicFixedCR = fixedRates(4);
        scale = struct('logC_l',log(1.16),'logC_x',log(1.16), ...
            'logC_y',log(0.91),'logC_omega',log(1.09), ...
            'physicalTime',0.05,'X_shift',0.12,'canonicalTime',0.02);
        details = struct('fixedRates',fixedRates);
    otherwise
        error('ipm:SSPRK54ProductionCase', ...
            'Unknown production temporal verification case "%s".', ...
            productionCase);
end

config = ipm.config.resolve(options);
ops = ipm.mesh.build(config);
rho = ipm.field.initialDensity(ops,config.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
assert(isfield(ops,'integrationWeights') && ...
    isequal(size(ops.integrationWeights),[ops.ny,ops.nx]), ...
    'ipm:SSPRK54ProductionWeights', ...
    'The production high-order full-node weights are unavailable.');
end

function [rho,scale] = advance_production_steps( ...
    initialRho,initialScale,finalTime,stepCount,ops)
dt = finalTime/stepCount;
rho = initialRho;
scale = initialScale;
for step = 1:stepCount
    [rho,~,scale] = ipm.evolve.stepSsprk54(rho,dt,ops,scale);
end
end

function values = production_error( ...
    rho,scale,referenceRho,referenceScale,ops,productionCase)
values = [full_node_norms(rho-referenceRho,ops); ...
    max(abs(pack_production_scale(scale,productionCase)- ...
        pack_production_scale(referenceScale,productionCase)))];
end

function values = pack_production_scale(scale,productionCase)
if strcmp(productionCase,'anisotropic_fixed')
    values = [scale.logC_l;scale.logC_y;scale.logC_omega; ...
        scale.physicalTime;scale.X_shift;scale.canonicalTime];
else
    values = [scale.logC_l;scale.logC_omega;scale.physicalTime; ...
        scale.X_shift;scale.canonicalTime];
end
end

function ops = fixed_uniform_operators(gridSize)
options = struct('nx',gridSize(1),'ny',gridSize(2), ...
    'xlim',[-1,1],'ymax',1,'gridMode','uniform', ...
    'gridStretchAutomatic',false,'gridStretch',[0,0], ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','closed', ...
    'wallTransportMode','conservative_flux', ...
    'symmetryMode','double_odd_omega', ...
    'adaptiveRemesh',false,'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
ops = ipm.mesh.build(ipm.config.resolve(options));
assert(isfield(ops,'integrationWeights') && ...
    isequal(size(ops.integrationWeights),[ops.ny,ops.nx]), ...
    'ipm:SSPRK54IpmWeights', ...
    'The high-order full-node integration weights are unavailable.');
end

function rate = forced_ipm_rhs(rho,time,ops)
% Both velocity and WENO transport depend on the current RK stage density.
[u1,u2] = ipm.field.velocity(rho,ops);
transportRate = ipm.field.transport( ...
    rho,u1,u2,ops,ops.transportBoundaryMode);
manufactured = ipmtests.support.mms(ops.X,ops.Y,time);
rate = transportRate+manufactured.forcing;
end

function state = advance_fixed_steps(initial,finalTime,stepCount,rhs,tableau)
dt = finalTime/stepCount;
state = initial;
for step = 1:stepCount
    time = (step-1)*dt;
    rates = cell(tableau.stages,1);
    for stage = 1:tableau.stages
        stageState = state;
        for previous = 1:stage-1
            stageState = stageState+dt*tableau.A(stage,previous)* ...
                rates{previous};
        end
        stageTime = time+tableau.c(stage)*dt;
        rates{stage} = rhs(stageState,stageTime);
    end
    for stage = 1:tableau.stages
        state = state+dt*tableau.b(stage)*rates{stage};
    end
end
end

function values = full_node_norms(error,ops)
weights = ops.integrationWeights;
weightedSquare = sum(weights.*abs(error).^2,'all');
weightSum = sum(weights,'all');
assert(weightSum > 0 && weightedSquare >= 0, ...
    'ipm:SSPRK54IpmNorm', ...
    'The high-order all-node weighted norm is not positive.');
values = [sqrt(weightedSquare/weightSum);max(abs(error),[],'all')];
end

function text = format_values(values)
parts = arrayfun(@(value)sprintf('%.6g',value),values(:)', ...
    'UniformOutput',false);
text = strjoin(parts,', ');
end

function text = format_matrix(values)
rows = cell(1,size(values,1));
for row = 1:size(values,1)
    rows{row} = ['[',format_values(values(row,:)),']'];
end
text = strjoin(rows,'; ');
end
