function quality = quality(axis,stencilWidth,quadratureWeights)
%IPM.MESH.QUALITY Conditioning and smoothness diagnostics for one grid axis.
%   The diagnostics are scale invariant.  They are intended both for hard
%   sixth-order admission gates and for comparing candidate smooth mappings.

validateattributes(axis,{'numeric'}, ...
    {'vector','real','finite','increasing'},mfilename,'axis');
validateattributes(stencilWidth,{'numeric'}, ...
    {'scalar','integer','>=',3,'<=',numel(axis)}, ...
    mfilename,'stencilWidth');
validateattributes(quadratureWeights,{'numeric'}, ...
    {'vector','numel',numel(axis),'real','finite'}, ...
    mfilename,'quadratureWeights');

axis = axis(:);
faces = diff(axis);
if numel(faces) > 1
    adjacentRatios = max(faces(2:end)./faces(1:end-1), ...
        faces(1:end-1)./faces(2:end));
    maximumAdjacentCellRatio = max(adjacentRatios);
    maximumLogSpacingSlope = max(abs(diff(log(faces))));
else
    maximumAdjacentCellRatio = 1;
    maximumLogSpacingSlope = 0;
end
if numel(faces) > 2
    maximumLogSpacingCurvature = max(abs(diff(log(faces),2)));
else
    maximumLogSpacingCurvature = 0;
end

numberOfNodes = numel(axis);
halfWidth = floor(stencilWidth/2);
stencilRcond = inf(numberOfNodes,1);
firstDerivativeAmplification = zeros(numberOfNodes,1);
secondDerivativeAmplification = zeros(numberOfNodes,1);
for node = 1:numberOfNodes
    first = min(max(node-halfWidth,1), ...
        numberOfNodes-stencilWidth+1);
    stencil = first:first+stencilWidth-1;
    offsets = axis(stencil)-axis(node);
    scale = max(abs(offsets));
    normalized = offsets/scale;
    moments = normalized'.^((0:stencilWidth-1)');
    stencilRcond(node) = rcond(moments);

    firstTarget = zeros(stencilWidth,1);
    firstTarget(2) = 1;
    firstWeights = moments\firstTarget;
    firstDerivativeAmplification(node) = sum(abs(firstWeights));

    secondTarget = zeros(stencilWidth,1);
    secondTarget(3) = 2;
    secondWeights = moments\secondTarget;
    secondDerivativeAmplification(node) = sum(abs(secondWeights));
end

quadratureWeights = quadratureWeights(:);
meanWeight = sum(quadratureWeights)/numberOfNodes;
controlWidths = [faces(1)/2; ...
    (faces(1:end-1)+faces(2:end))/2;faces(end)/2];
localQuadratureRatios = quadratureWeights./controlWidths;
quality = struct( ...
    'nodeCount',numberOfNodes, ...
    'stencilWidth',stencilWidth, ...
    'minimumSpacing',min(faces), ...
    'maximumSpacing',max(faces), ...
    'globalCellRatio',max(faces)/min(faces), ...
    'maximumAdjacentCellRatio',maximumAdjacentCellRatio, ...
    'maximumLogSpacingSlope',maximumLogSpacingSlope, ...
    'maximumLogSpacingCurvature',maximumLogSpacingCurvature, ...
    'minimumStencilRcond',min(stencilRcond), ...
    'maximumFirstDerivativeAmplification', ...
    max(firstDerivativeAmplification), ...
    'maximumSecondDerivativeAmplification', ...
    max(secondDerivativeAmplification), ...
    'minimumQuadratureWeight',min(quadratureWeights), ...
    'quadratureWeightsStrictlyPositive',all(quadratureWeights > 0), ...
    'minimumQuadratureWeightRatio', ...
    min(quadratureWeights)/meanWeight, ...
    'minimumQuadratureWeightToControlWidthRatio', ...
    min(localQuadratureRatios), ...
    'maximumQuadratureWeightToControlWidthRatio', ...
    max(localQuadratureRatios), ...
    'maximumQuadratureWeightToControlWidthAbsoluteDeviationFromUnity', ...
    max(abs(localQuadratureRatios-1)));
end
