function policy = sixthOrderPolicy()
%IPM.MESH.SIXTHORDERPOLICY Fixed admission gates for sixth-order grids.

policy = struct( ...
    'maximumAdjacentCellRatio',1.15, ...
    'minimumStencilRcond',1e-9, ...
    'minimumQuadratureWeightRatio',1e-4, ...
    'maximumMetricError',1e-6, ...
    'recommendedCfl',0.4);
end
