function report = ipm_perflab_time_refinement(sourceFile,outputDirectory,requested)
%IPM_PERFLAB_TIME_REFINEMENT Native same-grid, matched-physical-time branches.
%   REQUIRED: physicalFinalTime and canonicalFinalTime, frozen before runs.
%   Source must use CFL=.5,maxDt=.004. Fine branch changes only these two
%   choices to .25,.002 in a separately serialized research transaction.
%   Both evolutions use ipm.solve; its resume whitelist remains unchanged.
%   Defaults reject grids larger than 65^2 pending a separately scheduled run.

assert(nargin == 3 && isstruct(requested) && isscalar(requested), ...
    'Pass source checkpoint, new output directory, and explicit horizons.');
assert(~exist(outputDirectory,'dir'),'Use a new experiment output directory.');
settings = freeze_settings(requested);
assert(maxNumCompThreads == 10,'Existing production checkpoints require 10 threads.');
source = ipm.output.readCheckpoint(sourceFile);
saved = source.payload.state;
assert(saved.config.time.cfl == 0.5 && saved.config.time.maxDt == 0.004, ...
    'ipm:TimeRefinementBaseline','Source must have CFL=.5 and maxDt=.004.');
assert(~saved.config.remesh.adaptiveRemesh, ...
    'ipm:TimeRefinementGrid','A fixed-grid source is required; do not change remesh policy.');
assert(ismember(saved.config.transport.spatialDiscretization,{'high_order','sixth_order'}), ...
    'This research rhoY comparison supports the maintained fourth/sixth derivatives.');
assert(settings.allowLargeGrid || numel(saved.rho) <= 65^2, ...
    'ipm:TimeRefinementScheduling','Large-grid computation requires an explicitly scheduled window.');
assert(settings.physicalFinalTime > saved.scale.physicalTime && ...
    settings.canonicalFinalTime > saved.scale.canonicalTime, ...
    'Both horizons must be later than the accepted source state.');
mkdir(outputDirectory);
study = struct('schemaVersion',1,'kind','ipm_frozen_time_refinement', ...
    'sourceFile',char(sourceFile),'sourceSignature',source.signature, ...
    'sourceStep',saved.step,'sourceCanonicalTime',saved.scale.canonicalTime, ...
    'sourcePhysicalTime',saved.scale.physicalTime,'sourceConfig',saved.config, ...
    'settings',settings,'baselineCfl',0.5,'baselineMaxDt',0.004, ...
    'refinedCfl',0.25,'refinedMaxDt',0.002, ...
    'matlabVersion',version,'computationalThreads',maxNumCompThreads, ...
    'thresholdsFrozenBeforeEvolution',true);
save(fullfile(outputDirectory,'frozen_study.mat'),'study');
jsonStudy = study;
if isa(jsonStudy.sourceConfig.physics.initialCondition,'function_handle')
    jsonStudy.sourceConfig.physics.initialCondition = ...
        func2str(jsonStudy.sourceConfig.physics.initialCondition);
end
write_json(fullfile(outputDirectory,'frozen_study.json'),jsonStudy);
clear jsonStudy;

% This is a deliberately different numerical experiment, not a claimed
% bitwise same-method restart. Preserve every accepted mathematical value,
% history row and output cursor; only the two timestep config values change.
[state,log,cursor] = ipm.output.restoreCheckpoint(source);
state.config.time.cfl = 0.25;
state.config.time.maxDt = 0.002;
fineSeed = ipm.output.makeCheckpoint(state,log,cursor);
expectedState = saved;
expectedState.config.time.cfl = 0.25;
expectedState.config.time.maxDt = 0.002;
branchAudit = struct( ...
    'acceptedStateExceptRestoreMetadataExact',isequaln( ...
        rmfield(expectedState,'runMetadata'),rmfield(fineSeed.payload.state,'runMetadata')), ...
    'historyAndSnapshotsExact',isequaln(source.payload.log,fineSeed.payload.log), ...
    'cursorExact',isequaln(source.payload.cursor,fineSeed.payload.cursor), ...
    'numericalChanges',{{'time.cfl: .5 -> .25','time.maxDt: .004 -> .002'}}, ...
    'pdeStepsTaken',0);
assert(branchAudit.acceptedStateExceptRestoreMetadataExact && ...
    branchAudit.historyAndSnapshotsExact && branchAudit.cursorExact, ...
    'ipm:TimeRefinementBranch','Timestep branch changed an unauthorized payload value.');
[written,fineSeedFile] = ipm.output.writeCheckpoint(fineSeed, ...
    fullfile(outputDirectory,'refined_seed_checkpoint.mat'));
readback = ipm.output.readCheckpoint(fineSeedFile);
branchAudit.strictReadbackExact = isequaln(written,readback);
assert(branchAudit.strictReadbackExact,'Refined seed failed exact strict readback.');
branchAudit.fineSeedFile = char(fineSeedFile);
write_json(fullfile(outputDirectory,'branch_provenance.json'),branchAudit);
% Avoid retaining a restored 2D LU during either ipm.solve initialization.
clear state log cursor fineSeed written readback expectedState;

options = run_options(outputDirectory,'baseline',saved.step,settings);
timer = tic;
baseline = ipm.solve(options,source);
baselineWallSeconds = toc(timer);
options = run_options(outputDirectory,'refined',saved.step,settings);
timer = tic;
refined = ipm.solve(options,fineSeedFile);
refinedWallSeconds = toc(timer);

baselineAudit = result_audit(baseline,source,settings);
refinedAudit = result_audit(refined,source,settings);
[lab,deviations] = lab_comparison(baseline,refined,settings.window);
save(fullfile(outputDirectory,'lab_deviations.mat'),'deviations');
scalars = scalar_comparison(baseline,refined);
report = struct('schemaVersion',1,'kind','ipm_time_refinement_report', ...
    'studyFile',fullfile(outputDirectory,'frozen_study.mat'), ...
    'sourceFile',char(sourceFile),'branchAudit',branchAudit, ...
    'baseline',baselineAudit,'refined',refinedAudit, ...
    'baselineWallSeconds',baselineWallSeconds,'refinedWallSeconds',refinedWallSeconds, ...
    'physicalTimeDifference',refined.state.physicalTime-baseline.state.physicalTime, ...
    'canonicalTimeDifference',refined.state.canonicalTime-baseline.state.canonicalTime, ...
    'sameNumericalSpecificationExceptTimestep',isequaln( ...
        comparison_config(baseline.config),comparison_config(refined.config)), ...
    'localPhysical',lab,'scalars',scalars, ...
    'peakAlignedPhysical',ipm.output.compare(baseline,refined,settings.window), ...
    'thresholds',settings.thresholds, ...
    'deviationsFile',fullfile(outputDirectory,'lab_deviations.mat'));
t = settings.thresholds;
checks = struct('baselineTrusted',baselineAudit.allTrusted, ...
    'refinedTrusted',refinedAudit.allTrusted, ...
    'historyPrefixesExact',baselineAudit.historyPrefixExact && refinedAudit.historyPrefixExact, ...
    'sameFixedGrid',baselineAudit.fixedGridExact && refinedAudit.fixedGridExact, ...
    'terminalCheckpointsExact',baselineAudit.terminalCheckpointMatches && ...
        refinedAudit.terminalCheckpointMatches, ...
    'bothReachedPhysicalEndpoint',baselineAudit.endpointReached && refinedAudit.endpointReached, ...
    'refinementExercised',refinedAudit.segmentSteps > baselineAudit.segmentSteps, ...
    'timeMatched',abs(report.physicalTimeDifference) <= t.physicalTimeAbsolute, ...
    'sameSpecification',report.sameNumericalSpecificationExceptTimestep, ...
    'rho',lab.rhoRelativeL2 <= t.rhoRelativeL2, ...
    'omega',lab.omegaRelativeL2 <= t.omegaRelativeL2, ...
    'rhoY',lab.rhoYRelativeL2 <= t.rhoYRelativeL2, ...
    'gradientPeaks',all_scalar_bounds(scalars, ...
        {'physicalRhoXInf','physicalRhoYInf','physicalGradInf'},t.gradientPeakRelative), ...
    'gaugeRates',all_scalar_bounds(scalars,{'c_l','c_omega'},t.gaugeRateRelative), ...
    'scales',all_scalar_bounds(scalars,{'C_l','C_omega'},t.scaleRelative), ...
    'selectedQuadraticTelemetryPresent', ...
        ~strcmp(saved.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak') || ...
        (scalars.quadraticPeakP.available && scalars.quadraticCurvatureC.available), ...
    'quadraticPeak',optional_scalar_bound(scalars,'quadraticPeakP',t.quadraticPeakRelative), ...
    'quadraticCurvature',optional_scalar_bound(scalars,'quadraticCurvatureC',t.curvatureRelative));
report.checks = checks;
report.passed = all(structfun(@(value)value,checks));
report.interpretation = ['One short interval estimates temporal sensitivity; ' ...
    'it does not establish a convergence order or infinite-time profile.'];
save(fullfile(outputDirectory,'time_refinement_report.mat'),'report');
write_json(fullfile(outputDirectory,'time_refinement_report.json'),report);
fprintf(['TIME_REFINEMENT passed=%d steps=%d/%d targetError=%.9g/%.9g ' ...
    'dtPhysical=%.9g rhoL2=%.9g omegaL2=%.9g rhoYL2=%.9g\n'], ...
    report.passed,baselineAudit.segmentSteps,refinedAudit.segmentSteps, ...
    baselineAudit.physicalTargetError,refinedAudit.physicalTargetError, ...
    report.physicalTimeDifference,lab.rhoRelativeL2,lab.omegaRelativeL2,lab.rhoYRelativeL2);
end

function settings = freeze_settings(requested)
assert(all(isfield(requested,{'physicalFinalTime','canonicalFinalTime'})), ...
    'Freeze both physical and canonical horizons explicitly.');
settings = struct('physicalFinalTime',requested.physicalFinalTime, ...
    'canonicalFinalTime',requested.canonicalFinalTime,'maxSegmentSteps',128, ...
    'window',[-2,2,2],'allowLargeGrid',false, ...
    'thresholds',struct('physicalTimeAbsolute',1e-10,'rhoRelativeL2',5e-4, ...
    'omegaRelativeL2',5e-3,'rhoYRelativeL2',5e-3,'gradientPeakRelative',5e-3, ...
    'gaugeRateRelative',1e-2,'scaleRelative',1e-3, ...
    'quadraticPeakRelative',5e-3,'curvatureRelative',1e-2));
assert(isempty(setdiff(fieldnames(requested),fieldnames(settings))), ...
    'Unknown study setting.');
names = fieldnames(requested);
for index = 1:numel(names)
    if strcmp(names{index},'thresholds')
        thresholdNames = fieldnames(requested.thresholds);
        assert(isempty(setdiff(thresholdNames,fieldnames(settings.thresholds))), ...
            'Unknown comparison threshold.');
        for thresholdIndex = 1:numel(thresholdNames)
            name = thresholdNames{thresholdIndex};
            settings.thresholds.(name) = requested.thresholds.(name);
        end
    else
        settings.(names{index}) = requested.(names{index});
    end
end
validateattributes(settings.physicalFinalTime,{'double'},{'scalar','real','positive','finite'});
validateattributes(settings.canonicalFinalTime,{'double'},{'scalar','real','positive','finite'});
validateattributes(settings.maxSegmentSteps,{'numeric'},{'scalar','integer','positive','finite'});
validateattributes(settings.window,{'double'},{'vector','numel',3,'real','finite'});
assert(settings.window(2)>settings.window(1) && settings.window(3)>0,'Invalid lab window.');
assert(islogical(settings.allowLargeGrid) && isscalar(settings.allowLargeGrid));
assert(all(structfun(@(value)isnumeric(value) && isscalar(value) && ...
    isfinite(value) && value>0,settings.thresholds)),'Invalid comparison threshold.');
end

function options = run_options(directory,label,step,settings)
options = struct('finalTime',settings.canonicalFinalTime, ...
    'physicalFinalTime',settings.physicalFinalTime,'maxSteps',step+settings.maxSegmentSteps, ...
    'saveResults',true,'resultFile',fullfile(directory,[label '_result.mat']), ...
    'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false, ...
    'checkpoint',struct('enabled',true,'file',fullfile(directory,[label '_checkpoint.mat']), ...
    'every',Inf,'atExit',true));
end

function audit = result_audit(result,source,settings)
saved = source.payload.state;
[trusted,trustChecks] = ipm.output.trustedMask(result.history,result.config);
prefix = source.payload.log.history;
prefixExact = true;
groups = fieldnames(prefix);
for groupIndex = 1:numel(groups)
    group = groups{groupIndex};
    names = fieldnames(prefix.(group));
    for index = 1:numel(names)
        name = names{index};
        reference = prefix.(group).(name);
        if ~isfield(result.history.(group),name) || ...
                numel(result.history.(group).(name)) < numel(reference)
            prefixExact = false;
        else
            actual = result.history.(group).(name);
            prefixExact = prefixExact && isequaln(actual(1:numel(reference)),reference);
        end
    end
end
terminalCheckpointMatches = false;
checkpointFile = '';
if isfield(result.metadata,'latestCheckpointFile')
    checkpointFile = char(result.metadata.latestCheckpointFile);
    terminal = ipm.output.readCheckpoint(checkpointFile);
    terminalCheckpointMatches = terminal.payload.state.step == result.state.steps && ...
        isequaln(terminal.payload.state.rho,result.state.rho) && ...
        isequaln(terminal.payload.log.history,result.history);
end
targetError = result.state.physicalTime-settings.physicalFinalTime;
audit = struct('resultFile',char(result.metadata.resultFile),'checkpointFile',checkpointFile, ...
    'segmentSteps',result.state.steps-saved.step,'stopReason',result.state.stopReason, ...
    'physicalTime',result.state.physicalTime,'canonicalTime',result.state.canonicalTime, ...
    'physicalTargetError',targetError,'allTrusted',all(trusted), ...
    'trustChecks',trustChecks,'historyPrefixExact',prefixExact, ...
    'historyPrefixRows',numel(prefix.common.t), ...
    'fixedGridExact',isequaln(result.grid.x,saved.x) && isequaln(result.grid.y,saved.y) && ...
        result.grid.remeshCount == saved.remeshCount, ...
    'terminalCheckpointMatches',terminalCheckpointMatches, ...
    'endpointReached',strcmp(result.state.stopReason,'physical_final_time') && ...
        abs(targetError) <= settings.thresholds.physicalTimeAbsolute, ...
    'cfl',result.config.time.cfl,'maxDt',result.config.time.maxDt);
end

function config = comparison_config(config)
config = rmfield(config,'output');
config.time = rmfield(config.time,{'cfl','maxDt'});
end

function [comparison,deviations] = lab_comparison(baseline,refined,window)
assert(min(refined.grid.physicalX) <= window(1) && ...
    max(refined.grid.physicalX) >= window(2) && max(refined.grid.physicalY) >= window(3), ...
    'ipm:TimeRefinementCoverage','Candidate physical grid does not cover frozen lab window.');
referenceView = lab_view(baseline);
candidateView = lab_view(refined);
standard = ipm.output.compare(referenceView,candidateView,window);
baselineRhoY = physical_rho_y(baseline);
refinedRhoY = physical_rho_y(refined);
referenceView.physicalRho = baselineRhoY;
candidateView.physicalRho = refinedRhoY;
vertical = ipm.output.compare(referenceView,candidateView,window);
comparison = struct('window',window,'coordinates','physical_lab', ...
    'comparisonImplementation','ipm.output.compare','points',standard.points, ...
    'rhoRelativeL2',standard.rhoRelativeL2,'omegaRelativeL2',standard.omegaRelativeL2, ...
    'rhoYRelativeL2',vertical.rhoRelativeL2, ...
    'rhoAbsoluteInf',standard.rhoAbsoluteInf,'omegaAbsoluteInf',standard.omegaAbsoluteInf, ...
    'rhoYAbsoluteInf',vertical.rhoAbsoluteInf);
xi = find(baseline.grid.physicalX >= window(1) & baseline.grid.physicalX <= window(2));
yi = find(baseline.grid.physicalY >= 0 & baseline.grid.physicalY <= window(3));
[X,Y] = meshgrid(baseline.grid.physicalX(xi),baseline.grid.physicalY(yi));
assert(numel(X) == standard.points && vertical.points == standard.points, ...
    'Lab comparison dropped reference nodes from the frozen window.');
deviations = struct('window',window,'coordinates','physical_lab', ...
    'x',baseline.grid.physicalX(xi),'y',baseline.grid.physicalY(yi), ...
    'physicalTimeReference',baseline.state.physicalTime, ...
    'physicalTimeCandidate',refined.state.physicalTime, ...
    'interpolation','linear_to_reference_nodes');
fields = {'rho','omega','rhoY'};
referenceFields = {baseline.physical.rho,baseline.physical.omega,baselineRhoY};
candidateFields = {refined.physical.rho,refined.physical.omega,refinedRhoY};
for index = 1:numel(fields)
    reference = referenceFields{index}(yi,xi);
    candidate = interp2(refined.grid.physicalX,refined.grid.physicalY, ...
        candidateFields{index},X,Y,'linear',NaN);
    assert(all(isfinite(candidate),'all'),'Physical comparison left common coverage.');
    deviations.(fields{index}) = struct('reference',reference,'candidate',candidate, ...
        'difference',candidate-reference);
    comparison.([fields{index},'RelativeInf']) = max(abs(candidate-reference),[],'all') / ...
        max(max(abs(reference),[],'all'),eps);
end
end

function view = lab_view(result)
view = struct('comovingPhysicalX',result.grid.physicalX, ...
    'physicalY',result.grid.physicalY,'physicalRho',result.physical.rho, ...
    'physicalOmega',result.physical.omega, ...
    'physicalTrackedPeakX',result.grid.physicalTrackedPeakX, ...
    'history',struct('physicalTrackedWallOmegaPeak', ...
    result.history.common.physicalTrackedWallOmegaPeak, ...
    'physicalTrackedWallPeakWidth',result.history.common.physicalTrackedWallPeakWidth));
end

function rhoY = physical_rho_y(result)
width = 7;
if strcmp(result.config.transport.spatialDiscretization,'sixth_order')
    width = 9;
end
rhoY = (ipm.mesh.fdMatrix(result.grid.y,1,width)*result.state.rho) * ...
    (result.scale.Cy/result.scale.Comega);
end

function values = scalar_comparison(baseline,refined)
names = {'physicalRhoXInf','physicalRhoYInf','physicalGradInf','physicalOmegaInf', ...
    'physicalTrackedWallOmegaPeak','physicalTrackedPeakX','physicalTrackedWallPeakWidth', ...
    'c_l','c_omega','C_l','C_omega'};
values = struct();
for index = 1:numel(names)
    name = names{index};
    values.(name) = scalar_pair(baseline.history.common.(name)(end), ...
        refined.history.common.(name)(end));
end
pairs = {'quadraticPeakP','omegaGaugeQuadraticPeakValue'; ...
    'quadraticCurvatureC','omegaGaugeQuadraticCurvature'; ...
    'quadraticPeakX','omegaGaugeQuadraticPeakX'; ...
    'quadraticForcing','omegaGaugeQuadraticForcing'};
for index = 1:size(pairs,1)
    field = pairs{index,2};
    if isfield(baseline.history.gauge,field) && isfield(refined.history.gauge,field)
        values.(pairs{index,1}) = scalar_pair(baseline.history.gauge.(field)(end), ...
            refined.history.gauge.(field)(end));
    else
        values.(pairs{index,1}) = struct('available',false,'baseline',NaN, ...
            'refined',NaN,'difference',NaN,'relativeDifference',NaN);
    end
end
end

function value = scalar_pair(baseline,refined)
value = struct('available',true,'baseline',baseline,'refined',refined, ...
    'difference',refined-baseline, ...
    'relativeDifference',(refined-baseline)/max(abs(baseline),eps));
end

function answer = all_scalar_bounds(values,names,limit)
answer = true;
for index = 1:numel(names)
    pair = values.(names{index});
    answer = answer && pair.available && isfinite(pair.relativeDifference) && ...
        abs(pair.relativeDifference) <= limit;
end
end

function answer = optional_scalar_bound(values,name,limit)
pair = values.(name);
answer = ~pair.available || (isfinite(pair.relativeDifference) && ...
    abs(pair.relativeDifference) <= limit);
end

function write_json(fileName,value)
file = fopen(fileName,'w');
assert(file >= 0,'Unable to write study artifact.');
cleanup = onCleanup(@()fclose(file));
fprintf(file,'%s\n',jsonencode(value,'PrettyPrint',true));
end
