function report = ipm_perflab_screen_current_axis(currentFile,baseDesignFile, ...
        rootReferenceFile,parentPlatformFile,outputDirectory,controls)
%IPM_PERFLAB_SCREEN_CURRENT_AXIS Explicit single-hop current-axis experiment.
% Original immutable root data remain the external reference. The current
% axis is separately audited against its last globally rooted platform.
% No checkpoint/runtime references, shared helper, LU, or PDE are changed.
if nargin < 6, controls = struct(); end
defaults = struct('sigmas',[.18,.25,.35,.5,.75,1,1.5,2,3], ...
    'xConstructionPaddings',[1,1.10],'kernelFocusMode','anchor');
assert(isstruct(controls) && isscalar(controls) && ...
    isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
names = fieldnames(defaults);
for k=1:numel(names)
    if ~isfield(controls,names{k}), controls.(names{k})=defaults.(names{k}); end
end
validateattributes(controls.sigmas,{'double'},{'vector','nonempty','positive','finite'});
validateattributes(controls.xConstructionPaddings,{'double'},{'vector','nonempty','>=',1,'finite'});
controls.kernelFocusMode = validatestring(controls.kernelFocusMode, ...
    {'anchor','core_front_intersection'});
assert(~exist(fullfile(outputDirectory,'current_axis_report.mat'),'file'), ...
    'This output already has a completed report.');
if ~exist(outputDirectory,'dir'), mkdir(outputDirectory); end
current = ipm.output.validate(currentFile);
assert(all(ipm.output.trustedMask(current)),'A full trusted prefix is required.');
loaded = load(baseDesignFile,'design'); base = loaded.design;
loaded = load(rootReferenceFile,'dataset'); root = loaded.dataset;
loaded = load(parentPlatformFile,'candidate'); parent = loaded.candidate;
loaded = load(parent.referenceFile,'dataset'); parentRoot = loaded.dataset;
assert(strcmp(parent.kind,'ipm_longtime_moving_platform_candidate') && ...
    parent.rootAxisFactoryReproducedExactly && parent.transactionReady, ...
    'The current axis needs an audited globally rooted construction parent.');
assert(isequal(parent.candidateX(:),current.grid.x(:)) && ...
    isequal(parent.candidateY(:),current.grid.y(:)), ...
    'Last committed globally rooted platform does not match the current axes.');
assert(isequal(root.snapshots(1).x,parentRoot.snapshots(1).x) && ...
    isequal(root.snapshots(1).y,parentRoot.snapshots(1).y), ...
    'Immutable external root mismatch.');
assert(isequal(base.dataset.snapshots(1).rho,current.state.rho) && ...
    isequal(base.dataset.snapshots(1).x(:),current.grid.x(:)) && ...
    isequal(base.dataset.snapshots(1).y(:),current.grid.y(:)) && ...
    ~base.reference.usesCurrentAxesAsReference, ...
    'The supplied frozen design must pair this terminal field with the root.');
xReference = current.grid.x(:).';
yReference = root.snapshots(1).y;
assert(any(xReference==1) && any(xReference==-1),'Current axis needs exact ±1 nodes.');
sigmas = controls.sigmas(:).';
paddings = controls.xConstructionPaddings(:).';
records = base.profiles.records;
core = [[records.safetyCoreCenter]'-[records.safetyCoreWidthLeft]', ...
    [records.safetyCoreCenter]'+[records.safetyCoreWidthRight]'];
front = [[records.leftFrontCenter]'-[records.leftFrontHalfWidth]', ...
    [records.leftFrontCenter]'+[records.leftFrontHalfWidth]'];
intervals = min(max([core;front],0),xReference(end));
focusCenter = 1;
if strcmp(controls.kernelFocusMode,'core_front_intersection')
    intersection = [max(intervals(:,1)),min(intervals(:,2))];
    assert(diff(intersection)>1024*eps(max(1,xReference(end))), ...
        'A strict actual-field core/front intersection is required.');
    focusCenter = .5*sum(intersection);
end
provenance = struct('currentFile',currentFile,'rootReferenceFile',rootReferenceFile, ...
    'parentPlatformFile',parentPlatformFile,'baseDesignFile',baseDesignFile, ...
    'canonicalTime',current.state.canonicalTime,'sourceRemeshCount',current.grid.remeshCount, ...
    'referenceProvenance','trusted_terminal_axis_single_hop', ...
    'currentIncrementalReferenceDepth',0,'incrementalGeneration',1, ...
    'maximumIncrementalReferenceDepth',1, ...
    'depthEvidence','Current axes exactly equal a successfully scored root-factory platform, not an incremental child.', ...
    'externalRootAxesPreserved',true,'runtimeReferencesAccessedOrModified',false, ...
    'sameRoundRecursiveReference',false,'sigmas',sigmas,'xConstructionPaddings',paddings, ...
    'kernelFocusMode',controls.kernelFocusMode,'kernelFocusCenter',focusCenter, ...
    'targetCoreCells',[21,21],'targetFrontCells',20,'yConstructionPadding',1.15);
write_json(fullfile(outputDirectory,'frozen_provenance.json'),provenance);
options = base.options;
options.equalizationOptions.currentAxisXFallbackEnabled = true;
options.equalizationOptions.currentAxisXSigmas = sigmas;
options.equalizationOptions.currentAxisXPower = 2;
options.equalizationOptions.currentIncrementalReferenceDepth = 0;
options.equalizationOptions.maximumIncrementalReferenceDepth = 1;
options.outputFile = fullfile(outputDirectory,'existing_fallback_design.mat');
if exist(options.outputFile,'file')
    loaded = load(options.outputFile,'design'); fallback = loaded.design;
    assert(isequaln(fallback.options,rmfield(options,'outputFile')), ...
        'Saved fallback options differ from these frozen controls.');
else
    fallback = ipm_gridlab_design_continuation_stage(currentFile,rootReferenceFile,options);
end
audit = fallback.reference.currentAxisXFallback;
assert(audit.usedAsReference && audit.referenceAudit.passed && ...
    audit.incrementalGeneration==1 && ~audit.sameRoundRecursiveReference);
assert(isequal(fallback.dataset.snapshots(1).x(:),xReference(:)) && ...
    isequal(fallback.dataset.snapshots(1).y(:),current.grid.y(:)) && ...
    isequal(fallback.dataset.snapshots(1).rho,current.state.rho) && ...
    isequal(fallback.reference.xSignature,base.reference.xSignature) && ...
    isequal(fallback.reference.ySignature,base.reference.ySignature), ...
    'The saved fallback must preserve the actual entry field and external root.');
nativeItems = {};
for index = audit.candidateIndices(:).'
    c = fallback.xCandidates(index);
    distance = NaN;
    if ~isempty(c.axis), distance = min(abs(c.axis-1)); end
    nativeItems{end+1} = struct('name',c.name,'sigma',c.model.sigma, ...
        'status',c.status,'meetsTargets',c.meetsTargets,'core',c.minimumCoreCells, ...
        'front',c.minimumFrontCells,'ratio',c.maximumAdjacentCellRatio, ...
        'constructedAnchorPosition',c.model.anchorPhysicalPosition, ...
        'runtimeAnchorOneDistance',distance,'runtimeAnchorOneExact',any(c.axis==1), ...
        'incrementalGeneration',c.model.incrementalGeneration, ...
        'referenceProvenance',c.model.referenceProvenance); %#ok<AGROW>
end
% Preserve the built-in depth guard as a negative audit. This is a metadata
% control test on the same field, not a claim that the actual source is depth1.
options.equalizationOptions.currentIncrementalReferenceDepth = 1;
options.outputFile = fullfile(outputDirectory,'exhausted_depth_negative_design.mat');
negative = ipm_gridlab_design_continuation_stage(currentFile,rootReferenceFile,options);
negativeAudit = negative.reference.currentAxisXFallback;
assert(strcmp(negativeAudit.status,'maximum_incremental_reference_depth_reached') && ...
    ~negativeAudit.usedAsReference && isempty(negativeAudit.candidateIndices));
yOptions = struct('geometry','positive','focusCenters',0, ...
    'sigma',base.options.equalizationOptions.ySigma, ...
    'power',base.options.equalizationOptions.yPower,'meshLimits',base.options.meshLimits);
[y,yInfo] = ipm_gridlab_equalize_axis(yReference, ...
    [zeros(numel(records),1),[records.yCoreWidth]'],21*1.15*ones(numel(records),1),yOptions);
items = {};
anchorNode = find(xReference==1);
for padding = paddings
    for sigma = sigmas
        xOptions = struct('geometry','symmetric','focusCenters',focusCenter, ...
            'anchorPhysicalPosition',1,'sigma',sigma,'power',2,'meshLimits',base.options.meshLimits);
        targets = padding*[21*ones(numel(records),1);20*ones(numel(records),1)];
        % Every trial starts from the entry axis, never a preceding candidate.
        [x,xInfo] = ipm_gridlab_equalize_axis(xReference,intervals,targets,xOptions);
        beforeSnap = x(anchorNode);
        x(anchorNode) = 1; x(numel(x)+1-anchorNode) = -1;
        scoreOptions = base.options.pairScoreOptions;
        scoreOptions.profiles = base.profiles;
        scoreOptions.minimumXCoreCells = 21; scoreOptions.minimumYCoreCells = 21;
        scoreOptions.minimumXFrontCells = 20; scoreOptions.meshLimits = base.options.meshLimits;
        score = ipm_gridlab_score_frozen_pair(base.dataset,x,y,scoreOptions);
        localPassed = local_quality(score.quality.x) && local_quality(score.quality.y);
        resolutionPassed = false; transferPassed = false;
        coreCells = NaN; frontCells = NaN; yCells = NaN; peakJump = NaN;
        if score.admissible && ~isempty(fieldnames(score.aggregate))
            a = score.aggregate;
            coreCells = a.minimumXCoreCells; frontCells = a.minimumXLeftFrontCells;
            yCells = a.minimumYCoreCells; peakJump = a.worst.rhoXMaximumRelativeChange;
            resolutionPassed = coreCells>=21-1e-6 && yCells>=21-1e-6 && frontCells>=20-1e-6;
            transferPassed = peakJump<=2e-3 && a.worst.conservationRelativeDefect<=5e-12 && ...
                a.worst.relativeRangeViolation<=2e-4;
        end
        ready = score.admissible && localPassed && resolutionPassed && transferPassed;
        file = fullfile(outputDirectory,sprintf('current_anchor1_sigma%04d_pad%03d.mat', ...
            round(100*sigma),round(100*padding)));
        candidate = struct('kind','ipm_current_axis_single_hop_anchor1_candidate', ...
            'provenance',provenance,'existingFallbackReferenceAudit',audit, ...
            'currentIncrementalReferenceDepth',0,'incrementalGeneration',1, ...
            'candidateX',x,'candidateY',y,'sigma',sigma,'xConstructionPadding',padding, ...
            'xEqualizationInfo',xInfo,'yEqualizationInfo',yInfo, ...
            'anchorPosition',1,'anchorNodeIndex',anchorNode,'anchorNodeBeforeSnap',beforeSnap, ...
            'anchorSnapDisplacement',1-beforeSnap,'completeAxisRescoredAfterSnap',true, ...
            'localQuadraturePassed',localPassed,'resolutionPassed',resolutionPassed, ...
            'transferPassed',transferPassed,'pairScore',score,'transactionReady',ready, ...
            'pdeAdvanced',false,'checkpointRegridCommitted',false);
        save(file,'candidate','-v7.3');
        item = struct('sigma',sigma,'xConstructionPadding',padding, ...
            'file',file,'ready',ready,'xStatus',xInfo.status,'coreX',coreCells, ...
            'coreY',yCells,'frontCells',frontCells,'ratio',score.quality.x.maximumAdjacentCellRatio, ...
            'curvature',score.quality.x.maximumLogSpacingCurvature, ...
            'peakJump',peakJump,'anchorSnapDisplacement',1-beforeSnap, ...
            'anchorOneExact',any(x==1)&&any(x==-1), ...
            'localPassed',localPassed,'resolutionPassed',resolutionPassed,'transferPassed',transferPassed, ...
            'meshAdmissible',score.admissible,'meshReasons',{score.rejectionReasons});
        items{end+1} = item; %#ok<AGROW>
        write_json(fullfile(outputDirectory,'partial_candidates.json'),items);
        fprintf('CURRENT_AXIS sigma=%.3g padding=%.2f ready=%d core=%.6g/%.6g front=%.6g ratio=%.9g snap=%.3e\n', ...
            sigma,padding,ready,coreCells,yCells,frontCells,item.ratio,item.anchorSnapDisplacement);
    end
end
report = struct('schemaVersion',1,'kind','current_axis_single_hop_frozen_screen', ...
    'provenance',provenance,'existingFallbackAudit',audit,'nativeFallbackCandidates',{nativeItems}, ...
    'exhaustedDepthNegativeAudit',negativeAudit,'items',{items}, ...
    'readyCount',nnz(cellfun(@(v)v.ready,items)), ...
    'pdeAdvanced',false,'poissonBuilt',false,'runtimeReferencesModified',false, ...
    'interpretation','Depth0 to1 measured from a globally rooted current platform; future reuse must persist depth1.');
save(fullfile(outputDirectory,'current_axis_report.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'current_axis_report.json'),report);
end

function value = local_quality(q)
value = q.quadratureWeightsStrictlyPositive && ...
    q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end

function write_json(filename,value)
fid=fopen(filename,'w'); assert(fid>=0); cleanup=onCleanup(@()fclose(fid));
fwrite(fid,jsonencode(value,PrettyPrint=true),'char');
end
