function report = ipm_perflab_verify_regrid_memory()
%IPM_PERFLAB_VERIFY_REGRID_MEMORY Small-grid exact comparison of factor release.
%   No PDE step, large-grid experiment, checkpoint write, or source edits.
%   Tests PCHIP, fourth-order and sixth-order physical transfer plus a
%   dynamic fourth-order quadratic-peak gauge on 65-by-33 states.

paths = {'legacy_second_order','high_order','sixth_order','high_order'};
transports = {'muscl_minmod','weno5_fd','weno7_fd','weno5_fd'};
integrators = {'ssprk3','ssprk54','rk6','ssprk54'};
transfers = {'pchip','high_order','sixth_order','high_order'};
cases = struct('spatialDiscretization',{},'rescalingMode',{},'identityGrid',{}, ...
    'checkpointPayloadExact',{},'checkpointSignatureExact',{}, ...
    'checkpointExceptTimestampExact',{},'auditExact',{}, ...
    'transferMetricsExact',{},'transferRhoExact',{}, ...
    'oldPoissonClass',{},'newPoissonClass',{}, ...
    'oldPoissonAbsentAtTransfer',{},'sourceCheckpointUnchanged',{});
for method = 1:numel(paths)
    opts = struct('nx',65,'ny',33,'xlim',[-4,4],'ymax',4, ...
        'gridMode','uniform','gridStretchAutomatic',false,'gridStretch',[0,0], ...
        'initialCondition',@smooth_density,'rescalingMode','physical', ...
        'symmetryMode','double_odd_omega', ...
        'spatialDiscretization',paths{method}, ...
        'transportScheme',transports{method}, ...
        'timeIntegrator',integrators{method}, ...
        'remeshTransferScheme',transfers{method}, ...
        'farBoundaryMode','dirichlet_zero','transportBoundaryMode','closed', ...
        'wallTransportMode','conservative_flux','adaptiveRemesh',false, ...
        'initialAnalyticRemesh',false,'saveResults',false,'makePlots',false, ...
        'livePlot',false,'writeVideo',false,'verbose',false, ...
        'storeSnapshots',false,'rangeStopTolerance',0.1, ...
        'minimumPeakPoints',2,'minimumLevelPoints',[2,2,2], ...
        'positiveWallNegativeTolerance',0.99,'oscillationTVTolerance',10);
    if method == 4
        opts.rescalingMode = 'dynamic';
        opts.lengthGauge = 'transport_anchor';
        opts.transportAnchorX = 1;
        opts.cOmegaGauge = 'wall_omega_quadratic_peak';
    end
    state = ipm.evolve.initialize(opts);
    log = ipm.output.initializeLog();
    [log,~] = ipm.output.record(log,state);
    cursor = struct('nextOutput',state.config.time.outputEvery, ...
        'nextCheckpoint',Inf,'lastCheckpointStep',state.step, ...
        'lastCheckpointCanonicalTime',state.scale.canonicalTime);
    source = ipm.output.makeCheckpoint(state,log,cursor);
    sourceCopy = source;
    for identityGrid = [true,false]
        x = state.ops.x;
        y = state.ops.y;
        if ~identityGrid
            x = x-0.001*sin(pi*x/4);
            y = y-0.001*sin(pi*y/4);
            x([1,end]) = state.ops.x([1,end]);
            y([1,end]) = state.ops.y([1,end]);
        end
        % These are explicit small-grid equivalence-test gates, not
        % proposed production acceptance thresholds.
        options = struct('minimumXCoreCells',0.01,'minimumYCoreCells',0.01, ...
            'maximumRhoXRelativeChange',0.02, ...
            'maximumMassRelativeDefect',1e-8, ...
            'maximumRelativeRangeViolation',0.01);
        if method == 1
            % Physical PCHIP does not impose conservative correction.
            options.maximumMassRelativeDefect = 1e-3;
        end
        [expected,expectedAudit,expectedFile] = ...
            ipm_gridlab_regrid_checkpoint(source,x,y,options);
        [actual,actualAudit,actualFile,memoryInfo] = ...
            ipm_perflab_regrid_checkpoint(source,x,y,options);
        [transferRho,~,transferMetrics] = ipm.remesh.transfer( ...
            state.rho,state.ops,expected.payload.state.config,struct('x',x,'y',y));
        item = struct('spatialDiscretization',paths{method}, ...
            'rescalingMode',opts.rescalingMode, ...
            'identityGrid',identityGrid, ...
            'checkpointPayloadExact',isequaln(actual.payload,expected.payload), ...
            'checkpointSignatureExact',isequaln(actual.signature,expected.signature), ...
            'checkpointExceptTimestampExact',isequaln( ...
                rmfield(actual,'createdUtc'),rmfield(expected,'createdUtc')), ...
            'auditExact',isequaln(actualAudit,expectedAudit), ...
            'transferMetricsExact',isequaln(memoryInfo.transferMetrics,transferMetrics), ...
            'transferRhoExact',isequaln(actual.payload.state.rho,transferRho), ...
            'oldPoissonClass',memoryInfo.oldPoissonClass, ...
            'newPoissonClass',memoryInfo.newPoissonClass, ...
            'oldPoissonAbsentAtTransfer',~memoryInfo.oldStateHasPoisson && ...
                ~memoryInfo.stateHasPoissonAtTransfer, ...
            'sourceCheckpointUnchanged',isequaln(source,sourceCopy));
        assert(strlength(expectedFile) == 0 && strlength(actualFile) == 0, ...
            'This test must not persist checkpoints.');
        assert(item.checkpointPayloadExact && item.checkpointSignatureExact && ...
            item.checkpointExceptTimestampExact && item.auditExact && ...
            item.transferMetricsExact && item.transferRhoExact && ...
            item.oldPoissonAbsentAtTransfer && item.sourceCheckpointUnchanged, ...
            'ipm:RegridMemoryEquivalence','Old-factor release changed regrid output.');
        cases(end+1) = item; %#ok<AGROW>
        fprintf('Regrid %s/%s identity=%d payload/audit/transfer exact, factor=%s\n', ...
            paths{method},opts.rescalingMode,identityGrid,memoryInfo.oldPoissonClass);
    end
end
report = struct('schemaVersion',1,'kind','ipm_regrid_old_factor_release_verification', ...
    'matlabVersion',version,'computer',computer, ...
    'computationalThreads',maxNumCompThreads,'grid',[33,65], ...
    'caseCount',numel(cases),'cases',cases,'allPassed',true, ...
    'pdeStepsTaken',0,'largeGridTestPerformed',false, ...
    'residentMemoryMeasured',false, ...
    'interpretation','exact small-grid transaction equivalence and old-factor lifetime evidence');
end

function rho = smooth_density(X,Y)
rho = -exp(-X.^2-Y.^2);
end
