function report=ipm_perflab_test_box_extension_tiny(outputDirectory)
%IPM_PERFLAB_TEST_BOX_EXTENSION_TINY Real native histories and endpoint failure.
assert(~isfolder(outputDirectory));mkdir(outputDirectory);assert(maxNumCompThreads==10);
opts=struct('nx',65,'ny',65,'xlim',[-6,6],'ymax',6,'gridMode','uniform', ...
 'initialCondition',@(X,Y)-exp(-(X.^2+Y.^2)), ...
 'symmetryMode','double_odd_omega','rescalingMode','dynamic', ...
 'dynamicScaleGeometry','isotropic','lengthGauge','transport_anchor','transportAnchorX',1, ...
 'cOmegaGauge','wall_omega_quadratic_peak','spatialDiscretization','high_order', ...
 'transportScheme','weno5_fd','timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
 'farBoundaryMode','green','physicalFinalTime',Inf,'finalTime',.01, ...
 'cfl',.25,'maxDt',.001,'minDt',1e-12,'maxSteps',64,'outputEvery',.002, ...
 'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
 'minimumPeakPoints',2,'minimumLevelPoints',[2 2 2],'oscillationTVTolerance',1e12, ...
 'storeSnapshots',false,'saveResults',true,'resultFile',fullfile(outputDirectory,'source_result.mat'), ...
 'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false, ...
 'checkpoint',struct('enabled',true,'file',fullfile(outputDirectory,'source.mat'),'every',Inf,'atExit',true));
sourceResult=ipm.solve(opts);assert(all(ipm.output.trustedMask(sourceResult)));
files=dir(fullfile(outputDirectory,'source_*_step*.mat'));assert(isscalar(files));sourceFile=fullfile(files.folder,files.name);
epoch=sourceResult.state.physicalTime;sourceStep=sourceResult.state.steps;clear sourceResult
shortDirectory=fullfile(outputDirectory,'short_protocol');
short=mesh_run_fresh_box_protocol(sourceFile,.75,.002,shortDirectory,struct('maximumSteps',64));
assert(short.completed&&short.shortIntervalComparisonPassed);clear short
referenceDirectory=fullfile(outputDirectory,'native_reference');mkdir(referenceDirectory);target=epoch+.006;
result=ipm.solve(struct('finalTime',Inf,'physicalFinalTime',target,'maxSteps',sourceStep+64, ...
 'saveResults',true,'resultFile',fullfile(referenceDirectory,'result.mat'), ...
 'checkpoint',struct('enabled',true,'file',fullfile(referenceDirectory,'checkpoint.mat'),'every',Inf,'atExit',true)),sourceFile);
assert(all(ipm.output.trustedMask(result))&&strcmp(result.state.stopReason,'physical_final_time'));clear result
files=dir(fullfile(referenceDirectory,'checkpoint_*_step*.mat'));assert(isscalar(files));referenceCP=fullfile(files.folder,files.name);
control=struct('absolutePhysicalTarget',target,'middleFraction',.875,'maximumAdditionalSteps',64);
positive=ipm_perflab_extend_box_to_reference(fullfile(shortDirectory,'protocol_report.json'), ...
 fullfile(referenceDirectory,'result.mat'),referenceCP,fullfile(outputDirectory,'positive'),control);
assert(positive.completed&&positive.passed&&positive.nativeCovarianceCheckedAtTarget);
assert(all(cellfun(@(b)b.audit.historyPrefixExact&&b.audit.runtimeReferencesExact&&b.audit.lineageExact&&b.audit.nativeTerminalPaired,positive.branches)));
control.maximumAdditionalSteps=1;negativeDirectory=fullfile(outputDirectory,'insufficient_steps');caught='';
try
 ipm_perflab_extend_box_to_reference(fullfile(shortDirectory,'protocol_report.json'), ...
  fullfile(referenceDirectory,'result.mat'),referenceCP,negativeDirectory,control);
catch exception
 caught=exception.identifier;
end
assert(strcmp(caught,'ipm:ThreeBoxBranchGate'));
failure=jsondecode(fileread(fullfile(negativeDirectory,'failure.json')));
assert(strcmp(failure.stage,'branch_gate')&&failure.dependentsStopped&& ...
 ~failure.audit.physicalEndpointStop&&failure.audit.physicalEndpointError>1e-11&& ...
 ~isfolder(fullfile(negativeDirectory,'crop_natural'))&&~isfolder(fullfile(negativeDirectory,'middle_natural')));
report=struct('kind','three_box_extension_tiny_validation','nodes',[65,65], ...
 'sourceFile',sourceFile,'absolutePhysicalTarget',target,'positive',positive, ...
 'insufficientStepsFailure',failure,'passed',true,'q512Executed',false);
save(fullfile(outputDirectory,'tiny_report.mat'),'report','-v7.3');
fid=fopen(fullfile(outputDirectory,'tiny_report.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fwrite(fid,jsonencode(report,PrettyPrint=true),'char');
fprintf('THREE_BOX_TINY_PASS endpoint_covariance=%d ladder=%d insufficient_steps_rejected=1\n', ...
 positive.actualEndpointCovariance.passed,positive.naturalEpsilonLadder.passed);
end
