function report=ipm_perflab_fresh_stage5_pairs(geometryFile,sourceReviewFile,outDir)
%IPM_PERFLAB_FRESH_STAGE5_PAIRS Original frozen-field score, fixed top three.
assert(maxNumCompThreads==10&&~isfolder(outDir));mkdir(outDir);
g=load(geometryFile,'rows','axes','original','report');p=g.original.policy;
review=jsondecode(fileread(sourceReviewFile));sourceFile=review.checkpointFile;
registration=struct('kind','fresh_stage5_fixed_top_three_frozen_pairs_v1', ...
    'geometryFile',geometryFile,'sourceReviewFile',sourceReviewFile,'sourceFile',sourceFile, ...
    'sourceStep',9205,'maximumPairs',3,'ySigma',[.35,.5], ...
    'ranking','original weakest dimensionless quality margin; stable X trial then Y order ties', ...
    'minimumXCoreCells',32,'minimumYCoreCells',32,'minimumXFrontCells',20, ...
    'maximumPeakJump',.002,'maximumCumulativePeakJump',.02, ...
    'maximumMassRelativeDefect',5e-12,'maximumRelativeRangeViolation',2e-4, ...
    'noLU',true,'noFlow',true,'noPDE',true,'nativeTransactionPerformed',false, ...
    'frozenInterpolationPerformed',true,'geometryCoreMeaning','original source feature intervals on candidate axes', ...
    'candidateNativeCoreFloorStillRequired',31,'originalFailureChanged',false);
write_json(fullfile(outDir,'registration.json'),registration);
issues=checkcode(which(mfilename),'-id');write_json(fullfile(outDir,'checkcode.json'),issues);
assert(isempty(issues),jsonencode(issues));
profile clear;profile on;timer=tic;
source=ipm.output.readCheckpoint(sourceFile);s=source.payload.state;
assert(s.step==9205&&isequaln(s.baseX,g.report.originalBaseX)&& ...
    isequaln(s.baseY,g.report.originalBaseY)&&isequaln(s.rescaling,g.report.originalRuntimeReferences)&& ...
    s.scale.canonicalTime==review.localCanonicalTime&&s.scale.physicalTime==review.localPhysicalTime&& ...
    strcmp(s.runMetadata.caseId,review.caseId)&&all(ipm.output.trustedMask(source.payload.log.history,s.config)));
Dx=ipm.mesh.fdMatrix(s.x,1,7);view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx,'source',s.rho*Dx','trusted',true);
assert(isequaln(ipm.diagnostics.meshFeatureIntervals(view),g.original.feature));
xi=find([g.rows.admissible]);yi=find([g.original.yTrials.admissible]);
assert(numel(xi)==10&&isequal([g.original.yTrials(yi).sigma],[.35,.5]));
indices=[];ranks=[];
for i=xi
 for j=yi
    indices(end+1,:)=[i,j]; %#ok<AGROW>
    ranks(end+1,1)=min(quality_margin(g.rows(i).quality,p.qualityLimits), ...
        quality_margin(g.original.yTrials(j).quality,p.qualityLimits)); %#ok<AGROW>
 end
end
[~,order]=sort(ranks,'descend');selected=indices(order(1:3),:);selectedRanks=ranks(order(1:3));
write_json(fullfile(outDir,'fixed_selection.json'),struct('indices',selected, ...
    'ranks',selectedRanks,'fullEnumeration',indices,'fullRanks',ranks));
snapshot=struct('datasetIndex',1,'sourceLabel',sourceFile,'trusted',true, ...
    'rho',s.rho,'x',s.x,'y',s.y,'scale',struct('Cx',exp(s.scale.logC_l), ...
    'Cy',exp(s.scale.logC_l),'Comega',exp(s.scale.logC_omega)), ...
    'canonicalTime',s.scale.canonicalTime,'physicalTime',s.scale.physicalTime);
dataset=struct('schemaVersion',2,'kind','ipm_frozen_grid_dataset','tag','actual_fresh9205_source', ...
    'snapshotCount',1,'snapshots',snapshot,'xLimits',s.x([1,end]),'yLimits',s.y([1,end])');
limits=rmfield(p.qualityLimits,{'minWeightToControlWidth','maxWeightToControlWidth'});
rows=struct([]);
for k=1:3
    i=selected(k,1);j=selected(k,2);x=g.axes{i};
    y=g.original.yTrials(j).equalizerInfo.positiveAxis(:)*g.original.anchor;
    y(1)=s.y(1);y(end)=s.y(end);
    assert(isequaln(ipm.mesh.quality(y,7,ipm.mesh.quadrature(y)),g.original.yTrials(j).quality));
    axes=struct('x',x,'y',y,'unchanged',false,'xIndex',i,'yIndex',j, ...
        'predictedCells',[g.rows(i).coreCells,g.original.yTrials(j).coreCells,g.rows(i).frontCells], ...
        'quality',struct('x',g.rows(i).quality,'y',g.original.yTrials(j).quality));
    score=ipm_gridlab_score_frozen_pair(dataset,x,y,struct('trustedOnly',true, ...
        'meshLimits',limits,'minimumXCoreCells',32,'minimumYCoreCells',32,'minimumXFrontCells',20));
    a=score.aggregate;
    gates=struct('scoreMeshAdmissible',score.admissible, ...
        'coreX',a.minimumXCoreCells>=32-1e-6,'coreY',a.minimumYCoreCells>=32-1e-6, ...
        'front',a.minimumXLeftFrontCells>=20-1e-6, ...
        'peakJump',a.worst.rhoXMaximumRelativeChange<=.002, ...
        'cumulativePeakJump',review.cumulativeAbsolutePeakJump+a.worst.rhoXMaximumRelativeChange<=.02, ...
        'mass',a.worst.conservationRelativeDefect<=5e-12, ...
        'range',a.worst.relativeRangeViolation<=2e-4, ...
        'localQuadratureX',local_quality(score.quality.x), ...
        'localQuadratureY',local_quality(score.quality.y));
    ready=all(structfun(@(v)islogical(v)&&isscalar(v)&&v,gates));
    candidate=struct('kind','campaign_bounded_paired_candidate_v1','transactionReady',ready, ...
        'candidateX',x,'candidateY',y,'anchorExact',any(x==g.original.anchor)&&any(x==-g.original.anchor), ...
        'completePairScoredInOriginalUnits',true,'currentTransactionNodeCountSupported',true, ...
        'controls',struct('targetXCoreCells',32,'targetYCoreCells',32,'minimumXFrontCells',20), ...
        'pairScore',score,'nativeTransactionPerformed',false,'pdeAdvanced',false);
    assert(candidate.anchorExact&&numel(x)==numel(s.x)&&numel(y)==numel(s.y)&& ...
        isequal(x([1,end]),s.x([1,end]))&&isequal(y([1,end]),s.y([1,end])));
    policy=p;priorJump=review.cumulativeAbsolutePeakJump;
    candidateFile=fullfile(outDir,sprintf('candidate_%02d.mat',k));
    save(candidateFile,'candidate','axes','policy','sourceFile','priorJump','gates','-v7.3');
    write_json(fullfile(outDir,sprintf('pair_%02d.json',k)),struct('candidateFile',candidateFile, ...
        'xTrialIndex',i,'yTrialIndex',j,'ySigma',g.original.yTrials(j).sigma, ...
        'rankingMargin',selectedRanks(k),'readyForNativeTransactionTest',ready, ...
        'nativeTransactionPerformed',false,'gates',gates,'aggregate',a));
    row=struct('candidateFile',candidateFile,'xTrialIndex',i,'yTrialIndex',j, ...
        'rankingMargin',selectedRanks(k),'passed',ready,'gates',gates,'aggregate',a);
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
end
report=registration;report.sourceNativeSignatureValidated=true;report.originalFeaturesExactlyPaired=true;
report.originalBaseRuntimeReferencesAndClocksExact=true;report.rows=rows;
report.readyCount=nnz([rows.passed]);report.sourcePayloadUnchanged=isequaln(s,source.payload.state);
assert(report.sourcePayloadUnchanged);report.wallSeconds=toc(timer);report.completed=true;
profile off;profileInfo=profile('info');names={profileInfo.FunctionTable.FunctionName};
for forbidden={'ipm.mesh.build','ipm.output.restoreCheckpoint','ipm.evolve.flow', ...
        'ipm.field.velocity','ipm.field.poisson','ipm.evolve.advance','ipm.solve','ipm.remesh.transfer'}
    assert(~any(strcmp(names,forbidden{1})));
end
save(fullfile(outDir,'report.mat'),'report','profileInfo','-v7.3');
write_json(fullfile(outDir,'report.json'),report);
fprintf('FRESH_STAGE5_PAIRS_COMPLETE ready=%d/3 noLU=1 nativeTransactions=0\n',report.readyCount);
end
function margin=quality_margin(q,l)
v=[q.maximumAdjacentCellRatio,q.maximumLogSpacingCurvature,q.minimumStencilRcond, ...
    q.minimumQuadratureWeightRatio,q.minimumQuadratureWeightToControlWidthRatio,q.maximumQuadratureWeightToControlWidthRatio];
assert(all(isfinite(v))&&q.quadratureWeightsStrictlyPositive);
margin=min([l.maxAdjacentCellRatio/v(1),l.maxLogSpacingCurvature/max(v(2),realmin), ...
    v(3)/l.minStencilRcond,v(4)/l.minQuadratureWeightRatio, ...
    v(5)/l.minWeightToControlWidth,l.maxWeightToControlWidth/v(6)]);
end
function yes=local_quality(q)
yes=q.quadratureWeightsStrictlyPositive&&q.minimumQuadratureWeightToControlWidthRatio>=.35&& ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
