function report = ipm_perflab_screen_anchor_transport(locationScreenFile,outputFile)
%IPM_PERFLAB_SCREEN_ANCHOR_TRANSPORT Read-only row-anchor algebraic CFL screen.
%   Uses paired saved v2 velocities/axes, never builds ops or a Poisson LU,
%   never interpolates/evolves density, never changes the production CFL.
%   b_x=alpha(Y)*X, alpha=c_l+U1(X=1,Y), remainder=V1-b_x.

assert(nargin == 2 && ~isfile(outputFile),'Pass existing screen JSON and a new MAT path.');
location = jsondecode(fileread(locationScreenFile));
records = cell(1,numel(location.records));
for index = 1:numel(location.records)
    prior = location.records(index);
    r = ipm.output.validate(prior.resultFile);
    assert(all(ipm.output.trustedMask(r)),'Only a fully trusted saved result is screened.');
    assert(strcmp(r.config.transport.spatialDiscretization,'high_order') && ...
        strcmp(r.config.scaling.dynamicScaleGeometry,'isotropic') && ...
        strcmp(r.config.scaling.lengthGauge,'transport_anchor') && ...
        strcmp(r.config.physics.symmetryMode,'double_odd_omega'), ...
        'This experiment requires the maintained fourth-order isotropic anchor gauge.');
    assert(r.scale.rates.cr == 0 && r.config.scaling.transportAnchorX == 1, ...
        'The proposed exact cancellation assumes zero translation and anchor X=1.');
    x = r.grid.x(:).';
    y = r.grid.y(:);
    anchor = find(x == 1);
    if isscalar(anchor)
        anchorVelocity = r.state.velocity.x(:,anchor);
        anchorEvaluation = 'exact_grid_node';
    else
        % Same public interpolation used by the maintained transport-anchor
        % gauge, applied independently to every height. No density remap.
        anchorVelocity = interp1(x,r.state.velocity.x.',1,'linear').';
        anchorEvaluation = 'linear_existing_gauge_evaluation';
    end
    hx = control_width(x);
    hy = control_width(y);
    X = repmat(x,numel(y),1);
    Y = repmat(y,1,numel(x));
    cL = r.scale.rates.cx;
    v1 = r.state.velocity.x+cL*X+r.scale.rates.cr;
    v2 = r.state.velocity.y+r.scale.rates.cy*Y;
    alpha = cL+anchorVelocity;
    b1 = alpha.*X;
    remainder1 = v1-b1;
    originalRate = abs(v1)./hx+abs(v2)./hy;
    remainderRate = abs(remainder1)./hx+abs(v2)./hy;
    splitRate = abs(b1)./hx;
    selectorOps = struct('spatialDiscretization','high_order','hx',hx,'hy',hy);
    selectorFlow = struct('transportU1',v1,'transportU2',v2);
    scale = struct('logC_omega',log(r.scale.Comega),'logC_l',log(r.scale.Cx), ...
        'canonicalTime',r.state.canonicalTime,'physicalTime',r.state.physicalTime);
    [~,~,originalSelection] = ipm.evolve.selectTimestep( ...
        selectorFlow,scale,selectorOps,r.config.time);
    selectorFlow.transportU1 = remainder1;
    [~,~,remainderSelection] = ipm.evolve.selectTimestep( ...
        selectorFlow,scale,selectorOps,r.config.time);
    selectorExact = isequal(originalSelection.rate,max(originalRate,[],'all')) && ...
        isequal(originalSelection.rate,prior.globalRate) && ...
        isequal(remainderSelection.rate,max(remainderRate,[],'all'));
    assert(selectorExact,'Saved-endpoint original rate did not exactly match maintained selector.');
    reconstructionDefect = max(abs((remainder1+b1)-v1),[],'all');
    if isscalar(anchor)
        anchorDefect = max(abs(remainder1(:,anchor)));
    else
        anchorDefect = max(abs(interp1(x,remainder1.',1,'linear')));
    end
    assert(anchorDefect <= 64*eps(max([1;abs(anchorVelocity)])), ...
        'Row-anchor remainder exceeded floating-point interpolation roundoff.');
    alphaPrime = ipm.mesh.fdMatrix(y,1,7)*alpha;
    intervalSlope = diff(alpha)./diff(y);
    g = r.history.gauge;
    m = r.history.mesh;
    a = g.omegaGaugeQuadraticPeakX(end);
    wx = m.trackedWallCoreWidth(end);
    wy = m.trackedVerticalCoreWidth(end);
    near = abs(abs(X)-a) <= 3*wx & Y <= 3*wy;
    lab = abs(X) <= 2 & Y <= 2;
    aboveCore = Y >= 3*wy;
    nearWallRows = y <= 3*wy;
    signs = sign(alpha(alpha~=0));
    signChanges = nnz(signs(2:end)~=signs(1:end-1));
    departure = struct('dt',{},'minimumBackwardScale',{},'maximumBackwardScale',{}, ...
        'maximumDisplacementInControlWidths',{},'outsideDomainNodes',{});
    for dt = [0.004,0.008,0.016]
        backwardScale = exp(-alpha*dt);
        departureX = backwardScale.*X;
        item = struct('dt',dt,'minimumBackwardScale',min(backwardScale), ...
            'maximumBackwardScale',max(backwardScale), ...
            'maximumDisplacementInControlWidths',max(abs(departureX-X)./hx,[],'all'), ...
            'outsideDomainNodes',nnz(departureX < x(1) | departureX > x(end)));
        departure(end+1) = item; %#ok<AGROW>
    end
    record = struct('resultFile',prior.resultFile,'tau',r.state.canonicalTime, ...
        'physicalTime',r.state.physicalTime,'grid',[numel(y),numel(x)], ...
        'anchorEvaluation',anchorEvaluation,'nearestNodeAnchorDistance',min(abs(x-1)), ...
        'cL',cL,'alphaMinimum',min(alpha),'alphaMaximum',max(alpha), ...
        'alphaWall',alpha(1),'alphaTop',alpha(end), ...
        'alphaTopMinusCL',alpha(end)-cL, ...
        'alphaPositiveRows',nnz(alpha>0),'alphaNegativeRows',nnz(alpha<0), ...
        'alphaZeroRows',nnz(alpha==0),'alphaSignChanges',signChanges, ...
        'alphaNonfiniteRows',nnz(~isfinite(alpha)), ...
        'alphaNearWallMaximumAbs',max(abs(alpha(nearWallRows))), ...
        'alphaMaximumAbsDerivative',max(abs(alphaPrime)), ...
        'alphaMaximumAbsLogYDerivative',max(abs(y.*alphaPrime)), ...
        'alphaMaximumAbsIntervalSlope',max(abs(intervalSlope)), ...
        'alphaMaximumAdjacentJump',max(abs(diff(alpha))), ...
        'alphaDecreasingIntervals',nnz(diff(alpha)<0), ...
        'globalOriginalRate',originalSelection.rate, ...
        'globalRemainderRate',remainderSelection.rate, ...
        'rateReductionFactor',originalSelection.rate/remainderSelection.rate, ...
        'originalCflDt',originalSelection.dtCfl, ...
        'hypotheticalRemainderCflDt',remainderSelection.dtCfl, ...
        'unchangedMaximumDt',r.config.time.maxDt, ...
        'globalSplitTransportRate',max(splitRate,[],'all'), ...
        'globalOriginalXOnlyRate',max(abs(v1)./hx,[],'all'), ...
        'globalRemainderXOnlyRate',max(abs(remainder1)./hx,[],'all'), ...
        'globalUnchangedYOnlyRate',max(abs(v2)./hy,[],'all'), ...
        'nearPeakOriginalRate',max(originalRate(near)), ...
        'nearPeakRemainderRate',max(remainderRate(near)), ...
        'labOriginalRate',max(originalRate(lab)), ...
        'labRemainderRate',max(remainderRate(lab)), ...
        'wallOriginalRate',max(originalRate(1,:)), ...
        'wallRemainderRate',max(remainderRate(1,:)), ...
        'aboveCoreRemainderRate',max(remainderRate(aboveCore)), ...
        'originalTopCells',top_cells(originalRate,v1,v2,x,y,r.state.omega,a,wx,wy), ...
        'remainderTopCells',top_cells(remainderRate,remainder1,v2,x,y,r.state.omega,a,wx,wy), ...
        'anchorRemainderMaximumAbs',anchorDefect, ...
        'algebraicReconstructionMaximumAbs',reconstructionDefect, ...
        'algebraicReconstructionRelative',reconstructionDefect/max(max(abs(v1),[],'all'),eps), ...
        'maintainedSelectorRateExact',selectorExact, ...
        'recordedAcceptedStepRate',r.history.common.transportRate(end), ...
        'alphaProfile',struct('y',y,'alpha',alpha,'alphaPrime',alphaPrime, ...
        'originalRowRate',max(originalRate,[],2), ...
        'remainderRowRate',max(remainderRate,[],2)), ...
        'frozenCharacteristicDeparture',departure);
    records{index} = record;
    fprintf(['ANCHOR_TRANSPORT tau%.12g original=%.9g remainder=%.9g reduction=%.4g ' ...
        'alpha=[%.6g,%.6g] wall=%.3g negRows%d nearRate=%.8g->%.8g\n'], ...
        record.tau,record.globalOriginalRate,record.globalRemainderRate, ...
        record.rateReductionFactor,record.alphaMinimum,record.alphaMaximum, ...
        record.alphaWall,record.alphaNegativeRows, ...
        record.nearPeakOriginalRate,record.nearPeakRemainderRate);
    % Release full result/field arrays before reading the next result.
    clear r X Y v1 v2 b1 remainder1 originalRate remainderRate splitRate departureX;
end
report = struct('schemaVersion',1,'kind','ipm_row_anchor_transport_algebraic_screen', ...
    'sourceLocationScreen',locationScreenFile,'records',[records{:}], ...
    'pdeAdvanced',false,'poissonOperatorBuilt',false,'densityRemapped',false, ...
    'productionCflChanged',false, ...
    'interpretation',['An exact continuous transport-velocity decomposition, not an ' ...
    'equivalent discrete WENO update or an authorization for a larger explicit step. ' ...
    'State-dependent alpha, splitting order, Y coupling and nonuniform remap errors remain untested.']);
save(outputFile,'report');
[directory,name] = fileparts(outputFile);
file = fopen(fullfile(directory,[name,'.json']),'w');
assert(file >= 0,'Cannot write algebraic screen JSON.');
cleanup = onCleanup(@()fclose(file));
fprintf(file,'%s\n',jsonencode(report,'PrettyPrint',true));
end

function width = control_width(axis)
width = zeros(size(axis));
width([1,end]) = [axis(2)-axis(1),axis(end)-axis(end-1)]/2;
width(2:end-1) = (axis(3:end)-axis(1:end-2))/2;
end

function cells = top_cells(rate,v1,v2,x,y,source,peakX,wx,wy)
[values,indices] = maxk(rate(:),10);
[iy,ix] = ind2sub(size(rate),indices);
cells = struct('x',reshape(x(ix),[],1),'y',y(iy),'rate',values, ...
    'horizontalVelocity',v1(indices),'verticalVelocity',v2(indices), ...
    'sourceRelativeToPeak',abs(source(indices))/max(abs(source),[],'all'), ...
    'horizontalCoreDistance',abs(abs(reshape(x(ix),[],1))-peakX)/wx, ...
    'verticalCoreDistance',y(iy)/wy);
end
