function report = ipm_perflab_bridge_threads(sourceFile,requestedFile,targetThreads)
%IPM_PERFLAB_BRIDGE_THREADS Strict zero-time checkpoint branch reserialization.
%   Validate/restore SOURCEFILE at its established 10-thread environment,
%   preserve state/config/log/cursor exactly except restore provenance, and
%   use the existing make/write/readCheckpoint path at TARGETTHREADS.
%   No solver code or signature formula changes, no PDE step, no replacement
%   of SOURCEFILE. The calling environment is restored to 10 threads.

assert(nargin == 3,'Pass source, output stem, and target thread count.');
validateattributes(targetThreads,{'numeric'}, ...
    {'scalar','integer','positive','finite'});
maxNumCompThreads(10);
threadCleanup = onCleanup(@()maxNumCompThreads(10));
source = ipm.output.readCheckpoint(sourceFile);
[state,log,cursor] = ipm.output.restoreCheckpoint(source,struct());
maxNumCompThreads(targetThreads);
bridged = ipm.output.makeCheckpoint(state,log,cursor);
sourceState = source.payload.state;
bridgedState = bridged.payload.state;
stateExceptMetadataExact = isequaln(rmfield(sourceState,'runMetadata'), ...
    rmfield(bridgedState,'runMetadata'));
logExact = isequaln(source.payload.log,bridged.payload.log);
cursorExact = isequaln(source.payload.cursor,bridged.payload.cursor);
assert(stateExceptMetadataExact && logExact && cursorExact, ...
    'ipm:ThreadBridgePayload','Zero-time bridge changed mathematical payload.');
metadataNames = union(fieldnames(sourceState.runMetadata), ...
    fieldnames(bridgedState.runMetadata));
changedMetadata = {};
for index = 1:numel(metadataNames)
    name = metadataNames{index};
    if ~isfield(sourceState.runMetadata,name) || ...
            ~isfield(bridgedState.runMetadata,name) || ...
            ~isequaln(sourceState.runMetadata.(name),bridgedState.runMetadata.(name))
        changedMetadata{end+1} = name; %#ok<AGROW>
    end
end
allowedMetadata = {'resumeCount','resumedFromStep', ...
    'resumedFromCanonicalTime','resumedFromPhysicalTime', ...
    'resumedFromCheckpoint','caseMetadata','resultFile','videoFile'};
assert(all(ismember(changedMetadata,allowedMetadata)), ...
    'ipm:ThreadBridgeMetadata','Unexpected metadata change in thread bridge.');
[written,targetFile] = ipm.output.writeCheckpoint(bridged,requestedFile);
reloaded = ipm.output.readCheckpoint(targetFile);
readbackExact = isequaln(written,reloaded);
assert(readbackExact,'ipm:ThreadBridgeReadback', ...
    'Strict target-thread checkpoint readback changed the written artifact.');
% Re-evaluate the frozen flow at the target setting; it is telemetry only
% and is not substituted into any mathematical checkpoint field.
[targetRate,targetFlow] = ipm.evolve.flow(state.rho,state.ops,state.scale);
flowExact = isequaln(targetFlow,state.flow) && ...
    isequaln(targetRate,state.rhsCache.rhoRate);
report = struct('schemaVersion',1,'kind','ipm_zero_time_thread_bridge', ...
    'createdUtc',char(datetime('now','TimeZone','UTC', ...
        'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z''')), ...
    'sourceFile',char(sourceFile),'targetFile',char(targetFile), ...
    'sourceThreads',10,'targetThreads',maxNumCompThreads, ...
    'matlabVersion',version,'computer',computer, ...
    'canonicalTime',state.scale.canonicalTime, ...
    'physicalTime',state.scale.physicalTime,'acceptedStep',state.step, ...
    'pdeStepsTaken',0,'stateExceptRestoreMetadataExact',stateExceptMetadataExact, ...
    'logExact',logExact,'cursorExact',cursorExact, ...
    'strictReadbackExact',readbackExact,'frozenFlowExact',flowExact, ...
    'changedMetadataFields',{changedMetadata}, ...
    'signatureImplementationChanged',false, ...
    'requiresTargetThreadEnvironmentOnRead',true);
provenanceFile = [char(targetFile),'.thread_provenance.json'];
assert(~isfile(provenanceFile),'Refusing to overwrite thread provenance.');
file = fopen(provenanceFile,'w');
assert(file >= 0,'Unable to open thread-provenance output.');
fileCleanup = onCleanup(@()fclose(file));
fprintf(file,'%s\n',jsonencode(report,'PrettyPrint',true));
clear fileCleanup;
report.provenanceFile = provenanceFile;
maxNumCompThreads(10);
report.restoredThreads = maxNumCompThreads;
fprintf('Thread bridge %d -> %d: payload exact=%d, readback exact=%d, flow exact=%d\n', ...
    report.sourceThreads,report.targetThreads,stateExceptMetadataExact, ...
    readbackExact,flowExact);
fprintf('  %s\n',targetFile);
clear threadCleanup;
end
