function report = ipm_perflab_screen_platform_budget(currentResultFile,rootResultFile,outputDirectory)
%IPM_PERFLAB_SCREEN_PLATFORM_BUDGET Frozen-field parameter screen, no PDE/LU.
% Calls the existing maintained research design/platform/pair-score paths.
% Predictions use only saved scalar histories and never fabricate a field.
assert(~exist(outputDirectory,'dir'),'Pass a new output directory.');
variables = whos('-file',currentResultFile);
assert(any(strcmp({variables.name},'result')), ...
    'Pass a saved v2 result, never a checkpoint requiring operator restore.');
mkdir(outputDirectory);
current = ipm.output.validate(currentResultFile);
assert(all(ipm.output.trustedMask(current)),'Current full history must be trusted.');
assert(current.config.schemaVersion==4 && ...
    strcmp(current.config.scaling.lengthGauge,'transport_anchor') && ...
    strcmp(current.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak'));
frozen = struct('currentResultFile',currentResultFile,'rootResultFile',rootResultFile, ...
    'canonicalTime',current.state.canonicalTime,'physicalTime',current.state.physicalTime, ...
    'sourceSteps',current.state.steps,'grid',[numel(current.grid.x),numel(current.grid.y)], ...
    'positiveFineCells',[96,112,128,144,160],'anchorFineCellFractions',[.85,.90,.95], ...
    'targetXCoreCells',21,'targetYCoreCells',21,'minimumXFrontCells',20, ...
    'resolutionPadding',1.10,'verticalResolutionPadding',1.15,'xEqualizationSigma',.5, ...
    'existingDesignHelper',which('mesh_design_stage'), ...
    'existingPlatformHelper',which('mesh_platform_candidate'), ...
    'pdeAdvanced',false,'poissonOperatorsBuilt',false,'regridCommitted',false, ...
    'predictionPolicy','Saved scalar-history extrapolation only; no future field or PDE claim.');
write_json(fullfile(outputDirectory,'frozen_screen_controls.json'),frozen);
controls = struct('targetXCoreCells',21,'targetYCoreCells',21, ...
    'minimumXFrontCells',20,'xEqualizationSigma',.5);
designDirectory = fullfile(outputDirectory,'terminal_design');
designReport = mesh_design_stage(currentResultFile,rootResultFile,designDirectory,controls);
data = load(designReport.designFile,'design');
design = data.design;
assert(isscalar(design.profiles.records),'This screen must freeze one terminal field.');
record = design.profiles.records(1);
width = record.safetyCoreWidthLeft+record.safetyCoreWidthRight;
coreInterval = record.safetyCoreCenter+[-record.safetyCoreWidthLeft,record.safetyCoreWidthRight];
frontInterval = record.leftFrontCenter+[-1,1]*record.leftFrontHalfWidth;
peak = current.history.gauge.omegaGaugeQuadraticPeakX(end);
feature = struct('quadraticPeakX',peak,'profilePeakCenter',record.peakCenter, ...
    'safetyCoreCenter',record.safetyCoreCenter,'coreWidth',width, ...
    'coreInterval',coreInterval,'frontInterval',frontInterval,'yCoreWidth',record.yCoreWidth, ...
    'anchorGapOverCoreWidth',(1-peak)/width, ...
    'anchorGapOverCoreWidthUsingCoreCenter',(1-record.safetyCoreCenter)/width, ...
    'historyCoreWidth',current.history.mesh.trackedWallCoreWidth(end), ...
    'currentHistoryCoreCells',[current.history.mesh.coreGridPoints(end), ...
        current.history.mesh.verticalCoreGridPoints(end)]);
trend = scalar_history_prediction(current,feature);
items = {};
for fine = frozen.positiveFineCells
    for fraction = frozen.anchorFineCellFractions
        platform = struct('positiveFineCells',fine,'anchorFineCellFraction',fraction, ...
            'resolutionPadding',1.10,'verticalResolutionPadding',1.15);
        file = fullfile(outputDirectory,sprintf('candidate_fine%03d_anchor%02d.mat',fine,round(100*fraction)));
        requestedSpacing = min([width/21,2*record.leftFrontHalfWidth/20])/1.10;
        anchorCell = round(fine*fraction);
        requestedInterval = 1+[-anchorCell,fine-anchorCell]*requestedSpacing;
        item = struct('positiveFineCells',fine,'anchorFraction',fraction, ...
            'candidateFile',file,'completed',false,'ready',false, ...
            'failureIdentifier','','failureMessage','','seconds',NaN, ...
            'coreX',NaN,'coreY',NaN,'frontCells',NaN,'maximumAdjacentRatioX',NaN, ...
            'maximumAdjacentRatioY',NaN,'maximumLogCurvatureX',NaN, ...
            'minimumStencilRcondX',NaN,'fineInterval',requestedInterval, ...
            'fineSpacing',requestedSpacing,'fineCoreCoverageFraction',NaN, ...
            'fineFrontCoverageFraction',NaN,'leftCoreMarginInCoreWidths',NaN, ...
            'leftFrontMarginInCoreWidths',NaN,'anchorGapOverCoreWidth',feature.anchorGapOverCoreWidth, ...
            'localQuadraturePassed',false,'resolutionPassed',false,'transferPassed',false, ...
            'meshAdmissible',false,'meshRejectionReasons',{{}}, ...
            'rhoXMaximumRelativeChange',NaN,'conservationRelativeDefect',NaN, ...
            'relativeRangeViolation',NaN,'scalarPrediction',struct());
        timer = tic;
        try
            candidate = mesh_platform_candidate(designReport.designFile, ...
                designReport.referenceFile,file,platform);
            item.completed = true;
            item.ready = candidate.transactionReady;
            item.fineInterval = candidate.fineInterval;
            item.fineSpacing = candidate.requestedFineSpacing;
            item.localQuadraturePassed = candidate.localQuadraturePassed;
            item.resolutionPassed = candidate.resolutionPassed;
            item.transferPassed = candidate.transferPassed;
            score = candidate.pairScore;
            item.meshAdmissible = score.admissible;
            item.meshRejectionReasons = score.rejectionReasons;
            item.maximumAdjacentRatioX = score.quality.x.maximumAdjacentCellRatio;
            item.maximumAdjacentRatioY = score.quality.y.maximumAdjacentCellRatio;
            item.maximumLogCurvatureX = score.quality.x.maximumLogSpacingCurvature;
            item.minimumStencilRcondX = score.quality.x.minimumStencilRcond;
            if isfield(score.aggregate,'minimumXCoreCells')
                item.coreX = score.aggregate.minimumXCoreCells;
                item.coreY = score.aggregate.minimumYCoreCells;
                item.frontCells = score.aggregate.minimumXLeftFrontCells;
                item.rhoXMaximumRelativeChange = score.aggregate.worst.rhoXMaximumRelativeChange;
                item.conservationRelativeDefect = score.aggregate.worst.conservationRelativeDefect;
                item.relativeRangeViolation = score.aggregate.worst.relativeRangeViolation;
            end
            item.fineCoreCoverageFraction = interval_overlap_fraction(coreInterval,candidate.fineInterval);
            item.fineFrontCoverageFraction = interval_overlap_fraction(frontInterval,candidate.fineInterval);
            item.leftCoreMarginInCoreWidths = (coreInterval(1)-candidate.fineInterval(1))/width;
            item.leftFrontMarginInCoreWidths = (frontInterval(1)-candidate.fineInterval(1))/width;
            item.scalarPrediction = predicted_platform_margin(candidate,feature,trend);
        catch exception
            item.failureIdentifier = exception.identifier;
            item.failureMessage = exception.message;
            if ~startsWith(exception.identifier,'ipm:')
                save(fullfile(outputDirectory,'unexpected_failure.mat'),'item','exception');
                rethrow(exception);
            end
        end
        item.seconds = toc(timer);
        items{end+1} = item; %#ok<AGROW>
        save(fullfile(outputDirectory,'screen_partial.mat'),'frozen','feature','trend','items','designReport');
        write_json(fullfile(outputDirectory,'screen_partial.json'),items);
        fprintf('PLATFORM_SCREEN fine=%d fraction=%.2f ready=%d core=%.6g/%.6g front=%.6g ratio=%.9g leftMargin=%.6g failure=%s\n', ...
            fine,fraction,item.ready,item.coreX,item.coreY,item.frontCells, ...
            item.maximumAdjacentRatioX,item.leftCoreMarginInCoreWidths,item.failureIdentifier);
    end
end
ready = cellfun(@(v)v.ready,items);
report = struct('schemaVersion',1,'kind','frozen_platform_cell_budget_screen', ...
    'frozen',frozen,'feature',feature,'historyScalarPrediction',trend, ...
    'designReport',designReport,'items',{items},'readyCount',nnz(ready), ...
    'allTrialsAttempted',numel(items)==numel(frozen.positiveFineCells)*numel(frozen.anchorFineCellFractions), ...
    'allTrialsCompleted',all(cellfun(@(v)v.completed,items)), ...
    'numberOfTrials',numel(items),'pdeAdvanced',false,'poissonOperatorsBuilt',false, ...
    'hardGatesChanged',false,'transactionPerformed',false, ...
    'interpretation','Ready means frozen field/axis/transfer gates only; no future PDE or restart approval.');
save(fullfile(outputDirectory,'platform_screen_report.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'platform_screen_report.json'),report);
end

function trend = scalar_history_prediction(result,feature)
h = result.history;
t = h.common.canonicalTau(:);
mask = h.mesh.remeshCount(:)==h.mesh.remeshCount(end) & t>=t(end)-.35;
indices = find(mask);
[~,uniqueIndex] = unique(t(indices),'stable'); indices = indices(uniqueIndex);
assert(numel(indices)>=4,'Need four unique same-grid scalar history rows.');
times = t(indices)-t(end);
peak = h.gauge.omegaGaugeQuadraticPeakX(indices);
width = h.mesh.trackedWallCoreWidth(indices);
assert(all(width>0));
fitPeak = polyfit(times,peak(:),1);
fitLogWidth = polyfit(times,log(width(:)),1);
future = [0,.1,.2,.4];
predictedPeak = feature.quadraticPeakX+fitPeak(1)*future;
predictedWidth = feature.coreWidth*exp(fitLogWidth(1)*future);
trend = struct('kind','same_grid_scalar_extrapolation_not_PDE', ...
    'historyRows',indices,'sampleCount',numel(indices), ...
    'historyCanonicalInterval',[t(indices(1)),t(indices(end))], ...
    'remeshCount',h.mesh.remeshCount(end),'peakSlope',fitPeak(1), ...
    'logCoreWidthSlope',fitLogWidth(1), ...
    'peakFitResidualRms',sqrt(mean((peak(:)-polyval(fitPeak,times)).^2)), ...
    'logWidthFitResidualRms',sqrt(mean((log(width(:))-polyval(fitLogWidth,times)).^2)), ...
    'deltaTau',future,'predictedPeakX',predictedPeak,'predictedCoreWidth',predictedWidth, ...
    'predictedAnchorGapOverCoreWidth',(1-predictedPeak)./predictedWidth, ...
    'caveat','Scalar continuation of recent trends, not a future field, mesh score, or proof.');
end

function value = predicted_platform_margin(candidate,feature,trend)
% Evaluate scalar geometry only. No transported or deformed rho is created.
ratio = trend.predictedCoreWidth/feature.coreWidth;
peakShift = trend.predictedPeakX-feature.quadraticPeakX;
leftWidth = feature.safetyCoreCenter-feature.coreInterval(1);
rightWidth = feature.coreInterval(2)-feature.safetyCoreCenter;
center = feature.safetyCoreCenter+peakShift;
coreLeft = center-leftWidth*ratio;
coreRight = center+rightWidth*ratio;
fixedFineLeftMargin = (coreLeft-candidate.fineInterval(1))./trend.predictedCoreWidth;
fixedFineRightMargin = (candidate.fineInterval(2)-coreRight)./trend.predictedCoreWidth;
% A future regenerated platform would keep today's spacing/core ratio.
% The front/core ratio may change; this assumption is explicitly recorded.
futureSpacing = candidate.requestedFineSpacing*ratio;
anchorCell = round(candidate.controls.positiveFineCells*candidate.controls.anchorFineCellFraction);
futureFineLeft = 1-anchorCell*futureSpacing;
requiredAnchorCellsForCore = (1-coreLeft)./futureSpacing;
value = struct('kind','scalar_geometry_prediction_only','deltaTau',trend.deltaTau, ...
    'predictedCoreLeft',coreLeft,'predictedCoreRight',coreRight, ...
    'fixedCandidateLeftMarginInPredictedCoreWidths',fixedFineLeftMargin, ...
    'fixedCandidateRightMarginInPredictedCoreWidths',fixedFineRightMargin, ...
    'regeneratedFineLeftAssumingFixedSpacingToCoreRatio',futureFineLeft, ...
    'regeneratedLeftMarginInPredictedCoreWidths',(coreLeft-futureFineLeft)./trend.predictedCoreWidth, ...
    'requiredAnchorFineCellsForCore',requiredAnchorCellsForCore, ...
    'availableAnchorFineCells',anchorCell, ...
    'assumptions',{{'recent same-grid scalar slopes persist', ...
        'core asymmetry fractions remain fixed','front/core spacing constraint ratio remains fixed'}}, ...
    'futureFrozenScoreOrPdePerformed',false);
end

function fraction = interval_overlap_fraction(a,b)
fraction = max(0,min(a(2),b(2))-max(a(1),b(1)))/diff(a);
end

function write_json(filename,value)
fid = fopen(filename,'w'); assert(fid>=0,'Cannot write screen report.');
cleanup = onCleanup(@()fclose(fid));
fwrite(fid,jsonencode(value,PrettyPrint=true),'char');
end
