function ipm_perflab_window_validate(m)
% Research persistence boundary; cannot reconstruct discarded raw data.
assert(isstruct(m) && isscalar(m),'ipm:ResearchWindowState','Scalar state required.');
names={'kind';'version';'windowWidth';'rawCapacity';'bucketCapacity'; ...
    'bucketWidth';'origin';'epoch';'raw';'rawCount';'bucketCount';'buckets'};
assert(isequal(sort(fieldnames(m)),sort(names)), ...
    'ipm:ResearchWindowState','Unexpected state fields could hide unbounded data.');
assert(isequal(m.kind,'research_bounded_window_v1') && isequal(m.version,1) && ...
    isequal(m.windowWidth,.35) && isequal(m.bucketWidth,.35/478) && ...
    isequal(m.rawCapacity,32) && isequal(m.bucketCapacity,480), ...
    'ipm:ResearchWindowState','Registration mismatch.');
validateattributes(m.origin,{'double'},{'scalar','finite','real','nonnegative'});
validateattributes(m.epoch,{'double'},{'scalar','finite','integer','nonnegative'});
validateattributes(m.rawCount,{'double'},{'scalar','integer','>=',1,'<=',32});
validateattributes(m.bucketCount,{'double'},{'scalar','integer','>=',1,'<=',480});
validateattributes(m.raw,{'double'},{'real','finite','size',[32 6]});
r=m.raw(1:m.rawCount,:);n=m.bucketCount;b=m.buckets;
assert(all(r(:,3)==m.epoch) && all(r(:,1)>=m.origin) && ...
    all(diff(r(:,1))>0) && all(diff(r(:,2))==1) && ...
    all(r(:,4:5)>0,'all') && all(r(:,6)>=0) && ...
    all(m.raw(m.rawCount+1:end,:)==0,'all'), ...
    'ipm:ResearchWindowState','Raw pool invariant.');
bNames={'index';'count';'firstTime';'firstStep';'last';'meanTime'; ...
    'meanLog';'sumTime2';'sumTimeLog';'maximumDecay';'hasEvidence'; ...
    'fromX';'toX';'fromY';'toY'};
widths=[1 1 1 1 6 1 2 1 2 2 2 6 6 6 6];
assert(isstruct(b) && isscalar(b) && isequal(sort(fieldnames(b)),sort(bNames)), ...
    'ipm:ResearchWindowState','Bucket schema invariant.');
for k=1:numel(bNames)
    cls='double';if strcmp(bNames{k},'hasEvidence'),cls='logical';end
    validateattributes(b.(bNames{k}),{cls},{'real','finite','size',[480 widths(k)]});
    a=b.(bNames{k});
    assert(all(a(n+1:end,:)==0,'all'),'ipm:ResearchWindowState','Unused slots must be zero.');
end
assert(all(b.index(1:n)>=0 & b.index(1:n)<2^48) && ...
    all(b.index(1:n)==fix(b.index(1:n))) && all(diff(b.index(1:n))>0) && ...
    all(b.count(1:n)>=1 & b.count(1:n)<flintmax) && ...
    all(b.count(1:n)==fix(b.count(1:n))) && ...
    all(b.sumTime2(1:n)>=0) && all(b.maximumDecay(1:n,:)>=0,'all'), ...
    'ipm:ResearchWindowState','Bucket index/statistic invariant.');
assert(all(b.last(1:n,3)==m.epoch) && all(b.last(1:n,4:5)>0,'all') && ...
    all(b.last(1:n,6)>=0) && all(diff(b.last(1:n,1))>0) && ...
    all(diff(b.last(1:n,2))>0) && isequal(b.last(n,:),r(end,:)) && ...
    all(b.firstTime(1:n)<=b.last(1:n,1)) && ...
    all(b.firstStep(1:n)<=b.last(1:n,2)) && ...
    all(b.count(1:n)==b.last(1:n,2)-b.firstStep(1:n)+1) && ...
    all(floor((b.last(1:n,1)-m.origin)/m.bucketWidth)==b.index(1:n)) && ...
    all(floor((b.firstTime(1:n)-m.origin)/m.bucketWidth)==b.index(1:n)), ...
    'ipm:ResearchWindowState','Bucket provenance invariant.');
cutoff=r(end,1)-m.windowWidth;
assert(all(b.last(1:n,1)>=cutoff) && all(r(:,1)>=cutoff), ...
    'ipm:ResearchWindowState','Expired bucket or raw observation.');
fromNames={'fromX','fromY'};toNames={'toX','toY'};
for axis=1:2
    for k=1:n
        a=b.(fromNames{axis})(k,:);z=b.(toNames{axis})(k,:);
        if b.hasEvidence(k,axis)
            assert(a(3)==m.epoch && z(3)==m.epoch && ...
                z(2)==a(2)+1 && z(1)>a(1) && all(a(4:5)>0) && ...
                all(z(4:5)>0) && z(1)<=b.last(k,1) && ...
                floor((z(1)-m.origin)/m.bucketWidth)==b.index(k), ...
                'ipm:ResearchWindowState','Secant endpoint provenance.');
            d=-(log(z(4:5))-log(a(4:5)))/(z(1)-a(1));
            assert(isequal(d(axis),b.maximumDecay(k,axis)) && d(axis)>0, ...
                'ipm:ResearchWindowState','Secant evidence changed.');
        else
            assert(b.maximumDecay(k,axis)==0 && all(a==0) && all(z==0), ...
                'ipm:ResearchWindowState','Empty evidence invariant.');
        end
    end
end
end
