function report=ipm_perflab_late_rate_response(cacheFile,observationReportFile,failureFile,outputDirectory)
%IPM_PERFLAB_LATE_RATE_RESPONSE Frozen-field native/alternative wall diagnostic.
% Original assemblers, fixed physical flow, no LU, PDE step or normalization.
assert(maxNumCompThreads==10&&~isfolder(outputDirectory));mkdir(outputDirectory);
p=struct('cacheFile',cacheFile,'observationReportFile',observationReportFile, ...
    'failureFile',failureFile,'relativeSteps',[1e-5,5e-6], ...
    'directions',{{'centered_isotropic_dilation','amplitude','width_normalized_translation','raw_isotropic_dilation'}}, ...
    'modes',{{'conservative_flux','advective_upwind'}}, ...
    'coordinateParameterization','q=[cl,cw,(cr+cl*a)/wx]; a and wx fixed from original native geometry.', ...
    'constraintCoordinates',{{'PPrime/P','aPrime/wx','beta','gamma'}}, ...
    'coreMask','Fixed original-native |X-a|<=3wx and 0<=Y<=3wy; wall uses same x mask.', ...
    'originalAssembler',which('ipm.evolve.assembleRhs'),'originalWeno',which('ipm.field.weno5FluxDerivative'), ...
    'geometryFunction',which('ipm_accellab_continuous_inner_rates'),'poissonEvaluations',0,'pdeSteps',0, ...
    'densityProjectionCount',0,'fieldUnits','All saved arrays retain source native scales. No field rescaling.', ...
    'alternativeIsNativeAlgorithm',false,'maximumOriginalAssemblyCalls',36);
write_json(fullfile(outputDirectory,'registration.json'),p);save(fullfile(outputDirectory,'registration.mat'),'p');
d=load(cacheFile);prior=load(observationReportFile,'report');prior=prior.report;
failed=load(failureFile,'failure');failed=failed.failure;
assert(d.cacheAudit.fullFlowAndRhoRateSaved&&d.cacheAudit.noEllipticFactorSaved);
assert(isequaln(prior.cacheAudit,d.cacheAudit));ops=d.transportOps;rho=d.rho;flow=d.flow;
assert(strcmp(ops.wallTransportMode,'conservative_flux')&&strcmp(ops.transportScheme,'weno5_fd')&& ...
    strcmp(ops.spatialDiscretization,'high_order')&&strcmp(ops.transportBoundaryMode,'open'));
assert(~any(isfield(ops,{'A','poisson','decomposition','LU'})));
assert(isequaln(d.Omega,rho*ops.Dx')&&isequaln(d.FX,d.rhoRate*ops.Dx'));
window=prior.localWindow;r0=ipm_accellab_continuous_inner_rates(d.Omega,d.FX,d.x,d.y,d.Dx,d.Dy,window);
assert(r0.valid&&isequaln(r0,prior.coordinates));a=r0.peak.x;w=r0.wallCoreWidth;wy=r0.verticalCoreWidth;
q0=[flow.c_l;flow.c_omega;(flow.c_r+flow.c_l*a)/w];
raw0=[flow.c_l,flow.c_l,flow.c_omega,flow.c_r];
directions=[1,0,0,1;1,0,0,1;0,1,0,0;-a,0,w,0];
stepsBase=[max(1,abs(q0));max(1,abs(q0(1)))];
rx=rho*ops.Dx';ry=ops.Dy*rho;
generators=cat(3,-(ops.X-a).*rx-ops.Y.*ry,rho,-w*rx,-ops.X.*rx-ops.Y.*ry);
wallMask=abs(d.x-a)<=3*w;coreMask=wallMask & d.y<=3*wy;
assert(nnz(wallMask)>=7&&nnz(coreMask)>=49);
selection=struct('xFaces',find(wallMask)-1,'yLines',find(wallMask));
context=struct('Omega',d.Omega,'ops',ops,'window',window,'width',w, ...
    'weights',ops.integrationWeights,'coreMask',coreMask,'wallMask',wallMask);
genCoordinates=zeros(4,4);
for k=1:4,genCoordinates(:,k)=coordinate(generators(:,:,k),context);end
[base,baseFields]=pair(raw0,rho,flow,ops,selection,context);
assert(isequaln(baseFields.F{1},d.rhoRate),'ipm:RateResponseNativeParity','Original native RHS must match its saved cache.');
save(fullfile(outputDirectory,'baseline_fields.mat'),'baseFields','raw0','q0','directions','generators','genCoordinates', ...
    'a','w','wy','wallMask','coreMask','-v7.3');
records=cell(2,4);jacobians=zeros(4,4,2,2);calls=2;
for e=1:2
    for k=1:4
        h=p.relativeSteps(e)*stepsBase(k);delta=h*directions(:,k)';
        [plus,pf]=pair(raw0+delta,rho,flow,ops,selection,context);
        [minus,mf]=pair(raw0-delta,rho,flow,ops,selection,context);calls=calls+4;
        numericalResponse=cell(1,2);modes=cell(1,2);
        for mode=1:2
            numericalResponse{mode}=(pf.F{mode}-mf.F{mode})/(2*h);
            measured=(plus.coordinates(:,mode)-minus.coordinates(:,mode))/(2*h);
            direct=coordinate(numericalResponse{mode},context);
            jacobians(:,k,e,mode)=measured;
            modes{mode}=struct('mode',p.modes{mode},'geometryResponse',measured, ...
                'geometryFromDifferencedField',direct,'geometryDifferenceOrderRoundoff',direct-measured, ...
                'generatorCoordinates',genCoordinates(:,k),'geometryGeneratorDefect',measured-genCoordinates(:,k), ...
                'fieldGeneratorDefect',norms(numericalResponse{mode}-generators(:,:,k),generators(:,:,k),context), ...
                'responseNorm',norms(numericalResponse{mode},generators(:,:,k),context));
        end
        responseX=(pf.xTerm-mf.xTerm)/(2*h);responseY=(pf.yTerm-mf.yTerm)/(2*h);
        amplitudeResponse=directions(3,k)*rho;
        geometryX=coordinate(responseX,context);geometryY=coordinate(responseY,context);
        geometryAmplitude=coordinate(amplitudeResponse,context);
        effectiveWallYResponse=numericalResponse{1}-numericalResponse{2};
        rec=struct('direction',p.directions{k},'relativeStep',p.relativeSteps(e),'actualStep',h, ...
            'rawRateDirection',directions(:,k),'rawRatesPlus',raw0+delta,'rawRatesMinus',raw0-delta, ...
            'modes',{modes},'xContributionGeometryResponse',geometryX,'yContributionGeometryResponse',geometryY, ...
            'amplitudeGeometryResponse',geometryAmplitude,'geometryTermClosure', ...
            coordinate(numericalResponse{1},context)-geometryX-geometryY-geometryAmplitude, ...
            'effectiveWallYGeometryResponse',coordinate(effectiveWallYResponse,context), ...
            'effectiveWallYResponseNorm',norms(effectiveWallYResponse,generators(:,:,k),context), ...
            'observedNativePairExact',plus.observerNativeExact&&minus.observerNativeExact, ...
            'alternativeOffWallExact',plus.alternativeOffWallExact&&minus.alternativeOffWallExact, ...
            'wenoResponse',observation_response(pf.observations,mf.observations,h,selection), ...
            'fieldFile',fullfile(outputDirectory,sprintf('epsilon_%d_direction_%d.mat',e,k)));
        save(rec.fieldFile,'pf','mf','numericalResponse','responseX','responseY','effectiveWallYResponse','-v7.3');
        records{e,k}=rec;
        fprintf('RATE_RESPONSE epsilon=%g direction=%s generatorDefectCore=%g wallYbeta=%g\n', ...
            p.relativeSteps(e),p.directions{k},modes{1}.fieldGeneratorDefect.core.relativeL2,rec.effectiveWallYGeometryResponse(3));
    end
end
failedQ=failed.lastQ;failedRaw=[failedQ(1),failedQ(1),failedQ(2),failedQ(3)*w-failedQ(1)*a];
[failedObservation,failedFields]=pair(failedRaw,rho,flow,ops,selection,context);calls=calls+2;
save(fullfile(outputDirectory,'unaccepted_rate_fields.mat'),'failedQ','failedRaw','failedFields','-v7.3');
epsilonComparison=cell(1,2);
for mode=1:2
    J1=jacobians(:,1:3,1,mode);J2=jacobians(:,1:3,2,mode);
    epsilonComparison{mode}=struct('mode',p.modes{mode},'jacobianEpsilon1',J1,'jacobianEpsilon2',J2, ...
        'relativeDifference',norm(J1-J2,'fro')/max(norm(J2,'fro'),realmin), ...
        'threeConstraintRcond',rcond(J2(1:3,:)), ...
        'generatorRelativeDifference',norm(J2-genCoordinates(:,1:3),'fro')/max(norm(genCoordinates(:,1:3),'fro'),realmin));
end
assert(calls==p.maximumOriginalAssemblyCalls);
report=struct('registration',p,'cacheAudit',d.cacheAudit,'nativeRates',d.nativeRates,'centeredNativeQ',q0, ...
    'nativeGeometry',r0,'generatorCoordinates',genCoordinates,'baseline',base,'records',{records}, ...
    'epsilonComparison',{epsilonComparison},'unacceptedQ',failedQ,'unacceptedRawRates',failedRaw, ...
    'unacceptedObservation',failedObservation,'originalFailureIdentifier',failed.identifier, ...
    'sourceNormalWallVelocityInf',max(abs(flow.u2(1,:))),'originalAssemblyCalls',calls, ...
    'originalCacheReproducedBitwise',true,'allObserverPairsExact',all(cellfun(@(r)r.observedNativePairExact,records),'all'), ...
    'allAlternativeDifferencesWallOnly',all(cellfun(@(r)r.alternativeOffWallExact,records),'all'), ...
    'sourceInputsValueUnchanged',isequaln(rho,d.rho)&&isequaln(flow,d.flow)&&isequaln(ops,d.transportOps), ...
    'interpretation','Frozen original-native fields only. Alternative wall is a changed research discretization, not a native continuation. Generator differences include WENO, mapped differencing, LF normalization and rounding; measured weight changes do not isolate causation by LF alone. No rate is selected and the original failed Newton gate remains failed.');
save(fullfile(outputDirectory,'report.mat'),'report','-v7.3');write_json(fullfile(outputDirectory,'report.json'),report);
fprintf('LATE_RATE_RESPONSE_COMPLETE calls=%d noLU=1 observerExact=%d\n',calls,report.allObserverPairsExact);
end
function [summary,fields]=pair(raw,rho,flow,ops,selection,context)
[F,~,a1,a2]=ipm.evolve.assembleRhs(rho,flow.u1,flow.u2,raw(1),raw(2),raw(3),raw(4),ops,ops.transportBoundaryMode);
alternate=ops;alternate.wallTransportMode='advective_upwind';
altF=ipm.evolve.assembleRhs(rho,flow.u1,flow.u2,raw(1),raw(2),raw(3),raw(4),alternate,alternate.transportBoundaryMode);
options=struct('lowerBoundary','extrapolate','upperBoundary','extrapolate','extrapolationDegree',5, ...
    'epsilon',ops.wenoEpsilon,'observeLines',1,'observeFaces',selection.xFaces);
[dx,rx]=ipm_perflab_weno5_observe(rho,a1,ops.metricX,ops.computationalSpacingX,options);
[vx,ux]=ipm_perflab_weno5_observe(ones(size(rho)),a1,ops.metricX,ops.computationalSpacingX,options);
options.observeLines=selection.yLines;options.observeFaces=[0,1];
[dy,ry]=ipm_perflab_weno5_observe(rho',a2',ops.metricY',ops.computationalSpacingY,options);dy=dy';
[vy,uy]=ipm_perflab_weno5_observe(ones(size(rho')),a2',ops.metricY',ops.computationalSpacingY,options);vy=vy';
observed=-(dx+dy-rho.*(vx+vy));
if raw(3)~=0,observed=observed+raw(3)*rho;end
assert(isequaln(observed,F),'ipm:RateObserverParity','Observed derivative arithmetic differs from original assembly.');
xTerm=-(dx-rho.*vx);yTerm=-(dy-rho.*vy);
observedAlt=xTerm(1,:);if raw(3)~=0,observedAlt=observedAlt+raw(3)*rho(1,:);end
assert(isequaln(observedAlt,altF(1,:))&&isequaln(F(2:end,:),altF(2:end,:)));
coords=[coordinate(F,context),coordinate(altF,context)];
obs=struct('rhoX',rx,'unitX',ux,'rhoY',ry,'unitY',uy);
nearY=1:min(9,size(rho,1));localYRate=max(abs(a2(nearY,:)./ops.metricY(nearY,:)),[],1);
alphaY=ry.alpha(selection.yLines);localY=localYRate(selection.yLines)';
summary=struct('rawRates',raw,'coordinates',coords,'observerNativeExact',true,'alternativeOffWallExact',true, ...
    'alternativeDifference',norms(F-altF,F,context),'wallYEffectiveGeometry',coordinate(F-altF,context), ...
    'xTermGeometry',coordinate(xTerm,context),'yTermGeometry',coordinate(yTerm,context), ...
    'sourceGeometry',coordinate(raw(3)*rho,context),'termClosureInf',max(abs(F-xTerm-yTerm-raw(3)*rho),[],'all'), ...
    'coreYAlphaMinMax',[min(alphaY),max(alphaY)],'coreYNearWallMappedSpeedMinMax',[min(localY),max(localY)], ...
    'coreYAlphaOverNearWallSpeedMinMax',[min(alphaY./max(localY,realmin)),max(alphaY./max(localY,realmin))], ...
    'coreYAlphaMaximizerNativeYMinMax',[min(ops.y(ry.maximumSpeedNodes(selection.yLines))),max(ops.y(ry.maximumSpeedNodes(selection.yLines)))], ...
    'wallXAlpha',rx.alpha(1),'wallXAlphaMaximizerNativeX',ops.x(rx.maximumSpeedNodes(1)));
fields=struct('F',{{F,altF}},'xTerm',xTerm,'yTerm',yTerm,'observations',obs);
end
function v=coordinate(F,c)
r=ipm_accellab_continuous_inner_rates(c.Omega,F*c.ops.Dx',c.ops.x,c.ops.y,c.ops.Dx,c.ops.Dy,c.window);
assert(r.valid,'ipm:RateResponseGeometry','Fixed geometry functional is not differentiable.');
v=[r.peakPrime/r.peak.value;r.translationRate/c.width;r.logScaleXRate;r.logScaleYRate];
end
function s=norms(delta,reference,c)
s=struct('wholeBox',region(delta,reference,c.weights,true(size(delta))), ...
    'core',region(delta,reference,c.weights,c.coreMask), ...
    'wall',region(delta(1,:),reference(1,:),ones(size(delta(1,:))),true(size(delta(1,:)))), ...
    'coreWall',region(delta(1,:),reference(1,:),ones(size(delta(1,:))),c.wallMask));
end
function s=region(delta,reference,weights,mask)
d=delta(mask);r=reference(mask);w=weights(mask);absoluteL2=sqrt(sum(w.*d.^2)/sum(w));
s=struct('absoluteInf',max(abs(d)),'absoluteL2',absoluteL2, ...
    'relativeInf',max(abs(d))/max(max(abs(r)),realmin), ...
    'relativeL2',sqrt(sum(w.*d.^2)/max(sum(w.*r.^2),realmin)));
end
function s=observation_response(plus,minus,h,selection)
s=struct();
for name={'rhoX','unitX','rhoY','unitY'}
    key=name{1};a=plus.(key);b=minus.(key);
    if endsWith(key,'X'),lines=1;else,lines=selection.yLines;end
    s.(key)=struct('alphaDerivativeMinMax',[min((a.alpha(lines)-b.alpha(lines))/(2*h)),max((a.alpha(lines)-b.alpha(lines))/(2*h))], ...
        'alphaMaximizerSwitchCount',sum(a.maximumSpeedNodes(lines)~=b.maximumSpeedNodes(lines)), ...
        'positiveScaleDerivativeInf',max(abs(a.positiveScale(lines)-b.positiveScale(lines)))/(2*h), ...
        'negativeScaleDerivativeInf',max(abs(a.negativeScale(lines)-b.negativeScale(lines)))/(2*h), ...
        'positiveWeightDerivativeInf',max(abs(a.positiveWeights-b.positiveWeights),[],'all')/(2*h), ...
        'negativeWeightDerivativeInf',max(abs(a.negativeWeights-b.negativeWeights),[],'all')/(2*h));
end
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fwrite(fid,jsonencode(value,PrettyPrint=true),'char');
end
