function report = ipm_perflab_thread_probe(checkpointFile,options)
%IPM_PERFLAB_THREAD_PROBE Restore once at 10 threads, compare frozen kernels.
%   This probe never writes or reloads a checkpoint after changing threads.
%   It compares one maintained flow and advance at each thread setting,
%   retaining the same accepted-state RHS cache for every advance. The
%   original 10-thread setting is restored on completion or error.

if nargin < 2
    options = struct();
end
defaults = struct('threads',[10,1,2,4],'repetitions',1, ...
    'finalTime',4,'physicalFinalTime',10);
names = fieldnames(options);
assert(all(ismember(names,fieldnames(defaults))),'Unknown thread-probe option.');
for index = 1:numel(names)
    defaults.(names{index}) = options.(names{index});
end
options = defaults;
validateattributes(options.threads,{'numeric'}, ...
    {'vector','integer','positive','finite'});
validateattributes(options.repetitions,{'numeric'}, ...
    {'scalar','integer','>=',1,'<=',3});
assert(options.threads(1) == 10,'The reference must run at 10 threads.');
maxNumCompThreads(10);
threadCleanup = onCleanup(@()maxNumCompThreads(10));
overrides = struct('finalTime',options.finalTime, ...
    'physicalFinalTime',options.physicalFinalTime,'saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false, ...
    'checkpoint',struct('enabled',false));
timer = tic;
[state,~,~] = ipm.output.restoreCheckpoint(checkpointFile,overrides);
restoreSeconds = toc(timer);
records = struct('threads',{},'flowSeconds',{},'advanceSeconds',{}, ...
    'flowMedianSeconds',{},'advanceMedianSeconds',{},'flowSpeedup',{}, ...
    'advanceSpeedup',{},'rhoRateRelativeInfDifference',{}, ...
    'velocityRelativeInfDifference',{},'flowCLDifference',{}, ...
    'flowCOmegaDifference',{},'advanceRhoRelativeInfDifference',{}, ...
    'advanceScaleMaximumAbsoluteDifference',{},'flowExact',{}, ...
    'advanceExact',{},'stopReason',{},'canonicalTime',{});
for threadIndex = 1:numel(options.threads)
    count = options.threads(threadIndex);
    maxNumCompThreads(count);
    flowSeconds = zeros(1,options.repetitions);
    advanceSeconds = zeros(1,options.repetitions);
    for repetition = 1:options.repetitions
        timer = tic;
        [rhoRate,flow] = ipm.evolve.flow(state.rho,state.ops,state.scale);
        flowSeconds(repetition) = toc(timer);
        timer = tic;
        [advanced,stopReason] = ipm.evolve.advance(state);
        advanceSeconds(repetition) = toc(timer);
    end
    if threadIndex == 1
        referenceRhoRate = rhoRate;
        referenceFlow = flow;
        referenceAdvanced = advanced;
        referenceFlowSeconds = median(flowSeconds);
        referenceAdvanceSeconds = median(advanceSeconds);
    end
    scaleNames = fieldnames(advanced.scale);
    scaleDifference = 0;
    for index = 1:numel(scaleNames)
        name = scaleNames{index};
        scaleDifference = max(scaleDifference,abs( ...
            advanced.scale.(name)-referenceAdvanced.scale.(name)));
    end
    record = struct('threads',maxNumCompThreads, ...
        'flowSeconds',flowSeconds,'advanceSeconds',advanceSeconds, ...
        'flowMedianSeconds',median(flowSeconds), ...
        'advanceMedianSeconds',median(advanceSeconds), ...
        'flowSpeedup',referenceFlowSeconds/median(flowSeconds), ...
        'advanceSpeedup',referenceAdvanceSeconds/median(advanceSeconds), ...
        'rhoRateRelativeInfDifference',relative_difference( ...
            rhoRate,referenceRhoRate), ...
        'velocityRelativeInfDifference',max( ...
            relative_difference(flow.u1,referenceFlow.u1), ...
            relative_difference(flow.u2,referenceFlow.u2)), ...
        'flowCLDifference',flow.c_l-referenceFlow.c_l, ...
        'flowCOmegaDifference',flow.c_omega-referenceFlow.c_omega, ...
        'advanceRhoRelativeInfDifference',relative_difference( ...
            advanced.rho,referenceAdvanced.rho), ...
        'advanceScaleMaximumAbsoluteDifference',scaleDifference, ...
        'flowExact',isequaln(flow,referenceFlow) && ...
            isequaln(rhoRate,referenceRhoRate), ...
        'advanceExact',isequaln(advanced.rho,referenceAdvanced.rho) && ...
            isequaln(advanced.scale,referenceAdvanced.scale) && ...
            isequaln(advanced.flow,referenceAdvanced.flow), ...
        'stopReason',stopReason,'canonicalTime',advanced.scale.canonicalTime);
    records(end+1) = record; %#ok<AGROW>
    fprintf(['threads=%d flow=%.6g s advance=%.6g s speedup=%.3fx ' ...
        'RHSdiff=%.3g rhodiff=%.3g scalediff=%.3g stop=%s\n'], ...
        record.threads,record.flowMedianSeconds,record.advanceMedianSeconds, ...
        record.advanceSpeedup,record.rhoRateRelativeInfDifference, ...
        record.advanceRhoRelativeInfDifference,scaleDifference,stopReason);
end
maxNumCompThreads(10);
report = struct('schemaVersion',1,'kind','ipm_frozen_thread_probe', ...
    'options',options,'checkpointFile',char(checkpointFile), ...
    'restoreThreads',10,'restoredThreads',maxNumCompThreads, ...
    'restoreSeconds',restoreSeconds,'matlabVersion',version,'computer',computer, ...
    'grid',[state.ops.ny,state.ops.nx],'canonicalTime',state.scale.canonicalTime, ...
    'physicalTime',state.scale.physicalTime,'acceptedStep',state.step, ...
    'records',records,'checkpointWritten',false, ...
    'cacheProvenance','all advances start with the restored 10-thread cache', ...
    'interpretation','bounded local cost and roundoff probe; no trajectory equivalence claim');
clear threadCleanup;
end

function difference = relative_difference(actual,expected)
difference = max(abs(actual-expected),[],'all') / ...
    max(max(abs(expected),[],'all'),realmin);
end
