function [x,metrics] = ipm_perflab_row_solve(cache,b,A)
%IPM_PERFLAB_ROW_SOLVE Apply a cached left-scaled LU, audit ORIGINAL system.
%   A and b are the original complete interior operator and assembled RHS,
%   including all boundary contributions. No PDE source term is rescaled
%   in isolation. Returned metrics do not replace production acceptance.

assert(isequal(size(A),cache.matrixSize) && size(b,1) == size(A,1), ...
    'Matrix/RHS dimensions do not match the factor cache.');
scaledB = cache.rowScale.*b;
x = cache.factor\scaledB;
if nargout < 2
    return;
end
residual = A*x-b;
componentwiseDenominator = abs(A)*abs(x)+abs(b);
commonRowScale = 1./full(max(abs(A),[],2));
metrics = struct( ...
    'originalRelativeResidual',norm(residual,inf)/max(norm(b,inf),eps), ...
    'componentwiseBackwardError',max( ...
        abs(residual)./max(componentwiseDenominator,realmin),[],'all'), ...
    'commonRowNormalizedResidual', ...
        norm(commonRowScale.*residual,inf) / ...
        max(norm(commonRowScale.*b,inf),realmin), ...
    'scaledRelativeResidual',norm(cache.rowScale.*residual,inf) / ...
        max(norm(scaledB,inf),realmin), ...
    'finiteSolution',all(isfinite(x),'all'));
end
