function report=ipm_perflab_search_current_axis_amplitude(previousReportFile,outputDirectory)
%IPM_PERFLAB_SEARCH_CURRENT_AXIS_AMPLITUDE Bounded nonmonotone axis search.
% Uses the maintained equalizer as a requested-amplitude constructor. The
% current entry axis, immutable external root and single-hop depth remain
% distinct. Only the best three sigma families receive a full field score.
assert(~exist(outputDirectory,'dir'),'Use a new output directory.');
mkdir(outputDirectory);
loaded=load(previousReportFile,'report'); previous=loaded.report;p=previous.provenance;
assert(p.currentIncrementalReferenceDepth==0 && p.incrementalGeneration==1 && ...
    p.maximumIncrementalReferenceDepth==1 && ~p.sameRoundRecursiveReference);
assert(previous.existingFallbackAudit.referenceAudit.passed && ...
    strcmp(previous.exhaustedDepthNegativeAudit.status,'maximum_incremental_reference_depth_reached'));
current=ipm.output.validate(p.currentFile);
assert(all(ipm.output.trustedMask(current)));
loaded=load(p.baseDesignFile,'design');design=loaded.design;
loaded=load(p.rootReferenceFile,'dataset');root=loaded.dataset;
loaded=load(p.parentPlatformFile,'candidate');parent=loaded.candidate;
loaded=load(parent.referenceFile,'dataset');parentRoot=loaded.dataset;
assert(strcmp(parent.kind,'ipm_longtime_moving_platform_candidate') && ...
    parent.rootAxisFactoryReproducedExactly && parent.transactionReady);
assert(isequal(parent.candidateX(:),current.grid.x(:)) && ...
    isequal(parent.candidateY(:),current.grid.y(:)));
assert(isequal(root.snapshots(1).x,parentRoot.snapshots(1).x) && ...
    isequal(root.snapshots(1).y,parentRoot.snapshots(1).y));
assert(isscalar(design.dataset.snapshots) && isscalar(design.profiles.records) && ...
    isequal(design.dataset.snapshots(1).rho,current.state.rho) && ...
    isequal(design.dataset.snapshots(1).x(:),current.grid.x(:)) && ...
    isequal(design.dataset.snapshots(1).y(:),current.grid.y(:)) && ...
    ~design.reference.usesCurrentAxesAsReference);
assert(isequal([design.targets.xCoreCells,design.targets.yCoreCells,design.targets.xFrontCells],[21,21,20]));
x=current.grid.x(:)';record=design.profiles.records;
intervals=[record.safetyCoreCenter-record.safetyCoreWidthLeft,record.safetyCoreCenter+record.safetyCoreWidthRight; ...
    record.leftFrontCenter-record.leftFrontHalfWidth,record.leftFrontCenter+record.leftFrontHalfWidth];
intersection=[max(intervals(:,1)),min(intervals(:,2))];
assert(diff(intersection)>1024*eps(max(1,x(end))));
focus=.5*sum(intersection);anchorIndex=find(x==1);assert(isscalar(anchorIndex)&&any(x==-1));
protocol=struct('sigmas',[.18,.25,.35,.5,.75,1],'axisTargets',[21,20], ...
    'uniformAmplitudePoints',33,'localIntervals',2,'localPoints',5,'localRounds',4, ...
    'maximumAmplitudeCap',16,'fullPairScoreCount',3,'focusCenter',focus,'anchorPosition',1, ...
    'objective','min(core/21,front/20), subject to all post-snap axis gates', ...
    'yTarget',21,'yPadding',1.15,'nativeTransactionCoreFloor',20, ...
    'maximumPeakJump',2e-3,'maximumMassDefect',5e-12,'maximumRangeViolation',2e-4, ...
    'localQuadratureLimits',[.35,1.65],'resolutionRoundoffTolerance',1e-6, ...
    'meshLimits',design.options.meshLimits,'previousReportFile',previousReportFile, ...
    'upperBoundPolicy','First maintained mesh barrier or explicit A=16 cap; not a global feasibility proof', ...
    'axisSourcePolicy','Every A is built from the same immutable current entry axis', ...
    'referenceProvenance','trusted_terminal_axis_single_hop','currentReferenceDepth',0, ...
    'candidateReferenceDepth',1,'externalRootAxesPreserved',true,'runtimeReferencesAccessedOrModified',false);
write_json(fullfile(outputDirectory,'frozen_protocol.json'),protocol);
sourceAuditProvenance=p;
p.sigmas=protocol.sigmas;p.xConstructionPaddings=1;
p.kernelFocusMode='core_front_intersection';p.kernelFocusCenter=focus;
families=cell(numel(protocol.sigmas),1);bestAxes=families;bestInfos=families;
for k=1:numel(protocol.sigmas)
    sigma=protocol.sigmas(k);
    [family,bestAxis,bestInfo]=search_sigma(x,intervals,anchorIndex,focus,sigma,protocol);
    families{k}=family;bestAxes{k}=bestAxis;bestInfos{k}=bestInfo;
    save(fullfile(outputDirectory,sprintf('axis_search_sigma%04d.mat',round(100*sigma))), ...
        'family','bestAxis','bestInfo','-v7.3');
    write_json(fullfile(outputDirectory,'partial_axis_search.json'),families(1:k));
    fprintf('NONMONOTONE sigma=%.2f samples=%d bestA=%.9g objective=%.9g core=%.8g front=%.8g ratio=%.9g upperA=%.8g\n', ...
        sigma,numel(family.trials),family.best.amplitude,family.best.objective, ...
        family.best.coreCells,family.best.frontCells,family.best.ratio,family.maximumSampledAmplitude);
end
objectives=cellfun(@(f)f.best.objective,families);
[~,order]=sort(objectives,'descend');selected=order(1:min(protocol.fullPairScoreCount,numel(order)));
yOptions=struct('geometry','positive','focusCenters',0,'sigma',design.options.equalizationOptions.ySigma, ...
    'power',design.options.equalizationOptions.yPower,'meshLimits',protocol.meshLimits);
[y,yInfo]=ipm_gridlab_equalize_axis(root.snapshots(1).y,[0,record.yCoreWidth],21*1.15,yOptions);
items=cell(numel(selected),1);
for rank=1:numel(selected)
    k=selected(rank);family=families{k};candidateX=bestAxes{k};
    scoreOptions=design.options.pairScoreOptions;scoreOptions.profiles=design.profiles;
    scoreOptions.minimumXCoreCells=21;scoreOptions.minimumYCoreCells=21;scoreOptions.minimumXFrontCells=20;
    scoreOptions.meshLimits=protocol.meshLimits;
    score=ipm_gridlab_score_frozen_pair(design.dataset,candidateX,y,scoreOptions);
    localPassed=local_quality(score.quality.x)&&local_quality(score.quality.y);
    resolutionPassed=false;transferPassed=false;peakJump=NaN;coreX=NaN;coreY=NaN;front=NaN;
    if score.admissible && ~isempty(fieldnames(score.aggregate))
        a=score.aggregate;coreX=a.minimumXCoreCells;coreY=a.minimumYCoreCells;front=a.minimumXLeftFrontCells;
        resolutionPassed=coreX>=21-1e-6&&coreY>=21-1e-6&&front>=20-1e-6;
        peakJump=a.worst.rhoXMaximumRelativeChange;
        transferPassed=peakJump<=2e-3&&a.worst.conservationRelativeDefect<=5e-12&&a.worst.relativeRangeViolation<=2e-4;
        assert(abs(coreX-family.best.coreCells)<1e-10&&abs(front-family.best.frontCells)<1e-10, ...
            'Axis-only counts must agree with maintained full pair scoring.');
    end
    ready=score.admissible&&localPassed&&resolutionPassed&&transferPassed;
    candidate=struct('kind','ipm_nonmonotone_current_axis_single_hop_candidate', ...
        'protocol',protocol,'provenance',p,'sourceAuditProvenance',sourceAuditProvenance, ...
        'actualKernelFocus',focus,'currentIncrementalReferenceDepth',0, ...
        'incrementalGeneration',1,'sigma',family.sigma,'amplitude',family.best.amplitude, ...
        'candidateX',candidateX,'candidateY',y,'anchorPosition',1,'anchorNodeIndex',anchorIndex, ...
        'xEqualizationInfo',bestInfos{k},'yEqualizationInfo',yInfo,'axisSearchBest',family.best, ...
        'completeAxisRescoredAfterSnap',true,'pairScore',score,'localQuadraturePassed',localPassed, ...
        'resolutionPassed',resolutionPassed,'transferPassed',transferPassed,'transactionReady',ready, ...
        'pdeAdvanced',false,'checkpointRegridCommitted',false);
    file=fullfile(outputDirectory,sprintf('candidate_rank%d_sigma%04d.mat',rank,round(100*family.sigma)));
    save(file,'candidate','-v7.3');
    items{rank}=struct('rank',rank,'sigma',family.sigma,'amplitude',family.best.amplitude, ...
        'objective',family.best.objective,'file',file,'coreX',coreX,'coreY',coreY,'frontCells',front, ...
        'ratio',score.quality.x.maximumAdjacentCellRatio,'peakJump',peakJump,'localPassed',localPassed, ...
        'resolutionPassed',resolutionPassed,'transferPassed',transferPassed,'ready',ready);
    fprintf('NONMONOTONE_PAIR rank=%d sigma=%.2f ready=%d core=%.8g/%.8g front=%.8g peakJump=%.9g\n', ...
        rank,family.sigma,ready,coreX,coreY,front,peakJump);
end
report=struct('kind','nonmonotone_current_axis_frozen_search','protocol',protocol,'provenance',p, ...
    'sourceAuditProvenance',sourceAuditProvenance, ...
    'families',{families},'selectedFamilyIndices',selected,'items',{items}, ...
    'readyCount',nnz(cellfun(@(v)v.ready,items)),'pdeAdvanced',false,'poissonBuilt',false);
save(fullfile(outputDirectory,'search_report.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'search_report.json'),report);
end

function [family,bestAxis,bestInfo]=search_sigma(x,intervals,anchorIndex,focus,sigma,p)
options=struct('geometry','symmetric','focusCenters',focus,'anchorPhysicalPosition',1, ...
    'sigma',sigma,'power',2,'meshLimits',p.meshLimits,'maximumAmplitude',p.maximumAmplitudeCap);
% An impossible cell target disables the maintained monotone target exit.
% We use only its unchanged axis constructor and first mesh-barrier bound.
[~,upperInfo]=ipm_gridlab_equalize_axis(x,intervals,numel(x)*ones(2,1),options);
upper=upperInfo.amplitude;assert(upper>0&&upper<=p.maximumAmplitudeCap);
trials={};axes={};infos={};keys=containers.Map('KeyType','char','ValueType','double');
amplitudes=linspace(0,upper,p.uniformAmplitudePoints);
indices=arrayfun(@evaluate,amplitudes);scores=cellfun(@(v)v.objective,trials(indices));
peaks=find(scores>=[-Inf,scores(1:end-1)] & scores>=[scores(2:end),-Inf]);
[~,rank]=sort(scores(peaks),'descend');peaks=peaks(rank(1:min(p.localIntervals,numel(rank))));
for peak=peaks
    lo=amplitudes(max(1,peak-1));hi=amplitudes(min(numel(amplitudes),peak+1));
    for roundIndex=1:p.localRounds
        points=linspace(lo,hi,p.localPoints);ii=arrayfun(@evaluate,points);
        ss=cellfun(@(v)v.objective,trials(ii));[~,jj]=max(ss);
        lo=points(max(1,jj-1));hi=points(min(numel(points),jj+1));
    end
end
allScores=cellfun(@(v)v.objective,trials);[~,bestIndex]=max(allScores);
bestAxis=axes{bestIndex};bestInfo=infos{bestIndex};best=trials{bestIndex};
family=struct('sigma',sigma,'maximumSampledAmplitude',upper,'upperBoundStatus',upperInfo.status, ...
    'upperBoundInfo',upperInfo,'uniformAmplitudePoints',amplitudes, ...
    'localGridPeakIndices',peaks,'trials',{trials},'best',best,'bestIndex',bestIndex);
    function index=evaluate(amplitude)
        key=sprintf('%.17g',amplitude);
        if isKey(keys,key),index=keys(key);return;end
        opts=options;
        if amplitude==0
            targets=1e-6*ones(2,1);
        else
            opts.initialAmplitude=amplitude;opts.maximumAmplitude=amplitude;
            targets=numel(x)*ones(2,1);
        end
        [axis,info]=ipm_gridlab_equalize_axis(x,intervals,targets,opts);
        assert(info.amplitude==amplitude,'Requested-amplitude constructor selected another A.');
        before=axis(anchorIndex);axis(anchorIndex)=1;axis(numel(axis)+1-anchorIndex)=-1;
        weights=ipm.mesh.quadrature(axis);q=ipm.mesh.quality(axis,7,weights);
        admitted=all(isfinite(axis))&&all(diff(axis)>0)&&isequal(axis,-fliplr(axis))&& ...
            q.maximumAdjacentCellRatio<=p.meshLimits.maxAdjacentCellRatio&& ...
            q.maximumLogSpacingCurvature<=p.meshLimits.maxLogSpacingCurvature&& ...
            q.minimumStencilRcond>=p.meshLimits.minStencilRcond&& ...
            q.minimumQuadratureWeightRatio>=p.meshLimits.minQuadratureWeightRatio&&local_quality(q);
        counts=zeros(2,1);
        for row=1:2
            overlap=max(0,min(axis(2:end),intervals(row,2))-max(axis(1:end-1),intervals(row,1)));
            counts(row)=sum(overlap./diff(axis));
        end
        objective=-Inf;if admitted,objective=min(counts./[21;20]);end
        trial=struct('amplitude',amplitude,'admitted',admitted,'coreCells',counts(1), ...
            'frontCells',counts(2),'objective',objective,'ratio',q.maximumAdjacentCellRatio, ...
            'curvature',q.maximumLogSpacingCurvature,'minimumStencilRcond',q.minimumStencilRcond, ...
            'minimumQuadratureRatio',q.minimumQuadratureWeightRatio, ...
            'localQuadratureRatios',[q.minimumQuadratureWeightToControlWidthRatio,q.maximumQuadratureWeightToControlWidthRatio], ...
            'snapDisplacement',1-before,'anchorExactlyOne',axis(anchorIndex)==1, ...
            'axisTargetPassed',admitted&&all(counts>=[21;20]));
        trials{end+1}=trial;axes{end+1}=axis;infos{end+1}=info;index=numel(trials);keys(key)=index;
    end
end

function passed=local_quality(q)
passed=q.quadratureWeightsStrictlyPositive&&q.minimumQuadratureWeightToControlWidthRatio>=.35&& ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end

function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fwrite(fid,jsonencode(value,PrettyPrint=true),'char');
end
