function audit=ipm_perflab_audit_long_box_lineage(reportFile,outputFile)
%IPM_PERFLAB_AUDIT_LONG_BOX_LINEAGE Strict reads, no restore/operator/PDE.
assert(maxNumCompThreads==10&&~isfile(outputFile));loaded=load(reportFile,'report');r=loaded.report;
assert(r.completed&&all(cellfun(@(b)b.audit.passed,r.branches)));
parent=r.registration.parentRegistration;
source=ipm.output.readCheckpoint(parent.sourceFile);s=source.payload.state;
Cx=exp(s.scale.logC_l);Comega=exp(s.scale.logC_omega);rows=cell(1,3);
for k=1:3
 branch=r.branches{k};fraction=r.registration.fractions(k);
 cp=ipm.output.readCheckpoint(branch.checkpointFile);v=cp.payload.state;
 xi=find(abs(s.x(:)')<=fraction*max(abs(s.x)));yi=find(s.y(:)<=fraction*max(s.y));
 expectedX=s.x(xi)/Cx;expectedY=s.y(yi)/Cx;expectedRho=exp(-s.scale.logC_omega)*s.rho(yi,xi);
 actualLineage=v.runMetadata.caseMetadata.latePhysicalBoxBranch;
 row=struct('label',branch.label,'strictNativeRead',true,'lineageMatchesReportExact',isequaln(actualLineage,branch.lineage), ...
  'parentCaseMatches',strcmp(actualLineage.parentCaseId,char(s.runMetadata.caseId)), ...
  'parentCheckpointMatches',strcmp(actualLineage.parentCheckpoint,parent.sourceFile), ...
  'parentClockMatches',actualLineage.parentStep==s.step&&actualLineage.parentCanonicalTime==s.scale.canonicalTime&& ...
  actualLineage.absolutePhysicalEpoch==s.scale.physicalTime, ...
  'parentScalesMatch',actualLineage.parentCx==Cx&&actualLineage.parentComega==Comega&&actualLineage.canonicalCovarianceFactor==Cx/Comega, ...
  'originalNodeIndicesExact',isequal(actualLineage.initialNodeIndicesX(:),xi(:))&&isequal(actualLineage.initialNodeIndicesY(:),yi(:)), ...
  'freshFixedAxesExact',isequal(v.x(:),expectedX(:))&&isequal(v.y(:),expectedY(:)), ...
  'physicalAnchorExact',v.config.scaling.transportAnchorX==s.config.scaling.transportAnchorX/Cx, ...
  'freshHistoryAndIdentity',cp.payload.log.history.common.physicalTime(1)==0&& ...
  cp.payload.log.history.common.acceptedStep(1)==0&&~actualLineage.parentHistoryInherited&& ...
  ~strcmp(char(v.runMetadata.caseId),char(s.runMetadata.caseId)), ...
  'adaptiveRemeshDisabled',~v.config.remesh.adaptiveRemesh,'publicEpsilonPreserved',v.config.transport.wenoEpsilon==s.config.transport.wenoEpsilon);
 descriptor=functions(v.config.physics.initialCondition);
 assert(strcmp(descriptor.type,'anonymous')&&isscalar(descriptor.workspace));w=descriptor.workspace{1};
 row.capturedInitialPhysicalArraysExact=isequal(w.physicalX(:),expectedX(:))&&isequal(w.physicalY(:),expectedY(:))&&isequal(w.physicalRho,expectedRho);
 names=fieldnames(row);names=setdiff(names,{'label'});row.passed=all(cellfun(@(n)row.(n),names));
 rows{k}=row;clear cp v descriptor w
end
audit=struct('kind','strict_original_physical_initial_data_and_native_lineage_pairing','rows',{rows}, ...
 'passed',all(cellfun(@(a)a.passed,rows)),'operatorRestores',0,'poissonBuilds',0,'pdeSteps',0, ...
 'reportFile',reportFile,'parentCheckpoint',parent.sourceFile);
fid=fopen(outputFile,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fwrite(fid,jsonencode(audit,PrettyPrint=true),'char');
assert(audit.passed,'ipm:ThreeBoxOriginalLineage','An original-data lineage check failed; full details saved.');
fprintf('THREE_BOX_ORIGINAL_LINEAGE_PASS cases=3 strict_native_reads=4 restores=0\n');
end
