function report = ipm_perflab_verify_row_equilibration()
%IPM_PERFLAB_VERIFY_ROW_EQUILIBRATION Small MMS and controlled row-scale tests.
%   No production source edits, checkpoints, or q512 computations. Uses the
%   maintained Poisson assembly as an oracle for complete boundary RHSs.

methods = {'none','power2_row_max','row_max'};
cases = struct('family',{},'grid',{},'method',{},'factorInfo',{}, ...
    'metrics',{},'solveSamplesSeconds',{},'solveMedianSeconds',{}, ...
    'psiRelativeDifferenceFromMaintained',{}, ...
    'velocityRelativeDifferenceFromMaintained',{}, ...
    'psiMmsRelativeError',{},'velocityMmsRelativeError',{}, ...
    'boundaryExact',{},'warningIdentifier',{});
for family = 1:3
    for n = [17,33,49]
        opts = struct('nx',n,'ny',n,'xlim',[-1,1],'ymax',1, ...
            'gridMode','uniform','gridStretchAutomatic',false,'gridStretch',[0,0], ...
            'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
            'timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
            'rescalingMode','physical','farBoundaryMode','dirichlet_zero', ...
            'transportBoundaryMode','closed','wallTransportMode','conservative_flux', ...
            'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
            'saveResults',false,'makePlots',false,'livePlot',false, ...
            'writeVideo',false,'verbose',false);
        familyName = 'fourth_uniform_nonzero_boundary_mms';
        if family == 2
            opts.gridMode = 'stretched';
            opts.gridStretch = [0.9,0.7];
            familyName = 'fourth_stretched_nonzero_boundary_mms';
        elseif family == 3
            opts = ipm.config.sixthOrder(opts);
            opts.spatialDiscretization = 'sixth_order';
            opts.transportScheme = 'weno7_fd';
            opts.timeIntegrator = 'rk6';
            opts.remeshTransferScheme = 'sixth_order';
            familyName = 'sixth_uniform_nonzero_boundary_mms';
        end
        config = ipm.config.resolve(opts);
        ops = ipm.mesh.build(config);
        exact = mms(ops.X,ops.Y);
        boundary = struct('left',exact.psi(:,1),'right',exact.psi(:,end), ...
            'bottom',exact.psi(1,:),'top',exact.psi(end,:));
        [maintainedPsi,rhs] = ipm.field.poisson(exact.source,ops,1,boundary);
        [maintainedU1,maintainedU2] = velocity(maintainedPsi,ops);
        A = ops.A;
        for methodIndex = 1:numel(methods)
            method = methods{methodIndex};
            [cache,factorInfo] = ipm_perflab_row_factor(A,method);
            lastwarn('');
            [interior,metrics] = ipm_perflab_row_solve(cache,rhs(:),A);
            [~,warningIdentifier] = lastwarn;
            samples = time_solves(cache,rhs(:),A,5);
            psi = maintainedPsi;
            psi(2:end-1,2:end-1) = reshape(interior,n-2,n-2);
            [u1,u2] = velocity(psi,ops);
            item = struct('family',familyName,'grid',[n,n],'method',method, ...
                'factorInfo',factorInfo,'metrics',metrics, ...
                'solveSamplesSeconds',samples,'solveMedianSeconds',median(samples), ...
                'psiRelativeDifferenceFromMaintained',relative(psi,maintainedPsi), ...
                'velocityRelativeDifferenceFromMaintained',max( ...
                    relative(u1,maintainedU1),relative(u2,maintainedU2)), ...
                'psiMmsRelativeError',relative(psi,exact.psi), ...
                'velocityMmsRelativeError',max(relative(u1,exact.u1),relative(u2,exact.u2)), ...
                'boundaryExact',isequaln(psi([1,end],:),exact.psi([1,end],:)) && ...
                    isequaln(psi(:,[1,end]),exact.psi(:,[1,end])), ...
                'warningIdentifier',warningIdentifier);
            assert(metrics.finiteSolution && item.boundaryExact && ...
                item.psiRelativeDifferenceFromMaintained < 1e-10 && ...
                item.velocityRelativeDifferenceFromMaintained < 1e-9 && ...
                metrics.originalRelativeResidual < 1e-10, ...
                'ipm:RowEquilibrationMms','Small-grid MMS equivalence failed.');
            cases(end+1) = item; %#ok<AGROW>
            fprintf('%s n=%d %s rcond=%.3g psiDelta=%.3g originalResidual=%.3g\n', ...
                familyName,n,method,factorInfo.rcond, ...
                item.psiRelativeDifferenceFromMaintained,metrics.originalRelativeResidual);
        end
    end
end
% Isolate extreme equation-row units WITHOUT pretending this is an
% admitted small grid spanning the production near/far scale separation.
% The base A comes from the last small admitted grid and has a known
% discrete solution; multiplying rows changes no mathematical solution.
exactDiscrete = exact.psi(2:end-1,2:end-1);
exactDiscrete = exactDiscrete(:);
baseA = A;
baseB = baseA*exactDiscrete;
stress = struct('rowScaleOrders',{},'method',{},'factorInfo',{}, ...
    'metrics',{},'solutionRelativeError',{},'solveMedianSeconds',{}, ...
    'warningIdentifier',{});
for orders = [8,16]
    equationUnits = 10.^linspace(-orders/2,orders/2,size(baseA,1))';
    stressA = spdiags(equationUnits,0,size(baseA,1),size(baseA,1))*baseA;
    stressB = equationUnits.*baseB;
    for methodIndex = 1:numel(methods)
        method = methods{methodIndex};
        [cache,factorInfo] = ipm_perflab_row_factor(stressA,method);
        lastwarn('');
        [interior,metrics] = ipm_perflab_row_solve(cache,stressB,stressA);
        [~,warningIdentifier] = lastwarn;
        samples = time_solves(cache,stressB,stressA,5);
        item = struct('rowScaleOrders',orders,'method',method, ...
            'factorInfo',factorInfo,'metrics',metrics, ...
            'solutionRelativeError',relative(interior,exactDiscrete), ...
            'solveMedianSeconds',median(samples), ...
            'warningIdentifier',warningIdentifier);
        stress(end+1) = item; %#ok<AGROW>
        assert(metrics.finiteSolution && item.solutionRelativeError < 1e-9, ...
            'ipm:RowEquilibrationStress','Controlled row-unit stress solve failed.');
        fprintf('row-unit stress 1e%d %s rcond=%.3g xError=%.3g originalResidual=%.3g\n', ...
            orders,method,factorInfo.rcond,item.solutionRelativeError, ...
            metrics.originalRelativeResidual);
    end
end
report = struct('schemaVersion',1,'kind','ipm_poisson_row_equilibration_study', ...
    'matlabVersion',version,'computer',computer, ...
    'computationalThreads',maxNumCompThreads,'caseCount',numel(cases), ...
    'cases',cases,'rowUnitStress',stress,'allChecksPassed',true, ...
    'largeGridTestPerformed',false,'pdeEvolutionPerformed',false, ...
    'stressInterpretation','algebraic row-unit stress, not an admitted production grid', ...
    'productionInterpretation','equivalent linear equations; LU rounding and trajectories may change');
end

function exact = mms(X,Y)
% Nonzero artificial side data tests that the FULL RHS is scaled. The
% physical wall and top traces vanish, with compatible wall u2=0.
g = exp(0.3*X).*cos(1.2*X);
gx = exp(0.3*X).*(0.3*cos(1.2*X)-1.2*sin(1.2*X));
gxx = exp(0.3*X).*((0.3^2-1.2^2)*cos(1.2*X)-0.72*sin(1.2*X));
h = Y.*(1-Y);
exact = struct('psi',g.*h,'source',-gxx.*h+2*g, ...
    'u1',-g.*(1-2*Y),'u2',gx.*h);
end

function [u1,u2] = velocity(psi,ops)
u1 = -(ops.Dy*psi);
u2 = psi*ops.Dx';
u2(1,:) = 0;
end

function difference = relative(actual,expected)
difference = max(abs(actual-expected),[],'all') / ...
    max(max(abs(expected),[],'all'),realmin);
end

function samples = time_solves(cache,b,A,repetitions)
ipm_perflab_row_solve(cache,b,A);
samples = zeros(1,repetitions);
for index = 1:repetitions
    timer = tic;
    ipm_perflab_row_solve(cache,b,A);
    samples(index) = toc(timer);
end
end
