function report = ipm_perflab_verify_time_refinement(outputDirectory)
%IPM_PERFLAB_VERIFY_TIME_REFINEMENT Exercise real solver/checkpoint comparison.
%   Tiny physical and exact dynamic-gauge cases, each with a nonzero source
%   time and multiple preserved history rows. No alternate integrator model.
assert(nargin == 1 && ~exist(outputDirectory,'dir'),'Pass a new tiny-test directory.');
mkdir(outputDirectory);
cases = {};
for dynamic = [false,true]
    label = 'physical';
    if dynamic
        label = 'dynamic_quadratic';
    end
    directory = fullfile(outputDirectory,label);
    mkdir(directory);
    opts = struct('nx',65,'ny',33,'xlim',[-4,4],'ymax',4, ...
        'gridMode','uniform','gridStretchAutomatic',false,'gridStretch',[0,0], ...
        'initialCondition',@smooth_density,'rescalingMode','physical', ...
        'symmetryMode','double_odd_omega', ...
        'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
        'timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
        'farBoundaryMode','dirichlet_zero','transportBoundaryMode','closed', ...
        'wallTransportMode','conservative_flux','adaptiveRemesh',false, ...
        'initialAnalyticRemesh',false,'saveResults',false,'makePlots',false, ...
        'livePlot',false,'writeVideo',false,'verbose',false,'storeSnapshots',false, ...
        'cfl',0.5,'maxDt',0.004,'finalTime',0.008,'physicalFinalTime',1, ...
        'outputEvery',0.004,'rangeStopTolerance',0.1, ...
        'minimumPeakPoints',2,'minimumLevelPoints',[2,2,2], ...
        'positiveWallNegativeTolerance',0.99,'oscillationTVTolerance',10, ...
        'checkpoint',struct('enabled',true, ...
        'file',fullfile(directory,'source_checkpoint.mat'),'every',Inf,'atExit',true));
    if dynamic
        opts.rescalingMode = 'dynamic';
        opts.lengthGauge = 'transport_anchor';
        opts.transportAnchorX = 1;
        opts.cOmegaGauge = 'wall_omega_quadratic_peak';
    end
    sourceResult = ipm.solve(opts);
    assert(sourceResult.state.steps >= 2 && ...
        all(ipm.output.trustedMask(sourceResult.history,sourceResult.config)), ...
        'Tiny source must contain a nonzero, fully trusted native history.');
    sourceFile = char(sourceResult.metadata.latestCheckpointFile);
    settings = struct('physicalFinalTime',sourceResult.state.physicalTime+0.012, ...
        'canonicalFinalTime',sourceResult.state.canonicalTime+0.1, ...
        'maxSegmentSteps',32,'window',[-2,2,2]);
    experiment = ipm_perflab_time_refinement(sourceFile, ...
        fullfile(directory,'comparison'),settings);
    item = struct('mode',label,'sourceFile',sourceFile, ...
        'sourceSteps',sourceResult.state.steps,'sourceRows',numel(sourceResult.history.common.t), ...
        'experiment',experiment);
    cases{end+1} = item; %#ok<AGROW>
    assert(experiment.passed && experiment.refined.segmentSteps > experiment.baseline.segmentSteps, ...
        'ipm:TimeRefinementTiny','Actual solver time-refinement smoke failed.');
end
% An open but insufficient canonical horizon is a valid solve request,
% yet it must never count as matched-physical-time refinement evidence.
settings.canonicalFinalTime = sourceResult.state.canonicalTime+0.001;
shortHorizon = ipm_perflab_time_refinement(sourceFile, ...
    fullfile(outputDirectory,'insufficient_canonical_horizon'),settings);
assert(~shortHorizon.passed && ~shortHorizon.checks.bothReachedPhysicalEndpoint && ...
    ~shortHorizon.checks.refinementExercised && shortHorizon.checks.historyPrefixesExact && ...
    shortHorizon.checks.baselineTrusted && shortHorizon.checks.refinedTrusted, ...
    'An uncompleted physical endpoint was incorrectly accepted.');
report = struct('schemaVersion',1,'kind','ipm_time_refinement_tiny_validation', ...
    'cases',{cases},'expectedRejectedShortHorizon',shortHorizon, ...
    'allPassed',true,'largeGridTestPerformed',false, ...
    'interpretation','Native checkpoint, history, endpoint, trust and comparison workflow validation.');
save(fullfile(outputDirectory,'tiny_time_refinement_report.mat'),'report');
end

function rho = smooth_density(X,Y)
rho = -exp(-X.^2-Y.^2);
end
