function report=ipm_perflab_prepare_factor3_resource(capacityFile,outDir)
% Reuse the existing tau8 selected candidate. No70x4 search, no LU or PDE.
assert(maxNumCompThreads==10&&~isfolder(outDir));mkdir(outDir);
g=load(capacityFile,'report','proposedCandidates','proposedAxisReports','referenceEvidence');
registration=struct('kind','future_factor3_resource_preparation_v1','capacityFile',capacityFile, ...
    'checkpointFile',g.report.checkpointFile,'sourceStep',4545,'sourceTau',8, ...
    'selectedAdditionalDirection',1,'selectedCandidate',1,'nodeCount',[961,321], ...
    'maximumTotalNodes',310000,'maximumAcceptedGrowthTransitions',3, ...
    'maximumSelectedPairsPerLevel',3,'maximumSelectedPairsAllLevels',15, ...
    'noRepeatedSeventyByFourSearch',true,'candidateReconstructionCount',1, ...
    'frozenInputInterpolation','maintenance six-point constant-conservative X then Y, no projection', ...
    'inputIsNativeTransfer',false,'oldCheckpointModified',false,'noLU',true,'noPDE',true);
write_json(fullfile(outDir,'registration.json'),registration);profile clear;profile on;timer=tic;
cp=ipm.output.readCheckpoint(g.report.checkpointFile);s=cp.payload.state;
assert(s.step==4545&&s.scale.canonicalTime==8&&s.runMetadata.autonomousMesh.currentLevelId==4&& ...
    all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
p=s.config.remesh.autonomousMesh;oldFamily=s.runMetadata.autonomousMesh.referenceFamily;
[draft,family,familyAudit]=ipm_perflab_factor3_family(p,oldFamily);
assert(isequaln(family.members(5).baseX,g.referenceEvidence.x3)&& ...
    isequaln(family.members(5).baseY,oldFamily.members(4).baseY));
productionRejected=false;
try
    ipm.config.autonomousMeshPolicy(draft);
catch e
    productionRejected=startsWith(e.identifier,'ipm:');
end
assert(productionRejected,'ipm:ResearchFactor3Scope','The future draft must not silently pass the original native normalizer.');
a=g.proposedAxisReports{1};c=g.proposedCandidates{1}(1);f=g.report.feature;anchor=family.anchor;
assert(isequal(g.report.proposed(1).cellFactors,[3,2])&&a.admittedAxisPairCount>0&& ...
    numel(c.x)==961&&numel(c.y)==321&&~c.unchanged);
Dx=ipm.mesh.fdMatrix(s.x,1,7);view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx,'source',s.rho*Dx','trusted',true);
assert(isequaln(ipm.diagnostics.meshFeatureIntervals(view),f));
xrow=a.xTrials(c.xIndex);yrow=a.yTrials(c.yIndex);
spacing=min(diff(f.coreInterval)/p.targetCoreCells(1),diff(f.frontInterval)/p.minimumFrontCells)/p.search.xPadding;
[x,construction]=ipm.remesh.corePatchAxis(anchor,f.coreCenter,family.rootX(end),961,spacing, ...
    xrow.positiveFineCells,xrow.coreFineCellFraction,xrow.roundingCells,p.search.maximumWarpFraction);
limits=rmfield(p.qualityLimits,{'minWeightToControlWidth','maxWeightToControlWidth'});
[y,info]=ipm.remesh.equalizedAxis(family.members(5).baseY/anchor,[0,f.yCoreWidth/anchor], ...
    p.targetCoreCells(2)*p.search.yPadding,struct('geometry','positive','focusCenters',0,'sigma',yrow.sigma, ...
    'power',2,'meshLimits',limits));y=y(:)*anchor;y(1)=s.y(1);y(end)=s.y(end);
assert(isequaln(x,c.x)&&isequaln(y,c.y)&&isequaln(construction,xrow.construction)&&isequaln(info,yrow.equalizerInfo));
parameters=struct('xIndex',c.xIndex,'yIndex',c.yIndex,'positiveFineCells',xrow.positiveFineCells, ...
    'roundingCells',xrow.roundingCells,'coreFineCellFraction',xrow.coreFineCellFraction, ...
    'ySigma',yrow.sigma,'spacing',spacing,'warpFraction',p.search.maximumWarpFraction, ...
    'coreCenter',f.coreCenter,'originalCandidateExactlyReconstructed',true);
snapshot=struct('datasetIndex',1,'sourceLabel',g.report.checkpointFile,'trusted',true, ...
    'rho',s.rho,'x',s.x,'y',s.y,'scale',struct('Cx',exp(s.scale.logC_l),'Cy',exp(s.scale.logC_l),'Comega',exp(s.scale.logC_omega)), ...
    'canonicalTime',s.scale.canonicalTime,'physicalTime',s.scale.physicalTime);
dataset=struct('schemaVersion',2,'kind','ipm_frozen_grid_dataset','tag','tau8_factor3_operator_input', ...
    'snapshotCount',1,'snapshots',snapshot,'xLimits',s.x([1,end]),'yLimits',s.y([1,end])');
score=ipm_gridlab_score_frozen_pair(dataset,x,y,struct('trustedOnly',true,'meshLimits',limits, ...
    'minimumXCoreCells',32,'minimumYCoreCells',32,'minimumXFrontCells',20));
rhoX=ipm.remesh.interpolate(s.x,s.rho,x,struct('sampleDimension',2,'conservation','constant','stencilWidth',6));
rhoFrozen=ipm.remesh.interpolate(s.y,rhoX,y,struct('sampleDimension',1,'conservation','constant','stencilWidth',6));
newDx=ipm.mesh.fdMatrix(x,1,7);newView=struct('rho',rhoFrozen,'x',x,'y',y,'Dx',newDx,'source',rhoFrozen*newDx','trusted',true);
newFeature=ipm.diagnostics.meshFeatureIntervals(newView);z=score.aggregate;
gates=struct('wholeMesh',score.admissible,'sourceCore',all([z.minimumXCoreCells,z.minimumYCoreCells]>=32-1e-6), ...
    'sourceFront',z.minimumXLeftFrontCells>=20-1e-6,'interpolatedCore',all(newFeature.actualCoreCells>=31), ...
    'interpolatedFront',newFeature.leftFrontCells>=20,'peak',z.worst.rhoXMaximumRelativeChange<=.002, ...
    'cumulativePeak',s.runMetadata.autonomousMesh.cumulativeAbsolutePeakJump+z.worst.rhoXMaximumRelativeChange<=.02, ...
    'mass',z.worst.conservationRelativeDefect<=5e-12,'range',z.worst.relativeRangeViolation<=2e-4);
ready=all(structfun(@(v)islogical(v)&&isscalar(v)&&v,gates));
bundle=struct('kind','operator_only_factor3_frozen_input_v1','sourceFile',g.report.checkpointFile, ...
    'capacityFile',capacityFile,'sourceStep',s.step,'sourceScale',s.scale,'sourceNormalizedTime',s.normalizedTime, ...
    'sourceRemeshCount',s.remeshCount,'sourceConfig',s.config,'sourceReferences',s.rescaling, ...
    'originalReferenceFamily',oldFamily,'futureDraftPolicy',draft,'futureReferenceFamily',family, ...
    'candidate',c,'candidateParameters',parameters,'rhoFrozen',rhoFrozen, ...
    'score',score,'interpolatedFeature',newFeature,'inputGates',gates,'readyForOperatorResourceProbe',ready, ...
    'nativeTransferQualified',false,'LUResourceQualified',false,'PDEQualified',false);
save(fullfile(outDir,'resource_bundle.mat'),'bundle','familyAudit','-v7.3');
report=registration;report.familyAudit=familyAudit;report.sourceSignatureValidated=true;
report.productionPolicyRejectsDraft=true;report.candidateParameters=parameters;report.inputGates=gates;
report.readyForOperatorResourceProbe=ready;report.interpolatedCore=newFeature.actualCoreCells;
report.interpolatedFront=newFeature.leftFrontCells;report.pairAggregate=z;report.resourceBundleFile=fullfile(outDir,'resource_bundle.mat');
report.sourceStateUnchanged=isequaln(s,cp.payload.state);assert(report.sourceStateUnchanged);
profile off;profileInfo=profile('info');files={profileInfo.FunctionTable.FileName};
assert(~any(contains(files,{'/+mesh/build.m','/+field/poisson.m','/+evolve/flow.m','/+ipm/solve.m','/+remesh/transfer.m','/+remesh/plannedAxisPairs.m'})));
report.wallSeconds=toc(timer);report.completed=true;save(fullfile(outDir,'report.mat'),'report','profileInfo','-v7.3');
write_json(fullfile(outDir,'report.json'),report);assert(ready,'ipm:ResearchFactor3Input','Frozen input failed an original gate; do not launch its LU probe.');
fprintf('FACTOR3_RESOURCE_PREP_PASS nodes=961x321 oldFourExact=1 newSearches=0 noLU=1\n');
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
