function quality = finalQuality(history)
%IPM.DIAGNOSTICS.FINALQUALITY Compact terminal quality summary.

common = history.common;
mesh = history.mesh;
quality = struct('aspect',common.aspect(end), ...
    'horizontalScale',common.C_x(end), ...
    'verticalScale',common.C_y(end), ...
    'densityRangeViolation',common.physicalRangeViolation(end), ...
    'wallPeakLocalMaxima',common.wallPeakLocalMaxima(end), ...
    'wallPeakTVRatio',common.wallPeakTVRatio(end), ...
    'positiveWallNegativeRatio',common.positiveWallNegativeRatio(end), ...
    'positiveHalfPlaneOmegaMinimum', ...
        common.positiveHalfPlaneOmegaMinimum(end), ...
    'positiveHalfPlaneOmegaNegativeRatio', ...
        common.positiveHalfPlaneOmegaNegativeRatio(end), ...
    'maximumCellRatioX',mesh.maximumCellRatioX(end), ...
    'maximumCellRatioY',mesh.maximumCellRatioY(end), ...
    'globalGridRatioX',mesh.globalGridRatioX(end), ...
    'globalGridRatioY',mesh.globalGridRatioY(end));

optional = { ...
    'safetyFactor','mesh','safetyFactor'; ...
    'horizontalCorePoints','mesh','coreGridPoints'; ...
    'verticalCorePoints','mesh','verticalCoreGridPoints'; ...
    'omegaGaugeResidual','gauge','omegaGaugeResidual'; ...
    'omegaGaugeEnergy','gauge','omegaGaugeEnergy'; ...
    'omegaGaugeEnergyX','gauge','omegaGaugeEnergyX'; ...
    'omegaGaugeEnergyY','gauge','omegaGaugeEnergyY'; ...
    'omegaGaugeForcing','gauge','omegaGaugeForcing'; ...
    'omegaGaugeForcingCancellationRatio','gauge', ...
        'omegaGaugeForcingCancellationRatio'; ...
    'cOmegaOverCL','gauge','cOmegaOverCL'; ...
    'cLMinusCOmegaOverCL','gauge','cLMinusCOmegaOverCL'; ...
    'omegaGaugeAnchorCondition','gauge','omegaGaugeAnchorCondition'; ...
    'omegaGaugeAnchorRateResidual','gauge', ...
        'omegaGaugeAnchorRateResidual'; ...
    'omegaGaugeWindowCondition','gauge','omegaGaugeWindowCondition'; ...
    'omegaGaugeWindowRateResidual','gauge', ...
        'omegaGaugeWindowRateResidual'; ...
    'omegaGaugeTemplateCondition','gauge','omegaGaugeTemplateCondition'; ...
    'omegaGaugeTemplateRateResidual','gauge', ...
        'omegaGaugeTemplateRateResidual'; ...
    'omegaGaugeBulkCondition','gauge','omegaGaugeBulkCondition'; ...
    'omegaGaugeBulkRateResidual','gauge', ...
        'omegaGaugeBulkRateResidual'; ...
    'omegaGaugeQuadraticPeakX','gauge', ...
        'omegaGaugeQuadraticPeakX'; ...
    'omegaGaugeQuadraticPeakValue','gauge', ...
        'omegaGaugeQuadraticPeakValue'; ...
    'omegaGaugeQuadraticForcing','gauge', ...
        'omegaGaugeQuadraticForcing'; ...
    'omegaGaugeQuadraticCurvatureCondition','gauge', ...
        'omegaGaugeQuadraticCurvatureCondition'; ...
    'omegaGaugeQuadraticWeightCondition','gauge', ...
        'omegaGaugeQuadraticWeightCondition'; ...
    'omegaGaugeQuadraticActiveNodeMargin','gauge', ...
        'omegaGaugeQuadraticActiveNodeMargin'; ...
    'omegaGaugeQuadraticVertexInteriorFraction','gauge', ...
        'omegaGaugeQuadraticVertexInteriorFraction'; ...
    'omegaGaugeQuadraticRateResidual','gauge', ...
        'omegaGaugeQuadraticRateResidual'; ...
    'omegaGaugeQuadraticActiveSelectionMargin','gauge', ...
        'omegaGaugeQuadraticActiveSelectionMargin'; ...
    'omegaGaugeQuadraticStencilCenterX','gauge', ...
        'omegaGaugeQuadraticStencilCenterX'; ...
    'strainCondition','gauge','strainCondition'; ...
    'lengthGaugeResidual','gauge','lengthGaugeResidual'; ...
    'travelingWaveResidual','gauge','travelingWaveResidual'; ...
    'peakTranslationResidual','anisotropic','peakTranslationResidual'};
for index = 1:size(optional,1)
    outputName = optional{index,1};
    group = history.(optional{index,2});
    historyName = optional{index,3};
    if isfield(group,historyName)
        quality.(outputName) = group.(historyName)(end);
    end
end
if isfield(history.gauge,'omegaGaugeEnergy')
    energy = history.gauge.omegaGaugeEnergy(:);
    finiteEnergy = isfinite(energy) & energy > 0;
    if any(finiteEnergy)
        first = find(finiteEnergy,1,'first');
        reference = energy(first);
        quality.omegaGaugeEnergyInitial = reference;
        quality.omegaGaugeEnergyMaximumRelativeDrift = max( ...
            abs(energy(finiteEnergy)/reference-1));
    end
end
end
