function diagnostic = gaugeRateConvergence(canonicalTau,cL,cOmega,options)
%IPM.DIAGNOSTICS.GAUGERATECONVERGENCE Diagnose gauge-rate tail trends.
%   DIAGNOSTIC = IPM.DIAGNOSTICS.GAUGERATECONVERGENCE(TAU,CL,COMEGA)
%   measures c_l, c_omega, c_omega/c_l, and
%   (c_l-c_omega)/c_l on fixed trailing 25%, 40%, and 60% canonical-tau
%   windows.  It is diagnostic only: a provisional pass still requires
%   independent box, time-step, and grid refinement.
%
%   DIAGNOSTIC = IPM.DIAGNOSTICS.GAUGERATECONVERGENCE(...,OPTIONS) accepts
%   the optional logical scalar OPTIONS.selectedRatePrescribed.  Omitting
%   it leaves provenance unavailable.  The new zero-limit branch tests the
%   preregistered dimensionless candidate c_omega/c_l -> 0 with absolute
%   one-percent gates; provenance separately controls whether that numerical
%   pass is eligible for an empirical convergence statement.

if nargin < 4
    options = struct();
end
provenance = parse_options(options);

canonicalTau = canonicalTau(:);
cL = cL(:);
cOmega = cOmega(:);
if numel(canonicalTau) ~= numel(cL) || numel(canonicalTau) ~= numel(cOmega)
    error('ipm:GaugeRateConvergenceSize', ...
        'Canonical tau, c_l, and c_omega must have the same length.');
end

diagnostic = empty_diagnostic(provenance);
diagnostic.points = numel(canonicalTau);
diagnostic.canonicalTau = canonicalTau;
diagnostic.cL = cL;
diagnostic.cOmega = cOmega;
if diagnostic.points < diagnostic.minimumPoints
    diagnostic.validityReason = 'insufficient_points';
    return;
end
if any(~isfinite(canonicalTau)) || any(~isfinite(cL)) || ...
        any(~isfinite(cOmega))
    diagnostic.validityReason = 'nonfinite_input';
    return;
end
if any(diff(canonicalTau) <= 0)
    diagnostic.validityReason = ...
        'canonical_tau_not_strictly_increasing';
    return;
end

rateScale = max(cat(2,ones(size(cL)),abs(cL),abs(cOmega)),[],2);
safeDenominator = abs(cL) > 100*eps(rateScale);
diagnostic.ratiosAvailable = all(safeDenominator);
if diagnostic.ratiosAvailable
    diagnostic.cOmegaOverCL = cOmega./cL;
    diagnostic.cLMinusCOmegaOverCL = (cL-cOmega)./cL;
else
    diagnostic.cOmegaOverCL = NaN(size(cL));
    diagnostic.cLMinusCOmegaOverCL = NaN(size(cL));
end

series = struct('cL',cL,'cOmega',cOmega, ...
    'cOmegaOverCL',diagnostic.cOmegaOverCL, ...
    'cLMinusCOmegaOverCL',diagnostic.cLMinusCOmegaOverCL);
fractions = diagnostic.windowFractions;
windows = repmat(empty_window(),numel(fractions),1);
for index = 1:numel(fractions)
    [windowTau,windowSeries,originalPoints] = trailing_window( ...
        canonicalTau,series,fractions(index));
    windows(index).trailingFraction = fractions(index);
    windows(index).startCanonicalTau = windowTau(1);
    windows(index).endCanonicalTau = windowTau(end);
    windows(index).canonicalTauSpan = windowTau(end)-windowTau(1);
    windows(index).points = numel(windowTau);
    windows(index).originalPoints = originalPoints;
    for seriesIndex = 1:numel(diagnostic.seriesNames)
        name = diagnostic.seriesNames{seriesIndex};
        windows(index).(name) = window_statistics( ...
            windowTau,windowSeries.(name));
    end
end

diagnostic.windows = windows;
for seriesIndex = 1:numel(diagnostic.seriesNames)
    name = diagnostic.seriesNames{seriesIndex};
    diagnostic.seriesSummary.(name) = summarize_windows( ...
        windows,name,diagnostic.relativeTrendTolerance, ...
        diagnostic.windowMeanSpreadTolerance, ...
        diagnostic.relativeDetrendedRmsTolerance);
end
diagnostic.cLNonzeroAndStable = diagnostic.ratiosAvailable && ...
    diagnostic.seriesSummary.cL.valid && ...
    diagnostic.seriesSummary.cL.stable;
diagnostic.cOmegaZeroLimit = summarize_zero_limit( ...
    windows,'cOmegaOverCL',diagnostic.zeroLimitTolerance);
diagnostic.cOmegaZeroLimitStable = ...
    diagnostic.cLNonzeroAndStable && diagnostic.cOmegaZeroLimit.stable;
diagnostic.zeroAwareProvisionalStable = ...
    diagnostic.empiricalRateConvergenceEligible && ...
    diagnostic.seriesSummary.cL.stable && ...
    (diagnostic.seriesSummary.cOmega.stable || ...
    diagnostic.cOmegaZeroLimitStable);
diagnostic.valid = diagnostic.seriesSummary.cL.valid && ...
    diagnostic.seriesSummary.cOmega.valid;
if ~diagnostic.valid
    diagnostic.validityReason = 'relative_statistics_undefined';
    return;
end
diagnostic.validityReason = 'valid';
diagnostic.provisionalStable = ...
    diagnostic.seriesSummary.cL.stable && ...
    diagnostic.seriesSummary.cOmega.stable;
diagnostic.ratioDiagnosticsStable = ...
    diagnostic.ratiosAvailable && ...
    diagnostic.seriesSummary.cOmegaOverCL.stable && ...
    diagnostic.seriesSummary.cLMinusCOmegaOverCL.stable;
end

function provenance = parse_options(options)
if isempty(options)
    options = struct();
end
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeRateConvergenceOptions', ...
        'Gauge-rate convergence options must be a scalar structure.');
end
names = fieldnames(options);
unknown = setdiff(names,{'selectedRatePrescribed'});
if ~isempty(unknown)
    error('ipm:GaugeRateConvergenceOptions', ...
        'Unknown gauge-rate convergence option: %s.',unknown{1});
end
provenance = struct('selectedRatePrescribed',false, ...
    'selectedRateProvenanceAvailable',false, ...
    'empiricalRateConvergenceEligible',false, ...
    'empiricalRateConvergenceEligibilityReason', ...
        'selected_rate_provenance_unavailable');
if ~isfield(options,'selectedRatePrescribed')
    return;
end
value = options.selectedRatePrescribed;
if ~islogical(value) || ~isscalar(value)
    error('ipm:GaugeRateConvergenceOptions', ...
        'options.selectedRatePrescribed must be a logical scalar.');
end
provenance.selectedRatePrescribed = value;
provenance.selectedRateProvenanceAvailable = true;
if value
    provenance.empiricalRateConvergenceEligibilityReason = ...
        'selected_rate_prescribed';
else
    provenance.empiricalRateConvergenceEligible = true;
    provenance.empiricalRateConvergenceEligibilityReason = ...
        'selected_rate_nonprescribed';
end
end

function [windowTau,windowSeries,originalPoints] = ...
        trailing_window(tau,series,fraction)
startTau = tau(end)-fraction*(tau(end)-tau(1));
first = find(tau >= startTau,1,'first');
names = fieldnames(series);
if tau(first) > startTau && first > 1
    interpolationWeight = (startTau-tau(first-1))/ ...
        (tau(first)-tau(first-1));
    windowTau = [startTau;tau(first:end)];
    for index = 1:numel(names)
        name = names{index};
        values = series.(name);
        startValue = values(first-1)+interpolationWeight* ...
            (values(first)-values(first-1));
        windowSeries.(name) = [startValue;values(first:end)];
    end
else
    windowTau = tau(first:end);
    for index = 1:numel(names)
        name = names{index};
        values = series.(name);
        windowSeries.(name) = values(first:end);
    end
end
originalPoints = numel(tau)-first+1;
end

function statistics = window_statistics(tau,values)
statistics = empty_statistics();
if numel(tau) < 2 || any(~isfinite(values))
    return;
end
weights = trapezoidal_weights(tau);
weightedMean = sum(weights.*values)/sum(weights);
centerTau = sum(weights.*tau)/sum(weights);
centeredTau = tau-centerTau;
denominator = sum(weights.*centeredTau.^2);
if denominator <= 0
    return;
end
slope = sum(weights.*centeredTau.*(values-weightedMean))/denominator;
intercept = weightedMean;
residual = values-(intercept+slope*centeredTau);
detrendedRms = sqrt(sum(weights.*residual.^2)/sum(weights));
valueScale = max(1,max(abs(values)));
relativeFloor = 100*eps(valueScale);
if abs(weightedMean) > relativeFloor
    relativeTrend = slope*(tau(end)-tau(1))/abs(weightedMean);
    relativeDetrendedRms = detrendedRms/abs(weightedMean);
else
    relativeTrend = NaN;
    relativeDetrendedRms = NaN;
end
statistics.valid = true;
statistics.weightedMean = weightedMean;
statistics.slope = slope;
statistics.maximumAbsoluteValue = max(abs(values));
statistics.absoluteTrendSpan = abs(slope)*(tau(end)-tau(1));
statistics.relativeTrend = relativeTrend;
statistics.detrendedRms = detrendedRms;
statistics.relativeDetrendedRms = relativeDetrendedRms;
end

function summary = summarize_zero_limit(windows,name,tolerance)
summary = empty_zero_limit_summary();
statistics = arrayfun(@(window)window.(name),windows);
if ~all([statistics.valid])
    return;
end
summary.windowWeightedMeans = [statistics.weightedMean];
summary.windowMaximumAbsoluteValues = ...
    [statistics.maximumAbsoluteValue];
summary.windowAbsoluteTrendSpans = [statistics.absoluteTrendSpan];
summary.windowDetrendedRms = [statistics.detrendedRms];
values = [summary.windowWeightedMeans, ...
    summary.windowMaximumAbsoluteValues, ...
    summary.windowAbsoluteTrendSpans,summary.windowDetrendedRms];
if any(~isfinite(values))
    return;
end
summary.maximumAbsoluteValue = ...
    max(summary.windowMaximumAbsoluteValues);
summary.maximumAbsoluteTrendSpan = ...
    max(summary.windowAbsoluteTrendSpans);
summary.maximumDetrendedRms = max(summary.windowDetrendedRms);
summary.windowMeanSpread = max(summary.windowWeightedMeans)- ...
    min(summary.windowWeightedMeans);
summary.levelWithinTolerance = ...
    summary.maximumAbsoluteValue <= tolerance;
summary.trendWithinTolerance = ...
    summary.maximumAbsoluteTrendSpan <= tolerance;
summary.detrendedRmsWithinTolerance = ...
    summary.maximumDetrendedRms <= tolerance;
summary.windowMeanSpreadWithinTolerance = ...
    summary.windowMeanSpread <= tolerance;
summary.valid = true;
summary.stable = summary.levelWithinTolerance && ...
    summary.trendWithinTolerance && ...
    summary.detrendedRmsWithinTolerance && ...
    summary.windowMeanSpreadWithinTolerance;
end

function summary = summarize_windows( ...
        windows,name,trendTolerance,spreadTolerance,rmsTolerance)
summary = empty_summary();
statistics = arrayfun(@(window)window.(name),windows);
statisticsValid = all([statistics.valid]);
if ~statisticsValid
    return;
end
summary.windowWeightedMeans = [statistics.weightedMean];
summary.windowSlopes = [statistics.slope];
summary.windowRelativeTrends = [statistics.relativeTrend];
summary.windowDetrendedRms = [statistics.detrendedRms];
summary.windowRelativeDetrendedRms = ...
    [statistics.relativeDetrendedRms];
if any(~isfinite(summary.windowRelativeTrends)) || ...
        any(~isfinite(summary.windowRelativeDetrendedRms))
    return;
end
summary.maximumAbsoluteRelativeTrend = ...
    max(abs(summary.windowRelativeTrends));
meanScale = max(abs(summary.windowWeightedMeans));
if meanScale <= 100*eps(max(1,meanScale))
    return;
end
summary.relativeWindowMeanSpread = ...
    (max(summary.windowWeightedMeans)- ...
    min(summary.windowWeightedMeans))/meanScale;
summary.trendWithinTolerance = ...
    summary.maximumAbsoluteRelativeTrend <= trendTolerance;
summary.windowMeanSpreadWithinTolerance = ...
    summary.relativeWindowMeanSpread <= spreadTolerance;
summary.maximumRelativeDetrendedRms = ...
    max(summary.windowRelativeDetrendedRms);
summary.detrendedRmsWithinTolerance = ...
    summary.maximumRelativeDetrendedRms <= rmsTolerance;
summary.valid = true;
summary.stable = summary.trendWithinTolerance && ...
    summary.windowMeanSpreadWithinTolerance && ...
    summary.detrendedRmsWithinTolerance;
end

function weights = trapezoidal_weights(tau)
spacing = diff(tau);
weights = [spacing(1)/2; ...
    (spacing(1:end-1)+spacing(2:end))/2;spacing(end)/2];
end

function diagnostic = empty_diagnostic(provenance)
seriesNames = {'cL','cOmega','cOmegaOverCL', ...
    'cLMinusCOmegaOverCL'};
summary = struct();
for index = 1:numel(seriesNames)
    summary.(seriesNames{index}) = empty_summary();
end
diagnostic = struct('valid',false,'validityReason','unavailable', ...
    'criteriaVersion',3, ...
    'points',0,'minimumPoints',16, ...
    'coordinateName','canonical_tau', ...
    'coordinateWeighting','trapezoidal_canonical_tau', ...
    'windowFractions',[0.25,0.40,0.60], ...
    'relativeTrendTolerance',0.01, ...
    'windowMeanSpreadTolerance',0.01, ...
    'relativeDetrendedRmsTolerance',0.01, ...
    'zeroLimitCandidate','cOmegaOverCL', ...
    'zeroLimitTolerance',0.01, ...
    'provisionalStable',false,'ratioDiagnosticsStable',false, ...
    'cLNonzeroAndStable',false, ...
    'cOmegaZeroLimitStable',false, ...
    'zeroAwareProvisionalStable',false, ...
    'ratiosAvailable',false, ...
    'selectedRatePrescribed',provenance.selectedRatePrescribed, ...
    'selectedRateProvenanceAvailable', ...
        provenance.selectedRateProvenanceAvailable, ...
    'empiricalRateConvergenceEligible', ...
        provenance.empiricalRateConvergenceEligible, ...
    'empiricalRateConvergenceEligibilityReason', ...
        provenance.empiricalRateConvergenceEligibilityReason, ...
    'interpretation', ...
        'diagnostic_only_requires_box_time_grid_refinement', ...
    'provisionalStableCriteria', ...
        ['cL_and_cOmega_each_max_abs_relative_trend_le_1pct_' ...
        'nested_window_mean_spread_le_1pct_' ...
        'and_max_relative_detrended_rms_le_1pct'], ...
    'zeroLimitCriteria', ...
        ['cOmega_over_cL_each_window_max_abs_level_abs_trend_span_' ...
        'detrended_rms_and_nested_window_mean_spread_le_1pct_' ...
        'with_nonzero_stable_cL'], ...
    'seriesNames',{seriesNames},'canonicalTau',[],'cL',[], ...
    'cOmega',[],'cOmegaOverCL',[], ...
    'cLMinusCOmegaOverCL',[], ...
    'windows',repmat(empty_window(),0,1), ...
    'seriesSummary',summary, ...
    'cOmegaZeroLimit',empty_zero_limit_summary());
end

function window = empty_window()
window = struct('trailingFraction',NaN, ...
    'startCanonicalTau',NaN,'endCanonicalTau',NaN, ...
    'canonicalTauSpan',NaN,'points',0,'originalPoints',0, ...
    'cL',empty_statistics(),'cOmega',empty_statistics(), ...
    'cOmegaOverCL',empty_statistics(), ...
    'cLMinusCOmegaOverCL',empty_statistics());
end

function statistics = empty_statistics()
statistics = struct('valid',false,'weightedMean',NaN,'slope',NaN, ...
    'maximumAbsoluteValue',NaN,'absoluteTrendSpan',NaN, ...
    'relativeTrend',NaN,'detrendedRms',NaN, ...
    'relativeDetrendedRms',NaN);
end

function summary = empty_zero_limit_summary()
summary = struct('valid',false,'windowWeightedMeans',[], ...
    'windowMaximumAbsoluteValues',[], ...
    'windowAbsoluteTrendSpans',[],'windowDetrendedRms',[], ...
    'maximumAbsoluteValue',NaN,'maximumAbsoluteTrendSpan',NaN, ...
    'maximumDetrendedRms',NaN,'windowMeanSpread',NaN, ...
    'levelWithinTolerance',false,'trendWithinTolerance',false, ...
    'detrendedRmsWithinTolerance',false, ...
    'windowMeanSpreadWithinTolerance',false,'stable',false);
end

function summary = empty_summary()
summary = struct('valid',false,'windowWeightedMeans',[], ...
    'windowSlopes',[],'windowRelativeTrends',[], ...
    'windowDetrendedRms',[],'windowRelativeDetrendedRms',[], ...
    'maximumAbsoluteRelativeTrend',NaN, ...
    'relativeWindowMeanSpread',NaN, ...
    'maximumRelativeDetrendedRms',NaN, ...
    'trendWithinTolerance',false, ...
    'windowMeanSpreadWithinTolerance',false, ...
    'detrendedRmsWithinTolerance',false,'stable',false);
end
