function events = postRemeshWarnings( ...
        rho,flow,ops,scale,mass0,rhoRange0,diagnostics,remesh)
%IPM.DIAGNOSTICS.POSTREMESHWARNINGS Audit an accepted replacement grid.
%   The returned events are observations only. They never reject a mesh,
%   roll back an accepted state, or terminate time evolution.

d = ipm.diagnostics.measure(rho,flow,ops,mass0);
physicalGradient = ipm.diagnostics.physicalGradientInf(d,scale,rho,ops);
amplitudeInverse = exp(-scale.logC_omega);
physicalMinimum = amplitudeInverse*d.rhoMin;
physicalMaximum = amplitudeInverse*d.rhoMax;
rangeViolation = max([rhoRange0(1)-physicalMinimum, ...
    physicalMaximum-rhoRange0(2),0]);
ratioX = maximum_cell_ratio(ops.dxFaces);
ratioY = maximum_cell_ratio(ops.dyFaces);

events = empty_events();
events = add_if(events,physicalGradient >= diagnostics.gradientStop, ...
    'gradient_threshold','physical_gradient_inf',physicalGradient, ...
    diagnostics.gradientStop, ...
    sprintf('physical ||grad rho||_inf %.6e exceeds %.6e', ...
    physicalGradient,diagnostics.gradientStop));
events = add_if(events,rangeViolation >= diagnostics.rangeStopTolerance, ...
    'maximum_principle_violation','physical_range_violation', ...
    rangeViolation,diagnostics.rangeStopTolerance, ...
    sprintf('physical density range violation %.6e exceeds %.6e', ...
    rangeViolation,diagnostics.rangeStopTolerance));
events = add_if(events,d.wallPeakLocalMaxima > 1 && ...
    d.wallPeakTVRatio > diagnostics.oscillationTVTolerance, ...
    'wall_profile_oscillation','wall_peak_tv_ratio', ...
    d.wallPeakTVRatio,diagnostics.oscillationTVTolerance, ...
    sprintf('wall profile has %d local maxima and TV ratio %.6e exceeds %.6e', ...
    d.wallPeakLocalMaxima,d.wallPeakTVRatio, ...
    diagnostics.oscillationTVTolerance));
events = add_if(events,d.positiveWallNegativeRatio > ...
    diagnostics.positiveWallNegativeTolerance, ...
    'wall_profile_oscillation','positive_wall_negative_ratio', ...
    d.positiveWallNegativeRatio,diagnostics.positiveWallNegativeTolerance, ...
    sprintf('positive-wall negative ratio %.6e exceeds %.6e', ...
    d.positiveWallNegativeRatio, ...
    diagnostics.positiveWallNegativeTolerance));
events = add_if(events,ratioX > remesh.remeshMaximumCellRatio*(1+1e-10), ...
    'grid_smoothness_failure','maximum_adjacent_cell_ratio_x',ratioX, ...
    remesh.remeshMaximumCellRatio, ...
    sprintf('x adjacent-cell ratio %.6e exceeds %.6e', ...
    ratioX,remesh.remeshMaximumCellRatio));
events = add_if(events,ratioY > remesh.remeshMaximumCellRatio*(1+1e-10), ...
    'grid_smoothness_failure','maximum_adjacent_cell_ratio_y',ratioY, ...
    remesh.remeshMaximumCellRatio, ...
    sprintf('y adjacent-cell ratio %.6e exceeds %.6e', ...
    ratioY,remesh.remeshMaximumCellRatio));

if isfinite(flow.safetyFactor)
    counts = [flow.peakGridPoints,flow.supportGridPoints, ...
        flow.coreGridPoints,flow.verticalPeakGridPoints, ...
        flow.verticalSupportGridPoints,flow.verticalCoreGridPoints];
    r = ops.rescaling;
    minimumCounts = 0.5*[r.safetyPeakPoints,r.safetyLevelPoints(1), ...
        r.safetyLevelPoints(end),r.safetyVerticalPeakPoints, ...
        r.safetyVerticalLevelPoints(1),r.safetyVerticalLevelPoints(end)];
    resolutionMargin = min(counts./minimumCounts);
    events = add_if(events,ipm.diagnostics.resolutionFailed(flow,ops), ...
        'grid_resolution_failure','minimum_resolution_margin', ...
        resolutionMargin,1, ...
        sprintf(['minimum post-remesh resolution margin %.6e is below 1; ' ...
        'observed counts [%s]'],resolutionMargin,sprintf(' %.6g',counts)));
end
end

function events = empty_events()
events = struct('code',{},'metric',{},'value',{},'threshold',{}, ...
    'message',{});
end

function events = add_if( ...
        events,condition,code,metric,value,threshold,message)
if ~condition
    return;
end
event = struct('code',code,'metric',metric,'value',value, ...
    'threshold',threshold,'message',message);
events(end+1) = event;
end

function ratio = maximum_cell_ratio(widths)
if numel(widths) < 2
    ratio = 1;
else
    ratio = max(max(widths(2:end)./widths(1:end-1), ...
        widths(1:end-1)./widths(2:end)));
end
end
