function failed = resolutionFailed(flow,ops)
%IPM.DIAGNOSTICS.RESOLUTIONFAILED Historical lower-bound classification.
%   Runtime callers may use this only as post-remesh warning evidence.

if ~isfinite(flow.safetyFactor)
    failed = false;
    return;
end
r = ops.rescaling;
failed = flow.peakGridPoints < 0.5*r.safetyPeakPoints || ...
    flow.supportGridPoints < 0.5*r.safetyLevelPoints(1) || ...
    flow.coreGridPoints < 0.5*r.safetyLevelPoints(end) || ...
    flow.verticalPeakGridPoints < 0.5*r.safetyVerticalPeakPoints || ...
    flow.verticalSupportGridPoints < ...
        0.5*r.safetyVerticalLevelPoints(1) || ...
    flow.verticalCoreGridPoints < 0.5*r.safetyVerticalLevelPoints(end);
end
