function details = trackFeatures(rho,physicalRhs,flow,ops)
%IPM.DIAGNOSTICS.TRACKFEATURES Extract peak, crossing, width, and resolution data.

details = empty_details();
r = ops.rescaling;
sourceScale = max(abs(flow.source),[],'all');
details.rhoXInf = sourceScale;

if ~r.enabled && ~isfield(r,'pinX')
    return;
end

trackingMask = abs(ops.x-r.pinX) <= r.peakTrackingHalfWidth;
wall = ipm.diagnostics.measureFeatures( ...
    flow.source(1,:),ops.x,r.adaptiveLevels,trackingMask);
if ~r.enabled && wall.peak <= 0
    return;
end
trackedPeakX = ipm.diagnostics.peakLocation( ...
    wall.feature,ops.x,wall.peakIndex);
if r.enabled && strcmp(r.lengthGauge,'wall_omega_width')
    [~,reportedWidthIndex] = max(r.adaptiveLevels);
else
    [~,reportedWidthIndex] = min(abs(r.adaptiveLevels-0.5));
end
levelGridPoints = wall.gridPoints;
% Count only the connected primary component; remote tails cannot hide
% an under-resolved core.
peakGridPoints = wall.areaPoints(1);
vertical = ipm.diagnostics.measureFeatures( ...
    abs(flow.source(:,wall.peakIndex))',ops.y',r.adaptiveLevels,[]);
if r.enabled && strcmp(r.lengthGauge,'wall_density_width')
    positive = find(ops.x >= 0);
    wallDensity = rho(1,positive);
    wallScale = max(wallDensity);
    if wallScale <= r.cOmegaGaugeFloor
        error('ipm:DegenerateLengthGauge', ...
            'Wall density is too small for the width length gauge.');
    end
    normalizedWallDensity = wallDensity/wallScale;
    [details.wallDensityLowerX,details.wallDensityLowerSlope, ...
        details.wallDensityLowerCondition, ...
        details.wallDensityLowerBracket] = upward_crossing( ...
        ops.x(positive),normalizedWallDensity,r.lengthGaugeLevels(1));
    [details.wallDensityUpperX,details.wallDensityUpperSlope, ...
        details.wallDensityUpperCondition, ...
        details.wallDensityUpperBracket] = upward_crossing( ...
        ops.x(positive),normalizedWallDensity,r.lengthGaugeLevels(2));
    details.wallDensityWidth = ...
        details.wallDensityUpperX-details.wallDensityLowerX;
    if details.wallDensityWidth <= 100*eps(max(abs([ ...
            details.wallDensityLowerX,details.wallDensityUpperX])))
        error('ipm:DegenerateLengthGauge', ...
            'Wall-density level crossings are not separated.');
    end
elseif r.enabled && strcmp(r.lengthGauge,'wall_omega_width')
    level = r.adaptiveLevels(reportedWidthIndex);
    rate0 = physicalRhs*ops.Dx';
    details.wallWidthRate = normalized_width_rate( ...
        wall.feature,rate0(1,:),ops.x,wall.peakIndex,level);
    details.wallWidthCurrent = wall.widths(reportedWidthIndex);
end

details = measured_details(details,wall,vertical,trackedPeakX, ...
    reportedWidthIndex,r,ops.x,sourceScale);
% These counts are diagnostics and hard-stop/remesh evidence only.  They
% never feed back into c_l or c_omega under the exact-gauge contract.
details.peakExpansionRatio = max([ ...
    peakGridPoints/max(r.referencePeakPoints,eps), ...
    levelGridPoints./max(r.referenceLevelPoints,eps)]);
details.resolutionFactor = max([ ...
    r.adaptiveTargetPeakPoints/max(peakGridPoints,1), ...
    r.adaptiveTargetLevelPoints./max(levelGridPoints,1), ...
    r.adaptiveTargetVerticalPeakPoints/ ...
    max(vertical.areaPoints(1),1), ...
    r.adaptiveTargetVerticalLevelPoints./ ...
    max(vertical.gridPoints,1)]);
details.safetyFactor = max([ ...
    r.safetyPeakPoints/max(peakGridPoints,1), ...
    r.safetyLevelPoints./max(levelGridPoints,1), ...
    r.safetyVerticalPeakPoints/max(vertical.areaPoints(1),1), ...
    r.safetyVerticalLevelPoints./max(vertical.gridPoints,1)]);
end

function details = measured_details(details,wall,vertical,trackedPeakX, ...
        reportedWidthIndex,r,x,sourceScale)
[~,verticalHalfIndex] = min(abs(r.adaptiveLevels-0.5));
details.peakGridPoints = wall.areaPoints(1);
details.levelGridPoints = wall.gridPoints;
details.supportGridPoints = wall.gridPoints(1);
details.coreGridPoints = wall.gridPoints(end);
details.verticalPeakGridPoints = vertical.areaPoints(1);
details.verticalLevelGridPoints = vertical.gridPoints;
details.verticalSupportGridPoints = vertical.gridPoints(1);
details.verticalCoreGridPoints = vertical.gridPoints(end);
details.trackedVerticalPeakWidth = vertical.widths(verticalHalfIndex);
details.trackedVerticalCoreWidth = vertical.widths(end);
details.targetPeakGridPoints = r.adaptiveTargetPeakPoints;
details.targetSupportGridPoints = r.adaptiveTargetLevelPoints(1);
details.targetCoreGridPoints = r.adaptiveTargetLevelPoints(end);
details.trackedWallPeak = wall.peak;
details.trackedWallPeakWidth = wall.widths(reportedWidthIndex);
details.trackedWallCoreWidth = wall.widths(end);
details.wallOmegaPeakIndex = wall.peakIndex;
details.omegaGaugePeakX = x(wall.peakIndex);
details.omegaGaugePeakCondition = wall.peak/sourceScale;
details.trackedPeakX = trackedPeakX;
details.trackedPeakOffset = trackedPeakX-r.pinX;
end

function details = empty_details()
details = struct('c_lNominal',0,'lengthScaleGain',1, ...
    'widthCorrection',0,'widthControlMode',0,'peakGridPoints',NaN, ...
    'levelGridPoints',[],'verticalLevelGridPoints',[], ...
    'supportGridPoints',NaN,'coreGridPoints',NaN, ...
    'verticalPeakGridPoints',NaN,'verticalSupportGridPoints',NaN, ...
    'verticalCoreGridPoints',NaN, ...
    'targetPeakGridPoints',NaN,'targetSupportGridPoints',NaN, ...
    'targetCoreGridPoints',NaN,'peakExpansionRatio',NaN, ...
    'resolutionFactor',1,'safetyFactor',NaN, ...
    'trackedWallPeak',NaN,'trackedWallPeakWidth',NaN, ...
    'trackedWallCoreWidth',NaN, ...
    'trackedVerticalPeakWidth',NaN,'trackedVerticalCoreWidth',NaN, ...
    'strain',NaN,'strainError',NaN,'strainCondition',NaN, ...
    'strainRateResidual',NaN,'omegaGaugeEnergy',NaN, ...
    'omegaGaugeEnergyX',NaN,'omegaGaugeEnergyY',NaN, ...
    'omegaGaugeForcingX',NaN,'omegaGaugeForcingY',NaN, ...
    'omegaGaugeForcing',NaN,'omegaGaugeAbsoluteForcing',NaN, ...
    'omegaGaugeForcingCancellationRatio',NaN, ...
    'omegaGaugeResidual',NaN,'omegaPeakRateResidual',NaN, ...
    'omegaGaugePeakX',NaN,'omegaGaugePeakCondition',NaN, ...
    'omegaGaugeQuadraticPeakX',NaN, ...
    'omegaGaugeQuadraticPeakValue',NaN, ...
    'omegaGaugeQuadraticForcing',NaN, ...
    'omegaGaugeQuadraticCurvature',NaN, ...
    'omegaGaugeQuadraticStationarityResidual',NaN, ...
    'omegaGaugeQuadraticNormalizedStationarityResidual',NaN, ...
    'omegaGaugeQuadraticCurvatureCondition',NaN, ...
    'omegaGaugeQuadraticWeightCondition',NaN, ...
    'omegaGaugeQuadraticActiveNodeMargin',NaN, ...
    'omegaGaugeQuadraticActiveSelectionMargin',NaN, ...
    'omegaGaugeQuadraticStencilCenterX',NaN, ...
    'omegaGaugeQuadraticVertexInteriorFraction',NaN, ...
    'omegaGaugeQuadraticRelativeSubgridLift',NaN, ...
    'omegaGaugeQuadraticRateResidual',NaN, ...
    'omegaGaugeQuadraticRateScale',NaN, ...
    'omegaGaugeAnchorX',NaN,'omegaGaugeAnchorValue',NaN, ...
    'omegaGaugeAnchorCondition',NaN, ...
    'omegaGaugeAnchorRateResidual',NaN, ...
    'omegaGaugeReferenceAnchorValue',NaN, ...
    'omegaGaugeWindowCenter',NaN,'omegaGaugeWindowRadius',NaN, ...
    'omegaGaugeWindowValue',NaN,'omegaGaugeWindowCondition',NaN, ...
    'omegaGaugeWindowEnergy',NaN,'omegaGaugeWindowRateResidual',NaN, ...
    'omegaGaugeReferenceWindowValue',NaN, ...
    'omegaGaugeWindowMomentOrder',NaN,'omegaGaugeWindowMoment',NaN, ...
    'omegaGaugeWindowSupportPoints',NaN, ...
    'omegaGaugeWindowRateScale',NaN, ...
    'omegaGaugeTemplateCenter',NaN,'omegaGaugeTemplateRadius',NaN, ...
    'omegaGaugeTemplateSupportPoints',NaN, ...
    'omegaGaugeTemplateValue',NaN,'omegaGaugeTemplateCondition',NaN, ...
    'omegaGaugeTemplateRateResidual',NaN, ...
    'omegaGaugeTemplateRateScale',NaN, ...
    'omegaGaugeReferenceTemplateValue',NaN, ...
    'omegaGaugeBulkCenterX',NaN,'omegaGaugeBulkCenterY',NaN, ...
    'omegaGaugeBulkRadius',NaN,'omegaGaugeBulkSupportPointsX',NaN, ...
    'omegaGaugeBulkSupportPointsY',NaN,'omegaGaugeBulkValue',NaN, ...
    'omegaGaugeBulkCondition',NaN,'omegaGaugeBulkEnergy',NaN, ...
    'omegaGaugeBulkRateResidual',NaN,'omegaGaugeBulkRateScale',NaN, ...
    'omegaGaugeReferenceBulkValue',NaN, ...
    'pinGaugeResidual',NaN,'pinTransportVelocity',NaN, ...
    'transportAnchorX',NaN,'transportAnchorVelocity',NaN, ...
    'lengthGaugeStrain',NaN,'lengthGaugeResidual',NaN, ...
    'peakLocationRhoXX',NaN,'peakLocationRhoXXScale',NaN, ...
    'peakLocationPhaseDefect',NaN, ...
    'peakLocationResponseCondition',NaN, ...
    'peakLocationFullPhaseResidual',NaN, ...
    'peakLocationNormalizedFullPhaseResidual',NaN, ...
    'widthRateScale',NaN,'trackedPeakX',NaN, ...
    'trackedPeakOffset',NaN,'peakTransportVelocity',NaN, ...
    'wallOmegaPeakIndex',NaN,'wallDensityLowerX',NaN, ...
    'wallDensityUpperX',NaN,'wallDensityWidth',NaN, ...
    'wallDensityLowerSlope',NaN,'wallDensityUpperSlope',NaN, ...
    'wallDensityLowerCondition',NaN,'wallDensityUpperCondition',NaN, ...
    'wallDensityLowerBracket',NaN,'wallDensityUpperBracket',NaN, ...
    'wallWidthRate',NaN,'wallWidthCurrent',NaN, ...
    'travelingWaveResidual',NaN,'rhoXInf',NaN);
end

function widthRate = normalized_width_rate( ...
        feature,featureRate,x,peakIndex,level)
peak = feature(peakIndex);
threshold = level*peak;
leftNode = peakIndex;
while leftNode > 1 && feature(leftNode-1) >= threshold
    leftNode = leftNode-1;
end
rightNode = peakIndex;
while rightNode < numel(feature) && feature(rightNode+1) >= threshold
    rightNode = rightNode+1;
end
if leftNode == 1 || rightNode == numel(feature)
    error('ipm:DegenerateLengthGauge', ...
        'The tracked wall-omega half-height component is not interior.');
end

[leftSlope,leftRate] = crossing_data(leftNode-1,leftNode, ...
    feature,featureRate,x,threshold);
[rightSlope,rightRate] = crossing_data(rightNode,rightNode+1, ...
    feature,featureRate,x,threshold);
peakRate = featureRate(peakIndex);
leftVelocity = -(leftRate-level*peakRate)/leftSlope;
rightVelocity = -(rightRate-level*peakRate)/rightSlope;
widthRate = rightVelocity-leftVelocity;
end

function [slope,rate] = crossing_data( ...
        left,right,feature,featureRate,x,threshold)
valueDifference = feature(right)-feature(left);
if abs(valueDifference) <= 100*eps(max(abs(feature)))
    error('ipm:DegenerateLengthGauge', ...
        'A wall-omega half-height crossing has zero discrete slope.');
end
fraction = (threshold-feature(left))/valueDifference;
slope = valueDifference/(x(right)-x(left));
rate = featureRate(left)+fraction*(featureRate(right)-featureRate(left));
end

function [crossing,slope,condition,leftIndex] = ...
        upward_crossing(x,values,level)
index = find(values >= level,1,'first');
if isempty(index)
    error('ipm:DegenerateLengthGauge', ...
        'A wall-density length-gauge level has no crossing.');
end
if index == 1
    error('ipm:DegenerateLengthGauge', ...
        'A wall-density crossing is not bracketed in the open profile.');
end
leftValue = values(index-1);
rightValue = values(index);
valueDifference = rightValue-leftValue;
valueScale = max(abs(values));
if valueDifference <= 100*eps(max(valueScale,1))
    error('ipm:DegenerateLengthGauge', ...
        ['A wall-density crossing has zero, reversed, or numerically ' ...
        'unresolved discrete slope.']);
end
fraction = (level-leftValue)/valueDifference;
if ~isfinite(fraction) || fraction < 0 || fraction > 1
    error('ipm:DegenerateLengthGauge', ...
        'A wall-density crossing left its discrete interpolation bracket.');
end
crossing = x(index-1)+fraction*(x(index)-x(index-1));
slope = valueDifference/(x(index)-x(index-1));
condition = valueDifference/max(valueScale,realmin);
leftIndex = index-1;
end
