function comparison = compare(reference,candidate,window)
%IPM.OUTPUT.COMPARE Peak-aligned physical comparison of two IPM results.
%   WINDOW=[xMin,xMax,yMax] defaults to the common part of [-2,2]x[0,2].

reference = comparison_view(reference);
candidate = comparison_view(candidate);
required = {'comovingPhysicalX','physicalY','physicalRho','physicalOmega', ...
    'physicalTrackedPeakX','history'};
for k = 1:numel(required)
    if ~isfield(reference,required{k}) || ~isfield(candidate,required{k})
        error('ipm:ComparisonField', ...
            'Both results must contain the current physical reconstruction fields.');
    end
end
if nargin < 3 || isempty(window)
    window = [max([-2,min(reference.comovingPhysicalX), ...
        min(candidate.comovingPhysicalX)]), ...
        min([2,max(reference.comovingPhysicalX), ...
        max(candidate.comovingPhysicalX)]), ...
        min([2,max(reference.physicalY),max(candidate.physicalY)])];
end
validateattributes(window,{'numeric'},{'vector','numel',3,'finite'});
if window(2) <= window(1) || window(3) <= 0
    error('ipm:ComparisonWindow','The common comparison window is empty.');
end

[referenceX,referenceY] = meshgrid(reference.comovingPhysicalX, ...
    reference.physicalY);
candidateRho = interp2(candidate.comovingPhysicalX,candidate.physicalY, ...
    candidate.physicalRho,referenceX,referenceY,'linear',NaN);
candidateOmega = interp2(candidate.comovingPhysicalX,candidate.physicalY, ...
    candidate.physicalOmega,referenceX,referenceY,'linear',NaN);
mask = referenceX >= window(1) & referenceX <= window(2) & ...
    referenceY <= window(3) & isfinite(candidateRho) & ...
    isfinite(candidateOmega);
if nnz(mask) < 9
    error('ipm:ComparisonOverlap', ...
        'Too few common physical points lie in the comparison window.');
end

weights = line_weights(reference.physicalY) * ...
    line_weights(reference.comovingPhysicalX);
comparison = struct('window',window,'points',nnz(mask), ...
    'rhoRelativeL2',relative_l2(reference.physicalRho,candidateRho, ...
    weights,mask),'omegaRelativeL2',relative_l2(reference.physicalOmega, ...
    candidateOmega,weights,mask), ...
    'rhoAbsoluteInf',max(abs(reference.physicalRho(mask)-candidateRho(mask))), ...
    'omegaAbsoluteInf',max(abs(reference.physicalOmega(mask)-candidateOmega(mask))), ...
    'labPeakShift',candidate.physicalTrackedPeakX- ...
    reference.physicalTrackedPeakX, ...
    'wallPeakRelativeDifference',relative_difference( ...
    reference.history.physicalTrackedWallOmegaPeak(end), ...
    candidate.history.physicalTrackedWallOmegaPeak(end)), ...
    'wallWidthRelativeDifference',relative_difference( ...
    reference.history.physicalTrackedWallPeakWidth(end), ...
    candidate.history.physicalTrackedWallPeakWidth(end)));
end

function result = comparison_view(inputResult)
isSolverResult = ischar(inputResult) || ...
    (isstring(inputResult) && isscalar(inputResult)) || ...
    (isstruct(inputResult) && (isfield(inputResult,'schemaVersion') || ...
    all(isfield(inputResult,{'rho','opts','history','physicalTime'}))));
if isSolverResult
    canonical = ipm.output.validate(inputResult);
    result = struct( ...
        'comovingPhysicalX',canonical.grid.comovingPhysicalX, ...
        'physicalY',canonical.grid.physicalY, ...
        'physicalRho',canonical.physical.rho, ...
        'physicalOmega',canonical.physical.omega, ...
        'physicalTrackedPeakX',canonical.grid.physicalTrackedPeakX, ...
        'history',struct( ...
            'physicalTrackedWallOmegaPeak', ...
            canonical.history.common.physicalTrackedWallOmegaPeak, ...
            'physicalTrackedWallPeakWidth', ...
            canonical.history.common.physicalTrackedWallPeakWidth));
else
    result = inputResult;
end
end

function value = relative_l2(reference,candidate,weights,mask)
numerator = sum((reference(mask)-candidate(mask)).^2.*weights(mask),'all');
denominator = sum(reference(mask).^2.*weights(mask),'all');
value = sqrt(numerator/max(denominator,eps));
end

function value = relative_difference(reference,candidate)
value = (candidate-reference)/max(abs(reference),eps);
end

function weights = line_weights(coordinate)
wasRow = isrow(coordinate);
coordinate = coordinate(:);
weights = zeros(size(coordinate));
weights([1,end]) = [coordinate(2)-coordinate(1), ...
    coordinate(end)-coordinate(end-1)]/2;
weights(2:end-1) = (coordinate(3:end)-coordinate(1:end-2))/2;
if wasRow
    weights = weights';
end
end
