function wallCore = emptyWallCoreHistory()
%IPM.OUTPUT.EMPTYWALLCOREHISTORY Empty compact wall-profile record.

wallCore = struct( ...
    'historyIndex',zeros(0,1), ...
    'acceptedStep',zeros(0,1), ...
    'canonicalTime',zeros(0,1), ...
    'physicalTime',zeros(0,1), ...
    'trackedPeakX',zeros(0,1), ...
    'physicalTrackedPeakX',zeros(0,1), ...
    'physicalCoreHalfWidth',zeros(0,1), ...
    'physicalRhoXMaximum',zeros(0,1), ...
    'gridIndex',{{}}, ...
    'rescaledX',{{}}, ...
    'physicalX',{{}}, ...
    'comovingPhysicalX',{{}}, ...
    'physicalRho',{{}}, ...
    'physicalRhoX',{{}});
end
