function result = finalize(state,log,stopReason)
%IPM.OUTPUT.FINALIZE Build the compact, versioned solver result contract.

history = log.history;
if ~isfield(history,'common') || ...
        ~isfield(history.common,'t') || isempty(history.common.t)
    error('ipm:EmptyRunHistory', ...
        'Finalization requires at least one recorded solver state.');
end
common = history.common;
rawTrusted = ipm.output.trustedMask(history,state.config);
trusted = ipm.output.continuousTrustedPrefix(rawTrusted);
fit = ipm.diagnostics.blowupFit( ...
    common.physicalTime(trusted),common.physicalGradInf(trusted));
fit.trustedRecords = nnz(trusted);
fit.rawTrustedRecords = nnz(rawTrusted);
fit.continuousTrustedPrefix = true;
if any(trusted)
    fit.trustedThroughTime = ...
        common.physicalTime(find(trusted,1,'last'));
else
    fit.trustedThroughTime = NaN;
end
[fit.maximumGrowthRate,fit.canonicalMaximumGrowth] = ...
    maximum_growth_diagnostics(common,trusted);
rateOptions = struct('selectedRatePrescribed', ...
    selected_rate_prescribed(state.config));
fit.gaugeRateConvergence = ipm.diagnostics.gaugeRateConvergence( ...
    common.canonicalTau(trusted),common.c_l(trusted), ...
    common.c_omega(trusted),rateOptions);
fit.gaugeRateConvergence.observable = 'c_l_and_c_omega';
fit.gaugeRateConvergence.inputAvailable = any(trusted);
fit.gaugeRateConvergence.trustedRecords = nnz(trusted);
fit.gaugeRateConvergence.continuousTrustedPrefix = true;
fit.quadraticPeakTelemetry = quadratic_peak_telemetry( ...
    history,trusted,state.config);

physical = ipm.field.reconstructPhysical( ...
    state.rho,state.flow,state.scale,state.ops);
if state.ops.rescaling.enabled
    trackedPeakX = state.flow.trackedPeakX;
else
    trackedPeakX = common.wallPeakX(end);
end

result = struct();
result.schemaVersion = 2;
result.metadata = state.runMetadata;
result.state = struct( ...
    'rho',state.rho,'psi',state.flow.psi,'omega',state.flow.source, ...
    'velocity',struct('x',state.flow.u1,'y',state.flow.u2), ...
    'normalizedTime',state.normalizedTime, ...
    'canonicalTime',state.scale.canonicalTime, ...
    'physicalTime',state.scale.physicalTime, ...
    'steps',state.step,'stopReason',stopReason);
result.grid = struct( ...
    'x',state.ops.x,'y',state.ops.y, ...
    'physicalX',physical.x,'physicalY',physical.y, ...
    'comovingPhysicalX',(state.ops.x-trackedPeakX)/physical.Cx, ...
    'trackedPeakX',trackedPeakX, ...
    'physicalTrackedPeakX',(trackedPeakX-state.scale.X_shift)/physical.Cx, ...
    'remeshCount',state.ops.remeshCount);
result.scale = struct( ...
    'geometry',state.ops.dynamicScaleGeometry, ...
    'Cx',physical.Cx,'Cy',physical.Cy,'Comega',exp(state.scale.logC_omega), ...
    'Lx',physical.Lx,'Ly',physical.Ly,'aspect',physical.aspect, ...
    'Xshift',state.scale.X_shift, ...
    'rates',struct('cx',common.c_x(end),'cy',common.c_y(end), ...
        'comega',common.c_omega(end),'cr',common.c_r(end)), ...
    'canonicalRates',struct('cx',common.canonicalCX(end), ...
        'cy',common.canonicalCY(end), ...
        'comega',common.canonicalCOmega(end), ...
        'cr',common.canonicalCR(end)), ...
    'conservativeSource',common.conservativeSource(end), ...
    'canonicalConservativeSource', ...
        common.canonicalConservativeSource(end));
result.physical = rmfield(physical,{'Cx','Cy','Lx','Ly','aspect'});
result.history = history;
result.quality = ipm.diagnostics.finalQuality(history);
result.fit = fit;
result.config = state.config;
result.elliptic = struct('solveInfo',state.flow.poissonSolveInfo);
result.snapshots = struct( ...
    'rho',{log.snapshotRho}, ...
    'normalizedTime',log.snapshotNormalizedTime, ...
    'x',{log.snapshotX},'y',{log.snapshotY});
if state.config.output.storeSnapshots
    result.snapshots.physicalTime = common.physicalTime;
    result.snapshots.canonicalTime = common.canonicalTau;
else
    result.snapshots.physicalTime = [];
    result.snapshots.canonicalTime = [];
end
result = ipm.output.validate(result);
end

function [physicalFit,canonicalFit] = ...
        maximum_growth_diagnostics(common,trusted)
physicalTime = common.physicalTime(trusted);
canonicalTau = common.canonicalTau(trusted);
maximumValues = common.physicalRhoXInf(trusted);
inputAvailable = ~isempty(maximumValues) && ...
    all(isfinite(maximumValues)) && all(maximumValues > 0);
if inputAvailable
    physicalFit = ipm.diagnostics.maximumGrowthRateFit( ...
        physicalTime,maximumValues);
    canonicalFit = ipm.diagnostics.canonicalMaximumGrowthFit( ...
        canonicalTau,maximumValues);
else
    physicalFit = ipm.diagnostics.maximumGrowthRateFit([],[]);
    canonicalFit = ipm.diagnostics.canonicalMaximumGrowthFit([],[]);
end
physicalFit.observable = 'physicalRhoXInf';
physicalFit.inputAvailable = inputAvailable;
physicalFit.trustedRecords = numel(maximumValues);
canonicalFit.observable = 'physicalRhoXInf';
canonicalFit.inputAvailable = inputAvailable;
canonicalFit.trustedRecords = numel(maximumValues);
end

function prescribed = selected_rate_prescribed(config)
scaling = config.scaling;
prescribed = strcmp(scaling.rescalingMode,'physical') || ...
    strcmp(scaling.dynamicScaleGeometry,'anisotropic') || ...
    strcmp(scaling.cOmegaGauge,'none');
end

function telemetry = quadratic_peak_telemetry(history,trusted,config)
common = history.common;
names = {'physicalQuadraticPeak','inversePhysicalQuadraticPeak', ...
    'quadraticInverseSlopeAlgebraic','quadraticLocalTerminalTime', ...
    'rescaledRhoXInfToQuadraticPeak'};
count = nnz(trusted);
telemetry = struct( ...
    'schemaVersion',1, ...
    'observable','selected_wall_omega_quadratic_peak', ...
    'interpretation', ...
        'algebraic_identity_telemetry_only_no_empirical_blowup_claim', ...
    'empiricalClassificationPerformed',false, ...
    'selectedGauge',config.scaling.cOmegaGauge, ...
    'inputAvailable',false,'trustedRecords',count,'validRecords',0, ...
    'storedRecords',0,'reconstructedRecords',0, ...
    'source','unavailable', ...
    'storedReconstructionComparedValues',0, ...
    'maximumStoredReconstructionScaledError',0, ...
    'storedReconstructionConsistent',true, ...
    'physicalTime',common.physicalTime(trusted), ...
    'canonicalTau',common.canonicalTau(trusted));
reconstructed = reconstruct_quadratic_peak_telemetry( ...
    history,trusted,config);
valid = true(count,1);
storedRecord = true(count,1);
reconstructedRecord = false(count,1);
for index = 1:numel(names)
    name = names{index};
    if isfield(common,name)
        values = common.(name)(trusted);
        values = values(:);
    else
        values = NaN(count,1);
    end
    candidate = reconstructed.(name);
    compared = isfinite(values) & isfinite(candidate);
    if any(compared)
        scale = max([ones(nnz(compared),1),abs(values(compared)), ...
            abs(candidate(compared))],[],2);
        error = abs(values(compared)-candidate(compared))./scale;
        telemetry.storedReconstructionComparedValues = ...
            telemetry.storedReconstructionComparedValues+nnz(compared);
        telemetry.maximumStoredReconstructionScaledError = max( ...
            telemetry.maximumStoredReconstructionScaledError,max(error));
        telemetry.storedReconstructionConsistent = ...
            telemetry.storedReconstructionConsistent && ...
            all(abs(values(compared)-candidate(compared)) <= 100*eps(scale));
    end
    fill = ~isfinite(values) & isfinite(candidate);
    values(fill) = candidate(fill);
    reconstructedRecord = reconstructedRecord | fill;
    storedRecord = storedRecord & isfinite(telemetry_value( ...
        common,name,trusted,count));
    telemetry.(name) = values;
    valid = valid & isfinite(values);
end
telemetry.validRecords = nnz(valid);
telemetry.storedRecords = nnz(storedRecord);
telemetry.reconstructedRecords = nnz(reconstructedRecord);
telemetry.inputAvailable = strcmp(config.scaling.cOmegaGauge, ...
    'wall_omega_quadratic_peak') && count > 0 && all(valid) && ...
    telemetry.storedReconstructionConsistent;
if telemetry.inputAvailable && telemetry.reconstructedRecords == 0
    telemetry.source = 'stored_history';
elseif telemetry.inputAvailable && telemetry.storedRecords == 0
    telemetry.source = 'reconstructed_from_schema4_history';
elseif telemetry.inputAvailable
    telemetry.source = 'mixed_stored_and_reconstructed_history';
elseif strcmp(config.scaling.cOmegaGauge,'wall_omega_quadratic_peak')
    telemetry.source = 'partial_or_inconsistent_history';
end
end

function reconstructed = reconstruct_quadratic_peak_telemetry( ...
        history,trusted,config)
count = nnz(trusted);
empty = NaN(count,1);
reconstructed = struct( ...
    'physicalQuadraticPeak',empty, ...
    'inversePhysicalQuadraticPeak',empty, ...
    'quadraticInverseSlopeAlgebraic',empty, ...
    'quadraticLocalTerminalTime',empty, ...
    'rescaledRhoXInfToQuadraticPeak',empty);
if ~strcmp(config.scaling.cOmegaGauge,'wall_omega_quadratic_peak') || ...
        ~isfield(history,'gauge') || ...
        ~isfield(history.gauge,'omegaGaugeQuadraticPeakValue')
    return;
end
common = history.common;
peak = history.gauge.omegaGaugeQuadraticPeakValue(trusted);
peak = peak(:);
scaleLength = telemetry_value(common,'C_l',trusted,count);
scaleAmplitude = telemetry_value(common,'C_omega',trusted,count);
cL = preferred_rate(common,'canonicalCL','c_l',trusted,count);
cOmega = preferred_rate(common,'canonicalCOmega','c_omega',trusted,count);
physicalTime = telemetry_value(common,'physicalTime',trusted,count);
rescaledMaximum = telemetry_value(common,'rhoXInf',trusted,count);
kappa = cL-cOmega;
baseValid = isfinite(peak) & peak > 0 & ...
    isfinite(scaleLength) & scaleLength > 0 & ...
    isfinite(scaleAmplitude) & scaleAmplitude > 0 & ...
    isfinite(rescaledMaximum) & rescaledMaximum > 0;
physicalPeak = empty;
physicalPeak(baseValid) = scaleLength(baseValid) ./ ...
    scaleAmplitude(baseValid).*peak(baseValid);
baseValid = baseValid & isfinite(physicalPeak) & physicalPeak > 0;
reconstructed.physicalQuadraticPeak(baseValid) = ...
    physicalPeak(baseValid);
reconstructed.inversePhysicalQuadraticPeak(baseValid) = ...
    1./physicalPeak(baseValid);
reconstructed.rescaledRhoXInfToQuadraticPeak(baseValid) = ...
    rescaledMaximum(baseValid)./peak(baseValid);
rateValid = baseValid & isfinite(kappa);
reconstructed.quadraticInverseSlopeAlgebraic(rateValid) = ...
    -kappa(rateValid)./peak(rateValid);
terminalValid = rateValid & kappa > 0 & isfinite(physicalTime);
reconstructed.quadraticLocalTerminalTime(terminalValid) = ...
    physicalTime(terminalValid) + peak(terminalValid) ./ ...
    (kappa(terminalValid).*physicalPeak(terminalValid));
end

function values = preferred_rate(common,preferred,fallback,trusted,count)
values = telemetry_value(common,preferred,trusted,count);
missing = ~isfinite(values);
if any(missing)
    fallbackValues = telemetry_value(common,fallback,trusted,count);
    values(missing) = fallbackValues(missing);
end
end

function values = telemetry_value(common,name,trusted,count)
if isfield(common,name)
    values = common.(name)(trusted);
    values = values(:);
else
    values = NaN(count,1);
end
end
