function log = initializeLog()
%IPM.OUTPUT.INITIALIZELOG Empty grouped history and optional snapshot storage.

log = struct( ...
    'history',struct('common',struct(),'gauge',struct(), ...
        'mesh',struct(),'anisotropic',struct()), ...
    'snapshotRho',{{}},'snapshotNormalizedTime',[], ...
    'snapshotX',{{}},'snapshotY',{{}});
end
