function checkpoint = makeCheckpoint(state,log,cursor)
%IPM.OUTPUT.MAKECHECKPOINT Pack one trusted schema-4 solver transaction.

if ~ipm.evolve.isFinite(state)
    error('ipm:CheckpointFinite', ...
        'Only a complete finite solver state may be checkpointed.');
end
ops = state.ops;
statePayload = struct( ...
    'config',state.config,'runMetadata',state.runMetadata, ...
    'rho',state.rho,'x',ops.x,'y',ops.y, ...
    'baseX',ops.baseX,'baseY',ops.baseY, ...
    'rescaling',ops.rescaling,'remeshCount',ops.remeshCount, ...
    'scale',state.scale,'normalizedTime',state.normalizedTime, ...
    'step',state.step,'mass0',state.mass0,'rhoRange0',state.rhoRange0);
payload = struct('state',statePayload,'log',log,'cursor',cursor);
checkpoint = struct( ...
    'schemaVersion',4, ...
    'kind','ipm_accepted_step_checkpoint', ...
    'createdUtc',char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z''')), ...
    'acceptedStep',true,'trustedRecord',true, ...
    'payload',payload, ...
    'signature',ipm.output.checkpointSignature(payload));
checkpoint = ipm.output.readCheckpoint(checkpoint);
end
