function [log,d] = record(log,state)
%IPM.OUTPUT.RECORD Append one state to the version-2 grouped run history.

rho = state.rho;
flow = state.flow;
scale = state.scale;
ops = state.ops;
scaling = state.config.scaling;
output = state.config.output;
d = ipm.diagnostics.measure(rho,flow,ops,state.mass0);

isAnisotropic = strcmp(ops.dynamicScaleGeometry,'anisotropic');
Cx = exp(scale.logC_l);
if isAnisotropic
    Cy = exp(scale.logC_y);
else
    Cy = Cx;
end
Comega = exp(scale.logC_omega);
amplitudeInverse = 1/Comega;

common = struct( ...
    'acceptedStep',state.step, ...
    't',state.normalizedTime, ...
    'canonicalTau',scale.canonicalTime, ...
    'physicalTime',scale.physicalTime, ...
    'C_l',Cx,'C_x',Cx,'C_y',Cy,'L_x',1/Cx,'L_y',1/Cy, ...
    'aspect',Cy/Cx,'C_omega',Comega,'X_shift',scale.X_shift, ...
    'c_l',flow.c_l,'c_x',flow.c_l,'c_y',flow.c_l, ...
    'c_omega',flow.c_omega,'c_r',flow.c_r, ...
    'canonicalCL',flow.canonicalCL, ...
    'canonicalCX',flow.canonicalCL,'canonicalCY',flow.canonicalCL, ...
    'canonicalCOmega',flow.canonicalCOmega, ...
    'canonicalCR',flow.canonicalCR, ...
    'timeSpeed',flow.timeSpeed, ...
    'canonicalRateMagnitude',flow.canonicalRateMagnitude, ...
    'aspectRate',0,'canonicalAspectRate',0, ...
    'conservativeSource',2*flow.c_l+flow.c_omega, ...
    'canonicalConservativeSource', ...
        2*flow.canonicalCL+flow.canonicalCOmega, ...
    'physicalRhoInf',amplitudeInverse*max(abs(rho),[],'all'), ...
    'physicalRhoMin',amplitudeInverse*d.rhoMin, ...
    'physicalRhoMax',amplitudeInverse*d.rhoMax, ...
    'physicalOmegaInf',Cx*amplitudeInverse*d.omegaInf, ...
    'physicalRhoXInf',Cx*amplitudeInverse*d.rhoXInf, ...
    'physicalRhoYInf',Cy*amplitudeInverse*d.rhoYInf, ...
    'physicalWallDensityMax',amplitudeInverse*d.wallDensityMax, ...
    'physicalWallOmegaPeak',Cx*amplitudeInverse*d.wallPeak, ...
    'physicalWallPeak',Cx*amplitudeInverse*d.wallPeak, ...
    'physicalWallPeakWidth',d.wallPeakWidth/Cx);
common = merge_scalars(common,quadratic_peak_telemetry( ...
    scaling,flow,scale,d,Cx/Comega));
if isfield(state.config.remesh,'autonomousMesh') && ...
        state.config.remesh.autonomousMesh.enabled && any(state.config.remesh.autonomousMesh.version == [2,3,4,5])
    common.nodeCountX=ops.nx;
    common.nodeCountY=ops.ny;
    common.meshLevelId=state.runMetadata.autonomousMesh.currentLevelId;
end

% Keep the evolving physical coverage explicit.  A computational endpoint
% of 1e6 is not a terminal physical endpoint once C_l has changed.
common.physicalDomainXMinimum = (ops.x(1)-scale.X_shift)/Cx;
common.physicalDomainXMaximum = (ops.x(end)-scale.X_shift)/Cx;
common.physicalDomainXRadius = max(abs([ ...
    common.physicalDomainXMinimum,common.physicalDomainXMaximum]));
common.physicalDomainYMaximum = ops.y(end)/Cy;
common.physicalMinimumDx = min(ops.dxFaces)/Cx;
common.physicalMinimumDy = min(ops.dyFaces)/Cy;

if isfield(state,'timeStep') && isstruct(state.timeStep) && ...
        isscalar(state.timeStep)
    timeStep = state.timeStep;
else
    timeStep = ipm.evolve.emptyTimestep( ...
        state.config.time,scale,'unavailable');
end
common.acceptedCanonicalDt = timeStep.dt;
common.transportRate = timeStep.rate;
common.cflDtLimit = timeStep.dtCfl;
common.maximumDtLimit = timeStep.maxDtLimit;
common.canonicalEndpointDtLimit = timeStep.canonicalLimit;
common.physicalEndpointDtLimit = timeStep.physicalLimit;
common.physicalClockSpeed = timeStep.physicalClockSpeed;
common.realizedCfl = timeStep.realizedCfl;
common.timestepActiveLimiter = string(timeStep.activeLimiter);
common.amplitudeSourceStep = timeStep.dt*abs(flow.c_omega);
common.conservativeSourceStep = timeStep.dt* ...
    abs(2*flow.c_l+flow.c_omega);

common.physicalRangeViolation = max([state.rhoRange0(1)- ...
    common.physicalRhoMin,common.physicalRhoMax-state.rhoRange0(2),0]);
if isAnisotropic
    common.c_x = flow.c_x;
    common.c_y = flow.c_y;
    common.canonicalCX = flow.canonicalCX;
    common.canonicalCY = flow.canonicalCY;
    common.aspectRate = flow.aspectRate;
    common.canonicalAspectRate = flow.canonicalAspectRate;
    common.conservativeSource = flow.conservativeSource;
    common.canonicalConservativeSource = ...
        flow.canonicalConservativeSource;
end

if isAnisotropic
    common.physicalGradientEnergyX = amplitudeInverse^2 * ...
        (Cx/Cy)*d.gradientEnergyX;
    common.physicalGradientEnergyY = amplitudeInverse^2 * ...
        (Cy/Cx)*d.gradientEnergyY;
    common.physicalGradientEffectiveLength = ...
        anisotropic_gradient_effective_length( ...
            rho,ops,Cx,Cy,amplitudeInverse);
    common.physicalMass = amplitudeInverse*d.mass/(Cx*Cy);
else
    common.physicalGradientEnergyX = ...
        amplitudeInverse^2*d.gradientEnergyX;
    common.physicalGradientEnergyY = ...
        amplitudeInverse^2*d.gradientEnergyY;
    common.physicalGradientEffectiveLength = ...
        d.gradientEffectiveLength/Cx;
    common.physicalMass = amplitudeInverse*d.mass/Cx^2;
end
common.physicalGradientEnergy = common.physicalGradientEnergyX + ...
    common.physicalGradientEnergyY;
common.physicalGradInf = ...
    ipm.diagnostics.physicalGradientInf(d,scale,rho,ops);
common.physicalMassDrift = ...
    (common.physicalMass-state.mass0)/max(abs(state.mass0),eps);

if ops.rescaling.enabled
    common.physicalPinX = (ops.rescaling.pinX-scale.X_shift)/Cx;
    common.physicalTrackedPeakX = (flow.trackedPeakX-scale.X_shift)/Cx;
    common.physicalTrackedWallOmegaPeak = ...
        Cx*amplitudeInverse*flow.trackedWallPeak;
    common.physicalTrackedWallPeakWidth = ...
        flow.trackedWallPeakWidth/Cx;
else
    common.physicalTrackedPeakX = d.wallPeakX;
    common.physicalTrackedWallOmegaPeak = common.physicalWallOmegaPeak;
    common.physicalTrackedWallPeakWidth = common.physicalWallPeakWidth;
end

diagnostics = d;
if ~strcmp(ops.symmetryMode,'double_odd_omega')
    diagnostics = rmfield(diagnostics,{'rhoEvenDefect','omegaOddDefect'});
end
if ~ops.rescaling.enabled
    diagnostics = rmfield(diagnostics,{'pinDensity','pinOmega','pinOffset'});
end
common = merge_scalars(common,diagnostics);
log.history.common = append_scalars(log.history.common,common);

mesh = struct('remeshCount',ops.remeshCount, ...
    'minimumDx',min(ops.dxFaces),'minimumDy',min(ops.dyFaces), ...
    'maximumCellRatioX',maximum_cell_ratio(ops.dxFaces), ...
    'maximumCellRatioY',maximum_cell_ratio(ops.dyFaces), ...
    'globalGridRatioX',max(ops.dxFaces)/min(ops.dxFaces), ...
    'globalGridRatioY',max(ops.dyFaces)/min(ops.dyFaces));
[~,originIndex] = min(abs(ops.x));
if originIndex < ops.nx
    mesh.originDx = ops.x(originIndex+1)-ops.x(originIndex);
end
if isfinite(flow.omegaGaugePeakX)
    [~,peakIndex] = min(abs(ops.x-flow.omegaGaugePeakX));
    peakLeft = max(peakIndex-1,1);
    peakRight = min(peakIndex+1,ops.nx);
    mesh.peakDx = (ops.x(peakRight)-ops.x(peakLeft)) / ...
        max(peakRight-peakLeft,1);
end
meshNames = {'peakGridPoints','supportGridPoints','coreGridPoints', ...
    'verticalPeakGridPoints','verticalSupportGridPoints', ...
    'verticalCoreGridPoints','targetPeakGridPoints', ...
    'targetSupportGridPoints','targetCoreGridPoints', ...
    'peakExpansionRatio','resolutionFactor','safetyFactor', ...
    'trackedWallPeak','trackedWallPeakWidth','trackedWallCoreWidth', ...
    'trackedVerticalPeakWidth','trackedVerticalCoreWidth'};
mesh = copy_finite_fields(mesh,flow,meshNames);
log.history.mesh = append_scalars(log.history.mesh,mesh);

if ops.rescaling.enabled && ~isAnisotropic
    gaugeNames = {'c_lNominal','canonicalCLNominal','lengthScaleGain', ...
        'widthCorrection','canonicalWidthCorrection','widthRateScale', ...
        'widthControlMode','pinGaugeResidual','pinTransportVelocity', ...
        'lengthGaugeStrain','lengthGaugeResidual','trackedPeakX', ...
        'trackedPeakOffset','peakTransportVelocity', ...
        'travelingWaveResidual'};
    if strcmp(scaling.lengthGauge,'transport_anchor')
        gaugeNames = [gaugeNames,{'transportAnchorX', ...
            'canonicalTransportAnchorVelocity','transportAnchorVelocity'}];
    end
    if strcmp(scaling.lengthGauge,'omega_peak_location')
        gaugeNames = [gaugeNames,{ ...
            'peakLocationRhoXX','peakLocationRhoXXScale', ...
            'peakLocationPhaseDefect', ...
            'peakLocationResponseCondition', ...
            'peakLocationFullPhaseResidual', ...
            'peakLocationNormalizedFullPhaseResidual'}];
    elseif strcmp(scaling.lengthGauge,'wall_density_width')
        gaugeNames = [gaugeNames,{ ...
            'wallDensityLowerSlope','wallDensityUpperSlope', ...
            'wallDensityLowerCondition','wallDensityUpperCondition', ...
            'wallDensityLowerBracket','wallDensityUpperBracket'}];
    end
    if strcmp(scaling.lengthGauge,'local_strain') || ...
            strcmp(scaling.cOmegaGauge,'strain_point')
        gaugeNames = [gaugeNames, ...
            {'strain','strainError','strainCondition'}];
    end
    switch scaling.cOmegaGauge
        case 'wall_omega_peak'
            gaugeNames = [gaugeNames,{'omegaGaugeEnergy', ...
                'omegaGaugeResidual','omegaPeakRateResidual', ...
                'omegaGaugePeakX','omegaGaugePeakCondition'}];
        case 'wall_omega_quadratic_peak'
            gaugeNames = [gaugeNames,{'omegaGaugeEnergy', ...
                'omegaGaugeResidual','omegaPeakRateResidual', ...
                'omegaGaugePeakX','omegaGaugePeakCondition', ...
                'omegaGaugeQuadraticPeakX', ...
                'omegaGaugeQuadraticPeakValue', ...
                'omegaGaugeQuadraticForcing', ...
                'omegaGaugeQuadraticCurvature', ...
                'omegaGaugeQuadraticStationarityResidual', ...
                'omegaGaugeQuadraticNormalizedStationarityResidual', ...
                'omegaGaugeQuadraticCurvatureCondition', ...
                'omegaGaugeQuadraticWeightCondition', ...
                'omegaGaugeQuadraticActiveNodeMargin', ...
                'omegaGaugeQuadraticActiveSelectionMargin', ...
                'omegaGaugeQuadraticStencilCenterX', ...
                'omegaGaugeQuadraticVertexInteriorFraction', ...
                'omegaGaugeQuadraticRelativeSubgridLift', ...
                'omegaGaugeQuadraticRateResidual', ...
                'omegaGaugeQuadraticRateScale'}];
        case 'none'
            % The selected zero rate is prescribed.  These quadratic
            % fields are an independent counterfactual peak diagnostic,
            % not a hidden amplitude feedback.
            gaugeNames = [gaugeNames,{'omegaGaugeEnergy', ...
                'omegaGaugeResidual','omegaPeakRateResidual', ...
                'omegaGaugePeakX','omegaGaugePeakCondition', ...
                'omegaGaugeQuadraticPeakX', ...
                'omegaGaugeQuadraticPeakValue', ...
                'omegaGaugeQuadraticForcing', ...
                'omegaGaugeQuadraticCurvature', ...
                'omegaGaugeQuadraticStationarityResidual', ...
                'omegaGaugeQuadraticNormalizedStationarityResidual', ...
                'omegaGaugeQuadraticCurvatureCondition', ...
                'omegaGaugeQuadraticWeightCondition', ...
                'omegaGaugeQuadraticActiveNodeMargin', ...
                'omegaGaugeQuadraticActiveSelectionMargin', ...
                'omegaGaugeQuadraticStencilCenterX', ...
                'omegaGaugeQuadraticVertexInteriorFraction', ...
                'omegaGaugeQuadraticRelativeSubgridLift', ...
                'omegaGaugeQuadraticRateResidual', ...
                'omegaGaugeQuadraticRateScale'}];
        case 'gradient_energy'
            gaugeNames = [gaugeNames, ...
                {'omegaGaugeEnergy','omegaGaugeEnergyX', ...
                'omegaGaugeEnergyY','omegaGaugeForcingX', ...
                'omegaGaugeForcingY','omegaGaugeForcing', ...
                'omegaGaugeAbsoluteForcing', ...
                'omegaGaugeForcingCancellationRatio', ...
                'omegaGaugeResidual'}];
        case 'strain_point'
            gaugeNames = [gaugeNames,{'strainRateResidual', ...
                'omegaGaugeEnergy','omegaGaugeResidual'}];
        case {'anchor_wall_slope','anchor_wall_strain'}
            gaugeNames = [gaugeNames,{'omegaGaugeEnergy', ...
                'omegaGaugeResidual','omegaGaugeAnchorX', ...
                'omegaGaugeAnchorValue','omegaGaugeAnchorCondition', ...
                'omegaGaugeAnchorRateResidual', ...
                'omegaGaugeReferenceAnchorValue'}];
        case {'anchor_wall_window_l2','anchor_wall_window_l4', ...
                'outer_wall_density_window_l2'}
            gaugeNames = [gaugeNames,{'omegaGaugeEnergy', ...
                'omegaGaugeResidual','omegaGaugeWindowCenter', ...
                'omegaGaugeWindowRadius','omegaGaugeWindowValue', ...
                'omegaGaugeWindowCondition','omegaGaugeWindowEnergy', ...
                'omegaGaugeWindowRateResidual', ...
                'omegaGaugeReferenceWindowValue', ...
                'omegaGaugeWindowMomentOrder','omegaGaugeWindowMoment', ...
                'omegaGaugeWindowSupportPoints', ...
                'omegaGaugeWindowRateScale'}];
        case 'anchor_wall_template_projection'
            gaugeNames = [gaugeNames,{'omegaGaugeEnergy', ...
                'omegaGaugeResidual','omegaGaugeTemplateCenter', ...
                'omegaGaugeTemplateRadius', ...
                'omegaGaugeTemplateSupportPoints', ...
                'omegaGaugeTemplateValue','omegaGaugeTemplateCondition', ...
                'omegaGaugeTemplateRateResidual', ...
                'omegaGaugeTemplateRateScale', ...
                'omegaGaugeReferenceTemplateValue'}];
        case 'anchor_bulk_gradient_l2'
            gaugeNames = [gaugeNames,{'omegaGaugeEnergy', ...
                'omegaGaugeResidual','omegaGaugeBulkCenterX', ...
                'omegaGaugeBulkCenterY','omegaGaugeBulkRadius', ...
                'omegaGaugeBulkSupportPointsX', ...
                'omegaGaugeBulkSupportPointsY','omegaGaugeBulkValue', ...
                'omegaGaugeBulkCondition','omegaGaugeBulkEnergy', ...
                'omegaGaugeBulkRateResidual','omegaGaugeBulkRateScale', ...
                'omegaGaugeReferenceBulkValue'}];
    end
    gauge = copy_finite_fields( ...
        struct(),flow,unique(gaugeNames,'stable'));
    gauge.cOmegaOverCL = guarded_rate_ratio(flow.c_omega,flow.c_l);
    gauge.cLMinusCOmegaOverCL = guarded_rate_ratio( ...
        flow.c_l-flow.c_omega,flow.c_l);
    log.history.gauge = append_scalars(log.history.gauge,gauge);
end

if isAnisotropic
    anisotropic = struct( ...
        'anisotropicGaugeMode',string(flow.anisotropicGaugeMode));
    anisotropicNames = {'peakTranslationResidual', ...
        'peakTranslationRawVelocity'};
    if strcmp(flow.anisotropicGaugeMode,'peak_translation')
        anisotropicNames = [anisotropicNames, ...
            {'peakTranslationTargetVelocity', ...
            'canonicalPeakTranslationTargetVelocity'}];
    end
    anisotropic = copy_finite_fields(anisotropic,flow,anisotropicNames);
    log.history.anisotropic = append_scalars( ...
        log.history.anisotropic,anisotropic);
end

if output.storeSnapshots
    log.snapshotRho{end+1} = rho;
    log.snapshotNormalizedTime(end+1,1) = state.normalizedTime;
    log.snapshotX{end+1} = ops.x;
    log.snapshotY{end+1} = ops.y;
end

if output.verbose
    fprintf(['tau=%9.5f  normalized=%9.5f  physical grad=%10.3e  ' ...
        '|u|=%9.3e  physical mass drift=%9.2e  c_l=%9.2e  c_w=%9.2e\n'], ...
        scale.canonicalTime,state.normalizedTime, ...
        common.physicalGradInf,d.uInf,common.physicalMassDrift, ...
        flow.c_l,flow.c_omega);
end
end

function target = append_scalars(target,values)
existingNames = fieldnames(target);
valueNames = fieldnames(values);
names = [existingNames;setdiff(valueNames,existingNames,'stable')];
count = 0;
for index = 1:numel(existingNames)
    count = max(count,numel(target.(existingNames{index})));
end
for index = 1:numel(names)
    name = names{index};
    if isfield(target,name)
        series = target.(name)(:);
        if numel(series) < count
            padded = missing_series(series,count);
            padded(1:numel(series)) = series;
            series = padded;
        end
    else
        series = missing_series(values.(name),count);
    end
    if isfield(values,name)
        value = values.(name);
        if ~isscalar(value)
            error('ipm:HistoryScalar', ...
                'History field "%s" must be scalar at each record.',name);
        end
    else
        value = missing_value(series);
    end
    nextSeries = missing_series(series,count+1);
    if count > 0
        nextSeries(1:count) = series;
    end
    nextSeries(end) = value;
    target.(name) = nextSeries;
end
end

function series = missing_series(template,count)
if isstring(template)
    series = strings(count,1);
elseif islogical(template)
    series = false(count,1);
elseif isfloat(template)
    series = NaN(count,1,'like',template);
else
    series = zeros(count,1,'like',template);
end
end

function value = missing_value(series)
if isstring(series)
    value = "";
elseif islogical(series)
    value = false;
elseif isfloat(series)
    value = cast(NaN,'like',series);
else
    value = cast(0,'like',series);
end
end

function target = merge_scalars(target,source)
names = fieldnames(source);
for index = 1:numel(names)
    target.(names{index}) = source.(names{index});
end
end

function target = copy_finite_fields(target,source,names)
for index = 1:numel(names)
    name = names{index};
    if isfield(source,name) && isscalar(source.(name)) && ...
            isnumeric(source.(name)) && isfinite(source.(name))
        target.(name) = source.(name);
    end
end
end

function value = anisotropic_gradient_effective_length( ...
        rho,ops,Cx,Cy,amplitudeInverse)
rhoX = rho*ops.Dx';
rhoY = ops.Dy*rho;
physicalSquared = amplitudeInverse^2 * ...
    (Cx^2*rhoX.^2+Cy^2*rhoY.^2);
weights = ops.integrationWeights;
energy = sum(physicalSquared.*weights,'all')/(Cx*Cy);
fourthMoment = sum(physicalSquared.^2.*weights,'all')/(Cx*Cy);
value = energy/sqrt(max(fourthMoment,eps));
end

function ratio = maximum_cell_ratio(faces)
if numel(faces) < 2
    ratio = 1;
else
    ratio = max(max(faces(2:end)./faces(1:end-1), ...
        faces(1:end-1)./faces(2:end)));
end
end

function value = guarded_rate_ratio(numerator,denominator)
scale = max([1,abs(numerator),abs(denominator)]);
if abs(denominator) <= 100*eps(scale)
    value = NaN;
else
    value = numerator/denominator;
end
end

function telemetry = quadratic_peak_telemetry( ...
        scaling,flow,scale,d,scaleRatio)
% Algebraic read-only telemetry for the selected quadratic-peak gauge.
telemetry = struct( ...
    'physicalQuadraticPeak',NaN, ...
    'inversePhysicalQuadraticPeak',NaN, ...
    'quadraticInverseSlopeAlgebraic',NaN, ...
    'quadraticLocalTerminalTime',NaN, ...
    'rescaledRhoXInfToQuadraticPeak',NaN);
if ~strcmp(scaling.cOmegaGauge,'wall_omega_quadratic_peak') || ...
        ~isfield(flow,'omegaGaugeQuadraticPeakValue')
    return;
end
peak = flow.omegaGaugeQuadraticPeakValue;
rescaledMaximum = d.rhoXInf;
if ~all(isfinite([peak,rescaledMaximum,scaleRatio])) || ...
        peak <= 0 || rescaledMaximum <= 0 || scaleRatio <= 0
    return;
end
physicalPeak = scaleRatio*peak;
if ~isfinite(physicalPeak) || physicalPeak <= 0
    return;
end
telemetry.physicalQuadraticPeak = physicalPeak;
telemetry.inversePhysicalQuadraticPeak = 1/physicalPeak;
telemetry.rescaledRhoXInfToQuadraticPeak = rescaledMaximum/peak;
kappa = flow.canonicalCL-flow.canonicalCOmega;
if ~isfinite(kappa)
    return;
end
telemetry.quadraticInverseSlopeAlgebraic = -kappa/peak;
if kappa > 0
    terminalTime = scale.physicalTime + peak/(kappa*physicalPeak);
    if isfinite(terminalTime)
        telemetry.quadraticLocalTerminalTime = terminalTime;
    end
end
end
