function report(result)
%IPM.OUTPUT.REPORT Print a compact terminal summary for verbose runs.

result = ipm.output.validate(result);
output = result.config.output;
if ~output.verbose
    return;
end
state = result.state;
scale = result.scale;
common = result.history.common;
mesh = result.history.mesh;
scaling = result.config.scaling;
diagnostics = result.config.diagnostics;
fprintf(['IPM stopped at canonical tau=%.8g (normalized tau=%.8g) ' ...
    'after %d steps (%s).\n'],state.canonicalTime,state.normalizedTime, ...
    state.steps,state.stopReason);
fprintf(['  geometry=%s, mode=%s, physical t=%.8g, ' ...
    'c_x/c_y/c_omega/c_r=%.4e/%.4e/%.4e/%.4e\n'], ...
    scale.geometry,scaling.rescalingMode,state.physicalTime, ...
    scale.rates.cx,scale.rates.cy,scale.rates.comega,scale.rates.cr);
fprintf(['  physical ||grad rho||_inf=%.6e, physical/rescaled mass ' ...
    'drift=%.3e/%.3e, div(u)=%.3e\n'],common.physicalGradInf(end), ...
    common.physicalMassDrift(end),common.massDrift(end),common.divInf(end));
fprintf('  physical density range=[%.6e,%.6e], violation=%.3e\n', ...
    common.physicalRhoMin(end),common.physicalRhoMax(end), ...
    common.physicalRangeViolation(end));
fprintf('  wall max: physical rho_x=%.6e, rescaled R_X=%.6e\n', ...
    common.physicalWallOmegaPeak(end),common.wallPeak(end));

gauge = result.history.gauge;
if isfield(gauge,'omegaGaugeResidual')
    fprintf('  gauge=%s/%s, omega residual=%.3e, safety=%.3e\n', ...
        scaling.lengthGauge,scaling.cOmegaGauge, ...
        gauge.omegaGaugeResidual(end),mesh.safetyFactor(end));
end
if common.farBoundaryVelocityRatio(end) > diagnostics.farBoundaryTolerance
    fprintf(['  WARNING: far-boundary velocity ratio %.3e exceeds %.3e; ' ...
        'repeat on a larger box at fixed center spacing.\n'], ...
        common.farBoundaryVelocityRatio(end),diagnostics.farBoundaryTolerance);
end
if common.farBoundarySourceRatio(end) > diagnostics.farBoundaryTolerance
    fprintf(['  WARNING: far-boundary omega ratio %.3e exceeds %.3e; ' ...
        'repeat on a larger box.\n'],common.farBoundarySourceRatio(end), ...
        diagnostics.farBoundaryTolerance);
end
if result.fit.candidate
    fprintf(['  Candidate physical-time fit: ||grad rho|| ~ ' ...
        '(T-t)^(-p), T=%.6g, p=%.4g, R^2=%.5f\n'], ...
        result.fit.T,result.fit.p,result.fit.r2Power);
else
    fprintf('  No power-law blow-up candidate beats exponential growth.\n');
end
end
