function validateWallCoreHistory(wallCore,common)
%IPM.OUTPUT.VALIDATEWALLCOREHISTORY Validate compact wall records.

required = {'historyIndex','acceptedStep','canonicalTime','physicalTime', ...
    'trackedPeakX','physicalTrackedPeakX','physicalCoreHalfWidth', ...
    'physicalRhoXMaximum','gridIndex','rescaledX','physicalX', ...
    'comovingPhysicalX','physicalRho','physicalRhoX'};
if ~isstruct(wallCore) || ~isscalar(wallCore) || ...
        ~all(isfield(wallCore,required))
    error('ipm:WallCoreHistory','The wall-core history is incomplete.');
end

count = numel(wallCore.historyIndex);
numericNames = required(1:8);
cellNames = required(9:end);
for index = 1:numel(numericNames)
    values = wallCore.(numericNames{index});
    if ~isnumeric(values) || ~isreal(values) || ...
            (count > 0 && ~iscolumn(values)) || numel(values) ~= count || ...
            any(~isfinite(values))
        error('ipm:WallCoreHistory', ...
            'Wall-core field %s is invalid.',numericNames{index});
    end
end
for index = 1:numel(cellNames)
    values = wallCore.(cellNames{index});
    if ~iscell(values) || (count > 0 && ~iscolumn(values)) || ...
            numel(values) ~= count
        error('ipm:WallCoreHistory', ...
            'Wall-core field %s is invalid.',cellNames{index});
    end
end
if count == 0
    return;
end

historyIndex = wallCore.historyIndex;
historyCount = numel(common.canonicalTau);
if any(historyIndex < 1 | historyIndex > historyCount | ...
        mod(historyIndex,1) ~= 0) || any(diff(historyIndex) <= 0) || ...
        ~isequal(wallCore.acceptedStep,common.acceptedStep(historyIndex)) || ...
        ~isequal(wallCore.canonicalTime,common.canonicalTau(historyIndex)) || ...
        ~isequal(wallCore.physicalTime,common.physicalTime(historyIndex)) || ...
        ~isequal(wallCore.physicalRhoXMaximum, ...
            common.physicalRhoXInf(historyIndex))
    error('ipm:WallCoreHistory', ...
        'Wall-core rows are not aligned with the scalar history.');
end

for row = 1:count
    n = numel(wallCore.gridIndex{row});
    if n < 1 || n > 129
        error('ipm:WallCoreHistory', ...
            'Wall-core row %d has an invalid node count.',row);
    end
    for index = 1:numel(cellNames)
        values = wallCore.(cellNames{index}){row};
        if ~isnumeric(values) || ~isreal(values) || ~isrow(values) || ...
                numel(values) ~= n || any(~isfinite(values))
            error('ipm:WallCoreHistory', ...
                'Wall-core row %d field %s is invalid.', ...
                row,cellNames{index});
        end
    end
    gridIndex = wallCore.gridIndex{row};
    if any(mod(gridIndex,1) ~= 0) || any(diff(gridIndex) ~= 1) || ...
            any(diff(wallCore.rescaledX{row}) <= 0) || ...
            any(diff(wallCore.physicalX{row}) <= 0) || ...
            any(diff(wallCore.comovingPhysicalX{row}) <= 0)
        error('ipm:WallCoreHistory', ...
            'Wall-core row %d coordinates are invalid.',row);
    end
end
end
