% Local long-time n=256 quadrant run from the current Git-managed source.
% sourceRoot is deliberately absolute. mfilename only locates this job's output.
mainPath=mfilename('fullpath');
jobRoot=fileparts(mainPath);
sourceRoot=['/Users/bjchen/Library/CloudStorage/OneDrive-北京大学/' ...
    'Research/IPM/ipm_grid_v6'];
assert(isfolder(fullfile(sourceRoot,'+ipm')), ...
    'ipm:QuadrantLongSource','Cannot find current IPM source at %s.',sourceRoot);

restoredefaultpath;
addpath(sourceRoot);
n=256;
settings=struct( ...
    'resolutionLevel',n, ...
    'initialNodeCount',[2*n+1,n+1], ...
    'boxHalfWidth',8,'boxHeight',4, ...
    'canonicalFinalTime',1000,'maximumSteps',Inf, ...
    'maximumTimeStep',.004,'minimumTimeStep',1e-12, ...
    'snapshotEvery',.5,'checkpointEvery',25, ...
    'maximumAdjacentGridRatio',2);
outputDirectory=fullfile(jobRoot,'output');

opts=struct( ...
    'quadrantOnly',true, ...
    'nx',settings.initialNodeCount(1),'ny',settings.initialNodeCount(2), ...
    'xlim',[0,settings.boxHalfWidth],'ymax',settings.boxHeight, ...
    'gridMode','uniform','gridStretchAutomatic',false,'gridStretch',[0,0], ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'rescalingMode','dynamic','dynamicScaleGeometry','isotropic', ...
    'symmetryMode','double_odd_omega', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',.5, ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'wallTransportMode','conservative_flux', ...
    'transportBoundaryMode','open', ...
    'adaptiveRemesh',true,'initialAnalyticRemesh',true, ...
    'initialAnalyticRemeshPasses',1, ...
    'finalTime',settings.canonicalFinalTime,'physicalFinalTime',Inf, ...
    'maxSteps',settings.maximumSteps, ...
    'maxDt',settings.maximumTimeStep,'minDt',settings.minimumTimeStep, ...
    'outputEvery',settings.snapshotEvery, ...
    'remeshMaximumCellRatio',settings.maximumAdjacentGridRatio, ...
    'storeSnapshots',true,'saveResults',true, ...
    'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',true, ...
    'checkpoint',struct('enabled',true, ...
        'file',fullfile(outputDirectory,'checkpoint.mat'), ...
        'every',settings.checkpointEvery,'atExit',true), ...
    'caseMetadata',struct( ...
        'kind','quadrant_level_set_n256_long_unbounded_steps_v1', ...
        'resolutionLevel',n,'actualStoredGrid',settings.initialNodeCount, ...
        'diagnosticQualityStops',false,'sourceRoot',sourceRoot));
config=ipm.config.resolve(opts);
assert(config.grid.quadrantOnly && isinf(config.time.maxSteps) && ...
    isequal([config.grid.nx,config.grid.ny],settings.initialNodeCount), ...
    'ipm:QuadrantLongConfig','The n=256 unbounded-step job resolved incorrectly.');

if isfolder(outputDirectory)
    prior=dir(outputDirectory);
    assert(numel(prior)<=2,'ipm:QuadrantLongOutputExists', ...
        'The long-run output directory is not empty: %s',outputDirectory);
else
    mkdir(outputDirectory);
end
save(fullfile(outputDirectory,'launch_configuration.mat'), ...
    'settings','opts','config','sourceRoot','-v7.3');
diary(fullfile(outputDirectory,'console.log'));
diaryCleanup=onCleanup(@()diary('off'));
fprintf(['Source: %s\nJob: %s\nResolution level: %d\n' ...
    'Positive grid: %d x %d\nFinal tau: %.0f\n' ...
    'Maximum steps: Inf\nFull-field slice interval: %.3g\nOutput: %s\n'], ...
    sourceRoot,jobRoot,n,config.grid.nx,config.grid.ny, ...
    config.time.finalTime,config.time.outputEvery,outputDirectory);

result=ipm.solve(opts);
resultPointer=struct( ...
    'caseId',result.metadata.caseId, ...
    'resultFile',result.metadata.resultFile, ...
    'latestCheckpointFile',result.metadata.latestCheckpointFile, ...
    'steps',result.state.steps, ...
    'canonicalTime',result.state.canonicalTime, ...
    'physicalTime',result.state.physicalTime, ...
    'stopReason',result.state.stopReason);
save(fullfile(outputDirectory,'launcher_result_pointer.mat'),'resultPointer');
clear diaryCleanup
diary off;
