% Copy this release's main.m into the server job folder and run that copy by
% absolute path. Only the dated releaseRoot below changes between versions.
% IPM_PREFLIGHT_ONLY=1 checks configuration without a Poisson factorization.
mainPath=mfilename('fullpath');
jobRoot=fileparts(mainPath);
releaseRoot='/data/user/hd58131/ipm/ipm_long_time_server_20260914';
assert(isfolder(fullfile(releaseRoot,'+ipm')) && ...
    isfile(fullfile(releaseRoot,'+ipm','+remesh','directLevelSetAdapt.m')), ...
    'ipm:QuadrantServerRelease', ...
    'The fixed absolute releaseRoot must name the NEW quadrant package.');

restoredefaultpath;
addpath(releaseRoot);
settings=struct( ...
    'boxHalfWidth',8,'boxHeight',4, ...
    'initialNodeCount',[1025,513], ... % actual positive-X and Y nodes
    'canonicalFinalTime',4.5,'maximumSteps',4000, ...
    'maximumTimeStep',.004,'minimumTimeStep',1e-12, ...
    'outputEvery',.01,'checkpointEvery',.1, ...
    'maximumAdjacentGridRatio',2, ...
    'storeSnapshots',false,'makePlots',false,'verbose',true);
outputDirectory=fullfile(jobRoot,sprintf('output_quadrant_%dx%d', ...
    settings.initialNodeCount));
settings.outputDirectory=outputDirectory;

% Construct the quadrant configuration directly: longTimeProfile first
% validates the legacy full-domain autonomousMesh policy, so it is not the
% configuration builder for this positive-only job.
opts=struct( ...
    'quadrantOnly',true, ...
    'nx',settings.initialNodeCount(1),'ny',settings.initialNodeCount(2), ...
    'xlim',[0,settings.boxHalfWidth],'ymax',settings.boxHeight, ...
    'gridMode','uniform','gridStretchAutomatic',false, ...
    'gridStretch',[0,0], ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'rescalingMode','dynamic','dynamicScaleGeometry','isotropic', ...
    'symmetryMode','double_odd_omega', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',.5, ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'wallTransportMode','conservative_flux', ...
    'transportBoundaryMode','open', ...
    'adaptiveRemesh',true,'initialAnalyticRemesh',true, ...
    'initialAnalyticRemeshPasses',1, ...
    'finalTime',settings.canonicalFinalTime,'physicalFinalTime',Inf, ...
    'maxSteps',settings.maximumSteps, ...
    'maxDt',settings.maximumTimeStep,'minDt',settings.minimumTimeStep, ...
    'outputEvery',settings.outputEvery, ...
    'remeshMaximumCellRatio',settings.maximumAdjacentGridRatio, ...
    'storeSnapshots',settings.storeSnapshots, ...
    'saveResults',true, ...
    'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'makePlots',settings.makePlots, ...
    'livePlot',false,'writeVideo',false,'verbose',settings.verbose, ...
    'checkpoint',struct('enabled',true, ...
        'file',fullfile(outputDirectory,'checkpoint.mat'), ...
        'every',settings.checkpointEvery,'atExit',true), ...
    'caseMetadata',struct( ...
        'kind','quadrant_level_set_absolute_job_v1', ...
        'manualMidRunGridChanges',false, ...
        'requestedNodeCount',settings.initialNodeCount, ...
        'releaseRoot',releaseRoot));
config=ipm.config.resolve(opts);
assert(config.grid.quadrantOnly && ...
    isequal(config.grid.xlim,[0,settings.boxHalfWidth]) && ...
    ~isfield(config.remesh,'autonomousMesh'), ...
    'ipm:QuadrantServerConfig','The job resolved a legacy full-domain mesh.');

fprintf('Release: %s\nJob: %s\nPositive grid: %d x %d\nOutput: %s\n', ...
    releaseRoot,jobRoot,config.grid.nx,config.grid.ny,outputDirectory);
if strcmp(getenv('IPM_PREFLIGHT_ONLY'),'1')
    fprintf('Preflight only: no Poisson factorization or PDE step was run.\n');
    return
end

% Fresh-run entry: never replace a previous output or checkpoint.
if isfolder(outputDirectory)
    prior=dir(outputDirectory);
    assert(numel(prior)<=2,'ipm:QuadrantServerOutputExists', ...
        'Choose a new empty output directory for a new run.');
else
    mkdir(outputDirectory);
end
save(fullfile(outputDirectory,'launch_configuration.mat'), ...
    'settings','opts','config','-v7.3');
diary(fullfile(outputDirectory,'console.log'));
result=ipm.solve(opts);
resultPointer=struct( ...
    'caseId',result.metadata.caseId, ...
    'resultFile',result.metadata.resultFile, ...
    'latestCheckpointFile',result.metadata.latestCheckpointFile, ...
    'steps',result.state.steps, ...
    'canonicalTime',result.state.canonicalTime, ...
    'physicalTime',result.state.physicalTime, ...
    'stopReason',result.state.stopReason);
save(fullfile(outputDirectory,'launcher_result_pointer.mat'), ...
    'resultPointer');
diary off;
