% Copy this release's main.m into the server job folder and run that copy by
% absolute path. Only the dated releaseRoot below changes between versions.
% IPM_PREFLIGHT_ONLY=1 checks configuration without a Poisson factorization.
mainPath=mfilename('fullpath');
jobRoot=fileparts(mainPath);
releaseRoot='/data/user/hd58131/ipm/ipm_long_time_server_20260915_v2';
assert(isfolder(fullfile(releaseRoot,'+ipm')) && ...
    isfile(fullfile(releaseRoot,'+ipm','+remesh','directLevelSetAdapt.m')), ...
    'ipm:QuadrantServerRelease', ...
    'The fixed absolute releaseRoot must name the NEW quadrant package.');

restoredefaultpath;
addpath(releaseRoot);
settings=struct( ...
    'boxHalfWidth',8,'boxHeight',4, ...
    'initialNodeCount',[1025,513], ... % actual positive-X and Y nodes
    'canonicalFinalTime',4.5,'maximumSteps',Inf, ...
    'maximumTimeStep',.004,'minimumTimeStep',1e-12, ...
    'outputEvery',.01,'checkpointEvery',.1, ...
    'maximumAdjacentGridRatio',2, ...
    'storeSnapshots',false,'makePlots',false,'verbose',true);
outputDirectory=fullfile(jobRoot,sprintf('output_quadrant_%dx%d', ...
    settings.initialNodeCount));
settings.outputDirectory=outputDirectory;
restartCheckpoint=strtrim(getenv('IPM_RESTART_CHECKPOINT'));

% Construct the quadrant configuration directly: longTimeProfile first
% validates the legacy full-domain autonomousMesh policy, so it is not the
% configuration builder for this positive-only job.
opts=struct( ...
    'quadrantOnly',true, ...
    'nx',settings.initialNodeCount(1),'ny',settings.initialNodeCount(2), ...
    'xlim',[0,settings.boxHalfWidth],'ymax',settings.boxHeight, ...
    'gridMode','uniform','gridStretchAutomatic',false, ...
    'gridStretch',[0,0], ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'rescalingMode','dynamic','dynamicScaleGeometry','isotropic', ...
    'symmetryMode','double_odd_omega', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',.5, ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'wallTransportMode','conservative_flux', ...
    'transportBoundaryMode','open', ...
    'adaptiveRemesh',true,'initialAnalyticRemesh',true, ...
    'initialAnalyticRemeshPasses',1, ...
    'finalTime',settings.canonicalFinalTime,'physicalFinalTime',Inf, ...
    'maxSteps',settings.maximumSteps, ...
    'maxDt',settings.maximumTimeStep,'minDt',settings.minimumTimeStep, ...
    'outputEvery',settings.outputEvery, ...
    'remeshMaximumCellRatio',settings.maximumAdjacentGridRatio, ...
    'storeSnapshots',settings.storeSnapshots, ...
    'saveResults',true, ...
    'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'makePlots',settings.makePlots, ...
    'livePlot',false,'writeVideo',false,'verbose',settings.verbose, ...
    'checkpoint',struct('enabled',true, ...
        'file',fullfile(outputDirectory,'checkpoint.mat'), ...
        'every',settings.checkpointEvery,'atExit',true), ...
    'caseMetadata',struct( ...
        'kind','quadrant_level_set_absolute_job_v2', ...
        'manualMidRunGridChanges',false, ...
        'requestedNodeCount',settings.initialNodeCount, ...
        'releaseRoot',releaseRoot));
config=ipm.config.resolve(opts);
assert(config.grid.quadrantOnly && ...
    isequal(config.grid.xlim,[0,settings.boxHalfWidth]) && ...
    ~isfield(config.remesh,'autonomousMesh'), ...
    'ipm:QuadrantServerConfig','The job resolved a legacy full-domain mesh.');

fprintf('Release: %s\nJob: %s\nPositive grid: %d x %d\nOutput: %s\n', ...
    releaseRoot,jobRoot,config.grid.nx,config.grid.ny,outputDirectory);
if isempty(restartCheckpoint)
    fprintf('Mode: fresh run\n');
else
    fprintf('Mode: resume %s\n',restartCheckpoint);
end
if strcmp(getenv('IPM_PREFLIGHT_ONLY'),'1')
    fprintf('Preflight only: no Poisson factorization or PDE step was run.\n');
    return
end

% A fresh run never replaces output. A requested resume writes new immutable
% checkpoints and a uniquely named result beside the existing run artifacts.
if isempty(restartCheckpoint) && isfolder(outputDirectory)
    prior=dir(outputDirectory);
    assert(numel(prior)<=2,'ipm:QuadrantServerOutputExists', ...
        'Choose a new empty output directory for a new run.');
else
    if ~isfolder(outputDirectory)
        mkdir(outputDirectory);
    end
end
if isempty(restartCheckpoint)
    launchFile=fullfile(outputDirectory,'launch_configuration.mat');
    consoleFile=fullfile(outputDirectory,'console.log');
else
    assert(isfile(restartCheckpoint),'ipm:QuadrantServerCheckpoint', ...
        'Cannot find restart checkpoint at %s.',restartCheckpoint);
    launchFile=ipm.output.uniquePath( ...
        fullfile(outputDirectory,'launch_configuration_resume.mat'),'resume');
    consoleFile=ipm.output.uniquePath( ...
        fullfile(outputDirectory,'console_resume.log'),'resume');
end
save(launchFile,'settings','opts','config','restartCheckpoint','-v7.3');
diary(consoleFile);
if isempty(restartCheckpoint)
    result=ipm.solve(opts);
else
    resume=struct( ...
        'finalTime',settings.canonicalFinalTime, ...
        'physicalFinalTime',Inf,'maxSteps',settings.maximumSteps, ...
        'saveResults',true,'resultFile',opts.resultFile, ...
        'makePlots',settings.makePlots,'livePlot',false, ...
        'writeVideo',false,'verbose',settings.verbose, ...
        'checkpoint',opts.checkpoint, ...
        'caseMetadata',struct( ...
            'kind','quadrant_level_set_absolute_resume_v2', ...
            'sourceCheckpoint',restartCheckpoint, ...
            'releaseRoot',releaseRoot));
    result=ipm.solve(resume,restartCheckpoint);
end
resultPointer=struct( ...
    'caseId',result.metadata.caseId, ...
    'resultFile',result.metadata.resultFile, ...
    'latestCheckpointFile',result.metadata.latestCheckpointFile, ...
    'steps',result.state.steps, ...
    'canonicalTime',result.state.canonicalTime, ...
    'physicalTime',result.state.physicalTime, ...
    'stopReason',result.state.stopReason);
pointerFile=ipm.output.uniquePath( ...
    fullfile(outputDirectory,'launcher_result_pointer.mat'),result.metadata.caseId);
save(pointerFile,'resultPointer');
diary off;
