function status = profile_status(runDirectory)
%PROFILE_STATUS Read the latest accepted long-time Profile checkpoint.
%   STATUS = PROFILE_STATUS(RUNDIRECTORY) validates one saved checkpoint and
%   reports its numerical state. A checkpoint alone does not prove that the
%   solver process is still running.

serverDirectory = fileparts(mfilename('fullpath'));
projectRoot = fileparts(serverDirectory);
addpath(projectRoot);
if nargin < 1 || isempty(runDirectory)
    settings = profile_settings(projectRoot);
    runDirectory = settings.outputDirectory;
end
if isstring(runDirectory) && isscalar(runDirectory)
    runDirectory = char(runDirectory);
end
if ~ischar(runDirectory) || ~isrow(runDirectory) || ~isfolder(runDirectory)
    error('ipm:ProfileStatusDirectory', ...
        'Provide an existing run directory.');
end

files = dir(fullfile(runDirectory,'checkpoint_*_step*.mat'));
if isempty(files)
    error('ipm:ProfileStatusCheckpoint', ...
        'No accepted-step checkpoint exists in %s.',runDirectory);
end
dates = [files.datenum];
latest = find(dates == max(dates),1,'last');
checkpointFile = fullfile(files(latest).folder,files(latest).name);
checkpoint = ipm.output.readCheckpoint(checkpointFile);
saved = checkpoint.payload.state;
history = checkpoint.payload.log.history;
common = history.common;
mesh = history.mesh;
assert(history.common.acceptedStep(end) == saved.step && ...
    history.common.canonicalTau(end) == saved.scale.canonicalTime, ...
    'ipm:ProfileStatusPairing', ...
    'The latest checkpoint and its accepted history do not agree.');

status = struct( ...
    'checkpointFile',checkpointFile, ...
    'caseId',saved.runMetadata.caseId, ...
    'step',saved.step, ...
    'canonicalTime',saved.scale.canonicalTime, ...
    'physicalTime',saved.scale.physicalTime, ...
    'nodeCount',[numel(saved.x),numel(saved.y)], ...
    'remeshCount',saved.remeshCount, ...
    'meshLevelId',saved.runMetadata.autonomousMesh.currentLevelId, ...
    'coreCells',[mesh.coreGridPoints(end),mesh.verticalCoreGridPoints(end)], ...
    'adjacentCellRatio',[mesh.maximumCellRatioX(end),mesh.maximumCellRatioY(end)], ...
    'safetyFactor',mesh.safetyFactor(end), ...
    'physicalGradientMaximum',common.physicalGradInf(end), ...
    'physicalWallOmegaPeak',common.physicalWallOmegaPeak(end), ...
    'farBoundaryVelocityRatio',common.farBoundaryVelocityRatio(end), ...
    'farBoundarySourceRatio',common.farBoundarySourceRatio(end), ...
    'farBoundaryTolerance',saved.config.diagnostics.farBoundaryTolerance, ...
    'trustedCheckpoint',checkpoint.trustedRecord);
if isfield(saved.runMetadata,'continuousVerticalShadow')
    shadow=saved.runMetadata.continuousVerticalShadow;
    status.shadowVerticalCoreCells=shadow.latest.continuousCells;
    status.shadowObservedStep=shadow.latest.step;
    status.shadowObservedRemeshCount=shadow.latest.remeshCount;
    status.shadowDifferentRequests=shadow.differentRequests;
end
if isfield(saved.runMetadata,'continuousVerticalShadowFailure')
    status.shadowObservationFailures= ...
        saved.runMetadata.continuousVerticalShadowFailure.count;
end

fprintf(['Profile checkpoint: tau=%.9g, physical t=%.9g, step=%d, ' ...
    'grid=%d x %d, remesh=%d, level=%d\n'], ...
    status.canonicalTime,status.physicalTime,status.step, ...
    status.nodeCount,status.remeshCount,status.meshLevelId);
fprintf(['  core cells X/Y=%.3f/%.3f, adjacent ratio X/Y=%.6f/%.6f, ' ...
    'safety=%.4g\n'],status.coreCells,status.adjacentCellRatio, ...
    status.safetyFactor);
fprintf(['  physical gradient=%.6g, wall omega peak=%.6g, ' ...
    'far-boundary source/velocity=%.4g/%.4g (warning threshold %.4g)\n'], ...
    status.physicalGradientMaximum,status.physicalWallOmegaPeak, ...
    status.farBoundarySourceRatio,status.farBoundaryVelocityRatio, ...
    status.farBoundaryTolerance);
if isfield(status,'shadowVerticalCoreCells')
    fprintf(['  shadow continuous Y core=%.3f at step %d/remesh %d, ' ...
        'different grid requests=%d\n'], ...
        status.shadowVerticalCoreCells,status.shadowObservedStep, ...
        status.shadowObservedRemeshCount,status.shadowDifferentRequests);
end
if isfield(status,'shadowObservationFailures')
    fprintf('  shadow observation failures=%d (native grid decisions unaffected)\n', ...
        status.shadowObservationFailures);
end
if max(status.farBoundarySourceRatio,status.farBoundaryVelocityRatio) > ...
        status.farBoundaryTolerance
    fprintf(['  WARNING: far-boundary diagnostic exceeds its threshold; ' ...
        'a larger-box comparison is needed for Profile accuracy.\n']);
end
fprintf('  checkpoint: %s\n',status.checkpointFile);
end
