% Server launcher. The numerical solver still has one entry: ipm.solve.
serverDirectory = fileparts(mfilename('fullpath'));
projectRoot = fileparts(serverDirectory);
restoredefaultpath;
addpath(projectRoot,serverDirectory);
settings = profile_settings(projectRoot);
restartCheckpoint = settings.restartCheckpoint;
settings = rmfield(settings,'restartCheckpoint');
opts = ipm.config.longTimeProfile(settings);
config = ipm.config.resolve(opts);

if ~isempty(restartCheckpoint)
    savedCheckpoint = ipm.output.readCheckpoint(restartCheckpoint);
    savedConfig = savedCheckpoint.payload.state.config;
    timeInvariantNames = {'cfl','maxDt','minDt','outputEvery','timeIntegrator'};
    newTimeInvariant = struct();
    savedTimeInvariant = struct();
    for name = timeInvariantNames
        newTimeInvariant.(name{1}) = config.time.(name{1});
        savedTimeInvariant.(name{1}) = savedConfig.time.(name{1});
    end
    assert(isequaln(config.grid,savedConfig.grid) && ...
        isequaln(config.physics,savedConfig.physics) && ...
        isequaln(config.elliptic,savedConfig.elliptic) && ...
        isequaln(config.transport,savedConfig.transport) && ...
        isequaln(config.scaling,savedConfig.scaling) && ...
        isequaln(config.remesh,savedConfig.remesh) && ...
        isequaln(config.diagnostics,savedConfig.diagnostics) && ...
        isequaln(newTimeInvariant,savedTimeInvariant), ...
        'ipm:ServerResumeSettingsMismatch', ...
        ['Restart settings must match the checkpoint grid, physics, ' ...
        'discretization, C rule, mesh policy, safety gates, and time cadence.']);
    clear savedCheckpoint savedConfig newTimeInvariant savedTimeInvariant name;
end

if ~isfolder(settings.outputDirectory)
    mkdir(settings.outputDirectory);
end
diaryFile = fullfile(settings.outputDirectory,'console.log');
diary(diaryFile);
fprintf('IPM long-time profile\n');
fprintf('  project: %s\n',projectRoot);
fprintf('  output: %s\n',settings.outputDirectory);
fprintf('  canonical target: %.17g\n',config.time.finalTime);
fprintf('  maximum steps: %d\n',config.time.maxSteps);
fprintf('  adjacent-grid-ratio stop: max(r_x,r_y) > %.17g*(1+1e-10)\n', ...
    config.remesh.remeshMaximumCellRatio);
fprintf('  autonomous mesh: version %d, node cap %d\n', ...
    config.remesh.autonomousMesh.version, ...
    config.remesh.autonomousMesh.nodeFamily.maximumTotalNodes);
save(fullfile(settings.outputDirectory,'launch_configuration.mat'), ...
    'settings','opts','config','restartCheckpoint','-v7.3');

if isempty(restartCheckpoint)
    fprintf('  mode: new original physical t=0 run\n');
    result = ipm.solve(opts);
else
    fprintf('  mode: resume %s\n',restartCheckpoint);
    resume = struct( ...
        'finalTime',opts.finalTime, ...
        'physicalFinalTime',opts.physicalFinalTime, ...
        'maxSteps',opts.maxSteps, ...
        'saveResults',opts.saveResults, ...
        'resultFile',opts.resultFile, ...
        'makePlots',opts.makePlots, ...
        'livePlot',opts.livePlot, ...
        'writeVideo',opts.writeVideo, ...
        'verbose',opts.verbose, ...
        'caseMetadata',opts.caseMetadata, ...
        'checkpoint',opts.checkpoint);
    result = ipm.solve(resume,restartCheckpoint);
end
resultPointer = struct('caseId',result.metadata.caseId, ...
    'resultFile',result.metadata.resultFile, ...
    'latestCheckpointFile',result.metadata.latestCheckpointFile, ...
    'steps',result.state.steps,'canonicalTime',result.state.canonicalTime, ...
    'physicalTime',result.state.physicalTime, ...
    'stopReason',result.state.stopReason);
save(fullfile(settings.outputDirectory,'launcher_result_pointer.mat'), ...
    'resultPointer');
diary off;
