function report = ipm_gaugelab_test_q512_cfl_ladder()
%IPM_GAUGELAB_TEST_Q512_CFL_LADDER Lightweight no-PDE preflight test.

laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    laboratoryDirectory);

temporaryRoot = [tempname,'_q512_cfl_preflight'];
mkdir(temporaryRoot);
cleanup = onCleanup(@()remove_temporary_root(temporaryRoot));
ladder = ipm_gaugelab_run_q512_cfl_ladder(struct( ...
    'outputRoot',temporaryRoot,'verbose',false));

assert(strcmp(ladder.status,'preflight_complete') && ...
    strcmp(ladder.executionMode,'preflight_only') && ...
    ladder.preflightPassed && ~ladder.hardPassed && ...
    ladder.freshRootsOnly && ~ladder.checkpointInputsAccepted && ...
    ladder.internalConfirmLongRun && ...
    strcmp(ladder.rootRunMode,'campaign') && ...
    strcmp(ladder.onlyConfigurationVariable,'time.cfl') && ...
    isequal(ladder.cflCandidates,[0.25,0.50]) && ...
    strcmp(ladder.interpretation, ...
        'short_window_cfl_consistency_only_not_late_time_evidence') && ...
    ~ladder.lateTimeEvidence, ...
    'ipm:GaugeLabQ512CflTestProtocol', ...
    'The q512 CFL ladder protocol or default execution guard changed.');

requested = ladder.requested;
assert(~requested.execute && strcmp(requested.boxMode,'large_box') && ...
    requested.boxHalfWidth == 1e6 && ...
    requested.physicalFinalTime == 0.03 && ...
    requested.canonicalFinalTime == 0.05 && ...
    requested.maxDt == 0.004 && requested.maxSteps == 512 && ...
    requested.outputEvery == 1e-10 && ...
    requested.checkpointEvery == 0.01, ...
    'ipm:GaugeLabQ512CflTestDefaults', ...
    'The bounded short-campaign defaults changed unexpectedly.');

assert(numel(ladder.roots) == 2 && ...
    all(strcmp({ladder.roots.status},'preflight_only')) && ...
    all(strcmp({ladder.roots.rootStatus},'preflight_only')) && ...
    all([ladder.roots.rootAccepted]) && ...
    all(strcmp({ladder.roots.boxMode},'large_box')) && ...
    all(strcmp({ladder.roots.runMode},'campaign')) && ...
    all([ladder.roots.preflightOnly]) && ...
    all([ladder.roots.freshStart]) && ...
    all(strcmp({ladder.roots.restartInput},'none')) && ...
    all([ladder.roots.meshPassed]) && ...
    all([ladder.roots.contractPassed]) && ...
    ~any([ladder.roots.resultAvailable]) && ...
    ladder.sharedContractAudit.passed && ...
    strcmp(ladder.comparison.status,'preflight_only_not_executed') && ...
    ~ladder.comparison.available, ...
    'ipm:GaugeLabQ512CflTestRoots', ...
    'Fresh-root preflight or shared-contract audit did not pass.');

for index = 1:numel(ladder.roots)
    root = ladder.roots(index);
    assert(root.requested.cfl == ladder.cflCandidates(index) && ...
        root.requested.maxDt == requested.maxDt && ...
        root.requested.physicalFinalTime == ...
            requested.physicalFinalTime && ...
        root.requested.canonicalFinalTime == ...
            requested.canonicalFinalTime && ...
        root.requested.maxSteps == requested.maxSteps && ...
        isequal(root.domain.initialPhysicalX,[-1e6,1e6]) && ...
        isequal(root.domain.initialPhysicalY,[0,1e6]) && ...
        root.configSignature.cfl == ladder.cflCandidates(index) && ...
        strcmp(root.configSignature.scaling.lengthGauge, ...
            'transport_anchor') && ...
        root.configSignature.scaling.transportAnchorX == 1 && ...
        strcmp(root.configSignature.scaling.cOmegaGauge, ...
            'gradient_energy') && ...
        strcmp(root.configSignature.timeExceptCfl.timeIntegrator, ...
            'ssprk54'), ...
        'ipm:GaugeLabQ512CflTestRootContract', ...
        'A root changed a protected box, time, gauge, or RK choice.');
end

assert(isfile(ladder.summaryFile) && isfile(ladder.manifestFile) && ...
    isempty(dir(fullfile(temporaryRoot,'**','result.mat'))), ...
    'ipm:GaugeLabQ512CflTestNoSolve', ...
    'Default preflight either omitted records or executed a PDE solve.');
loaded = load(ladder.summaryFile,'ladder');
assert(strcmp(loaded.ladder.status,'preflight_complete') && ...
    loaded.ladder.preflightPassed, ...
    'ipm:GaugeLabQ512CflTestSavedSummary', ...
    'The final preflight summary was not saved.');

checkpointRejected = false;
try
    ipm_gaugelab_run_q512_cfl_ladder(struct( ...
        'checkpoint','forbidden.mat'));
catch exception
    checkpointRejected = strcmp(exception.identifier, ...
        'ipm:GaugeLabQ512CflLadderOptions');
end
assert(checkpointRejected, ...
    'ipm:GaugeLabQ512CflTestCheckpointInput', ...
    'The q512 CFL ladder accepted a checkpoint input option.');

mutableCflRejected = false;
try
    ipm_gaugelab_run_q512_cfl_ladder(struct( ...
        'cflCandidates',[0.2,0.5]));
catch exception
    mutableCflRejected = strcmp(exception.identifier, ...
        'ipm:GaugeLabQ512CflLadderOptions');
end
assert(mutableCflRejected, ...
    'ipm:GaugeLabQ512CflTestCandidates', ...
    'The fixed [0.25,0.50] q512 CFL pair became user-mutable.');

report = struct( ...
    'status',ladder.status, ...
    'preflightPassed',ladder.preflightPassed, ...
    'cflCandidates',ladder.cflCandidates, ...
    'boxHalfWidth',ladder.requested.boxHalfWidth, ...
    'rootStatuses',{ {ladder.roots.status} }, ...
    'checkpointInputRejected',checkpointRejected, ...
    'mutableCflRejected',mutableCflRejected, ...
    'solveExecuted',false);
clear cleanup;
fprintf(['Q512 CFL ladder preflight: roots=%d, box=%.0e, ' ...
    'checkpoint input rejected=%d.\n'],numel(ladder.roots), ...
    report.boxHalfWidth,report.checkpointInputRejected);
end

function remove_temporary_root(pathName)
if isfolder(pathName)
    rmdir(pathName,'s');
end
end
