function products = ipm_gaugelab_run_cfl_ladder(userOptions)
%IPM_GAUGELAB_RUN_CFL_LADDER Compare exact gauges at several CFL values.
%   The default is a short q256 scientific smoke test at common physical
%   time.  maxDt and every spatial/gauge choice remain fixed, so the only
%   numerical variable is CFL.  This runner never changes a gauge rate or
%   treats a generic stability certificate as late-time evidence.

if nargin < 1
    userOptions = struct();
end
options = resolve_options(userOptions);
laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    laboratoryDirectory);

stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
outputDirectory = fullfile(projectDirectory,'result','verification', ...
    'q256_exact_gauge_cfl_ladders',['ladder_',stamp]);
mkdir(outputDirectory);
summaryFile = fullfile(outputDirectory,'cfl_ladder_summary.mat');
manifestFile = fullfile(outputDirectory,'cfl_ladder_manifest.jsonl');
protocol = struct('schemaVersion',1,'kind','q256_exact_gauge_cfl_ladder', ...
    'baseCaseName',options.baseCaseName, ...
    'cflCandidates',options.cflCandidates, ...
    'maximumTimeStep',options.maxDt, ...
    'physicalFinalTime',options.physicalFinalTime, ...
    'comparisonWindow',[-2,2,2], ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','gradient_energy', ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'numericalTuple',struct('spatialDiscretization','high_order', ...
        'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
        'remeshTransferScheme','high_order'), ...
    'hardLimits',hard_limits());
template = struct('cfl',NaN,'status','registered','resultFile','', ...
    'elapsedSeconds',NaN,'acceptedSteps',NaN,'secondsPerStep',NaN, ...
    'stopReason','','physicalTime',NaN,'canonicalTime',NaN, ...
    'physicalRhoXInf',NaN,'canonicalCL',NaN,'canonicalCOmega',NaN, ...
    'cOmegaOverCL',NaN,'cLTrend',struct(),'cOmegaTrend',struct(), ...
    'limiterRecords',struct(),'trustedTerminal',false, ...
    'exactContract',false,'errorIdentifier','','errorMessage','');
products = struct('schemaVersion',1,'kind',protocol.kind, ...
    'status','registered','startedAt',datetime('now','TimeZone','local'), ...
    'completedAt',NaT,'protocol',protocol, ...
    'outputDirectory',outputDirectory,'summaryFile',summaryFile, ...
    'manifestFile',manifestFile, ...
    'runs',repmat(template,numel(options.cflCandidates),1), ...
    'comparisons',repmat(empty_comparison(), ...
        numel(options.cflCandidates),1),'hardPassed',false, ...
    'elapsedSeconds',NaN);
save(summaryFile,'products','-v7.3');
append_manifest(manifestFile,struct('event','registered', ...
    'timestampUtc',stamp,'protocol',protocol));

clock = tic;
results = cell(numel(options.cflCandidates),1);
products.status = 'running';
save(summaryFile,'products','-v7.3');
for index = 1:numel(options.cflCandidates)
    cfl = options.cflCandidates(index);
    candidateDirectory = fullfile(outputDirectory, ...
        sprintf('cfl_%03d',round(100*cfl)));
    mkdir(candidateDirectory);
    resultFile = fullfile(candidateDirectory,'result.mat');
    run = template;
    run.cfl = cfl;
    run.status = 'running';
    append_manifest(manifestFile,struct('event','run_started', ...
        'timestampUtc',utc_stamp(),'cfl',cfl));
    runClock = tic;
    try
        metadata = struct('cflLadder',struct( ...
            'schemaVersion',1,'freshInitialState',true, ...
            'onlyCflVaried',true,'candidateCfl',cfl, ...
            'protocol',protocol));
        opts = fourth_order_blowup_case(options.baseCaseName,struct( ...
            'rescalingMode','dynamic', ...
            'dynamicScaleGeometry','isotropic', ...
            'lengthGauge','transport_anchor','transportAnchorX',1, ...
            'cOmegaGauge','gradient_energy', ...
            'lengthScaleGain',1,'widthGaugeGain',0, ...
            'omegaGaugeGain',0,'travelingWaveGain',0, ...
            'physicalFinalTime',options.physicalFinalTime, ...
            'maxDt',options.maxDt,'cfl',cfl, ...
            'maxSteps',options.maxSteps, ...
            'outputEvery',options.outputEvery, ...
            'checkpoint',struct('enabled',false), ...
            'saveResults',true,'resultFile',resultFile, ...
            'storeSnapshots',false,'makePlots',false, ...
            'livePlot',false,'writeVideo',false, ...
            'verbose',options.verbose,'caseMetadata',metadata));
        assert_exact_options(opts,protocol);
        result = ipm.solve(opts);
        results{index} = result;
        run = summarize_run(result,cfl,toc(runClock));
        run.resultFile = char(result.metadata.resultFile);
        run.status = 'completed';
    catch exception
        run.elapsedSeconds = toc(runClock);
        run.status = 'failed';
        run.errorIdentifier = exception.identifier;
        run.errorMessage = exception.message;
    end
    products.runs(index) = run;
    save(summaryFile,'products','-v7.3');
    append_manifest(manifestFile,struct('event','run_finished', ...
        'timestampUtc',utc_stamp(),'run',run));
end

reference = results{1};
for index = 1:numel(results)
    if isempty(reference) || isempty(results{index})
        continue;
    end
    products.comparisons(index) = compare_to_reference( ...
        reference,results{index},products.runs(1), ...
        products.runs(index),protocol.hardLimits,protocol.comparisonWindow);
end
completed = strcmp({products.runs.status},'completed');
comparisonPass = [products.comparisons.hardPassed];
products.hardPassed = all(completed) && all(comparisonPass);
if products.hardPassed
    products.status = 'passed';
else
    products.status = 'failed';
end
products.completedAt = datetime('now','TimeZone','local');
products.elapsedSeconds = toc(clock);
save(summaryFile,'products','-v7.3');
append_manifest(manifestFile,struct('event','ladder_finished', ...
    'timestampUtc',utc_stamp(),'status',products.status, ...
    'hardPassed',products.hardPassed, ...
    'elapsedSeconds',products.elapsedSeconds));
fprintf('Q256 CFL LADDER: status=%s summary=%s\n', ...
    products.status,summaryFile);
end

function options = resolve_options(user)
if ~isstruct(user) || ~isscalar(user)
    error('ipm:GaugeLabCflOptions','Options must be a scalar structure.');
end
options = struct('baseCaseName', ...
    'coordinated_log_F80_R20_c114_quadrant_256', ...
    'cflCandidates',[0.25,0.35,0.50], ...
    'physicalFinalTime',0.10,'maxDt',2e-3,'maxSteps',1200, ...
    'outputEvery',1e-6,'verbose',false);
unexpected = setdiff(fieldnames(user),fieldnames(options),'stable');
if ~isempty(unexpected)
    error('ipm:GaugeLabCflOptions','Unknown option(s): %s.', ...
        strjoin(unexpected,', '));
end
names = fieldnames(user);
for index = 1:numel(names)
    options.(names{index}) = user.(names{index});
end
validateattributes(options.cflCandidates,{'numeric'}, ...
    {'vector','nonempty','real','finite','>',0,'<=',0.5,'increasing'});
validateattributes(options.physicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(options.maxDt,{'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(options.maxSteps,{'numeric'}, ...
    {'scalar','real','finite','integer','positive'});
validateattributes(options.outputEvery,{'numeric'}, ...
    {'scalar','real','finite','positive'});
if ~(islogical(options.verbose) && isscalar(options.verbose))
    error('ipm:GaugeLabCflOptions','verbose must be scalar logical.');
end
end

function limits = hard_limits()
limits = struct( ...
    'maximumPhysicalEndpointDifference',1e-10, ...
    'maximumTerminalCLRelativeDifference',1e-2, ...
    'maximumTerminalCOmegaRelativeDifference',1e-2, ...
    'maximumRateTrendDifference',1e-2, ...
    'maximumPhysicalRhoXRelativeDifference',5e-3, ...
    'maximumRhoRelativeL2',5e-4, ...
    'maximumOmegaRelativeL2',5e-3, ...
    'maximumRhoAbsoluteInf',5e-4, ...
    'maximumOmegaAbsoluteInf',5e-3);
end

function assert_exact_options(opts,protocol)
config = ipm.config.resolve(opts);
retired = {'maxDynamicRate','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
tuple = protocol.numericalTuple;
assert(config.schemaVersion == 4 && ...
    strcmp(config.scaling.scalingContract,protocol.scalingContract) && ...
    strcmp(config.scaling.lengthGauge,protocol.lengthGauge) && ...
    config.scaling.transportAnchorX == protocol.transportAnchorX && ...
    strcmp(config.scaling.cOmegaGauge,protocol.cOmegaGauge) && ...
    config.scaling.lengthScaleGain == 1 && ...
    config.scaling.widthGaugeGain == 0 && ...
    config.scaling.omegaGaugeGain == 0 && ...
    config.scaling.travelingWaveGain == 0 && ...
    isempty(intersect(fieldnames(config.scaling),retired)) && ...
    strcmp(config.transport.spatialDiscretization, ...
        tuple.spatialDiscretization) && ...
    strcmp(config.transport.transportScheme,tuple.transportScheme) && ...
    strcmp(config.time.timeIntegrator,tuple.timeIntegrator) && ...
    strcmp(config.remesh.remeshTransferScheme, ...
        tuple.remeshTransferScheme) && ...
    ~config.remesh.adaptiveRemesh, ...
    'ipm:GaugeLabCflContract', ...
    'A CFL candidate changed the exact fixed-grid numerical contract.');
end

function run = summarize_run(result,cfl,elapsed)
common = result.history.common;
trusted = ipm.output.continuousTrustedPrefix( ...
    ipm.output.trustedMask(result));
run = struct('cfl',cfl,'status','completed', ...
    'resultFile','','elapsedSeconds',elapsed, ...
    'acceptedSteps',result.state.steps, ...
    'secondsPerStep',elapsed/max(result.state.steps,1), ...
    'stopReason',result.state.stopReason, ...
    'physicalTime',result.state.physicalTime, ...
    'canonicalTime',result.state.canonicalTime, ...
    'physicalRhoXInf',common.physicalRhoXInf(end), ...
    'canonicalCL',common.canonicalCL(end), ...
    'canonicalCOmega',common.canonicalCOmega(end), ...
    'cOmegaOverCL',common.canonicalCOmega(end)/common.canonicalCL(end), ...
    'cLTrend',trailing_trend(common,'canonicalCL'), ...
    'cOmegaTrend',trailing_trend(common,'canonicalCOmega'), ...
    'limiterRecords',limiter_counts(common), ...
    'trustedTerminal',~isempty(trusted) && trusted(end), ...
    'exactContract',exact_result_contract(result), ...
    'errorIdentifier','','errorMessage','');
end

function exact = exact_result_contract(result)
common = result.history.common;
gauge = result.history.gauge;
exact = result.config.schemaVersion == 4 && ...
    strcmp(result.config.scaling.scalingContract, ...
        'exact_gauge_no_feedback_v1') && ...
    strcmp(result.config.scaling.cOmegaGauge,'gradient_energy') && ...
    all(common.timeSpeed == 1) && ...
    max(abs(common.c_l-common.canonicalCL)) == 0 && ...
    max(abs(common.c_omega-common.canonicalCOmega)) == 0 && ...
    isfield(gauge,'omegaGaugeResidual') && ...
    max(abs(gauge.omegaGaugeResidual)) <= 1e-10;
end

function counts = limiter_counts(common)
names = ["initial","max_dt","cfl", ...
    "canonical_final_time","physical_final_time","other"];
counts = struct('initial',0,'maxDt',0,'cfl',0, ...
    'canonicalFinalTime',0,'physicalFinalTime',0,'other',0, ...
    'records',numel(common.t));
if ~isfield(common,'timestepActiveLimiter')
    counts.other = counts.records;
    return;
end
values = string(common.timestepActiveLimiter(:));
raw = zeros(size(names));
for index = 1:numel(names)-1
    raw(index) = nnz(values == names(index));
end
raw(end) = numel(values)-sum(raw(1:end-1));
counts.initial = raw(1);
counts.maxDt = raw(2);
counts.cfl = raw(3);
counts.canonicalFinalTime = raw(4);
counts.physicalFinalTime = raw(5);
counts.other = raw(6);
end

function trend = trailing_trend(common,name)
tau = common.canonicalTau(:);
values = common.(name)(:);
start = tau(end)-0.4*(tau(end)-tau(1));
keep = tau >= start;
tau = tau(keep);
values = values(keep);
trend = struct('valid',false,'records',numel(values), ...
    'relativeTrend',NaN,'detrendedRelativeRms',NaN);
if numel(tau) < 6 || tau(end) <= tau(1)
    return;
end
centered = tau-mean(tau);
coefficients = [ones(size(centered)),centered]\values;
fitted = [ones(size(centered)),centered]*coefficients;
scale = max(abs(mean(values)),eps);
trend.valid = all(isfinite(coefficients));
trend.relativeTrend = coefficients(2)*(tau(end)-tau(1))/scale;
trend.detrendedRelativeRms = sqrt(mean((values-fitted).^2))/scale;
end

function comparison = compare_to_reference( ...
        reference,candidate,referenceRun,candidateRun,limits,window)
forward = ipm.output.compare(reference,candidate,window);
reverse = ipm.output.compare(candidate,reference,window);
physical = symmetric_max(forward,reverse);
comparison = empty_comparison();
comparison.referenceCfl = referenceRun.cfl;
comparison.candidateCfl = candidateRun.cfl;
comparison.physicalEndpointDifference = ...
    candidateRun.physicalTime-referenceRun.physicalTime;
comparison.terminalCLRelativeDifference = relative_difference( ...
    referenceRun.canonicalCL,candidateRun.canonicalCL);
comparison.terminalCOmegaRelativeDifference = relative_difference( ...
    referenceRun.canonicalCOmega,candidateRun.canonicalCOmega);
comparison.cLTrendDifference = candidateRun.cLTrend.relativeTrend- ...
    referenceRun.cLTrend.relativeTrend;
comparison.cOmegaTrendDifference = ...
    candidateRun.cOmegaTrend.relativeTrend- ...
    referenceRun.cOmegaTrend.relativeTrend;
comparison.physicalRhoXRelativeDifference = relative_difference( ...
    referenceRun.physicalRhoXInf,candidateRun.physicalRhoXInf);
comparison.physicalComparison = physical;
comparison.hardPassed = referenceRun.trustedTerminal && ...
    candidateRun.trustedTerminal && referenceRun.exactContract && ...
    candidateRun.exactContract && ...
    abs(comparison.physicalEndpointDifference) <= ...
        limits.maximumPhysicalEndpointDifference && ...
    abs(comparison.terminalCLRelativeDifference) <= ...
        limits.maximumTerminalCLRelativeDifference && ...
    abs(comparison.terminalCOmegaRelativeDifference) <= ...
        limits.maximumTerminalCOmegaRelativeDifference && ...
    referenceRun.cLTrend.valid && candidateRun.cLTrend.valid && ...
    abs(comparison.cLTrendDifference) <= ...
        limits.maximumRateTrendDifference && ...
    referenceRun.cOmegaTrend.valid && candidateRun.cOmegaTrend.valid && ...
    abs(comparison.cOmegaTrendDifference) <= ...
        limits.maximumRateTrendDifference && ...
    abs(comparison.physicalRhoXRelativeDifference) <= ...
        limits.maximumPhysicalRhoXRelativeDifference && ...
    physical.rhoRelativeL2 <= limits.maximumRhoRelativeL2 && ...
    physical.omegaRelativeL2 <= limits.maximumOmegaRelativeL2 && ...
    physical.rhoAbsoluteInf <= limits.maximumRhoAbsoluteInf && ...
    physical.omegaAbsoluteInf <= limits.maximumOmegaAbsoluteInf;
end

function value = symmetric_max(forward,reverse)
value = forward;
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference'};
for index = 1:numel(names)
    name = names{index};
    value.(name) = max(abs([forward.(name),reverse.(name)]));
end
end

function value = relative_difference(reference,candidate)
value = (candidate-reference)/max(abs(reference),eps);
end

function value = empty_comparison()
value = struct('referenceCfl',NaN,'candidateCfl',NaN, ...
    'physicalEndpointDifference',NaN, ...
    'terminalCLRelativeDifference',NaN, ...
    'terminalCOmegaRelativeDifference',NaN, ...
    'cLTrendDifference',NaN,'cOmegaTrendDifference',NaN, ...
    'physicalRhoXRelativeDifference',NaN, ...
    'physicalComparison',struct(),'hardPassed',false);
end

function append_manifest(fileName,entry)
file = fopen(fileName,'a');
if file < 0
    error('ipm:GaugeLabCflManifest','Cannot open manifest: %s.',fileName);
end
cleanup = onCleanup(@()fclose(file));
fprintf(file,'%s\n',jsonencode(entry));
end

function stamp = utc_stamp()
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
end
