function report = ipm_gaugelab_test_q256_cl_tournament()
%IPM_GAUGELAB_TEST_Q256_CL_TOURNAMENT Lightweight registry/preflight test.

laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    laboratoryDirectory);

specifications = ipm_gaugelab_length_candidate_specifications();
expected = {'transport_anchor','symmetry_peak','local_strain', ...
    'omega_peak_location','wall_omega_width','wall_density_width'};
assert(isequal({specifications.lengthGauge},expected) && ...
    numel(unique({specifications.formula})) == numel(expected), ...
    'ipm:GaugeLabCLTestRegistry', ...
    'The preregistered c_l candidate set or formula registry changed.');

temporaryRoot = [tempname,'_CaseSensitiveCL'];
mkdir(temporaryRoot);
cleanup = onCleanup(@()remove_temporary_root(temporaryRoot));
products = ipm_gaugelab_run_q256_cl_tournament(struct( ...
    'runMode','formal','preflightOnly',true, ...
    'outputRoot',temporaryRoot,'cfl',0.5,'maxDt',4e-3));
protocol = products.protocol;
assert(strcmp(products.status,'registered') && ...
    strcmp(protocol.onlyConfigurationVariable,'scaling.lengthGauge') && ...
    strcmp(protocol.cOmegaGauge,'gradient_energy') && ...
    strcmp(protocol.scalingContract,'exact_gauge_no_feedback_v1') && ...
    protocol.minimumSuccessfulCandidates == 2 && ...
    protocol.cfl == 0.5 && protocol.maximumTimeStep == 4e-3 && ...
    isequal(protocol.rateConvergenceWindows,[0.25,0.40,0.60]) && ...
    startsWith(products.outputDirectory,temporaryRoot) && ...
    isequal({protocol.candidateSpecifications.lengthGauge},expected), ...
    'ipm:GaugeLabCLTestProtocol', ...
    'The formal c_l preflight protocol is incomplete or mutable.');

retired = {'maxDynamicRate','adaptiveGain','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
for index = 1:numel(protocol.candidateConfigurations)
    config = protocol.candidateConfigurations{index};
    assert(config.schemaVersion == 4 && ...
        strcmp(config.scaling.lengthGauge,expected{index}) && ...
        strcmp(config.scaling.cOmegaGauge,'gradient_energy') && ...
        config.scaling.lengthScaleGain == 1 && ...
        config.scaling.widthGaugeGain == 0 && ...
        config.scaling.omegaGaugeGain == 0 && ...
        config.scaling.travelingWaveGain == 0 && ...
        config.time.cfl == 0.5 && config.time.maxDt == 4e-3 && ...
        isempty(intersect(fieldnames(config.scaling),retired)) && ...
        ~config.remesh.initialAnalyticRemesh && ...
        ~config.remesh.adaptiveRemesh, ...
        'ipm:GaugeLabCLTestConfiguration', ...
        'A preflight candidate violates the exact fixed-grid contract.');
end

confirmationRejected = false;
try
    ipm_gaugelab_run_q256_cl_tournament(struct('runMode','formal'));
catch exception
    confirmationRejected = strcmp(exception.identifier, ...
        'ipm:GaugeLabCLLongRunConfirmation');
end
assert(confirmationRejected, ...
    'ipm:GaugeLabCLTestLongRunGuard', ...
    'Formal mode was not protected by the explicit long-run confirmation.');

invalidCflRejected = false;
try
    ipm_gaugelab_run_q256_cl_tournament(struct('cfl',0.5001));
catch
    invalidCflRejected = true;
end
assert(invalidCflRejected, ...
    'ipm:GaugeLabCLTestCflGuard', ...
    'A c_l tournament CFL above 0.5 was not rejected.');

report = struct('candidateCount',numel(specifications), ...
    'preflightStatus',products.status, ...
    'formalConfirmationRejected',confirmationRejected, ...
    'invalidCflRejected',invalidCflRejected, ...
    'meshStoredNodes',products.meshAudit.storedNodes, ...
    'anchorNodeDistance', ...
        products.meshAudit.transportAnchorNodeDistance);
clear cleanup;
fprintf(['Q256 c_l tournament preflight: %d candidates, ' ...
    'formal guard %d, X=1 node distance %.6g.\n'], ...
    report.candidateCount,report.formalConfirmationRejected, ...
    report.anchorNodeDistance);
end

function remove_temporary_root(pathName)
if isfolder(pathName)
    rmdir(pathName,'s');
end
end
