function products = ipm_gaugelab_run_q256_tournament(userOptions)
%IPM_GAUGELAB_RUN_Q256_TOURNAMENT Run a schema-4 q256 gauge group stage.
%   All candidates start from the same physical initial datum and fixed grid.
%   Only cOmegaGauge changes.  The scaling contract is exact and has no
%   state-dependent feedback.  Results are immutable and saved incrementally.

if nargin < 1
    userOptions = struct();
end
options = resolve_options(userOptions);
laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
experimentDirectory = fullfile(researchDirectory,'experiments');
analysisDirectory = fullfile(researchDirectory,'analysis');
addpath(projectDirectory,experimentDirectory,analysisDirectory, ...
    laboratoryDirectory);

baseOptions = fourth_order_blowup_case(options.baseCaseName,struct( ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'lengthScaleGain',1,'widthGaugeGain',0,'omegaGaugeGain',0, ...
    'travelingWaveGain',0,'omegaGaugeWindowRadius',0.75, ...
    'pointStrainConditionFloor',0.25, ...
    'maxDt',options.maxDt,'cfl',options.cfl, ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'storeSnapshots',false,'verbose',false));
[meshAudit,meshPassed] = audit_shared_mesh(baseOptions,options.meshLimits);
if ~meshPassed
    error('ipm:GaugeLabMeshGate', ...
        'The shared q256 axis fails the frozen tournament mesh gates.');
end
assert_common_contract(baseOptions);

stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
outputParent = fullfile(projectDirectory,'result','verification', ...
    'q256_comega_gauge_tournaments_exact_v4');
if ~isfolder(outputParent)
    mkdir(outputParent);
end
outputDirectory = fullfile(outputParent,['tournament_',stamp]);
if isfolder(outputDirectory)
    error('ipm:GaugeLabOutputCollision', ...
        'Tournament directory already exists: %s',outputDirectory);
end
mkdir(outputDirectory);
summaryFile = fullfile(outputDirectory,'tournament_summary.mat');
manifestFile = fullfile(outputDirectory,'tournament_manifest.jsonl');

specifications = ipm_gaugelab_candidate_specifications( ...
    options.includeNegativeControl);
if ~isempty(options.candidates)
    keep = ismember({specifications.cOmegaGauge},options.candidates);
    specifications = specifications(keep);
end
if isempty(specifications)
    error('ipm:GaugeLabCandidatesEmpty', ...
        'At least one gauge candidate must be selected.');
end

emptyComparison = struct('available',false,'rhoRelativeL2',NaN, ...
    'omegaRelativeL2',NaN,'rhoAbsoluteInf',NaN, ...
    'omegaAbsoluteInf',NaN,'labPeakShift',NaN, ...
    'physicalTimeDifference',NaN, ...
    'physicalRhoXRelativeDifference',NaN, ...
    'wallPeakRelativeDifference',NaN, ...
    'wallWidthRelativeDifference',NaN);
emptyPairwise = struct('available',false, ...
    'method','bidirectional_absolute_worst', ...
    'successfulCompetitorCount',0,'requiredCompetitorCount',2, ...
    'peerCount',0,'requiredPeerCount',1,'peers',{{}}, ...
    'worst',emptyComparison,'passed',false);
emptyPairRecord = struct('peerGauge','','available',false, ...
    'forward',emptyComparison,'reverse',emptyComparison, ...
    'symmetricWorst',emptyComparison,'passed',false, ...
    'errorIdentifier','','errorMessage','');
template = struct('cOmegaGauge','','role','', ...
    'candidateSpecification',struct(),'startedAt',NaT, ...
    'completedAt',NaT,'elapsedSeconds',NaN,'resultFile','', ...
    'assessmentFile','','auditFile','','latestCheckpointFile','', ...
    'stopReason','','errorIdentifier','','errorMessage','', ...
    'failureClass','', ...
    'audit',struct(),'physicalComparison',emptyComparison, ...
    'baselineDisplayComparison',emptyComparison, ...
    'pairwiseComparisons',repmat(emptyPairRecord,0,1), ...
    'pairwisePhysicalCovariance',emptyPairwise, ...
    'physicalCovariancePassed',false,'productionEligible',false, ...
    'artifactDisposition','incomplete','eligible',false);
products = struct('schemaVersion',4, ...
    'kind','q256_comega_gauge_tournament_exact_no_feedback', ...
    'status','running','startedAt',datetime('now','TimeZone','local'), ...
    'completedAt',NaT,'baseCaseName',options.baseCaseName, ...
    'requestedPhysicalFinalTime',options.physicalFinalTime, ...
    'requestedMaximumTimeStep',options.maxDt, ...
    'requestedCfl',options.cfl, ...
    'outputDirectory',outputDirectory,'summaryFile',summaryFile, ...
    'manifestFile',manifestFile,'meshLimits',options.meshLimits, ...
    'meshAudit',meshAudit,'physicalCovarianceLimits', ...
    options.physicalCovarianceLimits,'checkpointCanonicalCadence', ...
    options.checkpointCanonicalCadence,'checkpointEnabled',true, ...
    'checkpointAtExit',true, ...
    'checkpointImmutable',true,'wallClockBudgetSeconds', ...
    options.wallClockBudgetSeconds, ...
    'requiredConfigSchemaVersion',4, ...
    'configurationContract','exact_gauge_no_feedback_v1', ...
    'numericalTuple',frozen_numerical_tuple(),'fixedMesh',true, ...
    'candidateSpecifications',specifications, ...
    'physicalCovarianceMethod','symmetric_pairwise_bidirectional_worst', ...
    'minimumSuccessfulCompetitors',2, ...
    'displayBaselineGauge','gradient_energy', ...
    'legacyPhysicalComparisonUsage','display_only_not_scored', ...
    'baselineDisplay',struct(),'pairwiseEvidence',struct(),'runs', ...
    repmat(template,numel(specifications),1),'ranking',{{}}, ...
    'provisionalWinner','','postprocessingStatus','pending', ...
    'plotFile','','plotError',struct(),'failureSummary',struct(), ...
    'elapsedSeconds',NaN,'wallClockBoundary',false, ...
    'wallClockOverrunSeconds',NaN);
save(summaryFile,'products');
append_manifest(manifestFile,struct('event','tournament_started', ...
    'timestampUtc',stamp,'outputDirectory',outputDirectory, ...
    'schemaVersion',products.schemaVersion, ...
    'requiredConfigSchemaVersion',products.requiredConfigSchemaVersion, ...
    'configurationContract',products.configurationContract, ...
    'numericalTuple',products.numericalTuple,'fixedMesh',true, ...
    'candidateSpecifications',specifications, ...
    'physicalFinalTime',options.physicalFinalTime, ...
    'maxDt',options.maxDt,'cfl',options.cfl, ...
    'meshLimits',options.meshLimits, ...
    'physicalCovarianceLimits',options.physicalCovarianceLimits, ...
    'checkpointCanonicalCadence',options.checkpointCanonicalCadence, ...
    'checkpointEnabled',true,'checkpointAtExit',true, ...
    'checkpointImmutable',true, ...
    'wallClockBudgetSeconds',options.wallClockBudgetSeconds, ...
    'physicalCovarianceMethod',products.physicalCovarianceMethod, ...
    'minimumSuccessfulCompetitors', ...
    products.minimumSuccessfulCompetitors));

contractReference = [];
tournamentClock = tic;
wallClockBoundary = false;
for index = 1:numel(specifications)
    specification = specifications(index);
    if index > 1
        completedDurations = [products.runs.elapsedSeconds];
        completedDurations = completedDurations(isfinite(completedDurations));
        forecast = max(600,1.35*median(completedDurations));
        if toc(tournamentClock)+forecast > options.wallClockBudgetSeconds
            wallClockBoundary = true;
            append_manifest(manifestFile,struct( ...
                'event','tournament_stopped','timestampUtc',utc_stamp(), ...
                'reason','wall_clock_boundary','elapsedSeconds', ...
                toc(tournamentClock),'nextCandidate', ...
                specification.cOmegaGauge,'forecastSeconds',forecast));
            break;
        end
    end
    run = template;
    run.cOmegaGauge = specification.cOmegaGauge;
    run.role = specification.role;
    run.candidateSpecification = specification;
    run.startedAt = datetime('now','TimeZone','local');
    candidateDirectory = fullfile(outputDirectory, ...
        specification.cOmegaGauge);
    mkdir(candidateDirectory);
    requestedResultFile = fullfile(candidateDirectory,'result.mat');
    requestedCheckpointFile = fullfile(candidateDirectory,'checkpoint.mat');
    fprintf('\nGAUGE GROUP %d/%d: %s\n',index,numel(specifications), ...
        specification.cOmegaGauge);
    append_manifest(manifestFile,struct('event','candidate_started', ...
        'timestampUtc',utc_stamp(),'candidate', ...
        specification.cOmegaGauge,'role',specification.role));
    wallClock = tic;
    try
        metadata = struct('gaugeTournament',struct( ...
            'schemaVersion',4,'stage','q256_exact_no_feedback_group', ...
            'candidate',specification.cOmegaGauge, ...
            'baseCaseName',options.baseCaseName, ...
            'onlyAmplitudeGaugeVaried',true, ...
            'candidateSpecification',specification, ...
            'configurationContract', ...
            'exact_gauge_no_feedback_v1', ...
            'physicalCovarianceMethod', ...
            'symmetric_pairwise_bidirectional_worst'));
        opts = fourth_order_blowup_case(options.baseCaseName,struct( ...
            'cOmegaGauge',specification.cOmegaGauge, ...
            'lengthGauge','transport_anchor','transportAnchorX',1, ...
            'lengthScaleGain',1,'widthGaugeGain',0, ...
            'omegaGaugeGain',0,'travelingWaveGain',0, ...
            'omegaGaugeWindowRadius',0.75, ...
            'pointStrainConditionFloor',0.25, ...
            'physicalFinalTime',options.physicalFinalTime, ...
            'maxDt',options.maxDt,'cfl',options.cfl, ...
            'resultFile',requestedResultFile, ...
            'checkpoint',struct('enabled',true, ...
                'file',requestedCheckpointFile,'every', ...
                options.checkpointCanonicalCadence,'atExit',true), ...
            'caseMetadata',metadata,'saveResults',true, ...
            'storeSnapshots',false,'makePlots',false,'livePlot',false, ...
            'writeVideo',false,'verbose',options.verbose));
        if isempty(contractReference)
            contractReference = opts;
        end
        assert_candidate_contract(contractReference,opts);
        result = ipm.solve(opts);
        run.elapsedSeconds = toc(wallClock);
        run.completedAt = datetime('now','TimeZone','local');
        run.resultFile = char(result.metadata.resultFile);
        if isfield(result.metadata,'latestCheckpointFile')
            run.latestCheckpointFile = ...
                char(result.metadata.latestCheckpointFile);
        end
        if isempty(run.latestCheckpointFile) || ...
                ~isfile(run.latestCheckpointFile)
            run.latestCheckpointFile = ...
                latest_immutable_checkpoint(candidateDirectory);
        end
        run.stopReason = result.state.stopReason;
        run.failureClass = classify_stop_reason(run.stopReason);
        assessment = ipm_assess_fourth_order_blowup(result);
        assessmentFile = fullfile(candidateDirectory,'assessment.mat');
        save(assessmentFile,'assessment');
        run.assessmentFile = assessmentFile;
        audit = ipm_gaugelab_assess(result,options.physicalFinalTime);
        auditFile = fullfile(candidateDirectory,'gauge_audit.mat');
        save(auditFile,'audit');
        run.auditFile = auditFile;
        run.audit = audit;
        if strcmp(run.failureClass,'target_reached') && ~audit.hardPassed
            run.failureClass = classify_audit_failure(audit);
        end

        fprintf(['GAUGE RESULT %s: stop=%s class=%s, ' ...
            't/tau %.9g/%.9g, steps %d, ' ...
            'osc cl/cw %.3e/%.3e, drift cl/cw %.3e/%.3e, ' ...
            'pairwise covariance pending\n'], ...
            run.cOmegaGauge,run.stopReason,run.failureClass, ...
            audit.physicalTime,audit.canonicalTau, ...
            audit.steps,audit.canonicalCL.detrendedRelativeRms, ...
            audit.canonicalCOmega.detrendedRelativeRms, ...
            audit.canonicalCL.relativeTrendAcrossWindow, ...
            audit.canonicalCOmega.relativeTrendAcrossWindow);
        candidateEvent = 'candidate_completed';
        if ~strcmp(run.failureClass,'target_reached')
            candidateEvent = 'candidate_stopped';
        end
        append_manifest(manifestFile,struct('event',candidateEvent, ...
            'timestampUtc',utc_stamp(),'candidate',run.cOmegaGauge, ...
            'resultFile',run.resultFile,'checkpointFile', ...
            run.latestCheckpointFile,'hardPassed',audit.hardPassed, ...
            'stopReason',run.stopReason,'failureClass',run.failureClass, ...
            'pairwiseCovariancePending',true));
    catch exception
        run.elapsedSeconds = toc(wallClock);
        run.completedAt = datetime('now','TimeZone','local');
        run.errorIdentifier = exception.identifier;
        run.errorMessage = exception.message;
        run.failureClass = classify_exception(exception);
        run.latestCheckpointFile = ...
            latest_immutable_checkpoint(candidateDirectory);
        fprintf(2,'GAUGE ERROR %s: %s (%s)\n', ...
            run.cOmegaGauge,exception.message,exception.identifier);
        append_manifest(manifestFile,struct('event','candidate_failed', ...
            'timestampUtc',utc_stamp(),'candidate',run.cOmegaGauge, ...
            'identifier',exception.identifier,'message',exception.message, ...
            'failureClass',run.failureClass,'checkpointFile', ...
            run.latestCheckpointFile));
    end
    products.runs(index) = run;
    save(summaryFile,'products','-v7.3');
end

[products.runs,products.baselineDisplay] = ...
    populate_baseline_display_comparisons(products.runs, ...
    products.displayBaselineGauge,emptyComparison);
[products.runs,products.pairwiseEvidence] = ...
    evaluate_pairwise_covariance(products.runs, ...
    options.physicalCovarianceLimits,emptyComparison, ...
    emptyPairwise,emptyPairRecord);
for index = 1:numel(products.runs)
    run = products.runs(index);
    if isempty(run.cOmegaGauge)
        continue;
    end
    append_manifest(manifestFile,struct( ...
        'event','candidate_pairwise_assessed','timestampUtc',utc_stamp(), ...
        'candidate',run.cOmegaGauge, ...
        'successfulCompetitorCount', ...
        run.pairwisePhysicalCovariance.successfulCompetitorCount, ...
        'peerCount',run.pairwisePhysicalCovariance.peerCount, ...
        'physicalCovariancePassed',run.physicalCovariancePassed, ...
        'failureClass',run.failureClass,'eligible',run.eligible));
end

attempted = ~cellfun(@isempty,{products.runs.cOmegaGauge});
failureClasses = {products.runs(attempted).failureClass};
competitive = attempted & ...
    ~strcmp({products.runs.role},'negative_control');
pairwiseInfrastructureFailed = ...
    ~isempty(products.pairwiseEvidence.errors);
products.elapsedSeconds = toc(tournamentClock);
products.wallClockOverrunSeconds = max(0, ...
    products.elapsedSeconds-options.wallClockBudgetSeconds);
if products.wallClockOverrunSeconds > 0
    wallClockBoundary = true;
    append_manifest(manifestFile,struct( ...
        'event','wall_clock_budget_overrun','timestampUtc',utc_stamp(), ...
        'elapsedSeconds',products.elapsedSeconds, ...
        'budgetSeconds',options.wallClockBudgetSeconds, ...
        'overrunSeconds',products.wallClockOverrunSeconds));
end
products.wallClockBoundary = wallClockBoundary;
products.failureSummary = summarize_failures(products.runs,attempted, ...
    wallClockBoundary,pairwiseInfrastructureFailed);
if any(strcmp(failureClasses,'unexpected_error')) || ...
        pairwiseInfrastructureFailed
    [products.ranking,~] = rank_runs(products.runs);
    products.provisionalWinner = '';
    products.status = 'failed_infrastructure';
elseif wallClockBoundary
    [products.ranking,~] = rank_runs(products.runs);
    products.provisionalWinner = '';
    products.status = 'wall_clock_boundary';
elseif products.pairwiseEvidence.successfulCompetitorCount < ...
        products.minimumSuccessfulCompetitors
    products.ranking = {};
    products.provisionalWinner = '';
    products.status = insufficient_competitor_status( ...
        products.failureSummary);
else
    [products.ranking,products.provisionalWinner] = rank_runs(products.runs);
    if products.failureSummary.failureCategoryCount > 1
        products.status = 'completed_with_mixed_failures';
    elseif products.failureSummary.designedSafetyStopCount > 0
        products.status = 'completed_with_designed_safety_stops';
    elseif products.failureSummary.numericalGateFailureCount > 0
        products.status = 'completed_with_numerical_gate_failures';
    elseif products.failureSummary.gaugeFailureCount > 0
        products.status = 'completed_with_gauge_failures';
    elseif any(competitive & ~[products.runs.eligible])
        products.status = 'completed_with_gate_failures';
    else
        products.status = 'completed';
    end
end
products.completedAt = datetime('now','TimeZone','local');
if ~strcmp(products.status,'failed_infrastructure')
    try
        plotFile = fullfile(outputDirectory,'q256_gauge_tournament_rates.png');
        [figureHandle,products.plotFile] = ...
            ipm_gaugelab_plot_tournament(products,plotFile);
        close(figureHandle);
        products.postprocessingStatus = 'completed';
    catch exception
        products.plotFile = '';
        products.plotError = struct('identifier',exception.identifier, ...
            'message',exception.message);
        products.postprocessingStatus = 'failed';
        products.provisionalWinner = '';
    end
else
    products.postprocessingStatus = 'not_run';
end
products.elapsedSeconds = toc(tournamentClock);
products.wallClockOverrunSeconds = max(0, ...
    products.elapsedSeconds-options.wallClockBudgetSeconds);
products.wallClockBoundary = products.wallClockBoundary || ...
    products.wallClockOverrunSeconds > 0;
products.failureSummary.wallClockBoundary = products.wallClockBoundary;
if products.wallClockBoundary && ...
        ~strcmp(products.status,'failed_infrastructure')
    products.status = 'wall_clock_boundary';
    products.provisionalWinner = '';
end
save(summaryFile,'products','-v7.3');
append_manifest(manifestFile,struct('event','tournament_finished', ...
    'timestampUtc',utc_stamp(),'status',products.status, ...
    'postprocessingStatus',products.postprocessingStatus, ...
    'pairwiseEvidenceAvailable',products.pairwiseEvidence.available, ...
    'failureSummary',products.failureSummary, ...
    'elapsedSeconds',products.elapsedSeconds, ...
    'wallClockBoundary',products.wallClockBoundary, ...
    'wallClockOverrunSeconds',products.wallClockOverrunSeconds, ...
    'ranking',{products.ranking}, ...
    'provisionalWinner',products.provisionalWinner));
fprintf('\nGAUGE TOURNAMENT COMPLETE: %s\n',summaryFile);
fprintf('Tournament status: %s\n',products.status);
fprintf(['Run outcomes: target=%d, designed safety=%d, numerical gate=%d, ' ...
    'gauge failure=%d, unexpected crash=%d, not attempted=%d\n'], ...
    products.failureSummary.targetReachedCount, ...
    products.failureSummary.designedSafetyStopCount, ...
    products.failureSummary.numericalGateFailureCount, ...
    products.failureSummary.gaugeFailureCount, ...
    products.failureSummary.unexpectedCrashCount, ...
    products.failureSummary.notAttemptedCount);
fprintf('Provisional q256 group winner: %s\n',products.provisionalWinner);
end

function options = resolve_options(user)
if ~isstruct(user) || ~isscalar(user)
    error('ipm:GaugeLabOptions','Options must be a scalar structure.');
end
options = struct( ...
    'baseCaseName','coordinated_log_F80_R20_c114_quadrant_256', ...
    'physicalFinalTime',0.55,'includeNegativeControl',false, ...
    'maxDt',2e-3,'cfl',0.25,'candidates',{{ ...
        'gradient_energy','anchor_wall_window_l2', ...
        'anchor_wall_template_projection','anchor_bulk_gradient_l2', ...
        'anchor_wall_window_l4'}},'verbose',true);
names = fieldnames(user);
unknown = setdiff(names,fieldnames(options));
if ~isempty(unknown)
    error('ipm:GaugeLabOptionName','Unknown option(s): %s', ...
        strjoin(unknown,', '));
end
for index = 1:numel(names)
    options.(names{index}) = user.(names{index});
end
options.meshLimits = frozen_mesh_limits();
options.physicalCovarianceLimits = frozen_physical_covariance_limits();
options.checkpointCanonicalCadence = frozen_checkpoint_cadence();
options.wallClockBudgetSeconds = frozen_wall_clock_budget();
validateattributes(options.physicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(options.maxDt,{'numeric'}, ...
    {'scalar','real','finite','positive'});
validateattributes(options.cfl,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',0.5});
options.includeNegativeControl = normalize_flag( ...
    options.includeNegativeControl,'includeNegativeControl');
options.verbose = normalize_flag(options.verbose,'verbose');
if isstring(options.baseCaseName)
    if ~isscalar(options.baseCaseName) || ismissing(options.baseCaseName)
        error('ipm:GaugeLabBaseCase','baseCaseName must be scalar text.');
    end
    options.baseCaseName = char(options.baseCaseName);
elseif ~ischar(options.baseCaseName) || ~isrow(options.baseCaseName)
    error('ipm:GaugeLabBaseCase','baseCaseName must be scalar text.');
end
if ~iscellstr(options.candidates)
    error('ipm:GaugeLabCandidates','candidates must be a cell array of text.');
end
options.candidates = cellfun(@char,options.candidates,'UniformOutput',false);
options.candidates = cellfun(@(value)lower(strtrim(value)), ...
    options.candidates,'UniformOutput',false);
if options.includeNegativeControl && ...
        ~any(strcmp(options.candidates,'none'))
    options.candidates{end+1} = 'none';
end
allowed = {ipm_gaugelab_candidate_specifications(true).cOmegaGauge};
unrecognized = setdiff(options.candidates,allowed);
if ~isempty(unrecognized)
    error('ipm:GaugeLabCandidateName','Unknown candidate(s): %s', ...
        strjoin(unrecognized,', '));
end
if any(strcmp(options.candidates,'none')) && ...
        ~logical(options.includeNegativeControl)
    error('ipm:GaugeLabNegativeControlDisabled', ...
        'Set includeNegativeControl=true to request candidate none.');
end
end

function limits = frozen_mesh_limits()
limits = struct('maximumAdjacentCellRatio',1.08, ...
    'maximumLogSpacingCurvature',0.01, ...
    'minimumStencilRcond',1e-9, ...
    'minimumQuadratureWeightRatio',1e-8, ...
    'minimumLocalQuadratureWeightRatio',0.35, ...
    'maximumLocalQuadratureWeightRatio',1.65);
end

function limits = frozen_physical_covariance_limits()
limits = struct('rhoRelativeL2',5e-4, ...
    'omegaRelativeL2',5e-3,'rhoAbsoluteInf',5e-4, ...
    'omegaAbsoluteInf',5e-3, ...
    'physicalRhoXRelativeDifference',5e-3, ...
    'wallPeakRelativeDifference',5e-3, ...
    'wallWidthRelativeDifference',2e-2, ...
    'maximumAbsoluteLabPeakShift',5e-4, ...
    'maximumAbsolutePhysicalTimeDifference',1e-10);
end

function cadence = frozen_checkpoint_cadence()
cadence = 0.20;
end

function seconds = frozen_wall_clock_budget()
seconds = 7200;
end

function tuple = frozen_numerical_tuple()
tuple = struct('spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order');
end

function [audit,passed] = audit_shared_mesh(opts,limits)
quadratureX = ipm.mesh.quadrature(opts.customX);
quadratureY = ipm.mesh.quadrature(opts.customY);
qualityX = ipm.mesh.quality(opts.customX,7,quadratureX);
qualityY = ipm.mesh.quality(opts.customY,7,quadratureY);
audit = struct('storedNodes',[opts.nx,opts.ny], ...
    'firstQuadrantCells',[(opts.nx-1)/2,opts.ny-1], ...
    'x',qualityX,'y',qualityY,'anchorNodeDistance', ...
    min(abs(opts.customX-1)));
passed = opts.nx == 513 && opts.ny == 257 && ...
    all([qualityX.maximumAdjacentCellRatio, ...
        qualityY.maximumAdjacentCellRatio] <= ...
        limits.maximumAdjacentCellRatio) && ...
    all([qualityX.maximumLogSpacingCurvature, ...
        qualityY.maximumLogSpacingCurvature] <= ...
        limits.maximumLogSpacingCurvature) && ...
    all([qualityX.minimumStencilRcond,qualityY.minimumStencilRcond] >= ...
        limits.minimumStencilRcond) && ...
    all([qualityX.minimumQuadratureWeightRatio, ...
        qualityY.minimumQuadratureWeightRatio] >= ...
        limits.minimumQuadratureWeightRatio) && ...
    all([qualityX.minimumQuadratureWeightToControlWidthRatio, ...
        qualityY.minimumQuadratureWeightToControlWidthRatio] >= ...
        limits.minimumLocalQuadratureWeightRatio) && ...
    all([qualityX.maximumQuadratureWeightToControlWidthRatio, ...
        qualityY.maximumQuadratureWeightToControlWidthRatio] <= ...
        limits.maximumLocalQuadratureWeightRatio);
end

function assert_common_contract(opts)
config = ipm.config.resolve(opts);
scaling = config.scaling;
assert(config.schemaVersion == 4, ...
    'ipm:GaugeLabConfigSchema', ...
    'The production group stage requires configuration schema 4.');
assert(config.grid.nx == 513 && config.grid.ny == 257, ...
    'ipm:GaugeLabResolution','The group stage must be q256.');
assert(strcmp(config.transport.spatialDiscretization,'high_order') && ...
    strcmp(config.transport.transportScheme,'weno5_fd') && ...
    strcmp(config.time.timeIntegrator,'ssprk54') && ...
    strcmp(config.remesh.remeshTransferScheme,'high_order'), ...
    'ipm:GaugeLabNumericalTuple','The fourth-order tuple changed.');
assert(strcmp(scaling.lengthGauge,'transport_anchor') && ...
    scaling.transportAnchorX == 1 && scaling.lengthScaleGain == 1 && ...
    scaling.omegaGaugeWindowRadius == 0.75 && ...
    scaling.pointStrainConditionFloor == 0.25, ...
    'ipm:GaugeLabLengthGauge', ...
    ['The fixed X=1 anchor, localized radius, or condition floor ' ...
    'changed.']);
assert(strcmp(scaling.scalingContract,'exact_gauge_no_feedback_v1'), ...
    'ipm:GaugeLabScalingContract', ...
    'The schema-4 exact-no-feedback scaling contract is required.');
assert(scaling.widthGaugeGain == 0 && scaling.omegaGaugeGain == 0 && ...
    scaling.travelingWaveGain == 0, ...
    'ipm:GaugeLabFeedbackGain', ...
    'All optional scaling feedback gains must be exactly zero.');
assert(~config.remesh.initialAnalyticRemesh && ...
    ~config.remesh.adaptiveRemesh, ...
    'ipm:GaugeLabFixedMesh','The group stage must use one frozen mesh.');
retired = retired_adaptive_fields();
assert(~any(isfield(scaling,retired)), ...
    'ipm:GaugeLabRetiredAdaptiveOption', ...
    'The exact schema must not contain retired adaptive scaling options.');
end

function assert_candidate_contract(reference,candidate)
assert_common_contract(candidate);
referenceConfig = ipm.config.resolve(reference);
candidateConfig = ipm.config.resolve(candidate);
domains = {'grid','time','physics','elliptic','transport','scaling', ...
    'remesh','diagnostics'};
referenceConfig.scaling = rmfield( ...
    referenceConfig.scaling,'cOmegaGauge');
candidateConfig.scaling = rmfield( ...
    candidateConfig.scaling,'cOmegaGauge');
for index = 1:numel(domains)
    name = domains{index};
    assert(isequaln(referenceConfig.(name),candidateConfig.(name)), ...
        'ipm:GaugeLabCandidateContract', ...
        'Candidate changed protected configuration domain %s.',name);
end
end

function names = retired_adaptive_fields()
names = {'maxDynamicRate','adaptiveLengthScaling', ...
    'widthExpansionStrength', ...
    'widthContractionOnset','widthContractionStrength', ...
    'maxWidthRateCorrection'};
end

function [runs,display] = populate_baseline_display_comparisons( ...
        runs,baselineGauge,emptyComparison)
errorTemplate = struct('candidate','','identifier','','message','');
display = struct('usage','display_only_not_scored', ...
    'baselineGauge',baselineGauge,'available',false, ...
    'errors',repmat(errorTemplate,0,1));
baselineIndex = find(strcmp({runs.cOmegaGauge},baselineGauge) & ...
    cellfun(@isempty,{runs.errorIdentifier}) & ...
    ~cellfun(@isempty,{runs.resultFile}),1,'first');
if isempty(baselineIndex)
    return;
end
try
    baseline = ipm.output.validate(runs(baselineIndex).resultFile);
catch exception
    displayError = errorTemplate;
    displayError.candidate = baselineGauge;
    displayError.identifier = exception.identifier;
    displayError.message = exception.message;
    display.errors(end+1,1) = displayError;
    return;
end
display.available = true;
for index = 1:numel(runs)
    comparison = emptyComparison;
    comparable = ~isempty(runs(index).cOmegaGauge) && ...
        isempty(runs(index).errorIdentifier) && ...
        ~isempty(runs(index).resultFile);
    if comparable
        try
            if index == baselineIndex
                comparison = zero_comparison(emptyComparison);
            else
                candidate = ipm.output.validate(runs(index).resultFile);
                comparison = directional_physical_comparison( ...
                    baseline,candidate);
            end
        catch exception
            displayError = errorTemplate;
            displayError.candidate = runs(index).cOmegaGauge;
            displayError.identifier = exception.identifier;
            displayError.message = exception.message;
            display.errors(end+1,1) = displayError;
        end
    end
    runs(index).baselineDisplayComparison = comparison;
    % Historical alias retained for old plotting/reporting consumers only.
    runs(index).physicalComparison = comparison;
end
end

function comparison = zero_comparison(emptyComparison)
comparison = emptyComparison;
comparison.available = true;
names = comparison_metric_names();
for index = 1:numel(names)
    comparison.(names{index}) = 0;
end
end

function [runs,evidence] = evaluate_pairwise_covariance( ...
        runs,limits,emptyComparison,emptyPairwise,emptyPairRecord)
successful = false(size(runs));
for index = 1:numel(runs)
    successful(index) = ~isempty(runs(index).cOmegaGauge) && ...
        ~strcmp(runs(index).role,'negative_control') && ...
        isfield(runs(index).candidateSpecification, ...
        'productionCandidate') && ...
        runs(index).candidateSpecification.productionCandidate && ...
        isempty(runs(index).errorIdentifier) && ...
        ~isempty(runs(index).resultFile) && ...
        isfield(runs(index).audit,'hardPassed') && ...
        runs(index).audit.hardPassed;
    runs(index).pairwiseComparisons = repmat(emptyPairRecord,0,1);
    runs(index).pairwisePhysicalCovariance = emptyPairwise;
    runs(index).physicalCovariancePassed = false;
    runs(index).productionEligible = false;
    runs(index).artifactDisposition = 'failed_or_incomplete';
    runs(index).eligible = false;
end
competitors = find(successful);
competitorNames = {runs(competitors).cOmegaGauge};
for index = 1:numel(runs)
    summary = runs(index).pairwisePhysicalCovariance;
    summary.successfulCompetitorCount = numel(competitors);
    summary.requiredPeerCount = max(1,numel(competitors)-1);
    runs(index).pairwisePhysicalCovariance = summary;
end
errorTemplate = struct('candidateA','','candidateB','', ...
    'identifier','','message','');
evidence = struct();
evidence.method = 'symmetric_pairwise_bidirectional_worst';
evidence.successfulCompetitorDefinition = ...
    ['registered_production_candidate_with_hard_audit_passed_' ...
    'completed_without_error'];
evidence.minimumSuccessfulCompetitors = 2;
evidence.successfulCompetitorCount = numel(competitors);
evidence.successfulCompetitors = competitorNames;
evidence.requestedPairCount = ...
    numel(competitors)*(numel(competitors)-1)/2;
evidence.completedPairCount = 0;
evidence.errors = repmat(errorTemplate,0,1);

for firstPosition = 1:(numel(competitors)-1)
    firstIndex = competitors(firstPosition);
    for secondPosition = firstPosition+1:numel(competitors)
        secondIndex = competitors(secondPosition);
        firstRecord = emptyPairRecord;
        secondRecord = emptyPairRecord;
        firstRecord.peerGauge = runs(secondIndex).cOmegaGauge;
        secondRecord.peerGauge = runs(firstIndex).cOmegaGauge;
        try
            firstResult = ipm.output.validate(runs(firstIndex).resultFile);
            secondResult = ipm.output.validate(runs(secondIndex).resultFile);
            forward = directional_physical_comparison( ...
                firstResult,secondResult);
            reverse = directional_physical_comparison( ...
                secondResult,firstResult);
            symmetricWorst = symmetric_worst_comparison( ...
                forward,reverse,emptyComparison);
            pairPassed = covariance_passed(symmetricWorst,limits);
            firstRecord.available = true;
            firstRecord.forward = forward;
            firstRecord.reverse = reverse;
            firstRecord.symmetricWorst = symmetricWorst;
            firstRecord.passed = pairPassed;
            secondRecord.available = true;
            secondRecord.forward = reverse;
            secondRecord.reverse = forward;
            secondRecord.symmetricWorst = symmetricWorst;
            secondRecord.passed = pairPassed;
            evidence.completedPairCount = evidence.completedPairCount+1;
        catch exception
            firstRecord.errorIdentifier = exception.identifier;
            firstRecord.errorMessage = exception.message;
            secondRecord.errorIdentifier = exception.identifier;
            secondRecord.errorMessage = exception.message;
            pairError = errorTemplate;
            pairError.candidateA = runs(firstIndex).cOmegaGauge;
            pairError.candidateB = runs(secondIndex).cOmegaGauge;
            pairError.identifier = exception.identifier;
            pairError.message = exception.message;
            evidence.errors(end+1,1) = pairError;
        end
        runs(firstIndex).pairwiseComparisons(end+1,1) = firstRecord;
        runs(secondIndex).pairwiseComparisons(end+1,1) = secondRecord;
    end
end

for position = 1:numel(competitors)
    index = competitors(position);
    records = runs(index).pairwiseComparisons;
    summary = emptyPairwise;
    summary.successfulCompetitorCount = numel(competitors);
    summary.requiredPeerCount = max(1,numel(competitors)-1);
    summary.peerCount = nnz([records.available]);
    summary.peers = {records.peerGauge};
    summary.available = numel(competitors) >= 2 && ...
        numel(records) == numel(competitors)-1 && ...
        all([records.available]);
    if summary.available
        summary.worst = aggregate_pairwise_worst( ...
            records,emptyComparison);
        summary.passed = covariance_passed(summary.worst,limits);
    end
    runs(index).pairwisePhysicalCovariance = summary;
    runs(index).physicalCovariancePassed = summary.passed;
    if strcmp(runs(index).failureClass,'target_reached') && ...
            summary.available && ~summary.passed
        runs(index).failureClass = 'numerical_gate_failure';
    end
    runs(index).productionEligible = summary.passed && ...
        isfield(runs(index).audit,'productionEligible') && ...
        runs(index).audit.productionEligible;
    runs(index).eligible = runs(index).productionEligible;
    if runs(index).productionEligible
        runs(index).artifactDisposition = 'production_candidate';
    elseif isfield(runs(index).audit,'artifactDisposition') && ...
            strcmp(runs(index).audit.artifactDisposition, ...
            'read_only_history')
        runs(index).artifactDisposition = 'read_only_history';
    end
end
evidence.available = numel(competitors) >= 2 && ...
    isempty(evidence.errors) && ...
    evidence.completedPairCount == evidence.requestedPairCount;
end

function comparison = directional_physical_comparison(reference,candidate)
comparison = ipm.output.compare(reference,candidate,[-2,2,2]);
comparison.available = true;
comparison.physicalTimeDifference = ...
    candidate.state.physicalTime-reference.state.physicalTime;
comparison.physicalRhoXRelativeDifference = relative_difference( ...
    reference.history.common.physicalRhoXInf(end), ...
    candidate.history.common.physicalRhoXInf(end));
end

function worst = symmetric_worst_comparison( ...
        forward,reverse,emptyComparison)
worst = emptyComparison;
worst.available = forward.available && reverse.available;
names = comparison_metric_names();
for index = 1:numel(names)
    name = names{index};
    worst.(name) = max(abs([forward.(name),reverse.(name)]));
end
end

function worst = aggregate_pairwise_worst(records,emptyComparison)
worst = emptyComparison;
worst.available = ~isempty(records) && all([records.available]);
names = comparison_metric_names();
for nameIndex = 1:numel(names)
    name = names{nameIndex};
    values = NaN(numel(records),1);
    for recordIndex = 1:numel(records)
        values(recordIndex) = ...
            records(recordIndex).symmetricWorst.(name);
    end
    worst.(name) = max(values);
end
end

function names = comparison_metric_names()
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','physicalTimeDifference', ...
    'physicalRhoXRelativeDifference','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference'};
end

function passed = covariance_passed(comparison,limits)
passed = comparison.available && ...
    isfinite(comparison.physicalTimeDifference) && ...
    abs(comparison.physicalTimeDifference) <= ...
        limits.maximumAbsolutePhysicalTimeDifference && ...
    isfinite(comparison.labPeakShift) && ...
    abs(comparison.labPeakShift) <= limits.maximumAbsoluteLabPeakShift && ...
    isfinite(comparison.rhoAbsoluteInf) && ...
    comparison.rhoAbsoluteInf <= limits.rhoAbsoluteInf && ...
    isfinite(comparison.omegaAbsoluteInf) && ...
    comparison.omegaAbsoluteInf <= limits.omegaAbsoluteInf && ...
    isfinite(comparison.physicalRhoXRelativeDifference) && ...
    abs(comparison.physicalRhoXRelativeDifference) <= ...
        limits.physicalRhoXRelativeDifference && ...
    comparison.rhoRelativeL2 <= limits.rhoRelativeL2 && ...
    comparison.omegaRelativeL2 <= limits.omegaRelativeL2 && ...
    abs(comparison.wallPeakRelativeDifference) <= ...
        limits.wallPeakRelativeDifference && ...
    abs(comparison.wallWidthRelativeDifference) <= ...
        limits.wallWidthRelativeDifference;
end

function value = relative_difference(reference,candidate)
value = (candidate-reference)/max(abs(reference),eps);
end

function value = normalize_flag(value,name)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && any(value == [0,1]);
if ~(validLogical || validNumeric)
    error('ipm:GaugeLabBoolean','%s must be logical or numeric 0/1.',name);
end
value = logical(value);
end

function classification = classify_exception(exception)
identifier = char(exception.identifier);
if is_gauge_design_identifier(identifier)
    classification = 'designed_gauge_failure';
elseif is_mesh_grid_identifier(identifier)
    classification = 'mesh_grid_gate_failure';
elseif is_numerical_identifier(identifier)
    classification = 'numerical_failure';
else
    classification = 'unexpected_error';
end
end

function classification = classify_stop_reason(stopReason)
stopReason = char(stopReason);
switch stopReason
    case 'physical_final_time'
        classification = 'target_reached';
    case {'gradient_threshold','maximum_principle_violation', ...
            'wall_profile_oscillation','final_time','maximum_steps'}
        classification = 'designed_safety_stop';
    case {'grid_smoothness_failure','grid_resolution_failure', ...
            'time_step_below_minimum','non_finite_solution'}
        classification = 'numerical_gate_failure';
    otherwise
        classification = 'unexpected_error';
end
end

function classification = classify_audit_failure(audit)
reasons = strsplit(char(audit.hardFailureReason),',');
reasons = reasons(~cellfun(@isempty,reasons));
gaugePrefixes = {'candidate_specification','dynamic_isotropic', ...
    'transport_anchor','fixed_localization','schema4_exact_no_feedback', ...
    'exact_no_feedback','retired_adaptive','direct_canonical_clock', ...
    'anchor_','window_','template_','bulk_','amplitude_gauge'};
isGauge = false(size(reasons));
for index = 1:numel(reasons)
    isGauge(index) = any(startsWith(strtrim(reasons{index}), ...
        gaugePrefixes));
end
if ~isempty(isGauge) && all(isGauge)
    classification = 'designed_gauge_failure';
elseif any(isGauge)
    classification = 'mixed_gauge_numerical_gate_failure';
else
    classification = 'numerical_gate_failure';
end
end

function tf = is_gauge_design_identifier(identifier)
prefixes = {'ipm:Degenerate','ipm:OmegaGaugeWindow', ...
    'ipm:OmegaGaugeBulk','ipm:TemplateGauge', ...
    'ipm:AnchorWallGauge','ipm:TransportAnchor', ...
    'ipm:BadCOmegaGauge','ipm:BadLengthGauge', ...
    'ipm:BadScalingContract','ipm:SymmetryLengthGauge', ...
    'ipm:RetiredCOmegaGauge','ipm:OuterAnchorGeometry', ...
    'ipm:GaugeLabUnregisteredGauge','ipm:GaugeLabSupportKind'};
tf = any(startsWith(identifier,prefixes));
end

function tf = is_mesh_grid_identifier(identifier)
prefixes = {'ipm:GaugeLabMeshGate','ipm:GaugeLabResolution', ...
    'ipm:GaugeLabFixedMesh','ipm:AdaptiveAxis', ...
    'ipm:AdaptiveGrid','ipm:AdaptiveLevel', ...
    'ipm:AdaptiveMonitor','ipm:CustomGrid', ...
    'ipm:HighOrderGrid','ipm:HighOrderQuadrature', ...
    'ipm:HighOrderRemesh','ipm:SixthOrderGrid', ...
    'ipm:SixthOrderQuadrature','ipm:FiniteDifference', ...
    'ipm:MinimumLevelPoints','ipm:SymmetryGrid'};
tf = any(startsWith(identifier,prefixes));
end

function tf = is_numerical_identifier(identifier)
prefixes = {'ipm:NonFinite','ipm:HighOrderPoisson', ...
    'ipm:AnisotropicPoisson','ipm:Poisson','ipm:Weno', ...
    'ipm:TimeIntegrator','ipm:BadTimeStep', ...
    'ipm:ConservativeRemesh'};
tf = any(startsWith(identifier,prefixes));
end

function fileName = latest_immutable_checkpoint(candidateDirectory)
fileName = '';
files = dir(fullfile(candidateDirectory,'checkpoint*.mat'));
files = files(~[files.isdir]);
if isempty(files)
    return;
end
newestDate = max([files.datenum]);
indices = find([files.datenum] == newestDate);
if numel(indices) > 1
    names = {files(indices).name};
    [~,nameOrder] = sort(names);
    selected = indices(nameOrder(end));
else
    selected = indices;
end
if isfield(files,'folder') && ~isempty(files(selected).folder)
    fileName = fullfile(files(selected).folder,files(selected).name);
else
    fileName = fullfile(candidateDirectory,files(selected).name);
end
end

function summary = summarize_failures( ...
        runs,attempted,wallClockBoundary,pairwiseInfrastructureFailed)
classes = {runs(attempted).failureClass};
summary = struct( ...
    'targetReachedCount',nnz(strcmp(classes,'target_reached')), ...
    'designedSafetyStopCount', ...
        nnz(strcmp(classes,'designed_safety_stop')), ...
    'numericalGateFailureCount',nnz(ismember(classes,{ ...
        'numerical_gate_failure','mesh_grid_gate_failure', ...
        'numerical_failure','mixed_gauge_numerical_gate_failure'})), ...
    'gaugeFailureCount',nnz(ismember(classes,{ ...
        'designed_gauge_failure','mixed_gauge_numerical_gate_failure'})), ...
    'unexpectedCrashCount',nnz(strcmp(classes,'unexpected_error')), ...
    'attemptedCount',nnz(attempted), ...
    'notAttemptedCount',nnz(~attempted), ...
    'wallClockBoundary',logical(wallClockBoundary), ...
    'pairwiseInfrastructureFailed',logical(pairwiseInfrastructureFailed), ...
    'failureCategoryCount',0,'categories',{{}});
categories = {};
if summary.designedSafetyStopCount > 0
    categories{end+1} = 'designed_safety_stop';
end
if summary.numericalGateFailureCount > 0
    categories{end+1} = 'numerical_gate_failure';
end
if summary.gaugeFailureCount > 0
    categories{end+1} = 'gauge_failure';
end
if summary.unexpectedCrashCount > 0
    categories{end+1} = 'unexpected_crash';
end
summary.failureCategoryCount = numel(categories);
summary.categories = categories;
end

function status = insufficient_competitor_status(summary)
if summary.failureCategoryCount > 1
    status = 'insufficient_successful_competitors_mixed_failures';
elseif summary.designedSafetyStopCount > 0
    status = 'insufficient_successful_competitors_designed_safety_stop';
elseif summary.numericalGateFailureCount > 0
    status = 'insufficient_successful_competitors_numerical_gate_failure';
elseif summary.gaugeFailureCount > 0
    status = 'insufficient_successful_competitors_gauge_failure';
else
    status = 'insufficient_successful_competitors';
end
end

function [ranking,winner] = rank_runs(runs)
eligible = find([runs.eligible]);
if isempty(eligible)
    ranking = {};
    winner = '';
    return;
end
score = NaN(numel(eligible),6);
for row = 1:numel(eligible)
    run = runs(eligible(row));
    score(row,:) = [max(abs([ ...
        run.audit.canonicalCL.relativeTrendAcrossWindow, ...
        run.audit.canonicalCOmega.relativeTrendAcrossWindow])),max( ...
        run.audit.canonicalCL.detrendedRelativeRms, ...
        run.audit.canonicalCOmega.detrendedRelativeRms), ...
        abs(run.audit.canonicalKappa.relativeTrendAcrossWindow), ...
        run.pairwisePhysicalCovariance.worst.physicalRhoXRelativeDifference, ...
        run.pairwisePhysicalCovariance.worst.omegaRelativeL2, ...
        run.elapsedSeconds];
end
if any(~isfinite(score),'all')
    error('ipm:GaugeLabNonfiniteRanking', ...
        'An eligible candidate has a nonfinite tournament score.');
end
[~,order] = sortrows(score,1:size(score,2));
ranking = {runs(eligible(order)).cOmegaGauge};
winner = ranking{1};
end

function append_manifest(fileName,record)
fileId = fopen(fileName,'a');
if fileId < 0
    warning('ipm:GaugeLabManifest','Could not append %s.',fileName);
    return;
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function value = utc_stamp()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
