function report = ipm_gaugelab_test_q512_gauge_cfl_screen()
%IPM_GAUGELAB_TEST_Q512_GAUGE_CFL_SCREEN No-PDE synthetic/preflight test.

laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    laboratoryDirectory);

temporaryRoot = [tempname,'_q512_gauge_cfl_preflight'];
mkdir(temporaryRoot);
cleanup = onCleanup(@()remove_temporary_root(temporaryRoot));
screen = ipm_gaugelab_run_q512_gauge_cfl_screen(struct( ...
    'outputRoot',temporaryRoot,'verbose',false));

assert(screen.schemaVersion == 4 && ...
    strcmp(screen.kind,'q512_fresh_gauge_cfl_short_time_screen') && ...
    strcmp(screen.status,'preflight_complete') && ...
    strcmp(screen.executionMode,'preflight_only') && ...
    screen.freshRootsOnly && ~screen.checkpointInputsAccepted && ...
    screen.pdeSolveCount == 0 && screen.preflightPassed && ...
    ~screen.hardPassed && ~screen.lateTimeEvidence && ...
    ~screen.truncationEvidence && ~screen.gridConvergenceEvidence && ...
    ~screen.blowupEvidence, ...
    'ipm:GaugeLabQ512GaugeCflTestProtocol', ...
    'The schema-4 fresh-root short-screen protocol changed.');

assert(screen.boxHalfWidth == 1e6 && ...
    isequal(screen.domain.x,[-1e6,1e6]) && ...
    isequal(screen.domain.y,[0,1e6]) && ...
    isequal(screen.gauges, ...
        {'wall_omega_quadratic_peak','none'}) && ...
    isequal(screen.cflCandidates,[0.25,0.50]) && ...
    strcmp(screen.nonExecutedReference.gauge,'gradient_energy') && ...
    ~screen.nonExecutedReference.executed && ...
    strcmp(screen.nonExecutedReference.role, ...
        'nonexecuted_negative_control_reference'), ...
    'ipm:GaugeLabQ512GaugeCflTestCandidates', ...
    'The registered box, gauges, CFL pair, or negative control changed.');

requested = screen.requested;
assert(~requested.execute && requested.preflightOnly && ...
    strcmp(requested.defaultExecution,'preflight_only') && ...
    requested.physicalFinalTime == 0.03 && ...
    requested.canonicalFinalTime == 0.05 && ...
    requested.maxDt == 0.004 && requested.maxSteps == 128 && ...
    requested.outputEvery == 1e-10 && ...
    requested.minimumRecordCount == 16 && ...
    requested.outputEvery <= 0.002, ...
    'ipm:GaugeLabQ512GaugeCflTestDefaults', ...
    'The bounded defaults or every-step output cadence changed.');

assert(screen.meshPassed && screen.meshAudit.passed && ...
    screen.meshAudit.anchorIsGridNode && ...
    abs(screen.meshAudit.nearestAnchorNode-1) <= ...
        screen.meshAudit.anchorNodeTolerance && ...
    screen.sharedContractAudit.passed && ...
    screen.syntheticDerivedTelemetryAudit.passed && ...
    strcmp(screen.syntheticDerivedTelemetryAudit.kind, ...
        'no_pde_synthetic_derived_telemetry') && ...
    ~screen.syntheticDerivedTelemetryAudit. ...
        riccatiQuantitiesAppliedToDiscreteHardGate, ...
    'ipm:GaugeLabQ512GaugeCflTestPreflight', ...
    'Mesh, shared-contract, or synthetic telemetry preflight failed.');

assert(numel(screen.runs) == 4 && ...
    all(strcmp({screen.runs.status},'preflight_only')) && ...
    all([screen.runs.freshStart]) && ...
    all(strcmp({screen.runs.restartInput},'none')) && ...
    ~any([screen.runs.checkpointInputAccepted]) && ...
    all([screen.contractAudits.passed]), ...
    'ipm:GaugeLabQ512GaugeCflTestFreshRoots', ...
    'A registered root failed preflight or accepted restart state.');

for index = 1:numel(screen.runs)
    run = screen.runs(index);
    config = run.config;
    gaugeRule = run.gaugeRule;
    assert(config.schemaVersion == 4 && config.frozen && ...
        config.grid.nx == 1025 && config.grid.ny == 513 && ...
        strcmp(config.physics.initialCondition,'degenerate_primitive') && ...
        strcmp(config.scaling.scalingContract, ...
            'exact_gauge_no_feedback_v1') && ...
        strcmp(config.scaling.lengthGauge,'transport_anchor') && ...
        config.scaling.transportAnchorX == 1 && ...
        strcmp(config.scaling.cOmegaGauge,run.gauge) && ...
        config.time.cfl == run.cfl && ...
        strcmp(config.transport.spatialDiscretization,'high_order') && ...
        strcmp(config.transport.transportScheme,'weno5_fd') && ...
        strcmp(config.time.timeIntegrator,'ssprk54') && ...
        strcmp(config.remesh.remeshTransferScheme,'high_order') && ...
        ~config.remesh.initialAnalyticRemesh && ...
        ~config.remesh.adaptiveRemesh && ...
        ~config.output.saveResults && ~config.output.storeSnapshots && ...
        ~isfield(config.output,'checkpoint'), ...
        'ipm:GaugeLabQ512GaugeCflTestRootContract', ...
        'A protected schema, datum, gauge, tuple, or output field changed.');
    assert(gaugeRule.schemaVersion == 2 && ...
        strcmp(gaugeRule.length.name,'transport_anchor') && ...
        gaugeRule.length.anchorX == 1 && ...
        gaugeRule.length.anchorIsGridNode && ...
        strcmp(gaugeRule.amplitude.name,run.gauge), ...
        'ipm:GaugeLabQ512GaugeCflTestGaugeRule', ...
        'A registered root lost its exact serializable gauge rule.');
    if strcmp(run.gauge,'none')
        assert(run.selectedRatePrescribed && ...
            ~run.empiricalRateConvergenceEligible && ...
            strcmp(gaugeRule.amplitude.observable, ...
                'material_density_identity_scale') && ...
            strcmp(gaugeRule.amplitude.evaluation, ...
                ['prescribed_identity_scale_with_counterfactual_' ...
                'peak_diagnostic']), ...
            'ipm:GaugeLabQ512GaugeCflTestNoneProvenance', ...
            'The prescribed identity-gauge provenance was lost.');
    else
        assert(~run.selectedRatePrescribed && ...
            run.empiricalRateConvergenceEligible && ...
            strcmp(gaugeRule.amplitude.observable, ...
                'tracked_wall_omega_quadratic_peak') && ...
            strcmp(gaugeRule.amplitude.evaluation, ...
                'active_nonuniform_three_node_quadratic_vertex'), ...
            'ipm:GaugeLabQ512GaugeCflTestQuadraticProvenance', ...
            'The active quadratic-gauge provenance was changed.');
    end
end

assert(strcmp(screen.rankingHints.status,'not_executed') && ...
    ~screen.rankingHints.orderedWinnerDeclared && ...
    screen.rankingHints.nonePromotionBlocked && ...
    ~screen.rankingHints.noneEmpiricalRateConvergenceEligible && ...
    isempty(screen.cflComparisons) && ...
    isempty(screen.gaugeComparisons), ...
    'ipm:GaugeLabQ512GaugeCflTestNoPromotion', ...
    'Preflight fabricated a ranking or comparison result.');

assert(isfile(screen.summaryFile) && isfile(screen.manifestFile) && ...
    isempty(dir(fullfile(temporaryRoot,'**', ...
        'solver_result_must_not_exist*.mat'))) && ...
    isempty(dir(fullfile(temporaryRoot,'**','checkpoint*.mat'))), ...
    'ipm:GaugeLabQ512GaugeCflTestNoPde', ...
    'Preflight omitted its audit artifacts or wrote solver artifacts.');
loaded = load(screen.summaryFile,'screen');
assert(strcmp(loaded.screen.status,'preflight_complete') && ...
    loaded.screen.preflightPassed && loaded.screen.pdeSolveCount == 0, ...
    'ipm:GaugeLabQ512GaugeCflTestSavedSummary', ...
    'The final preflight summary was not saved.');

conflictRejected = rejects_options(struct( ...
    'execute',true,'preflightOnly',true));
checkpointRejected = rejects_options(struct( ...
    'checkpoint','forbidden.mat'));
mutableGaugesRejected = rejects_options(struct( ...
    'gauges',{{'none'}}));
mutableCflRejected = rejects_options(struct( ...
    'cflCandidates',[0.2,0.5]));
oversizedStepBudgetRejected = rejects_options(struct('maxSteps',129));
assert(conflictRejected && checkpointRejected && ...
    mutableGaugesRejected && mutableCflRejected && ...
    oversizedStepBudgetRejected, ...
    'ipm:GaugeLabQ512GaugeCflTestOptions', ...
    'The screen accepted a contradictory or unregistered option.');

report = struct( ...
    'status',screen.status, ...
    'schemaVersion',screen.schemaVersion, ...
    'preflightPassed',screen.preflightPassed, ...
    'runCount',numel(screen.runs), ...
    'boxHalfWidth',screen.boxHalfWidth, ...
    'syntheticAuditPassed', ...
        screen.syntheticDerivedTelemetryAudit.passed, ...
    'checkpointInputRejected',checkpointRejected, ...
    'mutableGaugesRejected',mutableGaugesRejected, ...
    'mutableCflRejected',mutableCflRejected, ...
    'pdeSolveCount',screen.pdeSolveCount);
clear cleanup;
fprintf(['Q512 gauge x CFL preflight: runs=%d, H=%.0e, ' ...
    'synthetic=%d, PDE solves=%d.\n'],report.runCount, ...
    report.boxHalfWidth,report.syntheticAuditPassed,report.pdeSolveCount);
end

function rejected = rejects_options(options)
rejected = false;
try
    ipm_gaugelab_run_q512_gauge_cfl_screen(options);
catch
    rejected = true;
end
end

function remove_temporary_root(pathName)
if isfolder(pathName)
    rmdir(pathName,'s');
end
end
