function products = ipm_gaugelab_run_q256_cl_tournament(userOptions)
%IPM_GAUGELAB_RUN_Q256_CL_TOURNAMENT Compare registered exact c_l gauges.
%   A bare call runs a bounded q256 smoke test.  The physical-time 0.55
%   formal comparison requires runMode='formal' and confirmLongRun=true.
%   cOmegaGauge is always gradient_energy; no limiter, filtering, feedback,
%   remeshing, or unregistered evolution formula is permitted.

if nargin < 1
    userOptions = struct();
end
options = resolve_options(userOptions);
laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
experimentDirectory = fullfile(researchDirectory,'experiments');
addpath(projectDirectory,experimentDirectory,laboratoryDirectory);
if ~isempty(options.finalizeExistingSummary)
    products = finalize_existing_summary( ...
        options.finalizeExistingSummary,projectDirectory);
    return
end

allSpecifications = ipm_gaugelab_length_candidate_specifications();
specifications = select_specifications(allSpecifications,options);
settings = mode_settings(options.runMode);
settings.cfl = options.cfl;
settings.maxDt = options.maxDt;
if strcmp(options.runMode,'formal') && ~options.preflightOnly && ...
        ~options.confirmLongRun
    error('ipm:GaugeLabCLLongRunConfirmation', ...
        ['The formal six-candidate q256 comparison requires both ' ...
        'runMode=''formal'' and confirmLongRun=true.']);
end

stamp = utc_stamp();
outputParent = options.outputRoot;
if isempty(outputParent)
    outputParent = fullfile(projectDirectory,'result','verification', ...
        'q256_cl_gauge_tournaments_exact_v4');
elseif ~startsWith(outputParent,filesep)
    outputParent = fullfile(projectDirectory,outputParent);
end
if ~isfolder(outputParent)
    mkdir(outputParent);
end
outputDirectory = fullfile(outputParent,sprintf('tournament_%s_%s', ...
    stamp,options.runMode));
if isfolder(outputDirectory)
    error('ipm:GaugeLabCLOutputCollision', ...
        'Tournament directory already exists: %s.',outputDirectory);
end
mkdir(outputDirectory);
summaryFile = fullfile(outputDirectory,'cl_tournament_summary.mat');
manifestFile = fullfile(outputDirectory,'cl_tournament_manifest.jsonl');

[candidateOptions,candidateConfigs] = build_candidate_options( ...
    specifications,settings,options,outputDirectory);
assert_only_length_gauge_varies(candidateConfigs);
[meshAudit,meshPassed] = audit_shared_mesh( ...
    candidateOptions{1},frozen_mesh_limits());
if ~meshPassed
    error('ipm:GaugeLabCLMeshGate', ...
        'The shared q256 axis fails the frozen c_l tournament mesh gates.');
end
covarianceReference = 'transport_anchor';
if ~any(strcmp({specifications.lengthGauge},covarianceReference))
    covarianceReference = specifications(1).lengthGauge;
end

protocol = struct( ...
    'schemaVersion',1, ...
    'kind','q256_cl_gauge_tournament_exact_no_feedback', ...
    'runMode',options.runMode, ...
    'preflightOnly',options.preflightOnly, ...
    'baseCaseName',options.baseCaseName, ...
    'candidateSpecifications',specifications, ...
    'candidateConfigurations',{candidateConfigs}, ...
    'onlyConfigurationVariable','scaling.lengthGauge', ...
    'commonRegisteredParameters',struct( ...
        'transportAnchorX',1, ...
        'lengthGaugeLevels',[0.2,0.6], ...
        'adaptiveLevels',[0.1,0.5,0.9], ...
        'peakTrackingWidthFactor',3), ...
    'cOmegaGauge','gradient_energy', ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'numericalTuple',frozen_numerical_tuple(), ...
    'fixedMesh',true, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'maximumCanonicalTime',settings.finalTime, ...
    'maximumSteps',settings.maxSteps, ...
    'maximumTimeStep',settings.maxDt, ...
    'cfl',settings.cfl, ...
    'outputEvery',settings.outputEvery, ...
    'rateConvergenceWindows',[0.25,0.40,0.60], ...
    'rateConvergenceCoordinate','canonical_tau', ...
    'rateConvergenceDiagnosticOnly',true, ...
    'comparisonWindow',[-2,2,2], ...
    'commonWallWidthDefinition', ...
        'terminal_physical_omega_connected_half_maximum', ...
    'physicalCovarianceMethod', ...
        'all_pairs_bidirectional_absolute_worst', ...
    'physicalCovarianceReference',covarianceReference, ...
    'comparisonEligibility', ...
        'integrity_and_bidirectional_covariance_to_reference', ...
    'minimumSuccessfulCandidates',2, ...
    'physicalCovarianceLimits',frozen_covariance_limits(), ...
    'meshLimits',frozen_mesh_limits(), ...
    'lengthResidualNormalization', ...
        'abs(residual)/max(1,abs(c_lNominal),abs(lengthGaugeStrain),abs(widthRateScale))', ...
    'maximumNormalizedGaugeResidual',1e-10, ...
    'formalRankingOrder',{{ ...
        'worst_c_l_or_c_omega_tail_relative_trend', ...
        'worst_c_l_or_c_omega_nested_window_mean_spread', ...
        'worst_c_l_or_c_omega_detrended_relative_rms', ...
        'worst_bidirectional_physical_covariance_metric', ...
        'elapsed_seconds'}}, ...
    'interpretation', ...
        'screening_only_requires_box_time_grid_and_CFL_refinement');

runTemplate = empty_run();
for index = 1:numel(specifications)
    runTemplate(index,1) = empty_run();
    runTemplate(index).lengthGauge = specifications(index).lengthGauge;
    runTemplate(index).formula = specifications(index).formula;
    runTemplate(index).status = 'registered';
    runTemplate(index).requestedResultFile = ...
        candidateOptions{index}.resultFile;
end
products = struct( ...
    'schemaVersion',1, ...
    'kind',protocol.kind, ...
    'status','registered', ...
    'startedAt',datetime('now','TimeZone','local'), ...
    'completedAt',NaT, ...
    'protocol',protocol, ...
    'meshAudit',meshAudit, ...
    'outputDirectory',outputDirectory, ...
    'summaryFile',summaryFile, ...
    'manifestFile',manifestFile, ...
    'runs',runTemplate, ...
    'pairwiseComparisons',repmat(empty_pair(),0,1), ...
    'successfulCandidates',{{}}, ...
    'comparisonEligibleCandidates',{{}}, ...
    'comparisonExcludedCandidates',{{}}, ...
    'successfulCandidateCount',0, ...
    'sufficientCandidatesComparable',false, ...
    'allCandidatesComparable',false, ...
    'pairwiseHardPassed',false, ...
    'comparisonSubsetHardPassed',false, ...
    'ranking',{{}}, ...
    'rankingEvidence',repmat(empty_ranking_record(),0,1), ...
    'screeningWinner','', ...
    'allRatesProvisionallyStable',false, ...
    'elapsedSeconds',0);
save(summaryFile,'products','-v7.3');
append_manifest(manifestFile,struct( ...
    'event','registered','timestampUtc',stamp, ...
    'kind',protocol.kind,'runMode',options.runMode, ...
    'preflightOnly',options.preflightOnly, ...
    'candidates',{ {specifications.lengthGauge} }, ...
    'cOmegaGauge',protocol.cOmegaGauge, ...
    'scalingContract',protocol.scalingContract, ...
    'onlyConfigurationVariable',protocol.onlyConfigurationVariable, ...
    'physicalFinalTime',protocol.physicalFinalTime, ...
    'maximumSteps',protocol.maximumSteps, ...
    'cfl',protocol.cfl));
if options.preflightOnly
    products.completedAt = datetime('now','TimeZone','local');
    save(summaryFile,'products','-v7.3');
    fprintf('Q256 C_L PREFLIGHT: summary=%s\n',summaryFile);
    return;
end

campaignClock = tic;
results = cell(numel(specifications),1);
products.status = 'running';
save(summaryFile,'products','-v7.3');
for index = 1:numel(specifications)
    specification = specifications(index);
    opts = candidateOptions{index};
    candidateDirectory = fileparts(opts.resultFile);
    if ~isfolder(candidateDirectory)
        mkdir(candidateDirectory);
    end
    run = products.runs(index);
    run.status = 'running';
    products.runs(index) = run;
    save(summaryFile,'products','-v7.3');
    append_manifest(manifestFile,struct( ...
        'event','candidate_started','timestampUtc',utc_stamp(), ...
        'candidate',specification.lengthGauge, ...
        'formula',specification.formula));
    runClock = tic;
    try
        result = ipm.solve(opts);
        elapsed = toc(runClock);
        results{index} = result;
        run = summarize_result(result,specification,settings,elapsed);
        run.resultFile = char(result.metadata.resultFile);
        run.status = 'completed';
        if run.integrityPassed
            run.failureClass = 'target_reached';
        else
            run.failureClass = 'integrity_gate_failure';
        end
        append_manifest(manifestFile,struct( ...
            'event','candidate_completed','timestampUtc',utc_stamp(), ...
            'candidate',specification.lengthGauge, ...
            'resultFile',run.resultFile, ...
            'elapsedSeconds',run.elapsedSeconds, ...
            'acceptedSteps',run.acceptedSteps, ...
            'trustedPrefixRecords',run.trustedPrefixRecords, ...
            'terminalTrusted',run.terminalTrusted, ...
            'exactContractPassed',run.exactContractPassed, ...
            'integrityPassed',run.integrityPassed, ...
            'rateConvergenceValid',run.rateConvergenceValid));
    catch exception
        run.elapsedSeconds = toc(runClock);
        run.status = 'failed';
        run.failureClass = classify_exception(exception);
        run.errorIdentifier = exception.identifier;
        run.errorMessage = exception.message;
        append_manifest(manifestFile,struct( ...
            'event','candidate_failed','timestampUtc',utc_stamp(), ...
            'candidate',specification.lengthGauge, ...
            'identifier',exception.identifier,'message',exception.message));
    end
    products.runs(index) = run;
    save(summaryFile,'products','-v7.3');
end

products.elapsedSeconds = toc(campaignClock);
products = finalize_products(products,results,false);
end

function products = finalize_existing_summary(inputPath,projectDirectory)
summaryFile = inputPath;
if ~startsWith(summaryFile,filesep)
    summaryFile = fullfile(projectDirectory,summaryFile);
end
if isfolder(summaryFile)
    summaryFile = fullfile(summaryFile,'cl_tournament_summary.mat');
end
if ~isfile(summaryFile)
    error('ipm:GaugeLabCLFinalizeMissing', ...
        'Existing tournament summary does not exist: %s.',summaryFile);
end
loaded = load(summaryFile,'products');
if ~isfield(loaded,'products') || ~isstruct(loaded.products) || ...
        ~isscalar(loaded.products)
    error('ipm:GaugeLabCLFinalizeSummary', ...
        'The MAT-file must contain one scalar products structure.');
end
products = loaded.products;
required = {'kind','protocol','runs','summaryFile','manifestFile'};
if ~all(isfield(products,required)) || ...
        ~strcmp(products.kind, ...
        'q256_cl_gauge_tournament_exact_no_feedback') || ...
        ~strcmp(char(products.summaryFile),summaryFile)
    error('ipm:GaugeLabCLFinalizeContract', ...
        'The saved artifact is not this registered q256 c_l tournament.');
end
results = cell(numel(products.runs),1);
for index = 1:numel(products.runs)
    run = products.runs(index);
    if ~strcmp(run.status,'completed')
        continue
    end
    resultFile = run.resultFile;
    if isempty(resultFile)
        resultFile = run.requestedResultFile;
    end
    if ~isfile(resultFile)
        error('ipm:GaugeLabCLFinalizeResultMissing', ...
            'Completed candidate %s has no result file.',run.lengthGauge);
    end
    result = ipm.output.validate(resultFile);
    if ~strcmp(result.config.scaling.lengthGauge,run.lengthGauge)
        error('ipm:GaugeLabCLFinalizeGaugeMismatch', ...
            'Result gauge does not match saved candidate %s.', ...
            run.lengthGauge);
    end
    results{index} = result;
end
append_manifest(products.manifestFile,struct( ...
    'event','tournament_finalize_recovery_started', ...
    'timestampUtc',utc_stamp(), ...
    'summaryFile',summaryFile, ...
    'completedCandidateResults',nnz(~cellfun(@isempty,results))));
elapsed = [products.runs.elapsedSeconds];
elapsed = elapsed(isfinite(elapsed));
products.elapsedSeconds = sum(elapsed);
products = finalize_products(products,results,true);
end

function products = finalize_products(products,results,recovered)
protocol = products.protocol;
[products.runs,products.pairwiseComparisons,successful, ...
    comparisonEligible,products.pairwiseHardPassed, ...
    products.comparisonSubsetHardPassed] = ...
    compare_all_pairs(products.runs,results,protocol);
products.successfulCandidates = {products.runs(successful).lengthGauge};
products.comparisonEligibleCandidates = ...
    {products.runs(comparisonEligible).lengthGauge};
products.comparisonExcludedCandidates = ...
    {products.runs(~comparisonEligible).lengthGauge};
products.successfulCandidateCount = nnz(successful);
products.sufficientCandidatesComparable = ...
    nnz(comparisonEligible) >= protocol.minimumSuccessfulCandidates;
products.allCandidatesComparable = all(comparisonEligible);
if products.comparisonSubsetHardPassed
    [products.ranking,products.rankingEvidence, ...
        products.screeningWinner] = rank_runs( ...
        products.runs,strcmp(protocol.runMode,'formal'));
else
    products.ranking = {};
    products.rankingEvidence = ...
        repmat(empty_ranking_record(),0,1);
    products.screeningWinner = '';
end
validRate = [products.runs.rateConvergenceValid];
stableRate = [products.runs.rateConvergenceProvisionalStable];
products.allRatesProvisionallyStable = ...
    products.sufficientCandidatesComparable && ...
    all(validRate(comparisonEligible)) && ...
    all(stableRate(comparisonEligible));
allCompleted = all(strcmp({products.runs.status},'completed'));
if allCompleted && products.comparisonSubsetHardPassed && ...
        products.allCandidatesComparable
    if strcmp(protocol.runMode,'formal')
        products.status = 'formal_completed';
    else
        products.status = 'smoke_passed';
    end
elseif products.comparisonSubsetHardPassed
    if strcmp(protocol.runMode,'formal')
        products.status = 'formal_completed_with_exclusions';
    else
        products.status = 'smoke_passed_with_exclusions';
    end
elseif allCompleted
    products.status = 'completed_with_gate_failures';
else
    products.status = 'completed_with_candidate_failures';
end
products.completedAt = datetime('now','TimeZone','local');
save(products.summaryFile,'products','-v7.3');
append_manifest(products.manifestFile,struct( ...
    'event','tournament_finished','timestampUtc',utc_stamp(), ...
    'recoveredFinalization',logical(recovered), ...
    'status',products.status, ...
    'successfulCandidateCount',products.successfulCandidateCount, ...
    'successfulCandidates',{products.successfulCandidates}, ...
    'comparisonEligibleCandidates', ...
        {products.comparisonEligibleCandidates}, ...
    'comparisonExcludedCandidates', ...
        {products.comparisonExcludedCandidates}, ...
    'sufficientCandidatesComparable', ...
        products.sufficientCandidatesComparable, ...
    'allCandidatesComparable',products.allCandidatesComparable, ...
    'pairwiseHardPassed',products.pairwiseHardPassed, ...
    'comparisonSubsetHardPassed', ...
        products.comparisonSubsetHardPassed, ...
    'allRatesProvisionallyStable', ...
        products.allRatesProvisionallyStable, ...
    'ranking',{products.ranking}, ...
    'screeningWinner',products.screeningWinner, ...
    'elapsedSeconds',products.elapsedSeconds));
fprintf('Q256 C_L TOURNAMENT: status=%s summary=%s\n', ...
    products.status,products.summaryFile);
end

function options = resolve_options(user)
if ~isstruct(user) || ~isscalar(user)
    error('ipm:GaugeLabCLOptions','Options must be a scalar structure.');
end
options = struct( ...
    'runMode','smoke', ...
    'preflightOnly',false, ...
    'confirmLongRun',false, ...
    'candidates',{{}}, ...
    'baseCaseName','coordinated_log_F80_R20_c114_quadrant_256', ...
    'outputRoot','', ...
    'cfl',0.25, ...
    'maxDt',2e-3, ...
    'finalizeExistingSummary','', ...
    'verbose',false);
unknown = setdiff(fieldnames(user),fieldnames(options),'stable');
if ~isempty(unknown)
    error('ipm:GaugeLabCLOptions','Unknown option(s): %s.', ...
        strjoin(unknown,', '));
end
names = fieldnames(user);
for index = 1:numel(names)
    options.(names{index}) = user.(names{index});
end
options.runMode = normalize_text(options.runMode,'runMode');
if ~any(strcmp(options.runMode,{'smoke','formal'}))
    error('ipm:GaugeLabCLRunMode', ...
        'runMode must be ''smoke'' or ''formal''.');
end
options.preflightOnly = normalize_flag( ...
    options.preflightOnly,'preflightOnly');
options.confirmLongRun = normalize_flag( ...
    options.confirmLongRun,'confirmLongRun');
options.verbose = normalize_flag(options.verbose,'verbose');
options.baseCaseName = normalize_text( ...
    options.baseCaseName,'baseCaseName');
options.outputRoot = normalize_path_text(options.outputRoot,'outputRoot');
options.finalizeExistingSummary = normalize_path_text( ...
    options.finalizeExistingSummary,'finalizeExistingSummary');
validateattributes(options.cfl,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',0.5},mfilename,'cfl');
validateattributes(options.maxDt,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'maxDt');
if ~iscellstr(options.candidates)
    error('ipm:GaugeLabCLCandidates', ...
        'candidates must be a cell array of character vectors.');
end
options.candidates = cellfun( ...
    @(value)lower(strtrim(value)),options.candidates, ...
    'UniformOutput',false);
end

function specifications = select_specifications(allSpecifications,options)
registered = {allSpecifications.lengthGauge};
if isempty(options.candidates)
    specifications = allSpecifications;
else
    unknown = setdiff(options.candidates,registered,'stable');
    if ~isempty(unknown)
        error('ipm:GaugeLabCLCandidateName', ...
            'Unknown length-gauge candidate(s): %s.',strjoin(unknown,', '));
    end
    keep = ismember(registered,options.candidates);
    specifications = allSpecifications(keep);
end
if numel(specifications) < 2
    error('ipm:GaugeLabCLCandidateCount', ...
        'A comparison requires at least two registered candidates.');
end
if strcmp(options.runMode,'formal') && ...
        ~isequal({specifications.lengthGauge},registered)
    error('ipm:GaugeLabCLFormalCandidateSet', ...
        'Formal mode requires the complete preregistered candidate set.');
end
end

function settings = mode_settings(mode)
settings = struct('physicalFinalTime',1e-4,'finalTime',1e-3, ...
    'maxSteps',4,'maxDt',2e-3,'cfl',0.25,'outputEvery',1e-4, ...
    'checkpointEnabled',false,'checkpointCanonicalCadence',Inf);
if strcmp(mode,'formal')
    settings.physicalFinalTime = 0.55;
    settings.finalTime = Inf;
    settings.maxSteps = 1200;
    settings.outputEvery = 5e-3;
    settings.checkpointEnabled = true;
    settings.checkpointCanonicalCadence = 0.20;
end
end

function [candidateOptions,candidateConfigs] = build_candidate_options( ...
        specifications,settings,options,outputDirectory)
candidateOptions = cell(numel(specifications),1);
candidateConfigs = cell(numel(specifications),1);
for index = 1:numel(specifications)
    specification = specifications(index);
    candidateDirectory = fullfile( ...
        outputDirectory,specification.lengthGauge);
    resultFile = fullfile(candidateDirectory,'result.mat');
    if settings.checkpointEnabled
        checkpoint = struct('enabled',true, ...
            'file',fullfile(candidateDirectory,'checkpoint.mat'), ...
            'every',settings.checkpointCanonicalCadence,'atExit',true);
    else
        checkpoint = struct('enabled',false);
    end
    metadata = struct('clGaugeTournament',struct( ...
        'schemaVersion',1,'runMode',options.runMode, ...
        'candidateSpecification',specification, ...
        'onlyConfigurationVariable','scaling.lengthGauge', ...
        'cOmegaGauge','gradient_energy', ...
        'scalingContract','exact_gauge_no_feedback_v1'));
    overrides = struct( ...
        'rescalingMode','dynamic', ...
        'dynamicScaleGeometry','isotropic', ...
        'lengthGauge',specification.lengthGauge, ...
        'transportAnchorX',1, ...
        'lengthGaugeLevels',[0.2,0.6], ...
        'adaptiveLevels',[0.1,0.5,0.9], ...
        'peakTrackingWidthFactor',3, ...
        'cOmegaGauge','gradient_energy', ...
        'lengthScaleGain',1, ...
        'widthGaugeGain',0, ...
        'omegaGaugeGain',0, ...
        'travelingWaveGain',0, ...
        'physicalFinalTime',settings.physicalFinalTime, ...
        'finalTime',settings.finalTime, ...
        'maxSteps',settings.maxSteps, ...
        'maxDt',settings.maxDt, ...
        'cfl',settings.cfl, ...
        'outputEvery',settings.outputEvery, ...
        'initialAnalyticRemesh',false, ...
        'adaptiveRemesh',false, ...
        'checkpoint',checkpoint, ...
        'saveResults',true, ...
        'resultFile',resultFile, ...
        'storeSnapshots',false, ...
        'makePlots',false, ...
        'livePlot',false, ...
        'writeVideo',false, ...
        'verbose',options.verbose, ...
        'caseMetadata',metadata);
    opts = fourth_order_blowup_case(options.baseCaseName,overrides);
    config = ipm.config.resolve(opts);
    assert_exact_config(config,specification);
    candidateOptions{index} = opts;
    candidateConfigs{index} = config;
end
end

function assert_exact_config(config,specification)
scaling = config.scaling;
tuple = frozen_numerical_tuple();
retired = retired_fields();
assert(config.schemaVersion == 4 && ...
    strcmp(scaling.scalingContract,'exact_gauge_no_feedback_v1') && ...
    strcmp(scaling.lengthGauge,specification.lengthGauge) && ...
    strcmp(scaling.cOmegaGauge,'gradient_energy') && ...
    scaling.transportAnchorX == 1 && ...
    isequal(scaling.lengthGaugeLevels,[0.2,0.6]) && ...
    isequal(scaling.adaptiveLevels,[0.1,0.5,0.9]) && ...
    scaling.peakTrackingWidthFactor == 3 && ...
    scaling.lengthScaleGain == 1 && ...
    scaling.widthGaugeGain == 0 && ...
    scaling.omegaGaugeGain == 0 && ...
    scaling.travelingWaveGain == 0 && ...
    isempty(intersect(fieldnames(scaling),retired)) && ...
    strcmp(config.transport.spatialDiscretization, ...
        tuple.spatialDiscretization) && ...
    strcmp(config.transport.transportScheme,tuple.transportScheme) && ...
    strcmp(config.time.timeIntegrator,tuple.timeIntegrator) && ...
    strcmp(config.remesh.remeshTransferScheme, ...
        tuple.remeshTransferScheme) && ...
    ~config.remesh.initialAnalyticRemesh && ...
    ~config.remesh.adaptiveRemesh, ...
    'ipm:GaugeLabCLContract', ...
    'A candidate violates the frozen schema-4 c_l comparison contract.');
end

function assert_only_length_gauge_varies(configs)
domains = {'grid','time','physics','elliptic','transport','scaling', ...
    'remesh','diagnostics'};
reference = configs{1};
reference.scaling = rmfield(reference.scaling,'lengthGauge');
for candidateIndex = 2:numel(configs)
    candidate = configs{candidateIndex};
    candidate.scaling = rmfield(candidate.scaling,'lengthGauge');
    for domainIndex = 1:numel(domains)
        name = domains{domainIndex};
        assert(isequaln(reference.(name),candidate.(name)), ...
            'ipm:GaugeLabCLProtectedConfiguration', ...
            ['Candidate changed protected configuration domain %s; ' ...
            'only scaling.lengthGauge may vary.'],name);
    end
end
end

function run = summarize_result(result,specification,settings,elapsed)
common = result.history.common;
rawTrusted = ipm.output.trustedMask(result);
trusted = ipm.output.continuousTrustedPrefix(rawTrusted);
lastTrusted = find(trusted,1,'last');
if isempty(lastTrusted)
    trustedPhysicalTime = NaN;
    trustedCanonicalTime = NaN;
else
    trustedPhysicalTime = common.physicalTime(lastTrusted);
    trustedCanonicalTime = common.canonicalTau(lastTrusted);
end
[exactPassed,exactEvidence] = exact_result_audit( ...
    result,specification,1e-10);
targetTolerance = 1e-10*max(1,settings.physicalFinalTime);
reachedTarget = strcmp(result.state.stopReason,'physical_final_time') && ...
    abs(result.state.physicalTime-settings.physicalFinalTime) <= ...
        targetTolerance;
rateConvergence = result.fit.gaugeRateConvergence;
run = empty_run();
run.lengthGauge = specification.lengthGauge;
run.formula = specification.formula;
run.status = 'completed';
run.resultFile = '';
run.elapsedSeconds = elapsed;
run.acceptedSteps = result.state.steps;
run.secondsPerStep = elapsed/max(result.state.steps,1);
run.stopReason = result.state.stopReason;
run.physicalTime = result.state.physicalTime;
run.canonicalTime = result.state.canonicalTime;
run.rawTrustedMask = rawTrusted;
run.trustedPrefixMask = trusted;
run.rawTrustedRecords = nnz(rawTrusted);
run.trustedPrefixRecords = nnz(trusted);
run.trustedPhysicalTime = trustedPhysicalTime;
run.trustedCanonicalTime = trustedCanonicalTime;
run.terminalTrusted = ~isempty(trusted) && trusted(end);
run.reachedTarget = reachedTarget;
run.exactContractPassed = exactPassed;
run.exactEvidence = exactEvidence;
run.rateConvergence = rateConvergence;
run.rateConvergenceValid = rateConvergence.valid;
run.rateConvergenceProvisionalStable = ...
    rateConvergence.provisionalStable;
run.terminalCL = common.c_l(end);
run.terminalCOmega = common.c_omega(end);
run.terminalCOmegaOverCL = ...
    guarded_ratio(common.c_omega(end),common.c_l(end));
run.terminalPhysicalRhoXInf = common.physicalRhoXInf(end);
run.integrityPassed = run.terminalTrusted && reachedTarget && exactPassed;
end

function [passed,evidence] = exact_result_audit(result,specification,tolerance)
config = result.config;
common = result.history.common;
gauge = result.history.gauge;
requiredCommon = {'timeSpeed','c_l','canonicalCL','c_omega', ...
    'canonicalCOmega'};
requiredGauge = {'c_lNominal','canonicalCLNominal', ...
    'lengthScaleGain','widthControlMode','widthCorrection', ...
    'canonicalWidthCorrection','lengthGaugeStrain', ...
    'lengthGaugeResidual','widthRateScale','omegaGaugeResidual'};
if strcmp(specification.lengthGauge,'omega_peak_location')
    requiredGauge = [requiredGauge,{ ...
        'peakLocationRhoXX','peakLocationRhoXXScale', ...
        'peakLocationPhaseDefect','peakLocationResponseCondition', ...
        'peakLocationFullPhaseResidual', ...
        'peakLocationNormalizedFullPhaseResidual'}];
elseif strcmp(specification.lengthGauge,'wall_density_width')
    requiredGauge = [requiredGauge,{ ...
        'wallDensityLowerSlope','wallDensityUpperSlope', ...
        'wallDensityLowerCondition','wallDensityUpperCondition', ...
        'wallDensityLowerBracket','wallDensityUpperBracket'}];
end
historyComplete = has_finite_equal_length_fields( ...
    common,requiredCommon,numel(common.c_l)) && ...
    has_finite_equal_length_fields(gauge,requiredGauge,numel(common.c_l));
if historyComplete
    denominator = max([ones(numel(common.c_l),1), ...
        abs(gauge.c_lNominal(:)),abs(gauge.lengthGaugeStrain(:)), ...
        abs(gauge.widthRateScale(:))],[],2);
    normalizedLengthResidual = ...
        abs(gauge.lengthGaugeResidual(:))./denominator;
    maximumLengthResidual = max(normalizedLengthResidual);
    maximumOmegaResidual = max(abs(gauge.omegaGaugeResidual(:)));
    rateIdentities = isequal(common.c_l,common.canonicalCL) && ...
        isequal(common.c_omega,common.canonicalCOmega) && ...
        isequal(common.c_l,gauge.c_lNominal) && ...
        isequal(common.canonicalCL,gauge.canonicalCLNominal);
    noFeedbackHistory = all(gauge.lengthScaleGain == 1) && ...
        all(gauge.widthControlMode == 0) && ...
        all(gauge.widthCorrection == 0) && ...
        all(gauge.canonicalWidthCorrection == 0);
else
    maximumLengthResidual = Inf;
    maximumOmegaResidual = Inf;
    rateIdentities = false;
    noFeedbackHistory = false;
end
retiredAbsent = isempty(intersect( ...
    fieldnames(config.scaling),retired_fields()));
metadataContract = isfield(result.metadata,'gaugeContract') && ...
    isfield(result.metadata.gaugeContract,'length') && ...
    isfield(result.metadata.gaugeContract,'amplitude') && ...
    isfield(result.metadata.gaugeContract,'feedback') && ...
    strcmp(result.metadata.gaugeContract.length.name, ...
        specification.lengthGauge) && ...
    strcmp(result.metadata.gaugeContract.length.formula, ...
        specification.formula) && ...
    strcmp(result.metadata.gaugeContract.length.observable, ...
        specification.observable) && ...
    strcmp(result.metadata.gaugeContract.length.evaluation, ...
        specification.evaluation) && ...
    isfield(result.metadata.gaugeContract.length, ...
        'registeredParameters') && ...
    isequaln(orderfields( ...
        result.metadata.gaugeContract.length.registeredParameters), ...
        orderfields(specification.registeredParameters)) && ...
    strcmp(result.metadata.gaugeContract.amplitude.name, ...
        'gradient_energy') && ...
    result.metadata.gaugeContract.timeSpeed == 1 && ...
    strcmp(result.metadata.gaugeContract.feedback.rateLimiter,'absent');
configContract = config.schemaVersion == 4 && ...
    strcmp(config.scaling.scalingContract, ...
        'exact_gauge_no_feedback_v1') && ...
    strcmp(config.scaling.lengthGauge,specification.lengthGauge) && ...
    strcmp(config.scaling.cOmegaGauge,'gradient_energy') && ...
    config.scaling.lengthScaleGain == 1 && ...
    config.scaling.widthGaugeGain == 0 && ...
    config.scaling.omegaGaugeGain == 0 && ...
    config.scaling.travelingWaveGain == 0 && retiredAbsent;
directClock = historyComplete && all(common.timeSpeed == 1);
fixedMesh = result.grid.remeshCount == 0 && ...
    all(result.history.mesh.remeshCount == 0);
maximumPeakPhaseDefect = NaN;
maximumNormalizedFullPhaseResidual = NaN;
minimumPeakResponseCondition = NaN;
minimumDensityCrossingCondition = NaN;
if historyComplete && strcmp( ...
        specification.lengthGauge,'omega_peak_location')
    maximumPeakPhaseDefect = max(gauge.peakLocationPhaseDefect);
    maximumNormalizedFullPhaseResidual = max(abs( ...
        gauge.peakLocationNormalizedFullPhaseResidual));
    minimumPeakResponseCondition = min( ...
        gauge.peakLocationResponseCondition);
elseif historyComplete && strcmp( ...
        specification.lengthGauge,'wall_density_width')
    minimumDensityCrossingCondition = min([ ...
        gauge.wallDensityLowerCondition, ...
        gauge.wallDensityUpperCondition],[],'all');
end
passed = configContract && metadataContract && historyComplete && ...
    directClock && rateIdentities && noFeedbackHistory && fixedMesh && ...
    maximumLengthResidual <= tolerance && ...
    maximumOmegaResidual <= tolerance;
evidence = struct( ...
    'configContract',configContract, ...
    'metadataFormulaMatchesRegistry',metadataContract, ...
    'historyComplete',historyComplete, ...
    'directCanonicalClock',directClock, ...
    'directCanonicalRateIdentities',rateIdentities, ...
    'noFeedbackHistory',noFeedbackHistory, ...
    'retiredFieldsAbsent',retiredAbsent, ...
    'fixedMesh',fixedMesh, ...
    'maximumNormalizedLengthGaugeResidual',maximumLengthResidual, ...
    'maximumOmegaGaugeResidual',maximumOmegaResidual, ...
    'maximumPeakLocationPhaseDefect',maximumPeakPhaseDefect, ...
    'maximumNormalizedFullPeakPhaseResidual', ...
        maximumNormalizedFullPhaseResidual, ...
    'minimumPeakLocationResponseCondition', ...
        minimumPeakResponseCondition, ...
    'minimumWallDensityCrossingCondition', ...
        minimumDensityCrossingCondition, ...
    'residualTolerance',tolerance);
end

function complete = has_finite_equal_length_fields(value,names,count)
complete = isstruct(value) && isscalar(value);
for index = 1:numel(names)
    name = names{index};
    complete = complete && isfield(value,name) && ...
        isnumeric(value.(name)) && isreal(value.(name)) && ...
        numel(value.(name)) == count && all(isfinite(value.(name)));
end
end

function [runs,pairs,successful,comparisonEligible,allPassed,subsetPassed] = ...
        compare_all_pairs(runs,results,protocol)
successful = [runs.integrityPassed] & ~cellfun(@isempty,results');
competitors = find(successful);
sufficient = numel(competitors) >= protocol.minimumSuccessfulCandidates;
pairs = repmat(empty_pair(),0,1);
peerRecords = cell(numel(runs),1);
for index = 1:numel(peerRecords)
    peerRecords{index} = repmat(empty_pair(),0,1);
end
for firstPosition = 1:numel(competitors)-1
    first = competitors(firstPosition);
    for secondPosition = firstPosition+1:numel(competitors)
        second = competitors(secondPosition);
        pair = empty_pair();
        pair.candidateA = runs(first).lengthGauge;
        pair.candidateB = runs(second).lengthGauge;
        try
            pair.forward = directional_comparison( ...
                results{first},results{second}, ...
                protocol.comparisonWindow);
            pair.reverse = directional_comparison( ...
                results{second},results{first}, ...
                protocol.comparisonWindow);
            pair.symmetricWorst = symmetric_worst( ...
                pair.forward,pair.reverse);
            pair.available = true;
            pair.passed = covariance_passed( ...
                pair.symmetricWorst, ...
                protocol.physicalCovarianceLimits);
        catch exception
            pair.errorIdentifier = exception.identifier;
            pair.errorMessage = exception.message;
        end
        pairs(end+1,1) = pair; %#ok<AGROW>
        peerRecords{first}(end+1,1) = pair;
        peerRecords{second}(end+1,1) = reverse_pair(pair);
    end
end
allPassed = sufficient && ~isempty(pairs) && ...
    all([pairs.available]) && all([pairs.passed]);
reference = find(strcmp({runs.lengthGauge}, ...
    protocol.physicalCovarianceReference),1,'first');
if isempty(reference) || ~successful(reference)
    error('ipm:GaugeLabCLCovarianceReference', ...
        'The preregistered physical-covariance reference is unavailable.');
end
comparisonEligible = false(size(successful));
for index = 1:numel(runs)
    runs(index).pairwiseComparisons = peerRecords{index};
    if isempty(peerRecords{index})
        runs(index).physicalCovariancePassed = false;
        runs(index).worstPhysicalCovarianceMetric = NaN;
        runs(index).worstAllPeerPhysicalCovarianceMetric = NaN;
    else
        available = [peerRecords{index}.available];
        if index == reference
            runs(index).physicalCovariancePassed = successful(index);
        else
            againstReference = strcmp( ...
                {peerRecords{index}.candidateB}, ...
                runs(reference).lengthGauge);
            runs(index).physicalCovariancePassed = ...
                successful(index) && nnz(againstReference) == 1 && ...
                peerRecords{index}(againstReference).available && ...
                peerRecords{index}(againstReference).passed;
        end
        if all(available)
            values = arrayfun(@(pair)covariance_scalar( ...
                pair.symmetricWorst,protocol.physicalCovarianceLimits), ...
                peerRecords{index});
            runs(index).worstAllPeerPhysicalCovarianceMetric = max(values);
        end
    end
    comparisonEligible(index) = runs(index).integrityPassed && ...
        runs(index).physicalCovariancePassed;
end
eligibleNames = {runs(comparisonEligible).lengthGauge};
for index = 1:numel(runs)
    runs(index).worstPhysicalCovarianceMetric = NaN;
    if comparisonEligible(index)
        withinSubset = ismember( ...
            {peerRecords{index}.candidateB},eligibleNames);
        subsetPeers = peerRecords{index}(withinSubset);
        if ~isempty(subsetPeers) && all([subsetPeers.available])
            values = arrayfun(@(pair)covariance_scalar( ...
                pair.symmetricWorst,protocol.physicalCovarianceLimits), ...
                subsetPeers);
            runs(index).worstPhysicalCovarianceMetric = max(values);
        end
    end
    runs(index).rankingEligible = comparisonEligible(index) && ...
        runs(index).rateConvergenceValid;
end
eligiblePairs = arrayfun(@(pair) ...
    any(strcmp(pair.candidateA,{runs(comparisonEligible).lengthGauge})) && ...
    any(strcmp(pair.candidateB,{runs(comparisonEligible).lengthGauge})), ...
    pairs);
subsetPassed = nnz(comparisonEligible) >= ...
    protocol.minimumSuccessfulCandidates && any(eligiblePairs) && ...
    all([pairs(eligiblePairs).available]) && ...
    all([pairs(eligiblePairs).passed]);
end

function comparison = directional_comparison(reference,candidate,window)
comparison = ipm.output.compare(reference,candidate,window);
comparison.available = true;
comparison.physicalTimeDifference = ...
    candidate.state.physicalTime-reference.state.physicalTime;
comparison.physicalRhoXRelativeDifference = relative_difference( ...
    reference.history.common.physicalRhoXInf(end), ...
    candidate.history.common.physicalRhoXInf(end));
referenceWidth = common_wall_half_maximum_width(reference);
candidateWidth = common_wall_half_maximum_width(candidate);
% output.compare uses the run's tracked reporting level.  That level is
% deliberately 0.9 for wall_omega_width and 0.5 for the other c_l gauges,
% so replace it here with one gauge-independent terminal physical width.
comparison.wallWidthRelativeDifference = relative_difference( ...
    referenceWidth,candidateWidth);
comparison.wallWidthDefinition = ...
    'terminal_physical_omega_connected_half_maximum';
end

function width = common_wall_half_maximum_width(result)
x = result.grid.physicalX(:)';
wall = result.physical.omega(1,:);
[peak,peakIndex] = max(wall);
if ~isfinite(peak) || peak <= 0
    error('ipm:GaugeLabCLWallWidth', ...
        'The terminal physical wall omega has no positive finite peak.');
end
threshold = 0.5*peak;
left = peakIndex;
while left > 1 && wall(left-1) >= threshold
    left = left-1;
end
right = peakIndex;
while right < numel(wall) && wall(right+1) >= threshold
    right = right+1;
end
if left == 1 || right == numel(wall)
    error('ipm:GaugeLabCLWallWidth', ...
        'The terminal physical wall-omega half-maximum component is not interior.');
end
leftCrossing = linear_crossing( ...
    x(left-1:left),wall(left-1:left),threshold);
rightCrossing = linear_crossing( ...
    x(right:right+1),wall(right:right+1),threshold);
width = rightCrossing-leftCrossing;
if ~isfinite(width) || width <= 0
    error('ipm:GaugeLabCLWallWidth', ...
        'The common terminal wall-omega half-maximum width is invalid.');
end
end

function crossing = linear_crossing(x,values,threshold)
difference = values(2)-values(1);
if difference == 0
    error('ipm:GaugeLabCLWallWidth', ...
        'A terminal wall-omega half-maximum crossing has zero slope.');
end
fraction = (threshold-values(1))/difference;
crossing = x(1)+fraction*(x(2)-x(1));
end

function worst = symmetric_worst(forward,reverse)
worst = struct('available',forward.available && reverse.available);
names = covariance_metric_names();
for index = 1:numel(names)
    name = names{index};
    worst.(name) = max(abs([forward.(name),reverse.(name)]));
end
end

function passed = covariance_passed(comparison,limits)
passed = comparison.available && ...
    comparison.rhoRelativeL2 <= limits.rhoRelativeL2 && ...
    comparison.omegaRelativeL2 <= limits.omegaRelativeL2 && ...
    comparison.rhoAbsoluteInf <= limits.rhoAbsoluteInf && ...
    comparison.omegaAbsoluteInf <= limits.omegaAbsoluteInf && ...
    comparison.labPeakShift <= limits.maximumAbsoluteLabPeakShift && ...
    comparison.physicalTimeDifference <= ...
        limits.maximumAbsolutePhysicalTimeDifference && ...
    comparison.physicalRhoXRelativeDifference <= ...
        limits.physicalRhoXRelativeDifference && ...
    comparison.wallPeakRelativeDifference <= ...
        limits.wallPeakRelativeDifference && ...
    comparison.wallWidthRelativeDifference <= ...
        limits.wallWidthRelativeDifference;
end

function value = covariance_scalar(comparison,limits)
values = [ ...
    abs(comparison.rhoRelativeL2)/limits.rhoRelativeL2, ...
    abs(comparison.omegaRelativeL2)/limits.omegaRelativeL2, ...
    abs(comparison.rhoAbsoluteInf)/limits.rhoAbsoluteInf, ...
    abs(comparison.omegaAbsoluteInf)/limits.omegaAbsoluteInf, ...
    abs(comparison.labPeakShift)/limits.maximumAbsoluteLabPeakShift, ...
    abs(comparison.physicalTimeDifference)/ ...
        limits.maximumAbsolutePhysicalTimeDifference, ...
    abs(comparison.physicalRhoXRelativeDifference)/ ...
        limits.physicalRhoXRelativeDifference, ...
    abs(comparison.wallPeakRelativeDifference)/ ...
        limits.wallPeakRelativeDifference, ...
    abs(comparison.wallWidthRelativeDifference)/ ...
        limits.wallWidthRelativeDifference];
value = max(values);
end

function names = covariance_metric_names()
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','physicalTimeDifference', ...
    'physicalRhoXRelativeDifference','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference'};
end

function reversed = reverse_pair(pair)
reversed = pair;
reversed.candidateA = pair.candidateB;
reversed.candidateB = pair.candidateA;
reversed.forward = pair.reverse;
reversed.reverse = pair.forward;
end

function [ranking,evidence,winner] = rank_runs(runs,isFormal)
ranking = {};
evidence = repmat(empty_ranking_record(),0,1);
winner = '';
rankingEligible = reshape([runs.rankingEligible],[],1);
finiteEvidence = arrayfun(@finite_ranking_evidence,runs(:));
eligible = find(rankingEligible & finiteEvidence);
if ~isFormal || numel(eligible) < 2
    return;
end
score = NaN(numel(eligible),5);
records = repmat(empty_ranking_record(),numel(eligible),1);
for position = 1:numel(eligible)
    index = eligible(position);
    diagnostic = runs(index).rateConvergence;
    cL = diagnostic.seriesSummary.cL;
    cOmega = diagnostic.seriesSummary.cOmega;
    worstTrend = max([cL.maximumAbsoluteRelativeTrend, ...
        cOmega.maximumAbsoluteRelativeTrend]);
    worstMeanSpread = max([cL.relativeWindowMeanSpread, ...
        cOmega.relativeWindowMeanSpread]);
    worstRms = max([cL.maximumRelativeDetrendedRms, ...
        cOmega.maximumRelativeDetrendedRms]);
    score(position,:) = [worstTrend,worstMeanSpread,worstRms, ...
        runs(index).worstPhysicalCovarianceMetric, ...
        runs(index).elapsedSeconds];
    records(position) = struct( ...
        'lengthGauge',runs(index).lengthGauge, ...
        'worstRateRelativeTrend',worstTrend, ...
        'worstNestedWindowMeanSpread',worstMeanSpread, ...
        'worstDetrendedRelativeRms',worstRms, ...
        'worstPhysicalCovarianceMetric', ...
            runs(index).worstPhysicalCovarianceMetric, ...
        'elapsedSeconds',runs(index).elapsedSeconds, ...
        'provisionalStable', ...
            runs(index).rateConvergenceProvisionalStable);
end
[~,order] = sortrows(score,[1,2,3,4,5]);
evidence = records(order);
ranking = {evidence.lengthGauge};
winner = ranking{1};
end

function finite = finite_ranking_evidence(run)
finite = false;
diagnostic = run.rateConvergence;
if ~isstruct(diagnostic) || ...
        ~isfield(diagnostic,'seriesSummary') || ...
        ~all(isfield(diagnostic.seriesSummary,{'cL','cOmega'}))
    return;
end
cL = diagnostic.seriesSummary.cL;
cOmega = diagnostic.seriesSummary.cOmega;
required = {'maximumAbsoluteRelativeTrend', ...
    'relativeWindowMeanSpread','maximumRelativeDetrendedRms'};
if ~all(isfield(cL,required)) || ~all(isfield(cOmega,required))
    return;
end
values = [cL.maximumAbsoluteRelativeTrend, ...
    cOmega.maximumAbsoluteRelativeTrend, ...
    cL.relativeWindowMeanSpread,cOmega.relativeWindowMeanSpread, ...
    cL.maximumRelativeDetrendedRms,cOmega.maximumRelativeDetrendedRms, ...
    run.worstPhysicalCovarianceMetric,run.elapsedSeconds];
finite = all(isfinite(values));
end

function [audit,passed] = audit_shared_mesh(opts,limits)
quadratureX = ipm.mesh.quadrature(opts.customX);
quadratureY = ipm.mesh.quadrature(opts.customY);
qualityX = ipm.mesh.quality(opts.customX,7,quadratureX);
qualityY = ipm.mesh.quality(opts.customY,7,quadratureY);
audit = struct('storedNodes',[opts.nx,opts.ny], ...
    'firstQuadrantCells',[(opts.nx-1)/2,opts.ny-1], ...
    'x',qualityX,'y',qualityY, ...
    'transportAnchorNodeDistance',min(abs(opts.customX-1)));
passed = opts.nx == 513 && opts.ny == 257 && ...
    all([qualityX.maximumAdjacentCellRatio, ...
        qualityY.maximumAdjacentCellRatio] <= ...
        limits.maximumAdjacentCellRatio) && ...
    all([qualityX.maximumLogSpacingCurvature, ...
        qualityY.maximumLogSpacingCurvature] <= ...
        limits.maximumLogSpacingCurvature) && ...
    all([qualityX.minimumStencilRcond, ...
        qualityY.minimumStencilRcond] >= limits.minimumStencilRcond) && ...
    all([qualityX.minimumQuadratureWeightRatio, ...
        qualityY.minimumQuadratureWeightRatio] >= ...
        limits.minimumQuadratureWeightRatio) && ...
    all([qualityX.minimumQuadratureWeightToControlWidthRatio, ...
        qualityY.minimumQuadratureWeightToControlWidthRatio] >= ...
        limits.minimumLocalQuadratureWeightRatio) && ...
    all([qualityX.maximumQuadratureWeightToControlWidthRatio, ...
        qualityY.maximumQuadratureWeightToControlWidthRatio] <= ...
        limits.maximumLocalQuadratureWeightRatio);
end

function limits = frozen_mesh_limits()
limits = struct('maximumAdjacentCellRatio',1.08, ...
    'maximumLogSpacingCurvature',0.01, ...
    'minimumStencilRcond',1e-9, ...
    'minimumQuadratureWeightRatio',1e-8, ...
    'minimumLocalQuadratureWeightRatio',0.35, ...
    'maximumLocalQuadratureWeightRatio',1.65);
end

function limits = frozen_covariance_limits()
limits = struct('rhoRelativeL2',5e-4, ...
    'omegaRelativeL2',5e-3, ...
    'rhoAbsoluteInf',5e-4, ...
    'omegaAbsoluteInf',5e-3, ...
    'physicalRhoXRelativeDifference',5e-3, ...
    'wallPeakRelativeDifference',5e-3, ...
    'wallWidthRelativeDifference',2e-2, ...
    'maximumAbsoluteLabPeakShift',5e-4, ...
    'maximumAbsolutePhysicalTimeDifference',1e-10);
end

function tuple = frozen_numerical_tuple()
tuple = struct('spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order');
end

function names = retired_fields()
names = {'maxDynamicRate','adaptiveGain','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
end

function run = empty_run()
run = struct('lengthGauge','','formula','','status','unregistered', ...
    'requestedResultFile','','resultFile','', ...
    'elapsedSeconds',NaN,'acceptedSteps',NaN,'secondsPerStep',NaN, ...
    'stopReason','','failureClass','','physicalTime',NaN,'canonicalTime',NaN, ...
    'rawTrustedMask',false(0,1),'trustedPrefixMask',false(0,1), ...
    'rawTrustedRecords',0,'trustedPrefixRecords',0, ...
    'trustedPhysicalTime',NaN,'trustedCanonicalTime',NaN, ...
    'terminalTrusted',false,'reachedTarget',false, ...
    'exactContractPassed',false,'exactEvidence',struct(), ...
    'rateConvergence',struct(),'rateConvergenceValid',false, ...
    'rateConvergenceProvisionalStable',false, ...
    'terminalCL',NaN,'terminalCOmega',NaN, ...
    'terminalCOmegaOverCL',NaN,'terminalPhysicalRhoXInf',NaN, ...
    'integrityPassed',false, ...
    'pairwiseComparisons',repmat(empty_pair(),0,1), ...
    'physicalCovariancePassed',false, ...
    'worstPhysicalCovarianceMetric',NaN, ...
    'worstAllPeerPhysicalCovarianceMetric',NaN, ...
    'rankingEligible',false, ...
    'errorIdentifier','','errorMessage','');
end

function pair = empty_pair()
pair = struct('candidateA','','candidateB','', ...
    'available',false,'forward',struct(),'reverse',struct(), ...
    'symmetricWorst',struct(),'passed',false, ...
    'errorIdentifier','','errorMessage','');
end

function record = empty_ranking_record()
record = struct('lengthGauge','', ...
    'worstRateRelativeTrend',NaN, ...
    'worstNestedWindowMeanSpread',NaN, ...
    'worstDetrendedRelativeRms',NaN, ...
    'worstPhysicalCovarianceMetric',NaN, ...
    'elapsedSeconds',NaN,'provisionalStable',false);
end

function value = guarded_ratio(numerator,denominator)
scale = max([1,abs(numerator),abs(denominator)]);
if abs(denominator) <= 100*eps(scale)
    value = NaN;
else
    value = numerator/denominator;
end
end

function value = relative_difference(reference,candidate)
value = (candidate-reference)/max(abs(reference),eps);
end

function classification = classify_exception(exception)
identifier = char(exception.identifier);
if any(startsWith(identifier,{'ipm:DegenerateLengthGauge', ...
        'ipm:BadLengthGauge','ipm:SymmetryLengthGauge'}))
    classification = 'designed_gauge_failure';
else
    classification = 'unexpected_error';
end
end

function value = normalize_flag(value,name)
validLogical = islogical(value) && isscalar(value);
validNumeric = isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && any(value == [0,1]);
if ~(validLogical || validNumeric)
    error('ipm:GaugeLabCLBoolean', ...
        '%s must be scalar logical or numeric 0/1.',name);
end
value = logical(value);
end

function value = normalize_text(value,name)
if isstring(value)
    if ~isscalar(value) || ismissing(value)
        error('ipm:GaugeLabCLText','%s must be scalar text.',name);
    end
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabCLText','%s must be scalar text.',name);
end
value = lower(strtrim(value));
end

function value = normalize_path_text(value,name)
if isstring(value)
    if ~isscalar(value) || ismissing(value)
        error('ipm:GaugeLabCLText','%s must be scalar text.',name);
    end
    value = char(value);
end
if ~ischar(value) || (~isempty(value) && ~isrow(value))
    error('ipm:GaugeLabCLText','%s must be scalar text.',name);
end
value = strtrim(value);
end

function append_manifest(fileName,entry)
file = fopen(fileName,'a');
if file < 0
    error('ipm:GaugeLabCLManifest', ...
        'Cannot open manifest: %s.',fileName);
end
cleanup = onCleanup(@()fclose(file));
fprintf(file,'%s\n',jsonencode(entry));
end

function stamp = utc_stamp()
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
end
