function report = ipm_gaugelab_test_q512_continuation()
%IPM_GAUGELAB_TEST_Q512_CONTINUATION Synthetic no-PDE contract tests.

laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
experimentsDirectory = fullfile(researchDirectory,'experiments');
addpath(projectDirectory,laboratoryDirectory,experimentsDirectory);

emptyHistory = struct('common',struct(),'gauge',struct(), ...
    'mesh',struct(),'anisotropic',struct());
[emptyGroupsPassed,emptyGroupsAudit] = ...
    ipm_gaugelab_history_prefix(emptyHistory,emptyHistory);
childOnlyFields = emptyHistory;
childOnlyFields.anisotropic.aspectRate = 0;
[emptyParentNonemptyChildPassed,~] = ...
    ipm_gaugelab_history_prefix(emptyHistory,childOnlyFields);
nonemptyParent = emptyHistory;
nonemptyParent.common.t = [0;1];
missingFieldChild = emptyHistory;
[missingPrefixFieldPassed,missingPrefixFieldAudit] = ...
    ipm_gaugelab_history_prefix(nonemptyParent,missingFieldChild);
assert(emptyGroupsPassed && emptyGroupsAudit.matched && ...
    emptyParentNonemptyChildPassed && ~missingPrefixFieldPassed && ...
    strcmp(missingPrefixFieldAudit.failure,'missing_history_field') && ...
    strcmp(missingPrefixFieldAudit.group,'common') && ...
    strcmp(missingPrefixFieldAudit.field,'t'), ...
    'ipm:GaugeLabQ512ContinuationHistoryPrefixTest', ...
    'The exact history-prefix audit mishandled an empty grouped history.');

scratch = tempname;
mkdir(scratch);
cleanup = onCleanup(@()cleanup_directory(scratch));
[rootCheckpoint,rootSummary,rootCheckpointFile] = ...
    synthetic_root_fixture(scratch);

positiveOptions = struct( ...
    'parentRootSummary',rootSummary, ...
    'outputRoot',fullfile(scratch,'first_positive'));
first = ipm_gaugelab_run_q512_continuation( ...
    rootCheckpointFile,positiveOptions);
assert(strcmp(first.status,'preflight_only') && ...
    first.preflightPassed && isscalar(first.restoreChain) && ...
    strcmp(first.cOmegaGauge,'gradient_energy') && ...
    first.restoreChain{1}.schemaVersion == 3 && ...
    strcmp(first.restoreChain{1}.cOmegaGauge,'gradient_energy') && ...
    isequaln(first.restoreChain{1}.parentCheckpointSignature, ...
        rootCheckpoint.signature), ...
    'ipm:GaugeLabQ512ContinuationPositiveTest', ...
    'A valid hard-passed root did not register a full-signature resume.');

[childCheckpoint,childSummary,childCheckpointFile] = ...
    synthetic_child_fixture(scratch,rootCheckpoint,first);
secondOptions = struct( ...
    'parentRootSummary',childSummary, ...
    'outputRoot',fullfile(scratch,'second_positive'));
second = ipm_gaugelab_run_q512_continuation( ...
    childCheckpointFile,secondOptions);
assert(strcmp(second.status,'preflight_only') && ...
    second.preflightPassed && numel(second.restoreChain) == 2 && ...
    isequaln(second.restoreChain{1},first.restoreChain{1}) && ...
    isequaln(second.restoreChain{2}.parentCheckpointSignature, ...
        childCheckpoint.signature), ...
    'ipm:GaugeLabQ512ContinuationChainPositiveTest', ...
    'A valid two-hop full-signature chain did not register exactly.');

[quadraticRoot,quadraticSummary,quadraticRootFile] = ...
    synthetic_root_fixture(scratch, ...
        'wall_omega_quadratic_peak','quadratic');
quadraticFirst = ipm_gaugelab_run_q512_continuation( ...
    quadraticRootFile,struct( ...
        'parentRootSummary',quadraticSummary, ...
        'outputRoot',fullfile(scratch,'quadratic_first_positive')));
quadraticAlgebra = quadraticFirst.parentAudit.gaugeHistoryAudit;
quadraticAlgebra = quadraticAlgebra.quadraticGaugeAlgebra;
assert(strcmp(quadraticFirst.status,'preflight_only') && ...
    quadraticFirst.preflightPassed && ...
    strcmp(quadraticFirst.cOmegaGauge, ...
        'wall_omega_quadratic_peak') && ...
    quadraticAlgebra.passed && ...
    strcmp(quadraticFirst.restoreChain{1}.cOmegaGauge, ...
        'wall_omega_quadratic_peak') && ...
    isequaln(quadraticFirst.restoreChain{1}. ...
        parentCheckpointSignature,quadraticRoot.signature), ...
    'ipm:GaugeLabQ512ContinuationQuadraticPositiveTest', ...
    'A valid quadratic-gauge root did not preserve its gauge contract.');
[~,quadraticChildSummary,quadraticChildFile] = ...
    synthetic_child_fixture(scratch,quadraticRoot,quadraticFirst);
quadraticSecond = ipm_gaugelab_run_q512_continuation( ...
    quadraticChildFile,struct( ...
        'parentRootSummary',quadraticChildSummary, ...
        'outputRoot',fullfile(scratch,'quadratic_second_positive')));
assert(strcmp(quadraticSecond.status,'preflight_only') && ...
    quadraticSecond.preflightPassed && ...
    numel(quadraticSecond.restoreChain) == 2 && ...
    all(cellfun(@(event)strcmp(event.cOmegaGauge, ...
        'wall_omega_quadratic_peak'),quadraticSecond.restoreChain)), ...
    'ipm:GaugeLabQ512ContinuationQuadraticChainPositiveTest', ...
    'A valid two-hop quadratic-gauge chain changed amplitude gauge.');

missingSummaryRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(rootCheckpointFile, ...
    struct('outputRoot',fullfile(scratch,'missing_summary'))), ...
    'ipm:GaugeLabQ512ContinuationParentSummary');

fakeSummary = rootSummary;
fakeSummary.status = 'registered';
fakeRootRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(rootCheckpointFile,struct( ...
    'parentRootSummary',fakeSummary, ...
    'outputRoot',fullfile(scratch,'fake_root'))), ...
    'ipm:GaugeLabQ512ContinuationParentSummary');

gridMismatch = rootCheckpoint;
gridMismatch.payload.state.x(2) = mean( ...
    gridMismatch.payload.state.x([1,3]));
gridMismatch.payload.state.baseX = gridMismatch.payload.state.x;
gridMismatch = resign_checkpoint(gridMismatch);
gridMismatchFile = fullfile(scratch,'grid_mismatch.mat');
save_checkpoint(gridMismatchFile,gridMismatch);
gridSummary = rootSummary;
gridSummary.checkpointFile = gridMismatchFile;
gridSummary.config = gridMismatch.payload.state.config;
gridMismatchRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(gridMismatchFile,struct( ...
    'parentRootSummary',gridSummary, ...
    'outputRoot',fullfile(scratch,'grid_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

wrongDatum = rootCheckpoint;
wrongDatum.payload.state.config = replace_config_option( ...
    wrongDatum.payload.state.config,'initialCondition','degenerate');
wrongDatum.payload.state.runMetadata.caseMetadata = ...
    wrongDatum.payload.state.config.output.caseMetadata;
wrongDatum = resign_checkpoint(wrongDatum);
wrongDatumFile = fullfile(scratch,'wrong_datum.mat');
save_checkpoint(wrongDatumFile,wrongDatum);
wrongDatumSummary = rootSummary;
wrongDatumSummary.checkpointFile = wrongDatumFile;
wrongDatumSummary.config = wrongDatum.payload.state.config;
wrongDatumRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(wrongDatumFile,struct( ...
    'parentRootSummary',wrongDatumSummary, ...
    'outputRoot',fullfile(scratch,'datum_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

wrongFactory = rootCheckpoint;
wrongFactory.payload.state.config.output.caseMetadata.caseName = ...
    'forged_q512_factory';
wrongFactory.payload.state.runMetadata.caseMetadata = ...
    wrongFactory.payload.state.config.output.caseMetadata;
wrongFactory = resign_checkpoint(wrongFactory);
wrongFactoryFile = fullfile(scratch,'wrong_factory.mat');
save_checkpoint(wrongFactoryFile,wrongFactory);
wrongFactorySummary = rootSummary;
wrongFactorySummary.checkpointFile = wrongFactoryFile;
wrongFactorySummary.config = wrongFactory.payload.state.config;
wrongFactoryRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(wrongFactoryFile,struct( ...
    'parentRootSummary',wrongFactorySummary, ...
    'outputRoot',fullfile(scratch,'factory_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

wrongBox = rootCheckpoint;
wrongBox.payload.state.config.output.caseMetadata. ...
    q512GaugeRoot.boxHalfWidth = 1e6;
wrongBox.payload.state.runMetadata.caseMetadata = ...
    wrongBox.payload.state.config.output.caseMetadata;
wrongBox = resign_checkpoint(wrongBox);
wrongBoxFile = fullfile(scratch,'wrong_box_metadata.mat');
save_checkpoint(wrongBoxFile,wrongBox);
wrongBoxSummary = rootSummary;
wrongBoxSummary.checkpointFile = wrongBoxFile;
wrongBoxSummary.config = wrongBox.payload.state.config;
boxMetadataRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(wrongBoxFile,struct( ...
    'parentRootSummary',wrongBoxSummary, ...
    'outputRoot',fullfile(scratch,'box_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

reducedHorizonRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(rootCheckpointFile,struct( ...
    'parentRootSummary',rootSummary, ...
    'maxSteps',rootCheckpoint.payload.state.config.time.maxSteps-1, ...
    'outputRoot',fullfile(scratch,'horizon_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationHorizon');

closedHorizon = rootCheckpoint;
closedHorizon.payload.state.config = replace_config_option( ...
    closedHorizon.payload.state.config,'finalTime', ...
    closedHorizon.payload.state.scale.canonicalTime);
closedHorizon.payload.state.runMetadata.caseMetadata = ...
    closedHorizon.payload.state.config.output.caseMetadata;
closedHorizon = resign_checkpoint(closedHorizon);
closedHorizonFile = fullfile(scratch,'closed_horizon.mat');
save_checkpoint(closedHorizonFile,closedHorizon);
closedHorizonSummary = rootSummary;
closedHorizonSummary.checkpointFile = closedHorizonFile;
closedHorizonSummary.config = closedHorizon.payload.state.config;
closedHorizonRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(closedHorizonFile,struct( ...
    'parentRootSummary',closedHorizonSummary, ...
    'outputRoot',fullfile(scratch,'closed_horizon_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationHorizon');

badGauge = rootCheckpoint;
badGauge.payload.log.history.gauge.omegaGaugeEnergy = ...
    badGauge.payload.log.history.gauge.omegaGaugeEnergy+0.25;
badGauge = resign_checkpoint(badGauge);
badGaugeFile = fullfile(scratch,'bad_gradient_algebra.mat');
save_checkpoint(badGaugeFile,badGauge);
badGaugeSummary = rootSummary;
badGaugeSummary.checkpointFile = badGaugeFile;
badGaugeSummary.config = badGauge.payload.state.config;
gradientAlgebraRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(badGaugeFile,struct( ...
    'parentRootSummary',badGaugeSummary, ...
    'outputRoot',fullfile(scratch,'gauge_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

zeroEnergy = rootCheckpoint;
zeroEnergy.payload.log.history.gauge.omegaGaugeEnergy = 0;
zeroEnergy.payload.log.history.gauge.omegaGaugeEnergyX = 0;
zeroEnergy.payload.log.history.gauge.omegaGaugeEnergyY = 0;
zeroEnergy.payload.log.history.gauge.omegaGaugeForcingX = 0;
zeroEnergy.payload.log.history.gauge.omegaGaugeForcingY = 0;
zeroEnergy.payload.log.history.gauge.omegaGaugeForcing = 0;
zeroEnergy.payload.log.history.gauge.omegaGaugeAbsoluteForcing = 0;
zeroEnergy.payload.log.history.gauge.omegaGaugeForcingCancellationRatio = 0;
zeroEnergy = resign_checkpoint(zeroEnergy);
zeroEnergyFile = fullfile(scratch,'zero_gradient_energy.mat');
save_checkpoint(zeroEnergyFile,zeroEnergy);
zeroEnergySummary = rootSummary;
zeroEnergySummary.checkpointFile = zeroEnergyFile;
zeroEnergyRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(zeroEnergyFile,struct( ...
    'parentRootSummary',zeroEnergySummary, ...
    'outputRoot',fullfile(scratch,'zero_energy_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

badForcing = rootCheckpoint;
badForcing.payload.log.history.gauge.omegaGaugeForcing = -0.5;
badForcing = resign_checkpoint(badForcing);
badForcingFile = fullfile(scratch,'bad_forcing_parts.mat');
save_checkpoint(badForcingFile,badForcing);
badForcingSummary = rootSummary;
badForcingSummary.checkpointFile = badForcingFile;
forcingPartsRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(badForcingFile,struct( ...
    'parentRootSummary',badForcingSummary, ...
    'outputRoot',fullfile(scratch,'forcing_parts_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

badCancellation = rootCheckpoint;
badCancellation.payload.log.history.gauge.omegaGaugeAbsoluteForcing = 0.5;
badCancellation.payload.log.history.gauge. ...
    omegaGaugeForcingCancellationRatio = 1.5;
badCancellation = resign_checkpoint(badCancellation);
badCancellationFile = fullfile(scratch,'bad_forcing_cancellation.mat');
save_checkpoint(badCancellationFile,badCancellation);
badCancellationSummary = rootSummary;
badCancellationSummary.checkpointFile = badCancellationFile;
forcingCancellationRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(badCancellationFile,struct( ...
        'parentRootSummary',badCancellationSummary, ...
        'outputRoot',fullfile(scratch,'forcing_cancellation_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

badQuadraticPeak = quadraticRoot;
badQuadraticPeak.payload.log.history.gauge. ...
    omegaGaugeQuadraticPeakValue = 3.5;
badQuadraticPeak = resign_checkpoint(badQuadraticPeak);
badQuadraticPeakFile = fullfile(scratch,'bad_quadratic_peak.mat');
save_checkpoint(badQuadraticPeakFile,badQuadraticPeak);
badQuadraticPeakSummary = quadraticSummary;
badQuadraticPeakSummary.checkpointFile = badQuadraticPeakFile;
badQuadraticPeakSummary.config = ...
    badQuadraticPeak.payload.state.config;
quadraticAlgebraRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation( ...
        badQuadraticPeakFile,struct( ...
        'parentRootSummary',badQuadraticPeakSummary, ...
        'outputRoot',fullfile(scratch,'quadratic_peak_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

badQuadraticCurvature = quadraticRoot;
badQuadraticCurvature.payload.log.history.gauge. ...
    omegaGaugeQuadraticCurvature = 4;
badQuadraticCurvature = resign_checkpoint(badQuadraticCurvature);
badQuadraticCurvatureFile = fullfile( ...
    scratch,'bad_quadratic_curvature.mat');
save_checkpoint(badQuadraticCurvatureFile,badQuadraticCurvature);
badQuadraticCurvatureSummary = quadraticSummary;
badQuadraticCurvatureSummary.checkpointFile = ...
    badQuadraticCurvatureFile;
badQuadraticCurvatureSummary.config = ...
    badQuadraticCurvature.payload.state.config;
quadraticCurvatureRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation( ...
        badQuadraticCurvatureFile,struct( ...
        'parentRootSummary',badQuadraticCurvatureSummary, ...
        'outputRoot',fullfile(scratch,'quadratic_curvature_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

unsupportedGauge = rootCheckpoint;
unsupportedGauge.payload.state.config = replace_config_option( ...
    unsupportedGauge.payload.state.config,'cOmegaGauge','none');
unsupportedGauge.payload.state.config.output.caseMetadata. ...
    q512GaugeRoot.cOmegaGauge = 'none';
unsupportedGauge.payload.state.runMetadata.caseMetadata = ...
    unsupportedGauge.payload.state.config.output.caseMetadata;
unsupportedGauge = resign_checkpoint(unsupportedGauge);
unsupportedGaugeFile = fullfile(scratch,'unsupported_gauge.mat');
save_checkpoint(unsupportedGaugeFile,unsupportedGauge);
unsupportedGaugeSummary = rootSummary;
unsupportedGaugeSummary.checkpointFile = unsupportedGaugeFile;
unsupportedGaugeSummary.config = unsupportedGauge.payload.state.config;
unsupportedGaugeRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation( ...
        unsupportedGaugeFile,struct( ...
        'parentRootSummary',unsupportedGaugeSummary, ...
        'outputRoot',fullfile(scratch,'unsupported_gauge_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

switchedGauge = childCheckpoint;
switchedGauge.payload.state.config = replace_config_option( ...
    switchedGauge.payload.state.config,'cOmegaGauge', ...
    'wall_omega_quadratic_peak');
switchedGauge.payload.state.config.output.caseMetadata. ...
    q512GaugeRoot.cOmegaGauge = 'wall_omega_quadratic_peak';
switchedGauge.payload.state.runMetadata.caseMetadata = ...
    switchedGauge.payload.state.config.output.caseMetadata;
switchedGauge.payload.state.runMetadata.gaugeContract = ...
    synthetic_gauge_contract('wall_omega_quadratic_peak');
switchedGauge.payload.log = synthetic_log( ...
    switchedGauge.payload.state.scale.canonicalTime, ...
    switchedGauge.payload.state.scale.physicalTime, ...
    switchedGauge.payload.state.step,'wall_omega_quadratic_peak');
switchedGauge = resign_checkpoint(switchedGauge);
switchedGaugeFile = fullfile(scratch,'mid_chain_gauge_switch.mat');
save_checkpoint(switchedGaugeFile,switchedGauge);
switchedGaugeSummary = childSummary;
switchedGaugeSummary.checkpointFile = switchedGaugeFile;
switchedGaugeSummary.childCheckpointSignature = ...
    switchedGauge.signature;
switchedGaugeSummary.config = switchedGauge.payload.state.config;
midChainGaugeSwitchRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation( ...
        switchedGaugeFile,struct( ...
        'parentRootSummary',switchedGaugeSummary, ...
        'outputRoot',fullfile(scratch,'gauge_switch_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

weakChain = childCheckpoint;
event = weakChain.payload.state.config.output. ...
    caseMetadata.q512ContinuationChain{1};
event = rmfield(event,'parentCheckpointSignature');
event.schemaVersion = 1;
weakChain.payload.state.config.output.caseMetadata. ...
    q512ContinuationChain = {event};
weakChain.payload.state.config.output.caseMetadata. ...
    q512ContinuationCurrent = event;
weakChain.payload.state.runMetadata.caseMetadata = ...
    weakChain.payload.state.config.output.caseMetadata;
weakChain = resign_checkpoint(weakChain);
weakChainFile = fullfile(scratch,'weak_chain.mat');
save_checkpoint(weakChainFile,weakChain);
weakChainRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(weakChainFile,struct( ...
    'parentRootSummary',childSummary, ...
    'outputRoot',fullfile(scratch,'weak_chain_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

signatureMismatch = childCheckpoint;
event = signatureMismatch.payload.state.config.output. ...
    caseMetadata.q512ContinuationChain{1};
event.parentCheckpointSignature.rho.weightedSum1 = ...
    event.parentCheckpointSignature.rho.weightedSum1+1;
signatureMismatch.payload.state.config.output.caseMetadata. ...
    q512ContinuationChain = {event};
signatureMismatch.payload.state.config.output.caseMetadata. ...
    q512ContinuationCurrent = event;
signatureMismatch.payload.state.runMetadata.caseMetadata = ...
    signatureMismatch.payload.state.config.output.caseMetadata;
signatureMismatch = resign_checkpoint(signatureMismatch);
signatureMismatchFile = fullfile(scratch,'chain_signature_mismatch.mat');
save_checkpoint(signatureMismatchFile,signatureMismatch);
signatureSummary = childSummary;
signatureSummary.checkpointFile = signatureMismatchFile;
signatureSummary.childCheckpointSignature = signatureMismatch.signature;
signatureSummary.config = signatureMismatch.payload.state.config;
signatureSummary.restoreChain = {event};
chainSignatureRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(signatureMismatchFile,struct( ...
    'parentRootSummary',signatureSummary, ...
    'outputRoot',fullfile(scratch,'signature_chain_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationParentSummary');

[grandchildCheckpoint,grandchildSummary,~] = ...
    synthetic_child_fixture(scratch,childCheckpoint,second);
brokenHop = grandchildCheckpoint;
events = brokenHop.payload.state.config.output. ...
    caseMetadata.q512ContinuationChain;
events{2}.parentCheckpointSignature.config.output.caseMetadata. ...
    q512ContinuationChain = {};
brokenHop.payload.state.config.output.caseMetadata. ...
    q512ContinuationChain = events;
brokenHop.payload.state.config.output.caseMetadata. ...
    q512ContinuationCurrent = events{end};
brokenHop.payload.state.runMetadata.caseMetadata = ...
    brokenHop.payload.state.config.output.caseMetadata;
brokenHop = resign_checkpoint(brokenHop);
brokenHopFile = fullfile(scratch,'broken_intermediate_hop.mat');
save_checkpoint(brokenHopFile,brokenHop);
grandchildSummary.checkpointFile = brokenHopFile;
grandchildSummary.childCheckpointSignature = brokenHop.signature;
grandchildSummary.config = brokenHop.payload.state.config;
grandchildSummary.restoreChain = events;
brokenHopRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(brokenHopFile,struct( ...
    'parentRootSummary',grandchildSummary, ...
    'outputRoot',fullfile(scratch,'broken_hop_rejected'))), ...
    'ipm:GaugeLabQ512ContinuationContract');

legacy = struct('schemaVersion',3);
legacyRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(legacy,struct( ...
    'parentRootSummary',struct('placeholder',true))), ...
    'ipm:CheckpointIncompatibleSchema');

protected = { ...
    'cfl',0.5; ...
    'maxDt',1e-3; ...
    'lengthGauge','omega_peak_location'; ...
    'cOmegaGauge','wall_omega_quadratic_peak'; ...
    'xlim',[-1,1]; ...
    'initialCondition','degenerate'; ...
    'checkpointEvery',0.1};
protectedRejected = false(size(protected,1),1);
for index = 1:size(protected,1)
    options = struct('parentRootSummary',struct('placeholder',true));
    options.(protected{index,1}) = protected{index,2};
    protectedRejected(index) = assert_throws(@() ...
        ipm_gaugelab_run_q512_continuation(struct(),options), ...
        'ipm:GaugeLabQ512ContinuationOptions');
end

missingCheckpointRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation([],struct( ...
    'parentRootSummary',struct('placeholder',true))), ...
    'ipm:GaugeLabQ512ContinuationCheckpoint');
nonscalarOptionsRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_continuation(struct(), ...
    repmat(struct('parentRootSummary',struct('placeholder',true)),2,1)), ...
    'ipm:GaugeLabQ512ContinuationOptions');

assert(legacyRejected && all(protectedRejected) && ...
    missingCheckpointRejected && nonscalarOptionsRejected && ...
    missingSummaryRejected && fakeRootRejected && ...
    gridMismatchRejected && wrongDatumRejected && ...
    wrongFactoryRejected && boxMetadataRejected && ...
    reducedHorizonRejected && closedHorizonRejected && ...
    gradientAlgebraRejected && ...
    zeroEnergyRejected && forcingPartsRejected && ...
    forcingCancellationRejected && quadraticAlgebraRejected && ...
    quadraticCurvatureRejected && unsupportedGaugeRejected && ...
    midChainGaugeSwitchRejected && ...
    weakChainRejected && chainSignatureRejected && brokenHopRejected, ...
    'ipm:GaugeLabQ512ContinuationNegativeTest', ...
    'The continuation runner accepted a synthetic contract violation.');
report = struct( ...
    'emptyHistoryGroupsPassed',emptyGroupsPassed, ...
    'emptyParentNonemptyChildPassed',emptyParentNonemptyChildPassed, ...
    'missingPrefixFieldRejected',~missingPrefixFieldPassed, ...
    'freshRootPreflightPassed',first.preflightPassed, ...
    'twoHopPreflightPassed',second.preflightPassed, ...
    'quadraticFreshRootPreflightPassed', ...
        quadraticFirst.preflightPassed, ...
    'quadraticTwoHopPreflightPassed', ...
        quadraticSecond.preflightPassed, ...
    'fullSignaturePersisted',isequaln( ...
        second.restoreChain{2}.parentCheckpointSignature, ...
        childCheckpoint.signature), ...
    'missingSummaryRejected',missingSummaryRejected, ...
    'fakeRootRejected',fakeRootRejected, ...
    'gridMismatchRejected',gridMismatchRejected, ...
    'wrongDatumRejected',wrongDatumRejected, ...
    'wrongFactoryRejected',wrongFactoryRejected, ...
    'boxMetadataRejected',boxMetadataRejected, ...
    'reducedHorizonRejected',reducedHorizonRejected, ...
    'closedHorizonRejected',closedHorizonRejected, ...
    'gradientAlgebraRejected',gradientAlgebraRejected, ...
    'zeroEnergyRejected',zeroEnergyRejected, ...
    'forcingPartsRejected',forcingPartsRejected, ...
    'forcingCancellationRejected',forcingCancellationRejected, ...
    'quadraticAlgebraRejected',quadraticAlgebraRejected, ...
    'quadraticCurvatureRejected',quadraticCurvatureRejected, ...
    'unsupportedGaugeRejected',unsupportedGaugeRejected, ...
    'midChainGaugeSwitchRejected',midChainGaugeSwitchRejected, ...
    'weakChainRejected',weakChainRejected, ...
    'chainSignatureRejected',chainSignatureRejected, ...
    'brokenIntermediateHopRejected',brokenHopRejected, ...
    'legacySchemaRejected',legacyRejected, ...
    'protectedOptionNames',{protected(:,1).'}, ...
    'protectedOptionsRejected',all(protectedRejected), ...
    'missingCheckpointRejected',missingCheckpointRejected, ...
    'nonscalarOptionsRejected',nonscalarOptionsRejected, ...
    'solveExecuted',false,'passed',true);
fprintf(['Q512 continuation synthetic test: fresh root and two-hop ' ...
    'full-signature registration and empty-group prefix regression ' ...
    'passed for both gauges; ' ...
    '%d rejection classes passed; no PDE solve executed.\n'], ...
    22+size(protected,1));
end

function [checkpoint,rootRun,fileName] = synthetic_root_fixture( ...
        scratch,cOmegaGauge,label)
if nargin < 2
    cOmegaGauge = 'gradient_energy';
end
if nargin < 3
    label = 'gradient';
end
runId = ['synthetic_q512_root_',label];
checkpointRequest = fullfile(scratch, ...
    ['synthetic_',label,'_checkpoint_request.mat']);
metadata = struct('q512GaugeRoot',struct( ...
    'schemaVersion',4,'runId',runId,'freshStart',true, ...
    'restartInput','none','boxMode','matched','boxHalfWidth',281, ...
    'runMode','campaign', ...
    'configurationContract','exact_gauge_no_feedback_v1', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge',cOmegaGauge));
overrides = struct( ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'rescalingMode','dynamic','dynamicScaleGeometry','isotropic', ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge',cOmegaGauge,'lengthScaleGain',1, ...
    'widthGaugeGain',0,'omegaGaugeGain',0,'travelingWaveGain',0, ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'initialAnalyticRemesh',false,'adaptiveRemesh',false, ...
    'remeshMaximumCellRatio',1.08, ...
    'physicalFinalTime',4,'finalTime',12,'cfl',0.25, ...
    'maxDt',2e-3,'maxSteps',30000,'outputEvery',5e-3, ...
    'checkpoint',struct('enabled',true,'file',checkpointRequest, ...
        'every',0.2,'atExit',true), ...
    'caseMetadata',metadata,'resultFile',fullfile( ...
        scratch,['result_',label,'.mat']), ...
    'saveResults',true,'storeSnapshots',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
opts = fourth_order_blowup_case( ...
    'coordinated_log_F80_R20_c114_quadrant_512',overrides);
config = ipm.config.resolve(opts);
tau = 0.01;
physicalTime = 0.005;
step = 1;
state = synthetic_state(config,tau,physicalTime,step);
log = synthetic_log(tau,physicalTime,step,cOmegaGauge);
cursor = struct('nextOutput',tau+config.time.outputEvery, ...
    'nextCheckpoint',tau+config.output.checkpoint.every, ...
    'lastCheckpointStep',step, ...
    'lastCheckpointCanonicalTime',tau);
payload = struct('state',state,'log',log,'cursor',cursor);
checkpoint = struct('schemaVersion',4, ...
    'kind','ipm_accepted_step_checkpoint', ...
    'createdUtc','2026-09-05T00:00:00.000Z', ...
    'acceptedStep',true,'trustedRecord',true,'payload',payload, ...
    'signature',ipm.output.checkpointSignature(payload));
fileName = fullfile(scratch, ...
    ['synthetic_',label,'_root_checkpoint.mat']);
save_checkpoint(fileName,checkpoint);
domain = struct('x',[-281,281],'y',[0,132], ...
    'initialPhysicalX',[-281,281],'initialPhysicalY',[0,132]);
rootRun = struct('schemaVersion',4, ...
    'kind','q512_fresh_exact_gauge_root','runId',runId, ...
    'status','completed','baseCaseName', ...
        'coordinated_log_F80_R20_c114_quadrant_512', ...
    'boxMode','matched','domain',domain,'steps',step, ...
    'cOmegaGauge',cOmegaGauge, ...
    'config',config,'checkpointFile',fileName, ...
    'postAudit',synthetic_post_audit());
end

function [checkpoint,summary,fileName] = synthetic_child_fixture( ...
        scratch,parentCheckpoint,registration)
checkpoint = parentCheckpoint;
state = checkpoint.payload.state;
state.config = registration.config;
state.step = state.step+1;
state.normalizedTime = state.normalizedTime+0.01;
state.scale.canonicalTime = state.normalizedTime;
state.scale.physicalTime = state.scale.physicalTime+0.005;
state.runMetadata.caseMetadata = state.config.output.caseMetadata;
state.runMetadata.resumeCount = numel(registration.restoreChain);
latest = registration.restoreChain{end};
state.runMetadata.resumedFromStep = latest.parentStep;
state.runMetadata.resumedFromCanonicalTime = latest.parentCanonicalTime;
state.runMetadata.resumedFromPhysicalTime = latest.parentPhysicalTime;
state.runMetadata.resumedFromCheckpoint = "in_memory_checkpoint";
checkpoint.payload.state = state;
checkpoint.payload.log = synthetic_log( ...
    state.scale.canonicalTime,state.scale.physicalTime,state.step, ...
    state.config.scaling.cOmegaGauge);
checkpoint.payload.cursor.nextOutput = ...
    state.scale.canonicalTime+state.config.time.outputEvery;
checkpoint.payload.cursor.nextCheckpoint = ...
    state.scale.canonicalTime+state.config.output.checkpoint.every;
checkpoint.payload.cursor.lastCheckpointStep = state.step;
checkpoint.payload.cursor.lastCheckpointCanonicalTime = ...
    state.scale.canonicalTime;
checkpoint = resign_checkpoint(checkpoint);
fileName = fullfile(scratch,sprintf( ...
    'synthetic_%s_child_step%04d_checkpoint.mat', ...
    state.config.scaling.cOmegaGauge,state.step));
save_checkpoint(fileName,checkpoint);
summary = registration;
summary.status = 'completed_intermediate';
summary.checkpointFile = fileName;
summary.childCheckpointSignature = checkpoint.signature;
summary.totalSteps = state.step;
summary.postAudit = synthetic_post_audit();
end

function audit = synthetic_post_audit()
audit = struct('hardPassed',true, ...
    'checks',struct('syntheticContractGate',true), ...
    'failures',{{}});
end

function state = synthetic_state(config,tau,physicalTime,step)
x = config.grid.customX;
y = config.grid.customY;
rho = zeros(numel(y),numel(x));
state = struct('config',config, ...
    'runMetadata',struct('caseMetadata',config.output.caseMetadata, ...
        'gaugeContract',synthetic_gauge_contract( ...
            config.scaling.cOmegaGauge),'resumeCount',0), ...
    'rho',rho,'x',x,'y',y,'baseX',x,'baseY',y, ...
    'rescaling',struct(),'remeshCount',0, ...
    'scale',struct('logC_l',0,'logC_omega',0, ...
        'physicalTime',physicalTime,'X_shift',0, ...
        'canonicalTime',tau), ...
    'normalizedTime',tau,'step',step,'mass0',0,'rhoRange0',[0,0]);
end

function log = synthetic_log(tau,physicalTime,step,cOmegaGauge)
cL = 0.5;
cOmega = 0.25;
common = struct('acceptedStep',step,'t',tau,'canonicalTau',tau, ...
    'physicalTime',physicalTime,'timeSpeed',1, ...
    'c_l',cL,'c_x',cL,'c_y',cL,'c_omega',cOmega,'c_r',0, ...
    'conservativeSource',2*cL+cOmega, ...
    'canonicalCL',cL,'canonicalCX',cL,'canonicalCY',cL, ...
    'canonicalCOmega',cOmega,'canonicalCR',0, ...
    'canonicalConservativeSource',2*cL+cOmega, ...
    'wallPeakLocalMaxima',1,'wallPeakTVRatio',0, ...
    'positiveWallNegativeRatio',0,'physicalRangeViolation',0);
gauge = struct('omegaGaugeResidual',0,'lengthGaugeResidual',0, ...
    'transportAnchorVelocity',0, ...
    'canonicalTransportAnchorVelocity',0,'transportAnchorX',1, ...
    'c_lNominal',cL,'canonicalCLNominal',cL, ...
    'lengthScaleGain',1,'widthControlMode',0,'widthCorrection',0, ...
    'canonicalWidthCorrection',0,'omegaGaugeEnergy',3);
if strcmp(cOmegaGauge,'gradient_energy')
    gauge.omegaGaugeEnergyX = 1;
    gauge.omegaGaugeEnergyY = 2;
    gauge.omegaGaugeForcingX = -0.25;
    gauge.omegaGaugeForcingY = -0.5;
    gauge.omegaGaugeForcing = -0.75;
    gauge.omegaGaugeAbsoluteForcing = 0.75;
    gauge.omegaGaugeForcingCancellationRatio = 1;
elseif strcmp(cOmegaGauge,'wall_omega_quadratic_peak')
    gauge.omegaPeakRateResidual = 0;
    gauge.omegaGaugePeakX = 1.1;
    gauge.omegaGaugePeakCondition = 0.5;
    gauge.omegaGaugeQuadraticPeakX = 1.1;
    gauge.omegaGaugeQuadraticPeakValue = 3;
    gauge.omegaGaugeQuadraticForcing = -0.75;
    gauge.omegaGaugeQuadraticCurvature = -4;
    gauge.omegaGaugeQuadraticStationarityResidual = 0;
    gauge.omegaGaugeQuadraticNormalizedStationarityResidual = 0;
    gauge.omegaGaugeQuadraticCurvatureCondition = 0.1;
    gauge.omegaGaugeQuadraticWeightCondition = 0.8;
    gauge.omegaGaugeQuadraticActiveNodeMargin = 0.1;
    gauge.omegaGaugeQuadraticActiveSelectionMargin = 0.1;
    gauge.omegaGaugeQuadraticStencilCenterX = 1;
    gauge.omegaGaugeQuadraticVertexInteriorFraction = 0.45;
    gauge.omegaGaugeQuadraticRelativeSubgridLift = 0.01;
    gauge.omegaGaugeQuadraticRateResidual = 0;
    gauge.omegaGaugeQuadraticRateScale = 0.75;
else
    error('ipm:GaugeLabQ512ContinuationSyntheticGauge', ...
        'Unsupported synthetic cOmegaGauge: %s.',cOmegaGauge);
end
mesh = struct('remeshCount',0,'maximumCellRatioX',1, ...
    'maximumCellRatioY',1,'safetyFactor',0);
log = struct('history',struct('common',common,'gauge',gauge, ...
    'mesh',mesh,'anisotropic',struct()), ...
    'snapshotRho',{{}},'snapshotNormalizedTime',[], ...
    'snapshotX',{{}},'snapshotY',{{}});
end

function contract = synthetic_gauge_contract(cOmegaGauge)
if strcmp(cOmegaGauge,'gradient_energy')
    amplitude = struct('name',cOmegaGauge, ...
        'formula',[ ...
        'c_omega=-sum(w*(R_X*B_X+R_Y*B_Y))/' ...
        'sum(w*(R_X^2+R_Y^2))'], ...
        'observable','global_discrete_gradient_energy', ...
        'evaluation','fixed_grid_quadrature');
elseif strcmp(cOmegaGauge,'wall_omega_quadratic_peak')
    amplitude = struct('name',cOmegaGauge, ...
        'formula','c_omega=-Q[B_X](X_vertex)/Q[R_X](X_vertex)', ...
        'observable','tracked_wall_omega_quadratic_peak', ...
        'evaluation', ...
            'active_nonuniform_three_node_quadratic_vertex');
else
    error('ipm:GaugeLabQ512ContinuationSyntheticGauge', ...
        'Unsupported synthetic cOmegaGauge: %s.',cOmegaGauge);
end
contract = struct('schemaVersion',2, ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'clock','canonical_tau_direct','timeSpeed',1, ...
    'feedback',struct('rateLimiter','absent', ...
        'lengthScaleGain',1,'widthGaugeGain',0, ...
        'omegaGaugeGain',0,'travelingWaveGain',0), ...
    'length',struct('name','transport_anchor', ...
        'formula','c_l=-U1(X_anchor,0)/X_anchor', ...
        'evaluation','fixed_coordinate_linear_interpolation', ...
        'anchorX',1,'registeredParameters', ...
            struct('transportAnchorX',1)), ...
    'amplitude',amplitude);
end

function config = replace_config_option(config,name,value)
schema = ipm.config.schema();
flat = struct();
for domainIndex = 1:numel(schema.domainNames)
    domain = config.(schema.domainNames{domainIndex});
    names = fieldnames(domain);
    for nameIndex = 1:numel(names)
        flat.(names{nameIndex}) = domain.(names{nameIndex});
    end
end
flat.(name) = value;
config = ipm.config.resolve(flat);
end

function checkpoint = resign_checkpoint(checkpoint)
checkpoint.signature = ipm.output.checkpointSignature(checkpoint.payload);
end

function save_checkpoint(fileName,value)
checkpoint = value;
save(fileName,'checkpoint');
end

function passed = assert_throws(action,identifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:GaugeLabQ512ContinuationUnexpectedError', ...
        'Expected %s but received %s: %s.', ...
        identifier,exception.identifier,exception.message);
    passed = true;
    return
end
error('ipm:GaugeLabQ512ContinuationMissingError', ...
    'Expected error %s.',identifier);
end

function cleanup_directory(directory)
if isfolder(directory)
    try
        rmdir(directory,'s');
    catch exception
        fprintf(2,'IPM warning: could not remove %s: %s\n', ...
            directory,exception.message);
    end
end
end
