function screen = ipm_gaugelab_screen_q512_comega_box(options)
%IPM_GAUGELAB_SCREEN_Q512_COMEGA_BOX Initial-RHS q512 box screen.
%   SCREEN = IPM_GAUGELAB_SCREEN_Q512_COMEGA_BOX() evaluates only the
%   initial right-hand side--it never advances the PDE--on the registered
%   anchor-aligned q512 large-box family with half-widths
%       [281, 1e3, 1e4, 1e5, 1e6].
%   The length gauge is fixed to transport_anchor at X=1.  The only
%   amplitude gauges are the negative control gradient_energy, the local
%   wall_omega_quadratic_peak candidate, and the exploratory exact `none`
%   gauge (c_omega=0).  All use the exact no-feedback contract and the
%   registered high-order numerical tuple.
%
%   The default is preflight-only: it registers and audits every schema-4
%   configuration without building a Poisson solver or evaluating an RHS.
%   Set OPTIONS.execute=true explicitly to evaluate the initial RHS.  Even
%   then, the runner performs no time step, checkpoint operation, or solver
%   result-file write.  Every call writes a new immutable
%   summary/JSONL-manifest directory.
%
%   This is a normalization screen, not truncation or late-time evidence.
%   Its hard gate requires the full-gradient negative control to expose its
%   extensive energy/forcing and requires the quadratic-peak rate and
%   local functional to converge on the final 1e5 -> 1e6 box comparison.
%   The identically-zero `none` rate is never promoted by this screen: it
%   remains ineligible until time-evolved field, box, and CFL evidence is
%   available.  Its exact-zero implementation and shared c_l box
%   consistency must nevertheless pass for the screen itself to be valid.

if nargin < 1 || isempty(options)
    options = struct();
end
settings = resolve_options(options);
require_factory();

[outputDirectory,screenId] = create_output_directory(settings.outputRoot);
summaryFile = fullfile(outputDirectory,'comega_box_screen_summary.mat');
manifestFile = fullfile(outputDirectory,'comega_box_screen_manifest.jsonl');
boxHalfWidths = [281,1e3,1e4,1e5,1e6];
gauges = {'gradient_energy','wall_omega_quadratic_peak','none'};
limits = registered_limits();

records = repmat(empty_box_record(gauges),numel(boxHalfWidths),1);
for index = 1:numel(boxHalfWidths)
    records(index).index = index;
    records(index).boxHalfWidth = boxHalfWidths(index);
    records(index).domain = struct( ...
        'x',[-boxHalfWidths(index),boxHalfWidths(index)], ...
        'y',[0,boxHalfWidths(index)]);
    records(index).status = 'pending';
end

startedUtc = utc_stamp();
screen = struct( ...
    'schemaVersion',4, ...
    'kind','q512_initial_rhs_comega_box_screen', ...
    'screenId',screenId, ...
    'status','registered', ...
    'startedUtc',startedUtc, ...
    'completedUtc','', ...
    'executionMode',execution_mode(settings), ...
    'initialRhsOnly',true, ...
    'solveExecuted',false, ...
    'pdeStepsExecuted',0, ...
    'freshInitialData',true, ...
    'checkpointInputsAccepted',false, ...
    'lateTimeEvidence',false, ...
    'truncationEvidence',false, ...
    'noneGaugePromotionEvidenceRequired',{ ...
        {'time_evolved_fields','box_refinement','cfl_refinement'}}, ...
    'interpretation',[ ...
        'initial_normalization_box_screen_only_not_late_time_or_' ...
        'truncation_evidence'], ...
    'boxFamily','anchor_aligned_q512_large_box_factory', ...
    'boxHalfWidths',boxHalfWidths, ...
    'gauges',{gauges}, ...
    'requested',requested_summary(settings), ...
    'registeredGaugeRules',registered_gauge_rules(), ...
    'hardLimits',limits, ...
    'outputDirectory',outputDirectory, ...
    'summaryFile',summaryFile, ...
    'manifestFile',manifestFile, ...
    'boxes',records, ...
    'successiveComparisons', ...
        repmat(empty_comparison(),0,1), ...
    'preflightPassed',false, ...
    'screeningGate',empty_screening_gate(), ...
    'hardPassed',false, ...
    'totalWallSeconds',NaN, ...
    'totalRhsWallSeconds',NaN, ...
    'failures',{{}});
save_summary(summaryFile,screen);
append_manifest(manifestFile,struct( ...
    'event','screen_registered', ...
    'timestampUtc',startedUtc, ...
    'screenId',screenId, ...
    'schemaVersion',screen.schemaVersion, ...
    'executionMode',screen.executionMode, ...
    'initialRhsOnly',true, ...
    'solveExecuted',false, ...
    'pdeStepsExecuted',0, ...
    'boxHalfWidths',boxHalfWidths, ...
    'gauges',{gauges}, ...
    'requested',screen.requested, ...
    'hardLimits',limits, ...
    'summaryFile',summaryFile));

totalClock = tic;
for boxIndex = 1:numel(boxHalfWidths)
    halfWidth = boxHalfWidths(boxIndex);
    record = screen.boxes(boxIndex);
    record.status = 'preflighting';
    record.startedUtc = utc_stamp();
    screen.boxes(boxIndex) = record;
    save_summary(summaryFile,screen);
    append_manifest(manifestFile,struct( ...
        'event','box_started', ...
        'timestampUtc',record.startedUtc, ...
        'screenId',screenId, ...
        'boxHalfWidth',halfWidth, ...
        'executeInitialRhs',settings.execute));

    try
        [flatOptions,configurations] = registered_configurations( ...
            halfWidth,gauges,screenId,outputDirectory);
        record.configurations = configurations;
        [record.meshAudit,record.meshPassed] = audit_mesh_axes( ...
            flatOptions.(gauges{1}),halfWidth);
        record.contractAudits = struct();
        for gaugeIndex = 1:numel(gauges)
            gauge = gauges{gaugeIndex};
            [audit,passed] = audit_config_contract( ...
                configurations.(gauge),flatOptions.(gauge), ...
                gauge,halfWidth);
            record.contractAudits.(gauge) = audit;
            record.gaugeRuns.(gauge).contractPassed = passed;
        end
        record.sharedCandidateAudit = audit_candidate_identity( ...
            configurations,gauges);
        contractPasses = cellfun(@(gauge) ...
            record.gaugeRuns.(gauge).contractPassed,gauges);
        record.preflightPassed = record.meshPassed && ...
            all(contractPasses) && record.sharedCandidateAudit.passed;
        if ~record.preflightPassed
            record.status = 'preflight_rejected';
        elseif ~settings.execute
            record.status = 'preflight_only';
        else
            [record.gaugeRuns,record.executionAudit] = ...
                execute_initial_rhs(configurations,record.gaugeRuns, ...
                gauges,limits);
            runPasses = cellfun(@(gauge)strcmp( ...
                record.gaugeRuns.(gauge).status,'completed'),gauges);
            if all(runPasses) && record.executionAudit.passed
                record.status = 'initial_rhs_complete';
            else
                record.status = 'initial_rhs_rejected';
            end
        end
    catch exception
        record.status = 'failed';
        record.errorIdentifier = exception.identifier;
        record.errorMessage = exception.message;
    end
    record.completedUtc = utc_stamp();
    screen.boxes(boxIndex) = record;
    save_summary(summaryFile,screen);
    if settings.execute
        for gaugeIndex = 1:numel(gauges)
            gauge = gauges{gaugeIndex};
            run = record.gaugeRuns.(gauge);
            append_manifest(manifestFile,struct( ...
                'event','initial_rhs_sample', ...
                'timestampUtc',record.completedUtc, ...
                'screenId',screenId, ...
                'boxHalfWidth',halfWidth, ...
                'gauge',gauge, ...
                'status',run.status, ...
                'rhsWallSeconds',run.rhsWallSeconds, ...
                'rates',run.rates, ...
                'wallQuadraticPeak',run.wallQuadraticPeak, ...
                'gradientEnergy',run.gradientEnergy, ...
                'farBoundary',run.farBoundary, ...
                'baseRhsCrossGaugeRelativeL2', ...
                    run.baseRhsCrossGaugeRelativeL2, ...
                'errorIdentifier',run.errorIdentifier, ...
                'errorMessage',run.errorMessage));
        end
    end
    append_manifest(manifestFile,struct( ...
        'event','box_finished', ...
        'timestampUtc',record.completedUtc, ...
        'screenId',screenId, ...
        'boxHalfWidth',halfWidth, ...
        'status',record.status, ...
        'meshPassed',record.meshPassed, ...
        'preflightPassed',record.preflightPassed, ...
        'rhsWallSeconds',box_rhs_wall_seconds(record,gauges), ...
        'errorIdentifier',record.errorIdentifier, ...
        'errorMessage',record.errorMessage));
end

screen.preflightPassed = all([screen.boxes.preflightPassed]);
if settings.execute
    screen.successiveComparisons = successive_comparisons( ...
        screen.boxes,gauges);
    screen.screeningGate = assess_screening_gate(screen,limits,gauges);
end
screen.totalWallSeconds = toc(totalClock);
rhsTimes = zeros(0,1);
for boxIndex = 1:numel(screen.boxes)
    for gaugeIndex = 1:numel(gauges)
        value = screen.boxes(boxIndex).gaugeRuns.( ...
            gauges{gaugeIndex}).rhsWallSeconds;
        if isfinite(value)
            rhsTimes(end+1,1) = value; %#ok<AGROW>
        end
    end
end
screen.totalRhsWallSeconds = sum(rhsTimes);
screen.failures = screen_failures(screen,settings,gauges);
if ~settings.execute
    screen.hardPassed = false;
    if screen.preflightPassed && isempty(screen.failures)
        screen.status = 'preflight_complete';
    else
        screen.status = 'preflight_rejected';
    end
else
    screen.hardPassed = screen.preflightPassed && ...
        screen.screeningGate.passed && isempty(screen.failures);
    if screen.hardPassed
        screen.status = 'screen_complete';
    elseif screen.preflightPassed && ...
            ~screen.screeningGate.checks.allInitialRhsCompleted
        screen.status = 'execution_failure';
    elseif screen.preflightPassed
        screen.status = 'screen_gate_failed';
    else
        screen.status = 'partial_failure';
    end
end
screen.completedUtc = utc_stamp();
save_summary(summaryFile,screen);
append_manifest(manifestFile,struct( ...
    'event','screen_finished', ...
    'timestampUtc',screen.completedUtc, ...
    'screenId',screenId, ...
    'status',screen.status, ...
    'preflightPassed',screen.preflightPassed, ...
    'hardPassed',screen.hardPassed, ...
    'screeningGateStatus',screen.screeningGate.status, ...
    'screeningGate',screen.screeningGate, ...
    'totalWallSeconds',screen.totalWallSeconds, ...
    'totalRhsWallSeconds',screen.totalRhsWallSeconds, ...
    'solveExecuted',false, ...
    'pdeStepsExecuted',0, ...
    'failures',{screen.failures}));

if settings.verbose
    fprintf(['Q512 C_OMEGA BOX SCREEN: status=%s, mode=%s, ' ...
        'RHS wall=%.3f s, summary=%s\n'],screen.status, ...
        screen.executionMode,screen.totalRhsWallSeconds,summaryFile);
end
end

function settings = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeLabQ512COmegaBoxOptions', ...
        'options must be a scalar structure.');
end
allowed = {'execute','preflightOnly','outputRoot','verbose'};
unknown = setdiff(fieldnames(options),allowed,'stable');
if ~isempty(unknown)
    error('ipm:GaugeLabQ512COmegaBoxOptions', ...
        'Unknown option(s): %s.',strjoin(unknown,', '));
end
executeWasSpecified = isfield(options,'execute');
settings.execute = logical_option(options,'execute',false);
settings.preflightOnly = logical_option(options,'preflightOnly',false);
if settings.preflightOnly
    if executeWasSpecified && settings.execute
        error('ipm:GaugeLabQ512COmegaBoxOptions', ...
            'execute=true and preflightOnly=true are contradictory.');
    end
    settings.execute = false;
elseif ~settings.execute
    settings.preflightOnly = true;
end
settings.outputRoot = path_option( ...
    options,'outputRoot',default_output_root());
settings.verbose = logical_option(options,'verbose',true);
end

function [flatOptions,configurations] = registered_configurations( ...
        halfWidth,gauges,screenId,outputDirectory)
flatOptions = struct();
configurations = struct();
for gaugeIndex = 1:numel(gauges)
    gauge = gauges{gaugeIndex};
    metadata = struct('q512COmegaInitialBoxScreen',struct( ...
        'schemaVersion',4, ...
        'screenId',screenId, ...
        'initialRhsOnly',true, ...
        'pdeStepsExecuted',0, ...
        'boxMode','large_box', ...
        'boxHalfWidth',halfWidth, ...
        'configurationContract','exact_gauge_no_feedback_v1', ...
        'lengthGauge','transport_anchor', ...
        'transportAnchorX',1, ...
        'cOmegaGauge',gauge));
    overrides = struct( ...
        'xlim',[-halfWidth,halfWidth], ...
        'ymax',halfWidth, ...
        'rescalingMode','dynamic', ...
        'dynamicScaleGeometry','isotropic', ...
        'scalingContract','exact_gauge_no_feedback_v1', ...
        'lengthGauge','transport_anchor', ...
        'transportAnchorX',1, ...
        'cOmegaGauge',gauge, ...
        'lengthScaleGain',1, ...
        'widthGaugeGain',0, ...
        'omegaGaugeGain',0, ...
        'travelingWaveGain',0, ...
        'spatialDiscretization','high_order', ...
        'transportScheme','weno5_fd', ...
        'timeIntegrator','ssprk54', ...
        'remeshTransferScheme','high_order', ...
        'initialAnalyticRemesh',false, ...
        'adaptiveRemesh',false, ...
        'remeshMaximumCellRatio',1.08, ...
        'resultFile',fullfile(outputDirectory,sprintf( ...
            'solver_result_must_not_exist_H%.17g.mat',halfWidth)), ...
        'saveResults',false, ...
        'storeSnapshots',false, ...
        'makePlots',false, ...
        'livePlot',false, ...
        'writeVideo',false, ...
        'verbose',false, ...
        'caseMetadata',metadata);
    if gaugeIndex == 1
        flatOptions.(gauge) = fourth_order_blowup_case( ...
            ['coordinated_log_anchor_F80_R20_large_box_' ...
            'quadrant_512'],overrides);
    else
        % The box axes and every protected option are shared exactly.  A
        % shallow configuration copy avoids regenerating the same custom
        % q512 grid merely to change the registered amplitude functional.
        flatOptions.(gauge) = flatOptions.(gauges{1});
        flatOptions.(gauge).cOmegaGauge = gauge;
        flatOptions.(gauge).caseMetadata. ...
            q512COmegaInitialBoxScreen.cOmegaGauge = gauge;
    end
    configurations.(gauge) = ipm.config.resolve( ...
        flatOptions.(gauge));
end
end

function [audit,passed] = audit_mesh_axes(options,halfWidth)
x = options.customX(:)';
y = options.customY(:);
weightsX = ipm.mesh.quadrature(x);
weightsY = ipm.mesh.quadrature(y);
qualityX = ipm.mesh.quality(x,7,weightsX);
qualityY = ipm.mesh.quality(y,7,weightsY);
[anchorDistance,anchorIndex] = min(abs(x-1));
anchorTolerance = 128*eps(max(1,max(abs(x))));
checks = struct();
checks.nodeCounts = numel(x) == 1025 && numel(y) == 513;
checks.endpoints = endpoint_close(x([1,end]),[-halfWidth,halfWidth]) && ...
    endpoint_close(y([1,end]),[0,halfWidth]);
checks.anchorExact = anchorDistance <= anchorTolerance;
checks.positiveQuadrature = ...
    qualityX.quadratureWeightsStrictlyPositive && ...
    qualityY.quadratureWeightsStrictlyPositive;
checks.adjacentCellRatio = max([qualityX.maximumAdjacentCellRatio, ...
    qualityY.maximumAdjacentCellRatio]) <= 1.08*(1+1e-12);
checks.logSpacingCurvature = max([ ...
    qualityX.maximumLogSpacingCurvature, ...
    qualityY.maximumLogSpacingCurvature]) <= 0.01*(1+1e-12);
checks.stencilRcond = min([qualityX.minimumStencilRcond, ...
    qualityY.minimumStencilRcond]) >= 1e-9*(1-1e-12);
checks.globalQuadrature = min([ ...
    qualityX.minimumQuadratureWeightRatio, ...
    qualityY.minimumQuadratureWeightRatio]) >= 1e-8*(1-1e-12);
checks.localQuadratureLower = min([ ...
    qualityX.minimumQuadratureWeightToControlWidthRatio, ...
    qualityY.minimumQuadratureWeightToControlWidthRatio]) >= ...
    0.35*(1-1e-12);
checks.localQuadratureUpper = max([ ...
    qualityX.maximumQuadratureWeightToControlWidthRatio, ...
    qualityY.maximumQuadratureWeightToControlWidthRatio]) <= ...
    1.65*(1+1e-12);
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct( ...
    'x',qualityX, ...
    'y',qualityY, ...
    'checks',checks, ...
    'failures',{failures}, ...
    'passed',passed, ...
    'anchorX',1, ...
    'nearestAnchorNode',x(anchorIndex), ...
    'anchorNodeDistance',anchorDistance, ...
    'anchorNodeTolerance',anchorTolerance, ...
    'anchorIsGridNode',checks.anchorExact);
end

function [audit,passed] = audit_config_contract( ...
        config,options,gauge,halfWidth)
scaling = config.scaling;
retired = retired_fields();
retiredPresent = unique([retired(isfield(options,retired)), ...
    retired(isfield(scaling,retired))],'stable');
checks = struct();
checks.schema4 = config.schemaVersion == 4 && config.frozen;
checks.q512 = config.grid.nx == 1025 && config.grid.ny == 513;
checks.domain = endpoint_close(config.grid.xlim, ...
    [-halfWidth,halfWidth]) && config.grid.ymax == halfWidth;
checks.numericalTuple = ...
    strcmp(config.transport.spatialDiscretization,'high_order') && ...
    strcmp(config.transport.transportScheme,'weno5_fd') && ...
    strcmp(config.time.timeIntegrator,'ssprk54') && ...
    strcmp(config.remesh.remeshTransferScheme,'high_order');
checks.dynamicIsotropic = ...
    strcmp(scaling.rescalingMode,'dynamic') && ...
    strcmp(scaling.dynamicScaleGeometry,'isotropic');
checks.exactNoFeedback = strcmp(scaling.scalingContract, ...
    'exact_gauge_no_feedback_v1') && ...
    scaling.lengthScaleGain == 1 && scaling.widthGaugeGain == 0 && ...
    scaling.omegaGaugeGain == 0 && scaling.travelingWaveGain == 0;
checks.transportAnchor = strcmp(scaling.lengthGauge, ...
    'transport_anchor') && scaling.transportAnchorX == 1;
checks.amplitudeGauge = strcmp(scaling.cOmegaGauge,gauge);
checks.activeDatum = strcmp(config.physics.initialCondition, ...
    'degenerate_primitive') && config.physics.degeneratePower == 8 && ...
    strcmp(config.physics.symmetryMode,'double_odd_omega');
checks.greenOpen = strcmp(config.elliptic.farBoundaryMode,'green') && ...
    strcmp(config.transport.transportBoundaryMode,'open');
checks.fixedMesh = ~config.remesh.initialAnalyticRemesh && ...
    ~config.remesh.adaptiveRemesh;
checks.diagnosticsOnlyOutput = ~config.output.saveResults && ...
    ~config.output.storeSnapshots && ~config.output.makePlots && ...
    ~config.output.livePlot && ~config.output.writeVideo;
checks.noRetiredFields = isempty(retiredPresent);
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct('checks',checks,'failures',{failures}, ...
    'passed',passed,'retiredFieldsPresent',{retiredPresent});
end

function audit = audit_candidate_identity(configurations,gauges)
reference = configurations.(gauges{1});
passed = true;
for index = 2:numel(gauges)
    candidate = configurations.(gauges{index});
    candidate.scaling.cOmegaGauge = reference.scaling.cOmegaGauge;
    candidate.output.caseMetadata = reference.output.caseMetadata;
    passed = passed && ...
        isequaln(orderfields(candidate),orderfields(reference));
end
audit = struct( ...
    'onlyRegisteredDifferences',{ ...
        {'scaling.cOmegaGauge','output.caseMetadata'}}, ...
    'passed',passed);
end

function [gaugeRuns,executionAudit] = execute_initial_rhs( ...
        configurations,gaugeRuns,gauges,limits)
baseConfig = configurations.(gauges{1});
meshClock = tic;
baseOps = ipm.mesh.build(baseConfig);
meshBuildWallSeconds = toc(meshClock);
rho = ipm.field.initialDensity(baseOps,baseConfig.physics);
initializationClock = tic;
baseOps = ipm.evolve.initializeScaling(rho,baseOps);
initializationWallSeconds = toc(initializationClock);

referenceBaseRhs = [];
for gaugeIndex = 1:numel(gauges)
    gauge = gauges{gaugeIndex};
    run = gaugeRuns.(gauge);
    run.status = 'rhs_running';
    rhsClock = tic;
    try
        gaugeOps = baseOps;
        gaugeOps.rescaling.cOmegaGauge = gauge;
        [rhs,flow] = ipm.evolve.rhs(rho,gaugeOps);
        run.rhsWallSeconds = toc(rhsClock);
        baseRhs = rhs-flow.canonicalCOmega*rho;
        run.rates = rate_metrics(flow);
        run.gradientEnergy = gradient_energy_metrics( ...
            rho,baseRhs,flow,gaugeOps);
        run.wallQuadraticPeak = wall_quadratic_metrics( ...
            baseRhs,flow,gaugeOps);
        run.farBoundary = far_boundary_metrics(flow,gaugeOps);
        run.field = field_metrics(rho,flow,gaugeOps);
        run.gaugeContract = ipm.evolve.gaugeContract( ...
            configurations.(gauge),gaugeOps);
        run.runtimeChecks = runtime_checks(run,gauge,limits);
        if isempty(referenceBaseRhs)
            referenceBaseRhs = baseRhs;
            run.baseRhsCrossGaugeRelativeL2 = 0;
        else
            run.baseRhsCrossGaugeRelativeL2 = norm( ...
                baseRhs(:)-referenceBaseRhs(:)) / ...
                max(norm(referenceBaseRhs(:)),realmin);
        end
        if isempty(failed_checks(run.runtimeChecks))
            run.status = 'completed';
        else
            run.status = 'runtime_rejected';
        end
    catch exception
        run.status = 'rhs_failed';
        run.errorIdentifier = exception.identifier;
        run.errorMessage = exception.message;
        if ~isfinite(run.rhsWallSeconds)
            run.rhsWallSeconds = toc(rhsClock);
        end
    end
    gaugeRuns.(gauge) = run;
end

crossGaugeValues = cellfun(@(gauge) ...
    gaugeRuns.(gauge).baseRhsCrossGaugeRelativeL2,gauges(2:end));
checks = struct();
checks.noPdeStep = true;
checks.sharedMeshBuiltOnce = isfinite(meshBuildWallSeconds);
checks.sharedInitialization = isfinite(initializationWallSeconds);
checks.bothRhsCompleted = all(cellfun(@(gauge)strcmp( ...
    gaugeRuns.(gauge).status,'completed'),gauges));
checks.baseRhsGaugeIndependent = all(isfinite(crossGaugeValues)) && ...
    max(crossGaugeValues) <= ...
    limits.maximumBaseRhsCrossGaugeRelativeL2;
executionAudit = struct( ...
    'meshBuildWallSeconds',meshBuildWallSeconds, ...
    'initializationWallSeconds',initializationWallSeconds, ...
    'meshBuildCount',1, ...
    'initializationCount',1, ...
    'rhsEvaluationCount',numel(gauges), ...
    'maximumBaseRhsCrossGaugeRelativeL2',max(crossGaugeValues), ...
    'ipmSolveCalled',false, ...
    'pdeStepsExecuted',0, ...
    'sharedInitializationJustification',[ ...
        'the_three_registered_amplitude_gauges_require_no_' ...
        'gauge_specific_initial_reference'], ...
    'checks',checks, ...
    'failures',{failed_checks(checks)}, ...
    'passed',isempty(failed_checks(checks)));
end

function metrics = rate_metrics(flow)
metrics = struct( ...
    'c_l',flow.c_l, ...
    'c_omega',flow.c_omega, ...
    'c_r',flow.c_r, ...
    'canonicalCL',flow.canonicalCL, ...
    'canonicalCOmega',flow.canonicalCOmega, ...
    'canonicalCR',flow.canonicalCR, ...
    'kappa',flow.canonicalCL-flow.canonicalCOmega, ...
    'timeSpeed',flow.timeSpeed, ...
    'lengthGaugeResidual',flow.lengthGaugeResidual, ...
    'transportAnchorVelocity',flow.transportAnchorVelocity, ...
    'omegaGaugeResidual',flow.omegaGaugeResidual);
end

function metrics = gradient_energy_metrics(rho,baseRhs,flow,ops)
rhoX = flow.source;
rhoY = ops.Dy*rho;
baseRhsX = baseRhs*ops.Dx';
baseRhsY = ops.Dy*baseRhs;
weights = ops.integrationWeights;
energyX = sum(rhoX.^2.*weights,'all');
energyY = sum(rhoY.^2.*weights,'all');
forcingX = sum(rhoX.*baseRhsX.*weights,'all');
forcingY = sum(rhoY.*baseRhsY.*weights,'all');
energy = energyX+energyY;
forcing = forcingX+forcingY;
absoluteForcing = sum(abs(rhoX.*baseRhsX+rhoY.*baseRhsY) .* ...
    weights,'all');
cancellation = forcing+flow.canonicalCOmega*energy;
cancellationScale = max([abs(forcing), ...
    abs(flow.canonicalCOmega*energy),realmin]);
metrics = struct( ...
    'energyX',energyX, ...
    'energyY',energyY, ...
    'energy',energy, ...
    'forcingX',forcingX, ...
    'forcingY',forcingY, ...
    'forcing',forcing, ...
    'absoluteForcing',absoluteForcing, ...
    'impliedCOmega',-forcing/energy, ...
    'candidateCancellation',cancellation, ...
    'candidateNormalizedCancellation',cancellation/cancellationScale, ...
    'energyYFraction',energyY/energy, ...
    'forcingYFraction',abs(forcingY)/max(abs(forcing),realmin), ...
    'energyPerXWidth',energy/(ops.x(end)-ops.x(1)), ...
    'forcingPerXWidth',forcing/(ops.x(end)-ops.x(1)));
end

function metrics = wall_quadratic_metrics(baseRhs,flow,ops)
trackingMask = abs(ops.x-ops.rescaling.pinX) <= ...
    ops.rescaling.peakTrackingHalfWidth;
feature = max(flow.source(1,:),0);
feature(~trackingMask) = 0;
[~,peakIndex] = max(feature);
peak = ipm.evolve.quadraticPeakFunctional( ...
    flow.source(1,:),ops.x,peakIndex);
stencilForcing = baseRhs(1,:)*ops.Dx(peak.indices,:)';
forcing = sum(peak.weights.*stencilForcing);
impliedCOmega = -forcing/peak.value;
rateResidual = forcing+flow.canonicalCOmega*peak.value;
rateScale = max([abs(forcing), ...
    abs(flow.canonicalCOmega*peak.value),realmin]);
competitorMask = trackingMask;
competitorMask(peakIndex) = false;
competitors = flow.source(1,competitorMask);
activeSelectionMargin = (flow.source(1,peakIndex)- ...
    max(competitors))/peak.value;
runtimeAgreement = NaN;
if isfinite(flow.omegaGaugeQuadraticPeakValue)
    scales = max(abs([peak.x,peak.value,forcing,peak.curvature, ...
        peak.curvatureCondition,peak.weightCondition, ...
        peak.activeNodeMargin,peak.vertexInteriorFraction, ...
        peak.relativeSubgridLift,rateResidual]),1);
    runtimeValues = [flow.omegaGaugeQuadraticPeakX, ...
        flow.omegaGaugeQuadraticPeakValue, ...
        flow.omegaGaugeQuadraticForcing, ...
        flow.omegaGaugeQuadraticCurvature, ...
        flow.omegaGaugeQuadraticCurvatureCondition, ...
        flow.omegaGaugeQuadraticWeightCondition, ...
        flow.omegaGaugeQuadraticActiveNodeMargin, ...
        flow.omegaGaugeQuadraticVertexInteriorFraction, ...
        flow.omegaGaugeQuadraticRelativeSubgridLift, ...
        flow.omegaGaugeQuadraticRateResidual];
    localValues = [peak.x,peak.value,forcing,peak.curvature, ...
        peak.curvatureCondition,peak.weightCondition, ...
        peak.activeNodeMargin,peak.vertexInteriorFraction, ...
        peak.relativeSubgridLift,rateResidual];
    runtimeAgreement = max(abs(runtimeValues-localValues)./scales);
end
metrics = struct( ...
    'peakIndex',peakIndex, ...
    'stencilIndices',peak.indices, ...
    'stencilWeights',peak.weights, ...
    'peakX',peak.x, ...
    'peakValue',peak.value, ...
    'forcing',forcing, ...
    'impliedCOmega',impliedCOmega, ...
    'candidateRateResidual',rateResidual, ...
    'candidateNormalizedRateResidual',rateResidual/rateScale, ...
    'curvature',peak.curvature, ...
    'normalizedStationarityResidual', ...
        peak.normalizedStationarityResidual, ...
    'curvatureCondition',peak.curvatureCondition, ...
    'weightCondition',peak.weightCondition, ...
    'activeNodeMargin',peak.activeNodeMargin, ...
    'activeSelectionMargin',activeSelectionMargin, ...
    'stencilCenterX',ops.x(peakIndex), ...
    'vertexInteriorFraction',peak.vertexInteriorFraction, ...
    'relativeSubgridLift',peak.relativeSubgridLift, ...
    'runtimeAgreementMaximumRelativeError',runtimeAgreement);
end

function metrics = far_boundary_metrics(flow,ops)
outer = false(ops.ny,ops.nx);
bandX = max(2,ceil(0.05*ops.nx));
bandY = max(2,ceil(0.05*ops.ny));
outer(:,[1:bandX,end-bandX+1:end]) = true;
outer(end-bandY+1:end,:) = true;
speed = hypot(flow.u1,flow.u2);
sourceMagnitude = abs(flow.source);
uInf = max(speed,[],'all');
omegaInf = max(sourceMagnitude,[],'all');
metrics = struct( ...
    'source',max(sourceMagnitude(outer),[],'all'), ...
    'sourceRatio',max(sourceMagnitude(outer),[],'all')/ ...
        max(omegaInf,realmin), ...
    'velocity',max(speed(outer),[],'all'), ...
    'velocityRatio',max(speed(outer),[],'all')/max(uInf,realmin), ...
    'uInf',uInf, ...
    'omegaInf',omegaInf, ...
    'outerBandFraction',0.05);
end

function metrics = field_metrics(rho,flow,ops)
rhoX = flow.source;
rhoY = ops.Dy*rho;
metrics = struct( ...
    'rhoMinimum',min(rho,[],'all'), ...
    'rhoMaximum',max(rho,[],'all'), ...
    'rhoXInf',max(abs(rhoX),[],'all'), ...
    'rhoYInf',max(abs(rhoY),[],'all'), ...
    'gradientInf',max(hypot(rhoX,rhoY),[],'all'), ...
    'wallOmegaPeak',max(rhoX(1,:)), ...
    'transportAnchorNodeDistance', ...
        min(abs(ops.x-ops.rescaling.transportAnchorX)));
end

function checks = runtime_checks(run,gauge,limits)
rates = run.rates;
quadratic = run.wallQuadraticPeak;
checks = struct();
checks.finiteRates = all(isfinite([rates.c_l,rates.c_omega, ...
    rates.c_r,rates.kappa]));
checks.directClock = rates.timeSpeed == 1;
checks.exactLengthGauge = abs(rates.lengthGaugeResidual) <= ...
    1e-12*max(abs(rates.c_l),1);
checks.anchorVelocityZero = abs(rates.transportAnchorVelocity) <= ...
    1e-12*max(abs(rates.c_l),1);
gradient = run.gradientEnergy;
checks.finiteGradientDiagnostics = all(isfinite([ ...
    gradient.energyX,gradient.energyY,gradient.energy, ...
    gradient.forcingX,gradient.forcingY,gradient.forcing, ...
    gradient.absoluteForcing,gradient.impliedCOmega, ...
    gradient.candidateCancellation, ...
    gradient.candidateNormalizedCancellation, ...
    gradient.energyYFraction,gradient.forcingYFraction, ...
    gradient.energyPerXWidth,gradient.forcingPerXWidth]));
far = run.farBoundary;
checks.finiteFarBoundaryDiagnostics = all(isfinite([ ...
    far.source,far.sourceRatio,far.velocity,far.velocityRatio, ...
    far.uInf,far.omegaInf,far.outerBandFraction]));
checks.finiteQuadraticDiagnostics = all(isfinite([ ...
    quadratic.peakIndex,quadratic.stencilIndices, ...
    quadratic.stencilWeights,quadratic.peakX,quadratic.peakValue, ...
    quadratic.forcing,quadratic.impliedCOmega, ...
    quadratic.candidateRateResidual, ...
    quadratic.candidateNormalizedRateResidual, ...
    quadratic.curvature, ...
    quadratic.normalizedStationarityResidual, ...
    quadratic.curvatureCondition,quadratic.weightCondition, ...
    quadratic.activeNodeMargin,quadratic.activeSelectionMargin, ...
    quadratic.stencilCenterX,quadratic.vertexInteriorFraction, ...
    quadratic.relativeSubgridLift]));
switch gauge
    case 'wall_omega_quadratic_peak'
        checks.quadraticRuntimeAgreement = isfinite( ...
            quadratic.runtimeAgreementMaximumRelativeError) && ...
            quadratic.runtimeAgreementMaximumRelativeError <= ...
            limits.maximumQuadraticRuntimeAgreementError;
        checks.quadraticGaugeResidual = abs( ...
            quadratic.candidateNormalizedRateResidual) <= 1e-12;
    case 'gradient_energy'
        checks.gradientGaugeResidual = abs( ...
            run.gradientEnergy.candidateNormalizedCancellation) <= 1e-12;
    case 'none'
        checks.noneGaugeExact = rates.c_omega == 0 && ...
            rates.canonicalCOmega == 0 && rates.omegaGaugeResidual == 0;
    otherwise
        checks.registeredGauge = false;
end
end

function comparisons = successive_comparisons(boxes,gauges)
comparisons = repmat(empty_comparison(), ...
    (numel(boxes)-1)*numel(gauges),1);
cursor = 0;
for gaugeIndex = 1:numel(gauges)
    gauge = gauges{gaugeIndex};
    for boxIndex = 1:numel(boxes)-1
        cursor = cursor+1;
        comparison = empty_comparison();
        comparison.gauge = gauge;
        comparison.referenceHalfWidth = boxes(boxIndex).boxHalfWidth;
        comparison.candidateHalfWidth = boxes(boxIndex+1).boxHalfWidth;
        reference = boxes(boxIndex).gaugeRuns.(gauge);
        candidate = boxes(boxIndex+1).gaugeRuns.(gauge);
        if strcmp(reference.status,'completed') && ...
                strcmp(candidate.status,'completed')
            comparison.available = true;
            comparison.status = 'compared';
            comparison.relativeDifferences = scalar_differences( ...
                reference,candidate);
            comparison.growthRatios = scalar_growth_ratios( ...
                reference,candidate,comparison.referenceHalfWidth, ...
                comparison.candidateHalfWidth);
        else
            comparison.status = 'rhs_unavailable';
        end
        comparisons(cursor) = comparison;
    end
end
end

function differences = scalar_differences(reference,candidate)
differences = struct( ...
    'c_l',relative_difference(reference.rates.c_l, ...
        candidate.rates.c_l), ...
    'c_omega',relative_difference(reference.rates.c_omega, ...
        candidate.rates.c_omega), ...
    'kappa',abs(reference.rates.kappa-candidate.rates.kappa) / ...
        max([abs(reference.rates.c_l), ...
        abs(reference.rates.c_omega),abs(candidate.rates.c_l), ...
        abs(candidate.rates.c_omega),realmin]), ...
    'gradientEnergyX',relative_difference( ...
        reference.gradientEnergy.energyX, ...
        candidate.gradientEnergy.energyX), ...
    'gradientEnergyY',relative_difference( ...
        reference.gradientEnergy.energyY, ...
        candidate.gradientEnergy.energyY), ...
    'gradientEnergy',relative_difference( ...
        reference.gradientEnergy.energy, ...
        candidate.gradientEnergy.energy), ...
    'gradientForcingX',relative_difference( ...
        reference.gradientEnergy.forcingX, ...
        candidate.gradientEnergy.forcingX), ...
    'gradientForcingY',relative_difference( ...
        reference.gradientEnergy.forcingY, ...
        candidate.gradientEnergy.forcingY), ...
    'gradientForcing',relative_difference( ...
        reference.gradientEnergy.forcing, ...
        candidate.gradientEnergy.forcing), ...
    'gradientAbsoluteForcing',relative_difference( ...
        reference.gradientEnergy.absoluteForcing, ...
        candidate.gradientEnergy.absoluteForcing), ...
    'quadraticPeakX',relative_difference( ...
        reference.wallQuadraticPeak.peakX, ...
        candidate.wallQuadraticPeak.peakX), ...
    'quadraticPeakValue',relative_difference( ...
        reference.wallQuadraticPeak.peakValue, ...
        candidate.wallQuadraticPeak.peakValue), ...
    'quadraticForcing',relative_difference( ...
        reference.wallQuadraticPeak.forcing, ...
        candidate.wallQuadraticPeak.forcing), ...
    'farBoundarySourceRatioAbsolute',abs( ...
        reference.farBoundary.sourceRatio- ...
        candidate.farBoundary.sourceRatio), ...
    'farBoundaryVelocityRatioAbsolute',abs( ...
        reference.farBoundary.velocityRatio- ...
        candidate.farBoundary.velocityRatio));
end

function ratios = scalar_growth_ratios( ...
        reference,candidate,referenceHalfWidth,candidateHalfWidth)
ratios = struct( ...
    'boxHalfWidth',candidateHalfWidth/referenceHalfWidth, ...
    'gradientEnergyX',candidate.gradientEnergy.energyX/ ...
        max(abs(reference.gradientEnergy.energyX),realmin), ...
    'gradientEnergyY',candidate.gradientEnergy.energyY/ ...
        max(abs(reference.gradientEnergy.energyY),realmin), ...
    'gradientEnergy',candidate.gradientEnergy.energy/ ...
        max(abs(reference.gradientEnergy.energy),realmin), ...
    'gradientForcingXMagnitude',abs( ...
        candidate.gradientEnergy.forcingX)/ ...
        max(abs(reference.gradientEnergy.forcingX),realmin), ...
    'gradientForcingYMagnitude',abs( ...
        candidate.gradientEnergy.forcingY)/ ...
        max(abs(reference.gradientEnergy.forcingY),realmin), ...
    'gradientForcingMagnitude',abs(candidate.gradientEnergy.forcing)/ ...
        max(abs(reference.gradientEnergy.forcing),realmin), ...
    'gradientAbsoluteForcing', ...
        candidate.gradientEnergy.absoluteForcing/ ...
        max(abs(reference.gradientEnergy.absoluteForcing),realmin));
end

function gate = assess_screening_gate(screen,limits,gauges)
gate = empty_screening_gate();
gate.status = 'assessing';
target = target_comparison(screen.successiveComparisons, ...
    'gradient_energy',1e5,1e6);
quadraticTarget = target_comparison(screen.successiveComparisons, ...
    'wall_omega_quadratic_peak',1e5,1e6);
noneTarget = target_comparison(screen.successiveComparisons, ...
    'none',1e5,1e6);
gate.targetComparison = struct( ...
    'referenceHalfWidth',1e5,'candidateHalfWidth',1e6);
gate.gradientEnergy = assess_gradient_candidate(target,limits);
gate.wallOmegaQuadraticPeak = assess_quadratic_candidate( ...
    quadraticTarget,screen.boxes,limits);
gate.none = assess_none_candidate(noneTarget,screen.boxes,limits);
checks = struct();
checks.allPreflightsPassed = screen.preflightPassed;
checks.allInitialRhsCompleted = all(arrayfun(@(box)all(cellfun( ...
    @(gauge)strcmp(box.gaugeRuns.(gauge).status,'completed'), ...
    gauges)),screen.boxes));
checks.gradientNegativeControlRejected = ...
    gate.gradientEnergy.rejectedForExtensiveNormalization;
checks.quadraticCandidateAdmissible = ...
    gate.wallOmegaQuadraticPeak.eligible;
checks.noneExploratoryControlValid = gate.none.initialScreenPassed && ...
    gate.none.promotionBlocked;
gate.checks = checks;
gate.failures = failed_checks(checks);
gate.passed = isempty(gate.failures);
if gate.passed
    gate.status = 'passed';
    gate.decision = ...
        'quadratic_candidate_admissible_for_time_evolution_screen';
else
    gate.status = 'gate_failed';
    gate.decision = 'no_candidate_promotion_from_initial_box_screen';
end
end

function assessment = assess_none_candidate(comparison,boxes,limits)
assessment = struct( ...
    'status','comparison_unavailable', ...
    'initialScreenPassed',false, ...
    'eligible',false, ...
    'promotionBlocked',true, ...
    'promotionEvidenceRequired',{ ...
        {'time_evolved_fields','box_refinement','cfl_refinement'}}, ...
    'checks',struct(), ...
    'failures',{{}});
if ~comparison.available
    assessment.failures = {'targetComparisonAvailable'};
    return
end
endpointBoxes = boxes([boxes.boxHalfWidth] >= 1e5);
exactRates = false(size(endpointBoxes));
exactResiduals = false(size(endpointBoxes));
for index = 1:numel(endpointBoxes)
    run = endpointBoxes(index).gaugeRuns.none;
    exactRates(index) = run.rates.c_omega == 0 && ...
        run.rates.canonicalCOmega == 0;
    exactResiduals(index) = run.rates.omegaGaugeResidual == 0;
end
difference = comparison.relativeDifferences;
checks = struct();
checks.exactZeroRate = all(exactRates);
checks.exactZeroResidual = all(exactResiduals);
checks.cLConverged = difference.c_l <= ...
    limits.maximumSuccessiveCLRelativeDifference;
checks.kappaConverged = difference.kappa <= ...
    limits.maximumSuccessiveKappaRelativeDifference;
checks.zeroRateNotTreatedAsConvergenceEvidence = true;
checks.noTimeEvolvedPromotion = true;
assessment.checks = checks;
assessment.failures = failed_checks(checks);
assessment.initialScreenPassed = isempty(assessment.failures);
assessment.eligible = false;
assessment.promotionBlocked = true;
if assessment.initialScreenPassed
    assessment.status = [ ...
        'exploratory_zero_rate_control_passed_requires_' ...
        'time_field_box_cfl_evidence'];
else
    assessment.status = 'exploratory_zero_rate_control_rejected';
end
end

function assessment = assess_gradient_candidate(comparison,limits)
assessment = struct( ...
    'status','comparison_unavailable', ...
    'eligible',false, ...
    'normalizationConverged',false, ...
    'extensivityDetected',false, ...
    'rejectedForExtensiveNormalization',false, ...
    'passedAsNegativeControl',false, ...
    'checks',struct(), ...
    'failures',{{}});
if ~comparison.available
    assessment.failures = {'targetComparisonAvailable'};
    return
end
difference = comparison.relativeDifferences;
growth = comparison.growthRatios;
checks = struct();
checks.rateConverged = difference.c_omega <= ...
    limits.maximumSuccessiveCOmegaRelativeDifference;
checks.energyConverged = difference.gradientEnergy <= ...
    limits.maximumGradientEnergyRelativeDifference;
checks.forcingConverged = difference.gradientForcing <= ...
    limits.maximumGradientForcingRelativeDifference;
checks.absoluteForcingConverged = ...
    difference.gradientAbsoluteForcing <= ...
    limits.maximumGradientAbsoluteForcingRelativeDifference;
checks.energyExtensive = growth.gradientEnergy >= ...
    limits.minimumExtensiveGrowthRatio;
checks.normalEnergyExtensive = growth.gradientEnergyY >= ...
    limits.minimumExtensiveGrowthRatio;
checks.forcingExtensive = growth.gradientForcingMagnitude >= ...
    limits.minimumExtensiveGrowthRatio;
checks.normalForcingExtensive = growth.gradientForcingYMagnitude >= ...
    limits.minimumExtensiveGrowthRatio;
checks.absoluteForcingExtensive = growth.gradientAbsoluteForcing >= ...
    limits.minimumExtensiveGrowthRatio;
assessment.checks = checks;
assessment.normalizationConverged = checks.energyConverged && ...
    checks.forcingConverged;
assessment.extensivityDetected = checks.energyExtensive && ...
    checks.normalEnergyExtensive && checks.forcingExtensive && ...
    checks.normalForcingExtensive;
assessment.eligible = checks.rateConverged && ...
    assessment.normalizationConverged;
assessment.rejectedForExtensiveNormalization = ...
    ~assessment.normalizationConverged && assessment.extensivityDetected;
assessment.passedAsNegativeControl = ...
    assessment.rejectedForExtensiveNormalization;
if assessment.rejectedForExtensiveNormalization
    assessment.status = 'rejected_extensive_global_normalization';
    assessment.failures = cell(0,1);
elseif assessment.eligible
    assessment.status = 'eligible';
    assessment.failures = {'negativeControlDidNotExposeExtensivity'};
else
    assessment.status = 'rejected_inconclusive';
    assessment.failures = {'extensivityNotResolved'};
end
end

function assessment = assess_quadratic_candidate( ...
        comparison,boxes,limits)
assessment = struct( ...
    'status','comparison_unavailable', ...
    'eligible',false, ...
    'checks',struct(), ...
    'failures',{{}});
if ~comparison.available
    assessment.failures = {'targetComparisonAvailable'};
    return
end
endpointMask = [boxes.boxHalfWidth] >= 1e5;
endpointBoxes = boxes(endpointMask);
residuals = NaN(size(endpointBoxes));
curvatureConditions = NaN(size(endpointBoxes));
weightConditions = NaN(size(endpointBoxes));
interiorFractions = NaN(size(endpointBoxes));
nodeMargins = NaN(size(endpointBoxes));
selectionMargins = NaN(size(endpointBoxes));
runtimeAgreement = NaN(size(endpointBoxes));
for index = 1:numel(endpointBoxes)
    run = endpointBoxes(index).gaugeRuns.wall_omega_quadratic_peak;
    diagnostic = run.wallQuadraticPeak;
    residuals(index) = abs( ...
        diagnostic.candidateNormalizedRateResidual);
    curvatureConditions(index) = diagnostic.curvatureCondition;
    weightConditions(index) = diagnostic.weightCondition;
    interiorFractions(index) = diagnostic.vertexInteriorFraction;
    nodeMargins(index) = diagnostic.activeNodeMargin;
    selectionMargins(index) = diagnostic.activeSelectionMargin;
    runtimeAgreement(index) = ...
        diagnostic.runtimeAgreementMaximumRelativeError;
end
difference = comparison.relativeDifferences;
checks = struct();
checks.cLConverged = difference.c_l <= ...
    limits.maximumSuccessiveCLRelativeDifference;
checks.cOmegaConverged = difference.c_omega <= ...
    limits.maximumSuccessiveCOmegaRelativeDifference;
checks.kappaConverged = difference.kappa <= ...
    limits.maximumSuccessiveKappaRelativeDifference;
checks.peakValueConverged = difference.quadraticPeakValue <= ...
    limits.maximumQuadraticPeakRelativeDifference;
checks.forcingConverged = difference.quadraticForcing <= ...
    limits.maximumQuadraticForcingRelativeDifference;
checks.exactRateResidual = max(residuals) <= ...
    limits.maximumQuadraticNormalizedRateResidual;
checks.curvatureResolved = min(curvatureConditions) >= ...
    limits.minimumQuadraticCurvatureCondition;
checks.weightsResolved = min(weightConditions) >= ...
    limits.minimumQuadraticWeightCondition;
checks.vertexInterior = min(interiorFractions) >= ...
    limits.minimumQuadraticVertexInteriorFraction;
checks.activeNode = min(nodeMargins) >= ...
    limits.minimumQuadraticActiveNodeMargin;
checks.activeSelection = min(selectionMargins) >= ...
    limits.minimumQuadraticActiveSelectionMargin;
checks.runtimeAgreement = max(runtimeAgreement) <= ...
    limits.maximumQuadraticRuntimeAgreementError;
assessment.checks = checks;
assessment.failures = failed_checks(checks);
assessment.eligible = isempty(assessment.failures);
if assessment.eligible
    assessment.status = ...
        'admissible_for_time_evolution_screen_not_promoted';
else
    assessment.status = 'rejected_initial_box_screen';
end
end

function comparison = target_comparison( ...
        comparisons,gauge,referenceHalfWidth,candidateHalfWidth)
mask = strcmp({comparisons.gauge},gauge) & ...
    [comparisons.referenceHalfWidth] == referenceHalfWidth & ...
    [comparisons.candidateHalfWidth] == candidateHalfWidth;
index = find(mask,1,'first');
if isempty(index)
    comparison = empty_comparison();
    comparison.gauge = gauge;
    comparison.referenceHalfWidth = referenceHalfWidth;
    comparison.candidateHalfWidth = candidateHalfWidth;
else
    comparison = comparisons(index);
end
end

function failures = screen_failures(screen,settings,gauges)
failures = cell(0,1);
for boxIndex = 1:numel(screen.boxes)
    box = screen.boxes(boxIndex);
    if ~box.preflightPassed
        failures{end+1,1} = sprintf( ...
            'box_%g_preflight',box.boxHalfWidth); %#ok<AGROW>
    end
    if settings.execute
        for gaugeIndex = 1:numel(gauges)
            gauge = gauges{gaugeIndex};
            if ~strcmp(box.gaugeRuns.(gauge).status,'completed')
                failures{end+1,1} = sprintf( ...
                    'box_%g_%s_rhs',box.boxHalfWidth,gauge); %#ok<AGROW>
            end
        end
    end
end
if settings.execute && ~screen.screeningGate.passed
    failures{end+1,1} = 'screening_gate';
end
end

function record = empty_box_record(gauges)
gaugeRuns = struct();
for index = 1:numel(gauges)
    gaugeRuns.(gauges{index}) = empty_gauge_run(gauges{index});
end
record = struct( ...
    'index',NaN, ...
    'boxHalfWidth',NaN, ...
    'domain',struct(), ...
    'status','', ...
    'startedUtc','', ...
    'completedUtc','', ...
    'meshPassed',false, ...
    'meshAudit',struct(), ...
    'preflightPassed',false, ...
    'contractAudits',struct(), ...
    'sharedCandidateAudit',struct(), ...
    'configurations',struct(), ...
    'gaugeRuns',gaugeRuns, ...
    'executionAudit',struct(), ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function run = empty_gauge_run(gauge)
run = struct( ...
    'gauge',gauge, ...
    'status','not_executed', ...
    'contractPassed',false, ...
    'rhsWallSeconds',NaN, ...
    'baseRhsCrossGaugeRelativeL2',NaN, ...
    'rates',struct(), ...
    'wallQuadraticPeak',struct(), ...
    'gradientEnergy',struct(), ...
    'farBoundary',struct(), ...
    'field',struct(), ...
    'gaugeContract',struct(), ...
    'runtimeChecks',struct(), ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function comparison = empty_comparison()
comparison = struct( ...
    'gauge','', ...
    'referenceHalfWidth',NaN, ...
    'candidateHalfWidth',NaN, ...
    'available',false, ...
    'status','not_executed', ...
    'relativeDifferences',struct(), ...
    'growthRatios',struct());
end

function gate = empty_screening_gate()
gate = struct( ...
    'status','not_executed', ...
    'targetComparison',struct(), ...
    'gradientEnergy',struct(), ...
    'wallOmegaQuadraticPeak',struct(), ...
    'none',struct(), ...
    'checks',struct(), ...
    'failures',{{}}, ...
    'decision','not_executed', ...
    'passed',false);
end

function limits = registered_limits()
limits = struct( ...
    'maximumSuccessiveCLRelativeDifference',1e-2, ...
    'maximumSuccessiveCOmegaRelativeDifference',1e-2, ...
    'maximumSuccessiveKappaRelativeDifference',1e-2, ...
    'maximumGradientEnergyRelativeDifference',1e-2, ...
    'maximumGradientForcingRelativeDifference',2e-2, ...
    'maximumGradientAbsoluteForcingRelativeDifference',2e-2, ...
    'minimumExtensiveGrowthRatio',5, ...
    'maximumQuadraticPeakRelativeDifference',1e-2, ...
    'maximumQuadraticForcingRelativeDifference',2e-2, ...
    'maximumQuadraticNormalizedRateResidual',1e-12, ...
    'minimumQuadraticCurvatureCondition',1e-6, ...
    'minimumQuadraticWeightCondition',0.25, ...
    'minimumQuadraticVertexInteriorFraction',0.05, ...
    'minimumQuadraticActiveNodeMargin',1e-12, ...
    'minimumQuadraticActiveSelectionMargin',1e-12, ...
    'maximumQuadraticRuntimeAgreementError',1e-11, ...
    'maximumBaseRhsCrossGaugeRelativeL2',1e-12);
end

function rules = registered_gauge_rules()
rules = struct( ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'clock','canonical_tau_direct_timeSpeed_1', ...
    'lengthGauge','transport_anchor', ...
    'lengthObservable','V_1(1,0)=0', ...
    'lengthFormula','c_l=-U_1(1,0)', ...
    'amplitudeCandidates',struct( ...
        'gradient_energy',struct( ...
            'role','extensive_negative_control', ...
            'observable','global_discrete_gradient_energy', ...
            'formula',[ ...
                'c_omega=-sum(w*(R_X*B_X+R_Y*B_Y))/' ...
                'sum(w*(R_X^2+R_Y^2))']), ...
        'wall_omega_quadratic_peak',struct( ...
            'role','local_candidate', ...
            'observable','tracked_wall_omega_quadratic_peak', ...
            'formula',[ ...
                'c_omega=-Q[B_X](X_vertex)/' ...
                'Q[R_X](X_vertex)']), ...
        'none',struct( ...
            'role','exploratory_zero_rate_control', ...
            'observable','unscaled_amplitude', ...
            'formula','c_omega=0', ...
            'scaleEvolution','C_omega(tau)=1', ...
            'rationale',[ ...
                'density_maximum_principle_preserves_amplitude_' ...
                'without_renormalization'], ...
            'promotionPolicy',[ ...
                'cannot_win_from_identically_zero_rate; requires_' ...
                'time_evolved_field_box_and_cfl_evidence'])), ...
    'rateLimiter','absent', ...
    'feedbackGains',[1,0,0,0]);
end

function requested = requested_summary(settings)
requested = struct( ...
    'execute',settings.execute, ...
    'preflightOnly',settings.preflightOnly, ...
    'defaultExecution','preflight_only', ...
    'resourceWarning',[ ...
        'execute_builds_five_q512_sparse_poisson_factorizations_' ...
        'sequentially'], ...
    'pdeSteps',0, ...
    'ipmSolveCalled',false, ...
    'saveSolverResults',false, ...
    'writeCheckpoints',false, ...
    'fixedBoxHalfWidths',true, ...
    'fixedGaugeCandidates',true);
end

function value = box_rhs_wall_seconds(record,gauges)
values = cellfun(@(gauge) ...
    record.gaugeRuns.(gauge).rhsWallSeconds,gauges);
values = values(isfinite(values));
if isempty(values)
    value = 0;
else
    value = sum(values);
end
end

function value = relative_difference(first,second)
value = abs(first-second)/max([abs(first),abs(second),realmin]);
end

function failures = failed_checks(checks)
names = fieldnames(checks);
failures = names(~cellfun(@(name)isequal(checks.(name),true),names));
failures = failures(:)';
end

function names = retired_fields()
names = {'maxDynamicRate','adaptiveGain','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
end

function mode = execution_mode(settings)
if settings.execute
    mode = 'initial_rhs';
else
    mode = 'preflight_only';
end
end

function value = logical_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
valid = (islogical(value) && isscalar(value)) || ...
    (isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && any(value == [0,1]));
if ~valid
    error('ipm:GaugeLabQ512COmegaBoxOptions', ...
        'Option %s must be a logical scalar.',name);
end
value = logical(value);
end

function value = path_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabQ512COmegaBoxOptions', ...
        'Option %s must be a nonempty path.',name);
end
end

function root = default_output_root()
fileName = mfilename('fullpath');
laboratoryDirectory = fileparts(fileName);
researchDirectory = fileparts(laboratoryDirectory);
repositoryRoot = fileparts(researchDirectory);
root = fullfile(repositoryRoot,'result','verification', ...
    'q512_comega_initial_box_screens_v4');
end

function [directory,screenId] = create_output_directory(root)
if ~isfolder(root)
    mkdir(root);
end
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
[~,token] = fileparts(tempname);
screenId = sprintf('screen_%s_%s',stamp,token);
directory = fullfile(root,screenId);
if isfile(directory) || isfolder(directory)
    error('ipm:GaugeLabQ512COmegaBoxOutputCollision', ...
        'Output path already exists: %s',directory);
end
mkdir(directory);
end

function save_summary(fileName,screen)
save(fileName,'screen');
end

function append_manifest(fileName,record)
fileId = fopen(fileName,'a');
if fileId < 0
    error('ipm:GaugeLabQ512COmegaBoxManifest', ...
        'Could not append manifest %s.',fileName);
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function require_factory()
if exist('fourth_order_blowup_case','file') ~= 2
    error('ipm:GaugeLabQ512COmegaBoxPath', ...
        ['fourth_order_blowup_case is not on the MATLAB path.  Add ' ...
        'research/experiments before calling this runner.']);
end
end

function tf = endpoint_close(actual,expected)
actual = actual(:);
expected = expected(:);
scale = max([ones(size(actual)),abs(actual),abs(expected)],[],2);
tf = numel(actual) == numel(expected) && ...
    all(abs(actual-expected) <= 100*eps(scale));
end

function value = utc_stamp()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
