function report = ipm_gaugelab_test_q512_comega_box_screen()
%IPM_GAUGELAB_TEST_Q512_COMEGA_BOX_SCREEN No-RHS protocol preflight.

laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    laboratoryDirectory);

temporaryRoot = [tempname,'_q512_comega_box_preflight'];
mkdir(temporaryRoot);
cleanup = onCleanup(@()remove_temporary_root(temporaryRoot));
screen = ipm_gaugelab_screen_q512_comega_box(struct( ...
    'outputRoot',temporaryRoot,'verbose',false));

expectedBoxes = [281,1e3,1e4,1e5,1e6];
expectedGauges = { ...
    'gradient_energy','wall_omega_quadratic_peak','none'};
assert(screen.schemaVersion == 4 && ...
    strcmp(screen.kind,'q512_initial_rhs_comega_box_screen') && ...
    strcmp(screen.status,'preflight_complete') && ...
    strcmp(screen.executionMode,'preflight_only') && ...
    screen.initialRhsOnly && ~screen.solveExecuted && ...
    screen.pdeStepsExecuted == 0 && ...
    screen.freshInitialData && ~screen.checkpointInputsAccepted && ...
    ~screen.lateTimeEvidence && ~screen.truncationEvidence && ...
    screen.preflightPassed && ~screen.hardPassed && ...
    ~screen.requested.execute && screen.requested.preflightOnly && ...
    strcmp(screen.requested.defaultExecution,'preflight_only') && ...
    strcmp(screen.screeningGate.status,'not_executed'), ...
    'ipm:GaugeLabQ512COmegaBoxTestProtocol', ...
    'The q512 c_omega initial-box protocol changed.');

assert(isequal(screen.boxHalfWidths,expectedBoxes) && ...
    isequal(screen.gauges,expectedGauges) && ...
    numel(screen.boxes) == numel(expectedBoxes) && ...
    all(strcmp({screen.boxes.status},'preflight_only')) && ...
    all([screen.boxes.meshPassed]) && ...
    all([screen.boxes.preflightPassed]) && ...
    all(arrayfun(@(box)box.meshAudit.anchorIsGridNode,screen.boxes)), ...
    'ipm:GaugeLabQ512COmegaBoxTestBoxes', ...
    'A fixed anchor-aligned q512 box failed preflight.');

for boxIndex = 1:numel(screen.boxes)
    box = screen.boxes(boxIndex);
    assert(box.sharedCandidateAudit.passed, ...
        'ipm:GaugeLabQ512COmegaBoxTestCandidateIdentity', ...
        'Candidates differ outside the registered gauge metadata.');
    for gaugeIndex = 1:numel(expectedGauges)
        gauge = expectedGauges{gaugeIndex};
        config = box.configurations.(gauge);
        audit = box.contractAudits.(gauge);
        run = box.gaugeRuns.(gauge);
        assert(config.schemaVersion == 4 && config.frozen && ...
            audit.passed && run.contractPassed && ...
            strcmp(run.status,'not_executed') && ...
            isnan(run.rhsWallSeconds) && ...
            strcmp(config.scaling.lengthGauge,'transport_anchor') && ...
            config.scaling.transportAnchorX == 1 && ...
            strcmp(config.scaling.cOmegaGauge,gauge) && ...
            strcmp(config.scaling.scalingContract, ...
                'exact_gauge_no_feedback_v1') && ...
            strcmp(config.transport.spatialDiscretization,'high_order') && ...
            strcmp(config.transport.transportScheme,'weno5_fd') && ...
            strcmp(config.time.timeIntegrator,'ssprk54') && ...
            strcmp(config.remesh.remeshTransferScheme,'high_order'), ...
            'ipm:GaugeLabQ512COmegaBoxTestContract', ...
            'A protected configuration field changed.');
    end
end

limits = screen.hardLimits;
requiredLimits = {'maximumSuccessiveCOmegaRelativeDifference', ...
    'maximumGradientEnergyRelativeDifference', ...
    'maximumGradientForcingRelativeDifference', ...
    'minimumExtensiveGrowthRatio', ...
    'maximumQuadraticPeakRelativeDifference', ...
    'maximumQuadraticForcingRelativeDifference', ...
    'maximumQuadraticNormalizedRateResidual', ...
    'minimumQuadraticCurvatureCondition', ...
    'maximumBaseRhsCrossGaugeRelativeL2'};
assert(all(isfield(limits,requiredLimits)) && ...
    strcmp(screen.registeredGaugeRules. ...
        amplitudeCandidates.gradient_energy.role, ...
        'extensive_negative_control') && ...
    strcmp(screen.registeredGaugeRules. ...
        amplitudeCandidates.wall_omega_quadratic_peak.role, ...
        'local_candidate') && ...
    strcmp(screen.registeredGaugeRules. ...
        amplitudeCandidates.none.role, ...
        'exploratory_zero_rate_control') && ...
    isequal(screen.noneGaugePromotionEvidenceRequired, ...
        {'time_evolved_fields','box_refinement','cfl_refinement'}), ...
    'ipm:GaugeLabQ512COmegaBoxTestLimits', ...
    'The preregistered negative-control or local-candidate gate changed.');

assert(isfile(screen.summaryFile) && isfile(screen.manifestFile) && ...
    isempty(dir(fullfile(temporaryRoot,'**','result.mat'))) && ...
    isempty(dir(fullfile(temporaryRoot,'**', ...
        'solver_result_must_not_exist*.mat'))) && ...
    isempty(dir(fullfile(temporaryRoot,'**','checkpoint*.mat'))), ...
    'ipm:GaugeLabQ512COmegaBoxTestNoRhs', ...
    'Preflight omitted evidence or wrote solver artifacts.');
loaded = load(screen.summaryFile,'screen');
assert(strcmp(loaded.screen.status,'preflight_complete') && ...
    loaded.screen.schemaVersion == 4 && loaded.screen.preflightPassed, ...
    'ipm:GaugeLabQ512COmegaBoxTestSavedSummary', ...
    'The final schema-4 preflight summary was not saved.');

conflictRejected = false;
try
    ipm_gaugelab_screen_q512_comega_box(struct( ...
        'execute',true,'preflightOnly',true));
catch exception
    conflictRejected = strcmp(exception.identifier, ...
        'ipm:GaugeLabQ512COmegaBoxOptions');
end
checkpointRejected = false;
try
    ipm_gaugelab_screen_q512_comega_box(struct( ...
        'checkpoint','forbidden.mat'));
catch exception
    checkpointRejected = strcmp(exception.identifier, ...
        'ipm:GaugeLabQ512COmegaBoxOptions');
end
assert(conflictRejected && checkpointRejected, ...
    'ipm:GaugeLabQ512COmegaBoxTestOptions', ...
    'The screen accepted contradictory execution or checkpoint input.');

report = struct( ...
    'status',screen.status, ...
    'boxHalfWidths',screen.boxHalfWidths, ...
    'gauges',{screen.gauges}, ...
    'schemaVersion',screen.schemaVersion, ...
    'preflightPassed',screen.preflightPassed, ...
    'rhsExecuted',false, ...
    'conflictRejected',conflictRejected, ...
    'checkpointRejected',checkpointRejected);
clear cleanup;
fprintf('Q512 c_omega box screen preflight: boxes=%d, gauges=%d.\n', ...
    numel(report.boxHalfWidths),numel(report.gauges));
end

function remove_temporary_root(pathName)
if isfolder(pathName)
    rmdir(pathName,'s');
end
end
