function report = ipm_gaugelab_test_q512_box_ladder()
%IPM_GAUGELAB_TEST_Q512_BOX_LADDER Lightweight no-PDE gate preflight.

laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    laboratoryDirectory);

temporaryRoot = [tempname,'_q512_box_preflight'];
mkdir(temporaryRoot);
cleanup = onCleanup(@()remove_temporary_root(temporaryRoot));
ladder = ipm_gaugelab_run_q512_box_ladder(struct( ...
    'outputRoot',temporaryRoot,'verbose',false));

assert(strcmp(ladder.status,'preflight_complete') && ...
    strcmp(ladder.executionMode,'preflight_only') && ...
    ladder.freshRootsOnly && ~ladder.checkpointInputsAccepted && ...
    ~ladder.hardPassed && ...
    ladder.campaignBoxHalfWidth == 1e6 && ...
    strcmp(ladder.campaignBoxGate.status,'not_executed') && ...
    ~ladder.campaignBoxGate.passed, ...
    'ipm:GaugeLabQ512BoxTestProtocol', ...
    'The q512 box-ladder execution guard or campaign gate changed.');

expectedHalfWidths = [281,1e3,1e4,1e5,1e6];
assert(isequal(ladder.boxHalfWidths,expectedHalfWidths) && ...
    numel(ladder.rungs) == numel(expectedHalfWidths)+1 && ...
    strcmp(ladder.matchedReference,'matched_281') && ...
    strcmp(ladder.anchorAlignedControl,'large_281') && ...
    all(strcmp({ladder.rungs.status},'preflight_only')) && ...
    all([ladder.rungs.meshPassed]) && ...
    all([ladder.rungs.contractPassed]) && ...
    ~ladder.rungs(1).anchorIsGridNode && ...
    all([ladder.rungs(2:end).anchorIsGridNode]) && ...
    ~any([ladder.rungs.resultAvailable]), ...
    'ipm:GaugeLabQ512BoxTestRoots', ...
    'A registered fresh q512 box root failed its preflight contract.');

limits = ladder.hardLimits;
requiredLimits = {'maximumRhoRelativeL2', ...
    'maximumOmegaRelativeL2','maximumPhysicalRhoXRelativeDifference', ...
    'maximumCanonicalCLRelativeDifference', ...
    'maximumCanonicalCOmegaRelativeDifference', ...
    'maximumGradientEnergyRelativeDifference', ...
    'maximumGradientForcingRelativeDifference', ...
    'maximumFarBoundarySourceRatio', ...
    'maximumFarBoundaryVelocityRatio'};
assert(all(isfield(limits,requiredLimits)) && ...
    all(structfun(@(value)isnumeric(value) && isscalar(value) && ...
        isfinite(value) && value > 0,limits)), ...
    'ipm:GaugeLabQ512BoxTestLimits', ...
    'The preregistered campaign-box limits are incomplete or invalid.');

assert(isfile(ladder.summaryFile) && isfile(ladder.manifestFile) && ...
    isempty(dir(fullfile(temporaryRoot,'**','result.mat'))), ...
    'ipm:GaugeLabQ512BoxTestNoSolve', ...
    'Default box preflight either omitted records or executed a PDE solve.');

injected = ipm_gaugelab_run_q512_box_ladder(struct( ...
    'boxHalfWidths',[1e3,1e6], ...
    'outputRoot',temporaryRoot,'verbose',false));
assert(isequal(injected.boxHalfWidths,[281,1e3,1e6]) && ...
    any([injected.rungs.boxHalfWidth] == 281) && ...
    any([injected.rungs.boxHalfWidth] == 1e6), ...
    'ipm:GaugeLabQ512BoxTestReferenceInjection', ...
    'The mandatory large-factory 281 control was not inserted safely.');

checkpointRejected = false;
try
    ipm_gaugelab_run_q512_box_ladder(struct( ...
        'checkpoint','forbidden.mat'));
catch exception
    checkpointRejected = strcmp(exception.identifier, ...
        'ipm:GaugeLabQ512BoxLadderOptions');
end
assert(checkpointRejected, ...
    'ipm:GaugeLabQ512BoxTestCheckpointInput', ...
    'The fresh q512 box ladder accepted a checkpoint input option.');

report = struct( ...
    'status',ladder.status, ...
    'rungs',numel(ladder.rungs), ...
    'boxHalfWidths',ladder.boxHalfWidths, ...
    'hardLimitCount',numel(fieldnames(limits)), ...
    'checkpointInputRejected',checkpointRejected, ...
    'solveExecuted',false);
clear cleanup;
fprintf(['Q512 box ladder preflight: roots=%d, campaign box=%.0e, ' ...
    'hard limits=%d.\n'],report.rungs,ladder.campaignBoxHalfWidth, ...
    report.hardLimitCount);
end

function remove_temporary_root(pathName)
if isfolder(pathName)
    rmdir(pathName,'s');
end
end
