function specifications = ipm_gaugelab_candidate_specifications( ...
        includeNegativeControl)
%IPM_GAUGELAB_CANDIDATE_SPECIFICATIONS Frozen gauge-lab candidate registry.
%   This registry is the single whitelist used by the schema-4 tournament.
%   Localized gauges share one fixed analytic support; a run is not allowed
%   to tune its center or radius after seeing the solution.

if nargin < 1
    includeNegativeControl = false;
end
validLogical = islogical(includeNegativeControl) && ...
    isscalar(includeNegativeControl);
validNumeric = isnumeric(includeNegativeControl) && ...
    isreal(includeNegativeControl) && isscalar(includeNegativeControl) && ...
    isfinite(includeNegativeControl) && ...
    any(includeNegativeControl == [0,1]);
if ~(validLogical || validNumeric)
    error('ipm:GaugeLabCandidateRegistryFlag', ...
        'includeNegativeControl must be logical or numeric 0/1.');
end
includeNegativeControl = logical(includeNegativeControl);

notLocalized = struct('center',[NaN,NaN],'radius',NaN, ...
    'supportX',[NaN,NaN],'supportY',[NaN,NaN]);
wallSupport = struct('center',[1,0],'radius',0.75, ...
    'supportX',[0.25,1.75],'supportY',[0,0]);
bulkSupport = struct('center',[1,0],'radius',0.75, ...
    'supportX',[0.25,1.75],'supportY',[0,0.75]);

prototype = struct('cOmegaGauge','','role','','family','', ...
    'momentOrder',NaN,'fixedSupport',notLocalized, ...
    'minimumCondition',NaN,'maximumNormalizedResidual',1e-10, ...
    'identityTolerance',NaN,'productionCandidate',true);
specifications = repmat(prototype,9,1);

specifications(1) = make_specification(prototype,'gradient_energy', ...
    'incumbent','global_gradient_energy',NaN,notLocalized,NaN,NaN);
specifications(2) = make_specification(prototype, ...
    'wall_omega_quadratic_peak','candidate', ...
    'moving_wall_quadratic_peak',NaN,notLocalized,1e-6,NaN);
specifications(3) = make_specification(prototype, ...
    'anchor_wall_window_l2','incumbent','wall_window_moment',2, ...
    wallSupport,0.25,1e-10);
specifications(4) = make_specification(prototype, ...
    'anchor_wall_template_projection','candidate', ...
    'wall_template_projection',NaN,wallSupport,0.25,NaN);
specifications(5) = make_specification(prototype, ...
    'anchor_bulk_gradient_l2','candidate','bulk_gradient_energy',2, ...
    bulkSupport,0.25,1e-10);
specifications(6) = make_specification(prototype, ...
    'anchor_wall_window_l4','candidate','wall_window_moment',4, ...
    wallSupport,0.25,1e-10);
specifications(7) = make_specification(prototype,'anchor_wall_slope', ...
    'historical_comparator','wall_anchor_point',NaN,wallSupport,0.25,NaN);
specifications(7).productionCandidate = false;
specifications(8) = make_specification(prototype,'wall_omega_peak', ...
    'historical_comparator','moving_wall_peak',NaN,notLocalized,NaN,NaN);
specifications(8).productionCandidate = false;
specifications(9) = make_specification(prototype,'anchor_wall_strain', ...
    'diagnostic_only','wall_anchor_strain',NaN,wallSupport,0.25,NaN);
specifications(9).productionCandidate = false;

if includeNegativeControl
    negative = make_specification(prototype,'none','negative_control', ...
        'negative_control',NaN,notLocalized,NaN,NaN);
    negative.productionCandidate = false;
    specifications(end+1,1) = negative;
end
end

function specification = make_specification(prototype,name,role,family, ...
        momentOrder,support,minimumCondition,identityTolerance)
specification = prototype;
specification.cOmegaGauge = name;
specification.role = role;
specification.family = family;
specification.momentOrder = momentOrder;
specification.fixedSupport = support;
specification.minimumCondition = minimumCondition;
specification.identityTolerance = identityTolerance;
end
