function report = ipm_gaugelab_test_q512_root()
%IPM_GAUGELAB_TEST_Q512_ROOT No-PDE root gauge/preflight tests.

laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    laboratoryDirectory);

temporaryRoot = [tempname,'_q512_root_preflight'];
mkdir(temporaryRoot);
cleanup = onCleanup(@()remove_temporary_root(temporaryRoot));

gradient = ipm_gaugelab_run_q512_root(struct( ...
    'preflightOnly',true, ...
    'outputRoot',fullfile(temporaryRoot,'gradient_default'), ...
    'verbose',false));
quadratic = ipm_gaugelab_run_q512_root(struct( ...
    'preflightOnly',true, ...
    'cOmegaGauge','wall_omega_quadratic_peak', ...
    'outputRoot',fullfile(temporaryRoot,'quadratic'), ...
    'verbose',false));

assert_root_preflight(gradient,'gradient_energy');
assert_root_preflight(quadratic,'wall_omega_quadratic_peak');
assert(strcmp(gradient.cOmegaGauge,'gradient_energy') && ...
    strcmp(gradient.gaugeRules.amplitudeObservable, ...
        'sum(w*(R_X^2+R_Y^2)) is constant'), ...
    'ipm:GaugeLabQ512RootGradientDefault', ...
    'The backward-compatible gradient-energy root default changed.');
assert(strcmp(quadratic.cOmegaGauge,'wall_omega_quadratic_peak') && ...
    strcmp(quadratic.gaugeRules.amplitudeObservable, ...
        'tracked nonuniform quadratic wall R_X peak is constant'), ...
    'ipm:GaugeLabQ512RootQuadraticPositive', ...
    'The explicit quadratic-peak root was not registered.');

gradientContract = exact_gauge_contract(gradient);
quadraticContract = exact_gauge_contract(quadratic);
assert(strcmp(gradientContract.amplitude.name,'gradient_energy') && ...
    strcmp(gradientContract.amplitude.formula, ...
        gradient.gaugeRules.amplitudeFormula) && ...
    strcmp(quadraticContract.amplitude.name, ...
        'wall_omega_quadratic_peak') && ...
    strcmp(quadraticContract.amplitude.formula, ...
        quadratic.gaugeRules.amplitudeFormula) && ...
    strcmp(quadraticContract.amplitude.evaluation, ...
        'active_nonuniform_three_node_quadratic_vertex'), ...
    'ipm:GaugeLabQ512RootGaugeContract', ...
    'The registered root and exact runtime gauge contracts disagree.');

unsupportedRejected = assert_throws(@() ...
    ipm_gaugelab_run_q512_root(struct('preflightOnly',true, ...
    'cOmegaGauge','none')), ...
    'ipm:GaugeLabQ512COmegaGauge');
assert(unsupportedRejected, ...
    'ipm:GaugeLabQ512RootQuadraticNegative', ...
    'The root accepted an unregistered amplitude gauge.');

assert(~isfile(gradient.requestedResultFile) && ...
    ~isfile(gradient.requestedCheckpointFile) && ...
    ~isfile(quadratic.requestedResultFile) && ...
    ~isfile(quadratic.requestedCheckpointFile), ...
    'ipm:GaugeLabQ512RootNoPde', ...
    'A preflight-only root wrote a solver result or checkpoint.');
gradientSaved = load(gradient.summaryFile,'rootRun');
quadraticSaved = load(quadratic.summaryFile,'rootRun');
assert(strcmp(gradientSaved.rootRun.cOmegaGauge,'gradient_energy') && ...
    strcmp(quadraticSaved.rootRun.cOmegaGauge, ...
        'wall_omega_quadratic_peak'), ...
    'ipm:GaugeLabQ512RootSavedGauge', ...
    'A saved root summary lost its selected amplitude gauge.');

report = struct( ...
    'status','passed', ...
    'pdeSolveCount',0, ...
    'defaultGauge',gradient.cOmegaGauge, ...
    'quadraticGauge',quadratic.cOmegaGauge, ...
    'gradientPreflightPassed',gradient.meshPassed && ...
        gradient.contractPassed, ...
    'quadraticPreflightPassed',quadratic.meshPassed && ...
        quadratic.contractPassed, ...
    'unsupportedGaugeRejected',unsupportedRejected);
clear cleanup;
fprintf(['Q512 root gauge preflight: default=%s, explicit=%s, ' ...
    'PDE solves=%d.\n'],report.defaultGauge,report.quadraticGauge, ...
    report.pdeSolveCount);
end

function assert_root_preflight(rootRun,expectedGauge)
metadata = rootRun.config.output.caseMetadata.q512GaugeRoot;
assert(rootRun.schemaVersion == 4 && ...
    strcmp(rootRun.kind,'q512_fresh_exact_gauge_root') && ...
    strcmp(rootRun.status,'preflight_only') && ...
    rootRun.preflightOnly && rootRun.freshStart && ...
    strcmp(rootRun.restartInput,'none') && ...
    rootRun.meshPassed && rootRun.contractPassed && ...
    rootRun.contractAudit.checks.registeredAmplitudeGauge && ...
    strcmp(rootRun.cOmegaGauge,expectedGauge) && ...
    strcmp(rootRun.requested.cOmegaGauge,expectedGauge) && ...
    strcmp(rootRun.gaugeRules.amplitudeGauge,expectedGauge) && ...
    ~rootRun.gaugeRules.selectedRatePrescribed && ...
    strcmp(rootRun.config.scaling.cOmegaGauge,expectedGauge) && ...
    strcmp(metadata.cOmegaGauge,expectedGauge) && ...
    strcmp(rootRun.config.scaling.scalingContract, ...
        'exact_gauge_no_feedback_v1') && ...
    strcmp(rootRun.config.scaling.lengthGauge,'transport_anchor') && ...
    rootRun.config.scaling.transportAnchorX == 1 && ...
    isempty(fieldnames(rootRun.postAudit)), ...
    'ipm:GaugeLabQ512RootPreflight', ...
    'A registered root lost its fresh schema-4 exact-gauge contract.');
assert(isfile(rootRun.summaryFile) && isfile(rootRun.manifestFile), ...
    'ipm:GaugeLabQ512RootPreflightArtifacts', ...
    'A registered root omitted its preflight summary or manifest.');
end

function contract = exact_gauge_contract(rootRun)
ops = struct('x',rootRun.config.grid.customX);
contract = ipm.evolve.gaugeContract(rootRun.config,ops);
assert(contract.schemaVersion == 2 && contract.timeSpeed == 1 && ...
    strcmp(contract.scalingContract,'exact_gauge_no_feedback_v1') && ...
    strcmp(contract.length.name,'transport_anchor') && ...
    contract.length.anchorX == 1 && ...
    strcmp(contract.feedback.rateLimiter,'absent'), ...
    'ipm:GaugeLabQ512RootExactContract', ...
    'The serializable exact-gauge contract changed.');
end

function passed = assert_throws(callback,identifier)
passed = false;
try
    callback();
catch exception
    passed = strcmp(exception.identifier,identifier);
end
end

function remove_temporary_root(pathName)
if isfolder(pathName)
    rmdir(pathName,'s');
end
end
