function comparison = ipm_gaugelab_compare_timesteps( ...
        coarseResult,halfResult)
%IPM_GAUGELAB_COMPARE_TIMESTEPS Hard-gate one q256 time-step rematch.
%   COMPARISON = IPM_GAUGELAB_COMPARE_TIMESTEPS(COARSERESULT,HALFRESULT)
%   validates two results using the same cOmegaGauge at a common physical
%   endpoint.  It compares terminal canonical rates, their relative trends
%   over the exact final 0.25 physical-time window, physical max|rho_x1|,
%   and the terminal reconstructed omega field.  This function performs
%   postprocessing only; it neither advances a solve nor writes a file.

narginchk(2,2);
coarse = ipm.output.validate(coarseResult);
half = ipm.output.validate(halfResult);
limits = hard_limits();

coarseGauge = coarse.config.scaling.cOmegaGauge;
halfGauge = half.config.scaling.cOmegaGauge;
if ~strcmp(coarseGauge,halfGauge)
    error('ipm:GaugeLabTimestepGaugeMismatch', ...
        ['The coarse- and half-step results must use the same ' ...
        'cOmegaGauge (received "%s" and "%s").'], ...
        coarseGauge,halfGauge);
end

coarseEndpoint = coarse.state.physicalTime;
halfEndpoint = half.state.physicalTime;
endpointDifference = halfEndpoint-coarseEndpoint;
coarseTarget = coarse.config.time.physicalFinalTime;
halfTarget = half.config.time.physicalFinalTime;
targetDifference = halfTarget-coarseTarget;
targetsMatch = isfinite(coarseTarget) && isfinite(halfTarget) && ...
    abs(targetDifference) <= ...
    limits.maximumAbsoluteConfiguredTargetDifference;
if ~targetsMatch
    error('ipm:GaugeLabTimestepTargetMismatch', ...
        ['The two results must declare the same finite physical target; ' ...
        'coarse target=%.17g, half-step target=%.17g.'], ...
        coarseTarget,halfTarget);
end
if ~isfinite(endpointDifference) || ...
        abs(endpointDifference) > ...
        limits.maximumAbsolutePhysicalEndpointDifference
    error('ipm:GaugeLabTimestepEndpointMismatch', ...
        ['The two results must share a physical endpoint to within %.3e; ' ...
        'coarse t=%.17g, half-step t=%.17g, difference=%.3e.'], ...
        limits.maximumAbsolutePhysicalEndpointDifference, ...
        coarseEndpoint,halfEndpoint,endpointDifference);
end
targetTolerance = limits.maximumAbsolutePhysicalEndpointDifference;
if abs(coarseEndpoint-coarseTarget) > targetTolerance || ...
        abs(halfEndpoint-coarseTarget) > targetTolerance
    error('ipm:GaugeLabTimestepTargetNotReached', ...
        ['Both results must reach their configured physical target %.17g ' ...
        'to within %.3e; endpoints are %.17g and %.17g.'], ...
        coarseTarget,targetTolerance,coarseEndpoint,halfEndpoint);
end
commonEndpoint = coarseTarget;

coarseAudit = ipm_gaugelab_assess(coarse,commonEndpoint);
halfAudit = ipm_gaugelab_assess(half,commonEndpoint);

coarseCL = trusted_terminal_value(coarse,coarseAudit,'canonicalCL');
halfCL = trusted_terminal_value(half,halfAudit,'canonicalCL');
coarseCOmega = trusted_terminal_value( ...
    coarse,coarseAudit,'canonicalCOmega');
halfCOmega = trusted_terminal_value(half,halfAudit,'canonicalCOmega');
coarseRhoX = trusted_terminal_value( ...
    coarse,coarseAudit,'physicalRhoXInf');
halfRhoX = trusted_terminal_value(half,halfAudit,'physicalRhoXInf');

terminalCLDifference = relative_difference(coarseCL,halfCL);
terminalCOmegaDifference = relative_difference( ...
    coarseCOmega,halfCOmega);
physicalRhoXDifference = relative_difference(coarseRhoX,halfRhoX);

coarseCLTrend = trailing_trend( ...
    coarse,coarseAudit,'canonicalCL',limits.trailingPhysicalWindow, ...
    commonEndpoint);
halfCLTrend = trailing_trend( ...
    half,halfAudit,'canonicalCL',limits.trailingPhysicalWindow, ...
    commonEndpoint);
coarseCOmegaTrend = trailing_trend( ...
    coarse,coarseAudit,'canonicalCOmega', ...
    limits.trailingPhysicalWindow,commonEndpoint);
halfCOmegaTrend = trailing_trend( ...
    half,halfAudit,'canonicalCOmega', ...
    limits.trailingPhysicalWindow,commonEndpoint);
clTrendDifference = halfCLTrend.relativeTrendAcrossWindow- ...
    coarseCLTrend.relativeTrendAcrossWindow;
cOmegaTrendDifference = ...
    halfCOmegaTrend.relativeTrendAcrossWindow- ...
    coarseCOmegaTrend.relativeTrendAcrossWindow;

forwardPhysicalComparison = ...
    ipm.output.compare(coarse,half,[-2,2,2]);
reversePhysicalComparison = ...
    ipm.output.compare(half,coarse,[-2,2,2]);
physicalComparison = symmetric_physical_comparison( ...
    forwardPhysicalComparison,reversePhysicalComparison);
[coarseTimeSpeedIdentity,coarseTimeSpeedDeviation] = ...
    time_speed_identity(coarse);
[halfTimeSpeedIdentity,halfTimeSpeedDeviation] = ...
    time_speed_identity(half);

comparison = struct();
comparison.schemaVersion = 1;
comparison.kind = 'q256_gauge_timestep_comparison';
comparison.cOmegaGauge = coarseGauge;
comparison.hardLimits = limits;
comparison.endpoint = struct( ...
    'coarseConfiguredTarget',coarseTarget, ...
    'halfConfiguredTarget',halfTarget, ...
    'configuredTargetDifference',targetDifference, ...
    'coarsePhysicalTime',coarseEndpoint, ...
    'halfPhysicalTime',halfEndpoint, ...
    'signedDifference',endpointDifference, ...
    'commonAuditTarget',commonEndpoint);
comparison.timeStep = struct( ...
    'coarseMaximum',coarse.config.time.maxDt, ...
    'halfMaximum',half.config.time.maxDt, ...
    'halfToCoarseRatio',half.config.time.maxDt/ ...
        coarse.config.time.maxDt, ...
    'coarseCfl',coarse.config.time.cfl, ...
    'halfCfl',half.config.time.cfl, ...
    'halfToCoarseCflRatio',half.config.time.cfl/ ...
        coarse.config.time.cfl);
comparison.terminalCanonicalCL = pair_comparison( ...
    coarseCL,halfCL,terminalCLDifference);
comparison.terminalCanonicalCOmega = pair_comparison( ...
    coarseCOmega,halfCOmega,terminalCOmegaDifference);
comparison.trailingCanonicalCL = trend_comparison( ...
    coarseCLTrend,halfCLTrend,clTrendDifference, ...
    limits.trailingPhysicalWindow);
comparison.trailingCanonicalCOmega = trend_comparison( ...
    coarseCOmegaTrend,halfCOmegaTrend,cOmegaTrendDifference, ...
    limits.trailingPhysicalWindow);
comparison.physicalRhoXInf = pair_comparison( ...
    coarseRhoX,halfRhoX,physicalRhoXDifference);
comparison.physicalComparison = physicalComparison;
comparison.canonicalClock = struct( ...
    'coarseTimeSpeedIdentity',coarseTimeSpeedIdentity, ...
    'halfTimeSpeedIdentity',halfTimeSpeedIdentity, ...
    'coarseMaximumTimeSpeedDeviation',coarseTimeSpeedDeviation, ...
    'halfMaximumTimeSpeedDeviation',halfTimeSpeedDeviation);
comparison.gaugeAudit = struct( ...
    'coarse',audit_summary(coarseAudit), ...
    'half',audit_summary(halfAudit));

gates = struct();
gates.coarseGaugeAuditPassed = coarseAudit.hardPassed;
gates.halfGaugeAuditPassed = halfAudit.hardPassed;
gates.commonPhysicalEndpoint = ...
    abs(endpointDifference) <= ...
    limits.maximumAbsolutePhysicalEndpointDifference;
gates.configuredPhysicalTarget = targetsMatch && ...
    abs(coarseEndpoint-coarseTarget) <= targetTolerance && ...
    abs(halfEndpoint-coarseTarget) <= targetTolerance;
gates.halfMaximumTimeStep = finite_within( ...
    comparison.timeStep.halfToCoarseRatio- ...
    limits.requiredHalfToCoarseRatio,limits.timeTupleTolerance);
gates.halfCfl = finite_within( ...
    comparison.timeStep.halfToCoarseCflRatio- ...
    limits.requiredHalfToCoarseRatio,limits.timeTupleTolerance);
gates.coarseTimeSpeedIdentity = coarseTimeSpeedIdentity;
gates.halfTimeSpeedIdentity = halfTimeSpeedIdentity;
gates.coarseWidthCorrectionZero = ...
    coarseAudit.widthCorrectionHistoryComplete && ...
    coarseAudit.maximumWidthCorrectionMagnitude == 0;
gates.halfWidthCorrectionZero = ...
    halfAudit.widthCorrectionHistoryComplete && ...
    halfAudit.maximumWidthCorrectionMagnitude == 0;
gates.terminalCanonicalCL = finite_within( ...
    terminalCLDifference,limits.maximumTerminalCanonicalCLRelativeDifference);
gates.terminalCanonicalCOmega = finite_within( ...
    terminalCOmegaDifference, ...
    limits.maximumTerminalCanonicalCOmegaRelativeDifference);
gates.trailingCanonicalCLTrend = ...
    coarseCLTrend.valid && halfCLTrend.valid && finite_within( ...
    clTrendDifference,limits.maximumRelativeTrendDifference);
gates.trailingCanonicalCOmegaTrend = ...
    coarseCOmegaTrend.valid && halfCOmegaTrend.valid && finite_within( ...
    cOmegaTrendDifference,limits.maximumRelativeTrendDifference);
gates.physicalRhoXInf = finite_within( ...
    physicalRhoXDifference,limits.maximumPhysicalRhoXRelativeDifference);
gates.terminalOmegaRelativeL2 = ...
    isfinite(physicalComparison.omegaRelativeL2) && ...
    physicalComparison.omegaRelativeL2 <= ...
    limits.maximumTerminalOmegaRelativeL2;
comparison.gates = gates;

gateNames = fieldnames(gates);
gateValues = false(size(gateNames));
for index = 1:numel(gateNames)
    gateValues(index) = gates.(gateNames{index});
end
comparison.hardPassed = all(gateValues);
comparison.hardFailureReason = char(strjoin( ...
    string(gateNames(~gateValues)),','));
end

function limits = hard_limits()
limits = struct( ...
    'maximumAbsolutePhysicalEndpointDifference',1e-10, ...
    'maximumAbsoluteConfiguredTargetDifference',1e-12, ...
    'requiredHalfToCoarseRatio',0.5, ...
    'timeTupleTolerance',100*eps(1), ...
    'trailingPhysicalWindow',0.25, ...
    'maximumTerminalCanonicalCLRelativeDifference',1e-2, ...
    'maximumTerminalCanonicalCOmegaRelativeDifference',1e-2, ...
    'maximumRelativeTrendDifference',1e-2, ...
    'maximumPhysicalRhoXRelativeDifference',5e-3, ...
    'maximumTerminalOmegaRelativeL2',5e-3);
end

function value = trusted_terminal_value(result,audit,name)
value = NaN;
if ~audit.terminalTrusted || ~isfield(result.history.common,name)
    return;
end
series = result.history.common.(name);
if isnumeric(series) && isreal(series) && isvector(series) && ...
        ~isempty(series) && isfinite(series(end))
    value = series(end);
end
end

function comparison = pair_comparison(coarse,half,signedDifference)
comparison = struct('coarse',coarse,'half',half, ...
    'signedRelativeDifference',signedDifference, ...
    'absoluteRelativeDifference',abs(signedDifference));
end

function comparison = trend_comparison( ...
        coarse,half,signedDifference,physicalWindow)
comparison = struct('physicalWindow',physicalWindow,'coarse',coarse, ...
    'half',half,'signedRelativeTrendDifference',signedDifference, ...
    'absoluteRelativeTrendDifference',abs(signedDifference));
end

function summary = audit_summary(audit)
summary = struct( ...
    'hardPassed',audit.hardPassed, ...
    'hardFailureReason',audit.hardFailureReason, ...
    'terminalTrusted',audit.terminalTrusted, ...
    'physicalTime',audit.physicalTime, ...
    'canonicalTau',audit.canonicalTau, ...
    'minimumTimeSpeed',audit.minimumTimeSpeed, ...
    'maximumTimeSpeedDeviation',audit.maximumTimeSpeedDeviation, ...
    'widthCorrectionHistoryComplete', ...
        audit.widthCorrectionHistoryComplete, ...
    'maximumWidthCorrectionMagnitude', ...
        audit.maximumWidthCorrectionMagnitude);
end

function [identity,maximumDeviation] = time_speed_identity(result)
identity = false;
maximumDeviation = Inf;
if ~isfield(result.history.common,'timeSpeed')
    return;
end
timeSpeed = result.history.common.timeSpeed;
if ~isnumeric(timeSpeed) || ~isreal(timeSpeed) || ...
        ~isvector(timeSpeed) || isempty(timeSpeed) || ...
        any(~isfinite(timeSpeed))
    return;
end
maximumDeviation = max(abs(timeSpeed-1));
identity = all(timeSpeed == 1);
end

function stats = trailing_trend( ...
        result,audit,name,physicalWindow,windowEnd)
stats = empty_trend(physicalWindow);
trusted = audit.trustedPrefixMask;
common = result.history.common;
required = {'physicalTime','canonicalTau',name};
if ~islogical(trusted) || ~isvector(trusted) || ~any(trusted) || ...
        ~all(isfield(common,required))
    return;
end

physicalTime = column(common.physicalTime(trusted));
canonicalTau = column(common.canonicalTau(trusted));
values = column(common.(name)(trusted));
if numel(physicalTime) ~= numel(canonicalTau) || ...
        numel(physicalTime) ~= numel(values) || ...
        numel(physicalTime) < 2 || ...
        any(~isfinite(physicalTime)) || any(~isfinite(canonicalTau)) || ...
        any(~isfinite(values)) || any(diff(physicalTime) <= 0) || ...
        any(diff(canonicalTau) <= 0)
    return;
end

windowStart = windowEnd-physicalWindow;
tolerance = 100*eps(max(1,abs(windowEnd)));
if physicalTime(1) > windowStart+tolerance
    return;
end

firstAtOrAfter = find(physicalTime >= windowStart,1,'first');
if isempty(firstAtOrAfter)
    return;
end
interpolatedStart = false;
if abs(physicalTime(firstAtOrAfter)-windowStart) <= tolerance
    physicalTime = physicalTime(firstAtOrAfter:end);
    canonicalTau = canonicalTau(firstAtOrAfter:end);
    values = values(firstAtOrAfter:end);
    physicalTime(1) = windowStart;
elseif firstAtOrAfter == 1
    return;
else
    before = firstAtOrAfter-1;
    fraction = (windowStart-physicalTime(before))/ ...
        (physicalTime(firstAtOrAfter)-physicalTime(before));
    startTau = canonicalTau(before)+fraction* ...
        (canonicalTau(firstAtOrAfter)-canonicalTau(before));
    startValue = values(before)+fraction* ...
        (values(firstAtOrAfter)-values(before));
    physicalTime = [windowStart;physicalTime(firstAtOrAfter:end)];
    canonicalTau = [startTau;canonicalTau(firstAtOrAfter:end)];
    values = [startValue;values(firstAtOrAfter:end)];
    interpolatedStart = true;
end

if numel(canonicalTau) < 2 || any(diff(canonicalTau) <= 0)
    return;
end
weights = trapezoid_weights(canonicalTau);
weightSum = sum(weights);
weightedMean = sum(weights.*values)/weightSum;
centeredTau = canonicalTau-sum(weights.*canonicalTau)/weightSum;
design = [ones(size(canonicalTau)),centeredTau];
coefficients = (design.*sqrt(weights))\(values.*sqrt(weights));
slope = coefficients(2);

stats.valid = all(isfinite([weightedMean,slope])) && weightSum > 0;
stats.records = numel(values);
stats.interpolatedWindowStart = interpolatedStart;
stats.physicalStart = physicalTime(1);
stats.physicalEnd = physicalTime(end);
stats.physicalWindow = physicalTime(end)-physicalTime(1);
stats.canonicalStart = canonicalTau(1);
stats.canonicalEnd = canonicalTau(end);
stats.canonicalWindow = canonicalTau(end)-canonicalTau(1);
stats.weightedMean = weightedMean;
stats.slope = slope;
stats.relativeTrendAcrossWindow = slope*stats.canonicalWindow/ ...
    max(abs(weightedMean),eps);
stats.start = values(1);
stats.finish = values(end);
stats.minimum = min(values);
stats.maximum = max(values);
stats.valid = stats.valid && ...
    isfinite(stats.relativeTrendAcrossWindow) && ...
    abs(stats.physicalWindow-physicalWindow) <= tolerance;
end

function stats = empty_trend(physicalWindow)
stats = struct('valid',false,'records',0, ...
    'interpolatedWindowStart',false,'requestedPhysicalWindow', ...
    physicalWindow,'physicalStart',NaN,'physicalEnd',NaN, ...
    'physicalWindow',NaN,'canonicalStart',NaN,'canonicalEnd',NaN, ...
    'canonicalWindow',NaN,'weightedMean',NaN,'slope',NaN, ...
    'relativeTrendAcrossWindow',NaN,'start',NaN,'finish',NaN, ...
    'minimum',NaN,'maximum',NaN);
end

function weights = trapezoid_weights(coordinate)
weights = zeros(size(coordinate));
weights(1) = (coordinate(2)-coordinate(1))/2;
weights(end) = (coordinate(end)-coordinate(end-1))/2;
if numel(coordinate) > 2
    weights(2:end-1) = ...
        (coordinate(3:end)-coordinate(1:end-2))/2;
end
end

function symmetric = symmetric_physical_comparison(forward,reverse)
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference'};
symmetric = struct('method','bidirectional_absolute_worst', ...
    'forward',forward,'reverse',reverse);
for index = 1:numel(names)
    name = names{index};
    symmetric.(name) = max(abs([forward.(name),reverse.(name)]));
end
end

function value = relative_difference(reference,candidate)
if ~isfinite(reference) || ~isfinite(candidate)
    value = NaN;
    return;
end
scale = max(abs([reference,candidate]));
if scale == 0
    value = 0;
else
    value = (candidate-reference)/scale;
end
end

function passed = finite_within(value,limit)
passed = isfinite(value) && abs(value) <= limit;
end

function value = column(value)
value = value(:);
end
