function ladder = ipm_gaugelab_run_q512_box_ladder(options)
%IPM_GAUGELAB_RUN_Q512_BOX_LADDER Register fresh q512 box rungs.
%   LADDER = IPM_GAUGELAB_RUN_Q512_BOX_LADDER() preregisters and audits a
%   matched [-281,281] reference plus an anchor-aligned large-box-factory
%   control at 281 and fresh large-box half-widths 1e3, 1e4, 1e5, and 1e6.
%   It performs no PDE solve by default.
%
%   Set OPTIONS.executeSmoke=true to execute the bounded smoke profile of
%   ipm_gaugelab_run_q512_root on every rung.  There is deliberately no
%   campaign or checkpoint-input option.  Every rung delegates to that
%   fresh-root runner, so all runs start at physical/canonical time zero.
%
%   Executed rungs summarize initial/terminal gauge rates, gradient-energy
%   cancellation, actual physical domains, far-boundary telemetry, and
%   wall cost.  Each large box is compared to the matched result, and each
%   neighboring pair from the common large-box factory is compared, in both
%   interpolation directions on one shared physical window.  A frozen
%   screening gate is applied to the last large-family comparison ending
%   at half-width 1e6, including field, gauge, and far-boundary checks.
%   This one-step gate is not late-time truncation evidence; the axes still
%   redistribute outer nodes as the box grows.

if nargin < 1 || isempty(options)
    options = struct();
end
settings = resolve_options(options);
require_root_runner();

[outputDirectory,ladderId] = create_output_directory(settings.outputRoot);
summaryFile = fullfile(outputDirectory,'box_ladder_summary.mat');
manifestFile = fullfile(outputDirectory,'box_ladder_manifest.jsonl');
rootOutputDirectory = fullfile(outputDirectory,'roots');
mkdir(rootOutputDirectory);

specifications = rung_specifications(settings.boxHalfWidths);
records = repmat(empty_rung(),numel(specifications),1);
for index = 1:numel(specifications)
    records(index).index = index;
    records(index).name = specifications(index).name;
    records(index).boxMode = specifications(index).boxMode;
    records(index).boxHalfWidth = specifications(index).boxHalfWidth;
    records(index).reference = specifications(index).reference;
    records(index).status = 'pending';
end

startedUtc = utc_stamp();
ladder = struct( ...
    'schemaVersion',4, ...
    'kind','q512_fresh_exact_gauge_box_ladder', ...
    'ladderId',ladderId, ...
    'status','registered', ...
    'startedUtc',startedUtc, ...
    'completedUtc','', ...
    'executionMode',execution_mode(settings), ...
    'freshRootsOnly',true, ...
    'checkpointInputsAccepted',false, ...
    'matchedReference','matched_281', ...
    'anchorAlignedControl','large_281', ...
    'boxHalfWidths',settings.boxHalfWidths, ...
    'requested',requested_summary(settings), ...
    'comparisonMethod','bidirectional_common_physical_window', ...
    'comparisonWindowCap',settings.comparisonWindowCap, ...
    'campaignBoxHalfWidth',1e6, ...
    'hardLimits',box_hard_limits(), ...
    'outputDirectory',outputDirectory, ...
    'rootOutputDirectory',rootOutputDirectory, ...
    'summaryFile',summaryFile, ...
    'manifestFile',manifestFile, ...
    'rungs',records, ...
    'successiveLargeComparisons', ...
        repmat(empty_successive_comparison(),0,1), ...
    'completedRungs',0, ...
    'successfulRoots',0, ...
    'availableMatchedComparisons',0, ...
    'availableSuccessiveComparisons',0, ...
    'availableComparisons',0, ...
    'campaignBoxGate',empty_box_gate(), ...
    'hardPassed',false, ...
    'orchestrationWallSeconds',NaN, ...
    'sumRootSolveWallSeconds',NaN, ...
    'failures',{{}});
save_summary(summaryFile,ladder);
append_manifest(manifestFile,struct( ...
    'event','box_ladder_registered', ...
    'timestampUtc',startedUtc, ...
    'ladderId',ladderId, ...
    'executionMode',ladder.executionMode, ...
    'freshRootsOnly',true, ...
    'checkpointInputsAccepted',false, ...
    'matchedReference',ladder.matchedReference, ...
    'boxHalfWidths',settings.boxHalfWidths, ...
    'requested',ladder.requested, ...
    'comparisonMethod',ladder.comparisonMethod, ...
    'comparisonWindowCap',settings.comparisonWindowCap, ...
    'campaignBoxHalfWidth',ladder.campaignBoxHalfWidth, ...
    'hardLimits',ladder.hardLimits, ...
    'summaryFile',summaryFile));

orchestrationClock = tic;
for index = 1:numel(specifications)
    specification = specifications(index);
    record = ladder.rungs(index);
    record.status = 'root_running';
    record.startedUtc = utc_stamp();
    rungRootDirectory = fullfile( ...
        rootOutputDirectory,specification.name);
    record.rootOutputRoot = rungRootDirectory;
    ladder.rungs(index) = record;
    save_summary(summaryFile,ladder);
    append_manifest(manifestFile,struct( ...
        'event','box_rung_started', ...
        'timestampUtc',record.startedUtc, ...
        'ladderId',ladderId, ...
        'rung',specification.name, ...
        'boxMode',specification.boxMode, ...
        'boxHalfWidth',specification.boxHalfWidth, ...
        'executeSmoke',settings.executeSmoke));

    rootOptions = root_options(settings,specification,rungRootDirectory);
    try
        rootRun = ipm_gaugelab_run_q512_root(rootOptions);
        record = populate_from_root(record,rootRun,settings.executeSmoke);
    catch exception
        record.errorIdentifier = exception.identifier;
        record.errorMessage = exception.message;
        record.status = 'root_failed';
        recovered = recover_root_summary(rungRootDirectory);
        if ~isempty(recovered)
            try
                record = populate_from_root(record,recovered, ...
                    settings.executeSmoke);
            catch recoveryException
                record.errorMessage = sprintf('%s | recovery: %s', ...
                    record.errorMessage,recoveryException.message);
            end
            record.status = 'root_failed';
            record.errorIdentifier = exception.identifier;
        end
    end
    record.completedUtc = utc_stamp();
    ladder.rungs(index) = record;
    ladder.completedRungs = index;
    save_summary(summaryFile,ladder);
    append_manifest(manifestFile,struct( ...
        'event','box_rung_finished', ...
        'timestampUtc',record.completedUtc, ...
        'ladderId',ladderId, ...
        'rung',record.name, ...
        'status',record.status, ...
        'rootStatus',record.rootStatus, ...
        'meshPassed',record.meshPassed, ...
        'contractPassed',record.contractPassed, ...
        'resultAvailable',record.resultAvailable, ...
        'rootSummaryFile',record.rootSummaryFile, ...
        'resultFile',record.resultFile, ...
        'errorIdentifier',record.errorIdentifier, ...
        'errorMessage',record.errorMessage));
end

if settings.executeSmoke
    ladder = compare_to_matched(ladder,settings.comparisonWindowCap);
    ladder.successiveLargeComparisons = compare_successive_large( ...
        ladder,settings.comparisonWindowCap);
    ladder.campaignBoxGate = assess_campaign_box_gate(ladder);
end
ladder.orchestrationWallSeconds = toc(orchestrationClock);
rootTimes = [ladder.rungs.wallSeconds];
rootTimes = rootTimes(isfinite(rootTimes));
if isempty(rootTimes)
    ladder.sumRootSolveWallSeconds = 0;
else
    ladder.sumRootSolveWallSeconds = sum(rootTimes);
end
ladder.successfulRoots = nnz(arrayfun( ...
    @(record)strcmp(record.status,expected_root_status(settings)), ...
    ladder.rungs));
ladder.availableMatchedComparisons = nnz(arrayfun( ...
    @(record)record.comparisonToMatched.available,ladder.rungs));
ladder.availableSuccessiveComparisons = nnz(arrayfun( ...
    @(record)record.comparison.available, ...
    ladder.successiveLargeComparisons));
ladder.availableComparisons = ladder.availableMatchedComparisons+ ...
    ladder.availableSuccessiveComparisons;
ladder.hardPassed = settings.executeSmoke && ...
    ladder.successfulRoots == numel(ladder.rungs) && ...
    ladder.campaignBoxGate.passed;
ladder.failures = ladder_failures(ladder,settings);
ladder.hardPassed = ladder.hardPassed && isempty(ladder.failures);
if isempty(ladder.failures)
    if settings.executeSmoke
        ladder.status = 'smoke_complete';
    else
        ladder.status = 'preflight_complete';
    end
elseif settings.executeSmoke && ladder.successfulRoots == numel(ladder.rungs)
    if strcmp(ladder.campaignBoxGate.status,'gate_failed')
        ladder.status = 'smoke_gate_failed';
    else
        ladder.status = 'smoke_comparison_incomplete';
    end
else
    ladder.status = 'partial_failure';
end
ladder.completedUtc = utc_stamp();
save_summary(summaryFile,ladder);
append_manifest(manifestFile,struct( ...
    'event','box_ladder_finished', ...
    'timestampUtc',ladder.completedUtc, ...
    'ladderId',ladderId, ...
    'status',ladder.status, ...
    'completedRungs',ladder.completedRungs, ...
    'successfulRoots',ladder.successfulRoots, ...
    'availableMatchedComparisons',ladder.availableMatchedComparisons, ...
    'availableSuccessiveComparisons', ...
        ladder.availableSuccessiveComparisons, ...
    'availableComparisons',ladder.availableComparisons, ...
    'hardPassed',ladder.hardPassed, ...
    'campaignBoxGatePassed',ladder.campaignBoxGate.passed, ...
    'orchestrationWallSeconds',ladder.orchestrationWallSeconds, ...
    'sumRootSolveWallSeconds',ladder.sumRootSolveWallSeconds, ...
    'failures',{ladder.failures}));

fprintf(['Q512 BOX LADDER: status=%s, roots=%d/%d, ' ...
    'comparisons=%d, wall=%.3f s, summary=%s\n'], ...
    ladder.status,ladder.successfulRoots,numel(ladder.rungs), ...
    ladder.availableComparisons,ladder.orchestrationWallSeconds, ...
    summaryFile);
end

function settings = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeLabQ512BoxLadderOptions', ...
        'options must be a scalar structure.');
end
allowed = {'executeSmoke','boxHalfWidths','outputRoot','verbose', ...
    'cfl','maxDt','physicalFinalTime','canonicalFinalTime', ...
    'maxSteps','outputEvery','checkpointEvery','comparisonWindowCap'};
unknown = setdiff(fieldnames(options),allowed,'stable');
if ~isempty(unknown)
    error('ipm:GaugeLabQ512BoxLadderOptions', ...
        'Unknown option(s): %s.',strjoin(unknown,', '));
end

settings = struct();
settings.executeSmoke = logical_option(options,'executeSmoke',false);
settings.boxHalfWidths = numeric_option( ...
    options,'boxHalfWidths',[281,1e3,1e4,1e5,1e6]);
settings.outputRoot = path_option( ...
    options,'outputRoot',default_output_root());
settings.verbose = logical_option(options,'verbose',true);
settings.cfl = numeric_option(options,'cfl',0.25);
settings.maxDt = numeric_option(options,'maxDt',1e-4);
settings.physicalFinalTime = numeric_option( ...
    options,'physicalFinalTime',1e-4);
settings.canonicalFinalTime = numeric_option( ...
    options,'canonicalFinalTime',1e-3);
settings.maxSteps = numeric_option(options,'maxSteps',2);
settings.outputEvery = numeric_option(options,'outputEvery',1e-4);
settings.checkpointEvery = numeric_option( ...
    options,'checkpointEvery',1e-4);
settings.comparisonWindowCap = numeric_option( ...
    options,'comparisonWindowCap',[-2,2,2]);

validateattributes(settings.boxHalfWidths,{'numeric'}, ...
    {'vector','real','finite','>',2,'increasing'},mfilename, ...
    'boxHalfWidths');
settings.boxHalfWidths = settings.boxHalfWidths(:)';
if numel(unique(settings.boxHalfWidths)) ~= ...
        numel(settings.boxHalfWidths)
    error('ipm:GaugeLabQ512BoxLadderRungs', ...
        'boxHalfWidths must contain unique rungs.');
end
if ~ismember(281,settings.boxHalfWidths)
    settings.boxHalfWidths = sort([281,settings.boxHalfWidths]);
end
validateattributes(settings.cfl,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',0.5},mfilename,'cfl');
validateattributes(settings.maxDt,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'maxDt');
validateattributes(settings.physicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',1e-3},mfilename, ...
    'physicalFinalTime');
validateattributes(settings.canonicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',1e-2},mfilename, ...
    'canonicalFinalTime');
validateattributes(settings.maxSteps,{'numeric'}, ...
    {'scalar','real','finite','integer','positive','<=',10},mfilename, ...
    'maxSteps');
validateattributes(settings.outputEvery,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'outputEvery');
validateattributes(settings.checkpointEvery,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'checkpointEvery');
validateattributes(settings.comparisonWindowCap,{'numeric'}, ...
    {'vector','numel',3,'real','finite'},mfilename, ...
    'comparisonWindowCap');
settings.comparisonWindowCap = settings.comparisonWindowCap(:)';
if settings.comparisonWindowCap(2) <= ...
        settings.comparisonWindowCap(1) || ...
        settings.comparisonWindowCap(3) <= 0
    error('ipm:GaugeLabQ512BoxLadderWindow', ...
        'comparisonWindowCap must be [xMin,xMax,yMax] with nonempty area.');
end
end

function specifications = rung_specifications(halfWidths)
specifications = repmat(struct('name','','boxMode','', ...
    'boxHalfWidth',NaN,'reference',false),numel(halfWidths)+1,1);
specifications(1) = struct('name','matched_281', ...
    'boxMode','matched','boxHalfWidth',281,'reference',true);
for index = 1:numel(halfWidths)
    specifications(index+1) = struct( ...
        'name',rung_name(halfWidths(index)), ...
        'boxMode','large_box', ...
        'boxHalfWidth',halfWidths(index), ...
        'reference',false);
end
end

function options = root_options(settings,specification,outputRoot)
options = struct( ...
    'boxMode',specification.boxMode, ...
    'runMode','smoke', ...
    'preflightOnly',~settings.executeSmoke, ...
    'outputRoot',outputRoot, ...
    'verbose',settings.verbose, ...
    'cfl',settings.cfl, ...
    'maxDt',settings.maxDt, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'canonicalFinalTime',settings.canonicalFinalTime, ...
    'maxSteps',settings.maxSteps, ...
    'outputEvery',settings.outputEvery, ...
    'checkpointEvery',settings.checkpointEvery);
if strcmp(specification.boxMode,'large_box')
    options.boxHalfWidth = specification.boxHalfWidth;
end
end

function record = populate_from_root(record,rootRun,executed)
record.rootStatus = rootRun.status;
record.rootAccepted = any(strcmp(rootRun.status, ...
    {'preflight_only','completed'}));
record.rootSummaryFile = rootRun.summaryFile;
record.rootManifestFile = rootRun.manifestFile;
record.meshPassed = rootRun.meshPassed;
record.contractPassed = rootRun.contractPassed;
record.anchorNodeDistance = rootRun.meshAudit.anchorNodeDistance;
record.anchorIsGridNode = rootRun.meshAudit.anchorIsGridNode;
record.resultFile = rootRun.resultFile;
record.checkpointFile = rootRun.checkpointFile;
record.wallSeconds = rootRun.wallSeconds;
record.steps = rootRun.steps;
record.wallSecondsPerStep = rootRun.wallSecondsPerStep;
record.stopReason = rootRun.stopReason;
record.status = rootRun.status;
if isfield(rootRun,'postAudit') && isstruct(rootRun.postAudit) && ...
        isscalar(rootRun.postAudit) && ...
        isfield(rootRun.postAudit,'hardPassed')
    record.postAuditPassed = isequal(rootRun.postAudit.hardPassed,true);
end
if executed && ~isempty(rootRun.resultFile) && isfile(rootRun.resultFile)
    result = ipm.output.validate(rootRun.resultFile);
    record.metrics = summarize_result(result,rootRun);
    record.resultAvailable = true;
end
end

function metrics = summarize_result(result,rootRun)
common = result.history.common;
gauge = result.history.gauge;
requiredCommon = {'canonicalTau','physicalTime','c_l','c_omega', ...
    'canonicalCL','canonicalCOmega','farBoundarySource', ...
    'farBoundarySourceRatio','farBoundaryVelocity', ...
    'farBoundaryVelocityRatio','physicalRhoXInf'};
requiredGauge = {'omegaGaugeEnergy','omegaGaugeEnergyX', ...
    'omegaGaugeEnergyY','omegaGaugeForcingX','omegaGaugeForcingY', ...
    'omegaGaugeForcing','omegaGaugeAbsoluteForcing', ...
    'omegaGaugeForcingCancellationRatio','omegaGaugeResidual'};
require_history(common,requiredCommon,'history.common');
require_history(gauge,requiredGauge,'history.gauge');

initialIndex = 1;
terminalIndex = numel(common.canonicalTau);
metrics = empty_metrics();
metrics.available = true;
metrics.clocks = struct( ...
    'initialCanonicalTime',common.canonicalTau(initialIndex), ...
    'terminalCanonicalTime',common.canonicalTau(terminalIndex), ...
    'initialPhysicalTime',common.physicalTime(initialIndex), ...
    'terminalPhysicalTime',common.physicalTime(terminalIndex));
metrics.rates = struct( ...
    'initial',rate_sample(common,initialIndex), ...
    'terminal',rate_sample(common,terminalIndex));
metrics.gradientEnergy = struct( ...
    'initial',energy_sample(common,gauge,initialIndex), ...
    'terminal',energy_sample(common,gauge,terminalIndex));
metrics.physicalDomain = struct( ...
    'initialX',rootRun.domain.initialPhysicalX, ...
    'initialY',rootRun.domain.initialPhysicalY, ...
    'terminalX',result.grid.physicalX([1,end]), ...
    'terminalY',result.grid.physicalY([1,end]), ...
    'terminalComovingX',result.grid.comovingPhysicalX([1,end]));
metrics.farBoundary = struct( ...
    'initial',far_sample(common,initialIndex), ...
    'terminal',far_sample(common,terminalIndex));
metrics.physicalRhoXInf = struct( ...
    'initial',common.physicalRhoXInf(initialIndex), ...
    'terminal',common.physicalRhoXInf(terminalIndex));
metrics.cost = struct( ...
    'steps',result.state.steps, ...
    'wallSeconds',rootRun.wallSeconds, ...
    'wallSecondsPerStep',rootRun.wallSecondsPerStep);
metrics.gaugeRateConvergence = result.fit.gaugeRateConvergence;
metrics.maximumGrowthRate = result.fit.maximumGrowthRate;
metrics.canonicalMaximumGrowth = result.fit.canonicalMaximumGrowth;
end

function sample = rate_sample(common,index)
sample = struct( ...
    'c_l',common.c_l(index), ...
    'c_omega',common.c_omega(index), ...
    'canonicalCL',common.canonicalCL(index), ...
    'canonicalCOmega',common.canonicalCOmega(index), ...
    'kappa',common.canonicalCL(index)-common.canonicalCOmega(index));
end

function sample = energy_sample(common,gauge,index)
energy = gauge.omegaGaugeEnergy(index);
forcing = gauge.omegaGaugeForcing(index);
cOmega = common.canonicalCOmega(index);
cancellation = forcing+cOmega*energy;
cancellationScale = max([abs(forcing),abs(cOmega*energy),realmin]);
sample = struct( ...
    'energyX',gauge.omegaGaugeEnergyX(index), ...
    'energyY',gauge.omegaGaugeEnergyY(index), ...
    'energy',energy, ...
    'forcingX',gauge.omegaGaugeForcingX(index), ...
    'forcingY',gauge.omegaGaugeForcingY(index), ...
    'forcing',forcing, ...
    'absoluteForcing',gauge.omegaGaugeAbsoluteForcing(index), ...
    'forcingCancellationRatio', ...
        gauge.omegaGaugeForcingCancellationRatio(index), ...
    'cOmegaEnergy',cOmega*energy, ...
    'cancellation',cancellation, ...
    'normalizedCancellation',cancellation/cancellationScale, ...
    'recordedNormalizedResidual',gauge.omegaGaugeResidual(index));
end

function sample = far_sample(common,index)
sample = struct( ...
    'source',common.farBoundarySource(index), ...
    'sourceRatio',common.farBoundarySourceRatio(index), ...
    'velocity',common.farBoundaryVelocity(index), ...
    'velocityRatio',common.farBoundaryVelocityRatio(index));
end

function ladder = compare_to_matched(ladder,windowCap)
matchedIndex = find([ladder.rungs.reference],1,'first');
if isempty(matchedIndex) || ...
        ~ladder.rungs(matchedIndex).resultAvailable
    for index = 1:numel(ladder.rungs)
        comparison = empty_comparison();
        comparison.status = 'matched_result_unavailable';
        ladder.rungs(index).comparisonToMatched = comparison;
    end
    return
end

matched = ipm.output.validate(ladder.rungs(matchedIndex).resultFile);
for index = 1:numel(ladder.rungs)
    comparison = empty_comparison();
    if ~ladder.rungs(index).resultAvailable || ...
            ~strcmp(ladder.rungs(index).rootStatus,'completed')
        comparison.status = 'candidate_result_unavailable';
        ladder.rungs(index).comparisonToMatched = comparison;
        continue
    end
    try
        candidate = ipm.output.validate(ladder.rungs(index).resultFile);
        comparison = bidirectional_comparison( ...
            matched,candidate,windowCap);
    catch exception
        comparison.status = 'comparison_failed';
        comparison.errorIdentifier = exception.identifier;
        comparison.errorMessage = exception.message;
    end
    ladder.rungs(index).comparisonToMatched = comparison;
end
end

function records = compare_successive_large(ladder,windowCap)
large = find(strcmp({ladder.rungs.boxMode},'large_box'));
records = repmat(empty_successive_comparison(),max(numel(large)-1,0),1);
for position = 1:numel(large)-1
    referenceIndex = large(position);
    candidateIndex = large(position+1);
    record = empty_successive_comparison();
    record.referenceRung = ladder.rungs(referenceIndex).name;
    record.candidateRung = ladder.rungs(candidateIndex).name;
    record.referenceHalfWidth = ...
        ladder.rungs(referenceIndex).boxHalfWidth;
    record.candidateHalfWidth = ...
        ladder.rungs(candidateIndex).boxHalfWidth;
    if ~ladder.rungs(referenceIndex).resultAvailable || ...
            ~ladder.rungs(candidateIndex).resultAvailable || ...
            ~strcmp(ladder.rungs(referenceIndex).rootStatus,'completed') || ...
            ~strcmp(ladder.rungs(candidateIndex).rootStatus,'completed')
        record.comparison.status = 'successive_result_unavailable';
        records(position) = record;
        continue
    end
    try
        reference = ipm.output.validate( ...
            ladder.rungs(referenceIndex).resultFile);
        candidate = ipm.output.validate( ...
            ladder.rungs(candidateIndex).resultFile);
        record.comparison = bidirectional_comparison( ...
            reference,candidate,windowCap);
    catch exception
        record.comparison.status = 'comparison_failed';
        record.comparison.errorIdentifier = exception.identifier;
        record.comparison.errorMessage = exception.message;
    end
    records(position) = record;
end
end

function comparison = bidirectional_comparison(reference,candidate,windowCap)
endpointDifference = candidate.state.physicalTime- ...
    reference.state.physicalTime;
endpointTolerance = max(1e-10,100*eps(max([1, ...
    abs(reference.state.physicalTime),abs(candidate.state.physicalTime)])));
if abs(endpointDifference) > endpointTolerance
    error('ipm:GaugeLabQ512BoxLadderEndpoint', ...
        ['Terminal physical times differ by %.3e, exceeding the common-' ...
        'endpoint tolerance %.3e.'],endpointDifference,endpointTolerance);
end
window = common_window(reference,candidate,windowCap);
forward = directional_comparison(reference,candidate,window);
reverse = directional_comparison(candidate,reference,window);
names = comparison_metric_names();
worst = struct();
for index = 1:numel(names)
    name = names{index};
    worst.(name) = max(abs([forward.(name),reverse.(name)]));
end
comparison = empty_comparison();
comparison.available = true;
comparison.status = 'available';
comparison.method = 'bidirectional_absolute_worst';
comparison.commonWindow = window;
comparison.referencePhysicalTime = reference.state.physicalTime;
comparison.candidatePhysicalTime = candidate.state.physicalTime;
comparison.physicalTimeDifference = endpointDifference;
comparison.physicalTimeTolerance = endpointTolerance;
comparison.forward = forward;
comparison.reverse = reverse;
comparison.symmetricWorst = worst;
end

function directional = directional_comparison(reference,candidate,window)
directional = ipm.output.compare(reference,candidate,window);
referenceCommon = reference.history.common;
candidateCommon = candidate.history.common;
referenceGauge = reference.history.gauge;
candidateGauge = candidate.history.gauge;
directional.physicalTimeDifference = ...
    candidate.state.physicalTime-reference.state.physicalTime;
directional.physicalRhoXRelativeDifference = relative_difference( ...
    referenceCommon.physicalRhoXInf(end), ...
    candidateCommon.physicalRhoXInf(end));
directional.canonicalCLRelativeDifference = relative_difference( ...
    referenceCommon.canonicalCL(end),candidateCommon.canonicalCL(end));
directional.canonicalCOmegaRelativeDifference = relative_difference( ...
    referenceCommon.canonicalCOmega(end), ...
    candidateCommon.canonicalCOmega(end));
directional.gradientEnergyRelativeDifference = relative_difference( ...
    referenceGauge.omegaGaugeEnergy(end), ...
    candidateGauge.omegaGaugeEnergy(end));
directional.gradientForcingRelativeDifference = relative_difference( ...
    referenceGauge.omegaGaugeForcing(end), ...
    candidateGauge.omegaGaugeForcing(end));
directional.gradientAbsoluteForcingRelativeDifference = ...
    relative_difference( ...
    referenceGauge.omegaGaugeAbsoluteForcing(end), ...
    candidateGauge.omegaGaugeAbsoluteForcing(end));
directional.forcingCancellationRatioAbsoluteDifference = ...
    candidateGauge.omegaGaugeForcingCancellationRatio(end)- ...
    referenceGauge.omegaGaugeForcingCancellationRatio(end);
end

function window = common_window(reference,candidate,cap)
window = [max([cap(1),min(reference.grid.comovingPhysicalX), ...
    min(candidate.grid.comovingPhysicalX)]), ...
    min([cap(2),max(reference.grid.comovingPhysicalX), ...
    max(candidate.grid.comovingPhysicalX)]), ...
    min([cap(3),max(reference.grid.physicalY), ...
    max(candidate.grid.physicalY)])];
if window(2) <= window(1) || window(3) <= 0
    error('ipm:GaugeLabQ512BoxLadderWindow', ...
        'The matched and candidate results have no common physical window.');
end
end

function names = comparison_metric_names()
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference','physicalTimeDifference', ...
    'physicalRhoXRelativeDifference','canonicalCLRelativeDifference', ...
    'canonicalCOmegaRelativeDifference', ...
    'gradientEnergyRelativeDifference', ...
    'gradientForcingRelativeDifference', ...
    'gradientAbsoluteForcingRelativeDifference', ...
    'forcingCancellationRatioAbsoluteDifference'};
end

function gate = assess_campaign_box_gate(ladder)
gate = empty_box_gate();
gate.targetHalfWidth = ladder.campaignBoxHalfWidth;
large = find(strcmp({ladder.rungs.boxMode},'large_box'));
target = large([ladder.rungs(large).boxHalfWidth] == ...
    ladder.campaignBoxHalfWidth);
if numel(target) ~= 1
    gate.status = 'campaign_box_rung_unavailable';
    gate.failures = {'campaignBoxRungAvailable'};
    return
end
target = target(1);
smaller = large([ladder.rungs(large).boxHalfWidth] < ...
    ladder.campaignBoxHalfWidth);
if isempty(smaller)
    gate.status = 'predecessor_rung_unavailable';
    gate.failures = {'campaignBoxPredecessorAvailable'};
    return
end
[~,position] = max([ladder.rungs(smaller).boxHalfWidth]);
reference = smaller(position);
gate.referenceRung = ladder.rungs(reference).name;
gate.candidateRung = ladder.rungs(target).name;
gate.referenceHalfWidth = ladder.rungs(reference).boxHalfWidth;
gate.candidateHalfWidth = ladder.rungs(target).boxHalfWidth;
matches = arrayfun(@(record) ...
    strcmp(record.referenceRung,gate.referenceRung) && ...
    strcmp(record.candidateRung,gate.candidateRung), ...
    ladder.successiveLargeComparisons);
if nnz(matches) ~= 1
    gate.status = 'campaign_box_comparison_unavailable';
    gate.failures = {'campaignBoxComparisonAvailable'};
    return
end
comparison = ladder.successiveLargeComparisons(matches).comparison;
gate.comparison = comparison;
if ~comparison.available
    gate.status = 'campaign_box_comparison_unavailable';
    gate.failures = {'campaignBoxComparisonAvailable'};
    return
end
worst = comparison.symmetricWorst;
limits = ladder.hardLimits;
terminalFar = ladder.rungs(target).metrics.farBoundary.terminal;
checks = struct();
checks.campaignBoxComparisonAvailable = comparison.available;
checks.allRootsPostAudited = all([ladder.rungs.postAuditPassed]);
largeRungs = strcmp({ladder.rungs.boxMode},'large_box');
checks.allLargeBoxTransportAnchorsAreExactNodes = ...
    all([ladder.rungs(largeRungs).anchorIsGridNode]);
checks.physicalEndpoint = comparison.available && ...
    abs(comparison.physicalTimeDifference) <= ...
    limits.maximumPhysicalEndpointDifference;
checks.rhoRelativeL2 = comparison.available && ...
    worst.rhoRelativeL2 <= limits.maximumRhoRelativeL2;
checks.omegaRelativeL2 = comparison.available && ...
    worst.omegaRelativeL2 <= limits.maximumOmegaRelativeL2;
checks.rhoAbsoluteInf = comparison.available && ...
    worst.rhoAbsoluteInf <= limits.maximumRhoAbsoluteInf;
checks.omegaAbsoluteInf = comparison.available && ...
    worst.omegaAbsoluteInf <= limits.maximumOmegaAbsoluteInf;
checks.labPeakShift = comparison.available && ...
    worst.labPeakShift <= limits.maximumLabPeakShift;
checks.wallPeak = comparison.available && ...
    worst.wallPeakRelativeDifference <= ...
    limits.maximumWallPeakRelativeDifference;
checks.wallWidth = comparison.available && ...
    worst.wallWidthRelativeDifference <= ...
    limits.maximumWallWidthRelativeDifference;
checks.physicalRhoX = comparison.available && ...
    worst.physicalRhoXRelativeDifference <= ...
    limits.maximumPhysicalRhoXRelativeDifference;
checks.canonicalCL = comparison.available && ...
    worst.canonicalCLRelativeDifference <= ...
    limits.maximumCanonicalCLRelativeDifference;
checks.canonicalCOmega = comparison.available && ...
    worst.canonicalCOmegaRelativeDifference <= ...
    limits.maximumCanonicalCOmegaRelativeDifference;
checks.gradientEnergy = comparison.available && ...
    worst.gradientEnergyRelativeDifference <= ...
    limits.maximumGradientEnergyRelativeDifference;
checks.gradientForcing = comparison.available && ...
    worst.gradientForcingRelativeDifference <= ...
    limits.maximumGradientForcingRelativeDifference;
checks.gradientAbsoluteForcing = comparison.available && ...
    worst.gradientAbsoluteForcingRelativeDifference <= ...
    limits.maximumGradientAbsoluteForcingRelativeDifference;
checks.forcingCancellationRatio = comparison.available && ...
    worst.forcingCancellationRatioAbsoluteDifference <= ...
    limits.maximumForcingCancellationRatioAbsoluteDifference;
checks.campaignFarSource = isfinite(terminalFar.sourceRatio) && ...
    terminalFar.sourceRatio <= limits.maximumFarBoundarySourceRatio;
checks.campaignFarVelocity = isfinite(terminalFar.velocityRatio) && ...
    terminalFar.velocityRatio <= limits.maximumFarBoundaryVelocityRatio;
gate.checks = checks;
gate.failures = failed_checks(checks);
gate.passed = isempty(gate.failures);
if gate.passed
    gate.status = 'passed';
else
    gate.status = 'gate_failed';
end
end

function limits = box_hard_limits()
limits = struct( ...
    'maximumPhysicalEndpointDifference',1e-10, ...
    'maximumRhoRelativeL2',5e-4, ...
    'maximumOmegaRelativeL2',5e-3, ...
    'maximumRhoAbsoluteInf',5e-4, ...
    'maximumOmegaAbsoluteInf',5e-3, ...
    'maximumLabPeakShift',2e-2, ...
    'maximumWallPeakRelativeDifference',1e-2, ...
    'maximumWallWidthRelativeDifference',1e-2, ...
    'maximumPhysicalRhoXRelativeDifference',5e-3, ...
    'maximumCanonicalCLRelativeDifference',1e-2, ...
    'maximumCanonicalCOmegaRelativeDifference',1e-2, ...
    'maximumGradientEnergyRelativeDifference',1e-2, ...
    'maximumGradientForcingRelativeDifference',2e-2, ...
    'maximumGradientAbsoluteForcingRelativeDifference',2e-2, ...
    'maximumForcingCancellationRatioAbsoluteDifference',5e-2, ...
    'maximumFarBoundarySourceRatio',1e-2, ...
    'maximumFarBoundaryVelocityRatio',1e-2);
end

function value = relative_difference(reference,candidate)
if ~isfinite(reference) || ~isfinite(candidate)
    value = NaN;
    return
end
scale = max(abs([reference,candidate]));
if scale == 0
    value = 0;
else
    value = (candidate-reference)/scale;
end
end

function require_history(group,names,label)
for index = 1:numel(names)
    name = names{index};
    if ~isfield(group,name) || ~isnumeric(group.(name)) || ...
            ~isreal(group.(name)) || ~isvector(group.(name)) || ...
            isempty(group.(name)) || any(~isfinite(group.(name)))
        error('ipm:GaugeLabQ512BoxLadderHistory', ...
            '%s.%s must be a nonempty finite numeric series.',label,name);
    end
end
end

function recovered = recover_root_summary(outputRoot)
recovered = [];
candidates = dir(fullfile(outputRoot,'root_*','root_summary.mat'));
if isempty(candidates)
    return
end
[~,order] = sort([candidates.datenum],'descend');
fileName = fullfile(candidates(order(1)).folder, ...
    candidates(order(1)).name);
loaded = load(fileName,'rootRun');
if isfield(loaded,'rootRun') && isstruct(loaded.rootRun) && ...
        isscalar(loaded.rootRun)
    recovered = loaded.rootRun;
end
end

function failures = ladder_failures(ladder,settings)
failures = cell(0,1);
expected = expected_root_status(settings);
for index = 1:numel(ladder.rungs)
    record = ladder.rungs(index);
    if ~strcmp(record.status,expected)
        failures{end+1,1} = sprintf('%s:root:%s', ...
            record.name,record.status); %#ok<AGROW>
    elseif settings.executeSmoke && ...
            ~record.comparisonToMatched.available
        failures{end+1,1} = sprintf('%s:comparison:%s', ...
            record.name,record.comparisonToMatched.status); %#ok<AGROW>
    end
end
if settings.executeSmoke
    for index = 1:numel(ladder.successiveLargeComparisons)
        record = ladder.successiveLargeComparisons(index);
        if ~record.comparison.available
            failures{end+1,1} = sprintf('%s_to_%s:comparison:%s', ...
                record.referenceRung,record.candidateRung, ...
                record.comparison.status); %#ok<AGROW>
        end
    end
    for index = 1:numel(ladder.campaignBoxGate.failures)
        failures{end+1,1} = sprintf('campaign_box_gate:%s', ...
            ladder.campaignBoxGate.failures{index}); %#ok<AGROW>
    end
end
end

function status = expected_root_status(settings)
if settings.executeSmoke
    status = 'completed';
else
    status = 'preflight_only';
end
end

function mode = execution_mode(settings)
if settings.executeSmoke
    mode = 'smoke';
else
    mode = 'preflight_only';
end
end

function requested = requested_summary(settings)
requested = struct( ...
    'executeSmoke',settings.executeSmoke, ...
    'rootRunMode','smoke', ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'canonicalFinalTime',settings.canonicalFinalTime, ...
    'maxDt',settings.maxDt, ...
    'maxSteps',settings.maxSteps, ...
    'cfl',settings.cfl, ...
    'outputEvery',settings.outputEvery, ...
    'checkpointEvery',settings.checkpointEvery);
end

function record = empty_rung()
record = struct( ...
    'index',NaN, ...
    'name','', ...
    'boxMode','', ...
    'boxHalfWidth',NaN, ...
    'reference',false, ...
    'status','', ...
    'startedUtc','', ...
    'completedUtc','', ...
    'rootOutputRoot','', ...
    'rootStatus','', ...
    'rootAccepted',false, ...
    'rootSummaryFile','', ...
    'rootManifestFile','', ...
    'meshPassed',false, ...
    'contractPassed',false, ...
    'anchorNodeDistance',NaN, ...
    'anchorIsGridNode',false, ...
    'resultAvailable',false, ...
    'resultFile','', ...
    'checkpointFile','', ...
    'postAuditPassed',false, ...
    'wallSeconds',NaN, ...
    'steps',NaN, ...
    'wallSecondsPerStep',NaN, ...
    'stopReason','', ...
    'metrics',empty_metrics(), ...
    'comparisonToMatched',empty_comparison(), ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function metrics = empty_metrics()
metrics = struct( ...
    'available',false, ...
    'clocks',struct(), ...
    'rates',struct(), ...
    'gradientEnergy',struct(), ...
    'physicalDomain',struct(), ...
    'farBoundary',struct(), ...
    'physicalRhoXInf',struct(), ...
    'cost',struct(), ...
    'gaugeRateConvergence',struct(), ...
    'maximumGrowthRate',struct(), ...
    'canonicalMaximumGrowth',struct());
end

function record = empty_successive_comparison()
record = struct( ...
    'referenceRung','', ...
    'candidateRung','', ...
    'referenceHalfWidth',NaN, ...
    'candidateHalfWidth',NaN, ...
    'comparison',empty_comparison());
end

function comparison = empty_comparison()
comparison = struct( ...
    'available',false, ...
    'status','not_executed', ...
    'method','bidirectional_absolute_worst', ...
    'commonWindow',[NaN,NaN,NaN], ...
    'referencePhysicalTime',NaN, ...
    'candidatePhysicalTime',NaN, ...
    'physicalTimeDifference',NaN, ...
    'physicalTimeTolerance',NaN, ...
    'forward',struct(), ...
    'reverse',struct(), ...
    'symmetricWorst',struct(), ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function gate = empty_box_gate()
gate = struct( ...
    'status','not_executed', ...
    'targetHalfWidth',1e6, ...
    'referenceRung','', ...
    'candidateRung','', ...
    'referenceHalfWidth',NaN, ...
    'candidateHalfWidth',NaN, ...
    'comparison',empty_comparison(), ...
    'checks',struct(), ...
    'failures',{{}}, ...
    'passed',false);
end

function failures = failed_checks(checks)
names = fieldnames(checks);
failures = names(~cellfun(@(name)isequal(checks.(name),true),names));
failures = failures(:)';
end

function name = rung_name(halfWidth)
% Seventeen significant digits give a one-to-one text representation for
% distinct finite IEEE-754 doubles; rounded scientific notation did not.
raw = sprintf('large_%.17g',halfWidth);
name = strrep(raw,'+','');
name = strrep(name,'-','m');
name = strrep(name,'.','p');
end

function value = numeric_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
end

function value = logical_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
valid = (islogical(value) && isscalar(value)) || ...
    (isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && any(value == [0,1]));
if ~valid
    error('ipm:GaugeLabQ512BoxLadderOptions', ...
        'Option %s must be a logical scalar.',name);
end
value = logical(value);
end

function value = path_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabQ512BoxLadderOptions', ...
        'Option %s must be a nonempty path.',name);
end
end

function root = default_output_root()
fileName = mfilename('fullpath');
gaugeDirectory = fileparts(fileName);
researchDirectory = fileparts(gaugeDirectory);
repositoryRoot = fileparts(researchDirectory);
root = fullfile(repositoryRoot,'result','verification', ...
    'q512_fresh_box_ladders_v4');
end

function [directory,ladderId] = create_output_directory(root)
if ~isfolder(root)
    mkdir(root);
end
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
[~,token] = fileparts(tempname);
ladderId = sprintf('ladder_%s_%s',stamp,token);
directory = fullfile(root,ladderId);
if isfile(directory) || isfolder(directory)
    error('ipm:GaugeLabQ512BoxLadderOutputCollision', ...
        'Output path already exists: %s',directory);
end
mkdir(directory);
end

function save_summary(fileName,ladder)
save(fileName,'ladder');
end

function append_manifest(fileName,record)
fileId = fopen(fileName,'a');
if fileId < 0
    error('ipm:GaugeLabQ512BoxLadderManifest', ...
        'Could not append manifest %s.',fileName);
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function require_root_runner()
if exist('ipm_gaugelab_run_q512_root','file') ~= 2
    error('ipm:GaugeLabQ512BoxLadderPath', ...
        ['ipm_gaugelab_run_q512_root is not on the MATLAB path.  Add ' ...
        'research/gauge_lab before calling this runner.']);
end
end

function value = utc_stamp()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
