function ladder = ipm_gaugelab_run_q512_cfl_ladder(options)
%IPM_GAUGELAB_RUN_Q512_CFL_LADDER Register two fresh q512 CFL roots.
%   LADDER = IPM_GAUGELAB_RUN_Q512_CFL_LADDER() preregisters independent
%   cfl=0.25 and cfl=0.50 roots on the same large box, whose default
%   half-width is 1e6.  The default is preflight-only and executes no PDE.
%
%   OPTIONS.execute=true runs both bounded short campaigns from the
%   analytic datum.  The orchestrator supplies runMode='campaign' and
%   confirmLongRun=true internally to ipm_gaugelab_run_q512_root.  It has
%   no checkpoint or restart input, and neither candidate may resume an
%   artifact.
%
%   Executed roots record endpoint/cost summaries, every accepted step's
%   timestep telemetry, and the complete gauge-rate and maximum-
%   growth diagnostics.  Terminal fields are compared in both
%   interpolation directions on one common physical window.  Registered
%   tolerances are short-window CFL-consistency gates only; passing them is
%   not late-time or asymptotic evidence.

if nargin < 1 || isempty(options)
    options = struct();
end
settings = resolve_options(options);
require_root_runner();

[outputDirectory,ladderId] = create_output_directory(settings.outputRoot);
summaryFile = fullfile(outputDirectory,'cfl_ladder_summary.mat');
manifestFile = fullfile(outputDirectory,'cfl_ladder_manifest.jsonl');
rootOutputDirectory = fullfile(outputDirectory,'roots');
mkdir(rootOutputDirectory);

specifications = cfl_specifications();
roots = repmat(empty_root_record(),numel(specifications),1);
for index = 1:numel(specifications)
    roots(index).index = index;
    roots(index).name = specifications(index).name;
    roots(index).cfl = specifications(index).cfl;
    roots(index).status = 'pending';
end

startedUtc = utc_stamp();
ladder = struct( ...
    'schemaVersion',4, ...
    'kind','q512_fresh_exact_gauge_cfl_ladder', ...
    'ladderId',ladderId, ...
    'status','registered', ...
    'startedUtc',startedUtc, ...
    'completedUtc','', ...
    'executionMode',execution_mode(settings), ...
    'freshRootsOnly',true, ...
    'checkpointInputsAccepted',false, ...
    'rootRunMode','campaign', ...
    'internalConfirmLongRun',true, ...
    'cflCandidates',[specifications.cfl], ...
    'onlyConfigurationVariable','time.cfl', ...
    'sameBoxRequired',true, ...
    'gaugeContract',gauge_contract(), ...
    'numericalTuple',numerical_tuple(), ...
    'requested',requested_summary(settings), ...
    'comparisonMethod','bidirectional_common_physical_window', ...
    'comparisonWindowCap',settings.comparisonWindowCap, ...
    'hardLimits',hard_limits(), ...
    'interpretation', ...
        'short_window_cfl_consistency_only_not_late_time_evidence', ...
    'lateTimeEvidence',false, ...
    'outputDirectory',outputDirectory, ...
    'rootOutputDirectory',rootOutputDirectory, ...
    'summaryFile',summaryFile, ...
    'manifestFile',manifestFile, ...
    'roots',roots, ...
    'sharedContractAudit',empty_shared_contract_audit(), ...
    'comparison',empty_comparison(), ...
    'completedRoots',0, ...
    'successfulRoots',0, ...
    'preflightPassed',false, ...
    'hardPassed',false, ...
    'orchestrationWallSeconds',NaN, ...
    'sumRootSolveWallSeconds',NaN, ...
    'failures',{{}});
save_summary(summaryFile,ladder);
append_manifest(manifestFile,struct( ...
    'event','cfl_ladder_registered', ...
    'timestampUtc',startedUtc, ...
    'ladderId',ladderId, ...
    'executionMode',ladder.executionMode, ...
    'freshRootsOnly',true, ...
    'checkpointInputsAccepted',false, ...
    'rootRunMode','campaign', ...
    'internalConfirmLongRun',true, ...
    'cflCandidates',ladder.cflCandidates, ...
    'onlyConfigurationVariable',ladder.onlyConfigurationVariable, ...
    'requested',ladder.requested, ...
    'hardLimits',ladder.hardLimits, ...
    'interpretation',ladder.interpretation, ...
    'summaryFile',summaryFile));

orchestrationClock = tic;
for index = 1:numel(specifications)
    specification = specifications(index);
    record = ladder.roots(index);
    record.status = 'root_running';
    record.startedUtc = utc_stamp();
    record.rootOutputRoot = fullfile( ...
        rootOutputDirectory,specification.name);
    ladder.roots(index) = record;
    save_summary(summaryFile,ladder);
    append_manifest(manifestFile,struct( ...
        'event','cfl_root_started', ...
        'timestampUtc',record.startedUtc, ...
        'ladderId',ladderId, ...
        'root',record.name, ...
        'cfl',record.cfl, ...
        'boxMode',settings.boxMode, ...
        'boxHalfWidth',settings.boxHalfWidth, ...
        'execute',settings.execute, ...
        'freshStart',true, ...
        'restartInput','none'));

    rootOptions = root_options( ...
        settings,specification,record.rootOutputRoot);
    try
        rootRun = ipm_gaugelab_run_q512_root(rootOptions);
        record = populate_from_root(record,rootRun,settings.execute);
    catch exception
        record.status = 'root_failed';
        record.errorIdentifier = exception.identifier;
        record.errorMessage = exception.message;
        recovered = recover_root_summary(record.rootOutputRoot);
        if ~isempty(recovered)
            try
                record = populate_from_root( ...
                    record,recovered,settings.execute);
            catch recoveryException
                record.errorMessage = sprintf('%s | recovery: %s', ...
                    record.errorMessage,recoveryException.message);
            end
            record.status = 'root_failed';
            record.errorIdentifier = exception.identifier;
        end
    end
    record.completedUtc = utc_stamp();
    ladder.roots(index) = record;
    ladder.completedRoots = index;
    save_summary(summaryFile,ladder);
    append_manifest(manifestFile,struct( ...
        'event','cfl_root_finished', ...
        'timestampUtc',record.completedUtc, ...
        'ladderId',ladderId, ...
        'root',record.name, ...
        'cfl',record.cfl, ...
        'status',record.status, ...
        'rootStatus',record.rootStatus, ...
        'freshStart',record.freshStart, ...
        'restartInput',record.restartInput, ...
        'meshPassed',record.meshPassed, ...
        'contractPassed',record.contractPassed, ...
        'resultAvailable',record.resultAvailable, ...
        'steps',record.cost.steps, ...
        'wallSeconds',record.cost.wallSeconds, ...
        'rootSummaryFile',record.rootSummaryFile, ...
        'resultFile',record.resultFile, ...
        'errorIdentifier',record.errorIdentifier, ...
        'errorMessage',record.errorMessage));
end

ladder.sharedContractAudit = shared_contract_audit( ...
    ladder.roots,settings,specifications);
if settings.execute && all([ladder.roots.resultAvailable])
    try
        reference = ipm.output.validate(ladder.roots(1).resultFile);
        candidate = ipm.output.validate(ladder.roots(2).resultFile);
        ladder.comparison = bidirectional_comparison( ...
            reference,candidate,ladder.roots(1),ladder.roots(2), ...
            settings.comparisonWindowCap,ladder.hardLimits);
    catch exception
        ladder.comparison.status = 'comparison_failed';
        ladder.comparison.errorIdentifier = exception.identifier;
        ladder.comparison.errorMessage = exception.message;
    end
elseif settings.execute
    ladder.comparison.status = 'root_result_unavailable';
else
    ladder.comparison.status = 'preflight_only_not_executed';
end

ladder.orchestrationWallSeconds = toc(orchestrationClock);
rootTimes = arrayfun(@(record)record.cost.wallSeconds,ladder.roots);
rootTimes = rootTimes(isfinite(rootTimes));
if isempty(rootTimes)
    ladder.sumRootSolveWallSeconds = 0;
else
    ladder.sumRootSolveWallSeconds = sum(rootTimes);
end
expected = expected_root_status(settings);
ladder.successfulRoots = nnz(strcmp({ladder.roots.status},expected));
ladder.preflightPassed = ...
    ladder.successfulRoots == numel(ladder.roots) && ...
    ladder.sharedContractAudit.passed;
ladder.hardPassed = settings.execute && ladder.preflightPassed && ...
    ladder.comparison.available && ladder.comparison.hardPassed;
ladder.failures = ladder_failures(ladder,settings);
if ~ladder.preflightPassed
    ladder.status = 'partial_failure';
elseif ~settings.execute
    ladder.status = 'preflight_complete';
elseif ladder.hardPassed
    ladder.status = 'short_cfl_passed';
else
    ladder.status = 'short_cfl_gate_failed';
end
ladder.completedUtc = utc_stamp();
save_summary(summaryFile,ladder);
append_manifest(manifestFile,struct( ...
    'event','cfl_ladder_finished', ...
    'timestampUtc',ladder.completedUtc, ...
    'ladderId',ladderId, ...
    'status',ladder.status, ...
    'successfulRoots',ladder.successfulRoots, ...
    'preflightPassed',ladder.preflightPassed, ...
    'hardPassed',ladder.hardPassed, ...
    'comparisonStatus',ladder.comparison.status, ...
    'comparisonAvailable',ladder.comparison.available, ...
    'orchestrationWallSeconds',ladder.orchestrationWallSeconds, ...
    'sumRootSolveWallSeconds',ladder.sumRootSolveWallSeconds, ...
    'interpretation',ladder.interpretation, ...
    'failures',{ladder.failures}));

fprintf(['Q512 CFL LADDER: status=%s, roots=%d/%d, ' ...
    'comparison=%s, wall=%.3f s, summary=%s\n'], ...
    ladder.status,ladder.successfulRoots,numel(ladder.roots), ...
    ladder.comparison.status,ladder.orchestrationWallSeconds,summaryFile);
end

function settings = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeLabQ512CflLadderOptions', ...
        'options must be a scalar structure.');
end
allowed = {'execute','boxMode','boxHalfWidth','outputRoot','verbose', ...
    'physicalFinalTime','canonicalFinalTime','maxDt','maxSteps', ...
    'outputEvery','checkpointEvery','comparisonWindowCap'};
unknown = setdiff(fieldnames(options),allowed,'stable');
if ~isempty(unknown)
    error('ipm:GaugeLabQ512CflLadderOptions', ...
        'Unknown option(s): %s.',strjoin(unknown,', '));
end

settings = struct();
settings.execute = logical_option(options,'execute',false);
settings.boxMode = text_option(options,'boxMode','large_box');
settings.boxHalfWidth = numeric_option(options,'boxHalfWidth',[]);
settings.outputRoot = path_option( ...
    options,'outputRoot',default_output_root());
settings.verbose = logical_option(options,'verbose',false);
settings.physicalFinalTime = numeric_option( ...
    options,'physicalFinalTime',0.03);
settings.canonicalFinalTime = numeric_option( ...
    options,'canonicalFinalTime',0.05);
settings.maxDt = numeric_option(options,'maxDt',0.004);
settings.maxSteps = numeric_option(options,'maxSteps',512);
settings.outputEvery = numeric_option(options,'outputEvery',1e-10);
settings.checkpointEvery = numeric_option( ...
    options,'checkpointEvery',0.01);
settings.comparisonWindowCap = numeric_option( ...
    options,'comparisonWindowCap',[-2,2,2]);

if ~any(strcmp(settings.boxMode,{'matched','large_box'}))
    error('ipm:GaugeLabQ512CflLadderBoxMode', ...
        'boxMode must be ''matched'' or ''large_box''.');
end
if strcmp(settings.boxMode,'matched')
    if isempty(settings.boxHalfWidth)
        settings.boxHalfWidth = 281;
    else
        validateattributes(settings.boxHalfWidth,{'numeric'}, ...
            {'scalar','real','finite','positive'},mfilename, ...
            'boxHalfWidth');
        if settings.boxHalfWidth ~= 281
            error('ipm:GaugeLabQ512CflLadderMatchedBox', ...
                ['The matched q512 factory is registered only at half-' ...
                'width 281.']);
        end
    end
else
    if isempty(settings.boxHalfWidth)
        settings.boxHalfWidth = 1e6;
    end
    validateattributes(settings.boxHalfWidth,{'numeric'}, ...
        {'scalar','real','finite','>',2},mfilename,'boxHalfWidth');
end

validateattributes(settings.physicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',0.03},mfilename, ...
    'physicalFinalTime');
validateattributes(settings.canonicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',0.05},mfilename, ...
    'canonicalFinalTime');
validateattributes(settings.maxDt,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',0.004},mfilename,'maxDt');
validateattributes(settings.maxSteps,{'numeric'}, ...
    {'scalar','real','finite','integer','positive','<=',1024}, ...
    mfilename,'maxSteps');
validateattributes(settings.outputEvery,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'outputEvery');
validateattributes(settings.checkpointEvery,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'checkpointEvery');
validateattributes(settings.comparisonWindowCap,{'numeric'}, ...
    {'vector','numel',3,'real','finite'},mfilename, ...
    'comparisonWindowCap');
settings.comparisonWindowCap = settings.comparisonWindowCap(:)';
if settings.comparisonWindowCap(2) <= ...
        settings.comparisonWindowCap(1) || ...
        settings.comparisonWindowCap(3) <= 0
    error('ipm:GaugeLabQ512CflLadderWindow', ...
        'comparisonWindowCap must be [xMin,xMax,yMax] with nonempty area.');
end
end

function specifications = cfl_specifications()
specifications = struct( ...
    'name',{'cfl_025','cfl_050'}, ...
    'cfl',{0.25,0.50});
end

function options = root_options(settings,specification,outputRoot)
options = struct( ...
    'boxMode',settings.boxMode, ...
    'runMode','campaign', ...
    'confirmLongRun',true, ...
    'preflightOnly',~settings.execute, ...
    'outputRoot',outputRoot, ...
    'verbose',settings.verbose, ...
    'cfl',specification.cfl, ...
    'maxDt',settings.maxDt, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'canonicalFinalTime',settings.canonicalFinalTime, ...
    'maxSteps',settings.maxSteps, ...
    'outputEvery',settings.outputEvery, ...
    'checkpointEvery',settings.checkpointEvery);
if strcmp(settings.boxMode,'large_box')
    options.boxHalfWidth = settings.boxHalfWidth;
end
end

function record = populate_from_root(record,rootRun,executed)
record.rootStatus = rootRun.status;
record.rootAccepted = any(strcmp(rootRun.status, ...
    {'preflight_only','completed'}));
record.boxMode = rootRun.boxMode;
record.runMode = rootRun.runMode;
record.preflightOnly = rootRun.preflightOnly;
record.freshStart = isequal(rootRun.freshStart,true);
record.restartInput = rootRun.restartInput;
record.rootSummaryFile = rootRun.summaryFile;
record.rootManifestFile = rootRun.manifestFile;
record.meshPassed = rootRun.meshPassed;
record.contractPassed = rootRun.contractPassed;
record.anchorNodeDistance = rootRun.meshAudit.anchorNodeDistance;
record.anchorIsGridNode = rootRun.meshAudit.anchorIsGridNode;
record.domain = rootRun.domain;
record.requested = rootRun.requested;
record.configSignature = config_signature(rootRun);
record.resultFile = rootRun.resultFile;
record.checkpointFile = rootRun.checkpointFile;
record.cost = struct( ...
    'steps',rootRun.steps, ...
    'wallSeconds',rootRun.wallSeconds, ...
    'wallSecondsPerStep',rootRun.wallSecondsPerStep);
record.stopReason = rootRun.stopReason;
record.status = rootRun.status;
if executed && ~isempty(rootRun.resultFile) && isfile(rootRun.resultFile)
    result = ipm.output.validate(rootRun.resultFile);
    record = summarize_result(record,result,rootRun);
    record.resultAvailable = true;
end
end

function record = summarize_result(record,result,rootRun)
common = result.history.common;
required = {'acceptedStep','canonicalTau','physicalTime','c_l', ...
    'c_omega','canonicalCL','canonicalCOmega','C_l','C_omega', ...
    'physicalRhoXInf','acceptedCanonicalDt','realizedCfl', ...
    'timestepActiveLimiter'};
require_history(common,required,'history.common');

terminal = numel(common.canonicalTau);
cL = common.canonicalCL(terminal);
cOmega = common.canonicalCOmega(terminal);
record.endpoint = struct( ...
    'canonicalTime',result.state.canonicalTime, ...
    'physicalTime',result.state.physicalTime, ...
    'physicalRhoXInf',common.physicalRhoXInf(terminal), ...
    'cL',cL, ...
    'cOmega',cOmega, ...
    'kappa',cL-cOmega, ...
    'cOmegaOverCL',safe_ratio(cOmega,cL), ...
    'cLMinusCOmegaOverCL',safe_ratio(cL-cOmega,cL), ...
    'C_l',common.C_l(terminal), ...
    'C_omega',common.C_omega(terminal), ...
    'physicalX',result.grid.physicalX([1,end]), ...
    'physicalY',result.grid.physicalY([1,end]), ...
    'comovingPhysicalX',result.grid.comovingPhysicalX([1,end]));
record.cost = struct( ...
    'steps',result.state.steps, ...
    'wallSeconds',rootRun.wallSeconds, ...
    'wallSecondsPerStep',rootRun.wallSecondsPerStep);
record.timestep = timestep_statistics( ...
    common,result.state.steps,record.cfl,result.config.time.maxDt, ...
    record.requested.outputEvery,result.config.time.minDt);
record.diagnostics = struct( ...
    'evidenceWindow','short_window_only', ...
    'lateTimeEvidence',false, ...
    'gaugeRateConvergence',result.fit.gaugeRateConvergence, ...
    'maximumGrowthRate',result.fit.maximumGrowthRate, ...
    'canonicalMaximumGrowth',result.fit.canonicalMaximumGrowth);
record.integrity = struct( ...
    'trustedTerminal',rootRun.postAudit.checks.continuousTrustedTerminal, ...
    'exactContract',rootRun.postAudit.checks.resultContract, ...
    'postAuditPassed',rootRun.postAudit.hardPassed, ...
    'postAuditFailures',{rootRun.postAudit.failures});
end

function statistics = timestep_statistics( ...
        common,steps,cfl,maxDt,outputEvery,minDt)
acceptedStep = common.acceptedStep(:);
acceptedDt = common.acceptedCanonicalDt(:);
realizedCfl = common.realizedCfl(:);
activeLimiter = string(common.timestepActiveLimiter(:));
accepted = isfinite(acceptedDt) & acceptedDt > 0;
recordedSteps = acceptedStep(accepted);
dtValues = acceptedDt(accepted);
cflValues = realizedCfl(accepted);
limiterValues = activeLimiter(accepted);

statistics = struct( ...
    'sampling','all_accepted_steps_requested', ...
    'outputEvery',outputEvery, ...
    'minimumAcceptedDt',minDt, ...
    'outputCadenceAtOrBelowMinimumDt',outputEvery <= minDt, ...
    'outputRecordCount',numel(acceptedStep), ...
    'acceptedStepSampleCount',nnz(accepted), ...
    'solverAcceptedSteps',steps, ...
    'completeAcceptedStepCoverage',false, ...
    'acceptedSteps',recordedSteps, ...
    'acceptedCanonicalDt',dtValues, ...
    'realizedCfl',cflValues, ...
    'activeLimiter',limiterValues, ...
    'acceptedCanonicalDtStatistics',distribution(dtValues), ...
    'realizedCflStatistics',distribution(cflValues), ...
    'activeLimiterCounts',limiter_counts(limiterValues), ...
    'requestedCfl',cfl, ...
    'requestedMaximumDt',maxDt, ...
    'maximumDtRespected',false, ...
    'maximumCflRespected',false);
if ~isempty(recordedSteps)
    uniqueSteps = unique(recordedSteps,'stable');
    statistics.completeAcceptedStepCoverage = ...
        numel(uniqueSteps) == steps && ...
        isequal(uniqueSteps(:),(1:steps)');
end
dtTolerance = 100*eps(max(1,maxDt));
cflTolerance = 100*eps(max(1,cfl));
statistics.maximumDtRespected = ~isempty(dtValues) && ...
    all(dtValues <= maxDt+dtTolerance);
statistics.maximumCflRespected = ~isempty(cflValues) && ...
    all(isfinite(cflValues)) && all(cflValues >= 0) && ...
    all(cflValues <= cfl+cflTolerance);
end

function values = distribution(samples)
values = struct('count',numel(samples),'minimum',NaN,'maximum',NaN, ...
    'mean',NaN,'median',NaN,'standardDeviation',NaN);
if isempty(samples) || any(~isfinite(samples))
    return
end
values.minimum = min(samples);
values.maximum = max(samples);
values.mean = mean(samples);
values.median = median(samples);
values.standardDeviation = std(samples,0);
end

function counts = limiter_counts(values)
known = ["max_dt","cfl","canonical_final_time", ...
    "physical_final_time"];
raw = zeros(size(known));
for index = 1:numel(known)
    raw(index) = nnz(values == known(index));
end
other = numel(values)-sum(raw);
denominator = max(numel(values),1);
counts = struct( ...
    'records',numel(values), ...
    'maxDt',raw(1), ...
    'cfl',raw(2), ...
    'canonicalFinalTime',raw(3), ...
    'physicalFinalTime',raw(4), ...
    'other',other, ...
    'maxDtFraction',raw(1)/denominator, ...
    'cflFraction',raw(2)/denominator, ...
    'canonicalFinalTimeFraction',raw(3)/denominator, ...
    'physicalFinalTimeFraction',raw(4)/denominator, ...
    'otherFraction',other/denominator);
end

function audit = shared_contract_audit(roots,settings,specifications)
checks = struct();
checks.twoRegisteredRoots = numel(roots) == 2;
checks.fixedCflCandidates = isequal([roots.cfl],[0.25,0.50]) && ...
    isequal([roots.cfl],[specifications.cfl]);
checks.campaignRootMode = all(strcmp({roots.runMode},'campaign'));
checks.expectedPreflightMode = ...
    all([roots.preflightOnly]) == ~settings.execute;
checks.freshStarts = all([roots.freshStart]);
checks.noRestartInputs = all(strcmp({roots.restartInput},'none'));
checks.sameDomain = isequaln(roots(1).domain,roots(2).domain);
checks.sameRequestedBoxMode = ...
    all(strcmp({roots.boxMode},settings.boxMode));
checks.requestedSameExceptCfl = requested_same_except_cfl(roots);
checks.configSameExceptCfl = signatures_same_except_cfl(roots);
checks.requestedBox = requested_box(roots,settings);
checks.meshContractsPassed = all([roots.meshPassed]) && ...
    all([roots.contractPassed]);
failures = failed_checks(checks);
audit = struct('checks',checks,'failures',{failures}, ...
    'passed',isempty(failures), ...
    'onlyAllowedDifference','time.cfl');
end

function passed = requested_same_except_cfl(roots)
passed = false;
if numel(roots) ~= 2 || isempty(fieldnames(roots(1).requested)) || ...
        isempty(fieldnames(roots(2).requested))
    return
end
left = roots(1).requested;
right = roots(2).requested;
if ~isfield(left,'cfl') || ~isfield(right,'cfl')
    return
end
left = rmfield(left,'cfl');
right = rmfield(right,'cfl');
passed = isequaln(orderfields(left),orderfields(right));
end

function passed = signatures_same_except_cfl(roots)
passed = false;
if numel(roots) ~= 2 || ...
        isempty(fieldnames(roots(1).configSignature)) || ...
        isempty(fieldnames(roots(2).configSignature))
    return
end
left = roots(1).configSignature;
right = roots(2).configSignature;
if ~isfield(left,'cfl') || ~isfield(right,'cfl')
    return
end
left = rmfield(left,'cfl');
right = rmfield(right,'cfl');
passed = isequaln(orderfields(left),orderfields(right));
end

function passed = requested_box(roots,settings)
passed = all(strcmp({roots.rootStatus},expected_root_status(settings))) && ...
    all(arrayfun(@(record) ...
        isequal(record.domain.initialPhysicalX, ...
        [-settings.boxHalfWidth,settings.boxHalfWidth]),roots));
if strcmp(settings.boxMode,'large_box')
    passed = passed && all(arrayfun(@(record) ...
        isequal(record.domain.initialPhysicalY,[0,settings.boxHalfWidth]), ...
        roots));
else
    passed = passed && all(arrayfun(@(record) ...
        isequal(record.domain.initialPhysicalY,[0,132]),roots));
end
end

function signature = config_signature(rootRun)
config = rootRun.config;
time = config.time;
if isfield(time,'cfl')
    time = rmfield(time,'cfl');
end
output = struct( ...
    'outputEvery',rootRun.requested.outputEvery, ...
    'checkpointEvery',rootRun.requested.checkpointEvery, ...
    'checkpointAtExit',rootRun.requested.checkpointAtExit, ...
    'saveResults',rootRun.requested.saveResults);
signature = struct( ...
    'schemaVersion',config.schemaVersion, ...
    'baseCaseName',rootRun.baseCaseName, ...
    'boxMode',rootRun.boxMode, ...
    'domain',rootRun.domain, ...
    'grid',config.grid, ...
    'transport',config.transport, ...
    'timeExceptCfl',time, ...
    'remesh',config.remesh, ...
    'scaling',config.scaling, ...
    'outputProtocol',output, ...
    'cfl',rootRun.requested.cfl);
end

function comparison = bidirectional_comparison( ...
        reference,candidate,referenceRecord,candidateRecord,cap,limits)
endpointDifference = candidate.state.physicalTime- ...
    reference.state.physicalTime;
endpointTolerance = max(limits.maximumPhysicalEndpointDifference, ...
    100*eps(max([1,abs(reference.state.physicalTime), ...
    abs(candidate.state.physicalTime)])));
if abs(endpointDifference) > endpointTolerance
    error('ipm:GaugeLabQ512CflLadderEndpoint', ...
        ['Terminal physical times differ by %.3e, exceeding the common-' ...
        'endpoint tolerance %.3e.'],endpointDifference,endpointTolerance);
end
window = common_window(reference,candidate,cap);
forward = directional_comparison(reference,candidate,window);
reverse = directional_comparison(candidate,reference,window);
names = physical_metric_names();
worst = struct();
for index = 1:numel(names)
    name = names{index};
    worst.(name) = max(abs([forward.(name),reverse.(name)]));
end

endpoint = endpoint_comparison(referenceRecord,candidateRecord);
rateDiagnostic = rate_diagnostic_comparison( ...
    referenceRecord.diagnostics.gaugeRateConvergence, ...
    candidateRecord.diagnostics.gaugeRateConvergence,limits);
growth = growth_diagnostic_comparison( ...
    referenceRecord.diagnostics,candidateRecord.diagnostics);
checks = comparison_checks( ...
    referenceRecord,candidateRecord,endpoint,worst, ...
    rateDiagnostic,endpointDifference,limits);
failures = failed_checks(checks);

comparison = empty_comparison();
comparison.available = true;
comparison.status = ternary(isempty(failures),'passed','gate_failed');
comparison.method = 'bidirectional_absolute_worst';
comparison.referenceCfl = referenceRecord.cfl;
comparison.candidateCfl = candidateRecord.cfl;
comparison.commonWindow = window;
comparison.referencePhysicalTime = reference.state.physicalTime;
comparison.candidatePhysicalTime = candidate.state.physicalTime;
comparison.physicalTimeDifference = endpointDifference;
comparison.physicalTimeTolerance = endpointTolerance;
comparison.forward = forward;
comparison.reverse = reverse;
comparison.symmetricWorst = worst;
comparison.endpoint = endpoint;
comparison.rateDiagnostics = rateDiagnostic;
comparison.growthDiagnostics = growth;
comparison.checks = checks;
comparison.failures = failures;
comparison.hardPassed = isempty(failures);
end

function directional = directional_comparison(reference,candidate,window)
directional = ipm.output.compare(reference,candidate,window);
referenceCommon = reference.history.common;
candidateCommon = candidate.history.common;
directional.physicalTimeDifference = ...
    candidate.state.physicalTime-reference.state.physicalTime;
directional.physicalRhoXRelativeDifference = relative_difference( ...
    referenceCommon.physicalRhoXInf(end), ...
    candidateCommon.physicalRhoXInf(end));
directional.canonicalTimeRelativeDifference = relative_difference( ...
    reference.state.canonicalTime,candidate.state.canonicalTime);
directional.cLRelativeDifference = relative_difference( ...
    referenceCommon.canonicalCL(end),candidateCommon.canonicalCL(end));
directional.cOmegaRelativeDifference = relative_difference( ...
    referenceCommon.canonicalCOmega(end), ...
    candidateCommon.canonicalCOmega(end));
directional.kappaRelativeDifference = relative_difference( ...
    referenceCommon.canonicalCL(end)- ...
    referenceCommon.canonicalCOmega(end), ...
    candidateCommon.canonicalCL(end)- ...
    candidateCommon.canonicalCOmega(end));
end

function endpoint = endpoint_comparison(reference,candidate)
left = reference.endpoint;
right = candidate.endpoint;
endpoint = struct( ...
    'physicalTimeDifference',right.physicalTime-left.physicalTime, ...
    'canonicalTimeRelativeDifference',relative_difference( ...
        left.canonicalTime,right.canonicalTime), ...
    'physicalRhoXRelativeDifference',relative_difference( ...
        left.physicalRhoXInf,right.physicalRhoXInf), ...
    'cLRelativeDifference',relative_difference(left.cL,right.cL), ...
    'cOmegaRelativeDifference',relative_difference( ...
        left.cOmega,right.cOmega), ...
    'kappaRelativeDifference',relative_difference( ...
        left.kappa,right.kappa), ...
    'cOmegaOverCLRelativeDifference',relative_difference( ...
        left.cOmegaOverCL,right.cOmegaOverCL), ...
    'cLMinusCOmegaOverCLRelativeDifference',relative_difference( ...
        left.cLMinusCOmegaOverCL,right.cLMinusCOmegaOverCL));
end

function diagnostic = rate_diagnostic_comparison(reference,candidate,limits)
diagnostic = struct( ...
    'available',false, ...
    'status','invalid_or_insufficient_short_window', ...
    'appliedToHardGate',false, ...
    'series',struct(), ...
    'hardPassed',false);
if ~isstruct(reference) || ~isstruct(candidate) || ...
        ~isfield(reference,'valid') || ~isfield(candidate,'valid') || ...
        ~reference.valid || ~candidate.valid || ...
        ~isequal(reference.windowFractions,candidate.windowFractions)
    return
end
names = {'cL','cOmega','cOmegaOverCL','cLMinusCOmegaOverCL'};
series = struct();
passed = true;
for index = 1:numel(names)
    name = names{index};
    left = reference.seriesSummary.(name);
    right = candidate.seriesSummary.(name);
    if ~(left.valid && right.valid)
        passed = false;
        series.(name) = struct('available',false);
        continue
    end
    meanDifference = vector_relative_difference( ...
        left.windowWeightedMeans,right.windowWeightedMeans);
    trendDifference = right.windowRelativeTrends- ...
        left.windowRelativeTrends;
    rmsDifference = right.windowRelativeDetrendedRms- ...
        left.windowRelativeDetrendedRms;
    seriesPassed = ...
        max(abs(meanDifference)) <= ...
        limits.maximumRateWindowMeanRelativeDifference && ...
        max(abs(trendDifference)) <= ...
        limits.maximumRateRelativeTrendDifference && ...
        max(abs(rmsDifference)) <= ...
        limits.maximumRateRelativeRmsDifference;
    series.(name) = struct( ...
        'available',true, ...
        'windowMeanRelativeDifference',meanDifference, ...
        'windowRelativeTrendDifference',trendDifference, ...
        'windowRelativeDetrendedRmsDifference',rmsDifference, ...
        'maximumWindowMeanRelativeDifference', ...
            max(abs(meanDifference)), ...
        'maximumRelativeTrendDifference',max(abs(trendDifference)), ...
        'maximumRelativeDetrendedRmsDifference', ...
            max(abs(rmsDifference)), ...
        'hardPassed',seriesPassed);
    passed = passed && seriesPassed;
end
diagnostic.available = true;
diagnostic.status = ternary(passed,'passed','gate_failed');
diagnostic.appliedToHardGate = true;
diagnostic.series = series;
diagnostic.hardPassed = passed;
end

function comparison = growth_diagnostic_comparison(reference,candidate)
comparison = struct( ...
    'interpretation','short_window_diagnostic_only', ...
    'lateTimeEvidence',false, ...
    'physical',growth_pair(reference.maximumGrowthRate, ...
        candidate.maximumGrowthRate), ...
    'canonical',growth_pair(reference.canonicalMaximumGrowth, ...
        candidate.canonicalMaximumGrowth));
end

function pair = growth_pair(reference,candidate)
pair = struct('available',false,'referenceValid',false, ...
    'candidateValid',false,'referenceTotalLogGrowth',NaN, ...
    'candidateTotalLogGrowth',NaN,'totalLogGrowthDifference',NaN, ...
    'referenceCredibleClassification',false, ...
    'candidateCredibleClassification',false);
if ~isstruct(reference) || ~isstruct(candidate) || ...
        ~isfield(reference,'valid') || ~isfield(candidate,'valid')
    return
end
pair.referenceValid = reference.valid;
pair.candidateValid = candidate.valid;
if isfield(reference,'totalLogGrowth')
    pair.referenceTotalLogGrowth = reference.totalLogGrowth;
end
if isfield(candidate,'totalLogGrowth')
    pair.candidateTotalLogGrowth = candidate.totalLogGrowth;
end
pair.totalLogGrowthDifference = ...
    pair.candidateTotalLogGrowth-pair.referenceTotalLogGrowth;
if isfield(reference,'credibleClassification')
    pair.referenceCredibleClassification = ...
        reference.credibleClassification;
end
if isfield(candidate,'credibleClassification')
    pair.candidateCredibleClassification = ...
        candidate.credibleClassification;
end
pair.available = pair.referenceValid && pair.candidateValid;
end

function checks = comparison_checks( ...
        reference,candidate,endpoint,physical,rateDiagnostic, ...
        physicalTimeDifference,limits)
checks = struct();
checks.rootPostAudits = reference.integrity.postAuditPassed && ...
    candidate.integrity.postAuditPassed;
checks.trustedTerminals = reference.integrity.trustedTerminal && ...
    candidate.integrity.trustedTerminal;
checks.exactContracts = reference.integrity.exactContract && ...
    candidate.integrity.exactContract;
checks.recordedTimestepSamples = ...
    reference.timestep.acceptedStepSampleCount > 0 && ...
    candidate.timestep.acceptedStepSampleCount > 0;
checks.completeTimestepCoverage = ...
    reference.timestep.outputCadenceAtOrBelowMinimumDt && ...
    candidate.timestep.outputCadenceAtOrBelowMinimumDt && ...
    reference.timestep.completeAcceptedStepCoverage && ...
    candidate.timestep.completeAcceptedStepCoverage;
checks.maximumDtRespected = reference.timestep.maximumDtRespected && ...
    candidate.timestep.maximumDtRespected;
checks.maximumCflRespected = reference.timestep.maximumCflRespected && ...
    candidate.timestep.maximumCflRespected;
checks.physicalEndpoint = abs(physicalTimeDifference) <= ...
    limits.maximumPhysicalEndpointDifference;
checks.canonicalEndpoint = ...
    abs(endpoint.canonicalTimeRelativeDifference) <= ...
    limits.maximumCanonicalEndpointRelativeDifference;
checks.terminalCL = abs(endpoint.cLRelativeDifference) <= ...
    limits.maximumTerminalCLRelativeDifference;
checks.terminalCOmega = abs(endpoint.cOmegaRelativeDifference) <= ...
    limits.maximumTerminalCOmegaRelativeDifference;
checks.terminalKappa = abs(endpoint.kappaRelativeDifference) <= ...
    limits.maximumTerminalKappaRelativeDifference;
checks.terminalCOmegaOverCL = ...
    abs(endpoint.cOmegaOverCLRelativeDifference) <= ...
    limits.maximumTerminalRateRatioRelativeDifference;
checks.terminalKappaOverCL = ...
    abs(endpoint.cLMinusCOmegaOverCLRelativeDifference) <= ...
    limits.maximumTerminalRateRatioRelativeDifference;
checks.physicalRhoX = ...
    abs(endpoint.physicalRhoXRelativeDifference) <= ...
    limits.maximumPhysicalRhoXRelativeDifference;
checks.rhoRelativeL2 = physical.rhoRelativeL2 <= ...
    limits.maximumRhoRelativeL2;
checks.omegaRelativeL2 = physical.omegaRelativeL2 <= ...
    limits.maximumOmegaRelativeL2;
checks.rhoAbsoluteInf = physical.rhoAbsoluteInf <= ...
    limits.maximumRhoAbsoluteInf;
checks.omegaAbsoluteInf = physical.omegaAbsoluteInf <= ...
    limits.maximumOmegaAbsoluteInf;
checks.labPeakShift = physical.labPeakShift <= ...
    limits.maximumLabPeakShift;
checks.wallPeak = physical.wallPeakRelativeDifference <= ...
    limits.maximumWallPeakRelativeDifference;
checks.wallWidth = physical.wallWidthRelativeDifference <= ...
    limits.maximumWallWidthRelativeDifference;
checks.rateDiagnosticsWhenAvailable = ...
    ~rateDiagnostic.appliedToHardGate || rateDiagnostic.hardPassed;
end

function window = common_window(reference,candidate,cap)
window = [max([cap(1),min(reference.grid.comovingPhysicalX), ...
    min(candidate.grid.comovingPhysicalX)]), ...
    min([cap(2),max(reference.grid.comovingPhysicalX), ...
    max(candidate.grid.comovingPhysicalX)]), ...
    min([cap(3),max(reference.grid.physicalY), ...
    max(candidate.grid.physicalY)])];
if window(2) <= window(1) || window(3) <= 0
    error('ipm:GaugeLabQ512CflLadderWindow', ...
        'The two CFL results have no common physical comparison window.');
end
end

function names = physical_metric_names()
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference','physicalTimeDifference', ...
    'physicalRhoXRelativeDifference', ...
    'canonicalTimeRelativeDifference','cLRelativeDifference', ...
    'cOmegaRelativeDifference','kappaRelativeDifference'};
end

function limits = hard_limits()
limits = struct( ...
    'maximumPhysicalEndpointDifference',1e-10, ...
    'maximumCanonicalEndpointRelativeDifference',1e-2, ...
    'maximumTerminalCLRelativeDifference',1e-2, ...
    'maximumTerminalCOmegaRelativeDifference',1e-2, ...
    'maximumTerminalKappaRelativeDifference',1e-2, ...
    'maximumTerminalRateRatioRelativeDifference',1e-2, ...
    'maximumPhysicalRhoXRelativeDifference',5e-3, ...
    'maximumRhoRelativeL2',5e-4, ...
    'maximumOmegaRelativeL2',5e-3, ...
    'maximumRhoAbsoluteInf',5e-4, ...
    'maximumOmegaAbsoluteInf',5e-3, ...
    'maximumLabPeakShift',2e-2, ...
    'maximumWallPeakRelativeDifference',1e-2, ...
    'maximumWallWidthRelativeDifference',1e-2, ...
    'maximumRateWindowMeanRelativeDifference',1e-2, ...
    'maximumRateRelativeTrendDifference',1e-2, ...
    'maximumRateRelativeRmsDifference',1e-2);
end

function contract = gauge_contract()
contract = struct( ...
    'schemaVersion',4, ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge','gradient_energy', ...
    'rateLimiter','absent', ...
    'timeSpeed',1);
end

function tuple = numerical_tuple()
tuple = struct( ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'adaptiveRemesh',false);
end

function requested = requested_summary(settings)
requested = struct( ...
    'execute',settings.execute, ...
    'boxMode',settings.boxMode, ...
    'boxHalfWidth',settings.boxHalfWidth, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'canonicalFinalTime',settings.canonicalFinalTime, ...
    'maxDt',settings.maxDt, ...
    'maxSteps',settings.maxSteps, ...
    'outputEvery',settings.outputEvery, ...
    'checkpointEvery',settings.checkpointEvery, ...
    'shortCampaignCaps',struct( ...
        'maximumPhysicalFinalTime',0.03, ...
        'maximumCanonicalFinalTime',0.05, ...
        'maximumDt',0.004, ...
        'maximumSteps',1024));
end

function failures = ladder_failures(ladder,settings)
failures = cell(0,1);
expected = expected_root_status(settings);
for index = 1:numel(ladder.roots)
    record = ladder.roots(index);
    if ~strcmp(record.status,expected)
        failures{end+1,1} = sprintf('%s:root:%s', ...
            record.name,record.status); %#ok<AGROW>
    end
end
for index = 1:numel(ladder.sharedContractAudit.failures)
    failures{end+1,1} = sprintf('shared_contract:%s', ...
        ladder.sharedContractAudit.failures{index}); %#ok<AGROW>
end
if settings.execute
    if ~ladder.comparison.available
        failures{end+1,1} = sprintf('comparison:%s', ...
            ladder.comparison.status);
    else
        for index = 1:numel(ladder.comparison.failures)
            failures{end+1,1} = sprintf('comparison_gate:%s', ...
                ladder.comparison.failures{index}); %#ok<AGROW>
        end
    end
end
end

function status = expected_root_status(settings)
if settings.execute
    status = 'completed';
else
    status = 'preflight_only';
end
end

function mode = execution_mode(settings)
if settings.execute
    mode = 'bounded_short_campaign';
else
    mode = 'preflight_only';
end
end

function record = empty_root_record()
record = struct( ...
    'index',NaN, ...
    'name','', ...
    'cfl',NaN, ...
    'status','', ...
    'startedUtc','', ...
    'completedUtc','', ...
    'rootOutputRoot','', ...
    'rootStatus','', ...
    'rootAccepted',false, ...
    'boxMode','', ...
    'runMode','', ...
    'preflightOnly',false, ...
    'freshStart',false, ...
    'restartInput','', ...
    'rootSummaryFile','', ...
    'rootManifestFile','', ...
    'meshPassed',false, ...
    'contractPassed',false, ...
    'anchorNodeDistance',NaN, ...
    'anchorIsGridNode',false, ...
    'domain',struct(), ...
    'requested',struct(), ...
    'configSignature',struct(), ...
    'resultAvailable',false, ...
    'resultFile','', ...
    'checkpointFile','', ...
    'cost',empty_cost(), ...
    'stopReason','', ...
    'endpoint',struct(), ...
    'timestep',struct(), ...
    'diagnostics',struct(), ...
    'integrity',struct(), ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function cost = empty_cost()
cost = struct('steps',NaN,'wallSeconds',NaN, ...
    'wallSecondsPerStep',NaN);
end

function audit = empty_shared_contract_audit()
audit = struct('checks',struct(),'failures',{{}}, ...
    'passed',false,'onlyAllowedDifference','time.cfl');
end

function comparison = empty_comparison()
comparison = struct( ...
    'available',false, ...
    'status','not_executed', ...
    'method','bidirectional_absolute_worst', ...
    'referenceCfl',0.25, ...
    'candidateCfl',0.50, ...
    'commonWindow',[NaN,NaN,NaN], ...
    'referencePhysicalTime',NaN, ...
    'candidatePhysicalTime',NaN, ...
    'physicalTimeDifference',NaN, ...
    'physicalTimeTolerance',NaN, ...
    'forward',struct(), ...
    'reverse',struct(), ...
    'symmetricWorst',struct(), ...
    'endpoint',struct(), ...
    'rateDiagnostics',struct(), ...
    'growthDiagnostics',struct(), ...
    'checks',struct(), ...
    'failures',{{}}, ...
    'hardPassed',false, ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function recovered = recover_root_summary(outputRoot)
recovered = [];
candidates = dir(fullfile(outputRoot,'root_*','root_summary.mat'));
if isempty(candidates)
    return
end
[~,order] = sort([candidates.datenum],'descend');
fileName = fullfile(candidates(order(1)).folder, ...
    candidates(order(1)).name);
loaded = load(fileName,'rootRun');
if isfield(loaded,'rootRun') && isstruct(loaded.rootRun) && ...
        isscalar(loaded.rootRun)
    recovered = loaded.rootRun;
end
end

function require_history(group,names,label)
for index = 1:numel(names)
    name = names{index};
    if ~isfield(group,name) || ...
            ~(isnumeric(group.(name)) || isstring(group.(name))) || ...
            ~isvector(group.(name)) || isempty(group.(name))
        error('ipm:GaugeLabQ512CflLadderHistory', ...
            '%s.%s must be a nonempty vector series.',label,name);
    end
    if isnumeric(group.(name)) && ...
            any(~isfinite(group.(name)) & ~isnan(group.(name)))
        error('ipm:GaugeLabQ512CflLadderHistory', ...
            '%s.%s contains a nonfinite value.',label,name);
    end
end
end

function failures = failed_checks(checks)
names = fieldnames(checks);
failures = cell(0,1);
for index = 1:numel(names)
    if ~isequal(checks.(names{index}),true)
        failures{end+1,1} = names{index}; %#ok<AGROW>
    end
end
end

function value = relative_difference(reference,candidate)
if ~isfinite(reference) || ~isfinite(candidate)
    value = NaN;
    return
end
scale = max([abs(reference),abs(candidate),eps]);
value = (candidate-reference)/scale;
end

function value = vector_relative_difference(reference,candidate)
scale = max(cat(1,abs(reference),abs(candidate), ...
    eps*ones(size(reference))),[],1);
value = (candidate-reference)./scale;
end

function value = safe_ratio(numerator,denominator)
scale = max([1,abs(numerator),abs(denominator)]);
if abs(denominator) <= 100*eps(scale)
    value = NaN;
else
    value = numerator/denominator;
end
end

function value = ternary(condition,trueValue,falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end

function value = numeric_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
end

function value = logical_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
valid = (islogical(value) && isscalar(value)) || ...
    (isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && any(value == [0,1]));
if ~valid
    error('ipm:GaugeLabQ512CflLadderOptions', ...
        'Option %s must be a logical scalar.',name);
end
value = logical(value);
end

function value = text_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabQ512CflLadderOptions', ...
        'Option %s must be nonempty text.',name);
end
value = lower(strtrim(value));
end

function value = path_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabQ512CflLadderOptions', ...
        'Option %s must be a nonempty path.',name);
end
end

function root = default_output_root()
fileName = mfilename('fullpath');
gaugeDirectory = fileparts(fileName);
researchDirectory = fileparts(gaugeDirectory);
repositoryRoot = fileparts(researchDirectory);
root = fullfile(repositoryRoot,'result','verification', ...
    'q512_fresh_cfl_ladders_v4');
end

function [directory,ladderId] = create_output_directory(root)
if ~isfolder(root)
    mkdir(root);
end
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
[~,token] = fileparts(tempname);
ladderId = sprintf('ladder_%s_%s',stamp,token);
directory = fullfile(root,ladderId);
if isfile(directory) || isfolder(directory)
    error('ipm:GaugeLabQ512CflLadderOutputCollision', ...
        'Output path already exists: %s',directory);
end
mkdir(directory);
end

function save_summary(fileName,ladder)
save(fileName,'ladder');
end

function append_manifest(fileName,record)
fileId = fopen(fileName,'a');
if fileId < 0
    error('ipm:GaugeLabQ512CflLadderManifest', ...
        'Could not append manifest %s.',fileName);
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function require_root_runner()
if exist('ipm_gaugelab_run_q512_root','file') ~= 2
    error('ipm:GaugeLabQ512CflLadderPath', ...
        ['ipm_gaugelab_run_q512_root is not on the MATLAB path.  Add ' ...
        'research/gauge_lab before calling this runner.']);
end
end

function value = utc_stamp()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
