function screen = ipm_gaugelab_run_q512_gauge_cfl_screen(options)
%IPM_GAUGELAB_RUN_Q512_GAUGE_CFL_SCREEN Short q512 gauge-by-CFL screen.
%   SCREEN = IPM_GAUGELAB_RUN_Q512_GAUGE_CFL_SCREEN() registers four
%   independent fresh-root calculations on the anchor-aligned H=1e6 q512
%   factory and performs no PDE solve.  The registered pairs are
%
%       c_omega gauge: wall_omega_quadratic_peak, none
%       CFL:           0.25, 0.50
%
%   Set OPTIONS.execute=true explicitly to run the bounded short screen.
%   Every run starts from the analytic datum through the one-argument
%   ipm.solve entry point.  Checkpoint input is not accepted.  The mesh is
%   fixed and the numerical tuple is high_order/WENO5-FD/SSPRK(5,4).
%
%   Both gauges record the same quadratic-peak telemetry in the maintained
%   solver history.  For `none` it is explicitly counterfactual and never
%   feeds the prescribed c_omega=0 rate.  Solver snapshots, result files,
%   and checkpoints are disabled; the schema-4 screen summary
%   contains the complete scalar history, algebraic audits, bidirectional
%   terminal comparisons, and cost record.
%
%   Hard gates cover only short-window numerical consistency and exact
%   algebraic constraints.  Ranking hints are diagnostic.  In particular,
%   `none` is a prescribed zero selected rate and is ineligible for an
%   empirical c_omega convergence claim.  No result from this screen is
%   asymptotic, truncation, grid-convergence, or blowup evidence.

if nargin < 1 || isempty(options)
    options = struct();
end
settings = resolve_options(options);
require_dependencies();

[outputDirectory,screenId] = create_output_directory(settings.outputRoot);
summaryFile = fullfile(outputDirectory,'gauge_cfl_screen_summary.mat');
manifestFile = fullfile(outputDirectory,'gauge_cfl_screen_manifest.jsonl');
specifications = run_specifications();
[flatOptions,configurations] = registered_configurations( ...
    settings,specifications,screenId,outputDirectory);
[meshAudit,meshPassed] = audit_mesh(flatOptions{1},settings.boxHalfWidth);
[contractAudits,sharedAudit,contractsPassed] = ...
    audit_registered_contracts(flatOptions,configurations, ...
    specifications,settings);
syntheticAudit = synthetic_derived_telemetry_audit();

runs = repmat(empty_run_record(),numel(specifications),1);
for index = 1:numel(specifications)
    runs(index).index = index;
    runs(index).name = specifications(index).name;
    runs(index).gauge = specifications(index).gauge;
    runs(index).cfl = specifications(index).cfl;
    runs(index).selectedRatePrescribed = ...
        strcmp(specifications(index).gauge,'none');
    runs(index).empiricalRateConvergenceEligible = ...
        ~runs(index).selectedRatePrescribed;
    runs(index).freshStart = true;
    runs(index).restartInput = 'none';
    runs(index).checkpointInputAccepted = false;
    runs(index).config = configurations{index};
    runs(index).contractAudit = contractAudits(index);
    runs(index).gaugeRule = ipm.evolve.gaugeContract( ...
        configurations{index},struct('x',flatOptions{index}.customX));
    runs(index).status = 'registered';
end

startedUtc = utc_stamp();
screen = struct( ...
    'schemaVersion',4, ...
    'kind','q512_fresh_gauge_cfl_short_time_screen', ...
    'screenId',screenId, ...
    'status','registered', ...
    'startedUtc',startedUtc, ...
    'completedUtc','', ...
    'executionMode',execution_mode(settings), ...
    'freshRootsOnly',true, ...
    'checkpointInputsAccepted',false, ...
    'pdeSolveCount',0, ...
    'boxFamily','anchor_aligned_q512_large_box_factory', ...
    'boxHalfWidth',settings.boxHalfWidth, ...
    'domain',struct('x',[-settings.boxHalfWidth,settings.boxHalfWidth], ...
        'y',[0,settings.boxHalfWidth]), ...
    'gauges',{{'wall_omega_quadratic_peak','none'}}, ...
    'cflCandidates',[0.25,0.50], ...
    'nonExecutedReference',gradient_energy_reference(), ...
    'requested',requested_summary(settings), ...
    'numericalTuple',numerical_tuple(), ...
    'gaugeContract',gauge_contract(), ...
    'counterfactualDefinition',counterfactual_definition(), ...
    'interpretation',[ ...
        'short_time_numerical_and_algebraic_screen_only_not_' ...
        'asymptotic_truncation_grid_or_blowup_evidence'], ...
    'lateTimeEvidence',false, ...
    'truncationEvidence',false, ...
    'gridConvergenceEvidence',false, ...
    'blowupEvidence',false, ...
    'meshAudit',meshAudit, ...
    'meshPassed',meshPassed, ...
    'contractAudits',contractAudits, ...
    'sharedContractAudit',sharedAudit, ...
    'syntheticDerivedTelemetryAudit',syntheticAudit, ...
    'preflightPassed',meshPassed && contractsPassed && ...
        sharedAudit.passed && syntheticAudit.passed, ...
    'hardLimits',hard_limits(), ...
    'runs',runs, ...
    'cflComparisons',repmat(empty_comparison(),0,1), ...
    'gaugeComparisons',repmat(empty_comparison(),0,1), ...
    'rankingHints',empty_ranking_hints(), ...
    'completedRuns',0, ...
    'successfulRuns',0, ...
    'hardPassed',false, ...
    'orchestrationWallSeconds',NaN, ...
    'outputDirectory',outputDirectory, ...
    'summaryFile',summaryFile, ...
    'manifestFile',manifestFile, ...
    'failures',{{}});
save_summary(summaryFile,screen);
append_manifest(manifestFile,struct( ...
    'event','gauge_cfl_screen_registered', ...
    'timestampUtc',startedUtc, ...
    'screenId',screenId, ...
    'schemaVersion',4, ...
    'executionMode',screen.executionMode, ...
    'freshRootsOnly',true, ...
    'checkpointInputsAccepted',false, ...
    'boxHalfWidth',settings.boxHalfWidth, ...
    'gauges',{screen.gauges}, ...
    'cflCandidates',screen.cflCandidates, ...
    'nonExecutedReference',screen.nonExecutedReference, ...
    'requested',screen.requested, ...
    'preflightPassed',screen.preflightPassed, ...
    'summaryFile',summaryFile));

if ~screen.preflightPassed
    screen.status = 'preflight_rejected';
    screen.failures = preflight_failures(screen);
    screen.completedUtc = utc_stamp();
    save_summary(summaryFile,screen);
    append_manifest(manifestFile,struct( ...
        'event','gauge_cfl_screen_preflight_rejected', ...
        'timestampUtc',screen.completedUtc, ...
        'screenId',screenId, ...
        'failures',{screen.failures}));
    error('ipm:GaugeLabQ512GaugeCflPreflight', ...
        'The q512 gauge-by-CFL screen failed preflight; inspect %s.', ...
        summaryFile);
end

if ~settings.execute
    for index = 1:numel(screen.runs)
        screen.runs(index).status = 'preflight_only';
    end
    screen.status = 'preflight_complete';
    screen.completedUtc = utc_stamp();
    screen.failures = {};
    save_summary(summaryFile,screen);
    append_manifest(manifestFile,struct( ...
        'event','gauge_cfl_screen_preflight_complete', ...
        'timestampUtc',screen.completedUtc, ...
        'screenId',screenId, ...
        'pdeSolveCount',0, ...
        'resultFilesWritten',0, ...
        'checkpointFilesWritten',0));
    if settings.verbose
        fprintf(['Q512 GAUGE x CFL PREFLIGHT: 4 fresh roots, H=%.0e, ' ...
            'summary=%s\n'],settings.boxHalfWidth,summaryFile);
    end
    return
end

orchestrationClock = tic;
terminalResults = cell(numel(specifications),1);
for index = 1:numel(specifications)
    specification = specifications(index);
    run = screen.runs(index);
    run.status = 'running';
    run.startedUtc = utc_stamp();
    screen.runs(index) = run;
    save_summary(summaryFile,screen);
    append_manifest(manifestFile,struct( ...
        'event','fresh_root_started', ...
        'timestampUtc',run.startedUtc, ...
        'screenId',screenId, ...
        'run',run.name, ...
        'gauge',run.gauge, ...
        'cfl',run.cfl, ...
        'freshStart',true, ...
        'restartInput','none'));

    solveClock = tic;
    try
        % One argument is deliberate: no checkpoint can enter a screen root.
        screen.pdeSolveCount = screen.pdeSolveCount+1;
        result = ipm.solve(flatOptions{index});
        run.cost.solveWallSeconds = toc(solveClock);
        result = ipm.output.validate(result);
        [telemetry,counterfactualWallSeconds] = ...
            summarize_telemetry(result,specification);
        run.cost.counterfactualWallSeconds = counterfactualWallSeconds;
        run.cost.totalWallSeconds = run.cost.solveWallSeconds+ ...
            counterfactualWallSeconds;
        run.cost.steps = result.state.steps;
        run.cost.solveWallSecondsPerStep = safe_per_step( ...
            run.cost.solveWallSeconds,result.state.steps);
        run.cost.totalWallSecondsPerStep = safe_per_step( ...
            run.cost.totalWallSeconds,result.state.steps);
        run.telemetry = telemetry;
        run.stopReason = result.state.stopReason;
        run.resultMetadata = result.metadata;
        run.resultFile = '';
        run.solverResultRetained = false;
        [run.postAudit,run.hardPassed] = audit_executed_run( ...
            result,run,settings,screen.hardLimits);
        if run.hardPassed
            run.status = 'completed';
        else
            run.status = 'postrun_rejected';
        end
        terminalResults{index} = strip_snapshots(result);
    catch exception
        run.cost.solveWallSeconds = finite_elapsed( ...
            run.cost.solveWallSeconds,solveClock);
        run.status = 'failed';
        run.errorIdentifier = exception.identifier;
        run.errorMessage = exception.message;
        run.hardPassed = false;
    end
    run.completedUtc = utc_stamp();
    screen.runs(index) = run;
    screen.completedRuns = index;
    save_summary(summaryFile,screen);
    append_manifest(manifestFile,run_manifest_record( ...
        screenId,run));
end

screen.successfulRuns = nnz([screen.runs.hardPassed]);
if all(~cellfun(@isempty,terminalResults))
    [screen.cflComparisons,screen.gaugeComparisons] = ...
        build_comparisons(terminalResults,screen.runs, ...
        specifications,settings.comparisonWindowCap,screen.hardLimits);
end
screen.rankingHints = build_ranking_hints( ...
    screen.runs,screen.cflComparisons,screen.gaugeComparisons);
screen.orchestrationWallSeconds = toc(orchestrationClock);
comparisonPass = all([screen.cflComparisons.hardPassed]) && ...
    all([screen.gaugeComparisons.hardPassed]) && ...
    numel(screen.cflComparisons) == 2 && ...
    numel(screen.gaugeComparisons) == 2;
screen.hardPassed = screen.successfulRuns == numel(screen.runs) && ...
    comparisonPass;
screen.failures = execution_failures(screen);
if screen.hardPassed
    screen.status = 'short_screen_passed';
elseif screen.successfulRuns < numel(screen.runs)
    screen.status = 'run_gate_failed';
else
    screen.status = 'comparison_gate_failed';
end
screen.completedUtc = utc_stamp();
save_summary(summaryFile,screen);
append_manifest(manifestFile,struct( ...
    'event','gauge_cfl_screen_finished', ...
    'timestampUtc',screen.completedUtc, ...
    'screenId',screenId, ...
    'status',screen.status, ...
    'pdeSolveCount',screen.pdeSolveCount, ...
    'successfulRuns',screen.successfulRuns, ...
    'hardPassed',screen.hardPassed, ...
    'cflComparisonsPassed',all([screen.cflComparisons.hardPassed]), ...
    'gaugeComparisonsPassed',all([screen.gaugeComparisons.hardPassed]), ...
    'orchestrationWallSeconds',screen.orchestrationWallSeconds, ...
    'failures',{screen.failures}));

if settings.verbose
    fprintf(['Q512 GAUGE x CFL SCREEN: status=%s, runs=%d/%d, ' ...
        'wall=%.3f s, summary=%s\n'],screen.status, ...
        screen.successfulRuns,numel(screen.runs), ...
        screen.orchestrationWallSeconds,summaryFile);
end
end

function settings = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeLabQ512GaugeCflOptions', ...
        'options must be a scalar structure.');
end
allowed = {'execute','preflightOnly','outputRoot','verbose', ...
    'physicalFinalTime','canonicalFinalTime','maxDt','maxSteps', ...
    'outputEvery','comparisonWindowCap'};
unknown = setdiff(fieldnames(options),allowed,'stable');
if ~isempty(unknown)
    error('ipm:GaugeLabQ512GaugeCflOptions', ...
        'Unknown option(s): %s.',strjoin(unknown,', '));
end
executeSpecified = isfield(options,'execute');
settings.execute = logical_option(options,'execute',false);
settings.preflightOnly = logical_option(options,'preflightOnly',false);
if settings.preflightOnly
    if executeSpecified && settings.execute
        error('ipm:GaugeLabQ512GaugeCflOptions', ...
            'execute=true and preflightOnly=true are contradictory.');
    end
    settings.execute = false;
elseif ~settings.execute
    settings.preflightOnly = true;
end
settings.outputRoot = path_option( ...
    options,'outputRoot',default_output_root());
settings.verbose = logical_option(options,'verbose',true);
settings.physicalFinalTime = numeric_option( ...
    options,'physicalFinalTime',0.03);
settings.canonicalFinalTime = numeric_option( ...
    options,'canonicalFinalTime',0.05);
settings.maxDt = numeric_option(options,'maxDt',0.004);
settings.maxSteps = numeric_option(options,'maxSteps',128);
settings.outputEvery = numeric_option(options,'outputEvery',1e-10);
settings.comparisonWindowCap = numeric_option( ...
    options,'comparisonWindowCap',[-2,2,2]);
settings.boxHalfWidth = 1e6;
settings.minimumRecordCount = 16;

validateattributes(settings.physicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',0.05},mfilename, ...
    'physicalFinalTime');
validateattributes(settings.canonicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',0.05},mfilename, ...
    'canonicalFinalTime');
validateattributes(settings.maxDt,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',0.004},mfilename,'maxDt');
validateattributes(settings.maxSteps,{'numeric'}, ...
    {'scalar','real','finite','integer','positive','<=',128}, ...
    mfilename,'maxSteps');
validateattributes(settings.outputEvery,{'numeric'}, ...
    {'scalar','real','finite','positive','<=',1e-10},mfilename, ...
    'outputEvery');
validateattributes(settings.comparisonWindowCap,{'numeric'}, ...
    {'vector','numel',3,'real','finite'},mfilename, ...
    'comparisonWindowCap');
settings.comparisonWindowCap = settings.comparisonWindowCap(:)';
if settings.comparisonWindowCap(2) <= ...
        settings.comparisonWindowCap(1) || ...
        settings.comparisonWindowCap(3) <= 0
    error('ipm:GaugeLabQ512GaugeCflWindow', ...
        'comparisonWindowCap must be [xMin,xMax,yMax].');
end
end

function specifications = run_specifications()
gauges = {'wall_omega_quadratic_peak','none'};
cflValues = [0.25,0.50];
specifications = repmat(struct('name','','gauge','','cfl',NaN),4,1);
cursor = 0;
for gaugeIndex = 1:numel(gauges)
    for cflIndex = 1:numel(cflValues)
        cursor = cursor+1;
        gauge = gauges{gaugeIndex};
        shortGauge = gauge;
        if strcmp(gauge,'wall_omega_quadratic_peak')
            shortGauge = 'quadratic_peak';
        end
        specifications(cursor) = struct( ...
            'name',sprintf('%s_cfl_%03d',shortGauge, ...
                round(100*cflValues(cflIndex))), ...
            'gauge',gauge, ...
            'cfl',cflValues(cflIndex));
    end
end
end

function [flatOptions,configurations] = registered_configurations( ...
        settings,specifications,screenId,outputDirectory)
flatOptions = cell(numel(specifications),1);
configurations = cell(numel(specifications),1);
baseMetadata = run_metadata(screenId,specifications(1));
overrides = struct( ...
    'xlim',[-settings.boxHalfWidth,settings.boxHalfWidth], ...
    'ymax',settings.boxHalfWidth, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'finalTime',settings.canonicalFinalTime, ...
    'maxDt',settings.maxDt, ...
    'maxSteps',settings.maxSteps, ...
    'outputEvery',settings.outputEvery, ...
    'cfl',specifications(1).cfl, ...
    'rescalingMode','dynamic', ...
    'dynamicScaleGeometry','isotropic', ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge',specifications(1).gauge, ...
    'lengthScaleGain',1, ...
    'widthGaugeGain',0, ...
    'omegaGaugeGain',0, ...
    'travelingWaveGain',0, ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'initialAnalyticRemesh',false, ...
    'adaptiveRemesh',false, ...
    'remeshMaximumCellRatio',1.08, ...
    'resultFile',fullfile(outputDirectory, ...
        'solver_result_must_not_exist_quadratic_peak_cfl_025.mat'), ...
    'saveResults',false, ...
    'storeSnapshots',false, ...
    'makePlots',false, ...
    'livePlot',false, ...
    'writeVideo',false, ...
    'verbose',false, ...
    'caseMetadata',baseMetadata);
flatOptions{1} = fourth_order_blowup_case( ...
    'coordinated_log_anchor_F80_R20_large_box_quadrant_512', ...
    overrides);
for index = 1:numel(specifications)
    if index > 1
        flatOptions{index} = flatOptions{1};
    end
    specification = specifications(index);
    flatOptions{index}.cOmegaGauge = specification.gauge;
    flatOptions{index}.cfl = specification.cfl;
    flatOptions{index}.resultFile = fullfile(outputDirectory, ...
        ['solver_result_must_not_exist_',specification.name,'.mat']);
    metadata = run_metadata(screenId,specification);
    flatOptions{index}.caseMetadata. ...
        q512GaugeCflShortScreen = metadata.q512GaugeCflShortScreen;
    configurations{index} = ipm.config.resolve(flatOptions{index});
end
end

function metadata = run_metadata(screenId,specification)
metadata = struct('q512GaugeCflShortScreen',struct( ...
    'schemaVersion',4, ...
    'screenId',screenId, ...
    'freshStart',true, ...
    'restartInput','none', ...
    'checkpointInputAccepted',false, ...
    'boxMode','large_box', ...
    'boxHalfWidth',1e6, ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge',specification.gauge, ...
    'cfl',specification.cfl, ...
    'evidenceScope','bounded_short_time_screen'));
end

function [audits,sharedAudit,passed] = audit_registered_contracts( ...
        flatOptions,configurations,specifications,settings)
audits = repmat(struct('checks',struct(),'failures',{{}}, ...
    'passed',false,'retiredFieldsPresent',{{}}), ...
    numel(specifications),1);
for index = 1:numel(specifications)
    config = configurations{index};
    scaling = config.scaling;
    retired = retired_fields();
    retiredPresent = unique([ ...
        retired(isfield(flatOptions{index},retired)), ...
        retired(isfield(scaling,retired))],'stable');
    checks = struct();
    checks.schema4 = config.schemaVersion == 4 && config.frozen;
    checks.q512 = config.grid.nx == 1025 && config.grid.ny == 513;
    checks.largeBox = endpoint_close(config.grid.xlim,[-1e6,1e6]) && ...
        config.grid.ymax == 1e6;
    checks.activeDatum = strcmp(config.physics.initialCondition, ...
        'degenerate_primitive') && config.physics.degeneratePower == 8 && ...
        strcmp(config.physics.symmetryMode,'double_odd_omega');
    checks.greenOpen = strcmp(config.elliptic.farBoundaryMode,'green') && ...
        strcmp(config.transport.transportBoundaryMode,'open');
    checks.numericalTuple = strcmp( ...
        config.transport.spatialDiscretization,'high_order') && ...
        strcmp(config.transport.transportScheme,'weno5_fd') && ...
        strcmp(config.time.timeIntegrator,'ssprk54') && ...
        strcmp(config.remesh.remeshTransferScheme,'high_order');
    checks.fixedMesh = ~config.remesh.initialAnalyticRemesh && ...
        ~config.remesh.adaptiveRemesh;
    checks.dynamicIsotropic = strcmp(scaling.rescalingMode,'dynamic') && ...
        strcmp(scaling.dynamicScaleGeometry,'isotropic');
    checks.exactNoFeedback = strcmp(scaling.scalingContract, ...
        'exact_gauge_no_feedback_v1') && ...
        scaling.lengthScaleGain == 1 && scaling.widthGaugeGain == 0 && ...
        scaling.omegaGaugeGain == 0 && ...
        scaling.travelingWaveGain == 0;
    checks.transportAnchor = strcmp(scaling.lengthGauge, ...
        'transport_anchor') && scaling.transportAnchorX == 1;
    checks.registeredGauge = strcmp(scaling.cOmegaGauge, ...
        specifications(index).gauge);
    checks.registeredCfl = config.time.cfl == specifications(index).cfl;
    checks.shortBounds = config.time.physicalFinalTime == ...
        settings.physicalFinalTime && config.time.finalTime == ...
        settings.canonicalFinalTime && ...
        config.time.maxDt == settings.maxDt && ...
        config.time.maxSteps == settings.maxSteps;
    checks.everyStepOutput = config.time.outputEvery == ...
        settings.outputEvery && ...
        config.time.outputEvery <= config.time.minDt;
    checks.noSnapshots = ~config.output.storeSnapshots;
    checks.noSolverResultWrite = ~config.output.saveResults;
    checks.noVisualization = ~config.output.makePlots && ...
        ~config.output.livePlot && ~config.output.writeVideo;
    checks.noCheckpoint = ~isfield(config.output,'checkpoint');
    checks.noRetiredFields = isempty(retiredPresent);
    failures = failed_checks(checks);
    audits(index) = struct('checks',checks,'failures',{failures}, ...
        'passed',isempty(failures), ...
        'retiredFieldsPresent',{retiredPresent});
end

reference = normalized_config(configurations{1});
sameExceptGaugeAndCfl = true;
for index = 2:numel(configurations)
    sameExceptGaugeAndCfl = sameExceptGaugeAndCfl && isequaln( ...
        reference,normalized_config(configurations{index}));
end
checks = struct();
checks.fourFreshRoots = numel(specifications) == 4;
checks.fixedGauges = isequal(unique({specifications.gauge},'stable'), ...
    {'wall_omega_quadratic_peak','none'});
checks.fixedCflPair = isequal(unique([specifications.cfl],'stable'), ...
    [0.25,0.50]);
gauges = {'wall_omega_quadratic_peak','none'};
checks.twoRunsPerGauge = all(arrayfun(@(gaugeIndex)nnz(strcmp( ...
    {specifications.gauge},gauges{gaugeIndex})) == 2,1:2));
checks.sameExceptGaugeCflMetadata = sameExceptGaugeAndCfl;
checks.allContractsPassed = all([audits.passed]);
failures = failed_checks(checks);
sharedAudit = struct( ...
    'onlyRegisteredDifferences',{ ...
        {'scaling.cOmegaGauge','time.cfl', ...
        'output.caseMetadata','output.resultFile'}}, ...
    'checks',checks, ...
    'failures',{failures}, ...
    'passed',isempty(failures));
passed = all([audits.passed]);
end

function normalized = normalized_config(config)
normalized = config;
normalized.scaling.cOmegaGauge = '__registered_gauge__';
normalized.time.cfl = NaN;
normalized.output.resultFile = '__disabled_result_file__';
normalized.output.caseMetadata = struct();
normalized = orderfields(normalized);
end

function [audit,passed] = audit_mesh(options,halfWidth)
x = options.customX(:)';
y = options.customY(:);
weightsX = ipm.mesh.quadrature(x);
weightsY = ipm.mesh.quadrature(y);
qualityX = ipm.mesh.quality(x,7,weightsX);
qualityY = ipm.mesh.quality(y,7,weightsY);
[anchorDistance,anchorIndex] = min(abs(x-1));
anchorTolerance = 128*eps(max(1,max(abs(x))));
checks = struct();
checks.nodeCounts = numel(x) == 1025 && numel(y) == 513;
checks.endpoints = endpoint_close(x([1,end]),[-halfWidth,halfWidth]) && ...
    endpoint_close(y([1,end]),[0,halfWidth]);
checks.anchorExact = anchorDistance <= anchorTolerance;
checks.positiveQuadrature = ...
    qualityX.quadratureWeightsStrictlyPositive && ...
    qualityY.quadratureWeightsStrictlyPositive;
checks.adjacentCellRatio = max([qualityX.maximumAdjacentCellRatio, ...
    qualityY.maximumAdjacentCellRatio]) <= 1.08*(1+1e-12);
checks.logSpacingCurvature = max([ ...
    qualityX.maximumLogSpacingCurvature, ...
    qualityY.maximumLogSpacingCurvature]) <= 0.01*(1+1e-12);
checks.stencilRcond = min([qualityX.minimumStencilRcond, ...
    qualityY.minimumStencilRcond]) >= 1e-9*(1-1e-12);
checks.globalQuadrature = min([ ...
    qualityX.minimumQuadratureWeightRatio, ...
    qualityY.minimumQuadratureWeightRatio]) >= 1e-8*(1-1e-12);
checks.localQuadratureLower = min([ ...
    qualityX.minimumQuadratureWeightToControlWidthRatio, ...
    qualityY.minimumQuadratureWeightToControlWidthRatio]) >= ...
    0.35*(1-1e-12);
checks.localQuadratureUpper = max([ ...
    qualityX.maximumQuadratureWeightToControlWidthRatio, ...
    qualityY.maximumQuadratureWeightToControlWidthRatio]) <= ...
    1.65*(1+1e-12);
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct('x',qualityX,'y',qualityY,'checks',checks, ...
    'failures',{failures},'passed',passed,'anchorX',1, ...
    'nearestAnchorNode',x(anchorIndex), ...
    'anchorNodeDistance',anchorDistance, ...
    'anchorNodeTolerance',anchorTolerance, ...
    'anchorIsGridNode',checks.anchorExact);
end

function [telemetry,counterfactualWallSeconds] = summarize_telemetry( ...
        result,specification)
common = result.history.common;
gaugeHistory = result.history.gauge;
requiredCommon = {'acceptedStep','canonicalTau','physicalTime', ...
    'c_l','c_omega','canonicalCL','canonicalCOmega','C_l','C_omega', ...
    'physicalRhoXInf','wallPeak','physicalWallOmegaPeak', ...
    'acceptedCanonicalDt','transportRate','cflDtLimit', ...
    'maximumDtLimit','canonicalEndpointDtLimit', ...
    'physicalEndpointDtLimit','realizedCfl','timestepActiveLimiter', ...
    'farBoundarySource','farBoundarySourceRatio', ...
    'farBoundaryVelocity','farBoundaryVelocityRatio'};
require_history(common,requiredCommon,'history.common');
recordCount = numel(common.canonicalTau);

counterfactualClock = tic;
counterfactual = counterfactual_from_quadratic_history( ...
    common,gaugeHistory,specification.gauge);
counterfactualWallSeconds = toc(counterfactualClock);

cL = common.c_l(:);
cOmega = common.c_omega(:);
kappa = cL-cOmega;
scaleCL = common.C_l(:);
scaleCOmega = common.C_omega(:);
scaleRatio = scaleCL./scaleCOmega;
derived = derive_peak_observables(cL,cOmega,scaleRatio, ...
    counterfactual.peakValue,counterfactual.impliedCOmega, ...
    strcmp(specification.gauge,'none'));
counterfactual.rescaledQuadraticPeakLogRate = ...
    derived.rescaledQuadraticPeakLogRate;
counterfactual.canonicalPhysicalPeakLogRate = ...
    derived.canonicalPhysicalPeakLogRate;
counterfactual.instantaneousPowerExponent = ...
    derived.instantaneousPowerExponent;
counterfactual.wallRiccatiCoefficient = ...
    derived.wallRiccatiCoefficient;
counterfactual.physicalQuadraticPeak = derived.physicalQuadraticPeak;
counterfactual.inversePhysicalQuadraticPeak = ...
    derived.inversePhysicalQuadraticPeak;
counterfactual.counterfactualCOmegaOverCL = ...
    derived.counterfactualCOmegaOverCL;
counterfactual.selectedRatePrescribed = ...
    derived.selectedRatePrescribed;
counterfactual.empiricalRateConvergenceEligible = ...
    derived.empiricalRateConvergenceEligible;

accepted = common.acceptedStep(:) > 0;
timestep = struct( ...
    'sampling','every_accepted_step', ...
    'recordCount',recordCount, ...
    'acceptedStepCount',nnz(accepted), ...
    'acceptedStep',common.acceptedStep(accepted), ...
    'canonicalTau',common.canonicalTau(accepted), ...
    'physicalTime',common.physicalTime(accepted), ...
    'acceptedCanonicalDt',common.acceptedCanonicalDt(accepted), ...
    'transportRate',common.transportRate(accepted), ...
    'cflDtLimit',common.cflDtLimit(accepted), ...
    'maximumDtLimit',common.maximumDtLimit(accepted), ...
    'canonicalEndpointDtLimit', ...
        common.canonicalEndpointDtLimit(accepted), ...
    'physicalEndpointDtLimit', ...
        common.physicalEndpointDtLimit(accepted), ...
    'realizedCfl',common.realizedCfl(accepted), ...
    'activeLimiter',string(common.timestepActiveLimiter(accepted)), ...
    'activeLimiterCounts',limiter_counts( ...
        string(common.timestepActiveLimiter(accepted))));

trajectory = struct( ...
    'acceptedStep',common.acceptedStep(:), ...
    'canonicalTau',common.canonicalTau(:), ...
    'physicalTime',common.physicalTime(:), ...
    'c_l',cL, ...
    'c_omega',cOmega, ...
    'kappa',kappa, ...
    'C_l',scaleCL, ...
    'C_omega',scaleCOmega, ...
    'C_lOverC_omega',scaleRatio, ...
    'physicalRhoXInf',common.physicalRhoXInf(:), ...
    'inversePhysicalRhoXInf',1./common.physicalRhoXInf(:), ...
    'rescaledWallPeak',common.wallPeak(:), ...
    'physicalWallOmegaPeak',common.physicalWallOmegaPeak(:), ...
    'farBoundarySource',common.farBoundarySource(:), ...
    'farBoundarySourceRatio',common.farBoundarySourceRatio(:), ...
    'farBoundaryVelocity',common.farBoundaryVelocity(:), ...
    'farBoundaryVelocityRatio',common.farBoundaryVelocityRatio(:));

telemetry = struct( ...
    'recordCount',recordCount, ...
    'timestep',timestep, ...
    'trajectory',trajectory, ...
    'counterfactualQuadratic',counterfactual, ...
    'endpoint',endpoint_summary(trajectory,counterfactual), ...
    'diagnostics',struct( ...
        'gaugeRateConvergence',result.fit.gaugeRateConvergence, ...
        'maximumGrowthRate',result.fit.maximumGrowthRate, ...
        'canonicalMaximumGrowth',result.fit.canonicalMaximumGrowth), ...
    'quality',result.quality, ...
    'rankingHints',run_ranking_hints(trajectory,counterfactual), ...
    'interpretation',[ ...
        'counterfactual_quadratic_identity_is_semidiscrete_piecewise_' ...
        'smooth;_Riccati_quantities_are_not_WENO_discrete_hard_gates']);
end

function counterfactual = counterfactual_from_quadratic_history( ...
        common,gauge,gaugeName)
required = {'omegaGaugeQuadraticPeakX', ...
    'omegaGaugeQuadraticPeakValue','omegaGaugeQuadraticForcing', ...
    'omegaGaugeQuadraticCurvature', ...
    'omegaGaugeQuadraticNormalizedStationarityResidual', ...
    'omegaGaugeQuadraticCurvatureCondition', ...
    'omegaGaugeQuadraticWeightCondition', ...
    'omegaGaugeQuadraticActiveNodeMargin', ...
    'omegaGaugeQuadraticActiveSelectionMargin', ...
    'omegaGaugeQuadraticStencilCenterX', ...
    'omegaGaugeQuadraticVertexInteriorFraction', ...
    'omegaGaugeQuadraticRelativeSubgridLift', ...
    'omegaGaugeQuadraticRateResidual', ...
    'omegaGaugeQuadraticRateScale'};
require_history(gauge,required,'history.gauge');
peak = gauge.omegaGaugeQuadraticPeakValue(:);
forcing = gauge.omegaGaugeQuadraticForcing(:);
implied = -forcing./peak;
if strcmp(gaugeName,'wall_omega_quadratic_peak')
    runtime = common.c_omega(:);
    evaluationMode = 'active_gauge_history_independent_F_over_P';
else
    % Under `none`, the maintained solver records F and P without using
    % -F/P as its selected rate.  The independently reconstructed value is
    % therefore the counterfactual runtime value for agreement purposes.
    runtime = implied;
    evaluationMode = ...
        'selected_none_history_counterfactual_independent_F_over_P';
end
counterfactual = struct( ...
    'peakX',gauge.omegaGaugeQuadraticPeakX(:), ...
    'peakValue',peak, ...
    'forcing',forcing, ...
    'impliedCOmega',implied, ...
    'counterfactualQuadraticCOmega',implied, ...
    'runtimeQuadraticCOmega',runtime, ...
    'runtimeCOmegaAgreement',runtime-implied, ...
    'gaugeRateResidual',forcing+implied.*peak, ...
    'gaugeRateScale',max([abs(forcing),abs(implied.*peak), ...
        realmin*ones(size(peak))],[],2), ...
    'selectedRateResidual',forcing+common.c_omega(:).*peak, ...
    'curvature',gauge.omegaGaugeQuadraticCurvature(:), ...
    'normalizedStationarityResidual', ...
        gauge.omegaGaugeQuadraticNormalizedStationarityResidual(:), ...
    'curvatureCondition', ...
        gauge.omegaGaugeQuadraticCurvatureCondition(:), ...
    'weightCondition',gauge.omegaGaugeQuadraticWeightCondition(:), ...
    'activeNodeMargin',gauge.omegaGaugeQuadraticActiveNodeMargin(:), ...
    'activeSelectionMargin', ...
        gauge.omegaGaugeQuadraticActiveSelectionMargin(:), ...
    'stencilCenterX',gauge.omegaGaugeQuadraticStencilCenterX(:), ...
    'vertexInteriorFraction', ...
        gauge.omegaGaugeQuadraticVertexInteriorFraction(:), ...
    'relativeSubgridLift', ...
        gauge.omegaGaugeQuadraticRelativeSubgridLift(:), ...
    'recordedRateResidual',gauge.omegaGaugeQuadraticRateResidual(:), ...
    'recordedRateScale',gauge.omegaGaugeQuadraticRateScale(:), ...
    'stencilSwitchCount',count_stencil_switches( ...
        gauge.omegaGaugeQuadraticStencilCenterX(:)), ...
    'evaluationMode',evaluationMode);
end

function derived = derive_peak_observables( ...
        cL,cOmega,scaleRatio,peakValue,impliedCOmega,isPrescribed)
cL = cL(:);
cOmega = cOmega(:);
scaleRatio = scaleRatio(:);
peakValue = peakValue(:);
impliedCOmega = impliedCOmega(:);
kappa = cL-cOmega;
physicalRate = cL-impliedCOmega;
derived = struct( ...
    'rescaledQuadraticPeakLogRate',cOmega-impliedCOmega, ...
    'canonicalPhysicalPeakLogRate',physicalRate, ...
    'instantaneousPowerExponent',safe_series_ratio(physicalRate,kappa), ...
    'wallRiccatiCoefficient',physicalRate./peakValue, ...
    'physicalQuadraticPeak',scaleRatio.*peakValue, ...
    'inversePhysicalQuadraticPeak',1./(scaleRatio.*peakValue), ...
    'counterfactualCOmegaOverCL', ...
        safe_series_ratio(impliedCOmega,cL), ...
    'selectedRatePrescribed',logical(isPrescribed), ...
    'empiricalRateConvergenceEligible',~logical(isPrescribed));
end

function endpoint = endpoint_summary(trajectory,counterfactual)
index = numel(trajectory.canonicalTau);
endpoint = struct( ...
    'canonicalTime',trajectory.canonicalTau(index), ...
    'physicalTime',trajectory.physicalTime(index), ...
    'c_l',trajectory.c_l(index), ...
    'c_omega',trajectory.c_omega(index), ...
    'kappa',trajectory.kappa(index), ...
    'C_l',trajectory.C_l(index), ...
    'C_omega',trajectory.C_omega(index), ...
    'C_lOverC_omega',trajectory.C_lOverC_omega(index), ...
    'physicalRhoXInf',trajectory.physicalRhoXInf(index), ...
    'rescaledWallPeak',trajectory.rescaledWallPeak(index), ...
    'rescaledQuadraticPeak',counterfactual.peakValue(index), ...
    'physicalQuadraticPeak', ...
        counterfactual.physicalQuadraticPeak(index), ...
    'counterfactualQuadraticCOmega', ...
        counterfactual.impliedCOmega(index), ...
    'counterfactualCOmegaOverCL', ...
        counterfactual.counterfactualCOmegaOverCL(index), ...
    'rescaledQuadraticPeakLogRate', ...
        counterfactual.rescaledQuadraticPeakLogRate(index), ...
    'canonicalPhysicalPeakLogRate', ...
        counterfactual.canonicalPhysicalPeakLogRate(index), ...
    'instantaneousPowerExponent', ...
        counterfactual.instantaneousPowerExponent(index), ...
    'wallRiccatiCoefficient', ...
        counterfactual.wallRiccatiCoefficient(index), ...
    'farBoundarySourceRatio',trajectory.farBoundarySourceRatio(index), ...
    'farBoundaryVelocityRatio', ...
        trajectory.farBoundaryVelocityRatio(index));
end

function hints = run_ranking_hints(trajectory,counterfactual)
hints = struct( ...
    'scope','short_time_diagnostic_only', ...
    'cLRelativeDrift',relative_drift(trajectory.c_l), ...
    'selectedCOmegaAbsoluteChange',absolute_change(trajectory.c_omega), ...
    'counterfactualQuadraticCOmegaAbsoluteChange', ...
        absolute_change(counterfactual.impliedCOmega), ...
    'counterfactualCOmegaOverCLAbsoluteChange', ...
        absolute_change(counterfactual.counterfactualCOmegaOverCL), ...
    'rescaledQuadraticPeakRelativeDrift', ...
        relative_drift(counterfactual.peakValue), ...
    'physicalQuadraticPeakRelativeDrift', ...
        relative_drift(counterfactual.physicalQuadraticPeak), ...
    'physicalRhoXInfRelativeDrift', ...
        relative_drift(trajectory.physicalRhoXInf), ...
    'physicalRhoXInfTrend',linear_trend( ...
        trajectory.physicalTime,trajectory.physicalRhoXInf), ...
    'inversePhysicalQuadraticPeakTrend',linear_trend( ...
        trajectory.physicalTime, ...
        counterfactual.inversePhysicalQuadraticPeak), ...
    'inversePhysicalRhoXInfTrend',linear_trend( ...
        trajectory.physicalTime,trajectory.inversePhysicalRhoXInf), ...
    'stencilSwitchCount',counterfactual.stencilSwitchCount);
end

function [audit,passed] = audit_executed_run( ...
        result,run,settings,limits)
common = result.history.common;
gauge = result.history.gauge;
telemetry = run.telemetry;
trajectory = telemetry.trajectory;
counterfactual = telemetry.counterfactualQuadratic;
acceptedSteps = telemetry.timestep.acceptedStep(:);
acceptedDt = telemetry.timestep.acceptedCanonicalDt(:);
realizedCfl = telemetry.timestep.realizedCfl(:);
trusted = ipm.output.trustedMask(result);
endpointAudit = requested_endpoint_audit(result,settings);

checks = struct();
checks.resultSchema = result.schemaVersion == 2 && ...
    result.config.schemaVersion == 4 && result.config.frozen;
checks.freshMetadata = result.config.output.caseMetadata. ...
    q512GaugeCflShortScreen.freshStart && ...
    strcmp(result.config.output.caseMetadata. ...
    q512GaugeCflShortScreen.restartInput,'none');
checks.noCheckpoint = ~isfield(result.config.output,'checkpoint');
checks.noSolverResultWritten = ~result.config.output.saveResults && ...
    strlength(result.metadata.resultFile) == 0;
checks.expectedGauge = strcmp(result.config.scaling.cOmegaGauge,run.gauge);
checks.expectedCfl = result.config.time.cfl == run.cfl;
checks.fixedMesh = result.grid.remeshCount == 0 && ...
    ~result.config.remesh.adaptiveRemesh;
checks.targetReached = endpointAudit.passed;
checks.notStepBudgetLimited = ~strcmp(result.state.stopReason, ...
    'maximum_steps') && result.state.steps <= settings.maxSteps;
checks.minimumRecords = telemetry.recordCount >= ...
    settings.minimumRecordCount;
checks.recordPerAcceptedStep = telemetry.recordCount == ...
    result.state.steps+1 && ...
    isequal(common.acceptedStep(:),(0:result.state.steps)') && ...
    isequal(acceptedSteps,(1:result.state.steps)');
checks.snapshotsDisabled = isempty(result.snapshots.rho) && ...
    ~result.config.output.storeSnapshots;
checks.acceptedTimestepFinite = ~isempty(acceptedDt) && ...
    all(isfinite(acceptedDt) & acceptedDt > 0);
checks.maximumDtRespected = all(acceptedDt <= ...
    settings.maxDt+100*eps(max(1,settings.maxDt)));
checks.maximumCflRespected = all(isfinite(realizedCfl) & ...
    realizedCfl >= 0 & realizedCfl <= ...
    run.cfl+100*eps(max(1,run.cfl)));
checks.limiterRecorded = all(~ismissing( ...
    telemetry.timestep.activeLimiter)) && ...
    all(strlength(telemetry.timestep.activeLimiter) > 0);
checks.allRecordsTrusted = all(trusted);
checks.directClock = all(common.timeSpeed == 1) && ...
    close_series(common.c_l,common.canonicalCL,1e-13) && ...
    close_series(common.c_omega,common.canonicalCOmega,1e-13);
rateDiagnostic = result.fit.gaugeRateConvergence;
checks.rateProvenanceV3 = isstruct(rateDiagnostic) && ...
    isfield(rateDiagnostic,'criteriaVersion') && ...
    rateDiagnostic.criteriaVersion == 3 && ...
    isfield(rateDiagnostic,'selectedRatePrescribed') && ...
    rateDiagnostic.selectedRatePrescribed == ...
        run.selectedRatePrescribed && ...
    isfield(rateDiagnostic,'empiricalRateConvergenceEligible') && ...
    rateDiagnostic.empiricalRateConvergenceEligible == ...
        run.empiricalRateConvergenceEligible;
checks.finiteTrajectory = all_finite_numeric_fields(trajectory);
checks.finiteCounterfactual = ...
    all_finite_numeric_fields(counterfactual, ...
    {'instantaneousPowerExponent'});
checks.exactLengthGauge = isfield(gauge,'lengthGaugeResidual') && ...
    normalized_max(gauge.lengthGaugeResidual,common.c_l) <= ...
    limits.maximumLengthGaugeResidual;
checks.transportAnchorZero = isfield(gauge,'transportAnchorVelocity') && ...
    normalized_max(gauge.transportAnchorVelocity,common.c_l) <= ...
    limits.maximumTransportAnchorVelocity;
checks.counterfactualRateIdentity = max(abs( ...
    counterfactual.gaugeRateResidual./ ...
    counterfactual.gaugeRateScale)) <= ...
    limits.maximumQuadraticRateResidual;
checks.counterfactualRuntimeAgreement = normalized_max( ...
    counterfactual.runtimeCOmegaAgreement, ...
    counterfactual.impliedCOmega) <= ...
    limits.maximumCounterfactualRuntimeAgreement;
checks.recordedSelectedPeakResidual = normalized_max( ...
    counterfactual.recordedRateResidual- ...
    counterfactual.selectedRateResidual, ...
    counterfactual.recordedRateScale) <= ...
    limits.maximumQuadraticRateResidual;
checks.quadraticStationarity = max(abs( ...
    counterfactual.normalizedStationarityResidual)) <= ...
    limits.maximumQuadraticStationarityResidual;
checks.quadraticCondition = min( ...
    counterfactual.curvatureCondition) >= ...
    limits.minimumQuadraticCurvatureCondition && ...
    all(counterfactual.weightCondition > 0);
checks.positiveQuadraticPeak = all( ...
    counterfactual.peakValue > 0) && ...
    all(counterfactual.physicalQuadraticPeak > 0);
checks.finiteFarRatios = all(isfinite([ ...
    trajectory.farBoundarySourceRatio; ...
    trajectory.farBoundaryVelocityRatio]));
if strcmp(run.gauge,'none')
    checks.selectedRatePrescribed = run.selectedRatePrescribed && ...
        ~run.empiricalRateConvergenceEligible;
    checks.selectedRateExactlyZero = all(common.c_omega == 0) && ...
        all(common.canonicalCOmega == 0) && ...
        all(common.C_omega == 1);
else
    checks.selectedRatePrescribed = ~run.selectedRatePrescribed && ...
        run.empiricalRateConvergenceEligible;
    checks.selectedQuadraticRate = normalized_max( ...
        common.c_omega(:)-counterfactual.impliedCOmega, ...
        counterfactual.impliedCOmega) <= ...
        limits.maximumSelectedQuadraticRateDifference;
    checks.selectedQuadraticResidual = normalized_max( ...
        counterfactual.selectedRateResidual, ...
        counterfactual.gaugeRateScale) <= ...
        limits.maximumQuadraticRateResidual;
end
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct( ...
    'checks',checks, ...
    'failures',{failures}, ...
    'passed',passed, ...
    'trustedRecordCount',nnz(trusted), ...
    'recordCount',telemetry.recordCount, ...
    'acceptedStepCount',result.state.steps, ...
    'endpointAudit',endpointAudit, ...
    'maximumNormalizedQuadraticRateResidual',max(abs( ...
        counterfactual.gaugeRateResidual./ ...
        counterfactual.gaugeRateScale)), ...
    'maximumNormalizedStationarityResidual',max(abs( ...
        counterfactual.normalizedStationarityResidual)), ...
    'minimumCurvatureCondition',min( ...
        counterfactual.curvatureCondition), ...
    'maximumFarBoundarySourceRatio',max( ...
        trajectory.farBoundarySourceRatio), ...
    'maximumFarBoundaryVelocityRatio',max( ...
        trajectory.farBoundaryVelocityRatio), ...
    'riccatiQuantitiesAppliedToHardGate',false, ...
    'lateTimeConvergenceAppliedToHardGate',false);
end

function audit = requested_endpoint_audit(result,settings)
state = result.state;
config = result.config;
roundoffPhysical = 100*eps(max(1,abs(settings.physicalFinalTime)));
roundoffCanonical = 100*eps(max(1,abs(settings.canonicalFinalTime)));
physicalClockSpeed = result.scale.Comega/result.scale.Cx;
physicalStopTolerance = max(roundoffPhysical, ...
    config.time.minDt*physicalClockSpeed*(1+100*eps));
canonicalStopTolerance = max(roundoffCanonical,config.time.minDt);
physicalRemainder = settings.physicalFinalTime-state.physicalTime;
canonicalRemainder = settings.canonicalFinalTime-state.canonicalTime;
physicalReached = strcmp(state.stopReason,'physical_final_time') && ...
    physicalRemainder >= -roundoffPhysical && ...
    physicalRemainder <= physicalStopTolerance && ...
    canonicalRemainder >= -roundoffCanonical;
canonicalReached = strcmp(state.stopReason,'final_time') && ...
    canonicalRemainder >= -roundoffCanonical && ...
    canonicalRemainder <= canonicalStopTolerance && ...
    physicalRemainder >= -roundoffPhysical;
audit = struct( ...
    'passed',physicalReached || canonicalReached, ...
    'acceptedPhysicalEndpoint',physicalReached, ...
    'acceptedCanonicalEndpoint',canonicalReached, ...
    'physicalRemainder',physicalRemainder, ...
    'canonicalRemainder',canonicalRemainder, ...
    'physicalStopTolerance',physicalStopTolerance, ...
    'canonicalStopTolerance',canonicalStopTolerance, ...
    'terminalPhysicalClockSpeed',physicalClockSpeed, ...
    'minimumCanonicalStep',config.time.minDt);
end

function [cflComparisons,gaugeComparisons] = build_comparisons( ...
        results,runs,specifications,windowCap,limits)
cflComparisons = repmat(empty_comparison(),2,1);
gauges = {'wall_omega_quadratic_peak','none'};
for index = 1:numel(gauges)
    gauge = gauges{index};
    left = find_specification(specifications,gauge,0.25);
    right = find_specification(specifications,gauge,0.50);
    cflComparisons(index) = physical_comparison( ...
        results{left},results{right},runs(left),runs(right), ...
        windowCap,limits,'same_gauge_cfl',true);
end
gaugeComparisons = repmat(empty_comparison(),2,1);
cflValues = [0.25,0.50];
for index = 1:numel(cflValues)
    cfl = cflValues(index);
    left = find_specification( ...
        specifications,'wall_omega_quadratic_peak',cfl);
    right = find_specification(specifications,'none',cfl);
    gaugeComparisons(index) = physical_comparison( ...
        results{left},results{right},runs(left),runs(right), ...
        windowCap,limits,'same_cfl_gauge_covariance',false);
end
end

function comparison = physical_comparison( ...
        reference,candidate,referenceRun,candidateRun,cap,limits, ...
        comparisonKind,includeRateChecks)
comparison = empty_comparison();
comparison.kind = comparisonKind;
comparison.referenceRun = referenceRun.name;
comparison.candidateRun = candidateRun.name;
comparison.referenceGauge = referenceRun.gauge;
comparison.candidateGauge = candidateRun.gauge;
comparison.referenceCfl = referenceRun.cfl;
comparison.candidateCfl = candidateRun.cfl;
try
    endpointDifference = candidate.state.physicalTime- ...
        reference.state.physicalTime;
    window = common_window(reference,candidate,cap);
    forward = ipm.output.compare(reference,candidate,window);
    reverse = ipm.output.compare(candidate,reference,window);
    names = physical_metric_names();
    worst = struct();
    for index = 1:numel(names)
        name = names{index};
        worst.(name) = max(abs([forward.(name),reverse.(name)]));
    end
    endpoint = struct( ...
        'physicalTimeDifference',endpointDifference, ...
        'physicalRhoXRelativeDifference',symmetric_relative_difference( ...
            referenceRun.telemetry.endpoint.physicalRhoXInf, ...
            candidateRun.telemetry.endpoint.physicalRhoXInf), ...
        'physicalQuadraticPeakRelativeDifference', ...
            symmetric_relative_difference( ...
            referenceRun.telemetry.endpoint.physicalQuadraticPeak, ...
            candidateRun.telemetry.endpoint.physicalQuadraticPeak), ...
        'cLRelativeDifference',symmetric_relative_difference( ...
            referenceRun.telemetry.endpoint.c_l, ...
            candidateRun.telemetry.endpoint.c_l), ...
        'counterfactualCOmegaScaledDifference',scaled_difference( ...
            referenceRun.telemetry.endpoint. ...
                counterfactualQuadraticCOmega, ...
            candidateRun.telemetry.endpoint. ...
                counterfactualQuadraticCOmega,0.1), ...
        'rescaledQuadraticPeakRelativeDifference', ...
            symmetric_relative_difference( ...
            referenceRun.telemetry.endpoint.rescaledQuadraticPeak, ...
            candidateRun.telemetry.endpoint.rescaledQuadraticPeak));
    checks = physical_comparison_checks( ...
        endpointDifference,worst,endpoint,limits);
    if includeRateChecks
        checks.cLConsistency = endpoint.cLRelativeDifference <= ...
            limits.maximumCflCLRelativeDifference;
        checks.counterfactualCOmegaConsistency = ...
            endpoint.counterfactualCOmegaScaledDifference <= ...
            limits.maximumCflCounterfactualCOmegaScaledDifference;
        checks.rescaledQuadraticPeakConsistency = ...
            endpoint.rescaledQuadraticPeakRelativeDifference <= ...
            limits.maximumCflRescaledQuadraticPeakRelativeDifference;
    end
    failures = failed_checks(checks);
    comparison.available = true;
    comparison.status = ternary(isempty(failures),'passed','gate_failed');
    comparison.commonWindow = window;
    comparison.forward = forward;
    comparison.reverse = reverse;
    comparison.symmetricWorst = worst;
    comparison.endpoint = endpoint;
    comparison.checks = checks;
    comparison.failures = failures;
    comparison.hardPassed = isempty(failures);
catch exception
    comparison.status = 'comparison_failed';
    comparison.errorIdentifier = exception.identifier;
    comparison.errorMessage = exception.message;
end
end

function checks = physical_comparison_checks( ...
        endpointDifference,physical,endpoint,limits)
checks = struct();
checks.physicalEndpoint = abs(endpointDifference) <= ...
    limits.maximumPhysicalEndpointDifference;
checks.rhoRelativeL2 = physical.rhoRelativeL2 <= ...
    limits.maximumRhoRelativeL2;
checks.omegaRelativeL2 = physical.omegaRelativeL2 <= ...
    limits.maximumOmegaRelativeL2;
checks.rhoAbsoluteInf = physical.rhoAbsoluteInf <= ...
    limits.maximumRhoAbsoluteInf;
checks.omegaAbsoluteInf = physical.omegaAbsoluteInf <= ...
    limits.maximumOmegaAbsoluteInf;
checks.labPeakShift = physical.labPeakShift <= ...
    limits.maximumLabPeakShift;
checks.wallPeak = physical.wallPeakRelativeDifference <= ...
    limits.maximumWallPeakRelativeDifference;
checks.wallWidth = physical.wallWidthRelativeDifference <= ...
    limits.maximumWallWidthRelativeDifference;
checks.physicalRhoX = endpoint.physicalRhoXRelativeDifference <= ...
    limits.maximumPhysicalRhoXRelativeDifference;
checks.physicalQuadraticPeak = ...
    endpoint.physicalQuadraticPeakRelativeDifference <= ...
    limits.maximumPhysicalQuadraticPeakRelativeDifference;
end

function window = common_window(reference,candidate,cap)
window = [max([cap(1),min(reference.grid.comovingPhysicalX), ...
    min(candidate.grid.comovingPhysicalX)]), ...
    min([cap(2),max(reference.grid.comovingPhysicalX), ...
    max(candidate.grid.comovingPhysicalX)]), ...
    min([cap(3),max(reference.grid.physicalY), ...
    max(candidate.grid.physicalY)])];
if window(2) <= window(1) || window(3) <= 0
    error('ipm:GaugeLabQ512GaugeCflWindow', ...
        'The terminal results have no common physical comparison window.');
end
end

function index = find_specification(specifications,gauge,cfl)
matches = strcmp({specifications.gauge},gauge) & ...
    [specifications.cfl] == cfl;
if nnz(matches) ~= 1
    error('ipm:GaugeLabQ512GaugeCflSpecification', ...
        'A unique gauge-by-CFL specification was not found.');
end
index = find(matches,1);
end

function hints = build_ranking_hints(runs,cflComparisons,gaugeComparisons)
runHints = repmat(struct('run','','gauge','','cfl',NaN, ...
    'metrics',struct()),numel(runs),1);
for index = 1:numel(runs)
    runHints(index).run = runs(index).name;
    runHints(index).gauge = runs(index).gauge;
    runHints(index).cfl = runs(index).cfl;
    if isfield(runs(index).telemetry,'rankingHints')
        metrics = runs(index).telemetry.rankingHints;
        metrics.solveWallSeconds = runs(index).cost.solveWallSeconds;
        metrics.counterfactualWallSeconds = ...
            runs(index).cost.counterfactualWallSeconds;
        metrics.totalWallSeconds = runs(index).cost.totalWallSeconds;
        metrics.solveWallSecondsPerStep = ...
            runs(index).cost.solveWallSecondsPerStep;
        runHints(index).metrics = metrics;
    end
end

gauges = {'wall_omega_quadratic_peak','none'};
gaugeHints = repmat(struct('gauge','','promotionBlocked',true, ...
    'promotionBlockReason','','empiricalRateConvergenceEligible',false, ...
    'cflComparisonPassed',false,'maximumAbsoluteCLRelativeDrift',NaN, ...
    'maximumCounterfactualCOmegaAbsoluteChange',NaN, ...
    'maximumAbsoluteRescaledPeakRelativeDrift',NaN, ...
    'cfl050SolveSpeedupOverCfl025',NaN),2,1);
for gaugeIndex = 1:numel(gauges)
    gauge = gauges{gaugeIndex};
    selected = find(strcmp({runs.gauge},gauge));
    gaugeHints(gaugeIndex).gauge = gauge;
    gaugeHints(gaugeIndex).empiricalRateConvergenceEligible = ...
        ~strcmp(gauge,'none');
    if strcmp(gauge,'none')
        gaugeHints(gaugeIndex).promotionBlockReason = [ ...
            'prescribed_zero_selected_rate_requires_long_tail_box_' ...
            'and_grid_evidence'];
    else
        gaugeHints(gaugeIndex).promotionBlockReason = ...
            'short_screen_only_requires_long_tail_box_and_grid_evidence';
    end
    if numel(cflComparisons) == 2
        gaugeHints(gaugeIndex).cflComparisonPassed = ...
            cflComparisons(gaugeIndex).hardPassed;
    end
    if numel(selected) == 2 && all(arrayfun(@(index) ...
            isfield(runs(index).telemetry,'rankingHints'),selected))
        local = [runs(selected).telemetry];
        local = [local.rankingHints];
        gaugeHints(gaugeIndex).maximumAbsoluteCLRelativeDrift = ...
            max(abs([local.cLRelativeDrift]));
        gaugeHints(gaugeIndex). ...
            maximumCounterfactualCOmegaAbsoluteChange = max( ...
            [local.counterfactualQuadraticCOmegaAbsoluteChange]);
        gaugeHints(gaugeIndex). ...
            maximumAbsoluteRescaledPeakRelativeDrift = max(abs( ...
            [local.rescaledQuadraticPeakRelativeDrift]));
        cfl025 = selected([runs(selected).cfl] == 0.25);
        cfl050 = selected([runs(selected).cfl] == 0.50);
        gaugeHints(gaugeIndex).cfl050SolveSpeedupOverCfl025 = ...
            runs(cfl025).cost.solveWallSeconds / ...
            max(runs(cfl050).cost.solveWallSeconds,realmin);
    end
end
hints = struct( ...
    'status','diagnostic_hints_only_no_promotion', ...
    'orderedWinnerDeclared',false, ...
    'quantities',{{'c_l drift','counterfactual c_omega change', ...
        'counterfactual c_omega/c_l','quadratic peak drift', ...
        'physical rho_x and inverse trends', ...
        'inverse physical quadratic peak trend','cost'}}, ...
    'runs',runHints, ...
    'gauges',gaugeHints, ...
    'cflComparisonsPassed',numel(cflComparisons) == 2 && ...
        all([cflComparisons.hardPassed]), ...
    'gaugeCovariancePassed',numel(gaugeComparisons) == 2 && ...
        all([gaugeComparisons.hardPassed]), ...
    'nonePromotionBlocked',true, ...
    'noneEmpiricalRateConvergenceEligible',false);
end

function audit = synthetic_derived_telemetry_audit()
cL = [0.50;0.55];
selected = [0.10;0];
scaleRatio = [1.2;1.4];
peak = [2;2.5];
implied = [0.10;0.125];
active = derive_peak_observables( ...
    cL(1),selected(1),scaleRatio(1),peak(1),implied(1),false);
prescribed = derive_peak_observables( ...
    cL(2),selected(2),scaleRatio(2),peak(2),implied(2),true);
checks = struct();
checks.activeRescaledRateZero = ...
    active.rescaledQuadraticPeakLogRate == 0;
checks.activePowerExponentOne = ...
    active.instantaneousPowerExponent == 1;
checks.physicalPeakScaling = ...
    active.physicalQuadraticPeak == scaleRatio(1)*peak(1) && ...
    prescribed.physicalQuadraticPeak == scaleRatio(2)*peak(2);
checks.noneRescaledRate = prescribed.rescaledQuadraticPeakLogRate == ...
    -implied(2);
checks.nonePhysicalRate = prescribed.canonicalPhysicalPeakLogRate == ...
    cL(2)-implied(2);
checks.nonePowerExponent = abs( ...
    prescribed.instantaneousPowerExponent- ...
    (cL(2)-implied(2))/(cL(2)-selected(2))) <= eps;
checks.noneRiccatiCoefficient = ...
    prescribed.wallRiccatiCoefficient == ...
    (cL(2)-implied(2))/peak(2);
checks.prescriptionFlags = prescribed.selectedRatePrescribed && ...
    ~prescribed.empiricalRateConvergenceEligible && ...
    ~active.selectedRatePrescribed && ...
    active.empiricalRateConvergenceEligible;
failures = failed_checks(checks);
audit = struct( ...
    'kind','no_pde_synthetic_derived_telemetry', ...
    'checks',checks, ...
    'failures',{failures}, ...
    'passed',isempty(failures), ...
    'riccatiQuantitiesAppliedToDiscreteHardGate',false);
end

function result = strip_snapshots(result)
result.snapshots.rho = {};
result.snapshots.x = {};
result.snapshots.y = {};
result.snapshots.normalizedTime = [];
result.snapshots.canonicalTime = [];
result.snapshots.physicalTime = [];
result = ipm.output.validate(result);
end

function record = run_manifest_record(screenId,run)
endpoint = struct();
ranking = struct();
recordCount = NaN;
if isfield(run.telemetry,'endpoint')
    endpoint = run.telemetry.endpoint;
    ranking = run.telemetry.rankingHints;
    recordCount = run.telemetry.recordCount;
end
record = struct( ...
    'event','fresh_root_finished', ...
    'timestampUtc',run.completedUtc, ...
    'screenId',screenId, ...
    'run',run.name, ...
    'gauge',run.gauge, ...
    'cfl',run.cfl, ...
    'status',run.status, ...
    'hardPassed',run.hardPassed, ...
    'freshStart',run.freshStart, ...
    'restartInput',run.restartInput, ...
    'selectedRatePrescribed',run.selectedRatePrescribed, ...
    'empiricalRateConvergenceEligible', ...
        run.empiricalRateConvergenceEligible, ...
    'recordCount',recordCount, ...
    'cost',run.cost, ...
    'endpoint',endpoint, ...
    'rankingHints',ranking, ...
    'resultFileWritten',false, ...
    'checkpointFileWritten',false, ...
    'errorIdentifier',run.errorIdentifier, ...
    'errorMessage',run.errorMessage);
end

function failures = preflight_failures(screen)
failures = cell(0,1);
if ~screen.meshPassed
    failures{end+1,1} = 'mesh';
end
for index = 1:numel(screen.contractAudits)
    for failureIndex = 1:numel(screen.contractAudits(index).failures)
        failures{end+1,1} = sprintf('run_%d_contract:%s',index, ...
            screen.contractAudits(index).failures{failureIndex}); %#ok<AGROW>
    end
end
for index = 1:numel(screen.sharedContractAudit.failures)
    failures{end+1,1} = ['shared_contract:', ...
        screen.sharedContractAudit.failures{index}]; %#ok<AGROW>
end
for index = 1:numel(screen.syntheticDerivedTelemetryAudit.failures)
    failures{end+1,1} = ['synthetic:', ...
        screen.syntheticDerivedTelemetryAudit.failures{index}]; %#ok<AGROW>
end
end

function failures = execution_failures(screen)
failures = cell(0,1);
for index = 1:numel(screen.runs)
    run = screen.runs(index);
    if ~run.hardPassed
        failures{end+1,1} = sprintf('%s:%s',run.name,run.status); %#ok<AGROW>
        if isfield(run.postAudit,'failures')
            for failureIndex = 1:numel(run.postAudit.failures)
                failures{end+1,1} = sprintf('%s:%s',run.name, ...
                    run.postAudit.failures{failureIndex}); %#ok<AGROW>
            end
        end
    end
end
groups = {'cflComparisons','gaugeComparisons'};
for groupIndex = 1:numel(groups)
    comparisons = screen.(groups{groupIndex});
    for index = 1:numel(comparisons)
        if ~comparisons(index).hardPassed
            failures{end+1,1} = sprintf('%s:%s', ...
                groups{groupIndex},comparisons(index).status); %#ok<AGROW>
            for failureIndex = 1:numel(comparisons(index).failures)
                failures{end+1,1} = sprintf('%s:%s', ...
                    groups{groupIndex}, ...
                    comparisons(index).failures{failureIndex}); %#ok<AGROW>
            end
        end
    end
end
end

function reference = gradient_energy_reference()
reference = struct( ...
    'gauge','gradient_energy', ...
    'executed',false, ...
    'status','excluded_after_q512_initial_box_screen', ...
    'reason',[ ...
        'full_gradient_energy_and_forcing_are_extensive_for_the_' ...
        'registered_degenerate_primitive_large_box_family'], ...
    'role','nonexecuted_negative_control_reference');
end

function definition = counterfactual_definition()
definition = struct( ...
    'symbol','cHatOmega', ...
    'formula','cHatOmega=-F/P', ...
    'peakFunctional', ...
        'three_point_nonuniform_quadratic_wall_R_X_peak', ...
    'rescaledQuadraticPeakLogRate','c_omega-cHatOmega', ...
    'canonicalPhysicalPeakLogRate','c_l-cHatOmega', ...
    'instantaneousPowerExponent','(c_l-cHatOmega)/(c_l-c_omega)', ...
    'wallRiccatiCoefficient','(c_l-cHatOmega)/P', ...
    'physicalQuadraticPeak','(C_l/C_omega)*P', ...
    'discreteScope',[ ...
        'F_plus_cHatOmega_times_P_is_the_piecewise_semidiscrete_' ...
        'algebraic_gate'], ...
    'riccatiScope', ...
        'diagnostic_continuum_interpretation_not_a_WENO_discrete_identity');
end

function contract = gauge_contract()
contract = struct( ...
    'schemaVersion',4, ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'amplitudeGauges',{{'wall_omega_quadratic_peak','none'}}, ...
    'rateLimiter','absent', ...
    'feedback','absent', ...
    'timeSpeed',1);
end

function tuple = numerical_tuple()
tuple = struct( ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'initialAnalyticRemesh',false, ...
    'adaptiveRemesh',false);
end

function requested = requested_summary(settings)
requested = struct( ...
    'execute',settings.execute, ...
    'preflightOnly',settings.preflightOnly, ...
    'defaultExecution','preflight_only', ...
    'boxHalfWidth',settings.boxHalfWidth, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'canonicalFinalTime',settings.canonicalFinalTime, ...
    'maxDt',settings.maxDt, ...
    'maxSteps',settings.maxSteps, ...
    'outputEvery',settings.outputEvery, ...
    'minimumRecordCount',settings.minimumRecordCount, ...
    'comparisonWindowCap',settings.comparisonWindowCap, ...
    'shortCampaignCaps',struct( ...
        'maximumPhysicalFinalTime',0.05, ...
        'maximumCanonicalFinalTime',0.05, ...
        'maximumDt',0.004, ...
        'maximumSteps',128, ...
        'maximumOutputEvery',1e-10));
end

function limits = hard_limits()
limits = struct( ...
    'minimumRecordCount',16, ...
    'maximumLengthGaugeResidual',1e-12, ...
    'maximumTransportAnchorVelocity',1e-12, ...
    'maximumQuadraticRateResidual',1e-10, ...
    'maximumQuadraticStationarityResidual',1e-10, ...
    'minimumQuadraticCurvatureCondition',1e-6, ...
    'maximumCounterfactualRuntimeAgreement',1e-12, ...
    'maximumSelectedQuadraticRateDifference',1e-12, ...
    'maximumPhysicalEndpointDifference',1e-10, ...
    'maximumRhoRelativeL2',5e-4, ...
    'maximumOmegaRelativeL2',5e-3, ...
    'maximumRhoAbsoluteInf',5e-4, ...
    'maximumOmegaAbsoluteInf',5e-3, ...
    'maximumLabPeakShift',2e-2, ...
    'maximumWallPeakRelativeDifference',1e-2, ...
    'maximumWallWidthRelativeDifference',1e-2, ...
    'maximumPhysicalRhoXRelativeDifference',5e-3, ...
    'maximumPhysicalQuadraticPeakRelativeDifference',5e-3, ...
    'maximumCflCLRelativeDifference',1e-2, ...
    'maximumCflCounterfactualCOmegaScaledDifference',1e-2, ...
    'maximumCflRescaledQuadraticPeakRelativeDifference',1e-2);
end

function hints = empty_ranking_hints()
hints = struct( ...
    'status','not_executed', ...
    'orderedWinnerDeclared',false, ...
    'quantities',{{}}, ...
    'runs',struct([]), ...
    'gauges',struct([]), ...
    'cflComparisonsPassed',false, ...
    'gaugeCovariancePassed',false, ...
    'nonePromotionBlocked',true, ...
    'noneEmpiricalRateConvergenceEligible',false);
end

function record = empty_run_record()
record = struct( ...
    'index',NaN, ...
    'name','', ...
    'gauge','', ...
    'cfl',NaN, ...
    'status','', ...
    'startedUtc','', ...
    'completedUtc','', ...
    'freshStart',false, ...
    'restartInput','', ...
    'checkpointInputAccepted',false, ...
    'selectedRatePrescribed',false, ...
    'empiricalRateConvergenceEligible',false, ...
    'config',struct(), ...
    'contractAudit',struct(), ...
    'gaugeRule',struct(), ...
    'stopReason','', ...
    'cost',struct( ...
        'steps',NaN, ...
        'solveWallSeconds',NaN, ...
        'counterfactualWallSeconds',NaN, ...
        'totalWallSeconds',NaN, ...
        'solveWallSecondsPerStep',NaN, ...
        'totalWallSecondsPerStep',NaN), ...
    'telemetry',struct(), ...
    'postAudit',struct(), ...
    'hardPassed',false, ...
    'resultMetadata',struct(), ...
    'resultFile','', ...
    'solverResultRetained',false, ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function comparison = empty_comparison()
comparison = struct( ...
    'available',false, ...
    'kind','', ...
    'status','not_executed', ...
    'referenceRun','', ...
    'candidateRun','', ...
    'referenceGauge','', ...
    'candidateGauge','', ...
    'referenceCfl',NaN, ...
    'candidateCfl',NaN, ...
    'commonWindow',[NaN,NaN,NaN], ...
    'forward',struct(), ...
    'reverse',struct(), ...
    'symmetricWorst',struct(), ...
    'endpoint',struct(), ...
    'checks',struct(), ...
    'failures',{{}}, ...
    'hardPassed',false, ...
    'errorIdentifier','', ...
    'errorMessage','');
end

function names = physical_metric_names()
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference'};
end

function trend = linear_trend(x,y)
x = x(:);
y = y(:);
valid = isfinite(x) & isfinite(y);
x = x(valid);
y = y(valid);
trend = struct('valid',false,'count',numel(x),'slope',NaN, ...
    'intercept',NaN,'residualRms',NaN,'relativeResidualRms',NaN, ...
    'rSquared',NaN);
if numel(x) < 3 || x(end) <= x(1)
    return
end
xCenter = mean(x);
design = [ones(size(x)),x-xCenter];
coefficients = design\y;
fitted = design*coefficients;
residual = y-fitted;
centered = y-mean(y);
denominator = sum(centered.^2);
if denominator > 0
    rSquared = 1-sum(residual.^2)/denominator;
else
    rSquared = NaN;
end
trend.valid = true;
trend.slope = coefficients(2);
trend.intercept = coefficients(1)-coefficients(2)*xCenter;
trend.residualRms = sqrt(mean(residual.^2));
trend.relativeResidualRms = trend.residualRms / ...
    max(mean(abs(y)),realmin);
trend.rSquared = rSquared;
end

function counts = limiter_counts(values)
known = ["max_dt","cfl","canonical_final_time", ...
    "physical_final_time"];
raw = zeros(size(known));
for index = 1:numel(known)
    raw(index) = nnz(values == known(index));
end
counts = struct( ...
    'records',numel(values), ...
    'maxDt',raw(1), ...
    'cfl',raw(2), ...
    'canonicalFinalTime',raw(3), ...
    'physicalFinalTime',raw(4), ...
    'other',numel(values)-sum(raw));
end

function count = count_stencil_switches(center)
center = center(:);
if numel(center) < 2
    count = 0;
else
    count = nnz(diff(center) ~= 0);
end
end

function value = relative_drift(series)
series = series(:);
if isempty(series) || any(~isfinite(series([1,end])))
    value = NaN;
else
    value = (series(end)-series(1))/max(abs(series(1)),realmin);
end
end

function value = absolute_change(series)
series = series(:);
if isempty(series) || any(~isfinite(series([1,end])))
    value = NaN;
else
    value = abs(series(end)-series(1));
end
end

function values = safe_series_ratio(numerator,denominator)
numerator = numerator(:);
denominator = denominator(:);
scale = max([abs(numerator),abs(denominator), ...
    ones(size(numerator))],[],2);
valid = abs(denominator) > 100*eps(1).*scale;
values = NaN(size(numerator));
values(valid) = numerator(valid)./denominator(valid);
end

function value = normalized_max(numerator,reference)
numerator = numerator(:);
reference = reference(:);
if isempty(numerator) || any(~isfinite(numerator)) || ...
        any(~isfinite(reference))
    value = Inf;
    return
end
scale = max([max(abs(reference)),1]);
value = max(abs(numerator))/scale;
end

function value = symmetric_relative_difference(left,right)
if ~isfinite(left) || ~isfinite(right)
    value = Inf;
else
    value = abs(right-left)/max([abs(left),abs(right),realmin]);
end
end

function value = scaled_difference(left,right,floorValue)
if ~isfinite(left) || ~isfinite(right)
    value = Inf;
else
    value = abs(right-left)/max([abs(left),abs(right),floorValue]);
end
end

function passed = close_series(left,right,tolerance)
left = left(:);
right = right(:);
passed = numel(left) == numel(right) && ...
    all(isfinite(left)) && all(isfinite(right)) && ...
    max(abs(left-right)./max([abs(left),abs(right), ...
    ones(size(left))],[],2)) <= tolerance;
end

function passed = all_finite_numeric_fields(value,allowedNonfinite)
if nargin < 2
    allowedNonfinite = {};
end
passed = true;
names = fieldnames(value);
for index = 1:numel(names)
    name = names{index};
    fieldValue = value.(name);
    if isnumeric(fieldValue) && ~ismember(name,allowedNonfinite)
        passed = passed && isreal(fieldValue) && all(isfinite(fieldValue));
    end
end
end

function value = safe_per_step(seconds,steps)
if isfinite(seconds) && isfinite(steps) && steps > 0
    value = seconds/steps;
else
    value = NaN;
end
end

function value = finite_elapsed(existing,clock)
if isfinite(existing)
    value = existing;
else
    value = toc(clock);
end
end

function failures = failed_checks(checks)
names = fieldnames(checks);
failures = cell(0,1);
for index = 1:numel(names)
    if ~isequal(checks.(names{index}),true)
        failures{end+1,1} = names{index}; %#ok<AGROW>
    end
end
end

function passed = endpoint_close(actual,expected)
actual = actual(:);
expected = expected(:);
scale = max([1,max(abs(actual)),max(abs(expected))]);
passed = numel(actual) == numel(expected) && ...
    max(abs(actual-expected)) <= 128*eps(scale);
end

function value = ternary(condition,trueValue,falseValue)
if condition
    value = trueValue;
else
    value = falseValue;
end
end

function value = numeric_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
end

function value = logical_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
valid = (islogical(value) && isscalar(value)) || ...
    (isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && any(value == [0,1]));
if ~valid
    error('ipm:GaugeLabQ512GaugeCflOptions', ...
        'Option %s must be a logical scalar.',name);
end
value = logical(value);
end

function value = path_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabQ512GaugeCflOptions', ...
        'Option %s must be a nonempty path.',name);
end
end

function mode = execution_mode(settings)
if settings.execute
    mode = 'bounded_short_time_screen';
else
    mode = 'preflight_only';
end
end

function root = default_output_root()
fileName = mfilename('fullpath');
gaugeDirectory = fileparts(fileName);
researchDirectory = fileparts(gaugeDirectory);
repositoryRoot = fileparts(researchDirectory);
root = fullfile(repositoryRoot,'result','verification', ...
    'q512_fresh_gauge_cfl_short_screens_v4');
end

function [directory,screenId] = create_output_directory(root)
if ~isfolder(root)
    mkdir(root);
end
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
[~,token] = fileparts(tempname);
screenId = sprintf('screen_%s_%s',stamp,token);
directory = fullfile(root,screenId);
if isfile(directory) || isfolder(directory)
    error('ipm:GaugeLabQ512GaugeCflOutputCollision', ...
        'Output path already exists: %s',directory);
end
mkdir(directory);
end

function save_summary(fileName,screen)
save(fileName,'screen','-v7.3');
end

function append_manifest(fileName,record)
fileId = fopen(fileName,'a');
if fileId < 0
    error('ipm:GaugeLabQ512GaugeCflManifest', ...
        'Could not append manifest %s.',fileName);
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function fields = retired_fields()
fields = {'maxDynamicRate','adaptiveGain','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
end

function require_history(group,names,label)
for index = 1:numel(names)
    name = names{index};
    if ~isfield(group,name) || ...
            ~(isnumeric(group.(name)) || isstring(group.(name))) || ...
            ~isvector(group.(name)) || isempty(group.(name))
        error('ipm:GaugeLabQ512GaugeCflHistory', ...
            '%s.%s must be a nonempty vector series.',label,name);
    end
end
end

function require_dependencies()
required = {'fourth_order_blowup_case'};
for index = 1:numel(required)
    if exist(required{index},'file') ~= 2
        error('ipm:GaugeLabQ512GaugeCflPath', ...
            ['%s is not on the MATLAB path. Add research/experiments ' ...
            'and research/gauge_lab before running this screen.'], ...
            required{index});
    end
end
end

function value = utc_stamp()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
