function rootRun = ipm_gaugelab_run_q512_root(options)
%IPM_GAUGELAB_RUN_Q512_ROOT Start a fresh schema-4 q512 gauge run.
%   ROOTRUN = IPM_GAUGELAB_RUN_Q512_ROOT() runs a deliberately short,
%   at-most-two-step matched-box smoke calculation.  It never resumes an
%   older artifact: the physical datum and both scale clocks start at zero.
%
%   OPTIONS.boxMode is 'matched' (the registered x=[-281,281], y=[0,132]
%   q512 refinement) or 'large_box'.  The latter defaults to half-width
%   1e6 in both directions; OPTIONS.boxHalfWidth can select another rung of
%   the same fresh-root box ladder.
%
%   A long root segment is intentionally opt-in:
%
%       options.runMode = 'campaign';
%       options.confirmLongRun = true;
%
%   Campaign defaults define a discovery window rather than a blowup
%   claim: canonical tau=12 with physical time 4 as a safety ceiling.  The
%   former t=2.1 ceiling stopped near tau=3 on the q256 trajectory and was
%   too short to expose three e-folds of gradient amplification.
%
%   OPTIONS.preflightOnly=true resolves and audits the complete q512
%   configuration, writes its registered summary/manifest, and performs no
%   PDE solve.  Every executed run uses configuration/checkpoint schema 4,
%   exact_gauge_no_feedback_v1, the X=1 transport anchor, the selected exact
%   amplitude gauge, the high_order/WENO5-FD/SSPRK(5,4)/high_order tuple,
%   and a fixed mesh. OPTIONS.cOmegaGauge is either gradient_energy (the
%   backward-compatible default) or wall_omega_quadratic_peak.

if nargin < 1 || isempty(options)
    options = struct();
end
settings = resolve_options(options);
require_factory();

[outputDirectory,runId] = create_output_directory(settings);
summaryFile = fullfile(outputDirectory,'root_summary.mat');
manifestFile = fullfile(outputDirectory,'root_manifest.jsonl');
resultFile = fullfile(outputDirectory,'result.mat');
checkpointFile = fullfile(outputDirectory,'checkpoint.mat');

[opts,baseCaseName,domain] = registered_options( ...
    settings,resultFile,checkpointFile,runId);
config = ipm.config.resolve(opts);
gates = registered_mesh_gates();
[meshAudit,meshPassed] = audit_mesh( ...
    opts,config,gates,domain,settings.boxMode);
[contractAudit,contractPassed] = audit_config_contract( ...
    config,opts,settings.cOmegaGauge);

registeredUtc = utc_stamp();
rootRun = struct( ...
    'schemaVersion',4, ...
    'kind','q512_fresh_exact_gauge_root', ...
    'runId',runId, ...
    'status','registered', ...
    'registeredUtc',registeredUtc, ...
    'startedUtc','', ...
    'completedUtc','', ...
    'freshStart',true, ...
    'restartInput','none', ...
    'baseCaseName',baseCaseName, ...
    'boxMode',settings.boxMode, ...
    'runMode',settings.runMode, ...
    'cOmegaGauge',settings.cOmegaGauge, ...
    'preflightOnly',settings.preflightOnly, ...
    'domain',domain, ...
    'requested',requested_summary(settings), ...
    'gaugeRules',registered_gauge_rules(settings.cOmegaGauge), ...
    'meshGates',gates, ...
    'meshAudit',meshAudit, ...
    'meshPassed',meshPassed, ...
    'contractAudit',contractAudit, ...
    'contractPassed',contractPassed, ...
    'config',config, ...
    'outputDirectory',outputDirectory, ...
    'summaryFile',summaryFile, ...
    'manifestFile',manifestFile, ...
    'requestedResultFile',resultFile, ...
    'requestedCheckpointFile',checkpointFile, ...
    'resultFile','', ...
    'checkpointFile','', ...
    'wallSeconds',NaN, ...
    'steps',NaN, ...
    'wallSecondsPerStep',NaN, ...
    'stopReason','', ...
    'postAudit',struct(), ...
    'errorIdentifier','', ...
    'errorMessage','');
save_summary(summaryFile,rootRun);
append_manifest(manifestFile,struct( ...
    'event','root_registered', ...
    'timestampUtc',registeredUtc, ...
    'runId',runId, ...
    'freshStart',true, ...
    'baseCaseName',baseCaseName, ...
    'boxMode',settings.boxMode, ...
    'runMode',settings.runMode, ...
    'cOmegaGauge',settings.cOmegaGauge, ...
    'preflightOnly',settings.preflightOnly, ...
    'domain',domain, ...
    'requested',rootRun.requested, ...
    'gaugeRules',rootRun.gaugeRules, ...
    'meshGates',gates, ...
    'meshPassed',meshPassed, ...
    'contractPassed',contractPassed, ...
    'retiredFieldsPresent',{contractAudit.retiredFieldsPresent}, ...
    'summaryFile',summaryFile, ...
    'resultFile',resultFile, ...
    'checkpointFile',checkpointFile));

if ~(meshPassed && contractPassed)
    rootRun.status = 'preflight_rejected';
    rootRun.completedUtc = utc_stamp();
    save_summary(summaryFile,rootRun);
    append_manifest(manifestFile,struct( ...
        'event','root_preflight_rejected', ...
        'timestampUtc',rootRun.completedUtc, ...
        'runId',runId, ...
        'meshFailures',{meshAudit.failures}, ...
        'contractFailures',{contractAudit.failures}));
    error('ipm:GaugeLabQ512PreflightGate', ...
        'The registered q512 root failed preflight; inspect %s.', ...
        summaryFile);
end

if settings.preflightOnly
    rootRun.status = 'preflight_only';
    rootRun.completedUtc = utc_stamp();
    save_summary(summaryFile,rootRun);
    append_manifest(manifestFile,struct( ...
        'event','root_preflight_complete', ...
        'timestampUtc',rootRun.completedUtc, ...
        'runId',runId, ...
        'solveExecuted',false));
    fprintf(['Q512 ROOT PREFLIGHT: mode=%s, box=%s, ' ...
        'mesh/contract=pass, summary=%s\n'], ...
        settings.runMode,settings.boxMode,summaryFile);
    return
end

rootRun.status = 'running';
rootRun.startedUtc = utc_stamp();
save_summary(summaryFile,rootRun);
append_manifest(manifestFile,struct( ...
    'event','root_solve_started', ...
    'timestampUtc',rootRun.startedUtc, ...
    'runId',runId, ...
    'cOmegaGauge',settings.cOmegaGauge, ...
    'freshStart',true));

wallClock = tic;
try
    % Deliberately use the one-argument entry point.  No result or
    % checkpoint can enter this fresh-root transaction.
    result = ipm.solve(opts);
    rootRun.wallSeconds = toc(wallClock);
catch exception
    rootRun.wallSeconds = toc(wallClock);
    rootRun.status = 'solver_failed';
    rootRun.completedUtc = utc_stamp();
    rootRun.errorIdentifier = exception.identifier;
    rootRun.errorMessage = exception.message;
    save_summary(summaryFile,rootRun);
    append_manifest(manifestFile,struct( ...
        'event','root_solve_failed', ...
        'timestampUtc',rootRun.completedUtc, ...
        'runId',runId, ...
        'wallSeconds',rootRun.wallSeconds, ...
        'errorIdentifier',exception.identifier, ...
        'errorMessage',exception.message));
    rethrow(exception)
end

try
    result = ipm.output.validate(result);
    [postAudit,checkpointPath] = audit_result( ...
        result,config,settings,rootRun.wallSeconds,checkpointFile);
catch exception
    rootRun.status = 'postprocess_failed';
    rootRun.completedUtc = utc_stamp();
    rootRun.errorIdentifier = exception.identifier;
    rootRun.errorMessage = exception.message;
    if exist('result','var') && isstruct(result) && ...
            isfield(result,'metadata') && ...
            isfield(result.metadata,'resultFile')
        rootRun.resultFile = char(result.metadata.resultFile);
    end
    save_summary(summaryFile,rootRun);
    append_manifest(manifestFile,struct( ...
        'event','root_postprocess_failed', ...
        'timestampUtc',rootRun.completedUtc, ...
        'runId',runId, ...
        'wallSeconds',rootRun.wallSeconds, ...
        'errorIdentifier',exception.identifier, ...
        'errorMessage',exception.message, ...
        'resultFile',rootRun.resultFile));
    rethrow(exception)
end
rootRun.steps = result.state.steps;
rootRun.wallSecondsPerStep = postAudit.wallSecondsPerStep;
rootRun.stopReason = result.state.stopReason;
rootRun.resultFile = char(result.metadata.resultFile);
rootRun.checkpointFile = checkpointPath;
rootRun.postAudit = postAudit;
rootRun.completedUtc = utc_stamp();
if postAudit.hardPassed
    rootRun.status = 'completed';
else
    rootRun.status = 'postrun_rejected';
end
save_summary(summaryFile,rootRun);
append_manifest(manifestFile,struct( ...
    'event','root_solve_finished', ...
    'timestampUtc',rootRun.completedUtc, ...
    'runId',runId, ...
    'status',rootRun.status, ...
    'cOmegaGauge',settings.cOmegaGauge, ...
    'stopReason',rootRun.stopReason, ...
    'steps',rootRun.steps, ...
    'wallSeconds',rootRun.wallSeconds, ...
    'wallSecondsPerStep',rootRun.wallSecondsPerStep, ...
    'postrunPassed',postAudit.hardPassed, ...
    'postrunFailures',{postAudit.failures}, ...
    'resultFile',rootRun.resultFile, ...
    'checkpointFile',rootRun.checkpointFile));

fprintf(['Q512 ROOT RESULT: status=%s, stop=%s, steps=%d, ' ...
    'wall=%.3f s, %.3f s/step\n'],rootRun.status, ...
    rootRun.stopReason,rootRun.steps,rootRun.wallSeconds, ...
    rootRun.wallSecondsPerStep);
if ~postAudit.hardPassed
    error('ipm:GaugeLabQ512PostrunGate', ...
        'The q512 result failed postrun gate(s): %s. See %s.', ...
        strjoin(postAudit.failures,','),summaryFile);
end
end

function settings = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeLabQ512Options', ...
        'options must be a scalar structure.');
end
allowed = {'boxMode','boxHalfWidth','runMode','confirmLongRun', ...
    'preflightOnly','outputRoot','verbose','cfl','maxDt', ...
    'physicalFinalTime','canonicalFinalTime','maxSteps', ...
    'outputEvery','checkpointEvery','cOmegaGauge'};
unknown = setdiff(fieldnames(options),allowed,'stable');
if ~isempty(unknown)
    error('ipm:GaugeLabQ512Options', ...
        'Unknown option(s): %s.',strjoin(unknown,', '));
end

settings = struct();
settings.boxMode = text_option(options,'boxMode','matched');
settings.runMode = text_option(options,'runMode','smoke');
settings.cOmegaGauge = text_option( ...
    options,'cOmegaGauge','gradient_energy');
settings.confirmLongRun = logical_option( ...
    options,'confirmLongRun',false);
settings.preflightOnly = logical_option(options,'preflightOnly',false);
settings.verbose = logical_option(options,'verbose',true);
settings.outputRoot = path_option(options,'outputRoot',default_output_root());
settings.boxHalfWidth = numeric_option(options,'boxHalfWidth',[]);
settings.cfl = numeric_option(options,'cfl',0.25);

if strcmp(settings.runMode,'smoke')
    settings.physicalFinalTime = numeric_option( ...
        options,'physicalFinalTime',1e-4);
    settings.canonicalFinalTime = numeric_option( ...
        options,'canonicalFinalTime',1e-3);
    settings.maxDt = numeric_option(options,'maxDt',1e-4);
    settings.maxSteps = numeric_option(options,'maxSteps',2);
    settings.outputEvery = numeric_option(options,'outputEvery',1e-4);
    settings.checkpointEvery = numeric_option( ...
        options,'checkpointEvery',1e-4);
elseif strcmp(settings.runMode,'campaign')
    settings.physicalFinalTime = numeric_option( ...
        options,'physicalFinalTime',4.0);
    settings.canonicalFinalTime = numeric_option( ...
        options,'canonicalFinalTime',12);
    settings.maxDt = numeric_option(options,'maxDt',2e-3);
    settings.maxSteps = numeric_option(options,'maxSteps',30000);
    settings.outputEvery = numeric_option(options,'outputEvery',5e-3);
    settings.checkpointEvery = numeric_option( ...
        options,'checkpointEvery',0.20);
else
    error('ipm:GaugeLabQ512RunMode', ...
        'runMode must be ''smoke'' or ''campaign''.');
end
if ~any(strcmp(settings.boxMode,{'matched','large_box'}))
    error('ipm:GaugeLabQ512BoxMode', ...
        'boxMode must be ''matched'' or ''large_box''.');
end
if ~any(strcmp(settings.cOmegaGauge, ...
        {'gradient_energy','wall_omega_quadratic_peak'}))
    error('ipm:GaugeLabQ512COmegaGauge', ...
        ['cOmegaGauge must be ''gradient_energy'' or ' ...
        '''wall_omega_quadratic_peak''.']);
end

validateattributes(settings.cfl,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',0.5},mfilename,'cfl');
validateattributes(settings.physicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename, ...
    'physicalFinalTime');
validateattributes(settings.canonicalFinalTime,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename, ...
    'canonicalFinalTime');
validateattributes(settings.maxDt,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'maxDt');
validateattributes(settings.maxSteps,{'numeric'}, ...
    {'scalar','real','finite','integer','positive'},mfilename,'maxSteps');
validateattributes(settings.outputEvery,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'outputEvery');
validateattributes(settings.checkpointEvery,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'checkpointEvery');

if strcmp(settings.boxMode,'matched')
    if isempty(settings.boxHalfWidth)
        settings.boxHalfWidth = 281;
    else
        validateattributes(settings.boxHalfWidth,{'numeric'}, ...
            {'scalar','real','finite','positive'},mfilename, ...
            'boxHalfWidth');
        if settings.boxHalfWidth ~= 281
            error('ipm:GaugeLabQ512MatchedBox', ...
                ['The matched factory is registered only at x half-width ' ...
                '281; use boxMode=''large_box'' for a box ladder rung.']);
        end
    end
else
    if isempty(settings.boxHalfWidth)
        settings.boxHalfWidth = 1e6;
    end
    validateattributes(settings.boxHalfWidth,{'numeric'}, ...
        {'scalar','real','finite','>',2},mfilename,'boxHalfWidth');
end

if strcmp(settings.runMode,'smoke') && ...
        (settings.physicalFinalTime > 1e-3 || ...
        settings.canonicalFinalTime > 1e-2 || ...
        settings.maxSteps > 10)
    error('ipm:GaugeLabQ512SmokeBudget', ...
        ['Smoke mode is capped at physical time 1e-3, canonical time ' ...
        '1e-2, and 10 steps.  Use the explicitly confirmed campaign mode.']);
end
if strcmp(settings.runMode,'campaign') && ...
        ~settings.preflightOnly && ~settings.confirmLongRun
    error('ipm:GaugeLabQ512LongRunConfirmation', ...
        ['A campaign root may take hours.  Set confirmLongRun=true ' ...
        'explicitly, or use preflightOnly=true.']);
end
end

function [opts,baseCaseName,domain] = registered_options( ...
        settings,resultFile,checkpointFile,runId)
if strcmp(settings.boxMode,'matched')
    baseCaseName = 'coordinated_log_F80_R20_c114_quadrant_512';
    domain = struct('x',[-281,281],'y',[0,132], ...
        'initialPhysicalX',[-281,281], ...
        'initialPhysicalY',[0,132]);
    boxOverrides = struct();
else
    baseCaseName = ...
        'coordinated_log_anchor_F80_R20_large_box_quadrant_512';
    halfWidth = settings.boxHalfWidth;
    domain = struct('x',[-halfWidth,halfWidth], ...
        'y',[0,halfWidth], ...
        'initialPhysicalX',[-halfWidth,halfWidth], ...
        'initialPhysicalY',[0,halfWidth]);
    boxOverrides = struct('xlim',[-halfWidth,halfWidth], ...
        'ymax',halfWidth);
end

metadata = struct('q512GaugeRoot',struct( ...
    'schemaVersion',4, ...
    'runId',runId, ...
    'freshStart',true, ...
    'restartInput','none', ...
    'boxMode',settings.boxMode, ...
    'boxHalfWidth',settings.boxHalfWidth, ...
    'runMode',settings.runMode, ...
    'configurationContract','exact_gauge_no_feedback_v1', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge',settings.cOmegaGauge));
overrides = struct( ...
    'rescalingMode','dynamic', ...
    'dynamicScaleGeometry','isotropic', ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge',settings.cOmegaGauge, ...
    'lengthScaleGain',1, ...
    'widthGaugeGain',0, ...
    'omegaGaugeGain',0, ...
    'travelingWaveGain',0, ...
    'omegaGaugeWindowRadius',0.75, ...
    'pointStrainConditionFloor',0.25, ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'initialAnalyticRemesh',false, ...
    'adaptiveRemesh',false, ...
    'remeshMaximumCellRatio',1.08, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'finalTime',settings.canonicalFinalTime, ...
    'cfl',settings.cfl, ...
    'maxDt',settings.maxDt, ...
    'maxSteps',settings.maxSteps, ...
    'outputEvery',settings.outputEvery, ...
    'checkpoint',struct('enabled',true,'file',checkpointFile, ...
        'every',settings.checkpointEvery,'atExit',true), ...
    'caseMetadata',metadata, ...
    'resultFile',resultFile, ...
    'saveResults',true, ...
    'storeSnapshots',false, ...
    'makePlots',false, ...
    'livePlot',false, ...
    'writeVideo',false, ...
    'verbose',settings.verbose);
names = fieldnames(boxOverrides);
for index = 1:numel(names)
    overrides.(names{index}) = boxOverrides.(names{index});
end
opts = fourth_order_blowup_case(baseCaseName,overrides);
end

function gates = registered_mesh_gates()
gates = struct( ...
    'maximumAdjacentCellRatio',1.08, ...
    'maximumLogSpacingCurvature',0.01, ...
    'minimumStencilRcond',1e-9, ...
    'minimumQuadratureWeightRatio',1e-8, ...
    'minimumLocalQuadratureWeightRatio',0.35, ...
    'maximumLocalQuadratureWeightRatio',1.65, ...
    'stencilWidth',7);
end

function [audit,passed] = audit_mesh(opts,config,gates,domain,boxMode)
weightsX = ipm.mesh.quadrature(opts.customX);
weightsY = ipm.mesh.quadrature(opts.customY);
qualityX = ipm.mesh.quality( ...
    opts.customX,gates.stencilWidth,weightsX);
qualityY = ipm.mesh.quality( ...
    opts.customY,gates.stencilWidth,weightsY);
[anchorDistance,anchorIndex] = min(abs(opts.customX-1));
anchorTolerance = 128*eps(max(1,max(abs(opts.customX))));

checks = struct();
checks.nodeCounts = numel(opts.customX) == 1025 && ...
    numel(opts.customY) == 513 && config.grid.nx == 1025 && ...
    config.grid.ny == 513;
checks.endpoints = endpoint_close(opts.customX([1,end]),domain.x) && ...
    endpoint_close(opts.customY([1,end]),domain.y);
anchorIsGridNode = anchorDistance <= anchorTolerance;
exactAnchorRequired = strcmp(boxMode,'large_box');
checks.transportAnchorNodePolicy = ...
    ~exactAnchorRequired || anchorIsGridNode;
checks.positiveQuadrature = qualityX.quadratureWeightsStrictlyPositive && ...
    qualityY.quadratureWeightsStrictlyPositive;
checks.adjacentCellRatio = max([qualityX.maximumAdjacentCellRatio, ...
    qualityY.maximumAdjacentCellRatio]) <= ...
    gates.maximumAdjacentCellRatio*(1+1e-12);
checks.logSpacingCurvature = max([ ...
    qualityX.maximumLogSpacingCurvature, ...
    qualityY.maximumLogSpacingCurvature]) <= ...
    gates.maximumLogSpacingCurvature*(1+1e-12);
checks.stencilRcond = min([qualityX.minimumStencilRcond, ...
    qualityY.minimumStencilRcond]) >= ...
    gates.minimumStencilRcond*(1-1e-12);
checks.globalQuadrature = min([ ...
    qualityX.minimumQuadratureWeightRatio, ...
    qualityY.minimumQuadratureWeightRatio]) >= ...
    gates.minimumQuadratureWeightRatio*(1-1e-12);
checks.localQuadratureLower = min([ ...
    qualityX.minimumQuadratureWeightToControlWidthRatio, ...
    qualityY.minimumQuadratureWeightToControlWidthRatio]) >= ...
    gates.minimumLocalQuadratureWeightRatio*(1-1e-12);
checks.localQuadratureUpper = max([ ...
    qualityX.maximumQuadratureWeightToControlWidthRatio, ...
    qualityY.maximumQuadratureWeightToControlWidthRatio]) <= ...
    gates.maximumLocalQuadratureWeightRatio*(1+1e-12);
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct( ...
    'x',qualityX, ...
    'y',qualityY, ...
    'checks',checks, ...
    'failures',{failures}, ...
    'passed',passed, ...
    'anchorX',1, ...
    'nearestAnchorNode',opts.customX(anchorIndex), ...
    'anchorNodeDistance',anchorDistance, ...
    'anchorIsGridNode',anchorIsGridNode, ...
    'exactAnchorRequired',exactAnchorRequired, ...
    'anchorNodeTolerance',anchorTolerance);
end

function [audit,passed] = audit_config_contract(config,opts,expectedGauge)
scaling = config.scaling;
retired = retired_fields();
retiredInOptions = retired(isfield(opts,retired));
retiredInScaling = retired(isfield(scaling,retired));
retiredPresent = unique([retiredInOptions,retiredInScaling],'stable');

checks = struct();
checks.configSchema4 = config.schemaVersion == 4 && config.frozen;
checks.q512 = config.grid.nx == 1025 && config.grid.ny == 513;
checks.numericalTuple = ...
    strcmp(config.transport.spatialDiscretization,'high_order') && ...
    strcmp(config.transport.transportScheme,'weno5_fd') && ...
    strcmp(config.time.timeIntegrator,'ssprk54') && ...
    strcmp(config.remesh.remeshTransferScheme,'high_order');
checks.dynamicIsotropic = ...
    strcmp(scaling.rescalingMode,'dynamic') && ...
    strcmp(scaling.dynamicScaleGeometry,'isotropic');
checks.exactScalingContract = strcmp( ...
    scaling.scalingContract,'exact_gauge_no_feedback_v1');
checks.transportAnchorX1 = strcmp(scaling.lengthGauge, ...
    'transport_anchor') && scaling.transportAnchorX == 1;
checks.registeredAmplitudeGauge = ...
    strcmp(scaling.cOmegaGauge,expectedGauge);
checks.noFeedback = scaling.lengthScaleGain == 1 && ...
    scaling.widthGaugeGain == 0 && scaling.omegaGaugeGain == 0 && ...
    scaling.travelingWaveGain == 0;
checks.noRetiredFields = isempty(retiredPresent);
checks.fixedMesh = ~config.remesh.initialAnalyticRemesh && ...
    ~config.remesh.adaptiveRemesh;
checks.checkpointSchema4Policy = ...
    isfield(config.output,'checkpoint') && ...
    config.output.checkpoint.enabled && config.output.checkpoint.atExit;
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct('checks',checks,'failures',{failures}, ...
    'passed',passed,'retiredFieldsPresent',{retiredPresent});
end

function [audit,checkpointPath] = audit_result( ...
        result,registeredConfig,settings,wallSeconds,requestedCheckpoint)
common = result.history.common;
gauge = result.history.gauge;
[rawTrusted,trustChecks] = ipm.output.trustedMask(result);
trusted = ipm.output.continuousTrustedPrefix(rawTrusted);

requiredGauge = {'omegaGaugeResidual','lengthGaugeResidual', ...
    'transportAnchorVelocity','canonicalTransportAnchorVelocity', ...
    'transportAnchorX','c_lNominal','canonicalCLNominal', ...
    'lengthScaleGain','widthControlMode','widthCorrection', ...
    'canonicalWidthCorrection'};
if strcmp(settings.cOmegaGauge,'gradient_energy')
    requiredGauge = [requiredGauge,gradient_history_fields()];
else
    requiredGauge = [requiredGauge,quadratic_history_fields()];
end
gaugeHistoryComplete = all(isfield(gauge,requiredGauge));
if gaugeHistoryComplete
    gaugeFinite = true;
    for fieldIndex = 1:numel(requiredGauge)
        values = gauge.(requiredGauge{fieldIndex});
        gaugeFinite = gaugeFinite && isnumeric(values) && ...
            isreal(values) && isvector(values) && ...
            numel(values) == numel(common.t) && all(isfinite(values));
    end
else
    gaugeFinite = false;
end

maximumOmegaGaugeResidual = Inf;
maximumLengthGaugeResidual = Inf;
maximumTransportAnchorDefect = Inf;
maximumCanonicalTransportAnchorDefect = Inf;
if gaugeHistoryComplete && gaugeFinite
    maximumOmegaGaugeResidual = max(abs(gauge.omegaGaugeResidual));
    maximumLengthGaugeResidual = max(normalized_anchor_residual( ...
        gauge.lengthGaugeResidual,gauge.c_lNominal, ...
        gauge.transportAnchorX));
    maximumTransportAnchorDefect = max(normalized_anchor_residual( ...
        gauge.transportAnchorVelocity,gauge.c_lNominal, ...
        gauge.transportAnchorX));
    maximumCanonicalTransportAnchorDefect = max( ...
        normalized_anchor_residual( ...
        gauge.canonicalTransportAnchorVelocity, ...
        gauge.canonicalCLNominal,gauge.transportAnchorX));
end

checkpointPath = locate_checkpoint(result,requestedCheckpoint);
checkpointValidated = false;
checkpointMatchesTerminal = false;
checkpointContractPassed = false;
checkpointRetiredFields = retired_fields();
if ~isempty(checkpointPath)
    checkpoint = ipm.output.readCheckpoint(checkpointPath);
    checkpointValidated = true;
    checkpointRetiredFields = checkpoint_retired_fields(checkpoint);
    state = checkpoint.payload.state;
    checkpointMatchesTerminal = state.step == result.state.steps && ...
        scalar_close(state.scale.canonicalTime, ...
            result.state.canonicalTime) && ...
        scalar_close(state.scale.physicalTime,result.state.physicalTime) && ...
        isequaln(state.rho,result.state.rho) && ...
        isequaln(state.x,result.grid.x) && ...
        isequaln(state.y,result.grid.y) && ...
        isequaln(orderfields(state.config), ...
            orderfields(result.config));
    checkpointContractPassed = checkpoint.schemaVersion == 4 && ...
        state.config.schemaVersion == 4 && ...
        strcmp(state.config.scaling.scalingContract, ...
            'exact_gauge_no_feedback_v1') && ...
        strcmp(state.config.scaling.lengthGauge,'transport_anchor') && ...
        state.config.scaling.transportAnchorX == 1 && ...
        strcmp(state.config.scaling.cOmegaGauge,settings.cOmegaGauge) && ...
        state.config.scaling.lengthScaleGain == 1 && ...
        state.config.scaling.widthGaugeGain == 0 && ...
        state.config.scaling.omegaGaugeGain == 0 && ...
        state.config.scaling.travelingWaveGain == 0 && ...
        ~state.config.remesh.initialAnalyticRemesh && ...
        ~state.config.remesh.adaptiveRemesh && ...
        isempty(checkpointRetiredFields);
end

resultContract = audit_config_contract(result.config,flatten_config( ...
    result.config),settings.cOmegaGauge);
registeredConfigurationIdentity = isequaln( ...
    orderfields(result.config),orderfields(registeredConfig));
timeSpeedExact = isfield(common,'timeSpeed') && ...
    all(common.timeSpeed == 1);
clockStartsAtZero = common.t(1) == 0 && ...
    common.canonicalTau(1) == 0 && common.physicalTime(1) == 0;
canonicalClockDirect = isequal(common.t,common.canonicalTau);
rateIdentity = isequal(common.c_l,common.canonicalCL) && ...
    isequal(common.c_omega,common.canonicalCOmega);
noFeedbackHistory = gaugeHistoryComplete && ...
    all(gauge.lengthScaleGain == 1) && ...
    all(gauge.widthControlMode == 0) && ...
    all(gauge.widthCorrection == 0) && ...
    all(gauge.canonicalWidthCorrection == 0);
fixedMeshHistory = result.grid.remeshCount == 0 && ...
    isfield(result.history.mesh,'remeshCount') && ...
    all(result.history.mesh.remeshCount == 0);
[amplitudeGaugeAudit,amplitudeGaugePassed] = ...
    audit_amplitude_gauge(result,settings.cOmegaGauge);
rateProvenance = audit_rate_provenance( ...
    result.fit.gaugeRateConvergence);
growthTelemetry = audit_growth_telemetry(result);
recordedGaugeContract = struct();
gaugeContractRecorded = false;
if isfield(result.metadata,'gaugeContract') && ...
        isstruct(result.metadata.gaugeContract) && ...
        isscalar(result.metadata.gaugeContract)
    recordedGaugeContract = result.metadata.gaugeContract;
    gaugeContractRecorded = ...
        isfield(recordedGaugeContract,'scalingContract') && ...
        strcmp(recordedGaugeContract.scalingContract, ...
            'exact_gauge_no_feedback_v1') && ...
        isfield(recordedGaugeContract,'timeSpeed') && ...
        recordedGaugeContract.timeSpeed == 1 && ...
        isfield(recordedGaugeContract,'length') && ...
        isstruct(recordedGaugeContract.length) && ...
        isscalar(recordedGaugeContract.length) && ...
        all(isfield(recordedGaugeContract.length,{'name','anchorX'})) && ...
        strcmp(recordedGaugeContract.length.name,'transport_anchor') && ...
        recordedGaugeContract.length.anchorX == 1 && ...
        isfield(recordedGaugeContract,'amplitude') && ...
        isstruct(recordedGaugeContract.amplitude) && ...
        isscalar(recordedGaugeContract.amplitude) && ...
        isfield(recordedGaugeContract.amplitude,'name') && ...
        strcmp(recordedGaugeContract.amplitude.name,settings.cOmegaGauge);
end

checks = struct();
checks.resultSchema2ConfigSchema4 = result.schemaVersion == 2 && ...
    result.config.schemaVersion == 4;
checks.registeredConfigurationIdentity = registeredConfigurationIdentity;
checks.acceptedTerminalReason = any(strcmp(result.state.stopReason, ...
    {'physical_final_time','final_time'}));
endpointAudit = requested_endpoint_audit( ...
    result,settings,registeredConfig);
checks.requestedEndpointReached = endpointAudit.passed;
checks.freshZeroClocks = clockStartsAtZero;
checks.continuousTrustedTerminal = ~isempty(trusted) && trusted(end);
checks.timeSpeedExactlyOne = timeSpeedExact;
checks.directCanonicalClock = canonicalClockDirect;
checks.directCanonicalRates = rateIdentity;
checks.gaugeHistoryCompleteFinite = gaugeHistoryComplete && gaugeFinite;
checks.amplitudeGaugeAlgebra = amplitudeGaugePassed;
checks.nonprescribedRateProvenance = rateProvenance.passed;
checks.growthTelemetry = growthTelemetry.passed;
checks.omegaGaugeResidual = ...
    maximumOmegaGaugeResidual <= 1e-10;
checks.transportAnchorResidual = max([maximumLengthGaugeResidual, ...
    maximumTransportAnchorDefect, ...
    maximumCanonicalTransportAnchorDefect]) <= 1e-10;
checks.noFeedbackHistory = noFeedbackHistory;
checks.fixedMeshHistory = fixedMeshHistory;
checks.gaugeContractRecorded = gaugeContractRecorded;
checks.resultContract = resultContract.passed;
checks.checkpointFoundValidated = checkpointValidated;
checks.checkpointMatchesTerminal = checkpointMatchesTerminal;
checks.checkpointSchema4Contract = checkpointContractPassed;
failures = failed_checks(checks);

steps = result.state.steps;
wallSecondsPerStep = NaN;
if steps > 0
    wallSecondsPerStep = wallSeconds/steps;
end
audit = struct( ...
    'cOmegaGauge',settings.cOmegaGauge, ...
    'selectedRatePrescribed',rateProvenance.selectedRatePrescribed, ...
    'checks',checks, ...
    'failures',{failures}, ...
    'hardPassed',isempty(failures), ...
    'rawTrustedRecords',nnz(rawTrusted), ...
    'continuousTrustedRecords',nnz(trusted), ...
    'totalRecords',numel(trusted), ...
    'trustChecks',trustChecks, ...
    'maximumOmegaGaugeResidual',maximumOmegaGaugeResidual, ...
    'maximumNormalizedLengthGaugeResidual', ...
        maximumLengthGaugeResidual, ...
    'maximumNormalizedTransportAnchorDefect', ...
        maximumTransportAnchorDefect, ...
    'maximumNormalizedCanonicalTransportAnchorDefect', ...
        maximumCanonicalTransportAnchorDefect, ...
    'checkpointValidated',checkpointValidated, ...
    'checkpointRetiredFieldsPresent',{checkpointRetiredFields}, ...
    'recordedGaugeContract',recordedGaugeContract, ...
    'amplitudeGaugeAudit',amplitudeGaugeAudit, ...
    'rateProvenance',rateProvenance, ...
    'growthTelemetry',growthTelemetry, ...
    'endpointAudit',endpointAudit, ...
    'gaugeRateConvergence',result.fit.gaugeRateConvergence, ...
    'maximumGrowthRate',result.fit.maximumGrowthRate, ...
    'canonicalMaximumGrowth',result.fit.canonicalMaximumGrowth, ...
    'wallSeconds',wallSeconds, ...
    'steps',steps, ...
    'wallSecondsPerStep',wallSecondsPerStep, ...
    'terminalCanonicalTime',result.state.canonicalTime, ...
    'terminalPhysicalTime',result.state.physicalTime, ...
    'requestedCanonicalTime',settings.canonicalFinalTime, ...
    'requestedPhysicalTime',settings.physicalFinalTime, ...
    'stopReason',result.state.stopReason, ...
    'terminalPhysicalRhoXInf',common.physicalRhoXInf(end), ...
    'terminalCL',common.canonicalCL(end), ...
    'terminalCOmega',common.canonicalCOmega(end));
end

function audit = requested_endpoint_audit(result,settings,config)
state = result.state;
roundoffPhysical = endpoint_roundoff(settings.physicalFinalTime);
roundoffCanonical = endpoint_roundoff(settings.canonicalFinalTime);
physicalClockSpeed = result.scale.Comega/result.scale.Cx;
physicalStopTolerance = max(roundoffPhysical, ...
    config.time.minDt*physicalClockSpeed*(1+100*eps));
canonicalStopTolerance = max(roundoffCanonical,config.time.minDt);
physicalRemainder = settings.physicalFinalTime-state.physicalTime;
canonicalRemainder = settings.canonicalFinalTime-state.canonicalTime;
physicalReached = strcmp(state.stopReason,'physical_final_time') && ...
    physicalRemainder >= -roundoffPhysical && ...
    physicalRemainder <= physicalStopTolerance && ...
    canonicalRemainder >= -roundoffCanonical;
canonicalReached = strcmp(state.stopReason,'final_time') && ...
    canonicalRemainder >= -roundoffCanonical && ...
    canonicalRemainder <= canonicalStopTolerance && ...
    physicalRemainder >= -roundoffPhysical;
audit = struct( ...
    'passed',physicalReached || canonicalReached, ...
    'acceptedPhysicalEndpoint',physicalReached, ...
    'acceptedCanonicalEndpoint',canonicalReached, ...
    'physicalRemainder',physicalRemainder, ...
    'canonicalRemainder',canonicalRemainder, ...
    'physicalStopTolerance',physicalStopTolerance, ...
    'canonicalStopTolerance',canonicalStopTolerance, ...
    'terminalPhysicalClockSpeed',physicalClockSpeed, ...
    'minimumCanonicalStep',config.time.minDt);
end

function tolerance = endpoint_roundoff(value)
tolerance = 100*eps(max(1,abs(value)));
end

function names = quadratic_history_fields()
names = {'omegaGaugeEnergy','omegaPeakRateResidual', ...
    'omegaGaugePeakX','omegaGaugePeakCondition', ...
    'omegaGaugeQuadraticPeakX','omegaGaugeQuadraticPeakValue', ...
    'omegaGaugeQuadraticForcing','omegaGaugeQuadraticCurvature', ...
    'omegaGaugeQuadraticStationarityResidual', ...
    'omegaGaugeQuadraticNormalizedStationarityResidual', ...
    'omegaGaugeQuadraticCurvatureCondition', ...
    'omegaGaugeQuadraticWeightCondition', ...
    'omegaGaugeQuadraticActiveNodeMargin', ...
    'omegaGaugeQuadraticActiveSelectionMargin', ...
    'omegaGaugeQuadraticStencilCenterX', ...
    'omegaGaugeQuadraticVertexInteriorFraction', ...
    'omegaGaugeQuadraticRelativeSubgridLift', ...
    'omegaGaugeQuadraticRateResidual', ...
    'omegaGaugeQuadraticRateScale'};
end

function names = gradient_history_fields()
names = {'omegaGaugeEnergy','omegaGaugeEnergyX', ...
    'omegaGaugeEnergyY','omegaGaugeForcingX', ...
    'omegaGaugeForcingY','omegaGaugeForcing', ...
    'omegaGaugeAbsoluteForcing', ...
    'omegaGaugeForcingCancellationRatio'};
end

function [audit,passed] = audit_amplitude_gauge(result,gaugeName)
if strcmp(gaugeName,'gradient_energy')
    [audit,passed] = audit_gradient_amplitude_gauge(result,gaugeName);
    return
end
if ~strcmp(gaugeName,'wall_omega_quadratic_peak')
    error('ipm:GaugeLabQ512COmegaGauge', ...
        'Unsupported post-audit cOmegaGauge: %s.',gaugeName);
end

common = result.history.common;
gauge = result.history.gauge;
required = quadratic_history_fields();
recordCount = numel(common.t);
complete = all(isfield(gauge,required));
finiteHistory = complete && recordCount > 0;
if complete
    for index = 1:numel(required)
        values = gauge.(required{index});
        finiteHistory = finiteHistory && isnumeric(values) && ...
            isreal(values) && isvector(values) && ...
            numel(values) == recordCount && all(isfinite(values(:)));
    end
end
cOmegaAvailable = isfield(common,'c_omega') && ...
    isnumeric(common.c_omega) && isreal(common.c_omega) && ...
    isvector(common.c_omega) && numel(common.c_omega) == recordCount && ...
    all(isfinite(common.c_omega(:)));

checks = struct( ...
    'selectedGauge',strcmp(result.config.scaling.cOmegaGauge,gaugeName), ...
    'historyComplete',complete, ...
    'historyFinite',finiteHistory, ...
    'cOmegaHistoryAvailable',cOmegaAvailable, ...
    'peakStrictlyPositive',false, ...
    'peakCondition',false, ...
    'curvatureStrictlyNegative',false, ...
    'curvatureConditionStrictlyPositive',false, ...
    'weightCondition',false, ...
    'activeNodeMargin',false, ...
    'activeSelectionMargin',false, ...
    'stencilCenterOnGrid',false, ...
    'stencilCenterInterior',false, ...
    'quadraticVertexInterior',false, ...
    'vertexInteriorFractionIdentity',false, ...
    'relativeSubgridLiftNonnegative',false, ...
    'stationarityResidual',false, ...
    'rateScaleStrictlyPositive',false, ...
    'rateScaleIdentity',false, ...
    'selectedRateIdentity',false, ...
    'rateEquationResidual',false, ...
    'recordedRateResidualIdentity',false, ...
    'normalizedGaugeResidualIdentity',false, ...
    'peakAliasesIdentity',false);
metrics = empty_quadratic_gauge_metrics();
if finiteHistory && cOmegaAvailable
    peak = gauge.omegaGaugeQuadraticPeakValue(:);
    forcing = gauge.omegaGaugeQuadraticForcing(:);
    cOmega = common.c_omega(:);
    curvature = gauge.omegaGaugeQuadraticCurvature(:);
    curvatureCondition = ...
        gauge.omegaGaugeQuadraticCurvatureCondition(:);
    weightCondition = gauge.omegaGaugeQuadraticWeightCondition(:);
    activeNodeMargin = ...
        gauge.omegaGaugeQuadraticActiveNodeMargin(:);
    activeSelectionMargin = ...
        gauge.omegaGaugeQuadraticActiveSelectionMargin(:);
    vertexFraction = ...
        gauge.omegaGaugeQuadraticVertexInteriorFraction(:);
    subgridLift = gauge.omegaGaugeQuadraticRelativeSubgridLift(:);
    normalizedStationarity = gauge. ...
        omegaGaugeQuadraticNormalizedStationarityResidual(:);
    recordedRateResidual = ...
        gauge.omegaGaugeQuadraticRateResidual(:);
    recordedRateScale = gauge.omegaGaugeQuadraticRateScale(:);
    impliedCOmega = -forcing./peak;
    reconstructedRateResidual = forcing+cOmega.*peak;
    expectedRateScale = max([abs(forcing),abs(cOmega.*peak), ...
        realmin*ones(recordCount,1)],[],2);
    normalizedRateResidual = ...
        abs(reconstructedRateResidual)./expectedRateScale;
    rateScaleDefect = relative_identity_defect( ...
        recordedRateScale,expectedRateScale);
    selectedRateDefect = relative_identity_defect(cOmega,impliedCOmega);
    recordedResidualDefect = relative_identity_defect( ...
        recordedRateResidual,reconstructedRateResidual);
    normalizedResidualDefect = relative_identity_defect( ...
        gauge.omegaGaugeResidual(:), ...
        recordedRateResidual./recordedRateScale);
    peakEnergyDefect = relative_identity_defect( ...
        gauge.omegaGaugeEnergy(:),peak);
    peakResidualDefect = relative_identity_defect( ...
        gauge.omegaPeakRateResidual(:),recordedRateResidual);
    peakCoordinateDefect = relative_identity_defect( ...
        gauge.omegaGaugePeakX(:), ...
        gauge.omegaGaugeQuadraticPeakX(:));
    stencil = audit_quadratic_stencil_history( ...
        result.grid.x,gauge.omegaGaugeQuadraticStencilCenterX(:), ...
        gauge.omegaGaugeQuadraticPeakX(:),vertexFraction);
    algebraTolerance = 1e-10;
    selectionTolerance = 1e-10;
    minimumCurvatureCondition = 1e-6;
    pointConditionFloor = ...
        result.config.scaling.pointStrainConditionFloor;

    checks.peakStrictlyPositive = all(peak > 0);
    checks.peakCondition = all(gauge.omegaGaugePeakCondition(:) >= ...
        pointConditionFloor*(1-algebraTolerance));
    checks.curvatureStrictlyNegative = all(curvature < 0);
    checks.curvatureConditionStrictlyPositive = ...
        all(curvatureCondition >= minimumCurvatureCondition);
    checks.weightCondition = all(weightCondition > 0 & ...
        weightCondition <= 1+algebraTolerance);
    checks.activeNodeMargin = ...
        all(activeNodeMargin >= -selectionTolerance);
    checks.activeSelectionMargin = ...
        all(activeSelectionMargin >= -selectionTolerance);
    checks.stencilCenterOnGrid = stencil.centerOnGrid;
    checks.stencilCenterInterior = stencil.centerInterior;
    checks.quadraticVertexInterior = stencil.vertexInterior;
    checks.vertexInteriorFractionIdentity = ...
        stencil.fractionIdentity;
    checks.relativeSubgridLiftNonnegative = ...
        all(subgridLift >= -algebraTolerance);
    checks.stationarityResidual = ...
        max(abs(normalizedStationarity)) <= algebraTolerance;
    checks.rateScaleStrictlyPositive = all(recordedRateScale > 0);
    checks.rateScaleIdentity = max(rateScaleDefect) <= algebraTolerance;
    checks.selectedRateIdentity = ...
        max(selectedRateDefect) <= algebraTolerance;
    checks.rateEquationResidual = ...
        max(normalizedRateResidual) <= algebraTolerance;
    checks.recordedRateResidualIdentity = ...
        max(recordedResidualDefect) <= algebraTolerance;
    checks.normalizedGaugeResidualIdentity = ...
        max(normalizedResidualDefect) <= algebraTolerance;
    checks.peakAliasesIdentity = max([peakEnergyDefect; ...
        peakResidualDefect;peakCoordinateDefect]) <= algebraTolerance;

    metrics = struct( ...
        'recordCount',recordCount, ...
        'minimumP',min(peak),'maximumP',max(peak), ...
        'terminalP',peak(end), ...
        'minimumF',min(forcing),'maximumF',max(forcing), ...
        'terminalF',forcing(end), ...
        'terminalImpliedCOmega',impliedCOmega(end), ...
        'maximumSelectedRateDefect',max(selectedRateDefect), ...
        'maximumNormalizedRateResidual',max(normalizedRateResidual), ...
        'maximumRecordedRateResidualDefect', ...
            max(recordedResidualDefect), ...
        'maximumRateScaleDefect',max(rateScaleDefect), ...
        'maximumNormalizedStationarityResidual', ...
            max(abs(normalizedStationarity)), ...
        'minimumCurvature',min(curvature), ...
        'maximumCurvature',max(curvature), ...
        'minimumCurvatureCondition',min(curvatureCondition), ...
        'minimumCurvatureConditionLimit',minimumCurvatureCondition, ...
        'minimumWeightCondition',min(weightCondition), ...
        'minimumActiveNodeMargin',min(activeNodeMargin), ...
        'minimumActiveSelectionMargin',min(activeSelectionMargin), ...
        'minimumVertexInteriorFraction',min(vertexFraction), ...
        'minimumRelativeSubgridLift',min(subgridLift), ...
        'stencilSwitchCount',nnz(diff( ...
            gauge.omegaGaugeQuadraticStencilCenterX(:)) ~= 0), ...
        'stencil',stencil);
end
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct( ...
    'name',gaugeName, ...
    'kind','active_nonuniform_three_node_quadratic_vertex', ...
    'selectedRatePrescribed',false, ...
    'requiredFields',{required}, ...
    'checks',checks, ...
    'failures',{failures}, ...
    'passed',passed, ...
    'tolerance',1e-10, ...
    'metrics',metrics);
end

function [audit,passed] = audit_gradient_amplitude_gauge(result,gaugeName)
common = result.history.common;
gauge = result.history.gauge;
required = [{'omegaGaugeResidual'},gradient_history_fields()];
recordCount = numel(common.t);
complete = all(isfield(gauge,required));
finiteHistory = complete && recordCount > 0;
if complete
    for index = 1:numel(required)
        values = gauge.(required{index});
        finiteHistory = finiteHistory && isnumeric(values) && ...
            isreal(values) && isvector(values) && ...
            numel(values) == recordCount && all(isfinite(values(:)));
    end
end
cOmegaAvailable = isfield(common,'c_omega') && ...
    isnumeric(common.c_omega) && isreal(common.c_omega) && ...
    isvector(common.c_omega) && numel(common.c_omega) == recordCount && ...
    all(isfinite(common.c_omega(:)));
checks = struct( ...
    'selectedGauge',strcmp(result.config.scaling.cOmegaGauge,gaugeName), ...
    'historyComplete',complete, ...
    'historyFinite',finiteHistory, ...
    'cOmegaHistoryAvailable',cOmegaAvailable, ...
    'energyStrictlyPositive',false, ...
    'energyPartsNonnegative',false, ...
    'energyPartsIdentity',false, ...
    'forcingPartsIdentity',false, ...
    'absoluteForcingNonnegative',false, ...
    'absoluteForcingDominatesNet',false, ...
    'cancellationRatioIdentity',false, ...
    'cancellationRatioRange',false, ...
    'selectedRateIdentity',false, ...
    'gaugeEquationResidual',false, ...
    'recordedResidualIdentity',false);
minimumEnergy = NaN;
maximumResidual = Inf;
maximumSelectedRateDefect = Inf;
maximumEnergyPartsDefect = Inf;
maximumForcingPartsDefect = Inf;
maximumCancellationDefect = Inf;
maximumRecordedResidualDefect = Inf;
if finiteHistory && cOmegaAvailable
    tolerance = 1e-10;
    energy = gauge.omegaGaugeEnergy(:);
    energyX = gauge.omegaGaugeEnergyX(:);
    energyY = gauge.omegaGaugeEnergyY(:);
    forcing = gauge.omegaGaugeForcing(:);
    forcingX = gauge.omegaGaugeForcingX(:);
    forcingY = gauge.omegaGaugeForcingY(:);
    absoluteForcing = gauge.omegaGaugeAbsoluteForcing(:);
    cancellation = gauge.omegaGaugeForcingCancellationRatio(:);
    cOmega = common.c_omega(:);
    expectedCancellation = abs(forcing)./max(absoluteForcing,realmin);
    equation = forcing+cOmega.*energy;
    equationScale = max([abs(forcing),abs(cOmega.*energy), ...
        realmin*ones(recordCount,1)],[],2);
    expectedResidual = equation./equationScale;
    energyPartsDefect = normalized_identity_defect( ...
        energy,energyX+energyY);
    forcingPartsDefect = normalized_identity_defect( ...
        forcing,forcingX+forcingY);
    cancellationDefect = normalized_identity_defect( ...
        cancellation,expectedCancellation);
    selectedRateDefect = relative_identity_defect( ...
        cOmega,-forcing./energy);
    recordedResidualDefect = normalized_identity_defect( ...
        gauge.omegaGaugeResidual(:),expectedResidual);
    absoluteTolerance = tolerance*max([ones(recordCount,1), ...
        abs(forcing),absoluteForcing],[],2);
    checks.energyStrictlyPositive = all(energy > 0);
    checks.energyPartsNonnegative = ...
        all(energyX >= 0) && all(energyY >= 0);
    checks.energyPartsIdentity = max(energyPartsDefect) <= tolerance;
    checks.forcingPartsIdentity = max(forcingPartsDefect) <= tolerance;
    checks.absoluteForcingNonnegative = all(absoluteForcing >= 0);
    checks.absoluteForcingDominatesNet = ...
        all(absoluteForcing+absoluteTolerance >= abs(forcing));
    checks.cancellationRatioIdentity = ...
        max(cancellationDefect) <= tolerance;
    checks.cancellationRatioRange = all(cancellation >= 0 & ...
        cancellation <= 1+tolerance);
    checks.selectedRateIdentity = ...
        max(selectedRateDefect) <= tolerance;
    maximumResidual = max(abs(equation)./equationScale);
    checks.gaugeEquationResidual = maximumResidual <= tolerance;
    checks.recordedResidualIdentity = ...
        max(recordedResidualDefect) <= tolerance;
    minimumEnergy = min(energy);
    maximumSelectedRateDefect = max(selectedRateDefect);
    maximumEnergyPartsDefect = max(energyPartsDefect);
    maximumForcingPartsDefect = max(forcingPartsDefect);
    maximumCancellationDefect = max(cancellationDefect);
    maximumRecordedResidualDefect = max(recordedResidualDefect);
end
failures = failed_checks(checks);
passed = isempty(failures);
audit = struct( ...
    'name',gaugeName, ...
    'kind','fixed_grid_gradient_energy', ...
    'selectedRatePrescribed',false, ...
    'requiredFields',{required}, ...
    'checks',checks, ...
    'failures',{failures}, ...
    'passed',passed, ...
    'tolerance',1e-10, ...
    'minimumEnergy',minimumEnergy, ...
    'maximumSelectedRateDefect',maximumSelectedRateDefect, ...
    'maximumEnergyPartsDefect',maximumEnergyPartsDefect, ...
    'maximumForcingPartsDefect',maximumForcingPartsDefect, ...
    'maximumCancellationRatioDefect',maximumCancellationDefect, ...
    'maximumGaugeEquationResidual',maximumResidual, ...
    'maximumRecordedResidualIdentityDefect', ...
        maximumRecordedResidualDefect);
end

function metrics = empty_quadratic_gauge_metrics()
metrics = struct( ...
    'recordCount',0, ...
    'minimumP',NaN,'maximumP',NaN,'terminalP',NaN, ...
    'minimumF',NaN,'maximumF',NaN,'terminalF',NaN, ...
    'terminalImpliedCOmega',NaN, ...
    'maximumSelectedRateDefect',Inf, ...
    'maximumNormalizedRateResidual',Inf, ...
    'maximumRecordedRateResidualDefect',Inf, ...
    'maximumRateScaleDefect',Inf, ...
    'maximumNormalizedStationarityResidual',Inf, ...
    'minimumCurvature',NaN,'maximumCurvature',NaN, ...
    'minimumCurvatureCondition',NaN, ...
    'minimumCurvatureConditionLimit',1e-6, ...
    'minimumWeightCondition',NaN, ...
    'minimumActiveNodeMargin',NaN, ...
    'minimumActiveSelectionMargin',NaN, ...
    'minimumVertexInteriorFraction',NaN, ...
    'minimumRelativeSubgridLift',NaN, ...
    'stencilSwitchCount',NaN, ...
    'stencil',struct());
end

function audit = audit_quadratic_stencil_history( ...
        gridX,stencilCenter,vertexX,recordedFraction)
gridX = gridX(:);
recordCount = numel(stencilCenter);
centerOnGrid = false(recordCount,1);
centerInterior = false(recordCount,1);
vertexInterior = false(recordCount,1);
fractionIdentity = false(recordCount,1);
centerDistance = Inf(recordCount,1);
fractionDefect = Inf(recordCount,1);
centerIndex = NaN(recordCount,1);
for index = 1:recordCount
    [centerDistance(index),nearest] = ...
        min(abs(gridX-stencilCenter(index)));
    centerIndex(index) = nearest;
    tolerance = 128*eps(max([1;abs(stencilCenter(index));abs(gridX)]));
    centerOnGrid(index) = centerDistance(index) <= tolerance;
    centerInterior(index) = nearest > 1 && nearest < numel(gridX);
    if centerOnGrid(index) && centerInterior(index)
        left = gridX(nearest-1);
        right = gridX(nearest+1);
        vertexInterior(index) = vertexX(index) > left+tolerance && ...
            vertexX(index) < right-tolerance;
        expectedFraction = min(vertexX(index)-left, ...
            right-vertexX(index))/(right-left);
        fractionDefect(index) = abs(recordedFraction(index)- ...
            expectedFraction)/max([abs(recordedFraction(index)), ...
            abs(expectedFraction),realmin]);
        fractionIdentity(index) = fractionDefect(index) <= 1e-10 && ...
            recordedFraction(index) > 0 && ...
            recordedFraction(index) <= 0.5+1e-10;
    end
end
audit = struct( ...
    'centerOnGrid',all(centerOnGrid), ...
    'centerInterior',all(centerInterior), ...
    'vertexInterior',all(vertexInterior), ...
    'fractionIdentity',all(fractionIdentity), ...
    'maximumCenterDistance',max(centerDistance), ...
    'maximumFractionDefect',max(fractionDefect), ...
    'centerIndices',centerIndex);
end

function audit = audit_rate_provenance(diagnostic)
structure = isstruct(diagnostic) && isscalar(diagnostic);
criteriaV3 = structure && isfield(diagnostic,'criteriaVersion') && ...
    isequal(diagnostic.criteriaVersion,3);
selectedRatePrescribed = NaN;
selectedField = structure && ...
    isfield(diagnostic,'selectedRatePrescribed');
if selectedField
    selectedRatePrescribed = diagnostic.selectedRatePrescribed;
end
selectedNotPrescribed = selectedField && ...
    islogical(selectedRatePrescribed) && ...
    isscalar(selectedRatePrescribed) && ~selectedRatePrescribed;
provenanceAvailable = structure && ...
    isfield(diagnostic,'selectedRateProvenanceAvailable') && ...
    islogical(diagnostic.selectedRateProvenanceAvailable) && ...
    isscalar(diagnostic.selectedRateProvenanceAvailable) && ...
    diagnostic.selectedRateProvenanceAvailable;
empiricalEligible = structure && ...
    isfield(diagnostic,'empiricalRateConvergenceEligible') && ...
    islogical(diagnostic.empiricalRateConvergenceEligible) && ...
    isscalar(diagnostic.empiricalRateConvergenceEligible) && ...
    diagnostic.empiricalRateConvergenceEligible;
checks = struct( ...
    'scalarStructure',structure, ...
    'criteriaVersion3',criteriaV3, ...
    'selectedRateNotPrescribed',selectedNotPrescribed, ...
    'selectedRateProvenanceAvailable',provenanceAvailable, ...
    'empiricalRateConvergenceEligible',empiricalEligible);
failures = failed_checks(checks);
audit = struct( ...
    'passed',isempty(failures), ...
    'checks',checks, ...
    'failures',{failures}, ...
    'criteriaVersion',select_struct_field( ...
        diagnostic,'criteriaVersion',NaN), ...
    'selectedRatePrescribed',selectedRatePrescribed, ...
    'selectedRateProvenanceAvailable',provenanceAvailable, ...
    'empiricalRateConvergenceEligible',empiricalEligible);
end

function audit = audit_growth_telemetry(result)
common = result.history.common;
requiredHistory = {'canonicalTau','physicalTime','physicalRhoXInf', ...
    'physicalGradInf'};
recordCount = numel(common.t);
historyComplete = all(isfield(common,requiredHistory));
historyFinite = historyComplete && recordCount > 0;
if historyComplete
    for index = 1:numel(requiredHistory)
        values = common.(requiredHistory{index});
        historyFinite = historyFinite && isnumeric(values) && ...
            isreal(values) && isvector(values) && ...
            numel(values) == recordCount && all(isfinite(values(:)));
    end
end
physicalFitAvailable = isfield(result.fit,'maximumGrowthRate') && ...
    growth_fit_schema(result.fit.maximumGrowthRate);
canonicalFitAvailable = isfield(result.fit,'canonicalMaximumGrowth') && ...
    growth_fit_schema(result.fit.canonicalMaximumGrowth);

checks = struct( ...
    'historyComplete',historyComplete, ...
    'historyFinite',historyFinite, ...
    'positivePhysicalMaximum',false, ...
    'nondecreasingClocks',false, ...
    'physicalFitSchema',physicalFitAvailable, ...
    'canonicalFitSchema',canonicalFitAvailable, ...
    'fitInputAvailable',false, ...
    'quadraticTelemetrySchema',true, ...
    'quadraticTelemetryAvailable',true, ...
    'quadraticTelemetryGauge',true, ...
    'quadraticTelemetryAlgebra',true);
initialMaximum = NaN;
terminalMaximum = NaN;
totalLogGrowth = NaN;
if historyFinite
    physicalMaximum = common.physicalRhoXInf(:);
    checks.positivePhysicalMaximum = all(physicalMaximum > 0) && ...
        all(common.physicalGradInf(:) > 0);
    checks.nondecreasingClocks = ...
        all(diff(common.canonicalTau(:)) >= 0) && ...
        all(diff(common.physicalTime(:)) >= 0);
    initialMaximum = physicalMaximum(1);
    terminalMaximum = physicalMaximum(end);
    if initialMaximum > 0 && terminalMaximum > 0
        totalLogGrowth = log(terminalMaximum/initialMaximum);
    end
end
if physicalFitAvailable && canonicalFitAvailable
    physicalFit = result.fit.maximumGrowthRate;
    canonicalFit = result.fit.canonicalMaximumGrowth;
    checks.fitInputAvailable = ...
        isequal(physicalFit.inputAvailable,true) && ...
        isequal(canonicalFit.inputAvailable,true) && ...
        strcmp(physicalFit.observable,'physicalRhoXInf') && ...
        strcmp(canonicalFit.observable,'physicalRhoXInf');
end

quadraticAudit = struct('required',false,'passed',true);
if strcmp(result.config.scaling.cOmegaGauge, ...
        'wall_omega_quadratic_peak')
    [quadraticAudit,quadraticChecks] = ...
        audit_quadratic_growth_telemetry(result);
    checks.quadraticTelemetrySchema = quadraticChecks.schema;
    checks.quadraticTelemetryAvailable = quadraticChecks.available;
    checks.quadraticTelemetryGauge = quadraticChecks.gauge;
    checks.quadraticTelemetryAlgebra = quadraticChecks.algebra;
end
failures = failed_checks(checks);
audit = struct( ...
    'passed',isempty(failures), ...
    'checks',checks, ...
    'failures',{failures}, ...
    'observable','physicalRhoXInf', ...
    'recordCount',recordCount, ...
    'initialPhysicalRhoXInf',initialMaximum, ...
    'terminalPhysicalRhoXInf',terminalMaximum, ...
    'totalLogGrowth',totalLogGrowth, ...
    'quadraticPeakTelemetryAudit',quadraticAudit);
end

function valid = growth_fit_schema(fit)
required = {'valid','points','minimumCredibleEFolds','totalLogGrowth', ...
    'credibleClassification','observable','inputAvailable', ...
    'trustedRecords'};
valid = isstruct(fit) && isscalar(fit) && all(isfield(fit,required)) && ...
    islogical(fit.valid) && isscalar(fit.valid) && ...
    isnumeric(fit.points) && isscalar(fit.points) && ...
    isfinite(fit.points) && fit.points >= 0 && ...
    isequal(fit.minimumCredibleEFolds,3) && ...
    islogical(fit.credibleClassification) && ...
    isscalar(fit.credibleClassification) && ...
    islogical(fit.inputAvailable) && isscalar(fit.inputAvailable) && ...
    isnumeric(fit.trustedRecords) && isscalar(fit.trustedRecords) && ...
    isfinite(fit.trustedRecords) && fit.trustedRecords >= 0;
end

function [audit,checks] = audit_quadratic_growth_telemetry(result)
required = {'schemaVersion','observable','interpretation', ...
    'empiricalClassificationPerformed','selectedGauge', ...
    'inputAvailable','trustedRecords','validRecords', ...
    'storedReconstructionConsistent','physicalTime','canonicalTau', ...
    'physicalQuadraticPeak','inversePhysicalQuadraticPeak', ...
    'quadraticInverseSlopeAlgebraic','quadraticLocalTerminalTime', ...
    'rescaledRhoXInfToQuadraticPeak'};
available = isfield(result.fit,'quadraticPeakTelemetry');
schema = false;
gaugePassed = false;
algebra = false;
maximumDefect = Inf;
trustedRecords = 0;
if available
    telemetry = result.fit.quadraticPeakTelemetry;
    schema = isstruct(telemetry) && isscalar(telemetry) && ...
        all(isfield(telemetry,required)) && ...
        isequal(telemetry.schemaVersion,1);
    if schema
        gaugePassed = ...
            strcmp(telemetry.selectedGauge, ...
                'wall_omega_quadratic_peak') && ...
            strcmp(telemetry.observable, ...
                'selected_wall_omega_quadratic_peak') && ...
            isequal(telemetry.empiricalClassificationPerformed,false) && ...
            isequal(telemetry.inputAvailable,true) && ...
            isequal(telemetry.storedReconstructionConsistent,true);
        rawTrusted = ipm.output.trustedMask(result);
        trusted = ipm.output.continuousTrustedPrefix(rawTrusted);
        trustedRecords = nnz(trusted);
        series = {'physicalTime','canonicalTau', ...
            'physicalQuadraticPeak','inversePhysicalQuadraticPeak', ...
            'quadraticInverseSlopeAlgebraic', ...
            'quadraticLocalTerminalTime', ...
            'rescaledRhoXInfToQuadraticPeak'};
        alignedFinite = telemetry.trustedRecords == trustedRecords && ...
            telemetry.validRecords == trustedRecords && trustedRecords > 0;
        for index = 1:numel(series)
            values = telemetry.(series{index});
            alignedFinite = alignedFinite && isnumeric(values) && ...
                isreal(values) && isvector(values) && ...
                numel(values) == trustedRecords && ...
                all(isfinite(values(:)));
        end
        if alignedFinite
            common = result.history.common;
            peak = result.history.gauge. ...
                omegaGaugeQuadraticPeakValue(trusted);
            peak = peak(:);
            lengthScale = common.C_l(trusted);
            lengthScale = lengthScale(:);
            amplitudeScale = common.C_omega(trusted);
            amplitudeScale = amplitudeScale(:);
            cL = common.canonicalCL(trusted);
            cL = cL(:);
            cOmega = common.canonicalCOmega(trusted);
            cOmega = cOmega(:);
            physicalTime = common.physicalTime(trusted);
            physicalTime = physicalTime(:);
            rescaledMaximum = common.rhoXInf(trusted);
            rescaledMaximum = rescaledMaximum(:);
            physicalPeak = lengthScale./amplitudeScale.*peak;
            inversePeak = 1./physicalPeak;
            kappa = cL-cOmega;
            inverseSlope = -kappa./peak;
            terminalTime = physicalTime + ...
                peak./(kappa.*physicalPeak);
            maximumRatio = rescaledMaximum./peak;
            defects = [ ...
                relative_identity_defect( ...
                    telemetry.physicalTime(:),physicalTime); ...
                relative_identity_defect( ...
                    telemetry.canonicalTau(:), ...
                    reshape(common.canonicalTau(trusted),[],1)); ...
                relative_identity_defect( ...
                    telemetry.physicalQuadraticPeak(:),physicalPeak); ...
                relative_identity_defect( ...
                    telemetry.inversePhysicalQuadraticPeak(:),inversePeak); ...
                relative_identity_defect( ...
                    telemetry.quadraticInverseSlopeAlgebraic(:), ...
                    inverseSlope); ...
                relative_identity_defect( ...
                    telemetry.quadraticLocalTerminalTime(:),terminalTime); ...
                relative_identity_defect( ...
                    telemetry.rescaledRhoXInfToQuadraticPeak(:), ...
                    maximumRatio)];
            maximumDefect = max(defects);
            algebra = all(physicalPeak > 0) && all(inversePeak > 0) && ...
                all(kappa > 0) && maximumDefect <= 1e-10;
        end
    end
end
checks = struct('schema',schema,'available',available && schema && ...
    gaugePassed,'gauge',gaugePassed,'algebra',algebra);
audit = struct( ...
    'required',true, ...
    'passed',all(structfun(@(value)isequal(value,true),checks)), ...
    'checks',checks, ...
    'requiredFields',{required}, ...
    'trustedRecords',trustedRecords, ...
    'maximumAlgebraicDefect',maximumDefect);
end

function defect = relative_identity_defect(actual,expected)
actual = actual(:);
expected = expected(:);
scale = max([abs(actual),abs(expected), ...
    realmin*ones(size(actual))],[],2);
defect = abs(actual-expected)./scale;
end

function defect = normalized_identity_defect(actual,expected)
actual = actual(:);
expected = expected(:);
scale = max([ones(size(actual)),abs(actual),abs(expected)],[],2);
defect = abs(actual-expected)./scale;
end

function value = select_struct_field(values,name,defaultValue)
if isstruct(values) && isscalar(values) && isfield(values,name)
    value = values.(name);
else
    value = defaultValue;
end
end

function flattened = flatten_config(config)
flattened = struct();
domains = {'grid','time','physics','elliptic','transport','scaling', ...
    'remesh','diagnostics','output'};
for domainIndex = 1:numel(domains)
    values = config.(domains{domainIndex});
    names = fieldnames(values);
    for nameIndex = 1:numel(names)
        flattened.(names{nameIndex}) = values.(names{nameIndex});
    end
end
end

function present = checkpoint_retired_fields(checkpoint)
retired = retired_fields();
state = checkpoint.payload.state;
present = retired(isfield(state.rescaling,retired));
present = unique([present, ...
    retired(isfield(state.config.scaling,retired))],'stable');
end

function path = locate_checkpoint(result,requestedFile)
path = '';
if isfield(result.metadata,'latestCheckpointFile')
    candidate = char(result.metadata.latestCheckpointFile);
    if ~isempty(candidate) && isfile(candidate)
        path = candidate;
        return
    end
end
[directory,stem,~] = fileparts(requestedFile);
candidates = dir(fullfile(directory,[stem,'_*.mat']));
if isempty(candidates)
    return
end
[~,order] = sort([candidates.datenum],'descend');
candidate = candidates(order(1));
path = fullfile(candidate.folder,candidate.name);
end

function normalized = normalized_anchor_residual(residual,rate,anchorX)
anchorU1 = residual-rate.*anchorX;
scale = max(abs(rate.*anchorX),abs(anchorU1));
scale = max(scale,realmin);
normalized = abs(residual)./scale;
end

function rules = registered_gauge_rules(cOmegaGauge)
rules = struct( ...
    'scalingContract','exact_gauge_no_feedback_v1', ...
    'clock','tau_is_integrated_directly; timeSpeed=1', ...
    'lengthGauge','transport_anchor', ...
    'lengthObservable','V_1(1,0)=0', ...
    'lengthFormula','c_l=-U_1(1,0)', ...
    'amplitudeGauge',cOmegaGauge, ...
    'amplitudeObservable','', ...
    'amplitudeFormula','', ...
    'selectedRatePrescribed',false, ...
    'rateLimiter','absent', ...
    'feedbackGains',[1,0,0,0]);
switch cOmegaGauge
    case 'gradient_energy'
        rules.amplitudeObservable = ...
            'sum(w*(R_X^2+R_Y^2)) is constant';
        rules.amplitudeFormula = [ ...
            'c_omega=-sum(w*(R_X*B_X+R_Y*B_Y))/' ...
            'sum(w*(R_X^2+R_Y^2))'];
    case 'wall_omega_quadratic_peak'
        rules.amplitudeObservable = ...
            'tracked nonuniform quadratic wall R_X peak is constant';
        rules.amplitudeFormula = ...
            'c_omega=-Q[B_X](X_vertex)/Q[R_X](X_vertex)';
    otherwise
        error('ipm:GaugeLabQ512COmegaGauge', ...
            'Unsupported registered cOmegaGauge: %s.',cOmegaGauge);
end
end

function requested = requested_summary(settings)
requested = struct( ...
    'cOmegaGauge',settings.cOmegaGauge, ...
    'physicalFinalTime',settings.physicalFinalTime, ...
    'canonicalFinalTime',settings.canonicalFinalTime, ...
    'maxDt',settings.maxDt, ...
    'maxSteps',settings.maxSteps, ...
    'cfl',settings.cfl, ...
    'outputEvery',settings.outputEvery, ...
    'checkpointEvery',settings.checkpointEvery, ...
    'checkpointAtExit',true, ...
    'saveResults',true, ...
    'fixedMesh',true);
end

function failures = failed_checks(checks)
names = fieldnames(checks);
failures = cell(0,1);
for index = 1:numel(names)
    if ~isequal(checks.(names{index}),true)
        failures{end+1,1} = names{index}; %#ok<AGROW>
    end
end
end

function names = retired_fields()
names = {'maxDynamicRate','adaptiveGain','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
end

function value = numeric_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
end

function value = text_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabQ512Options', ...
        'Option %s must be nonempty text.',name);
end
value = lower(value);
end

function value = path_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(value)
    error('ipm:GaugeLabQ512Options', ...
        'Option %s must be a nonempty path.',name);
end
end

function value = logical_option(options,name,defaultValue)
if isfield(options,name)
    value = options.(name);
else
    value = defaultValue;
end
valid = (islogical(value) && isscalar(value)) || ...
    (isnumeric(value) && isreal(value) && isscalar(value) && ...
    isfinite(value) && any(value == [0,1]));
if ~valid
    error('ipm:GaugeLabQ512Options', ...
        'Option %s must be a logical scalar.',name);
end
value = logical(value);
end

function root = default_output_root()
fileName = mfilename('fullpath');
gaugeDirectory = fileparts(fileName);
researchDirectory = fileparts(gaugeDirectory);
repositoryRoot = fileparts(researchDirectory);
root = fullfile(repositoryRoot,'result','verification', ...
    'q512_fresh_exact_gauge_roots_v4');
end

function [directory,runId] = create_output_directory(settings)
root = char(settings.outputRoot);
if ~isfolder(root)
    mkdir(root);
end
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
[~,token] = fileparts(tempname);
runId = sprintf('root_%s_%s_%s_%s',stamp,settings.boxMode, ...
    settings.runMode,token);
directory = fullfile(root,runId);
if isfile(directory) || isfolder(directory)
    error('ipm:GaugeLabQ512OutputCollision', ...
        'Output path already exists: %s',directory);
end
mkdir(directory);
end

function save_summary(fileName,rootRun)
save(fileName,'rootRun');
end

function append_manifest(fileName,record)
fileId = fopen(fileName,'a');
if fileId < 0
    error('ipm:GaugeLabQ512Manifest', ...
        'Could not append manifest %s.',fileName);
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function require_factory()
if exist('fourth_order_blowup_case','file') ~= 2
    error('ipm:GaugeLabQ512Path', ...
        ['fourth_order_blowup_case is not on the MATLAB path.  Add ' ...
        'research/experiments before calling this runner.']);
end
end

function tf = endpoint_close(actual,expected)
actual = actual(:);
expected = expected(:);
scale = max([ones(size(actual)),abs(actual),abs(expected)],[],2);
tf = numel(actual) == numel(expected) && ...
    all(abs(actual-expected) <= 100*eps(scale));
end

function tf = scalar_close(actual,expected)
scale = max([1,abs(actual),abs(expected)]);
tf = isfinite(actual) && isfinite(expected) && ...
    abs(actual-expected) <= 100*eps(scale);
end

function value = utc_stamp()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
