function specifications = ipm_gaugelab_length_candidate_specifications()
%IPM_GAUGELAB_LENGTH_CANDIDATE_SPECIFICATIONS Frozen q256 c_l registry.
%   These are existing schema-4 exact algebraic gauges.  The registry adds
%   no filtering, limiter, restoring feedback, or new evolution formula.

template = struct('lengthGauge','','role','production_candidate', ...
    'formula','','observable','','evaluation','', ...
    'registeredParameters',struct(),'scientificCaveat','');
specifications = repmat(template,6,1);

specifications(1) = candidate('transport_anchor', ...
    'c_l=-U1(X_anchor,0)/X_anchor', ...
    'V1(X_anchor,0)=0','fixed_coordinate_linear_interpolation', ...
    struct('transportAnchorX',1), ...
    ['The q256 F80 axis does not place X=1 exactly on a node, so this ' ...
    'candidate includes the existing linear interpolation error.']);
specifications(2) = candidate('symmetry_peak', ...
    'c_l=-(U1(X_peak,0)-U1(0,0))/(X_peak-0)', ...
    'peak_separation', ...
    'quadratic_R_X_peak_then_linear_velocity_interpolation', ...
    struct('peakTrackingWidthFactor',3), ...
    ['The tracked wall-omega peak is a moving, interpolated discrete ' ...
    'feature and can become ambiguous if the wall profile loses unimodality.']);
specifications(3) = candidate('local_strain', ...
    'c_l=-d_X(U1)(X_peak,0)', ...
    'wall_peak_local_strain', ...
    'quadratic_R_X_peak_then_linear_strain_interpolation', ...
    struct('peakTrackingWidthFactor',3), ...
    ['This local derivative gauge can be more sensitive to spatial ' ...
    'resolution than velocity or width functionals.']);
specifications(4) = candidate('omega_peak_location', ...
    'c_l=physicalRhs_XX(X_peak)/(X_peak*R_XXX(X_peak))', ...
    'wall_omega_peak_location', ...
    'quadratic_R_X_peak_then_linear_Dx_field_interpolation', ...
    struct('peakTrackingWidthFactor',3), ...
    ['This is an algebraic phase candidate, not an exact discrete peak ' ...
    'condition: X_peak comes from a quadratic R_X peak while R_XX and ' ...
    'R_XXX use differentiated fields with linear interpolation. The full ' ...
    'phase defect and the global response condition must be inspected.']);
specifications(5) = candidate('wall_omega_width', ...
    'c_l=-physical_width_rate/current_width', ...
    'wall_omega_level_width','piecewise_linear_level_crossings', ...
    struct('adaptiveLevels',[0.1,0.5,0.9], ...
        'selectedWidthLevel',0.9,'selectionRule','maximum_adaptive_level'), ...
    ['The registered 0.9 connected-component width uses interpolated ' ...
    'level crossings and fails closed if either crossing is not interior.']);
specifications(6) = candidate('wall_density_width', ...
    ['c_l=-(U1(X_upper,0)-U1(X_lower,0))/' ...
    '(X_upper-X_lower)'], ...
    'wall_density_level_width','piecewise_linear_level_crossings', ...
    struct('lengthGaugeLevels',[0.2,0.6]), ...
    ['The two crossings are defined relative to the instantaneous wall ' ...
    'density maximum and can become ill-conditioned if they coalesce.']);
end

function value = candidate(name,formula,observable,evaluation,parameters,caveat)
value = struct('lengthGauge',name,'role','production_candidate', ...
    'formula',formula,'observable',observable,'evaluation',evaluation, ...
    'registeredParameters',parameters,'scientificCaveat',caveat);
end
