function products = ipm_gaugelab_run_q256_playoffs(userOptions)
%IPM_GAUGELAB_RUN_Q256_PLAYOFFS Describe the retired schema-3 playoff.
%   This entry point is intentionally read-only. It creates no directory,
%   starts no solve, resumes no checkpoint, and grants no production status.

if nargin < 1
    userOptions = struct();
end
validate_options(userOptions);
products = struct( ...
    'schemaVersion',1, ...
    'kind','q256_comega_gauge_playoffs_unlimited', ...
    'status','read_only_history', ...
    'artifactDisposition','read_only_history', ...
    'productionEligible',false, ...
    'launchEnabled',false, ...
    'message',[ ...
        'The schema-3 playoff is retired. Existing artifacts may be ' ...
        'analyzed but not resumed or promoted; use ' ...
        'ipm_gaugelab_run_q256_group_stage_v4 for new runs.'], ...
    'protocol',legacy_protocol());
warning('ipm:GaugeLabLegacyPlayoffReadOnly','%s',products.message);
end

function protocol = legacy_protocol()
protocol = struct( ...
    'schemaVersion',1, ...
    'configurationSchemaVersion',3, ...
    'registration','frozen_before_long_or_half_step_runs', ...
    'artifactDisposition','read_only_history', ...
    'productionEligible',false,'launchEnabled',false, ...
    'candidates',{{'gradient_energy','anchor_wall_slope'}}, ...
    'physicalFinalTime',1.10, ...
    'coarseMaxDt',2e-3,'coarseCfl',0.25, ...
    'halfStepMaxDt',1e-3,'halfStepCfl',0.125, ...
    'tailPhysicalWindows',[0.25,0.125], ...
    'maximumRateRelativeTrend',5e-2, ...
    'maximumRateDetrendedRelativeRms',2e-3, ...
    'maximumKappaRelativeTrend',5e-2, ...
    'maximumWallToGradientRelativeTrend',2e-2, ...
    'minimumRateMeanToMaximumRatio',0.1, ...
    'maximumTerminalRateRelativeStepDifference',1e-2, ...
    'maximumTailTrendStepDifference',1e-2, ...
    'maximumPhysicalRhoXRelativeStepDifference',5e-3, ...
    'maximumPhysicalOmegaRelativeL2StepDifference',5e-3, ...
    'wallClockBudgetSeconds',7200, ...
    'grid','coordinated_log_F80_R20_c114_quadrant_256', ...
    'lengthGauge','transport_anchor_X1_without_width_feedback', ...
    'dynamicRateLimiter','absent');
end

function validate_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeLabLegacyPlayoffOptions', ...
        'Options must be a scalar structure.');
end
unknown = setdiff(fieldnames(options),{'verbose'});
if ~isempty(unknown)
    error('ipm:GaugeLabLegacyPlayoffOptionName', ...
        'The read-only legacy descriptor accepts only verbose.');
end
if isfield(options,'verbose')
    value = options.verbose;
    validLogical = islogical(value) && isscalar(value);
    validNumeric = isnumeric(value) && isreal(value) && ...
        isscalar(value) && isfinite(value) && any(value == [0,1]);
    if ~(validLogical || validNumeric)
        error('ipm:GaugeLabLegacyPlayoffVerbose', ...
            'verbose must be logical or numeric 0/1.');
    end
end
end
