function products = ipm_gaugelab_run_q256_group_stage_v4(userOptions)
%IPM_GAUGELAB_RUN_Q256_GROUP_STAGE_V4 Run the preregistered five-gauge screen.
%   Only verbose output may be changed.  The protocol is written before the
%   first solve and delegates execution to the immutable schema-4 tournament.

if nargin < 1
    userOptions = struct();
end
verbose = resolve_verbose(userOptions);
laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,fullfile(researchDirectory,'experiments'), ...
    fullfile(researchDirectory,'analysis'),laboratoryDirectory);

protocol = registered_protocol();
stamp = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS''Z'''));
outputParent = fullfile(projectDirectory,'result','verification', ...
    'q256_comega_gauge_group_stage_v4');
if ~isfolder(outputParent)
    mkdir(outputParent);
end
outputDirectory = fullfile(outputParent,['group_',stamp]);
if isfolder(outputDirectory)
    error('ipm:GaugeLabGroupV4Collision', ...
        'Registered group-stage directory already exists: %s', ...
        outputDirectory);
end
mkdir(outputDirectory);
summaryFile = fullfile(outputDirectory,'group_stage_summary.mat');
manifestFile = fullfile(outputDirectory,'group_stage_manifest.jsonl');

products = struct('schemaVersion',4, ...
    'kind','q256_comega_gauge_group_stage_exact_no_feedback', ...
    'status','registered','startedAt',datetime('now','TimeZone','local'), ...
    'completedAt',NaT,'protocol',protocol, ...
    'outputDirectory',outputDirectory,'summaryFile',summaryFile, ...
    'manifestFile',manifestFile,'tournament',struct(), ...
    'ranking',{{}},'provisionalWinner','', ...
    'productionCandidatesAvailable',false,'elapsedSeconds',NaN, ...
    'failureSummary',struct(),'failureClass','', ...
    'errorIdentifier','','errorMessage','');
save(summaryFile,'products','-v7.3');
append_manifest(manifestFile,struct('event','group_stage_registered', ...
    'timestampUtc',stamp,'protocol',protocol));

clock = tic;
products.status = 'running';
save(summaryFile,'products','-v7.3');
try
    tournamentOptions = struct( ...
        'baseCaseName',protocol.baseCaseName, ...
        'physicalFinalTime',protocol.physicalFinalTime, ...
        'maxDt',protocol.maxDt,'cfl',protocol.cfl, ...
        'candidates',{protocol.candidates}, ...
        'includeNegativeControl',false,'verbose',verbose);
    products.tournament = ...
        ipm_gaugelab_run_q256_tournament(tournamentOptions);
    assert_tournament_contract(products.tournament,protocol);
    products.ranking = products.tournament.ranking;
    products.provisionalWinner = products.tournament.provisionalWinner;
    products.failureSummary = products.tournament.failureSummary;
    if isfield(products.tournament,'runs') && ...
            ~isempty(products.tournament.runs)
        products.productionCandidatesAvailable = ...
            any([products.tournament.runs.productionEligible]);
    end
    products.status = products.tournament.status;
catch exception
    products.status = classify_group_exception(exception);
    products.failureClass = products.status;
    products.errorIdentifier = exception.identifier;
    products.errorMessage = exception.message;
    append_manifest(manifestFile,struct('event','group_stage_error', ...
        'timestampUtc',utc_stamp(),'identifier',exception.identifier, ...
        'message',exception.message,'failureClass', ...
        products.failureClass));
end
products.completedAt = datetime('now','TimeZone','local');
products.elapsedSeconds = toc(clock);
save(summaryFile,'products','-v7.3');
append_manifest(manifestFile,struct('event','group_stage_finished', ...
    'timestampUtc',utc_stamp(),'status',products.status, ...
    'ranking',{products.ranking},'provisionalWinner', ...
    products.provisionalWinner,'failureClass',products.failureClass, ...
    'failureSummary',products.failureSummary, ...
    'elapsedSeconds',products.elapsedSeconds));
fprintf('Q256 GAUGE GROUP V4: status=%s winner=%s summary=%s\n', ...
    products.status,products.provisionalWinner,summaryFile);
end

function protocol = registered_protocol()
candidates = {'gradient_energy','anchor_wall_window_l2', ...
    'anchor_wall_template_projection','anchor_bulk_gradient_l2', ...
    'anchor_wall_window_l4'};
registry = ipm_gaugelab_candidate_specifications(false);
selected = registry(ismember({registry.cOmegaGauge},candidates));
if ~isequal({selected.cOmegaGauge},candidates)
    error('ipm:GaugeLabGroupV4Registry', ...
        'The frozen candidate registry does not match the registered order.');
end
meshLimits = frozen_mesh_limits();
physicalCovarianceLimits = frozen_physical_covariance_limits();
protocol = struct( ...
    'schemaVersion',4, ...
    'registration','frozen_before_any_candidate_solve', ...
    'configurationContract','exact_gauge_no_feedback_v1', ...
    'numericalTuple',frozen_numerical_tuple(), ...
    'artifactEligibility','schema4_production_candidate_only', ...
    'legacySchema3Disposition','read_only_history', ...
    'baseCaseName','coordinated_log_F80_R20_c114_quadrant_256', ...
    'grid','q256_513_by_257_stored_nodes', ...
    'storedNodeCounts',[513,257], ...
    'firstQuadrantCellCounts',[256,256], ...
    'fixedMesh',true, ...
    'physicalFinalTime',0.55,'maxDt',2e-3,'cfl',0.25, ...
    'candidates',{candidates},'candidateSpecifications',selected, ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'omegaGaugeWindowRadius',0.75, ...
    'pointStrainConditionFloor',0.25, ...
    'feedbackGains',[1,0,0,0], ...
    'feedbackGainOrder',{{'lengthScaleGain','widthGaugeGain', ...
        'omegaGaugeGain','travelingWaveGain'}}, ...
    'minimumLocalizedCondition',0.25, ...
    'maximumNormalizedGaugeResidual',1e-10, ...
    'maximumIdentityRelativeError',1e-10, ...
    'meshLimits',meshLimits, ...
    'physicalCovarianceLimits',physicalCovarianceLimits, ...
    'physicalCovarianceMethod','symmetric_pairwise_bidirectional_worst', ...
    'minimumSuccessfulCompetitors',2, ...
    'checkpointCanonicalCadence',frozen_checkpoint_cadence(), ...
    'checkpointEnabled',true,'checkpointAtExit',true, ...
    'checkpointImmutable',true, ...
    'wallClockBudgetSeconds',frozen_wall_clock_budget(), ...
    'resultOverwriteAllowed',false);
end

function assert_tournament_contract(tournament,protocol)
assert(isstruct(tournament) && isscalar(tournament) && ...
    tournament.schemaVersion == 4, ...
    'ipm:GaugeLabGroupV4TournamentSchema', ...
    'The delegated tournament did not return schema 4.');
assert(strcmp(tournament.configurationContract, ...
    protocol.configurationContract) && ...
    tournament.requiredConfigSchemaVersion == 4, ...
    'ipm:GaugeLabGroupV4ScalingContract', ...
    'The delegated tournament changed the exact scaling contract.');
assert(isequaln(tournament.numericalTuple,protocol.numericalTuple) && ...
    tournament.fixedMesh == protocol.fixedMesh, ...
    'ipm:GaugeLabGroupV4NumericalTuple', ...
    'The delegated tournament changed the fixed fourth-order tuple.');
assert(tournament.requestedPhysicalFinalTime == protocol.physicalFinalTime && ...
    strcmp(tournament.baseCaseName,protocol.baseCaseName) && ...
    tournament.requestedMaximumTimeStep == protocol.maxDt && ...
    tournament.requestedCfl == protocol.cfl && ...
    tournament.checkpointCanonicalCadence == ...
        protocol.checkpointCanonicalCadence && ...
    tournament.checkpointEnabled == protocol.checkpointEnabled && ...
    tournament.checkpointAtExit == protocol.checkpointAtExit && ...
    tournament.checkpointImmutable == protocol.checkpointImmutable && ...
    tournament.wallClockBudgetSeconds == protocol.wallClockBudgetSeconds, ...
    'ipm:GaugeLabGroupV4NumericalProtocol', ...
    'The delegated tournament changed the preregistered numerical protocol.');
assert(isequaln(tournament.meshAudit.storedNodes, ...
    protocol.storedNodeCounts) && ...
    isequaln(tournament.meshAudit.firstQuadrantCells, ...
        protocol.firstQuadrantCellCounts), ...
    'ipm:GaugeLabGroupV4GridProtocol', ...
    'The delegated tournament changed the preregistered q256 grid size.');
assert(isequaln(tournament.candidateSpecifications, ...
    protocol.candidateSpecifications), ...
    'ipm:GaugeLabGroupV4CandidateProtocol', ...
    ['The delegated tournament changed the complete preregistered ' ...
    'candidate specifications.']);
assert(isequaln(tournament.meshLimits,protocol.meshLimits), ...
    'ipm:GaugeLabGroupV4MeshProtocol', ...
    'The delegated tournament changed the complete mesh limits.');
assert(isequaln(tournament.physicalCovarianceLimits, ...
    protocol.physicalCovarianceLimits), ...
    'ipm:GaugeLabGroupV4CovarianceProtocol', ...
    ['The delegated tournament changed the complete physical-' ...
    'covariance limits.']);
assert(strcmp(tournament.physicalCovarianceMethod, ...
    protocol.physicalCovarianceMethod) && ...
    tournament.minimumSuccessfulCompetitors == ...
        protocol.minimumSuccessfulCompetitors, ...
    'ipm:GaugeLabGroupV4CovarianceProtocol', ...
    'The delegated tournament changed the covariance comparison protocol.');
attempted = {tournament.runs.cOmegaGauge};
attempted = attempted(~cellfun(@isempty,attempted));
assert(all(ismember(attempted,protocol.candidates)), ...
    'ipm:GaugeLabGroupV4CandidateProtocol', ...
    'The delegated tournament attempted an unregistered candidate.');
end

function limits = frozen_mesh_limits()
limits = struct('maximumAdjacentCellRatio',1.08, ...
    'maximumLogSpacingCurvature',0.01, ...
    'minimumStencilRcond',1e-9, ...
    'minimumQuadratureWeightRatio',1e-8, ...
    'minimumLocalQuadratureWeightRatio',0.35, ...
    'maximumLocalQuadratureWeightRatio',1.65);
end

function limits = frozen_physical_covariance_limits()
limits = struct('rhoRelativeL2',5e-4, ...
    'omegaRelativeL2',5e-3,'rhoAbsoluteInf',5e-4, ...
    'omegaAbsoluteInf',5e-3, ...
    'physicalRhoXRelativeDifference',5e-3, ...
    'wallPeakRelativeDifference',5e-3, ...
    'wallWidthRelativeDifference',2e-2, ...
    'maximumAbsoluteLabPeakShift',5e-4, ...
    'maximumAbsolutePhysicalTimeDifference',1e-10);
end

function cadence = frozen_checkpoint_cadence()
cadence = 0.20;
end

function seconds = frozen_wall_clock_budget()
seconds = 7200;
end

function tuple = frozen_numerical_tuple()
tuple = struct('spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order');
end

function verbose = resolve_verbose(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:GaugeLabGroupV4Options', ...
        'Options must be a scalar structure.');
end
unknown = setdiff(fieldnames(options),{'verbose'});
if ~isempty(unknown)
    error('ipm:GaugeLabGroupV4OptionName', ...
        'Only the verbose display option may be changed.');
end
if isfield(options,'verbose')
    verbose = options.verbose;
else
    verbose = true;
end
validLogical = islogical(verbose) && isscalar(verbose);
validNumeric = isnumeric(verbose) && isreal(verbose) && ...
    isscalar(verbose) && isfinite(verbose) && any(verbose == [0,1]);
if ~(validLogical || validNumeric)
    error('ipm:GaugeLabGroupV4Verbose', ...
        'verbose must be logical or numeric 0/1.');
end
verbose = logical(verbose);
end

function status = classify_group_exception(exception)
identifier = char(exception.identifier);
if is_gauge_design_identifier(identifier)
    status = 'failed_gauge_design';
elseif is_mesh_grid_identifier(identifier)
    status = 'failed_grid_gate';
elseif is_numerical_identifier(identifier)
    status = 'failed_numerical_gate';
else
    status = 'failed_infrastructure';
end
end

function tf = is_gauge_design_identifier(identifier)
prefixes = {'ipm:Degenerate','ipm:OmegaGaugeWindow', ...
    'ipm:OmegaGaugeBulk','ipm:TemplateGauge', ...
    'ipm:AnchorWallGauge','ipm:TransportAnchor', ...
    'ipm:BadCOmegaGauge','ipm:BadLengthGauge', ...
    'ipm:BadScalingContract','ipm:SymmetryLengthGauge', ...
    'ipm:RetiredCOmegaGauge','ipm:OuterAnchorGeometry', ...
    'ipm:GaugeLabUnregisteredGauge','ipm:GaugeLabSupportKind'};
tf = any(startsWith(identifier,prefixes));
end

function tf = is_mesh_grid_identifier(identifier)
prefixes = {'ipm:GaugeLabMeshGate','ipm:GaugeLabResolution', ...
    'ipm:GaugeLabFixedMesh','ipm:AdaptiveAxis', ...
    'ipm:AdaptiveGrid','ipm:AdaptiveLevel', ...
    'ipm:AdaptiveMonitor','ipm:CustomGrid', ...
    'ipm:HighOrderGrid','ipm:HighOrderQuadrature', ...
    'ipm:HighOrderRemesh','ipm:SixthOrderGrid', ...
    'ipm:SixthOrderQuadrature','ipm:FiniteDifference', ...
    'ipm:MinimumLevelPoints','ipm:SymmetryGrid'};
tf = any(startsWith(identifier,prefixes));
end

function tf = is_numerical_identifier(identifier)
prefixes = {'ipm:NonFinite','ipm:HighOrderPoisson', ...
    'ipm:AnisotropicPoisson','ipm:Poisson','ipm:Weno', ...
    'ipm:TimeIntegrator','ipm:BadTimeStep', ...
    'ipm:ConservativeRemesh'};
tf = any(startsWith(identifier,prefixes));
end

function append_manifest(fileName,record)
fileId = fopen(fileName,'a');
if fileId < 0
    warning('ipm:GaugeLabGroupV4Manifest', ...
        'Could not append %s.',fileName);
    return;
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function value = utc_stamp()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
