function report = ipm_gaugelab_compare_cl_tournament_cfl(firstInput,secondInput)
%IPM_GAUGELAB_COMPARE_CL_TOURNAMENT_CFL Compare two c_l CFL artifacts.
%   REPORT = IPM_GAUGELAB_COMPARE_CL_TOURNAMENT_CFL(FIRST,SECOND) is a
%   read-only postprocessor. FIRST and SECOND may each name a
%   cl_tournament_summary.mat file, its containing directory, or one
%   candidate result MAT file. Tournament inputs are matched by
%   scaling.lengthGauge; result inputs compare their single common gauge.
%
%   Every matched pair must share a physical endpoint before its terminal
%   fields are compared in both interpolation directions with
%   ipm.output.compare. The report also retains endpoint rates, the fixed
%   canonical-tail diagnostics, accepted-step/wall-time data, and a
%   distinction between the unchanged evolution contract and the stronger
%   gauge-contract/phase evidence fields added after older campaigns.
%   This function advances no PDE and writes no file.

narginchk(2,2);
laboratoryDirectory = fileparts(mfilename('fullpath'));
researchDirectory = fileparts(laboratoryDirectory);
projectDirectory = fileparts(researchDirectory);
addpath(projectDirectory,laboratoryDirectory);

first = read_campaign_input(firstInput,'first');
second = read_campaign_input(secondInput,'second');
specifications = ipm_gaugelab_length_candidate_specifications();
[candidateNames,firstOnly,secondOnly] = shared_candidates(first,second);
if isempty(candidateNames)
    error('ipm:GaugeLabCLCflNoCommonCandidate', ...
        'The two inputs contain no common length-gauge candidate.');
end
comparisonWindow = common_comparison_window(first,second);

records = repmat(empty_record(),numel(candidateNames),1);
for candidateIndex = 1:numel(candidateNames)
    name = candidateNames{candidateIndex};
    firstRun = find_run(first,name);
    secondRun = find_run(second,name);
    firstResult = ipm.output.validate(firstRun.resultFile);
    secondResult = ipm.output.validate(secondRun.resultFile);
    specification = find_specification(specifications,name);
    records(candidateIndex) = compare_candidate( ...
        name,firstRun,secondRun,firstResult,secondResult, ...
        specification,comparisonWindow,first,second);
end

report = struct( ...
    'schemaVersion',1, ...
    'kind','q256_cl_tournament_cross_cfl_read_only', ...
    'generatedAt',datetime('now','TimeZone','local'), ...
    'first',campaign_description(first), ...
    'second',campaign_description(second), ...
    'comparisonWindow',comparisonWindow, ...
    'candidateNames',{candidateNames}, ...
    'firstOnlyCandidates',{firstOnly}, ...
    'secondOnlyCandidates',{secondOnly}, ...
    'sameCandidateSet',isempty(firstOnly) && isempty(secondOnly), ...
    'records',{records}, ...
    'summary',summarize_records(records));
print_report(report);
end

function campaign = read_campaign_input(inputValue,label)
pathName = normalize_input_path(inputValue,label);
if isfolder(pathName)
    pathName = fullfile(pathName,'cl_tournament_summary.mat');
end
if ~isfile(pathName)
    error('ipm:GaugeLabCLCflInputMissing', ...
        '%s input does not exist: %s.',label,pathName);
end
loaded = load(pathName);
if isfield(loaded,'products') && isstruct(loaded.products) && ...
        isscalar(loaded.products)
    products = loaded.products;
    if ~isfield(products,'runs') || isempty(products.runs)
        error('ipm:GaugeLabCLCflSummaryRuns', ...
            'Tournament summary has no candidate runs: %s.',pathName);
    end
    runs = normalize_summary_runs(products.runs,pathName);
    protocol = struct();
    status = '';
    if isfield(products,'protocol') && isstruct(products.protocol) && ...
            isscalar(products.protocol)
        protocol = products.protocol;
    end
    if isfield(products,'status')
        status = scalar_text(products.status,'products.status');
    end
    campaign = struct('inputPath',pathName,'inputKind','tournament_summary', ...
        'status',status,'protocol',protocol,'runs',{runs});
elseif isfield(loaded,'result') && isstruct(loaded.result) && ...
        isscalar(loaded.result)
    result = ipm.output.validate(loaded.result);
    run = empty_source_run();
    run.lengthGauge = result.config.scaling.lengthGauge;
    run.resultFile = pathName;
    campaign = struct('inputPath',pathName,'inputKind','single_result', ...
        'status',result.state.stopReason,'protocol',struct(),'runs',{run});
else
    error('ipm:GaugeLabCLCflInputType', ...
        '%s input must contain scalar variable products or result: %s.', ...
        label,pathName);
end
assert_unique_candidates(campaign.runs,pathName);
end

function pathName = normalize_input_path(value,label)
if isstring(value)
    if ~isscalar(value) || ismissing(value)
        error('ipm:GaugeLabCLCflInputText', ...
            '%s input must be scalar text.',label);
    end
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(strtrim(value))
    error('ipm:GaugeLabCLCflInputText', ...
        '%s input must be nonempty scalar text.',label);
end
pathName = strtrim(value);
end

function runs = normalize_summary_runs(sourceRuns,summaryFile)
runs = repmat(empty_source_run(),numel(sourceRuns),1);
for index = 1:numel(sourceRuns)
    source = sourceRuns(index);
    if ~isfield(source,'lengthGauge')
        error('ipm:GaugeLabCLCflRunGauge', ...
            'A summary run lacks lengthGauge: %s.',summaryFile);
    end
    runs(index).lengthGauge = scalar_text( ...
        source.lengthGauge,'run.lengthGauge');
    runs(index).resultFile = resolve_result_file( ...
        source,summaryFile,runs(index).lengthGauge);
    runs(index).elapsedSeconds = optional_numeric_scalar( ...
        source,'elapsedSeconds',NaN);
    runs(index).acceptedSteps = optional_numeric_scalar( ...
        source,'acceptedSteps',NaN);
    runs(index).secondsPerStep = optional_numeric_scalar( ...
        source,'secondsPerStep',NaN);
    runs(index).recordedExactContractPassed = optional_logical_scalar( ...
        source,'exactContractPassed');
    if isfield(source,'exactEvidence') && isstruct(source.exactEvidence) && ...
            isscalar(source.exactEvidence)
        runs(index).recordedExactEvidenceFields = ...
            sort(fieldnames(source.exactEvidence));
    end
end
end

function resultFile = resolve_result_file(source,summaryFile,candidate)
candidates = {};
if isfield(source,'resultFile')
    candidates{end+1} = source.resultFile;
end
if isfield(source,'requestedResultFile')
    candidates{end+1} = source.requestedResultFile;
end
summaryDirectory = fileparts(summaryFile);
candidates{end+1} = fullfile(summaryDirectory,candidate,'result.mat');
for index = 1:numel(candidates)
    value = candidates{index};
    if isstring(value)
        if ~isscalar(value) || ismissing(value)
            continue;
        end
        value = char(value);
    end
    if ~ischar(value) || ~isrow(value) || isempty(strtrim(value))
        continue;
    end
    value = strtrim(value);
    trials = {value};
    if ~startsWith(value,filesep)
        trials{end+1} = fullfile(summaryDirectory,value); %#ok<AGROW>
    end
    for trialIndex = 1:numel(trials)
        if isfile(trials{trialIndex})
            resultFile = trials{trialIndex};
            return;
        end
    end
end
error('ipm:GaugeLabCLCflResultMissing', ...
    'Cannot locate result for candidate %s from %s.',candidate,summaryFile);
end

function assert_unique_candidates(runs,pathName)
names = {runs.lengthGauge};
if numel(unique(names)) ~= numel(names)
    error('ipm:GaugeLabCLCflDuplicateCandidate', ...
        'Input contains duplicate length-gauge candidates: %s.',pathName);
end
end

function [shared,firstOnly,secondOnly] = shared_candidates(first,second)
firstNames = {first.runs.lengthGauge};
secondNames = {second.runs.lengthGauge};
shared = firstNames(ismember(firstNames,secondNames));
firstOnly = firstNames(~ismember(firstNames,secondNames));
secondOnly = secondNames(~ismember(secondNames,firstNames));
end

function window = common_comparison_window(first,second)
firstWindow = protocol_value(first.protocol,'comparisonWindow',[]);
secondWindow = protocol_value(second.protocol,'comparisonWindow',[]);
if isempty(firstWindow) && isempty(secondWindow)
    window = [-2,2,2];
elseif isempty(firstWindow)
    window = secondWindow;
elseif isempty(secondWindow)
    window = firstWindow;
elseif isequaln(firstWindow,secondWindow)
    window = firstWindow;
else
    error('ipm:GaugeLabCLCflWindowMismatch', ...
        'Tournament comparison windows differ between the two inputs.');
end
validateattributes(window,{'numeric'}, ...
    {'vector','numel',3,'real','finite'},mfilename,'comparisonWindow');
window = window(:)';
end

function run = find_run(campaign,name)
index = find(strcmp({campaign.runs.lengthGauge},name),1,'first');
if isempty(index)
    error('ipm:GaugeLabCLCflCandidateLookup', ...
        'Candidate %s is absent from %s.',name,campaign.inputPath);
end
run = campaign.runs(index);
end

function specification = find_specification(specifications,name)
index = find(strcmp({specifications.lengthGauge},name),1,'first');
if isempty(index)
    error('ipm:GaugeLabCLCflUnregisteredGauge', ...
        'Length gauge %s is not in the current registry.',name);
end
specification = specifications(index);
end

function record = compare_candidate(name,firstRun,secondRun, ...
        firstResult,secondResult,specification,window,firstCampaign, ...
        secondCampaign)
if ~strcmp(firstResult.config.scaling.lengthGauge,name) || ...
        ~strcmp(secondResult.config.scaling.lengthGauge,name)
    error('ipm:GaugeLabCLCflResultGaugeMismatch', ...
        'Saved result lengthGauge does not match candidate %s.',name);
end
record = empty_record();
record.lengthGauge = name;
record.firstResultFile = firstRun.resultFile;
record.secondResultFile = secondRun.resultFile;
record.endpoint = compare_endpoints(firstResult,secondResult);
record.firstRun = run_statistics(firstResult,firstRun);
record.secondRun = run_statistics(secondResult,secondRun);
if record.endpoint.samePhysicalEndpoint
    record.physicalFields = compare_physical_fields( ...
        firstResult,secondResult,window, ...
        common_covariance_limits(firstCampaign,secondCampaign));
else
    record.physicalFields.errorIdentifier = ...
        'ipm:GaugeLabCLCflPhysicalEndpointMismatch';
    record.physicalFields.errorMessage = ...
        'Terminal fields were not compared because physical endpoints differ.';
end
record.endpointRates = compare_endpoint_rates(firstResult,secondResult);
record.tailRates = compare_tail_rates(firstResult,secondResult);
record.firstContract = contract_audit( ...
        firstResult,firstRun,specification);
record.secondContract = contract_audit( ...
        secondResult,secondRun,specification);
record.contractComparison = compare_contracts( ...
        firstResult,secondResult,record.firstContract, ...
        record.secondContract);
end

function endpoint = compare_endpoints(first,second)
firstTime = first.state.physicalTime;
secondTime = second.state.physicalTime;
firstTarget = first.config.time.physicalFinalTime;
secondTarget = second.config.time.physicalFinalTime;
tolerance = 1e-10*max([1,abs(firstTime),abs(secondTime), ...
    abs(firstTarget),abs(secondTarget)]);
endpoint = struct( ...
    'firstPhysicalTime',firstTime, ...
    'secondPhysicalTime',secondTime, ...
    'signedPhysicalTimeDifference',secondTime-firstTime, ...
    'firstConfiguredTarget',firstTarget, ...
    'secondConfiguredTarget',secondTarget, ...
    'tolerance',tolerance, ...
    'sameConfiguredTarget',isfinite(firstTarget) && ...
        isfinite(secondTarget) && abs(secondTarget-firstTarget) <= tolerance, ...
    'firstReachedTarget',isfinite(firstTime) && isfinite(firstTarget) && ...
        abs(firstTime-firstTarget) <= tolerance, ...
    'secondReachedTarget',isfinite(secondTime) && isfinite(secondTarget) && ...
        abs(secondTime-secondTarget) <= tolerance, ...
    'samePhysicalEndpoint',isfinite(firstTime) && isfinite(secondTime) && ...
        abs(secondTime-firstTime) <= tolerance);
end

function statistics = run_statistics(result,run)
common = result.history.common;
statistics = struct( ...
    'cfl',result.config.time.cfl, ...
    'maximumDt',result.config.time.maxDt, ...
    'acceptedSteps',result.state.steps, ...
    'recordedAcceptedSteps',run.acceptedSteps, ...
    'elapsedSeconds',run.elapsedSeconds, ...
    'secondsPerStep',run.secondsPerStep, ...
    'canonicalTime',result.state.canonicalTime, ...
    'physicalTime',result.state.physicalTime, ...
    'stopReason',result.state.stopReason, ...
    'historyRecords',numel(common.c_l), ...
    'maximumRealizedCfl',finite_max(common,'realizedCfl'), ...
    'cflLimitedRecords',count_limiter(common,'cfl'));
if ~isfinite(statistics.secondsPerStep) && ...
        isfinite(statistics.elapsedSeconds) && statistics.acceptedSteps > 0
    statistics.secondsPerStep = ...
        statistics.elapsedSeconds/statistics.acceptedSteps;
end
end

function comparison = compare_physical_fields(first,second,window,limits)
comparison = empty_field_comparison();
try
    forward = ipm.output.compare(first,second,window);
    reverse = ipm.output.compare(second,first,window);
    firstRhoX = first.history.common.physicalRhoXInf(end);
    secondRhoX = second.history.common.physicalRhoXInf(end);
    forward.physicalRhoXRelativeDifference = ...
        directional_relative_difference(firstRhoX,secondRhoX);
    reverse.physicalRhoXRelativeDifference = ...
        directional_relative_difference(secondRhoX,firstRhoX);
    forward.physicalTimeDifference = ...
        second.state.physicalTime-first.state.physicalTime;
    reverse.physicalTimeDifference = ...
        first.state.physicalTime-second.state.physicalTime;
    firstWallWidth = common_wall_half_maximum_width(first);
    secondWallWidth = common_wall_half_maximum_width(second);
    forward.commonWallWidthRelativeDifference = ...
        directional_relative_difference(firstWallWidth,secondWallWidth);
    reverse.commonWallWidthRelativeDifference = ...
        directional_relative_difference(secondWallWidth,firstWallWidth);
    names = physical_metric_names();
    symmetric = struct();
    for index = 1:numel(names)
        metric = names{index};
        symmetric.(metric) = max(abs([ ...
            forward.(metric),reverse.(metric)]));
    end
    comparison.available = true;
    comparison.forward = forward;
    comparison.reverse = reverse;
    comparison.symmetricWorst = symmetric;
    comparison.limitsAvailable = ~isempty(fieldnames(limits));
    if comparison.limitsAvailable
        [comparison.withinTournamentLimits, ...
            comparison.maximumNormalizedLimitUsage] = ...
            covariance_limit_check(symmetric,limits);
    end
catch exception
    comparison.errorIdentifier = exception.identifier;
    comparison.errorMessage = exception.message;
end
end

function limits = common_covariance_limits(first,second)
firstLimits = protocol_value( ...
    first.protocol,'physicalCovarianceLimits',struct());
secondLimits = protocol_value( ...
    second.protocol,'physicalCovarianceLimits',struct());
if ~isstruct(firstLimits) || ~isscalar(firstLimits)
    firstLimits = struct();
end
if ~isstruct(secondLimits) || ~isscalar(secondLimits)
    secondLimits = struct();
end
if isempty(fieldnames(firstLimits))
    limits = secondLimits;
elseif isempty(fieldnames(secondLimits))
    limits = firstLimits;
elseif isequaln(firstLimits,secondLimits)
    limits = firstLimits;
else
    limits = struct();
end
end

function [passed,maximumUsage] = covariance_limit_check(values,limits)
mapping = { ...
    'rhoRelativeL2','rhoRelativeL2'; ...
    'omegaRelativeL2','omegaRelativeL2'; ...
    'rhoAbsoluteInf','rhoAbsoluteInf'; ...
    'omegaAbsoluteInf','omegaAbsoluteInf'; ...
    'labPeakShift','maximumAbsoluteLabPeakShift'; ...
    'physicalTimeDifference','maximumAbsolutePhysicalTimeDifference'; ...
    'physicalRhoXRelativeDifference','physicalRhoXRelativeDifference'; ...
    'wallPeakRelativeDifference','wallPeakRelativeDifference'; ...
    'commonWallWidthRelativeDifference','wallWidthRelativeDifference'};
usage = NaN(size(mapping,1),1);
for index = 1:size(mapping,1)
    if ~isfield(values,mapping{index,1}) || ...
            ~isfield(limits,mapping{index,2})
        passed = false;
        maximumUsage = Inf;
        return;
    end
    usage(index) = abs(values.(mapping{index,1})) / ...
        limits.(mapping{index,2});
end
passed = all(isfinite(usage)) && all(usage <= 1);
maximumUsage = max(usage);
end

function rates = compare_endpoint_rates(first,second)
names = {'c_l','c_omega'};
rates = struct();
for index = 1:numel(names)
    name = names{index};
    rates.(name) = compare_scalar( ...
        first.history.common.(name)(end), ...
        second.history.common.(name)(end));
end
firstCL = rates.c_l.first;
secondCL = rates.c_l.second;
firstCOmega = rates.c_omega.first;
secondCOmega = rates.c_omega.second;
rates.cOmegaOverCL = compare_scalar( ...
    guarded_ratio(firstCOmega,firstCL), ...
    guarded_ratio(secondCOmega,secondCL));
rates.cLMinusCOmega = compare_scalar( ...
    firstCL-firstCOmega,secondCL-secondCOmega);
rates.cLMinusCOmegaOverCL = compare_scalar( ...
    guarded_ratio(firstCL-firstCOmega,firstCL), ...
    guarded_ratio(secondCL-secondCOmega,secondCL));
rates.physicalRhoXInf = compare_scalar( ...
    first.history.common.physicalRhoXInf(end), ...
    second.history.common.physicalRhoXInf(end));
end

function pair = compare_scalar(first,second)
pair = struct('first',first,'second',second, ...
    'signedDifference',second-first, ...
    'absoluteDifference',abs(second-first), ...
    'signedRelativeDifference',relative_difference(first,second), ...
    'absoluteRelativeDifference',abs(relative_difference(first,second)));
end

function tails = compare_tail_rates(first,second)
firstDiagnostic = first.fit.gaugeRateConvergence;
secondDiagnostic = second.fit.gaugeRateConvergence;
sameWindowFractions = isequaln( ...
    firstDiagnostic.windowFractions,secondDiagnostic.windowFractions);
tails = struct( ...
    'firstValid',firstDiagnostic.valid, ...
    'secondValid',secondDiagnostic.valid, ...
    'sameWindowFractions',sameWindowFractions, ...
    'firstWindowFractions',firstDiagnostic.windowFractions, ...
    'secondWindowFractions',secondDiagnostic.windowFractions, ...
    'cL',compare_tail_series(firstDiagnostic,secondDiagnostic,'cL', ...
        sameWindowFractions), ...
    'cOmega',compare_tail_series( ...
        firstDiagnostic,secondDiagnostic,'cOmega',sameWindowFractions), ...
    'cOmegaOverCL',compare_tail_series( ...
        firstDiagnostic,secondDiagnostic,'cOmegaOverCL', ...
        sameWindowFractions), ...
    'cLMinusCOmegaOverCL',compare_tail_series( ...
        firstDiagnostic,secondDiagnostic,'cLMinusCOmegaOverCL', ...
        sameWindowFractions));
tails.firstWorstCLCOmegaTrend = NaN;
tails.secondWorstCLCOmegaTrend = NaN;
tails.signedWorstTrendDifference = NaN;
tails.absoluteWorstTrendDifference = NaN;
if tails.cL.valid && tails.cOmega.valid
    tails.firstWorstCLCOmegaTrend = max([ ...
        tails.cL.firstMaximumAbsoluteRelativeTrend, ...
        tails.cOmega.firstMaximumAbsoluteRelativeTrend]);
    tails.secondWorstCLCOmegaTrend = max([ ...
        tails.cL.secondMaximumAbsoluteRelativeTrend, ...
        tails.cOmega.secondMaximumAbsoluteRelativeTrend]);
    tails.signedWorstTrendDifference = ...
        tails.secondWorstCLCOmegaTrend-tails.firstWorstCLCOmegaTrend;
    tails.absoluteWorstTrendDifference = ...
        abs(tails.signedWorstTrendDifference);
end
end

function comparison = compare_tail_series(first,second,name,sameWindows)
comparison = empty_tail_series();
if ~isfield(first.seriesSummary,name) || ...
        ~isfield(second.seriesSummary,name)
    return;
end
firstSeries = first.seriesSummary.(name);
secondSeries = second.seriesSummary.(name);
required = {'maximumAbsoluteRelativeTrend','relativeWindowMeanSpread', ...
    'maximumRelativeDetrendedRms','windowRelativeTrends', ...
    'windowWeightedMeans','windowRelativeDetrendedRms','stable'};
if ~all(isfield(firstSeries,required)) || ...
        ~all(isfield(secondSeries,required))
    return;
end
sameArrayShapes = isequal(size(firstSeries.windowRelativeTrends), ...
        size(secondSeries.windowRelativeTrends)) && ...
    isequal(size(firstSeries.windowWeightedMeans), ...
        size(secondSeries.windowWeightedMeans)) && ...
    isequal(size(firstSeries.windowRelativeDetrendedRms), ...
        size(secondSeries.windowRelativeDetrendedRms));
comparison.valid = sameWindows && sameArrayShapes && ...
    all(isfinite([ ...
    firstSeries.maximumAbsoluteRelativeTrend, ...
    secondSeries.maximumAbsoluteRelativeTrend, ...
    firstSeries.relativeWindowMeanSpread, ...
    secondSeries.relativeWindowMeanSpread, ...
    firstSeries.maximumRelativeDetrendedRms, ...
    secondSeries.maximumRelativeDetrendedRms])) && ...
    all(isfinite(firstSeries.windowRelativeTrends(:))) && ...
    all(isfinite(secondSeries.windowRelativeTrends(:))) && ...
    all(isfinite(firstSeries.windowWeightedMeans(:))) && ...
    all(isfinite(secondSeries.windowWeightedMeans(:))) && ...
    all(isfinite(firstSeries.windowRelativeDetrendedRms(:))) && ...
    all(isfinite(secondSeries.windowRelativeDetrendedRms(:)));
comparison.firstStable = firstSeries.stable;
comparison.secondStable = secondSeries.stable;
comparison.firstMaximumAbsoluteRelativeTrend = ...
    firstSeries.maximumAbsoluteRelativeTrend;
comparison.secondMaximumAbsoluteRelativeTrend = ...
    secondSeries.maximumAbsoluteRelativeTrend;
comparison.firstRelativeWindowMeanSpread = ...
    firstSeries.relativeWindowMeanSpread;
comparison.secondRelativeWindowMeanSpread = ...
    secondSeries.relativeWindowMeanSpread;
comparison.firstMaximumRelativeDetrendedRms = ...
    firstSeries.maximumRelativeDetrendedRms;
comparison.secondMaximumRelativeDetrendedRms = ...
    secondSeries.maximumRelativeDetrendedRms;
comparison.firstWindowRelativeTrends = firstSeries.windowRelativeTrends;
comparison.secondWindowRelativeTrends = secondSeries.windowRelativeTrends;
comparison.firstWindowWeightedMeans = firstSeries.windowWeightedMeans;
comparison.secondWindowWeightedMeans = secondSeries.windowWeightedMeans;
comparison.firstWindowRelativeDetrendedRms = ...
    firstSeries.windowRelativeDetrendedRms;
comparison.secondWindowRelativeDetrendedRms = ...
    secondSeries.windowRelativeDetrendedRms;
if ~comparison.valid
    return;
end
comparison.signedMaximumTrendDifference = ...
    secondSeries.maximumAbsoluteRelativeTrend - ...
    firstSeries.maximumAbsoluteRelativeTrend;
comparison.absoluteMaximumTrendDifference = ...
    abs(comparison.signedMaximumTrendDifference);
comparison.signedWindowMeanSpreadDifference = ...
    secondSeries.relativeWindowMeanSpread - ...
    firstSeries.relativeWindowMeanSpread;
comparison.signedMaximumDetrendedRmsDifference = ...
    secondSeries.maximumRelativeDetrendedRms - ...
    firstSeries.maximumRelativeDetrendedRms;
comparison.windowRelativeTrendDifferences = ...
    secondSeries.windowRelativeTrends-firstSeries.windowRelativeTrends;
comparison.windowWeightedMeanDifferences = ...
    secondSeries.windowWeightedMeans-firstSeries.windowWeightedMeans;
end

function audit = contract_audit(result,run,specification)
common = result.history.common;
gauge = result.history.gauge;
scaling = result.config.scaling;
retired = retired_fields();
count = numel(common.c_l);
audit = empty_contract_audit();
audit.recordedAuditPassed = run.recordedExactContractPassed;
audit.recordedAuditEvidenceFields = run.recordedExactEvidenceFields;
audit.configSchemaVersion = result.config.schemaVersion;
[audit.gaugeContractFields,audit.lengthContractFields, ...
    audit.amplitudeContractFields,audit.feedbackContractFields] = ...
    metadata_contract_field_sets(result.metadata);
audit.retiredFieldsAbsent = ...
    isempty(intersect(fieldnames(scaling),retired));
audit.configCorePassed = result.config.schemaVersion == 4 && ...
    strcmp(scaling.scalingContract,'exact_gauge_no_feedback_v1') && ...
    strcmp(scaling.lengthGauge,specification.lengthGauge) && ...
    strcmp(scaling.cOmegaGauge,'gradient_energy') && ...
    scaling.lengthScaleGain == 1 && scaling.widthGaugeGain == 0 && ...
    scaling.omegaGaugeGain == 0 && scaling.travelingWaveGain == 0 && ...
    audit.retiredFieldsAbsent;
requiredCommon = {'timeSpeed','c_l','canonicalCL','c_omega', ...
    'canonicalCOmega'};
requiredGauge = {'c_lNominal','canonicalCLNominal', ...
    'lengthScaleGain','widthControlMode','widthCorrection', ...
    'canonicalWidthCorrection','lengthGaugeStrain', ...
    'lengthGaugeResidual','widthRateScale','omegaGaugeResidual'};
audit.coreHistoryComplete = has_finite_equal_length_fields( ...
    common,requiredCommon,count) && ...
    has_finite_equal_length_fields(gauge,requiredGauge,count);
audit.directClockPassed = audit.coreHistoryComplete && ...
    all(common.timeSpeed == 1);
audit.directRateIdentitiesPassed = audit.coreHistoryComplete && ...
    isequal(common.c_l,common.canonicalCL) && ...
    isequal(common.c_omega,common.canonicalCOmega) && ...
    isequal(common.c_l,gauge.c_lNominal) && ...
    isequal(common.canonicalCL,gauge.canonicalCLNominal);
audit.noFeedbackHistoryPassed = audit.coreHistoryComplete && ...
    all(gauge.lengthScaleGain == 1) && ...
    all(gauge.widthControlMode == 0) && ...
    all(gauge.widthCorrection == 0) && ...
    all(gauge.canonicalWidthCorrection == 0);
audit.fixedMeshPassed = isfield(result,'grid') && ...
    isstruct(result.grid) && isscalar(result.grid) && ...
    isfield(result.grid,'remeshCount') && result.grid.remeshCount == 0 && ...
    isfield(result.history,'mesh') && ...
    isfield(result.history.mesh,'remeshCount') && ...
    all(result.history.mesh.remeshCount == 0);

[audit.metadataCorePassed,audit.metadataStrengthenedPassed, ...
    audit.gaugeContractSchemaVersion,audit.missingStrengthenedFields, ...
    audit.mismatchedStrengthenedFields] = ...
    metadata_contract_audit(result.metadata,specification);
[audit.candidateDiagnosticsAvailable, ...
    audit.missingCandidateDiagnosticFields] = ...
    candidate_diagnostic_audit(gauge,specification.lengthGauge, ...
        count);
[audit.residualFieldsPassed, ...
    audit.maximumNormalizedLengthGaugeResidual, ...
    audit.maximumOmegaGaugeResidual] = ...
    residual_field_audit(gauge,count);
audit.currentStrengthenedFieldContractPassed = ...
    audit.configCorePassed && audit.metadataCorePassed && ...
    audit.metadataStrengthenedPassed && audit.directClockPassed && ...
    audit.directRateIdentitiesPassed && audit.noFeedbackHistoryPassed && ...
    audit.fixedMeshPassed && audit.candidateDiagnosticsAvailable && ...
    audit.residualFieldsPassed;
if audit.currentStrengthenedFieldContractPassed
    audit.evidenceClass = 'strengthened_current';
elseif audit.configCorePassed && audit.metadataCorePassed && ...
        audit.directClockPassed && audit.directRateIdentitiesPassed && ...
        audit.noFeedbackHistoryPassed && audit.fixedMeshPassed && ...
        audit.residualFieldsPassed
    audit.evidenceClass = 'legacy_core_only';
else
    audit.evidenceClass = 'invalid_or_incomplete_core';
end
audit.recordedAuditComparableToCurrent = ...
    islogical(audit.recordedAuditPassed) && ...
    audit.metadataStrengthenedPassed;
audit.recordedAuditAgreesWithCurrent = ...
    audit.recordedAuditComparableToCurrent && ...
    audit.recordedAuditPassed == ...
        audit.currentStrengthenedFieldContractPassed;
end

function [corePassed,strengthenedPassed,schemaVersion,missing,mismatch] = ...
        metadata_contract_audit(metadata,specification)
corePassed = false;
strengthenedPassed = false;
schemaVersion = NaN;
missing = {};
mismatch = {};
if ~isstruct(metadata) || ~isscalar(metadata) || ...
        ~isfield(metadata,'gaugeContract') || ...
        ~isstruct(metadata.gaugeContract) || ...
        ~isscalar(metadata.gaugeContract)
    missing{end+1} = 'metadata.gaugeContract';
    return;
end
contract = metadata.gaugeContract;
if isfield(contract,'schemaVersion') && isnumeric(contract.schemaVersion) && ...
        isscalar(contract.schemaVersion)
    schemaVersion = contract.schemaVersion;
end
requiredCore = {'clock','timeSpeed','feedback','length','amplitude'};
for index = 1:numel(requiredCore)
    if ~isfield(contract,requiredCore{index})
        missing{end+1} = ['gaugeContract.',requiredCore{index}]; %#ok<AGROW>
    end
end
if ~isempty(missing)
    return;
end
lengthContract = contract.length;
amplitudeContract = contract.amplitude;
feedback = contract.feedback;
if ~isstruct(lengthContract) || ~isscalar(lengthContract) || ...
        ~isstruct(amplitudeContract) || ~isscalar(amplitudeContract) || ...
        ~isstruct(feedback) || ~isscalar(feedback)
    mismatch{end+1} = 'gaugeContract.core_substructure_type';
    return;
end
coreNamesPresent = all(isfield(lengthContract,{'name','formula'})) && ...
    isfield(amplitudeContract,'name') && isfield(feedback,'rateLimiter');
if ~coreNamesPresent
    mismatch{end+1} = 'gaugeContract.core_substructure_fields';
    return;
end
corePassed = text_matches(contract.clock,'canonical_tau_direct') && ...
    isequal(contract.timeSpeed,1) && ...
    text_matches(lengthContract.name,specification.lengthGauge) && ...
    text_matches(lengthContract.formula,specification.formula) && ...
    text_matches(amplitudeContract.name,'gradient_energy') && ...
    text_matches(feedback.rateLimiter,'absent');

strengthenedNames = {'observable','evaluation', ...
    'registeredParameters','phaseInterpretation'};
for index = 1:numel(strengthenedNames)
    name = strengthenedNames{index};
    if ~isfield(lengthContract,name)
        missing{end+1} = ['gaugeContract.length.',name]; %#ok<AGROW>
    end
end
amplitudeStrengthenedNames = {'formula','observable','evaluation'};
for index = 1:numel(amplitudeStrengthenedNames)
    name = amplitudeStrengthenedNames{index};
    if ~isfield(amplitudeContract,name)
        missing{end+1} = ['gaugeContract.amplitude.',name]; %#ok<AGROW>
    end
end
if ~isfinite(schemaVersion) || schemaVersion ~= 2
    mismatch{end+1} = 'gaugeContract.schemaVersion~=2';
end
if isfield(lengthContract,'observable') && ...
        ~text_matches(lengthContract.observable,specification.observable)
    mismatch{end+1} = 'gaugeContract.length.observable';
end
if isfield(lengthContract,'evaluation') && ...
        ~text_matches(lengthContract.evaluation,specification.evaluation)
    mismatch{end+1} = 'gaugeContract.length.evaluation';
end
if isfield(lengthContract,'registeredParameters')
    parametersMatch = isstruct(lengthContract.registeredParameters) && ...
        isscalar(lengthContract.registeredParameters) && ...
        isequaln(orderfields(lengthContract.registeredParameters), ...
            orderfields(specification.registeredParameters));
    if ~parametersMatch
        mismatch{end+1} = ...
            'gaugeContract.length.registeredParameters';
    end
end
if isfield(lengthContract,'phaseInterpretation') && ...
        ~text_matches(lengthContract.phaseInterpretation, ...
            expected_phase_interpretation(specification.lengthGauge))
    mismatch{end+1} = 'gaugeContract.length.phaseInterpretation';
end
expectedAmplitudeFormula = [ ...
    'c_omega=-sum(w*(R_X*B_X+R_Y*B_Y))/' ...
    'sum(w*(R_X^2+R_Y^2))'];
if isfield(amplitudeContract,'formula') && ...
        ~text_matches(amplitudeContract.formula,expectedAmplitudeFormula)
    mismatch{end+1} = 'gaugeContract.amplitude.formula';
end
if isfield(amplitudeContract,'observable') && ...
        ~text_matches(amplitudeContract.observable, ...
            'global_discrete_gradient_energy')
    mismatch{end+1} = 'gaugeContract.amplitude.observable';
end
if isfield(amplitudeContract,'evaluation') && ...
        ~text_matches(amplitudeContract.evaluation,'fixed_grid_quadrature')
    mismatch{end+1} = 'gaugeContract.amplitude.evaluation';
end
strengthenedPassed = corePassed && isempty(missing) && isempty(mismatch);
end

function [contractFields,lengthFields,amplitudeFields,feedbackFields] = ...
        metadata_contract_field_sets(metadata)
contractFields = {};
lengthFields = {};
amplitudeFields = {};
feedbackFields = {};
if ~isstruct(metadata) || ~isscalar(metadata) || ...
        ~isfield(metadata,'gaugeContract') || ...
        ~isstruct(metadata.gaugeContract) || ...
        ~isscalar(metadata.gaugeContract)
    return;
end
contract = metadata.gaugeContract;
contractFields = sort(fieldnames(contract));
if isfield(contract,'length') && isstruct(contract.length) && ...
        isscalar(contract.length)
    lengthFields = sort(fieldnames(contract.length));
end
if isfield(contract,'amplitude') && isstruct(contract.amplitude) && ...
        isscalar(contract.amplitude)
    amplitudeFields = sort(fieldnames(contract.amplitude));
end
if isfield(contract,'feedback') && isstruct(contract.feedback) && ...
        isscalar(contract.feedback)
    feedbackFields = sort(fieldnames(contract.feedback));
end
end

function value = expected_phase_interpretation(lengthGauge)
if strcmp(lengthGauge,'omega_peak_location')
    value = 'algebraic_candidate_with_recorded_full_phase_defect';
else
    value = 'not_applicable';
end
end

function [available,missing] = ...
        candidate_diagnostic_audit(gauge,lengthGauge,count)
required = {};
if strcmp(lengthGauge,'omega_peak_location')
    required = {'peakLocationRhoXX','peakLocationRhoXXScale', ...
        'peakLocationPhaseDefect','peakLocationResponseCondition', ...
        'peakLocationFullPhaseResidual', ...
        'peakLocationNormalizedFullPhaseResidual'};
elseif strcmp(lengthGauge,'wall_density_width')
    required = {'wallDensityLowerSlope','wallDensityUpperSlope', ...
        'wallDensityLowerCondition','wallDensityUpperCondition', ...
        'wallDensityLowerBracket','wallDensityUpperBracket'};
end
missing = {};
for index = 1:numel(required)
    name = required{index};
    if ~isfield(gauge,name) || ~isnumeric(gauge.(name)) || ...
            ~isreal(gauge.(name)) || numel(gauge.(name)) ~= count || ...
            any(~isfinite(gauge.(name)),'all')
        missing{end+1} = ['history.gauge.',name]; %#ok<AGROW>
    end
end
available = isempty(missing);
end

function [passed,maximumLengthResidual,maximumOmegaResidual] = ...
        residual_field_audit(gauge,count)
required = {'c_lNominal','lengthGaugeStrain','widthRateScale', ...
    'lengthGaugeResidual','omegaGaugeResidual'};
passed = has_finite_equal_length_fields(gauge,required,count);
maximumLengthResidual = Inf;
maximumOmegaResidual = Inf;
if ~passed
    return;
end
denominator = max([ones(count,1),abs(gauge.c_lNominal(:)), ...
    abs(gauge.lengthGaugeStrain(:)),abs(gauge.widthRateScale(:))],[],2);
maximumLengthResidual = max(abs(gauge.lengthGaugeResidual(:))./denominator);
maximumOmegaResidual = max(abs(gauge.omegaGaugeResidual(:)));
passed = maximumLengthResidual <= 1e-10 && maximumOmegaResidual <= 1e-10;
end

function complete = has_finite_equal_length_fields(value,names,count)
complete = isstruct(value) && isscalar(value);
for index = 1:numel(names)
    name = names{index};
    complete = complete && isfield(value,name) && ...
        isnumeric(value.(name)) && isreal(value.(name)) && ...
        numel(value.(name)) == count && all(isfinite(value.(name)),'all');
end
end

function comparison = compare_contracts(first,second,firstAudit,secondAudit)
protectedDomains = {'grid','physics','elliptic','transport','scaling', ...
    'remesh','diagnostics'};
sameProtected = true;
for index = 1:numel(protectedDomains)
    name = protectedDomains{index};
    sameProtected = sameProtected && isfield(first.config,name) && ...
        isfield(second.config,name) && ...
        isequaln(first.config.(name),second.config.(name));
end
timeDifferences = differing_struct_fields( ...
    first.config.time,second.config.time);
nonCflTimeDifferences = setdiff(timeDifferences,{'cfl'},'stable');
sameTimeExceptCfl = isempty(nonCflTimeDifferences);
recordedEvidenceFieldsAvailable = ...
    ~isempty(firstAudit.recordedAuditEvidenceFields) && ...
    ~isempty(secondAudit.recordedAuditEvidenceFields);
sameRecordedEvidenceFields = recordedEvidenceFieldsAvailable && ...
    isequal(firstAudit.recordedAuditEvidenceFields, ...
        secondAudit.recordedAuditEvidenceFields);
sameMetadataFieldSchema = ...
    isequal(firstAudit.gaugeContractFields, ...
        secondAudit.gaugeContractFields) && ...
    isequal(firstAudit.lengthContractFields, ...
        secondAudit.lengthContractFields) && ...
    isequal(firstAudit.amplitudeContractFields, ...
        secondAudit.amplitudeContractFields) && ...
    isequal(firstAudit.feedbackContractFields, ...
        secondAudit.feedbackContractFields);
[firstOnlyEvidenceFields,secondOnlyEvidenceFields] = ...
    exact_evidence_field_differences(firstAudit,secondAudit);
sameMetadataEvidenceSchema = ...
    firstAudit.gaugeContractSchemaVersion == ...
        secondAudit.gaugeContractSchemaVersion && ...
    strcmp(firstAudit.evidenceClass,secondAudit.evidenceClass) && ...
    sameMetadataFieldSchema && ...
    firstAudit.currentStrengthenedFieldContractPassed && ...
    secondAudit.currentStrengthenedFieldContractPassed;
comparison = struct( ...
    'sameProtectedEvolutionConfiguration',sameProtected, ...
    'timeConfigurationDifferences',{timeDifferences}, ...
    'nonCflTimeConfigurationDifferences',{nonCflTimeDifferences}, ...
    'sameTimeConfigurationExceptCfl',sameTimeExceptCfl, ...
    'firstCfl',first.config.time.cfl, ...
    'secondCfl',second.config.time.cfl, ...
    'cflDiffers',first.config.time.cfl ~= second.config.time.cfl, ...
    'onlyCflNumericallyVaries',sameProtected && sameTimeExceptCfl && ...
        first.config.time.cfl ~= second.config.time.cfl, ...
    'sameEvolutionContract',sameProtected && sameTimeExceptCfl && ...
        firstAudit.configCorePassed && secondAudit.configCorePassed && ...
        firstAudit.metadataCorePassed && secondAudit.metadataCorePassed, ...
    'sameGaugeContractFieldSchema',sameMetadataFieldSchema, ...
    'firstOnlyExactEvidenceFields',{firstOnlyEvidenceFields}, ...
    'secondOnlyExactEvidenceFields',{secondOnlyEvidenceFields}, ...
    'recordedExactEvidenceFieldsAvailable', ...
        recordedEvidenceFieldsAvailable, ...
    'sameRecordedExactEvidenceFieldSchema',sameRecordedEvidenceFields, ...
    'sameStrengthenedEvidenceContract',sameMetadataEvidenceSchema, ...
    'firstEvidenceClass',firstAudit.evidenceClass, ...
    'secondEvidenceClass',secondAudit.evidenceClass, ...
    'evidenceSchemaRelation',evidence_schema_relation( ...
        firstAudit.evidenceClass,secondAudit.evidenceClass, ...
        sameMetadataFieldSchema,sameRecordedEvidenceFields), ...
    'legacyToStrengthenedEvidenceMismatch',xor( ...
        strcmp(firstAudit.evidenceClass,'legacy_core_only'), ...
        strcmp(secondAudit.evidenceClass,'legacy_core_only')));
end

function [firstOnly,secondOnly] = ...
        exact_evidence_field_differences(firstAudit,secondAudit)
firstFields = [ ...
    qualify_fields('gaugeContract.',firstAudit.gaugeContractFields); ...
    qualify_fields('gaugeContract.length.',firstAudit.lengthContractFields); ...
    qualify_fields('gaugeContract.amplitude.', ...
        firstAudit.amplitudeContractFields); ...
    qualify_fields('gaugeContract.feedback.', ...
        firstAudit.feedbackContractFields); ...
    qualify_fields('summary.exactEvidence.', ...
        firstAudit.recordedAuditEvidenceFields)];
secondFields = [ ...
    qualify_fields('gaugeContract.',secondAudit.gaugeContractFields); ...
    qualify_fields('gaugeContract.length.',secondAudit.lengthContractFields); ...
    qualify_fields('gaugeContract.amplitude.', ...
        secondAudit.amplitudeContractFields); ...
    qualify_fields('gaugeContract.feedback.', ...
        secondAudit.feedbackContractFields); ...
    qualify_fields('summary.exactEvidence.', ...
        secondAudit.recordedAuditEvidenceFields)];
firstOnly = setdiff(firstFields,secondFields,'stable');
secondOnly = setdiff(secondFields,firstFields,'stable');
end

function qualified = qualify_fields(prefix,names)
qualified = cell(size(names));
for index = 1:numel(names)
    qualified{index} = [prefix,names{index}];
end
qualified = qualified(:);
end

function relation = evidence_schema_relation(firstClass,secondClass, ...
        sameMetadataFields,sameRecordedFields)
if strcmp(firstClass,'legacy_core_only') && ...
        strcmp(secondClass,'strengthened_current')
    relation = 'first_legacy_second_strengthened';
elseif strcmp(firstClass,'strengthened_current') && ...
        strcmp(secondClass,'legacy_core_only')
    relation = 'first_strengthened_second_legacy';
elseif strcmp(firstClass,secondClass) && sameMetadataFields && ...
        sameRecordedFields
    relation = 'same_metadata_and_recorded_evidence_fields';
elseif strcmp(firstClass,secondClass) && sameMetadataFields
    relation = 'same_metadata_fields_recorded_evidence_differs_or_missing';
else
    relation = 'different_or_invalid_evidence_schema';
end
end

function differences = differing_struct_fields(first,second)
names = union(fieldnames(first),fieldnames(second),'stable');
differences = {};
for index = 1:numel(names)
    name = names{index};
    if ~isfield(first,name) || ~isfield(second,name) || ...
            ~isequaln(first.(name),second.(name))
        differences{end+1} = name; %#ok<AGROW>
    end
end
end

function description = campaign_description(campaign)
description = struct( ...
    'inputPath',campaign.inputPath, ...
    'inputKind',campaign.inputKind, ...
    'status',campaign.status, ...
    'candidateNames',{{campaign.runs.lengthGauge}}, ...
    'cfl',protocol_value(campaign.protocol,'cfl',NaN), ...
    'maximumDt',protocol_value(campaign.protocol,'maximumTimeStep',NaN));
end

function summary = summarize_records(records)
available = [records.physicalFields];
available = [available.available];
endpointMatches = arrayfun( ...
    @(record)record.endpoint.samePhysicalEndpoint,records);
sameEvolution = arrayfun( ...
    @(record)record.contractComparison.sameEvolutionContract,records);
onlyCfl = arrayfun( ...
    @(record)record.contractComparison.onlyCflNumericallyVaries,records);
sameEvidence = arrayfun( ...
    @(record)record.contractComparison.sameStrengthenedEvidenceContract, ...
    records);
sameMetadataFields = arrayfun( ...
    @(record)record.contractComparison.sameGaugeContractFieldSchema,records);
recordedFieldsAvailable = arrayfun( ...
    @(record)record.contractComparison.recordedExactEvidenceFieldsAvailable, ...
    records);
sameRecordedFields = arrayfun( ...
    @(record)record.contractComparison.sameRecordedExactEvidenceFieldSchema, ...
    records);
legacyMismatch = arrayfun( ...
    @(record)record.contractComparison.legacyToStrengthenedEvidenceMismatch, ...
    records);
tailDifferences = arrayfun( ...
    @(record)record.tailRates.absoluteWorstTrendDifference,records);
summary = struct( ...
    'candidateCount',numel(records), ...
    'allPhysicalEndpointsMatch',all(endpointMatches), ...
    'allPhysicalComparisonsAvailable',all(available), ...
    'allEvolutionContractsSame',all(sameEvolution), ...
    'allOnlyCflNumericallyVaries',all(onlyCfl), ...
    'allGaugeContractFieldSchemasSame',all(sameMetadataFields), ...
    'allRecordedExactEvidenceFieldsAvailable', ...
        all(recordedFieldsAvailable), ...
    'allRecordedExactEvidenceFieldSchemasSame', ...
        all(sameRecordedFields), ...
    'allStrengthenedEvidenceContractsSame',all(sameEvidence), ...
    'anyLegacyToStrengthenedEvidenceMismatch',any(legacyMismatch), ...
    'maximumRhoRelativeL2',NaN, ...
    'maximumOmegaRelativeL2',NaN, ...
    'maximumRhoAbsoluteInf',NaN, ...
    'maximumOmegaAbsoluteInf',NaN, ...
    'maximumPhysicalRhoXRelativeDifference',NaN, ...
    'maximumWorstTailTrendDifference',max(tailDifferences));
if any(available)
    comparisons = [records(available).physicalFields];
    worst = [comparisons.symmetricWorst];
    summary.maximumRhoRelativeL2 = max([worst.rhoRelativeL2]);
    summary.maximumOmegaRelativeL2 = max([worst.omegaRelativeL2]);
    summary.maximumRhoAbsoluteInf = max([worst.rhoAbsoluteInf]);
    summary.maximumOmegaAbsoluteInf = max([worst.omegaAbsoluteInf]);
    summary.maximumPhysicalRhoXRelativeDifference = ...
        max([worst.physicalRhoXRelativeDifference]);
end
end

function print_report(report)
fprintf(['Q256 C_L CROSS-CFL: first=%s second=%s ' ...
    'window=[%.6g %.6g %.6g]\n'], ...
    report.first.inputPath,report.second.inputPath, ...
    report.comparisonWindow(1),report.comparisonWindow(2), ...
    report.comparisonWindow(3));
for index = 1:numel(report.records)
    record = report.records(index);
    fields = record.physicalFields;
    if fields.available
        worst = fields.symmetricWorst;
        fprintf([ ...
            '%s: CFL %.6g->%.6g steps %d->%d wall %.6g->%.6g s; ' ...
            'rhoL2 %.3e omegaL2 %.3e rhoInf %.3e omegaInf %.3e ' ...
            'rhoXrel %.3e\n'], ...
            record.lengthGauge,record.firstRun.cfl,record.secondRun.cfl, ...
            record.firstRun.acceptedSteps,record.secondRun.acceptedSteps, ...
            record.firstRun.elapsedSeconds,record.secondRun.elapsedSeconds, ...
            worst.rhoRelativeL2,worst.omegaRelativeL2, ...
            worst.rhoAbsoluteInf,worst.omegaAbsoluteInf, ...
            worst.physicalRhoXRelativeDifference);
    else
        fprintf('%s: physical comparison unavailable (%s).\n', ...
            record.lengthGauge,record.physicalFields.errorIdentifier);
    end
    fprintf([ ...
        '  time: physical %.9g->%.9g, canonical %.9g->%.9g; ' ...
        'max realized CFL %.6g->%.6g; sec/step %.6g->%.6g\n'], ...
        record.firstRun.physicalTime,record.secondRun.physicalTime, ...
        record.firstRun.canonicalTime,record.secondRun.canonicalTime, ...
        record.firstRun.maximumRealizedCfl, ...
        record.secondRun.maximumRealizedCfl, ...
        record.firstRun.secondsPerStep,record.secondRun.secondsPerStep);
    fprintf([ ...
        '  endpoint c_l %.9g->%.9g (rel %.3e), ' ...
        'c_omega %.9g->%.9g (rel %.3e); worst tail %.6g->%.6g ' ...
        '(delta %+.3e)\n'], ...
        record.endpointRates.c_l.first,record.endpointRates.c_l.second, ...
        record.endpointRates.c_l.signedRelativeDifference, ...
        record.endpointRates.c_omega.first, ...
        record.endpointRates.c_omega.second, ...
        record.endpointRates.c_omega.signedRelativeDifference, ...
        record.tailRates.firstWorstCLCOmegaTrend, ...
        record.tailRates.secondWorstCLCOmegaTrend, ...
        record.tailRates.signedWorstTrendDifference);
    fprintf([ ...
        '  contracts: evolutionSame=%d onlyCfl=%d evidenceSame=%d ' ...
        'first=%s(v%.0f,recordedAudit=%s) ' ...
        'second=%s(v%.0f,recordedAudit=%s)\n'], ...
        record.contractComparison.sameEvolutionContract, ...
        record.contractComparison.onlyCflNumericallyVaries, ...
        record.contractComparison.sameStrengthenedEvidenceContract, ...
        record.firstContract.evidenceClass, ...
        record.firstContract.gaugeContractSchemaVersion, ...
        logical_text(record.firstContract.recordedAuditPassed), ...
        record.secondContract.evidenceClass, ...
        record.secondContract.gaugeContractSchemaVersion, ...
        logical_text(record.secondContract.recordedAuditPassed));
    fprintf([ ...
        '  exact fields: metadataSame=%d recordedEvidenceSame=%d ' ...
        'relation=%s; recorded/current agreement %s->%s\n'], ...
        record.contractComparison.sameGaugeContractFieldSchema, ...
        record.contractComparison.sameRecordedExactEvidenceFieldSchema, ...
        record.contractComparison.evidenceSchemaRelation, ...
        conditional_logical_text( ...
            record.firstContract.recordedAuditComparableToCurrent, ...
            record.firstContract.recordedAuditAgreesWithCurrent), ...
        conditional_logical_text( ...
            record.secondContract.recordedAuditComparableToCurrent, ...
            record.secondContract.recordedAuditAgreesWithCurrent));
    print_field_difference('first-only exact fields', ...
        record.contractComparison.firstOnlyExactEvidenceFields);
    print_field_difference('second-only exact fields', ...
        record.contractComparison.secondOnlyExactEvidenceFields);
    print_contract_missing('first',record.firstContract);
    print_contract_missing('second',record.secondContract);
end
end

function print_field_difference(label,fields)
if ~isempty(fields)
    fprintf('    %s: %s\n',label,strjoin(fields,', '));
end
end

function print_contract_missing(label,audit)
missing = [audit.missingStrengthenedFields, ...
    audit.missingCandidateDiagnosticFields];
mismatch = audit.mismatchedStrengthenedFields;
if ~isempty(missing)
    fprintf('    %s missing: %s\n',label,strjoin(missing,', '));
end
if ~isempty(mismatch)
    fprintf('    %s mismatch: %s\n',label,strjoin(mismatch,', '));
end
end

function text = logical_text(value)
if islogical(value) && isscalar(value)
    if value
        text = 'true';
    else
        text = 'false';
    end
elseif isnumeric(value) && isscalar(value) && isnan(value)
    text = 'unavailable';
else
    text = 'invalid';
end
end

function text = conditional_logical_text(available,value)
if available
    text = logical_text(value);
else
    text = 'not-comparable';
end
end

function names = physical_metric_names()
names = {'rhoRelativeL2','omegaRelativeL2','rhoAbsoluteInf', ...
    'omegaAbsoluteInf','labPeakShift','wallPeakRelativeDifference', ...
    'wallWidthRelativeDifference','physicalTimeDifference', ...
    'physicalRhoXRelativeDifference', ...
    'commonWallWidthRelativeDifference'};
end

function width = common_wall_half_maximum_width(result)
x = result.grid.physicalX(:)';
wall = result.physical.omega(1,:);
[peak,peakIndex] = max(wall);
if ~isfinite(peak) || peak <= 0
    error('ipm:GaugeLabCLCflWallWidth', ...
        'The terminal physical wall omega has no positive finite peak.');
end
threshold = 0.5*peak;
left = peakIndex;
while left > 1 && wall(left-1) >= threshold
    left = left-1;
end
right = peakIndex;
while right < numel(wall) && wall(right+1) >= threshold
    right = right+1;
end
if left == 1 || right == numel(wall)
    error('ipm:GaugeLabCLCflWallWidth', ...
        ['The terminal physical wall-omega half-maximum component is ' ...
        'not interior.']);
end
leftCrossing = linear_crossing( ...
    x(left-1:left),wall(left-1:left),threshold);
rightCrossing = linear_crossing( ...
    x(right:right+1),wall(right:right+1),threshold);
width = rightCrossing-leftCrossing;
if ~isfinite(width) || width <= 0
    error('ipm:GaugeLabCLCflWallWidth', ...
        'The common terminal wall-omega half-maximum width is invalid.');
end
end

function crossing = linear_crossing(x,values,threshold)
difference = values(2)-values(1);
if difference == 0
    error('ipm:GaugeLabCLCflWallWidth', ...
        'A terminal wall-omega half-maximum crossing has zero slope.');
end
fraction = (threshold-values(1))/difference;
crossing = x(1)+fraction*(x(2)-x(1));
end

function value = finite_max(source,name)
value = NaN;
if ~isfield(source,name) || ~isnumeric(source.(name))
    return;
end
finite = source.(name)(isfinite(source.(name)));
if ~isempty(finite)
    value = max(finite);
end
end

function count = count_limiter(common,name)
count = NaN;
if ~isfield(common,'timestepActiveLimiter')
    return;
end
values = string(common.timestepActiveLimiter);
count = nnz(values == string(name));
end

function value = guarded_ratio(numerator,denominator)
scale = max([1,abs(numerator),abs(denominator)]);
if ~all(isfinite([numerator,denominator])) || ...
        abs(denominator) <= 100*eps(scale)
    value = NaN;
else
    value = numerator/denominator;
end
end

function value = relative_difference(reference,candidate)
if ~all(isfinite([reference,candidate]))
    value = NaN;
    return;
end
scale = max(abs([reference,candidate]));
if scale == 0
    value = 0;
else
    value = (candidate-reference)/scale;
end
end

function value = directional_relative_difference(reference,candidate)
if ~all(isfinite([reference,candidate]))
    value = NaN;
else
    value = (candidate-reference)/max(abs(reference),eps);
end
end

function value = protocol_value(protocol,name,fallback)
if isstruct(protocol) && isscalar(protocol) && isfield(protocol,name)
    value = protocol.(name);
else
    value = fallback;
end
end

function value = optional_numeric_scalar(source,name,fallback)
value = fallback;
if isfield(source,name) && isnumeric(source.(name)) && ...
        isreal(source.(name)) && isscalar(source.(name))
    value = source.(name);
end
end

function value = optional_logical_scalar(source,name)
value = NaN;
if ~isfield(source,name)
    return;
end
candidate = source.(name);
if islogical(candidate) && isscalar(candidate)
    value = candidate;
elseif isnumeric(candidate) && isscalar(candidate) && ...
        isfinite(candidate) && any(candidate == [0,1])
    value = logical(candidate);
end
end

function value = scalar_text(value,name)
if isstring(value)
    if ~isscalar(value) || ismissing(value)
        error('ipm:GaugeLabCLCflText','%s must be scalar text.',name);
    end
    value = char(value);
end
if ~ischar(value) || ~isrow(value)
    error('ipm:GaugeLabCLCflText','%s must be scalar text.',name);
end
value = strtrim(value);
end

function matched = text_matches(value,expected)
matched = false;
if isstring(value)
    if ~isscalar(value) || ismissing(value)
        return;
    end
    value = char(value);
end
if ischar(value) && isrow(value)
    matched = strcmp(value,expected);
end
end

function names = retired_fields()
names = {'maxDynamicRate','adaptiveGain','adaptiveLengthScaling', ...
    'widthExpansionStrength','widthContractionOnset', ...
    'widthContractionStrength','maxWidthRateCorrection'};
end

function run = empty_source_run()
run = struct('lengthGauge','','resultFile','', ...
    'elapsedSeconds',NaN,'acceptedSteps',NaN,'secondsPerStep',NaN, ...
    'recordedExactContractPassed',NaN, ...
    'recordedExactEvidenceFields',{{}});
end

function comparison = empty_field_comparison()
comparison = struct('available',false,'forward',struct(), ...
    'reverse',struct(),'symmetricWorst',struct(), ...
    'limitsAvailable',false,'withinTournamentLimits',false, ...
    'maximumNormalizedLimitUsage',NaN, ...
    'errorIdentifier','','errorMessage','');
end

function series = empty_tail_series()
series = struct('valid',false,'firstStable',false,'secondStable',false, ...
    'firstMaximumAbsoluteRelativeTrend',NaN, ...
    'secondMaximumAbsoluteRelativeTrend',NaN, ...
    'signedMaximumTrendDifference',NaN, ...
    'absoluteMaximumTrendDifference',NaN, ...
    'firstRelativeWindowMeanSpread',NaN, ...
    'secondRelativeWindowMeanSpread',NaN, ...
    'signedWindowMeanSpreadDifference',NaN, ...
    'firstMaximumRelativeDetrendedRms',NaN, ...
    'secondMaximumRelativeDetrendedRms',NaN, ...
    'signedMaximumDetrendedRmsDifference',NaN, ...
    'firstWindowRelativeTrends',[], ...
    'secondWindowRelativeTrends',[], ...
    'windowRelativeTrendDifferences',[], ...
    'firstWindowWeightedMeans',[], ...
    'secondWindowWeightedMeans',[], ...
    'windowWeightedMeanDifferences',[], ...
    'firstWindowRelativeDetrendedRms',[], ...
    'secondWindowRelativeDetrendedRms',[]);
end

function audit = empty_contract_audit()
audit = struct('recordedAuditPassed',NaN, ...
    'recordedAuditEvidenceFields',{{}}, ...
    'configSchemaVersion',NaN,'gaugeContractSchemaVersion',NaN, ...
    'gaugeContractFields',{{}},'lengthContractFields',{{}}, ...
    'amplitudeContractFields',{{}},'feedbackContractFields',{{}}, ...
    'retiredFieldsAbsent',false,'configCorePassed',false, ...
    'metadataCorePassed',false,'metadataStrengthenedPassed',false, ...
    'coreHistoryComplete',false,'directClockPassed',false, ...
    'directRateIdentitiesPassed',false, ...
    'noFeedbackHistoryPassed',false,'fixedMeshPassed',false, ...
    'candidateDiagnosticsAvailable',false, ...
    'residualFieldsPassed',false, ...
    'maximumNormalizedLengthGaugeResidual',Inf, ...
    'maximumOmegaGaugeResidual',Inf, ...
    'recordedAuditComparableToCurrent',false, ...
    'recordedAuditAgreesWithCurrent',false, ...
    'currentStrengthenedFieldContractPassed',false, ...
    'evidenceClass','invalid_or_incomplete_core', ...
    'missingStrengthenedFields',{{}}, ...
    'mismatchedStrengthenedFields',{{}}, ...
    'missingCandidateDiagnosticFields',{{}});
end

function record = empty_record()
record = struct('lengthGauge','','firstResultFile','', ...
    'secondResultFile','','endpoint',struct(), ...
    'firstRun',struct(),'secondRun',struct(), ...
    'physicalFields',empty_field_comparison(), ...
    'endpointRates',struct(),'tailRates',struct(), ...
    'firstContract',empty_contract_audit(), ...
    'secondContract',empty_contract_audit(), ...
    'contractComparison',struct());
end
