% Short smooth fixed-grid fourth-order example; no files or figures.
smoothRho = @(X,Y) 2 + ...
    ((pi^2.*Y.*(1-Y)+2)./pi).*cos(pi.*(X+1));
opts = struct( ...
    'nx',33,'ny',33,'xlim',[-1,1],'ymax',1, ...
    'gridMode','uniform','gridStretchAutomatic',false,'gridStretch',[0,0], ...
    'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
    'rescalingMode','physical','initialCondition',smoothRho, ...
    'farBoundaryMode','dirichlet_zero','transportBoundaryMode','closed', ...
    'wallTransportMode','conservative_flux', ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'physicalFinalTime',2e-4,'maxDt',1e-4,'maxSteps',8, ...
    'storeSnapshots',false,'saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false, ...
    'verbose',true);
result = ipm.solve(opts);
