% A short first-quadrant dynamic IPM run with one direct level-set remesh.
% Add the ipm_grid_v6 root to the MATLAB path before running this script.
opts = struct( ...
    'quadrantOnly',true,'nx',65,'ny',33,'xlim',[0,4],'ymax',4, ...
    'gridMode','uniform','gridStretchAutomatic',false, ...
    'gridStretch',[0,0], ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'rescalingMode','dynamic','dynamicScaleGeometry','isotropic', ...
    'symmetryMode','double_odd_omega', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',0.5, ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order','farBoundaryMode','green', ...
    'adaptiveRemesh',true,'initialAnalyticRemesh',true, ...
    'initialAnalyticRemeshPasses',1, ...
    'finalTime',0.002,'maxDt',0.0005,'maxSteps',8, ...
    'outputEvery',0.0005, ...
    'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
result = ipm.solve(opts);
fprintf('Quadrant: %d x %d nodes, %d steps, %d remeshes.\n', ...
    numel(result.grid.x),numel(result.grid.y), ...
    result.state.steps,result.grid.remeshCount);
