% Short physical run. Add only the project root to the MATLAB path first.
% This example neither writes results nor creates figures.
opts = struct( ...
    'nx',33,'ny',17,'xlim',[-4,4],'ymax',4, ...
    'gridMode','stretched','gridStretchAutomatic',false, ...
    'gridStretch',[1.5,1.5],'targetCenterSpacing',[0.1,0.1], ...
    'initialCondition','degenerate','degeneratePower',4, ...
    'farBoundaryMode','dirichlet_zero','transportBoundaryMode','open', ...
    'rescalingMode','physical', ...
    'physicalFinalTime',2e-4,'maxDt',1e-4,'maxSteps',8, ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'storeSnapshots',false,'saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false, ...
    'verbose',true);
result = ipm.solve(opts);
