% Short smooth fixed-grid sixth-order example; no files or figures.
smoothRho = @(X,Y) 2 + ...
    ((pi^2.*Y.*(1-Y)+2)./pi).*cos(pi.*(X+1));
opts = ipm.config.sixthOrder(struct( ...
    'nx',33,'ny',33,'xlim',[-1,1],'ymax',1, ...
    'initialCondition',smoothRho, ...
    'physicalFinalTime',2e-4,'maxDt',1e-4,'maxSteps',8, ...
    'storeSnapshots',false,'saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false, ...
    'verbose',true));
result = ipm.solve(opts);
