function report = ipm_gridlab_score_frozen(dataset,candidateAxis,options)
%IPM_GRIDLAB_SCORE_FROZEN Score one x grid without evolving the PDE.
%   Every frozen rho is transferred old->candidate->old.  The report uses
%   field, wall-trace, and d_x rho errors together with conservation, range,
%   symmetry, feature-resolution, and mesh-quality diagnostics.

if nargin < 3 || isempty(options)
    options = struct();
end
options = resolve_options(options);
validate_dataset(dataset);
xCandidate = double(candidateAxis(:)');
validateattributes(xCandidate,{'numeric'}, ...
    {'vector','real','finite','increasing'},mfilename,'candidateAxis');
if mod(numel(xCandidate),2) ~= 1 || ...
        max(abs(xCandidate+fliplr(xCandidate))) > ...
        1e3*eps(max(1,max(abs(xCandidate))))
    error('ipm:gridlab:ScoreAxis', ...
        'candidateAxis must be odd, increasing, and symmetric.');
end

if isempty(options.profiles)
    profiles = ipm_gridlab_feature_profiles(dataset);
else
    profiles = options.profiles;
end
if numel(profiles.records) ~= dataset.snapshotCount
    error('ipm:gridlab:ScoreProfiles', ...
        'Feature-profile count must match the frozen dataset.');
end

qCandidate = ipm.mesh.quadrature(xCandidate);
quality = ipm.mesh.quality(xCandidate,7,qCandidate);
[meshAdmissible,meshReasons] = admit_mesh( ...
    quality,qCandidate,options.meshLimits);
DxCandidate = ipm.mesh.fdMatrix( ...
    xCandidate,1,min(options.stencilWidth,numel(xCandidate)));

template = struct('datasetIndex',0,'trusted',false, ...
    'canonicalTime',NaN,'physicalTime',NaN, ...
    'roundTripRelativeL2',NaN,'roundTripRelativeLinf',NaN, ...
    'wallRelativeL2',NaN,'sourceRelativeL2',NaN, ...
    'rowMassRelativeDefect',NaN,'relativeRangeViolation',NaN, ...
    'symmetryRelativeDefect',NaN,'coreCells',0,'leftFrontCells',0, ...
    'minimumCoreDx',NaN,'minimumLeftFrontDx',NaN);
if options.trustedOnly
    selectedCount = nnz([dataset.snapshots.trusted]);
else
    selectedCount = dataset.snapshotCount;
end
metrics = repmat(template,selectedCount,1);
metricIndex = 0;

for index = 1:dataset.snapshotCount
    snapshot = dataset.snapshots(index);
    if options.trustedOnly && ~snapshot.trusted
        continue
    end
    metricIndex = metricIndex+1;
    xOld = double(snapshot.x(:)');
    y = double(snapshot.y(:));
    rho = double(snapshot.rho);
    domainTolerance = 1e3*eps(max(1,max(abs(xOld))));
    if max(abs(xOld([1,end])-xCandidate([1,end]))) > domainTolerance
        error('ipm:gridlab:ScoreDomain', ...
            'Candidate and frozen grids must have identical endpoints.');
    end
    qOld = ipm.mesh.quadrature(xOld);
    qY = ipm.mesh.quadrature(y);
    transferOptions = struct('sampleDimension',2, ...
        'conservation','constant','stencilWidth',6);
    rhoCandidate = ipm.remesh.interpolate( ...
        xOld,rho,xCandidate,transferOptions);
    rhoRoundTrip = ipm.remesh.interpolate( ...
        xCandidate,rhoCandidate,xOld,transferOptions);

    errorField = rhoRoundTrip-rho;
    roundTripL2 = tensor_relative_l2(errorField,rho,qY,qOld);
    roundTripLinf = norm(errorField(:),inf)/max(norm(rho(:),inf),eps);
    wallError = errorField(1,:);
    wallL2 = weighted_relative_l2(wallError,rho(1,:),qOld);

    DxOld = ipm.mesh.fdMatrix( ...
        xOld,1,min(options.stencilWidth,numel(xOld)));
    sourceOld = rho*DxOld';
    sourceCandidate = rhoCandidate*DxCandidate';
    sourceOnOld = ipm.remesh.interpolate( ...
        xCandidate,sourceCandidate,xOld, ...
        struct('sampleDimension',2,'conservation','none', ...
        'stencilWidth',6));
    sourceL2 = tensor_relative_l2( ...
        sourceOnOld-sourceOld,sourceOld,qY,qOld);

    oldMass = rho*qOld(:);
    newMass = rhoCandidate*qCandidate(:);
    massDefect = norm(newMass-oldMass,inf)/max(norm(oldMass,inf),eps);
    oldMinimum = min(rho,[],'all');
    oldMaximum = max(rho,[],'all');
    rangeScale = max([oldMaximum-oldMinimum,abs(oldMinimum), ...
        abs(oldMaximum),eps]);
    rangeViolation = max([oldMinimum-min(rhoCandidate,[],'all'), ...
        max(rhoCandidate,[],'all')-oldMaximum,0])/rangeScale;
    symmetryDefect = norm(rhoCandidate-fliplr(rhoCandidate),'fro') / ...
        max(norm(rhoCandidate,'fro'),eps);

    feature = profiles.records(index);
    coreInterval = [max(0,feature.peakCenter-feature.coreWidthLeft), ...
        min(xCandidate(end),feature.peakCenter+feature.coreWidthRight)];
    frontInterval = [max(0,feature.leftFrontCenter- ...
        feature.leftFrontHalfWidth), ...
        min(xCandidate(end),feature.leftFrontCenter+ ...
        feature.leftFrontHalfWidth)];
    [coreCells,minimumCoreDx] = interval_resolution( ...
        xCandidate,coreInterval);
    [frontCells,minimumFrontDx] = interval_resolution( ...
        xCandidate,frontInterval);

    metrics(metricIndex,1) = struct( ...
        'datasetIndex',snapshot.datasetIndex,'trusted',snapshot.trusted, ...
        'canonicalTime',snapshot.canonicalTime, ...
        'physicalTime',snapshot.physicalTime, ...
        'roundTripRelativeL2',roundTripL2, ...
        'roundTripRelativeLinf',roundTripLinf, ...
        'wallRelativeL2',wallL2,'sourceRelativeL2',sourceL2, ...
        'rowMassRelativeDefect',massDefect, ...
        'relativeRangeViolation',rangeViolation, ...
        'symmetryRelativeDefect',symmetryDefect, ...
        'coreCells',coreCells,'leftFrontCells',frontCells, ...
        'minimumCoreDx',minimumCoreDx, ...
        'minimumLeftFrontDx',minimumFrontDx);
end
if isempty(metrics)
    error('ipm:gridlab:ScoreEmpty', ...
        'No frozen times survived the score selection.');
end

aggregate = aggregate_metrics(metrics,options.quantile);
objectiveTerms = [ ...
    aggregate.worst.roundTripRelativeL2/options.targets.roundTripRelativeL2, ...
    aggregate.worst.wallRelativeL2/options.targets.wallRelativeL2, ...
    aggregate.worst.sourceRelativeL2/options.targets.sourceRelativeL2, ...
    aggregate.worst.rowMassRelativeDefect/ ...
        options.targets.rowMassRelativeDefect, ...
    aggregate.worst.relativeRangeViolation/ ...
        options.targets.relativeRangeViolation];
quantileTerms = [ ...
    aggregate.quantile.roundTripRelativeL2/ ...
        options.targets.roundTripRelativeL2, ...
    aggregate.quantile.wallRelativeL2/options.targets.wallRelativeL2, ...
    aggregate.quantile.sourceRelativeL2/options.targets.sourceRelativeL2, ...
    aggregate.quantile.rowMassRelativeDefect/ ...
        options.targets.rowMassRelativeDefect, ...
    aggregate.quantile.relativeRangeViolation/ ...
        options.targets.relativeRangeViolation];
errorScore = sum(options.errorWeights.*(log1p(objectiveTerms) + ...
    options.quantileWeight*log1p(quantileTerms)));
corePenalty = max(0,options.minimumCoreCells-aggregate.minimumCoreCells) / ...
    options.minimumCoreCells;
frontPenalty = max(0,options.minimumFrontCells- ...
    aggregate.minimumLeftFrontCells)/options.minimumFrontCells;
resolutionPenalty = options.resolutionPenaltyWeight*( ...
    corePenalty+frontPenalty);
objective = errorScore+resolutionPenalty;
if ~meshAdmissible
    objective = inf;
end

report = struct('schemaVersion',1,'admissible',meshAdmissible, ...
    'rejectionReasons',{meshReasons},'objective',objective, ...
    'errorScore',errorScore,'resolutionPenalty',resolutionPenalty, ...
    'candidateAxis',xCandidate,'quality',quality, ...
    'quadratureWeights',qCandidate,'metrics',metrics, ...
    'aggregate',aggregate,'options',rmfield(options,'profiles'));
end

function options = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:gridlab:ScoreOptions', ...
        'options must be a scalar structure.');
end
defaultLimits = struct('maxAdjacentCellRatio',1.08, ...
    'maxLogSpacingCurvature',0.03,'minStencilRcond',1e-9, ...
    'minQuadratureWeightRatio',1e-4);
defaultTargets = struct('roundTripRelativeL2',2e-5, ...
    'wallRelativeL2',2e-5,'sourceRelativeL2',5e-3, ...
    'rowMassRelativeDefect',5e-12,'relativeRangeViolation',2e-4);
defaults = struct('trustedOnly',false,'profiles',[], ...
    'stencilWidth',7,'quantile',0.9,'quantileWeight',0.25, ...
    'minimumCoreCells',12, ...
    'minimumFrontCells',8,'resolutionPenaltyWeight',4, ...
    'errorWeights',[1,0.6,1.4,0.25,0.5], ...
    'meshLimits',defaultLimits,'targets',defaultTargets);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:ScoreOptions', ...
        'Unknown option(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(options,name)
        options.(name) = defaults.(name);
    end
end
if ~(islogical(options.trustedOnly) && isscalar(options.trustedOnly))
    error('ipm:gridlab:ScoreOptions', ...
        'options.trustedOnly must be a logical scalar.');
end
validateattributes(options.stencilWidth,{'numeric'}, ...
    {'scalar','integer','>=',5},mfilename,'options.stencilWidth');
if mod(options.stencilWidth,2) ~= 1
    error('ipm:gridlab:ScoreOptions', ...
        'options.stencilWidth must be odd.');
end
validateattributes(options.quantile,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',1},mfilename,'options.quantile');
validateattributes(options.quantileWeight,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename, ...
    'options.quantileWeight');
for field = {'minimumCoreCells','minimumFrontCells'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','integer','positive'},mfilename,['options.' field{1}]);
end
validateattributes(options.resolutionPenaltyWeight,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename, ...
    'options.resolutionPenaltyWeight');
validateattributes(options.errorWeights,{'numeric'}, ...
    {'vector','numel',5,'real','finite','nonnegative'},mfilename, ...
    'options.errorWeights');
options.errorWeights = options.errorWeights(:)';
options.meshLimits = merge_named_struct( ...
    options.meshLimits,defaultLimits,'meshLimits');
options.targets = merge_named_struct(options.targets,defaultTargets,'targets');
end

function value = merge_named_struct(value,defaults,label)
if ~isstruct(value) || ~isscalar(value)
    error('ipm:gridlab:ScoreOptions','options.%s must be a structure.',label);
end
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(value),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:ScoreOptions', ...
        'Unknown options.%s field(s): %s.',label,strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(value,name)
        value.(name) = defaults.(name);
    end
    validateattributes(value.(name),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        ['options.' label '.' name]);
end
end

function validate_dataset(dataset)
if ~isstruct(dataset) || ~isscalar(dataset) || ...
        ~isfield(dataset,'kind') || ...
        ~strcmp(dataset.kind,'ipm_frozen_grid_dataset') || ...
        ~isfield(dataset,'snapshots') || isempty(dataset.snapshots)
    error('ipm:gridlab:ScoreDataset', ...
        'Pass a nonempty frozen grid dataset.');
end
end

function [admissible,reasons] = admit_mesh(quality,weights,limits)
reasons = {};
if quality.maximumAdjacentCellRatio > limits.maxAdjacentCellRatio
    reasons{end+1} = 'adjacent_cell_ratio';
end
if quality.maximumLogSpacingCurvature > limits.maxLogSpacingCurvature
    reasons{end+1} = 'log_spacing_curvature';
end
if quality.minimumStencilRcond < limits.minStencilRcond
    reasons{end+1} = 'stencil_conditioning';
end
if quality.minimumQuadratureWeightRatio < ...
        limits.minQuadratureWeightRatio || any(weights <= 0)
    reasons{end+1} = 'quadrature_margin';
end
admissible = isempty(reasons);
end

function value = tensor_relative_l2(errorField,reference,qY,qX)
errorEnergy = qY(:)'*(errorField.^2)*qX(:);
referenceEnergy = qY(:)'*(reference.^2)*qX(:);
value = sqrt(max(errorEnergy,0)/max(referenceEnergy,eps));
end

function value = weighted_relative_l2(error,reference,weights)
errorEnergy = sum(weights(:)'.*(error.^2));
referenceEnergy = sum(weights(:)'.*(reference.^2));
value = sqrt(max(errorEnergy,0)/max(referenceEnergy,eps));
end

function [count,minimumDx] = interval_resolution(axis,interval)
positive = axis(axis >= 0);
centers = 0.5*(positive(1:end-1)+positive(2:end));
widths = diff(positive);
inside = centers >= interval(1) & centers <= interval(2);
count = nnz(inside);
if any(inside)
    minimumDx = min(widths(inside));
else
    minimumDx = inf;
end
end

function aggregate = aggregate_metrics(metrics,probability)
errorNames = {'roundTripRelativeL2','roundTripRelativeLinf', ...
    'wallRelativeL2','sourceRelativeL2','rowMassRelativeDefect', ...
    'relativeRangeViolation','symmetryRelativeDefect'};
worst = struct();
quantileValues = struct();
for index = 1:numel(errorNames)
    name = errorNames{index};
    values = [metrics.(name)];
    worst.(name) = max(values);
    quantileValues.(name) = scalar_quantile(values,probability);
end
aggregate = struct('worst',worst,'quantile',quantileValues, ...
    'quantileProbability',probability, ...
    'minimumCoreCells',min([metrics.coreCells]), ...
    'minimumLeftFrontCells',min([metrics.leftFrontCells]), ...
    'maximumMinimumCoreDx',max([metrics.minimumCoreDx]), ...
    'maximumMinimumLeftFrontDx',max([metrics.minimumLeftFrontDx]));
end

function value = scalar_quantile(values,probability)
values = sort(values(:));
position = 1+(numel(values)-1)*probability;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    fraction = position-lower;
    value = (1-fraction)*values(lower)+fraction*values(upper);
end
end
