function campaign = ipm_gridlab_run_q512_campaign( ...
        terminalInput,referenceInput,options)
%IPM_GRIDLAB_RUN_Q512_CAMPAIGN Conservative staged q512 continuation.
%   CAMPAIGN = IPM_GRIDLAB_RUN_Q512_CAMPAIGN(TERMINAL,REFERENCE,OPTIONS)
%   repeatedly performs
%
%       global-reference design -> audited checkpoint regrid -> ipm.solve
%
%   until max|physical rho_x| reaches OPTIONS.targetPhysicalRhoX, a strict
%   terminal gate fails, or the inter-stage wall-clock budget is exhausted.
%   TERMINAL is a production schema-4 accepted-step checkpoint, a compact
%   schema-v2 result, or its MAT-file. REFERENCE is the initial schema-v2
%   frozen dataset (or its
%   MAT-file) whose axes are the primary global reference at every stage.
%   An explicitly configured, generation-limited current-axis fallback is
%   available for x and is disabled by default. A root-reference corridor
%   fallback for x is independently available and disabled by default. A
%   fixed uniform global fallback is available for y; every design records
%   which reference was actually selected.
%
%   A native terminal checkpoint is the preferred input and is required
%   between solver stages. A terminal result is accepted only through
%   ipm.output.checkpointFromResult and is prominently recorded as the
%   machine-precision result bridge, not as a bitwise native restart.
%
%   This driver is deliberately restricted to the maintained 1025-by-513
%   stored-node fourth-order isotropic tuple. The default stage is 0.35 and
%   every stage is at most 0.42 canonical-time units. Native checkpoints
%   are requested every 0.20
%   canonical-time units and at exit on trusted recorded states. Results,
%   designs, audits, checkpoints, and summary snapshots are installed under
%   a unique campaign directory; no result or checkpoint path is reused.
%
%   The wall-clock budget is a conservative inter-stage launch gate. The
%   current design, regrid, and ipm.solve interfaces have no wall-clock
%   callback, so an already running phase is allowed to finish and may
%   overrun the budget. Numerical target attainment is not a blowup proof.

if nargin < 3 || isempty(options)
    options = struct();
end
options = resolve_options(options);
[campaignDirectory,campaignId] = create_campaign_directory(options);
campaign = initialize_campaign( ...
    campaignDirectory,campaignId,terminalInput,referenceInput,options);
referenceForDesign = stable_input_reference(referenceInput);
campaign.referenceLabel = input_label(referenceForDesign);
campaignTimer = tic;
activeStage = 0;

try
    [checkpoint,currentCheckpoint,restart] = resolve_terminal_input( ...
        terminalInput,campaignDirectory);
    validate_q512_source(checkpoint,options);
    campaign.restart = restart;
    campaign.currentCheckpointFile = currentCheckpoint;
    campaign.inheritedRegridRhoXRelativeJump = ...
        inherited_regrid_jump(checkpoint);
    campaign.cumulativeRegridRhoXRelativeJump = ...
        campaign.inheritedRegridRhoXRelativeJump;
    initialMetrics = checkpoint_terminal_metrics(checkpoint);
    campaign.initialMetrics = initialMetrics;
    campaign.finalMetrics = initialMetrics;

    [sourcePassed,sourceReasons] = terminal_gate(initialMetrics,options);
    if campaign.cumulativeRegridRhoXRelativeJump > ...
            options.maximumCumulativeRegridRhoXRelativeJump
        sourcePassed = false;
        sourceReasons{end+1} = 'inherited_regrid_rho_x_jump_budget';
    end
    if ~sourcePassed
        campaign.status = 'stopped_gate';
        campaign.stopReason = strjoin(sourceReasons,',');
        campaign = finish_campaign(campaign,campaignTimer);
        campaign = save_snapshot(campaign,'source_gate_failed',0);
        return
    end
    if initialMetrics.physicalRhoX >= options.targetPhysicalRhoX
        campaign.status = 'target_reached';
        campaign.stopReason = 'target_already_reached_at_input';
        campaign.targetReached = true;
        campaign = finish_campaign(campaign,campaignTimer);
        campaign = save_snapshot(campaign,'target_reached',0);
        return
    end

    campaign.status = 'running';
    campaign.stopReason = '';
    campaign = save_snapshot(campaign,'campaign_ready',0);
    lastSolveSeconds = NaN;

    for localStage = 1:options.maximumStages
        elapsed = toc(campaignTimer);
        launchReserve = launch_reserve(options,lastSolveSeconds);
        if elapsed+launchReserve > options.wallClockBudgetSeconds
            campaign.status = 'wall_clock_budget';
            campaign.stopReason = 'insufficient_budget_before_stage_design';
            break
        end

        stageNumber = options.firstStageIndex+localStage-1;
        stage = stage_template();
        stage.index = stageNumber;
        stage.localIndex = localStage;
        stage.tag = sprintf('%s_stage_%03d',options.campaignTag,stageNumber);
        stage.status = 'designing';
        stage.phase = 'design';
        stage.startedUtc = utc_now();
        stage.inputCheckpointFile = currentCheckpoint;
        stage.inputCanonicalTime = checkpoint.payload.state.scale.canonicalTime;
        stage.inputPhysicalTime = checkpoint.payload.state.scale.physicalTime;
        stage.inputStep = checkpoint.payload.state.step;
        stage.inputPhysicalRhoX = ...
            checkpoint.payload.log.history.common.physicalRhoXInf(end);
        stage.targetCanonicalTime = stage.inputCanonicalTime + ...
            options.stageCanonicalIncrement;
        stage.configuredXSeedOptions = options.xSeedOptions;
        stage.configuredCurrentAxisXFallbackOptions = ...
            current_axis_x_fallback_options(options);
        stage.configuredRootCorridorXFallbackOptions = ...
            root_corridor_x_fallback_options(options);
        stage.selectedXIncrementalReferenceDepth = ...
            options.currentIncrementalReferenceDepth;
        campaign.stages(end+1,1) = stage;
        activeStage = numel(campaign.stages);

        designFile = fullfile(campaignDirectory,sprintf( ...
            'stage_%03d_grid_design.mat',stageNumber));
        assert_new_file(designFile,'stage design');
        designOptions = stage_design_options( ...
            options,stage.tag,designFile);
        design = ipm_gridlab_design_continuation_stage( ...
            currentCheckpoint,referenceForDesign,designOptions);
        stage.designFile = designFile;
        stage.designStatus = design.status;
        stage.pairAdmissible = isfield(design,'pairScore') && ...
            isstruct(design.pairScore) && ...
            isfield(design.pairScore,'admissible') && ...
            isequal(design.pairScore.admissible,true);

        if ~strcmp(design.status,'feasible') || ...
                isempty(design.selected.x) || isempty(design.selected.y) || ...
                ~stage.pairAdmissible
            stage.status = 'design_failed';
            stage.phase = 'design_gate';
            stage.failureMessage = sprintf( ...
                'Stage design status is %s.',design.status);
            campaign.stages(activeStage) = complete_stage(stage);
            campaign.status = 'stopped_gate';
            campaign.stopReason = 'grid_design_not_feasible';
            campaign = save_snapshot( ...
                campaign,'stage_design_failed',activeStage);
            break
        end
        stage.selectedXReferenceProvenance = ...
            design.selected.xReferenceProvenance;
        stage.selectedYReferenceProvenance = ...
            design.selected.yReferenceProvenance;
        stage.selectedXModelName = design.selected.xName;
        if isfield(design.selected.xModel,'strengthScale')
            stage.selectedXStrengthScale = ...
                design.selected.xModel.strengthScale;
        else
            stage.selectedXStrengthScale = NaN;
        end
        stage.selectedXIncrementalReferenceDepth = ...
            selected_incremental_reference_depth( ...
                design.selected.xModel, ...
                options.currentIncrementalReferenceDepth, ...
                options.maximumIncrementalReferenceDepth);

        stage.designQuadrature = quadrature_pair_quality( ...
            design.selected.x,design.selected.y);
        [quadraturePassed,quadratureReasons] = ...
            quadrature_pair_gate(stage.designQuadrature,options);
        stage.designQuadraturePassed = quadraturePassed;
        stage.designQuadratureRejection = ...
            strjoin(quadratureReasons,',');
        [stage.designGlobalQuadratureWarning,designWarningReasons] = ...
            quadrature_pair_warning(stage.designQuadrature,options);
        stage.designGlobalQuadratureWarningReasons = ...
            strjoin(designWarningReasons,',');
        if ~quadraturePassed
            stage.status = 'design_failed';
            stage.phase = 'local_quadrature_gate';
            stage.failureMessage = strjoin(quadratureReasons,',');
            campaign.stages(activeStage) = complete_stage(stage);
            campaign.status = 'stopped_gate';
            campaign.stopReason = 'design_local_quadrature_gate';
            campaign = save_snapshot( ...
                campaign,'stage_quadrature_preflight_failed',activeStage);
            break
        end

        stage.predictedRegridRhoXRelativeJump = ...
            design.pairScore.aggregate.worst.rhoXMaximumRelativeChange;
        predictedCumulative = ...
            campaign.cumulativeRegridRhoXRelativeJump + ...
            stage.predictedRegridRhoXRelativeJump;
        if ~isfinite(stage.predictedRegridRhoXRelativeJump) || ...
                stage.predictedRegridRhoXRelativeJump > ...
                options.maximumRegridRhoXRelativeChange || ...
                predictedCumulative > ...
                options.maximumCumulativeRegridRhoXRelativeJump
            stage.status = 'design_failed';
            stage.phase = 'rho_x_jump_preflight';
            stage.failureMessage = ...
                'Frozen pair score exceeds the per-regrid or cumulative jump budget.';
            campaign.stages(activeStage) = complete_stage(stage);
            campaign.status = 'stopped_gate';
            campaign.stopReason = 'predicted_regrid_rho_x_jump_budget';
            campaign = save_snapshot( ...
                campaign,'stage_jump_preflight_failed',activeStage);
            break
        end
        stage.status = 'designed';
        campaign.stages(activeStage) = stage;
        campaign = save_snapshot( ...
            campaign,'stage_design_complete',activeStage);

        stage.phase = 'transactional_regrid';
        regridBase = fullfile(campaignDirectory,sprintf( ...
            'stage_%03d_regridded_checkpoint.mat',stageNumber));
        regridOptions = transaction_options(options,stage.tag,regridBase);
        [checkpoint,regridAudit,regridFile] = ...
            ipm_gridlab_regrid_checkpoint(currentCheckpoint, ...
                design.selected.x,design.selected.y,regridOptions);
        stage.regridCheckpointFile = char(regridFile);
        stage.regridAuditPassed = regridAudit.passed;
        stage.actualRegridRhoXRelativeJump = ...
            regridAudit.rhoXMaximumRelativeChange;
        candidateCumulativeJump = ...
            campaign.cumulativeRegridRhoXRelativeJump + ...
            stage.actualRegridRhoXRelativeJump;
        stage.cumulativeRegridRhoXRelativeJump = ...
            candidateCumulativeJump;
        stage.regridQuadrature = quadrature_pair_quality( ...
            checkpoint.payload.state.x,checkpoint.payload.state.y);
        [regridQuadraturePassed,regridQuadratureReasons] = ...
            quadrature_pair_gate(stage.regridQuadrature,options);
        stage.regridQuadraturePassed = regridQuadraturePassed;
        stage.regridQuadratureRejection = ...
            strjoin(regridQuadratureReasons,',');
        [stage.regridGlobalQuadratureWarning,regridWarningReasons] = ...
            quadrature_pair_warning(stage.regridQuadrature,options);
        stage.regridGlobalQuadratureWarningReasons = ...
            strjoin(regridWarningReasons,',');
        regridAudit.campaignLocalQuadrature = stage.regridQuadrature;
        regridAudit.campaignLocalQuadraturePassed = ...
            regridQuadraturePassed;
        regridAudit.campaignLocalQuadratureRejectionReasons = ...
            regridQuadratureReasons;
        regridAudit.campaignGlobalQuadratureWarning = ...
            stage.regridGlobalQuadratureWarning;
        regridAudit.campaignGlobalQuadratureWarningReasons = ...
            regridWarningReasons;
        regridAudit.campaignGlobalQuadratureWarningThreshold = ...
            options.globalQuadratureWeightRatioWarning;
        auditFile = fullfile(campaignDirectory,sprintf( ...
            'stage_%03d_regrid_audit.mat',stageNumber));
        assert_new_file(auditFile,'regrid audit');
        write_audit(regridAudit,auditFile);
        stage.regridAuditFile = auditFile;

        if ~regridAudit.passed || ~regridQuadraturePassed || ...
                candidateCumulativeJump > ...
                options.maximumCumulativeRegridRhoXRelativeJump
            stage.status = 'regrid_failed';
            stage.phase = 'regrid_campaign_gate';
            failureReasons = regridQuadratureReasons;
            if candidateCumulativeJump > ...
                    options.maximumCumulativeRegridRhoXRelativeJump
                failureReasons{end+1} = ...
                    'cumulative_regrid_rho_x_jump_budget'; %#ok<AGROW>
            end
            if ~regridAudit.passed
                failureReasons{end+1} = 'transaction_audit'; %#ok<AGROW>
            end
            stage.failureMessage = strjoin(failureReasons,',');
            campaign.stages(activeStage) = complete_stage(stage);
            campaign.status = 'stopped_gate';
            campaign.stopReason = 'regrid_campaign_gate';
            campaign = save_snapshot( ...
                campaign,'stage_regrid_gate_failed',activeStage);
            break
        end
        campaign.cumulativeRegridRhoXRelativeJump = ...
            candidateCumulativeJump;
        options.currentIncrementalReferenceDepth = ...
            stage.selectedXIncrementalReferenceDepth;
        campaign.currentIncrementalReferenceDepth = ...
            options.currentIncrementalReferenceDepth;
        stage.regridAdopted = true;
        stage.status = 'regridded';
        campaign.stages(activeStage) = stage;
        campaign.currentCheckpointFile = char(regridFile);
        campaign = save_snapshot( ...
            campaign,'stage_regrid_complete',activeStage);

        elapsed = toc(campaignTimer);
        launchReserve = launch_reserve(options,lastSolveSeconds);
        if elapsed+launchReserve > options.wallClockBudgetSeconds
            stage.status = 'budget_stop_after_regrid';
            stage.phase = 'solve_launch_gate';
            stage.failureMessage = ...
                'Insufficient wall-clock reserve to launch the next solve segment.';
            campaign.stages(activeStage) = complete_stage(stage);
            campaign.status = 'wall_clock_budget';
            campaign.stopReason = 'insufficient_budget_after_regrid';
            campaign = save_snapshot( ...
                campaign,'stage_solve_not_launched',activeStage);
            break
        end

        resultBase = fullfile(campaignDirectory,sprintf( ...
            'stage_%03d_result.mat',stageNumber));
        nativeCheckpointBase = fullfile(campaignDirectory,sprintf( ...
            'stage_%03d_native_checkpoint.mat',stageNumber));
        assert_new_file(resultBase,'solver result');
        assert_new_file(nativeCheckpointBase,'native checkpoint base');
        solveOverrides = solve_overrides( ...
            checkpoint,options,stage,resultBase,nativeCheckpointBase, ...
            campaignId);
        stage.status = 'solving';
        stage.phase = 'ipm.solve';
        campaign.stages(activeStage) = stage;
        campaign = save_snapshot( ...
            campaign,'stage_solve_started',activeStage);

        solveTimer = tic;
        result = ipm.solve(solveOverrides,regridFile);
        stage.solveElapsedSeconds = toc(solveTimer);
        lastSolveSeconds = stage.solveElapsedSeconds;
        result = ipm.output.validate(result);
        stage.resultFile = char(result.metadata.resultFile);
        campaign.finalResultFile = stage.resultFile;
        stage.outputCanonicalTime = result.state.canonicalTime;
        stage.outputPhysicalTime = result.state.physicalTime;
        stage.outputStep = result.state.steps;
        stage.stopReason = result.state.stopReason;

        terminalMetrics = result_terminal_metrics( ...
            result,stage.targetCanonicalTime);
        stage.recordCount = terminalMetrics.recordCount;
        stage.trustedPrefixRecords = terminalMetrics.trustedPrefixRecords;
        stage.continuousTrustedPrefix = ...
            terminalMetrics.continuousTrustedPrefix;
        stage.terminalTrusted = terminalMetrics.terminalTrusted;
        stage.horizontalCoreCells = terminalMetrics.horizontalCoreCells;
        stage.verticalCoreCells = terminalMetrics.verticalCoreCells;
        stage.safetyFactor = terminalMetrics.safetyFactor;
        stage.physicalRhoX = terminalMetrics.physicalRhoX;
        stage.terminalQuadrature = terminalMetrics.quadrature;
        [stage.terminalQuadraturePassed,terminalQuadratureReasons] = ...
            quadrature_pair_gate(stage.terminalQuadrature,options);
        stage.terminalQuadratureRejection = ...
            strjoin(terminalQuadratureReasons,',');
        [stage.terminalGlobalQuadratureWarning,terminalWarningReasons] = ...
            quadrature_pair_warning(stage.terminalQuadrature,options);
        stage.terminalGlobalQuadratureWarningReasons = ...
            strjoin(terminalWarningReasons,',');
        stage.stageHorizonReached = terminalMetrics.stageHorizonReached;
        stage.targetReached = terminalMetrics.physicalRhoX >= ...
            options.targetPhysicalRhoX;
        campaign.finalMetrics = terminalMetrics;

        if terminalMetrics.terminalTrusted
            stage.phase = 'native_terminal_checkpoint';
            [terminalCheckpoint,terminalCheckpointFile] = ...
                find_terminal_checkpoint(result,nativeCheckpointBase);
            stage.terminalCheckpointFile = terminalCheckpointFile;
            checkpoint = terminalCheckpoint;
            currentCheckpoint = terminalCheckpointFile;
            campaign.currentCheckpointFile = currentCheckpoint;
        end

        stage.phase = 'terminal_gate';
        [terminalPassed,terminalReasons] = ...
            terminal_gate(terminalMetrics,options);
        if ~terminalMetrics.stageHorizonReached && ~stage.targetReached
            terminalPassed = false;
            terminalReasons{end+1} = 'stage_canonical_horizon'; %#ok<AGROW>
        end
        if ~terminalPassed
            stage.status = 'terminal_gate_failed';
            stage.phase = 'terminal_gate';
            stage.failureMessage = strjoin(terminalReasons,',');
            campaign.stages(activeStage) = complete_stage(stage);
            campaign.status = 'stopped_gate';
            campaign.stopReason = stage.failureMessage;
            campaign = save_snapshot( ...
                campaign,'stage_terminal_gate_failed',activeStage);
            break
        end

        if stage.targetReached
            stage.status = 'target_reached';
            stage.phase = 'complete';
            campaign.stages(activeStage) = complete_stage(stage);
            campaign.status = 'target_reached';
            campaign.stopReason = 'physical_rho_x_target_reached';
            campaign.targetReached = true;
            campaign = save_snapshot( ...
                campaign,'stage_target_reached',activeStage);
            break
        end

        stage.status = 'completed';
        stage.phase = 'complete';
        campaign.stages(activeStage) = complete_stage(stage);
        campaign = save_snapshot( ...
            campaign,'stage_complete',activeStage);
        activeStage = 0;
    end

    if strcmp(campaign.status,'running')
        campaign.status = 'maximum_stages';
        campaign.stopReason = 'maximum_stage_count_reached';
    end
    campaign = finish_campaign(campaign,campaignTimer);
    campaign = save_snapshot(campaign,'campaign_finished',activeStage);
catch exception
    if activeStage > 0 && activeStage <= numel(campaign.stages)
        if ~exist('stage','var') || ...
                stage.index ~= campaign.stages(activeStage).index
            stage = campaign.stages(activeStage);
        end
        stage.status = 'exception';
        stage.failureIdentifier = exception.identifier;
        stage.failureMessage = exception.message;
        campaign.stages(activeStage) = complete_stage(stage);
    end
    campaign.status = 'failed_exception';
    campaign.stopReason = exception.identifier;
    campaign.error = exception_summary(exception);
    campaign = finish_campaign(campaign,campaignTimer);
    campaign = save_snapshot(campaign,'campaign_exception',activeStage);
    if options.throwOnFailure
        rethrow(exception)
    end
end
end

function options = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:gridlab:CampaignOptions', ...
        'options must be a scalar structure.');
end
defaults = struct( ...
    'outputRoot',fullfile('result','verification', ...
        'q512_continuation_campaigns'), ...
    'campaignTag','q512_rho_x', ...
    'targetPhysicalRhoX',1e3, ...
    'wallClockBudgetSeconds',8*3600, ...
    'stageCanonicalIncrement',0.35, ...
    'checkpointEvery',0.20, ...
    'maximumStages',64, ...
    'firstStageIndex',4, ...
    'maximumStepsPerStage',5000, ...
    'minimumWallTimeToLaunchSeconds',1800, ...
    'wallTimeForecastFactor',1.25, ...
    'ratioCap',1.08, ...
    'targetXCoreCells',21, ...
    'targetYCoreCells',20, ...
    'minimumXFrontCells',20, ...
    'minimumRegridXCoreCells',20, ...
    'minimumRegridYCoreCells',19, ...
    'minimumTerminalCoreCells',14, ...
    'maximumTerminalSafetyFactor',0.70, ...
    'maximumRegridRhoXRelativeChange',2e-3, ...
    'maximumCumulativeRegridRhoXRelativeJump',2e-2, ...
    'maximumMassRelativeDefect',5e-12, ...
    'maximumRelativeRangeViolation',2e-4, ...
    'maximumLogSpacingCurvature',0.01, ...
    'minimumStencilRcond',1e-9, ...
    'minimumQuadratureWeightRatio',1e-8, ...
    'globalQuadratureWeightRatioWarning',1e-4, ...
    'minimumLocalQuadratureWeightRatio',0.35, ...
    'maximumLocalQuadratureWeightRatio',1.65, ...
    'designFineCount',131073, ...
    'xSeedOptions',struct('strengthScales',1), ...
    'xEqualizationSigma',0.35, ...
    'xEqualizationPower',1, ...
    'currentAxisXFallbackEnabled',false, ...
    'currentAxisXSigmas',[1.5,2,3], ...
    'currentAxisXPower',2, ...
    'rootCorridorXFallbackEnabled',false, ...
    'rootCorridorXShoulderCells',[16 24 32], ...
    'rootCorridorXExpansionShoulders',2, ...
    'maximumIncrementalReferenceDepth',1, ...
    'currentIncrementalReferenceDepth',0, ...
    'yEqualizationSigma',0.25, ...
    'yEqualizationPower',2, ...
    'uniformFlatTailEnabled',true, ...
    'uniformFlatTailSigma',0.35, ...
    'uniformFlatTailPower',3, ...
    'equalizationInitialAmplitude',0.25, ...
    'equalizationMaximumAmplitude',16, ...
    'equalizationAmplitudeTolerance',1e-9, ...
    'equalizationMaximumIterations',80, ...
    'verbose',true, ...
    'throwOnFailure',true);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:CampaignOptions', ...
        'Unknown option(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(options,name)
        options.(name) = defaults.(name);
    end
end
options.xSeedOptions = validate_x_seed_options(options.xSeedOptions);

for field = {'outputRoot','campaignTag'}
    value = options.(field{1});
    if ~(ischar(value) || (isstring(value) && isscalar(value))) || ...
            isempty(char(value))
        error('ipm:gridlab:CampaignOptions', ...
            'options.%s must be nonempty text.',field{1});
    end
    options.(field{1}) = char(value);
end
for field = {'targetPhysicalRhoX','wallClockBudgetSeconds', ...
        'stageCanonicalIncrement','checkpointEvery', ...
        'minimumWallTimeToLaunchSeconds','wallTimeForecastFactor', ...
        'ratioCap','minimumTerminalCoreCells', ...
        'maximumTerminalSafetyFactor', ...
        'maximumRegridRhoXRelativeChange', ...
        'maximumCumulativeRegridRhoXRelativeJump', ...
        'maximumMassRelativeDefect', ...
        'maximumRelativeRangeViolation', ...
        'maximumLogSpacingCurvature','minimumStencilRcond', ...
        'minimumQuadratureWeightRatio', ...
        'globalQuadratureWeightRatioWarning', ...
        'minimumLocalQuadratureWeightRatio', ...
        'maximumLocalQuadratureWeightRatio','xEqualizationSigma', ...
        'xEqualizationPower','currentAxisXPower', ...
        'yEqualizationSigma', ...
        'yEqualizationPower','equalizationInitialAmplitude', ...
        'uniformFlatTailSigma','uniformFlatTailPower', ...
        'equalizationMaximumAmplitude', ...
        'equalizationAmplitudeTolerance'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        ['options.' field{1}]);
end
validateattributes(options.currentAxisXSigmas,{'numeric'}, ...
    {'vector','real','finite','positive','nonempty'},mfilename, ...
    'options.currentAxisXSigmas');
validateattributes(options.rootCorridorXShoulderCells,{'numeric'}, ...
    {'vector','real','finite','positive','nonempty'},mfilename, ...
    'options.rootCorridorXShoulderCells');
if any(diff(options.rootCorridorXShoulderCells(:)) <= 0)
    error('ipm:gridlab:CampaignRootCorridorShoulderCells', ...
        'rootCorridorXShoulderCells must be strictly increasing.');
end
validateattributes(options.rootCorridorXExpansionShoulders,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename, ...
    'options.rootCorridorXExpansionShoulders');
if options.stageCanonicalIncrement > 0.42
    error('ipm:gridlab:CampaignStageLength', ...
        'stageCanonicalIncrement may not exceed 0.42.');
end
if options.checkpointEvery > 0.20
    error('ipm:gridlab:CampaignCheckpointCadence', ...
        'checkpointEvery may not exceed 0.20 canonical-time units.');
end
if options.maximumRegridRhoXRelativeChange >= 1 || ...
        options.maximumCumulativeRegridRhoXRelativeJump >= 1
    error('ipm:gridlab:CampaignJumpBudget', ...
        'The rho_x jump limits must be strictly smaller than one.');
end
if options.ratioCap < 1
    error('ipm:gridlab:CampaignRatioCap', ...
        'ratioCap must be at least one.');
end
if options.wallTimeForecastFactor < 1
    error('ipm:gridlab:CampaignWallForecast', ...
        'wallTimeForecastFactor must be at least one.');
end
if options.minimumQuadratureWeightRatio >= 1
    error('ipm:gridlab:CampaignQuadratureRatio', ...
        'minimumQuadratureWeightRatio must be smaller than one.');
end
if options.globalQuadratureWeightRatioWarning >= 1 || ...
        options.globalQuadratureWeightRatioWarning < ...
        options.minimumQuadratureWeightRatio
    error('ipm:gridlab:CampaignQuadratureWarning', ...
        ['globalQuadratureWeightRatioWarning must be smaller than one ' ...
        'and no smaller than minimumQuadratureWeightRatio.']);
end
if options.minimumLocalQuadratureWeightRatio >= 1 || ...
        options.maximumLocalQuadratureWeightRatio <= 1 || ...
        options.minimumLocalQuadratureWeightRatio >= ...
        options.maximumLocalQuadratureWeightRatio
    error('ipm:gridlab:CampaignLocalQuadratureRatio', ...
        ['Local quadrature ratio limits must form a positive interval ' ...
        'strictly containing one.']);
end
if options.equalizationInitialAmplitude > ...
        options.equalizationMaximumAmplitude
    error('ipm:gridlab:CampaignEqualizationAmplitude', ...
        ['equalizationInitialAmplitude may not exceed ' ...
        'equalizationMaximumAmplitude.']);
end
for field = {'maximumStages','firstStageIndex','maximumStepsPerStage', ...
        'targetXCoreCells','targetYCoreCells','minimumXFrontCells', ...
        'minimumRegridXCoreCells','minimumRegridYCoreCells', ...
        'designFineCount','equalizationMaximumIterations'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','integer','positive','finite'},mfilename, ...
        ['options.' field{1}]);
end
for field = {'maximumIncrementalReferenceDepth', ...
        'currentIncrementalReferenceDepth'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','integer','nonnegative','finite'},mfilename, ...
        ['options.' field{1}]);
end
if options.currentIncrementalReferenceDepth > ...
        options.maximumIncrementalReferenceDepth
    error('ipm:gridlab:CampaignIncrementalReferenceDepth', ...
        ['currentIncrementalReferenceDepth may not exceed ' ...
        'maximumIncrementalReferenceDepth.']);
end
if options.designFineCount < 4097
    error('ipm:gridlab:CampaignDesignFineCount', ...
        'designFineCount must be at least 4097.');
end
if options.minimumRegridXCoreCells > options.targetXCoreCells || ...
        options.minimumRegridYCoreCells > options.targetYCoreCells
    error('ipm:gridlab:CampaignRegridCoreGate', ...
        'Regrid core gates may not exceed their design targets.');
end
for field = {'uniformFlatTailEnabled','currentAxisXFallbackEnabled', ...
        'rootCorridorXFallbackEnabled','verbose','throwOnFailure'}
    if ~(islogical(options.(field{1})) && isscalar(options.(field{1})))
        error('ipm:gridlab:CampaignOptions', ...
            'options.%s must be a logical scalar.',field{1});
    end
end
options.outputRoot = absolute_path(options.outputRoot);
end

function options = validate_x_seed_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:gridlab:CampaignXSeedOptions', ...
        'options.xSeedOptions must be a scalar structure.');
end
defaults = struct('minimumWidthFraction',1e-6, ...
    'minimumCellWidths',2,'combinePower',4, ...
    'maximumTeacherPoints',4097,'contrastCaps',[6,10,16], ...
    'frontWidthFactors',[0.75,1.25], ...
    'leftTailPowers',[1.25,2],'strengthScales',1);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:CampaignXSeedOptions', ...
        'Unknown xSeedOptions field(s): %s.',strjoin(unexpected,', '));
end
if ~isfield(options,'strengthScales')
    options.strengthScales = defaults.strengthScales;
end
for field = {'minimumWidthFraction','minimumCellWidths'}
    name = field{1};
    if isfield(options,name)
        validateattributes(options.(name),{'numeric'}, ...
            {'scalar','real','finite','positive'},mfilename, ...
            ['options.xSeedOptions.' name]);
    end
end
if isfield(options,'combinePower')
    validateattributes(options.combinePower,{'numeric'}, ...
        {'scalar','real','finite','>=',1},mfilename, ...
        'options.xSeedOptions.combinePower');
end
if isfield(options,'maximumTeacherPoints')
    validateattributes(options.maximumTeacherPoints,{'numeric'}, ...
        {'scalar','integer','>=',17},mfilename, ...
        'options.xSeedOptions.maximumTeacherPoints');
end
for field = {'contrastCaps','frontWidthFactors','leftTailPowers', ...
        'strengthScales'}
    name = field{1};
    if isfield(options,name)
        validateattributes(options.(name),{'numeric'}, ...
            {'vector','real','finite','positive','nonempty'},mfilename, ...
            ['options.xSeedOptions.' name]);
    end
end
end

function value = current_axis_x_fallback_options(options)
value = struct( ...
    'currentAxisXFallbackEnabled', ...
        options.currentAxisXFallbackEnabled, ...
    'currentAxisXSigmas',options.currentAxisXSigmas, ...
    'currentAxisXPower',options.currentAxisXPower, ...
    'maximumIncrementalReferenceDepth', ...
        options.maximumIncrementalReferenceDepth, ...
    'currentIncrementalReferenceDepth', ...
        options.currentIncrementalReferenceDepth);
end

function value = root_corridor_x_fallback_options(options)
value = struct( ...
    'rootCorridorXFallbackEnabled', ...
        options.rootCorridorXFallbackEnabled, ...
    'rootCorridorXShoulderCells', ...
        options.rootCorridorXShoulderCells, ...
    'rootCorridorXExpansionShoulders', ...
        options.rootCorridorXExpansionShoulders);
end

function depth = selected_incremental_reference_depth( ...
        model,currentDepth,maximumDepth)
depth = currentDepth;
if ~isstruct(model) || ~isscalar(model) || ...
        ~isfield(model,'incrementalGeneration')
    return
end
generation = model.incrementalGeneration;
validateattributes(generation,{'numeric'}, ...
    {'scalar','integer','nonnegative','finite'},mfilename, ...
    'design.selected.xModel.incrementalGeneration');
if generation ~= currentDepth+1 || generation > maximumDepth
    error('ipm:gridlab:CampaignIncrementalReferenceDepth', ...
        ['Selected incremental x-reference generation is inconsistent ' ...
        'with the configured lineage depth or exceeds its hard limit.']);
end
depth = generation;
end

function [directory,campaignId] = create_campaign_directory(options)
root = options.outputRoot;
if ~isfolder(root)
    [created,message] = mkdir(root);
    if ~created
        error('ipm:gridlab:CampaignOutputRoot', ...
            'Could not create output root %s: %s',root,message);
    end
end
timestamp = datetime('now','TimeZone','UTC', ...
    'Format','yyyyMMdd''T''HHmmssSSS');
[~,token] = fileparts(tempname(root));
safeTag = regexprep(options.campaignTag,'[^A-Za-z0-9_.-]','_');
campaignId = sprintf('%s_%s_%s',safeTag,char(timestamp),token);
directory = fullfile(root,campaignId);
if isfile(directory) || isfolder(directory)
    error('ipm:gridlab:CampaignOutputCollision', ...
        'Refusing to reuse campaign path %s.',directory);
end
[created,message] = mkdir(directory);
if ~created
    error('ipm:gridlab:CampaignOutputDirectory', ...
        'Could not create campaign directory %s: %s',directory,message);
end
end

function campaign = initialize_campaign( ...
        directory,id,terminalInput,referenceInput,options)
campaign = struct( ...
    'schemaVersion',1, ...
    'kind','ipm_gridlab_q512_continuation_campaign', ...
    'campaignId',id, ...
    'campaignDirectory',directory, ...
    'createdUtc',utc_now(), ...
    'updatedUtc','', ...
    'completedUtc','', ...
    'status','initializing', ...
    'stopReason','', ...
    'targetReached',false, ...
    'targetPhysicalRhoX',options.targetPhysicalRhoX, ...
    'scientificScope','numerical_target_only_not_blowup_proof', ...
    'wallClockSemantics', ...
        'soft_phase_boundary_budget_no_mid_phase_interrupt', ...
    'wallClockElapsedSeconds',0, ...
    'sourceLabel',input_label(terminalInput), ...
    'referenceLabel',input_label(referenceInput), ...
    'restart',restart_template(), ...
    'inheritedRegridRhoXRelativeJump',0, ...
    'cumulativeRegridRhoXRelativeJump',0, ...
    'configuredCurrentAxisXFallbackOptions', ...
        current_axis_x_fallback_options(options), ...
    'configuredRootCorridorXFallbackOptions', ...
        root_corridor_x_fallback_options(options), ...
    'currentIncrementalReferenceDepth', ...
        options.currentIncrementalReferenceDepth, ...
    'initialMetrics',metrics_template(), ...
    'finalMetrics',metrics_template(), ...
    'currentCheckpointFile','', ...
    'finalResultFile','', ...
    'stages',repmat(stage_template(),0,1), ...
    'error',exception_template(), ...
    'summarySequence',0, ...
    'latestSummaryFile','', ...
    'manifestFile',fullfile(directory,'campaign_manifest.jsonl'), ...
    'options',options);
end

function [checkpoint,currentReference,restart] = ...
        resolve_terminal_input(input,campaignDirectory)
[kind,value,label] = classify_terminal_input(input);
restart = restart_template();
restart.sourceLabel = label;
switch kind
    case 'checkpoint_file'
        checkpoint = ipm.output.readCheckpoint(value);
        currentReference = label;
        restart.mode = 'native_checkpoint_file';
        restart.bitwiseRestartStateAvailable = true;
    case 'checkpoint_structure'
        checkpoint = ipm.output.readCheckpoint(value);
        requested = fullfile( ...
            campaignDirectory,'input_native_checkpoint.mat');
        [checkpoint,fileName] = ...
            ipm.output.writeCheckpoint(checkpoint,requested);
        currentReference = char(fileName);
        restart.mode = 'native_checkpoint_structure_copied';
        restart.bitwiseRestartStateAvailable = true;
    case {'result_file','result_structure'}
        result = ipm.output.validate(value);
        validate_q512_result(result);
        requested = fullfile( ...
            campaignDirectory,'input_result_bridge_checkpoint.mat');
        bridgeInput = result;
        if strcmp(kind,'result_file')
            bridgeInput = value;
        end
        [checkpoint,fileName] = ...
            ipm.output.checkpointFromResult(bridgeInput,requested);
        currentReference = char(fileName);
        restart.mode = 'terminal_result_bridge_machine_precision';
        restart.usedResultBridge = true;
        restart.bitwiseRestartStateAvailable = false;
        restart.bridgeWarning = [ ...
            'log(C) was reconstructed from exponentiated result scales; ' ...
            'this is not a bitwise native restart'];
        restart.bridgeCheckpointFile = currentReference;
    otherwise
        error('ipm:gridlab:CampaignTerminalKind', ...
            'Unsupported terminal input kind %s.',kind);
end
restart = annotate_bridge_ancestry(restart,checkpoint);
end

function restart = annotate_bridge_ancestry(restart,checkpoint)
metadata = checkpoint.payload.state.runMetadata;
hasBridge = false;
if isfield(metadata,'checkpointSource')
    source = string(metadata.checkpointSource);
    hasBridge = isscalar(source) && ~ismissing(source) && ...
        strcmp(source,"trusted_terminal_result_v2");
end
restart.hasResultBridgeAncestry = hasBridge;
restart.bitwiseToPreBridgeTrajectory = ~hasBridge;
if hasBridge && isempty(restart.bridgeWarning)
    restart.bridgeWarning = [ ...
        'this native accepted-state checkpoint descends from a terminal ' ...
        'result bridge; restart from the stored state is exact, but the ' ...
        'pre-bridge trajectory is only machine-precision equivalent'];
end
end

function [kind,value,label] = classify_terminal_input(input)
if ischar(input) || (isstring(input) && isscalar(input))
    fileName = absolute_path(char(input));
    if ~isfile(fileName)
        error('ipm:gridlab:CampaignTerminalMissing', ...
            'Terminal input does not exist: %s',fileName);
    end
    variables = whos('-file',fileName);
    names = {variables.name};
    hasCheckpoint = ismember('checkpoint',names);
    hasResult = ismember('result',names);
    if hasCheckpoint == hasResult
        error('ipm:gridlab:CampaignTerminalFile', ...
            ['Terminal MAT-file must contain exactly one recognized ' ...
            'variable: checkpoint or result.']);
    end
    if hasCheckpoint
        kind = 'checkpoint_file';
    else
        kind = 'result_file';
    end
    value = fileName;
    label = fileName;
elseif isstruct(input) && isscalar(input) && ...
        isfield(input,'kind') && ...
        strcmp(input.kind,'ipm_accepted_step_checkpoint')
    kind = 'checkpoint_structure';
    value = input;
    label = 'in_memory_checkpoint';
elseif isstruct(input) && isscalar(input)
    kind = 'result_structure';
    value = input;
    label = 'in_memory_result';
else
    error('ipm:gridlab:CampaignTerminalInput', ...
        'TERMINAL must be one scalar result/checkpoint or its MAT-file.');
end
end

function validate_q512_source(checkpoint,options)
state = checkpoint.payload.state;
validate_q512_config(state.config,numel(state.x),numel(state.y));
if state.config.time.outputEvery > options.checkpointEvery
    error('ipm:gridlab:CampaignCheckpointSampling', ...
        ['The frozen outputEvery must not exceed checkpointEvery because ' ...
        'checkpoints can be emitted only at trusted recorded states.']);
end
end

function validate_q512_result(result)
validate_q512_config( ...
    result.config,numel(result.grid.x),numel(result.grid.y));
end

function validate_q512_config(config,nx,ny)
if nx ~= 1025 || ny ~= 513
    error('ipm:gridlab:CampaignResolution', ...
        ['This driver is restricted to 1025-by-513 stored nodes ' ...
        '(q512 quadrant cells); received %d-by-%d.'],nx,ny);
end
transport = config.transport;
scaling = config.scaling;
requiredTuple = strcmp(transport.spatialDiscretization,'high_order') && ...
    strcmp(transport.transportScheme,'weno5_fd') && ...
    strcmp(config.time.timeIntegrator,'ssprk54') && ...
    strcmp(config.remesh.remeshTransferScheme,'high_order');
if ~requiredTuple
    error('ipm:gridlab:CampaignNumericalTuple', ...
        'This driver requires high_order/weno5_fd/ssprk54/high_order.');
end
if ~strcmp(scaling.rescalingMode,'dynamic') || ...
        ~strcmp(scaling.dynamicScaleGeometry,'isotropic')
    error('ipm:gridlab:CampaignScaleGeometry', ...
        'This driver requires dynamic isotropic rescaling.');
end
if ~strcmp(config.physics.symmetryMode,'double_odd_omega')
    error('ipm:gridlab:CampaignSymmetry', ...
        'This driver requires double_odd_omega symmetry.');
end
levels = double(scaling.adaptiveLevels(:)');
requiredLevels = [0.1,0.5,0.9];
if numel(levels) ~= numel(requiredLevels) || ...
        max(abs(levels-requiredLevels)) > 64*eps
    error('ipm:gridlab:CampaignCoreLevels', ...
        ['This driver fixes adaptiveLevels=[0.1 0.5 0.9] so every ' ...
        'reported terminal core is the strict 0.9 connected component.']);
end
end

function value = inherited_regrid_jump(checkpoint)
value = 0;
metadata = checkpoint.payload.state.runMetadata;
if ~isfield(metadata,'gridLabRegrids') || isempty(metadata.gridLabRegrids)
    return
end
records = metadata.gridLabRegrids;
if ~isstruct(records) || ...
        ~all(isfield(records,'rhoXMaximumRelativeChange'))
    error('ipm:gridlab:CampaignRegridProvenance', ...
        'Existing gridLabRegrids provenance has no rho_x jump field.');
end
jumps = [records.rhoXMaximumRelativeChange];
if ~isnumeric(jumps) || any(~isfinite(jumps)) || any(jumps < 0)
    error('ipm:gridlab:CampaignRegridProvenance', ...
        'Existing gridLabRegrids rho_x jumps are invalid.');
end
value = sum(jumps);
end

function options = stage_design_options(input,tag,outputFile)
meshLimits = mesh_limits(input);
equalization = struct( ...
    'enabled',true, ...
    'uniformFlatTailEnabled',input.uniformFlatTailEnabled, ...
    'xSigma',input.xEqualizationSigma, ...
    'ySigma',input.yEqualizationSigma, ...
    'xPower',input.xEqualizationPower, ...
    'yPower',input.yEqualizationPower, ...
    'currentAxisXFallbackEnabled', ...
        input.currentAxisXFallbackEnabled, ...
    'currentAxisXSigmas',input.currentAxisXSigmas, ...
    'currentAxisXPower',input.currentAxisXPower, ...
    'rootCorridorXFallbackEnabled', ...
        input.rootCorridorXFallbackEnabled, ...
    'rootCorridorXShoulderCells', ...
        input.rootCorridorXShoulderCells, ...
    'rootCorridorXExpansionShoulders', ...
        input.rootCorridorXExpansionShoulders, ...
    'maximumIncrementalReferenceDepth', ...
        input.maximumIncrementalReferenceDepth, ...
    'currentIncrementalReferenceDepth', ...
        input.currentIncrementalReferenceDepth, ...
    'uniformFlatTailSigma',input.uniformFlatTailSigma, ...
    'uniformFlatTailPower',input.uniformFlatTailPower, ...
    'initialAmplitude',input.equalizationInitialAmplitude, ...
    'maximumAmplitude',input.equalizationMaximumAmplitude, ...
    'amplitudeTolerance',input.equalizationAmplitudeTolerance, ...
    'maxIterations',input.equalizationMaximumIterations);
pairTargets = struct('rhoXMaximumRelativeChange', ...
    input.maximumRegridRhoXRelativeChange);
options = struct( ...
    'ratioCap',input.ratioCap, ...
    'targetXCoreCells',input.targetXCoreCells, ...
    'targetYCoreCells',input.targetYCoreCells, ...
    'minimumXFrontCells',input.minimumXFrontCells, ...
    'tag',tag, ...
    'outputFile',outputFile, ...
    'collectOptions',struct('trustedOnly',true,'tag',tag), ...
    'xSeedOptions',input.xSeedOptions, ...
    'equalizationOptions',equalization, ...
    'axisOptions',struct('fineCount',input.designFineCount, ...
        'projectToAdmissible',true), ...
    'pairScoreOptions',struct('trustedOnly',true, ...
        'targets',pairTargets), ...
    'meshLimits',meshLimits);
end

function options = transaction_options(input,tag,outputFile)
options = struct( ...
    'outputFile',outputFile, ...
    'tag',tag, ...
    'minimumXCoreCells',input.minimumRegridXCoreCells, ...
    'minimumYCoreCells',input.minimumRegridYCoreCells, ...
    'maximumRhoXRelativeChange', ...
        input.maximumRegridRhoXRelativeChange, ...
    'maximumMassRelativeDefect',input.maximumMassRelativeDefect, ...
    'maximumRelativeRangeViolation', ...
        input.maximumRelativeRangeViolation, ...
    'meshLimits',mesh_limits(input));
end

function limits = mesh_limits(input)
limits = struct( ...
    'maxAdjacentCellRatio',input.ratioCap, ...
    'maxLogSpacingCurvature',input.maximumLogSpacingCurvature, ...
    'minStencilRcond',input.minimumStencilRcond, ...
    'minQuadratureWeightRatio', ...
        input.minimumQuadratureWeightRatio);
end

function overrides = solve_overrides( ...
        checkpoint,options,stage,resultFile,checkpointFile,campaignId)
saved = checkpoint.payload.state;
caseMetadata = saved.config.output.caseMetadata;
caseMetadata.gridLabCampaign = struct( ...
    'campaignId',campaignId, ...
    'stageIndex',stage.index, ...
    'stageTag',stage.tag, ...
    'targetPhysicalRhoX',options.targetPhysicalRhoX, ...
    'stageCanonicalIncrement',options.stageCanonicalIncrement, ...
    'ratioCap',options.ratioCap, ...
    'configuredXSeedOptions',stage.configuredXSeedOptions, ...
    'configuredCurrentAxisXFallbackOptions', ...
        stage.configuredCurrentAxisXFallbackOptions, ...
    'configuredRootCorridorXFallbackOptions', ...
        stage.configuredRootCorridorXFallbackOptions, ...
    'selectedXModelName',stage.selectedXModelName, ...
    'selectedXStrengthScale',stage.selectedXStrengthScale, ...
    'selectedXIncrementalReferenceDepth', ...
        stage.selectedXIncrementalReferenceDepth, ...
    'minimumQuadratureWeightRatio', ...
        options.minimumQuadratureWeightRatio, ...
    'globalQuadratureWeightRatioWarning', ...
        options.globalQuadratureWeightRatioWarning, ...
    'minimumLocalQuadratureWeightRatio', ...
        options.minimumLocalQuadratureWeightRatio, ...
    'maximumLocalQuadratureWeightRatio', ...
        options.maximumLocalQuadratureWeightRatio, ...
    'selectedXReferenceProvenance', ...
        stage.selectedXReferenceProvenance, ...
    'selectedYReferenceProvenance', ...
        stage.selectedYReferenceProvenance);
overrides = struct( ...
    'finalTime',stage.targetCanonicalTime, ...
    'physicalFinalTime',Inf, ...
    'maxSteps',saved.step+options.maximumStepsPerStage, ...
    'saveResults',true, ...
    'resultFile',resultFile, ...
    'makePlots',false, ...
    'livePlot',false, ...
    'writeVideo',false, ...
    'verbose',options.verbose, ...
    'caseMetadata',caseMetadata, ...
    'checkpoint',struct( ...
        'enabled',true,'file',checkpointFile, ...
        'every',options.checkpointEvery,'atExit',true));
end

function metrics = checkpoint_terminal_metrics(checkpoint)
history = checkpoint.payload.log.history;
config = checkpoint.payload.state.config;
metrics = history_terminal_metrics(history,config);
metrics.quadrature = quadrature_pair_quality( ...
    checkpoint.payload.state.x,checkpoint.payload.state.y);
metrics.stageHorizonReached = true;
metrics.stopReason = 'accepted_checkpoint';
metrics.canonicalTime = ...
    checkpoint.payload.state.scale.canonicalTime;
metrics.physicalTime = checkpoint.payload.state.scale.physicalTime;
metrics.step = checkpoint.payload.state.step;
end

function metrics = result_terminal_metrics(result,targetTau)
metrics = history_terminal_metrics(result.history,result.config);
metrics.quadrature = quadrature_pair_quality( ...
    result.grid.x,result.grid.y);
metrics.stopReason = result.state.stopReason;
metrics.canonicalTime = result.state.canonicalTime;
metrics.physicalTime = result.state.physicalTime;
metrics.step = result.state.steps;
tolerance = 64*eps(max([1,abs(targetTau), ...
    abs(result.state.canonicalTime)]));
metrics.stageHorizonReached = ...
    result.state.canonicalTime+tolerance >= targetTau;
end

function metrics = history_terminal_metrics(history,config)
rawTrusted = ipm.output.trustedMask(history,config);
prefix = ipm.output.continuousTrustedPrefix(rawTrusted);
common = history.common;
mesh = history.mesh;
metrics = metrics_template();
metrics.recordCount = numel(rawTrusted);
metrics.rawTrustedRecords = nnz(rawTrusted);
metrics.trustedPrefixRecords = nnz(prefix);
metrics.continuousTrustedPrefix = all(prefix);
metrics.terminalTrusted = rawTrusted(end) && prefix(end);
metrics.physicalRhoX = terminal_series(common,'physicalRhoXInf');
metrics.horizontalCoreCells = terminal_series(mesh,'coreGridPoints');
metrics.verticalCoreCells = ...
    terminal_series(mesh,'verticalCoreGridPoints');
metrics.safetyFactor = terminal_series(mesh,'safetyFactor');
metrics.canonicalTime = terminal_series(common,'canonicalTau');
metrics.physicalTime = terminal_series(common,'physicalTime');
end

function value = terminal_series(group,name)
if ~isfield(group,name) || ~isnumeric(group.(name)) || ...
        isempty(group.(name))
    value = NaN;
else
    value = group.(name)(end);
end
end

function [passed,reasons] = terminal_gate(metrics,options)
reasons = {};
if ~metrics.continuousTrustedPrefix
    reasons{end+1} = 'continuous_trusted_prefix';
end
if ~metrics.terminalTrusted
    reasons{end+1} = 'terminal_trusted';
end
if ~isfinite(metrics.horizontalCoreCells) || ...
        metrics.horizontalCoreCells < options.minimumTerminalCoreCells
    reasons{end+1} = 'horizontal_core_gate';
end
if ~isfinite(metrics.verticalCoreCells) || ...
        metrics.verticalCoreCells < options.minimumTerminalCoreCells
    reasons{end+1} = 'vertical_core_gate';
end
if ~isfinite(metrics.safetyFactor) || ...
        metrics.safetyFactor >= options.maximumTerminalSafetyFactor
    reasons{end+1} = 'safety_factor_gate';
end
if ~isfinite(metrics.physicalRhoX) || metrics.physicalRhoX <= 0
    reasons{end+1} = 'physical_rho_x_invalid';
end
[quadraturePassed,quadratureReasons] = ...
    quadrature_pair_gate(metrics.quadrature,options);
if ~quadraturePassed
    reasons = [reasons,quadratureReasons];
end
passed = isempty(reasons);
end

function quality = quadrature_pair_quality(x,y)
quality = struct( ...
    'x',quadrature_axis_quality(x), ...
    'y',quadrature_axis_quality(y));
end

function quality = quadrature_axis_quality(axis)
axis = double(axis(:));
weights = double(ipm.mesh.quadrature(axis));
weights = weights(:);
meshQuality = ipm.mesh.quality(axis,7,weights);
faces = diff(axis);
controlWidths = [0.5*faces(1); ...
    0.5*(faces(1:end-1)+faces(2:end));0.5*faces(end)];
localRatios = weights./controlWidths;
[~,minimumIndex] = min(localRatios);
[~,maximumIndex] = max(localRatios);
maximumLocalDeviation = ...
    meshQuality.maximumQuadratureWeightToControlWidthAbsoluteDeviationFromUnity;
quality = struct( ...
    'quadratureWeightsStrictlyPositive', ...
        meshQuality.quadratureWeightsStrictlyPositive, ...
    'minimumQuadratureWeight',meshQuality.minimumQuadratureWeight, ...
    'minimumQuadratureWeightRatio', ...
        meshQuality.minimumQuadratureWeightRatio, ...
    'minimumQuadratureWeightToControlWidthRatio', ...
        meshQuality.minimumQuadratureWeightToControlWidthRatio, ...
    'maximumQuadratureWeightToControlWidthRatio', ...
        meshQuality.maximumQuadratureWeightToControlWidthRatio, ...
    'maximumQuadratureWeightToControlWidthAbsoluteDeviationFromUnity', ...
        maximumLocalDeviation, ...
    'minimumQuadratureWeightToControlWidthRatioNodeIndex',minimumIndex, ...
    'maximumQuadratureWeightToControlWidthRatioNodeIndex',maximumIndex, ...
    'minimumControlWidth',min(controlWidths), ...
    'maximumControlWidth',max(controlWidths), ...
    'quadratureSumRelativeDefect', ...
        abs(sum(weights)-(axis(end)-axis(1))) / ...
        max(abs(axis(end)-axis(1)),eps));
end

function [passed,reasons] = quadrature_pair_gate(quality,options)
reasons = {};
for field = {'x','y'}
    label = field{1};
    axisQuality = quality.(label);
    if ~axisQuality.quadratureWeightsStrictlyPositive
        reasons{end+1} = ...
            [label ':quadrature_not_strictly_positive']; %#ok<AGROW>
    end
    if ~isfinite(axisQuality.minimumQuadratureWeightRatio) || ...
            axisQuality.minimumQuadratureWeightRatio < ...
            options.minimumQuadratureWeightRatio
        reasons{end+1} = ...
            [label ':global_quadrature_weight_ratio']; %#ok<AGROW>
    end
    if ~isfinite( ...
            axisQuality.minimumQuadratureWeightToControlWidthRatio) || ...
            axisQuality.minimumQuadratureWeightToControlWidthRatio < ...
            options.minimumLocalQuadratureWeightRatio
        reasons{end+1} = ...
            [label ':minimum_local_quadrature_ratio']; %#ok<AGROW>
    end
    if ~isfinite( ...
            axisQuality.maximumQuadratureWeightToControlWidthRatio) || ...
            axisQuality.maximumQuadratureWeightToControlWidthRatio > ...
            options.maximumLocalQuadratureWeightRatio
        reasons{end+1} = ...
            [label ':maximum_local_quadrature_ratio']; %#ok<AGROW>
    end
end
passed = isempty(reasons);
end

function [active,reasons] = quadrature_pair_warning(quality,options)
reasons = {};
for field = {'x','y'}
    label = field{1};
    ratio = quality.(label).minimumQuadratureWeightRatio;
    if isfinite(ratio) && ...
            ratio < options.globalQuadratureWeightRatioWarning
        reasons{end+1} = ...
            [label ':global_quadrature_weight_ratio_warning']; %#ok<AGROW>
    end
end
active = ~isempty(reasons);
end

function reserve = launch_reserve(options,lastSolveSeconds)
reserve = options.minimumWallTimeToLaunchSeconds;
if isfinite(lastSolveSeconds) && lastSolveSeconds > 0
    reserve = max(reserve, ...
        options.wallTimeForecastFactor*lastSolveSeconds);
end
end

function [checkpoint,fileName] = ...
        find_terminal_checkpoint(result,requestedBase)
candidates = {};
if isfield(result.metadata,'latestCheckpointFile') && ...
        strlength(string(result.metadata.latestCheckpointFile)) > 0
    candidates{end+1} = char(result.metadata.latestCheckpointFile);
end
[folder,stem] = fileparts(requestedBase);
listing = dir(fullfile(folder,[stem,'*.mat']));
if ~isempty(listing)
    [~,order] = sort([listing.datenum],'descend');
    for index = order
        candidates{end+1} = ...
            fullfile(listing(index).folder, ...
            listing(index).name); %#ok<AGROW>
    end
end
candidates = unique(candidates,'stable');
for index = 1:numel(candidates)
    candidate = candidates{index};
    if ~isfile(candidate)
        continue
    end
    try
        probe = ipm.output.readCheckpoint(candidate);
    catch
        continue
    end
    if checkpoint_matches_result(probe,result)
        checkpoint = probe;
        fileName = absolute_path(candidate);
        return
    end
end
error('ipm:gridlab:CampaignTerminalCheckpoint', ...
    ['A terminal-trusted solve did not expose a native exit checkpoint ' ...
    'matching its exact step, clocks, grid, and rho field.']);
end

function answer = checkpoint_matches_result(checkpoint,result)
state = checkpoint.payload.state;
scale = max([1,abs(state.scale.canonicalTime), ...
    abs(result.state.canonicalTime),abs(state.scale.physicalTime), ...
    abs(result.state.physicalTime)]);
tolerance = 64*eps(scale);
answer = state.step == result.state.steps && ...
    abs(state.scale.canonicalTime-result.state.canonicalTime) <= tolerance && ...
    abs(state.scale.physicalTime-result.state.physicalTime) <= tolerance && ...
    isequal(state.x,result.grid.x) && isequal(state.y,result.grid.y) && ...
    isequal(state.rho,result.state.rho);
end

function campaign = finish_campaign(campaign,timer)
campaign.wallClockElapsedSeconds = toc(timer);
campaign.completedUtc = utc_now();
campaign.updatedUtc = campaign.completedUtc;
end

function campaign = save_snapshot(campaign,event,stageIndex)
campaign.summarySequence = campaign.summarySequence+1;
campaign.updatedUtc = utc_now();
fileName = fullfile(campaign.campaignDirectory,sprintf( ...
    'campaign_summary_%04d.mat',campaign.summarySequence));
assert_new_file(fileName,'campaign summary');
campaign.latestSummaryFile = fileName;
temporaryFile = [tempname(campaign.campaignDirectory),'.mat'];
cleanup = onCleanup(@()delete_temporary(temporaryFile));
save(temporaryFile,'campaign','-v7.3');
[moved,message] = movefile(temporaryFile,fileName);
if ~moved
    error('ipm:gridlab:CampaignSummaryMove', ...
        'Could not install summary %s: %s',fileName,message);
end
append_manifest(campaign,event,stageIndex);
end

function append_manifest(campaign,event,stageIndex)
record = struct( ...
    'schemaVersion',1, ...
    'timestampUtc',utc_now(), ...
    'event',event, ...
    'campaignId',campaign.campaignId, ...
    'campaignStatus',campaign.status, ...
    'stopReason',campaign.stopReason, ...
    'stageIndex',stageIndex, ...
    'summaryFile',campaign.latestSummaryFile, ...
    'currentCheckpointFile',campaign.currentCheckpointFile, ...
    'finalResultFile',campaign.finalResultFile, ...
    'targetReached',campaign.targetReached, ...
    'configuredXSeedOptions',campaign.options.xSeedOptions, ...
    'configuredCurrentAxisXFallbackOptions', ...
        campaign.configuredCurrentAxisXFallbackOptions, ...
    'configuredRootCorridorXFallbackOptions', ...
        campaign.configuredRootCorridorXFallbackOptions, ...
    'currentIncrementalReferenceDepth', ...
        campaign.currentIncrementalReferenceDepth, ...
    'restartMode',campaign.restart.mode, ...
    'usedResultBridge',campaign.restart.usedResultBridge, ...
    'hasResultBridgeAncestry', ...
        campaign.restart.hasResultBridgeAncestry, ...
    'bitwiseToPreBridgeTrajectory', ...
        campaign.restart.bitwiseToPreBridgeTrajectory, ...
    'bridgeWarning',campaign.restart.bridgeWarning, ...
    'campaignTerminalPhysicalRhoX', ...
        campaign.finalMetrics.physicalRhoX, ...
    'campaignTerminalQuadrature',campaign.finalMetrics.quadrature, ...
    'cumulativeRegridRhoXRelativeJump', ...
        campaign.cumulativeRegridRhoXRelativeJump);
if stageIndex > 0 && stageIndex <= numel(campaign.stages)
    stage = campaign.stages(stageIndex);
    record.configuredXSeedOptions = stage.configuredXSeedOptions;
    record.configuredCurrentAxisXFallbackOptions = ...
        stage.configuredCurrentAxisXFallbackOptions;
    record.configuredRootCorridorXFallbackOptions = ...
        stage.configuredRootCorridorXFallbackOptions;
    record.stageNumber = stage.index;
    record.stageStatus = stage.status;
    record.stagePhase = stage.phase;
    record.stagePhysicalRhoX = stage.physicalRhoX;
    record.stageHorizontalCoreCells = stage.horizontalCoreCells;
    record.stageVerticalCoreCells = stage.verticalCoreCells;
    record.stageSafetyFactor = stage.safetyFactor;
    record.regridAdopted = stage.regridAdopted;
    record.selectedXReferenceProvenance = ...
        stage.selectedXReferenceProvenance;
    record.selectedYReferenceProvenance = ...
        stage.selectedYReferenceProvenance;
    record.selectedXModelName = stage.selectedXModelName;
    record.selectedXStrengthScale = stage.selectedXStrengthScale;
    record.selectedXIncrementalReferenceDepth = ...
        stage.selectedXIncrementalReferenceDepth;
    record.designFile = stage.designFile;
    record.regridAuditFile = stage.regridAuditFile;
    record.regridCheckpointFile = stage.regridCheckpointFile;
    record.resultFile = stage.resultFile;
    record.terminalCheckpointFile = stage.terminalCheckpointFile;
    record.designQuadrature = stage.designQuadrature;
    record.regridQuadrature = stage.regridQuadrature;
    record.terminalQuadrature = stage.terminalQuadrature;
    record.designQuadraturePassed = stage.designQuadraturePassed;
    record.designQuadratureRejection = ...
        stage.designQuadratureRejection;
    record.regridQuadraturePassed = stage.regridQuadraturePassed;
    record.regridQuadratureRejection = ...
        stage.regridQuadratureRejection;
    record.terminalQuadraturePassed = stage.terminalQuadraturePassed;
    record.terminalQuadratureRejection = ...
        stage.terminalQuadratureRejection;
    record.designGlobalQuadratureWarning = ...
        stage.designGlobalQuadratureWarning;
    record.designGlobalQuadratureWarningReasons = ...
        stage.designGlobalQuadratureWarningReasons;
    record.regridGlobalQuadratureWarning = ...
        stage.regridGlobalQuadratureWarning;
    record.regridGlobalQuadratureWarningReasons = ...
        stage.regridGlobalQuadratureWarningReasons;
    record.terminalGlobalQuadratureWarning = ...
        stage.terminalGlobalQuadratureWarning;
    record.terminalGlobalQuadratureWarningReasons = ...
        stage.terminalGlobalQuadratureWarningReasons;
else
    record.stageNumber = 0;
    record.stageStatus = '';
    record.stagePhase = '';
    record.stagePhysicalRhoX = NaN;
    record.stageHorizontalCoreCells = NaN;
    record.stageVerticalCoreCells = NaN;
    record.stageSafetyFactor = NaN;
    record.regridAdopted = false;
    record.selectedXReferenceProvenance = '';
    record.selectedYReferenceProvenance = '';
    record.selectedXModelName = '';
    record.selectedXStrengthScale = NaN;
    record.selectedXIncrementalReferenceDepth = ...
        campaign.currentIncrementalReferenceDepth;
    record.designFile = '';
    record.regridAuditFile = '';
    record.regridCheckpointFile = '';
    record.resultFile = '';
    record.terminalCheckpointFile = '';
    record.designQuadrature = quadrature_pair_template();
    record.regridQuadrature = quadrature_pair_template();
    record.terminalQuadrature = quadrature_pair_template();
    record.designQuadraturePassed = false;
    record.designQuadratureRejection = '';
    record.regridQuadraturePassed = false;
    record.regridQuadratureRejection = '';
    record.terminalQuadraturePassed = false;
    record.terminalQuadratureRejection = '';
    record.designGlobalQuadratureWarning = false;
    record.designGlobalQuadratureWarningReasons = '';
    record.regridGlobalQuadratureWarning = false;
    record.regridGlobalQuadratureWarningReasons = '';
    record.terminalGlobalQuadratureWarning = false;
    record.terminalGlobalQuadratureWarningReasons = '';
end
fileId = fopen(campaign.manifestFile,'a');
if fileId < 0
    warning('ipm:gridlab:CampaignManifest', ...
        'Could not append campaign manifest %s.',campaign.manifestFile);
    return
end
cleanup = onCleanup(@()fclose(fileId));
fprintf(fileId,'%s\n',jsonencode(record));
end

function write_audit(audit,fileName)
temporaryFile = [tempname(fileparts(fileName)),'.mat'];
cleanup = onCleanup(@()delete_temporary(temporaryFile));
save(temporaryFile,'audit','-v7.3');
[moved,message] = movefile(temporaryFile,fileName);
if ~moved
    error('ipm:gridlab:CampaignAuditMove', ...
        'Could not install regrid audit %s: %s',fileName,message);
end
end

function stage = complete_stage(stage)
stage.completedUtc = utc_now();
end

function summary = exception_summary(exception)
stack = exception.stack;
frames = repmat(struct('file','','name','','line',NaN),numel(stack),1);
for index = 1:numel(stack)
    frames(index) = struct('file',stack(index).file, ...
        'name',stack(index).name,'line',stack(index).line);
end
summary = struct('identifier',exception.identifier, ...
    'message',exception.message,'stack',frames);
end

function value = restart_template()
value = struct( ...
    'mode','unresolved', ...
    'sourceLabel','', ...
    'usedResultBridge',false, ...
    'hasResultBridgeAncestry',false, ...
    'bitwiseRestartStateAvailable',false, ...
    'bitwiseToPreBridgeTrajectory',false, ...
    'bridgeWarning','', ...
    'bridgeCheckpointFile','');
end

function value = metrics_template()
value = struct( ...
    'recordCount',0, ...
    'rawTrustedRecords',0, ...
    'trustedPrefixRecords',0, ...
    'continuousTrustedPrefix',false, ...
    'terminalTrusted',false, ...
    'horizontalCoreCells',NaN, ...
    'verticalCoreCells',NaN, ...
    'safetyFactor',NaN, ...
    'physicalRhoX',NaN, ...
    'canonicalTime',NaN, ...
    'physicalTime',NaN, ...
    'step',NaN, ...
    'stopReason','', ...
    'stageHorizonReached',false, ...
    'quadrature',quadrature_pair_template());
end

function value = stage_template()
value = struct( ...
    'index',0, ...
    'localIndex',0, ...
    'tag','', ...
    'status','pending', ...
    'phase','', ...
    'startedUtc','', ...
    'completedUtc','', ...
    'inputCheckpointFile','', ...
    'regridCheckpointFile','', ...
    'terminalCheckpointFile','', ...
    'designFile','', ...
    'regridAuditFile','', ...
    'resultFile','', ...
    'designStatus','', ...
    'pairAdmissible',false, ...
    'configuredXSeedOptions',struct(), ...
    'configuredCurrentAxisXFallbackOptions',struct(), ...
    'configuredRootCorridorXFallbackOptions',struct(), ...
    'selectedXModelName','', ...
    'selectedXStrengthScale',NaN, ...
    'selectedXIncrementalReferenceDepth',0, ...
    'selectedXReferenceProvenance','', ...
    'selectedYReferenceProvenance','', ...
    'regridAuditPassed',false, ...
    'regridAdopted',false, ...
    'designQuadrature',quadrature_pair_template(), ...
    'designQuadraturePassed',false, ...
    'designQuadratureRejection','', ...
    'designGlobalQuadratureWarning',false, ...
    'designGlobalQuadratureWarningReasons','', ...
    'regridQuadrature',quadrature_pair_template(), ...
    'regridQuadraturePassed',false, ...
    'regridQuadratureRejection','', ...
    'regridGlobalQuadratureWarning',false, ...
    'regridGlobalQuadratureWarningReasons','', ...
    'terminalQuadrature',quadrature_pair_template(), ...
    'terminalQuadraturePassed',false, ...
    'terminalQuadratureRejection','', ...
    'terminalGlobalQuadratureWarning',false, ...
    'terminalGlobalQuadratureWarningReasons','', ...
    'inputCanonicalTime',NaN, ...
    'inputPhysicalTime',NaN, ...
    'inputStep',NaN, ...
    'inputPhysicalRhoX',NaN, ...
    'targetCanonicalTime',NaN, ...
    'outputCanonicalTime',NaN, ...
    'outputPhysicalTime',NaN, ...
    'outputStep',NaN, ...
    'stopReason','', ...
    'solveElapsedSeconds',NaN, ...
    'predictedRegridRhoXRelativeJump',NaN, ...
    'actualRegridRhoXRelativeJump',NaN, ...
    'cumulativeRegridRhoXRelativeJump',NaN, ...
    'recordCount',0, ...
    'trustedPrefixRecords',0, ...
    'continuousTrustedPrefix',false, ...
    'terminalTrusted',false, ...
    'horizontalCoreCells',NaN, ...
    'verticalCoreCells',NaN, ...
    'safetyFactor',NaN, ...
    'physicalRhoX',NaN, ...
    'stageHorizonReached',false, ...
    'targetReached',false, ...
    'failureIdentifier','', ...
    'failureMessage','');
end

function value = exception_template()
value = struct('identifier','','message','', ...
    'stack',repmat(struct('file','','name','','line',NaN),0,1));
end

function value = quadrature_pair_template()
axisTemplate = struct( ...
    'quadratureWeightsStrictlyPositive',false, ...
    'minimumQuadratureWeight',NaN, ...
    'minimumQuadratureWeightRatio',NaN, ...
    'minimumQuadratureWeightToControlWidthRatio',NaN, ...
    'maximumQuadratureWeightToControlWidthRatio',NaN, ...
    'maximumQuadratureWeightToControlWidthAbsoluteDeviationFromUnity',NaN, ...
    'minimumQuadratureWeightToControlWidthRatioNodeIndex',NaN, ...
    'maximumQuadratureWeightToControlWidthRatioNodeIndex',NaN, ...
    'minimumControlWidth',NaN, ...
    'maximumControlWidth',NaN, ...
    'quadratureSumRelativeDefect',NaN);
value = struct('x',axisTemplate,'y',axisTemplate);
end

function label = input_label(input)
if ischar(input) || (isstring(input) && isscalar(input))
    label = absolute_path(char(input));
elseif isstruct(input) && isscalar(input) && ...
        isfield(input,'kind') && ...
        strcmp(input.kind,'ipm_accepted_step_checkpoint')
    label = 'in_memory_checkpoint';
else
    label = 'in_memory_result_or_dataset';
end
end

function value = stable_input_reference(value)
if ischar(value) || (isstring(value) && isscalar(value))
    value = absolute_path(char(value));
end
end

function value = absolute_path(value)
value = char(value);
isUnixAbsolute = startsWith(value,filesep);
isWindowsAbsolute = ~isempty(regexp(value,'^[A-Za-z]:[\\/]', 'once'));
if ~(isUnixAbsolute || isWindowsAbsolute)
    value = fullfile(pwd,value);
end
end

function assert_new_file(fileName,label)
if isfile(fileName) || isfolder(fileName)
    error('ipm:gridlab:CampaignArtifactCollision', ...
        'Refusing to overwrite existing %s: %s',label,fileName);
end
end

function delete_temporary(fileName)
if isfile(fileName)
    try
        delete(fileName);
    catch exception
        fprintf(2,'IPM grid-lab warning: could not remove %s: %s\n', ...
            fileName,exception.message);
    end
end
end

function value = utc_now()
value = char(datetime('now','TimeZone','UTC', ...
    'Format','yyyy-MM-dd''T''HH:mm:ss.SSS''Z'''));
end
