function report = ipm_gridlab_score_frozen_pair( ...
        dataset,candidateX,candidateY,options)
%IPM_GRIDLAB_SCORE_FROZEN_PAIR Score one complete x/y grid offline.
%   REPORT = IPM_GRIDLAB_SCORE_FROZEN_PAIR(DATASET,XNEW,YNEW) first admits
%   both candidate axes.  Only an admissible pair is used for the separable
%   high-order transfer old->candidate->old.  Fields use the maintained
%   ny-by-nx layout.  XNEW must have an odd node count and be symmetric
%   about zero; YNEW must start at zero and increase toward the far wall.
%
%   The score reports field, wall, rho_x, rho_y, conservation, range,
%   x-symmetry, and horizontal/vertical feature-resolution diagnostics at
%   every frozen time.  Version-2 safety-core widths (the 0.9 connected
%   component) take precedence over the broader version-1 core widths.  A
%   version-1 profile has no vertical feature, so its 0.9 y-core width is
%   reconstructed from the paired frozen field.

if nargin < 4 || isempty(options)
    options = struct();
end
options = resolve_options(options);
[snapshots,xLimits,yLimits,datasetTag] = validate_dataset_header(dataset);
[xCandidate,yCandidate] = validate_candidate_axes( ...
    candidateX,candidateY,xLimits,yLimits,options);

[qXCandidate,xQuality] = axis_quality(xCandidate,options);
[qYCandidate,yQuality] = axis_quality(yCandidate,options);
[xAdmissible,xReasons] = admit_axis( ...
    xQuality,qXCandidate,options.meshLimits,'x');
[yAdmissible,yReasons] = admit_axis( ...
    yQuality,qYCandidate,options.meshLimits,'y');
meshReasons = [xReasons,yReasons];
meshAdmissible = xAdmissible && yAdmissible;

storedOptions = rmfield(options,'profiles');
report = struct( ...
    'schemaVersion',1,'kind','ipm_frozen_grid_pair_score', ...
    'status','rejected_mesh','admissible',meshAdmissible, ...
    'rejectionReasons',{meshReasons},'objective',inf, ...
    'errorScore',NaN,'resolutionPenalty',NaN, ...
    'datasetSchemaVersion',dataset.schemaVersion, ...
    'datasetTag',datasetTag,'datasetSnapshotCount',numel(snapshots), ...
    'selectedSnapshotCount',0,'profileSchemaVersion',NaN, ...
    'candidateX',xCandidate,'candidateY',yCandidate, ...
    'quality',struct('x',xQuality,'y',yQuality), ...
    'quadratureWeights',struct('x',qXCandidate,'y',qYCandidate), ...
    'metrics',empty_metrics(),'aggregate',struct(), ...
    'options',storedOptions);
if ~meshAdmissible
    return
end

profiles = resolve_profiles(dataset,options.profiles,numel(snapshots));
report.profileSchemaVersion = profiles.schemaVersion;
selected = true(numel(snapshots),1);
if options.trustedOnly
    selected = reshape([snapshots.trusted],[],1);
end
if ~any(selected)
    error('ipm:gridlab:PairScoreEmpty', ...
        'No frozen times survived the score selection.');
end

DxCandidate = ipm.mesh.fdMatrix( ...
    xCandidate,1,options.derivativeStencilWidth);
DyCandidate = ipm.mesh.fdMatrix( ...
    yCandidate,1,options.derivativeStencilWidth);
metricTemplate = metric_template();
metrics = repmat(metricTemplate,nnz(selected),1);
metricIndex = 0;

for index = 1:numel(snapshots)
    if ~selected(index)
        continue
    end
    metricIndex = metricIndex+1;
    snapshot = snapshots(index);
    validate_snapshot_field(snapshot,index);
    xOld = double(snapshot.x(:)');
    yOld = double(snapshot.y(:));
    rho = double(snapshot.rho);
    assert_matching_domain(xOld,yOld,xLimits,yLimits,index);

    qXOld = quadrature_weights(xOld,options.transferStencilWidth);
    qYOld = quadrature_weights(yOld,options.transferStencilWidth);
    if any(qXOld <= 0) || any(qYOld <= 0)
        error('ipm:gridlab:PairScoreFrozenQuadrature', ...
            'Frozen snapshot %d has a nonpositive quadrature weight.',index);
    end
    DxOld = ipm.mesh.fdMatrix( ...
        xOld,1,options.derivativeStencilWidth);
    DyOld = ipm.mesh.fdMatrix( ...
        yOld,1,options.derivativeStencilWidth);

    [rhoCandidate,rhoAfterX] = transfer_x_then_y( ...
        rho,xOld,yOld,xCandidate,yCandidate, ...
        options.transferStencilWidth,options.conservation);
    rhoRoundTrip = transfer_y_then_x( ...
        rhoCandidate,xCandidate,yCandidate,xOld,yOld, ...
        options.transferStencilWidth,options.conservation);

    errorField = rhoRoundTrip-rho;
    fieldL2 = tensor_relative_l2(errorField,rho,qYOld,qXOld);
    fieldLinf = relative_linf(errorField,rho);
    wallError = errorField(1,:);
    wallL2 = weighted_relative_l2(wallError,rho(1,:),qXOld);
    wallLinf = relative_linf(wallError,rho(1,:));

    rhoXOld = rho*DxOld';
    rhoYOld = DyOld*rho;
    rhoXCandidate = rhoCandidate*DxCandidate';
    rhoYCandidate = DyCandidate*rhoCandidate;
    [rhoXMaximumChange,rhoXMaximumSignedChange, ...
        rhoXMaximumRatio,rhoXMaximumOld,rhoXMaximumCandidate] = ...
        maximum_relative_change(rhoXOld,rhoXCandidate);
    [wallRhoXMaximumChange,wallRhoXMaximumSignedChange, ...
        wallRhoXMaximumRatio,wallRhoXMaximumOld, ...
        wallRhoXMaximumCandidate] = maximum_relative_change( ...
        rhoXOld(1,:),rhoXCandidate(1,:));
    [rhoYMaximumChange,rhoYMaximumSignedChange, ...
        rhoYMaximumRatio,rhoYMaximumOld,rhoYMaximumCandidate] = ...
        maximum_relative_change(rhoYOld,rhoYCandidate);
    rhoXOnOld = transfer_y_then_x( ...
        rhoXCandidate,xCandidate,yCandidate,xOld,yOld, ...
        options.transferStencilWidth,'none');
    rhoYOnOld = transfer_y_then_x( ...
        rhoYCandidate,xCandidate,yCandidate,xOld,yOld, ...
        options.transferStencilWidth,'none');
    rhoXError = rhoXOnOld-rhoXOld;
    rhoYError = rhoYOnOld-rhoYOld;
    rhoXL2 = tensor_relative_l2(rhoXError,rhoXOld,qYOld,qXOld);
    rhoXLinf = relative_linf(rhoXError,rhoXOld);
    rhoYL2 = tensor_relative_l2(rhoYError,rhoYOld,qYOld,qXOld);
    rhoYLinf = relative_linf(rhoYError,rhoYOld);
    wallRhoXL2 = weighted_relative_l2( ...
        rhoXError(1,:),rhoXOld(1,:),qXOld);
    wallRhoXLinf = relative_linf(rhoXError(1,:),rhoXOld(1,:));

    oldRowMass = rho*qXOld(:);
    xStageRowMass = rhoAfterX*qXCandidate(:);
    xRowMassDefect = relative_vector_defect( ...
        xStageRowMass,oldRowMass);
    xStageColumnMass = qYOld(:)'*rhoAfterX;
    candidateColumnMass = qYCandidate(:)'*rhoCandidate;
    yColumnMassDefect = relative_vector_defect( ...
        candidateColumnMass,xStageColumnMass);
    oldMass = qYOld(:)'*rho*qXOld(:);
    candidateMass = qYCandidate(:)'*rhoCandidate*qXCandidate(:);
    forwardMassDefect = relative_scalar_defect(candidateMass,oldMass);

    roundTripRowMass = rhoRoundTrip*qXOld(:);
    roundTripColumnMass = qYOld(:)'*rhoRoundTrip;
    oldColumnMass = qYOld(:)'*rho;
    roundTripRowDefect = relative_vector_defect( ...
        roundTripRowMass,oldRowMass);
    roundTripColumnDefect = relative_vector_defect( ...
        roundTripColumnMass,oldColumnMass);
    roundTripMass = qYOld(:)'*rhoRoundTrip*qXOld(:);
    roundTripMassDefect = relative_scalar_defect(roundTripMass,oldMass);
    % The committed forward transaction conserves every interpolated line
    % and total mass.  Round-trip marginal defects are interpolation-error
    % diagnostics, not conservation failures of that forward transaction.
    conservationDefect = max([xRowMassDefect,yColumnMassDefect, ...
        forwardMassDefect,roundTripMassDefect]);

    forwardRange = relative_range_violation(rho,rhoCandidate);
    roundTripRange = relative_range_violation(rho,rhoRoundTrip);
    rangeViolation = max(forwardRange,roundTripRange);
    symmetryDefect = norm( ...
        rhoCandidate-fliplr(rhoCandidate),'fro') / ...
        max(norm(rhoCandidate,'fro'),eps);

    profile = profiles.records(index);
    validate_profile_record(profile,snapshot,index);
    [coreInterval,frontInterval] = x_feature_intervals( ...
        profile,xCandidate(end));
    [xCoreCells,minimumXCoreDx] = interval_resolution( ...
        xCandidate(xCandidate >= 0),coreInterval);
    [xFrontCells,minimumXFrontDx] = interval_resolution( ...
        xCandidate(xCandidate >= 0),frontInterval);
    [yCoreWidth,yCoreSource] = y_core_width( ...
        profile,rhoXOld,xOld,yOld,options.yCoreLevel);
    [yCoreCells,minimumYCoreDy] = interval_resolution( ...
        yCandidate,[0,min(yCandidate(end),yCoreWidth)]);

    metrics(metricIndex,1) = struct( ...
        'datasetIndex',snapshot.datasetIndex, ...
        'trusted',snapshot.trusted, ...
        'canonicalTime',snapshot.canonicalTime, ...
        'physicalTime',snapshot.physicalTime, ...
        'fieldRelativeL2',fieldL2, ...
        'fieldRelativeLinf',fieldLinf, ...
        'wallRelativeL2',wallL2,'wallRelativeLinf',wallLinf, ...
        'rhoXRelativeL2',rhoXL2,'rhoXRelativeLinf',rhoXLinf, ...
        'rhoYRelativeL2',rhoYL2,'rhoYRelativeLinf',rhoYLinf, ...
        'wallRhoXRelativeL2',wallRhoXL2, ...
        'wallRhoXRelativeLinf',wallRhoXLinf, ...
        'rhoXMaximumOld',rhoXMaximumOld, ...
        'rhoXMaximumCandidate',rhoXMaximumCandidate, ...
        'rhoXMaximumRatio',rhoXMaximumRatio, ...
        'rhoXMaximumSignedRelativeChange',rhoXMaximumSignedChange, ...
        'rhoXMaximumRelativeChange',rhoXMaximumChange, ...
        'wallRhoXMaximumOld',wallRhoXMaximumOld, ...
        'wallRhoXMaximumCandidate',wallRhoXMaximumCandidate, ...
        'wallRhoXMaximumRatio',wallRhoXMaximumRatio, ...
        'wallRhoXMaximumSignedRelativeChange', ...
            wallRhoXMaximumSignedChange, ...
        'wallRhoXMaximumRelativeChange',wallRhoXMaximumChange, ...
        'rhoYMaximumOld',rhoYMaximumOld, ...
        'rhoYMaximumCandidate',rhoYMaximumCandidate, ...
        'rhoYMaximumRatio',rhoYMaximumRatio, ...
        'rhoYMaximumSignedRelativeChange',rhoYMaximumSignedChange, ...
        'rhoYMaximumRelativeChange',rhoYMaximumChange, ...
        'xTransferRowMassRelativeDefect',xRowMassDefect, ...
        'yTransferColumnMassRelativeDefect',yColumnMassDefect, ...
        'forwardTotalMassRelativeDefect',forwardMassDefect, ...
        'roundTripRowMassRelativeDefect',roundTripRowDefect, ...
        'roundTripColumnMassRelativeDefect',roundTripColumnDefect, ...
        'roundTripTotalMassRelativeDefect',roundTripMassDefect, ...
        'conservationRelativeDefect',conservationDefect, ...
        'forwardRelativeRangeViolation',forwardRange, ...
        'roundTripRelativeRangeViolation',roundTripRange, ...
        'relativeRangeViolation',rangeViolation, ...
        'xSymmetryRelativeDefect',symmetryDefect, ...
        'xCoreCells',xCoreCells,'xLeftFrontCells',xFrontCells, ...
        'yCoreCells',yCoreCells,'minimumXCoreDx',minimumXCoreDx, ...
        'minimumXLeftFrontDx',minimumXFrontDx, ...
        'minimumYCoreDy',minimumYCoreDy, ...
        'yCoreWidth',yCoreWidth,'yCoreSource',yCoreSource);
end

aggregate = aggregate_metrics(metrics,options.quantile);
[errorScore,resolutionPenalty,objective] = ...
    score_aggregate(aggregate,options);
report.status = 'scored';
report.objective = objective;
report.errorScore = errorScore;
report.resolutionPenalty = resolutionPenalty;
report.selectedSnapshotCount = numel(metrics);
report.metrics = metrics;
report.aggregate = aggregate;
end

function options = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:gridlab:PairScoreOptions', ...
        'options must be a scalar structure.');
end
defaultLimits = struct('maxAdjacentCellRatio',1.08, ...
    'maxLogSpacingCurvature',0.03,'minStencilRcond',1e-9, ...
    'minQuadratureWeightRatio',1e-4);
defaultTargets = struct('fieldRelativeL2',2e-5, ...
    'wallRelativeL2',2e-5,'rhoXRelativeL2',5e-3, ...
    'rhoXMaximumRelativeChange',5e-3,'rhoYRelativeL2',5e-3, ...
    'conservationRelativeDefect',5e-12, ...
    'relativeRangeViolation',2e-4, ...
    'xSymmetryRelativeDefect',1e-10);
defaults = struct('trustedOnly',false,'profiles',[], ...
    'derivativeStencilWidth',7,'transferStencilWidth',6, ...
    'conservation','constant','quantile',0.9, ...
    'quantileWeight',0.25,'yCoreLevel',0.9, ...
    'minimumXCoreCells',12,'minimumXFrontCells',8, ...
    'minimumYCoreCells',8,'resolutionPenaltyWeight',4, ...
    'errorWeights',[1,0.6,1.2,1.4,1.2,0.25,0.5,0.25], ...
    'meshLimits',defaultLimits,'targets',defaultTargets);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:PairScoreOptions', ...
        'Unknown option(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(options,name)
        options.(name) = defaults.(name);
    end
end
if ~(islogical(options.trustedOnly) && isscalar(options.trustedOnly))
    error('ipm:gridlab:PairScoreOptions', ...
        'options.trustedOnly must be a logical scalar.');
end
validateattributes(options.derivativeStencilWidth,{'numeric'}, ...
    {'scalar','integer'},mfilename,'options.derivativeStencilWidth');
validateattributes(options.transferStencilWidth,{'numeric'}, ...
    {'scalar','integer'},mfilename,'options.transferStencilWidth');
validTuple = options.derivativeStencilWidth == 7 && ...
    options.transferStencilWidth == 6 || ...
    options.derivativeStencilWidth == 9 && ...
    options.transferStencilWidth == 8;
if ~validTuple
    error('ipm:gridlab:PairScoreOptions', ...
        ['The derivative/transfer stencil tuple must be 7/6 ' ...
        'or 9/8.']);
end
if ~(ischar(options.conservation) || ...
        (isstring(options.conservation) && isscalar(options.conservation)))
    error('ipm:gridlab:PairScoreOptions', ...
        'options.conservation must be ''none'' or ''constant''.');
end
options.conservation = lower(char(options.conservation));
if ~ismember(options.conservation,{'none','constant'})
    error('ipm:gridlab:PairScoreOptions', ...
        'options.conservation must be ''none'' or ''constant''.');
end
validateattributes(options.quantile,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<=',1},mfilename, ...
    'options.quantile');
validateattributes(options.quantileWeight,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename, ...
    'options.quantileWeight');
validateattributes(options.yCoreLevel,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<',1},mfilename, ...
    'options.yCoreLevel');
for field = {'minimumXCoreCells','minimumXFrontCells', ...
        'minimumYCoreCells'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','integer','positive'},mfilename,['options.' field{1}]);
end
validateattributes(options.resolutionPenaltyWeight,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename, ...
    'options.resolutionPenaltyWeight');
validateattributes(options.errorWeights,{'numeric'}, ...
    {'vector','numel',8,'real','finite','nonnegative'},mfilename, ...
    'options.errorWeights');
options.errorWeights = options.errorWeights(:)';
if ~(isempty(options.profiles) || ...
        (isstruct(options.profiles) && isscalar(options.profiles)))
    error('ipm:gridlab:PairScoreOptions', ...
        'options.profiles must be empty or a scalar structure.');
end
options.meshLimits = merge_named_struct( ...
    options.meshLimits,defaultLimits,'meshLimits');
options.targets = merge_named_struct( ...
    options.targets,defaultTargets,'targets');
end

function value = merge_named_struct(value,defaults,label)
if ~isstruct(value) || ~isscalar(value)
    error('ipm:gridlab:PairScoreOptions', ...
        'options.%s must be a scalar structure.',label);
end
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(value),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:PairScoreOptions', ...
        'Unknown options.%s field(s): %s.', ...
        label,strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(value,name)
        value.(name) = defaults.(name);
    end
    validateattributes(value.(name),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        ['options.' label '.' name]);
end
end

function [snapshots,xLimits,yLimits,datasetTag] = ...
        validate_dataset_header(dataset)
if ~isstruct(dataset) || ~isscalar(dataset) || ...
        ~isfield(dataset,'schemaVersion') || ...
        ~isnumeric(dataset.schemaVersion) || ...
        ~isscalar(dataset.schemaVersion) || ...
        ~isfinite(dataset.schemaVersion) || ...
        ~ismember(dataset.schemaVersion,[1,2]) || ...
        ~isfield(dataset,'kind') || ...
        ~strcmp(dataset.kind,'ipm_frozen_grid_dataset') || ...
        ~isfield(dataset,'snapshots') || isempty(dataset.snapshots)
    error('ipm:gridlab:PairScoreDataset', ...
        'Pass a nonempty version-1 or version-2 frozen grid dataset.');
end
snapshots = dataset.snapshots(:);
if ~isfield(dataset,'snapshotCount') || ...
        dataset.snapshotCount ~= numel(snapshots)
    error('ipm:gridlab:PairScoreDataset', ...
        'Dataset snapshotCount is inconsistent.');
end
required = {'datasetIndex','trusted','rho','x','y', ...
    'canonicalTime','physicalTime'};
for index = 1:numel(snapshots)
    missing = required(~isfield(snapshots(index),required));
    if ~isempty(missing)
        error('ipm:gridlab:PairScoreDataset', ...
            'Snapshot %d is missing: %s.',index,strjoin(missing,', '));
    end
    x = snapshots(index).x;
    y = snapshots(index).y;
    validateattributes(x,{'numeric'}, ...
        {'vector','real','finite','increasing'},mfilename,'snapshot.x');
    validateattributes(y,{'numeric'}, ...
        {'vector','real','finite','increasing'},mfilename,'snapshot.y');
    if ~isnumeric(snapshots(index).rho) || ...
            ~isreal(snapshots(index).rho) || ...
            ~isequal(size(snapshots(index).rho),[numel(y),numel(x)])
        error('ipm:gridlab:PairScoreDataset', ...
            'Snapshot %d rho must have size numel(y)-by-numel(x).',index);
    end
    if ~(islogical(snapshots(index).trusted) && ...
            isscalar(snapshots(index).trusted))
        error('ipm:gridlab:PairScoreDataset', ...
            'Snapshot %d trusted flag must be a logical scalar.',index);
    end
end
xFirst = double(snapshots(1).x(:)');
yFirst = double(snapshots(1).y(:));
xLimits = xFirst([1,end]);
yLimits = yFirst([1,end])';
for index = 1:numel(snapshots)
    assert_matching_domain(double(snapshots(index).x(:)'), ...
        double(snapshots(index).y(:)),xLimits,yLimits,index);
end
if isfield(dataset,'xLimits')
    declared = double(dataset.xLimits(:)');
    if numel(declared) ~= 2 || ...
            ~endpoints_match(declared,xLimits)
        error('ipm:gridlab:PairScoreDataset', ...
            'Dataset xLimits do not match its frozen snapshots.');
    end
end
if isfield(dataset,'yLimits')
    declared = double(dataset.yLimits(:)');
    if numel(declared) ~= 2 || ...
            ~endpoints_match(declared,yLimits)
        error('ipm:gridlab:PairScoreDataset', ...
            'Dataset yLimits do not match its frozen snapshots.');
    end
end
if isfield(dataset,'tag') && ...
        (ischar(dataset.tag) || ...
        (isstring(dataset.tag) && isscalar(dataset.tag)))
    datasetTag = char(dataset.tag);
else
    datasetTag = '';
end
end

function [xCandidate,yCandidate] = validate_candidate_axes( ...
        candidateX,candidateY,xLimits,yLimits,options)
xCandidate = double(candidateX(:)');
yCandidate = double(candidateY(:));
validateattributes(xCandidate,{'numeric'}, ...
    {'vector','real','finite','increasing'},mfilename,'candidateX');
validateattributes(yCandidate,{'numeric'}, ...
    {'vector','real','finite','increasing'},mfilename,'candidateY');
minimumNodes = max(options.derivativeStencilWidth, ...
    options.transferStencilWidth);
if numel(xCandidate) < minimumNodes || numel(yCandidate) < minimumNodes
    error('ipm:gridlab:PairScoreAxisSize', ...
        'Both candidate axes must contain at least %d nodes.',minimumNodes);
end
xTolerance = axis_tolerance(xCandidate);
if mod(numel(xCandidate),2) ~= 1 || ...
        max(abs(xCandidate+fliplr(xCandidate))) > xTolerance || ...
        abs(xCandidate((numel(xCandidate)+1)/2)) > xTolerance
    error('ipm:gridlab:PairScoreXAxis', ...
        'candidateX must have odd length and be symmetric about zero.');
end
yTolerance = axis_tolerance(yCandidate);
if abs(yCandidate(1)) > yTolerance || any(yCandidate < -yTolerance)
    error('ipm:gridlab:PairScoreYAxis', ...
        'candidateY must start at zero and remain nonnegative.');
end
if ~endpoints_match(xCandidate([1,end]),xLimits) || ...
        ~endpoints_match(yCandidate([1,end])',yLimits)
    error('ipm:gridlab:PairScoreDomain', ...
        'Candidate and frozen axes must have identical endpoints.');
end
end

function [weights,quality] = axis_quality(axis,options)
weights = quadrature_weights(axis,options.transferStencilWidth);
quality = ipm.mesh.quality( ...
    axis,options.derivativeStencilWidth,weights);
end

function weights = quadrature_weights(axis,stencilWidth)
if stencilWidth == 6
    weights = ipm.mesh.quadrature(axis);
else
    weights = ipm.mesh.quadrature(axis,8);
end
weights = double(weights(:));
end

function [admissible,reasons] = admit_axis(quality,weights,limits,prefix)
reasons = {};
if quality.maximumAdjacentCellRatio > limits.maxAdjacentCellRatio
    reasons{end+1} = [prefix ':adjacent_cell_ratio'];
end
if quality.maximumLogSpacingCurvature > ...
        limits.maxLogSpacingCurvature
    reasons{end+1} = [prefix ':log_spacing_curvature'];
end
if quality.minimumStencilRcond < limits.minStencilRcond
    reasons{end+1} = [prefix ':stencil_conditioning'];
end
if quality.minimumQuadratureWeightRatio < ...
        limits.minQuadratureWeightRatio || any(weights <= 0)
    reasons{end+1} = [prefix ':quadrature_margin'];
end
admissible = isempty(reasons);
end

function profiles = resolve_profiles(dataset,inputProfiles,snapshotCount)
if isempty(inputProfiles)
    profiles = ipm_gridlab_feature_profiles(dataset);
else
    profiles = inputProfiles;
end
if ~isstruct(profiles) || ~isscalar(profiles) || ...
        ~isfield(profiles,'schemaVersion') || ...
        ~isnumeric(profiles.schemaVersion) || ...
        ~isscalar(profiles.schemaVersion) || ...
        ~isfinite(profiles.schemaVersion) || ...
        ~ismember(profiles.schemaVersion,[1,2]) || ...
        ~isfield(profiles,'kind') || ...
        ~strcmp(profiles.kind,'ipm_frozen_grid_features') || ...
        ~isfield(profiles,'records') || ...
        numel(profiles.records) ~= snapshotCount
    error('ipm:gridlab:PairScoreProfiles', ...
        ['Profiles must be a matching version-1 or version-2 output ' ...
        'from ipm_gridlab_feature_profiles.']);
end
profiles.records = profiles.records(:);
end

function validate_snapshot_field(snapshot,index)
if any(~isfinite(snapshot.rho),'all')
    error('ipm:gridlab:PairScoreDataset', ...
        'Snapshot %d rho contains a nonfinite value.',index);
end
end

function assert_matching_domain(x,y,xLimits,yLimits,index)
if ~endpoints_match(x([1,end]),xLimits) || ...
        ~endpoints_match(y([1,end])',yLimits)
    error('ipm:gridlab:PairScoreDomain', ...
        'Frozen snapshot %d has inconsistent domain endpoints.',index);
end
xTolerance = axis_tolerance(x);
yTolerance = axis_tolerance(y);
if mod(numel(x),2) ~= 1 || ...
        max(abs(x+fliplr(x))) > xTolerance || ...
        abs(y(1)) > yTolerance || any(y < -yTolerance)
    error('ipm:gridlab:PairScoreDomain', ...
        'Frozen snapshot %d does not satisfy the x/y axis contract.',index);
end
end

function answer = endpoints_match(left,right)
left = double(left(:)');
right = double(right(:)');
if numel(left) ~= 2 || numel(right) ~= 2
    answer = false;
    return
end
scale = max([1,abs(left),abs(right)]);
answer = all(abs(left-right) <= 128*eps(scale));
end

function tolerance = axis_tolerance(axis)
tolerance = 1e3*eps(max(1,max(abs(axis))));
end

function [rhoNew,rhoAfterX] = transfer_x_then_y( ...
        rho,xOld,yOld,xNew,yNew,stencilWidth,conservation)
rhoAfterX = ipm.remesh.interpolate(xOld,rho,xNew,struct( ...
    'sampleDimension',2,'conservation',conservation, ...
    'stencilWidth',stencilWidth));
rhoNew = ipm.remesh.interpolate(yOld,rhoAfterX,yNew,struct( ...
    'sampleDimension',1,'conservation',conservation, ...
    'stencilWidth',stencilWidth));
end

function valuesOld = transfer_y_then_x( ...
        valuesNew,xNew,yNew,xOld,yOld,stencilWidth,conservation)
afterY = ipm.remesh.interpolate(yNew,valuesNew,yOld,struct( ...
    'sampleDimension',1,'conservation',conservation, ...
    'stencilWidth',stencilWidth));
valuesOld = ipm.remesh.interpolate(xNew,afterY,xOld,struct( ...
    'sampleDimension',2,'conservation',conservation, ...
    'stencilWidth',stencilWidth));
end

function validate_profile_record(profile,snapshot,index)
required = {'peakCenter','coreWidthLeft','coreWidthRight', ...
    'leftFrontCenter','leftFrontHalfWidth'};
missing = required(~isfield(profile,required));
if ~isempty(missing)
    error('ipm:gridlab:PairScoreProfiles', ...
        'Profile %d is missing: %s.',index,strjoin(missing,', '));
end
for field = required
    validateattributes(profile.(field{1}),{'numeric'}, ...
        {'scalar','real','finite','nonnegative'},mfilename, ...
        ['profile.' field{1}]);
end
if profile.coreWidthLeft <= 0 || profile.coreWidthRight <= 0 || ...
        profile.leftFrontHalfWidth <= 0
    error('ipm:gridlab:PairScoreProfiles', ...
        'Profile %d feature widths must be positive.',index);
end
hasSafetyLeft = isfield(profile,'safetyCoreWidthLeft');
hasSafetyRight = isfield(profile,'safetyCoreWidthRight');
if hasSafetyLeft ~= hasSafetyRight
    error('ipm:gridlab:PairScoreProfiles', ...
        ['Profile %d must provide both safetyCoreWidthLeft and ' ...
        'safetyCoreWidthRight.'],index);
end
if hasSafetyLeft
    validateattributes(profile.safetyCoreWidthLeft,{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        'profile.safetyCoreWidthLeft');
    validateattributes(profile.safetyCoreWidthRight,{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        'profile.safetyCoreWidthRight');
end
if isfield(profile,'safetyCoreCenter')
    validateattributes(profile.safetyCoreCenter,{'numeric'}, ...
        {'scalar','real','finite','nonnegative'},mfilename, ...
        'profile.safetyCoreCenter');
end
if isfield(profile,'datasetIndex') && ...
        (~isequal(profile.datasetIndex,snapshot.datasetIndex))
    error('ipm:gridlab:PairScoreProfiles', ...
        'Profile %d does not match its frozen snapshot.',index);
end
end

function [coreInterval,frontInterval] = ...
        x_feature_intervals(profile,halfWidth)
if isfield(profile,'safetyCoreWidthLeft')
    coreWidthLeft = profile.safetyCoreWidthLeft;
    coreWidthRight = profile.safetyCoreWidthRight;
    if isfield(profile,'safetyCoreCenter')
        coreCenter = profile.safetyCoreCenter;
    else
        coreCenter = profile.peakCenter;
    end
else
    coreWidthLeft = profile.coreWidthLeft;
    coreWidthRight = profile.coreWidthRight;
    coreCenter = profile.peakCenter;
end
coreInterval = [max(0,coreCenter-coreWidthLeft), ...
    min(halfWidth,coreCenter+coreWidthRight)];
frontInterval = [ ...
    max(0,profile.leftFrontCenter-profile.leftFrontHalfWidth), ...
    min(halfWidth,profile.leftFrontCenter+profile.leftFrontHalfWidth)];
end

function [width,widthSource] = y_core_width( ...
        profile,rhoX,x,y,levelFraction)
if isfield(profile,'yCoreWidth')
    validateattributes(profile.yCoreWidth,{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        'profile.yCoreWidth');
    width = min(double(profile.yCoreWidth),y(end));
    widthSource = 'profile';
    return
end
positive = find(x >= -axis_tolerance(x));
[wallPeak,relativeIndex] = max(abs(rhoX(1,positive)));
if wallPeak <= 100*eps(max(1,norm(rhoX(1,:),inf)))
    error('ipm:gridlab:PairScoreYCore', ...
        'The frozen wall rho_x feature is degenerate.');
end
column = positive(relativeIndex);
vertical = abs(rhoX(:,column));
[peak,peakIndex] = max(vertical);
level = levelFraction*peak;
crossing = y(end);
for probe = peakIndex+1:numel(y)
    if vertical(probe) <= level
        crossing = linear_crossing(y(probe-1),y(probe), ...
            vertical(probe-1),vertical(probe),level);
        break
    end
end
width = max(crossing-y(1),local_spacing(y,peakIndex));
width = min(width,y(end));
widthSource = 'snapshot';
end

function value = linear_crossing(x1,x2,y1,y2,target)
if y2 == y1
    value = 0.5*(x1+x2);
else
    fraction = (target-y1)/(y2-y1);
    fraction = min(max(fraction,0),1);
    value = x1+fraction*(x2-x1);
end
end

function spacing = local_spacing(axis,index)
if index <= 1
    spacing = axis(2)-axis(1);
elseif index >= numel(axis)
    spacing = axis(end)-axis(end-1);
else
    spacing = 0.5*(axis(index+1)-axis(index-1));
end
end

function [count,minimumSpacing] = interval_resolution(axis,interval)
widths = diff(axis);
% Fractional edge cells match diagnostics.peakResolution.gridPoints.
overlap = max(0,min(axis(2:end),interval(2)) - ...
    max(axis(1:end-1),interval(1)));
fractions = overlap./widths;
count = sum(fractions);
inside = overlap > 0;
if any(inside)
    minimumSpacing = min(widths(inside));
else
    minimumSpacing = inf;
end
end

function value = tensor_relative_l2(errorField,reference,qY,qX)
errorEnergy = qY(:)'*(errorField.^2)*qX(:);
referenceEnergy = qY(:)'*(reference.^2)*qX(:);
value = sqrt(max(errorEnergy,0)/max(referenceEnergy,eps));
end

function value = weighted_relative_l2(error,reference,weights)
errorEnergy = sum(weights(:)'.*(error.^2));
referenceEnergy = sum(weights(:)'.*(reference.^2));
value = sqrt(max(errorEnergy,0)/max(referenceEnergy,eps));
end

function value = relative_linf(error,reference)
value = norm(error(:),inf)/max(norm(reference(:),inf),eps);
end

function [absoluteChange,signedChange,ratio,oldMaximum,newMaximum] = ...
        maximum_relative_change(reference,candidate)
oldMaximum = max(abs(reference),[],'all');
newMaximum = max(abs(candidate),[],'all');
scale = max(oldMaximum,eps);
signedChange = (newMaximum-oldMaximum)/scale;
absoluteChange = abs(signedChange);
ratio = newMaximum/scale;
end

function value = relative_vector_defect(candidate,reference)
value = norm(candidate(:)-reference(:),inf) / ...
    max(norm(reference(:),inf),eps);
end

function value = relative_scalar_defect(candidate,reference)
value = abs(candidate-reference)/max(abs(reference),eps);
end

function violation = relative_range_violation(reference,candidate)
oldMinimum = min(reference,[],'all');
oldMaximum = max(reference,[],'all');
scale = max([oldMaximum-oldMinimum,abs(oldMinimum), ...
    abs(oldMaximum),eps]);
violation = max([oldMinimum-min(candidate,[],'all'), ...
    max(candidate,[],'all')-oldMaximum,0])/scale;
end

function aggregate = aggregate_metrics(metrics,probability)
errorNames = {'fieldRelativeL2','fieldRelativeLinf', ...
    'wallRelativeL2','wallRelativeLinf','rhoXRelativeL2', ...
    'rhoXRelativeLinf','rhoYRelativeL2','rhoYRelativeLinf', ...
    'wallRhoXRelativeL2','wallRhoXRelativeLinf', ...
    'rhoXMaximumRelativeChange','wallRhoXMaximumRelativeChange', ...
    'rhoYMaximumRelativeChange', ...
    'xTransferRowMassRelativeDefect', ...
    'yTransferColumnMassRelativeDefect', ...
    'forwardTotalMassRelativeDefect', ...
    'roundTripRowMassRelativeDefect', ...
    'roundTripColumnMassRelativeDefect', ...
    'roundTripTotalMassRelativeDefect', ...
    'conservationRelativeDefect','forwardRelativeRangeViolation', ...
    'roundTripRelativeRangeViolation','relativeRangeViolation', ...
    'xSymmetryRelativeDefect'};
worst = struct();
quantileValues = struct();
for index = 1:numel(errorNames)
    name = errorNames{index};
    values = [metrics.(name)];
    if any(~isfinite(values))
        error('ipm:gridlab:PairScoreMetric', ...
            'Metric %s contains a nonfinite value.',name);
    end
    worst.(name) = max(values);
    quantileValues.(name) = scalar_quantile(values,probability);
end
aggregate = struct('worst',worst,'quantile',quantileValues, ...
    'quantileProbability',probability, ...
    'minimumXCoreCells',min([metrics.xCoreCells]), ...
    'minimumXLeftFrontCells',min([metrics.xLeftFrontCells]), ...
    'minimumYCoreCells',min([metrics.yCoreCells]), ...
    'maximumMinimumXCoreDx',max([metrics.minimumXCoreDx]), ...
    'maximumMinimumXLeftFrontDx', ...
        max([metrics.minimumXLeftFrontDx]), ...
    'maximumMinimumYCoreDy',max([metrics.minimumYCoreDy]), ...
    'profileYCoreCount',nnz(strcmp({metrics.yCoreSource},'profile')), ...
    'derivedYCoreCount',nnz(strcmp({metrics.yCoreSource},'snapshot')));
end

function [errorScore,resolutionPenalty,objective] = ...
        score_aggregate(aggregate,options)
names = {'fieldRelativeL2','wallRelativeL2','rhoXRelativeL2', ...
    'rhoXMaximumRelativeChange','rhoYRelativeL2', ...
    'conservationRelativeDefect', ...
    'relativeRangeViolation','xSymmetryRelativeDefect'};
worstTerms = zeros(1,numel(names));
quantileTerms = zeros(1,numel(names));
for index = 1:numel(names)
    name = names{index};
    target = options.targets.(name);
    worstTerms(index) = aggregate.worst.(name)/target;
    quantileTerms(index) = aggregate.quantile.(name)/target;
end
errorScore = sum(options.errorWeights.*(log1p(worstTerms) + ...
    options.quantileWeight*log1p(quantileTerms)));
xCorePenalty = resolution_deficit(aggregate.minimumXCoreCells, ...
    options.minimumXCoreCells);
xFrontPenalty = resolution_deficit( ...
    aggregate.minimumXLeftFrontCells,options.minimumXFrontCells);
yCorePenalty = resolution_deficit(aggregate.minimumYCoreCells, ...
    options.minimumYCoreCells);
resolutionPenalty = options.resolutionPenaltyWeight*( ...
    xCorePenalty+xFrontPenalty+yCorePenalty);
objective = errorScore+resolutionPenalty;
if ~isfinite(objective)
    error('ipm:gridlab:PairScoreObjective', ...
        'The frozen pair objective is not finite.');
end
end

function value = resolution_deficit(actual,target)
value = max(0,target-actual)/target;
end

function value = scalar_quantile(values,probability)
values = sort(values(:));
position = 1+(numel(values)-1)*probability;
lower = floor(position);
upper = ceil(position);
if lower == upper
    value = values(lower);
else
    fraction = position-lower;
    value = (1-fraction)*values(lower)+fraction*values(upper);
end
end

function metrics = empty_metrics()
metrics = repmat(metric_template(),0,1);
end

function value = metric_template()
value = struct( ...
    'datasetIndex',0,'trusted',false, ...
    'canonicalTime',NaN,'physicalTime',NaN, ...
    'fieldRelativeL2',NaN,'fieldRelativeLinf',NaN, ...
    'wallRelativeL2',NaN,'wallRelativeLinf',NaN, ...
    'rhoXRelativeL2',NaN,'rhoXRelativeLinf',NaN, ...
    'rhoYRelativeL2',NaN,'rhoYRelativeLinf',NaN, ...
    'wallRhoXRelativeL2',NaN,'wallRhoXRelativeLinf',NaN, ...
    'rhoXMaximumOld',NaN,'rhoXMaximumCandidate',NaN, ...
    'rhoXMaximumRatio',NaN, ...
    'rhoXMaximumSignedRelativeChange',NaN, ...
    'rhoXMaximumRelativeChange',NaN, ...
    'wallRhoXMaximumOld',NaN,'wallRhoXMaximumCandidate',NaN, ...
    'wallRhoXMaximumRatio',NaN, ...
    'wallRhoXMaximumSignedRelativeChange',NaN, ...
    'wallRhoXMaximumRelativeChange',NaN, ...
    'rhoYMaximumOld',NaN,'rhoYMaximumCandidate',NaN, ...
    'rhoYMaximumRatio',NaN, ...
    'rhoYMaximumSignedRelativeChange',NaN, ...
    'rhoYMaximumRelativeChange',NaN, ...
    'xTransferRowMassRelativeDefect',NaN, ...
    'yTransferColumnMassRelativeDefect',NaN, ...
    'forwardTotalMassRelativeDefect',NaN, ...
    'roundTripRowMassRelativeDefect',NaN, ...
    'roundTripColumnMassRelativeDefect',NaN, ...
    'roundTripTotalMassRelativeDefect',NaN, ...
    'conservationRelativeDefect',NaN, ...
    'forwardRelativeRangeViolation',NaN, ...
    'roundTripRelativeRangeViolation',NaN, ...
    'relativeRangeViolation',NaN, ...
    'xSymmetryRelativeDefect',NaN, ...
    'xCoreCells',0,'xLeftFrontCells',0,'yCoreCells',0, ...
    'minimumXCoreDx',NaN,'minimumXLeftFrontDx',NaN, ...
    'minimumYCoreDy',NaN,'yCoreWidth',NaN,'yCoreSource','');
end
