function profiles = ipm_gridlab_feature_profiles(dataset,options)
%IPM_GRIDLAB_FEATURE_PROFILES Extract peak/front features from frozen fields.
%   The solver source omega=d_x rho is evaluated with the maintained
%   seven-point finite-difference operator.  A positive-half profile records
%   the wall source, its y-envelope, the steep-front indicator, and a
%   dimensionless teacher monitor for every frozen time.  The same record
%   also resolves the wall-normal source profile through the tracked x peak,
%   because y resolution is often the first continuation bottleneck.

if nargin < 2 || isempty(options)
    options = struct();
end
options = resolve_options(options);
validate_dataset(dataset);

template = struct( ...
    'datasetIndex',0,'sourceLabel','','trusted',false, ...
    'canonicalTime',NaN,'physicalTime',NaN, ...
    'xPositive',[],'wallSource',[],'sourceEnvelope',[], ...
    'frontIndicator',[],'teacherIndicator',[], ...
    'yPositive',[],'verticalSource',[],'verticalEnvelope',[], ...
    'verticalFrontIndicator',[],'verticalTeacherIndicator',[], ...
    'peakCenter',NaN,'peakValue',NaN, ...
    'coreWidthLeft',NaN,'coreWidthRight',NaN, ...
    'leftFrontCenter',NaN,'leftFrontHalfWidth',NaN, ...
    'rightFrontCenter',NaN,'rightFrontHalfWidth',NaN, ...
    'resolutionLevels',[],'xLevelBounds',[],'xLevelWidths',[], ...
    'safetyCoreCenter',NaN,'safetyCoreWidthLeft',NaN, ...
    'safetyCoreWidthRight',NaN, ...
    'yPeakCenter',NaN,'yPeakValue',NaN,'yCoreWidth',NaN, ...
    'yHalfHeightWidth',NaN,'yLevelBounds',[],'yLevelWidths',[], ...
    'yEnvelopeWidth',NaN,'rescaledRhoXMaximum',NaN, ...
    'rescaledRhoYMaximum',NaN,'physicalRhoXMaximum',NaN, ...
    'physicalRhoYMaximum',NaN);
records = repmat(template,dataset.snapshotCount,1);

for index = 1:dataset.snapshotCount
    snapshot = dataset.snapshots(index);
    x = double(snapshot.x(:)');
    y = double(snapshot.y(:));
    rho = double(snapshot.rho);
    check_symmetric_axis(x);
    check_vertical_axis(y);
    xStencilWidth = odd_stencil_width(options.stencilWidth,numel(x));
    yStencilWidth = odd_stencil_width(options.stencilWidth,numel(y));
    Dx = ipm.mesh.fdMatrix(x,1,xStencilWidth);
    Dy = ipm.mesh.fdMatrix(y,1,yStencilWidth);
    omega = rho*Dx';
    rhoY = Dy*rho;
    wallSource = symmetric_average(abs(omega(1,:)));
    sourceEnvelope = symmetric_average(max(abs(omega),[],1));
    wallSource = smooth_signal(wallSource,options.smoothingSpan);
    sourceEnvelope = smooth_signal(sourceEnvelope,options.smoothingSpan);
    wallDerivative = (Dx*wallSource(:)).';
    frontIndicator = smooth_signal(abs(wallDerivative), ...
        options.smoothingSpan);

    tolerance = 100*eps(max(1,max(abs(x))));
    positive = x >= -tolerance;
    s = x(positive);
    s(abs(s) <= tolerance) = 0;
    wallPositive = wallSource(positive);
    rawWallPositive = max(omega(1,positive),0);
    envelopePositive = sourceEnvelope(positive);
    frontPositive = frontIndicator(positive);
    [peakCenter,peakValue,peakIndex,widthLeft,widthRight] = ...
        peak_geometry(s,wallPositive,envelopePositive,options.coreLevel);
    [leftCenter,leftHalfWidth] = front_geometry( ...
        s,frontPositive,1,max(peakIndex-1,1),peakCenter);
    [rightCenter,rightHalfWidth] = front_geometry( ...
        s,frontPositive,min(peakIndex+1,numel(s)),numel(s),peakCenter);
    horizontalMeasurement = ipm.diagnostics.peakResolution( ...
        rawWallPositive,s,options.resolutionLevels);
    safetyLevelIndex = nearest_level( ...
        options.resolutionLevels,options.safetyCoreLevel);
    halfHeightIndex = nearest_level(options.resolutionLevels,0.5);
    horizontalCoreBounds = horizontalMeasurement.bounds( ...
        safetyLevelIndex,:);
    safetyCoreCenter = s(horizontalMeasurement.peakIndex);
    safetyCoreWidthLeft = max( ...
        safetyCoreCenter-horizontalCoreBounds(1), ...
        local_spacing(s,horizontalMeasurement.peakIndex));
    safetyCoreWidthRight = max( ...
        horizontalCoreBounds(2)-safetyCoreCenter, ...
        local_spacing(s,horizontalMeasurement.peakIndex));

    positiveIndices = find(positive);
    peakColumn = positiveIndices(horizontalMeasurement.peakIndex);
    rawVerticalSource = abs(omega(:,peakColumn))';
    verticalSource = smooth_signal(rawVerticalSource, ...
        options.smoothingSpan);
    verticalEnvelope = smooth_signal(max(abs(omega),[],2)', ...
        options.smoothingSpan);
    verticalDerivative = (Dy*verticalSource(:)).';
    verticalFront = smooth_signal(abs(verticalDerivative), ...
        options.smoothingSpan);
    verticalMeasurement = ipm.diagnostics.peakResolution( ...
        rawVerticalSource,y,options.resolutionLevels);
    envelopeMeasurement = ipm.diagnostics.peakResolution( ...
        verticalEnvelope,y,0.5);
    yPeakCenter = y(verticalMeasurement.peakIndex);
    yCoreWidth = max(verticalMeasurement.widths(safetyLevelIndex), ...
        local_spacing(y,verticalMeasurement.peakIndex));
    yHalfHeightWidth = max(verticalMeasurement.widths(halfHeightIndex), ...
        local_spacing(y, ...
        verticalMeasurement.peakIndex));
    yEnvelopeWidth = max(envelopeMeasurement.widths,local_spacing(y, ...
        envelopeMeasurement.peakIndex));

    normalizedWall = normalize_profile(wallPositive);
    normalizedEnvelope = normalize_profile(envelopePositive);
    normalizedFront = normalize_profile(frontPositive);
    power = options.combinePower;
    combined = ( ...
        (options.wallWeight*normalizedWall).^power + ...
        (options.envelopeWeight*normalizedEnvelope).^power + ...
        (options.frontWeight*normalizedFront).^power).^(1/power);
    combined = normalize_profile(combined);
    teacher = 1+options.teacherContrast*combined;
    normalizedVertical = normalize_profile(verticalSource);
    normalizedVerticalEnvelope = normalize_profile(verticalEnvelope);
    normalizedVerticalFront = normalize_profile(verticalFront);
    verticalCombined = ( ...
        (options.verticalSourceWeight*normalizedVertical).^power + ...
        (options.verticalEnvelopeWeight*normalizedVerticalEnvelope).^power + ...
        (options.verticalFrontWeight*normalizedVerticalFront).^power ...
        ).^(1/power);
    verticalTeacher = 1+options.teacherContrast* ...
        normalize_profile(verticalCombined);
    [xScale,yScale] = derivative_scales(snapshot);

    records(index) = struct( ...
        'datasetIndex',snapshot.datasetIndex, ...
        'sourceLabel',snapshot.sourceLabel,'trusted',snapshot.trusted, ...
        'canonicalTime',snapshot.canonicalTime, ...
        'physicalTime',snapshot.physicalTime, ...
        'xPositive',s,'wallSource',wallPositive, ...
        'sourceEnvelope',envelopePositive, ...
        'frontIndicator',frontPositive,'teacherIndicator',teacher, ...
        'yPositive',y','verticalSource',verticalSource, ...
        'verticalEnvelope',verticalEnvelope, ...
        'verticalFrontIndicator',verticalFront, ...
        'verticalTeacherIndicator',verticalTeacher, ...
        'peakCenter',peakCenter,'peakValue',peakValue, ...
        'coreWidthLeft',widthLeft,'coreWidthRight',widthRight, ...
        'leftFrontCenter',leftCenter, ...
        'leftFrontHalfWidth',leftHalfWidth, ...
        'rightFrontCenter',rightCenter, ...
        'rightFrontHalfWidth',rightHalfWidth, ...
        'resolutionLevels',options.resolutionLevels, ...
        'xLevelBounds',horizontalMeasurement.bounds, ...
        'xLevelWidths',horizontalMeasurement.widths, ...
        'safetyCoreCenter',safetyCoreCenter, ...
        'safetyCoreWidthLeft',safetyCoreWidthLeft, ...
        'safetyCoreWidthRight',safetyCoreWidthRight, ...
        'yPeakCenter',yPeakCenter, ...
        'yPeakValue',verticalMeasurement.peak, ...
        'yCoreWidth',yCoreWidth,'yHalfHeightWidth',yHalfHeightWidth, ...
        'yLevelBounds',verticalMeasurement.bounds, ...
        'yLevelWidths',verticalMeasurement.widths, ...
        'yEnvelopeWidth',yEnvelopeWidth, ...
        'rescaledRhoXMaximum',max(abs(omega),[],'all'), ...
        'rescaledRhoYMaximum',max(abs(rhoY),[],'all'), ...
        'physicalRhoXMaximum',xScale*max(abs(omega),[],'all'), ...
        'physicalRhoYMaximum',yScale*max(abs(rhoY),[],'all'));
end

profiles = struct('schemaVersion',2, ...
    'kind','ipm_frozen_grid_features', ...
    'datasetTag',dataset.tag,'count',numel(records), ...
    'options',options,'records',records);
end

function options = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:gridlab:FeatureOptions', ...
        'options must be a scalar structure.');
end
defaults = struct('stencilWidth',7,'smoothingSpan',5, ...
    'coreLevel',0.5,'wallWeight',1,'envelopeWeight',0.55, ...
    'frontWeight',0.85,'resolutionLevels',[0.1,0.5,0.9], ...
    'safetyCoreLevel',0.9, ...
    'verticalSourceWeight',1,'verticalEnvelopeWeight',0.55, ...
    'verticalFrontWeight',0.5, ...
    'combinePower',4,'teacherContrast',12);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:FeatureOptions', ...
        'Unknown option(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(options,name)
        options.(name) = defaults.(name);
    end
end
validateattributes(options.stencilWidth,{'numeric'}, ...
    {'scalar','integer','>=',5},mfilename,'options.stencilWidth');
validateattributes(options.smoothingSpan,{'numeric'}, ...
    {'scalar','integer','positive'},mfilename,'options.smoothingSpan');
validateattributes(options.coreLevel,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<',1},mfilename,'options.coreLevel');
validateattributes(options.resolutionLevels,{'numeric'}, ...
    {'vector','real','finite','>',0,'<',1,'increasing'},mfilename, ...
    'options.resolutionLevels');
options.resolutionLevels = double(options.resolutionLevels(:)');
validateattributes(options.safetyCoreLevel,{'numeric'}, ...
    {'scalar','real','finite','>',0,'<',1},mfilename, ...
    'options.safetyCoreLevel');
for field = {'wallWeight','envelopeWeight','frontWeight', ...
        'verticalSourceWeight','verticalEnvelopeWeight', ...
        'verticalFrontWeight','teacherContrast'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','real','finite','nonnegative'},mfilename, ...
        ['options.' field{1}]);
end
validateattributes(options.combinePower,{'numeric'}, ...
    {'scalar','real','finite','>=',1},mfilename,'options.combinePower');
end

function validate_dataset(dataset)
if ~isstruct(dataset) || ~isscalar(dataset) || ...
        ~isfield(dataset,'schemaVersion') || ...
        ~ismember(dataset.schemaVersion,[1,2]) || ...
        ~isfield(dataset,'kind') || ...
        ~strcmp(dataset.kind,'ipm_frozen_grid_dataset') || ...
        ~isfield(dataset,'snapshots') || isempty(dataset.snapshots)
    error('ipm:gridlab:FeatureDataset', ...
        'Pass a nonempty dataset from ipm_gridlab_collect_dataset.');
end
if ~isfield(dataset,'snapshotCount') || ...
        dataset.snapshotCount ~= numel(dataset.snapshots)
    error('ipm:gridlab:FeatureDataset', ...
        'Dataset snapshotCount is inconsistent.');
end
end

function check_vertical_axis(y)
tolerance = 1e3*eps(max(1,max(abs(y))));
if numel(y) < 5 || any(diff(y) <= 0) || abs(y(1)) > tolerance || ...
        y(end) <= 0
    error('ipm:gridlab:FeatureAxis', ...
        'Frozen y axes must be increasing positive-half axes starting at 0.');
end
end

function width = odd_stencil_width(requested,nodeCount)
width = min(requested,nodeCount);
if mod(width,2) ~= 1
    width = width-1;
end
end

function index = nearest_level(levels,target)
[distance,index] = min(abs(levels-target));
if distance > 100*eps(max(1,abs(target)))
    error('ipm:gridlab:FeatureOptions', ...
        'options.resolutionLevels must contain %.16g.',target);
end
end

function [xScale,yScale] = derivative_scales(snapshot)
xScale = NaN;
yScale = NaN;
if ~isfield(snapshot,'scale') || ~isstruct(snapshot.scale) || ...
        ~all(isfield(snapshot.scale,{'Cx','Cy','Comega'}))
    return
end
values = [snapshot.scale.Cx,snapshot.scale.Cy,snapshot.scale.Comega];
if any(~isfinite(values)) || any(values <= 0)
    return
end
xScale = snapshot.scale.Cx/snapshot.scale.Comega;
yScale = snapshot.scale.Cy/snapshot.scale.Comega;
end

function check_symmetric_axis(x)
tolerance = 1e3*eps(max(1,max(abs(x))));
if mod(numel(x),2) ~= 1 || any(diff(x) <= 0) || ...
        max(abs(x+fliplr(x))) > tolerance
    error('ipm:gridlab:FeatureAxis', ...
        'Frozen x axes must be odd, increasing, and symmetric.');
end
end

function values = symmetric_average(values)
values = 0.5*(values+fliplr(values));
end

function values = smooth_signal(values,span)
span = min(span,numel(values));
if mod(span,2) == 0
    span = max(span-1,1);
end
if span > 1
    values = movmean(values,span,'Endpoints','shrink');
end
end

function values = normalize_profile(values)
scale = max(values);
if scale <= 100*eps(max(1,norm(values,inf)))
    values = zeros(size(values));
else
    values = values/scale;
end
end

function [center,value,index,leftWidth,rightWidth] = ...
        peak_geometry(s,wall,envelope,levelFraction)
[value,index] = max(wall);
signal = wall;
if value <= 100*eps(max(1,max(envelope)))
    [value,index] = max(envelope);
    signal = envelope;
end
if value <= 0
    error('ipm:gridlab:FeaturePeak', ...
        'The frozen field has no nonzero x-source feature.');
end
center = s(index);
level = levelFraction*value;
leftCross = crossing_left(s,signal,index,level);
rightCross = crossing_right(s,signal,index,level);
localSpacing = local_spacing(s,index);
leftWidth = max(center-leftCross,localSpacing);
rightWidth = max(rightCross-center,localSpacing);
end

function [center,halfWidth] = front_geometry(s,indicator,first,last,fallback)
if last < first || isempty(indicator(first:last)) || ...
        max(indicator(first:last)) <= 0
    center = fallback;
    halfWidth = local_spacing(s,min(max(first,1),numel(s)));
    return
end
[peak,relative] = max(indicator(first:last));
index = first+relative-1;
center = s(index);
left = crossing_left(s,indicator,index,0.5*peak);
right = crossing_right(s,indicator,index,0.5*peak);
halfWidth = max(0.5*(right-left),local_spacing(s,index));
end

function crossing = crossing_left(s,signal,index,level)
crossing = s(1);
for probe = index-1:-1:1
    if signal(probe) <= level
        crossing = linear_crossing(s(probe),s(probe+1), ...
            signal(probe),signal(probe+1),level);
        return
    end
end
end

function crossing = crossing_right(s,signal,index,level)
crossing = s(end);
for probe = index+1:numel(s)
    if signal(probe) <= level
        crossing = linear_crossing(s(probe-1),s(probe), ...
            signal(probe-1),signal(probe),level);
        return
    end
end
end

function x = linear_crossing(x1,x2,y1,y2,target)
if y2 == y1
    x = 0.5*(x1+x2);
else
    fraction = (target-y1)/(y2-y1);
    fraction = min(max(fraction,0),1);
    x = x1+fraction*(x2-x1);
end
end

function spacing = local_spacing(s,index)
if index <= 1
    spacing = s(2)-s(1);
elseif index >= numel(s)
    spacing = s(end)-s(end-1);
else
    spacing = 0.5*(s(index+1)-s(index-1));
end
end
