function [axis,info] = ipm_gridlab_equalize_axis( ...
        referenceAxis,intervals,targetCells,options)
%IPM_GRIDLAB_EQUALIZE_AXIS Spread feature compression over a global ramp.
%   [AXIS,INFO] = IPM_GRIDLAB_EQUALIZE_AXIS(REFERENCE,INTERVALS,TARGETS,OPTS)
%   modifies the admitted reference cell widths according to
%
%     log(h_new) = log(h_reference) - A exp(-(d(u,F)/sigma)^p),
%
%   where u=(i-1/2)/N is the global reference-cell coordinate and F is the
%   set of focus centres.  The widths are renormalized to the unchanged
%   endpoint.  Thus the additional compression decays across many adjacent
%   cells instead of creating one abrupt local density jump.
%   For symmetric interior features, OPTS.anchorPhysicalPosition may name
%   one strictly positive physical coordinate that must remain fixed by the
%   deformation.  A smooth monotone cosine log-width correction
%
%     beta (psi(u_cell)-psi(u_anchor)),
%     psi(u) = (1-cos(pi*u))/2,
%
%   is then solved at every amplitude so that the reference computational
%   coordinate of the anchor maps back to its original physical position.
%   The cosine basis has zero slope at both ends of the positive half-axis,
%   so its even mirror introduces no slope corner at the symmetry point.
%   On that anchored path, d is evaluated in the smooth even coordinate
%
%     r(u) = u tanh(u/delta) / tanh(u_anchor/delta),
%
%   with delta=u_anchor/8.  Thus the mirrored compression kernel is smooth
%   at the origin while its focus remains exactly at u_anchor.
%   Leaving the option empty retains the original unanchored construction.
%   OPTS.kernelKind='corridor' instead constructs an anchored soft plateau
%   spanning the outer endpoints of the union of INTERVALS.  If rL and rR
%   are those endpoints mapped through the reference coordinate and r(u),
%   its compression kernel is
%
%     P = (tanh((r-(rL-e*delta))/delta) ...
%          -tanh((r-(rR+e*delta))/delta))/2,
%
%   where delta=OPTS.corridorShoulderCells/NpositiveCell and
%   e=OPTS.corridorExpansionShoulders.  This optional construction requires
%   symmetric geometry and an enabled physical anchor.  The default
%   Gaussian construction retains its original arithmetic.
%
%   INTERVALS is K-by-2 on the nonnegative half-axis and TARGETS is scalar
%   or length K.  OPTS.geometry is 'positive' for a [0,L] axis or
%   'symmetric' for an odd [-L,L] axis.  The smallest amplitude meeting all
%   targets is found without ever relaxing a mesh limit.  If the targets
%   are infeasible, AXIS is the strongest admitted trial and INFO records
%   the achieved boundary and the limiting gate.

if nargin < 4 || isempty(options)
    options = struct();
end
options = resolve_options(options);
[referencePositive,geometry] = validate_reference( ...
    referenceAxis,options.geometry);
[intervals,targetCells] = validate_targets( ...
    intervals,targetCells,referencePositive(end));

referenceCoordinate = linspace(0,1,numel(referencePositive));
focusCoordinate = interp1(referencePositive,referenceCoordinate, ...
    options.focusCenters,'linear');
focusCoordinate = min(max(focusCoordinate,0),1);
cellCoordinate = ((1:numel(referencePositive)-1)-0.5) / ...
    (numel(referencePositive)-1);
anchor = configure_anchor(referencePositive,geometry, ...
    options.anchorPhysicalPosition);
if strcmp(options.kernelKind,'gaussian')
    if anchor.enabled
        kernelCellCoordinate = smooth_even_coordinate( ...
            cellCoordinate,anchor);
        kernelFocusCoordinate = smooth_even_coordinate( ...
            focusCoordinate,anchor);
        distance = min(abs(kernelCellCoordinate(:)- ...
            kernelFocusCoordinate(:)'),[],2)';
        anchor.kernelFocusCoordinate = kernelFocusCoordinate;
    else
        % Preserve the original kernel arithmetic on the default path.
        distance = min(abs(cellCoordinate(:)-focusCoordinate(:)'),[],2)';
        anchor.kernelFocusCoordinate = focusCoordinate;
    end
    kernel = exp(-(distance/options.sigma).^options.power);
    kernelModel = empty_corridor_model(options);
else
    if ~strcmp(geometry,'symmetric') || ~anchor.enabled
        error('ipm:gridlab:EqualizeCorridorConfiguration', ...
            ['kernelKind corridor requires symmetric geometry and a ' ...
            'valid anchorPhysicalPosition.']);
    end
    positiveCellCount = numel(referencePositive)-1;
    physicalBounds = [min(intervals(:,1)),max(intervals(:,2))];
    referenceBounds = interp1(referencePositive,referenceCoordinate, ...
        physicalBounds,'linear');
    kernelCellCoordinate = smooth_even_coordinate( ...
        cellCoordinate,anchor);
    kernelBounds = smooth_even_coordinate(referenceBounds,anchor);
    shoulderDelta = options.corridorShoulderCells/positiveCellCount;
    expandedKernelBounds = kernelBounds+ ...
        options.corridorExpansionShoulders*shoulderDelta*[-1,1];
    kernel = 0.5*( ...
        tanh((kernelCellCoordinate-expandedKernelBounds(1))/ ...
            shoulderDelta)- ...
        tanh((kernelCellCoordinate-expandedKernelBounds(2))/ ...
            shoulderDelta));
    anchor.kernelFocusCoordinate = [];
    kernelModel = struct( ...
        'kind',options.kernelKind, ...
        'physicalBounds',physicalBounds, ...
        'referenceCoordinateBounds',referenceBounds, ...
        'kernelCoordinateBounds',kernelBounds, ...
        'expandedKernelCoordinateBounds',expandedKernelBounds, ...
        'delta',shoulderDelta, ...
        'shoulderCells',options.corridorShoulderCells, ...
        'expansionShoulders',options.corridorExpansionShoulders, ...
        'positiveCellCount',positiveCellCount);
end

baseline = evaluate_trial(0,referencePositive,geometry,kernel,anchor, ...
    intervals,targetCells,options.meshLimits);
trace = trial_summary(baseline);
if ~baseline.admissible
    axis = baseline.axis;
    info = make_info('reference_inadmissible',baseline,trace, ...
        intervals,targetCells,focusCoordinate,kernel,kernelModel,anchor, ...
        options);
    return
end
if baseline.targetMet
    axis = baseline.axis;
    info = make_info('target_met_by_reference',baseline,trace, ...
        intervals,targetCells,focusCoordinate,kernel,kernelModel,anchor, ...
        options);
    return
end

lower = baseline;
amplitude = min(options.initialAmplitude,options.maximumAmplitude);
while true
    upper = evaluate_trial(amplitude,referencePositive,geometry,kernel, ...
        anchor, ...
        intervals,targetCells,options.meshLimits);
    trace(end+1,1) = trial_summary(upper); %#ok<AGROW>
    if upper.targetMet || ~upper.admissible
        [selected,status,bisectionTrace] = resolve_bracket( ...
            lower,upper,referencePositive,geometry,kernel,anchor, ...
            intervals,targetCells,options);
        trace = [trace;bisectionTrace]; %#ok<AGROW>
        axis = selected.axis;
        info = make_info(status,selected,trace,intervals,targetCells, ...
            focusCoordinate,kernel,kernelModel,anchor,options);
        return
    end
    lower = upper;
    if amplitude >= options.maximumAmplitude
        axis = lower.axis;
        info = make_info('maximum_amplitude_reached',lower,trace, ...
            intervals,targetCells,focusCoordinate,kernel,kernelModel, ...
            anchor,options);
        return
    end
    amplitude = min(options.maximumAmplitude,2*amplitude);
end
end

function options = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:gridlab:EqualizeOptions', ...
        'options must be a scalar structure.');
end
defaultLimits = struct('maxAdjacentCellRatio',1.08, ...
    'maxLogSpacingCurvature',0.03,'minStencilRcond',1e-9, ...
    'minQuadratureWeightRatio',1e-4);
defaults = struct('geometry','positive','focusCenters',0, ...
    'sigma',0.35,'power',1,'initialAmplitude',0.25, ...
    'maximumAmplitude',16,'amplitudeTolerance',1e-9, ...
    'maxIterations',80,'anchorPhysicalPosition',[], ...
    'kernelKind','gaussian','corridorShoulderCells',24, ...
    'corridorExpansionShoulders',2, ...
    'meshLimits',defaultLimits);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:EqualizeOptions', ...
        'Unknown option(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(options,name)
        options.(name) = defaults.(name);
    end
end
if ~(ischar(options.geometry) || ...
        (isstring(options.geometry) && isscalar(options.geometry)))
    error('ipm:gridlab:EqualizeOptions', ...
        'options.geometry must be positive or symmetric.');
end
options.geometry = validatestring(options.geometry, ...
    {'positive','symmetric'},mfilename,'options.geometry');
if ~(ischar(options.kernelKind) || ...
        (isstring(options.kernelKind) && isscalar(options.kernelKind)))
    error('ipm:gridlab:EqualizeOptions', ...
        'options.kernelKind must be gaussian or corridor.');
end
options.kernelKind = validatestring(options.kernelKind, ...
    {'gaussian','corridor'},mfilename,'options.kernelKind');
validateattributes(options.focusCenters,{'numeric'}, ...
    {'vector','nonempty','real','finite','nonnegative'},mfilename, ...
    'options.focusCenters');
options.focusCenters = double(options.focusCenters(:)');
for field = {'sigma','power','initialAmplitude','maximumAmplitude', ...
        'amplitudeTolerance'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        ['options.' field{1}]);
end
if options.initialAmplitude > options.maximumAmplitude
    error('ipm:gridlab:EqualizeOptions', ...
        'initialAmplitude must not exceed maximumAmplitude.');
end
validateattributes(options.maxIterations,{'numeric'}, ...
    {'scalar','integer','positive'},mfilename,'options.maxIterations');
validateattributes(options.corridorShoulderCells,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename, ...
    'options.corridorShoulderCells');
validateattributes(options.corridorExpansionShoulders,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename, ...
    'options.corridorExpansionShoulders');
if ~isnumeric(options.anchorPhysicalPosition) || ...
        ~(isempty(options.anchorPhysicalPosition) || ...
        (isscalar(options.anchorPhysicalPosition) && ...
        isreal(options.anchorPhysicalPosition) && ...
        isfinite(options.anchorPhysicalPosition)))
    error('ipm:gridlab:EqualizeOptions', ...
        'options.anchorPhysicalPosition must be empty or a real scalar.');
end
options.anchorPhysicalPosition = ...
    double(options.anchorPhysicalPosition);
options.meshLimits = merge_limits(options.meshLimits,defaultLimits);
end

function model = empty_corridor_model(options)
model = struct( ...
    'kind',options.kernelKind, ...
    'physicalBounds',[], ...
    'referenceCoordinateBounds',[], ...
    'kernelCoordinateBounds',[], ...
    'expandedKernelCoordinateBounds',[], ...
    'delta',NaN, ...
    'shoulderCells',options.corridorShoulderCells, ...
    'expansionShoulders',options.corridorExpansionShoulders, ...
    'positiveCellCount',NaN);
end

function limits = merge_limits(limits,defaults)
if ~isstruct(limits) || ~isscalar(limits)
    error('ipm:gridlab:EqualizeOptions', ...
        'options.meshLimits must be a scalar structure.');
end
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(limits),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:EqualizeOptions', ...
        'Unknown meshLimits field(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(limits,name)
        limits.(name) = defaults.(name);
    end
    validateattributes(limits.(name),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        ['options.meshLimits.' name]);
end
end

function [positive,geometry] = validate_reference(axis,geometry)
axis = double(axis(:)');
validateattributes(axis,{'numeric'}, ...
    {'vector','real','finite','increasing'},mfilename,'referenceAxis');
if strcmp(geometry,'positive')
    tolerance = 1e3*eps(max(1,max(abs(axis))));
    if numel(axis) < 7 || abs(axis(1)) > tolerance || axis(end) <= 0
        error('ipm:gridlab:EqualizeReference', ...
            'A positive reference axis must increase from zero.');
    end
    positive = axis;
else
    tolerance = 1e3*eps(max(1,max(abs(axis))));
    if numel(axis) < 13 || mod(numel(axis),2) ~= 1 || ...
            max(abs(axis+fliplr(axis))) > tolerance
        error('ipm:gridlab:EqualizeReference', ...
            'A symmetric reference axis must be odd and mirror exactly.');
    end
    positive = axis((numel(axis)+1)/2:end);
end
if any(diff(positive) <= 0)
    error('ipm:gridlab:EqualizeReference', ...
        'The positive reference half must be strictly increasing.');
end
end

function [intervals,targets] = validate_targets(intervals,targets,limit)
validateattributes(intervals,{'numeric'}, ...
    {'2d','real','finite','nonnegative'},mfilename,'intervals');
if size(intervals,2) ~= 2 || isempty(intervals) || ...
        any(intervals(:,2) <= intervals(:,1)) || ...
        any(intervals(:,2) > limit)
    error('ipm:gridlab:EqualizeTargets', ...
        'intervals must be nonempty increasing pairs inside [0,L].');
end
intervals = double(intervals);
validateattributes(targets,{'numeric'}, ...
    {'vector','nonempty','real','finite','positive'},mfilename, ...
    'targetCells');
targets = double(targets(:));
if isscalar(targets)
    targets = repmat(targets,size(intervals,1),1);
elseif numel(targets) ~= size(intervals,1)
    error('ipm:gridlab:EqualizeTargets', ...
        'targetCells must be scalar or match the interval count.');
end
end

function anchor = configure_anchor(referencePositive,geometry,position)
cellCount = numel(referencePositive)-1;
cellCoordinate = ((1:cellCount)-0.5)/cellCount;
anchor = struct( ...
    'enabled',false,'physicalPosition',[], ...
    'referenceCoordinate',[], ...
    'cellCoordinate',cellCoordinate, ...
    'tilt',zeros(1,cellCount), ...
    'tolerance',NaN,'maximumAbsBeta',256,'maxIterations',96, ...
    'correctionBasis', ...
        'beta*(psi(u_cell)-psi(u_anchor)), psi=(1-cos(pi*u))/2', ...
    'kernelCoordinateBasis','reference_coordinate_u', ...
    'kernelSmoothingScale',NaN,'kernelFocusCoordinate',[]);
if isempty(position)
    return
end
if ~strcmp(geometry,'symmetric')
    error('ipm:gridlab:EqualizeAnchorGeometry', ...
        ['anchorPhysicalPosition is supported only for symmetric ' ...
        'interior equalization.']);
end
limit = referencePositive(end);
if position <= 0 || position >= limit
    error('ipm:gridlab:EqualizeAnchorPosition', ...
        'anchorPhysicalPosition must lie strictly inside (0,L).');
end
referenceCoordinate = linspace(0,1,numel(referencePositive));
coordinate = interp1(referencePositive,referenceCoordinate,position, ...
    'linear');
if ~(isfinite(coordinate) && coordinate > 0 && coordinate < 1)
    error('ipm:gridlab:EqualizeAnchorPosition', ...
        'Could not locate the anchor inside the reference half-axis.');
end
anchor.enabled = true;
anchor.physicalPosition = position;
anchor.referenceCoordinate = coordinate;
psiCell = 0.5*(1-cos(pi*anchor.cellCoordinate));
psiAnchor = 0.5*(1-cos(pi*coordinate));
anchor.tilt = psiCell-psiAnchor;
anchor.tolerance = 1024*eps(max(1,limit));
anchor.kernelCoordinateBasis = ...
    'r(u)=u*tanh(u/delta)/tanh(u_anchor/delta)';
anchor.kernelSmoothingScale = max(coordinate/8,realmin);
end

function coordinate = smooth_even_coordinate(input,anchor)
normalization = tanh( ...
    anchor.referenceCoordinate/anchor.kernelSmoothingScale);
coordinate = input.*tanh(input/anchor.kernelSmoothingScale)/ ...
    normalization;
end

function trial = evaluate_trial( ...
        amplitude,referencePositive,geometry,kernel,anchor, ...
        intervals,targets,limits)
referenceWidths = diff(referencePositive);
logWidths = log(referenceWidths)-amplitude*kernel;
if anchor.enabled
    [widths,anchorSolution] = solve_anchor_correction( ...
        logWidths,referencePositive(end),anchor);
else
    % Preserve the original operation order exactly on the default path.
    widths = exp(logWidths-max(logWidths));
    widths = referencePositive(end)*widths/sum(widths);
    anchorSolution = empty_anchor_solution();
end
positive = [0,cumsum(widths)];
positive(end) = referencePositive(end);
if strcmp(geometry,'symmetric')
    axis = [-fliplr(positive(2:end)),positive];
    axis((numel(axis)+1)/2) = 0;
else
    axis = positive;
end
weights = ipm.mesh.quadrature(axis);
quality = ipm.mesh.quality(axis,7,weights);
reasons = admission_reasons(quality,weights,limits);
counts = zeros(size(intervals,1),1);
for index = 1:size(intervals,1)
    counts(index) = interval_cells(positive,intervals(index,:));
end
trial = struct('amplitude',amplitude,'axis',axis, ...
    'positiveAxis',positive,'admissible',isempty(reasons), ...
    'rejectionReasons',{reasons},'quality',quality, ...
    'quadratureWeights',weights,'achievedCells',counts, ...
    'targetMet',isempty(reasons) && all(counts >= targets), ...
    'minimumCellWidth',min(widths),'maximumCellWidth',max(widths), ...
    'anchorSolution',anchorSolution);
end

function solution = empty_anchor_solution()
solution = struct('beta',0,'residual',NaN, ...
    'mappedPhysicalPosition',NaN,'iterations',0, ...
    'betaBracket',[NaN,NaN]);
end

function [widths,solution] = solve_anchor_correction( ...
        logWidths,limit,anchor)
[widths,residual,mapped] = corrected_widths( ...
    logWidths,0,limit,anchor);
if abs(residual) <= anchor.tolerance
    solution = struct('beta',0,'residual',residual, ...
        'mappedPhysicalPosition',mapped,'iterations',0, ...
        'betaBracket',[0,0]);
    return
end

if residual > 0
    lowerBeta = 0;
    lowerResidual = residual;
    upperBeta = 1;
    [~,upperResidual] = corrected_widths( ...
        logWidths,upperBeta,limit,anchor);
    while upperResidual > 0 && ...
            upperBeta < anchor.maximumAbsBeta
        upperBeta = min(anchor.maximumAbsBeta,2*upperBeta);
        [~,upperResidual] = corrected_widths( ...
            logWidths,upperBeta,limit,anchor);
    end
else
    upperBeta = 0;
    upperResidual = residual;
    lowerBeta = -1;
    [~,lowerResidual] = corrected_widths( ...
        logWidths,lowerBeta,limit,anchor);
    while lowerResidual < 0 && ...
            abs(lowerBeta) < anchor.maximumAbsBeta
        lowerBeta = max(-anchor.maximumAbsBeta,2*lowerBeta);
        [~,lowerResidual] = corrected_widths( ...
            logWidths,lowerBeta,limit,anchor);
    end
end
if lowerResidual < 0 || upperResidual > 0
    error('ipm:gridlab:EqualizeAnchorBracket', ...
        ['The smooth anchor correction could not bracket the required ' ...
        'physical position within |beta| <= %.16g.'], ...
        anchor.maximumAbsBeta);
end

% The cell fraction to the left of the anchor decreases with cell index,
% while the cosine basis increases.  Hence the anchored physical position
% is strictly decreasing in beta and this bracket has a unique root.
bestBeta = lowerBeta;
[bestWidths,bestResidual,bestMapped] = corrected_widths( ...
    logWidths,bestBeta,limit,anchor);
if abs(upperResidual) < abs(bestResidual)
    bestBeta = upperBeta;
    [bestWidths,bestResidual,bestMapped] = corrected_widths( ...
        logWidths,bestBeta,limit,anchor);
end
iterations = 0;
for iteration = 1:anchor.maxIterations
    iterations = iteration;
    beta = 0.5*(lowerBeta+upperBeta);
    if beta == lowerBeta || beta == upperBeta
        break
    end
    [trialWidths,trialResidual,trialMapped] = corrected_widths( ...
        logWidths,beta,limit,anchor);
    if abs(trialResidual) < abs(bestResidual)
        bestBeta = beta;
        bestWidths = trialWidths;
        bestResidual = trialResidual;
        bestMapped = trialMapped;
    end
    if abs(trialResidual) <= anchor.tolerance
        break
    elseif trialResidual > 0
        lowerBeta = beta;
    else
        upperBeta = beta;
    end
end
if abs(bestResidual) > anchor.tolerance
    error('ipm:gridlab:EqualizeAnchorTolerance', ...
        ['The smooth anchor correction stopped with residual %.16g, ' ...
        'above tolerance %.16g.'],bestResidual,anchor.tolerance);
end
widths = bestWidths;
solution = struct('beta',bestBeta,'residual',bestResidual, ...
    'mappedPhysicalPosition',bestMapped,'iterations',iterations, ...
    'betaBracket',[lowerBeta,upperBeta]);
end

function [widths,residual,mapped] = corrected_widths( ...
        logWidths,beta,limit,anchor)
correctedLogWidths = logWidths+beta*anchor.tilt;
widths = exp(correctedLogWidths-max(correctedLogWidths));
widths = limit*widths/sum(widths);
cellPosition = anchor.referenceCoordinate*numel(widths);
wholeCells = floor(cellPosition);
fraction = cellPosition-wholeCells;
if wholeCells >= numel(widths)
    mapped = limit;
elseif wholeCells <= 0
    mapped = fraction*widths(1);
else
    mapped = sum(widths(1:wholeCells))+ ...
        fraction*widths(wholeCells+1);
end
residual = mapped-anchor.physicalPosition;
end

function reasons = admission_reasons(quality,weights,limits)
reasons = {};
if quality.maximumAdjacentCellRatio > limits.maxAdjacentCellRatio
    reasons{end+1} = 'adjacent_cell_ratio';
end
if quality.maximumLogSpacingCurvature > ...
        limits.maxLogSpacingCurvature
    reasons{end+1} = 'log_spacing_curvature';
end
if quality.minimumStencilRcond < limits.minStencilRcond
    reasons{end+1} = 'stencil_conditioning';
end
if quality.minimumQuadratureWeightRatio < ...
        limits.minQuadratureWeightRatio || any(weights <= 0)
    reasons{end+1} = 'quadrature_margin';
end
end

function [selected,status,trace] = resolve_bracket( ...
        lower,upper,referencePositive,geometry,kernel,anchor, ...
        intervals,targets,options)
trace = repmat(trial_summary(lower),0,1);
bestAdmitted = lower;
targetTrial = [];
if upper.admissible && upper.targetMet
    targetTrial = upper;
end
for iteration = 1:options.maxIterations
    if upper.amplitude-lower.amplitude <= ...
            options.amplitudeTolerance*max(1,upper.amplitude)
        break
    end
    amplitude = 0.5*(lower.amplitude+upper.amplitude);
    trial = evaluate_trial(amplitude,referencePositive,geometry,kernel, ...
        anchor, ...
        intervals,targets,options.meshLimits);
    trace(end+1,1) = trial_summary(trial); %#ok<AGROW>
    if trial.admissible
        if trial.amplitude > bestAdmitted.amplitude
            bestAdmitted = trial;
        end
        if trial.targetMet
            targetTrial = trial;
            upper = trial;
        else
            lower = trial;
        end
    else
        upper = trial;
    end
end
if ~isempty(targetTrial)
    selected = targetTrial;
    status = 'target_met';
else
    selected = bestAdmitted;
    status = 'mesh_gate_before_target';
end
end

function summary = trial_summary(trial)
summary = struct( ...
    'amplitude',trial.amplitude, ...
    'admissible',trial.admissible, ...
    'targetMet',trial.targetMet, ...
    'achievedCells',trial.achievedCells, ...
    'maximumAdjacentCellRatio', ...
        trial.quality.maximumAdjacentCellRatio, ...
    'maximumLogSpacingCurvature', ...
        trial.quality.maximumLogSpacingCurvature, ...
    'minimumStencilRcond',trial.quality.minimumStencilRcond, ...
    'minimumQuadratureWeightRatio', ...
        trial.quality.minimumQuadratureWeightRatio, ...
    'minimumCellWidth',trial.minimumCellWidth, ...
    'maximumCellWidth',trial.maximumCellWidth, ...
    'anchorCorrectionBeta',trial.anchorSolution.beta, ...
    'anchorResidual',trial.anchorSolution.residual, ...
    'rejectionReasons',{trial.rejectionReasons});
end

function info = make_info(status,trial,trace,intervals,targets, ...
        focusCoordinate,kernel,kernelModel,anchor,options)
referenceCellCoordinate = ((1:numel(kernel))-0.5)/numel(kernel);
compressionRamp = -trial.amplitude*kernel;
anchorCorrectionRamp = trial.anchorSolution.beta*anchor.tilt;
ramp = compressionRamp+anchorCorrectionRamp;
rampSlope = diff(ramp);
if numel(rampSlope) > 1 && max(abs(rampSlope)) > 0
    equalizationEfficiency = max(0,1- ...
        max(abs(diff(rampSlope)))/max(abs(rampSlope)));
else
    equalizationEfficiency = 1;
end
info = struct( ...
    'schemaVersion',1, ...
    'kind','ipm_gridlab_global_logwidth_equalization', ...
    'status',status,'targetMet',trial.targetMet, ...
    'admissible',trial.admissible, ...
    'amplitude',trial.amplitude,'sigma',options.sigma, ...
    'power',options.power, ...
    'kernelKind',options.kernelKind, ...
    'kernelModel',kernelModel, ...
    'corridorPhysicalBounds',kernelModel.physicalBounds, ...
    'corridorReferenceCoordinateBounds', ...
        kernelModel.referenceCoordinateBounds, ...
    'corridorKernelCoordinateBounds',kernelModel.kernelCoordinateBounds, ...
    'corridorExpandedKernelCoordinateBounds', ...
        kernelModel.expandedKernelCoordinateBounds, ...
    'corridorDelta',kernelModel.delta, ...
    'corridorShoulderCells',kernelModel.shoulderCells, ...
    'corridorExpansionShoulders',kernelModel.expansionShoulders, ...
    'corridorPositiveCellCount',kernelModel.positiveCellCount, ...
    'geometry',options.geometry, ...
    'focusCenters',options.focusCenters, ...
    'focusReferenceCoordinate',focusCoordinate, ...
    'kernelCoordinateBasis',anchor.kernelCoordinateBasis, ...
    'kernelSmoothingScale',anchor.kernelSmoothingScale, ...
    'kernelFocusCoordinate',anchor.kernelFocusCoordinate, ...
    'anchorEnabled',anchor.enabled, ...
    'anchorPhysicalPosition',anchor.physicalPosition, ...
    'anchorReferenceCoordinate',anchor.referenceCoordinate, ...
    'anchorCorrectionBasis',anchor.correctionBasis, ...
    'anchorCorrectionBeta',trial.anchorSolution.beta, ...
    'anchorResidual',trial.anchorSolution.residual, ...
    'anchorMappedPhysicalPosition', ...
        trial.anchorSolution.mappedPhysicalPosition, ...
    'anchorSolveTolerance',anchor.tolerance, ...
    'anchorMaximumAbsBeta',anchor.maximumAbsBeta, ...
    'anchorSolveMaximumIterations',anchor.maxIterations, ...
    'anchorSolveIterations',trial.anchorSolution.iterations, ...
    'anchorBetaBracket',trial.anchorSolution.betaBracket, ...
    'targetIntervals',intervals,'targetCells',targets, ...
    'achievedCells',trial.achievedCells, ...
    'positiveAxis',trial.positiveAxis, ...
    'quality',trial.quality, ...
    'quadratureWeights',trial.quadratureWeights, ...
    'rejectionReasons',{trial.rejectionReasons}, ...
    'minimumCellWidth',trial.minimumCellWidth, ...
    'maximumCellWidth',trial.maximumCellWidth, ...
    'referenceCellCoordinate',referenceCellCoordinate, ...
    'logWidthRamp',ramp, ...
    'compressionLogWidthRamp',compressionRamp, ...
    'anchorLogWidthCorrection',anchorCorrectionRamp, ...
    'kernel',kernel, ...
    'equalizationEfficiency',equalizationEfficiency, ...
    'equalizationEfficiencyDefinition', ...
        '1-max(abs(diff(rampSlope)))/max(abs(rampSlope))', ...
    'ratioCapRelaxed',false, ...
    'meshLimits',options.meshLimits,'trace',trace);
end

function count = interval_cells(axis,interval)
widths = diff(axis);
overlap = max(0,min(axis(2:end),interval(2))- ...
    max(axis(1:end-1),interval(1)));
count = sum(overlap./widths);
end
