function design = ipm_gridlab_design_continuation_stage( ...
        currentInput,referenceInput,options)
%IPM_GRIDLAB_DESIGN_CONTINUATION_STAGE Design a global-reference x/y regrid.
%   DESIGN = IPM_GRIDLAB_DESIGN_CONTINUATION_STAGE(CURRENT,REFERENCE,OPTIONS)
%   freezes the terminal accepted field in CURRENT, extracts strict 0.9
%   source cores, builds analytic x/y monitor families, and applies every
%   monitor to axes taken from the external schema-version-2 REFERENCE
%   dataset.  Optional x fallbacks preserve a strict tier order: anchored
%   Gaussian equalization of the original reference, then independent
%   corridor equalizations of that same immutable reference, and finally
%   depth-limited anchored equalization of an immutable copy of the trusted
%   terminal x axis.  A later tier is attempted only after all preceding
%   tiers fail their unchanged targets.  CURRENT may be a version-2 result,
%   an accepted-step checkpoint, or a MAT-file containing either contract.
%   REFERENCE may be a schema-version-2 frozen dataset or its MAT-file.
%
%   Required continuation controls are OPTIONS.ratioCap,
%   OPTIONS.targetXCoreCells, and OPTIONS.targetYCoreCells.  The adjacent
%   ratio cap is authoritative: this routine never raises it to make a
%   target feasible.  An infeasible design is saved and returned with the
%   best attainable core/front cell counts at that exact cap.
%
%   OPTIONS.outputFile saves DESIGN with -v7.3.  No PDE step is advanced
%   and no production solver file is modified.

if nargin < 3 || isempty(options)
    options = struct();
end
options = resolve_options(options);

[currentResult,currentKind,currentLabel] = resolve_current(currentInput);
collectOptions = options.collectOptions;
if ~isfield(collectOptions,'targetCanonicalTimes')
    collectOptions.targetCanonicalTimes = ...
        currentResult.state.canonicalTime;
end
if ~isfield(collectOptions,'trustedOnly')
    collectOptions.trustedOnly = true;
end
if ~isfield(collectOptions,'tag') || isempty(collectOptions.tag)
    collectOptions.tag = options.tag;
end
if isfield(collectOptions,'outputFile') && ...
        ~isempty(collectOptions.outputFile)
    error('ipm:gridlab:StageDesignCollectOutput', ...
        ['The stage designer keeps its frozen dataset in the final design; ' ...
        'collectOptions.outputFile must be empty or absent.']);
end
collectOptions.outputFile = '';
dataset = ipm_gridlab_collect_dataset(currentResult,collectOptions);

featureOptions = strict_feature_options(options.featureOptions);
profiles = ipm_gridlab_feature_profiles(dataset,featureOptions);
xSeeds = ipm_gridlab_seed_models(profiles,options.xSeedOptions);
ySeeds = ipm_gridlab_seed_y_models(profiles,options.ySeedOptions);

[referenceDataset,referenceLabel] = resolve_reference(referenceInput);
[referenceX,referenceY,referenceIndex] = select_reference_axes( ...
    referenceDataset,dataset,options.referenceSnapshotIndex);

meshLimits = options.meshLimits;
meshLimits.maxAdjacentCellRatio = options.ratioCap;
xAxisOptions = axis_options( ...
    options.axisOptions,referenceX,meshLimits);
yAxisOptions = axis_options( ...
    options.axisOptions,referenceY,meshLimits);

nx = numel(dataset.snapshots(1).x);
ny = numel(dataset.snapshots(1).y);
xCandidates = build_x_candidates(dataset,profiles,xSeeds.candidates, ...
    nx,xAxisOptions,options);
yCandidates = build_y_candidates(dataset,profiles,ySeeds.candidates, ...
    ny,yAxisOptions,options);
rootCorridorXFallback = initialize_root_corridor_x_fallback( ...
    options.equalizationOptions,referenceX,referenceIndex);
currentXReferenceFallback = initialize_current_x_reference_fallback( ...
    options.equalizationOptions);
if options.equalizationOptions.enabled && ...
        ~any([xCandidates.meetsTargets])
    fallback = build_equalized_x_candidate( ...
        referenceX,profiles,meshLimits,options);
    fallback.index = numel(xCandidates)+1;
    xCandidates(end+1,1) = fallback;
end
if options.equalizationOptions.enabled && ...
        options.equalizationOptions.rootCorridorXFallbackEnabled
    if any([xCandidates.meetsTargets])
        rootCorridorXFallback.status = ...
            'not_needed_preceding_tier_met_targets';
    else
        [corridorCandidates,rootCorridorXFallback] = ...
            build_root_corridor_x_fallbacks( ...
                referenceX,referenceIndex,profiles,meshLimits,options, ...
                rootCorridorXFallback);
        candidateIndices = zeros(numel(corridorCandidates),1);
        for candidateIndex = 1:numel(corridorCandidates)
            corridorCandidates(candidateIndex).index = ...
                numel(xCandidates)+1;
            candidateIndices(candidateIndex) = ...
                corridorCandidates(candidateIndex).index;
            xCandidates(end+1,1) = ...
                corridorCandidates(candidateIndex); %#ok<AGROW>
        end
        rootCorridorXFallback.candidateIndices = candidateIndices;
    end
end
if options.equalizationOptions.enabled && ...
        options.equalizationOptions.currentAxisXFallbackEnabled
    if any([xCandidates.meetsTargets])
        currentXReferenceFallback.status = ...
            'not_needed_preceding_tier_met_targets';
    else
        [incrementalCandidates,currentXReferenceFallback] = ...
            build_current_axis_x_fallbacks( ...
                dataset,referenceX,profiles,meshLimits,options, ...
                currentXReferenceFallback);
        candidateIndices = zeros(numel(incrementalCandidates),1);
        for candidateIndex = 1:numel(incrementalCandidates)
            incrementalCandidates(candidateIndex).index = ...
                numel(xCandidates)+1;
            candidateIndices(candidateIndex) = ...
                incrementalCandidates(candidateIndex).index;
            xCandidates(end+1,1) = ...
                incrementalCandidates(candidateIndex); %#ok<AGROW>
        end
        currentXReferenceFallback.candidateIndices = candidateIndices;
    end
end
if options.equalizationOptions.enabled && ...
        ~any([yCandidates.meetsTargets])
    fallback = build_equalized_y_candidate( ...
        referenceY,profiles,meshLimits,options, ...
        'external_original_reference');
    fallback.index = numel(yCandidates)+1;
    yCandidates(end+1,1) = fallback;
end
if options.equalizationOptions.enabled && ...
        options.equalizationOptions.uniformFlatTailEnabled && ...
        ~any([yCandidates.meetsTargets])
    flatTailReference = linspace( ...
        referenceY(1),referenceY(end),numel(referenceY));
    fallback = build_equalized_y_candidate( ...
        flatTailReference,profiles,meshLimits,options, ...
        'uniform_flat_tail_global_reference');
    fallback.index = numel(yCandidates)+1;
    yCandidates(end+1,1) = fallback;
end
[selectedXIndex,xOrder] = select_candidate(xCandidates);
[selectedYIndex,yOrder] = select_candidate(yCandidates);
feasibility = summarize_feasibility( ...
    xCandidates,yCandidates,options,meshLimits);

pairScore = struct();
selected = empty_selection();
if ~isempty(selectedXIndex) && ~isempty(selectedYIndex)
    selectedX = xCandidates(selectedXIndex);
    selectedY = yCandidates(selectedYIndex);
    pairOptions = pair_score_options( ...
        options.pairScoreOptions,profiles,meshLimits,options);
    pairScore = ipm_gridlab_score_frozen_pair( ...
        dataset,selectedX.axis,selectedY.axis,pairOptions);
    selected = struct( ...
        'xIndex',selectedXIndex,'yIndex',selectedYIndex, ...
        'xName',selectedX.name,'yName',selectedY.name, ...
        'x',selectedX.axis,'y',selectedY.axis, ...
        'xModel',selectedX.model,'yModel',selectedY.model, ...
        'xReferenceProvenance',candidate_reference_provenance( ...
            selectedX), ...
        'yReferenceProvenance',candidate_reference_provenance( ...
            selectedY));
    if pairScore.admissible
        status = 'feasible';
    else
        status = 'pair_score_rejected';
    end
elseif isempty(selectedXIndex) && isempty(selectedYIndex)
    status = 'infeasible_xy';
elseif isempty(selectedXIndex)
    status = 'infeasible_x';
else
    status = 'infeasible_y';
end

referenceRecord = referenceDataset.snapshots(referenceIndex);
xCandidateReferencePolicy = x_candidate_reference_policy( ...
    options.equalizationOptions);
referenceSummary = struct( ...
    'sourceLabel',referenceLabel,'datasetTag',referenceDataset.tag, ...
    'snapshotIndex',referenceIndex, ...
    'datasetIndex',referenceRecord.datasetIndex, ...
    'canonicalTime',referenceRecord.canonicalTime, ...
    'nodeCount',[numel(referenceX),numel(referenceY)], ...
    'xSignature',axis_signature(referenceX), ...
    'ySignature',axis_signature(referenceY), ...
    'construction','external_global_reference_multiplier', ...
    'xCandidateReferencePolicy',xCandidateReferencePolicy, ...
    'yCandidateReferencePolicy', ...
        'external_original_reference_then_uniform_flat_tail_fallback', ...
    'usesExternalOriginalReferenceCorridor', ...
        rootCorridorXFallback.usedAsReference, ...
    'usesCurrentAxesAsReference', ...
        currentXReferenceFallback.usedAsReference, ...
    'rootCorridorXFallback',rootCorridorXFallback, ...
    'currentAxisXFallback',currentXReferenceFallback);
storedOptions = rmfield(options,'outputFile');
design = struct( ...
    'schemaVersion',1, ...
    'kind','ipm_gridlab_continuation_stage_design', ...
    'createdUtc',char(datetime('now','TimeZone','UTC', ...
        'Format','yyyy-MM-dd''T''HH:mm:ss''Z''')), ...
    'status',status,'tag',options.tag, ...
    'currentInputKind',currentKind, ...
    'currentInputLabel',currentLabel, ...
    'ratioCap',options.ratioCap, ...
    'ratioCapRelaxed',false, ...
    'strictCoreLevel',0.9, ...
    'targets',struct('xCoreCells',options.targetXCoreCells, ...
        'yCoreCells',options.targetYCoreCells, ...
        'xFrontCells',options.minimumXFrontCells), ...
    'reference',referenceSummary, ...
    'dataset',dataset,'profiles',profiles, ...
    'seeds',struct('x',xSeeds,'y',ySeeds), ...
    'xCandidates',xCandidates,'yCandidates',yCandidates, ...
    'xOrder',xOrder,'yOrder',yOrder, ...
    'feasibility',feasibility,'selected',selected, ...
    'pairScore',pairScore,'options',storedOptions);
write_design(design,options.outputFile);
end

function options = resolve_options(options)
if ~isstruct(options) || ~isscalar(options)
    error('ipm:gridlab:StageDesignOptions', ...
        'options must be a scalar structure.');
end
defaultMeshLimits = struct( ...
    'maxAdjacentCellRatio',1.08, ...
    'maxLogSpacingCurvature',0.03, ...
    'minStencilRcond',1e-9, ...
    'minQuadratureWeightRatio',1e-4);
defaults = struct( ...
    'ratioCap',1.08, ...
    'targetXCoreCells',18, ...
    'targetYCoreCells',18, ...
    'minimumXFrontCells',8, ...
    'referenceSnapshotIndex',[], ...
    'tag','', ...
    'outputFile','', ...
    'collectOptions',struct(), ...
    'featureOptions',struct(), ...
    'xSeedOptions',struct(), ...
    'ySeedOptions',struct(), ...
    'equalizationOptions',struct( ...
        'enabled',true,'uniformFlatTailEnabled',true, ...
        'rootCorridorXFallbackEnabled',false, ...
        'rootCorridorXShoulderCells',[16,24,32], ...
        'rootCorridorXExpansionShoulders',2, ...
        'currentAxisXFallbackEnabled',false, ...
        'currentAxisXSigmas',[1.5,2,3], ...
        'currentAxisXPower',2, ...
        'maximumIncrementalReferenceDepth',1, ...
        'currentIncrementalReferenceDepth',0, ...
        'xSigma',0.35,'ySigma',0.35, ...
        'xPower',1,'yPower',1, ...
        'uniformFlatTailSigma',0.35, ...
        'uniformFlatTailPower',3, ...
        'initialAmplitude',0.25,'maximumAmplitude',16, ...
        'amplitudeTolerance',1e-9,'maxIterations',80), ...
    'axisOptions',struct('fineCount',131073, ...
        'projectToAdmissible',true), ...
    'pairScoreOptions',struct(), ...
    'meshLimits',defaultMeshLimits);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:StageDesignOptions', ...
        'Unknown option(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(options,name)
        options.(name) = defaults.(name);
    end
end
validateattributes(options.ratioCap,{'numeric'}, ...
    {'scalar','real','finite','>=',1},mfilename,'options.ratioCap');
for field = {'targetXCoreCells','targetYCoreCells', ...
        'minimumXFrontCells'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','integer','positive'},mfilename, ...
        ['options.' field{1}]);
end
if ~isempty(options.referenceSnapshotIndex)
    validateattributes(options.referenceSnapshotIndex,{'numeric'}, ...
        {'scalar','integer','positive'},mfilename, ...
        'options.referenceSnapshotIndex');
elseif ~isnumeric(options.referenceSnapshotIndex)
    error('ipm:gridlab:StageDesignOptions', ...
        'options.referenceSnapshotIndex must be numeric or empty.');
end
for field = {'tag','outputFile'}
    value = options.(field{1});
    if ~(ischar(value) || (isstring(value) && isscalar(value)))
        error('ipm:gridlab:StageDesignOptions', ...
            'options.%s must be text.',field{1});
    end
    options.(field{1}) = char(value);
end
for field = {'collectOptions','featureOptions','xSeedOptions', ...
        'ySeedOptions','equalizationOptions','axisOptions', ...
        'pairScoreOptions'}
    if ~isstruct(options.(field{1})) || ...
            ~isscalar(options.(field{1}))
        error('ipm:gridlab:StageDesignOptions', ...
            'options.%s must be a scalar structure.',field{1});
    end
end
options.equalizationOptions = validate_equalization_options( ...
    options.equalizationOptions);
options.meshLimits = merge_mesh_limits( ...
    options.meshLimits,defaultMeshLimits);
if isfield(options.axisOptions,'referenceAxis') && ...
        ~isempty(options.axisOptions.referenceAxis)
    error('ipm:gridlab:StageDesignReferenceOverride', ...
        ['axisOptions.referenceAxis is owned by referenceInput; pass the ' ...
        'initial global-reference dataset instead.']);
end
end

function options = validate_equalization_options(options)
defaults = struct('enabled',true, ...
    'uniformFlatTailEnabled',true, ...
    'rootCorridorXFallbackEnabled',false, ...
    'rootCorridorXShoulderCells',[16,24,32], ...
    'rootCorridorXExpansionShoulders',2, ...
    'currentAxisXFallbackEnabled',false, ...
    'currentAxisXSigmas',[1.5,2,3], ...
    'currentAxisXPower',2, ...
    'maximumIncrementalReferenceDepth',1, ...
    'currentIncrementalReferenceDepth',0, ...
    'xSigma',0.35,'ySigma',0.35,'xPower',1,'yPower',1, ...
    'uniformFlatTailSigma',0.35,'uniformFlatTailPower',3, ...
    'initialAmplitude',0.25,'maximumAmplitude',16, ...
    'amplitudeTolerance',1e-9,'maxIterations',80);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(options),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:StageDesignEqualizationOptions', ...
        'Unknown equalization option(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(options,name)
        options.(name) = defaults.(name);
    end
end
if ~(islogical(options.enabled) && isscalar(options.enabled))
    error('ipm:gridlab:StageDesignEqualizationOptions', ...
        'equalizationOptions.enabled must be a logical scalar.');
end
if ~(islogical(options.uniformFlatTailEnabled) && ...
        isscalar(options.uniformFlatTailEnabled))
    error('ipm:gridlab:StageDesignEqualizationOptions', ...
        ['equalizationOptions.uniformFlatTailEnabled must be a ' ...
        'logical scalar.']);
end
if ~(islogical(options.rootCorridorXFallbackEnabled) && ...
        isscalar(options.rootCorridorXFallbackEnabled))
    error('ipm:gridlab:StageDesignEqualizationOptions', ...
        ['equalizationOptions.rootCorridorXFallbackEnabled must be a ' ...
        'logical scalar.']);
end
validateattributes(options.rootCorridorXShoulderCells,{'numeric'}, ...
    {'vector','nonempty','real','finite','positive'}, ...
    mfilename,'equalizationOptions.rootCorridorXShoulderCells');
options.rootCorridorXShoulderCells = ...
    double(options.rootCorridorXShoulderCells(:)');
if any(diff(options.rootCorridorXShoulderCells) <= 0)
    error('ipm:gridlab:StageDesignEqualizationOptions', ...
        ['equalizationOptions.rootCorridorXShoulderCells must be ' ...
        'strictly increasing and contain no duplicates.']);
end
validateattributes(options.rootCorridorXExpansionShoulders,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'},mfilename, ...
    'equalizationOptions.rootCorridorXExpansionShoulders');
options.rootCorridorXExpansionShoulders = ...
    double(options.rootCorridorXExpansionShoulders);
if ~(islogical(options.currentAxisXFallbackEnabled) && ...
        isscalar(options.currentAxisXFallbackEnabled))
    error('ipm:gridlab:StageDesignEqualizationOptions', ...
        ['equalizationOptions.currentAxisXFallbackEnabled must be a ' ...
        'logical scalar.']);
end
validateattributes(options.currentAxisXSigmas,{'numeric'}, ...
    {'vector','nonempty','real','finite','positive'},mfilename, ...
    'equalizationOptions.currentAxisXSigmas');
options.currentAxisXSigmas = ...
    double(options.currentAxisXSigmas(:)');
validateattributes(options.currentAxisXPower,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename, ...
    'equalizationOptions.currentAxisXPower');
for field = {'maximumIncrementalReferenceDepth', ...
        'currentIncrementalReferenceDepth'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','integer','nonnegative'},mfilename, ...
        ['equalizationOptions.' field{1}]);
end
for field = {'xSigma','ySigma','xPower','yPower', ...
        'uniformFlatTailSigma','uniformFlatTailPower', ...
        'initialAmplitude','maximumAmplitude','amplitudeTolerance'}
    validateattributes(options.(field{1}),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        ['equalizationOptions.' field{1}]);
end
if options.initialAmplitude > options.maximumAmplitude
    error('ipm:gridlab:StageDesignEqualizationOptions', ...
        'initialAmplitude must not exceed maximumAmplitude.');
end
validateattributes(options.maxIterations,{'numeric'}, ...
    {'scalar','integer','positive'},mfilename, ...
    'equalizationOptions.maxIterations');
end

function limits = merge_mesh_limits(limits,defaults)
if ~isstruct(limits) || ~isscalar(limits)
    error('ipm:gridlab:StageDesignOptions', ...
        'options.meshLimits must be a scalar structure.');
end
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(limits),names,'stable');
if ~isempty(unexpected)
    error('ipm:gridlab:StageDesignOptions', ...
        'Unknown meshLimits field(s): %s.',strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if ~isfield(limits,name)
        limits.(name) = defaults.(name);
    end
    validateattributes(limits.(name),{'numeric'}, ...
        {'scalar','real','finite','positive'},mfilename, ...
        ['options.meshLimits.' name]);
end
end

function featureOptions = strict_feature_options(featureOptions)
if isfield(featureOptions,'safetyCoreLevel') && ...
        featureOptions.safetyCoreLevel ~= 0.9
    error('ipm:gridlab:StageDesignCoreLevel', ...
        'Continuation stage design fixes safetyCoreLevel at 0.9.');
end
featureOptions.safetyCoreLevel = 0.9;
if isfield(featureOptions,'resolutionLevels') && ...
        ~any(abs(featureOptions.resolutionLevels-0.9) <= 16*eps)
    error('ipm:gridlab:StageDesignCoreLevel', ...
        'featureOptions.resolutionLevels must contain the strict 0.9 level.');
end
end

function [result,kind,label] = resolve_current(input)
label = input_label(input);
if ischar(input) || (isstring(input) && isscalar(input))
    fileName = char(input);
    if ~isfile(fileName)
        error('ipm:gridlab:StageDesignCurrentMissing', ...
            'Current result/checkpoint does not exist: %s',fileName);
    end
    variables = whos('-file',fileName);
    names = {variables.name};
    hasResult = ismember('result',names);
    hasCheckpoint = ismember('checkpoint',names);
    if hasResult == hasCheckpoint
        error('ipm:gridlab:StageDesignCurrentFile', ...
            ['Current MAT-file must contain exactly one recognized variable: ' ...
            'result or checkpoint.']);
    end
    if hasResult
        result = ipm.output.validate(fileName);
        kind = 'result_file';
    else
        result = checkpoint_result(fileName);
        kind = 'checkpoint_file';
    end
elseif isstruct(input) && isscalar(input) && ...
        isfield(input,'kind') && ...
        strcmp(input.kind,'ipm_accepted_step_checkpoint')
    result = checkpoint_result(input);
    kind = 'checkpoint_structure';
elseif isstruct(input) && isscalar(input)
    result = ipm.output.validate(input);
    kind = 'result_structure';
else
    error('ipm:gridlab:StageDesignCurrentInput', ...
        'CURRENT must be a version-2 result/checkpoint or its MAT-file.');
end
end

function result = checkpoint_result(input)
[state,log,~] = ipm.output.restoreCheckpoint(input,struct());
result = ipm.output.finalize(state,log,'accepted_checkpoint_snapshot');
end

function [dataset,label] = resolve_reference(input)
label = input_label(input);
if ischar(input) || (isstring(input) && isscalar(input))
    fileName = char(input);
    if ~isfile(fileName)
        error('ipm:gridlab:StageDesignReferenceMissing', ...
            'Reference dataset does not exist: %s',fileName);
    end
    loaded = load(fileName,'dataset');
    if ~isfield(loaded,'dataset')
        error('ipm:gridlab:StageDesignReferenceFile', ...
            'Reference MAT-file must contain a variable named dataset.');
    end
    dataset = loaded.dataset;
else
    dataset = input;
end
if ~isstruct(dataset) || ~isscalar(dataset) || ...
        ~all(isfield(dataset,{'schemaVersion','kind','tag', ...
            'snapshotCount','snapshots'})) || ...
        dataset.schemaVersion ~= 2 || ...
        ~strcmp(dataset.kind,'ipm_frozen_grid_dataset') || ...
        dataset.snapshotCount ~= numel(dataset.snapshots) || ...
        isempty(dataset.snapshots)
    error('ipm:gridlab:StageDesignReference', ...
        'REFERENCE must be a nonempty schema-version-2 frozen dataset.');
end
end

function label = input_label(input)
if ischar(input) || (isstring(input) && isscalar(input))
    label = char(input);
else
    label = 'in_memory_structure';
end
end

function [x,y,index] = select_reference_axes(reference,current,requested)
nx = numel(current.snapshots(1).x);
ny = numel(current.snapshots(1).y);
if isempty(requested)
    nodeCounts = arrayfun(@(value) ...
        numel(value.x) == nx && numel(value.y) == ny, ...
        reference.snapshots);
    index = find(nodeCounts,1,'first');
    if isempty(index)
        error('ipm:gridlab:StageDesignReferenceResolution', ...
            ['The reference dataset has no snapshot with the current ' ...
            '%d-by-%d node counts.'],nx,ny);
    end
else
    if requested > numel(reference.snapshots)
        error('ipm:gridlab:StageDesignReferenceIndex', ...
            'referenceSnapshotIndex exceeds the reference snapshot count.');
    end
    index = requested;
end
record = reference.snapshots(index);
x = double(record.x(:)');
y = double(record.y(:));
if numel(x) ~= nx || numel(y) ~= ny
    error('ipm:gridlab:StageDesignReferenceResolution', ...
        'The selected reference axes must exactly match current node counts.');
end
currentX = double(current.snapshots(1).x(:)');
currentY = double(current.snapshots(1).y(:));
if ~matching_endpoints(x,currentX) || ~matching_endpoints(y,currentY)
    error('ipm:gridlab:StageDesignReferenceDomain', ...
        'Reference and current axes must have identical endpoints.');
end
if mod(numel(x),2) ~= 1 || any(diff(x) <= 0) || ...
        any(diff(y) <= 0) || y(1) ~= 0
    error('ipm:gridlab:StageDesignReferenceAxis', ...
        'Reference axes do not satisfy the double-odd grid contract.');
end
tolerance = 1e3*eps(max(1,max(abs(x))));
if max(abs(x+fliplr(x))) > tolerance
    error('ipm:gridlab:StageDesignReferenceAxis', ...
        'The reference x axis is not symmetric.');
end
end

function tf = matching_endpoints(first,second)
first = double(first(:));
second = double(second(:));
scale = max([1;abs(first([1,end]));abs(second([1,end]))]);
tf = max(abs(first([1,end])-second([1,end]))) <= 1e3*eps(scale);
end

function axisOptions = axis_options(input,reference,limits)
axisOptions = input;
axisOptions.referenceAxis = reference;
axisOptions.maxAdjacentCellRatio = limits.maxAdjacentCellRatio;
axisOptions.maxLogSpacingCurvature = limits.maxLogSpacingCurvature;
axisOptions.minStencilRcond = limits.minStencilRcond;
axisOptions.minQuadratureWeightRatio = limits.minQuadratureWeightRatio;
end

function summary = initialize_root_corridor_x_fallback( ...
        options,referenceX,referenceIndex)
if ~options.enabled
    status = 'disabled_by_equalization_master';
elseif options.rootCorridorXFallbackEnabled
    status = 'pending_preceding_tiers';
else
    status = 'not_requested';
end
summary = struct( ...
    'enabled',options.rootCorridorXFallbackEnabled, ...
    'masterEqualizationEnabled',options.enabled, ...
    'attempted',false,'usedAsReference',false, ...
    'status',status, ...
    'kernelKind','corridor', ...
    'referenceProvenance','external_original_reference_corridor', ...
    'referencePolicy', ...
        'immutable_copy_of_selected_external_reference_snapshot_x', ...
    'referenceSnapshotIndex',referenceIndex, ...
    'referenceAxisSignature',axis_signature(referenceX), ...
    'configuredShoulderCells',options.rootCorridorXShoulderCells, ...
    'configuredExpansionShoulders', ...
        options.rootCorridorXExpansionShoulders, ...
    'candidateIndices',zeros(0,1), ...
    'sameRoundRecursiveReference',false);
end

function [candidates,summary] = build_root_corridor_x_fallbacks( ...
        externalReferenceX,referenceIndex,profiles,limits,stageOptions, ...
        summary)
equalization = stageOptions.equalizationOptions;
candidates = repmat(candidate_template(),0,1);
summary.attempted = true;
summary.usedAsReference = true;
summary.status = 'candidates_built';

% Every shoulder uses the same immutable copy of the selected external
% reference axis.  No corridor candidate can recursively become another
% candidate's reference, and none belongs to the incremental lineage.
immutableReferenceX = double(externalReferenceX(:)');
referenceSignature = axis_signature(immutableReferenceX);
for index = 1:numel(equalization.rootCorridorXShoulderCells)
    shoulderCells = equalization.rootCorridorXShoulderCells(index);
    expansionShoulders = ...
        equalization.rootCorridorXExpansionShoulders;
    overrides = struct( ...
        'kernelKind','corridor', ...
        'corridorShoulderCells',shoulderCells, ...
        'corridorExpansionShoulders',expansionShoulders);
    record = build_equalized_x_candidate( ...
        immutableReferenceX,profiles,limits,stageOptions,overrides);
    record.family = 'root_corridor_global_logwidth_equalization';
    if isfield(record.model,'amplitude')
        record.name = sprintf( ...
            'x_root_corridor_shoulder_%.12g_expand_%.12g_A_%.12g', ...
            shoulderCells,expansionShoulders,record.model.amplitude);
    else
        record.name = sprintf( ...
            'x_root_corridor_shoulder_%.12g_expand_%.12g_failed', ...
            shoulderCells,expansionShoulders);
    end
    record.model.kind = record.family;
    record.model.gridlabFamily = record.family;
    record.model.formula = [ ...
        'log(h)=log(h_ref)-A*K_corridor(r(u);interval_union,' ...
        'shoulder_cells,expansion_shoulders)+anchor_correction'];
    record.model.kernelKind = 'corridor';
    record.model.corridorShoulderCells = shoulderCells;
    record.model.corridorExpansionShoulders = expansionShoulders;
    record.model.referenceProvenance = ...
        'external_original_reference_corridor';
    record.model.referencePolicy = ...
        'immutable_copy_of_selected_external_reference_snapshot_x';
    record.model.referenceSnapshotIndex = referenceIndex;
    record.model.referenceAxisSignature = referenceSignature;
    record.model.sameRoundRecursiveReference = false;
    if isstruct(record.axisInfo)
        record.axisInfo.referenceProvenance = ...
            'external_original_reference_corridor';
        record.axisInfo.referenceSnapshotIndex = referenceIndex;
        record.axisInfo.referenceAxisSignature = referenceSignature;
        record.axisInfo.sameRoundRecursiveReference = false;
    end
    candidates(end+1,1) = record; %#ok<AGROW>
end
end

function summary = initialize_current_x_reference_fallback(options)
summary = struct( ...
    'enabled',options.currentAxisXFallbackEnabled, ...
    'attempted',false,'usedAsReference',false, ...
    'status','not_requested', ...
    'referenceProvenance','trusted_terminal_axis_single_hop', ...
    'referencePolicy', ...
        'immutable_copy_of_entry_frozen_dataset_snapshot_1_x', ...
    'configuredSigmas',options.currentAxisXSigmas, ...
    'configuredPower',options.currentAxisXPower, ...
    'maximumIncrementalReferenceDepth', ...
        options.maximumIncrementalReferenceDepth, ...
    'currentIncrementalReferenceDepth', ...
        options.currentIncrementalReferenceDepth, ...
    'incrementalGeneration',NaN, ...
    'parentAxisSignature',struct(), ...
    'referenceAudit',struct(), ...
    'candidateIndices',zeros(0,1), ...
    'sameRoundRecursiveReference',false);
end

function [candidates,summary] = build_current_axis_x_fallbacks( ...
        dataset,externalReferenceX,profiles,limits,stageOptions,summary)
candidates = repmat(candidate_template(),0,1);
equalization = stageOptions.equalizationOptions;
if equalization.currentIncrementalReferenceDepth >= ...
        equalization.maximumIncrementalReferenceDepth
    summary.status = 'maximum_incremental_reference_depth_reached';
    return
end

summary.attempted = true;
currentReferenceX = dataset.snapshots(1).x;
audit = audit_current_x_reference( ...
    currentReferenceX,externalReferenceX,limits);
summary.referenceAudit = audit;
if ~audit.passed
    summary.status = 'current_axis_reference_audit_failed';
    return
end
currentReferenceX = double(currentReferenceX(:)');
summary.usedAsReference = true;
summary.status = 'candidates_built';
summary.incrementalGeneration = ...
    equalization.currentIncrementalReferenceDepth+1;
summary.parentAxisSignature = axis_signature(currentReferenceX);

% Every sigma is evaluated against this immutable entry-axis copy.  A
% candidate produced earlier in this loop can therefore never become the
% reference for another candidate in the same design round.
for index = 1:numel(equalization.currentAxisXSigmas)
    sigma = equalization.currentAxisXSigmas(index);
    overrides = struct('sigma',sigma, ...
        'power',equalization.currentAxisXPower);
    record = build_equalized_x_candidate( ...
        currentReferenceX,profiles,limits,stageOptions,overrides);
    record.family = ...
        'anchored_incremental_global_logwidth_equalization';
    if isfield(record.model,'amplitude')
        record.name = sprintf( ...
            'x_incremental_anchored_sigma_%.12g_A_%.12g', ...
            sigma,record.model.amplitude);
    else
        record.name = sprintf( ...
            'x_incremental_anchored_sigma_%.12g_failed',sigma);
    end
    record.model.kind = record.family;
    record.model.gridlabFamily = record.family;
    record.model.referenceProvenance = ...
        'trusted_terminal_axis_single_hop';
    record.model.parentAxisSignature = ...
        summary.parentAxisSignature;
    record.model.incrementalGeneration = ...
        summary.incrementalGeneration;
    record.model.referenceSnapshotIndex = 1;
    record.model.referenceAuditPassed = true;
    record.model.sameRoundRecursiveReference = false;
    if ~isfield(record.model,'anchorEnabled') || ...
            ~record.model.anchorEnabled
        record.status = 'incremental_anchor_required';
        record.admissible = false;
        record.meetsCoreTarget = false;
        record.meetsFrontTarget = false;
        record.meetsTargets = false;
        record.errorIdentifier = ...
            'ipm:gridlab:StageDesignIncrementalAnchor';
        record.errorMessage = [ ...
            'Current-axis incremental fallback requires a strict ' ...
            'common core/front anchor.'];
    end
    candidates(end+1,1) = record; %#ok<AGROW>
end
end

function audit = audit_current_x_reference(axis,externalReference,limits)
reasons = {};
quality = struct();
quadratureWeightsStrictlyPositive = false;
if ~(isnumeric(axis) && isvector(axis) && isreal(axis) && ...
        all(isfinite(axis(:))))
    reasons{end+1} = 'axis_not_finite_real_numeric_vector';
else
    axis = double(axis(:)');
    if numel(axis) ~= numel(externalReference)
        reasons{end+1} = 'node_count_mismatch';
    end
    if mod(numel(axis),2) ~= 1
        reasons{end+1} = 'node_count_not_odd';
    end
    if numel(axis) < 2 || any(diff(axis) <= 0)
        reasons{end+1} = 'axis_not_strictly_increasing';
    end
    if numel(axis) >= 2 && ...
            ~matching_endpoints(axis,externalReference)
        reasons{end+1} = 'domain_endpoint_mismatch';
    end
    tolerance = 1e3*eps(max(1,max(abs(axis))));
    if mod(numel(axis),2) == 1 && ...
            max(abs(axis+fliplr(axis))) > tolerance
        reasons{end+1} = 'axis_not_symmetric';
    end
end
if isempty(reasons)
    try
        weights = ipm.mesh.quadrature(axis);
        quality = ipm.mesh.quality(axis,7,weights);
        quadratureWeightsStrictlyPositive = all(weights > 0);
        if quality.maximumAdjacentCellRatio > ...
                limits.maxAdjacentCellRatio
            reasons{end+1} = 'adjacent_cell_ratio';
        end
        if quality.maximumLogSpacingCurvature > ...
                limits.maxLogSpacingCurvature
            reasons{end+1} = 'log_spacing_curvature';
        end
        if quality.minimumStencilRcond < limits.minStencilRcond
            reasons{end+1} = 'stencil_conditioning';
        end
        if quality.minimumQuadratureWeightRatio < ...
                limits.minQuadratureWeightRatio || ...
                ~quadratureWeightsStrictlyPositive
            reasons{end+1} = 'quadrature_margin';
        end
    catch exception
        reasons{end+1} = ...
            ['diagnostic_error:' exception.identifier];
    end
end
audit = struct('passed',isempty(reasons), ...
    'rejectionReasons',{reasons},'meshLimits',limits, ...
    'quality',quality, ...
    'quadratureWeightsStrictlyPositive', ...
        quadratureWeightsStrictlyPositive, ...
    'axisSignature',struct());
if audit.passed
    audit.axisSignature = axis_signature(axis);
end
end

function record = build_equalized_x_candidate( ...
        referenceX,profiles,limits,stageOptions,equalizeOverrides)
if nargin < 5
    equalizeOverrides = struct();
end
records = profiles.records;
positiveLimit = referenceX(end);
coreIntervals = zeros(numel(records),2);
frontIntervals = zeros(numel(records),2);
for index = 1:numel(records)
    coreIntervals(index,:) = [ ...
        max(0,records(index).safetyCoreCenter- ...
            records(index).safetyCoreWidthLeft), ...
        min(positiveLimit,records(index).safetyCoreCenter+ ...
            records(index).safetyCoreWidthRight)];
    frontIntervals(index,:) = [ ...
        max(0,records(index).leftFrontCenter- ...
            records(index).leftFrontHalfWidth), ...
        min(positiveLimit,records(index).leftFrontCenter+ ...
            records(index).leftFrontHalfWidth)];
end
intervals = [coreIntervals;frontIntervals];
targets = [repmat(stageOptions.targetXCoreCells,numel(records),1); ...
    repmat(stageOptions.minimumXFrontCells,numel(records),1)];
focusCenters = [[records.safetyCoreCenter], ...
    [records.leftFrontCenter]];
equalizeOptions = direct_equalize_options( ...
    stageOptions.equalizationOptions,limits,'symmetric', ...
    focusCenters,'x');
if isfield(equalizeOverrides,'sigma')
    equalizeOptions.sigma = equalizeOverrides.sigma;
end
if isfield(equalizeOverrides,'kernelKind')
    equalizeOptions.kernelKind = equalizeOverrides.kernelKind;
end
if isfield(equalizeOverrides,'corridorShoulderCells')
    equalizeOptions.corridorShoulderCells = ...
        equalizeOverrides.corridorShoulderCells;
end
if isfield(equalizeOverrides,'corridorExpansionShoulders')
    equalizeOptions.corridorExpansionShoulders = ...
        equalizeOverrides.corridorExpansionShoulders;
end
[anchorPosition,anchorProvenance] = combined_x_anchor( ...
    records,coreIntervals,frontIntervals,positiveLimit);
equalizeOptions.anchorPhysicalPosition = anchorPosition;
if anchorProvenance.enabled
    % One smooth focus avoids the derivative switch introduced by taking
    % the minimum distance to separate core and front focus centres.
    equalizeOptions.focusCenters = anchorPosition;
    if isfield(equalizeOverrides,'power')
        equalizeOptions.power = equalizeOverrides.power;
    else
        equalizeOptions.power = 2;
    end
end
anchorProvenance.requestedFocusCenters = focusCenters;
anchorProvenance.effectiveFocusCenters = equalizeOptions.focusCenters;
anchorProvenance.requestedKernelPower = ...
    stageOptions.equalizationOptions.xPower;
anchorProvenance.effectiveKernelPower = equalizeOptions.power;
anchorProvenance.kernelSigma = equalizeOptions.sigma;
try
    [axis,info] = ipm_gridlab_equalize_axis( ...
        referenceX,intervals,targets,equalizeOptions);
catch exception
    record = candidate_template();
    if anchorProvenance.enabled
        record.name = 'x_anchored_global_logwidth_equalization_failed';
        record.family = 'anchored_global_logwidth_equalization';
        formula = [ ...
            'log(h)=log(h_ref)-A*exp(-(d(r(u),r(F))/sigma)^p)' ...
            '+beta*(psi(u_cell)-psi(u_anchor))'];
        kernelCoordinateBasis = ...
            'r(u)=u*tanh(u/delta)/tanh(u_anchor/delta)';
    else
        record.name = 'x_global_logwidth_equalization_failed';
        record.family = 'direct_global_logwidth_equalization';
        formula = 'log(h)=log(h_ref)-A*exp(-(d(u,F)/sigma)^p)';
        kernelCoordinateBasis = 'reference_coordinate_u';
    end
    record.status = 'failed';
    record.model = struct( ...
        'kind',record.family, ...
        'gridlabFamily',record.family, ...
        'formula',formula, ...
        'sigma',equalizeOptions.sigma, ...
        'power',equalizeOptions.power, ...
        'focusCenters',equalizeOptions.focusCenters, ...
        'kernelCoordinateBasis',kernelCoordinateBasis, ...
        'anchorEnabled',anchorProvenance.enabled, ...
        'anchorPhysicalPosition',anchorPosition, ...
        'anchorProvenance',anchorProvenance);
    record.errorIdentifier = exception.identifier;
    record.errorMessage = exception.message;
    return
end
info.anchorProvenance = anchorProvenance;
[coreCounts,frontCounts] = x_resolution(axis,records);
record = candidate_template();
if info.anchorEnabled
    record.name = sprintf( ...
        'x_anchored_global_logwidth_equalized_A_%.12g',info.amplitude);
    record.family = 'anchored_global_logwidth_equalization';
else
    record.name = sprintf('x_global_logwidth_equalized_A_%.12g', ...
        info.amplitude);
    record.family = 'direct_global_logwidth_equalization';
end
record.model = equalization_model(info);
record = fill_candidate(record,axis,info,coreCounts,frontCounts);
record.status = info.status;
record.meetsCoreTarget = ...
    record.minimumCoreCells >= stageOptions.targetXCoreCells;
record.meetsFrontTarget = ...
    record.minimumFrontCells >= stageOptions.minimumXFrontCells;
record.meetsTargets = record.admissible && ...
    record.meetsCoreTarget && record.meetsFrontTarget;
end

function [position,provenance] = combined_x_anchor( ...
        records,coreIntervals,frontIntervals,positiveLimit)
coreCenters = double([records.safetyCoreCenter]);
frontCenters = double([records.leftFrontCenter]);
allIntervals = [coreIntervals;frontIntervals];
intersection = [max(allIntervals(:,1)),min(allIntervals(:,2))];
tolerance = 1024*eps(max(1,positiveLimit));
candidatePosition = 0.5*sum(intersection);
if all(isfinite(intersection)) && ...
        intersection(2)-intersection(1) > tolerance && ...
        candidatePosition > 0 && candidatePosition < positiveLimit
    position = candidatePosition;
    enabled = true;
    reason = 'strict_common_interval_midpoint';
else
    position = [];
    enabled = false;
    reason = 'no_strictly_interior_common_interval';
end
provenance = struct( ...
    'enabled',enabled, ...
    'policy','all_record_core_front_common_intersection_midpoint', ...
    'reason',reason, ...
    'physicalPosition',position, ...
    'trustedRecordCount',numel(records), ...
    'positiveDomainLimit',positiveLimit, ...
    'commonIntersection',intersection, ...
    'coreIntervals',coreIntervals, ...
    'leftFrontIntervals',frontIntervals, ...
    'coreCenters',coreCenters, ...
    'leftFrontCenters',frontCenters, ...
    'focusPolicy','single_anchor_focus_when_enabled', ...
    'anchoredKernelPower',2);
end

function record = build_equalized_y_candidate( ...
        referenceY,profiles,limits,stageOptions,referenceProvenance)
records = profiles.records;
intervals = [zeros(numel(records),1), ...
    min(referenceY(end),[records.yCoreWidth]')];
targets = repmat(stageOptions.targetYCoreCells,numel(records),1);
equalizeOptions = direct_equalize_options( ...
    stageOptions.equalizationOptions,limits,'positive',0,'y');
if strcmp(referenceProvenance,'uniform_flat_tail_global_reference')
    equalizeOptions.sigma = ...
        stageOptions.equalizationOptions.uniformFlatTailSigma;
    equalizeOptions.power = ...
        stageOptions.equalizationOptions.uniformFlatTailPower;
end
[axis,info] = ipm_gridlab_equalize_axis( ...
    referenceY,intervals,targets,equalizeOptions);
info.referenceProvenance = referenceProvenance;
info.referenceAxisSignature = axis_signature(referenceY);
coreCounts = y_resolution(axis,records);
record = candidate_template();
if strcmp(referenceProvenance,'uniform_flat_tail_global_reference')
    record.name = sprintf( ...
        'y_uniform_flat_tail_logwidth_equalized_A_%.12g',info.amplitude);
    record.family = 'uniform_flat_tail_global_reference';
else
    record.name = sprintf('y_global_logwidth_equalized_A_%.12g', ...
        info.amplitude);
    record.family = 'direct_global_logwidth_equalization';
end
record.model = equalization_model(info);
record.model.referenceProvenance = referenceProvenance;
record = fill_candidate(record,axis,info,coreCounts,[]);
record.status = info.status;
record.meetsCoreTarget = ...
    record.minimumCoreCells >= stageOptions.targetYCoreCells;
record.meetsFrontTarget = true;
record.meetsTargets = record.admissible && record.meetsCoreTarget;
end

function options = direct_equalize_options( ...
        input,limits,geometry,focusCenters,label)
options = struct('geometry',geometry,'focusCenters',focusCenters, ...
    'initialAmplitude',input.initialAmplitude, ...
    'maximumAmplitude',input.maximumAmplitude, ...
    'amplitudeTolerance',input.amplitudeTolerance, ...
    'maxIterations',input.maxIterations,'meshLimits',limits);
if strcmp(label,'x')
    options.sigma = input.xSigma;
    options.power = input.xPower;
else
    options.sigma = input.ySigma;
    options.power = input.yPower;
end
end

function model = equalization_model(info)
if info.anchorEnabled
    formula = [ ...
        'log(h)=log(h_ref)-A*exp(-(d(r(u),r(F))/sigma)^p)' ...
        '+beta*(psi(u_cell)-psi(u_anchor))'];
    kind = 'anchored_global_logwidth_equalization';
else
    formula = 'log(h)=log(h_ref)-A*exp(-(d(u,F)/sigma)^p)';
    kind = 'direct_global_logwidth_equalization';
end
model = struct( ...
    'kind',kind, ...
    'gridlabFamily',kind, ...
    'formula',formula, ...
    'amplitude',info.amplitude,'sigma',info.sigma, ...
    'power',info.power,'focusCenters',info.focusCenters, ...
    'focusReferenceCoordinate',info.focusReferenceCoordinate, ...
    'kernelCoordinateBasis',info.kernelCoordinateBasis, ...
    'kernelSmoothingScale',info.kernelSmoothingScale, ...
    'kernelFocusCoordinate',info.kernelFocusCoordinate, ...
    'anchorEnabled',info.anchorEnabled, ...
    'anchorPhysicalPosition',info.anchorPhysicalPosition, ...
    'anchorReferenceCoordinate',info.anchorReferenceCoordinate, ...
    'anchorCorrectionBasis',info.anchorCorrectionBasis, ...
    'anchorCorrectionBeta',info.anchorCorrectionBeta, ...
    'anchorResidual',info.anchorResidual, ...
    'anchorMappedPhysicalPosition', ...
        info.anchorMappedPhysicalPosition, ...
    'ratioCapRelaxed',false);
if isfield(info,'anchorProvenance')
    model.anchorProvenance = info.anchorProvenance;
end
if isfield(info,'kernelKind') && strcmp(info.kernelKind,'corridor')
    model.kernelKind = info.kernelKind;
    model.kernelModel = info.kernelModel;
    model.corridorPhysicalBounds = info.corridorPhysicalBounds;
    model.corridorReferenceCoordinateBounds = ...
        info.corridorReferenceCoordinateBounds;
    model.corridorKernelCoordinateBounds = ...
        info.corridorKernelCoordinateBounds;
    model.corridorExpandedKernelCoordinateBounds = ...
        info.corridorExpandedKernelCoordinateBounds;
    model.corridorDelta = info.corridorDelta;
    model.corridorShoulderCells = info.corridorShoulderCells;
    model.corridorExpansionShoulders = ...
        info.corridorExpansionShoulders;
    model.corridorPositiveCellCount = ...
        info.corridorPositiveCellCount;
end
end

function candidates = build_x_candidates( ...
        dataset,profiles,models,nodeCount,axisOptions,options)
template = candidate_template();
candidates = repmat(template,numel(models),1);
for index = 1:numel(models)
    record = template;
    record.index = index;
    record.model = models{index};
    record.name = model_name(models{index},index,'x');
    record.family = model_family(models{index});
    try
        [axis,info] = ipm_gridlab_axis( ...
            dataset.xLimits,nodeCount,models{index},axisOptions);
        [coreCounts,frontCounts] = x_resolution(axis,profiles.records);
        record = fill_candidate(record,axis,info,coreCounts,frontCounts);
        record.meetsCoreTarget = ...
            record.minimumCoreCells >= options.targetXCoreCells;
        record.meetsFrontTarget = ...
            record.minimumFrontCells >= options.minimumXFrontCells;
        record.meetsTargets = record.admissible && ...
            record.meetsCoreTarget && record.meetsFrontTarget;
    catch exception
        record.status = 'failed';
        record.errorIdentifier = exception.identifier;
        record.errorMessage = exception.message;
    end
    candidates(index) = record;
end
end

function candidates = build_y_candidates( ...
        dataset,profiles,models,nodeCount,axisOptions,options)
template = candidate_template();
candidates = repmat(template,numel(models),1);
for index = 1:numel(models)
    record = template;
    record.index = index;
    record.model = models{index};
    record.name = model_name(models{index},index,'y');
    record.family = model_family(models{index});
    try
        [axis,info] = ipm_gridlab_axis_positive( ...
            dataset.yLimits,nodeCount,models{index},axisOptions);
        coreCounts = y_resolution(axis,profiles.records);
        record = fill_candidate(record,axis,info,coreCounts,[]);
        record.meetsCoreTarget = ...
            record.minimumCoreCells >= options.targetYCoreCells;
        record.meetsFrontTarget = true;
        record.meetsTargets = record.admissible && ...
            record.meetsCoreTarget;
    catch exception
        record.status = 'failed';
        record.errorIdentifier = exception.identifier;
        record.errorMessage = exception.message;
    end
    candidates(index) = record;
end
end

function template = candidate_template()
template = struct( ...
    'index',0,'name','','family','','model',struct(), ...
    'status','not_evaluated', ...
    'admissible',false,'meetsCoreTarget',false, ...
    'meetsFrontTarget',false,'meetsTargets',false, ...
    'axis',[],'axisInfo',struct(), ...
    'coreCellsBySnapshot',[],'frontCellsBySnapshot',[], ...
    'minimumCoreCells',-Inf,'minimumFrontCells',-Inf, ...
    'minimumCellWidth',NaN,'maximumCellWidth',NaN, ...
    'maximumAdjacentCellRatio',Inf, ...
    'maximumLogSpacingCurvature',Inf, ...
    'errorIdentifier','','errorMessage','');
end

function family = model_family(model)
if isfield(model,'gridlabFamily') && ...
        (ischar(model.gridlabFamily) || ...
        (isstring(model.gridlabFamily) && isscalar(model.gridlabFamily)))
    family = char(model.gridlabFamily);
else
    family = 'analytic_power_front';
end
end

function record = fill_candidate(record,axis,info,coreCounts,frontCounts)
record.status = 'generated';
record.admissible = info.admissible;
record.axis = axis;
record.axisInfo = info;
record.coreCellsBySnapshot = coreCounts(:)';
record.minimumCoreCells = min(coreCounts);
record.frontCellsBySnapshot = frontCounts(:)';
if isempty(frontCounts)
    record.minimumFrontCells = NaN;
else
    record.minimumFrontCells = min(frontCounts);
end
widths = diff(axis);
record.minimumCellWidth = min(widths);
record.maximumCellWidth = max(widths);
record.maximumAdjacentCellRatio = ...
    info.quality.maximumAdjacentCellRatio;
record.maximumLogSpacingCurvature = ...
    info.quality.maximumLogSpacingCurvature;
end

function [coreCounts,frontCounts] = x_resolution(axis,records)
positive = axis((numel(axis)+1)/2:end);
coreCounts = zeros(numel(records),1);
frontCounts = zeros(numel(records),1);
for index = 1:numel(records)
    profile = records(index);
    coreInterval = [ ...
        max(0,profile.safetyCoreCenter-profile.safetyCoreWidthLeft), ...
        min(positive(end),profile.safetyCoreCenter+ ...
            profile.safetyCoreWidthRight)];
    frontInterval = [ ...
        max(0,profile.leftFrontCenter-profile.leftFrontHalfWidth), ...
        min(positive(end),profile.leftFrontCenter+ ...
            profile.leftFrontHalfWidth)];
    coreCounts(index) = interval_cells(positive,coreInterval);
    frontCounts(index) = interval_cells(positive,frontInterval);
end
end

function coreCounts = y_resolution(axis,records)
coreCounts = zeros(numel(records),1);
for index = 1:numel(records)
    interval = [0,min(axis(end),records(index).yCoreWidth)];
    coreCounts(index) = interval_cells(axis,interval);
end
end

function count = interval_cells(axis,interval)
widths = diff(axis);
overlap = max(0,min(axis(2:end),interval(2))- ...
    max(axis(1:end-1),interval(1)));
count = sum(overlap./widths);
end

function name = model_name(model,index,prefix)
if isfield(model,'name') && ...
        (ischar(model.name) || ...
        (isstring(model.name) && isscalar(model.name)))
    name = char(model.name);
else
    name = sprintf('%s_candidate_%03d',prefix,index);
end
end

function [selectedIndex,order] = select_candidate(candidates)
eligible = find([candidates.meetsTargets]);
if isempty(eligible)
    selectedIndex = [];
    order = zeros(0,1);
    return
end
ranking = [[candidates(eligible).minimumCellWidth]', ...
    [candidates(eligible).maximumAdjacentCellRatio]', ...
    [candidates(eligible).maximumLogSpacingCurvature]',eligible(:)];
[~,localOrder] = sortrows( ...
    [-ranking(:,1),ranking(:,2),ranking(:,3),ranking(:,4)], ...
    [1,2,3,4]);
order = eligible(localOrder);
selectedIndex = order(1);
end

function feasibility = summarize_feasibility( ...
        xCandidates,yCandidates,options,limits)
xAdmitted = find([xCandidates.admissible]);
yAdmitted = find([yCandidates.admissible]);
xCore = candidate_bound(xCandidates,xAdmitted,'minimumCoreCells');
xFront = candidate_bound(xCandidates,xAdmitted,'minimumFrontCells');
yCore = candidate_bound(yCandidates,yAdmitted,'minimumCoreCells');
xWithFront = xAdmitted([xCandidates(xAdmitted).minimumFrontCells] >= ...
    options.minimumXFrontCells);
xCoreWithFront = candidate_bound( ...
    xCandidates,xWithFront,'minimumCoreCells');
xWithCore = xAdmitted([xCandidates(xAdmitted).minimumCoreCells] >= ...
    options.targetXCoreCells);
xFrontWithCore = candidate_bound( ...
    xCandidates,xWithCore,'minimumFrontCells');
feasibility = struct( ...
    'ratioCap',options.ratioCap,'ratioCapRelaxed',false, ...
    'meshLimits',limits, ...
    'x',struct( ...
        'candidateCount',numel(xCandidates), ...
        'admissibleCount',numel(xAdmitted), ...
        'feasibleCount',nnz([xCandidates.meetsTargets]), ...
        'requiredCoreCells',options.targetXCoreCells, ...
        'requiredFrontCells',options.minimumXFrontCells, ...
        'maximumCoreCells',xCore, ...
        'maximumFrontCells',xFront, ...
        'maximumCoreCellsWithFrontGate',xCoreWithFront, ...
        'maximumFrontCellsWithCoreGate',xFrontWithCore), ...
    'y',struct( ...
        'candidateCount',numel(yCandidates), ...
        'admissibleCount',numel(yAdmitted), ...
        'feasibleCount',nnz([yCandidates.meetsTargets]), ...
        'requiredCoreCells',options.targetYCoreCells, ...
        'maximumCoreCells',yCore));
end

function bound = candidate_bound(candidates,indices,field)
bound = struct('value',NaN,'candidateIndex',NaN, ...
    'candidateName','','candidateFamily','');
if isempty(indices)
    return
end
values = [candidates(indices).(field)];
[value,localIndex] = max(values);
index = indices(localIndex);
bound = struct('value',value,'candidateIndex',index, ...
    'candidateName',candidates(index).name, ...
    'candidateFamily',candidates(index).family);
end

function options = pair_score_options(input,profiles,limits,stageOptions)
options = input;
options.profiles = profiles;
options.minimumXCoreCells = stageOptions.targetXCoreCells;
options.minimumXFrontCells = stageOptions.minimumXFrontCells;
options.minimumYCoreCells = stageOptions.targetYCoreCells;
options.meshLimits = limits;
end

function selected = empty_selection()
selected = struct('xIndex',[],'yIndex',[], ...
    'xName','','yName','','x',[],'y',[], ...
    'xModel',struct(),'yModel',struct(), ...
    'xReferenceProvenance','','yReferenceProvenance','');
end

function policy = x_candidate_reference_policy(options)
tiers = {'external_original_reference_analytic'};
if options.enabled
    tiers{end+1} = ...
        'external_original_reference_anchored_gaussian_if_infeasible';
    if options.rootCorridorXFallbackEnabled
        tiers{end+1} = ...
            'external_original_reference_corridor_if_infeasible';
    end
    if options.currentAxisXFallbackEnabled
        tiers{end+1} = ...
            'trusted_terminal_axis_single_hop_if_infeasible';
    end
end
policy = strjoin(tiers,'_then_');
end

function provenance = candidate_reference_provenance(candidate)
provenance = 'external_original_reference';
if isfield(candidate.model,'referenceProvenance') && ...
        ~isempty(candidate.model.referenceProvenance)
    provenance = char(candidate.model.referenceProvenance);
end
end

function signature = axis_signature(axis)
axis = double(axis(:));
signature = struct('nodeCount',numel(axis), ...
    'endpoints',axis([1,end])', ...
    'minimumSpacing',min(diff(axis)), ...
    'maximumSpacing',max(diff(axis)), ...
    'spacingNorm',norm(diff(axis)), ...
    'weightedSum',sum((1:numel(axis))'.*axis));
end

function write_design(design,outputFile)
if isempty(outputFile)
    return
end
folder = fileparts(outputFile);
if ~isempty(folder) && ~isfolder(folder)
    error('ipm:gridlab:StageDesignOutputFolder', ...
        'The output folder does not exist: %s',folder);
end
save(outputFile,'design','-v7.3');
end
