function opts = activeCase()
%IPM.CONFIG.ACTIVECASE Maintained no-argument ipm.solve configuration.
%   This is a plain option override structure, not a second solver entry.

opts = struct( ...
    'initialCondition','degenerate_primitive', ...
    'degeneratePower',8, ...
    'nx',513,'ny',257, ...
    'xlim',[-1e5,1e5],'ymax',1e5, ...
    'targetCenterSpacing',[0.01,0.01], ...
    'physicalFinalTime',2,'maxDt',1e-2, ...
    'transportScheme','weno5_nonuniform', ...
    'rescalingMode','dynamic', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge','wall_omega_peak', ...
    'targetPeakPoints',64, ...
    'targetLevelPoints',[96,64,48], ...
    'targetPeakExpansion',8, ...
    'minimumPeakPoints',12, ...
    'minimumLevelPoints',[16,10,8], ...
    'initialAnalyticRemesh',true, ...
    'initialAnalyticRemeshPasses',6, ...
    'remeshSafetyTrigger',0.15, ...
    'remeshTargetSafety',0.08, ...
    'remeshOuterAnchorFactor',3, ...
    'remeshMaximumCellRatio',1.5, ...
    'remeshReferenceMode','current', ...
    'remeshAxisProfile','lattice', ...
    'remeshLatticeTransitionFraction',0.125, ...
    'remeshBridgeFloor',0.005, ...
    'remeshBridgePower',4);
end
