function opts = longTimeProfile(settings)
%IPM.CONFIG.LONGTIMEPROFILE Build the supported long-time server options.
%   OPTS = IPM.CONFIG.LONGTIMEPROFILE(SETTINGS) maps a small, user-facing
%   settings structure to the flat options consumed by IPM.SOLVE.  It does
%   not create files, build a two-dimensional Poisson operator, or start a
%   solve. Version-5 initialNodeCount='auto' samples the original analytic
%   datum and a one-dimensional derivative for a bounded no-LU preflight.

if nargin < 1 || isempty(settings)
    settings = struct();
end
if ~isstruct(settings) || ~isscalar(settings)
    error('ipm:BadLongTimeProfileSettings', ...
        'Long-time profile settings must be a scalar structure.');
end

defaults = struct( ...
    'boxHalfWidth',8, ...
    'boxHeight',4, ...
    'initialNodeCount',[321,161], ...
    'canonicalFinalTime',16, ...
    'maximumSteps',60000, ...
    'maximumTimeStep',0.005, ...
    'minimumTimeStep',1e-12, ...
    'outputEvery',0.01, ...
    'checkpointEvery',0.1, ...
    'maximumAdjacentGridRatio',2, ...
    'amplitudeGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',0.5, ...
    'autonomousMeshVersion',4, ...
    'meshDensityVersion',0, ...
    'maximumTotalNodes',310000, ...
    'outputDirectory',fullfile(pwd,'runs','long_time_profile'), ...
    'storeSnapshots',false, ...
    'makePlots',false, ...
    'verbose',true);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(settings),names,'stable');
if ~isempty(unexpected)
    error('ipm:BadLongTimeProfileSettings', ...
        'Unknown long-time profile setting(s): %s.', ...
        strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if isfield(settings,name)
        defaults.(name) = settings.(name);
    end
end
s = defaults;

validateattributes(s.boxHalfWidth,{'numeric'}, ...
    {'real','scalar','finite','>',4},mfilename,'boxHalfWidth');
validateattributes(s.boxHeight,{'numeric'}, ...
    {'real','scalar','finite','>=',4},mfilename,'boxHeight');
validateattributes(s.maximumTotalNodes,{'numeric'}, ...
    {'real','scalar','finite','integer','positive'},mfilename,'maximumTotalNodes');
autoInitial=(ischar(s.initialNodeCount)&&strcmpi(s.initialNodeCount,'auto'))|| ...
    (isstring(s.initialNodeCount)&&isscalar(s.initialNodeCount)&& ...
    ~ismissing(s.initialNodeCount)&&strcmpi(s.initialNodeCount,"auto"));
if autoInitial
    if ~isscalar(s.autonomousMeshVersion)||s.autonomousMeshVersion~=5
        error('ipm:BadLongTimeProfileSettings', ...
            'initialNodeCount=auto requires autonomousMeshVersion=5.');
    end
    s.initialNodeCount=automatic_initial_node_count(s);
end
validateattributes(s.initialNodeCount,{'numeric'}, ...
    {'real','vector','numel',2,'finite','integer','>=',9}, ...
    mfilename,'initialNodeCount');
if mod(s.initialNodeCount(1),2) ~= 1
    error('ipm:BadLongTimeProfileSettings', ...
        'initialNodeCount(1) must be odd for double-odd symmetry.');
end
validateattributes(s.canonicalFinalTime,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'canonicalFinalTime');
validateattributes(s.maximumSteps,{'numeric'}, ...
    {'real','scalar','finite','integer','positive'},mfilename,'maximumSteps');
validateattributes(s.maximumTimeStep,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'maximumTimeStep');
validateattributes(s.minimumTimeStep,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'minimumTimeStep');
if s.minimumTimeStep >= s.maximumTimeStep
    error('ipm:BadLongTimeProfileSettings', ...
        'minimumTimeStep must be smaller than maximumTimeStep.');
end
validateattributes(s.outputEvery,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'outputEvery');
validateattributes(s.checkpointEvery,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'checkpointEvery');
validateattributes(s.maximumAdjacentGridRatio,{'numeric'}, ...
    {'real','scalar','finite','>',1},mfilename,'maximumAdjacentGridRatio');
if isstring(s.amplitudeGauge) && isscalar(s.amplitudeGauge) && ...
        ~ismissing(s.amplitudeGauge)
    s.amplitudeGauge = char(s.amplitudeGauge);
end
if ~ischar(s.amplitudeGauge) || ~isrow(s.amplitudeGauge) || ...
        ~any(strcmp(s.amplitudeGauge, ...
            {'outer_wall_density_window_l2','wall_omega_quadratic_peak'}))
    error('ipm:BadLongTimeProfileSettings', ...
        'amplitudeGauge must be outer_wall_density_window_l2 or wall_omega_quadratic_peak.');
end
validateattributes(s.omegaGaugeWindowRadius,{'numeric'}, ...
    {'real','scalar','finite','>',0,'<',2}, ...
    mfilename,'omegaGaugeWindowRadius');
if ~isscalar(s.autonomousMeshVersion) || ~any(s.autonomousMeshVersion == [4,5])
    error('ipm:BadLongTimeProfileSettings', ...
        'autonomousMeshVersion must be 4 or 5.');
end
if s.autonomousMeshVersion == 4 && s.maximumTotalNodes ~= 310000
    error('ipm:BadLongTimeProfileSettings', ...
        'The qualified version-4 policy requires maximumTotalNodes=310000.');
end
if ~isnumeric(s.meshDensityVersion) || ~isscalar(s.meshDensityVersion) || ...
        ~isreal(s.meshDensityVersion) || ~isfinite(s.meshDensityVersion) || ...
        ~any(s.meshDensityVersion==[0,1,2]) || ...
        (s.meshDensityVersion~=0 && s.autonomousMeshVersion~=5)
    error('ipm:BadLongTimeProfileSettings', ...
        'meshDensityVersion must be 0, 1, or 2 with autonomousMeshVersion=5.');
end
nodeFamily=struct('maximumTotalNodes',double(s.maximumTotalNodes));
if s.autonomousMeshVersion == 5
    nodeFamily.initialNodeCount=double(s.initialNodeCount(:)');
end
for name = {'storeSnapshots','makePlots','verbose'}
    value = s.(name{1});
    if ~islogical(value) || ~isscalar(value)
        error('ipm:BadLongTimeProfileSettings', ...
            '%s must be a logical scalar.',name{1});
    end
end
outputDirectory = normalize_directory(s.outputDirectory);

opts = struct( ...
    'nx',double(s.initialNodeCount(1)), ...
    'ny',double(s.initialNodeCount(2)), ...
    'xlim',[-double(s.boxHalfWidth),double(s.boxHalfWidth)], ...
    'ymax',double(s.boxHeight), ...
    'gridMode','uniform', ...
    'gridStretchAutomatic',false, ...
    'gridStretch',[0,0], ...
    'initialCondition','degenerate_primitive', ...
    'degeneratePower',8, ...
    'rescalingMode','dynamic', ...
    'dynamicScaleGeometry','isotropic', ...
    'symmetryMode','double_odd_omega', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge',s.amplitudeGauge, ...
    'omegaGaugeWindowRadius',double(s.omegaGaugeWindowRadius), ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'wallTransportMode','conservative_flux', ...
    'transportBoundaryMode','open', ...
    'adaptiveRemesh',true, ...
    'initialAnalyticRemesh',true, ...
    'autonomousMesh',struct('version',double(s.autonomousMeshVersion), ...
        'nodeFamily',nodeFamily), ...
    'finalTime',double(s.canonicalFinalTime), ...
    'physicalFinalTime',Inf, ...
    'maxSteps',double(s.maximumSteps), ...
    'maxDt',double(s.maximumTimeStep), ...
    'minDt',double(s.minimumTimeStep), ...
    'outputEvery',double(s.outputEvery), ...
    'remeshMaximumCellRatio',double(s.maximumAdjacentGridRatio), ...
    'storeSnapshots',s.storeSnapshots, ...
    'saveResults',true, ...
    'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'makePlots',s.makePlots, ...
    'livePlot',false, ...
    'writeVideo',false, ...
    'verbose',s.verbose, ...
    'checkpoint',struct('enabled',true, ...
        'file',fullfile(outputDirectory,'checkpoint.mat'), ...
        'every',double(s.checkpointEvery),'atExit',true), ...
    'caseMetadata',struct( ...
        'kind','long_time_profile_server_v1', ...
        'manualMidRunGridChanges',false, ...
        'maximumAdjacentGridRatio',double(s.maximumAdjacentGridRatio), ...
        'amplitudeGauge',s.amplitudeGauge, ...
        'autonomousMeshVersion',double(s.autonomousMeshVersion)));

if autoInitial
    opts.caseMetadata.initialNodeCountSelection='analytic_no_LU_preflight_v1';
    opts.caseMetadata.selectedInitialNodeCount=double(s.initialNodeCount(:)');
end

if s.meshDensityVersion~=0
    opts.autonomousMesh.densityVersion=double(s.meshDensityVersion);
    opts.caseMetadata.meshDensityVersion=double(s.meshDensityVersion);
end

if s.boxHeight > 4
    opts.initialMeshObservationFallback = struct();
end

% Resolve here so invalid public settings fail before a server job starts.
config = ipm.config.resolve(opts);
assert(config.remesh.remeshMaximumCellRatio == ...
    s.maximumAdjacentGridRatio && ...
    config.remesh.autonomousMesh.version == s.autonomousMeshVersion && ...
    config.remesh.autonomousMesh.nodeFamily.maximumTotalNodes == ...
    s.maximumTotalNodes && ...
    (s.meshDensityVersion==0 || ...
    config.remesh.autonomousMesh.densityVersion==s.meshDensityVersion), ...
    'ipm:LongTimeProfileResolution', ...
    'The long-time profile settings did not survive configuration resolution.');
end

function selected=automatic_initial_node_count(settings)
% The original physical t=0 analytic datum is screened before a solver LU.
% Both axes grow only within the user's frozen node budget; the first
% cost-ordered pair with a qualified analytic initial family is selected.
cap=settings.maximumTotalNodes;
start=[321,161];
if cap<prod(start)
    error('ipm:LongTimeInitialNodeCapacity', ...
        'The node cap must cover the automatic 321x161 starting grid.');
end
if settings.boxHeight==4
    selected=start;return
end
xs=initial_count_schedule(start(1),floor(cap/start(2)),80,641);
ys=initial_count_schedule(start(2),floor(cap/start(1)),40,321);
rows=zeros(numel(xs)*numel(ys),3);count=0;
for nx=xs
    for ny=ys
        if nx*ny>cap,continue;end
        count=count+1;rows(count,:)=[nx*ny,nx,ny];
    end
end
rows=sortrows(rows(1:count,:),[1,2,3]);
for k=1:size(rows,1)
    trial=settings;trial.initialNodeCount=rows(k,2:3);
    opts=ipm.config.longTimeProfile(trial);
    config=ipm.config.resolve(opts);
    axes=struct('x',linspace(config.grid.xlim(1), ...
        config.grid.xlim(2),config.grid.nx), ...
        'y',linspace(0,config.grid.ymax,config.grid.ny)');
    [candidates,~]=ipm.remesh.planInitialAnalyticFallback(config,axes);
    if ~isempty(candidates)
        selected=rows(k,2:3);return
    end
end
error('ipm:LongTimeInitialNodeCapacity', ...
    'No registered initial node pair under maximumTotalNodes passed the analytic no-LU preflight.');
end

function values=initial_count_schedule(first,maximum,step,linearEnd)
values=first;
while values(end)<maximum
    if values(end)<linearEnd
        next=values(end)+step;
    else
        next=2*ceil((1.25*(values(end)-1)+1)/2)-1;
    end
    next=min(maximum,next);
    if mod(next,2)~=1,next=next-1;end
    if next<=values(end),break;end
    values(end+1)=next; %#ok<AGROW>
end
end

function value = normalize_directory(value)
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(strtrim(value))
    error('ipm:BadLongTimeProfileSettings', ...
        'outputDirectory must be a nonempty character vector or string scalar.');
end
end
