function opts = longTimeProfile(settings)
%IPM.CONFIG.LONGTIMEPROFILE Build the supported long-time server options.
%   OPTS = IPM.CONFIG.LONGTIMEPROFILE(SETTINGS) maps a small, user-facing
%   settings structure to the flat options consumed by IPM.SOLVE.  It does
%   not create files, build operators, or start a solve.

if nargin < 1 || isempty(settings)
    settings = struct();
end
if ~isstruct(settings) || ~isscalar(settings)
    error('ipm:BadLongTimeProfileSettings', ...
        'Long-time profile settings must be a scalar structure.');
end

defaults = struct( ...
    'boxHalfWidth',8, ...
    'boxHeight',4, ...
    'initialNodeCount',[321,161], ...
    'canonicalFinalTime',16, ...
    'maximumSteps',60000, ...
    'maximumTimeStep',0.005, ...
    'minimumTimeStep',1e-12, ...
    'outputEvery',0.01, ...
    'checkpointEvery',0.1, ...
    'maximumAdjacentGridRatio',2, ...
    'maximumTotalNodes',310000, ...
    'outputDirectory',fullfile(pwd,'runs','long_time_profile'), ...
    'storeSnapshots',false, ...
    'makePlots',false, ...
    'verbose',true);
names = fieldnames(defaults);
unexpected = setdiff(fieldnames(settings),names,'stable');
if ~isempty(unexpected)
    error('ipm:BadLongTimeProfileSettings', ...
        'Unknown long-time profile setting(s): %s.', ...
        strjoin(unexpected,', '));
end
for index = 1:numel(names)
    name = names{index};
    if isfield(settings,name)
        defaults.(name) = settings.(name);
    end
end
s = defaults;

validateattributes(s.boxHalfWidth,{'numeric'}, ...
    {'real','scalar','finite','>',4},mfilename,'boxHalfWidth');
validateattributes(s.boxHeight,{'numeric'}, ...
    {'real','scalar','finite','>=',4},mfilename,'boxHeight');
validateattributes(s.initialNodeCount,{'numeric'}, ...
    {'real','vector','numel',2,'finite','integer','>=',9}, ...
    mfilename,'initialNodeCount');
if mod(s.initialNodeCount(1),2) ~= 1
    error('ipm:BadLongTimeProfileSettings', ...
        'initialNodeCount(1) must be odd for double-odd symmetry.');
end
validateattributes(s.canonicalFinalTime,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'canonicalFinalTime');
validateattributes(s.maximumSteps,{'numeric'}, ...
    {'real','scalar','finite','integer','positive'},mfilename,'maximumSteps');
validateattributes(s.maximumTimeStep,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'maximumTimeStep');
validateattributes(s.minimumTimeStep,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'minimumTimeStep');
if s.minimumTimeStep >= s.maximumTimeStep
    error('ipm:BadLongTimeProfileSettings', ...
        'minimumTimeStep must be smaller than maximumTimeStep.');
end
validateattributes(s.outputEvery,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'outputEvery');
validateattributes(s.checkpointEvery,{'numeric'}, ...
    {'real','scalar','finite','positive'},mfilename,'checkpointEvery');
validateattributes(s.maximumAdjacentGridRatio,{'numeric'}, ...
    {'real','scalar','finite','>',1},mfilename,'maximumAdjacentGridRatio');
validateattributes(s.maximumTotalNodes,{'numeric'}, ...
    {'real','scalar','finite','integer','positive'},mfilename,'maximumTotalNodes');
if s.maximumTotalNodes ~= 310000
    error('ipm:BadLongTimeProfileSettings', ...
        'The qualified version-4 policy requires maximumTotalNodes=310000.');
end
for name = {'storeSnapshots','makePlots','verbose'}
    value = s.(name{1});
    if ~islogical(value) || ~isscalar(value)
        error('ipm:BadLongTimeProfileSettings', ...
            '%s must be a logical scalar.',name{1});
    end
end
outputDirectory = normalize_directory(s.outputDirectory);

opts = struct( ...
    'nx',double(s.initialNodeCount(1)), ...
    'ny',double(s.initialNodeCount(2)), ...
    'xlim',[-double(s.boxHalfWidth),double(s.boxHalfWidth)], ...
    'ymax',double(s.boxHeight), ...
    'gridMode','uniform', ...
    'gridStretchAutomatic',false, ...
    'gridStretch',[0,0], ...
    'initialCondition','degenerate_primitive', ...
    'degeneratePower',8, ...
    'rescalingMode','dynamic', ...
    'dynamicScaleGeometry','isotropic', ...
    'symmetryMode','double_odd_omega', ...
    'lengthGauge','transport_anchor', ...
    'transportAnchorX',1, ...
    'cOmegaGauge','wall_omega_quadratic_peak', ...
    'spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order', ...
    'wallTransportMode','conservative_flux', ...
    'transportBoundaryMode','open', ...
    'adaptiveRemesh',true, ...
    'initialAnalyticRemesh',true, ...
    'autonomousMesh',struct('version',4, ...
        'nodeFamily',struct('maximumTotalNodes',double(s.maximumTotalNodes))), ...
    'finalTime',double(s.canonicalFinalTime), ...
    'physicalFinalTime',Inf, ...
    'maxSteps',double(s.maximumSteps), ...
    'maxDt',double(s.maximumTimeStep), ...
    'minDt',double(s.minimumTimeStep), ...
    'outputEvery',double(s.outputEvery), ...
    'remeshMaximumCellRatio',double(s.maximumAdjacentGridRatio), ...
    'storeSnapshots',s.storeSnapshots, ...
    'saveResults',true, ...
    'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'makePlots',s.makePlots, ...
    'livePlot',false, ...
    'writeVideo',false, ...
    'verbose',s.verbose, ...
    'checkpoint',struct('enabled',true, ...
        'file',fullfile(outputDirectory,'checkpoint.mat'), ...
        'every',double(s.checkpointEvery),'atExit',true), ...
    'caseMetadata',struct( ...
        'kind','long_time_profile_server_v1', ...
        'manualMidRunGridChanges',false, ...
        'maximumAdjacentGridRatio',double(s.maximumAdjacentGridRatio), ...
        'autonomousMeshVersion',4));

if s.boxHeight > 4
    opts.initialMeshObservationFallback = struct();
end

% Resolve here so invalid public settings fail before a server job starts.
config = ipm.config.resolve(opts);
assert(config.remesh.remeshMaximumCellRatio == ...
    s.maximumAdjacentGridRatio && ...
    config.remesh.autonomousMesh.version == 4 && ...
    config.remesh.autonomousMesh.nodeFamily.maximumTotalNodes == ...
    s.maximumTotalNodes, ...
    'ipm:LongTimeProfileResolution', ...
    'The long-time profile settings did not survive configuration resolution.');
end

function value = normalize_directory(value)
if isstring(value) && isscalar(value) && ~ismissing(value)
    value = char(value);
end
if ~ischar(value) || ~isrow(value) || isempty(strtrim(value))
    error('ipm:BadLongTimeProfileSettings', ...
        'outputDirectory must be a nonempty character vector or string scalar.');
end
end
