function schema = schema()
%IPM.CONFIG.SCHEMA Single declarative contract for public IPM options.

schema.domainNames = {'grid','time','physics','elliptic','transport', ...
    'scaling','remesh','diagnostics','output'};

rules = struct();
rules.gridCount = {'scalar','real','finite','integer','>=',9};
rules.domain = {'vector','numel',2,'real','finite'};
rules.positiveFinite = {'scalar','real','positive','finite'};
rules.nonnegativeFinite = {'scalar','real','finite','nonnegative'};
rules.positiveNonnan = {'scalar','real','positive','nonnan'};
rules.cfl = {'scalar','real','finite','>',0,'<=',0.5};
rules.positiveInteger = {'scalar','real','finite','integer','>=',1};
rules.integerAtLeastTwo = {'scalar','real','finite','integer','>=',2};
rules.nonnegativeVector = {'vector','nonempty','real','>=',0,'finite'};
rules.positiveVector = {'vector','nonempty','real','positive','finite'};
rules.gaugeLevels = {'vector','numel',2,'real','finite','>',0,'<',1,'increasing'};
rules.openUnitScalar = {'scalar','real','finite','positive','<',1};
rules.peakPointCount = {'scalar','real','finite','integer','>=',4};
rules.openUnitVector = {'vector','nonempty','real','finite','>',0,'<',1};
rules.positiveIntegerVector = {'vector','nonempty','real','finite','integer','positive'};
rules.atLeastOne = {'scalar','real','finite','>=',1};
rules.minimumPeakCount = {'scalar','real','finite','integer','>=',2};
rules.integerVectorAtLeastTwo = {'vector','nonempty','real','finite','integer','>=',2};
rules.greaterThanOne = {'scalar','real','finite','>',1};
rules.finiteScalar = {'scalar','real','finite'};
rules.positiveIntegerStrict = {'scalar','real','finite','integer','positive'};
rules.closedUnitUpper = {'scalar','real','finite','>',0,'<=',1};
rules.openUnitInterval = {'scalar','real','finite','>',0,'<',1};
rules.nonnegativeNonnan = {'scalar','real','nonnan','>=',0};
rules.nonnegativeOpenUnit = {'scalar','real','finite','>=',0,'<',1};
rules.nonnegativeInteger = {'scalar','real','finite','integer','>=',0};
rules.percentage = {'scalar','real','finite','>=',0,'<=',100};
rules.greenSourceCount = {'scalar','real','finite','integer','>=',100};
rules.exactOne = {'scalar','real','finite','>=',1,'<=',1};
rules.exactZero = {'scalar','real','finite','>=',0,'<=',0};
schema.rules = rules;

% name, domain, raw default, hasDefault, kind, rule, allowed values, error ID
spec = { ...
    'nx','grid',1025,true,'numeric','gridCount',{},''; ...
    'ny','grid',513,true,'numeric','gridCount',{},''; ...
    'xlim','grid',[-2000,2000],true,'numeric','domain',{},''; ...
    'quadrantOnly','grid',[],false,'boolean','',{},'ipm:BadQuadrantOnly'; ...
    'ymax','grid',2000,true,'numeric','positiveFinite',{},''; ...
    'gridMode','grid','stretched',true,'enum','', ...
        {'uniform','stretched'},'ipm:BadGridMode'; ...
    'gridStretch','grid',[],true,'numeric','nonnegativeVector',{},''; ...
    'gridStretchAutomatic','grid',true,true,'boolean','',{},'ipm:BadBoolean'; ...
    'targetCenterSpacing','grid',[0.01,0.01],true,'numeric','positiveVector',{},''; ...
    'finalTime','time',10,true,'numeric','positiveNonnan',{},''; ...
    'physicalFinalTime','time',Inf,true,'numeric','positiveNonnan',{},''; ...
    'cfl','time',0.35,true,'numeric','cfl',{},''; ...
    'maxDt','time',2.5e-4,true,'numeric','positiveFinite',{},''; ...
    'minDt','time',1e-10,true,'numeric','positiveFinite',{},''; ...
    'maxSteps','time',200000,true,'numeric','positiveNonnan',{},''; ...
    'outputEvery','time',0.002,true,'numeric','positiveFinite',{},''; ...
    'timeIntegrator','time','ssprk3',true,'enum','', ...
        {'ssprk3','ssprk54','rk6'},'ipm:BadTimeIntegrator'; ...
    'gradientStop','diagnostics',1e6,true,'numeric','positiveFinite',{},''; ...
    'rangeStopTolerance','diagnostics',5e-3,true,'numeric','positiveFinite',{},''; ...
    'farBoundaryTolerance','diagnostics',1e-2,true,'numeric','positiveFinite',{},''; ...
    'farBoundaryMode','elliptic','green',true,'enum','', ...
        {'green','dirichlet_zero'},'ipm:BadFarBoundaryMode'; ...
    'transportBoundaryMode','transport','open',true,'enum','', ...
        {'open','closed'},'ipm:BadTransportBoundaryMode'; ...
    'transportScheme','transport','muscl_minmod',true,'enum','', ...
        {'muscl_minmod','weno5_nonuniform','weno5_fd','weno7_fd'}, ...
        'ipm:BadTransportScheme'; ...
    'spatialDiscretization','transport','legacy_second_order',true, ...
        'enum','',{'legacy_second_order','high_order','sixth_order'}, ...
        'ipm:BadSpatialDiscretization'; ...
    'wallTransportMode','transport','conservative_flux',true,'enum','', ...
        {'conservative_flux','advective_upwind'},'ipm:BadWallTransportMode'; ...
    'wenoEpsilon','transport',1e-12,true,'numeric','positiveFinite',{},''; ...
    'symmetryMode','physics','double_odd_omega',true,'enum','', ...
        {'double_odd_omega','half_plane'},'ipm:BadSymmetryMode'; ...
    'greenSourceTolerance','elliptic',1e-6,true,'numeric','openUnitScalar',{},''; ...
    'greenMaxSources','elliptic',3000,true,'numeric','greenSourceCount',{},''; ...
    'initialCondition','physics','degenerate',true,'initial_condition','', ...
        {'unstable_front','smooth_blob','degenerate','degenerate_primitive', ...
        'ccf_heavy_tail'},'ipm:BadInitialCondition'; ...
    'frontHeight','physics',1.75,true,'numeric','nonnegativeFinite',{},''; ...
    'frontAmplitude','physics',0.45,true,'numeric','nonnegativeFinite',{},''; ...
    'frontWidth','physics',2.0,true,'numeric','positiveFinite',{},''; ...
    'frontThickness','physics',0.12,true,'numeric','positiveFinite',{},''; ...
    'degeneratePower','physics',4,true,'numeric','integerAtLeastTwo',{},''; ...
    'ccfTailOnset','physics',1.0,true,'numeric','positiveFinite',{},''; ...
    'ccfTailRegularization','physics',0.08,true,'numeric','positiveFinite',{},''; ...
    'ccfTailAmplitude','physics',1.0,true,'numeric','positiveFinite',{},''; ...
    'ccfTailCutoffScale','physics',16.0,true,'numeric','positiveNonnan',{},''; ...
    'ccfTailVerticalScale','physics',2.0,true,'numeric','positiveFinite',{},''; ...
    'ccfTailVerticalPower','physics',4,true,'numeric','integerAtLeastTwo',{},''; ...
    'rescalingMode','scaling','physical',true,'enum','', ...
        {'physical','dynamic'},'ipm:BadRescalingMode'; ...
    'dynamicScaleGeometry','scaling','isotropic',true,'enum','', ...
        {'isotropic','anisotropic'},'ipm:BadDynamicScaleGeometry'; ...
    'anisotropicGaugeMode','scaling','fixed',true,'enum','', ...
        {'fixed','peak_translation'},'ipm:BadAnisotropicGaugeMode'; ...
    'anisotropicFixedCX','scaling',0,true,'numeric','finiteScalar',{},''; ...
    'anisotropicFixedCY','scaling',0,true,'numeric','finiteScalar',{},''; ...
    'anisotropicFixedCOmega','scaling',0,true,'numeric','finiteScalar',{},''; ...
    'anisotropicFixedCR','scaling',0,true,'numeric','finiteScalar',{},''; ...
    'anisotropicPoissonSolver','elliptic','direct',true,'enum','', ...
        {'direct','pcg'},'ipm:BadAnisotropicPoissonSolver'; ...
    'anisotropicPoissonTolerance','elliptic',1e-11,true,'numeric','openUnitScalar',{},''; ...
    'anisotropicPoissonMaxIterations','elliptic',400,true,'numeric', ...
        'positiveIntegerStrict',{},''; ...
    'scalingContract','scaling','exact_gauge_no_feedback_v1',true, ...
        'enum','',{'exact_gauge_no_feedback_v1'}, ...
        'ipm:BadScalingContract'; ...
    'cOmegaGauge','scaling','wall_omega_peak',true,'enum','', ...
        {'wall_omega_peak','wall_omega_quadratic_peak', ...
        'gradient_energy','strain_point', ...
        'anchor_wall_slope','anchor_wall_strain', ...
        'anchor_wall_window_l2','anchor_wall_template_projection', ...
        'anchor_bulk_gradient_l2','anchor_wall_window_l4', ...
        'outer_wall_density_window_l2','none'}, ...
        'ipm:BadCOmegaGauge'; ...
    'cOmegaGaugeFloor','scaling',1e-20,true,'numeric','positiveFinite',{},''; ...
    'pointStrainConditionFloor','scaling',1e-6,true,'numeric','openUnitScalar',{},''; ...
    'omegaGaugeWindowRadius','scaling',0.75,true,'numeric','positiveFinite',{},''; ...
    'lengthGauge','scaling','omega_peak_location',true,'enum','', ...
        {'omega_peak_location','wall_omega_width','symmetry_peak', ...
        'transport_anchor','wall_density_width','local_strain'},'ipm:BadLengthGauge'; ...
    'transportAnchorX','scaling',1.0,true,'numeric','positiveFinite',{},''; ...
    'lengthGaugeLevels','scaling',[0.2,0.6],true,'numeric','gaugeLevels',{},''; ...
    'lengthScaleGain','scaling',1.0,true,'numeric','exactOne',{},''; ...
    'widthGaugeGain','scaling',0.0,true,'numeric','exactZero',{},''; ...
    'omegaGaugeGain','scaling',0.0,true,'numeric','exactZero',{},''; ...
    'targetPeakPoints','scaling',32,true,'numeric','peakPointCount',{},''; ...
    'adaptiveLevels','scaling',[0.1,0.5,0.9],true,'numeric','openUnitVector',{},''; ...
    'targetLevelPoints','scaling',[64,32,16],true,'numeric','positiveIntegerVector',{},''; ...
    'targetPeakExpansion','scaling',1.5,true,'numeric','atLeastOne',{},''; ...
    'minimumPeakPoints','scaling',12,true,'numeric','minimumPeakCount',{},''; ...
    'minimumLevelPoints','scaling',[16,8,4],true,'numeric','integerVectorAtLeastTwo',{},''; ...
    'peakTrackingWidthFactor','scaling',3.0,true,'numeric','atLeastOne',{},''; ...
    'travelingWaveGain','scaling',0.0,true,'numeric','exactZero',{},''; ...
    'adaptiveRemesh','remesh',true,true,'boolean','',{},'ipm:BadBoolean'; ...
    'initialAnalyticRemesh','remesh',false,true,'boolean','',{},'ipm:BadBoolean'; ...
    'initialAnalyticRemeshPasses','remesh',1,true,'numeric','positiveInteger',{},''; ...
    'remeshSafetyTrigger','remesh',0.75,true,'numeric','positiveFinite',{},''; ...
    'remeshConcentration','remesh',30.0,true,'numeric','positiveFinite',{},''; ...
    'remeshWindowFactor','remesh',4.0,true,'numeric','atLeastOne',{},''; ...
    'remeshAxisProfile','remesh','nested',true,'enum','', ...
        {'nested','lattice'},'ipm:BadRemeshAxisProfile'; ...
    'remeshLatticeTransitionFraction','remesh',0.125,true,'numeric', ...
        'closedUnitUpper',{},''; ...
    'remeshTargetSafety','remesh',0.4,true,'numeric','openUnitInterval',{},''; ...
    'remeshMaximumCellRatio','remesh',6.0,true,'numeric','greaterThanOne',{},''; ...
    'remeshBridgeFloor','remesh',0.05,true,'numeric','openUnitInterval',{},''; ...
    'remeshBridgePower','remesh',2.0,true,'numeric','atLeastOne',{},''; ...
    'remeshOuterAnchorFactor','remesh',Inf,true,'numeric','positiveNonnan',{},''; ...
    'remeshReferenceMode','remesh','original',true,'enum','', ...
        {'original','current'},'ipm:BadRemeshReferenceMode'; ...
    'remeshTransferScheme','remesh','pchip',true,'enum','', ...
        {'pchip','high_order','sixth_order'},'ipm:BadRemeshTransferScheme'; ...
    'remeshMinimumSpacingFactor','remesh',1e-4,true,'numeric','closedUnitUpper',{},''; ...
    'remeshMinimumImprovement','remesh',0.02,true,'numeric','nonnegativeOpenUnit',{},''; ...
    'remeshPeakChangeTolerance','remesh',0.03,true,'numeric','openUnitInterval',{},''; ...
    'maxRemeshes','remesh',300,true,'numeric','nonnegativeInteger',{},''; ...
    'oscillationTVTolerance','diagnostics',1.02,true,'numeric','atLeastOne',{},''; ...
    'positiveWallNegativeTolerance','diagnostics',1e-3,true,'numeric', ...
        'nonnegativeNonnan',{},''; ...
    'storeSnapshots','output',false,true,'boolean','',{},'ipm:BadBoolean'; ...
    'saveResults','output',true,true,'boolean','',{},'ipm:BadBoolean'; ...
    'resultFile','output',fullfile('result','production', ...
        'ipm_double_odd_dynamic.mat'),true,'path','',{},'ipm:BadOutputPath'; ...
    'makePlots','output',true,true,'boolean','',{},'ipm:BadBoolean'; ...
    'livePlot','output',true,true,'boolean','',{},'ipm:BadBoolean'; ...
    'writeVideo','output',true,true,'boolean','',{},'ipm:BadBoolean'; ...
    'videoFile','output',fullfile('result','production','ipm_evolution.mp4'), ...
        true,'path','',{},'ipm:BadOutputPath'; ...
    'videoFrameRate','output',20,true,'numeric','positiveFinite',{},''; ...
    'videoQuality','output',95,true,'numeric','percentage',{},''; ...
    'verbose','output',true,true,'boolean','',{},'ipm:BadBoolean'; ...
    'caseMetadata','output',struct(),true,'metadata','',{},'ipm:BadCaseMetadata'; ...
    'checkpoint','output',[],false,'checkpoint','',{}, ...
        'ipm:BadCheckpointPolicy'; ...
    'initialMeshObservationFallback','remesh',[],false,'initial_mesh_observation','',{}, ...
        'ipm:BadInitialMeshObservationPolicy'; ...
    'autonomousMesh','remesh',[],false,'autonomous_mesh','',{}, ...
        'ipm:BadAutonomousMeshPolicy'; ...
    'customX','grid',[],false,'custom_coordinate','',{},'ipm:CustomGridPair'; ...
    'customY','grid',[],false,'custom_coordinate','',{},'ipm:CustomGridPair'};

options = struct();
for index = 1:size(spec,1)
    descriptor = struct('domain',spec{index,2},'default',spec{index,3}, ...
        'hasDefault',spec{index,4},'kind',spec{index,5}, ...
        'rule',spec{index,6},'allowed',[],'errorId',spec{index,8});
    descriptor.allowed = spec{index,7};
    options.(spec{index,1}) = descriptor;
end
schema.options = options;
end
