function options = sixthOrder(overrides)
%IPM.CONFIG.SIXTHORDER Explicit opt-in sixth-order production tuple.
%   OPTIONS = IPM.CONFIG.SIXTHORDER() selects the complete sixth-order
%   numerical tuple on a fixed uniform grid with conservative certified
%   boundary and time-step settings. OPTIONS =
%   IPM.CONFIG.SIXTHORDER(OVERRIDES) applies caller fields last; the
%   standard configuration resolver remains the final validator.

if nargin < 1
    overrides = struct();
end
if ~isstruct(overrides) || ~isscalar(overrides)
    error('ipm:SixthOrderOverrides', ...
        'OVERRIDES must be a scalar structure.');
end
policy = ipm.mesh.sixthOrderPolicy();
options = struct( ...
    'spatialDiscretization','sixth_order', ...
    'transportScheme','weno7_fd', ...
    'timeIntegrator','rk6', ...
    'remeshTransferScheme','sixth_order', ...
    'gridMode','uniform', ...
    'gridStretchAutomatic',false, ...
    'gridStretch',[0,0], ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','closed', ...
    'wallTransportMode','conservative_flux', ...
    'rescalingMode','physical', ...
    'dynamicScaleGeometry','isotropic', ...
    'adaptiveRemesh',false, ...
    'initialAnalyticRemesh',false, ...
    'cfl',policy.recommendedCfl);
names = fieldnames(overrides);
for index = 1:numel(names)
    options.(names{index}) = overrides.(names{index});
end
end
