function [identifier,message] = tupleViolation( ...
        transportScheme,spatialDiscretization,timeIntegrator, ...
        remeshTransferScheme, ...
        dynamicScaleGeometry,anisotropicPoissonSolver)
%IPM.CONFIG.TUPLEVIOLATION Validate coupled numerical selectors.

identifier = '';
message = '';
if strcmp(spatialDiscretization,'sixth_order') && ...
        ~strcmp(transportScheme,'weno7_fd')
    identifier = 'ipm:SixthOrderTransport';
    message = ['spatialDiscretization=''sixth_order'' requires ' ...
        'transportScheme=''weno7_fd''.'];
elseif strcmp(transportScheme,'weno7_fd') && ...
        ~strcmp(spatialDiscretization,'sixth_order')
    identifier = 'ipm:Weno7RequiresSixthOrder';
    message = ['transportScheme=''weno7_fd'' requires ' ...
        'spatialDiscretization=''sixth_order''.'];
elseif strcmp(spatialDiscretization,'sixth_order') && ...
        ~strcmp(timeIntegrator,'rk6')
    identifier = 'ipm:SixthOrderTimeIntegrator';
    message = ['spatialDiscretization=''sixth_order'' requires ' ...
        'timeIntegrator=''rk6''.'];
elseif strcmp(timeIntegrator,'rk6') && ...
        ~strcmp(spatialDiscretization,'sixth_order')
    identifier = 'ipm:Rk6RequiresSixthOrder';
    message = ['timeIntegrator=''rk6'' requires ' ...
        'spatialDiscretization=''sixth_order''.'];
elseif strcmp(spatialDiscretization,'sixth_order') && ...
        ~strcmp(remeshTransferScheme,'sixth_order')
    identifier = 'ipm:SixthOrderRemesh';
    message = ['spatialDiscretization=''sixth_order'' requires ' ...
        'remeshTransferScheme=''sixth_order'' so any later remesh keeps ' ...
        'the paired quadrature and interpolation order.'];
elseif strcmp(remeshTransferScheme,'sixth_order') && ...
        ~strcmp(spatialDiscretization,'sixth_order')
    identifier = 'ipm:SixthOrderRemeshRequiresSixthOrder';
    message = ['remeshTransferScheme=''sixth_order'' requires ' ...
        'spatialDiscretization=''sixth_order''.'];
elseif strcmp(transportScheme,'weno5_fd') && ...
        ~strcmp(spatialDiscretization,'high_order')
    identifier = 'ipm:WenoFdRequiresHighOrder';
    message = ['transportScheme=''weno5_fd'' requires ' ...
        'spatialDiscretization=''high_order''.'];
elseif strcmp(remeshTransferScheme,'high_order') && ...
        ~strcmp(spatialDiscretization,'high_order')
    identifier = 'ipm:HighOrderRemeshRequiresHighOrder';
    message = ['remeshTransferScheme=''high_order'' requires the paired ' ...
        'high-order quadrature from spatialDiscretization=''high_order''.'];
elseif any(strcmp(spatialDiscretization,{'high_order','sixth_order'})) && ...
        strcmp(dynamicScaleGeometry,'anisotropic') && ...
        strcmp(anisotropicPoissonSolver,'pcg')
    identifier = 'ipm:HighOrderPoissonSolver';
    message = ['The experimental full-order boundary closure is ' ...
        'nonsymmetric and currently supports the direct anisotropic ' ...
        'solver only.'];
end
end
