function report=audit_cross_level_mesh_at_request(beforeCheckpoint, ...
        afterCheckpoint,transactionIndex,outputDirectory)
%AUDIT_CROSS_LEVEL_MESH_AT_REQUEST Compare frozen native and grown grids.
% Replays one signed source. Alternatives remain local, with no checkpoint
% or controller transaction committed. Large Poisson factors are built and
% released sequentially so production runs can continue on this machine.
assert(~isfolder(outputDirectory) && maxNumCompThreads==10);
before=ipm.output.readCheckpoint(beforeCheckpoint);
after=ipm.output.readCheckpoint(afterCheckpoint);
b=before.payload.state;a=after.payload.state;
assert(all(ipm.output.trustedMask(before.payload.log.history,b.config)) && ...
    all(ipm.output.trustedMask(after.payload.log.history,a.config)) && ...
    strcmp(b.runMetadata.caseId,a.runMetadata.caseId));
ledger=a.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>=transactionIndex && b.step<ledger(transactionIndex).sourceStep);
signed=ledger(transactionIndex);
[source,~,~]=ipm.output.restoreCheckpoint(before,struct());
clear before after a b
plan=[];
while source.step<signed.sourceStep
    [source,reason,plan]=ipm.evolve.advance(source);
    assert(isempty(reason),'ipm:CrossLevelReplayStopped');
    if ~isempty(plan),break;end
end
assert(~isempty(plan) && plan.requested && ...
    source.step==signed.sourceStep && ...
    source.scale.canonicalTime==signed.sourceCanonicalTime && ...
    isequaln(plan.coreCells,signed.controllerDecision.coreCells) && ...
    strcmp(plan.reason,signed.controllerDecision.reason), ...
    'ipm:CrossLevelSourceMismatch');
assert(signed.candidateIndex==1 && numel(plan.candidates)>=8 && ...
    plan.candidates(8).targetLevelId~=plan.sourceLevelId);
policy=source.config.remesh.autonomousMesh;
pre=observe(source,source.rhsCache.rhoRate,[]);
source.ops=rmfield(source.ops,'poisson');
indices=[1,8]; observations=cell(1,2);rows=struct([]);
for j=1:2
    k=indices(j);p=plan.candidates(k);
    proposal=struct('x',p.x,'y',p.y, ...
        'referenceFamily',source.runMetadata.autonomousMesh.referenceFamily, ...
        'sourceLevelId',plan.sourceLevelId, ...
        'targetLevelId',p.targetLevelId);
    trial=source;
    timer=tic;
    [trial.rho,trial.ops]=ipm.remesh.transfer( ...
        source.rho,source.ops,source.config,proposal);
    transferSeconds=toc(timer);
    audit=ipm.remesh.auditCandidate(source,trial,policy, ...
        source.runMetadata.autonomousMesh.cumulativeAbsolutePeakJump);
    timer=tic;
    [rhoRate,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
    flowSeconds=toc(timer);
    postPassed=audit.passed && ipm.evolve.isFinite(trial) && ...
        trial.flow.safetyFactor<policy.maximumSafety && ...
        all([trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints] ...
        >=policy.transactionMinimumCoreCells);
    observations{j}=observe(trial,rhoRate,pre.geometry);
    row=struct('candidateIndex',k,'xScheduleIndex',p.xIndex, ...
        'yTrialIndex',p.yIndex,'targetLevelId',p.targetLevelId, ...
        'nodeCount',[trial.ops.nx,trial.ops.ny], ...
        'totalNodes',trial.ops.nx*trial.ops.ny, ...
        'predictedCoreCells',p.predictedCells(1:2), ...
        'maximumAdjacentRatio',max( ...
        p.quality.x.maximumAdjacentCellRatio, ...
        p.quality.y.maximumAdjacentCellRatio), ...
        'auditPassed',audit.passed,'auditReasons',{audit.reasons}, ...
        'postFlowPassed',postPassed,'actualCoreCells',audit.coreCells, ...
        'relativePeakJump',audit.relativePeakJump, ...
        'massRelativeDefect',audit.massRelativeDefect, ...
        'relativeRangeViolation',audit.relativeRangeViolation, ...
        'safetyFactor',trial.flow.safetyFactor, ...
        'transferSeconds',transferSeconds,'flowSeconds',flowSeconds, ...
        'geometry',observations{j}.geometry, ...
        'c1',observations{j}.c1, ...
        'nativeCOmega',trial.flow.c_omega, ...
        'tangentRefinement',observations{j}.refinement);
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
    fprintf('CROSS_LEVEL k=%d nodes=%d ratio=%.6f audit=%d flow=%d transfer=%.2fs rhs=%.2fs\n', ...
        k,row.totalNodes,row.maximumAdjacentRatio,row.auditPassed, ...
        row.postFlowPassed,row.transferSeconds,row.flowSeconds);
    clear trial rhoRate audit proposal
end
assert(rows(1).auditPassed && rows(1).postFlowPassed && ...
    isequaln(rows(1).actualCoreCells,signed.coreCells) && ...
    rows(1).relativePeakJump==signed.relativePeakJump && ...
    rows(1).massRelativeDefect==signed.massRelativeDefect && ...
    rows(1).relativeRangeViolation==signed.relativeRangeViolation, ...
    'ipm:CrossLevelBaselineMismatch');
report=struct('kind','frozen_cross_level_original_rhs_mesh_comparison_v1', ...
    'beforeCheckpoint',beforeCheckpoint,'afterCheckpoint',afterCheckpoint, ...
    'transactionIndex',transactionIndex,'sourceTau',signed.sourceCanonicalTime, ...
    'sourceStep',signed.sourceStep,'sourceDecisionEqualsSigned',true, ...
    'baselineAuditEqualsSigned',true,'rows',{rows}, ...
    'baselineToGrowthShape',compare_pair( ...
        observations{1}.shape,observations{2}.shape), ...
    'baselineToGrowthTangent',compare_pair( ...
        observations{1}.tangent,observations{2}.tangent), ...
    'preToBaselineTangent',compare_pair(pre.tangent,observations{1}.tangent), ...
    'preToGrowthTangent',compare_pair(pre.tangent,observations{2}.tangent), ...
    'baselineToGrowthFields',compare_fields( ...
        observations{1}.fields,observations{2}.fields), ...
    'sourceToGrowthFields',compare_fields(pre.fields,observations{2}.fields), ...
    'growthNodeMultiplier',rows(2).totalNodes/rows(1).totalNodes, ...
    'alternativeTransactionCommitted',false, ...
    'futureLifetimeOrContinuumAccuracyCertified',false, ...
    'interpretation','Same-time discrete comparison on frozen original RHS. Lower ratio or closer tangent alone does not certify continuum accuracy or amortized runtime.');
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end

function o=observe(s,rhoRate,common)
ops=s.ops;omega=s.rho*ops.Dx';omegaRate=rhoRate*ops.Dx';
window=s.config.scaling.transportAnchorX*[.8,1.15];
g=continuous_inner_geometry(omega,ops.x,ops.y,ops.Dx,ops.Dy,window);
if isempty(common),common=g;end
o.geometry=struct('peakX',g.peakX,'peak',g.peak, ...
    'wallWidth',g.wallWidth,'verticalWidth',g.verticalWidth);
c1=ipm_accellab_continuous_inner_rates(omega,omegaRate, ...
    ops.x,ops.y,ops.Dx,ops.Dy,window);
o.c1=struct('valid',c1.valid,'peakPrime',c1.peak.PPrime, ...
    'relativePeakRate',c1.peak.PPrime/c1.peak.value, ...
    'phaseRate',NaN,'logWidthRates',[NaN,NaN]);
if c1.valid
    o.c1.phaseRate=c1.translationRate;
    o.c1.logWidthRates=[c1.logScaleXRate,c1.logScaleYRate];
end
o.shape=sample_shape(s.rho,ops,s.config);
epsilons=[1e-5,5e-6];t=cell(1,2);
for h=1:2
    u=sample_shape(s.rho+epsilons(h)*rhoRate,ops,s.config);
    t{h}=struct('wall',(u.wall-o.shape.wall)/epsilons(h), ...
        'vertical',(u.vertical-o.shape.vertical)/epsilons(h));
end
o.tangent=t{2};o.refinement=compare_pair(t{1},t{2});
names={'rho','omega','rhoRate','omegaRate'};
values={s.rho,omega,rhoRate,omegaRate};
for h=1:4
    v=values{h};
    xi=linspace(-2,2,401);eta=linspace(0,3,401);
    wall=ipm_accellab_tensor_hermite(v,ops.x,ops.y,ops.Dx,ops.Dy, ...
        common.peakX+common.wallWidth*xi,zeros(size(xi)));
    vertical=ipm_accellab_tensor_hermite(v,ops.x,ops.y,ops.Dx,ops.Dy, ...
        common.peakX+zeros(size(eta)),common.verticalWidth*eta);
    o.fields.(names{h})=struct('wall',wall.value(:)', ...
        'vertical',vertical.value(:)');
end
end

function q=sample_shape(rho,ops,config)
w=rho*ops.Dx';
g=continuous_inner_geometry(w,ops.x,ops.y,ops.Dx,ops.Dy, ...
    config.scaling.transportAnchorX*[.8,1.15]);
xi=linspace(-2,2,401);eta=linspace(0,3,401);
a=ipm_accellab_tensor_hermite(w,ops.x,ops.y,ops.Dx,ops.Dy, ...
    g.peakX+g.wallWidth*xi,zeros(size(xi)));
b=ipm_accellab_tensor_hermite(w,ops.x,ops.y,ops.Dx,ops.Dy, ...
    g.peakX+zeros(size(eta)),g.verticalWidth*eta);
q=struct('wall',a.value(:)'/g.peak, ...
    'vertical',b.value(:)'/g.peak);
assert(all(isfinite(q.wall)) && all(isfinite(q.vertical)));
end

function q=compare_fields(a,b)
names=fieldnames(a);
for j=1:numel(names)
    q.(names{j})=compare_pair(a.(names{j}),b.(names{j}));
end
end

function q=compare_pair(a,b)
q=struct('wall',compare_one(a.wall,b.wall), ...
    'vertical',compare_one(a.vertical,b.vertical));
end

function q=compare_one(a,b)
na=norm(a);nb=norm(b);
q=struct('preNorm',na,'postNorm',nb, ...
    'differenceNorm',norm(b-a), ...
    'relativeDifferenceToPre',norm(b-a)/max(na,realmin), ...
    'cosine',dot(a,b)/max(na*nb,realmin));
end
