function report=audit_alternative_candidate_transfer(checkpointFile,outputDirectory)
%AUDIT_ALTERNATIVE_CANDIDATE_TRANSFER Test two frozen real-field transfers.
% The original accepted checkpoint and its controller ledger stay untouched.
assert(~isfolder(outputDirectory));
checkpoint=ipm.output.readCheckpoint(checkpointFile);
saved=checkpoint.payload.state;
assert(saved.remeshCount==34 && ...
    saved.config.remesh.autonomousMesh.version==4 && ...
    all(ipm.output.trustedMask(checkpoint.payload.log.history,saved.config)));
[source,~,~]=ipm.output.restoreCheckpoint(checkpoint,struct());
policy=source.config.remesh.autonomousMesh;
ledger=source.runMetadata.autonomousMesh;
member=ledger.referenceFamily.members(ledger.currentLevelId);
view=struct('rho',source.rho,'x',source.ops.x,'y',source.ops.y, ...
    'Dx',source.ops.Dx,'source',source.rho*source.ops.Dx', ...
    'trusted',true);
[pairs,~,search]=ipm.remesh.hierarchicalAxisPairs(view, ...
    struct('x',member.baseX,'y',member.baseY), ...
    source.config.scaling.transportAnchorX,policy, ...
    policy.nodeFamily.maximumTotalNodes);
assert(strcmp(search.status,'refined_axes_proposed_require_actual_transfer') && ...
    numel(pairs)==3 && isequal([pairs(1).xIndex,pairs(3).xIndex],[82,89]));
% Transfer constructs a new LU. Release the restored source factor first,
% exactly as the native transaction owner does.
source.ops=rmfield(source.ops,'poisson');
clear checkpoint saved view
rows=struct([]);
for k=[1,3]
    p=pairs(k);
    proposal=struct('x',p.x,'y',p.y, ...
        'referenceFamily',ledger.referenceFamily, ...
        'sourceLevelId',ledger.currentLevelId, ...
        'targetLevelId',ledger.currentLevelId);
    trial=source;
    try
        [trial.rho,trial.ops]=ipm.remesh.transfer( ...
            source.rho,source.ops,source.config,proposal);
        audit=ipm.remesh.auditCandidate(source,trial,policy, ...
            ledger.cumulativeAbsolutePeakJump);
        postFlowPassed=false;postSafety=NaN;
        if audit.passed
            [~,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
            postSafety=trial.flow.safetyFactor;
            postFlowPassed=ipm.evolve.isFinite(trial) && ...
                postSafety<policy.maximumSafety && ...
                all([trial.flow.coreGridPoints, ...
                    trial.flow.verticalCoreGridPoints]>= ...
                    policy.transactionMinimumCoreCells);
        end
        row=struct('candidateIndex',k,'xScheduleIndex',p.xIndex, ...
            'yTrialIndex',p.yIndex, ...
            'predictedCoreCells',p.predictedCells(1:2), ...
            'geometryMaxAdjacentRatio',max( ...
                p.quality.x.maximumAdjacentCellRatio, ...
                p.quality.y.maximumAdjacentCellRatio), ...
            'nativeAuditPassed',audit.passed, ...
            'nativeAuditReasons',{audit.reasons}, ...
            'actualCoreCells',audit.coreCells, ...
            'actualFrontCells',audit.leftFrontCells, ...
            'relativePeakJump',audit.relativePeakJump, ...
            'massRelativeDefect',audit.massRelativeDefect, ...
            'relativeRangeViolation',audit.relativeRangeViolation, ...
            'postTransferFlowPassed',postFlowPassed, ...
            'postTransferSafety',postSafety);
    catch exception
        row=struct('candidateIndex',k,'xScheduleIndex',p.xIndex, ...
            'yTrialIndex',p.yIndex, ...
            'predictedCoreCells',p.predictedCells(1:2), ...
            'geometryMaxAdjacentRatio',max( ...
                p.quality.x.maximumAdjacentCellRatio, ...
                p.quality.y.maximumAdjacentCellRatio), ...
            'nativeAuditPassed',false,'nativeAuditReasons',{{exception.identifier}}, ...
            'actualCoreCells',[NaN,NaN],'actualFrontCells',NaN, ...
            'relativePeakJump',NaN,'massRelativeDefect',NaN, ...
            'relativeRangeViolation',NaN,'postTransferFlowPassed',false, ...
            'postTransferSafety',NaN);
    end
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
    clear trial audit proposal
end
report=struct('kind','frozen_alternative_native_transfer_audit_v1', ...
    'sourceCheckpoint',checkpointFile, ...
    'sourceStep',source.step,'sourceTau',source.scale.canonicalTime, ...
    'sourceRemeshCount',source.ops.remeshCount, ...
    'sourceCheckpointValidated',true, ...
    'originalSourceModified',false,'pdeAdvanced',false, ...
    'futureCandidateLifetimeCertified',false, ...
    'rows',{rows});
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
for row=rows
    fprintf('TRANSFER x=%d audit=%d flow=%d actualCore=%.3f/%.3f peakJump=%.3e\n', ...
        row.xScheduleIndex,row.nativeAuditPassed,row.postTransferFlowPassed, ...
        row.actualCoreCells,row.relativePeakJump);
end
end
