function report=audit_posttransfer_core_tangent(beforeCheckpoint, ...
        afterCheckpoint,transactionIndex,candidateIndices,outputDirectory)
%AUDIT_POSTTRANSFER_CORE_TANGENT Test a cheap request-time decay predictor.
% Each candidate receives its true native transfer and one original RHS.
% The accepted-state RHS then differentiates the unchanged core diagnostic
% on that frozen grid. Future requests are not read for candidate scoring.
assert(~isfolder(outputDirectory) && maxNumCompThreads==10);
before=ipm.output.readCheckpoint(beforeCheckpoint);
after=ipm.output.readCheckpoint(afterCheckpoint);
b=before.payload.state;a=after.payload.state;
assert(all(ipm.output.trustedMask(before.payload.log.history,b.config)) && ...
    all(ipm.output.trustedMask(after.payload.log.history,a.config)) && ...
    strcmp(b.runMetadata.caseId,a.runMetadata.caseId));
ledger=a.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>=transactionIndex && ...
    b.step<ledger(transactionIndex).sourceStep);
signed=ledger(transactionIndex);
[source,~,~]=ipm.output.restoreCheckpoint(before,struct());
clear before after a b
plan=[];
while source.step<signed.sourceStep
    [source,reason,plan]=ipm.evolve.advance(source);
    assert(isempty(reason),'ipm:CoreTangentReplayStopped');
    if ~isempty(plan),break;end
end
assert(~isempty(plan) && plan.requested && ...
    source.step==signed.sourceStep && ...
    source.scale.canonicalTime==signed.sourceCanonicalTime && ...
    isequaln(plan.coreCells,signed.controllerDecision.coreCells) && ...
    strcmp(plan.reason,signed.controllerDecision.reason), ...
    'ipm:CoreTangentSourceMismatch');
assert(isnumeric(candidateIndices) && isrow(candidateIndices) && ...
    all(candidateIndices==fix(candidateIndices)) && ...
    all(candidateIndices>=1) && ...
    all(candidateIndices<=numel(plan.candidates)) && ...
    numel(unique(candidateIndices))==numel(candidateIndices));
policy=source.config.remesh.autonomousMesh;
source.ops=rmfield(source.ops,'poisson');
rows=struct([]);
for k=candidateIndices
    p=plan.candidates(k);
    proposal=struct('x',p.x,'y',p.y, ...
        'referenceFamily',source.runMetadata.autonomousMesh.referenceFamily, ...
        'sourceLevelId',plan.sourceLevelId, ...
        'targetLevelId',p.targetLevelId);
    trial=source;
    [trial.rho,trial.ops]=ipm.remesh.transfer( ...
        source.rho,source.ops,source.config,proposal);
    audit=ipm.remesh.auditCandidate(source,trial,policy, ...
        source.runMetadata.autonomousMesh.cumulativeAbsolutePeakJump);
    assert(audit.passed);
    [rhoRate,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
    assert(ipm.evolve.isFinite(trial) && ...
        trial.flow.safetyFactor<policy.maximumSafety);
    [core0,selector0]=measure_core(trial.rho,trial.ops);
    assert(max(abs(core0-audit.coreCells))<1e-10 && ...
        max(abs(core0-[trial.flow.coreGridPoints, ...
            trial.flow.verticalCoreGridPoints]))<1e-10);
    epsilons=[1e-5,5e-6];rates=zeros(2,2);selectors=zeros(2,2);
    for j=1:2
        [c,s]=measure_core(trial.rho+epsilons(j)*rhoRate,trial.ops);
        rates(j,:)=(c-core0)/epsilons(j);
        selectors(j,:)=s;
    end
    logDecay=-rates(2,:)./core0;
    row=struct('candidateIndex',k,'targetLevelId',p.targetLevelId, ...
        'nodeCount',[trial.ops.nx,trial.ops.ny], ...
        'maximumAdjacentRatio',max(p.quality.x.maximumAdjacentCellRatio, ...
            p.quality.y.maximumAdjacentCellRatio), ...
        'nativeAuditPassed',audit.passed, ...
        'postTransferCoreCells',core0, ...
        'coreSelector',selector0, ...
        'epsilons',epsilons, ...
        'forwardCoreRates',rates, ...
        'forwardCoreSelectors',selectors, ...
        'localLogCoreDecay',logDecay, ...
        'halfStepDerivativeRelativeDifference', ...
            norm(rates(1,:)-rates(2,:))/max(norm(rates(2,:)),realmin), ...
        'selectorStable',all(all(selectors==selector0)), ...
        'oneOriginalRhsEvaluation',true);
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
    fprintf('CORE_TANGENT k=%d decayX/Y=%.6f/%.6f refinement=%.4g selectorStable=%d\n', ...
        k,logDecay,row.halfStepDerivativeRelativeDifference, ...
        row.selectorStable);
    clear trial rhoRate audit proposal
end
assert(candidateIndices(1)==signed.candidateIndex && ...
    rows(1).nativeAuditPassed && ...
    isequaln(rows(1).postTransferCoreCells,signed.coreCells), ...
    'ipm:CoreTangentBaselineMismatch');
report=struct('kind','frozen_posttransfer_original_rhs_core_tangent_v1', ...
    'beforeCheckpoint',beforeCheckpoint,'afterCheckpoint',afterCheckpoint, ...
    'transactionIndex',transactionIndex,'sourceTau',signed.sourceCanonicalTime, ...
    'sourceStep',signed.sourceStep,'sourceDecisionEqualsSigned',true, ...
    'candidateIndices',candidateIndices,'rows',{rows}, ...
    'futureRequestUsedForScoring',false, ...
    'alternativeTransactionCommitted',false, ...
    'continuumAccuracyCertified',false, ...
    'interpretation','One-sided original-RHS derivative of the unchanged discrete core diagnostic on each post-transfer grid. Peak-column or level-selector changes can make this local derivative unreliable; observed future decay must be tested separately.');
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end

function [core,selector]=measure_core(rho,ops)
omega=rho*ops.Dx';
x=ipm.diagnostics.peakResolution(max(omega(1,:),0),ops.x, ...
    ops.rescaling.adaptiveLevels);
y=ipm.diagnostics.peakResolution(abs(omega(:,x.peakIndex))', ...
    ops.y',ops.rescaling.adaptiveLevels);
core=[x.gridPoints(end),y.gridPoints(end)];
selector=[x.peakIndex,y.peakIndex];
end
