function report=audit_mesh_density_distribution(checkpointFile,outputFile)
%AUDIT_MESH_DENSITY_DISTRIBUTION Signed-state spacing burden, no PDE/LU.
assert(ischar(checkpointFile)&&isrow(checkpointFile)&&isfile(checkpointFile));
assert(ischar(outputFile)&&isrow(outputFile)&&~isfile(outputFile));
checkpoint=ipm.output.readCheckpoint(checkpointFile);
assert(checkpoint.trustedRecord);
saved=checkpoint.payload.state;
x=saved.x(:)';y=saved.y(:);
Dx=ipm.mesh.fdMatrix(x,1,7);
view=struct('rho',saved.rho,'x',x,'y',y,'Dx',Dx, ...
    'source',saved.rho*Dx','trusted',true);
feature=ipm.diagnostics.meshFeatureIntervals(view);
positiveX=x(x>=0);
report=struct('kind','signed_mesh_logwidth_distribution_v1', ...
    'checkpointFile',checkpointFile,'tau',saved.scale.canonicalTime, ...
    'step',saved.step,'nodeCount',[numel(x),numel(y)], ...
    'remeshCount',saved.remeshCount,'feature',feature, ...
    'x',one_axis(positiveX),'y',one_axis(y), ...
    'readOnly',true,'pdeAdvanced',false);
fid=fopen(outputFile,'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end

function item=one_axis(nodes)
widths=diff(nodes);
logSlope=diff(log(widths));
burden=abs(logSlope);
ratio=exp(burden);
sorted=sort(burden,'descend');
sortedRatio=sort(ratio);
topCount=max(1,ceil(.05*numel(sorted)));
item=struct('nodes',nodes,'cellWidths',widths, ...
    'interfacePositions',nodes(2:end-1), ...
    'interfaceLogWidthChange',logSlope, ...
    'interfaceAdjacentRatio',ratio, ...
    'maximumAdjacentRatio',max(ratio), ...
    'medianAdjacentRatio',median(ratio), ...
    'p95AdjacentRatio',interp1(linspace(0,1,numel(ratio)), ...
        sortedRatio,.95,'linear'), ...
    'meanAbsoluteLogWidthChange',mean(burden), ...
    'rmsLogWidthChange',sqrt(mean(logSlope.^2)), ...
    'totalAbsoluteLogWidthChange',sum(burden), ...
    'topFivePercentBurdenFraction', ...
        sum(sorted(1:topCount))/max(sum(sorted),realmin), ...
    'logSlopeParticipationFraction', ...
        sum(burden)^2/max(numel(burden)*sum(burden.^2),realmin), ...
    'maxRatioPosition',nodes(find(ratio==max(ratio),1)+1));
end
