function report=audit_amortized_mesh_ratio(runDirectory,outputDirectory)
%AUDIT_AMORTIZED_MESH_RATIO Retrospective, no-LU candidate lifetime bounds.
% Fit only pre-frozen same-epoch data; hold the later native trigger out.
assert(~isfolder(outputDirectory));
steps=[10273,10527,10773,11011];
t=zeros(1,numel(steps));xCells=t;yCells=t;epoch=t;
sourceState=[];sourceDx=[];
for k=1:numel(steps)
    files=dir(fullfile(runDirectory,sprintf('*step%010d.mat',steps(k))));
    assert(numel(files)==1);
    cp=ipm.output.readCheckpoint(fullfile(files.folder,files.name));
    s=cp.payload.state;h=cp.payload.log.history;
    assert(all(ipm.output.trustedMask(h,s.config)));
    Dx=ipm.mesh.fdMatrix(s.x,1,7);
    flow=struct('source',s.rho*Dx', ...
        'omegaGaugeQuadraticPeakX',h.gauge.omegaGaugeQuadraticPeakX(end));
    q=ipm.remesh.continuousVerticalCore(flow,s.x,s.y, ...
        s.config.scaling.adaptiveLevels);
    t(k)=s.scale.canonicalTime;epoch(k)=s.remeshCount;
    xCells(k)=h.mesh.coreGridPoints(end);yCells(k)=q.coreCells;
    if k==numel(steps),sourceState=s;sourceDx=Dx;end
end
assert(all(diff(t)>0)&&all(epoch==epoch(1))&&epoch(1)==34);
rates=[max(-diff(log(xCells))./diff(t)), ...
    max(-diff(log(yCells))./diff(t))];
assert(all(rates>0));
policy=sourceState.config.remesh.autonomousMesh;
ledger=sourceState.runMetadata.autonomousMesh;
member=ledger.referenceFamily.members(ledger.currentLevelId);
view=struct('rho',sourceState.rho,'x',sourceState.x, ...
    'y',sourceState.y,'Dx',sourceDx, ...
    'source',sourceState.rho*sourceDx','trusted',true);
[pairs,~,search]=ipm.remesh.hierarchicalAxisPairs(view, ...
    struct('x',member.baseX,'y',member.baseY), ...
    sourceState.config.scaling.transportAnchorX,policy, ...
    policy.nodeFamily.maximumTotalNodes);
assert(strcmp(search.status,'refined_axes_proposed_require_actual_transfer') ...
    && numel(pairs)==3);
trigger=policy.regridCoreTrigger;
rows=struct([]);
for k=1:numel(pairs)
    p=pairs(k);
    lifetime=log(p.predictedCells(1:2)./trigger)./rates;
    row=struct('xScheduleIndex',p.xIndex,'yTrialIndex',p.yIndex, ...
        'predictedCoreCells',p.predictedCells(1:2), ...
        'predictedFrontCells',p.predictedCells(3), ...
        'maxAdjacentRatio',max(p.quality.x.maximumAdjacentCellRatio, ...
            p.quality.y.maximumAdjacentCellRatio), ...
        'estimatedLifetimeByAxis',lifetime, ...
        'estimatedBottleneckLifetime',min(lifetime));
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
end
later=dir(fullfile(runDirectory,'*step0000011730.mat'));
assert(numel(later)==1);
cp=ipm.output.readCheckpoint(fullfile(later.folder,later.name));
transaction=cp.payload.state.runMetadata.autonomousMesh.transactions(end);
assert(transaction.sourceRemeshCount==34 && ...
    transaction.sourceCanonicalTime>t(end));
forecastTrigger=t(end)+log(xCells(end)/trigger(1))/rates(1);
report=struct('kind','pre_frozen_amortized_mesh_ratio_audit_v1', ...
    'signedCheckpoints',true,'noPoissonFactor',true,'noTransfer',true, ...
    'sameMeshEpoch',epoch(1),'preFrozenTimes',t, ...
    'preFrozenXCoreCells',xCells, ...
    'preFrozenContinuousYCoreCells',yCells, ...
    'maximumPreFrozenLogSecantDecayByAxis',rates, ...
    'triggerCoreCells',trigger, ...
    'forecastNativeTriggerTau',forecastTrigger, ...
    'heldOutActualTriggerTau',transaction.sourceCanonicalTime, ...
    'forecastTriggerError',forecastTrigger-transaction.sourceCanonicalTime, ...
    'candidateRows',{rows}, ...
    'futureCandidateLifetimeOrTransferCertified',false);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('AMORTIZED_GRID triggerPred=%.6f triggerActual=%.6f error=%.3e\n', ...
    forecastTrigger,transaction.sourceCanonicalTime,report.forecastTriggerError);
for row=rows
    fprintf('  x=%d ratio=%.6f lifetime=%.4f\n', ...
        row.xScheduleIndex,row.maxAdjacentRatio,row.estimatedBottleneckLifetime);
end
end
