function report=audit_candidate_lifetime_at_request(sourceCheckpoint, ...
        laterCheckpoint,transactionIndex,outputDirectory)
%AUDIT_CANDIDATE_LIFETIME_AT_REQUEST Score an independent native request.
% The ranking uses only the request-time accepted state and its prior
% same-epoch fit. The later signed checkpoint supplies an audit target,
% never a ranking input. No alternative transaction is committed.
assert(~isfolder(outputDirectory));
earlier=ipm.output.readCheckpoint(sourceCheckpoint);
later=ipm.output.readCheckpoint(laterCheckpoint);
ledger=later.payload.state.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>=transactionIndex && ...
    earlier.payload.state.step<ledger(transactionIndex).sourceStep);
[state,~,~]=ipm.output.restoreCheckpoint(earlier,struct());
clear earlier later
plan=[];
while state.step<ledger(transactionIndex).sourceStep
    [state,stopReason,plan]=ipm.evolve.advance(state);
    assert(isempty(stopReason),'ipm:HoldoutMeshReplayStopped');
    if ~isempty(plan),break;end
end
original=ledger(transactionIndex);
assert(~isempty(plan) && plan.requested && ...
    state.step==original.sourceStep && ...
    state.scale.canonicalTime==original.sourceCanonicalTime && ...
    isequaln(plan.coreCells,original.controllerDecision.coreCells) && ...
    strcmp(plan.reason,original.controllerDecision.reason), ...
    'ipm:HoldoutMeshSourceMismatch');
policy=state.config.remesh.autonomousMesh;
rates=max([plan.decayEvidence.fitDecay],1e-12);
trigger=policy.regridCoreTrigger;
rows=struct([]);
for k=1:numel(plan.candidates)
    p=plan.candidates(k);
    core=p.predictedCells(1:2);
    ratio=max(p.quality.x.maximumAdjacentCellRatio, ...
        p.quality.y.maximumAdjacentCellRatio);
    horizonByAxis=log(core./trigger)./rates;
    sameLevel=p.targetLevelId==plan.sourceLevelId;
    eligible=sameLevel && all(core>trigger) && ...
        ratio<=policy.qualityLimits.maxAdjacentCellRatio;
    row=struct('candidateIndex',k,'xScheduleIndex',p.xIndex, ...
        'yTrialIndex',p.yIndex,'targetLevelId',p.targetLevelId, ...
        'predictedCoreCells',core,'maxAdjacentRatio',ratio, ...
        'fitDecayByAxis',rates,'estimatedLifetimeByAxis',horizonByAxis, ...
        'estimatedBottleneckLifetime',min(horizonByAxis), ...
        'eligibleForSameCostRank',eligible);
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
end
scores=[rows.estimatedBottleneckLifetime];
scores(~[rows.eligibleForSameCostRank])=-Inf;
[best,bestIndex]=max(scores);
assert(isfinite(best),'ipm:HoldoutMeshNoRankedCandidate');
selectedIndices=unique([1,bestIndex],'stable');
source=state;source.ops=rmfield(source.ops,'poisson');
clear state
audits=struct([]);
for k=selectedIndices
    p=plan.candidates(k);
    proposal=struct('x',p.x,'y',p.y, ...
        'referenceFamily',source.runMetadata.autonomousMesh.referenceFamily, ...
        'sourceLevelId',plan.sourceLevelId, ...
        'targetLevelId',p.targetLevelId);
    trial=source;
    [trial.rho,trial.ops]=ipm.remesh.transfer( ...
        source.rho,source.ops,source.config,proposal);
    a=ipm.remesh.auditCandidate(source,trial,policy, ...
        source.runMetadata.autonomousMesh.cumulativeAbsolutePeakJump);
    [~,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
    postPassed=a.passed && ipm.evolve.isFinite(trial) && ...
        trial.flow.safetyFactor<policy.maximumSafety && ...
        all([trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints] ...
            >=policy.transactionMinimumCoreCells);
    audit=struct('candidateIndex',k,'passed',a.passed, ...
        'reasons',{a.reasons},'postTransferFlowPassed',postPassed, ...
        'actualCoreCells',a.coreCells, ...
        'relativePeakJump',a.relativePeakJump, ...
        'massRelativeDefect',a.massRelativeDefect, ...
        'relativeRangeViolation',a.relativeRangeViolation, ...
        'postTransferSafety',trial.flow.safetyFactor);
    if isempty(audits),audits=audit;else,audits(end+1)=audit;end %#ok<AGROW>
    clear trial a proposal
end
assert(audits(1).passed && audits(1).postTransferFlowPassed && ...
    isequaln(audits(1).actualCoreCells,original.coreCells) && ...
    audits(1).relativePeakJump==original.relativePeakJump && ...
    audits(1).massRelativeDefect==original.massRelativeDefect && ...
    audits(1).relativeRangeViolation==original.relativeRangeViolation, ...
    'ipm:HoldoutMeshBaselineMismatch');
baselineNextTau=NaN;
if numel(ledger)>transactionIndex
    baselineNextTau=ledger(transactionIndex+1).sourceCanonicalTime;
end
report=struct('kind','independent_late_mesh_lifetime_rank_audit_v1', ...
    'sourceCheckpoint',sourceCheckpoint,'signedLaterCheckpoint',laterCheckpoint, ...
    'transactionIndex',transactionIndex, ...
    'sourceStep',original.sourceStep,'sourceTau',original.sourceCanonicalTime, ...
    'baselineSelectedCandidateIndex',original.candidateIndex, ...
    'fitDecayByAxis',rates,'triggerCoreCells',trigger, ...
    'selectionRule','max fitted bottleneck lifetime within same node level and original quality gates', ...
    'rankedSelectedCandidateIndex',bestIndex, ...
    'rankingUsesLaterOutcome',false, ...
    'baselineSignedNextRequestTau',baselineNextTau, ...
    'rows',{rows},'nativeTransferAudits',{audits}, ...
    'alternativeTransactionCommitted',false, ...
    'alternativeFutureLifetimeCertified',false);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
for k=1:numel(rows)
    fprintf('HOLDOUT_RANK k=%d x=%d y=%d ratio=%.6f core=%.3f/%.3f life=%.5f eligible=%d\n', ...
        k,rows(k).xScheduleIndex,rows(k).yTrialIndex, ...
        rows(k).maxAdjacentRatio,rows(k).predictedCoreCells, ...
        rows(k).estimatedBottleneckLifetime,rows(k).eligibleForSameCostRank);
end
fprintf('HOLDOUT_SELECTED candidate=%d baseline=%d\n', ...
    bestIndex,original.candidateIndex);
end
