function report=audit_frozen_pair_ratio(runDirectory,outputDirectory)
%AUDIT_FROZEN_PAIR_RATIO Quantify smoothness achievable by the registered
% no-LU mesh proposal family at frozen native states. No transfer is tested.
steps=[7912,8693,9328,11011];
assert(~isfolder(outputDirectory));
rows=struct([]);
for k=1:numel(steps)
    files=dir(fullfile(runDirectory,sprintf('*step%010d.mat',steps(k))));
    assert(numel(files)==1);
    cp=ipm.output.readCheckpoint(fullfile(files.folder,files.name));
    s=cp.payload.state;h=cp.payload.log.history;
    assert(all(ipm.output.trustedMask(h,s.config)));
    policy=s.config.remesh.autonomousMesh;
    ledger=s.runMetadata.autonomousMesh;
    member=ledger.referenceFamily.members(ledger.currentLevelId);
    x=s.x;y=s.y;
    Dx=ipm.mesh.fdMatrix(x,1,7);source=s.rho*Dx';
    view=struct('rho',s.rho,'x',x,'y',y,'Dx',Dx, ...
        'source',source,'trusted',true);
    [pairs,detail]=ipm.remesh.plannedAxisPairs(view, ...
        struct('x',member.baseX,'y',member.baseY), ...
        s.config.scaling.transportAnchorX,policy);
    xr=detail.xTrials;yr=detail.yTrials;
    xa=find([xr.admissible]);ya=find([yr.admissible]);
    feasible=~isempty(xa)&&~isempty(ya);
    bestRatio=NaN;firstRatio=NaN;bestXCells=NaN;bestYCells=NaN;
    fallbackStatus='not_needed';fallbackPairs=0;fallbackRatio=NaN;
    fallbackCandidates=struct([]);
    if feasible
        [xRatio,xIndex]=min(arrayfun(@(r)r.quality.maximumAdjacentCellRatio,xr(xa)));
        [yRatio,yIndex]=min(arrayfun(@(r)r.quality.maximumAdjacentCellRatio,yr(ya)));
        bestRatio=max(xRatio,yRatio);
        bestXCells=xr(xa(xIndex)).coreCells;
        bestYCells=yr(ya(yIndex)).coreCells;
    end
    if ~isempty(pairs)
        firstRatio=max(pairs(1).quality.x.maximumAdjacentCellRatio, ...
            pairs(1).quality.y.maximumAdjacentCellRatio);
    end
    if ~feasible
        [extra,~,search]=ipm.remesh.hierarchicalAxisPairs(view, ...
            struct('x',member.baseX,'y',member.baseY), ...
            s.config.scaling.transportAnchorX,policy, ...
            policy.nodeFamily.maximumTotalNodes);
        fallbackStatus=search.status;fallbackPairs=numel(extra);
        if ~isempty(extra)
            fallbackRatio=max(extra(1).quality.x.maximumAdjacentCellRatio, ...
                extra(1).quality.y.maximumAdjacentCellRatio);
            for j=1:numel(extra)
                candidate=struct('xIndex',extra(j).xIndex, ...
                    'yIndex',extra(j).yIndex, ...
                    'minimaxRatio',max(extra(j).quality.x.maximumAdjacentCellRatio, ...
                        extra(j).quality.y.maximumAdjacentCellRatio), ...
                    'predictedCells',extra(j).predictedCells);
                if isempty(fallbackCandidates),fallbackCandidates=candidate;
                else,fallbackCandidates(end+1)=candidate;end %#ok<AGROW>
            end
        end
    end
    row=struct('step',s.step,'tau',s.scale.canonicalTime, ...
        'remeshCount',s.remeshCount,'nodeCount',[numel(x),numel(y)], ...
        'currentRatio',[h.mesh.maximumCellRatioX(end), ...
            h.mesh.maximumCellRatioY(end)], ...
        'currentCoreCells',[h.mesh.coreGridPoints(end), ...
            h.mesh.verticalCoreGridPoints(end)], ...
        'admissibleX',numel(xa),'admissibleY',numel(ya), ...
        'minimumNewPairMinimaxRatio',bestRatio, ...
        'minimumRatioPairPredictedCoreCells',[bestXCells,bestYCells], ...
        'nativeFirstPairRatio',firstRatio,'nativePairCount',numel(pairs), ...
        'proposalStatus',detail.status,'fallbackStatus',fallbackStatus, ...
        'fallbackPairCount',fallbackPairs,'fallbackFirstPairRatio',fallbackRatio, ...
        'fallbackCandidates',{fallbackCandidates});
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
end
report=struct('kind','frozen_registered_pair_ratio_audit_v1', ...
    'signedCheckpoints',true,'noPoissonFactor',true,'noTransfer',true, ...
    'actualTransferOrFutureGridLifetimeCertified',false, ...
    'rows',{rows});
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
for r=rows
    fprintf('RATIO tau=%.3f x/y=%d/%d eligible=%d/%d best=%.6f first=%.6f\n', ...
        r.tau,r.nodeCount,r.admissibleX,r.admissibleY, ...
        r.minimumNewPairMinimaxRatio,r.nativeFirstPairRatio);
end
end
