function report=audit_frozen_mesh_ratio(checkpointFiles,outputFile)
%AUDIT_FROZEN_MESH_RATIO Compare registered axis choices on accepted states.
% Geometry only: no field transfer, elliptic factorization, or PDE step.
if ischar(checkpointFiles) || isstring(checkpointFiles)
    checkpointFiles=cellstr(checkpointFiles);
end
assert(iscell(checkpointFiles)&&~isempty(checkpointFiles));
rows=struct([]);
for k=1:numel(checkpointFiles)
    cp=ipm.output.readCheckpoint(checkpointFiles{k});s=cp.payload.state;
    policy=s.config.remesh.autonomousMesh;
    level=s.runMetadata.autonomousMesh.currentLevelId;
    reference=s.runMetadata.autonomousMesh.referenceFamily.members(level);
    Dx=ipm.mesh.fdMatrix(s.x,1,7);
    view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx, ...
        'source',s.rho*Dx','trusted',true);
    [candidates,trial]=ipm.remesh.plannedAxisPairs(view, ...
        struct('x',reference.baseX,'y',reference.baseY), ...
        s.config.scaling.transportAnchorX,policy);
    xq=ipm.mesh.quality(s.x,7,ipm.mesh.quadrature(s.x));
    yq=ipm.mesh.quality(s.y,7,ipm.mesh.quadrature(s.y));
    xGood=find([trial.xTrials.admissible]);
    yGood=find([trial.yTrials.admissible]);
    xRatios=NaN(size(xGood));yRatios=NaN(size(yGood));
    for j=1:numel(xGood)
        xRatios(j)=trial.xTrials(xGood(j)).quality.maximumAdjacentCellRatio;
    end
    for j=1:numel(yGood)
        yRatios(j)=trial.yTrials(yGood(j)).quality.maximumAdjacentCellRatio;
    end
    best=struct('xIndex',NaN,'yIndex',NaN,'maximumRatio',NaN, ...
        'coreCells',[NaN,NaN],'frontCells',NaN);
    if ~isempty(xGood)&&~isempty(yGood)
        [xr,ix]=min(xRatios);[yr,iy]=min(yRatios);
        xrow=trial.xTrials(xGood(ix));yrow=trial.yTrials(yGood(iy));
        best=struct('xIndex',xGood(ix),'yIndex',yGood(iy), ...
            'maximumRatio',max(xr,yr),'coreCells',[xrow.coreCells,yrow.coreCells], ...
            'frontCells',xrow.frontCells);
    end
    selected=struct('xIndex',NaN,'yIndex',NaN,'maximumRatio',NaN, ...
        'coreCells',[NaN,NaN],'frontCells',NaN);
    changed=find(~[candidates.unchanged],1);
    if ~isempty(changed)
        c=candidates(changed);
        selected=struct('xIndex',c.xIndex,'yIndex',c.yIndex, ...
            'maximumRatio',max(c.quality.x.maximumAdjacentCellRatio, ...
            c.quality.y.maximumAdjacentCellRatio), ...
            'coreCells',c.predictedCells(1:2),'frontCells',c.predictedCells(3));
    end
    row=struct('checkpoint',checkpointFiles{k},'step',s.step, ...
        'canonicalTime',s.scale.canonicalTime,'physicalTime',s.scale.physicalTime, ...
        'nodeCount',[numel(s.x),numel(s.y)],'level',level, ...
        'actualCoreCells',trial.feature.actualCoreCells, ...
        'coreInterval',trial.feature.coreInterval, ...
        'frontInterval',trial.feature.frontInterval, ...
        'yCoreWidth',trial.feature.yCoreWidth, ...
        'currentRatio',[xq.maximumAdjacentCellRatio,yq.maximumAdjacentCellRatio], ...
        'admissibleAxisCount',[numel(xGood),numel(yGood)], ...
        'bestAdmittedMinimaxRatio',best,'productionFirstRank',selected, ...
        'xAdmissibleRatioRange',[min_or_nan(xRatios),max_or_nan(xRatios)], ...
        'yAdmissibleRatioRange',[min_or_nan(yRatios),max_or_nan(yRatios)], ...
        'noLU',true,'noTransfer',true);
    if isempty(rows),rows=row;else,rows(end+1)=row;end
    fprintf('FROZEN_RATIO tau=%.6f n=%dx%d Xpass=%d Ypass=%d current=%.6f best=%.6f first=%.6f\n', ...
        row.canonicalTime,row.nodeCount(1),row.nodeCount(2), ...
        numel(xGood),numel(yGood),max(row.currentRatio), ...
        best.maximumRatio,selected.maximumRatio);
end
report=struct('kind','frozen_ratio_minimax_audit_v1','rows',rows, ...
    'scope','registered primary family only; full axis quality, no transfer or PDE', ...
    'completed',true);
if nargin>=2 && ~isempty(outputFile)
    assert(~isfile(outputFile));
    fid=fopen(outputFile,'w');assert(fid>=0);
    cleanup=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
end

function value=min_or_nan(a)
if isempty(a),value=NaN;else,value=min(a);end
end
function value=max_or_nan(a)
if isempty(a),value=NaN;else,value=max(a);end
end
