function report=audit_continuous_vertical_width(checkpointFiles,outputDirectory)
%AUDIT_CONTINUOUS_VERTICAL_WIDTH Compare mesh width telemetry with a
% continuous-X peak trace. The original safety and remesh gates are untouched.
assert(iscell(checkpointFiles)&&numel(checkpointFiles)>=3&& ...
    ~isfolder(outputDirectory));
n=numel(checkpointFiles);
times=zeros(1,n);node=zeros(1,n);recorded=zeros(1,n);
pchip=zeros(1,n);spline=zeros(1,n);offset=zeros(1,n);
nodeCells=zeros(1,n);recordedCells=zeros(1,n);
pchipCells=zeros(1,n);splineCells=zeros(1,n);
firstX=[];firstY=[];caseIds=cell(1,n);
for k=1:n
    cp=ipm.output.readCheckpoint(checkpointFiles{k});
    s=cp.payload.state;h=cp.payload.log.history;
    assert(all(ipm.output.trustedMask(h,s.config)));
    x=s.x(:)';y=s.y(:);
    if k==1,firstX=x;firstY=y;
    else,assert(isequal(x,firstX)&&isequal(y,firstY), ...
        'ipm:ContinuousWidthAxesChanged');end
    times(k)=s.scale.canonicalTime;
    caseIds{k}=char(s.runMetadata.caseId);
    levels=s.config.scaling.adaptiveLevels;
    peakX=h.gauge.omegaGaugeQuadraticPeakX(end);
    wallWidth=h.mesh.trackedWallCoreWidth(end);
    recorded(k)=h.mesh.trackedVerticalCoreWidth(end);
    recordedCells(k)=h.mesh.verticalCoreGridPoints(end);
    assert(isfinite(peakX)&& ...
        wallWidth>0&&recorded(k)>0);
    source=s.rho*ipm.mesh.fdMatrix(x,1,7)';
    [~,ix]=max(source(1,:));
    nodalPeakX=x(ix);
    offset(k)=(nodalPeakX-peakX)/wallWidth;
    zNode=ipm.diagnostics.peakResolution(abs(source(:,ix))',y',levels);
    zPchip=interp1(x,source',peakX,'pchip');
    zSpline=interp1(x,source',peakX,'spline');
    qPchip=ipm.diagnostics.peakResolution(abs(zPchip),y',levels);
    qSpline=ipm.diagnostics.peakResolution(abs(zSpline),y',levels);
    node(k)=zNode.widths(end);
    pchip(k)=qPchip.widths(end);
    spline(k)=qSpline.widths(end);
    nodeCells(k)=zNode.gridPoints(end);
    pchipCells(k)=qPchip.gridPoints(end);
    splineCells(k)=qSpline.gridPoints(end);
    assert(abs(node(k)-recorded(k))<=1e-12*recorded(k), ...
        'ipm:ContinuousWidthLegacyMismatch');
    assert(abs(nodeCells(k)-recordedCells(k))<=1e-10, ...
        'ipm:ContinuousCellsLegacyMismatch');
end
assert(all(diff(times)>0)&&isscalar(unique(caseIds))&& ...
    all(isfinite([node,pchip,spline]))&& ...
    all([node,pchip,spline]>0));
report=struct('kind','continuous_peak_vertical_width_audit_v1', ...
    'checkpoints',{checkpointFiles},'times',times, ...
    'nodeWidth',node,'recordedNodeWidth',recorded, ...
    'nodeCoreCells',nodeCells,'recordedNodeCoreCells',recordedCells, ...
    'continuousPchipWidth',pchip, ...
    'continuousSplineWidth',spline, ...
    'continuousPchipCoreCells',pchipCells, ...
    'continuousSplineCoreCells',splineCells, ...
    'nodeVsContinuousRelativeDifference',(node-pchip)./pchip, ...
    'pchipSplineRelativeDifference',(pchip-spline)./pchip, ...
    'nodalPeakOffsetsInWallWidth',offset, ...
    'sameAxes',true,'fullHistoriesTrusted',true, ...
    'originalMeshGatesModified',false);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('CONTINUOUS_WIDTH tau=%.3f-%.3f maxNodeGap=%.3e maxInterpGap=%.3e\n', ...
    times(1),times(end), ...
    max(abs(report.nodeVsContinuousRelativeDifference)), ...
    max(abs(report.pchipSplineRelativeDifference)));
end
