function report=audit_fixed_density_transfer(distributionFile,xSweepFile,ySweepFile,outputFile)
%AUDIT_FIXED_DENSITY_TRANSFER Frozen same-N native transfer; no time advance.
assert(isfile(distributionFile)&&isfile(xSweepFile)&&isfile(ySweepFile)&&~isfile(outputFile));
d=jsondecode(fileread(distributionFile));
xDesign=jsondecode(fileread(xSweepFile));
yDesign=jsondecode(fileread(ySweepFile));
checkpoint=ipm.output.readCheckpoint(d.checkpointFile);
assert(checkpoint.trustedRecord);
[source,~,~]=ipm.output.restoreCheckpoint(checkpoint,struct());
maxNumCompThreads(4);
if isfield(source.ops,'poisson')
    source.ops=rmfield(source.ops,'poisson');
end
policy=source.config.remesh.autonomousMesh;
memory=source.runMetadata.autonomousMesh;
assert(numel(source.ops.x)==d.nodeCount(1)&&numel(source.ops.y)==d.nodeCount(2));
choices={{source.ops.x(:)',yDesign.best.axis(:)}, ...
    {xDesign.best.axis(:)',yDesign.best.axis(:)}};
names={'y_only','joint_x_y'};
rows=struct([]);
for k=1:2
    axes=choices{k};
    proposal=struct('x',axes{1},'y',axes{2}, ...
        'referenceFamily',memory.referenceFamily, ...
        'sourceLevelId',memory.currentLevelId, ...
        'targetLevelId',memory.currentLevelId);
    trial=source;
    timer=tic;
    [trial.rho,trial.ops]=ipm.remesh.transfer( ...
        source.rho,source.ops,source.config,proposal);
    transferSeconds=toc(timer);
    audit=ipm.remesh.auditCandidate(source,trial,policy, ...
        memory.cumulativeAbsolutePeakJump);
    flowPass=false;flowSeconds=NaN;safety=NaN;
    if audit.passed
        timer=tic;
        [~,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
        flowSeconds=toc(timer);
        safety=trial.flow.safetyFactor;
        flowPass=ipm.evolve.isFinite(trial) && ...
            safety<policy.maximumSafety && ...
            all([trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints] ...
                >=policy.transactionMinimumCoreCells);
    end
    qx=audit.xQuality;qy=audit.yQuality;
    row=struct('name',names{k},'auditPassed',audit.passed, ...
        'auditReasons',{audit.reasons},'postFlowPassed',flowPass, ...
        'xRatio',qx.maximumAdjacentCellRatio, ...
        'yRatio',qy.maximumAdjacentCellRatio, ...
        'xCurvature',qx.maximumLogSpacingCurvature, ...
        'yCurvature',qy.maximumLogSpacingCurvature, ...
        'actualCoreCells',audit.coreCells, ...
        'leftFrontCells',audit.leftFrontCells, ...
        'relativePeakJump',audit.relativePeakJump, ...
        'cumulativeAbsolutePeakJump',audit.cumulativeAbsolutePeakJump, ...
        'massRelativeDefect',audit.massRelativeDefect, ...
        'relativeRangeViolation',audit.relativeRangeViolation, ...
        'safetyFactor',safety,'transferSeconds',transferSeconds, ...
        'flowSeconds',flowSeconds);
    rows=append(rows,row);
    fprintf('%s audit=%d flow=%d x=%.8f y=%.8f peak=%.4g mass=%.4g\n', ...
        names{k},row.auditPassed,row.postFlowPassed,row.xRatio,row.yRatio, ...
        row.relativePeakJump,row.massRelativeDefect);
    clear trial audit
end
report=struct('kind','same_node_density_native_transfer_audit_v1', ...
    'sourceCheckpoint',d.checkpointFile,'tau',d.tau, ...
    'nodeCount',d.nodeCount,'rows',rows, ...
    'sourceUnchanged',true,'candidateCommitted',false,'futureLifetimeCertified',false);
fid=fopen(outputFile,'w');assert(fid>=0);c=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
function rows=append(rows,row)
if isempty(rows),rows=row;else,rows(end+1)=row;end
end
