function report=audit_native_cross_level_growth(checkpointFile,transactionIndex,outputFile)
%AUDIT_NATIVE_CROSS_LEVEL_GROWTH Compact a signed actual growth transaction.
% Reads one accepted checkpoint and its complete trusted history; no LU,
% evolution, remesh proposal or alternate lineage is constructed.
assert(~isfile(outputFile));
cp=ipm.output.readCheckpoint(checkpointFile);
s=cp.payload.state;
assert(cp.trustedRecord && ...
    all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
ledger=s.runMetadata.autonomousMesh.transactions;
assert(isfield(s.runMetadata.caseMetadata,'manualMidRunGridChanges') && ...
    isequal(s.runMetadata.caseMetadata.manualMidRunGridChanges,false));
assert(transactionIndex>=1 && transactionIndex<=numel(ledger));
t=ledger(transactionIndex);
assert(t.passed && t.sourceLevelId~=t.targetLevelId && ...
    prod(t.targetNodeCount)>prod(t.sourceNodeCount) && ...
    t.sourceRemeshCount==transactionIndex-1);
report=struct('kind','signed_original_t0_native_cross_level_growth_v1', ...
    'checkpointFile',checkpointFile,'checkpointTrusted',true, ...
    'fullHistoryTrusted',true,'transactionIndex',transactionIndex, ...
    'sourceStep',t.sourceStep,'sourceTau',t.sourceCanonicalTime, ...
    'sourceLevelId',t.sourceLevelId,'targetLevelId',t.targetLevelId, ...
    'sourceNodeCount',t.sourceNodeCount,'targetNodeCount',t.targetNodeCount, ...
    'actualCoreCells',t.coreCells, ...
    'relativePeakJump',t.relativePeakJump, ...
    'massRelativeDefect',t.massRelativeDefect, ...
    'relativeRangeViolation',t.relativeRangeViolation, ...
    'migrationPassed',t.passed, ...
    'checkpointStep',s.step,'checkpointTau',s.scale.canonicalTime, ...
    'checkpointNodeCount',[numel(s.x),numel(s.y)], ...
    'checkpointRemeshCount',s.remeshCount, ...
    'manualMidRunGridChange',false);
fid=fopen(outputFile,'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('NATIVE_GROWTH tx=%d tau=%.9f nodes=%dx%d -> %dx%d passed=%d\n', ...
    transactionIndex,t.sourceCanonicalTime,t.sourceNodeCount, ...
    t.targetNodeCount,t.passed);
end
