function report=audit_density_mode_one_planned(distributionFile,outputFile)
%AUDIT_DENSITY_MODE_ONE_PLANNED Native audit of the exact opt-in planned pair.
assert(isfile(distributionFile)&&~isfile(outputFile));
d=jsondecode(fileread(distributionFile));
c=ipm.output.readCheckpoint(d.checkpointFile);
[source,~,~]=ipm.output.restoreCheckpoint(c,struct());
maxNumCompThreads(4);
if isfield(source.ops,'poisson'),source.ops=rmfield(source.ops,'poisson');end
oldPolicy=source.config.remesh.autonomousMesh;
input=oldPolicy;input.densityVersion=1;
input.search.roundingCells=[8,16,24,32,40];
modeOne=ipm.config.autonomousMeshPolicy(input);
ops=source.ops;
view=struct('rho',source.rho,'x',ops.x,'y',ops.y,'Dx',ops.Dx, ...
    'source',source.rho*ops.Dx','trusted',true);
[pairs,~]=ipm.remesh.plannedAxisPairs(view, ...
    struct('x',ops.baseX,'y',ops.baseY),1,modeOne);
index=find(~[pairs.unchanged],1);
assert(~isempty(index));candidate=pairs(index);
memory=source.runMetadata.autonomousMesh;
proposal=struct('x',candidate.x,'y',candidate.y, ...
    'referenceFamily',memory.referenceFamily, ...
    'sourceLevelId',memory.currentLevelId, ...
    'targetLevelId',memory.currentLevelId);
trial=source;timer=tic;
[trial.rho,trial.ops]=ipm.remesh.transfer( ...
    source.rho,source.ops,source.config,proposal);
transferSeconds=toc(timer);
audit=ipm.remesh.auditCandidate(source,trial,oldPolicy, ...
    memory.cumulativeAbsolutePeakJump);
postFlowPassed=false;safety=NaN;
if audit.passed
    [~,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
    safety=trial.flow.safetyFactor;
    postFlowPassed=ipm.evolve.isFinite(trial) && ...
        safety<oldPolicy.maximumSafety && ...
        all([trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints] ...
            >=oldPolicy.transactionMinimumCoreCells);
end
report=struct('kind','density_mode_one_exact_planned_pair_native_audit_v1', ...
    'source',distributionFile,'tau',d.tau,'candidateIndex',index, ...
    'xTrial',candidate.xIndex,'yTrial',candidate.yIndex, ...
    'sameNodeCount',isequal([numel(candidate.x),numel(candidate.y)],d.nodeCount(:)'), ...
    'xRatio',audit.xQuality.maximumAdjacentCellRatio, ...
    'yRatio',audit.yQuality.maximumAdjacentCellRatio, ...
    'predictedCells',candidate.predictedCells, ...
    'actualCoreCells',audit.coreCells,'actualFrontCells',audit.leftFrontCells, ...
    'auditPassed',audit.passed,'auditReasons',{audit.reasons}, ...
    'postFlowPassed',postFlowPassed,'safetyFactor',safety, ...
    'relativePeakJump',audit.relativePeakJump, ...
    'massRelativeDefect',audit.massRelativeDefect, ...
    'relativeRangeViolation',audit.relativeRangeViolation, ...
    'transferSeconds',transferSeconds,'candidateCommitted',false);
assert(report.sameNodeCount,'ipm:DensityModeNodeCount');
fid=fopen(outputFile,'w');assert(fid>=0);cleaner=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
