function report=audit_frozen_capacity_v5(checkpointFile,outputFile)
%AUDIT_FROZEN_CAPACITY_V5 Screen v4 direction levels on a saved v2 stop state.
% The source is an actual accepted checkpoint. The v4 policy/reference is a
% counterfactual geometry screen only; no native restart/transfer is claimed.
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
assert(all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
assert(s.config.remesh.autonomousMesh.version==2);
target=s.config.remesh.autonomousMesh.targetCoreCells;
policy=ipm.config.autonomousMeshPolicy(struct('version',4, ...
    'targetCoreCells',target, ...
    'nodeFamily',struct('maximumTotalNodes',310000)));
root=s.runMetadata.autonomousMesh.referenceFamily;
family=ipm.remesh.referenceAxisFamily(root.rootX,root.rootY, ...
    s.config.scaling.transportAnchorX,policy);
Dx=ipm.mesh.fdMatrix(s.x,1,7);
view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx, ...
    'source',s.rho*Dx','trusted',true);
ids=[4,7,8];rows=struct([]);
for id=ids
    member=family.members(id);
    [candidates,trial,search]=ipm.remesh.hierarchicalAxisPairs(view, ...
        struct('x',member.baseX,'y',member.baseY), ...
        s.config.scaling.transportAnchorX,policy,310000);
    best=NaN;bestIndex=[NaN,NaN];
    xGood=find([trial.xTrials.admissible]);
    yGood=find([trial.yTrials.admissible]);
    for i=xGood
        for j=yGood
            ratio=max(trial.xTrials(i).quality.maximumAdjacentCellRatio, ...
                trial.yTrials(j).quality.maximumAdjacentCellRatio);
            if isnan(best)||ratio<best
                best=ratio;bestIndex=[i,j];
            end
        end
    end
    selectedRatio=NaN;
    if ~isempty(candidates)
        selectedRatio=max(candidates(1).quality.x.maximumAdjacentCellRatio, ...
            candidates(1).quality.y.maximumAdjacentCellRatio);
    end
    row=struct('levelId',id,'nodeCount',member.nodeCount, ...
        'totalNodes',prod(member.nodeCount), ...
        'xTrialsEvaluated',search.axisTrialsEvaluated, ...
        'xAdmitted',numel(xGood),'yAdmitted',numel(yGood), ...
        'bestMinimaxRatio',best,'bestIndices',bestIndex, ...
        'returnedPairCount',numel(candidates), ...
        'firstReturnedRatio',selectedRatio, ...
        'searchStatus',search.status,'fallbackUsed',search.fallbackUsed);
    if isempty(rows),rows=row;else,rows(end+1)=row;end
    fprintf('FROZEN_CAPACITY tau=%.6f level=%d n=%dx%d pass=%d/%d ratio=%.6f search=%s\n', ...
        s.scale.canonicalTime,id,member.nodeCount(1),member.nodeCount(2), ...
        numel(xGood),numel(yGood),best,search.status);
end
report=struct('kind','frozen_v2_failure_counterfactual_v4_geometry_v1', ...
    'checkpoint',checkpointFile,'step',s.step, ...
    'canonicalTime',s.scale.canonicalTime, ...
    'sourceVersion',2,'screenVersion',4,'rows',rows, ...
    'noLU',true,'noTransfer',true,'noPDE',true, ...
    'nativeContinuationClaim',false);
if nargin>=2&&~isempty(outputFile)
    assert(~isfile(outputFile));fid=fopen(outputFile,'w');assert(fid>=0);
    cleaner=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
end
