function report=compare_v4_v5_physical_core(checkpointV4,checkpointV5,outputDirectory)
%COMPARE_V4_V5_PHYSICAL_CORE Read-only nearby-time adaptive-policy check.
% Both complete original-t0 trajectories are validated. This is not a
% same-time or independent spatial convergence certificate.
assert(~isfolder(outputDirectory),'ipm:V4V5CoreOutputExists');
a=ipm.output.readCheckpoint(checkpointV4);
b=ipm.output.readCheckpoint(checkpointV5);
s4=a.payload.state;s5=b.payload.state;
assert(all(ipm.output.trustedMask(a.payload.log.history,s4.config))&& ...
    all(ipm.output.trustedMask(b.payload.log.history,s5.config)));
assert(s4.runMetadata.autonomousMesh.version==4&& ...
    s5.runMetadata.autonomousMesh.version==5&& ...
    isequaln(s4.config.physics,s5.config.physics)&& ...
    isequaln(s4.config.transport,s5.config.transport)&& ...
    isequaln(s4.config.scaling,s5.config.scaling)&& ...
    isequal(s4.config.grid.xlim,s5.config.grid.xlim)&& ...
    s4.config.grid.ymax==s5.config.grid.ymax);
timeGap=abs(s4.scale.physicalTime-s5.scale.physicalTime);
assert(timeGap<1e-5,'ipm:V4V5PhysicalTimeGap');
v4=physical_view(s4,a.payload.log.history);
v5=physical_view(s5,b.payload.log.history);
center=(v4.physicalPeakX+v5.physicalPeakX)/2;
wallWidth=max(v4.physicalWallWidth,v5.physicalWallWidth);
verticalWidth=max(v4.physicalVerticalWidth,v5.physicalVerticalWidth);
queryX=linspace(center-2*wallWidth,center+2*wallWidth,401);
queryY=linspace(0,2*verticalWidth,201)';
assert(queryX(1)>max(v4.x(1),v5.x(1))&& ...
    queryX(end)<min(v4.x(end),v5.x(end))&& ...
    queryY(end)<min(v4.y(end),v5.y(end)));
[X,Y]=meshgrid(queryX,queryY);
F4=griddedInterpolant({v4.y,v4.x},v4.physicalRhoX,'linear','none');
F5=griddedInterpolant({v5.y,v5.x},v5.physicalRhoX,'linear','none');
q4=F4(Y,X);q5=F5(Y,X);
assert(all(isfinite(q4),'all')&&all(isfinite(q5),'all'));
difference=q5-q4;
report=struct('kind','v4_v5_nearby_physical_core_v1', ...
    'v4Checkpoint',checkpointV4,'v5Checkpoint',checkpointV5, ...
    'v4Step',s4.step,'v5Step',s5.step, ...
    'v4Tau',s4.scale.canonicalTime,'v5Tau',s5.scale.canonicalTime, ...
    'v4PhysicalTime',s4.scale.physicalTime, ...
    'v5PhysicalTime',s5.scale.physicalTime, ...
    'physicalTimeGap',timeGap, ...
    'v4NodeCount',[numel(s4.x),numel(s4.y)], ...
    'v5NodeCount',[numel(s5.x),numel(s5.y)], ...
    'axesExactlyEqual',isequal(s4.x,s5.x)&&isequal(s4.y,s5.y), ...
    'v4RemeshCount',s4.remeshCount,'v5RemeshCount',s5.remeshCount, ...
    'v4PhysicalPeakX',v4.physicalPeakX, ...
    'v5PhysicalPeakX',v5.physicalPeakX, ...
    'physicalPeakXDifference',v5.physicalPeakX-v4.physicalPeakX, ...
    'v4PhysicalWallWidth',v4.physicalWallWidth, ...
    'v5PhysicalWallWidth',v5.physicalWallWidth, ...
    'v4PhysicalVerticalWidth',v4.physicalVerticalWidth, ...
    'v5PhysicalVerticalWidth',v5.physicalVerticalWidth, ...
    'v4PhysicalWallPeak',v4.physicalWallPeak, ...
    'v5PhysicalWallPeak',v5.physicalWallPeak, ...
    'commonQueryNodeCount',[numel(queryX),numel(queryY)], ...
    'physicalRhoXRelativeL2',norm(difference,'fro')/norm(q4,'fro'), ...
    'physicalRhoXRelativeInf',max(abs(difference),[],'all')/ ...
        max(abs(q4),[],'all'), ...
    'samePhysicalTimeClaim',false,'spatialConvergenceClaim',false, ...
    'fullHistoriesTrusted',true);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('V4_V5_CORE dt=%.3e drhoX L2/Inf=%.3e/%.3e dpeak=%.3e\n', ...
    timeGap,report.physicalRhoXRelativeL2, ...
    report.physicalRhoXRelativeInf,report.physicalPeakXDifference);
end

function view=physical_view(state,history)
x=state.x(:)';y=state.y(:);
Cx=exp(state.scale.logC_l);Cw=exp(state.scale.logC_omega);
source=state.rho*ipm.mesh.fdMatrix(x,1,7)';
peakX=history.gauge.omegaGaugeQuadraticPeakX(end);
peak=history.gauge.omegaGaugeQuadraticPeakValue(end);
wx=history.mesh.trackedWallCoreWidth(end);
wy=history.mesh.trackedVerticalCoreWidth(end);
view=struct('x',(x-state.scale.X_shift)/Cx,'y',y/Cx, ...
    'physicalRhoX',source*Cx/Cw, ...
    'physicalPeakX',(peakX-state.scale.X_shift)/Cx, ...
    'physicalWallWidth',wx/Cx,'physicalVerticalWidth',wy/Cx, ...
    'physicalWallPeak',peak*Cx/Cw);
assert(all(isfinite(view.physicalRhoX),'all')&& ...
    all(diff(view.x)>0)&&all(diff(view.y)>0));
end
