function report=compare_four_to_one_frozen(checkpointFiles,outputFile)
%COMPARE_FOUR_TO_ONE_FROZEN Screen fresh 4n-by-n roots on signed late states.
% Geometry only: these are not legal continuations of the source histories.
assert(iscell(checkpointFiles)&&numel(checkpointFiles)==2&&~isfile(outputFile));
rows=struct([]);
for sourceIndex=1:numel(checkpointFiles)
    cp=ipm.output.readCheckpoint(checkpointFiles{sourceIndex});
    assert(cp.trustedRecord);
    s=cp.payload.state;
    Dx=ipm.mesh.fdMatrix(s.x,1,7);
    view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx, ...
        'source',s.rho*Dx','trusted',true);
    for n=[256,320]
        counts=[4*n+1,n+1];
        cap=1200000;
        if n==320,cap=1700000;end
        opts=ipm.config.longTimeProfile(struct( ...
            'initialNodeCount',counts,'autonomousMeshVersion',5, ...
            'meshDensityVersion',2,'maximumTotalNodes',cap));
        config=ipm.config.resolve(opts);
        policy=config.remesh.autonomousMesh;
        reference=struct('x',linspace(s.x(1),s.x(end),counts(1)), ...
            'y',linspace(s.y(1),s.y(end),counts(2))');
        timer=tic;
        [pairs,detail,search]=ipm.remesh.hierarchicalAxisPairs( ...
            view,reference,config.scaling.transportAnchorX,policy,cap);
        elapsed=toc(timer);
        selected=struct('candidateIndex',NaN,'xIndex',NaN,'yIndex',NaN, ...
            'plannedRatio',[NaN,NaN],'predictedCells',[NaN,NaN,NaN]);
        changed=find(~[pairs.unchanged],1);
        if ~isempty(changed)
            p=pairs(changed);
            selected=struct('candidateIndex',changed,'xIndex',p.xIndex, ...
                'yIndex',p.yIndex,'plannedRatio', ...
                [p.quality.x.maximumAdjacentCellRatio, ...
                 p.quality.y.maximumAdjacentCellRatio], ...
                'predictedCells',p.predictedCells);
        end
        row=struct('sourceCheckpoint',checkpointFiles{sourceIndex}, ...
            'sourceTau',s.scale.canonicalTime,'sourceStep',s.step, ...
            'sourceGrid',[numel(s.x),numel(s.y)], ...
            'targetGrid',counts,'maximumTotalNodes',cap, ...
            'candidateCount',numel(pairs),'selected',selected, ...
            'planningStatus',detail.status,'searchStatus',search.status, ...
            'planningSeconds',elapsed);
        if isempty(rows),rows=row;else,rows(end+1)=row;end
        fprintf('FOUR_TO_ONE source_tau=%.6f target=%dx%d candidates=%d ratio=%.6f/%.6f core=%.3f/%.3f phase=%s\n', ...
            row.sourceTau,counts,numel(pairs),selected.plannedRatio, ...
            selected.predictedCells(1:2),search.status);
    end
end
report=struct('kind','fresh_four_to_one_late_frozen_geometry_v1', ...
    'rows',rows,'noLU',true,'noTransfer',true, ...
    'notSourceHistoryContinuation',true);
fid=fopen(outputFile,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
