function report=evaluate_frozen_profile_forecast(checkpointFile,forecastFile,outputFile)
%EVALUATE_FROZEN_PROFILE_FORECAST No-LU evaluation on newly computed states.
% The predictor and its training interval remain fixed. Fresh clocks have
% explicit direct-parent provenance, rather than an invented time shift.
assert(~isfile(outputFile),'Refusing to replace a prospective observation.');
assert(maxNumCompThreads==10);
loaded=load(forecastFile,'forecast');f=loaded.forecast;reg=f.registration;
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
assert(all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
assert(strcmp(s.config.scaling.lengthGauge,'transport_anchor') && ...
    strcmp(s.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak') && ...
    strcmp(s.config.scaling.dynamicScaleGeometry,'isotropic'));
equivalentTau=s.scale.canonicalTime;epoch=0;parentCaseId=char(s.runMetadata.caseId);
if isfield(s.runMetadata.caseMetadata,'latePhysicalBoxBranch')
    lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
    parent=ipm.output.readCheckpoint(lineage.parentCheckpoint);p=parent.payload.state;
    assert(~isfield(p.runMetadata.caseMetadata,'latePhysicalBoxBranch') && ...
        strcmp(p.runMetadata.caseId,lineage.parentCaseId) && p.step==lineage.parentStep && ...
        p.scale.canonicalTime==lineage.parentCanonicalTime && ...
        p.scale.physicalTime==lineage.absolutePhysicalEpoch && ...
        exp(p.scale.logC_l)==lineage.parentCx && exp(p.scale.logC_omega)==lineage.parentComega && ...
        ~lineage.parentHistoryInherited && ~lineage.parentCheckpointModified);
    equivalentTau=lineage.parentCanonicalTime+lineage.canonicalCovarianceFactor*s.scale.canonicalTime;
    epoch=lineage.absolutePhysicalEpoch;parentCaseId=char(lineage.parentCaseId);
end
assert(equivalentTau>=reg.futureEquivalentTauInterval(1) && ...
    equivalentTau<=reg.futureEquivalentTauInterval(2), ...
    'ipm:ProspectiveProfileTime','This state is outside the preregistered future interval.');
training=load(reg.trainingSource,'report');
original=ipm.output.readCheckpoint(training.report.registration.frames(1).checkpoint);
assert(strcmp(parentCaseId,original.payload.state.runMetadata.caseId));
anchor=s.config.scaling.transportAnchorX;window=anchor*reg.fixedPeakWindowInTransportAnchorUnits;
Dx=ipm.mesh.fdMatrix(s.x,1,7);Dy=ipm.mesh.fdMatrix(s.y,1,7);W=s.rho*Dx';
geometry=continuous_inner_geometry(W,s.x,s.y,Dx,Dy,window);
nx=reg.observerResolution(1);ny=reg.observerResolution(2);
[XI,ETA]=meshgrid(linspace(-1,1,nx),linspace(0,2,ny));
sample=ipm_accellab_tensor_hermite(W,s.x,s.y,Dx,Dy, ...
    geometry.peakX+geometry.wallWidth*XI,geometry.verticalWidth*ETA);
actual=reshape(sample.value/geometry.peak,1,[]);
dt=equivalentTau-f.trainingTau(end);fraction=dt/f.deltaTau;
predictions={f.candidateLimit+(f.lastTrainingField-f.candidateLimit)* ...
    f.incrementFactorPerStep^fraction, ...
    f.linearCoefficients(1,:)+dt*f.linearCoefficients(2,:), ...
    f.singleDecayCoefficients(1,:)+exp(-f.singleDecayRate*dt)*f.singleDecayCoefficients(2,:)};
wx=ones(1,nx);wx([1,end])=.5;wy=ones(ny,1);wy([1,end])=.5;
weights=wy*wx;weights=weights(:)'/sum(weights,'all');
names={'fixedIncrementRank1','fixedLinearTime','fixedSingleDecay'};errors=struct;
for k=1:numel(names)
    delta=predictions{k}-actual;
    errors.(names{k})=struct('relativeL2',sqrt(sum(delta.^2.*weights)/sum(actual.^2.*weights)), ...
        'relativeInf',max(abs(delta))/max(abs(actual)));
end
report=struct('checkpointFile',checkpointFile,'forecastFile',forecastFile, ...
    'caseId',char(s.runMetadata.caseId),'parentCaseId',parentCaseId,'step',s.step, ...
    'parentEquivalentTau',equivalentTau,'physicalEpoch',epoch, ...
    'absolutePhysicalTime',epoch+s.scale.physicalTime,'geometry',geometry, ...
    'errors',errors,'distanceToFixedCandidateLimit', ...
    sqrt(sum((f.candidateLimit-actual).^2.*weights)/sum(actual.^2.*weights)), ...
    'fullHistoryTrusted',true,'nativeSignatureValidated',true,'predictorRefitted',false, ...
    'pdeAdvanced',false,'interpretation','Prospective shape prediction, including actual mesh/box sensitivity; no extrapolated field is a PDE trajectory.');
fid=fopen(outputFile,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
