function report=fit_profile_increment_dmd(tau,fields,weights,trainingCount,rankValue)
%FIT_PROFILE_INCREMENT_DMD Finite-history reduced linear increment predictor.
% No fitted field is advanced as a PDE trajectory. Unstable/near-unit modes
% and a poorly determined limit are reported, never clipped to stability.
tau=tau(:);weights=weights(:)';weights=weights/sum(weights);
assert(size(fields,1)==numel(tau) && size(fields,2)==numel(weights));
assert(all(isfinite(fields),'all') && all(weights>0) && all(diff(tau)>0));
assert(max(abs(diff(tau)-mean(diff(tau))))<1e-9*mean(diff(tau)));
assert(trainingCount>=4 && trainingCount<numel(tau) && ...
    rankValue>=1 && rankValue<=trainingCount-2 && rankValue==fix(rankValue));
rootWeight=sqrt(weights);w=fields.*rootWeight;delta=diff(w(1:trainingCount,:),1,1);
X=delta(1:end-1,:)';Y=delta(2:end,:)';[U,S,V]=svd(X,'econ');singularValues=diag(S);
assert(singularValues(1)>1e-12*norm(w(1:trainingCount,:),'fro'), ...
    'Increment signal is too small for this predictor.');
assert(singularValues(rankValue)>1e-10*singularValues(1), ...
    'Requested rank includes a numerically unresolved singular direction.');
U=U(:,1:rankValue);S=S(1:rankValue,1:rankValue);V=V(:,1:rankValue);
B=(Y*V)/S;A=U'*B;lambda=eig(A);coordinates=U'*delta(end,:)';
predictions=zeros(numel(tau)-trainingCount,size(w,2));current=w(trainingCount,:)';
for k=1:size(predictions,1)
    current=current+B*coordinates;predictions(k,:)=current';coordinates=A*coordinates;
end
truth=w(trainingCount+1:end,:);error=predictions-truth;
stable=all(abs(lambda)<1-1e-8);limitCondition=rcond(eye(rankValue)-A);
limitAvailable=stable && limitCondition>1e-8;
candidateLimit=[];limitDistance=NaN;
if limitAvailable
    correction=B*((eye(rankValue)-A)\(U'*delta(end,:)'));
    candidateLimit=(w(trainingCount,:)'+correction)'./rootWeight;
    limitDistance=norm(correction)/norm(w(trainingCount,:));
end
report=struct('kind','reduced_increment_DMD_prediction_only', ...
    'trainingTimes',tau(1:trainingCount)','heldoutTimes',tau(trainingCount+1:end)', ...
    'rank',rankValue,'trainingSingularValues',singularValues', ...
    'eigenvaluesReal',real(lambda)','eigenvaluesImaginary',imag(lambda)', ...
    'spectralRadius',max(abs(lambda)),'allModesStrictlyStable',stable, ...
    'limitSystemRcond',limitCondition,'candidateLimitAvailable',limitAvailable, ...
    'trainingIncrementRelativeResidual',norm(Y-B*(U'*X),'fro')/norm(Y,'fro'), ...
    'relativeL2',sqrt(sum(error.^2,2)./sum(truth.^2,2))', ...
    'relativeInf',(max(abs(error./rootWeight),[],2)./ ...
        max(abs(fields(trainingCount+1:end,:)),[],2))', ...
    'candidateLimitDistanceFromLastTraining',limitDistance, ...
    'candidateLimit',candidateLimit,'pdeAdvanced',false);
end
