function report=fit_profile_mode(tau,fields,weights,trainingCount)
%FIT_PROFILE_MODE Fixed-window single-decay variable-projection forecast.
% Rows are ordered time samples, columns are paired observation points.
tau=tau(:);weights=weights(:)';
assert(size(fields,1)==numel(tau) && size(fields,2)==numel(weights));
assert(all(isfinite(fields),'all') && all(isfinite(tau)) && all(diff(tau)>0));
assert(all(isfinite(weights)) && all(weights>0) && trainingCount>=3 && ...
    trainingCount<numel(tau) && trainingCount==fix(trainingCount));
weights=weights/sum(weights);rootWeight=sqrt(weights);
weighted=fields.*rootWeight;
t=tau-tau(trainingCount);training=1:trainingCount;heldout=trainingCount+1:numel(tau);
rates=linspace(.02,4,201);loss=zeros(size(rates));
for k=1:numel(rates),loss(k)=objective(rates(k),t(training),weighted(training,:));end
[~,best]=min(loss);boundary=best==1 || best==numel(rates);
if boundary
    rate=rates(best);
else
    rate=fminbnd(@(r)objective(r,t(training),weighted(training,:)), ...
        rates(best-1),rates(best+1),optimset('TolX',1e-10));
end
decayCoefficients=[ones(trainingCount,1),exp(-rate*t(training))]\weighted(training,:);
linearCoefficients=[ones(trainingCount,1),t(training)]\weighted(training,:);
predictions={repmat(weighted(trainingCount,:),numel(heldout),1), ...
    [ones(numel(heldout),1),t(heldout)]*linearCoefficients, ...
    [ones(numel(heldout),1),exp(-rate*t(heldout))]*decayCoefficients};
names={'persistence','linearTime','singleDecay'};models=struct;
trainingChange=norm(diff(weighted(training,:),1,1),'fro')/max(norm(weighted(training,:),'fro'),eps);
for k=1:numel(names)
    error=predictions{k}-weighted(heldout,:);
    models.(names{k})=struct('relativeL2',sqrt(sum(error.^2,2)./sum(weighted(heldout,:).^2,2))', ...
        'relativeInf',(max(abs(error./rootWeight),[],2)./max(abs(fields(heldout,:)),[],2))');
end
report=struct('trainingTimes',tau(training)','heldoutTimes',tau(heldout)', ...
    'rateBounds',[rates(1),rates(end)],'rate',rate,'rateSearchBoundaryTouched',boundary, ...
    'trainingRelativeChange',trainingChange,'hasMeasurableTrainingChange',trainingChange>1e-10, ...
    'trainingWeightedSquaredResidual',objective(rate,t(training),weighted(training,:)), ...
    'models',models,'outperformsPersistenceAtEveryHeldoutTime', ...
    all(models.singleDecay.relativeL2<models.persistence.relativeL2), ...
    'outperformsLinearAtEveryHeldoutTime', ...
    all(models.singleDecay.relativeL2<models.linearTime.relativeL2), ...
    'candidateLimit',decayCoefficients(1,:)./rootWeight, ...
    'candidateLimitDistanceFromLastTraining', ...
    norm(decayCoefficients(1,:)-weighted(trainingCount,:))/norm(weighted(trainingCount,:)), ...
    'interpretation','Finite-dimensional prediction screen; a fitted limit is not a PDE trajectory or convergence proof.');
end

function value=objective(rate,t,fields)
basis=[ones(numel(t),1),exp(-rate*t)];
residual=fields-basis*(basis\fields);
value=sum(residual.^2,'all');
end
