function qualification=fresh_profile_campaign_admit(qualificationFile,resultFile,initialDataFile,checkpoint)
%FRESH_PROFILE_CAMPAIGN_ADMIT Explicit direct or rechecked-chain qualification.
% Existing same-grid admission remains unchanged. A saved chain success flag
% is never substituted for re-reading the complete actual native evidence.
q=jsondecode(fileread(qualificationFile));
if strcmp(q.kind,'fresh_profile_campaign_bootstrap_qualification_v1')
    qualification=fresh_profile_campaign_qualification(qualificationFile,resultFile,checkpoint);
    return
end
assert(strcmp(q.kind,'fresh_profile_campaign_bootstrap_chain_qualification_v1'), ...
    'ipm:FreshCampaignQualification','Unknown explicit bootstrap qualification type.');
required={'bootstrapResultFile','bootstrapCheckpointFile','baseQualificationFile', ...
    'campaignDirectories','newChainEvidenceDirectory','legacySmokePassed', ...
    'continuousObserverAuxiliaryPassed','originalLegacyDecisionChanged'};
assert(all(isfield(q,required)) && strcmp(q.bootstrapResultFile,resultFile) && ...
    ~q.legacySmokePassed && q.continuousObserverAuxiliaryPassed && ~q.originalLegacyDecisionChanged, ...
    'ipm:FreshCampaignQualification','Chain caller must identify its actual target and preserve all original decisions.');
native=ipm.output.readCheckpoint(checkpoint);result=ipm.output.validate(resultFile);
pairedNative=ipm.output.readCheckpoint(char(result.metadata.latestCheckpointFile));
assert(strcmp(q.bootstrapCheckpointFile,result.metadata.latestCheckpointFile) && ...
    fresh_profile_value_equal(native.payload,pairedNative.payload) && ...
    isequal(native.payload.state.rho,result.state.rho) && ...
    isequal(native.payload.state.x(:),result.grid.x(:)) && ...
    isequal(native.payload.state.y(:),result.grid.y(:)) && ...
    isequaln(native.payload.log.history,result.history) && native.payload.state.step==result.state.steps, ...
    'ipm:FreshCampaignQualification','Actual caller native input must pair with the target result.');
clear result pairedNative
budgetLimitedCheckpointFiles={};
if isfield(q,'budgetLimitedCheckpointFiles')
    budgetLimitedCheckpointFiles=q.budgetLimitedCheckpointFiles;
end
chain=fresh_profile_qualification_chain(q.baseQualificationFile,initialDataFile, ...
    q.campaignDirectories,resultFile,q.newChainEvidenceDirectory,budgetLimitedCheckpointFiles);
assert(chain.allPassed && strcmp(chain.targetCheckpointFile,q.bootstrapCheckpointFile) && ...
    strcmp(chain.targetResultFile,resultFile) && ~chain.originalLegacySmokePassed && ...
    chain.originalContinuousAuxiliaryPassed && ~chain.originalLegacyDecisionChanged && ...
    chain.noLU && chain.noPDE);
qualification=q;
qualification.recheckedNativeChain=struct('reportFile',fullfile(q.newChainEvidenceDirectory,'chain_report.json'), ...
    'linkCount',numel(chain.links),'targetStep',chain.targetReview.step, ...
    'targetParentEquivalentTau',chain.targetReview.parentEquivalentTau, ...
    'cumulativeAbsolutePeakJump',chain.cumulativeAbsolutePeakJump,'recomputedDuringThisAdmission',true);
end
