function q=fresh_profile_campaign_qualification(file,resultFile,bootstrap)
%FRESH_PROFILE_CAMPAIGN_QUALIFICATION Check the caller ledger against real evidence.
% No LU or PDE; same-grid qualified history must prefix the native bootstrap.
assert(maxNumCompThreads==10);
q=jsondecode(fileread(file));
required={'kind','bootstrapResultFile','bootstrapCheckpointFile','qualifiedGridCheckpointFile', ...
    'legacySmokeReportFile','legacySmokePassed','continuousAuxiliaryVerdictFile','continuousObserverAuxiliaryPassed'};
assert(all(isfield(q,required)) && strcmp(q.kind,'fresh_profile_campaign_bootstrap_qualification_v1') && ...
    strcmp(q.bootstrapResultFile,resultFile),'ipm:FreshCampaignQualification','Explicit caller qualification schema/result mismatch.');
bootstrap=ipm.output.readCheckpoint(bootstrap);
s=bootstrap.payload.state;actual=ipm.output.validate(resultFile);
assert(isequal(s.rho,actual.state.rho) && isequal(s.x,actual.grid.x) && isequal(s.y,actual.grid.y) && ...
    s.step==actual.state.steps && s.scale.canonicalTime==actual.state.canonicalTime && ...
    s.scale.physicalTime==actual.state.physicalTime && s.normalizedTime==actual.state.normalizedTime && ...
    exp(s.scale.logC_l)==actual.scale.Cx && exp(s.scale.logC_omega)==actual.scale.Comega && ...
    isequaln(bootstrap.payload.log.history,actual.history) && fresh_profile_value_equal(s.config,actual.config), ...
    'ipm:FreshCampaignQualification','The qualification input must be the actual result-paired native bootstrap.');
assert(strcmp(q.bootstrapCheckpointFile,actual.metadata.latestCheckpointFile));clear actual
legacy=jsondecode(fileread(q.legacySmokeReportFile));aux=jsondecode(fileread(q.continuousAuxiliaryVerdictFile));
assert(q.legacySmokePassed==legacy.passed && q.continuousObserverAuxiliaryPassed==aux.continuousObserverAuxiliaryPassed && ...
    aux.continuousObserverAuxiliaryPassed && ~aux.originalLegacyDecisionChanged && ...
    aux.originalLegacySmokePassed==legacy.passed && strcmp(aux.smokeFile,q.legacySmokeReportFile) && ...
    strcmp(legacy.branches(2).checkpointFile,q.qualifiedGridCheckpointFile), ...
    'ipm:FreshCampaignQualification','The actual legacy and independent auxiliary decisions must both be reported truthfully.');
auxiliaryChecks={'nativeTransactionEndpointPrefixLineagePassed','originalLinearFieldGatesPassed', ...
    'originalPeakGatesPassed','originalRateGatesPassed','zeroAndMatchedContinuousWidthGatesPassed'};
assert(~legacy.passed && ~q.legacySmokePassed && ~aux.originalLegacySmokePassed && ...
    all(isfield(aux,auxiliaryChecks)) && all(cellfun(@(name)isequal(aux.(name),true),auxiliaryChecks)), ...
    'ipm:FreshCampaignQualification','Every independent auxiliary subgate must pass while the original legacy decision remains false.');
qualified=ipm.output.readCheckpoint(q.qualifiedGridCheckpointFile);t=qualified.payload.state;
assert(all(ipm.output.trustedMask(qualified.payload.log.history,t.config)) && ...
    strcmp(s.runMetadata.caseId,t.runMetadata.caseId) && s.remeshCount==t.remeshCount && ...
    isequaln(s.runMetadata.caseMetadata.latePhysicalBoxBranch,t.runMetadata.caseMetadata.latePhysicalBoxBranch) && ...
    isequal(s.x,t.x) && isequal(s.y,t.y) && isequaln(s.rescaling,t.rescaling), ...
    'ipm:FreshCampaignQualification','Bootstrap must be the qualified fresh grid or its same-grid native continuation.');
for domain={'grid','physics','transport','elliptic','scaling','remesh','diagnostics'}
    assert(fresh_profile_value_equal(s.config.(domain{1}),t.config.(domain{1})), ...
        'ipm:FreshCampaignQualification','Bootstrap numerical specification or captured physical initial data differ from qualified source.');
end
assert(fresh_profile_value_equal(rmfield(s.config.time,{'finalTime','physicalFinalTime','maxSteps'}), ...
    rmfield(t.config.time,{'finalTime','physicalFinalTime','maxSteps'})), ...
    'ipm:FreshCampaignQualification','Bootstrap time numerics differ from qualified source.');
fresh_profile_history_prefix(qualified.payload.log.history,bootstrap.payload.log.history,false);
end

