function chain=fresh_profile_qualification_chain(baseQualificationFile,initialDataFile,campaignDirectories,targetResultFile,outDir,budgetLimitedCheckpointFiles)
%FRESH_PROFILE_QUALIFICATION_CHAIN Recheck a continuous native campaign chain.
% Future batch qualification only; no solver restore, LU, PDE or native edits.
assert(maxNumCompThreads==10 && ~isfolder(outDir));mkdir(outDir);
if nargin<6,budgetLimitedCheckpointFiles={};end
assert(iscell(budgetLimitedCheckpointFiles) && (isempty(budgetLimitedCheckpointFiles) || isvector(budgetLimitedCheckpointFiles)) && ...
    all(cellfun(@(p)ischar(p) && isrow(p) && ~isempty(p),budgetLimitedCheckpointFiles)) && ...
    numel(unique(budgetLimitedCheckpointFiles))==numel(budgetLimitedCheckpointFiles), ...
    'ipm:FreshChainBudgetAllowlist','Budget-limited endpoints require distinct explicit checkpoint paths.');
usedBudgetAllowlist=false(size(budgetLimitedCheckpointFiles));
campaignDirectories=cellstr(string(campaignDirectories));assert(~isempty(campaignDirectories));
base=jsondecode(fileread(baseQualificationFile));
[currentReview,current,contract]=fresh_profile_campaign_review(base.bootstrapResultFile,initialDataFile);
fresh_profile_campaign_qualification(baseQualificationFile,base.bootstrapResultFile,current);
assert(~isfield(base,'testFixtureOnly') || ~base.testFixtureOnly);
currentFile=currentReview.checkpointFile;currentResult=base.bootstrapResultFile;
cumulative=currentReview.cumulativeAbsolutePeakJump;links=struct([]);found=strcmp(currentResult,targetResultFile);
registration=struct('kind','future_fresh_profile_native_qualification_chain_v1', ...
    'baseQualificationFile',baseQualificationFile,'initialDataFile',initialDataFile, ...
    'campaignDirectories',{campaignDirectories},'targetResultFile',targetResultFile, ...
    'originalLegacySmokePassed',false,'originalContinuousAuxiliaryPassed',true, ...
    'originalLegacyDecisionChanged',false,'transactionMinimumCore',[31,31],'minimumFront',20, ...
    'maximumSingleJump',.002,'maximumCumulativeJump',.02,'minimumSegmentEndCore',[20,20], ...
    'maximumSafety',.70,'noEllipticOperatorsBuilt',true,'noPDEAdvanced',true);
if ~isempty(budgetLimitedCheckpointFiles)
    registration.budgetLimitedCheckpointFiles=budgetLimitedCheckpointFiles;
end
write_json(fullfile(outDir,'registration.json'),registration);
try
 for ci=1:numel(campaignDirectories)
    if found,break;end
    directory=campaignDirectories{ci};r=jsondecode(fileread(fullfile(directory,'registration.json')));
    campaign_budget(r,1);
    assert(strcmp(r.initialCheckpoint,currentFile) && strcmp(r.bootstrapResultFile,currentResult), ...
        'ipm:FreshChainGap','Campaign bootstrap does not equal the preceding accepted native endpoint.');
    stages=dir(fullfile(directory,'stage_*'));stages=stages([stages.isdir]);[~,order]=sort({stages.name});stages=stages(order);
    for k=1:numel(stages)
        assert(strcmp(stages(k).name,sprintf('stage_%03d',k)), ...
            'ipm:FreshChainGap','A numbered stage is missing from the explicit campaign.');
        stageDir=fullfile(stages(k).folder,stages(k).name);auditFile=fullfile(stageDir,'endpoint_audit.json');
        if ~isfile(auditFile)
            nativeFiles=dir(fullfile(stageDir,'**','*checkpoint_*_step*.mat'));
            assert(isempty(nativeFiles) && k==numel(stages), ...
                'ipm:FreshChainIncomplete','A nonterminal or native-advancing stage lacks a paired endpoint audit.');
            break
        end
        endpoint=jsondecode(fileread(auditFile));sourceReview=jsondecode(fileread(fullfile(stageDir,'source_review.json')));
        assert(strcmp(sourceReview.checkpointFile,currentFile), ...
            'ipm:FreshChainSource','Stage source review names the wrong native predecessor.');
        transactionFiles=dir(fullfile(stageDir,'regrid_checkpoint_*_step*.mat'));
        transaction=struct('applied',false);segmentSource=current;segmentFile=currentFile;
        if ~isempty(transactionFiles)
            assert(isscalar(transactionFiles),'ipm:FreshChainTransaction','More than one accepted transaction at one stage.');
            segmentFile=fullfile(transactionFiles.folder,transactionFiles.name);
            segmentSource=ipm.output.readCheckpoint(segmentFile);
            transaction=verify_transaction(current,segmentSource,fullfile(stageDir,'regrid_audit.mat'),cumulative,contract);
            cumulative=transaction.cumulativeAbsolutePeakJump;
        end
        assert(strcmp(endpoint.sourceCheckpoint,segmentFile), ...
            'ipm:FreshChainSource','Endpoint audit names the wrong source native checkpoint.');
        [nextReview,next]=fresh_profile_campaign_review(endpoint.resultFile,initialDataFile,contract);
        assert(strcmp(endpoint.checkpointFile,nextReview.checkpointFile), ...
            'ipm:FreshChainPair','Endpoint audit and paired result name different native checkpoints.');
        a=segmentSource.payload.state;b=next.payload.state;
        fresh_profile_history_prefix(segmentSource.payload.log.history,next.payload.log.history,false);
        assert(isequal(a.x,b.x) && isequal(a.y,b.y) && a.remeshCount==b.remeshCount && ...
            isequaln(a.rescaling,b.rescaling) && isequal(a.mass0,b.mass0) && isequal(a.rhoRange0,b.rhoRange0) && ...
            fresh_profile_value_equal(a.runMetadata.gridLabRegrids,b.runMetadata.gridLabRegrids), ...
            'ipm:FreshChainInvariant','Same-grid segment changed axes, references, remesh count or initial invariants.');
        tauDifference=contract.lineage.canonicalCovarianceFactor*(b.scale.canonicalTime-a.scale.canonicalTime);
        result=ipm.output.validate(endpoint.resultFile);stopReason=char(result.state.stopReason);clear result
        started=solve_registration(directory,k);
        verdict=verify_segment(r,k,sourceReview,endpoint,a,b,nextReview,contract,stopReason,cumulative, ...
            budgetLimitedCheckpointFiles,started);
        if ~verdict.reviewHorizonReached
            usedBudgetAllowlist(strcmp(budgetLimitedCheckpointFiles,nextReview.checkpointFile))=true;
        end
        link=struct('campaignDirectory',directory,'stage',k,'incomingCheckpoint',currentFile, ...
            'segmentSourceCheckpoint',segmentFile,'endpointCheckpoint',nextReview.checkpointFile, ...
            'endpointResultFile',endpoint.resultFile,'transaction',transaction,'sourcePrefixExact',true, ...
            'nativeAndResultExactlyPaired',true,'endpointReview',nextReview,'actualEquivalentTauIncrement',tauDifference, ...
            'reviewHorizonReached',verdict.reviewHorizonReached,'numericalStateQualified',true, ...
            'savedStageAccepted',endpoint.stageAccepted,'stopReason',stopReason, ...
            'registeredEquivalentTauIncrement',verdict.registeredEquivalentTauIncrement, ...
            'registeredAdditionalStepBudget',verdict.registeredAdditionalStepBudget);
        if isempty(links),links=link;else,links(end+1)=link;end %#ok<AGROW>
        current=next;currentFile=nextReview.checkpointFile;currentResult=endpoint.resultFile;currentReview=nextReview;
        clear next segmentSource a b
        found=strcmp(currentResult,targetResultFile);if found,break;end
    end
 end
 assert(found,'ipm:FreshChainGap','The explicit continuous native chain does not reach the requested paired result.');
 assert(all(usedBudgetAllowlist),'ipm:FreshChainBudgetAllowlist', ...
     'Every explicit budget-limited checkpoint must be an actual early maximum_steps link in this chain.');
 chain=struct('kind',registration.kind,'registrationFile',fullfile(outDir,'registration.json'), ...
    'baseQualificationFile',baseQualificationFile,'targetCheckpointFile',currentFile,'targetResultFile',currentResult, ...
    'targetReview',currentReview,'links',links,'cumulativeAbsolutePeakJump',cumulative, ...
    'allPassed',true,'originalLegacySmokePassed',false,'originalContinuousAuxiliaryPassed',true, ...
    'originalLegacyDecisionChanged',false,'parentNativeContinuationClaim',false,'noLU',true,'noPDE',true, ...
    'interpretation','Rechecked native lineage evidence for a future caller qualification; current frozen drivers are not changed.');
 write_json(fullfile(outDir,'chain_report.json'),chain);save(fullfile(outDir,'chain_report.mat'),'chain','contract','-v7.3');
 fprintf('FRESH_NATIVE_QUALIFICATION_CHAIN_PASS links=%d remesh=%d tau=%.12g\n',numel(links),current.payload.state.remeshCount,currentReview.parentEquivalentTau);
catch exception
 failure=struct('identifier',exception.identifier,'message',exception.message,'stack',exception.stack);
 write_json(fullfile(outDir,'chain_failure.json'),failure);rethrow(exception)
end
end

function [budget,increment]=campaign_budget(r,stage)
assert(isfield(r,'kind') && ischar(r.kind) && isfield(r,'maximumAdditionalStepsPerStage') && ...
    isa(r.maximumAdditionalStepsPerStage,'double') && isscalar(r.maximumAdditionalStepsPerStage) && ...
    isfield(r,'equivalentTauStep') && isequal(r.equivalentTauStep,.2), ...
    'ipm:FreshChainRegistration','Missing or changed campaign scheduling registration.');
increment=.2;
switch r.kind
    case {'independent_fresh_profile_campaign_v1','independent_fresh_profile_campaign_v2'}
        budget=512;
        assert(~isfield(r,'firstEquivalentTauStep'),'ipm:FreshChainRegistration', ...
            'Older campaign kinds do not register a shorter first interval.');
    case 'independent_fresh_profile_campaign_v3'
        budget=4096;
        assert(isfield(r,'firstEquivalentTauStep') && isa(r.firstEquivalentTauStep,'double') && ...
            isscalar(r.firstEquivalentTauStep) && isfinite(r.firstEquivalentTauStep) && ...
            r.firstEquivalentTauStep>0 && r.firstEquivalentTauStep<=.2, ...
            'ipm:FreshChainRegistration','Version 3 requires its explicit first positive interval at most .2.');
        if stage==1,increment=r.firstEquivalentTauStep;end
    otherwise
        error('ipm:FreshChainRegistration','Unknown campaign scheduling kind.');
end
assert(isequal(r.maximumAdditionalStepsPerStage,budget),'ipm:FreshChainRegistration', ...
    'The registered step budget must match the campaign version.');
end

function started=solve_registration(directory,stage)
lines=splitlines(fileread(fullfile(directory,'campaign_manifest.jsonl')));started=struct([]);
for k=1:numel(lines)
    if strlength(strtrim(lines(k)))==0,continue,end
    row=jsondecode(lines{k});
    if isfield(row,'event') && strcmp(row.event,'solve_started') && row.stage==stage
        assert(isempty(started),'ipm:FreshChainRegistration','Repeated solve_started entry at one stage.');
        started=row;
    end
end
assert(isscalar(started),'ipm:FreshChainRegistration','Missing original solve_started target registration.');
end

function verdict=verify_segment(r,k,sourceReview,endpoint,a,b,nextReview,contract,stopReason,cumulative,allowlist,started)
% Pure scheduling boundary. Field/axis/history/transaction qualification is
% performed by the caller before reaching this additional acceptance gate.
[budget,increment]=campaign_budget(r,k);
lambda=contract.lineage.canonicalCovarianceFactor;
targetLocal=a.scale.canonicalTime+increment/lambda;
targetEquivalent=contract.lineage.parentCanonicalTime+lambda*targetLocal;
tauDifference=lambda*(b.scale.canonicalTime-a.scale.canonicalTime);
assert(sourceReview.step==a.step && sourceReview.localCanonicalTime==a.scale.canonicalTime && ...
    sourceReview.localPhysicalTime==a.scale.physicalTime && ...
    sourceReview.parentEquivalentTau==contract.lineage.parentCanonicalTime+lambda*a.scale.canonicalTime && ...
    r.freshCanonicalStep==.2/lambda && ...
    endpoint.stage==k && endpoint.segmentSteps==b.step-a.step && endpoint.step==b.step && ...
    endpoint.localCanonicalTime==b.scale.canonicalTime && endpoint.localPhysicalTime==b.scale.physicalTime && ...
    endpoint.parentEquivalentTau==nextReview.parentEquivalentTau && strcmp(endpoint.stopReason,stopReason), ...
    'ipm:FreshChainRecordedEndpoint','Saved source/endpoint clocks, step counts or stop reason differ from actual native data.');
assert(strcmp(started.checkpointFile,endpoint.sourceCheckpoint) && ...
    started.targetLocalCanonicalTime==targetLocal && started.targetParentEquivalentTau==targetEquivalent && ...
    b.config.time.finalTime==targetLocal && endpoint.targetParentEquivalentTau==targetEquivalent && ...
    endpoint.parentEquivalentEndpointError==abs(nextReview.parentEquivalentTau-targetEquivalent) && ...
    b.config.time.maxSteps==a.step+budget, ...
    'ipm:FreshChainRegisteredTarget','Actual config and saved targets/budget must retain the original registered source horizon.');
assert(islogical(endpoint.stageAccepted) && isscalar(endpoint.stageAccepted) && ...
    b.step>a.step && b.step-a.step<=budget && all(nextReview.coreCells>=20) && nextReview.safety<.70 && ...
    abs(nextReview.cumulativeAbsolutePeakJump-cumulative)<=64*eps, ...
    'ipm:FreshChainEndpoint','Actual native segment violates original endpoint core/safety/jump or step gates.');
reached=abs(tauDifference-increment)<=1e-10 && strcmp(stopReason,'final_time') && endpoint.stageAccepted;
if ~reached
    assert(any(strcmp(allowlist,nextReview.checkpointFile)) && strcmp(stopReason,'maximum_steps') && ...
        ~endpoint.stageAccepted && b.step==b.config.time.maxSteps && b.step==a.step+budget && ...
        tauDifference>0 && tauDifference<increment && b.scale.canonicalTime<targetLocal, ...
        'ipm:FreshChainBudgetEndpoint', ...
        'Only an explicitly listed, fully exhausted maximum_steps endpoint before its unchanged target may qualify as a partial link.');
end
verdict=struct('reviewHorizonReached',reached,'numericalStateQualified',true, ...
    'savedStageAccepted',endpoint.stageAccepted,'stopReason',stopReason, ...
    'registeredEquivalentTauIncrement',increment,'registeredAdditionalStepBudget',budget);
end

function report=verify_transaction(old,new,auditFile,priorJump,contract)
a=old.payload.state;b=new.payload.state;h=new.payload.log.history;
assert(b.step==a.step && b.normalizedTime==a.normalizedTime && isequaln(a.scale,b.scale) && ...
    b.remeshCount==a.remeshCount+1 && strcmp(a.runMetadata.caseId,b.runMetadata.caseId) && ...
    isequaln(b.runMetadata.caseMetadata.latePhysicalBoxBranch,contract.lineage) && ...
    isequal(a.baseX,b.baseX) && isequal(a.baseY,b.baseY) && isequal(a.mass0,b.mass0) && isequal(a.rhoRange0,b.rhoRange0) && ...
    isequaln(rmfield(b.rescaling,{'originIndex','pinIndex'}),contract.runtimeReferences), ...
    'ipm:FreshChainTransaction','A transaction changed step, clocks, scales, lineage, base axes or reference values.');
[~,actualOriginIndex]=min(abs(b.x));[~,actualPinIndex]=min(abs(b.x-b.rescaling.pinX));
assert(numel(b.x)==895 && numel(b.y)==386 && isequal(b.x([1,end]),a.x([1,end])) && ...
    isequal(b.y([1,end]),a.y([1,end])) && any(b.x==contract.lineage.physicalAnchorX) && ...
    any(b.x==-contract.lineage.physicalAnchorX) && ...
    b.rescaling.originIndex==actualOriginIndex && b.rescaling.pinIndex==actualPinIndex);
for domain={'physics','transport','elliptic','scaling','remesh','diagnostics','time'}
    assert(fresh_profile_value_equal(a.config.(domain{1}),b.config.(domain{1})), ...
        'ipm:FreshChainTransaction','A transaction changed a numerical specification or captured physical data.');
end
fresh_profile_history_prefix(old.payload.log.history,h,true);
assert(all(ipm.output.trustedMask(h,b.config)));
qx=ipm.mesh.quadrature(b.x);qy=ipm.mesh.quadrature(b.y);qualityX=ipm.mesh.quality(b.x,7,qx);qualityY=ipm.mesh.quality(b.y,7,qy);
assert(hard_quality(qualityX) && hard_quality(qualityY));
oldOmega=a.rho*ipm.mesh.fdMatrix(a.x,1,7)';newOmega=b.rho*ipm.mesh.fdMatrix(b.x,1,7)';
oldMaximum=max(abs(oldOmega),[],'all');newMaximum=max(abs(newOmega),[],'all');jump=abs(newMaximum-oldMaximum)/max(oldMaximum,eps);
oldWeights=ipm.mesh.quadrature(a.y)*ipm.mesh.quadrature(a.x);newWeights=qy*qx;
oldMass=sum(a.rho.*oldWeights,'all');newMass=sum(b.rho.*newWeights,'all');mass=abs(newMass-oldMass)/max(abs(oldMass),eps);
lo=min(a.rho,[],'all');hi=max(a.rho,[],'all');range=max([lo-min(b.rho,[],'all'),max(b.rho,[],'all')-hi,0])/max([hi-lo,abs(lo),abs(hi),eps]);
r=b.rescaling;wall=ipm.diagnostics.measureFeatures(newOmega(1,:),b.x,r.adaptiveLevels,abs(b.x-r.pinX)<=r.peakTrackingHalfWidth);
vertical=ipm.diagnostics.measureFeatures(abs(newOmega(:,wall.peakIndex))',b.y',r.adaptiveLevels,[]);
cores=[wall.gridPoints(end),vertical.gridPoints(end)];
snapshot=struct('datasetIndex',1,'sourceLabel','native transaction recheck','trusted',true,'rho',b.rho,'x',b.x,'y',b.y, ...
    'canonicalTime',b.scale.canonicalTime,'physicalTime',b.scale.physicalTime, ...
    'scale',struct('Cx',exp(b.scale.logC_l),'Cy',exp(b.scale.logC_l),'Comega',exp(b.scale.logC_omega)));
dataset=struct('schemaVersion',2,'kind','ipm_frozen_grid_dataset','tag','chain_native_transaction', ...
    'snapshotCount',1,'snapshots',snapshot,'xLimits',b.x([1,end]),'yLimits',b.y([1,end])');
limits=struct('maxAdjacentCellRatio',1.08,'maxLogSpacingCurvature',.01,'minStencilRcond',1e-9,'minQuadratureWeightRatio',1e-8);
score=ipm_gridlab_score_frozen_pair(dataset,b.x,b.y,struct('trustedOnly',true,'meshLimits',limits));
assert(score.admissible);front=score.aggregate.minimumXLeftFrontCells;
loaded=load(auditFile,'audit');saved=loaded.audit;
assert(saved.limits.minimumXCoreCells>=31 && saved.limits.minimumYCoreCells>=31 && ...
    saved.limits.maximumRhoXRelativeChange<=.002 && saved.limits.maximumMassRelativeDefect<=5e-12 && ...
    saved.limits.maximumRelativeRangeViolation<=2e-4, ...
    'ipm:FreshChainTransaction','Saved transaction admission floors were weaker than the registered campaign.');
measured=[cores,jump,mass,range,front];recorded=[saved.xCoreCells,saved.yCoreCells,saved.rhoXMaximumRelativeChange, ...
    saved.massRelativeDefect,saved.relativeRangeViolation,saved.actualLeftFrontCells];
assert(all(abs(measured-recorded)<=64*eps(max(1,abs(recorded)))) && ...
    all(abs(cores-[h.mesh.coreGridPoints(end),h.mesh.verticalCoreGridPoints(end)])<=64*eps(max(1,cores))) && ...
    all(cores>=31) && front>=20 && jump<=.002 && mass<=5e-12 && range<=2e-4 && priorJump+jump<=.02, ...
    'ipm:FreshChainTransaction','Recomputed native transaction metrics disagree or violate original gates.');
records=b.runMetadata.gridLabRegrids;assert(numel(records)==b.remeshCount && ...
    fresh_profile_value_equal(records(1:end-1),a.runMetadata.gridLabRegrids) && ...
    abs(records(end).rhoXMaximumRelativeChange-jump)<=64*eps, ...
    'ipm:FreshChainTransaction','Native appended transaction provenance is incomplete or inconsistent.');
report=struct('applied',true,'nativeStepAndScalesUnchanged',true,'historyOnlyTerminalRecordReplaced',true, ...
    'nativeCoreCellsRecomputed',cores,'nativeLeftFrontRecomputed',front,'peakJumpRecomputed',jump, ...
    'massDefectRecomputed',mass,'rangeViolationRecomputed',range,'cumulativeAbsolutePeakJump',priorJump+jump, ...
    'allOriginalGatesPassed',true,'savedAuditAndNativeHistoryMatchRecomputation',true,'xQuality',qualityX,'yQuality',qualityY);
end
function passed=hard_quality(q)
passed=q.maximumAdjacentCellRatio<=1.08 && q.maximumLogSpacingCurvature<=.01 && q.minimumStencilRcond>=1e-9 && ...
    q.minimumQuadratureWeightRatio>=1e-8 && q.quadratureWeightsStrictlyPositive && ...
    q.minimumQuadratureWeightToControlWidthRatio>=.35 && q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
