function [review,checkpoint,contract]=fresh_profile_campaign_review(resultFile,initialDataFile,contract)
%FRESH_PROFILE_CAMPAIGN_REVIEW Native/paired/lineage audit and no-LU decision.
% Parent-equivalent tau is a coordinate label, never inherited parent history.
if nargin<3,contract=[];end
assert(maxNumCompThreads==10,'Native signatures require the original ten threads.');
result=ipm.output.validate(resultFile);
checkpointFile=char(result.metadata.latestCheckpointFile);
checkpoint=ipm.output.readCheckpoint(checkpointFile);s=checkpoint.payload.state;h=checkpoint.payload.log.history;
assert(all(ipm.output.trustedMask(result)) && all(ipm.output.trustedMask(h,s.config)), ...
    'ipm:FreshCampaignTrusted','Entire native and result histories must be trusted.');
assert(isequal(s.rho,result.state.rho) && isequal(s.x(:),result.grid.x(:)) && ...
    isequal(s.y(:),result.grid.y(:)) && s.step==result.state.steps && ...
    s.normalizedTime==result.state.normalizedTime && s.scale.canonicalTime==result.state.canonicalTime && ...
    s.scale.physicalTime==result.state.physicalTime && strcmp(s.runMetadata.caseId,result.metadata.caseId) && ...
    isequaln(h,result.history),'ipm:FreshCampaignPair','Native state, all clocks and full history must pair exactly with result.');
assert(exp(s.scale.logC_l)==result.scale.Cx && result.scale.Cy==result.scale.Cx && ...
    exp(s.scale.logC_omega)==result.scale.Comega && s.scale.X_shift==result.scale.Xshift && ...
    result.grid.remeshCount==s.remeshCount && ...
    isequal(exp(-s.scale.logC_omega)*s.rho,result.physical.rho) && ...
    isequal((s.x-s.scale.X_shift)/exp(s.scale.logC_l),result.physical.x) && ...
    isequal(s.y/exp(s.scale.logC_l),result.physical.y) && ...
    isequaln(checkpoint.payload.log.snapshotRho,result.snapshots.rho) && ...
    isequaln(checkpoint.payload.log.snapshotX,result.snapshots.x) && ...
    isequaln(checkpoint.payload.log.snapshotY,result.snapshots.y) && ...
    fresh_profile_value_equal(s.config,result.config), ...
    'ipm:FreshCampaignPair','Native scales, physical samples, paired snapshots and complete configuration must match result.');
assert(numel(s.x)==895 && numel(s.y)==386 && isequal(size(s.rho),[386,895]) && ...
    ~s.config.remesh.adaptiveRemesh && ~s.config.remesh.initialAnalyticRemesh && ...
    s.config.schemaVersion==4 && strcmp(s.config.scaling.dynamicScaleGeometry,'isotropic') && ...
    strcmp(s.config.scaling.lengthGauge,'transport_anchor') && ...
    strcmp(s.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak') && s.scale.X_shift==0, ...
    'ipm:FreshCampaignContract','The registered 895x386 exact fresh-box contract is required.');
lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
assert(strcmp(lineage.kind,'fresh_late_physical_initial_value_branch') && ...
    ~lineage.parentHistoryInherited && ~lineage.parentCheckpointModified && ...
    ~strcmp(s.runMetadata.caseId,lineage.parentCaseId) && h.common.acceptedStep(1)==0 && ...
    h.common.physicalTime(1)==0 && h.common.canonicalTau(1)==0, ...
    'ipm:FreshCampaignLineage','A genuine fresh case with its own zero-time history is required.');
if isempty(contract)
    initial=load(initialDataFile,'physicalX','physicalY','physicalRho','lineage');
    parent=ipm.output.readCheckpoint(lineage.parentCheckpoint);p=parent.payload.state;
    assert(isequaln(initial.lineage,lineage) && strcmp(p.runMetadata.caseId,lineage.parentCaseId) && ...
        p.step==lineage.parentStep && p.scale.canonicalTime==lineage.parentCanonicalTime && ...
        p.scale.physicalTime==lineage.absolutePhysicalEpoch && exp(p.scale.logC_l)==lineage.parentCx && ...
        exp(p.scale.logC_omega)==lineage.parentComega && ...
        isequal(initial.physicalX,p.x(lineage.initialNodeIndicesX)/lineage.parentCx) && ...
        isequal(initial.physicalY,p.y(lineage.initialNodeIndicesY)/lineage.parentCx) && ...
        isequal(initial.physicalRho,exp(-p.scale.logC_omega)*p.rho(lineage.initialNodeIndicesY,lineage.initialNodeIndicesX)), ...
        'ipm:FreshCampaignInitialData','Immutable fresh initial samples must reconstruct exactly from the native parent.');
    descriptor=functions(s.config.physics.initialCondition);
    assert(isfield(descriptor,'workspace') && isscalar(descriptor.workspace));
    captured=descriptor.workspace{1};
    assert(all(isfield(captured,{'physicalX','physicalY','physicalRho'})) && ...
        isequal(captured.physicalX,initial.physicalX) && isequal(captured.physicalY,initial.physicalY) && ...
        isequal(captured.physicalRho,initial.physicalRho), ...
        'ipm:FreshCampaignInitialData','The initial-condition closure must capture the exact immutable fresh samples.');
    assert(lineage.canonicalCovarianceFactor==lineage.parentCx/lineage.parentComega && ...
        lineage.physicalAnchorX==p.config.scaling.transportAnchorX/lineage.parentCx);
    contract=struct('caseId',char(s.runMetadata.caseId),'lineage',lineage,'initialDataFile',initialDataFile, ...
        'initialX',initial.physicalX(:)','initialY',initial.physicalY(:), ...
        'runtimeReferences',rmfield(s.rescaling,{'originIndex','pinIndex'}), ...
        'transport',s.config.transport,'physics',s.config.physics,'elliptic',s.config.elliptic, ...
        'scaling',s.config.scaling,'remesh',s.config.remesh,'diagnostics',s.config.diagnostics, ...
        'timeNumerics',rmfield(s.config.time,{'finalTime','physicalFinalTime','maxSteps'}), ...
        'CFL',s.config.time.cfl,'maxDt',s.config.time.maxDt,'minDt',s.config.time.minDt);
end
assert(strcmp(initialDataFile,contract.initialDataFile) && strcmp(s.runMetadata.caseId,contract.caseId) && isequaln(lineage,contract.lineage) && ...
    isequal(s.baseX(:),contract.initialX(:)) && isequal(s.baseY(:),contract.initialY(:)) && ...
    isequal(s.x([1,end]),contract.initialX([1,end])) && isequal(s.y([1,end]),contract.initialY([1,end])) && ...
    s.config.scaling.transportAnchorX==lineage.physicalAnchorX && ...
    any(s.x==lineage.physicalAnchorX) && any(s.x==-lineage.physicalAnchorX) && ...
    isequaln(rmfield(s.rescaling,{'originIndex','pinIndex'}),contract.runtimeReferences), ...
    'ipm:FreshCampaignInvariant','Fresh case, fixed domain/base axes, exact anchor and reference values must be preserved.');
for name={'transport','physics','elliptic','scaling','remesh','diagnostics'}
    assert(fresh_profile_value_equal(s.config.(name{1}),contract.(name{1})),'ipm:FreshCampaignNumerics','A frozen numerical/physical contract changed.');
end
assert(fresh_profile_value_equal(rmfield(s.config.time,{'finalTime','physicalFinalTime','maxSteps'}),contract.timeNumerics) && ...
    s.config.time.cfl==contract.CFL && s.config.time.maxDt==contract.maxDt && s.config.time.minDt==contract.minDt, ...
    'ipm:FreshCampaignNumerics','CFL and timestep bounds must not change.');
assert(all(isfinite(result.physical.rho),'all') && all(isfinite(result.physical.rhoX),'all') && ...
    all(isfinite(result.physical.rhoY),'all'),'ipm:FreshCampaignFinite','Physical fields must be finite.');
qualityX=axis_quality(s.x);qualityY=axis_quality(s.y);
assert(all(h.mesh.coreGridPoints>=14) && all(h.mesh.verticalCoreGridPoints>=14) && ...
    all(h.mesh.safetyFactor<.70),'ipm:FreshCampaignHistoryFloor','Full history must satisfy core14/safety.70.');
lambda=lineage.canonicalCovarianceFactor;equivalent=lineage.parentCanonicalTime+lambda*h.common.canonicalTau(:);
mask=h.mesh.remeshCount(:)==s.remeshCount & equivalent>=equivalent(end)-.35;
cores=[h.mesh.coreGridPoints(end),h.mesh.verticalCoreGridPoints(end)];
trendAvailable=nnz(mask)>=4 && max(equivalent(mask))-min(equivalent(mask))>64*eps(max(1,equivalent(end)));
decay=[0,0];
if trendAvailable
    time=equivalent(mask)-equivalent(end);
    for k=1:2
        names={'coreGridPoints','verticalCoreGridPoints'};v=h.mesh.(names{k})(:);
        assert(all(isfinite(v(mask))) && all(v(mask)>0));fit=polyfit(time,log(v(mask)),1);decay(k)=max(0,-fit(1));
    end
end
predicted=cores.*exp(-.2*decay);jump=cumulative_jump(s);
review=struct('resultFile',char(resultFile),'checkpointFile',checkpointFile,'caseId',char(s.runMetadata.caseId), ...
    'step',s.step,'localCanonicalTime',s.scale.canonicalTime,'localPhysicalTime',s.scale.physicalTime, ...
    'absolutePhysicalTime',lineage.absolutePhysicalEpoch+s.scale.physicalTime, ...
    'parentEquivalentTau',lineage.parentCanonicalTime+lambda*s.scale.canonicalTime, ...
    'equivalentTauDefinition','parent epoch tau + lambda0 * fresh local canonical time; no parent history inherited', ...
    'equivalentTauStep',.2,'localCanonicalStep',.2/lambda,'coreCells',cores,'safety',h.mesh.safetyFactor(end), ...
    'trendAvailable',trendAvailable,'trendRecords',nnz(mask),'sameRemeshTrendSpan',max(equivalent(mask))-min(equivalent(mask)), ...
    'nonnegativeCoreDecayPerEquivalentTau',decay,'predictedEndpointCoreCells',predicted, ...
    'predictionInterpretation','When unavailable, zero decay is only an explicitly marked planning fallback, not evidence of constant core.', ...
    'regridRequired',min(cores)<26 || (trendAvailable && min(predicted)<22), ...
    'cumulativeAbsolutePeakJump',jump,'xAxisQuality',qualityX,'yAxisQuality',qualityY, ...
    'minimumHistoryCoreCells',[min(h.mesh.coreGridPoints),min(h.mesh.verticalCoreGridPoints)], ...
    'maximumHistorySafety',max(h.mesh.safetyFactor),'physicalGradientMaximum',h.common.physicalRhoXInf(end), ...
    'physicalQuadraticPeak',h.common.physicalQuadraticPeak(end), ...
    'cLFreshUnits',h.common.c_l(end),'cOmegaFreshUnits',h.common.c_omega(end), ...
    'cLParentUnits',h.common.c_l(end)/lambda,'cOmegaParentUnits',h.common.c_omega(end)/lambda, ...
    'logLengthRatePerPhysicalTime',h.common.c_l(end)*exp(s.scale.logC_l-s.scale.logC_omega), ...
    'logAmplitudeRatePerPhysicalTime',h.common.c_omega(end)*exp(s.scale.logC_l-s.scale.logC_omega), ...
    'nativeAndResultEntireHistoryTrusted',true,'nativeResultStateClocksAndHistoryExactlyPaired',true, ...
    'freshLineagePreserved',true,'initialConditionCapturedSamplesExactlyPaired',true, ...
    'nativeResultScalesPhysicalSamplesSnapshotsAndConfigExactlyPaired',true,'parentNativeContinuationClaim',false,'noEllipticOperatorsBuilt',true);
assert(all(isfinite(cores)) && all(cores>=14) && isfinite(review.safety) && review.safety<.70 && jump<=.02, ...
    'ipm:FreshCampaignReview','Fresh state violates native core14/safety.70 or cumulative jump limits.');
end

function total=cumulative_jump(s)
if isfield(s.runMetadata,'gridLabRegrids')
    records=s.runMetadata.gridLabRegrids;assert(numel(records)==s.remeshCount,'ipm:FreshCampaignJump','Missing remesh provenance.');
    jumps=[records.rhoXMaximumRelativeChange];assert(all(isfinite(jumps)) && all(jumps>=0) && all(jumps<=.002));total=sum(abs(jumps));
else
    assert(s.remeshCount==0,'ipm:FreshCampaignJump','Missing inherited remesh provenance.');total=0;
end
end

function q=axis_quality(axis)
q=ipm.mesh.quality(axis,7,ipm.mesh.quadrature(axis));
assert(q.maximumAdjacentCellRatio<=1.08 && q.maximumLogSpacingCurvature<=.01 && ...
    q.minimumStencilRcond>=1e-9 && q.minimumQuadratureWeightRatio>=1e-8 && ...
    q.quadratureWeightsStrictlyPositive && q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65, ...
    'ipm:FreshCampaignAxis','Current axes must retain every registered hard mesh gate.');
end
