function report=measure_continuous_amplitude_width_index(cacheFile,outputFile)
%MEASURE_CONTINUOUS_AMPLITUDE_WIDTH_INDEX Retain measured inner-shape drift.
% Temporal scale index of an integrated gradient reconstruction, not a spatial
% Holder exponent. The density endpoint reconstruction defect is also saved.
assert(maxNumCompThreads==10 && ~isfile(outputFile));
d=load(cacheFile,'Omega','FX','x','y','Dx','Dy','scale','nativeRates','cacheAudit');
a=d.cacheAudit;assert(a.rhsCachePairedExactly && a.extraTimeSteps==0);
cp=ipm.output.readCheckpoint(a.sourceCheckpoint);s=cp.payload.state;
assert(all(ipm.output.trustedMask(cp.payload.log.history,s.config)) && ...
    isequaln(s.scale,d.scale) && isequal(s.x,d.x) && isequal(s.y,d.y) && ...
    isequal(d.Dx,ipm.mesh.fdMatrix(s.x,1,7)) && isequal(d.Dy,ipm.mesh.fdMatrix(s.y,1,7)) && ...
    isequal(d.Omega,s.rho*d.Dx'));
lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
assert(isequaln(a.lineage,lineage) && lineage.canonicalCovarianceFactor>0);
factor=lineage.canonicalCovarianceFactor;window=[0,2*lineage.physicalAnchorX];
r=ipm_accellab_continuous_inner_rates(d.Omega,d.FX,d.x,d.y,d.Dx,d.Dy,window);assert(r.valid);
widthRate=r.logScaleXRate-d.nativeRates(1);
peakRate=r.peakPrime/r.peak.value+d.nativeRates(1)-d.nativeRates(2);
assert(widthRate<0);
halfWidths=[.25,.5,1,2];records=cell(size(halfWidths));
for k=1:numel(halfWidths)
    b=halfWidths(k);[xi,w]=split_gauss((d.x-r.peak.x)/r.wallCoreWidth,[-b,b]);
    QX=r.peak.x+r.wallCoreWidth*xi;QY=zeros(size(QX));
    o=ipm_accellab_tensor_hermite(d.Omega,d.x,d.y,d.Dx,d.Dy,QX,QY);
    f=ipm_accellab_tensor_hermite(d.FX,d.x,d.y,d.Dx,d.Dy,QX,QY);
    U=o.value/r.peak.value;
    G=f.value/r.peak.value-r.peakPrime/r.peak.value*U+ ...
        (r.translationRate+r.wallCoreWidthPrime*xi).*o.derivativeX/r.peak.value;
    A=sum(w.*U);Aprime=sum(w.*G);assert(A>0);
    densityQueries=r.peak.x+r.wallCoreWidth*[-b,b];
    q=ipm_accellab_tensor_hermite(s.rho,d.x,d.y,d.Dx,d.Dy,densityQueries,[0,0]);
    reconstructed=r.peak.value*r.wallCoreWidth*A/exp(d.scale.logC_omega);
    endpointDifference=diff(q.value)/exp(d.scale.logC_omega);
    shapeRate=Aprime/A;
    uncorrected=1+peakRate/widthRate;corrected=uncorrected+shapeRate/widthRate;
    records{k}=struct('innerInterval',[-b,b],'shapeIntegral',A,'shapeIntegralPrimeFresh',Aprime, ...
        'logShapeIntegralRateParent',shapeRate/factor,'logPhysicalWidthRateParent',widthRate/factor, ...
        'logPhysicalPeakRateParent',peakRate/factor, ...
        'logReconstructedDensityIncrementRateParent',(peakRate+widthRate+shapeRate)/factor, ...
        'indexAssumingConstantShapeIntegral',uncorrected,'indexIncludingMeasuredShapeDrift',corrected, ...
        'shapeDriftIndexCorrection',shapeRate/widthRate,'integratedPhysicalGradientIncrement',reconstructed, ...
        'physicalDensityEndpointDifference',endpointDifference, ...
        'densityReconstructionRelativeDefect',abs(reconstructed-endpointDifference)/abs(endpointDifference), ...
        'quadratureNodes',numel(xi),'quadratureIntervalMeasureError',abs(sum(w)-2*b));
end
report=struct('kind','instantaneous_temporal_amplitude_width_index_with_shape_drift', ...
    'cacheFile',cacheFile,'sourceCheckpoint',a.sourceCheckpoint,'step',s.step, ...
    'parentEquivalentTau',lineage.parentCanonicalTime+factor*d.scale.canonicalTime, ...
    'absolutePhysicalTime',lineage.absolutePhysicalEpoch+d.scale.physicalTime, ...
    'nativeSignatureValidated',true,'nativeOmegaAndCachePairedExactly',true,'geometry',r,'records',[records{:}], ...
    'formula','Delta_rho_reconstructed = P*wx/Comega*A; alpha_time = 1 + (cl-cw+Pprime/P + Aprime/A)/(beta-cl).', ...
    'pdeAdvanced',false,'newRhsEvaluations',0,'newPoissonOperators',0,'spatialHolderExponentClaim',false, ...
    'interpretation','Instantaneous temporal scale ratio on moving inner intervals. It includes actual shape-integral drift and compares integrated gradient with the native density reconstruction. It is not a limiting spatial regularity exponent or a singularity-time fit.');
fid=fopen(outputFile,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end

function [q,w]=split_gauss(native,ends)
edges=unique([ends,native(native>ends(1) & native<ends(2))]);
z=[-sqrt((3+2*sqrt(6/5))/7),-sqrt((3-2*sqrt(6/5))/7), ...
    sqrt((3-2*sqrt(6/5))/7),sqrt((3+2*sqrt(6/5))/7)];
a=[(18-sqrt(30))/36,(18+sqrt(30))/36,(18+sqrt(30))/36,(18-sqrt(30))/36];
nodes=(edges(1:end-1)'+edges(2:end)')/2+diff(edges)'*z/2;
weights=diff(edges)'*a/2;q=nodes(:)';w=weights(:)';
end
