function candidate=mesh_anchor_grid_candidate(dataset,reference,anchor,outputFile,controls)
%MESH_ANCHOR_GRID_CANDIDATE Dimensionless design, complete real-unit scoring.
% reference.x/y are the actual immutable initial axes of this fresh branch.
% Any resampling is a declared candidate reference, never a historical axis.
if nargin<5,controls=struct();end
assert(~isfile(outputFile));
defaults=struct('nodeCountX',[],'nodeCountY',[],'targetXCoreCells',24, ...
    'targetYCoreCells',24,'minimumXFrontCells',20,'positiveFineCells',96, ...
    'anchorFineCellFraction',.85,'roundingCells',40,'resolutionPadding',1.10, ...
    'verticalResolutionPadding',1.15,'yEqualizationSigma',.25);
assert(isstruct(controls) && isscalar(controls) && isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
for name=fieldnames(defaults)'
    if ~isfield(controls,name{1}),controls.(name{1})=defaults.(name{1});end
end
validateattributes(anchor,{'numeric'},{'scalar','finite','positive'});
assert(dataset.schemaVersion==2 && all([dataset.snapshots.trusted]));
assert(isfield(reference,'kind') && isfield(reference,'provenance'));
assert(isequal(reference.x([1,end]),dataset.xLimits) && ...
    isequal(reference.y([1,end])',dataset.yLimits));
if isempty(controls.nodeCountX),controls.nodeCountX=numel(dataset.snapshots(1).x);end
if isempty(controls.nodeCountY),controls.nodeCountY=numel(dataset.snapshots(1).y);end
for name={'nodeCountX','nodeCountY','targetXCoreCells','targetYCoreCells','minimumXFrontCells'}
    validateattributes(controls.(name{1}),{'numeric'},{'scalar','integer','positive'});
end
assert(mod(controls.nodeCountX,2)==1 && controls.nodeCountY>=9);
validateattributes(controls.resolutionPadding,{'numeric'},{'scalar','finite','>=',1});
validateattributes(controls.verticalResolutionPadding,{'numeric'},{'scalar','finite','>=',1});
limits=struct('maxAdjacentCellRatio',1.08,'maxLogSpacingCurvature',.01, ...
    'minStencilRcond',1e-9,'minQuadratureWeightRatio',1e-8);
profiles=ipm_gridlab_feature_profiles(dataset);records=profiles.records;
core=[records.safetyCoreWidthLeft]+[records.safetyCoreWidthRight];front=2*[records.leftFrontHalfWidth];
spacing=min([core/controls.targetXCoreCells,front/controls.minimumXFrontCells])/controls.resolutionPadding;
[x,xInfo]=mesh_general_rounded_axis(anchor,dataset.xLimits(2),controls.nodeCountX, ...
    spacing,controls.positiveFineCells,controls.anchorFineCellFraction,controls.roundingCells);
referenceYNormalized=double(reference.y(:))/anchor;
if controls.nodeCountY==numel(reference.y)
    derivedYNormalized=referenceYNormalized;
else
    derivedYNormalized=interp1(linspace(0,1,numel(reference.y)),referenceYNormalized, ...
        linspace(0,1,controls.nodeCountY)','pchip');
end
derivedYNormalized(1)=0;derivedYNormalized(end)=referenceYNormalized(end);
equalization=struct('geometry','positive','focusCenters',0,'sigma',controls.yEqualizationSigma, ...
    'power',2,'meshLimits',limits);
[yn,yInfo]=ipm_gridlab_equalize_axis(derivedYNormalized, ...
    [zeros(numel(records),1),[records.yCoreWidth]'/anchor], ...
    repmat(controls.targetYCoreCells*controls.verticalResolutionPadding,numel(records),1),equalization);
y=yn(:)*anchor;y(1)=reference.y(1);y(end)=reference.y(end);
scoreOptions=struct('trustedOnly',true,'profiles',profiles,'meshLimits',limits, ...
    'minimumXCoreCells',controls.targetXCoreCells,'minimumYCoreCells',controls.targetYCoreCells, ...
    'minimumXFrontCells',controls.minimumXFrontCells,'targets',struct('rhoXMaximumRelativeChange',2e-3));
score=ipm_gridlab_score_frozen_pair(dataset,x,y,scoreOptions);
localPassed=local_quality(score.quality.x) && local_quality(score.quality.y);
resolutionPassed=false;transferPassed=false;
if score.admissible && ~isempty(fieldnames(score.aggregate))
    a=score.aggregate;
    resolutionPassed=a.minimumXCoreCells>=controls.targetXCoreCells-1e-6 && ...
        a.minimumYCoreCells>=controls.targetYCoreCells-1e-6 && ...
        a.minimumXLeftFrontCells>=controls.minimumXFrontCells-1e-6;
    transferPassed=a.worst.rhoXMaximumRelativeChange<=2e-3 && ...
        a.worst.conservationRelativeDefect<=5e-12 && a.worst.relativeRangeViolation<=2e-4;
end
sameCount=all(arrayfun(@(s)numel(s.x)==numel(x) && numel(s.y)==numel(y),dataset.snapshots));
anchorPassed=any(x==anchor) && any(x==-anchor);
candidate=struct('kind','fresh_branch_arbitrary_anchor_grid_candidate','controls',controls, ...
    'candidateX',x,'candidateY',y,'anchorPosition',anchor,'anchorExact',anchorPassed, ...
    'reference',reference,'referenceYResampledForBudget',numel(reference.y)~=numel(y), ...
    'derivedYReference',derivedYNormalized*anchor,'referenceMapUnits','actual fresh computational units', ...
    'profiles',profiles,'xConstruction',xInfo,'yEqualization',yInfo,'pairScore',score, ...
    'completePairScoredInOriginalUnits',true,'localQuadraturePassed',localPassed, ...
    'frozenTransferIsProductionTransaction',false, ...
    'resolutionPassed',resolutionPassed,'transferPassed',transferPassed, ...
    'frozenCandidatePassed',score.admissible && localPassed && resolutionPassed && transferPassed && anchorPassed, ...
    'currentTransactionNodeCountSupported',sameCount,'checkpointRegridCommitted',false, ...
    'pdeAdvanced',false,'historicalFactoryReproductionClaim',false);
candidate.transactionReady=candidate.frozenCandidatePassed && sameCount;
candidate.transactionInterpretation='Eligible for an independent native transaction test; frozen pair transfer is not the production bubble correction and does not establish actual transferred core or PDE accuracy.';
save(outputFile,'candidate','-v7.3');
fprintf('FRESH_ANCHOR_GRID nodes=%d/%d anchor=%.12g frozen=%d nativeCountSupported=%d\n', ...
    numel(x),numel(y),anchor,candidate.frozenCandidatePassed,sameCount);
end

function passed=local_quality(q)
passed=q.quadratureWeightsStrictlyPositive && ...
    q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
