function [report,result]=mesh_fresh_box_branch(sourceFile,fraction,elapsedPhysicalTime,outputDirectory,controls)
%MESH_FRESH_BOX_BRANCH New late-state initial-value problem in physical units.
% No parent history or checkpoint payload is modified or inherited. New
% native history starts at time zero; the parent's physical epoch is separate.
if nargin<5,controls=struct();end
defaults=struct('dtScale',1,'wenoEpsilon',[],'maximumSteps',2000,'allowLarge',false);
assert(isstruct(controls) && isscalar(controls) && isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
names=fieldnames(defaults);
for k=1:numel(names)
    if ~isfield(controls,names{k}),controls.(names{k})=defaults.(names{k});end
end
validateattributes(fraction,{'numeric'},{'scalar','finite','positive','<=',1});
validateattributes(elapsedPhysicalTime,{'numeric'},{'scalar','finite','positive'});
validateattributes(controls.dtScale,{'numeric'},{'scalar','finite','positive','<=',1});
assert(~isfolder(outputDirectory),'Refusing to replace a fresh branch.');
originalThreads=maxNumCompThreads(10); cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
cp=ipm.output.readCheckpoint(sourceFile); state=cp.payload.state;
assert(strcmp(state.config.transport.spatialDiscretization,'high_order') && ...
    strcmp(state.config.transport.transportScheme,'weno5_fd') && ...
    strcmp(state.config.scaling.dynamicScaleGeometry,'isotropic') && ...
    strcmp(state.config.scaling.lengthGauge,'transport_anchor') && ...
    strcmp(state.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak') && ...
    strcmp(state.config.physics.symmetryMode,'double_odd_omega') && state.scale.X_shift==0, ...
    'This physical restart requires the isotropic quadratic/anchor, zero-shift contract.');
assert(controls.allowLarge || numel(state.rho)<=20000, ...
    'Large fresh branches require an explicitly allocated computation window.');
Cx=exp(state.scale.logC_l); Comega=exp(state.scale.logC_omega); lambda=Cx/Comega;
x=state.x(:)';y=state.y(:);
xi=find(abs(x)<=fraction*max(abs(x)));yi=find(y<=fraction*max(y));
assert(numel(xi)>=9 && numel(yi)>=9 && mod(numel(xi),2)==1 && ...
    nnz(x(xi)>1.5)>=3 && nnz(y(yi)>1)>=3, ...
    'Keep the complete comparison core and outer stencil margins.');
physicalX=x(xi)/Cx;physicalY=y(yi)/Cx;
physicalRho=exp(-state.scale.logC_omega)*state.rho(yi,xi);
opts=flat_options(state.config);
opts.customX=physicalX;opts.customY=physicalY;opts.nx=numel(xi);opts.ny=numel(yi);
opts.xlim=physicalX([1,end]);opts.ymax=physicalY(end);
opts.gridStretchAutomatic=false;opts.targetCenterSpacing=opts.targetCenterSpacing/Cx;
opts.transportAnchorX=state.config.scaling.transportAnchorX/Cx;
opts.omegaGaugeWindowRadius=opts.omegaGaugeWindowRadius/Cx;
opts.initialCondition=@(X,Y)paired_samples(X,Y,physicalX,physicalY,physicalRho);
opts.finalTime=Inf;opts.physicalFinalTime=elapsedPhysicalTime;
opts.maxDt=state.config.time.maxDt/lambda*controls.dtScale;
opts.minDt=state.config.time.minDt/lambda*controls.dtScale;
opts.maxSteps=controls.maximumSteps;
opts.outputEvery=min(state.config.time.outputEvery/lambda,elapsedPhysicalTime);
opts.adaptiveRemesh=false;opts.initialAnalyticRemesh=false;
if ~isempty(controls.wenoEpsilon),opts.wenoEpsilon=controls.wenoEpsilon;end
lineage=struct('kind','fresh_late_physical_initial_value_branch', ...
    'parentCheckpoint',sourceFile,'parentCaseId',char(state.runMetadata.caseId), ...
    'parentStep',state.step,'parentCanonicalTime',state.scale.canonicalTime, ...
    'absolutePhysicalEpoch',state.scale.physicalTime,'boxFraction',fraction, ...
    'parentCx',Cx,'parentComega',Comega,'canonicalCovarianceFactor',lambda, ...
    'physicalAnchorX',opts.transportAnchorX, ...
    'runtimeReferences','freshly_initialized_explicitly_not_inherited', ...
    'parentHistoryInherited',false,'parentCheckpointModified',false, ...
    'initialNodeIndicesX',xi,'initialNodeIndicesY',yi, ...
    'actualPhysicalXLimits',opts.xlim,'actualPhysicalYMaximum',opts.ymax, ...
    'effectiveWenoEpsilonX',max(opts.wenoEpsilon,1/(opts.nx-1)^2), ...
    'effectiveWenoEpsilonY',max(opts.wenoEpsilon,1/(opts.ny-1)^2));
opts.caseMetadata=struct('latePhysicalBoxBranch',lineage);
opts.saveResults=true;opts.resultFile=fullfile(outputDirectory,'result.mat');
opts.storeSnapshots=false;opts.makePlots=false;opts.livePlot=false;opts.writeVideo=false;opts.verbose=false;
opts.checkpoint=struct('enabled',true,'file',fullfile(outputDirectory,'checkpoint.mat'),'every',Inf,'atExit',true);
mkdir(outputDirectory);
save(fullfile(outputDirectory,'initial_physical_data.mat'), ...
    'physicalX','physicalY','physicalRho','lineage','controls','-v7.3');
clear cp state
result=ipm.solve(opts);
files=dir(fullfile(outputDirectory,'checkpoint_*_step*.mat'));assert(isscalar(files));
report=struct('lineage',lineage,'newCaseId',char(result.metadata.caseId), ...
    'resultFile',char(result.metadata.resultFile),'checkpointFile',fullfile(files.folder,files.name), ...
    'elapsedPhysicalTime',result.state.physicalTime, ...
    'absolutePhysicalTime',lineage.absolutePhysicalEpoch+result.state.physicalTime, ...
    'localCanonicalTime',result.state.canonicalTime,'stopReason',result.state.stopReason, ...
    'initialHistoryPhysicalTime',result.history.common.physicalTime(1), ...
    'initialHistoryStep',result.history.common.acceptedStep(1), ...
    'fullNewHistoryTrusted',all(ipm.output.trustedMask(result.history,result.config)), ...
    'interpretation','Independent finite-box initial-value branch from the parent late state; not a changed-domain continuation of its native history.');
assert(~strcmp(report.newCaseId,lineage.parentCaseId) && ...
    report.initialHistoryPhysicalTime==0 && report.initialHistoryStep==0);
save(fullfile(outputDirectory,'fresh_branch_report.mat'),'report','-v7.3');
fid=fopen(fullfile(outputDirectory,'fresh_branch_report.json'),'w');assert(fid>=0);
fileCleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('FRESH_PHYSICAL_BOX fraction=%g newCase=%s epoch=%.14g elapsed=%.14g trusted=%d\n', ...
    fraction,report.newCaseId,lineage.absolutePhysicalEpoch,report.elapsedPhysicalTime,report.fullNewHistoryTrusted);
end

function opts=flat_options(config)
schema=ipm.config.schema();names=fieldnames(schema.options);opts=struct();
for k=1:numel(names)
    name=names{k};domain=schema.options.(name).domain;
    if isfield(config.(domain),name),opts.(name)=config.(domain).(name);end
end
end

function rho=paired_samples(X,Y,x,y,samples)
assert(isequal(X(1,:),x) && isequal(Y(:,1),y) && isequal(size(X),size(samples)) && ...
    isequal(size(Y),size(samples)),'Fresh initial data must be sampled on exactly their own paired axes.');
rho=samples;
end
