function report=mesh_prepare_time_control(factorialRegistration,sourceDirectory,outDir)
%MESH_PREPARE_TIME_CONTROL Register one original-t0 half-time-step control.
% Exact A geometry/policy/physics is reused; no solve, mesh.build or flow.
assert(maxNumCompThreads==10&&~isfolder(outDir));mkdir(outDir);
assert(strcmp(which('ipm.solve'),fullfile(sourceDirectory,'+ipm','solve.m')));
issues=checkcode(which(mfilename),'-id');assert(isempty(issues),jsonencode(issues));
q=load(factorialRegistration,'registration','plans');a=q.plans(strcmp({q.plans.label},'A_H8_T32'));
assert(isscalar(a)&&a.reuseExistingBaseline&&a.pureGeometryLaunchable&&a.pureInitialAudit.baselineInitialAxesBitwise);
base=ipm.output.validate(a.baselineResultFile);
baseline=mesh_audit_box_space_case(a.baselineResultFile,a.baselineCheckpointFile,q.registration.physicalFinalTime);
assert(baseline.passed&&base.config.time.cfl==.35&&base.config.time.maxDt==.005&& ...
    base.config.time.maxSteps==30000&&base.config.remesh.autonomousMesh.nodeFamily.maximumTotalNodes==110000);
o=a.options;o.cfl=.175;o.maxDt=.0025;o.maxSteps=60000;
label='E_H8_T32_HALF_TIME';runDir=fullfile(outDir,'runs',label);
o.resultFile=fullfile(runDir,'result.mat');o.checkpoint.file=fullfile(runDir,'checkpoint.mat');
o.caseMetadata=struct('kind','original_zero_time_control_half_cfl_and_maxDt_v1','label',label, ...
    'baselineCaseId',baseline.caseId,'originalPhysicalTime',0,'originalCanonicalTime',0, ...
    'newPhysicalEpochFromCheckpoint',false,'manualMidRunMeshChanges',false,'manualTransactionTriggers',false, ...
    'pureFixedGridTimeOrderClaim',false,'maximumTotalNodes',110000, ...
    'memoryBudgetInterpretation','registered node cap only; no LU RAM model');
config=ipm.config.resolve(o);
assert(config.time.cfl==.175&&config.time.maxDt==.0025&&config.time.maxSteps==60000&& ...
    isinf(config.time.finalTime)&&config.time.physicalFinalTime==baseline.actualPhysicalTime);
allowedTime={'cfl','maxDt','maxSteps','finalTime','physicalFinalTime'};
assert(isequaln(rmfield(config.time,allowedTime),rmfield(base.config.time,allowedTime)));
for group={'grid','physics','elliptic','transport','scaling','remesh','diagnostics'}
    assert(isequaln(config.(group{1}),base.config.(group{1})), ...
        'ipm:TimeControlContract','A non-time numerical domain changed: %s',group{1});
end
assert(isequaln(rmfield(config.output.checkpoint,'file'),rmfield(base.config.output.checkpoint,'file')));
assert(isequaln(rmfield(config.output,{'resultFile','checkpoint','caseMetadata'}), ...
    rmfield(base.config.output,{'resultFile','checkpoint','caseMetadata'})));
registration=struct('kind','from_zero_half_cfl_and_maxDt_time_control_v1','sourceDirectory',sourceDirectory, ...
    'baselineFactorialRegistration',factorialRegistration,'baselineAudit',baseline,'physicalFinalTime',baseline.actualPhysicalTime, ...
    'labels',{{label}},'maximumNewRuns',1,'initialNodeCount',[321,161],'maximumTotalNodes',110000, ...
    'cfl',[.35,.175],'maxDt',[.005,.0025],'maximumSteps',[30000,60000], ...
    'unchangedNumericalDomains',{{'grid','physics','elliptic','transport','scaling','remesh','diagnostics'}}, ...
    'initialGeometryQualification','reuse exact A physics/reference/policy with pure source-to-candidate axes already bitwise validated', ...
    'nativeInitializationQualification',false,'limits',q.registration.limits, ...
    'physicalWindows',q.registration.physicalWindows,'physicalPeakWindow',q.registration.physicalPeakWindow, ...
    'physicalRateUnits','d_log_scale_d_physical_time','comparison','E minus A at identical physical endpoint', ...
    'temporalAndAutomaticMeshEventSensitivity',true,'pureFixedGridTemporalOrderClaim',false, ...
    'fullGradientObservable','common.physicalGradInf = max hypot(physical rhoX, physical rhoY)', ...
    'horizontalGradientObservable','common.physicalRhoXInf = max abs(physical rhoX)', ...
    'legacyComparatorPhysicalGradientMaximumMeans','physicalRhoXInf', ...
    'noLU',true,'noPDE',true,'newRunStarted',false);
plans=struct('label',label,'reuseExistingBaseline',false,'runDirectory',runDir,'options',o,'config',config, ...
    'pureGeometryLaunchable',true,'pureInitialAudit',a.pureInitialAudit, ...
    'baselineResultFile',a.baselineResultFile,'baselineCheckpointFile',a.baselineCheckpointFile);
report=registration;report.configurationPassed=true;report.baselineNativePairingPassed=true;report.passed=true;
save(fullfile(outDir,'registration.mat'),'registration','plans','-v7.3');write_json(fullfile(outDir,'registration.json'),registration);
save(fullfile(outDir,'preflight_report.mat'),'report','-v7.3');write_json(fullfile(outDir,'preflight_report.json'),report);
fprintf('TIME_CONTROL_REGISTERED cfl=.175 maxDt=.0025 maxSteps=60000 t=%.17g newPDE=0\n',baseline.actualPhysicalTime);
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
