function report=mesh_diagnose_fresh_grid_width(smokeReportFile,outputFile)
%MESH_DIAGNOSE_FRESH_GRID_WIDTH Frozen C1/legacy width decomposition, no LU.
% This is a new observer audit. It never replaces the saved smoke decision.
assert(~isfile(outputFile));originalThreads=maxNumCompThreads(10);
cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
smoke=jsondecode(fileread(smokeReportFile));r=smoke.registration;
root=ipm.output.readCheckpoint(r.sourceFile);nativeLineage=root.payload.state.runMetadata.caseMetadata.latePhysicalBoxBranch;
assert(strcmp(nativeLineage.parentCheckpoint,r.lineage.parentCheckpoint) && ...
    nativeLineage.absolutePhysicalEpoch==r.lineage.absolutePhysicalEpoch && ...
    isequal(nativeLineage.initialNodeIndicesX(:),r.lineage.initialNodeIndicesX(:)) && ...
    isequal(nativeLineage.initialNodeIndicesY(:),r.lineage.initialNodeIndicesY(:)));
r.lineage=nativeLineage;clear root nativeLineage
transactionFiles=dir(fullfile(fileparts(smokeReportFile),'regrid_checkpoint_*_step*.mat'));assert(isscalar(transactionFiles));
files={r.sourceFile,fullfile(transactionFiles.folder,transactionFiles.name), ...
    smoke.branches(1).checkpointFile,smoke.branches(2).checkpointFile};
physicalWindow=[0,2*r.lineage.physicalAnchorX];
labels={'zero_time_source','zero_time_regrid','matched_old','matched_new'};
cases=cell(1,4);pairs=cell(1,2);
for pair=1:2
    first=2*pair-1;second=2*pair;
    [a,cases{first}]=read_view(files{first},labels{first},physicalWindow,r.lineage);
    [b,cases{second}]=read_view(files{second},labels{second},physicalWindow,r.lineage);
    assert(abs(a.physicalTime-b.physicalTime)<1e-10);
    commonPhysicalX=.5*(cases{first}.continuousPhysicalPeakX+cases{second}.continuousPhysicalPeakX);
    for k=[first,second]
        if k==first,v=a;else,v=b;end
        trace=ipm_accellab_tensor_hermite(v.omega,v.x,v.y,v.Dx,v.Dy, ...
            commonPhysicalX*v.Cx+zeros(size(v.y)),v.y);
        cases{k}.commonPhysicalColumnX=commonPhysicalX;
        cases{k}.commonPhysicalColumnContinuousYWidth=first_downcross(trace.value,trace.derivativeY,v.y)/v.Cx;
    end
    ca=cases{first};cb=cases{second};
    pairs{pair}=struct('labels',{{labels{first},labels{second}}}, ...
        'physicalTimeDifference',b.physicalTime-a.physicalTime, ...
        'legacyYWidthRelativeDifference',relative(ca.legacyPhysicalYWidth,cb.legacyPhysicalYWidth), ...
        'sameNodalColumnC1YWidthRelativeDifference',relative(ca.nodalColumnC1PhysicalYWidth,cb.nodalColumnC1PhysicalYWidth), ...
        'continuousPeakYWidthRelativeDifference',relative(ca.continuousPhysicalYWidth,cb.continuousPhysicalYWidth), ...
        'commonPhysicalColumnYWidthRelativeDifference',relative(ca.commonPhysicalColumnContinuousYWidth,cb.commonPhysicalColumnContinuousYWidth), ...
        'continuousWallWidthRelativeDifference',relative(ca.continuousPhysicalWallWidth,cb.continuousPhysicalWallWidth), ...
        'legacyWidthSignedDifference',cb.legacyPhysicalYWidth-ca.legacyPhysicalYWidth, ...
        'verticalCrossingCorrectionDifference',cb.verticalCrossingCorrection-ca.verticalCrossingCorrection, ...
        'peakColumnCorrectionDifference',cb.peakColumnCorrection-ca.peakColumnCorrection, ...
        'continuousWidthSignedDifference',cb.continuousPhysicalYWidth-ca.continuousPhysicalYWidth, ...
        'commonPhysicalColumnX',commonPhysicalX);
    d=pairs{pair};assert(abs(d.continuousWidthSignedDifference-d.legacyWidthSignedDifference- ...
        d.verticalCrossingCorrectionDifference-d.peakColumnCorrectionDifference)<1e-14);
    clear a b v trace ca cb
end
report=struct('kind','read_only_fresh_grid_continuous_width_observer_audit', ...
    'smokeReportFile',smokeReportFile,'originalSmokePassed',smoke.passed, ...
    'originalDecisionReplaced',false,'physicalWindowCommonToAllCases',physicalWindow, ...
    'windowDefinition','[0,2*initial physical transport anchor], mapped separately by each current Cx', ...
    'geometryImplementation',which('continuous_inner_geometry'), ...
    'nativeThreads',10,'nativeSignaturesValidated',true,'ellipticOperatorsBuilt',false, ...
    'pdeRhsEvaluated',false,'cases',{cases},'pairs',{pairs}, ...
    'interpretation','Connected 0.9 C1 geometry at a common continuous wall peak separates y crossing interpolation and native peak-column selection. No gate or native gauge changes; dummy zero forcing in geometry is not a PDE derivative.');
fid=fopen(outputFile,'w');assert(fid>=0);f=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('FRESH_GRID_WIDTH_OBSERVER zeroLegacy=%.9g zeroC1=%.9g matchedLegacy=%.9g matchedC1=%.9g originalPassed=%d\n', ...
    pairs{1}.legacyYWidthRelativeDifference,pairs{1}.continuousPeakYWidthRelativeDifference, ...
    pairs{2}.legacyYWidthRelativeDifference,pairs{2}.continuousPeakYWidthRelativeDifference,smoke.passed);
end

function [v,c]=read_view(file,label,physicalWindow,lineage)
cp=ipm.output.readCheckpoint(file);s=cp.payload.state;h=cp.payload.log.history;
assert(all(ipm.output.trustedMask(h,s.config)) && ...
    isequaln(s.runMetadata.caseMetadata.latePhysicalBoxBranch,lineage) && ...
    strcmp(s.config.scaling.dynamicScaleGeometry,'isotropic') && s.scale.X_shift==0);
Cx=exp(s.scale.logC_l);Comega=exp(s.scale.logC_omega);x=s.x(:)';y=s.y(:);
Dx=ipm.mesh.fdMatrix(x,1,7);Dy=ipm.mesh.fdMatrix(y,1,7);omega=s.rho*Dx';
g=continuous_inner_geometry(omega,x,y,Dx,Dy,physicalWindow*Cx);
wall=ipm.diagnostics.measureFeatures(omega(1,:),x,s.rescaling.adaptiveLevels, ...
    abs(x-s.rescaling.pinX)<=s.rescaling.peakTrackingHalfWidth);
column=wall.peakIndex;vertical=abs(omega(:,column));
measured=ipm.diagnostics.peakResolution(vertical,y,.9);
legacy=h.mesh.trackedVerticalCoreWidth(end)/Cx;
assert(abs(legacy-measured.widths/Cx)<1e-12*max(1,abs(legacy)));
nodalC1=first_downcross(vertical,Dy*vertical,y)/Cx;
deltaX=.5*(x(column+1)-x(column-1));
c=struct('label',label,'checkpointFile',file,'step',s.step,'localPhysicalTime',s.scale.physicalTime, ...
    'absolutePhysicalTime',lineage.absolutePhysicalEpoch+s.scale.physicalTime, ...
    'freshCx',Cx,'freshComega',Comega,'physicalClockSpeed',Cx/Comega, ...
    'reconstructedParentCx',lineage.parentCx*Cx,'reconstructedParentComega',lineage.parentComega*Comega, ...
    'cLFreshCanonicalUnits',h.common.c_l(end),'cOmegaFreshCanonicalUnits',h.common.c_omega(end), ...
    'cLParentCanonicalUnits',h.common.c_l(end)/lineage.canonicalCovarianceFactor, ...
    'cOmegaParentCanonicalUnits',h.common.c_omega(end)/lineage.canonicalCovarianceFactor, ...
    'logLengthRatePerPhysicalTime',h.common.c_l(end)*Cx/Comega, ...
    'logAmplitudeRatePerPhysicalTime',h.common.c_omega(end)*Cx/Comega, ...
    'legacyNodalPeakColumn',column,'legacyNodalPhysicalPeakX',x(column)/Cx, ...
    'continuousPhysicalPeakX',g.peakX/Cx,'nodalMinusContinuousPhysicalX',(x(column)-g.peakX)/Cx, ...
    'nodalMinusContinuousCellOffset',(x(column)-g.peakX)/deltaX, ...
    'legacyPhysicalYWidth',legacy,'nodalColumnC1PhysicalYWidth',nodalC1, ...
    'continuousPhysicalYWidth',g.verticalWidth/Cx,'continuousPhysicalWallWidth',g.wallWidth/Cx, ...
    'legacyPhysicalWallWidth',h.mesh.trackedWallCoreWidth(end)/Cx, ...
    'verticalCrossingCorrection',nodalC1-legacy, ...
    'peakColumnCorrection',g.verticalWidth/Cx-nodalC1,'geometry',g);
v=struct('x',x,'y',y,'omega',omega,'Dx',Dx,'Dy',Dy,'Cx',Cx,'physicalTime',s.scale.physicalTime);
end

function width=first_downcross(values,jets,y)
values=values(:);jets=jets(:);y=y(:);target=.9*values(1);
assert(values(1)>0 && abs(max(values)-values(1))<=1e-12*max(values));
for k=1:numel(y)-1
    if values(k)>=target && values(k+1)<target
        h=y(k+1)-y(k);v0=values(k);v1=values(k+1);d0=jets(k);d1=jets(k+1);
        coefficients=[2*v0-2*v1+h*(d0+d1),-3*v0+3*v1-h*(2*d0+d1),h*d0,v0-target];
        r=roots(coefficients/max(abs(coefficients)));
        r=real(r(abs(imag(r))<=1e-10 & real(r)>=0 & real(r)<=1));
        assert(isscalar(r));slope=polyval(polyder(coefficients),r)/h;assert(slope<0);
        width=y(k)+r*h;return
    end
end
error('ipm:FreshGridWidthCrossing','A transverse connected vertical downcrossing is required.');
end
function r=relative(a,b)
r=abs(a-b)/max(abs(a),realmin);
end
