function candidate = mesh_balance_y_candidate( ...
        designFile,referenceFile,outputFile,anchorPosition)
%MESH_BALANCE_Y_CANDIDATE Replace excess y compression by its minimum ramp.
% This independently scored candidate advances no PDE and installs no restart.
% Optional ANCHORPOSITION also recomputes x from the immutable reference,
% preserving that exact physical anchor in the reference coordinate.
if nargin < 4
    anchorPosition = [];
end
if exist(outputFile,'file')
    error('ipm:LongtimeMeshExistingOutput','Use a new candidate output file.');
end
loaded = load(designFile,'design');
design = loaded.design;
loaded = load(referenceFile,'dataset');
reference = loaded.dataset;
assert(~isempty(design.selected.x), ...
    'ipm:LongtimeMeshMissingX','The parent design needs an admitted x axis.');
records = design.profiles.records;
x = design.selected.x;
xInfo = struct();
if ~isempty(anchorPosition)
    xReference = reference.snapshots(1).x;
    xLimit = xReference(end);
    core = [[records.safetyCoreCenter]'-[records.safetyCoreWidthLeft]', ...
        [records.safetyCoreCenter]'+[records.safetyCoreWidthRight]'];
    front = [[records.leftFrontCenter]'-[records.leftFrontHalfWidth]', ...
        [records.leftFrontCenter]'+[records.leftFrontHalfWidth]'];
    xIntervals = min(max([core;front],0),xLimit);
    xTargets = [repmat(design.targets.xCoreCells,numel(records),1); ...
        repmat(design.targets.xFrontCells,numel(records),1)];
    xOptions = struct('geometry','symmetric', ...
        'focusCenters',anchorPosition,'anchorPhysicalPosition',anchorPosition, ...
        'sigma',design.options.equalizationOptions.xSigma, ...
        'power',2,'meshLimits',design.options.meshLimits);
    selectedModel=design.selected.xModel;
    if isfield(selectedModel,'sigma'), xOptions.sigma=selectedModel.sigma; end
    if isfield(selectedModel,'power'), xOptions.power=selectedModel.power; end
    if isfield(selectedModel,'kernelKind') && strcmp(selectedModel.kernelKind,'corridor')
        xOptions.kernelKind='corridor';
        xOptions.corridorShoulderCells=selectedModel.corridorShoulderCells;
        xOptions.corridorExpansionShoulders=selectedModel.corridorExpansionShoulders;
    end
    [x,xInfo] = ipm_gridlab_equalize_axis( ...
        xReference,xIntervals,xTargets,xOptions);
    % The existing equalizer scales its root tolerance by the far endpoint.
    % H=1e6 therefore permits O(1e-7) drift at the O(1) gauge anchor. Pin
    % the original reference node exactly and score the complete axis again.
    [referenceDistance,anchorNode] = min(abs(xReference-anchorPosition));
    assert(referenceDistance <= 64*eps(max(1,abs(anchorPosition))), ...
        'ipm:LongtimeMeshAnchorNode','The immutable root needs an exact anchor node.');
    xInfo.anchorNodeBeforeSnap = x(anchorNode);
    xInfo.anchorNodeSnap = anchorPosition-x(anchorNode);
    x(anchorNode) = anchorPosition;
    x(numel(x)+1-anchorNode) = -anchorPosition;
    xInfo.anchorNodeAfterSnap = x(anchorNode);
    xInfo.completeAxisRescoredAfterSnap = true;
end
intervals = [zeros(numel(records),1),[records.yCoreWidth]'];
target = design.targets.yCoreCells;
options = struct('geometry','positive','focusCenters',0, ...
    'sigma',design.options.equalizationOptions.ySigma, ...
    'power',design.options.equalizationOptions.yPower, ...
    'meshLimits',design.options.meshLimits);
[y,info] = ipm_gridlab_equalize_axis(reference.snapshots(1).y, ...
    intervals,repmat(target,numel(records),1),options);
scoreOptions = design.pairScore.options;
scoreOptions.profiles = design.profiles;
score = ipm_gridlab_score_frozen_pair( ...
    design.dataset,x,y,scoreOptions);
quality = score.quality;
localPassed = local_quality(quality.x) && local_quality(quality.y);
candidate = struct('kind','ipm_longtime_balanced_y_candidate', ...
    'parentDesignFile',designFile,'referenceFile',referenceFile, ...
    'candidateX',x,'candidateY',y, ...
    'anchorPosition',anchorPosition,'xEqualizationInfo',xInfo, ...
    'yEqualizationInfo',info,'pairScore',score, ...
    'localQuadraturePassed',localPassed, ...
    'transactionReady',score.admissible && localPassed, ...
    'pdeAdvanced',false,'checkpointRegridCommitted',false);
save(outputFile,'candidate','-v7.3');
if score.admissible
    fprintf(['BALANCED_MESH ready=%d core=%.8g/%.8g jump=%.9g ' ...
        'fieldL2=%.9g qRatioY=%.9g minDy=%.9g\n'], ...
        candidate.transactionReady,score.aggregate.minimumXCoreCells, ...
        score.aggregate.minimumYCoreCells, ...
        score.aggregate.worst.rhoXMaximumRelativeChange, ...
        score.aggregate.worst.fieldRelativeL2, ...
        quality.y.minimumQuadratureWeightRatio,quality.y.minimumSpacing);
else
    fprintf('BALANCED_MESH rejected=%s\n',strjoin(score.rejectionReasons,','));
end
end

function passed = local_quality(q)
passed = q.quadratureWeightsStrictlyPositive && ...
    q.minimumQuadratureWeightToControlWidthRatio >= 0.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio <= 1.65;
end
