function report=mesh_test_v2_second_growth_restart(sourceFile,targetFile,outDir,runReplay)
%MESH_TEST_V2_SECOND_GROWTH_RESTART Real 2370 -> 2481 native replay contract.
% Defaults to no-LU preflight. Root may explicitly pass true only after the
% uninterrupted tau8 run releases its LU window. Replay and reference restore
% are sequential: ipm.solve returns no LU object before reference rebuilding.
if nargin<4,runReplay=false;end
assert(islogical(runReplay) && isscalar(runReplay) && maxNumCompThreads==10 && ~isfolder(outDir));
mkdir(outDir);
source=ipm.output.readCheckpoint(sourceFile);target=ipm.output.readCheckpoint(targetFile);
a=source.payload.state;b=target.payload.state;
ma=a.runMetadata.autonomousMesh;mb=b.runMetadata.autonomousMesh;
assert(a.step==2370 && b.step==2481 && ma.version==2 && mb.version==2 && ...
    ma.currentLevelId==2 && mb.currentLevelId==4 && ...
    a.scale.canonicalTime<b.scale.canonicalTime && a.scale.physicalTime<b.scale.physicalTime && ...
    isequaln(a.config,b.config) && strcmp(a.runMetadata.caseId,b.runMetadata.caseId), ...
    'ipm:SecondGrowthSource','The explicitly registered actual pre/post checkpoints are required.');
assert(~a.config.output.storeSnapshots && ~b.config.output.storeSnapshots && ...
    ma.initialization.originalStep==0 && ma.initialization.originalCanonicalTime==0 && ...
    isequaln(ma.policy,mb.policy) && isequaln(ma.initialization,mb.initialization) && ...
    isequaln(ma.referenceFamily,mb.referenceFamily), ...
    'ipm:SecondGrowthFamily','Original t0 provenance, immutable family and no-snapshot registration must hold.');
assert(all(ipm.output.trustedMask(source.payload.log.history,a.config)) && ...
    all(ipm.output.trustedMask(target.payload.log.history,b.config)));
history_prefix(source.payload.log.history,target.payload.log.history);
n=numel(ma.transactions);assert(numel(mb.transactions)>n && isequaln(ma.transactions,mb.transactions(1:n)));
newTransactions=mb.transactions(n+1:end);
growth=newTransactions([newTransactions.sourceLevelId]~=[newTransactions.targetLevelId]);
assert(isscalar(growth) && growth.sourceStep==2477 && growth.sourceLevelId==2 && growth.targetLevelId==4 && ...
    growth.passed && growth.controllerDecision.requested && ~growth.controllerDecision.initial && ...
    growth.controllerDecision.sourceStep==2477 && ...
    isequal(growth.sourceNodeCount,[641,161]) && isequal(growth.targetNodeCount,[641,321]), ...
    'ipm:SecondGrowthTransaction','Expected the real natural step2477 level2-to4 growth.');
assert(isequal([numel(a.x),numel(a.y)],[641,161]) && ...
    isequal([numel(b.x),numel(b.y)],[641,321]) && ...
    isequal(a.baseX,ma.referenceFamily.members(2).baseX) && ...
    isequal(a.baseY,ma.referenceFamily.members(2).baseY) && ...
    isequal(b.baseX,mb.referenceFamily.members(4).baseX) && ...
    isequal(b.baseY,mb.referenceFamily.members(4).baseY));
assert(isequaln(rmfield(a.rescaling,{'originIndex','pinIndex'}), ...
    rmfield(b.rescaling,{'originIndex','pinIndex'})) && ...
    isequal(a.mass0,b.mass0) && isequal(a.rhoRange0,b.rhoRange0));
emptySource=empty_snapshot_log(source.payload.log);emptyTarget=empty_snapshot_log(target.payload.log);
policy=a.config.output.checkpoint;
assert(policy.enabled && policy.atExit && policy.every==.2);
policy.file=fullfile(outDir,'replay_checkpoint.mat');
overrides=struct('maxSteps',b.step,'saveResults',false,'checkpoint',policy, ...
    'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false);
report=struct('kind','actual_second_natural_growth_native_restart_v1', ...
    'sourceCheckpoint',sourceFile,'targetCheckpoint',targetFile,'sourceStep',a.step,'targetStep',b.step, ...
    'sourceCanonicalTime',a.scale.canonicalTime,'targetCanonicalTime',b.scale.canonicalTime, ...
    'growthTransaction',growth,'newTransactionCount',numel(newTransactions), ...
    'preflightPassed',true,'sourceAndTargetStrictSignedRead',true,'originalT0Provenance',true, ...
    'immutableFamilyAndPolicyExact',true,'registeredActiveBaseAxesExact',true, ...
    'allNativeHistoryTrusted',true,'sourceHistoryPrefixBitwise',true,'sourceControllerLedgerPrefixBitwise',true, ...
    'sourceSnapshots',emptySource,'targetSnapshots',emptyTarget, ...
    'storeSnapshots',false,'actualSnapshotsSpanMultipleNodeCounts',false, ...
    'emptySnapshotContractVerified',true,'runReplayRequested',runReplay, ...
    'nativeSplitReplayQualified',false,'PDEAdvanced',false,'LUConstructed',false, ...
    'overrides',overrides,'maximumConcurrentAdditionalLUObjects',1, ...
    'interpretation','No history node counts are used as evidence of stored cross-size snapshots.');
write_json(fullfile(outDir,'registration.json'),report);
save(fullfile(outDir,'registration.mat'),'report','-v7.3');
if ~runReplay
    write_json(fullfile(outDir,'preflight_report.json'),report);
    fprintf('SECOND_GROWTH_NO_LU_PREFLIGHT_PASS source=2370 target=2481 growth=2477 snapshots=0\n');
    return
end
assert(isfile(fullfile(fileparts(sourceFile),'report.json')), ...
    'ipm:SecondGrowthRunStillActive','Only run after the uninterrupted source experiment writes its completed report.');
try
    timer=tic;resumed=ipm.solve(overrides,source);report.replayWallSeconds=toc(timer);
    assert(strcmp(resumed.state.stopReason,'maximum_steps') && resumed.state.steps==b.step && ...
        resumed.state.canonicalTime==b.scale.canonicalTime && resumed.state.physicalTime==b.scale.physicalTime && ...
        resumed.state.normalizedTime==b.normalizedTime && isequal(resumed.state.rho,b.rho) && ...
        isequal(resumed.grid.x,b.x) && isequal(resumed.grid.y,b.y) && resumed.grid.remeshCount==b.remeshCount && ...
        isequaln(resumed.history,target.payload.log.history) && ...
        isequaln(resumed.metadata.autonomousMesh,mb));
    replay=ipm.output.readCheckpoint(resumed.metadata.latestCheckpointFile);p=replay.payload.state;
    stateFields=setdiff(fieldnames(b),{'config','runMetadata'});
    assert(isequal(sort(fieldnames(p)),sort(fieldnames(b))));
    for k=1:numel(stateFields)
        name=stateFields{k};assert(isequaln(p.(name),b.(name)), ...
            'ipm:SecondGrowthReplayState','Native mathematical state differs: %s',name);
    end
    assert(isequaln(replay.payload.log,target.payload.log), ...
        'ipm:SecondGrowthReplayLog','Complete native log differs.');
    assert(isequaln(replay.payload.cursor,target.payload.cursor), ...
        'ipm:SecondGrowthReplayCursor','Unchanged cadence requires the complete numerical cursor to match.');
    report.configurationDifferences=configuration_difference(p.config,b.config,overrides);
    report.metadataDifferences=metadata_difference(p.runMetadata,b.runMetadata,a.runMetadata,source);
    report.nativeMathematicalStateFieldsBitwise=stateFields;
    report.completeNativeLogBitwise=true;report.completeNativeCursorBitwise=true;
    report.replayedNativeCheckpoint=char(resumed.metadata.latestCheckpointFile);
    report.replayedSnapshotAudit=mesh_snapshot_shape_audit(resumed.snapshots);
    assert(report.replayedSnapshotAudit.empty && isempty(resumed.snapshots.normalizedTime) && ...
        isempty(resumed.snapshots.physicalTime) && isempty(resumed.snapshots.canonicalTime));
    clear replay p source a ma
    % No LU escapes the completed solve. Build exactly one reference factor
    % now, after replay, for complete reconstructed-field comparison.
    [referenceState,referenceLog]=ipm.output.restoreCheckpoint(target);
    reference=ipm.output.finalize(referenceState,referenceLog,'reference_checkpoint');
    clear referenceState referenceLog
    assert(isequaln(rmfield(resumed.state,'stopReason'),rmfield(reference.state,'stopReason')));
    groups={'grid','scale','physical','history','quality','fit','elliptic','snapshots'};
    for k=1:numel(groups)
        name=groups{k};assert(isequaln(resumed.(name),reference.(name)), ...
            'ipm:SecondGrowthReconstruction','Reconstructed result group differs: %s',name);
    end
    report.reconstructedResultGroupsBitwise=groups;
    report.psiOmegaVelocityPhysicalAndAllScalesBitwise=true;
    report.nativeSplitReplayQualified=true;report.PDEAdvanced=true;report.LUConstructed=true;
    report.additionalPDEBranches=1;report.referenceRestoreAfterReplayReturned=true;
    save(fullfile(outDir,'replayed_and_reference_results.mat'),'resumed','reference','-v7.3');
    clear resumed reference target b mb
    write_json(fullfile(outDir,'report.json'),report);save(fullfile(outDir,'report.mat'),'report','-v7.3');
    fprintf('SECOND_GROWTH_NATIVE_REPLAY_PASS 2370->2481 growth=2477 allMathLogCursorControllerBitwise=1 snapshots=0\n');
catch exception
    failure=struct('identifier',exception.identifier,'message',exception.message,'stack',exception.stack);
    write_json(fullfile(outDir,'failure.json'),failure);rethrow(exception)
end
end

function audit=empty_snapshot_log(log)
s=struct('rho',{log.snapshotRho},'x',{log.snapshotX},'y',{log.snapshotY});
audit=mesh_snapshot_shape_audit(s);assert(audit.empty && isempty(log.snapshotNormalizedTime));
end
function history_prefix(a,b)
assert(isequal(sort(fieldnames(a)),sort(fieldnames(b))));
groups=fieldnames(a);
for g=1:numel(groups)
    aa=a.(groups{g});bb=b.(groups{g});assert(isequal(sort(fieldnames(aa)),sort(fieldnames(bb))));
    names=fieldnames(aa);
    for k=1:numel(names)
        x=aa.(names{k});y=bb.(names{k});assert(isvector(x) && isvector(y) && numel(y)>=numel(x));
        assert(isequaln(x,y(1:numel(x))),'ipm:SecondGrowthPrefix','Changed full history prefix %s.%s',groups{g},names{k});
    end
end
end
function report=configuration_difference(actual,reference,overrides)
assert(actual.time.maxSteps==overrides.maxSteps);
a=actual;b=reference;a.time=rmfield(a.time,'maxSteps');b.time=rmfield(b.time,'maxSteps');
flags={'saveResults','makePlots','livePlot','writeVideo','verbose'};
for k=1:numel(flags)
    name=flags{k};assert(isequal(actual.output.(name),overrides.(name)));
end
assert(strcmp(actual.output.checkpoint.file,overrides.checkpoint.file) && ...
    isequaln(rmfield(actual.output.checkpoint,'file'),rmfield(reference.output.checkpoint,'file')));
a.output=rmfield(a.output,flags);b.output=rmfield(b.output,flags);
a.output.checkpoint=rmfield(a.output.checkpoint,'file');b.output.checkpoint=rmfield(b.output.checkpoint,'file');
assert(isequaln(a,b),'ipm:SecondGrowthConfig','An unregistered numerical or output option changed.');
report=struct('allowedOnly',{{'time.maxSteps','output.saveResults','output.makePlots', ...
    'output.livePlot','output.writeVideo','output.verbose','output.checkpoint.file'}}, ...
    'allOtherConfigurationExact',true,'checkpointCadenceExact',true);
end
function report=metadata_difference(actual,reference,sourceMetadata,source)
resumeCount=0;if isfield(sourceMetadata,'resumeCount'),resumeCount=sourceMetadata.resumeCount;end
assert(actual.resumeCount==resumeCount+1 && actual.resumedFromStep==source.payload.state.step && ...
    actual.resumedFromCanonicalTime==source.payload.state.scale.canonicalTime && ...
    actual.resumedFromPhysicalTime==source.payload.state.scale.physicalTime && ...
    isequal(actual.resumedFromCheckpoint,source.storageFile));
allowed={'resumeCount','resumedFromStep','resumedFromCanonicalTime','resumedFromPhysicalTime', ...
    'resumedFromCheckpoint','resultFile','videoFile','latestCheckpointFile'};
a=rmfield(actual,intersect(fieldnames(actual),allowed));b=rmfield(reference,intersect(fieldnames(reference),allowed));
assert(isequaln(a,b),'ipm:SecondGrowthMetadata','Metadata differs outside explicit restore/output provenance.');
report=struct('allowedOnly',{allowed},'allOtherMetadataIncludingControllerExact',true, ...
    'resumeProvenanceIndependentlyVerified',true);
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,'PrettyPrint',true));
end
