function report = mesh_design_stage(currentInput,rootResultFile,outputDirectory,controls)
%MESH_DESIGN_STAGE Freeze a schema-4 state and score a large-box regrid.
% No PDE integration and no checkpoint mutation. Root reference is fixed.
% Any selected pair still requires ipm_gridlab_regrid_checkpoint and a
% separate short PDE comparison before continuation is committed.
if nargin < 4
    controls = struct();
end
defaults = struct('targetXCoreCells',24,'targetYCoreCells',24, ...
    'minimumXFrontCells',20,'xEqualizationSigma',1.5, ...
    'yEqualizationSigma',0.25,'rootCorridorXFallbackEnabled',false, ...
    'rootCorridorXShoulderCells',[16 24 32]);
assert(isstruct(controls) && isscalar(controls) && ...
    isempty(setdiff(fieldnames(controls),fieldnames(defaults))), ...
    'Only mesh targets and candidate-family controls may be changed.');
names=fieldnames(defaults);
for index=1:numel(names)
    name=names{index};
    if ~isfield(controls,name), controls.(name)=defaults.(name); end
end
if exist(outputDirectory,'dir')
    error('ipm:LongtimeMeshExistingOutput', ...
        'Use a new output directory to preserve every design.');
end
mkdir(outputDirectory);
root = ipm.output.validate(rootResultFile);
assert(root.config.schemaVersion == 4 && ...
    strcmp(root.config.scaling.lengthGauge,'transport_anchor') && ...
    strcmp(root.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak'), ...
    'ipm:LongtimeMeshRootContract','Expected exact schema-4 root gauges.');
assert(root.history.mesh.remeshCount(end) == 0, ...
    'ipm:LongtimeMeshRootGrid','Root reference must be an unregridded run.');
referenceFile = fullfile(outputDirectory,'mesh_root_reference.mat');
reference = ipm_gridlab_collect_dataset(root,struct('trustedOnly',true, ...
    'targetCanonicalTimes',root.state.canonicalTime, ...
    'outputFile',referenceFile,'tag','schema4_h1e6_immutable_root_axes'));
limits = struct('maxAdjacentCellRatio',1.08, ...
    'maxLogSpacingCurvature',0.01,'minStencilRcond',1e-9, ...
    'minQuadratureWeightRatio',1e-8);
options = struct('ratioCap',1.08,'targetXCoreCells',controls.targetXCoreCells, ...
    'targetYCoreCells',controls.targetYCoreCells, ...
    'minimumXFrontCells',controls.minimumXFrontCells, ...
    'tag','schema4_h1e6_feature_scaled','meshLimits',limits, ...
    'collectOptions',struct('trustedOnly',true), ...
    'xSeedOptions',struct('minimumWidthFraction',1e-10, ...
        'minimumCellWidths',2,'contrastCaps',[6,12], ...
        'frontWidthFactors',1,'leftTailPowers',1.25), ...
    'ySeedOptions',struct('minimumWidthFraction',1e-10, ...
        'minimumCellWidths',2,'contrastCaps',[6,12], ...
        'coreWidthFactors',1,'bridgeWidthFactors',1), ...
    'axisOptions',struct('fineCount',32769,'projectToAdmissible',true), ...
    'equalizationOptions',struct('enabled',true, ...
        'xSigma',controls.xEqualizationSigma, ...
        'ySigma',controls.yEqualizationSigma,'xPower',2,'yPower',2, ...
        'uniformFlatTailEnabled',false, ...
        'currentAxisXFallbackEnabled',false, ...
        'rootCorridorXFallbackEnabled',controls.rootCorridorXFallbackEnabled, ...
        'rootCorridorXShoulderCells',controls.rootCorridorXShoulderCells), ...
    'pairScoreOptions',struct('trustedOnly',true, ...
        'targets',struct('rhoXMaximumRelativeChange',2e-3)), ...
    'outputFile',fullfile(outputDirectory,'mesh_design.mat'));
timer = tic;
design = ipm_gridlab_design_continuation_stage( ...
    currentInput,reference,options);
report = struct('status',design.status,'wallSeconds',toc(timer), ...
    'referenceFile',referenceFile,'designFile',options.outputFile, ...
    'options',options,'localQuadraturePassed',false, ...
    'pdeAdvanced',false,'checkpointRegridCommitted',false, ...
    'transactionReady',false);
if ~isempty(design.selected.x) && ~isempty(design.selected.y)
    report.xQuality = ipm.mesh.quality(design.selected.x,7, ...
        ipm.mesh.quadrature(design.selected.x));
    report.yQuality = ipm.mesh.quality(design.selected.y,7, ...
        ipm.mesh.quadrature(design.selected.y));
    report.xModelName = design.selected.xName;
    report.yModelName = design.selected.yName;
    report.localQuadraturePassed = local_quality(report.xQuality) && ...
        local_quality(report.yQuality);
    report.transactionReady = strcmp(design.status,'feasible') && ...
        report.localQuadraturePassed;
    report.pairScore = design.pairScore;
end
save(fullfile(outputDirectory,'mesh_report.mat'),'report','-v7.3');
fid = fopen(fullfile(outputDirectory,'mesh_report.json'),'w');
assert(fid >= 0,'ipm:LongtimeMeshReport','Cannot open mesh report.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('LONGTIME_MESH status=%s transactionReady=%d seconds=%.3f dir=%s\n', ...
    report.status,report.transactionReady,report.wallSeconds,outputDirectory);
end

function passed = local_quality(q)
passed = q.quadratureWeightsStrictlyPositive && ...
    q.minimumQuadratureWeightToControlWidthRatio >= 0.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio <= 1.65;
end
