function report=mesh_extend_fresh_box_ladder(shortReportFile,predictionFile,outputDirectory,controls)
%MESH_EXTEND_FRESH_BOX_LADDER Six serial fixed-inner-node, same-time cases.
% Continue four existing fresh native histories and add only the middle box.
% Reuse the earlier native/fresh calibration without claiming it was measured
% at the new target. No production checkpoint changes domain or loses history.
if nargin<4,controls=struct();end
defaults=struct('targetElapsedPhysicalTime',.01,'middleFraction',.1, ...
    'maximumAdditionalSteps',128,'allowLarge',false);
assert(isstruct(controls) && isscalar(controls) && isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
for name=fieldnames(defaults)'
    if ~isfield(controls,name{1}),controls.(name{1})=defaults.(name{1});end
end
validateattributes(controls.maximumAdditionalSteps,{'numeric'},{'scalar','integer','positive'});
assert(~isfolder(outputDirectory));
old=jsondecode(fileread(shortReportFile));r=old.registration;
if ~iscell(old.branches),old.branches=num2cell(old.branches);end
assert(old.completed && old.fullCovariance.passed && all(cellfun(@(b)b.audit.passed,old.branches)));
validateattributes(controls.targetElapsedPhysicalTime,{'numeric'},{'scalar','finite','>',r.elapsedPhysicalTime});
validateattributes(controls.middleFraction,{'numeric'},{'scalar','finite','>',r.fraction,'<',1});
assert(~r.large || controls.allowLarge,'A large ladder requires an allocated computation window.');
if r.large
    assert(old.shortIntervalComparisonPassed,'The prior short production box comparison must pass first.');
    forecast=jsondecode(fileread(predictionFile));
    assert(strcmp(forecast.checkpointFile,r.sourceFile) && ...
        forecast.sourcePhysicalEpoch==r.absolutePhysicalEpoch && ...
        isscalar(forecast.selectedElapsedPhysicalTime) && ...
        controls.targetElapsedPhysicalTime<=forecast.selectedElapsedPhysicalTime, ...
        'The requested physical interval exceeds the registered planning margin.');
    static=jsondecode(fileread(r.staticAssessment.file));
    assert(strcmp(static.registration.checkpointFile,r.sourceFile));
    for f=[controls.middleFraction,r.fraction]
        i=find([static.assessment.fraction]==f);assert(isscalar(i));
        assert(static.assessment(i).passed && static.assessment(i).eligibleForDynamicTest);
    end
else
    forecast=struct('tinyFixture',true,'nativeSignatureValidated',false);
end
originalThreads=maxNumCompThreads(10);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
source=ipm.output.readCheckpoint(r.sourceFile);s=source.payload.state;
assert(s.step==r.parentStep && s.scale.physicalTime==r.absolutePhysicalEpoch && ...
    strcmp(char(s.runMetadata.caseId),r.parentCaseId) && ...
    all(ipm.output.trustedMask(source.payload.log.history,s.config)));
middleNx=nnz(abs(s.x)<=controls.middleFraction*max(abs(s.x)));
middleNy=nnz(s.y<=controls.middleFraction*max(s.y));
assert(r.commonWenoEpsilon>=max([s.config.transport.wenoEpsilon,1/(middleNx-1)^2,1/(middleNy-1)^2]));
clear source s static
labels={'full_natural','middle_natural','crop_natural','full_common_epsilon','middle_common_epsilon','crop_common_epsilon'};
fractions=[1,controls.middleFraction,r.fraction,1,controls.middleFraction,r.fraction];
seeds=[2,0,3,4,0,5];
registration=struct('kind','continued_fresh_three_box_ladder_v1','shortReportFile',shortReportFile, ...
    'parentRegistration',r,'predictionFile',predictionFile,'forecast',forecast,'controls',controls, ...
    'caseOrder',{labels},'fractions',fractions,'seedIndices',seeds,'pdeCases',6, ...
    'existingFreshHistoriesContinued',4,'newMiddleBoxHistories',2,'ellipticAssemblies',6, ...
    'targetElapsedPhysicalTime',controls.targetElapsedPhysicalTime, ...
    'absolutePhysicalTarget',r.absolutePhysicalEpoch+controls.targetElapsedPhysicalTime, ...
    'threads',10,'extraReferenceRestores',0,'nativeCovarianceCheckedAtTarget',false, ...
    'priorNativeCovariance',old.fullCovariance,'productionDomainModified',false);
mkdir(outputDirectory);save(fullfile(outputDirectory,'registration.mat'),'registration','-v7.3');
write_json(fullfile(outputDirectory,'registration.json'),registration);
branches=cell(1,6);observations=cell(1,6);
for k=1:6
    directory=fullfile(outputDirectory,labels{k});timer=tic;
    if seeds(k)>0
        seed=old.branches{seeds(k)};cp=ipm.output.readCheckpoint(seed.checkpointFile);s=cp.payload.state;
        lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
        assert(strcmp(char(s.runMetadata.caseId),seed.newCaseId) && strcmp(lineage.parentCheckpoint,r.sourceFile) && ...
            lineage.absolutePhysicalEpoch==r.absolutePhysicalEpoch && lineage.boxFraction==fractions(k) && ...
            s.scale.physicalTime==seed.elapsedPhysicalTime && ...
            cp.payload.log.history.common.physicalTime(1)==0 && ...
            cp.payload.log.history.common.acceptedStep(1)==0 && ...
            ~s.config.remesh.adaptiveRemesh && all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
        if k>=4,assert(s.config.transport.wenoEpsilon==r.commonWenoEpsilon);
        else,assert(s.config.transport.wenoEpsilon==r.naturalPublicWenoEpsilon);end
        initialStep=s.step;initialElapsed=s.scale.physicalTime;clear cp s
        mkdir(directory);
        opts=struct('finalTime',Inf,'physicalFinalTime',controls.targetElapsedPhysicalTime, ...
            'maxSteps',initialStep+controls.maximumAdditionalSteps,'saveResults',true, ...
            'resultFile',fullfile(directory,'result.mat'),'makePlots',false,'livePlot',false, ...
            'writeVideo',false,'verbose',false,'checkpoint',struct('enabled',true, ...
            'file',fullfile(directory,'checkpoint.mat'),'every',Inf,'atExit',true));
        result=ipm.solve(opts,seed.checkpointFile);
        files=dir(fullfile(directory,'checkpoint_*_step*.mat'));assert(isscalar(files));
        branch=struct('newCaseId',char(result.metadata.caseId),'resultFile',char(result.metadata.resultFile), ...
            'checkpointFile',fullfile(files.folder,files.name),'lineage',lineage, ...
            'seedCheckpoint',seed.checkpointFile,'existingFreshHistoryContinued',true);
        assert(strcmp(branch.newCaseId,seed.newCaseId));
    else
        freshControls=struct('maximumSteps',controls.maximumAdditionalSteps,'allowLarge',controls.allowLarge);
        if k>=4,freshControls.wenoEpsilon=r.commonWenoEpsilon;end
        [branch,result]=mesh_fresh_box_branch(r.sourceFile,fractions(k),controls.targetElapsedPhysicalTime,directory,freshControls);
        branch.seedCheckpoint='';branch.existingFreshHistoryContinued=false;initialElapsed=0;initialStep=0;
    end
    branch.label=labels{k};branch.wallSeconds=toc(timer);branch.segmentAcceptedSteps=result.state.steps-initialStep;
    branch.elapsedPhysicalTime=result.state.physicalTime;
    branch.segmentElapsedPhysicalTime=result.state.physicalTime-initialElapsed;
    branch.absolutePhysicalTime=r.absolutePhysicalEpoch+result.state.physicalTime;
    branch.audit=audit(result,branch,registration);observation=observe(result,r.canonicalCovarianceFactor);clear result
    branches{k}=branch;observations{k}=observation;
    save(fullfile(directory,'protocol_observation.mat'),'observation','-v7.3');
    save(fullfile(directory,'ladder_branch_report.mat'),'branch','-v7.3');
    write_json(fullfile(directory,'ladder_branch_report.json'),branch);clear observation
    fprintf('FRESH_BOX_LADDER_CASE %d/6 %s elapsed=%.12g steps=%d core=%.8g/%.8g passed=%d\n', ...
        k,labels{k},branch.elapsedPhysicalTime,branch.segmentAcceptedSteps,branch.audit.coreCells,branch.audit.passed);
    assert(branch.audit.passed,'ipm:FreshBoxLadderGate','Ladder branch failed; prior artifacts retained.');
end
natural=compare_triplet(observations(1:3),r);common=compare_triplet(observations(4:6),r);
epsilonOnly=cell(1,3);
for k=1:3,epsilonOnly{k}=mesh_compare_fresh_box_data(observations{k},observations{k+3},r.physicalWindow,r.limits);end
ids=cellfun(@(b)b.newCaseId,branches,'UniformOutput',false);assert(numel(unique(ids))==6);
report=struct('registration',registration,'branches',{branches},'naturalEpsilonLadder',natural, ...
    'commonEpsilonLadder',common,'epsilonOnlyByBox',{epsilonOnly},'completed',true, ...
    'fixedIntervalLadderPassed',natural.passed && common.passed, ...
    'nativeCovarianceCheckedAtTarget',false,'dynamicBoxConvergenceEstablished',false, ...
    'productionDomainModified',false,'interpretation','Same physical endpoint on three independent late-state boxes, with natural/common epsilon separated. Prior covariance calibration is reused, not remeasured at this endpoint; no infinite-box or prior-history validation.');
save(fullfile(outputDirectory,'ladder_report.mat'),'report','-v7.3');write_json(fullfile(outputDirectory,'ladder_report.json'),report);
fprintf('FRESH_BOX_LADDER_COMPLETE natural=%d common=%d productionPromotion=0\n',natural.passed,common.passed);
end

function a=audit(result,branch,registration)
r=registration.parentRegistration;m=result.history.mesh;
terminal=ipm.output.readCheckpoint(branch.checkpointFile);s=terminal.payload.state;
a=struct('entireHistoryTrusted',all(ipm.output.trustedMask(result)), ...
    'nativeEntireHistoryTrusted',all(ipm.output.trustedMask(terminal.payload.log.history,s.config)), ...
    'nativeTerminalPaired',isequal(s.rho,result.state.rho) && isequal(s.x(:),result.grid.x(:)) && ...
        isequal(s.y(:),result.grid.y(:)) && s.step==result.state.steps && ...
        s.scale.physicalTime==result.state.physicalTime && s.scale.canonicalTime==result.state.canonicalTime && ...
        strcmp(char(s.runMetadata.caseId),char(result.metadata.caseId)), ...
    'physicalEndpointError',abs(branch.absolutePhysicalTime-registration.absolutePhysicalTarget), ...
    'coreCells',[m.coreGridPoints(end),m.verticalCoreGridPoints(end)], ...
    'safety',m.safetyFactor(end),'stopReason',result.state.stopReason, ...
    'freshInitialHistoryPreserved',result.history.common.physicalTime(1)==0 && result.history.common.acceptedStep(1)==0, ...
    'finitePhysicalFields',all(isfinite(result.physical.rho),'all') && ...
        all(isfinite(result.physical.rhoX),'all') && all(isfinite(result.physical.rhoY),'all'));
a.productionResolutionPassed=all(a.coreCells>=14) && isfinite(a.safety) && a.safety<.70;
a.tinyFixture=~r.large;
a.passed=a.entireHistoryTrusted && a.nativeEntireHistoryTrusted && a.nativeTerminalPaired && ...
    a.freshInitialHistoryPreserved && a.finitePhysicalFields && ...
    a.physicalEndpointError<=r.limits.physicalEndpointAbsolute && (a.productionResolutionPassed || a.tinyFixture);
end

function o=observe(result,rateScale)
p=result.physical;h=result.history;
o=struct('x',p.x,'y',p.y,'rho',p.rho,'rhoX',p.rhoX,'rhoY',p.rhoY, ...
    'cLParentUnits',result.scale.rates.cx/rateScale,'cOmegaParentUnits',result.scale.rates.comega/rateScale, ...
    'physicalGradientMaximum',h.common.physicalRhoXInf(end), ...
    'physicalQuadraticPeak',h.common.physicalQuadraticPeak(end), ...
    'physicalCoreWidthX',h.mesh.trackedWallCoreWidth(end)/result.scale.Cx, ...
    'physicalCoreWidthY',h.mesh.trackedVerticalCoreWidth(end)/result.scale.Cy);
end

function c=compare_triplet(o,r)
c=struct('fullVsMiddle',mesh_compare_fresh_box_data(o{1},o{2},r.physicalWindow,r.limits), ...
    'middleVsSmall',mesh_compare_fresh_box_data(o{2},o{3},r.physicalWindow,r.limits), ...
    'fullVsSmall',mesh_compare_fresh_box_data(o{1},o{3},r.physicalWindow,r.limits));
c.passed=c.fullVsMiddle.passed && c.middleVsSmall.passed && c.fullVsSmall.passed;
end

function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
