function candidate=mesh_anchor_first_candidate(designFile,referenceFile,outputFile,controls)
%MESH_ANCHOR_FIRST_CANDIDATE Try the required x=1 anchor before preselection.
% Uses the immutable root axes and existing equalizer/transfer scorer. A
% failed common-interval-anchor design supplies paired data, never an axis.
assert(~isfile(outputFile),'Refusing to replace a frozen candidate.');
defaults=struct('xSigma',.35,'xPower',2,'kernelKind','gaussian', ...
    'corridorShoulderCells',24,'corridorExpansionShoulders',2);
assert(isstruct(controls) && isscalar(controls) && ...
    isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
names=fieldnames(defaults);
for k=1:numel(names)
    if ~isfield(controls,names{k}), controls.(names{k})=defaults.(names{k}); end
end
loaded=load(designFile,'design'); design=loaded.design;
loaded=load(referenceFile,'dataset'); reference=loaded.dataset;
records=design.profiles.records;
xReference=reference.snapshots(1).x; yReference=reference.snapshots(1).y;
limit=xReference(end);
core=[[records.safetyCoreCenter]'-[records.safetyCoreWidthLeft]', ...
    [records.safetyCoreCenter]'+[records.safetyCoreWidthRight]'];
front=[[records.leftFrontCenter]'-[records.leftFrontHalfWidth]', ...
    [records.leftFrontCenter]'+[records.leftFrontHalfWidth]'];
intervals=min(max([core;front],0),limit);
xTargets=[repmat(design.targets.xCoreCells,numel(records),1); ...
    repmat(design.targets.xFrontCells,numel(records),1)];
xOptions=struct('geometry','symmetric','focusCenters',1, ...
    'anchorPhysicalPosition',1,'sigma',controls.xSigma,'power',controls.xPower, ...
    'kernelKind',controls.kernelKind,'corridorShoulderCells',controls.corridorShoulderCells, ...
    'corridorExpansionShoulders',controls.corridorExpansionShoulders, ...
    'meshLimits',design.options.meshLimits);
[x,xInfo]=ipm_gridlab_equalize_axis(xReference,intervals,xTargets,xOptions);
[distance,anchorNode]=min(abs(xReference-1));
assert(distance<=64*eps(1),'The immutable root must contain x=1.');
xInfo.anchorNodeBeforeSnap=x(anchorNode); xInfo.anchorNodeSnap=1-x(anchorNode);
x(anchorNode)=1; x(numel(x)+1-anchorNode)=-1;
xInfo.anchorNodeAfterSnap=1; xInfo.completeAxisRescoredAfterSnap=true;
yOptions=struct('geometry','positive','focusCenters',0, ...
    'sigma',design.options.equalizationOptions.ySigma, ...
    'power',design.options.equalizationOptions.yPower,'meshLimits',design.options.meshLimits);
[y,yInfo]=ipm_gridlab_equalize_axis(yReference,[zeros(numel(records),1),[records.yCoreWidth]'], ...
    repmat(design.targets.yCoreCells,numel(records),1),yOptions);
options=design.options.pairScoreOptions; options.profiles=design.profiles;
options.minimumXCoreCells=design.targets.xCoreCells;
options.minimumYCoreCells=design.targets.yCoreCells;
options.minimumXFrontCells=design.targets.xFrontCells;
options.meshLimits=design.options.meshLimits;
score=ipm_gridlab_score_frozen_pair(design.dataset,x,y,options);
localPassed=local_quality(score.quality.x) && local_quality(score.quality.y);
resolutionPassed=false; transferPassed=false;
if score.admissible && ~isempty(fieldnames(score.aggregate))
    a=score.aggregate; tolerance=1e-6;
    resolutionPassed=a.minimumXCoreCells>=design.targets.xCoreCells-tolerance && ...
        a.minimumYCoreCells>=design.targets.yCoreCells-tolerance && ...
        a.minimumXLeftFrontCells>=design.targets.xFrontCells-tolerance;
    transferPassed=a.worst.rhoXMaximumRelativeChange<=2e-3 && ...
        a.worst.conservationRelativeDefect<=5e-12 && ...
        a.worst.relativeRangeViolation<=2e-4;
end
candidate=struct('kind','ipm_longtime_anchor_first_candidate', ...
    'parentDesignFile',designFile,'referenceFile',referenceFile,'controls',controls, ...
    'candidateX',x,'candidateY',y,'anchorPosition',1, ...
    'xEqualizationInfo',xInfo,'yEqualizationInfo',yInfo,'pairScore',score, ...
    'localQuadraturePassed',localPassed,'resolutionPassed',resolutionPassed, ...
    'transferPassed',transferPassed, ...
    'transactionReady',score.admissible && localPassed && resolutionPassed && transferPassed, ...
    'pdeAdvanced',false,'checkpointRegridCommitted',false);
save(outputFile,'candidate','-v7.3');
coreCells=NaN; frontCells=NaN;
if isfield(score.aggregate,'minimumXCoreCells')
    coreCells=score.aggregate.minimumXCoreCells;
    frontCells=score.aggregate.minimumXLeftFrontCells;
end
fprintf('ANCHOR_FIRST sigma=%.4g power=%.4g kernel=%s shoulder=%g status=%s ready=%d core=%.8g front=%.8g ratio=%.10g\n', ...
    controls.xSigma,controls.xPower,controls.kernelKind,controls.corridorShoulderCells, ...
    xInfo.status,candidate.transactionReady,coreCells,frontCells, ...
    score.quality.x.maximumAdjacentCellRatio);
end

function passed=local_quality(q)
passed=q.quadratureWeightsStrictlyPositive && ...
    q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
