function report=mesh_test_fresh_box_tiny(outputDirectory)
%MESH_TEST_FRESH_BOX_TINY Physical covariance, references and sensitive crop.
assert(~isfolder(outputDirectory));mkdir(outputDirectory);
originalThreads=maxNumCompThreads(10);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
opts=struct('nx',65,'ny',33,'xlim',[-4,4],'ymax',4,'gridMode','uniform', ...
    'initialCondition','degenerate_primitive','degeneratePower',4, ...
    'symmetryMode','double_odd_omega','rescalingMode','dynamic', ...
    'dynamicScaleGeometry','isotropic','lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','wall_omega_quadratic_peak','spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
    'farBoundaryMode','green','physicalFinalTime',Inf,'finalTime',.2, ...
    'cfl',.25,'maxDt',.01,'minDt',1e-12,'maxSteps',64,'outputEvery',.05, ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'minimumPeakPoints',2,'minimumLevelPoints',[2 2 2],'oscillationTVTolerance',1e12, ...
    'storeSnapshots',false,'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false,'checkpoint',struct('enabled',true, ...
    'file',fullfile(outputDirectory,'source.mat'),'every',Inf,'atExit',true));
sourceResult=ipm.solve(opts);
files=dir(fullfile(outputDirectory,'source_*_step*.mat'));assert(isscalar(files));
sourceFile=fullfile(files.folder,files.name);source=ipm.output.readCheckpoint(sourceFile);
epoch=source.payload.state.scale.physicalTime;elapsed=.02;
parent=ipm.solve(struct('finalTime',Inf,'physicalFinalTime',epoch+elapsed, ...
    'maxSteps',source.payload.state.step+64,'saveResults',false, ...
    'checkpoint',struct('enabled',false)),source);
[fullReport,fullResult]=mesh_fresh_box_branch(sourceFile,1,elapsed,fullfile(outputDirectory,'full'));
[cropReport,cropResult]=mesh_fresh_box_branch(sourceFile,.75,elapsed,fullfile(outputDirectory,'crop'));
lambda=fullReport.lineage.canonicalCovarianceFactor;
assert(abs(parent.state.physicalTime-fullReport.absolutePhysicalTime)<=1e-12);
covariance=paired_covariance(parent,fullResult,lambda);
assert(covariance.coordinateRelativeInf<2e-9 && covariance.rhoRelativeInf<2e-8 && ...
    covariance.rhoXRelativeInf<2e-8 && covariance.rhoYRelativeInf<2e-8 && ...
    covariance.cLRelativeDifference<2e-7 && covariance.cOmegaRelativeDifference<2e-7, ...
    'The full-box physical fresh branch must reproduce the native continuation.');
window=[-2,2,1]/fullReport.lineage.parentCx;
cropDifference=bidirectional_comparison(fullResult,cropResult,window);
assert(cropDifference.rhoRelativeL2>1e-6, ...
    'This deliberately small crop should detect a dynamical field difference.');
fullReferenceAudit=mesh_audit_fresh_references(sourceFile,fullReport.checkpointFile, ...
    fullfile(outputDirectory,'full_reference_audit.mat'));
cropReferenceAudit=mesh_audit_fresh_references(sourceFile,cropReport.checkpointFile, ...
    fullfile(outputDirectory,'crop_reference_audit.mat'));
assert(fullReferenceAudit.rhsRelativeInf<1e-10 && cropReferenceAudit.rhsRelativeInf<1e-10);
% Cropping changes the built-in 1/(N-1)^2 regularizer even at fixed inner
% nodes. A second pair shares one explicit floor in both coordinate axes.
commonEpsilon=max([cropReport.lineage.effectiveWenoEpsilonX,cropReport.lineage.effectiveWenoEpsilonY]);
control=struct('wenoEpsilon',commonEpsilon);
[fullCommonReport,fullCommon]=mesh_fresh_box_branch(sourceFile,1,elapsed, ...
    fullfile(outputDirectory,'full_common_epsilon'),control);
[cropCommonReport,cropCommon]=mesh_fresh_box_branch(sourceFile,.75,elapsed, ...
    fullfile(outputDirectory,'crop_common_epsilon'),control);
assert(fullCommonReport.lineage.effectiveWenoEpsilonX==cropCommonReport.lineage.effectiveWenoEpsilonX && ...
    fullCommonReport.lineage.effectiveWenoEpsilonY==cropCommonReport.lineage.effectiveWenoEpsilonY);
commonEpsilonCropDifference=bidirectional_comparison(fullCommon,cropCommon,window);
epsilonOnlyDifference=bidirectional_comparison(fullResult,fullCommon,window);
assert(commonEpsilonCropDifference.rhoRelativeL2>1e-6);
allReports={fullReport,cropReport,fullCommonReport,cropCommonReport};
caseIds=cellfun(@(r)r.newCaseId,allReports,'UniformOutput',false);
assert(numel(unique(caseIds))==4 && all(cellfun(@(r)r.fullNewHistoryTrusted,allReports)));
for name={'mesh_fresh_box_branch.m','mesh_audit_fresh_references.m','mesh_test_fresh_box_tiny.m'}
    issues=checkcode(fullfile(fileparts(mfilename('fullpath')),name{1}),'-id');
    disp(issues);assert(isempty(issues));
end
report=struct('kind','tiny_fresh_late_box_covariance_test','sourceFile',sourceFile, ...
    'sourceEpoch',epoch,'sourceCanonicalTime',sourceResult.state.canonicalTime, ...
    'elapsedPhysicalTime',elapsed,'covariance',covariance,'cropDifference',cropDifference, ...
    'commonEpsilon',commonEpsilon,'commonEpsilonCropDifference',commonEpsilonCropDifference, ...
    'epsilonOnlyDifference',epsilonOnlyDifference,'fullReferenceAudit',fullReferenceAudit, ...
    'cropReferenceAudit',cropReferenceAudit,'branches',{allReports},'passed',true, ...
    'q512Executed',false,'interpretation','Tiny finite-time covariance and crop-sensitivity evidence, not late-time box convergence.');
save(fullfile(outputDirectory,'tiny_report.mat'),'report','-v7.3');
fid=fopen(fullfile(outputDirectory,'tiny_report.json'),'w');assert(fid>=0);
fileCleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('FRESH_BOX_TINY_PASS covarianceRho=%.6g covarianceRhoX=%.6g cropRhoL2=%.6g commonEpsilonCropRhoL2=%.6g\n', ...
    covariance.rhoRelativeInf,covariance.rhoXRelativeInf,cropDifference.rhoRelativeL2,commonEpsilonCropDifference.rhoRelativeL2);
end

function c=paired_covariance(a,b,lambda)
c=struct('coordinateRelativeInf',max([max(abs(a.physical.x-b.physical.x))/max(abs(a.physical.x)), ...
    max(abs(a.physical.y-b.physical.y))/max(abs(a.physical.y))]), ...
    'rhoRelativeInf',relative_inf(a.physical.rho,b.physical.rho), ...
    'rhoXRelativeInf',relative_inf(a.physical.rhoX,b.physical.rhoX), ...
    'rhoYRelativeInf',relative_inf(a.physical.rhoY,b.physical.rhoY), ...
    'cLRelativeDifference',abs(a.scale.rates.cx-b.scale.rates.cx/lambda)/abs(a.scale.rates.cx), ...
    'cOmegaRelativeDifference',abs(a.scale.rates.comega-b.scale.rates.comega/lambda)/abs(a.scale.rates.comega));
end

function c=bidirectional_comparison(a,b,window)
forward=directional(a,b,window);reverse=directional(b,a,window);c=forward;
names=fieldnames(forward);
for k=1:numel(names),c.(names{k})=max(forward.(names{k}),reverse.(names{k}));end
end

function c=directional(a,b,window)
x=a.physical.x;y=a.physical.y;
xi=find(x>=window(1) & x<=window(2));yi=find(y>=0 & y<=window(3));
assert(numel(xi)>=5 && numel(yi)>=5);
[X,Y]=meshgrid(x(xi),y(yi));c=struct();
for name={'rho','rhoX','rhoY'}
    field=name{1};reference=a.physical.(field)(yi,xi);
    sampled=interp2(b.physical.x,b.physical.y,b.physical.(field),X,Y,'linear');
    assert(all(isfinite(sampled),'all'));
    numerator=trapz(y(yi),trapz(x(xi),(sampled-reference).^2,2));
    denominator=trapz(y(yi),trapz(x(xi),reference.^2,2));assert(denominator>0);
    c.([field 'RelativeL2'])=sqrt(numerator/denominator);
    c.([field 'RelativeInf'])=relative_inf(reference,sampled);
end
end

function value=relative_inf(a,b)
value=max(abs(a-b),[],'all')/max(max(abs(a),[],'all'),realmin);
end
