function report=mesh_audit_box_space_case(resultFile,checkpointFile,targetTime,expectedConfig)
%MESH_AUDIT_BOX_SPACE_CASE Strict no-LU original-t0 endpoint qualification.
assert(maxNumCompThreads==10,'Historical checkpoint signatures require 10 threads.');
r=ipm.output.validate(resultFile);cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
if nargin<4,expectedConfig=r.config;end
m=s.runMetadata.autonomousMesh;p=s.config.remesh.autonomousMesh;h=cp.payload.log.history;
pair=isequaln(s.rho,r.state.rho)&&isequal(s.x,r.grid.x)&&isequal(s.y,r.grid.y)&& ...
    isequal(s.step,r.state.steps)&&isequal(s.remeshCount,r.grid.remeshCount)&& ...
    isequal(s.scale.canonicalTime,r.state.canonicalTime)&&isequal(s.scale.physicalTime,r.state.physicalTime)&& ...
    isequal(s.normalizedTime,r.state.normalizedTime)&&isequaln(h,r.history)&& ...
    isequaln(s.config,r.config)&&isequaln(s.config,expectedConfig)&& ...
    strcmp(s.runMetadata.caseId,r.metadata.caseId)&&isequaln(m,r.metadata.autonomousMesh)&& ...
    isequaln(s.runMetadata.caseMetadata,r.metadata.caseMetadata)&& ...
    isequaln(s.runMetadata.gaugeContract,r.metadata.gaugeContract)&& ...
    isequal(r.scale.Cx,exp(s.scale.logC_l))&&isequal(r.scale.Cy,exp(s.scale.logC_l))&& ...
    isequal(r.scale.Comega,exp(s.scale.logC_omega))&&isequal(r.scale.Xshift,s.scale.X_shift);
originalZero=h.common.t(1)==0&&h.common.canonicalTau(1)==0&&h.common.physicalTime(1)==0&& ...
    m.initialization.originalStep==0&&m.initialization.originalCanonicalTime==0&& ...
    m.initialization.originalRemeshCount==0&&m.initialization.audit.exactZeroTime&& ...
    m.initialization.audit.initialDensityExactlyResampled;
trusted=all(ipm.output.trustedMask(r));core=[h.mesh.coreGridPoints(end),h.mesh.verticalCoreGridPoints(end)];
coreHistory=min([h.mesh.coreGridPoints(:),h.mesh.verticalCoreGridPoints(:)],[],1);
safety=max(h.mesh.safetyFactor);endpoint=abs(s.scale.physicalTime-targetTime)<=1e-12;
family=ipm.remesh.referenceAxisFamily(m.referenceFamily.rootX,m.referenceFamily.rootY, ...
    s.config.scaling.transportAnchorX,p);
familyExact=isequaln(family,m.referenceFamily);f=family.members(m.currentLevelId);
geometry=isequal(s.baseX,f.baseX)&&isequal(s.baseY,f.baseY)&& ...
    isequal([numel(s.x),numel(s.y)],f.nodeCount)&&f.resourceAdmitted&& ...
    isequal(s.x([1,end]),s.config.grid.xlim)&&isequal(s.y([1,end]),[0;s.config.grid.ymax]);
growthCount=0;
if ~isempty(m.transactions)
    growthCount=nnz([m.transactions.sourceLevelId]~=[m.transactions.targetLevelId]);
end
report=struct('kind','from_original_zero_box_space_endpoint_audit_v1', ...
    'resultFile',resultFile,'checkpointFile',checkpointFile,'nativeSignatureValidated',true, ...
    'exactNativeResultPairing',pair,'originalZeroTimeLineage',originalZero, ...
    'allHistoryTrusted',trusted,'minimumHistoricalCore',coreHistory,'maximumHistoricalSafety',safety, ...
    'physicalEndpointReached',endpoint,'registeredPhysicalEndpoint',targetTime, ...
    'actualPhysicalTime',s.scale.physicalTime,'canonicalTime',s.scale.canonicalTime, ...
    'normalizedTime',s.normalizedTime,'step',s.step,'stopReason',r.state.stopReason, ...
    'caseId',s.runMetadata.caseId,'referenceFamilyExact',familyExact,'geometryContract',geometry, ...
    'targetCore',p.targetCoreCells,'endpointCore',core,'endpointSafety',h.mesh.safetyFactor(end), ...
    'currentLevelId',m.currentLevelId,'actualNodeCount',f.nodeCount,'remeshCount',s.remeshCount, ...
    'growthCount',growthCount, ...
    'cumulativeAbsolutePeakJump',m.cumulativeAbsolutePeakJump, ...
    'physicalGradientMaximum',h.common.physicalGradInf(end), ...
    'physicalRhoXMaximum',h.common.physicalRhoXInf(end), ...
    'physicalQuadraticPeak',h.common.physicalQuadraticPeak(end), ...
    'canonicalRates',[h.common.canonicalCX(end),h.common.canonicalCOmega(end)], ...
    'physicalTimeLogScaleRates',[h.common.canonicalCX(end),h.common.canonicalCOmega(end)]*r.scale.Cx/r.scale.Comega, ...
    'cfl',s.config.time.cfl,'maxDt',s.config.time.maxDt,'configuredWenoEpsilon',s.config.transport.wenoEpsilon, ...
    'noLU',true,'passed',false);
report.passed=pair&&originalZero&&trusted&&endpoint&&familyExact&&geometry&& ...
    all(coreHistory>=p.historyCoreFloor)&&safety<p.maximumSafety&& ...
    all(core>=p.endpointCoreFloor)&&m.cumulativeAbsolutePeakJump<=p.maximumCumulativeAbsolutePeakJump&& ...
    any(strcmp(r.state.stopReason,{'physical_final_time','final_time'}));
end
