function report = mesh_test_candidate(sourceFile,candidateFile,outputDirectory)
%MESH_TEST_CANDIDATE Audit a regrid and compare short runs at one physical time.
% Uses only maintained production regrid and ipm.solve numerical paths.
assert(~exist(outputDirectory,'dir'), ...
    'ipm:LongtimeMeshExistingOutput','Use a new test output directory.');
mkdir(outputDirectory);
source = ipm.output.readCheckpoint(sourceFile);
loaded = load(candidateFile,'candidate');
candidate = loaded.candidate;
assert(candidate.transactionReady, ...
    'ipm:LongtimeMeshRejectedCandidate','The frozen candidate was not admitted.');
loaded = load(candidate.parentDesignFile,'design');
frozen = loaded.design.dataset.snapshots(end);
transactionCoreTargets = max(16,[loaded.design.targets.xCoreCells, ...
    loaded.design.targets.yCoreCells]-1);
assert(isequal(source.payload.state.rho,frozen.rho) && ...
    isequal(source.payload.state.x(:),frozen.x(:)) && ...
    isequal(source.payload.state.y(:),frozen.y(:)), ...
    'ipm:LongtimeMeshSourceMismatch','Candidate and checkpoint must pair exactly.');
limits = struct('maxAdjacentCellRatio',1.08, ...
    'maxLogSpacingCurvature',0.01,'minStencilRcond',1e-9, ...
    'minQuadratureWeightRatio',1e-8);
regridOptions = struct('tag','longtime_schema4_anchor1_balanced_smoke', ...
    'minimumXCoreCells',transactionCoreTargets(1), ...
    'minimumYCoreCells',transactionCoreTargets(2), ...
    'maximumRhoXRelativeChange',2e-3,'maximumMassRelativeDefect',5e-12, ...
    'maximumRelativeRangeViolation',2e-4,'meshLimits',limits, ...
    'outputFile',fullfile(outputDirectory,'mesh_regrid_checkpoint.mat'));
[regridded,regridAudit,regridFile] = ipm_gridlab_regrid_checkpoint( ...
    source,candidate.candidateX,candidate.candidateY,regridOptions);
save(fullfile(outputDirectory,'mesh_transaction_audit.mat'), ...
    'regridAudit','regridFile','sourceFile','candidateFile','-v7.3');
fprintf('MESH_TRANSACTION passed=%d core=%.8g/%.8g jump=%.9g\n', ...
    regridAudit.passed,regridAudit.xCoreCells,regridAudit.yCoreCells, ...
    regridAudit.rhoXMaximumRelativeChange);
tau = source.payload.state.scale.canonicalTime;
oldOptions = run_options(outputDirectory,'old_grid',source, ...
    tau+0.01,Inf);
oldTimer = tic;
oldResult = ipm.solve(oldOptions,source);
oldWallSeconds = toc(oldTimer);
newOptions = run_options(outputDirectory,'new_grid',source, ...
    tau+0.02,oldResult.state.physicalTime);
newTimer = tic;
newResult = ipm.solve(newOptions,regridded);
newWallSeconds = toc(newTimer);
report = struct('sourceFile',sourceFile,'candidateFile',candidateFile, ...
    'regridFile',char(regridFile),'regridAudit',regridAudit, ...
    'oldResultFile',char(oldResult.metadata.resultFile), ...
    'newResultFile',char(newResult.metadata.resultFile), ...
    'oldSegmentSteps',oldResult.state.steps-source.payload.state.step, ...
    'newSegmentSteps',newResult.state.steps-source.payload.state.step, ...
    'oldWallSeconds',oldWallSeconds,'newWallSeconds',newWallSeconds, ...
    'oldStopReason',oldResult.state.stopReason, ...
    'newStopReason',newResult.state.stopReason, ...
    'oldPhysicalTime',oldResult.state.physicalTime, ...
    'newPhysicalTime',newResult.state.physicalTime, ...
    'physicalTimeDifference',newResult.state.physicalTime-oldResult.state.physicalTime, ...
    'canonicalTimeDifference',newResult.state.canonicalTime-oldResult.state.canonicalTime, ...
    'oldTrusted',all(ipm.output.trustedMask(oldResult.history,oldResult.config)), ...
    'newTrusted',all(ipm.output.trustedMask(newResult.history,newResult.config)), ...
    'physicalRhoXRelativeDifference',relative_difference( ...
        oldResult.history.common.physicalRhoXInf(end), ...
        newResult.history.common.physicalRhoXInf(end)), ...
    'cLRelativeDifference',relative_difference( ...
        oldResult.history.common.c_l(end),newResult.history.common.c_l(end)), ...
    'cOmegaRelativeDifference',relative_difference( ...
        oldResult.history.common.c_omega(end),newResult.history.common.c_omega(end)), ...
    'localPhysical',local_comparison(oldResult,newResult,[-2,2,2]), ...
    'peakAlignedPhysical',ipm.output.compare(oldResult,newResult,[-2,2,2]));
report.passed = regridAudit.passed && report.oldTrusted && report.newTrusted && ...
    abs(report.physicalTimeDifference) <= 1e-10 && ...
    abs(report.physicalRhoXRelativeDifference) <= 5e-3 && ...
    abs(report.cLRelativeDifference) <= 1e-2 && ...
    abs(report.cOmegaRelativeDifference) <= 1e-2 && ...
    report.localPhysical.rhoRelativeL2 <= 5e-4 && ...
    report.localPhysical.omegaRelativeL2 <= 5e-3 && ...
    report.localPhysical.rhoYRelativeL2 <= 5e-3;
save(fullfile(outputDirectory,'mesh_smoke_report.mat'),'report','-v7.3');
fid = fopen(fullfile(outputDirectory,'mesh_smoke_report.json'),'w');
assert(fid >= 0,'ipm:LongtimeMeshReport','Cannot write smoke report.');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf(['MESH_SMOKE passed=%d oldSteps=%d newSteps=%d dtPhysical=%.9g ' ...
    'rhoX=%.9g cL=%.9g cOmega=%.9g rhoL2=%.9g omegaL2=%.9g rhoYL2=%.9g\n'], ...
    report.passed,report.oldSegmentSteps,report.newSegmentSteps, ...
    report.physicalTimeDifference,report.physicalRhoXRelativeDifference, ...
    report.cLRelativeDifference,report.cOmegaRelativeDifference, ...
    report.localPhysical.rhoRelativeL2,report.localPhysical.omegaRelativeL2, ...
    report.localPhysical.rhoYRelativeL2);
end

function options = run_options(directory,label,source,finalTime,physicalTime)
options = struct('finalTime',finalTime,'physicalFinalTime',physicalTime, ...
    'maxSteps',source.payload.state.step+32,'saveResults',true, ...
    'resultFile',fullfile(directory,[label '_result.mat']), ...
    'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false, ...
    'checkpoint',struct('enabled',true, ...
    'file',fullfile(directory,[label '_checkpoint.mat']), ...
    'every',Inf,'atExit',true));
end

function value = relative_difference(old,new)
value = (new-old)/max(abs(old),eps);
end

function comparison = local_comparison(old,new,window)
x = old.grid.physicalX(:)';
y = old.grid.physicalY(:);
xi = find(x >= window(1) & x <= window(2));
yi = find(y >= 0 & y <= window(3));
[X,Y] = meshgrid(x(xi),y(yi));
weights = control_width(y)*control_width(x)';
weights = weights(yi,xi);
oldRhoY = ipm.mesh.fdMatrix(old.grid.y,1,7)*old.state.rho * ...
    (old.scale.Cy/old.scale.Comega);
newRhoY = ipm.mesh.fdMatrix(new.grid.y,1,7)*new.state.rho * ...
    (new.scale.Cy/new.scale.Comega);
fields = {'rho','omega','rhoY'};
oldFields = {old.physical.rho,old.physical.omega,oldRhoY};
newFields = {new.physical.rho,new.physical.omega,newRhoY};
comparison = struct('window',window,'comparisonCoordinates','physical_lab', ...
    'interpolation','linear_to_reference_nodes','points',numel(X));
for index = 1:numel(fields)
    reference = oldFields{index}(yi,xi);
    interpolated = interp2(new.grid.physicalX,new.grid.physicalY, ...
        newFields{index},X,Y,'linear',NaN);
    assert(all(isfinite(interpolated),'all'), ...
        'ipm:LongtimeMeshOverlap','Local physical comparison left the common box.');
    error = interpolated-reference;
    comparison.([fields{index} 'RelativeL2']) = sqrt( ...
        sum(error.^2.*weights,'all')/max(sum(reference.^2.*weights,'all'),eps));
    comparison.([fields{index} 'RelativeInf']) = ...
        max(abs(error),[],'all')/max(max(abs(reference),[],'all'),eps);
end
end

function width = control_width(axis)
d = diff(axis(:));
width = [d(1)/2;(d(1:end-1)+d(2:end))/2;d(end)/2];
end
