function report=mesh_run_fresh_resolution_branch(sourceResultFile,initialDataFile,candidateFile,referenceAuditFile,outDir)
%MESH_RUN_FRESH_RESOLUTION_BRANCH One finer branch to an existing actual epoch.
% Requires an allocated large-LU window. Never reruns the coarse reference.
assert(maxNumCompThreads==10 && ~isfolder(outDir));mkdir(outDir);
sourceRoot=fileparts(fileparts(fileparts(mfilename('fullpath'))));
required={'ipm.solve','ipm_gridlab_regrid_checkpoint','ipm_gridlab_collect_dataset', ...
    'ipm_gridlab_score_frozen_pair','fresh_profile_campaign_review','fresh_profile_value_equal', ...
    'fresh_profile_history_prefix','mesh_compare_fresh_box_data','compare_space_observers_with_epoch', ...
    'mesh_diagnose_fresh_grid_width','mesh_fresh_grid_auxiliary_verdict','continuous_inner_geometry', ...
    'ipm_accellab_hermite_peak','ipm_accellab_tensor_hermite'};
resolved=cell(size(required));
for k=1:numel(required)
    resolved{k}=which(required{k});assert(startsWith(resolved{k},[sourceRoot,filesep]), ...
        'ipm:FreshResolutionFreeze','A required numerical or observer dependency escapes the frozen source.');
end
[sourceReview,source,contract]=fresh_profile_campaign_review(sourceResultFile,initialDataFile);
referenceAudit=jsondecode(fileread(referenceAuditFile));assert(referenceAudit.stageAccepted);
[coarseReview,coarse]=fresh_profile_campaign_review(referenceAudit.resultFile,initialDataFile,contract);
assert(strcmp(referenceAudit.checkpointFile,coarseReview.checkpointFile) && ...
    strcmp(referenceAudit.sourceCheckpoint,sourceReview.checkpointFile) && ...
    referenceAudit.absolutePhysicalTime==coarseReview.absolutePhysicalTime && ...
    coarseReview.localPhysicalTime>sourceReview.localPhysicalTime);
fresh_profile_history_prefix(source.payload.log.history,coarse.payload.log.history,false);
assert(isequal(source.payload.state.x,coarse.payload.state.x) && isequal(source.payload.state.y,coarse.payload.state.y));
loaded=load(candidateFile,'candidate');candidate=loaded.candidate;
assert(candidate.transactionReady && candidate.anchorExact && candidate.completePairScoredInOriginalUnits && ...
    candidate.currentTransactionNodeCountSupported && ...
    candidate.controls.targetXCoreCells==42 && candidate.controls.targetYCoreCells==42 && ...
    candidate.corePatchControls.positiveFineCells==64 && candidate.corePatchControls.coreFineCellFraction==.65 && ...
    strcmp(candidate.reference.provenance.currentCheckpoint,sourceReview.checkpointFile) && ...
    strcmp(candidate.reference.provenance.initialPhysicalDataFile,initialDataFile) && ...
    isequal(candidate.reference.x,contract.initialX) && isequal(candidate.reference.y,contract.initialY));
lineage=contract.lineage;limits=struct('cropRhoRelativeL2Inf',1e-3,'cropGradientRelativeL2Inf',2e-3, ...
    'cropPeakRelative',2e-3,'cropRateRelative',2e-3,'cropRateAbsolute',1e-6,'cropPhysicalWidthRelative',5e-3);
registration=struct('kind','late_state_single_finer_branch_actual_time_sensitivity_v1', ...
    'sourceFile',sourceReview.checkpointFile,'sourceResultFile',sourceResultFile,'initialDataFile',initialDataFile, ...
    'candidateFile',candidateFile,'referenceEndpointAudit',referenceAuditFile,'referenceResultFile',referenceAudit.resultFile, ...
    'referenceCheckpoint',coarseReview.checkpointFile,'lineage',lineage,'caseId',contract.caseId, ...
    'absolutePhysicalTarget',coarseReview.absolutePhysicalTime,'targetElapsedPhysicalTime',coarseReview.localPhysicalTime, ...
    'referenceParentEquivalentTau',coarseReview.parentEquivalentTau,'physicalWindow',[-2,2,1]/lineage.parentCx, ...
    'transactionMinimumCore',[40,40],'transactionMinimumLeftFront',20,'transactionMaximumPeakJump',.002, ...
    'transactionMaximumMassDefect',5e-12,'transactionMaximumRangeViolation',2e-4, ...
    'maximumCumulativePeakJump',.02,'fineTerminalMinimumCore',[34,34],'fineTerminalMaximumSafety',.30, ...
    'fullHistoryMinimumCore',[14,14],'fullHistoryMaximumSafety',.70,'maximumAdditionalSteps',512, ...
    'unchangedCFL',contract.CFL,'unchangedMaxDt',contract.maxDt,'comparisonLimits',limits, ...
    'maximumContinuousWidthRelativeDifference',.005,'hermiteFieldThresholdsSameAsLinear',true, ...
    'legacyAndAuxiliaryDecisionsSeparate',true,'geometryUniversalPerRefinementRatioTestPassed',false, ...
    'genericFourthOrderClaim',false,'independentInitialGridConvergenceClaim',false, ...
    'coarseReferenceRerun',false,'oneOptionalPostRestoreRhsCache',true,'threads',10, ...
    'dependencies',{required},'resolvedDependencies',{resolved});
write_json(fullfile(outDir,'registration.json'),registration);
auxRegistration=struct('kind','prospective_same_continuous_peak_width_auxiliary_protocol_v1', ...
    'registeredBeforePDE',true,'replaceLegacySmokeDecision',false,'sourceCheckpoint',sourceReview.checkpointFile, ...
    'candidateFile',candidateFile,'maximumContinuousWidthRelativeDifference',.005, ...
    'additionalHermiteFieldGatesRequired',true,'geometryUniversalPerRefinementRatioTestPassed',false);
auxRegistrationFile=fullfile(outDir,'auxiliary_registration.json');write_json(auxRegistrationFile,auxRegistration);
sourceState=source.payload.state;sourceStep=sourceState.step;
coarseResult=ipm.output.validate(referenceAudit.resultFile);coarseObservation=observe(coarseResult,lineage.canonicalCovarianceFactor);
coarseBranch=struct('checkpointFile',coarseReview.checkpointFile,'resultFile',coarseReview.resultFile, ...
    'label','existing_completed_coarse_reference','computedByThisProtocol',false,'wallSeconds',0, ...
    'audit',struct('passed',true,'strictNativeReview',coarseReview));clear coarse coarseResult
try
    meshLimits=struct('maxAdjacentCellRatio',1.08,'maxLogSpacingCurvature',.01, ...
        'minStencilRcond',1e-9,'minQuadratureWeightRatio',1e-8);
    originalResult=ipm.output.validate(sourceResultFile);
    dataset=ipm_gridlab_collect_dataset(originalResult,struct('trustedOnly',true,'tag','actual_source139_resolution'));clear originalResult
    score=ipm_gridlab_score_frozen_pair(dataset,candidate.candidateX,candidate.candidateY, ...
        struct('trustedOnly',true,'meshLimits',meshLimits));
    assert(score.admissible && local_quality(score.quality.x) && local_quality(score.quality.y) && ...
        score.aggregate.minimumXCoreCells>=42 && score.aggregate.minimumYCoreCells>=42 && ...
        score.aggregate.minimumXLeftFrontCells>=20 && score.aggregate.worst.rhoXMaximumRelativeChange<=.002 && ...
        score.aggregate.worst.conservationRelativeDefect<=5e-12 && score.aggregate.worst.relativeRangeViolation<=2e-4);
    options=struct('minimumXCoreCells',40,'minimumYCoreCells',40,'maximumRhoXRelativeChange',.002, ...
        'maximumMassRelativeDefect',5e-12,'maximumRelativeRangeViolation',2e-4,'meshLimits',meshLimits, ...
        'tag','fresh_step139_target42_long_actual_time','outputFile','');
    timer=tic;[proposal,transaction]=ipm_gridlab_regrid_checkpoint(source,candidate.candidateX,candidate.candidateY,options);
    n=proposal.payload.state;
    assert(transaction.passed && transaction.xCoreCells>=40 && transaction.yCoreCells>=40 && ...
        local_quality(transaction.xQuality) && local_quality(transaction.yQuality));
    assert(n.step==sourceStep && n.normalizedTime==sourceState.normalizedTime && isequaln(n.scale,sourceState.scale) && ...
        isequal(n.baseX,sourceState.baseX) && isequal(n.baseY,sourceState.baseY) && ...
        isequal(n.x,candidate.candidateX(:)') && isequal(n.y,candidate.candidateY(:)) && ...
        strcmp(n.runMetadata.caseId,contract.caseId) && isequaln(n.runMetadata.caseMetadata.latePhysicalBoxBranch,lineage) && ...
        isequaln(rmfield(n.rescaling,{'originIndex','pinIndex'}),contract.runtimeReferences));
    fresh_profile_history_prefix(source.payload.log.history,proposal.payload.log.history,true);
    assert(all(ipm.output.trustedMask(proposal.payload.log.history,n.config)) && ...
        sourceReview.cumulativeAbsolutePeakJump+transaction.rhoXMaximumRelativeChange<=.02);
    dataset.snapshots.rho=n.rho;dataset.snapshots.x=n.x;dataset.snapshots.y=n.y;
    dataset.snapshots.physicalRho=exp(-n.scale.logC_omega)*n.rho;
    dataset.snapshots.physicalX=n.x/exp(n.scale.logC_l);dataset.snapshots.physicalY=n.y/exp(n.scale.logC_l);
    actual=ipm_gridlab_score_frozen_pair(dataset,n.x,n.y,struct('trustedOnly',true,'meshLimits',meshLimits));
    assert(actual.admissible && actual.aggregate.minimumXLeftFrontCells>=20);
    transaction.actualLeftFrontCells=actual.aggregate.minimumXLeftFrontCells;
    transaction.wallSeconds=toc(timer);
    [proposal,regridFile]=ipm.output.writeCheckpoint(proposal,fullfile(outDir,'regrid_checkpoint.mat'));
    validated=ipm.output.readCheckpoint(regridFile);assert(fresh_profile_value_equal(proposal.payload,validated.payload));
    sourceHistory=proposal.payload.log.history;sourceReferences=n.rescaling;fineX=n.x;fineY=n.y;
    write_json(fullfile(outDir,'transaction_audit.json'),transaction);
    fprintf('FRESH_FINE_LONG_TRANSACTION core=%.9g/%.9g front=%.9g peak=%.9g passed=1\n', ...
        transaction.xCoreCells,transaction.yCoreCells,transaction.actualLeftFrontCells,transaction.rhoXMaximumRelativeChange);
    clear source sourceState n proposal validated dataset actual score candidate loaded
    fineDirectory=fullfile(outDir,'fine_branch');mkdir(fineDirectory);
    options=struct('finalTime',Inf,'physicalFinalTime',registration.targetElapsedPhysicalTime,'maxSteps',sourceStep+512, ...
        'saveResults',true,'resultFile',fullfile(fineDirectory,'result.mat'),'makePlots',false,'livePlot',false, ...
        'writeVideo',false,'verbose',false,'checkpoint',struct('enabled',true,'file',fullfile(fineDirectory,'checkpoint.mat'), ...
        'every',.1/lineage.canonicalCovarianceFactor,'atExit',true));
    timer=tic;fineResult=ipm.solve(options,regridFile);wall=toc(timer);
    fineResultFile=char(fineResult.metadata.resultFile);stopReason=char(fineResult.state.stopReason);
    fineObservation=observe(fineResult,lineage.canonicalCovarianceFactor);clear fineResult
    [fineReview,terminal]=fresh_profile_campaign_review(fineResultFile,initialDataFile,contract);
    fresh_profile_history_prefix(sourceHistory,terminal.payload.log.history,false);
    assert(isequal(terminal.payload.state.x,fineX) && isequal(terminal.payload.state.y,fineY) && ...
        isequaln(terminal.payload.state.rescaling,sourceReferences));
    audit=struct('strictNativeReview',fineReview,'sourcePrefixExact',true,'lineageAndRuntimeReferencesPreserved',true, ...
        'fineAxesUnchanged',true,'physicalEndpointError',abs(fineReview.absolutePhysicalTime-registration.absolutePhysicalTarget), ...
        'stopReason',stopReason,'additionalSteps',fineReview.step-sourceStep, ...
        'terminalFineCorePassed',all(fineReview.coreCells>=34),'terminalFineSafetyPassed',fineReview.safety<.30);
    audit.passed=audit.physicalEndpointError<=1e-11 && strcmp(stopReason,'physical_final_time') && ...
        audit.additionalSteps<=512 && audit.terminalFineCorePassed && audit.terminalFineSafetyPassed;
    fineBranch=struct('checkpointFile',fineReview.checkpointFile,'resultFile',fineResultFile,'label','new_finer_branch', ...
        'computedByThisProtocol',true,'wallSeconds',wall,'audit',audit);
    write_json(fullfile(fineDirectory,'branch_report.json'),fineBranch);
    fprintf('FRESH_FINE_LONG_ENDPOINT steps=%d wall=%.3f core=%.9g/%.9g safety=%.9g passed=%d\n', ...
        audit.additionalSteps,wall,fineReview.coreCells,fineReview.safety,audit.passed);
    assert(audit.passed,'ipm:FreshResolutionEndpoint','Retain the actual endpoint but stop after a failed registered gate.');
    clear sourceHistory sourceReferences fineX fineY
    timer=tic;state=ipm.output.restoreCheckpoint(terminal,struct('saveResults',false,'makePlots',false, ...
        'livePlot',false,'writeVideo',false,'verbose',false));
    assert(isequaln(state.rhsCache.rho,state.rho) && isequaln(state.rhsCache.scale,state.scale));
    Omega=state.flow.source;FX=state.rhsCache.rhoRate*state.ops.Dx';x=state.ops.x;y=state.ops.y;
    Dx=state.ops.Dx;Dy=state.ops.Dy;scale=state.scale;nativeRates=[state.flow.c_l,state.flow.c_omega,state.flow.c_r];
    cacheAudit=struct('sourceCheckpoint',fineReview.checkpointFile,'rhsCachePairedExactly',true,'extraTimeSteps',0, ...
        'postRestoreSeconds',toc(timer),'poissonResidual',state.flow.poissonResidual,'absolutePhysicalEpoch',lineage.absolutePhysicalEpoch,'lineage',lineage);
    save(fullfile(outDir,'true_rhs_cache.mat'),'Omega','FX','x','y','Dx','Dy','scale','nativeRates','cacheAudit','-v7.3');
    clear state terminal Omega FX x y Dx Dy scale nativeRates
    linear=mesh_compare_fresh_box_data(coarseObservation,fineObservation,registration.physicalWindow,limits);
    clear coarseObservation fineObservation
    observers=compare_space_observers_with_epoch(coarseReview.checkpointFile,fineReview.checkpointFile, ...
        registration.physicalWindow,fullfile(outDir,'linear_hermite_observers.json'));
    report=struct('registration',registration,'transaction',transaction,'branches',{{coarseBranch,fineBranch}}, ...
        'linearComparison',linear,'comparisonLimits',limits,'linearHermiteObservers',observers, ...
        'completed',true,'passed',linear.passed,'legacyDecisionReplaced',false, ...
        'interpretation','Late-state spatial plus transfer/evolution sensitivity; not independent initial-grid convergence.');
    smokeFile=fullfile(outDir,'smoke_report.json');write_json(smokeFile,report);save(fullfile(outDir,'smoke_report.mat'),'report','-v7.3');
    widthFile=fullfile(outDir,'continuous_width_audit.json');mesh_diagnose_fresh_grid_width(smokeFile,widthFile);
    aux=mesh_fresh_grid_auxiliary_verdict(smokeFile,widthFile,auxRegistrationFile,fullfile(outDir,'continuous_auxiliary_verdict.json'));
    hermitePassed=hermite_fields_passed(observers,limits);
    final=struct('legacyLinearAndNodalWidthPassed',linear.passed,'continuousAuxiliaryPassed',aux.continuousObserverAuxiliaryPassed, ...
        'bidirectionalHermiteFieldGatesPassed',hermitePassed, ...
        'registeredCombinedAuxiliaryPassed',aux.continuousObserverAuxiliaryPassed && hermitePassed, ...
        'originalLegacyDecisionChanged',false,'coarseReferenceRerun',false,'independentInitialGridConvergenceClaim',false, ...
        'fineCheckpoint',fineReview.checkpointFile,'absolutePhysicalTarget',registration.absolutePhysicalTarget);
    write_json(fullfile(outDir,'final_verdicts.json'),final);
    fprintf('FRESH_FINE_LONG_COMPLETE legacy=%d continuousAux=%d hermite=%d combinedAux=%d\n', ...
        linear.passed,aux.continuousObserverAuxiliaryPassed,hermitePassed,final.registeredCombinedAuxiliaryPassed);
catch exception
    failure=struct('identifier',exception.identifier,'message',exception.message,'stack',exception.stack);
    write_json(fullfile(outDir,'failure.json'),failure);rethrow(exception)
end
end

function passed=hermite_fields_passed(o,limits)
passed=true;
for direction={'secondToFirstNodes','firstToSecondNodes'}
    for name={'rho','omega','rhoY'}
        values=o.(direction{1}).fields.(name{1}).hermite;
        if strcmp(name{1},'rho'),bound=limits.cropRhoRelativeL2Inf;else,bound=limits.cropGradientRelativeL2Inf;end
        passed=passed && max(values.relativeL2,values.relativeInf)<=bound;
    end
end
end
function passed=local_quality(q)
passed=q.quadratureWeightsStrictlyPositive && q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
function o=observe(r,rateScale)
p=r.physical;h=r.history;
o=struct('x',p.x,'y',p.y,'rho',p.rho,'rhoX',p.rhoX,'rhoY',p.rhoY, ...
    'cLParentUnits',r.scale.rates.cx/rateScale,'cOmegaParentUnits',r.scale.rates.comega/rateScale, ...
    'physicalGradientMaximum',h.common.physicalRhoXInf(end),'physicalQuadraticPeak',h.common.physicalQuadraticPeak(end), ...
    'physicalCoreWidthX',h.mesh.trackedWallCoreWidth(end)/r.scale.Cx,'physicalCoreWidthY',h.mesh.trackedVerticalCoreWidth(end)/r.scale.Cy);
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
