function report=mesh_run_fresh_box_protocol(sourceFile,fraction,elapsedPhysicalTime,outputDirectory,controls)
%MESH_RUN_FRESH_BOX_PROTOCOL Five serial, independently saved late-box cases.
% A native same-grid continuation and four genuinely fresh physical IVPs.
% Large runs require an allocated window and the matching passed static screen.
if nargin<5,controls=struct();end
defaults=struct('maximumSteps',64,'allowLarge',false,'staticReportFile','');
assert(isstruct(controls) && isscalar(controls) && isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
for name=fieldnames(defaults)'
    if ~isfield(controls,name{1}),controls.(name{1})=defaults.(name{1});end
end
validateattributes(controls.maximumSteps,{'numeric'},{'scalar','integer','positive'});
validateattributes(fraction,{'numeric'},{'scalar','positive','<',1,'finite'});
validateattributes(elapsedPhysicalTime,{'numeric'},{'scalar','positive','finite'});
assert(~isfolder(outputDirectory),'Refusing to overwrite a prior protocol.');
originalThreads=maxNumCompThreads(10);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
source=ipm.output.readCheckpoint(sourceFile);s=source.payload.state;
large=numel(s.rho)>20000;
assert(~large || controls.allowLarge,'A large protocol needs an allocated computation window.');
assert(all(ipm.output.trustedMask(source.payload.log.history,s.config)));
assert(~s.config.remesh.adaptiveRemesh,'This protocol does not admit an automatic regrid.');
epoch=s.scale.physicalTime;Cx=exp(s.scale.logC_l);lambda=exp(s.scale.logC_l-s.scale.logC_omega);
xi=find(abs(s.x)<=fraction*max(abs(s.x)));yi=find(s.y<=fraction*max(s.y));
commonEpsilon=max([s.config.transport.wenoEpsilon,1/(numel(xi)-1)^2,1/(numel(yi)-1)^2]);
staticAssessment=struct('required',large,'verified',false);
if ~isempty(controls.staticReportFile)
    static=jsondecode(fileread(controls.staticReportFile));
    assert(strcmp(static.registration.checkpointFile,sourceFile),'Static screen has a different parent checkpoint.');
    index=find([static.assessment.fraction]==fraction);assert(isscalar(index));
    assert(static.assessment(index).passed && static.assessment(index).eligibleForDynamicTest);
    record=static.screen.records(index);
    assert(isequal(record.nodes(:)',[numel(xi),numel(yi)]));
    staticAssessment=struct('required',large,'verified',true,'file',controls.staticReportFile, ...
        'assessment',static.assessment(index),'coreVelocityRelativeL2',record.coreVelocityRelativeL2, ...
        'coreVelocityRelativeInf',record.coreVelocityRelativeInf);
end
assert(~large || staticAssessment.verified,'A large crop must have a matching admitted frozen screen.');
limits=struct('physicalEndpointAbsolute',1e-11,'productionMinimumCoreCells',14, ...
    'productionMaximumSafety',.70,'covarianceCoordinateRelativeInf',1e-7, ...
    'covarianceFieldRelativeInf',1e-5,'covarianceRateRelative',1e-4, ...
    'cropRhoRelativeL2Inf',1e-3,'cropGradientRelativeL2Inf',2e-3, ...
    'cropPeakRelative',2e-3,'cropRateRelative',2e-3,'cropRateAbsolute',1e-6, ...
    'cropPhysicalWidthRelative',5e-3);
labels={'native_continuation','full_natural','crop_natural','full_common_epsilon','crop_common_epsilon'};
registration=struct('kind','serial_fresh_late_physical_box_protocol_v1', ...
    'sourceFile',sourceFile,'parentCaseId',char(s.runMetadata.caseId),'parentStep',s.step, ...
    'parentCanonicalTime',s.scale.canonicalTime,'absolutePhysicalEpoch',epoch, ...
    'elapsedPhysicalTime',elapsedPhysicalTime,'absolutePhysicalTarget',epoch+elapsedPhysicalTime, ...
    'fraction',fraction,'fullNodes',[numel(s.x),numel(s.y)],'cropNodes',[numel(xi),numel(yi)], ...
    'cropOriginalXHalfWidth',max(abs(s.x(xi))),'cropOriginalYMaximum',max(s.y(yi)), ...
    'parentCx',Cx,'canonicalCovarianceFactor',lambda,'physicalWindow',[-2,2,1]/Cx, ...
    'commonWenoEpsilon',commonEpsilon,'naturalPublicWenoEpsilon',s.config.transport.wenoEpsilon, ...
    'fullEffectiveNaturalEpsilon',[max(s.config.transport.wenoEpsilon,1/(numel(s.x)-1)^2), ...
        max(s.config.transport.wenoEpsilon,1/(numel(s.y)-1)^2)], ...
    'cropEffectiveNaturalEpsilon',[max(s.config.transport.wenoEpsilon,1/(numel(xi)-1)^2), ...
        max(s.config.transport.wenoEpsilon,1/(numel(yi)-1)^2)], ...
    'threads',10,'maximumStepsPerBranch',controls.maximumSteps,'pdeCases',5, ...
    'freshCases',4,'ellipticAssemblies',5,'extraReferenceRestores',0, ...
    'serial',true,'caseOrder',{labels},'limits',limits,'staticAssessment',staticAssessment, ...
    'large',large,'controls',controls,'runtimeReferences','Native inherited; fresh initialized with new case/history. Full native/fresh covariance is required.', ...
    'productionDomainModified',false,'productionPromotionPermitted',false);
mkdir(outputDirectory);save(fullfile(outputDirectory,'registration.mat'),'registration','-v7.3');
write_json(fullfile(outputDirectory,'registration.json'),registration);
clear source s static record
branches=cell(1,5);observations=cell(1,5);
for k=1:5
    branchDirectory=fullfile(outputDirectory,labels{k});timer=tic;
    if k==1
        mkdir(branchDirectory);
        opts=struct('finalTime',Inf,'physicalFinalTime',epoch+elapsedPhysicalTime, ...
            'maxSteps',registration.parentStep+controls.maximumSteps,'saveResults',true, ...
            'resultFile',fullfile(branchDirectory,'result.mat'), ...
            'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false, ...
            'checkpoint',struct('enabled',true,'file',fullfile(branchDirectory,'checkpoint.mat'), ...
            'every',Inf,'atExit',true));
        result=ipm.solve(opts,sourceFile);
        files=dir(fullfile(branchDirectory,'checkpoint_*_step*.mat'));assert(isscalar(files));
        branch=struct('newCaseId',char(result.metadata.caseId),'resultFile',char(result.metadata.resultFile), ...
            'checkpointFile',fullfile(files.folder,files.name),'absolutePhysicalTime',result.state.physicalTime, ...
            'elapsedPhysicalTime',result.state.physicalTime-epoch,'parentHistoryInherited',true);
        assert(strcmp(branch.newCaseId,registration.parentCaseId));rateScale=1;
    else
        branchFraction=1;if k==3 || k==5,branchFraction=fraction;end
        branchControls=struct('maximumSteps',controls.maximumSteps,'allowLarge',controls.allowLarge);
        if k>=4,branchControls.wenoEpsilon=commonEpsilon;end
        [branch,result]=mesh_fresh_box_branch(sourceFile,branchFraction,elapsedPhysicalTime,branchDirectory,branchControls);
        rateScale=lambda;
    end
    branch.wallSeconds=toc(timer);branch.label=labels{k};
    branch.audit=branch_audit(result,branch.absolutePhysicalTime,registration);
    terminal=ipm.output.readCheckpoint(branch.checkpointFile);t=terminal.payload.state;
    branch.audit.nativeTerminalPaired=isequal(t.rho,result.state.rho) && ...
        isequal(t.x(:),result.grid.x(:)) && isequal(t.y(:),result.grid.y(:)) && ...
        t.step==result.state.steps && t.scale.physicalTime==result.state.physicalTime && ...
        t.scale.canonicalTime==result.state.canonicalTime && ...
        strcmp(char(t.runMetadata.caseId),char(result.metadata.caseId));
    branch.audit.nativeTerminalEntireHistoryTrusted= ...
        all(ipm.output.trustedMask(terminal.payload.log.history,t.config));
    branch.audit.passed=branch.audit.passed && branch.audit.nativeTerminalPaired && ...
        branch.audit.nativeTerminalEntireHistoryTrusted;
    clear terminal t
    observation=observe(result,rateScale);clear result
    save(fullfile(branchDirectory,'protocol_observation.mat'),'observation','-v7.3');
    save(fullfile(branchDirectory,'protocol_branch_report.mat'),'branch','-v7.3');
    write_json(fullfile(branchDirectory,'protocol_branch_report.json'),branch);
    branches{k}=branch;observations{k}=observation;clear observation
    fprintf('FRESH_BOX_PROTOCOL_CASE %d/5 %s elapsed=%.12g core=%.8g/%.8g safety=%.8g passed=%d wall=%.4g\n', ...
        k,labels{k},branch.elapsedPhysicalTime,branch.audit.coreCells,branch.audit.safety,branch.audit.passed,branch.wallSeconds);
    assert(branch.audit.passed,'ipm:FreshBoxBranchGate','A branch failed endpoint/trust/resolution gates; partial files are preserved.');
    if k==2
        covariance=paired_covariance(observations{1},observations{2});
        covariance.passed=covariance.coordinateRelativeInf<=limits.covarianceCoordinateRelativeInf && ...
            max([covariance.rhoRelativeInf,covariance.rhoXRelativeInf,covariance.rhoYRelativeInf])<=limits.covarianceFieldRelativeInf && ...
            max([covariance.cLRelativeDifference,covariance.cOmegaRelativeDifference])<=limits.covarianceRateRelative;
        write_json(fullfile(outputDirectory,'full_covariance.json'),covariance);
        assert(covariance.passed,'ipm:FreshBoxCovariance','Full native/fresh covariance failed; crop cases were not launched.');
        observations{1}=[];
    end
end
natural=compare_observations(observations{2},observations{3},registration.physicalWindow,limits);
common=compare_observations(observations{4},observations{5},registration.physicalWindow,limits);
epsilonOnly=compare_observations(observations{2},observations{4},registration.physicalWindow,limits);
caseIds=cellfun(@(b)b.newCaseId,branches,'UniformOutput',false);
assert(numel(unique(caseIds))==5,'Every fresh IVP needs a different case ID.');
report=struct('registration',registration,'branches',{branches},'fullCovariance',covariance, ...
    'naturalCropDifference',natural,'commonEpsilonCropDifference',common, ...
    'fullBoxEpsilonOnlyDifference',epsilonOnly,'completed',true, ...
    'shortIntervalComparisonPassed',covariance.passed && natural.passed && common.passed, ...
    'eligibleForLongerIndependentBoxTest',large && covariance.passed && natural.passed && common.passed, ...
    'dynamicBoxConvergenceEstablished',false,'productionDomainModified',false, ...
    'interpretation','Independent late-state IVPs over one short physical interval. Public epsilon control does not hold global Lax-Friedrichs line maxima or outer closures fixed. Earlier full-box evolution and boundary error remain unvalidated.');
save(fullfile(outputDirectory,'protocol_report.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'protocol_report.json'),report);
fprintf('FRESH_BOX_PROTOCOL_COMPLETE covariance=%d natural=%d common=%d productionPromotion=0\n', ...
    covariance.passed,natural.passed,common.passed);
end

function a=branch_audit(result,absoluteTime,r)
h=result.history;m=h.mesh;
a=struct('entireHistoryTrusted',all(ipm.output.trustedMask(result)), ...
    'physicalEndpointError',abs(absoluteTime-r.absolutePhysicalTarget), ...
    'coreCells',[m.coreGridPoints(end),m.verticalCoreGridPoints(end)], ...
    'safety',m.safetyFactor(end),'stopReason',result.state.stopReason, ...
    'finitePhysicalFields',all(isfinite(result.physical.rho),'all') && ...
        all(isfinite(result.physical.rhoX),'all') && all(isfinite(result.physical.rhoY),'all'));
a.productionResolutionPassed=all(a.coreCells>=r.limits.productionMinimumCoreCells) && ...
    isfinite(a.safety) && a.safety<r.limits.productionMaximumSafety;
a.tinyFixture=~r.large;
a.passed=a.entireHistoryTrusted && a.finitePhysicalFields && ...
    a.physicalEndpointError<=r.limits.physicalEndpointAbsolute && (a.productionResolutionPassed || a.tinyFixture);
end

function o=observe(result,rateScale)
p=result.physical;h=result.history;
o=struct('x',p.x,'y',p.y,'rho',p.rho,'rhoX',p.rhoX,'rhoY',p.rhoY, ...
    'cLParentUnits',result.scale.rates.cx/rateScale,'cOmegaParentUnits',result.scale.rates.comega/rateScale, ...
    'physicalGradientMaximum',h.common.physicalRhoXInf(end), ...
    'physicalQuadraticPeak',h.common.physicalQuadraticPeak(end), ...
    'physicalCoreWidthX',h.mesh.trackedWallCoreWidth(end)/result.scale.Cx, ...
    'physicalCoreWidthY',h.mesh.trackedVerticalCoreWidth(end)/result.scale.Cy);
end

function c=paired_covariance(a,b)
assert(isequal(size(a.rho),size(b.rho)));
c=struct('coordinateRelativeInf',max(relative_inf(a.x,b.x),relative_inf(a.y,b.y)), ...
    'rhoRelativeInf',relative_inf(a.rho,b.rho),'rhoXRelativeInf',relative_inf(a.rhoX,b.rhoX), ...
    'rhoYRelativeInf',relative_inf(a.rhoY,b.rhoY), ...
    'cLRelativeDifference',relative_inf(a.cLParentUnits,b.cLParentUnits), ...
    'cOmegaRelativeDifference',relative_inf(a.cOmegaParentUnits,b.cOmegaParentUnits));
end

function c=compare_observations(a,b,window,limits)
forward=directional(a,b,window);reverse=directional(b,a,window);c=forward;
for name=fieldnames(forward)',c.(name{1})=max(forward.(name{1}),reverse.(name{1}));end
for name={'physicalGradientMaximum','physicalQuadraticPeak','physicalCoreWidthX','physicalCoreWidthY'}
    c.([name{1} 'RelativeDifference'])=relative_inf(a.(name{1}),b.(name{1}));
end
c.cLAbsoluteDifference=abs(a.cLParentUnits-b.cLParentUnits);
c.cOmegaAbsoluteDifference=abs(a.cOmegaParentUnits-b.cOmegaParentUnits);
c.cLRelativeDifference=relative_inf(a.cLParentUnits,b.cLParentUnits);
c.cOmegaRelativeDifference=relative_inf(a.cOmegaParentUnits,b.cOmegaParentUnits);
c.passed=max(c.rhoRelativeL2,c.rhoRelativeInf)<=limits.cropRhoRelativeL2Inf && ...
    max([c.rhoXRelativeL2,c.rhoXRelativeInf,c.rhoYRelativeL2,c.rhoYRelativeInf])<=limits.cropGradientRelativeL2Inf && ...
    max(c.physicalGradientMaximumRelativeDifference,c.physicalQuadraticPeakRelativeDifference)<=limits.cropPeakRelative && ...
    max(c.physicalCoreWidthXRelativeDifference,c.physicalCoreWidthYRelativeDifference)<=limits.cropPhysicalWidthRelative && ...
    c.cLAbsoluteDifference<=max(limits.cropRateAbsolute,limits.cropRateRelative*abs(a.cLParentUnits)) && ...
    c.cOmegaAbsoluteDifference<=max(limits.cropRateAbsolute,limits.cropRateRelative*abs(a.cOmegaParentUnits));
end

function c=directional(a,b,window)
xi=find(a.x>=window(1) & a.x<=window(2));yi=find(a.y>=0 & a.y<=window(3));
assert(numel(xi)>=5 && numel(yi)>=5);[X,Y]=meshgrid(a.x(xi),a.y(yi));c=struct();
for name={'rho','rhoX','rhoY'}
    field=name{1};reference=a.(field)(yi,xi);
    sampled=interp2(b.x,b.y,b.(field),X,Y,'linear');assert(all(isfinite(sampled),'all'));
    denominator=trapz(a.y(yi),trapz(a.x(xi),reference.^2,2));assert(denominator>0);
    c.([field 'RelativeL2'])=sqrt(trapz(a.y(yi),trapz(a.x(xi),(sampled-reference).^2,2))/denominator);
    c.([field 'RelativeInf'])=relative_inf(reference,sampled);
end
end

function v=relative_inf(a,b)
v=max(abs(a-b),[],'all')/max(max(abs(a),[],'all'),realmin);
end

function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
