function candidate=mesh_fresh_core_patch_candidate(designFile,yCandidateFile,outputFile,controls)
%MESH_FRESH_CORE_PATCH_CANDIDATE Real-unit paired score with transition anchor.
% Reuse only the admitted y axis/reference of the same immutable fresh case.
if nargin<4,controls=struct();end
defaults=struct('positiveFineCells',96,'coreFineCellFraction',.5,'roundingCells',40, ...
    'resolutionPadding',1.10,'anchorWarpRadius',.25);
assert(isstruct(controls) && isscalar(controls) && isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
for n=fieldnames(defaults)',if ~isfield(controls,n{1}),controls.(n{1})=defaults.(n{1});end,end
assert(~isfile(outputFile));loaded=load(designFile,'design');design=loaded.design;
loaded=load(yCandidateFile,'candidate');seed=loaded.candidate;
assert(isequaln(seed.reference,design.reference) && seed.anchorPosition==design.anchor);
dataset=design.dataset;assert(isscalar(dataset.snapshots) && dataset.snapshots.trusted);
profiles=ipm_gridlab_feature_profiles(dataset);p=profiles.records;
targetX=seed.controls.targetXCoreCells;targetY=seed.controls.targetYCoreCells;front=seed.controls.minimumXFrontCells;
assert(targetX>=21 && targetY>=21 && front>=20);
validateattributes(controls.resolutionPadding,{'numeric'},{'scalar','finite','>=',1});
spacing=min((p.safetyCoreWidthLeft+p.safetyCoreWidthRight)/targetX, ...
    2*p.leftFrontHalfWidth/front)/controls.resolutionPadding;
[x,info]=mesh_core_patch_axis(design.anchor,p.safetyCoreCenter,dataset.xLimits(2), ...
    numel(dataset.snapshots.x),spacing,controls.positiveFineCells,controls.coreFineCellFraction, ...
    controls.roundingCells,controls.anchorWarpRadius);
y=seed.candidateY(:);
limits=struct('maxAdjacentCellRatio',1.08,'maxLogSpacingCurvature',.01, ...
    'minStencilRcond',1e-9,'minQuadratureWeightRatio',1e-8);
score=ipm_gridlab_score_frozen_pair(dataset,x,y,struct('trustedOnly',true, ...
    'profiles',profiles,'meshLimits',limits,'minimumXCoreCells',targetX, ...
    'minimumYCoreCells',targetY,'minimumXFrontCells',front));
local=local_quality(score.quality.x) && local_quality(score.quality.y);
resolution=false;transfer=false;
if score.admissible
    a=score.aggregate;resolution=a.minimumXCoreCells>=targetX-1e-6 && ...
        a.minimumYCoreCells>=targetY-1e-6 && a.minimumXLeftFrontCells>=front-1e-6;
    transfer=a.worst.rhoXMaximumRelativeChange<=2e-3 && a.worst.conservationRelativeDefect<=5e-12 && ...
        a.worst.relativeRangeViolation<=2e-4;
end
anchorExact=any(x==design.anchor) && any(x==-design.anchor);
passed=score.admissible && local && resolution && transfer && anchorExact;
candidate=struct('kind','fresh_branch_core_patch_transition_anchor_candidate', ...
    'candidateX',x,'candidateY',y,'anchorPosition',design.anchor,'anchorExact',anchorExact, ...
    'reference',design.reference,'profiles',profiles,'xConstruction',info,'pairScore',score, ...
    'controls',struct('nodeCountX',numel(x),'nodeCountY',numel(y), ...
        'targetXCoreCells',targetX,'targetYCoreCells',targetY,'minimumXFrontCells',front), ...
    'corePatchControls',controls,'parentDesignFile',designFile,'yCandidateFile',yCandidateFile, ...
    'completePairScoredInOriginalUnits',true,'localQuadraturePassed',local, ...
    'resolutionPassed',resolution,'transferPassed',transfer,'frozenCandidatePassed',passed, ...
    'currentTransactionNodeCountSupported',true,'transactionReady',passed, ...
    'frozenTransferIsProductionTransaction',false,'checkpointRegridCommitted',false, ...
    'pdeAdvanced',false,'historicalFactoryReproductionClaim',false, ...
    'transactionInterpretation','Eligible only for a new measured native transaction and matched-time validation; no native post-transfer core or dynamic acceptance is inferred.');
save(outputFile,'candidate','-v7.3');
fprintf('FRESH_CORE_PATCH target=%d fine=%d fraction=%.2f radius=%.2f anchorOutsideFine=%d passed=%d\n', ...
    targetX,controls.positiveFineCells,controls.coreFineCellFraction,controls.anchorWarpRadius, ...
    info.anchorOutsideFineIntervalBeforeWarp,passed);
end
function passed=local_quality(q)
passed=q.quadratureWeightsStrictlyPositive && q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
