function design=mesh_design_fresh_core_patch(checkpointFile,resultFile,initialDataFile,outputDirectory,controls)
%MESH_DESIGN_FRESH_CORE_PATCH Native-lineage-checked core patch and exact anchor.
% The actual fresh initial axes are the immutable design reference. Reading
% native checkpoints validates signatures at their original ten threads;
% this function never restores operators, transfers a native state, or solves.
if nargin<5,controls=struct();end
controls=resolve_controls(controls);
assert(~isfolder(outputDirectory),'Use a new design output directory.');
mkdir(outputDirectory);
originalThreads=maxNumCompThreads(10);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
result=ipm.output.validate(resultFile);
assert(all(ipm.output.trustedMask(result)) && ...
    all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
assert(isequal(s.rho,result.state.rho) && isequal(s.x(:),result.grid.x(:)) && ...
    isequal(s.y(:),result.grid.y(:)) && s.step==result.state.steps && ...
    s.scale.canonicalTime==result.state.canonicalTime && ...
    s.scale.physicalTime==result.state.physicalTime && ...
    strcmp(s.runMetadata.caseId,result.metadata.caseId), ...
    'Current native checkpoint and result must match exactly.');
lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
assert(strcmp(lineage.kind,'fresh_late_physical_initial_value_branch') && ...
    ~lineage.parentHistoryInherited && ~lineage.parentCheckpointModified && ...
    result.history.common.acceptedStep(1)==0 && result.history.common.physicalTime(1)==0);
initial=load(initialDataFile,'physicalX','physicalY','physicalRho','lineage');
assert(isequaln(initial.lineage,lineage),'Fresh initial data must have this branch lineage.');
parent=ipm.output.readCheckpoint(lineage.parentCheckpoint);p=parent.payload.state;
assert(strcmp(p.runMetadata.caseId,lineage.parentCaseId) && p.step==lineage.parentStep && ...
    p.scale.canonicalTime==lineage.parentCanonicalTime && ...
    p.scale.physicalTime==lineage.absolutePhysicalEpoch && ...
    exp(p.scale.logC_l)==lineage.parentCx && exp(p.scale.logC_omega)==lineage.parentComega);
xi=lineage.initialNodeIndicesX;yi=lineage.initialNodeIndicesY;
assert(isequal(initial.physicalX,p.x(xi)/lineage.parentCx) && ...
    isequal(initial.physicalY,p.y(yi)/lineage.parentCx) && ...
    isequal(initial.physicalRho,exp(-p.scale.logC_omega)*p.rho(yi,xi)), ...
    'Stored initial axes and samples must equal the native parent crop exactly.');
anchor=s.config.scaling.transportAnchorX;
assert(anchor==lineage.physicalAnchorX && ...
    anchor==p.config.scaling.transportAnchorX/lineage.parentCx && ...
    s.scale.X_shift==0 && strcmp(s.config.scaling.lengthGauge,'transport_anchor'));
runtimeReferences=s.rescaling;
provenance=struct('freshCaseId',char(s.runMetadata.caseId), ...
    'currentCheckpoint',checkpointFile,'pairedCurrentResult',resultFile, ...
    'initialPhysicalDataFile',initialDataFile,'lineage',lineage, ...
    'nativeReadThreads',10,'nativeSignatureValidated',true, ...
    'initialSamplesExactlyReconstructedFromParent',true, ...
    'parentReferenceHistoryInherited',false, ...
    'runtimeReferencesSource','current native fresh branch; preserved for a future transaction');
reference=struct('kind','actual_immutable_fresh_initial_axes', ...
    'x',initial.physicalX(:)','y',initial.physicalY(:), ...
    'provenance',provenance,'runtimeReferences',runtimeReferences);
if numel(s.rho)>20000
    for name={'targetXCoreCells','targetYCoreCells'}
        assert(~isfield(controls,name{1}) || controls.(name{1})>=21, ...
            'Production fresh candidates retain target core >=21.');
    end
    assert(~isfield(controls,'minimumXFrontCells') || controls.minimumXFrontCells>=20);
end
clear cp s parent p initial
dataset=ipm_gridlab_collect_dataset(result,struct('trustedOnly',true,'tag','fresh_core_patch_native_terminal'));clear result
profiles=ipm_gridlab_feature_profiles(dataset);records=profiles.records;
assert(isscalar(records) && isscalar(dataset.snapshots));
design=struct('dataset',dataset,'reference',reference,'anchor',anchor,'profiles',profiles, ...
    'controls',controls,'noEllipticOperatorsBuilt',true,'noPDEAdvanced',true, ...
    'sourceCheckpoint',checkpointFile,'candidateFile',fullfile(outputDirectory,'candidate.mat'));
designFile=fullfile(outputDirectory,'design.mat');save(designFile,'design','-v7.3');
limits=struct('maxAdjacentCellRatio',1.08,'maxLogSpacingCurvature',.01, ...
    'minStencilRcond',1e-9,'minQuadratureWeightRatio',1e-8);
[yNormalized,yInfo]=ipm_gridlab_equalize_axis(reference.y/anchor, ...
    [0,records.yCoreWidth/anchor],controls.targetYCoreCells*controls.verticalResolutionPadding, ...
    struct('geometry','positive','focusCenters',0,'sigma',controls.yEqualizationSigma, ...
    'power',2,'meshLimits',limits));
y=yNormalized(:)*anchor;y(1)=reference.y(1);y(end)=reference.y(end);
% This is only a y-axis input descriptor, not an admitted x/y candidate.
candidate=struct('kind','independent_fresh_reference_y_axis_input', ...
    'reference',reference,'anchorPosition',anchor,'candidateY',y,'yEqualization',yInfo, ...
    'controls',struct('targetXCoreCells',controls.targetXCoreCells, ...
    'targetYCoreCells',controls.targetYCoreCells,'minimumXFrontCells',controls.minimumXFrontCells));
yFile=fullfile(outputDirectory,'y_axis_input.mat');save(yFile,'candidate','-v7.3');clear candidate
patchControls=struct('positiveFineCells',controls.positiveFineCells, ...
    'coreFineCellFraction',controls.coreFineCellFraction,'roundingCells',controls.roundingCells, ...
    'resolutionPadding',controls.resolutionPadding,'anchorWarpRadius',controls.anchorWarpRadius);
candidate=mesh_fresh_core_patch_candidate(designFile,yFile,design.candidateFile,patchControls);
design.frozenCandidatePassed=candidate.frozenCandidatePassed;
design.currentTransactionNodeCountSupported=candidate.currentTransactionNodeCountSupported;
design.status='scored';save(designFile,'design','-v7.3');
fprintf('FRESH_CORE_DIRECT_DESIGN ready=%d noLU=1\n',candidate.transactionReady);
end

function c=resolve_controls(c)
d=struct('targetXCoreCells',32,'targetYCoreCells',32,'minimumXFrontCells',20, ...
    'positiveFineCells',64,'coreFineCellFraction',.65,'roundingCells',40, ...
    'resolutionPadding',1.10,'verticalResolutionPadding',1.15, ...
    'yEqualizationSigma',.25,'anchorWarpRadius',.25);
assert(isstruct(c)&&isscalar(c)&&isempty(setdiff(fieldnames(c),fieldnames(d))));
for n=fieldnames(d)',if ~isfield(c,n{1}),c.(n{1})=d.(n{1});end,end
for n={'targetXCoreCells','targetYCoreCells','minimumXFrontCells','positiveFineCells','roundingCells'}
    validateattributes(c.(n{1}),{'numeric'},{'scalar','integer','positive'});
end
assert(c.targetXCoreCells>=21 && c.targetYCoreCells>=21 && c.minimumXFrontCells>=20);
validateattributes(c.resolutionPadding,{'numeric'},{'scalar','finite','>=',1});
validateattributes(c.verticalResolutionPadding,{'numeric'},{'scalar','finite','>=',1});
validateattributes(c.yEqualizationSigma,{'numeric'},{'scalar','finite','positive'});
end
