function design=mesh_fresh_grid_design(checkpointFile,resultFile,initialDataFile,outputDirectory,controls)
%MESH_FRESH_GRID_DESIGN Native-lineage-checked no-LU finite-box grid design.
% The actual fresh initial axes are the immutable design reference. Reading
% native checkpoints validates signatures at their original ten threads;
% this function never restores operators, transfers a native state, or solves.
if nargin<5,controls=struct();end
assert(~isfolder(outputDirectory),'Use a new design output directory.');
mkdir(outputDirectory);
originalThreads=maxNumCompThreads(10);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
result=ipm.output.validate(resultFile);
assert(all(ipm.output.trustedMask(result)) && ...
    all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
assert(isequal(s.rho,result.state.rho) && isequal(s.x(:),result.grid.x(:)) && ...
    isequal(s.y(:),result.grid.y(:)) && s.step==result.state.steps && ...
    s.scale.canonicalTime==result.state.canonicalTime && ...
    s.scale.physicalTime==result.state.physicalTime && ...
    strcmp(s.runMetadata.caseId,result.metadata.caseId), ...
    'Current native checkpoint and result must match exactly.');
lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
assert(strcmp(lineage.kind,'fresh_late_physical_initial_value_branch') && ...
    ~lineage.parentHistoryInherited && ~lineage.parentCheckpointModified && ...
    result.history.common.acceptedStep(1)==0 && result.history.common.physicalTime(1)==0);
initial=load(initialDataFile,'physicalX','physicalY','physicalRho','lineage');
assert(isequaln(initial.lineage,lineage),'Fresh initial data must have this branch lineage.');
parent=ipm.output.readCheckpoint(lineage.parentCheckpoint);p=parent.payload.state;
assert(strcmp(p.runMetadata.caseId,lineage.parentCaseId) && p.step==lineage.parentStep && ...
    p.scale.canonicalTime==lineage.parentCanonicalTime && ...
    p.scale.physicalTime==lineage.absolutePhysicalEpoch && ...
    exp(p.scale.logC_l)==lineage.parentCx && exp(p.scale.logC_omega)==lineage.parentComega);
xi=lineage.initialNodeIndicesX;yi=lineage.initialNodeIndicesY;
assert(isequal(initial.physicalX,p.x(xi)/lineage.parentCx) && ...
    isequal(initial.physicalY,p.y(yi)/lineage.parentCx) && ...
    isequal(initial.physicalRho,exp(-p.scale.logC_omega)*p.rho(yi,xi)), ...
    'Stored initial axes and samples must equal the native parent crop exactly.');
anchor=s.config.scaling.transportAnchorX;
assert(anchor==lineage.physicalAnchorX && ...
    anchor==p.config.scaling.transportAnchorX/lineage.parentCx && ...
    s.scale.X_shift==0 && strcmp(s.config.scaling.lengthGauge,'transport_anchor'));
runtimeReferences=s.rescaling;
provenance=struct('freshCaseId',char(s.runMetadata.caseId), ...
    'currentCheckpoint',checkpointFile,'pairedCurrentResult',resultFile, ...
    'initialPhysicalDataFile',initialDataFile,'lineage',lineage, ...
    'nativeReadThreads',10,'nativeSignatureValidated',true, ...
    'initialSamplesExactlyReconstructedFromParent',true, ...
    'parentReferenceHistoryInherited',false, ...
    'runtimeReferencesSource','current native fresh branch; preserved for a future transaction');
reference=struct('kind','actual_immutable_fresh_initial_axes', ...
    'x',initial.physicalX(:)','y',initial.physicalY(:), ...
    'provenance',provenance,'runtimeReferences',runtimeReferences);
if numel(s.rho)>20000
    for name={'targetXCoreCells','targetYCoreCells'}
        assert(~isfield(controls,name{1}) || controls.(name{1})>=21, ...
            'Production fresh candidates retain target core >=21.');
    end
    assert(~isfield(controls,'minimumXFrontCells') || controls.minimumXFrontCells>=20);
end
clear cp s parent p initial
dataset=ipm_gridlab_collect_dataset(result,struct('trustedOnly',true,'tag','fresh_box_native_paired_terminal'));
clear result
design=struct('dataset',dataset,'reference',reference,'anchor',anchor, ...
    'controls',controls,'noEllipticOperatorsBuilt',true,'noPDEAdvanced',true, ...
    'sourceCheckpoint',checkpointFile,'candidateFile',fullfile(outputDirectory,'candidate.mat'));
save(fullfile(outputDirectory,'design.mat'),'design','-v7.3');
try
    candidate=mesh_anchor_grid_candidate(dataset,reference,anchor,design.candidateFile,controls);
    design.frozenCandidatePassed=candidate.frozenCandidatePassed;
    design.currentTransactionNodeCountSupported=candidate.currentTransactionNodeCountSupported;
    design.status='scored';
catch exception
    failure=struct('identifier',exception.identifier,'message',exception.message, ...
        'stack',exception.stack,'controls',controls,'sourceCheckpoint',checkpointFile);
    save(fullfile(outputDirectory,'failure.mat'),'failure','-v7.3');
    fid=fopen(fullfile(outputDirectory,'failure.json'),'w');assert(fid>=0);
    fprintf(fid,'%s\n',jsonencode(failure,PrettyPrint=true));fclose(fid);
    design.frozenCandidatePassed=false;design.status='construction_failed';
end
save(fullfile(outputDirectory,'design.mat'),'design','-v7.3');
fprintf('FRESH_GRID_DESIGN status=%s frozen=%d noLU=1\n',design.status,design.frozenCandidatePassed);
end
