function candidate=mesh_platform_candidate(designFile,referenceFile,outputFile,controls)
%MESH_PLATFORM_CANDIDATE Move/refine the existing rounded-log fine platform.
% The immutable root remains the provenance/transfer reference. Exact x=1
% may occupy a new node index, unlike the root-index-locked equalizer family.
% Only existing grid construction/equalization/transfer routines are used.
assert(~isfile(outputFile),'Refusing to replace a frozen candidate.');
defaults=struct('positiveFineCells',96,'anchorFineCellFraction',.85, ...
    'resolutionPadding',1.10,'verticalResolutionPadding',1.15);
assert(isstruct(controls) && isscalar(controls) && ...
    isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
names=fieldnames(defaults);
for k=1:numel(names)
    if ~isfield(controls,names{k}),controls.(names{k})=defaults.(names{k});end
end
validateattributes(controls.positiveFineCells,{'numeric'},{'scalar','integer','>=',16,'<=',256});
assert(mod(controls.positiveFineCells,2)==0);
validateattributes(controls.anchorFineCellFraction,{'numeric'},{'scalar','>',0,'<',1});
validateattributes(controls.resolutionPadding,{'numeric'},{'scalar','finite','>=',1});
validateattributes(controls.verticalResolutionPadding,{'numeric'},{'scalar','finite','>=',1});
loaded=load(designFile,'design'); design=loaded.design;
loaded=load(referenceFile,'dataset'); reference=loaded.dataset;
records=design.profiles.records;
coreWidths=[records.safetyCoreWidthLeft]+[records.safetyCoreWidthRight];
frontWidths=2*[records.leftFrontHalfWidth];
spacing=min([coreWidths/design.targets.xCoreCells, ...
    frontWidths/design.targets.xFrontCells])/controls.resolutionPadding;
fineCells=controls.positiveFineCells;
anchorFineCell=round(fineCells*controls.anchorFineCellFraction);
fineInterval=1+[-anchorFineCell,fineCells-anchorFineCell]*spacing;
assert(fineInterval(1)>0 && fineInterval(2)>1);
opts=fourth_order_blowup_case('coordinated_log_anchor_F80_R20_large_box_quadrant_512', ...
    struct('saveResults',false,'makePlots',false,'verbose',false));
rootAxisReproduced=isequal(opts.customX(:),reference.snapshots(1).x(:));
assert(rootAxisReproduced,'The registered root-axis factory must reproduce the immutable reference.');
opts=rmfield(opts,{'customX','customY'});
parameters=struct('fineInterval',fineInterval,'fineCellFraction',fineCells/512, ...
    'roundingFraction',20/256,'peakCenter',1);
policy=struct('minimumStencilRcond',1e-9,'minimumQuadratureWeightRatio',1e-8, ...
    'minimumLocalQuadratureWeightRatio',.35,'maximumLocalQuadratureWeightRatio',1.65, ...
    'quadratureWarningRatio',1e-4);
[x,~,gridInfo]=fourth_order_smooth_peak_grid(opts,1,1,'coordinated_log_spacing',parameters,policy);
[anchorDistance,anchorIndex]=min(abs(x-1));
assert(anchorDistance<=256*eps(1),'The proposed fine platform must place x=1 on a node.');
beforeSnap=x(anchorIndex);x(anchorIndex)=1;x(numel(x)+1-anchorIndex)=-1;
yOptions=struct('geometry','positive','focusCenters',0, ...
    'sigma',design.options.equalizationOptions.ySigma, ...
    'power',design.options.equalizationOptions.yPower,'meshLimits',design.options.meshLimits);
[y,yInfo]=ipm_gridlab_equalize_axis(reference.snapshots(1).y, ...
    [zeros(numel(records),1),[records.yCoreWidth]'], ...
    repmat(design.targets.yCoreCells*controls.verticalResolutionPadding,numel(records),1),yOptions);
options=design.options.pairScoreOptions;options.profiles=design.profiles;
options.minimumXCoreCells=design.targets.xCoreCells;
options.minimumYCoreCells=design.targets.yCoreCells;
options.minimumXFrontCells=design.targets.xFrontCells;
options.meshLimits=design.options.meshLimits;
score=ipm_gridlab_score_frozen_pair(design.dataset,x,y,options);
localPassed=local_quality(score.quality.x) && local_quality(score.quality.y);
resolutionPassed=false;transferPassed=false;
if score.admissible && ~isempty(fieldnames(score.aggregate))
    a=score.aggregate;tolerance=1e-6;
    resolutionPassed=a.minimumXCoreCells>=design.targets.xCoreCells-tolerance && ...
        a.minimumYCoreCells>=design.targets.yCoreCells-tolerance && ...
        a.minimumXLeftFrontCells>=design.targets.xFrontCells-tolerance;
    transferPassed=a.worst.rhoXMaximumRelativeChange<=2e-3 && ...
        a.worst.conservationRelativeDefect<=5e-12 && a.worst.relativeRangeViolation<=2e-4;
end
candidate=struct('kind','ipm_longtime_moving_platform_candidate', ...
    'parentDesignFile',designFile,'referenceFile',referenceFile,'controls',controls, ...
    'candidateX',x,'candidateY',y,'anchorPosition',1, ...
    'anchorNodeIndex',anchorIndex,'positiveAnchorCellIndex',anchorIndex-(numel(x)+1)/2, ...
    'anchorNodeBeforeSnap',beforeSnap,'completeAxisRescoredAfterSnap',true, ...
    'rootAxisFactoryReproducedExactly',rootAxisReproduced, ...
    'fineInterval',fineInterval,'requestedFineSpacing',spacing, ...
    'gridConstructionInfo',gridInfo,'yEqualizationInfo',yInfo,'pairScore',score, ...
    'localQuadraturePassed',localPassed,'resolutionPassed',resolutionPassed,'transferPassed',transferPassed, ...
    'transactionReady',score.admissible && localPassed && resolutionPassed && transferPassed, ...
    'pdeAdvanced',false,'checkpointRegridCommitted',false);
save(outputFile,'candidate','-v7.3');
coreX=NaN;coreY=NaN;front=NaN;jump=NaN;
if isfield(score.aggregate,'minimumXCoreCells')
    coreX=score.aggregate.minimumXCoreCells;coreY=score.aggregate.minimumYCoreCells;
    front=score.aggregate.minimumXLeftFrontCells;jump=score.aggregate.worst.rhoXMaximumRelativeChange;
end
fprintf('MOVING_PLATFORM fine=%g spacing=%.9g anchorCell=%g ready=%d core=%.8g/%.8g front=%.8g jump=%.9g ratio=%.9g\n', ...
    fineCells,spacing,candidate.positiveAnchorCellIndex,candidate.transactionReady, ...
    coreX,coreY,front,jump, ...
    score.quality.x.maximumAdjacentCellRatio);
end

function passed=local_quality(q)
passed=q.quadratureWeightsStrictlyPositive && ...
    q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
