function report=mesh_score_hierarchical_pairs(geometryFile,sourceReviewFile,outDir)
%MESH_SCORE_HIERARCHICAL_PAIRS Score the saved ordered three, without LU/PDE.
assert(maxNumCompThreads==10&&~isfolder(outDir));mkdir(outDir);
g=load(geometryFile,'candidates','searchReport');p=g.searchReport.primaryReport.policy;
review=jsondecode(fileread(sourceReviewFile));sourceFile=review.checkpointFile;
assert(g.searchReport.fallbackUsed&&numel(g.candidates)==3);
registration=struct('kind','hierarchical_fixed_top_three_frozen_pairs_v1', ...
    'geometryFile',geometryFile,'sourceReviewFile',sourceReviewFile,'sourceFile',sourceFile, ...
    'sourceStep',review.step,'maximumPairs',3, ...
    'selection','saved ordered hierarchical candidates; no reranking or parameter changes', ...
    'minimumXCoreCells',32,'minimumYCoreCells',32,'minimumXFrontCells',20, ...
    'maximumPeakJump',.002,'maximumCumulativePeakJump',.02, ...
    'maximumMassRelativeDefect',5e-12,'maximumRelativeRangeViolation',2e-4, ...
    'noLU',true,'noFlow',true,'noPDE',true,'nativeTransactionPerformed',false, ...
    'frozenInterpolationPerformed',true,'candidateNativeCoreFloorStillRequired',31);
write_json(fullfile(outDir,'registration.json'),registration);
issues=checkcode(which(mfilename),'-id');write_json(fullfile(outDir,'checkcode.json'),issues);
assert(isempty(issues),jsonencode(issues));
profile clear;profile on;timer=tic;
source=ipm.output.readCheckpoint(sourceFile);s=source.payload.state;
r=ipm.output.validate(review.resultFile);
assert(isequaln(s.rho,r.state.rho)&&isequal(s.x,r.grid.x)&&isequal(s.y,r.grid.y)&& ...
    isequaln(source.payload.log.history,r.history)&&isequal(s.step,r.state.steps)&& ...
    s.step==review.step&&s.scale.canonicalTime==review.localCanonicalTime&& ...
    s.scale.physicalTime==review.localPhysicalTime&&strcmp(s.runMetadata.caseId,review.caseId)&& ...
    all(ipm.output.trustedMask(source.payload.log.history,s.config)));
clear r
Dx=ipm.mesh.fdMatrix(s.x,1,7);
view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx,'source',s.rho*Dx','trusted',true);
assert(isequaln(ipm.diagnostics.meshFeatureIntervals(view),g.searchReport.primaryReport.feature));
snapshot=struct('datasetIndex',1,'sourceLabel',sourceFile,'trusted',true, ...
    'rho',s.rho,'x',s.x,'y',s.y,'scale',struct('Cx',exp(s.scale.logC_l), ...
    'Cy',exp(s.scale.logC_l),'Comega',exp(s.scale.logC_omega)), ...
    'canonicalTime',s.scale.canonicalTime,'physicalTime',s.scale.physicalTime);
dataset=struct('schemaVersion',2,'kind','ipm_frozen_grid_dataset', ...
    'tag','actual_hierarchical_search_source','snapshotCount',1,'snapshots',snapshot, ...
    'xLimits',s.x([1,end]),'yLimits',s.y([1,end])');
limits=rmfield(p.qualityLimits,{'minWeightToControlWidth','maxWeightToControlWidth'});
rows=struct([]);anchor=g.searchReport.primaryReport.anchor;
for k=1:3
    axes=g.candidates(k);x=axes.x;y=axes.y;
    assert(~axes.unchanged&&numel(x)==numel(s.x)&&numel(y)==numel(s.y)&& ...
        isequal(x([1,end]),s.x([1,end]))&&isequal(y([1,end]),s.y([1,end]))&& ...
        any(x==anchor)&&any(x==-anchor));
    assert(isequaln(ipm.mesh.quality(x,7,ipm.mesh.quadrature(x)),axes.quality.x)&& ...
        isequaln(ipm.mesh.quality(y,7,ipm.mesh.quadrature(y)),axes.quality.y));
    score=ipm_gridlab_score_frozen_pair(dataset,x,y,struct('trustedOnly',true, ...
        'meshLimits',limits,'minimumXCoreCells',32,'minimumYCoreCells',32,'minimumXFrontCells',20));
    a=score.aggregate;
    gates=struct('scoreMeshAdmissible',score.admissible,'coreX',false,'coreY',false, ...
        'front',false,'peakJump',false,'cumulativePeakJump',false,'mass',false,'range',false, ...
        'localQuadratureX',local_quality(score.quality.x),'localQuadratureY',local_quality(score.quality.y));
    if score.admissible
        gates.coreX=a.minimumXCoreCells>=32-1e-6;gates.coreY=a.minimumYCoreCells>=32-1e-6;
        gates.front=a.minimumXLeftFrontCells>=20-1e-6;
        gates.peakJump=a.worst.rhoXMaximumRelativeChange<=.002;
        gates.cumulativePeakJump=review.cumulativeAbsolutePeakJump+a.worst.rhoXMaximumRelativeChange<=.02;
        gates.mass=a.worst.conservationRelativeDefect<=5e-12;
        gates.range=a.worst.relativeRangeViolation<=2e-4;
    end
    ready=all(structfun(@(v)islogical(v)&&isscalar(v)&&v,gates));
    candidate=struct('kind','campaign_bounded_paired_candidate_v1', ...
        'searchOriginKind','hierarchical_axis_search_v1','sourceGeometryFile',geometryFile, ...
        'fixedSelectionRank',k,'scheduleIndex',axes.xIndex, ...
        'transactionReady',ready,'candidateX',x,'candidateY',y,'anchorExact',true, ...
        'completePairScoredInOriginalUnits',true,'currentTransactionNodeCountSupported',true, ...
        'controls',struct('targetXCoreCells',32,'targetYCoreCells',32,'minimumXFrontCells',20), ...
        'pairScore',score,'nativeTransactionPerformed',false,'pdeAdvanced',false);
    policy=p;priorJump=review.cumulativeAbsolutePeakJump;
    candidateFile=fullfile(outDir,sprintf('candidate_%02d.mat',k));
    save(candidateFile,'candidate','axes','policy','sourceFile','priorJump','gates','-v7.3');
    row=struct('candidateFile',candidateFile,'fixedSelectionRank',k,'scheduleIndex',axes.xIndex, ...
        'parameters',g.searchReport.schedule(axes.xIndex,:), ...
        'yTrialIndex',axes.yIndex,'passed',ready,'gates',gates,'aggregate',a);
    rows=[rows,row]; %#ok<AGROW>
    write_json(fullfile(outDir,sprintf('pair_%02d.json',k)),row);
    fprintf('HIERARCHICAL_PAIR rank=%d schedule=%d ready=%d\n',k,axes.xIndex,ready);
end
report=registration;report.sourceNativeSignatureValidated=true;report.sourceResultHistoryPaired=true;
report.originalFeaturesExactlyPaired=true;report.rows=rows;report.readyCount=nnz([rows.passed]);
report.sourcePayloadUnchanged=isequaln(s,source.payload.state);assert(report.sourcePayloadUnchanged);
report.wallSeconds=toc(timer);report.completed=true;
report.firstPassingRank=find([rows.passed],1,'first');
profile off;profileInfo=profile('info');names={profileInfo.FunctionTable.FunctionName};
for forbidden={'ipm.mesh.build','ipm.output.restoreCheckpoint','ipm.evolve.flow', ...
        'ipm.field.velocity','ipm.field.poisson','ipm.evolve.advance','ipm.solve','ipm.remesh.transfer'}
    assert(~any(strcmp(names,forbidden{1})));
end
report.noLUFlowPDENativeTransfer=true;
save(fullfile(outDir,'report.mat'),'report','profileInfo','-v7.3');
write_json(fullfile(outDir,'report.json'),report);
fprintf('HIERARCHICAL_PAIRS_COMPLETE ready=%d/3 noLU=1 nativeTransactions=0\n',report.readyCount);
end
function yes=local_quality(q)
yes=q.quadratureWeightsStrictlyPositive&&q.minimumQuadratureWeightToControlWidthRatio>=.35&& ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
