function report=mesh_test_fresh_grid_tiny(outputDirectory,freshReportFile)
%MESH_TEST_FRESH_GRID_TINY Exercise full wrapper on a native identity candidate.
assert(~isfolder(outputDirectory));mkdir(outputDirectory);
originalThreads=maxNumCompThreads(10);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
branch=jsondecode(fileread(freshReportFile));cp=ipm.output.readCheckpoint(branch.checkpointFile);s=cp.payload.state;
assert(numel(s.rho)<=20000 && s.config.scaling.transportAnchorX~=1);
lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
provenance=struct('currentCheckpoint',branch.checkpointFile,'freshCaseId',char(s.runMetadata.caseId), ...
    'lineage',lineage,'initialPhysicalDataFile',fullfile(fileparts(branch.resultFile),'initial_physical_data.mat'));
candidate=struct('kind','tiny_identity_candidate_not_a_production_design', ...
    'transactionReady',true,'frozenCandidatePassed',true,'anchorExact',true, ...
    'completePairScoredInOriginalUnits',true,'currentTransactionNodeCountSupported',true, ...
    'reference',struct('provenance',provenance,'x',s.x,'y',s.y), ...
    'anchorPosition',s.config.scaling.transportAnchorX,'candidateX',s.x(:),'candidateY',s.y(:)', ...
    'controls',struct('targetXCoreCells',3,'targetYCoreCells',3,'minimumXFrontCells',2));
candidateFile=fullfile(outputDirectory,'identity_candidate.mat');save(candidateFile,'candidate','-v7.3');
clear cp s candidate
report=mesh_test_fresh_grid(branch.checkpointFile,branch.resultFile,candidateFile, ...
    fullfile(outputDirectory,'identity_smoke'),struct('elapsedPhysicalTime',.002,'maximumAdditionalSteps',32));
assert(report.passed && report.registration.tinyResolutionExemption && ...
    all(report.registration.nodeCount==[65,33]) && report.transaction.rhoXMaximumRelativeChange<1e-12);
fprintf('FRESH_GRID_WRAPPER_TINY_PASS matched=1 nativePaired=1 lineage=1 identity=1 hermite=1\n');
end
