function audit=mesh_snapshot_shape_audit(snapshots)
%MESH_SNAPSHOT_SHAPE_AUDIT Count actual paired snapshot fields, not history N.
assert(isstruct(snapshots) && isscalar(snapshots) && all(isfield(snapshots,{'rho','x','y'})) && ...
    iscell(snapshots.rho) && iscell(snapshots.x) && iscell(snapshots.y) && ...
    isequal(size(snapshots.rho),size(snapshots.x),size(snapshots.y)), ...
    'ipm:SnapshotShapeAudit','Actual snapshot cell arrays must pair.');
n=numel(snapshots.rho);nodes=zeros(n,2);fieldSizes=zeros(n,2);
for k=1:n
    x=snapshots.x{k};y=snapshots.y{k};rho=snapshots.rho{k};
    assert(isa(x,'double') && isrow(x) && ~isempty(x) && isreal(x) && all(isfinite(x)) && all(diff(x)>0) && ...
        isa(y,'double') && iscolumn(y) && ~isempty(y) && isreal(y) && all(isfinite(y)) && all(diff(y)>0) && ...
        isa(rho,'double') && ismatrix(rho) && isreal(rho) && all(isfinite(rho),'all') && ...
        isequal(size(rho),[numel(y),numel(x)]), ...
        'ipm:SnapshotShapeAudit','Snapshot %d rho does not pair with its own numerical axes.',k);
    nodes(k,:)=[numel(x),numel(y)];fieldSizes(k,:)=size(rho);
end
uniqueNodes=unique(nodes,'rows');
audit=struct('actualSnapshotCount',n,'actualNodeCounts',nodes, ...
    'actualRhoSizes',fieldSizes,'uniqueActualNodeCounts',uniqueNodes, ...
    'allActualRhoAxesPaired',true,'spansMultipleNodeCounts',size(uniqueNodes,1)>1, ...
    'usesHistoryNodeCountsAsSnapshotEvidence',false,'empty',n==0);
end
