function verdict=mesh_fresh_grid_auxiliary_verdict(smokeFile,widthAuditFile,registrationFile,outputFile)
%MESH_FRESH_GRID_AUXILIARY_VERDICT Prospectively registered observer verdict.
% Leaves the original smoke result unchanged; all non-width gates survive.
assert(~isfile(outputFile));smoke=jsondecode(fileread(smokeFile));w=jsondecode(fileread(widthAuditFile));
r=jsondecode(fileread(registrationFile));
assert(strcmp(r.kind,'prospective_same_continuous_peak_width_auxiliary_protocol_v1') && ...
    r.registeredBeforePDE && ~r.replaceLegacySmokeDecision && ...
    strcmp(r.sourceCheckpoint,smoke.registration.sourceFile) && ...
    strcmp(r.candidateFile,smoke.registration.candidateFile) && ...
    strcmp(w.smokeReportFile,smokeFile) && ~w.originalDecisionReplaced && ...
    w.nativeSignaturesValidated && ~w.ellipticOperatorsBuilt && ~w.pdeRhsEvaluated);
c=smoke.linearComparison;lim=smoke.comparisonLimits;
old=w.cases(3);new=w.cases(4);
fieldsPassed=max(c.rhoRelativeL2,c.rhoRelativeInf)<=lim.cropRhoRelativeL2Inf && ...
    max([c.rhoXRelativeL2,c.rhoXRelativeInf,c.rhoYRelativeL2,c.rhoYRelativeInf])<=lim.cropGradientRelativeL2Inf;
peaksPassed=max(c.physicalGradientMaximumRelativeDifference,c.physicalQuadraticPeakRelativeDifference)<=lim.cropPeakRelative;
ratesPassed=c.cLAbsoluteDifference<=max(lim.cropRateAbsolute,lim.cropRateRelative*abs(old.cLParentCanonicalUnits)) && ...
    c.cOmegaAbsoluteDifference<=max(lim.cropRateAbsolute,lim.cropRateRelative*abs(old.cOmegaParentCanonicalUnits));
nativePassed=smoke.transaction.passed && all(arrayfun(@(b)b.audit.passed,smoke.branches));
continuousPassed=all([w.pairs.continuousPeakYWidthRelativeDifference]<=r.maximumContinuousWidthRelativeDifference) && ...
    all([w.pairs.continuousWallWidthRelativeDifference]<=r.maximumContinuousWidthRelativeDifference);
verdict=struct('kind','separate_prospective_continuous_geometry_verdict', ...
    'registrationFile',registrationFile,'smokeFile',smokeFile,'widthAuditFile',widthAuditFile, ...
    'originalLegacySmokePassed',smoke.passed,'originalLegacyDecisionChanged',false, ...
    'nativeTransactionEndpointPrefixLineagePassed',nativePassed, ...
    'originalLinearFieldGatesPassed',fieldsPassed,'originalPeakGatesPassed',peaksPassed, ...
    'originalRateGatesPassed',ratesPassed,'zeroAndMatchedContinuousWidthGatesPassed',continuousPassed, ...
    'maximumContinuousWidthRelativeDifference',r.maximumContinuousWidthRelativeDifference, ...
    'continuousObserverAuxiliaryPassed',nativePassed && fieldsPassed && peaksPassed && ratesPassed && continuousPassed, ...
    'legacyWidthRelativeDifferences',[c.physicalCoreWidthXRelativeDifference,c.physicalCoreWidthYRelativeDifference], ...
    'matchedContinuousWidthRelativeDifferences',[w.pairs(2).continuousWallWidthRelativeDifference,w.pairs(2).continuousPeakYWidthRelativeDifference], ...
    'matchedPhysicalTimeDifference',new.localPhysicalTime-old.localPhysicalTime, ...
    'geometryUniversalPerRefinementRatioTestPassed',false,'genericFourthOrderClaim',false, ...
    'mainDomainPromotion',false,'newPDEPerformedByThisAudit',false);
fid=fopen(outputFile,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(verdict,PrettyPrint=true));
fprintf('FRESH_GRID_SEPARATE_VERDICTS legacy=%d auxiliaryC1=%d nonWidthGates=%d widthC1=%d\n', ...
    smoke.passed,verdict.continuousObserverAuxiliaryPassed,nativePassed && fieldsPassed && peaksPassed && ratesPassed,continuousPassed);
end
