function report=mesh_screen_late_box(checkpointFile,outputDirectory,boxFractions)
%MESH_SCREEN_LATE_BOX Independent static screening only; never installs a grid.
% Run serially after the coordinator allocates one q512 factorization slot.
% All thresholds below are preregistered candidate-screen criteria, not proof
% of box convergence or authorization to change the production domain.
if nargin<3
    boxFractions=[1,.3,.1,.03,.01,.003,.001];
end
validateattributes(boxFractions,{'numeric'}, ...
    {'vector','real','finite','positive','<=',1});
assert(numel(boxFractions)>=2 && boxFractions(1)==1 && ...
    all(diff(boxFractions)<0),'Use a decreasing ladder beginning with full-box control.');
assert(~isfolder(outputDirectory),'Refusing to replace a late-box screen.');
mkdir(outputDirectory);
limits=struct('maximumCoreVelocityRelativeL2',1e-3, ...
    'maximumCoreVelocityRelativeInf',1e-3, ...
    'maximumRateRelativeChange',1e-3,'maximumRateAbsoluteChange',1e-6, ...
    'maximumQuadraticPeakRelativeChange',1e-10, ...
    'maximumPeakXAbsoluteChange',1e-10, ...
    'maximumPoissonResidual',1e-8, ...
    'maximumAdjacentCellRatio',1.08,'maximumLogSpacingCurvature',.01, ...
    'minimumStencilRcond',1e-9,'minimumQuadratureWeightRatio',1e-8, ...
    'minimumLocalQuadratureRatio',.35,'maximumLocalQuadratureRatio',1.65);
registration=struct('checkpointFile',checkpointFile,'boxFractions',boxFractions, ...
    'limits',limits,'pdeStepsRequested',0,'productionDomainModified',false, ...
    'requiredDynamicEvidence', ...
    ['Matched-physical-time branches at control Delta tau .01, .05 and .2; ' ...
    'fresh roots on a fixed-inner-node box ladder with independent inner refinement ' ...
    'and CFL halving. Preserve the full no-feedback reference contract.']);
write_json(fullfile(outputDirectory,'registration.json'),registration);
screen=screen_frozen_box(checkpointFile,boxFractions, ...
    fullfile(outputDirectory,'frozen_screen.mat'));
records=screen.records; baseline=records(1);
controlPassed=baseline.coreVelocityRelativeL2<=1e-11 && ...
    baseline.coreVelocityRelativeInf<=1e-11 && ...
    baseline.cLAbsoluteChange<=max(1e-12,1e-10*abs(baseline.cL)) && ...
    baseline.cOmegaAbsoluteChange<=max(1e-12,1e-10*abs(baseline.cOmega));
assessment=cell(1,numel(records));
for k=1:numel(records)
    r=records(k);
    checks=struct('fullBoxControlPassed',controlPassed, ...
        'normalizationReferencesPreserved',r.normalizationReferencesPreserved, ...
        'velocityL2',r.coreVelocityRelativeL2<=limits.maximumCoreVelocityRelativeL2, ...
        'velocityInf',r.coreVelocityRelativeInf<=limits.maximumCoreVelocityRelativeInf, ...
        'cL',r.cLAbsoluteChange<=max(limits.maximumRateAbsoluteChange, ...
            limits.maximumRateRelativeChange*abs(baseline.cL)), ...
        'cOmega',r.cOmegaAbsoluteChange<=max(limits.maximumRateAbsoluteChange, ...
            limits.maximumRateRelativeChange*abs(baseline.cOmega)), ...
        'peak',r.quadraticPeakRelativeChange<=limits.maximumQuadraticPeakRelativeChange, ...
        'peakX',abs(r.quadraticPeakXChange)<=limits.maximumPeakXAbsoluteChange, ...
        'poisson',isfinite(r.poissonResidual) && r.poissonResidual<=limits.maximumPoissonResidual, ...
        'xQuality',mesh_passed(r.xQuality,limits), ...
        'yQuality',mesh_passed(r.yQuality,limits));
    names=fieldnames(checks); values=struct2cell(checks); passed=all([values{:}]);
    assessment{k}=struct('fraction',r.fraction,'actualXHalfWidth',r.actualXHalfWidth, ...
        'actualYMaximum',r.actualYMaximum,'checks',checks,'passed',passed, ...
        'failedChecks',{names(~cell2mat(values))},'eligibleForDynamicTest',false);
    if k>1
        assessment{k}.eligibleForDynamicTest=passed && assessment{k-1}.passed;
    end
end
assessment=[assessment{:}]; selected=find([assessment.eligibleForDynamicTest],1,'last');
status='no_crop_admitted_by_static_screen';
if ~isempty(selected), status='candidate_for_dynamic_validation_only'; end
report=struct('kind','late_box_static_preselection','registration',registration, ...
    'screen',screen,'assessment',assessment,'selectedIndex',selected, ...
    'status',status,'pdeAdvanced',false,'dynamicValidationPassed',false, ...
    'productionDomainModified',false);
save(fullfile(outputDirectory,'late_box_report.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'late_box_report.json'),report);
fprintf('LATE_BOX_STATIC status=%s selectedIndex=%s\n',status,mat2str(selected));
end

function passed=mesh_passed(q,l)
passed=q.quadratureWeightsStrictlyPositive && ...
    q.maximumAdjacentCellRatio<=l.maximumAdjacentCellRatio*(1+1e-12) && ...
    q.maximumLogSpacingCurvature<=l.maximumLogSpacingCurvature*(1+1e-12) && ...
    q.minimumStencilRcond>=l.minimumStencilRcond*(1-1e-12) && ...
    q.minimumQuadratureWeightRatio>=l.minimumQuadratureWeightRatio*(1-1e-12) && ...
    q.minimumQuadratureWeightToControlWidthRatio>=l.minimumLocalQuadratureRatio*(1-1e-12) && ...
    q.maximumQuadratureWeightToControlWidthRatio<=l.maximumLocalQuadratureRatio*(1+1e-12);
end

function write_json(file,value)
fid=fopen(file,'w'); assert(fid>=0); cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
