function report=mesh_audit_preselected_initial_probe(registrationFile,label,resultFile,checkpointFile)
%MESH_AUDIT_PRESELECTED_INITIAL_PROBE Read actual paired outputs; no PDE or LU.
assert(maxNumCompThreads==10);
q=load(registrationFile,'plans');k=find(strcmp({q.plans.label},label));assert(isscalar(k));p=q.plans(k);
result=ipm.output.validate(resultFile);
audit=mesh_audit_box_space_case(resultFile,checkpointFile, ...
    result.state.physicalTime,p.config);
m=result.metadata.autonomousMesh;h=result.history;init=m.initialization;
axes=isequal(init.sourceBaseX,p.options.customX)&&isequal(init.sourceBaseY,p.options.customY)&& ...
    isequal(init.selectedBaseX,p.options.customX)&&isequal(init.selectedBaseY,p.options.customY)&& ...
    isequal(result.grid.x,p.options.customX)&&isequal(result.grid.y,p.options.customY);
initial=isequal(result.snapshots.rho{1},p.initialRho)&&isequal(result.snapshots.x{1},p.options.customX)&& ...
    isequal(result.snapshots.y{1},p.options.customY)&&h.common.t(1)==0&&h.common.physicalTime(1)==0&& ...
    h.common.canonicalTau(1)==0&&init.selectedCandidateIndex==1&&init.audit.passed;
endpoint=result.state.steps>=1&&result.state.steps<=4&&result.state.canonicalTime==4e-5&& ...
    strcmp(result.state.stopReason,'final_time');
assert(isequaln(m.referenceFamily,p.family));
Dx=ipm.mesh.fdMatrix(result.grid.x,1,7);view=struct('rho',result.state.rho,'x',result.grid.x,'y',result.grid.y, ...
    'Dx',Dx,'source',result.state.rho*Dx','trusted',true);f=ipm.diagnostics.meshFeatureIntervals(view);
geometry=all(f.actualCoreCells>=31)&&f.leftFrontCells>=20&&result.grid.remeshCount==0;
report=struct('kind','externally_preselected_initial_native_qualification_v1','label',label,'H',p.H, ...
    'audit',audit,'sourceCandidate',p.candidateFile, ...
    'initialAndFinalAxesEqualPreselection',axes,'signedInitialSnapshotExactlyAnalytic',initial, ...
    'registeredCanonicalEndpointReached',endpoint,'endpointCoreAndFrontPassed',geometry, ...
    'endpointCore',f.actualCoreCells,'endpointFront',f.leftFrontCells,'actualSteps',result.state.steps, ...
    'physicalTime',result.state.physicalTime,'canonicalTime',result.state.canonicalTime, ...
    'fullPhysicalGradInf',h.common.physicalGradInf(end),'physicalRhoXInf',h.common.physicalRhoXInf(end), ...
    'physicalQuadraticPeak',h.common.physicalQuadraticPeak(end), ...
    'productionAnalyticFallbackIntegrated',false,'nativeLongtimeOrBoxQualified',false, ...
    'zeroTimeEvidence','Initial paired snapshot and initialization ledger signed in terminal native checkpoint; no separate zero-step CP claimed', ...
    'passed',audit.passed&&axes&&initial&&endpoint&&geometry);
end
