function report=mesh_test_fresh_grid(sourceFile,resultFile,candidateFile,outDir,controls)
%MESH_TEST_FRESH_GRID Same-count fresh-box transaction and matched-time PDE.
% A new grid transaction within the existing fresh case; no box/epoch reset.
if nargin<5,controls=struct();end
defaults=struct('elapsedPhysicalTime',.001,'maximumAdditionalSteps',64,'allowLarge',false);
assert(isstruct(controls) && isscalar(controls) && isempty(setdiff(fieldnames(controls),fieldnames(defaults))));
for n=fieldnames(defaults)',if ~isfield(controls,n{1}),controls.(n{1})=defaults.(n{1});end,end
validateattributes(controls.elapsedPhysicalTime,{'numeric'},{'scalar','finite','positive'});
validateattributes(controls.maximumAdditionalSteps,{'numeric'},{'scalar','integer','positive'});
assert(~isfolder(outDir));mkdir(outDir);
originalThreads=maxNumCompThreads(10);cleanup=onCleanup(@()maxNumCompThreads(originalThreads));
source=ipm.output.readCheckpoint(sourceFile);s=source.payload.state;
large=numel(s.rho)>20000;assert(~large || controls.allowLarge,'An allocated large-LU window is required.');
result=ipm.output.validate(resultFile);assert(native_paired(source,result));
assert(all(ipm.output.trustedMask(result)) && all(ipm.output.trustedMask(source.payload.log.history,s.config)));
loaded=load(candidateFile,'candidate');candidate=loaded.candidate;
assert(candidate.transactionReady && candidate.frozenCandidatePassed && candidate.anchorExact && ...
    candidate.completePairScoredInOriginalUnits && candidate.currentTransactionNodeCountSupported);
assert(strcmp(candidate.reference.provenance.currentCheckpoint,sourceFile) && ...
    strcmp(candidate.reference.provenance.freshCaseId,s.runMetadata.caseId));
lineage=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
assert(isequaln(lineage,candidate.reference.provenance.lineage) && ...
    strcmp(lineage.kind,'fresh_late_physical_initial_value_branch') && ...
    ~lineage.parentHistoryInherited && ~lineage.parentCheckpointModified && ...
    result.history.common.physicalTime(1)==0 && result.history.common.acceptedStep(1)==0);
initial=load(candidate.reference.provenance.initialPhysicalDataFile,'physicalX','physicalY','physicalRho','lineage');
parent=ipm.output.readCheckpoint(lineage.parentCheckpoint);p=parent.payload.state;
assert(isequaln(initial.lineage,lineage) && strcmp(p.runMetadata.caseId,lineage.parentCaseId) && ...
    p.step==lineage.parentStep && p.scale.physicalTime==lineage.absolutePhysicalEpoch && ...
    exp(p.scale.logC_l)==lineage.parentCx && exp(p.scale.logC_omega)==lineage.parentComega);
assert(isequal(initial.physicalX,p.x(lineage.initialNodeIndicesX)/lineage.parentCx) && ...
    isequal(initial.physicalY,p.y(lineage.initialNodeIndicesY)/lineage.parentCx) && ...
    isequal(initial.physicalRho,exp(-p.scale.logC_omega)*p.rho(lineage.initialNodeIndicesY,lineage.initialNodeIndicesX)));
assert(isequal(candidate.reference.x,initial.physicalX) && isequal(candidate.reference.y,initial.physicalY));
clear parent p initial
anchor=s.config.scaling.transportAnchorX;x=candidate.candidateX(:)';y=candidate.candidateY(:);
assert(anchor==lineage.physicalAnchorX && candidate.anchorPosition==anchor && ...
    any(x==anchor) && any(x==-anchor) && numel(x)==numel(s.x) && numel(y)==numel(s.y) && ...
    isequal(x([1,end]),s.x([1,end])) && isequal(y([1,end]),s.y([1,end])) && ...
    ~s.config.remesh.adaptiveRemesh && s.scale.X_shift==0);
targets=[candidate.controls.targetXCoreCells,candidate.controls.targetYCoreCells];
front=candidate.controls.minimumXFrontCells;
if large,assert(all(targets>=21) && front>=20);coreGate=max(20,targets-1);else,coreGate=max(2,targets-1);end
limits=struct('maxAdjacentCellRatio',1.08,'maxLogSpacingCurvature',.01, ...
    'minStencilRcond',1e-9,'minQuadratureWeightRatio',1e-8);
dataset=ipm_gridlab_collect_dataset(result,struct('trustedOnly',true,'tag','fresh_grid_transaction_source'));
score=ipm_gridlab_score_frozen_pair(dataset,x,y,struct('trustedOnly',true,'meshLimits',limits));
assert(score.admissible && local_quality(score.quality.x) && local_quality(score.quality.y));
a=score.aggregate;assert(a.minimumXCoreCells>=targets(1)-1e-6 && ...
    a.minimumYCoreCells>=targets(2)-1e-6 && a.minimumXLeftFrontCells>=front-1e-6 && ...
    a.worst.rhoXMaximumRelativeChange<=2e-3 && a.worst.conservationRelativeDefect<=5e-12 && ...
    a.worst.relativeRangeViolation<=2e-4);
registration=struct('kind','same_count_fresh_grid_matched_physical_smoke_v1', ...
    'sourceFile',sourceFile,'sourceResultFile',resultFile,'candidateFile',candidateFile, ...
    'lineage',lineage,'caseId',char(s.runMetadata.caseId),'sourceStep',s.step, ...
    'initialElapsedPhysicalTime',s.scale.physicalTime, ...
    'targetElapsedPhysicalTime',s.scale.physicalTime+controls.elapsedPhysicalTime, ...
    'absolutePhysicalTarget',lineage.absolutePhysicalEpoch+s.scale.physicalTime+controls.elapsedPhysicalTime, ...
    'physicalWindow',[-2,2,1]/lineage.parentCx,'threads',10,'serialLU',true, ...
    'nodeCount',[numel(x),numel(y)],'transactionCoreGate',coreGate,'leftFrontGate',front, ...
    'meshLimits',limits,'controls',controls,'large',large,'productionDomainChanged',false, ...
    'epsilonChanged',false,'physicalEndpointTolerance',1e-11,'productionCoreFloor',14, ...
    'productionSafetyCeiling',.70,'tinyResolutionExemption',~large);
write_json(fullfile(outDir,'registration.json'),registration);
save(fullfile(outDir,'registration.mat'),'registration','score','-v7.3');
clear result loaded candidate a score
opts=struct('minimumXCoreCells',coreGate(1),'minimumYCoreCells',coreGate(2), ...
    'maximumRhoXRelativeChange',2e-3,'maximumMassRelativeDefect',5e-12, ...
    'maximumRelativeRangeViolation',2e-4,'meshLimits',limits,'tag','fresh_box_nonunit_anchor_matchedtime');
timer=tic;
try
    [regridded,transaction]=ipm_gridlab_regrid_checkpoint(source,x,y,opts);
    n=regridded.payload.state;
    assert(isequaln(s.scale,n.scale) && s.step==n.step && s.normalizedTime==n.normalizedTime && ...
        isequaln(rmfield(s.rescaling,{'originIndex','pinIndex'}),rmfield(n.rescaling,{'originIndex','pinIndex'})) && ...
        isequaln(n.runMetadata.caseMetadata.latePhysicalBoxBranch,lineage) && ...
        n.config.scaling.transportAnchorX==anchor && n.config.transport.wenoEpsilon==s.config.transport.wenoEpsilon);
    assert(local_quality(transaction.xQuality) && local_quality(transaction.yQuality) && ...
        all(ipm.output.trustedMask(regridded.payload.log.history,n.config)));
    assert(isscalar(dataset.snapshots));dataset.snapshots.rho=n.rho;
    dataset.snapshots.x=n.x;dataset.snapshots.y=n.y;
    dataset.snapshots.physicalRho=n.rho/exp(n.scale.logC_omega);
    dataset.snapshots.physicalX=n.x/exp(n.scale.logC_l);
    dataset.snapshots.physicalY=n.y/exp(n.scale.logC_l);
    actual=ipm_gridlab_score_frozen_pair(dataset,n.x,n.y,struct('trustedOnly',true,'meshLimits',limits));
    assert(actual.admissible && actual.aggregate.minimumXLeftFrontCells>=front-1e-6);
    [~,regridFile]=ipm.output.writeCheckpoint(regridded,fullfile(outDir,'regrid_checkpoint.mat'));
    validated=ipm.output.readCheckpoint(regridFile);
    assert(isequal(validated.payload.state.rho,n.rho) && isequaln(validated.payload.state.scale,s.scale));
    transaction.wallSeconds=toc(timer);transaction.actualLeftFrontCells=actual.aggregate.minimumXLeftFrontCells;
    save(fullfile(outDir,'transaction_audit.mat'),'transaction','regridFile','-v7.3');
    write_json(fullfile(outDir,'transaction_audit.json'),transaction);
catch exception
    failure=struct('identifier',exception.identifier,'message',exception.message,'stack',exception.stack);
    write_json(fullfile(outDir,'transaction_failure.json'),failure);rethrow(exception);
end
fprintf('FRESH_GRID_TRANSACTION core=%.9g/%.9g front=%.9g peakJump=%.9g passed=1\n', ...
    transaction.xCoreCells,transaction.yCoreCells,transaction.actualLeftFrontCells,transaction.rhoXMaximumRelativeChange);
clear source s regridded validated n actual dataset x y
sources={sourceFile,char(regridFile)};labels={'old_grid','new_grid'};branches=cell(1,2);observations=cell(1,2);
for k=1:2
    d=fullfile(outDir,labels{k});mkdir(d);
    runOpts=struct('finalTime',Inf,'physicalFinalTime',registration.targetElapsedPhysicalTime, ...
        'maxSteps',registration.sourceStep+controls.maximumAdditionalSteps, ...
        'saveResults',true,'resultFile',fullfile(d,'result.mat'),'makePlots',false, ...
        'livePlot',false,'writeVideo',false,'verbose',false, ...
        'checkpoint',struct('enabled',true,'file',fullfile(d,'checkpoint.mat'),'every',Inf,'atExit',true));
    timer=tic;result=ipm.solve(runOpts,sources{k});wall=toc(timer);
    f=dir(fullfile(d,'checkpoint_*_step*.mat'));assert(isscalar(f));cpFile=fullfile(f.folder,f.name);
    cp=ipm.output.readCheckpoint(cpFile);terminal=cp.payload.state;h=result.history;
    cores=[min(h.mesh.coreGridPoints),min(h.mesh.verticalCoreGridPoints)];safety=max(h.mesh.safetyFactor);
    audit=struct('nativeTerminalPaired',native_paired(cp,result), ...
        'resultEntireHistoryTrusted',all(ipm.output.trustedMask(result)), ...
        'nativeEntireHistoryTrusted',all(ipm.output.trustedMask(cp.payload.log.history,terminal.config)), ...
        'physicalEndpointError',abs(result.state.physicalTime-registration.targetElapsedPhysicalTime), ...
        'stopReason',char(result.state.stopReason),'recordedHistoryMinimumCores',cores, ...
        'recordedHistoryMaximumSafety',safety,'terminalCoreCells',[h.mesh.coreGridPoints(end),h.mesh.verticalCoreGridPoints(end)], ...
        'finitePhysicalFields',all(isfinite(result.physical.rho),'all') && ...
            all(isfinite(result.physical.rhoX),'all') && all(isfinite(result.physical.rhoY),'all'), ...
        'lineagePreserved',isequaln(terminal.runMetadata.caseMetadata.latePhysicalBoxBranch,lineage) && ...
            strcmp(terminal.runMetadata.caseId,registration.caseId) && h.common.acceptedStep(1)==0 && h.common.physicalTime(1)==0);
    audit.passed=audit.nativeTerminalPaired && audit.resultEntireHistoryTrusted && audit.nativeEntireHistoryTrusted && ...
        audit.physicalEndpointError<=1e-11 && strcmp(audit.stopReason,'physical_final_time') && ...
        audit.finitePhysicalFields && audit.lineagePreserved && ...
        (~large || (all(cores>=14) && isfinite(safety) && safety<.70));
    branch=struct('checkpointFile',cpFile,'resultFile',char(result.metadata.resultFile), ...
        'label',labels{k},'wallSeconds',wall,'additionalSteps',result.state.steps-registration.sourceStep, ...
        'absolutePhysicalTime',lineage.absolutePhysicalEpoch+result.state.physicalTime,'audit',audit);
    observations{k}=observe(result,lineage.canonicalCovarianceFactor);branches{k}=branch;
    observation=observations{k};save(fullfile(d,'observation.mat'),'observation','-v7.3');
    clear result cp terminal observation
    write_json(fullfile(d,'branch_report.json'),branch);
    fprintf('FRESH_GRID_CASE %s steps=%d wall=%.4g core=%.9g/%.9g passed=%d\n', ...
        branch.label,branch.additionalSteps,wall,audit.terminalCoreCells,audit.passed);
    assert(audit.passed,'A fresh-grid branch failed; remaining work stopped with partial artifacts.');
end
comparisonLimits=struct('cropRhoRelativeL2Inf',1e-3,'cropGradientRelativeL2Inf',2e-3, ...
    'cropPeakRelative',2e-3,'cropRateRelative',2e-3,'cropRateAbsolute',1e-6,'cropPhysicalWidthRelative',5e-3);
linear=mesh_compare_fresh_box_data(observations{1},observations{2},registration.physicalWindow,comparisonLimits);
clear observations
observers=compare_space_observers(branches{1}.checkpointFile,branches{2}.checkpointFile, ...
    registration.physicalWindow,fullfile(outDir,'linear_hermite_observers.json'));
report=struct('registration',registration,'transaction',transaction,'branches',{branches}, ...
    'linearComparison',linear,'comparisonLimits',comparisonLimits,'linearHermiteObservers',observers, ...
    'completed',true,'passed',linear.passed,'productionDomainChanged',false, ...
    'interpretation','Independent same-box fresh-case grid sensitivity over a matched physical interval. Hermite is an additional observer, not a substituted decision gate.');
save(fullfile(outDir,'smoke_report.mat'),'report','-v7.3');write_json(fullfile(outDir,'smoke_report.json'),report);
fprintf('FRESH_GRID_SMOKE_COMPLETE passed=%d matchedPhysical=1 lineage=1 hermitePreserved=1\n',report.passed);
end

function yes=native_paired(cp,r)
s=cp.payload.state;
yes=isequal(s.rho,r.state.rho) && isequal(s.x(:),r.grid.x(:)) && isequal(s.y(:),r.grid.y(:)) && ...
    s.step==r.state.steps && s.scale.canonicalTime==r.state.canonicalTime && ...
    s.scale.physicalTime==r.state.physicalTime && strcmp(s.runMetadata.caseId,r.metadata.caseId);
end
function passed=local_quality(q)
passed=q.quadratureWeightsStrictlyPositive && q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
    q.maximumQuadratureWeightToControlWidthRatio<=1.65;
end
function o=observe(r,rateScale)
p=r.physical;h=r.history;
o=struct('x',p.x,'y',p.y,'rho',p.rho,'rhoX',p.rhoX,'rhoY',p.rhoY, ...
    'cLParentUnits',r.scale.rates.cx/rateScale,'cOmegaParentUnits',r.scale.rates.comega/rateScale, ...
    'physicalGradientMaximum',h.common.physicalRhoXInf(end),'physicalQuadraticPeak',h.common.physicalQuadraticPeak(end), ...
    'physicalCoreWidthX',h.mesh.trackedWallCoreWidth(end)/r.scale.Cx, ...
    'physicalCoreWidthY',h.mesh.trackedVerticalCoreWidth(end)/r.scale.Cy);
end
function write_json(path,value)
fid=fopen(path,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
