function report = mesh_compare_initial_box_summaries(summaryFile,outputFile)
%MESH_COMPARE_INITIAL_BOX_SUMMARIES Read stored axes; no operators or PDE.
assert(~isfile(outputFile),'Refusing to replace a box-summary audit.');
loaded=load(summaryFile,'screen'); screen=loaded.screen;
assert(screen.schemaVersion==4 && screen.initialRhsOnly && ...
    ~screen.solveExecuted && screen.pdeStepsExecuted==0);
reference=screen.boxes(end).configurations.wall_omega_quadratic_peak.grid;
records=cell(1,numel(screen.boxes));
for k=1:numel(screen.boxes)
    box=screen.boxes(k);
    config=box.configurations.wall_omega_quadratic_peak;
    run=box.gaugeRuns.wall_omega_quadratic_peak;
    grid=config.grid;
    records{k}=struct('halfWidth',max(abs(grid.xlim)), ...
        'cL',run.rates.c_l,'cOmega',run.rates.c_omega, ...
        'quadraticPeak',run.wallQuadraticPeak.peakValue, ...
        'peakX',run.wallQuadraticPeak.peakX, ...
        'farBoundaryMode',config.elliptic.farBoundaryMode, ...
        'sameAxesAcrossGauges',isequal(grid.customX, ...
            box.configurations.gradient_energy.grid.customX) && ...
            isequal(grid.customY,box.configurations.gradient_energy.grid.customY) && ...
            isequal(grid.customX,box.configurations.none.grid.customX) && ...
            isequal(grid.customY,box.configurations.none.grid.customY), ...
        'xPlatform',compare_axis(grid.customX,reference.customX,[.9475,1.2975]), ...
        'xInner',compare_axis(grid.customX,reference.customX,[-2,2]), ...
        'yInner',compare_axis(grid.customY,reference.customY,[0,1]), ...
        'minimumDx',min(diff(grid.customX)), ...
        'minimumDy',min(diff(grid.customY)), ...
        'xQuality',box.meshAudit.x,'yQuality',box.meshAudit.y, ...
        'originalMeshPassed',box.meshPassed);
end
report=struct('summaryFile',summaryFile,'referenceHalfWidth',1e6, ...
    'records',[records{:}],'initialRhsOnly',true,'pdeAdvanced',false, ...
    'innerNodeAbsoluteTolerance',1e-12, ...
    'interpretation','The protected x platform can match while full x/y inner grids differ; this is not fixed-inner-grid dynamical box convergence.');
save(outputFile,'report');
fid=fopen(strrep(outputFile,'.mat','.json'),'w'); assert(fid>=0);
cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
for k=1:numel(report.records)
    r=report.records(k);
    fprintf('INITIAL_BOX H=%g cl=%.14g cw=%.14g P=%.14g platform=%d fullX=%d fullY=%d Xnodes=%d/%d Ynodes=%d/%d yNearestMax=%.5g\n', ...
        r.halfWidth,r.cL,r.cOmega,r.quadraticPeak, ...
        r.xPlatform.allNodesMatch,r.xInner.allNodesMatch,r.yInner.allNodesMatch, ...
        r.xInner.nodeCount,r.xInner.referenceNodeCount, ...
        r.yInner.nodeCount,r.yInner.referenceNodeCount, ...
        r.yInner.maximumBidirectionalNearestDistance);
end
end

function record=compare_axis(axis,reference,window)
tolerance=1e-12;
a=axis(axis>=window(1)-tolerance & axis<=window(2)+tolerance); a=a(:);
b=reference(reference>=window(1)-tolerance & reference<=window(2)+tolerance); b=b(:);
assert(~isempty(a) && ~isempty(b));
distance=abs(a-b');
nearestA=min(distance,[],2); nearestB=min(distance,[],1);
sameCount=numel(a)==numel(b);
record=struct('window',window,'nodeCount',numel(a),'referenceNodeCount',numel(b), ...
    'bitwiseIdentical',isequal(a,b),'allNodesMatch',sameCount && all(nearestA<=tolerance) && all(nearestB<=tolerance), ...
    'maximumBidirectionalNearestDistance',max([nearestA;nearestB(:)]), ...
    'matchedNodeCount',nnz(nearestA<=tolerance));
end
