function report=preflight_four_to_one_initial(n,maximumTotalNodes,outputFile)
%PREFLIGHT_FOUR_TO_ONE_INITIAL Exact analytic t=0 axis screening without LU.
assert(~isfile(outputFile));
counts=[4*n+1,n+1];
opts=ipm.config.longTimeProfile(struct( ...
    'initialNodeCount',counts,'autonomousMeshVersion',5, ...
    'meshDensityVersion',2,'maximumTotalNodes',maximumTotalNodes));
config=ipm.config.resolve(opts);p=config.remesh.autonomousMesh;
x=linspace(config.grid.xlim(1),config.grid.xlim(2),counts(1));
y=linspace(0,config.grid.ymax,counts(2))';
view=analytic_view(x,y,config);
[pairs,detail]=ipm.remesh.plannedAxisPairs(view,struct('x',x,'y',y),1,p);
selected=struct('candidateIndex',NaN,'coreCells',[NaN,NaN], ...
    'frontCells',NaN,'maximumAdjacentRatio',[NaN,NaN], ...
    'registeredLevelCount',0);
for k=1:numel(pairs)
    pair=pairs(k);trial=analytic_view(pair.x,pair.y,config);
    feature=ipm.diagnostics.meshFeatureIntervals(trial);
    if any(feature.actualCoreCells<p.transactionMinimumCoreCells) || ...
            feature.leftFrontCells<p.minimumFrontCells
        continue
    end
    family=ipm.remesh.referenceAxisFamily(pair.x,pair.y,1,p);
    selected=struct('candidateIndex',k,'coreCells',feature.actualCoreCells, ...
        'frontCells',feature.leftFrontCells, ...
        'maximumAdjacentRatio', ...
        [pair.quality.x.maximumAdjacentCellRatio, ...
         pair.quality.y.maximumAdjacentCellRatio], ...
        'registeredLevelCount',numel(family.members));
    break
end
report=struct('kind','four_to_one_original_t0_no_lu_preflight_v1', ...
    'initialNodeCount',counts,'maximumTotalNodes',maximumTotalNodes, ...
    'candidateCount',numel(pairs),'planningStatus',detail.status, ...
    'selected',selected,'qualified',isfinite(selected.candidateIndex), ...
    'noLU',true,'noFlow',true,'noNativeTransfer',true);
fid=fopen(outputFile,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('T0_FOUR_TO_ONE n=%d initial=%dx%d candidates=%d qualified=%d core=%.3f/%.3f ratio=%.6f/%.6f levels=%d\n', ...
    n,counts,numel(pairs),report.qualified,selected.coreCells, ...
    selected.maximumAdjacentRatio,selected.registeredLevelCount);
end

function view=analytic_view(x,y,c)
[X,Y]=meshgrid(x,y);
ops=struct('X',X,'Y',Y,'nx',numel(x),'ny',numel(y), ...
    'symmetryMode',c.physics.symmetryMode);
rho=ipm.field.initialDensity(ops,c.physics);
Dx=ipm.mesh.fdMatrix(x,1,7);
view=struct('rho',rho,'x',x,'y',y,'Dx',Dx, ...
    'source',rho*Dx','trusted',true);
end
