function report=replay_requested_alternative_transfer(sourceCheckpoint, ...
        laterCheckpoint,outputDirectory)
%REPLAY_REQUESTED_ALTERNATIVE_TRANSFER Reproduce the next actual mesh
% request from a signed checkpoint, then audit two alternative real-field
% transfers at that exact accepted source. No transaction is committed.
assert(~isfolder(outputDirectory));
earlier=ipm.output.readCheckpoint(sourceCheckpoint);
later=ipm.output.readCheckpoint(laterCheckpoint);
original=later.payload.state.runMetadata.autonomousMesh.transactions(end);
assert(earlier.payload.state.step<original.sourceStep && ...
    earlier.payload.state.remeshCount==original.sourceRemeshCount && ...
    all(ipm.output.trustedMask(earlier.payload.log.history, ...
        earlier.payload.state.config)));
[state,~,~]=ipm.output.restoreCheckpoint(earlier,struct());
clear earlier later
plan=[];
while state.step<original.sourceStep
    [state,stopReason,plan]=ipm.evolve.advance(state);
    assert(isempty(stopReason),'ipm:AlternativeReplayStopped');
    if ~isempty(plan),break;end
end
assert(~isempty(plan) && plan.requested && ...
    state.step==original.sourceStep && ...
    state.scale.canonicalTime==original.sourceCanonicalTime && ...
    isequaln(plan.coreCells,original.controllerDecision.coreCells) && ...
    strcmp(plan.reason,original.controllerDecision.reason), ...
    'ipm:AlternativeReplaySourceMismatch');
indices=[plan.candidates.xIndex];
fprintf('REQUEST_CANDIDATES source=%.9f step=%d xIndices=%s yIndices=%s\n', ...
    state.scale.canonicalTime,state.step,mat2str(indices), ...
    mat2str([plan.candidates.yIndex]));
selected=find(indices==82,1);alternative=find(indices==90,1);
assert(~isempty(selected)&&~isempty(alternative));
source=state;source.ops=rmfield(source.ops,'poisson');
clear state
policy=source.config.remesh.autonomousMesh;
ledger=source.runMetadata.autonomousMesh;
rows=struct([]);
for index=[selected,alternative]
    pair=plan.candidates(index);
    proposal=struct('x',pair.x,'y',pair.y, ...
        'referenceFamily',ledger.referenceFamily, ...
        'sourceLevelId',ledger.currentLevelId, ...
        'targetLevelId',pair.nodeFamilyIndex);
    trial=source;
    [trial.rho,trial.ops]=ipm.remesh.transfer( ...
        source.rho,source.ops,source.config,proposal);
    audit=ipm.remesh.auditCandidate(source,trial,policy, ...
        ledger.cumulativeAbsolutePeakJump);
    postFlowPassed=false;postSafety=NaN;
    if audit.passed
        [~,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
        postSafety=trial.flow.safetyFactor;
        postFlowPassed=ipm.evolve.isFinite(trial) && ...
            postSafety<policy.maximumSafety && ...
            all([trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints] ...
                >=policy.transactionMinimumCoreCells);
    end
    row=struct('candidateIndex',index,'xScheduleIndex',pair.xIndex, ...
        'yTrialIndex',pair.yIndex, ...
        'geometryCoreCells',pair.predictedCells(1:2), ...
        'geometryMaxAdjacentRatio',max( ...
            pair.quality.x.maximumAdjacentCellRatio, ...
            pair.quality.y.maximumAdjacentCellRatio), ...
        'nativeAuditPassed',audit.passed, ...
        'nativeAuditReasons',{audit.reasons}, ...
        'actualCoreCells',audit.coreCells, ...
        'actualFrontCells',audit.leftFrontCells, ...
        'relativePeakJump',audit.relativePeakJump, ...
        'massRelativeDefect',audit.massRelativeDefect, ...
        'relativeRangeViolation',audit.relativeRangeViolation, ...
        'postTransferFlowPassed',postFlowPassed, ...
        'postTransferSafety',postSafety);
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
    clear trial audit proposal
end
signedSelectedEqual=isequaln( ...
    rows(1).actualCoreCells,original.coreCells) && ...
    rows(1).relativePeakJump==original.relativePeakJump && ...
    rows(1).massRelativeDefect==original.massRelativeDefect && ...
    rows(1).relativeRangeViolation==original.relativeRangeViolation;
assert(signedSelectedEqual && all([rows.nativeAuditPassed]) && ...
    all([rows.postTransferFlowPassed]), ...
    'ipm:AlternativeReplayAuditMismatch');
report=struct('kind','requested_source_alternative_transfer_replay_v1', ...
    'sourceCheckpoint',sourceCheckpoint, ...
    'signedLaterCheckpoint',laterCheckpoint, ...
    'sourceStep',source.step,'sourceTau',source.scale.canonicalTime, ...
    'requestReason',plan.reason, ...
    'sourceDecisionMatchesSignedTransaction',true, ...
    'selectedAuditMatchesSignedTransaction',signedSelectedEqual, ...
    'pdeAdvancedOnlyToRequest',true, ...
    'candidateTransactionCommitted',false, ...
    'futureCandidateLifetimeCertified',false, ...
    'rows',{rows});
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
for row=rows
    fprintf('REQUEST_TRANSFER x=%d actualCore=%.3f/%.3f ratio=%.6f jump=%.3e\n', ...
        row.xScheduleIndex,row.actualCoreCells,row.geometryMaxAdjacentRatio, ...
        row.relativePeakJump);
end
end
