function report=rollout_cross_level_mesh_interval(beforeCheckpoint, ...
        afterCheckpoint,transactionIndex,alternativeIndex,outputDirectory)
%ROLLOUT_CROSS_LEVEL_MESH_INTERVAL Isolated true-PDE counterfactual.
% The registered cross-level axes are transferred and audited on the true
% source state. A local research lineage allows the unmodified native step
% and planner to run to the next request. No native checkpoint is written.
assert(~isfolder(outputDirectory) && maxNumCompThreads==10);
before=ipm.output.readCheckpoint(beforeCheckpoint);
after=ipm.output.readCheckpoint(afterCheckpoint);
b=before.payload.state;a=after.payload.state;
assert(all(ipm.output.trustedMask(before.payload.log.history,b.config)) && ...
    all(ipm.output.trustedMask(after.payload.log.history,a.config)) && ...
    strcmp(b.runMetadata.caseId,a.runMetadata.caseId));
ledger=a.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>transactionIndex && ...
    b.step<ledger(transactionIndex).sourceStep);
signed=ledger(transactionIndex);baselineNext=ledger(transactionIndex+1);
[source,~,~]=ipm.output.restoreCheckpoint(before,struct());
clear before after a b
plan=[];
while source.step<signed.sourceStep
    [source,reason,plan]=ipm.evolve.advance(source);
    assert(isempty(reason),'ipm:CrossLevelRolloutReplayStopped');
    if ~isempty(plan),break;end
end
assert(~isempty(plan) && plan.requested && ...
    source.step==signed.sourceStep && ...
    source.scale.canonicalTime==signed.sourceCanonicalTime && ...
    isequaln(plan.coreCells,signed.controllerDecision.coreCells) && ...
    strcmp(plan.reason,signed.controllerDecision.reason) && ...
    alternativeIndex>1 && alternativeIndex<=numel(plan.candidates), ...
    'ipm:CrossLevelRolloutSourceMismatch');
p=plan.candidates(alternativeIndex);
assert(p.targetLevelId~=plan.sourceLevelId && ...
    max(p.quality.x.maximumAdjacentCellRatio, ...
        p.quality.y.maximumAdjacentCellRatio)<= ...
        source.config.remesh.autonomousMesh.qualityLimits.maxAdjacentCellRatio);
policy=source.config.remesh.autonomousMesh;
source.ops=rmfield(source.ops,'poisson');
proposal=struct('x',p.x,'y',p.y, ...
    'referenceFamily',source.runMetadata.autonomousMesh.referenceFamily, ...
    'sourceLevelId',plan.sourceLevelId, ...
    'targetLevelId',p.targetLevelId);
trial=source;clock=tic;
[trial.rho,trial.ops]=ipm.remesh.transfer( ...
    source.rho,source.ops,source.config,proposal);
transferSeconds=toc(clock);
audit=ipm.remesh.auditCandidate(source,trial,policy, ...
    source.runMetadata.autonomousMesh.cumulativeAbsolutePeakJump);
assert(audit.passed,'ipm:CrossLevelRolloutTransferRejected');
clock=tic;
[rhoRate,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
flowSeconds=toc(clock);
assert(ipm.evolve.isFinite(trial) && ...
    trial.flow.safetyFactor<policy.maximumSafety && ...
    all([trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints] ...
    >=policy.transactionMinimumCoreCells), ...
    'ipm:CrossLevelRolloutPostFlowRejected');

% Only the local state receives this accurately measured but UNSIGNED
% research transaction. Preserve the native struct schema for planning.
memory=source.runMetadata.autonomousMesh;
synthetic=signed;names=fieldnames(audit);
assert(all(isfield(synthetic,names)), ...
    'ipm:CrossLevelRolloutLedgerSchemaMismatch');
for j=1:numel(names),synthetic.(names{j})=audit.(names{j});end
synthetic.candidateIndex=alternativeIndex;
synthetic.controllerDecision=rmfield(plan,{'candidates','axisReport'});
memory.transactions(end+1)=synthetic;
memory.currentLevelId=p.targetLevelId;
memory.cumulativeAbsolutePeakJump=sum([memory.transactions.relativePeakJump]);
trial.ops.remeshCount=source.ops.remeshCount+1;
trial.runMetadata.autonomousMesh=memory;
trial.runMetadata.autonomousMesh= ...
    ipm.remesh.controllerTelemetry(memory,trial,policy);
trial.rhsCache=ipm.evolve.makeRhsCache( ...
    trial.rho,rhoRate,trial.flow,trial.ops,trial.scale);
assert(ipm.evolve.isFinite(trial));
sourceTau=trial.scale.canonicalTime;sourceStep=trial.step;
fprintf('CROSS_LEVEL_ROLLOUT_START tau=%.9f nodes=%d core=%.3f/%.3f baselineNext=%.9f\n', ...
    sourceTau,trial.ops.nx*trial.ops.ny,trial.flow.coreGridPoints, ...
    trial.flow.verticalCoreGridPoints,baselineNext.sourceCanonicalTime);
clear source rhoRate proposal p memory synthetic audit

clock=tic;nextProgress=sourceTau+.05;terminalReason='';nextPlan=[];
while trial.scale.canonicalTime<13.5 && trial.step<sourceStep+3000
    [trial,stepStop,nextPlan]=ipm.evolve.advance(trial);
    if ~isempty(stepStop),terminalReason=stepStop;break;end
    if ~isempty(nextPlan)
        assert(nextPlan.requested);
        terminalReason='next_mesh_requested';break
    end
    if trial.scale.canonicalTime>=nextProgress
        fprintf('CROSS_LEVEL_ROLLOUT_PROGRESS tau=%.6f step=%d core=%.3f/%.3f\n', ...
            trial.scale.canonicalTime,trial.step, ...
            trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints);
        nextProgress=nextProgress+.05;
    end
end
if isempty(terminalReason),terminalReason='censored_at_time_or_step_cap';end
report=struct('kind','research_only_cross_level_actual_interval_v1', ...
    'beforeCheckpoint',beforeCheckpoint,'afterCheckpoint',afterCheckpoint, ...
    'transactionIndex',transactionIndex, ...
    'acceptedAlternativeCandidateIndex',alternativeIndex, ...
    'acceptedAlternativeTargetLevelId',trial.runMetadata.autonomousMesh.currentLevelId, ...
    'sourceDecisionEqualsSigned',true, ...
    'alternativeTransferAndPostFlowPassed',true, ...
    'sourceStep',sourceStep,'sourceTau',sourceTau, ...
    'baselineSignedNextRequestTau',baselineNext.sourceCanonicalTime, ...
    'baselineSignedInterval',baselineNext.sourceCanonicalTime-sourceTau, ...
    'alternativeTerminalTau',trial.scale.canonicalTime, ...
    'alternativeInterval',trial.scale.canonicalTime-sourceTau, ...
    'alternativeMinusBaselineInterval',trial.scale.canonicalTime-baselineNext.sourceCanonicalTime, ...
    'alternativeAcceptedSteps',trial.step-sourceStep, ...
    'alternativeWallSeconds',toc(clock), ...
    'transferSeconds',transferSeconds,'initialFlowSeconds',flowSeconds, ...
    'terminalReason',terminalReason, ...
    'terminalCoreCells',[trial.flow.coreGridPoints,trial.flow.verticalCoreGridPoints], ...
    'terminalNodeCount',[trial.ops.nx,trial.ops.ny], ...
    'syntheticResearchLedgerUsed',true, ...
    'nativeCheckpointWritten',false, ...
    'originalLineageOrAccuracyCertified',false);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('CROSS_LEVEL_ROLLOUT_FINAL reason=%s baseline=%.9f alternative=%.9f steps=%d wall=%.1fs\n', ...
    terminalReason,baselineNext.sourceCanonicalTime, ...
    trial.scale.canonicalTime,trial.step-sourceStep,report.alternativeWallSeconds);
end
