function report=rollout_alternative_mesh_interval(sourceCheckpoint, ...
        laterCheckpoint,outputDirectory)
%ROLLOUT_ALTERNATIVE_MESH_INTERVAL One explicitly counterfactual mesh choice.
% Replay the signed source, reorder only its three registered source-level
% candidates, accept X=90, and stop at the next mesh request. Never serialize
% this altered lineage as an original native checkpoint or result.
assert(~isfolder(outputDirectory));
earlier=ipm.output.readCheckpoint(sourceCheckpoint);
later=ipm.output.readCheckpoint(laterCheckpoint);
ledger=later.payload.state.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>=36 && earlier.payload.state.step<ledger(35).sourceStep);
[state,~,~]=ipm.output.restoreCheckpoint(earlier,struct());
clear earlier later
plan=[];
while state.step<ledger(35).sourceStep
    [state,stopReason,plan]=ipm.evolve.advance(state);
    assert(isempty(stopReason),'ipm:AlternativeRolloutReplayStopped');
    if ~isempty(plan),break;end
end
assert(~isempty(plan) && plan.requested && ...
    state.step==ledger(35).sourceStep && ...
    state.scale.canonicalTime==ledger(35).sourceCanonicalTime && ...
    isequaln(plan.coreCells,ledger(35).controllerDecision.coreCells), ...
    'ipm:AlternativeRolloutReplayMismatch');
e=plan.axisSearchEvidence;
n=numel(plan.candidates);
assert(n==numel(e.candidates) && ...
    isequal(e.filteredCandidateIndices,1:n) && n>=3 && ...
    isequal([plan.candidates(1:3).xIndex],[82,81,90]) && ...
    all([plan.candidates(1:3).targetLevelId]==plan.sourceLevelId));
order=[3,1,2,4:n];
plan.candidates=plan.candidates(order);e.candidates=e.candidates(order);
for k=1:3
    e.candidates(k).localPairIndex=k;
    plan.candidates(k).localPairIndex=k;
    plan.candidates(k).searchDescriptor=e.candidates(k);
end
e.filteredCandidateIndices=find(~[e.candidates.unchanged]);
plan.axisSearchEvidence=e;
state.runMetadata.autonomousMesh.lastDecision= ...
    rmfield(plan,{'candidates','axisReport'});
state.ops=rmfield(state.ops,'poisson');
[state,success,attempts]=ipm.evolve.applyAutonomousMesh(state,plan);
assert(success && numel(attempts)==1 && ...
    attempts(1).passed && ...
    attempts(1).searchDescriptor.xScheduleIndex==90 && ...
    state.ops.remeshCount==35, ...
    'ipm:AlternativeRolloutTransferRejected');
firstTau=state.scale.canonicalTime;
nextProgress=firstTau+.05;
reason='censored_at_tau_12p6';nextPlan=[];
while state.scale.canonicalTime<12.6 && state.step<ledger(35).sourceStep+2000
    [state,stepStop,nextPlan]=ipm.evolve.advance(state);
    if ~isempty(stepStop),reason=stepStop;break;end
    if ~isempty(nextPlan),reason='next_mesh_requested';break;end
    if state.scale.canonicalTime>=nextProgress
        fprintf('ALT_MESH_ROLLOUT tau=%.6f x/y=%.3f/%.3f\n', ...
            state.scale.canonicalTime,state.flow.coreGridPoints, ...
            state.flow.verticalCoreGridPoints);
        nextProgress=nextProgress+.05;
    end
end
alternativeTau=state.scale.canonicalTime;
baselineTau=ledger(36).sourceCanonicalTime;
report=struct('kind','research_only_alternative_mesh_interval_v1', ...
    'sourceCheckpoint',sourceCheckpoint, ...
    'signedLaterCheckpoint',laterCheckpoint, ...
    'sourceStep',ledger(35).sourceStep, ...
    'sourceTau',firstTau,'acceptedAlternativeXScheduleIndex',90, ...
    'alternativeActualCoreAtTransfer',attempts(1).audit.coreCells, ...
    'baselineSignedNextRequestTau',baselineTau, ...
    'baselineSignedInterval',baselineTau-firstTau, ...
    'alternativeNextRequestTau',alternativeTau, ...
    'alternativeInterval',alternativeTau-firstTau, ...
    'alternativeMinusBaselineInterval',alternativeTau-baselineTau, ...
    'terminalStep',state.step,'terminalReason',reason, ...
    'terminalCoreCells',[state.flow.coreGridPoints, ...
        state.flow.verticalCoreGridPoints], ...
    'researchOnlyCandidateOrderOverride',true, ...
    'nativeCheckpointWritten',false, ...
    'originalLineageOrAccuracyCertified',false);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('ALT_MESH_FINAL reason=%s baseline=%.9f alternate=%.9f delta=%.6f\n', ...
    reason,baselineTau,alternativeTau,alternativeTau-baselineTau);
end
