function report=run_v5_native_continuation(checkpointFile,outputDirectory,targetTau,maximumSteps)
%RUN_V5_NATIVE_CONTINUATION Extend one validated original-t0 version-5 run.
% The source checkpoint and its numerical settings stay immutable. A new
% output directory records the resumed trajectory and its validation.
assert(~isfolder(outputDirectory),'ipm:V5ContinuationOutputExists');
validateattributes(targetTau,{'numeric'},{'real','scalar','finite','positive'});
validateattributes(maximumSteps,{'numeric'},{'real','scalar','finite','integer','positive'});
source=ipm.output.readCheckpoint(checkpointFile);
state=source.payload.state;
assert(all(ipm.output.trustedMask(source.payload.log.history,state.config)), ...
    'ipm:V5ContinuationUntrustedHistory');
assert(state.runMetadata.autonomousMesh.version==5&& ...
    targetTau>state.scale.canonicalTime&&maximumSteps>state.step, ...
    'ipm:V5ContinuationSource');
mkdir(outputDirectory);
resume=struct('finalTime',targetTau,'maxSteps',maximumSteps, ...
    'saveResults',true,'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'verbose',false,'checkpoint',struct('enabled',true, ...
        'file',fullfile(outputDirectory,'checkpoint.mat'), ...
        'every',.1,'atExit',true));
result=ipm.solve(resume,checkpointFile);
validated=ipm.output.validate(result);
assert(validated.state.steps==result.state.steps&& ...
    result.state.steps>state.step&& ...
    result.state.canonicalTime>state.scale.canonicalTime);
lastFile=char(result.metadata.latestCheckpointFile);
last=ipm.output.readCheckpoint(lastFile);
accepted=last.payload.state;
assert(accepted.step==result.state.steps&& ...
    accepted.runMetadata.autonomousMesh.version==5);
report=struct('kind','v5_native_continuation_v1', ...
    'sourceCheckpoint',checkpointFile,'outputDirectory',outputDirectory, ...
    'sourceStep',state.step,'sourceTau',state.scale.canonicalTime, ...
    'targetTau',targetTau,'acceptedStep',accepted.step, ...
    'acceptedTau',accepted.scale.canonicalTime, ...
    'nodeCount',[numel(accepted.x),numel(accepted.y)], ...
    'remeshCount',accepted.remeshCount, ...
    'stopReason',char(result.state.stopReason), ...
    'latestCheckpoint',lastFile,'resultValidated',true, ...
    'checkpointValidated',true);
file=fullfile(outputDirectory,'continuation_report.json');
fid=fopen(file,'w');assert(fid>=0);closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('V5_CONTINUATION tau=%.9f->%.9f step=%d->%d remesh=%d n=%dx%d stop=%s\n', ...
    report.sourceTau,report.acceptedTau,report.sourceStep, ...
    report.acceptedStep,report.remeshCount,report.nodeCount(1), ...
    report.nodeCount(2),report.stopReason);
end
