function report=run_shadow_resume_smoke(sourceDirectory,outputDirectory,sourceStep,horizon)
%RUN_SHADOW_RESUME_SMOKE Advance a signed early H8 checkpoint on the isolated
% observer branch, then validate the written native result and checkpoint.
assert(~isfolder(outputDirectory));
if nargin<3,sourceStep=58;end
if nargin<4,horizon=.02;end
files=dir(fullfile(sourceDirectory,sprintf('*step%010d.mat',sourceStep)));
assert(numel(files)==1);
source=fullfile(files.folder,files.name);
cp=ipm.output.readCheckpoint(source);s=cp.payload.state;
assert(s.remeshCount>=0 && s.config.remesh.autonomousMesh.version==4);
mkdir(outputDirectory);
overrides=struct('finalTime',s.scale.canonicalTime+horizon, ...
    'maxSteps',s.step+300,'saveResults',true, ...
    'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'makePlots',false,'verbose',false, ...
    'checkpoint',struct('enabled',true, ...
        'file',fullfile(outputDirectory,'checkpoint.mat'), ...
        'every',.01,'atExit',true));
result=ipm.solve(overrides,source);
assert(strcmp(result.state.stopReason,'final_time') && ...
    isfield(result.metadata,'continuousVerticalShadow') && ...
    result.metadata.continuousVerticalShadow.observations>=4);
assert(~isfield(result.metadata,'continuousVerticalShadowFailure'));
ipm.output.validate(result);
terminal=ipm.output.readCheckpoint(result.metadata.latestCheckpointFile);
assert(terminal.payload.state.step==result.state.steps && ...
    terminal.payload.state.runMetadata.continuousVerticalShadow.observations== ...
    result.metadata.continuousVerticalShadow.observations);
q=result.metadata.continuousVerticalShadow;
report=struct('kind','isolated_native_shadow_resume_smoke_v1', ...
    'sourceCheckpoint',source,'sourceStep',s.step, ...
    'terminalStep',result.state.steps, ...
    'terminalTau',result.state.canonicalTime, ...
    'stopReason',result.state.stopReason,'observations',q.observations, ...
    'differentRequests',q.differentRequests, ...
    'maximumRelativeCellGap',q.maximumRelativeCellGap, ...
    'validatedResult',true,'validatedTerminalCheckpoint',true, ...
    'originalLongRunsUnchanged',true);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('SHADOW_NATIVE tau=%.6f steps=%d observations=%d gap=%.3e\n', ...
    report.terminalTau,report.terminalStep,report.observations,report.maximumRelativeCellGap);
end
