function report=score_v5_frozen_growth(checkpointFile,outputFile,requestedFactors)
%SCORE_V5_FROZEN_GROWTH Independent no-LU forward/round-trip pair screen.
% This cannot certify the native transfer, but rejects poor frozen pairs.
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
if nargin<3,requestedFactors=[3,2];end
assert(isequal(size(requestedFactors),[1,2]) && ...
    all(isfinite(requestedFactors)) && all(requestedFactors>=1) && ...
    all(requestedFactors==fix(requestedFactors)));
assert(all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
initial=[s.config.grid.nx,s.config.grid.ny];
policy=ipm.config.autonomousMeshPolicy(struct('version',5, ...
    'nodeFamily',struct('maximumTotalNodes',1000000, ...
    'initialNodeCount',initial)));
root=s.runMetadata.autonomousMesh.referenceFamily;
family=ipm.remesh.referenceAxisFamily(root.rootX,root.rootY, ...
    s.config.scaling.transportAnchorX,policy);
factors=vertcat(family.members.cellFactors);
id=find(all(factors==requestedFactors,2));assert(isscalar(id));
member=family.members(id);
Dx=ipm.mesh.fdMatrix(s.x,1,7);
view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx, ...
    'source',s.rho*Dx','trusted',true);
[candidates,~,~]=ipm.remesh.hierarchicalAxisPairs(view, ...
    struct('x',member.baseX,'y',member.baseY), ...
    s.config.scaling.transportAnchorX,policy,policy.nodeFamily.maximumTotalNodes);
assert(~isempty(candidates));c=candidates(1);
snapshot=struct('datasetIndex',1,'sourceLabel',checkpointFile,'trusted',true, ...
    'rho',s.rho,'x',s.x,'y',s.y, ...
    'scale',struct('Cx',exp(s.scale.logC_l), ...
        'Cy',exp(s.scale.logC_l),'Comega',exp(s.scale.logC_omega)), ...
    'canonicalTime',s.scale.canonicalTime, ...
    'physicalTime',s.scale.physicalTime);
dataset=struct('schemaVersion',2,'kind','ipm_frozen_grid_dataset', ...
    'tag','v5_original_zero_directional_screen','snapshotCount',1, ...
    'snapshots',snapshot,'xLimits',s.x([1,end]),'yLimits',s.y([1,end])');
limits=rmfield(policy.qualityLimits, ...
    {'minWeightToControlWidth','maxWeightToControlWidth'});
score=ipm_gridlab_score_frozen_pair(dataset,c.x,c.y,struct( ...
    'trustedOnly',true,'meshLimits',limits, ...
    'minimumXCoreCells',32,'minimumYCoreCells',32, ...
    'minimumXFrontCells',20));
assert(score.admissible);
a=score.aggregate;
report=struct('kind','v5_frozen_directional_pair_screen_v1', ...
    'sourceCheckpoint',checkpointFile,'sourceStep',s.step, ...
    'sourceCanonicalTime',s.scale.canonicalTime, ...
    'sourceNodeCount',[numel(s.x),numel(s.y)], ...
    'targetCellFactors',requestedFactors, ...
    'targetNodeCount',[numel(c.x),numel(c.y)], ...
    'maximumAdjacentRatio',max(c.quality.x.maximumAdjacentCellRatio, ...
        c.quality.y.maximumAdjacentCellRatio), ...
    'scoreAdmissible',score.admissible, ...
    'minimumXCoreCells',a.minimumXCoreCells, ...
    'minimumYCoreCells',a.minimumYCoreCells, ...
    'minimumXFrontCells',a.minimumXLeftFrontCells, ...
    'relativePeakJump',a.worst.rhoXMaximumRelativeChange, ...
    'relativeConservationDefect',a.worst.conservationRelativeDefect, ...
    'relativeRangeViolation',a.worst.relativeRangeViolation, ...
    'noLU',true,'noPDE',true,'nativeTransferPerformed',false);
fprintf('V5_FROZEN_SCORE n=%dx%d ratio=%.9f peak=%.3e mass=%.3e range=%.3e\n', ...
    report.targetNodeCount(1),report.targetNodeCount(2), ...
    report.maximumAdjacentRatio,report.relativePeakJump, ...
    report.relativeConservationDefect,report.relativeRangeViolation);
if nargin>=2&&~isempty(outputFile)
    assert(~isfile(outputFile));fid=fopen(outputFile,'w');assert(fid>=0);
    closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
end
