function report = screen_frozen_box(checkpointFile,boxFractions,outputFile)
%SCREEN_FROZEN_BOX Frozen-field truncation sensitivity; no time evolution.
% Crops only existing outer nodes, preserving every common inner node.
% This is an elliptic/gauge screen, not a box-converged dynamical trajectory.
% Outer finite-difference closures and artificial boundary data change with
% the crop. Green traces are recomputed using only the cropped source.
assert(~isfile(outputFile),'Refusing to replace a box screen.');
validateattributes(boxFractions,{'numeric'}, ...
    {'vector','real','finite','nonempty','positive','<=',1});
originalThreads=maxNumCompThreads(10);
threadCleanup=onCleanup(@() maxNumCompThreads(originalThreads));
cp = ipm.output.readCheckpoint(checkpointFile);
[state,~,~] = ipm.output.restoreCheckpoint(cp,struct());
assert(strcmp(state.config.transport.spatialDiscretization,'high_order') && ...
    strcmp(state.config.scaling.rescalingMode,'dynamic') && ...
    strcmp(state.config.scaling.dynamicScaleGeometry,'isotropic') && ...
    strcmp(state.config.scaling.lengthGauge,'transport_anchor') && ...
    strcmp(state.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak') && ...
    strcmp(state.config.scaling.scalingContract,'exact_gauge_no_feedback_v1'), ...
    'This frozen crop screen requires the fourth-order isotropic exact quadratic/anchor contract.');
base = state.flow; x = state.ops.x; y = state.ops.y;
config=state.config; rho=state.rho; scale=state.scale;
references=state.ops.rescaling;
referenceNames=fieldnames(references);
referenceNames=referenceNames(startsWith(referenceNames,'reference') | ...
    startsWith(referenceNames,'adaptiveTarget') | startsWith(referenceNames,'safety') | ...
    ismember(referenceNames,{'pinX','strainTarget','peakTrackingHalfWidth'}));
% Retain accepted scalar/field data and release the original LU before
% building any cropped operator. The immutable source checkpoint remains.
clear state cp
records = cell(1,numel(boxFractions));
for k=1:numel(boxFractions)
    fraction=boxFractions(k);
    xi=find(abs(x)<=fraction*max(abs(x)));
    yi=find(y<=fraction*max(y));
    assert(numel(xi)>=9 && mod(numel(xi),2)==1 && numel(yi)>=9 && ...
        max(abs(x(xi)+fliplr(x(xi))))<=64*eps(max(1,max(abs(x(xi))))), ...
        'Each cropped grid must remain symmetric with enough nodes for all stencils.');
    % Keep the entire diagnostic rectangle and three extra nodes on each
    % outward side, so an outer one-sided closure cannot enter that core.
    assert(nnz(x(xi)>1.5)>=3 && nnz(y(yi)>1)>=3 && ...
        config.scaling.transportAnchorX<x(xi(end)), ...
        'Each crop must retain the full diagnostic core, gauge anchor and stencil margin.');
    grid=config.grid;
    grid.customX=x(xi); grid.customY=y(yi);
    grid.nx=numel(xi); grid.ny=numel(yi);
    grid.xlim=[x(xi(1)),x(xi(end))]; grid.ymax=y(yi(end));
    qx=ipm.mesh.quality(grid.customX,7,ipm.mesh.quadrature(grid.customX));
    qy=ipm.mesh.quality(grid.customY,7,ipm.mesh.quadrature(grid.customY));
    assert(qx.quadratureWeightsStrictlyPositive && qy.quadratureWeightsStrictlyPositive, ...
        'A cropped axis has nonpositive quadrature weights; do not build its operator.');
    timer=tic;
    ops=ipm.mesh.build(config,grid);
    ops.rescaling=ipm.output.restoreRuntimeReferences( ...
        ops.rescaling,references,ops.x,true);
    for index=1:numel(referenceNames)
        name=referenceNames{index};
        assert(isfield(ops.rescaling,name) && ...
            isequaln(ops.rescaling.(name),references.(name)), ...
            'The crop changed a frozen normalization/resolution reference.');
    end
    [~,flow]=ipm.evolve.flow(rho(yi,xi),ops,scale);
    core=ops.X>=0.5 & ops.X<=1.5 & ops.Y<=1;
    u1=base.u1(yi,xi); u2=base.u2(yi,xi);
    d1=flow.u1-u1; d2=flow.u2-u2;
    weights=ops.integrationWeights(core);
    denominator=sum(weights.*(u1(core).^2+u2(core).^2));
    assert(nnz(core)>=9 && all(weights>0) && isfinite(denominator) && denominator>0, ...
        'The complete common core needs positive weights and a nonzero velocity norm.');
    metric=sqrt(sum(weights.*(d1(core).^2+d2(core).^2))/denominator);
    record=struct('fraction',fraction,'nodes',[grid.nx,grid.ny], ...
        'actualXHalfWidth',max(abs(ops.x)),'actualYMaximum',max(ops.y), ...
        'coreVelocityRelativeL2',metric, ...
        'coreVelocityAbsoluteInf',max(hypot(d1(core),d2(core))), ...
        'baseCoreVelocityInf',max(hypot(u1(core),u2(core))), ...
        'coreVelocityRelativeInf',max(hypot(d1(core),d2(core)))/ ...
            max(hypot(u1(core),u2(core))), ...
        'cL',flow.c_l,'cOmega',flow.c_omega, ...
        'cLAbsoluteChange',abs(flow.c_l-base.c_l), ...
        'cOmegaAbsoluteChange',abs(flow.c_omega-base.c_omega), ...
        'cLRelativeChange',abs(flow.c_l-base.c_l)/max(abs(base.c_l),eps), ...
        'cOmegaRelativeChange',abs(flow.c_omega-base.c_omega)/max(abs(base.c_omega),eps), ...
        'quadraticPeak',flow.omegaGaugeQuadraticPeakValue, ...
        'quadraticPeakRelativeChange',abs(flow.omegaGaugeQuadraticPeakValue- ...
            base.omegaGaugeQuadraticPeakValue)/abs(base.omegaGaugeQuadraticPeakValue), ...
        'quadraticPeakXChange',flow.omegaGaugeQuadraticPeakX-base.omegaGaugeQuadraticPeakX, ...
        'normalizationReferencesPreserved',true, ...
        'farBoundaryMode',config.elliptic.farBoundaryMode, ...
        'poissonResidual',flow.poissonResidual, ...
        'xQuality',qx,'yQuality',qy,'wallSeconds',toc(timer));
    records{k}=record;
    fprintf('FROZEN_BOX %s\n',jsonencode(record));
    clear ops flow
end
report=struct('kind','frozen_field_box_sensitivity_not_dynamical_validation', ...
    'checkpointFile',checkpointFile,'tau',scale.canonicalTime, ...
    'physicalTime',scale.physicalTime,'coreX',[0.5,1.5],'coreY',[0,1], ...
    'coreCoordinates','rescaled','checkpointValidationThreads',10, ...
    'scalingContract',config.scaling.scalingContract, ...
    'farBoundaryMode',config.elliptic.farBoundaryMode, ...
    'preservedRuntimeReferenceFields',{referenceNames}, ...
    'records',[records{:}], 'pdeAdvanced',false, ...
    'interpretation', ...
    ['Cropping preserves common rho/grid samples and frozen reference values, but changes ' ...
    'outer derivative closures and artificial boundary data. Under green boundary mode ' ...
    'the Green traces are recomputed using only the cropped source. A stable frozen ' ...
    'screen cannot establish that prior dynamics or the original large box are free of truncation error.'], ...
    'requiredNextEvidence','Fresh-root/matched-physical-time box ladder before a smaller production box.');
save(outputFile,'report','-v7.3');
end
