function report=screen_poisson_backward_error(resultFiles,outputFile)
%SCREEN_POISSON_BACKWARD_ERROR Audit saved endpoint linear systems, no LU.
% Reassembles the maintained high-order A and RHS using saved paired fields
% and boundary traces. Small componentwise backward error is not a forward
% error bound, a mesh-convergence test, or a proof of an accurate PDE.
assert(iscell(resultFiles) && ~isempty(resultFiles) && ~isfile(outputFile));
records=cell(1,numel(resultFiles));
for k=1:numel(resultFiles)
    r=ipm.output.validate(resultFiles{k});
    assert(all(ipm.output.trustedMask(r)) && r.scale.aspect==1 && ...
        strcmp(r.config.transport.spatialDiscretization,'high_order'));
    x=r.grid.x(:)'; y=r.grid.y(:); nxi=numel(x)-2; nyi=numel(y)-2;
    ddx=-ipm.mesh.fdMatrix(x,2,7); ddy=-ipm.mesh.fdMatrix(y,2,7);
    tx=ddx(2:end-1,2:end-1); ty=ddy(2:end-1,2:end-1);
    a=kron(speye(nxi),ty)+kron(tx,speye(nyi));
    psi=r.state.psi;
    bx=[psi(2:end-1,1),psi(2:end-1,end)];
    by=[psi(1,2:end-1);psi(end,2:end-1)];
    b=r.state.omega(2:end-1,2:end-1)-bx*ddx(2:end-1,[1,end])'- ...
        ddy(2:end-1,[1,end])*by;
    z=psi(2:end-1,2:end-1); z=z(:); b=b(:);
    residual=a*z-b;
    globalResidual=norm(residual,inf)/max(norm(b,inf),eps);
    storedResidual=r.elliptic.solveInfo.relativeResidual;
    assert(abs(globalResidual-storedResidual)<=64*eps(max(1,storedResidual)), ...
        'The saved endpoint linear system did not reproduce its maintained residual.');
    denominator=abs(a)*abs(z)+abs(b);
    component=zeros(size(b)); active=denominator>0;
    component(active)=abs(residual(active))./denominator(active);
    assert(all(residual(~active)==0));
    [X,Y]=meshgrid(x(2:end-1),y(2:end-1));
    g=r.history.gauge; m=r.history.mesh;
    peak=g.omegaGaugeQuadraticPeakX(end);
    near=abs(abs(X)-peak)<=3*m.trackedWallCoreWidth(end) & ...
        Y<=3*m.trackedVerticalCoreWidth(end);
    core=abs(X)<=1.5 & Y<=1;
    [worst,worstIndex]=max(component);
    records{k}=struct('resultFile',resultFiles{k},'tau',r.state.canonicalTime, ...
        'physicalTime',r.state.physicalTime,'unknowns',numel(z),'nonzeros',nnz(a), ...
        'maintainedGlobalResidual',storedResidual,'recomputedGlobalResidual',globalResidual, ...
        'globalResidualExact',isequal(globalResidual,storedResidual), ...
        'componentwiseBackwardError',worst, ...
        'coreComponentwiseBackwardError',max(component(core)), ...
        'nearPeakComponentwiseBackwardError',max(component(near)), ...
        'coreAbsoluteEquationResidual',max(abs(residual(core))), ...
        'nearPeakAbsoluteEquationResidual',max(abs(residual(near))), ...
        'worstCellXY',[X(worstIndex),Y(worstIndex)], ...
        'worstCellResidual',residual(worstIndex),'worstCellDenominator',denominator(worstIndex), ...
        'rowsAbove1eMinus12',nnz(component>1e-12), ...
        'matrixCoefficientRange',[min(abs(nonzeros(a))),max(abs(nonzeros(a)))], ...
        'sourceInf',max(abs(r.state.omega),[],'all'));
end
report=struct('kind','saved_linear_system_componentwise_backward_error', ...
    'records',[records{:}],'newFactorization',false,'newPoissonSolve',false,'pdeAdvanced',false, ...
    'interpretation',['This measures residual relative to each original equation row. ' ...
    'It supplies no forward-error bound and does not validate space/box truncation.']);
save(outputFile,'report');
[folder,name]=fileparts(outputFile);
fid=fopen(fullfile(folder,[name,'.json']),'w');assert(fid>=0);
cleanup=onCleanup(@() fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
