function report=screen_v5_h256_initial_counts(outputFile)
%SCREEN_V5_H256_INITIAL_COUNTS Counterfactual pure t=0 observer node screen.
% Each row freezes one initial solver count before invoking the production
% analytic-observation planner. It does not build LU or evolve the PDE.
counts=[321,161;401,161;481,161;561,161;641,161];
rows=struct([]);
for k=1:size(counts,1)
    n=counts(k,:);
    opts=ipm.config.longTimeProfile(struct('boxHalfWidth',256, ...
        'boxHeight',128,'initialNodeCount',n, ...
        'autonomousMeshVersion',5,'maximumTotalNodes',310000, ...
        'verbose',false));
    config=ipm.config.resolve(opts);
    axes=struct('x',linspace(-256,256,n(1)), ...
        'y',linspace(0,128,n(2))');
    [candidates,e]=ipm.remesh.planInitialAnalyticFallback(config,axes);
    assert(~e.used&&strcmp(e.selectedPhase,'analytic_preflight'));
    firstCore=[NaN,NaN];firstFront=NaN;
    if ~isempty(candidates)
        a=e.candidateAudits(e.admittedOriginalPairIndices(1));
        firstCore=a.features.actualCoreCells;
        firstFront=a.features.leftFrontCells;
    end
    row=struct('initialNodeCount',n,'totalNodes',prod(n), ...
        'xAdmitted',sum([e.axisReport.xTrials.admissible]), ...
        'yAdmitted',sum([e.axisReport.yTrials.admissible]), ...
        'pureCandidates',numel(candidates), ...
        'observationNodeCount',e.observation.nodeCount, ...
        'firstActualAnalyticCoreCells',firstCore, ...
        'firstActualAnalyticFrontCells',firstFront, ...
        'noLU',true,'noPDE',true);
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
    fprintf('V5_H256_INITIAL n=%dx%d x=%d y=%d accepted=%d core=%.3f/%.3f\n', ...
        n(1),n(2),row.xAdmitted,row.yAdmitted,row.pureCandidates, ...
        firstCore(1),firstCore(2));
end
report=struct('kind','v5_h256_initial_solver_count_screen_v1', ...
    'box',[256,128],'cap',310000,'rows',rows, ...
    'frozenOriginalPhysicalTime',0,'noLU',true,'noFlow',true, ...
    'noPDE',true,'nativeQualificationClaim',false);
if nargin>=1&&~isempty(outputFile)
    assert(~isfile(outputFile));fid=fopen(outputFile,'w');assert(fid>=0);
    closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
end
