function report=smoke_density_mode_one_zero(outputFile,finalTau)
%SMOKE_DENSITY_MODE_ONE_ZERO Short original-t0 numerical-path smoke check.
assert(~isfile(outputFile));
if nargin<2,finalTau=.02;end
settings=struct('autonomousMeshVersion',5,'meshDensityVersion',1, ...
    'maximumTotalNodes',310000,'canonicalFinalTime',finalTau, ...
    'maximumSteps',1000,'outputDirectory',fileparts(outputFile), ...
    'verbose',false,'storeSnapshots',false,'makePlots',false);
opts=ipm.config.longTimeProfile(settings);
opts.saveResults=false;opts.checkpoint.enabled=false;
result=ipm.solve(opts);
x=result.grid.x;y=result.grid.y;
qx=ipm.mesh.quality(x,7,ipm.mesh.quadrature(x));
qy=ipm.mesh.quality(y,7,ipm.mesh.quadrature(y));
assert(result.state.steps>0 && result.state.canonicalTime>0 && ...
    all(isfinite(result.state.rho),'all') && ...
    qx.maximumAdjacentCellRatio<1.08 && ...
    qy.maximumAdjacentCellRatio<1.08 && ...
    result.config.remesh.autonomousMesh.densityVersion==1);
report=struct('kind','density_mode_one_original_t0_short_smoke_v1', ...
    'requestedFinalTau',finalTau, ...
    'steps',result.state.steps,'canonicalTime',result.state.canonicalTime, ...
    'stopReason',result.state.stopReason,'nodeCount',[numel(x),numel(y)], ...
    'remeshCount',result.grid.remeshCount, ...
    'maximumAdjacentRatio',[qx.maximumAdjacentCellRatio, ...
        qy.maximumAdjacentCellRatio], ...
    'xCurvature',qx.maximumLogSpacingCurvature, ...
    'yCurvature',qy.maximumLogSpacingCurvature, ...
    'finiteField',true,'fullLongTimeCertified',false);
fid=fopen(outputFile,'w');assert(fid>=0);c=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
