function report=stress_last_frozen_remesh(sourceDistribution,policyDistribution,outputFile,growX,xPadding,densityVersion)
%STRESS_LAST_FROZEN_REMESH Audit opt-in density on an extreme signed state.
% The source checkpoint remains immutable; the candidate is never committed.
assert(isfile(sourceDistribution)&&isfile(policyDistribution)&&~isfile(outputFile));
if nargin<5,xPadding=1.10;end
if nargin<6,densityVersion=1;end
sourceData=jsondecode(fileread(sourceDistribution));
policyData=jsondecode(fileread(policyDistribution));
signedSource=ipm.output.readCheckpoint(sourceData.checkpointFile);
signedPolicy=ipm.output.readCheckpoint(policyData.checkpointFile);
[source,~,~]=ipm.output.restoreCheckpoint(signedSource,struct());
maxNumCompThreads(4);
if isfield(source.ops,'poisson'),source.ops=rmfield(source.ops,'poisson');end
input=signedPolicy.payload.state.config.remesh.autonomousMesh;
assert(input.version==5);
input.densityVersion=densityVersion;
input.search.roundingCells=[8,16,24,32,40];
if densityVersion==2,input.search.xPadding=1.50;end
modeOne=ipm.config.autonomousMeshPolicy(input);
% A changed padding is a research-only geometry variant until it is
% registered under a new density policy version.
modeOne.search.xPadding=xPadding;
memory=source.runMetadata.autonomousMesh;
if ischar(growX) || isstring(growX)
    assert(strcmp(string(growX),"growY"));
    members=memory.referenceFamily.members;
    counts=vertcat(members.nodeCount);
    eligible=counts(:,1)==numel(source.ops.x) & ...
        counts(:,2)>numel(source.ops.y);
    targetId=find(eligible,1);
    assert(~isempty(targetId));
    reference=struct('x',members(targetId).baseX,'y',members(targetId).baseY);
elseif growX
    members=memory.referenceFamily.members;
    counts=vertcat(members.nodeCount);
    targetId=find(counts(:,1)>numel(source.ops.x) & ...
        counts(:,2)==numel(source.ops.y),1);
    assert(~isempty(targetId));
    reference=struct('x',members(targetId).baseX,'y',members(targetId).baseY);
else
    targetId=memory.currentLevelId;
    reference=struct('x',source.ops.baseX,'y',source.ops.baseY);
end
ops=source.ops;
view=struct('rho',source.rho,'x',ops.x,'y',ops.y,'Dx',ops.Dx, ...
    'source',source.rho*ops.Dx','trusted',true);
timer=tic;
[pairs,detail,search]=ipm.remesh.hierarchicalAxisPairs(view,reference, ...
    ops.rescaling.transportAnchorX,modeOne,modeOne.nodeFamily.maximumTotalNodes);
planningSeconds=toc(timer);
report=struct('kind','extreme_signed_frozen_density_native_stress_v2', ...
    'source',sourceDistribution,'policySource',policyDistribution, ...
    'researchXPadding',xPadding,'densityVersion',densityVersion, ...
    'densityPolicyRegistered', ...
        (densityVersion==1&&xPadding==1.10) || ...
        (densityVersion==2&&xPadding==1.50), ...
    'tau',sourceData.tau,'step',sourceData.step, ...
    'sourcePolicyVersion',source.config.remesh.autonomousMesh.version, ...
    'sourceNodeCount',[numel(ops.x),numel(ops.y)], ...
    'targetNodeCount',[numel(reference.x),numel(reference.y)], ...
    'sourceLevelId',memory.currentLevelId,'targetLevelId',targetId, ...
    'planningStatus',detail.status,'searchStatus',search.status, ...
    'planningSeconds',planningSeconds,'candidateCount',numel(pairs), ...
    'geometryPassed',~isempty(pairs),'nativeAttempts',struct([]), ...
    'nativePassed',false,'candidateCommitted',false, ...
    'continuousLifetimeProven',false);
for k=1:numel(pairs)
    p=pairs(k);
    if p.unchanged,continue;end
    row=struct('candidateIndex',k,'xTrial',p.xIndex,'yTrial',p.yIndex, ...
        'predictedCells',p.predictedCells, ...
        'plannedRatio',[p.quality.x.maximumAdjacentCellRatio, ...
                        p.quality.y.maximumAdjacentCellRatio], ...
        'xDistribution',ratio_distribution(p.x), ...
        'yDistribution',ratio_distribution(p.y), ...
        'transferSeconds',NaN,'auditPassed',false,'auditReasons',{{}}, ...
        'postFlowPassed',false,'actualCoreCells',[NaN,NaN], ...
        'actualFrontCells',NaN,'relativePeakJump',NaN, ...
        'massRelativeDefect',NaN,'safetyFactor',NaN);
    proposal=struct('x',p.x,'y',p.y, ...
        'referenceFamily',memory.referenceFamily, ...
        'sourceLevelId',memory.currentLevelId,'targetLevelId',targetId);
    trial=source;timer=tic;
    [trial.rho,trial.ops]=ipm.remesh.transfer( ...
        source.rho,source.ops,source.config,proposal);
    row.transferSeconds=toc(timer);
    policy=source.config.remesh.autonomousMesh;
    audit=ipm.remesh.auditCandidate(source,trial,policy, ...
        memory.cumulativeAbsolutePeakJump);
    row.auditPassed=audit.passed;row.auditReasons=audit.reasons;
    row.actualCoreCells=audit.coreCells;row.actualFrontCells=audit.leftFrontCells;
    row.relativePeakJump=audit.relativePeakJump;
    row.massRelativeDefect=audit.massRelativeDefect;
    if audit.passed
        [~,trial.flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
        row.safetyFactor=trial.flow.safetyFactor;
        row.postFlowPassed=ipm.evolve.isFinite(trial) && ...
            row.safetyFactor<policy.maximumSafety && ...
            all(trial.flow.coreGridPoints>=policy.transactionMinimumCoreCells) && ...
            all(trial.flow.verticalCoreGridPoints>=policy.transactionMinimumCoreCells);
    end
    report.nativeAttempts=append(report.nativeAttempts,row);
    if row.auditPassed && row.postFlowPassed
        report.nativePassed=true;break
    end
end
fid=fopen(outputFile,'w');assert(fid>=0);cleaner=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end

function d=ratio_distribution(v)
h=diff(v(:));burden=abs(diff(log(h)));n=numel(burden);
ordered=sort(burden,'descend');top=max(1,ceil(.05*n));
d=struct('maximumRatio',exp(max(burden)), ...
    'medianRatio',exp(median(burden)), ...
    'p95Ratio',exp(prctile(burden,95)), ...
    'topFivePercentBurdenShare',sum(ordered(1:top))/sum(burden), ...
    'burdenParticipationFraction',sum(burden)^2/(n*sum(burden.^2)), ...
    'nearMaximumInterfaceFraction',mean(burden>=.8*max(burden)));
end

function rows=append(rows,row)
if isempty(rows),rows=row;else,rows(end+1)=row;end
end
