function report=test_density_mode_two_resume(outputDirectory)
%TEST_DENSITY_MODE_TWO_RESUME Check frozen policy and native split continuation.
assert(~isfolder(outputDirectory));mkdir(outputDirectory);
opts=ipm.config.longTimeProfile(struct( ...
    'autonomousMeshVersion',5,'meshDensityVersion',2, ...
    'maximumTotalNodes',310000,'canonicalFinalTime',.25, ...
    'maximumSteps',1000,'checkpointEvery',.05, ...
    'outputDirectory',outputDirectory,'verbose',false, ...
    'storeSnapshots',false,'makePlots',false));
opts.saveResults=false;
first=ipm.solve(opts);
checkpointFile=first.metadata.latestCheckpointFile;
assert(isfile(checkpointFile));
checkpoint=ipm.output.readCheckpoint(checkpointFile);
assert(checkpoint.payload.state.config.remesh.autonomousMesh.densityVersion==2 && ...
    checkpoint.payload.state.config.remesh.autonomousMesh.search.xPadding==1.50);
resume=struct('finalTime',.30,'maxSteps',1000,'saveResults',false, ...
    'checkpoint',opts.checkpoint,'verbose',false);
second=ipm.solve(resume,checkpointFile);
assert(first.state.canonicalTime==.25 && second.state.canonicalTime==.30 && ...
    second.state.steps>first.state.steps && ...
    second.grid.remeshCount>=first.grid.remeshCount && ...
    second.config.remesh.autonomousMesh.densityVersion==2 && ...
    all(isfinite(second.state.rho),'all'));
report=struct('kind','density_mode_two_native_checkpoint_resume_v1', ...
    'firstTau',first.state.canonicalTime,'firstSteps',first.state.steps, ...
    'firstRemeshCount',first.grid.remeshCount, ...
    'secondTau',second.state.canonicalTime,'secondSteps',second.state.steps, ...
    'secondRemeshCount',second.grid.remeshCount, ...
    'checkpointFile',checkpointFile, ...
    'resumedDensityVersion',second.config.remesh.autonomousMesh.densityVersion, ...
    'finiteField',true);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
cleaner=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
