function report=test_v5_initial_preflight_equivalence()
%TEST_V5_INITIAL_PREFLIGHT_EQUIVALENCE Keep the original fallback immutable.
opts=ipm.config.longTimeProfile(struct('boxHalfWidth',256, ...
    'boxHeight',128,'initialNodeCount',[401,161], ...
    'autonomousMeshVersion',5,'maximumTotalNodes',310000, ...
    'verbose',false));
config=ipm.config.resolve(opts);
axes=struct('x',linspace(-256,256,401), ...
    'y',linspace(0,128,161)');
plan=struct('initial',true,'requested',true,'sourceStep',0, ...
    'sourceCanonicalTime',0,'sourcePhysicalTime',0, ...
    'sourceNormalizedTime',0,'sourceRemeshCount',0, ...
    'sourceLevelId',1,'sourceNodeCount',[401,161], ...
    'stopReason','autonomous_mesh_axis_capacity', ...
    'candidates',struct([]),'coreCells',[NaN,NaN]);
original=struct('plan',plan,'attempts',struct([]));
[preflight,a]=ipm.remesh.planInitialAnalyticFallback(config,axes);
[fallback,b]=ipm.remesh.planInitialAnalyticFallback(config,axes,original);
assert(numel(preflight)==3&&isequaln(preflight,fallback)&& ...
    isequaln(without_exception_stacks(a.axisReport), ...
        without_exception_stacks(b.axisReport))&& ...
    isequaln(a.candidateAudits,b.candidateAudits)&& ...
    ~a.used&&b.used&&strcmp(a.selectedPhase,'analytic_preflight')&& ...
    strcmp(b.selectedPhase,'fixed_observation'));
bad=original;bad.plan.sourceStep=1;
try
    ipm.remesh.planInitialAnalyticFallback(config,axes,bad);
    error('ipm:ExpectedRejection','A forged evolved source was accepted.');
catch e
    assert(strcmp(e.identifier,'ipm:InitialObservationContext'));
end
report=struct('kind','v5_initial_preflight_fallback_exact_equivalence_v1', ...
    'box',[256,128],'initialNodeCount',[401,161], ...
    'candidateCount',numel(preflight), ...
    'axesReportsAndAuditsExact',true,'invalidSourceRejected',true, ...
    'noLU',true,'noPDE',true);
fprintf('V5_PREFLIGHT_EQUIVALENT H256 n=401x161 pairs=%d\n',numel(preflight));
end

function report=without_exception_stacks(report)
% A rejected trial embeds MATLAB's caller-dependent diagnostic stack.
for name={'xTrials','yTrials'}
    trials=report.(name{1});
    for k=1:numel(trials)
        if isfield(trials,'failure')&&isfield(trials(k).failure,'stack')
            trials(k).failure.stack=[];
        end
    end
    report.(name{1})=trials;
end
end
