function report=test_v5_native_zero_smoke(outputDirectory)
%TEST_V5_NATIVE_ZERO_SMOKE Exercise the real v5 t=0 initialization and step.
% A short run tests native operator, flow, checkpoint, and controller wiring;
% it makes no late-time accuracy or singularity claim.
assert(~isfolder(outputDirectory),'ipm:V5SmokeOutputExists');
settings=struct('canonicalFinalTime',.004,'maximumSteps',3, ...
    'maximumTimeStep',.002,'autonomousMeshVersion',5, ...
    'maximumTotalNodes',310000,'maximumAdjacentGridRatio',2, ...
    'outputDirectory',outputDirectory,'verbose',false);
opts=ipm.config.longTimeProfile(settings);
result=ipm.solve(opts);
assert(result.state.steps>=1&& ...
    result.config.remesh.autonomousMesh.version==5);
validated=ipm.output.validate(result);
assert(validated.state.steps==result.state.steps);
checkpointFile=char(result.metadata.latestCheckpointFile);
assert(isfile(checkpointFile));
cp=ipm.output.readCheckpoint(checkpointFile);
assert(cp.payload.state.step==result.state.steps&& ...
    cp.payload.state.runMetadata.autonomousMesh.version==5);
report=struct('kind','v5_native_zero_time_smoke_v1', ...
    'outputDirectory',outputDirectory,'steps',result.state.steps, ...
    'canonicalTime',result.state.canonicalTime, ...
    'nodeCount',[numel(result.grid.x),numel(result.grid.y)], ...
    'stopReason',char(result.state.stopReason), ...
    'checkpointFile',checkpointFile,'checkpointValidated',true, ...
    'resultValidated',true,'nativePdeAdvanced',true, ...
    'longTimeClaim',false);
fprintf('V5_NATIVE_ZERO steps=%d tau=%.9g grid=%dx%d stop=%s\n', ...
    report.steps,report.canonicalTime,report.nodeCount(1), ...
    report.nodeCount(2),report.stopReason);
end
