function report=test_v5_native_resume_smoke(checkpointFile,outputDirectory)
%TEST_V5_NATIVE_RESUME_SMOKE Resume a real version-5 accepted-step state.
assert(~isfolder(outputDirectory),'ipm:V5ResumeOutputExists');
cp=ipm.output.readCheckpoint(checkpointFile);
assert(cp.payload.state.runMetadata.autonomousMesh.version==5);
mkdir(outputDirectory);
resume=struct('finalTime',.008,'maxSteps',6, ...
    'saveResults',true,'resultFile',fullfile(outputDirectory,'result.mat'), ...
    'verbose',false,'checkpoint',struct('enabled',true, ...
    'file',fullfile(outputDirectory,'checkpoint.mat'), ...
    'every',.002,'atExit',true));
result=ipm.solve(resume,checkpointFile);
assert(result.state.steps>cp.payload.state.step&& ...
    result.state.canonicalTime>cp.payload.state.scale.canonicalTime);
ipm.output.validate(result);
newCheckpointFile=char(result.metadata.latestCheckpointFile);
next=ipm.output.readCheckpoint(newCheckpointFile);
assert(next.payload.state.step==result.state.steps&& ...
    next.payload.state.runMetadata.autonomousMesh.version==5);
report=struct('kind','v5_native_resume_smoke_v1', ...
    'sourceCheckpoint',checkpointFile,'outputDirectory',outputDirectory, ...
    'sourceStep',cp.payload.state.step,'targetStep',result.state.steps, ...
    'sourceCanonicalTime',cp.payload.state.scale.canonicalTime, ...
    'targetCanonicalTime',result.state.canonicalTime, ...
    'targetCheckpoint',newCheckpointFile,'resultValidated',true, ...
    'checkpointValidated',true,'nativePdeAdvanced',true);
fprintf('V5_NATIVE_RESUME steps=%d->%d tau=%.9g->%.9g\n', ...
    report.sourceStep,report.targetStep, ...
    report.sourceCanonicalTime,report.targetCanonicalTime);
end
