function report=test_v5_frozen_controller_plan(checkpointFile,cap,outputFile)
%TEST_V5_FROZEN_CONTROLLER_PLAN Exercise the full no-LU v5 decision path.
% The frozen v4 field and grid seed a counterfactual v5 controller ledger;
% no PDE step, factor, field transfer, or checkpoint mutation occurs.
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
assert(all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
policy=ipm.config.autonomousMeshPolicy(struct('version',5, ...
    'nodeFamily',struct('maximumTotalNodes',cap, ...
    'initialNodeCount',[s.config.grid.nx,s.config.grid.ny])));
old=s.runMetadata.autonomousMesh;
family=ipm.remesh.referenceAxisFamily(old.referenceFamily.rootX, ...
    old.referenceFamily.rootY,s.config.scaling.transportAnchorX,policy);
matches=find(arrayfun(@(m)isequal(m.baseX,s.baseX)&& ...
    isequal(m.baseY,s.baseY),family.members));
assert(isscalar(matches));
memory=old;memory.version=5;memory.policy=policy;
memory.referenceFamily=family;memory.currentLevelId=matches;
memory.window.levelId(:)=matches;
config=s.config;config.remesh.autonomousMesh=policy;
ops=struct('x',s.x,'y',s.y,'baseX',s.baseX,'baseY',s.baseY, ...
    'nx',numel(s.x),'ny',numel(s.y),'remeshCount',s.remeshCount, ...
    'Dx',ipm.mesh.fdMatrix(s.x,1,7));
flow=struct('coreGridPoints',memory.window.coreCells(end,1), ...
    'verticalCoreGridPoints',memory.window.coreCells(end,2), ...
    'safetyFactor',memory.window.safety(end));
% Force a review using a frozen observation without changing the field.
flow.coreGridPoints=min(flow.coreGridPoints,policy.regridCoreTrigger(1)-1);
flow.verticalCoreGridPoints=min(flow.verticalCoreGridPoints,policy.regridCoreTrigger(2)-1);
state=struct('config',config,'runMetadata',s.runMetadata,'rho',s.rho, ...
    'ops',ops,'flow',flow,'scale',s.scale, ...
    'normalizedTime',s.normalizedTime,'step',s.step);
state.runMetadata.autonomousMesh=memory;
timer=tic;[~,plan]=ipm.evolve.planAutonomousMesh(state,false);
elapsed=toc(timer);
assert(plan.requested && isempty(plan.stopReason));
e=plan.axisSearchEvidence;
ipm.remesh.searchEvidence('validate',e,policy,family,matches,false,true);
assert(numel(plan.candidates)==numel(e.filteredCandidateIndices));
assert(numel(e.members)==numel(plan.axisReport.eligibleLevelOrder));
assert(all(arrayfun(@(m)all(m.nodeCount>=family.members(matches).nodeCount), ...
    family.members(plan.axisReport.eligibleLevelOrder))));
pareto=struct([]);bestRatio=Inf;
for member=e.members
    ids=find([plan.candidates.nodeFamilyIndex]==member.levelId);
    if isempty(ids),continue;end
    q=plan.candidates(ids(1)).quality;
    ratio=max(q.x.maximumAdjacentCellRatio,q.y.maximumAdjacentCellRatio);
    if ratio<bestRatio-1e-12
        bestRatio=ratio;
        row=struct('levelId',member.levelId, ...
            'cellFactors',family.members(member.levelId).cellFactors, ...
            'nodeCount',member.nodeCount,'totalNodes',prod(member.nodeCount), ...
            'xAdjacentRatio',q.x.maximumAdjacentCellRatio, ...
            'yAdjacentRatio',q.y.maximumAdjacentCellRatio, ...
            'maximumAdjacentRatio',ratio);
        if isempty(pareto),pareto=row;else,pareto(end+1)=row;end %#ok<AGROW>
    end
end
report=struct('kind','v5_frozen_full_controller_plan_v1', ...
    'sourceCheckpoint',checkpointFile,'sourceStep',s.step, ...
    'sourceCanonicalTime',s.scale.canonicalTime,'cap',cap, ...
    'registeredMembers',numel(family.members), ...
    'eligibleMembers',numel(e.members), ...
    'evaluatedAxisTrials',sum([e.members.evaluatedAxisTrials]), ...
    'distinctXReferenceTrials',plan.axisReport.distinctXReferenceTrials, ...
    'distinctYReferenceTrials',plan.axisReport.distinctYReferenceTrials, ...
    'returnedCandidates',numel(plan.candidates), ...
    'costOrderedRatioPareto',pareto, ...
    'elapsedSeconds',elapsed,'noLU',true,'noTransfer',true,'noPDE',true);
fprintf('V5_PLAN cap=%d members=%d eligible=%d trials=%d distinct=%d/%d candidates=%d seconds=%.3f\n', ...
    cap,report.registeredMembers,report.eligibleMembers, ...
    report.evaluatedAxisTrials,report.distinctXReferenceTrials, ...
    report.distinctYReferenceTrials,report.returnedCandidates,elapsed);
if nargin>=3&&~isempty(outputFile)
    assert(~isfile(outputFile));fid=fopen(outputFile,'w');assert(fid>=0);
    closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
end
