function report=test_rounded_geometric_density(distributionFile,outputFile)
%TEST_ROUNDED_GEOMETRIC_DENSITY Frozen same-N Y-density comparison.
assert(isfile(distributionFile)&&~isfile(outputFile));
d=jsondecode(fileread(distributionFile));f=d.feature;
original=d.y.nodes(:);
rows=struct([]);best=struct();bestRatio=Inf;
for roundCells=[2,4,8,12,16,24,32,48]
    try
        [v,info]=ipm.remesh.roundedGeometricAxis(original, ...
            f.yCoreWidth,32*1.15,roundCells);
        q=ipm.mesh.quality(v,7,ipm.mesh.quadrature(v));
        valid=q.maximumAdjacentCellRatio<=1.08 && ...
            q.maximumLogSpacingCurvature<=.01 && ...
            q.minimumStencilRcond>=1e-9 && ...
            q.minimumQuadratureWeightRatio>=1e-8 && ...
            q.minimumQuadratureWeightToControlWidthRatio>=.35 && ...
            q.maximumQuadratureWeightToControlWidthRatio<=1.65 && ...
            info.achievedCoreCells>=32;
        row=struct('roundingCells',roundCells,'valid',valid, ...
            'ratio',q.maximumAdjacentCellRatio, ...
            'curvature',q.maximumLogSpacingCurvature, ...
            'coreCells',info.achievedCoreCells, ...
            'stencilRcond',q.minimumStencilRcond, ...
            'quadratureRatio',q.minimumQuadratureWeightRatio);
        rows=append(rows,row);
        if valid&&row.ratio<bestRatio
            bestRatio=row.ratio;
            best=struct('axis',v,'info',info,'quality',q);
        end
    catch e
        if ~strcmp(e.identifier,'ipm:RoundedGeometricInfeasible')
            rethrow(e);
        end
    end
end
report=struct('kind','frozen_same_n_rounded_geometric_density_v1', ...
    'source',distributionFile,'baselineRatio',d.y.maximumAdjacentRatio, ...
    'bestRatio',bestRatio,'best',best,'rows',rows, ...
    'geometryOnly',true,'nativeTransferCertified',false);
fid=fopen(outputFile,'w');assert(fid>=0);c=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
function rows=append(rows,row)
if isempty(rows),rows=row;else,rows(end+1)=row;end
end
