function report=test_v5_native_growth_pair(checkpointFile,outputFile)
%TEST_V5_NATIVE_GROWTH_PAIR Screen a real v5 t=0 field through native transfer.
% This directly builds target operators and audits the field; it does not
% claim that the controller naturally requested or committed this growth.
[source,~,~]=ipm.output.restoreCheckpoint(checkpointFile);
policy=source.config.remesh.autonomousMesh;
assert(policy.version==5 && source.ops.remeshCount==0 && ...
    source.runMetadata.autonomousMesh.currentLevelId==1);
family=source.runMetadata.autonomousMesh.referenceFamily;
factors=vertcat(family.members.cellFactors);
target=find(all(factors==[2,1],2));assert(isscalar(target));
member=family.members(target);
source.ops=rmfield(source.ops,'poisson');
view=struct('rho',source.rho,'x',source.ops.x,'y',source.ops.y, ...
    'Dx',source.ops.Dx,'source',source.rho*source.ops.Dx','trusted',true);
[pairs,~,~]=ipm.remesh.hierarchicalAxisPairs(view, ...
    struct('x',member.baseX,'y',member.baseY), ...
    source.config.scaling.transportAnchorX,policy, ...
    policy.nodeFamily.maximumTotalNodes);
assert(~isempty(pairs));rows=struct([]);accepted=0;
for k=1:numel(pairs)
    c=pairs(k);
    proposal=struct('x',c.x,'y',c.y,'referenceFamily',family, ...
        'sourceLevelId',1,'targetLevelId',target);
    timer=tic;
    [rhoNew,opsNew]=ipm.remesh.transfer( ...
        source.rho,source.ops,source.config,proposal);
    trial=source;trial.rho=rhoNew;trial.ops=opsNew;
    audit=ipm.remesh.auditCandidate(source,trial,policy, ...
        source.runMetadata.autonomousMesh.cumulativeAbsolutePeakJump);
    safe=false;flowCore=[NaN,NaN];safety=NaN;
    if audit.passed
        [~,flow]=ipm.evolve.flow(trial.rho,trial.ops,trial.scale);
        flowCore=[flow.coreGridPoints,flow.verticalCoreGridPoints];
        safety=flow.safetyFactor;
        safe=isfinite(safety)&&safety<policy.maximumSafety&& ...
            all(flowCore>=policy.transactionMinimumCoreCells);
    end
    row=struct('candidateIndex',k,'sourceLevelId',1,'targetLevelId',target, ...
        'sourceNodeCount',[source.ops.nx,source.ops.ny], ...
        'targetNodeCount',[opsNew.nx,opsNew.ny], ...
        'maximumAdjacentRatio',max(c.quality.x.maximumAdjacentCellRatio, ...
            c.quality.y.maximumAdjacentCellRatio), ...
        'auditPassed',audit.passed,'auditReasons',{audit.reasons}, ...
        'postTransferSafe',safe,'coreCells',audit.coreCells, ...
        'flowCoreCells',flowCore,'flowSafety',safety, ...
        'frontCells',audit.leftFrontCells, ...
        'relativePeakJump',audit.relativePeakJump, ...
        'massRelativeDefect',audit.massRelativeDefect, ...
        'relativeRangeViolation',audit.relativeRangeViolation, ...
        'elapsedSeconds',toc(timer));
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
    fprintf('V5_NATIVE_GROWTH candidate=%d n=%dx%d audit=%d safe=%d ratio=%.9f\n', ...
        k,opsNew.nx,opsNew.ny,audit.passed,safe,row.maximumAdjacentRatio);
    clear trial opsNew rhoNew flow
    if audit.passed&&safe,accepted=k;break;end
end
report=struct('kind','v5_native_zero_field_growth_pair_v1', ...
    'sourceCheckpoint',checkpointFile,'sourceStep',source.step, ...
    'sourceCanonicalTime',source.scale.canonicalTime, ...
    'targetCellFactors',[2,1],'selectedCandidateIndex',accepted, ...
    'rows',rows,'nativeOperatorBuilt',true,'nativeFieldTransferred',true, ...
    'nativeAuditPerformed',true,'controllerCommitted',false, ...
    'laterTimeClaim',false);
if nargin>=2&&~isempty(outputFile)
    assert(~isfile(outputFile));fid=fopen(outputFile,'w');assert(fid>=0);
    closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
    fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
end
