function report=test_density_mode_one(distributionFile,outputFile)
%TEST_DENSITY_MODE_ONE Opt-in registration and frozen production-planner test.
assert(isfile(distributionFile)&&~isfile(outputFile));
d=jsondecode(fileread(distributionFile));
c=ipm.output.readCheckpoint(d.checkpointFile);
saved=c.payload.state;
old=saved.config.remesh.autonomousMesh;
assert(old.version==5&&~isfield(old,'densityVersion'));
input=old;input.densityVersion=1;
input.search.roundingCells=[8,16,24,32,40];
policy=ipm.config.autonomousMeshPolicy(input);
assert(policy.densityVersion==1 && ...
    isequal(policy.search.roundingCells,[8,16,24,32,40]));
x=saved.x(:)';y=saved.y(:);Dx=ipm.mesh.fdMatrix(x,1,7);
view=struct('rho',saved.rho,'x',x,'y',y,'Dx',Dx, ...
    'source',saved.rho*Dx','trusted',true);
reference=struct('x',saved.baseX,'y',saved.baseY);
[pairs,detail]=ipm.remesh.plannedAxisPairs(view,reference,1,policy);
[again,repeated]=ipm.remesh.plannedAxisPairs(view,reference,1,policy);
assert(isequaln(pairs,again)&&isequaln(detail,repeated));
assert(numel(detail.xTrials)==70&&numel(detail.yTrials)==4);
assert(strcmp(detail.yTrials(4).equalizerInfo.kind, ...
    'one_sided_rounded_geometric_equalizer_v1'));
assert(detail.yTrials(4).admissible);
rows=struct([]);
for k=1:numel(pairs)
    p=pairs(k);
    rows=append(rows,struct('index',k,'unchanged',p.unchanged, ...
        'xTrial',p.xIndex,'yTrial',p.yIndex, ...
        'nodeCount',[numel(p.x),numel(p.y)], ...
        'maximumAdjacentRatio',max(p.quality.x.maximumAdjacentCellRatio, ...
            p.quality.y.maximumAdjacentCellRatio), ...
        'xRatio',p.quality.x.maximumAdjacentCellRatio, ...
        'yRatio',p.quality.y.maximumAdjacentCellRatio, ...
        'predictedCells',p.predictedCells));
end
report=struct('kind','density_mode_one_frozen_planner_v1', ...
    'source',distributionFile,'tau',d.tau,'oldPolicyExactDefault',true, ...
    'optInPolicy',policy,'candidateCount',numel(pairs), ...
    'xTrials',numel(detail.xTrials),'yTrials',numel(detail.yTrials), ...
    'geometricYRatio',detail.yTrials(4).quality.maximumAdjacentCellRatio, ...
    'baselineXRatio',d.x.maximumAdjacentRatio, ...
    'baselineYRatio',d.y.maximumAdjacentRatio, ...
    'rows',rows,'deterministic',true,'noTransfer',true);
fid=fopen(outputFile,'w');assert(fid>=0);cleaner=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
function rows=append(rows,row)
if isempty(rows),rows=row;else,rows(end+1)=row;end
end
