function report=test_v5_axis_cache_equivalence(checkpointFile)
%TEST_V5_AXIS_CACHE_EQUIVALENCE The per-plan cache changes cost, not output.
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
assert(all(ipm.output.trustedMask(cp.payload.log.history,s.config)));
policy=ipm.config.autonomousMeshPolicy(struct('version',5, ...
    'nodeFamily',struct('maximumTotalNodes',1000000, ...
    'initialNodeCount',[s.config.grid.nx,s.config.grid.ny])));
root=s.runMetadata.autonomousMesh.referenceFamily;
family=ipm.remesh.referenceAxisFamily(root.rootX,root.rootY, ...
    s.config.scaling.transportAnchorX,policy);
Dx=ipm.mesh.fdMatrix(s.x,1,7);
view=struct('rho',s.rho,'x',s.x,'y',s.y,'Dx',Dx, ...
    'source',s.rho*Dx','trusted',true);
factors=[2,2;3,2;3,3;2,3];registered=vertcat(family.members.cellFactors);
cache=struct();
for k=1:size(factors,1)
    id=find(all(registered==factors(k,:),2));assert(isscalar(id));
    member=family.members(id);axes=struct('x',member.baseX,'y',member.baseY);
    [fresh,plain,audit]=ipm.remesh.hierarchicalAxisPairs(view,axes, ...
        s.config.scaling.transportAnchorX,policy,1000000);
    [reused,cached,cachedAudit,cache]=ipm.remesh.hierarchicalAxisPairs(view,axes, ...
        s.config.scaling.transportAnchorX,policy,1000000,cache);
    assert(isequaln(fresh,reused)&&isequaln(plain,cached)&&isequaln(audit,cachedAudit));
end
assert(numel(cache.xEntries)==2&&numel(cache.yEntries)==2);
report=struct('kind','v5_axis_cache_exact_equivalence_v1', ...
    'sourceCheckpoint',checkpointFile,'testedFactors',factors, ...
    'uniqueXAxisTrials',numel(cache.xEntries), ...
    'uniqueYAxisTrials',numel(cache.yEntries), ...
    'allCandidatesReportsAndAuditsExact',true,'noLU',true);
fprintf('V5_CACHE_EQUIVALENT comparisons=%d uniqueX=%d uniqueY=%d\n', ...
    size(factors,1),numel(cache.xEntries),numel(cache.yEntries));
end
