function report=test_v5_natural_remesh(outputDirectory)
%TEST_V5_NATURAL_REMESH Native t=0 run through unforced controller actions.
assert(~isfolder(outputDirectory),'ipm:V5NaturalRemeshOutputExists');
settings=struct('canonicalFinalTime',.5,'maximumSteps',1000, ...
    'autonomousMeshVersion',5,'maximumTotalNodes',310000, ...
    'maximumAdjacentGridRatio',2,'outputEvery',.05, ...
    'checkpointEvery',.1,'outputDirectory',outputDirectory, ...
    'storeSnapshots',false,'verbose',false);
opts=ipm.config.longTimeProfile(settings);
result=ipm.solve(opts);
assert(strcmp(char(result.state.stopReason),'final_time')&& ...
    result.state.canonicalTime>=.5-1e-10);
ipm.output.validate(result);
checkpointFile=char(result.metadata.latestCheckpointFile);
cp=ipm.output.readCheckpoint(checkpointFile);s=cp.payload.state;
memory=s.runMetadata.autonomousMesh;
assert(s.step==result.state.steps&&memory.version==5&& ...
    s.remeshCount>=1&&numel(memory.transactions)==s.remeshCount);
report=struct('kind','v5_unforced_t0_remesh_run_v1', ...
    'outputDirectory',outputDirectory,'checkpointFile',checkpointFile, ...
    'steps',s.step,'canonicalTime',s.scale.canonicalTime, ...
    'physicalTime',s.scale.physicalTime, ...
    'nodeCount',[numel(s.x),numel(s.y)], ...
    'naturalRemeshCount',s.remeshCount, ...
    'currentLevelId',memory.currentLevelId, ...
    'firstTransactionTime',memory.transactions(1).sourceCanonicalTime, ...
    'resultValidated',true,'checkpointValidated',true, ...
    'manualTriggerUsed',false,'nativePdeAdvanced',true);
fprintf('V5_NATURAL tau=%.9f steps=%d remesh=%d n=%dx%d firstTau=%.9f\n', ...
    report.canonicalTime,report.steps,report.naturalRemeshCount, ...
    report.nodeCount(1),report.nodeCount(2),report.firstTransactionTime);
end
