function report=test_v5_initial_failure_compact()
%TEST_V5_INITIAL_FAILURE_COMPACT Verify bounded H256 failure diagnostics.
opts=ipm.config.longTimeProfile(struct('boxHalfWidth',256, ...
    'boxHeight',128,'initialNodeCount',[321,161], ...
    'autonomousMeshVersion',5,'maximumTotalNodes',310000, ...
    'verbose',false));
try
    ipm.evolve.initialize(opts);
    error('ipm:ExpectedInitialCapacityFailure', ...
        'The known fixed 321x161 H256 failure unexpectedly passed.');
catch e
    assert(strcmp(e.identifier,'ipm:InitialObservationCapacity'));
    assert(~isempty(e.cause)&&strcmp(e.cause{1}.identifier, ...
        'ipm:InitialObservationEvidence'));
    message=e.cause{1}.message;
    assert(numel(message)<4000&&contains(message,'xAdmitted')&& ...
        contains(message,'sourceNodeCount')&& ...
        contains(message,'fixed_observation_capacity_rejected'));
end
report=struct('kind','v5_initial_capacity_compact_diagnostic_v1', ...
    'box',[256,128],'initialNodeCount',[321,161], ...
    'exceptionIdentifier',e.identifier,'renderedCharacters',numel(message), ...
    'bounded',true);
fprintf('V5_INITIAL_FAILURE_COMPACT chars=%d id=%s\n', ...
    report.renderedCharacters,report.exceptionIdentifier);
end
