function report=test_density_mode_one_cross_level(distributionFile,outputFile)
%TEST_DENSITY_MODE_ONE_CROSS_LEVEL Late frozen directional growth geometry.
assert(isfile(distributionFile)&&~isfile(outputFile));
d=jsondecode(fileread(distributionFile));c=ipm.output.readCheckpoint(d.checkpointFile);
saved=c.payload.state;memory=saved.runMetadata.autonomousMesh;
input=saved.config.remesh.autonomousMesh;input.densityVersion=1;
input.search.roundingCells=[8,16,24,32,40];
policy=ipm.config.autonomousMeshPolicy(input);
members=memory.referenceFamily.members;
counts=vertcat(members.nodeCount);
index=find(counts(:,1)>numel(saved.x) & counts(:,2)==numel(saved.y),1);
assert(~isempty(index));target=members(index);
x=saved.x(:)';y=saved.y(:);Dx=ipm.mesh.fdMatrix(x,1,7);
view=struct('rho',saved.rho,'x',x,'y',y,'Dx',Dx, ...
    'source',saved.rho*Dx','trusted',true);
[pairs,detail,search]=ipm.remesh.hierarchicalAxisPairs(view, ...
    struct('x',target.baseX,'y',target.baseY),1,policy, ...
    policy.nodeFamily.maximumTotalNodes);
[oldPairs,oldDetail]=ipm.remesh.hierarchicalAxisPairs(view, ...
    struct('x',target.baseX,'y',target.baseY),1, ...
    saved.config.remesh.autonomousMesh, ...
    saved.config.remesh.autonomousMesh.nodeFamily.maximumTotalNodes);
legacyBest=[NaN,NaN,NaN];
if ~isempty(oldPairs)
    legacyBest=[oldPairs(1).quality.x.maximumAdjacentCellRatio, ...
        oldPairs(1).quality.y.maximumAdjacentCellRatio, ...
        max(oldPairs(1).quality.x.maximumAdjacentCellRatio, ...
            oldPairs(1).quality.y.maximumAdjacentCellRatio)];
end
rows=struct([]);
for k=1:numel(pairs)
    p=pairs(k);
    rows=append(rows,struct('index',k,'nodeCount',[numel(p.x),numel(p.y)], ...
        'xTrial',p.xIndex,'yTrial',p.yIndex, ...
        'maximumAdjacentRatio',max(p.quality.x.maximumAdjacentCellRatio, ...
            p.quality.y.maximumAdjacentCellRatio), ...
        'xRatio',p.quality.x.maximumAdjacentCellRatio, ...
        'yRatio',p.quality.y.maximumAdjacentCellRatio, ...
        'predictedCells',p.predictedCells));
end
report=struct('kind','density_mode_one_late_cross_level_geometry_v1', ...
    'source',distributionFile,'tau',d.tau, ...
    'sourceNodeCount',[numel(x),numel(y)], ...
    'targetNodeCount',target.nodeCount,'targetLevelId',index, ...
    'status',detail.status,'searchStatus',search.status, ...
    'geometricYAdmissible',detail.yTrials(4).admissible, ...
    'geometricYRatio',NaN,'candidateCount',numel(pairs), ...
    'legacyCandidateCount',numel(oldPairs), ...
    'legacyStatus',oldDetail.status, ...
    'legacyBestRatioXYMax',legacyBest, ...
    'rows',rows,'noTransfer',true,'futureLifetimeCertified',false);
if detail.yTrials(4).admissible
    report.geometricYRatio=detail.yTrials(4).quality.maximumAdjacentCellRatio;
end
fid=fopen(outputFile,'w');assert(fid>=0);cleaner=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
function rows=append(rows,row)
if isempty(rows),rows=row;else,rows(end+1)=row;end
end
