function report=verify_ranked_lifetime_followup(auditReportFile, ...
        outcomeCheckpoint,outputDirectory)
%VERIFY_RANKED_LIFETIME_FOLLOWUP Compare an earlier rank with a new signed event.
assert(~isfolder(outputDirectory));
audit=jsondecode(fileread(auditReportFile));
assert(strcmp(audit.kind,'independent_late_mesh_lifetime_rank_audit_v1'));
checkpoint=ipm.output.readCheckpoint(outcomeCheckpoint);
saved=checkpoint.payload.state;
assert(all(ipm.output.trustedMask( ...
    checkpoint.payload.log.history,saved.config)));
transactions=saved.runMetadata.autonomousMesh.transactions;
k=audit.transactionIndex;
assert(numel(transactions)>=k+1 && ...
    transactions(k).sourceStep==audit.sourceStep && ...
    transactions(k).sourceCanonicalTime==audit.sourceTau && ...
    transactions(k).candidateIndex==audit.baselineSelectedCandidateIndex && ...
    audit.rankedSelectedCandidateIndex==audit.baselineSelectedCandidateIndex, ...
    'ipm:RankedLifetimeFollowupLineageMismatch');
estimated=audit.rows(audit.rankedSelectedCandidateIndex).estimatedBottleneckLifetime;
actual=transactions(k+1).sourceCanonicalTime-audit.sourceTau;
report=struct('kind','signed_ranked_lifetime_followup_v1', ...
    'auditReportFile',auditReportFile, ...
    'outcomeCheckpoint',outcomeCheckpoint, ...
    'outcomeCheckpointValidated',true, ...
    'transactionIndex',k,'sourceTau',audit.sourceTau, ...
    'nextRequestTau',transactions(k+1).sourceCanonicalTime, ...
    'nextRequestReason',transactions(k+1).controllerDecision.reason, ...
    'estimatedBottleneckLifetime',estimated, ...
    'actualInterval',actual, ...
    'estimatedToActualRatio',estimated/actual, ...
    'estimationError',estimated-actual);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('FOLLOWUP tx=%d actual=%.9f estimate=%.9f ratio=%.5f\n', ...
    k,actual,estimated,estimated/actual);
end
