function report=verify_continuous_vertical_shadow(runDirectory,outputDirectory)
%VERIFY_CONTINUOUS_VERTICAL_SHADOW Test local PCHIP against full interpolation
% on frozen, signed native checkpoints without constructing a Poisson factor.
steps=[7912,8107,8296,8478,8693,8912,9124,9328];
assert(~isfolder(outputDirectory));
maxCellError=0;maxWidthError=0;records=struct([]);
shadow=[];
for k=1:numel(steps)
    pattern=sprintf('*step%010d.mat',steps(k));
    files=dir(fullfile(runDirectory,pattern));assert(numel(files)==1);
    cp=ipm.output.readCheckpoint(fullfile(files.folder,files.name));
    s=cp.payload.state;h=cp.payload.log.history;
    x=s.x;y=s.y;source=s.rho*ipm.mesh.fdMatrix(x,1,7)';
    peakX=h.gauge.omegaGaugeQuadraticPeakX(end);
    flow=struct('source',source,'omegaGaugeQuadraticPeakX',peakX, ...
        'omegaGaugePeakX',h.gauge.omegaGaugePeakX(end), ...
        'verticalCoreGridPoints',h.mesh.verticalCoreGridPoints(end), ...
        'safetyFactor',h.mesh.safetyFactor(end));
    q=ipm.remesh.continuousVerticalCore(flow,x,y,s.config.scaling.adaptiveLevels);
    full=ipm.diagnostics.peakResolution( ...
        abs(interp1(x,source',peakX,'pchip')),y,s.config.scaling.adaptiveLevels);
    maxCellError=max(maxCellError,abs(q.coreCells-full.gridPoints(end)));
    maxWidthError=max(maxWidthError,abs(q.coreWidth-full.widths(end)));
    state=struct('config',s.config,'scale',s.scale,'step',s.step, ...
        'ops',struct('x',x,'y',y,'remeshCount',s.remeshCount), ...
        'flow',flow);
    baseline=struct('coreCells',[h.mesh.coreGridPoints(end), ...
        h.mesh.verticalCoreGridPoints(end)], ...
        'predictedCoreCells',[h.mesh.coreGridPoints(end), ...
        h.mesh.verticalCoreGridPoints(end)], ...
        'requested',false,'reason','frozen_observation_only');
    if k==5,shadow=[];end
    shadow=ipm.remesh.continuousVerticalShadow(shadow,state, ...
        s.config.remesh.autonomousMesh,baseline);
    assert(shadow.observations==mod(k-1,4)+1 && ...
        shadow.latest.continuousCells==q.coreCells);
    if k==1
        modified=cp;
        modified.payload.state.runMetadata.continuousVerticalShadow=shadow;
        modified.signature=ipm.output.checkpointSignature(modified.payload);
        ipm.output.readCheckpoint(modified);
    end
    row=struct('step',s.step,'tau',s.scale.canonicalTime, ...
        'remeshCount',s.remeshCount,'nodalYCells',flow.verticalCoreGridPoints, ...
        'continuousYCells',q.coreCells,'localPchipWidth',q.coreWidth, ...
        'fullPchipWidth',full.widths(end), ...
        'sparseShadowPredictedYCells',shadow.latest.continuousPredictedCells(2)); %#ok<AGROW>
    if isempty(records),records=row;else,records(end+1)=row;end %#ok<AGROW>
end
assert(maxCellError<1e-10 && maxWidthError<1e-12, ...
    'ipm:ContinuousVerticalPchipMismatch');
report=struct('kind','continuous_vertical_shadow_frozen_checkpoint_verification_v1', ...
    'noPoissonFactor',true,'nativeStateUnchanged',true, ...
    'shadowMetadataAcceptedBySignedCheckpointContract',true, ...
    'shadowDecisionsAreSparseCheckpointSamplesOnly',true, ...
    'maxAbsoluteCellError',maxCellError,'maxAbsoluteWidthError',maxWidthError, ...
    'records',{records});
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('CONTINUOUS_SHADOW maxCellError=%.3e maxWidthError=%.3e\n', ...
    maxCellError,maxWidthError);
end
