function report = layout()
%LAYOUT Ensure public packages resolve locally and runtime dependencies stay local.

root = fileparts(fileparts(fileparts(mfilename('fullpath'))));
entryPoints = { ...
    'ipm.solve',fullfile(root,'+ipm','solve.m'); ...
    'ipm.verify',fullfile(root,'+ipm','verify.m'); ...
    'ipm.config.resolve',fullfile(root,'+ipm','+config','resolve.m'); ...
    'ipm.output.validate',fullfile(root,'+ipm','+output','validate.m')};
for index = 1:size(entryPoints,1)
    assert(strcmp(which(entryPoints{index,1}),entryPoints{index,2}), ...
        'ipm:PackageResolution', ...
        '%s does not resolve to this repository.',entryPoints{index,1});
end

dependencies = matlab.codetools.requiredFilesAndProducts( ...
    fullfile(root,'+ipm','solve.m'));
for index = 1:numel(dependencies)
    file = dependencies{index};
    localRuntime = startsWith(file,[fullfile(root,'+ipm'),filesep]);
    matlabRuntime = startsWith(file,[matlabroot,filesep]);
    assert(localRuntime || matlabRuntime,'ipm:ExternalSolverDependency', ...
        'The solver depends on a file outside its runtime packages: %s',file);
end
runtimeFiles = dir(fullfile(root,'+ipm','**','*.m'));
report = struct('passed',true,'runtimeFiles',numel(runtimeFiles), ...
    'publicEntryPoints',size(entryPoints,1), ...
    'runtimeDependencies',numel(dependencies));
fprintf(['Package layout passed: %d runtime files, %d public entry ' ...
    'points, %d dependencies.\n'],report.runtimeFiles, ...
    report.publicEntryPoints,report.runtimeDependencies);
end
