function report = quadrant()
%QUADRANT Verify positive-only storage, parity, Green, RHS, and direct remesh.
full = base_options();
legacyConfig = ipm.config.resolve(full);
assert(~isfield(legacyConfig.grid,'quadrantOnly'), ...
    'ipm:QuadrantOptIn','The legacy configuration gained an implicit quadrant flag.');
bad = full;bad.quadrantOnly=true;
assert_error(@()ipm.config.resolve(bad),'ipm:QuadrantDomain');
bad = full;bad.quadrantOnly=2;
assert_error(@()ipm.config.resolve(bad),'ipm:BadQuadrantOnly');
quarter = full;
quarter.quadrantOnly = true;
quarter.nx = (full.nx+1)/2;
quarter.xlim = [0,full.xlim(2)];
bad=quarter;bad.transportScheme='muscl_minmod';
assert_error(@()ipm.config.resolve(bad),'ipm:QuadrantNumericalTuple');
fullState = ipm.evolve.initialize(full);
quarterState = ipm.evolve.initialize(quarter);
first = (full.nx+1)/2;
assert(quarterState.ops.x(1)==0 && ...
    all(quarterState.ops.x>=0) && ...
    isequal(size(quarterState.rho),[full.ny,quarter.nx]) && ...
    ~isfield(fullState.ops,'quadrantOnly'), ...
    'ipm:QuadrantStorage','The runtime must store only positive x nodes.');
[fullRhs,fullFlow] = ipm.evolve.flow( ...
    fullState.rho,fullState.ops,fullState.scale);
[quarterRhs,quarterFlow] = ipm.evolve.flow( ...
    quarterState.rho,quarterState.ops,quarterState.scale);
errors = struct( ...
    'rho',max(abs(fullState.rho(:,first:end)-quarterState.rho),[],'all'), ...
    'omega',max(abs(fullFlow.source(:,first:end)-quarterFlow.source),[],'all'), ...
    'psi',max(abs(fullFlow.psi(:,first:end)-quarterFlow.psi),[],'all'), ...
    'u1',max(abs(fullFlow.u1(:,first:end)-quarterFlow.u1),[],'all'), ...
    'u2',max(abs(fullFlow.u2(:,first:end)-quarterFlow.u2),[],'all'), ...
    'rhs',max(abs(fullRhs(:,first:end)-quarterRhs),[],'all'), ...
    'cL',abs(fullFlow.c_l-quarterFlow.c_l), ...
    'cOmega',abs(fullFlow.c_omega-quarterFlow.c_omega));
assert(max(struct2array(errors))<1e-10 && ...
    all(quarterFlow.source(:,1)==0) && ...
    all(quarterFlow.psi(:,1)==0) && ...
    all(quarterFlow.u1(:,1)==0), ...
    'ipm:QuadrantParity','Quadrant and full positive-side RHS differ.');
diagnostics=ipm.diagnostics.measure(quarterState.rho, ...
    quarterFlow,quarterState.ops,quarterState.mass0);
speed=hypot(quarterFlow.u1,quarterFlow.u2);
outerX=max(2,ceil(.05*quarter.nx));
outerY=max(2,ceil(.05*quarter.ny));
expectedFar=max(max(speed(:,end-outerX+1:end),[],'all'), ...
    max(speed(end-outerY+1:end,:),[],'all'));
assert(abs(diagnostics.farBoundaryVelocity-expectedFar)<1e-14, ...
    'ipm:QuadrantFarBoundary', ...
    'The x=0 symmetry axis was misclassified as an artificial far boundary.');

small = quarter;
small.nx = 65;
small.ny = 33;
smallState = ipm.evolve.initialize(small);
[rhoNew,opsNew,info] = ipm.remesh.directLevelSetAdapt( ...
    smallState.rho,smallState.ops,smallState.flow,smallState.config,1);
assert(info.applied && info.geometryProposals==1 && ...
    info.nativeTransfers==1 && opsNew.x(1)==0 && ...
    strcmp(info.xConstruction.baseConstruction.splitStrategy, ...
        'direct_log_span_projection') && ...
    info.xConstruction.baseConstruction.splitEvaluations==1 && ...
    isequal(size(rhoNew),size(smallState.rho)) && ...
    info.massRelativeDefect<5e-12, ...
    'ipm:QuadrantDirectRemesh', ...
    'The direct level-set transaction failed its native gates.');
[largeAxis,largeConstruction]=ipm.remesh.roundedAxis( ...
    1,4,1025,.001,24,.5,16,true);
assert(numel(largeAxis)==1025 && all(diff(largeAxis)>0) && ...
    largeConstruction.nodeCount==1025 && ...
    largeConstruction.conceptualFullNodeCount==2049 && ...
    largeConstruction.splitEvaluations==1, ...
    'ipm:QuadrantLargeAxis', ...
    'The positive 1025-node axis must avoid split enumeration.');
[evenAxis,evenConstruction]=ipm.remesh.roundedAxis( ...
    1,4,1024,.001,24,.5,16,true);
assert(numel(evenAxis)==1024 && all(diff(evenAxis)>0) && ...
    evenConstruction.nodeCount==1024 && ...
    evenConstruction.conceptualFullNodeCount==2047 && ...
    evenConstruction.splitEvaluations==1, ...
    'ipm:QuadrantEvenAxis', ...
    'The quadrant constructor must count actual nodes, even when N is even.');
enabledConfig=smallState.config;
enabledConfig.remesh.adaptiveRemesh=true;
quietSafety=smallState.flow;quietSafety.safetyFactor=0;
[~,~,~,directTrigger]=ipm.evolve.remeshIfNeeded( ...
    smallState.rho,smallState.ops,quietSafety,smallState.scale,enabledConfig);
assert(directTrigger.applied, ...
    'ipm:QuadrantLevelSetTrigger', ...
    'The 90%% core level set must trigger without the legacy safety factor.');
resolvedCore=smallState.flow;
resolvedCore.coreGridPoints=1e3;
resolvedCore.verticalCoreGridPoints=1e3;
resolvedCore.safetyFactor=1e6;
[~,~,~,noTrigger]=ipm.evolve.remeshIfNeeded( ...
    smallState.rho,smallState.ops,resolvedCore,smallState.scale,enabledConfig);
assert(~noTrigger.applied, ...
    'ipm:QuadrantLevelSetTrigger', ...
    'A legacy safety factor alone must not trigger quadrant remeshing.');
otherLevels=small;
otherLevels.adaptiveLevels=[.1,.5,.8];
otherState=ipm.evolve.initialize(otherLevels);
otherConfig=otherState.config;
otherConfig.remesh.adaptiveRemesh=true;
otherFlow=otherState.flow;
otherFlow.coreGridPoints=1e3;
otherFlow.verticalCoreGridPoints=1e3;
otherFlow.safetyFactor=0;
[~,~,~,otherTrigger]=ipm.evolve.remeshIfNeeded( ...
    otherState.rho,otherState.ops,otherFlow,otherState.scale,otherConfig);
assert(isfield(otherTrigger,'kind'), ...
    'ipm:QuadrantLevelSetFallback', ...
    'A non-90%% diagnostic level must use the direct 90%% measurement.');
noPeak=small;
noPeak.rescalingMode='physical';
noPeak.initialCondition=@(X,Y)zeros(size(X));
noPeak.adaptiveRemesh=true;
noPeak.initialAnalyticRemesh=true;
noPeakState=ipm.evolve.initialize(noPeak);
assert(noPeakState.ops.remeshCount==0 && ...
    all(noPeakState.rho==0,'all'), ...
    'ipm:QuadrantAbsentLevelSet', ...
    'A peak-free physical state must not attempt level-set remeshing.');
[~,newFlow] = ipm.evolve.flow(rhoNew,opsNew,smallState.scale);
assert(all(isfinite(newFlow.u1),'all') && ...
    all(newFlow.source(:,1)==0), ...
    'ipm:QuadrantDirectFlow','The transferred flow is invalid.');
fullCustom=full;
fullCustom.ny=small.ny;
fullCustom.customX=[-fliplr(opsNew.x(2:end)),opsNew.x];
fullCustom.customY=opsNew.y;
customConfig=ipm.config.resolve(fullCustom);
customFullOps=ipm.mesh.build(customConfig);
customFullRho=[fliplr(rhoNew(:,2:end)),rhoNew];
[fullU1,fullU2,fullPsi,fullSource]= ...
    ipm.field.velocity(customFullRho,customFullOps);
[fullTransport,~]=ipm.field.transport( ...
    customFullRho,fullU1,fullU2,customFullOps);
[quarterTransport,~]=ipm.field.transport( ...
    rhoNew,newFlow.u1,newFlow.u2,opsNew);
positiveColumns=small.nx:2*small.nx-1;
nonuniformErrors=[ ...
    max(abs(customFullOps.metricX(positiveColumns)-opsNew.metricX)), ...
    max(abs(fullSource(:,positiveColumns)-newFlow.source),[],'all'), ...
    max(abs(fullPsi(:,positiveColumns)-newFlow.psi),[],'all'), ...
    max(abs(fullU1(:,positiveColumns)-newFlow.u1),[],'all'), ...
    max(abs(fullU2(:,positiveColumns)-newFlow.u2),[],'all'), ...
    max(abs(fullTransport(:,positiveColumns)-quarterTransport),[],'all')];
assert(max(nonuniformErrors)<1e-10, ...
    'ipm:QuadrantNonuniformParity', ...
    'The focused nonuniform grid lost full-domain parity equivalence.');

small.adaptiveRemesh=true;
small.initialAnalyticRemesh=true;
small.initialAnalyticRemeshPasses=1;
small.finalTime=.002;
small.maxDt=.0005;
small.maxSteps=8;
small.outputEvery=.0005;
result=ipm.solve(small);
assert(result.grid.x(1)==0 && all(result.grid.x>=0) && ...
    result.grid.remeshCount>=1 && result.state.steps>=2 && ...
    isequal(size(result.state.rho),[small.ny,small.nx]) && ...
    all(isfinite(result.state.rho),'all'), ...
    'ipm:QuadrantShortSolve','The short quadrant solve failed.');
ipm.output.validate(result);
checkpointFolder=tempname;
mkdir(checkpointFolder);
checkpointCleanup=onCleanup(@()rmdir(checkpointFolder,'s'));
small.checkpoint=struct('enabled',true, ...
    'file',fullfile(checkpointFolder,'checkpoint.mat'), ...
    'every',Inf,'atExit',true);
checkpointResult=ipm.solve(small);
checkpoint=ipm.output.readCheckpoint( ...
    checkpointResult.metadata.latestCheckpointFile);
[restored,~,~]=ipm.output.restoreCheckpoint( ...
    checkpoint,struct('finalTime',.003,'maxSteps',12,'saveResults',false));
assert(all(checkpoint.payload.state.x>=0) && ...
    restored.ops.x(1)==0 && ...
    restored.ops.nx==small.nx && ...
    restored.ops.remeshCount>=1, ...
    'ipm:QuadrantCheckpoint', ...
    'The native checkpoint recorded a mirrored axis or failed restoration.');
assert(isa(checkpointCleanup,'onCleanup'));
report=struct('passed',true,'comparison',errors, ...
    'nonuniformErrors',nonuniformErrors, ...
    'directRemesh',info,'shortSteps',result.state.steps, ...
    'shortRemeshCount',result.grid.remeshCount, ...
    'storedNodes',numel(result.state.rho), ...
    'conceptualFullNodes',(2*small.nx-1)*small.ny, ...
    'checkpointRestored',true);
fprintf('Quadrant parity, single-proposal remesh, and short solve passed.\n');
end

function assert_error(action,identifier)
try
    action();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:QuadrantConfigError', ...
        'Expected %s, got %s.',identifier,exception.identifier);
    return
end
error('ipm:QuadrantConfigError','Expected %s to be rejected.',identifier);
end

function opts=base_options()
opts=struct('nx',129,'ny',65,'xlim',[-4,4],'ymax',4, ...
    'gridMode','uniform','gridStretchAutomatic',false, ...
    'gridStretch',[0,0], ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'rescalingMode','dynamic','lengthGauge','transport_anchor', ...
    'transportAnchorX',1,'cOmegaGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',.5, ...
    'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'farBoundaryMode','green','saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false, ...
    'verbose',false);
end
