function [metadata,config,current] = autonomousControllerFixture()
%IPMTESTS.SUPPORT.AUTONOMOUSCONTROLLERFIXTURE Synthetic ledger, not a PDE run.
% Recorded feature values/jumps below are constructed contract fixtures.
x = linspace(-2,2,129);y = linspace(0,2,65)';
options = struct('nx',numel(x),'ny',numel(y),'customX',x,'customY',y, ...
    'rescalingMode','dynamic','dynamicScaleGeometry','isotropic','symmetryMode','double_odd_omega', ...
    'lengthGauge','transport_anchor','cOmegaGauge','wall_omega_quadratic_peak', ...
    'spatialDiscretization','high_order','transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order','adaptiveRemesh',true,'initialAnalyticRemesh',true,'autonomousMesh',struct());
config = ipm.config.resolve(options);p = config.remesh.autonomousMesh;
qx = ipm.mesh.quality(x,7,ipm.mesh.quadrature(x));qy = ipm.mesh.quality(y,7,ipm.mesh.quadrature(y));
s = struct('step',0,'scale',struct('canonicalTime',0,'physicalTime',0), ...
    'ops',struct('remeshCount',0),'flow',struct('coreGridPoints',40,'verticalCoreGridPoints',44,'safetyFactor',.3));
memory = ipm.remesh.controllerTelemetry([],s,p);
audit = struct('kind','analytic_zero_time_axis_selection_audit','passed',true,'reasons',{{}}, ...
    'coreCells',[40,44],'leftFrontCells',24,'qualityPassed',true,'exactZeroTime',true, ...
    'xQuality',qx,'yQuality',qy,'massMigrationClaim',false,'initialDensityExactlyResampled',true);
attempt = struct('candidateIndex',1,'passed',true,'audit',audit,'errorIdentifier','','errorMessage','');
memory.initialization = struct('sourceBaseX',x,'sourceBaseY',y,'selectedBaseX',x,'selectedBaseY',y, ...
    'selectedCandidateIndex',1,'audit',audit,'attempts',attempt,'analyticDatumResampled',true, ...
    'originalStep',0,'originalCanonicalTime',0,'originalPhysicalTime',0,'originalRemeshCount',0, ...
    'newPhysicalEpochCreated',false,'operatorGridRepresentation','custom_axes');
physical = [.03,.08];cores = [38,42;35,40];
for k = 1:2
    a = struct('version',1,'kind','autonomous_actual_candidate_audit','passed',true,'reasons',{{}}, ...
        'sourceStep',10*k,'sourceCanonicalTime',.1*k,'sourcePhysicalTime',physical(k), ...
        'sourceRemeshCount',k-1,'coreCells',cores(k,:),'leftFrontCells',22,'relativePeakJump',k*1e-4, ...
        'priorCumulativeAbsolutePeakJump',memory.cumulativeAbsolutePeakJump, ...
        'cumulativeAbsolutePeakJump',memory.cumulativeAbsolutePeakJump+k*1e-4, ...
        'massRelativeDefect',1e-14,'relativeRangeViolation',1e-6,'xQuality',qx,'yQuality',qy, ...
        'clocksAndReferencesPreserved',true,'sameBoxAndNodeCount',true);
    if isempty(memory.transactions),memory.transactions=a;else,memory.transactions(end+1)=a;end
    memory.cumulativeAbsolutePeakJump = sum([memory.transactions.relativePeakJump]);
    s.step = 10*k;s.scale.canonicalTime = .1*k;s.scale.physicalTime = physical(k);s.ops.remeshCount = k;
    s.flow.coreGridPoints = cores(k,1);s.flow.verticalCoreGridPoints = cores(k,2);
    memory = ipm.remesh.controllerTelemetry(memory,s,p);
end
steps = [21,22,25];times = [.21,.22,.25];physical = [.082,.084,.09];
for k = 1:3
    s.step = steps(k);s.scale.canonicalTime = times(k);s.scale.physicalTime = physical(k);
    s.flow.coreGridPoints = 35-k;s.flow.verticalCoreGridPoints = 40-k;
    memory = ipm.remesh.controllerTelemetry(memory,s,p);
end
h = struct('common',struct('acceptedStep',[0;10;15;20;25], ...
    'canonicalTau',[0;.1;.15;.2;.25],'physicalTime',[0;.03;.05;.08;.09],'t',[0;.1;.15;.2;.25]), ...
    'mesh',struct('remeshCount',[0;1;1;2;2],'coreGridPoints',[40;38;37;35;32], ...
    'verticalCoreGridPoints',[44;42;41;40;37],'safetyFactor',.3*ones(5,1)));
current = struct('step',25,'canonicalTime',.25,'physicalTime',.09,'normalizedTime',.25, ...
    'remeshCount',2,'coreCells',[32,37],'safety',.3,'x',x,'y',y,'baseX',x,'baseY',y,'history',h);
metadata = struct('caseId','synthetic_controller_contract_only', ...
    'caseMetadata',struct('testFixtureOnly',true,'pdeRunClaim',false),'autonomousMesh',memory);
end
