function report = analyze_outer_cutoff_checkpoints(runDirectory,outputFile,maximumFiles)
%ANALYZE_OUTER_CUTOFF_CHECKPOINTS Read native R2.2 checkpoints, no PDE steps.
%   Select the latest MAXIMUMFILES accepted checkpoints in increasing step
%   order. Each checkpoint is restored on its own paired adaptive grid, and
%   its exact semidiscrete RHS supplies R_{X tau}. The stored trajectory is
%   neither resumed nor altered.
if nargin < 3 || isempty(maximumFiles), maximumFiles = 8; end
assert(isfolder(runDirectory) && ischar(outputFile) && ...
    isnumeric(maximumFiles) && isscalar(maximumFiles) && ...
    maximumFiles>=1 && maximumFiles==fix(maximumFiles), ...
    'ipm:OuterCutoffInput','Provide a run directory, output file, and count.');
assert(~isfile(outputFile),'ipm:OuterCutoffOutputExists', ...
    'Choose a new output file; do not overwrite an earlier audit.');
files = dir(fullfile(runDirectory,'checkpoint_*_step*.mat'));
assert(~isempty(files),'ipm:OuterCutoffNoCheckpoint', ...
    'The run has no accepted checkpoint yet.');
steps = zeros(1,numel(files));
for k=1:numel(files)
    token = regexp(files(k).name,'_step([0-9]+)\.mat$','tokens','once');
    assert(~isempty(token),'ipm:OuterCutoffCheckpointName', ...
        'Checkpoint names must contain their accepted step.');
    steps(k) = str2double(token{1});
end
[~,order] = sort(steps);
files = files(order);
files = files(max(1,numel(files)-maximumFiles+1):end);
count = numel(files);
sample = cell(1,count);
pair = cell(1,max(count-1,0));
finalPairObservationRefinement = struct([]);
tau = zeros(1,count);
caseId = cell(1,count);
previousNative = [];
for k=1:count
    fileName = fullfile(files(k).folder,files(k).name);
    [state,~,~] = ipm.output.restoreCheckpoint(fileName,struct());
    assert(strcmp(state.config.scaling.cOmegaGauge, ...
        'outer_wall_density_window_l2') && ...
        state.config.remesh.autonomousMesh.enabled && ...
        state.config.remesh.autonomousMesh.version==5, ...
        'ipm:OuterCutoffWrongRun','Expected the new C and v5 mesh run.');
    sample{k} = outer_cutoff_norms(state);
    native = struct('x',state.ops.x,'y',state.ops.y, ...
        'Rx',state.rho*state.ops.Dx', ...
        'tau',state.scale.canonicalTime);
    if k>1
        pair{k-1}=outer_cutoff_pair_norms(previousNative,native, ...
            sample{k}.radii,[1,2,4,Inf]);
        if k==count
            fine=outer_cutoff_pair_norms(previousNative,native, ...
                sample{k}.radii,[1,2,4,Inf],[801,401]);
            coarseNorms=[pair{k-1}.rows.incrementNorm];
            fineNorms=[fine.rows.incrementNorm];
            relativeDifference=abs(coarseNorms-fineNorms)./ ...
                max(abs(fineNorms),realmin);
            finalPairObservationRefinement=struct( ...
                'coarseNodes',pair{k-1}.observationNodes, ...
                'fineNodes',fine.observationNodes, ...
                'relativeDifference',relativeDifference, ...
                'maximumRelativeDifference',max(relativeDifference), ...
                'finePair',fine);
        end
    end
    previousNative=native;
    sample{k}.checkpointFile = fileName;
    tau(k) = state.scale.canonicalTime;
    caseId{k} = char(state.runMetadata.caseId);
    fprintf('Outer cutoff: tau=%.9g, step=%d, grid=%d x %d\n', ...
        tau(k),state.step,numel(state.ops.x),numel(state.ops.y));
    clear state
end
assert(all(diff(tau)>0) && isscalar(unique(string(caseId))), ...
    'ipm:OuterCutoffTrajectory','Checkpoints must be one ordered trajectory.');

rowCount = numel(sample{1}.rows);
series = struct([]);
for rowIndex=1:rowCount
    first = sample{1}.rows(rowIndex);
    norms = zeros(1,count);
    relative = zeros(1,count);
    candidateC = NaN(1,count);
    increments = zeros(1,max(count-1,0));
    relativeIncrements = increments;
    for k=1:count
        row=sample{k}.rows(rowIndex);
        assert(row.radius==first.radius && ...
            strcmp(row.domain,first.domain) && strcmp(row.p,first.p));
        norms(k)=row.mixedDerivativeNorm;
        relative(k)=row.relativeMixedDerivativeNorm;
        candidateC(k)=row.candidateOuterGradientGaugeC;
    end
    for k=2:count
        pairRow=pair{k-1}.rows(rowIndex);
        assert(pairRow.radius==first.radius && ...
            strcmp(pairRow.domain,first.domain) && ...
            strcmp(pairRow.p,first.p));
        increments(k-1)=pairRow.incrementNorm;
        relativeIncrements(k-1)=pairRow.relativeIncrementNorm;
    end
    logSlope=NaN;
    if count>=3
        tail=max(1,count-3):count;
        fit=polyfit(tau(tail)-tau(tail(1)), ...
            log(max(norms(tail),realmin)),1);
        logSlope=fit(1);
    end
    sampledIntegral=0;
    if count>=2
        sampledIntegral=trapz(tau,norms);
    end
    row=struct('radius',first.radius,'domain',first.domain,'p',first.p, ...
        'mixedDerivativeNorm',norms, ...
        'relativeMixedDerivativeNorm',relative, ...
        'cauchyIncrementNorm',increments, ...
        'relativeCauchyIncrementNorm',relativeIncrements, ...
        'sampledIncrementSum',sum(increments), ...
        'candidateOuterGradientGaugeC',candidateC, ...
        'sampledTimeIntegral',sampledIntegral, ...
        'lastOverFirst',norms(end)/max(norms(1),realmin), ...
        'lastFourPointLogSlope',logSlope);
    if isempty(series),series=row;else,series(end+1)=row;end %#ok<AGROW>
end
report=struct('kind','outer_cutoff_new_c_native_series_v1', ...
    'caseId',caseId{1},'tau',tau,'sampleCount',count, ...
    'sampleRecords',{sample},'pairRecords',{pair},'series',series, ...
    'finalPairObservationRefinement',finalPairObservationRefinement, ...
    'trustedCheckpointInputs',true,'pdeAdvanced',false, ...
    'interpretation', ...
    ['Finite-window norm trends and trapezoid integrals are diagnostic. ' ...
     'Convergence requires time-integrability or Cauchy control plus ' ...
     'space, time-step, radius and domain checks.']);
fid=fopen(outputFile,'w');
assert(fid>=0,'ipm:OuterCutoffOutput','Cannot create audit output.');
closer=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
