function report=audit_outer_wall_gauge_rhs(checkpointFile,outputFile)
%AUDIT_OUTER_WALL_GAUGE_RHS Exact frozen-state alternative c_omega rates.
% Restores one signed state and its native RHS. It does not advance the PDE,
% alter the checkpoint, or construct a counterfactual trajectory.
assert(maxNumCompThreads==10);
[state,~,~]=ipm.output.restoreCheckpoint(checkpointFile,struct());
assert(strcmp(state.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak') && ...
    strcmp(state.config.scaling.dynamicScaleGeometry,'isotropic'));
x=state.ops.x(:)';R=state.rho;
old=state.flow.c_omega;
B=state.rhsCache.rhoRate-old*R;
Rx=state.flow.source;
Bx=B*state.ops.Dx';
anchor=2;radius=0.5;
z=(x-anchor)/radius;
bump=zeros(size(z));inside=abs(z)<1;
bump(inside)=cos(pi*z(inside)/2).^2;
dx=diff(x);
wx=[dx(1),dx(1:end-1)+dx(2:end),dx(end)]/2;
w=wx.*bump;w=w/sum(w);
assert(nnz(w)>5 && all(isfinite(w)) && all(w>=0));
pointR=interp1(x,R(1,:),anchor,'linear');
pointB=interp1(x,B(1,:),anchor,'linear');
assert(isfinite(pointR) && pointR>0 && ...
    pointR/max(abs(R(1,:)))>1e-3);
cPoint=-pointB/pointR;
denom=sum(w.*R(1,:).^2);
numer=sum(w.*R(1,:).*B(1,:));
assert(denom>0 && all(isfinite([denom,numer])));
cWindow=-numer/denom;
samples=[1.4,1.6,2,2.4,2.8];
sampleRx=interp1(x,Rx(1,:),samples,'linear');
sampleBx=interp1(x,Bx(1,:),samples,'linear');
sampleLogRateOld=(sampleBx+old*sampleRx)./sampleRx;
sampleLogRatePoint=(sampleBx+cPoint*sampleRx)./sampleRx;
sampleLogRateWindow=(sampleBx+cWindow*sampleRx)./sampleRx;
[peak,peakIndex]=max(Rx(1,x>0));
positive=find(x>0);peakIndex=positive(peakIndex);
report=struct('kind','signed_native_frozen_outer_wall_gauge_rhs_v1', ...
    'checkpointFile',checkpointFile,'step',state.step, ...
    'tau',state.scale.canonicalTime, ...
    'nodeCount',[numel(state.ops.x),numel(state.ops.y)], ...
    'anchor',[anchor,0],'windowHalfWidth',radius, ...
    'windowSupportNodes',nnz(w), ...
    'pointR',pointR,'pointB',pointB, ...
    'pointCondition',pointR/max(abs(R(1,:))), ...
    'oldCOmega',old,'pointCOmega',cPoint,'windowCOmega',cWindow, ...
    'pointRateResidual',pointB+cPoint*pointR, ...
    'windowRateResidual',numer+cWindow*denom, ...
    'pointVsWindowRateDifference',cPoint-cWindow, ...
    'outerSamplesX',samples,'outerRx',sampleRx, ...
    'outerRxLogRateOld',sampleLogRateOld, ...
    'outerRxLogRatePoint',sampleLogRatePoint, ...
    'outerRxLogRateWindow',sampleLogRateWindow, ...
    'wallPeak',peak,'wallPeakX',x(peakIndex), ...
    'peakLogRateOld',(Bx(1,peakIndex)+old*peak)/peak, ...
    'peakLogRatePoint',(Bx(1,peakIndex)+cPoint*peak)/peak, ...
    'peakLogRateWindow',(Bx(1,peakIndex)+cWindow*peak)/peak, ...
    'nativeRhsReconstructed',true,'pdeAdvanced',false, ...
    'interpretation',['Algebraic counterfactual rate at one accepted ' ...
        'physical state. It does not prove long-time stability of the ' ...
        'new gauge or covariance of a new discrete trajectory.']);
fid=fopen(outputFile,'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
