function report=audit_native_remesh_profile_jump(beforeCheckpoint, ...
        afterCheckpoint,transactionIndex,outputDirectory)
%AUDIT_NATIVE_REMESH_PROFILE_JUMP Split observed shape change at a native remesh.
% Replays only to the signed request, applies its original selected mesh,
% and compares measured inner shapes at exactly the same canonical time.
% No alternative PDE history or native checkpoint is written.
assert(~isfolder(outputDirectory) && maxNumCompThreads==10);
before=ipm.output.readCheckpoint(beforeCheckpoint);
after=ipm.output.readCheckpoint(afterCheckpoint);
b=before.payload.state;a=after.payload.state;
assert(all(ipm.output.trustedMask(before.payload.log.history,b.config)) && ...
    all(ipm.output.trustedMask(after.payload.log.history,a.config)) && ...
    strcmp(b.runMetadata.caseId,a.runMetadata.caseId));
ledger=a.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>=transactionIndex && ...
    b.step<ledger(transactionIndex).sourceStep && ...
    a.step>ledger(transactionIndex).sourceStep);
signed=ledger(transactionIndex);
startShape=shape_from_saved(b);
endShape=shape_from_saved(a);
[state,~,~]=ipm.output.restoreCheckpoint(before,struct());
clear before after b a
plan=[];
while state.step<signed.sourceStep
    [state,stopReason,plan]=ipm.evolve.advance(state);
    assert(isempty(stopReason),'ipm:ProfileJumpReplayStopped');
    if ~isempty(plan),break;end
    if mod(state.step,50)==0
        fprintf('PROFILE_JUMP_REPLAY step=%d target=%d tau=%.9f\n', ...
            state.step,signed.sourceStep,state.scale.canonicalTime);
    end
end
assert(~isempty(plan) && plan.requested && ...
    state.step==signed.sourceStep && ...
    state.scale.canonicalTime==signed.sourceCanonicalTime && ...
    isequaln(plan.coreCells,signed.controllerDecision.coreCells) && ...
    strcmp(plan.reason,signed.controllerDecision.reason), ...
    'ipm:ProfileJumpSourceMismatch');
preShape=shape_from_live(state);
state.ops=rmfield(state.ops,'poisson');
[state,success,attempts]=ipm.evolve.applyAutonomousMesh(state,plan);
assert(success && numel(attempts)>=signed.candidateIndex && ...
    attempts(signed.candidateIndex).passed && ...
    isequaln(attempts(signed.candidateIndex).audit,signed), ...
    'ipm:ProfileJumpSignedTransactionMismatch');
postShape=shape_from_live(state);
assert(preShape.tau==postShape.tau && preShape.physicalTime==postShape.physicalTime);
report=struct('kind','signed_native_remesh_profile_jump_v1', ...
    'beforeCheckpoint',beforeCheckpoint,'afterCheckpoint',afterCheckpoint, ...
    'transactionIndex',transactionIndex,'sourceStep',signed.sourceStep, ...
    'sourceTau',signed.sourceCanonicalTime, ...
    'sourceDecisionEqualsSigned',true,'nativeAuditEqualsSigned',true, ...
    'sameTimeTransfer',true,'checkpointWritten',false, ...
    'start',compact(startShape),'preTransfer',compact(preShape), ...
    'postTransfer',compact(postShape),'end',compact(endShape), ...
    'startToPre',shape_difference(startShape,preShape), ...
    'preToPost',shape_difference(preShape,postShape), ...
    'postToEnd',shape_difference(postShape,endShape), ...
    'startToEnd',shape_difference(startShape,endShape), ...
    'interpretation','Same-time transfer jump is a native mesh interpolation effect, not a physical-time derivative or a spatial-convergence bound.');
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('PROFILE_JUMP tx=%d pre/post wall L2=%.6g vertical L2=%.6g full wall L2=%.6g\n', ...
    transactionIndex,report.preToPost.wall.relativeL2, ...
    report.preToPost.vertical.relativeL2,report.startToEnd.wall.relativeL2);
end

function shape=shape_from_saved(s)
Dx=ipm.mesh.fdMatrix(s.x,1,7);Dy=ipm.mesh.fdMatrix(s.y,1,7);
shape=measured_shape(s.rho,s.x,s.y,Dx,Dy,s.scale,s.config);
end

function shape=shape_from_live(s)
ops=s.ops;
shape=measured_shape(s.rho,ops.x,ops.y,ops.Dx,ops.Dy,s.scale,s.config);
end

function shape=measured_shape(rho,x,y,Dx,Dy,scale,config)
W=rho*Dx';
g=continuous_inner_geometry(W,x,y,Dx,Dy, ...
    config.scaling.transportAnchorX*[.8,1.15]);
xi=linspace(-2,2,401);eta=linspace(0,3,401);
wall=ipm_accellab_tensor_hermite(W,x,y,Dx,Dy, ...
    g.peakX+g.wallWidth*xi,zeros(size(xi)));
vertical=ipm_accellab_tensor_hermite(W,x,y,Dx,Dy, ...
    g.peakX+zeros(size(eta)),g.verticalWidth*eta);
Cx=exp(scale.logC_l);Cw=exp(scale.logC_omega);
shape=struct('tau',scale.canonicalTime,'physicalTime',scale.physicalTime, ...
    'peak',g.peak*Cx/Cw,'peakX',g.peakX/Cx, ...
    'physicalWidths',[g.wallWidth,g.verticalWidth]/Cx, ...
    'wall',wall.value(:)'/g.peak,'vertical',vertical.value(:)'/g.peak);
assert(all(isfinite(shape.wall)) && all(isfinite(shape.vertical)));
end

function out=compact(shape)
out=rmfield(shape,{'wall','vertical'});
end

function result=shape_difference(before,after)
wall=norm_difference(before.wall,after.wall);
vertical=norm_difference(before.vertical,after.vertical);
result=struct('deltaTau',after.tau-before.tau, ...
    'deltaPhysicalTime',after.physicalTime-before.physicalTime, ...
    'wall',wall,'vertical',vertical, ...
    'relativePeakChange',after.peak/before.peak-1, ...
    'relativeWidthChange',after.physicalWidths./before.physicalWidths-1, ...
    'peakShiftOverAfterWallWidth', ...
        (after.peakX-before.peakX)/after.physicalWidths(1));
end

function out=norm_difference(before,after)
out=struct('relativeL2',norm(after-before)/norm(after), ...
    'relativeSampledInf',max(abs(after-before))/max(abs(after)));
end
