function report=audit_original_t0_shape_train(trainingProfilesFile,outputDirectory)
%AUDIT_ORIGINAL_T0_SHAPE_TRAIN Training-only acceleration preflight.
% Uses signed, actual finite-time normalized profiles previously rendered
% from original-t0 checkpoints. No future checkpoint, PDE or LU is read.
assert(~isfolder(outputDirectory));
d=load(trainingProfilesFile,'report','curves');
parent=d.report;frames=d.curves;n=numel(frames);
assert(n==8 && parent.nativeSignatureValidated && ...
    all(~[parent.records.freshCase]) && ...
    isequal([parent.records.step], ...
        [12593,12897,13197,13488,13770,14098,14421,14751]));
t=[parent.records.tau]';
assert(all(diff(t)>0) && max(abs(diff(t)-.1))<.0002);
lambdas=[0,.1,1,10,100];
directions={'wall','vertical'};rows=struct([]);
for q=1:2
    A=zeros(n,401);
    for k=1:n,A(k,:)=frames{k}.(['normalized',upper(directions{q}(1)),directions{q}(2:end)]);end
    D=diff(A,1,1)';
    incrementNorms=vecnorm(D);
    relativeIncrementNorms=incrementNorms./vecnorm(A(2:end,:),2,2)';
    correlations=zeros(1,n-2);
    for k=1:n-2
        correlations(k)=dot(D(:,k),D(:,k+1))/ ...
            (norm(D(:,k))*norm(D(:,k+1)));
    end
    [U,S,V]=svd(D(:,1:6),'econ');sv=diag(S);
    residual=zeros(1,2);
    for rank=1:2
        B=D(:,2:7)*V(:,1:rank)/S(1:rank,1:rank)*U(:,1:rank)';
        residual(rank)=norm(D(:,2:7)-B*D(:,1:6),'fro')/ ...
            norm(D(:,2:7),'fro');
    end
    errors=zeros(3,1+numel(lambdas));
    for m=5:7
        u=(t(1:m)-t(m))/.1;uf=(t(m+1)-t(m))/.1;
        X=[ones(m,1),u];
        linear=[1,uf]*((X'*X)\(X'*A(1:m,:)));
        errors(m-4,1)=norm(linear-A(m+1,:))/norm(A(m+1,:));
        Xq=[X,u.^2];
        for j=1:numel(lambdas)
            beta=(Xq'*Xq+diag([0,0,lambdas(j)]))\(Xq'*A(1:m,:));
            quadratic=[1,uf,uf^2]*beta;
            errors(m-4,j+1)=norm(quadratic-A(m+1,:))/norm(A(m+1,:));
        end
    end
    row=struct('direction',directions{q}, ...
        'sampledIncrementL2Norms',incrementNorms, ...
        'sampledRelativeIncrementL2',relativeIncrementNorms, ...
        'consecutiveIncrementCorrelations',correlations, ...
        'firstSingularEnergyFraction',sv(1)^2/sum(sv.^2), ...
        'firstTwoSingularEnergyFraction',sum(sv(1:2).^2)/sum(sv.^2), ...
        'incrementDmdFitResidualRankOneTwo',residual, ...
        'quadraticCurvaturePenalties',lambdas, ...
        'rollingOneStepRelativeL2',errors, ...
        'meanLinearError',mean(errors(:,1)), ...
        'meanQuadraticErrors',mean(errors(:,2:end),1), ...
        'allTestedQuadraticsWorseThanLinear', ...
            all(mean(errors(:,2:end),1)>mean(errors(:,1))));
    if isempty(rows),rows=row;else,rows(end+1)=row;end %#ok<AGROW>
end
report=struct('kind','original_t0_shape_training_preflight_v1', ...
    'trainingProfilesFile',trainingProfilesFile, ...
    'trainingSteps',[parent.records.step], ...
    'trainingTimes',t', ...
    'signedNativeProfiles',true,'futureFramesRead',false, ...
    'sampledPointsPerDirection',401, ...
    'rows',{rows}, ...
    'rankOneAccelerationQualified',false, ...
    'testedQuadraticAccelerationQualified',false, ...
    'interpretation','Training-only screen on sampled normalized finite-time shapes; no limit, spatial error or PDE acceleration claim.');
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
for row=rows
    fprintf('SHAPE_TRAIN %s DMD1/2 residual=%.5f/%.5f linear=%.6g bestQuad=%.6g\n', ...
        row.direction,row.incrementDmdFitResidualRankOneTwo, ...
        row.meanLinearError,min(row.meanQuadraticErrors));
end
end
