function report = audit_outer_gauge_frozen(checkpointFiles,outputFile,center)
%AUDIT_OUTER_GAUGE_FROZEN Inspect candidate amplitude anchors without PDE work.
% This reads signed original-t0 states and their maintained seven-point
% derivatives. No Poisson factor, gauge change, or time step is performed.
assert(iscell(checkpointFiles) && numel(checkpointFiles)>=3);
assert(maxNumCompThreads==10);
if nargin<3,center=[2,1];end
assert(isequal(size(center),[1,2]) && all(isfinite(center)) && ...
    center(1)>0 && center(2)>=0);
records=struct([]);
for k=1:numel(checkpointFiles)
    cp=ipm.output.readCheckpoint(checkpointFiles{k});
    s=cp.payload.state;
    assert(cp.trustedRecord && ...
        all(ipm.output.trustedMask(cp.payload.log.history,s.config)) && ...
        strcmp(s.config.scaling.dynamicScaleGeometry,'isotropic') && ...
        strcmp(s.config.scaling.cOmegaGauge,'wall_omega_quadratic_peak'));
    x=s.x(:)';y=s.y(:);R=s.rho;
    Dx=ipm.mesh.fdMatrix(x,1,7);
    Dy=ipm.mesh.fdMatrix(y,1,7);
    Rx=R*Dx';Ry=Dy*R;
    radius=[0.5,0.5];
    bx=bump((x-center(1))/radius(1));
    by=bump((y-center(2))/radius(2));
    wx=trap_weights(x);wy=trap_weights(y);
    weights=(wy.*by)*(wx(:)'.*bx);
    weights=weights/sum(weights,'all');
    pointR=interp2(x,y,R,center(1),center(2),'linear');
    pointRx=interp2(x,y,Rx,center(1),center(2),'linear');
    patchR=sqrt(sum(weights.*R.^2,'all'));
    patchGradient=sqrt(sum(weights.*(Rx.^2+Ry.^2),'all'));
    wallWeights=wx(:)'.*bx;
    wallWeights=wallWeights/sum(wallWeights);
    wallR=sqrt(sum(wallWeights.*R(1,:).^2));
    wallRx=sqrt(sum(wallWeights.*Rx(1,:).^2));
    wallSamplesX=[1.4,1.6,2,2.4,2.8];
    wallSamplesR=interp1(x,R(1,:),wallSamplesX,'linear');
    wallSamplesRx=interp1(x,Rx(1,:),wallSamplesX,'linear');
    peak=max(Rx(1,x>0));
    row=struct('checkpointFile',checkpointFiles{k}, ...
        'step',s.step,'tau',s.scale.canonicalTime, ...
        'nodeCount',[numel(x),numel(y)], ...
        'point',[center(1),center(2)], ...
        'pointR',pointR,'pointRx',pointRx, ...
        'pointRCondition',abs(pointR)/max(abs(R),[],'all'), ...
        'patchCenter',center,'patchHalfWidth',radius, ...
        'supportNodes',[nnz(bx),nnz(by)], ...
        'patchRrms',patchR,'patchGradientRms',patchGradient, ...
        'wallWindowRrms',wallR,'wallWindowRxRms',wallRx, ...
        'wallSamplesX',wallSamplesX, ...
        'wallSamplesR',wallSamplesR,'wallSamplesRx',wallSamplesRx, ...
        'wallSamplesROverPointR',wallSamplesR/pointR, ...
        'wallSamplesRxOverPointR',wallSamplesRx/pointR, ...
        'wallRxPeak',peak, ...
        'oldCOmega',cp.payload.log.history.common.c_omega(end));
    if isempty(records),records=row;else,records(end+1)=row;end %#ok<AGROW>
end
assert(all(diff([records.tau])>0));
report=struct('kind','signed_original_t0_outer_gauge_frozen_v1', ...
    'point',center,'records',records,'nativeSignatureValidated',true, ...
    'pdeAdvanced',false,'poissonFactored',false, ...
    'interpretation',['Outer point and smooth-window amplitudes from the ' ...
        'unchanged peak-pinned orbit. Temporal drift is a screening ' ...
        'diagnostic, not a validated counterfactual gauge trajectory.']);
fid=fopen(outputFile,'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end

function values=bump(z)
values=zeros(size(z));inside=abs(z)<1;
values(inside)=cos(pi*z(inside)/2).^2;
end

function w=trap_weights(nodes)
nodes=nodes(:);d=diff(nodes);
w=[d(1);d(1:end-1)+d(2:end);d(end)]/2;
end
