function report=audit_native_remesh_rhs_c_decomposition(beforeCheckpoint, ...
        afterCheckpoint,transactionIndex,outputDirectory)
%AUDIT_NATIVE_REMESH_RHS_C_DECOMPOSITION Separate RHS and C1 observations.
% Replays to one signed native request. The pre/post accepted-state RHS
% caches are sampled on the same pre-transfer inner coordinates. No new
% Poisson solve, alternative gauge or accepted checkpoint is produced.
assert(~isfolder(outputDirectory) && maxNumCompThreads==10);
before=ipm.output.readCheckpoint(beforeCheckpoint);
after=ipm.output.readCheckpoint(afterCheckpoint);
b=before.payload.state;a=after.payload.state;
assert(all(ipm.output.trustedMask(before.payload.log.history,b.config)) && ...
    all(ipm.output.trustedMask(after.payload.log.history,a.config)) && ...
    strcmp(b.runMetadata.caseId,a.runMetadata.caseId));
ledger=a.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>=transactionIndex && ...
    b.step<ledger(transactionIndex).sourceStep);
signed=ledger(transactionIndex);
[state,~,~]=ipm.output.restoreCheckpoint(before,struct());
clear before after b a
plan=[];
while state.step<signed.sourceStep
    [state,stopReason,plan]=ipm.evolve.advance(state);
    assert(isempty(stopReason),'ipm:RhsCDecompositionReplayStopped');
    if ~isempty(plan),break;end
end
assert(~isempty(plan) && plan.requested && ...
    state.step==signed.sourceStep && ...
    state.scale.canonicalTime==signed.sourceCanonicalTime && ...
    isequaln(plan.coreCells,signed.controllerDecision.coreCells) && ...
    strcmp(plan.reason,signed.controllerDecision.reason), ...
    'ipm:RhsCDecompositionSourceMismatch');
pre=observe(state,[]);
state.ops=rmfield(state.ops,'poisson');
[state,success,attempts]=ipm.evolve.applyAutonomousMesh(state,plan);
assert(success && attempts(signed.candidateIndex).passed && ...
    isequaln(attempts(signed.candidateIndex).audit,signed), ...
    'ipm:RhsCDecompositionSignedTransactionMismatch');
post=observe(state,pre.geometry);
assert(pre.tau==post.tau && pre.physicalTime==post.physicalTime);
metrics=struct();
fields={'rho','omega','rhoRate','omegaRate'};
for k=1:numel(fields)
    name=fields{k};
    metrics.(name)=struct( ...
        'wall',compare_one(pre.samples.(name).wall,post.samples.(name).wall), ...
        'vertical',compare_one(pre.samples.(name).vertical,post.samples.(name).vertical));
end
report=struct('kind','signed_native_remesh_rhs_c_decomposition_v1', ...
    'beforeCheckpoint',beforeCheckpoint,'afterCheckpoint',afterCheckpoint, ...
    'transactionIndex',transactionIndex,'sourceStep',signed.sourceStep, ...
    'sourceTau',signed.sourceCanonicalTime, ...
    'sourceDecisionEqualsSigned',true,'nativeAuditEqualsSigned',true, ...
    'originalAcceptedRhsCaches',true,'additionalPoissonSolve',false, ...
    'alternativeGaugeApplied',false,'checkpointWritten',false, ...
    'samePreTransferInnerCoordinates',true, ...
    'pre',compact(pre),'post',compact(post), ...
    'fieldComparison',metrics, ...
    'interpretation','Frozen discrete RHS/paired Omega-rate and read-only C1 peak/width rates on each native grid. Relative differences do not certify which grid approaches the continuum limit.');
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('RHS_C tx=%d rhoRateWallRelative=%.6g omegaRateWallRelative=%.6g oldCJump=%.6g C1Valid=%d/%d\n', ...
    transactionIndex,metrics.rhoRate.wall.relativeDifferenceToPre, ...
    metrics.omegaRate.wall.relativeDifferenceToPre, ...
    post.nativeCOmega-pre.nativeCOmega,pre.c1.valid,post.c1.valid);
end

function out=observe(s,common)
ops=s.ops;cache=s.rhsCache;
assert(isequaln(cache.rho,s.rho) && isequaln(cache.x,ops.x) && ...
    isequaln(cache.y,ops.y) && isequaln(cache.scale,s.scale) && ...
    cache.remeshCount==ops.remeshCount);
omega=s.rho*ops.Dx';rhoRate=cache.rhoRate;
omegaRate=rhoRate*ops.Dx';
window=s.config.scaling.transportAnchorX*[.8,1.15];
g=continuous_inner_geometry(omega,ops.x,ops.y,ops.Dx,ops.Dy,window);
if isempty(common),common=g;end
fields=struct('rho',s.rho,'omega',omega, ...
    'rhoRate',rhoRate,'omegaRate',omegaRate);
names=fieldnames(fields);samples=struct();
for k=1:numel(names)
    name=names{k};samples.(name)=sample_pair(fields.(name),ops,common);
end
try
    c1=ipm_accellab_continuous_inner_rates(omega,omegaRate, ...
        ops.x,ops.y,ops.Dx,ops.Dy,window);
    summary=struct('valid',c1.valid,'invalidReasons',{c1.invalidReasons}, ...
        'peak',c1.peak.value,'peakX',c1.peak.x, ...
        'peakPrime',c1.peak.PPrime, ...
        'relativePeakRate',c1.peak.PPrime/c1.peak.value, ...
        'hypotheticalC1COmega',s.flow.c_omega-c1.peak.PPrime/c1.peak.value, ...
        'phaseRate',NaN,'logWidthRates',[NaN,NaN]);
    if c1.valid
        summary.phaseRate=c1.translationRate;
        summary.logWidthRates=[c1.logScaleXRate,c1.logScaleYRate];
    end
catch exception
    summary=struct('valid',false,'invalidReasons',{{exception.identifier}}, ...
        'peak',NaN,'peakX',NaN,'peakPrime',NaN, ...
        'relativePeakRate',NaN,'hypotheticalC1COmega',NaN, ...
        'phaseRate',NaN,'logWidthRates',[NaN,NaN]);
end
out=struct('tau',s.scale.canonicalTime,'physicalTime',s.scale.physicalTime, ...
    'nodeCount',[ops.nx,ops.ny], ...
    'coreCells',[s.flow.coreGridPoints,s.flow.verticalCoreGridPoints], ...
    'nativeCL',s.flow.c_l,'nativeCOmega',s.flow.c_omega, ...
    'geometry',g,'c1',summary,'samples',samples);
end

function samples=sample_pair(field,ops,g)
xi=linspace(-2,2,401);eta=linspace(0,3,401);
wall=ipm_accellab_tensor_hermite(field,ops.x,ops.y,ops.Dx,ops.Dy, ...
    g.peakX+g.wallWidth*xi,zeros(size(xi)));
vertical=ipm_accellab_tensor_hermite(field,ops.x,ops.y,ops.Dx,ops.Dy, ...
    g.peakX+zeros(size(eta)),g.verticalWidth*eta);
samples=struct('wall',wall.value(:)','vertical',vertical.value(:)');
assert(all(isfinite(samples.wall)) && all(isfinite(samples.vertical)));
end

function summary=compact(data)
summary=rmfield(data,{'samples','geometry'});
summary.geometry=struct('peakX',data.geometry.peakX, ...
    'peak',data.geometry.peak,'wallWidth',data.geometry.wallWidth, ...
    'verticalWidth',data.geometry.verticalWidth);
end

function out=compare_one(a,b)
na=norm(a);nb=norm(b);
out=struct('preNorm',na,'postNorm',nb, ...
    'differenceNorm',norm(b-a), ...
    'relativeDifferenceToPre',norm(b-a)/max(na,realmin), ...
    'cosine',dot(a,b)/max(na*nb,realmin));
end
