function report=audit_native_remesh_shape_tangent(beforeCheckpoint, ...
        afterCheckpoint,transactionIndex,outputDirectory)
%AUDIT_NATIVE_REMESH_SHAPE_TANGENT Compare original RHS shape tangents.
% The accepted-state RHS caches on both sides of the native transaction
% avoid extra Poisson solves. This is a frozen finite-grid diagnostic.
assert(~isfolder(outputDirectory) && maxNumCompThreads==10);
before=ipm.output.readCheckpoint(beforeCheckpoint);
after=ipm.output.readCheckpoint(afterCheckpoint);
saved=before.payload.state;later=after.payload.state;
assert(all(ipm.output.trustedMask(before.payload.log.history,saved.config)) && ...
    all(ipm.output.trustedMask(after.payload.log.history,later.config)) && ...
    strcmp(saved.runMetadata.caseId,later.runMetadata.caseId));
ledger=later.runMetadata.autonomousMesh.transactions;
assert(numel(ledger)>=transactionIndex && ...
    saved.step<ledger(transactionIndex).sourceStep);
signed=ledger(transactionIndex);
[state,~,~]=ipm.output.restoreCheckpoint(before,struct());
clear before after saved later
plan=[];
while state.step<signed.sourceStep
    [state,stopReason,plan]=ipm.evolve.advance(state);
    assert(isempty(stopReason),'ipm:ShapeTangentReplayStopped');
    if ~isempty(plan),break;end
end
assert(~isempty(plan) && plan.requested && ...
    state.step==signed.sourceStep && ...
    state.scale.canonicalTime==signed.sourceCanonicalTime && ...
    isequaln(plan.coreCells,signed.controllerDecision.coreCells) && ...
    strcmp(plan.reason,signed.controllerDecision.reason), ...
    'ipm:ShapeTangentSourceMismatch');
pre=shape_and_tangent(state);
preFlow=flow_summary(state.flow);
state.ops=rmfield(state.ops,'poisson');
[state,success,attempts]=ipm.evolve.applyAutonomousMesh(state,plan);
assert(success && attempts(signed.candidateIndex).passed && ...
    isequaln(attempts(signed.candidateIndex).audit,signed), ...
    'ipm:ShapeTangentSignedTransactionMismatch');
post=shape_and_tangent(state);
postFlow=flow_summary(state.flow);
assert(pre.tau==post.tau && pre.physicalTime==post.physicalTime);
report=struct('kind','signed_native_remesh_shape_tangent_v1', ...
    'beforeCheckpoint',beforeCheckpoint,'afterCheckpoint',afterCheckpoint, ...
    'transactionIndex',transactionIndex,'sourceStep',signed.sourceStep, ...
    'sourceTau',signed.sourceCanonicalTime, ...
    'sourceDecisionEqualsSigned',true,'nativeAuditEqualsSigned',true, ...
    'originalAcceptedRhsCaches',true,'additionalPoissonSolve',false, ...
    'checkpointWritten',false, ...
    'epsilons',[1e-5,5e-6], ...
    'preFlow',preFlow,'postFlow',postFlow, ...
    'sameTimeShapeJump',compare_traces(pre.shape,post.shape), ...
    'shapeTangentChange',compare_traces(pre.tangent,post.tangent), ...
    'preFiniteDifferenceRefinement',pre.refinement, ...
    'postFiniteDifferenceRefinement',post.refinement, ...
    'interpretation','Canonical normalized-shape tangent of the discrete original RHS, measured at two transferred representations of the same time; not a continuum error bound.');
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('SHAPE_TANGENT tx=%d wall tangent cosine=%.6f relativeChange=%.6g shapeJump=%.6g\n', ...
    transactionIndex,report.shapeTangentChange.wall.cosine, ...
    report.shapeTangentChange.wall.relativeDifferenceToPre, ...
    report.sameTimeShapeJump.wall.relativeDifferenceToPre);
end

function out=shape_and_tangent(s)
cache=s.rhsCache;
assert(isequaln(cache.rho,s.rho) && isequaln(cache.x,s.ops.x) && ...
    isequaln(cache.y,s.ops.y) && isequaln(cache.scale,s.scale) && ...
    cache.remeshCount==s.ops.remeshCount);
out.tau=s.scale.canonicalTime;
out.physicalTime=s.scale.physicalTime;
out.shape=sample(s.rho,s.ops,s.config);
epsilons=[1e-5,5e-6];tangents=cell(1,2);
for j=1:2
    trial=sample(s.rho+epsilons(j)*cache.rhoRate,s.ops,s.config);
    tangents{j}=struct('wall',(trial.wall-out.shape.wall)/epsilons(j), ...
        'vertical',(trial.vertical-out.shape.vertical)/epsilons(j));
end
out.tangent=tangents{2};
out.refinement=compare_traces(tangents{1},tangents{2});
end

function out=sample(rho,ops,config)
W=rho*ops.Dx';
g=continuous_inner_geometry(W,ops.x,ops.y,ops.Dx,ops.Dy, ...
    config.scaling.transportAnchorX*[.8,1.15]);
xi=linspace(-2,2,401);eta=linspace(0,3,401);
w=ipm_accellab_tensor_hermite(W,ops.x,ops.y,ops.Dx,ops.Dy, ...
    g.peakX+g.wallWidth*xi,zeros(size(xi)));
v=ipm_accellab_tensor_hermite(W,ops.x,ops.y,ops.Dx,ops.Dy, ...
    g.peakX+zeros(size(eta)),g.verticalWidth*eta);
out=struct('wall',w.value(:)'/g.peak, ...
    'vertical',v.value(:)'/g.peak);
assert(all(isfinite(out.wall)) && all(isfinite(out.vertical)));
end

function out=compare_traces(a,b)
out=struct('wall',compare_one(a.wall,b.wall), ...
    'vertical',compare_one(a.vertical,b.vertical));
end

function out=compare_one(a,b)
na=norm(a);nb=norm(b);
out=struct('preNorm',na,'postNorm',nb, ...
    'differenceNorm',norm(b-a), ...
    'relativeDifferenceToPre',norm(b-a)/max(na,realmin), ...
    'cosine',dot(a,b)/max(na*nb,realmin));
end

function out=flow_summary(f)
out=struct('cL',f.c_l,'cOmega',f.c_omega, ...
    'safetyFactor',f.safetyFactor, ...
    'coreCells',[f.coreGridPoints,f.verticalCoreGridPoints]);
end
