function report = ipm_accellab_exact_inner_rates(omega,forcing,x,y,peakIndex,user)
%IPM_ACCELLAB_EXACT_INNER_RATES Differentiate the actual discrete coordinates.
%   forcing is the unchanged F_X, not a fitted or normalized forcing. The
%   amplitude, peak, horizontal crossings, and vertical trace use the
%   registered quadratic/linear functionals on their current fixed templates.
if nargin < 6, user = struct(); end
opts = struct('level',0.9,'minimumRelativeSegmentDrop',1e-10, ...
    'minimumTemplateMargin',1e-10,'previousSignature',struct());
names = fieldnames(user);
assert(all(ismember(names,fieldnames(opts))),'ipm:InnerRateOptions','Unknown exact-inner-rate option.');
for index = 1:numel(names), opts.(names{index}) = user.(names{index}); end
assert(isstruct(opts.previousSignature) && isscalar(opts.previousSignature), ...
    'ipm:InnerRateSignature','previousSignature must be a scalar structure.');
validateattributes(opts.level,{'numeric'},{'scalar','>',0,'<',1});
validateattributes(opts.minimumRelativeSegmentDrop,{'numeric'},{'scalar','>',0,'<',1});
validateattributes(opts.minimumTemplateMargin,{'numeric'},{'scalar','>',0,'<',0.5});
validateattributes(x,{'numeric'},{'vector','real','finite','increasing'});
validateattributes(y,{'numeric'},{'vector','real','finite','increasing'});
x = x(:)'; y = y(:);
assert(isequal(size(omega),[numel(y),numel(x)]) && isequal(size(forcing),size(omega)) && ...
    isreal(omega) && isreal(forcing) && all(isfinite(omega(:))) && ...
    all(isfinite(forcing(:))) && y(1) == 0, ...
    'ipm:InnerRateFields','Finite paired fields on a half-plane grid with wall Y=0 are required.');
peak = ipm.evolve.quadraticPeakFunctional(omega(1,:),x,peakIndex);
assert(peak.activeNodeMargin > opts.minimumTemplateMargin, ...
    'ipm:InnerCoordinateSwitchBoundary','The active peak is at or too near a stencil-selection tie.');
motion = ipm_accellab_quadratic_motion(omega(1,:),forcing(1,:),x,peakIndex);
peakPrime = sum(peak.weights.*forcing(1,peak.indices));
threshold = opts.level*peak.value;
thresholdPrime = opts.level*peakPrime;
wall = omega(1,:);
assert(wall(peakIndex) > threshold,'ipm:InnerRatePeakSupport', ...
    'The active peak node does not lie strictly inside the selected level set.');
leftIndex = find(wall(1:peakIndex) < threshold,1,'last');
rightOffset = find(wall(peakIndex+1:end) < threshold,1,'first');
assert(~isempty(leftIndex) && ~isempty(rightOffset), ...
    'ipm:InnerRateBracket','Both connected horizontal level crossings must be bracketed.');
rightIndex = peakIndex+rightOffset;
left = crossing(x,wall,forcing(1,:),[leftIndex,leftIndex+1], ...
    threshold,thresholdPrime,peak.value,1,opts);
right = crossing(x,wall,forcing(1,:),[rightIndex-1,rightIndex], ...
    threshold,thresholdPrime,peak.value,-1,opts);
width = right.coordinate-left.coordinate;
widthPrime = right.coordinatePrime-left.coordinatePrime;
assert(width > 0,'ipm:InnerRateWidth','The horizontal width must be positive.');
assert(left.coordinate < peak.x && peak.x < right.coordinate, ...
    'ipm:InnerRatePeakSupport', ...
    'The piecewise-linear level component does not contain the quadratic peak vertex.');

index = peakIndex;
hLeft = x(index)-x(index-1);
hRight = x(index+1)-x(index);
offset = peak.x-x(index);
derivativeWeights = [(2*offset-hRight)/(hLeft*(hLeft+hRight)), ...
    -(2*offset+hLeft-hRight)/(hLeft*hRight), ...
    (2*offset+hLeft)/(hRight*(hLeft+hRight))];
verticalValues = omega(:,peak.indices)*peak.weights(:);
verticalFixedForcing = forcing(:,peak.indices)*peak.weights(:);
verticalXDerivative = omega(:,peak.indices)*derivativeWeights(:);
verticalMovingForcing = verticalFixedForcing+motion.translationRate*verticalXDerivative;
verticalOffset = find(verticalValues(2:end) < threshold,1,'first');
assert(~isempty(verticalOffset),'ipm:InnerRateBracket', ...
    'The first downward vertical level crossing must be bracketed.');
vertical = crossing(y,verticalValues,verticalMovingForcing, ...
    [verticalOffset,verticalOffset+1],threshold,thresholdPrime,peak.value,-1,opts);
assert(vertical.coordinate > 0,'ipm:InnerRateWidth','The vertical crossing must lie above the wall.');
signature = struct('peakStencil',peak.indices,'leftBracket',left.indices, ...
    'rightBracket',right.indices,'verticalBracket',vertical.indices, ...
    'peakCoordinates',x(peak.indices),'leftCoordinates',left.bracketCoordinates, ...
    'rightCoordinates',right.bracketCoordinates,'verticalCoordinates',vertical.bracketCoordinates, ...
    'gridSize',[numel(y),numel(x)]);
assert(all(isfinite([peakPrime,motion.translationRate,width,widthPrime, ...
    vertical.coordinate,vertical.coordinatePrime])), ...
    'ipm:InnerRateNonfinite','The exact coordinate derivative is nonfinite.');
changed = {};
hasPrevious = ~isempty(fieldnames(opts.previousSignature));
templateStatus = 'not_compared';
if hasPrevious
    names = fieldnames(signature);
    assert(all(isfield(opts.previousSignature,names)),'ipm:InnerRateSignature', ...
        'The previous template signature is incomplete.');
    for k = 1:numel(names)
        if ~isequal(signature.(names{k}),opts.previousSignature.(names{k}))
            changed{end+1} = names{k}; %#ok<AGROW>
        end
    end
    if isempty(changed), templateStatus = 'unchanged'; else, templateStatus = 'switched'; end
end
report = struct('kind','exact_instantaneous_discrete_inner_coordinates', ...
    'valid',true,'level',opts.level,'peak',peak,'peakPrime',peakPrime, ...
    'peakRelativeRate',peakPrime/peak.value,'translationRate',motion.translationRate, ...
    'strictQuadraticMotion',motion,'horizontalLeft',left,'horizontalRight',right, ...
    'wallCoreWidth',width,'wallCoreWidthPrime',widthPrime, ...
    'logScaleXRate',widthPrime/width,'verticalCrossing',vertical, ...
    'verticalCoreWidth',vertical.coordinate,'verticalCoreWidthPrime',vertical.coordinatePrime, ...
    'logScaleYRate',vertical.coordinatePrime/vertical.coordinate, ...
    'verticalQuadraticWeights',peak.weights,'verticalQuadraticDerivativeWeights',derivativeWeights, ...
    'verticalWallValueMinusPeak',verticalValues(1)-peak.value, ...
    'verticalWallMovingForcingMinusPeakPrime',verticalMovingForcing(1)-peakPrime, ...
    'verticalPreCrossingIncreasingSegments',nnz(diff(verticalValues(1:verticalOffset+1)) > 0), ...
    'signature',signature,'comparedPreviousSignature',hasPrevious, ...
    'templateStatus',templateStatus,'templateChanged',~isempty(changed), ...
    'changedTemplateFields',{changed}, ...
    'options',rmfield(opts,'previousSignature'),'isEvolutionGauge',false, ...
    'contract','Instantaneous derivatives are exact on the recorded active templates; switching is explicit and no feedback is applied.');
end

function result = crossing(axis,values,forcing,indices,threshold,thresholdPrime,peakScale,orientation,opts)
coordinate = axis(indices);
sample = values(indices);
sampleForcing = forcing(indices);
spacing = coordinate(2)-coordinate(1);
difference = sample(2)-sample(1);
slope = difference/spacing;
condition = abs(difference)/max([peakScale,abs(sample(:)')]);
assert(orientation*slope > 0 && condition > opts.minimumRelativeSegmentDrop, ...
    'ipm:InnerRateCrossingCondition','A level crossing has a flat, reversed, or ill-conditioned segment.');
fraction = (threshold-sample(1))/difference;
margin = min(fraction,1-fraction);
assert(margin > opts.minimumTemplateMargin, ...
    'ipm:InnerCoordinateSwitchBoundary','A level crossing is at or too near a node-template boundary.');
point = coordinate(1)+fraction*spacing;
interpolatedForcing = (1-fraction)*sampleForcing(1)+fraction*sampleForcing(2);
rate = (thresholdPrime-interpolatedForcing)/slope;
result = struct('indices',indices,'bracketCoordinates',coordinate(:)', ...
    'bracketValues',sample(:)','bracketForcing',sampleForcing(:)', ...
    'coordinate',point,'coordinatePrime',rate,'slope',slope, ...
    'relativeSegmentDrop',condition,'fraction',fraction,'templateInteriorMargin',margin, ...
    'interpolatedForcing',interpolatedForcing,'threshold',threshold, ...
    'thresholdPrime',thresholdPrime,'implicitResidual', ...
    interpolatedForcing+slope*rate-thresholdPrime);
end
