function report = ipm_accellab_recycle_shadow(A,B,Xnative,velocityMap)
%IPM_ACCELLAB_RECYCLE_SHADOW Pure-array, tiny Poisson projection screening.
% B includes the freshly assembled boundary contribution in every column.
% Xnative contains native direct-solve INTERIOR values from the same epoch.
% velocityMap maps interior error to the registered velocity observations;
% identical fresh boundary values cancel in this error calculation.
% This helper never solves A, calls the PDE, or accepts a production state.
% All training columns are exact native references: savings are optimistic.

n = size(A,1);
assert(n <= 4096 && n == size(A,2),'ipm:ResearchSize','Tiny only.');
assert(isequal(size(B),size(Xnative)) && size(B,1)==n && size(B,2)>=6);
assert(size(velocityMap,2)==n && size(velocityMap,1)>0);
assert(isreal(A) && isreal(B) && isreal(Xnative) && isreal(velocityMap));
assert(all(isfinite(nonzeros(A))) && all(isfinite(B),'all') && ...
    all(isfinite(Xnative),'all') && all(isfinite(nonzeros(velocityMap))));
rowScale = full(max(abs(A),[],2));
assert(all(rowScale>0));
memory = 4;
report = struct('kind','tiny_exact_reference_recycle_shadow_v1', ...
    'memory',memory,'rankRelativeCutoff',1e-10, ...
    'coefficientNormLimit',32,'maximumGlobalResidual',5e-12, ...
    'maximumComponentwiseBackwardError',5e-14, ...
    'maximumVelocityRelativeInf',1e-10, ...
    'allTrainingReferencesNative',true,'nativeSolveSavingsMeasured',false, ...
    'integrationApproved',false,'entries',[]);
for j=6:size(B,2)
    seed = Xnative(:,j-1);
    V = Xnative(:,j-5:j-2)-seed;
    AV = A*V;
    columnNorm = sqrt(sum((AV./rowScale).^2,1));
    active = columnNorm>0;
    basis = V(:,active)./columnNorm(active);
    images = AV(:,active)./columnNorm(active);
    [U,S,Z] = svd(images./rowScale,'econ');
    singular = diag(S);
    retained = singular>report.rankRelativeCutoff*max(singular,[],'all');
    target = (B(:,j)-A*seed)./rowScale;
    coefficients = Z(:,retained)*((U(:,retained)'*target)./singular(retained));
    trial = seed+basis*coefficients;
    rawCoefficients = zeros(memory,1);
    rawCoefficients(active) = coefficients./columnNorm(active)';
    residual = A*trial-B(:,j);
    referenceResidual = A*Xnative(:,j)-B(:,j);
    denominator = abs(A)*abs(trial)+abs(B(:,j));
    referenceDenominator = abs(A)*abs(Xnative(:,j))+abs(B(:,j));
    velocityError = velocityMap*(trial-Xnative(:,j));
    velocityScale = max(norm(velocityMap*Xnative(:,j),inf),realmin);
    e = struct('column',j,'referenceColumns',j-5:j-1, ...
        'retainedRank',nnz(retained),'singularValues',singular', ...
        'rawCoefficientNorm',norm(rawCoefficients), ...
        'relativeGlobalResidual',norm(residual,inf)/max(norm(B(:,j),inf),eps), ...
        'componentwiseBackwardError',max(abs(residual)./max(denominator,realmin)), ...
        'nativeComponentwiseBackwardError', ...
            max(abs(referenceResidual)./max(referenceDenominator,realmin)), ...
        'velocityRelativeInf',norm(velocityError,inf)/velocityScale, ...
        'interiorRelativeInf',norm(trial-Xnative(:,j),inf)/ ...
            max(norm(Xnative(:,j),inf),realmin),'candidate',trial);
    e.screenPassed = all(isfinite(trial)) && e.retainedRank>0 && ...
        e.rawCoefficientNorm<=report.coefficientNormLimit && ...
        e.relativeGlobalResidual<=report.maximumGlobalResidual && ...
        e.componentwiseBackwardError<=report.maximumComponentwiseBackwardError && ...
        e.velocityRelativeInf<=report.maximumVelocityRelativeInf;
    report.entries = [report.entries;e]; %#ok<AGROW>
end
end
