function report=ipm_accellab_prepare_t0_tail_pair(registrationFile)
%IPM_ACCELLAB_PREPARE_T0_TAIL_PAIR Strict original t0 contexts and full tails.
% Only readCheckpoint, analytic sampling, 1D derivatives and quadrature.
reg=jsondecode(fileread(registrationFile));out=reg.outputDirectory;
assert(maxNumCompThreads==10&&~isfolder(out));mkdir(out);profile clear;profile on;
report=struct('kind','original_t0_fixed_operator_tail_preparation_v1', ...
    'registrationFile',registrationFile,'cases',{{}},'LUCount',0,'PDECount',0, ...
    'executeNative',false,'solverInjectionPerformed',false);
for k=1:numel(reg.cases)
    item=reg.cases(k);fprintf('Preparing %s: strict source and full boundary quadrature.\n',item.label);
    cp=ipm.output.readCheckpoint(item.checkpointFile);s=cp.payload.state;h=cp.payload.log.history;l=cp.payload.log;
    assert(all(ipm.output.trustedMask(h,s.config))&&s.remeshCount==0);
    assert(h.common.acceptedStep(1)==0&&h.common.t(1)==0&&h.common.canonicalTau(1)==0&&h.common.physicalTime(1)==0);
    assert(all(h.mesh.remeshCount==0)&&l.snapshotNormalizedTime(1)==0);
    x=l.snapshotX{1};y=l.snapshotY{1};rho=l.snapshotRho{1};config=s.config;
    assert(isequaln(x,s.x)&&isequaln(y,s.y)&&isequaln(x,s.baseX)&&isequaln(y,s.baseY));
    assert(isequal([numel(x),numel(y)],[config.grid.nx,config.grid.ny])&&numel(x)*numel(y)<=reg.maximumNodesPerCase);
    assert(isequal([x(1),x(end),y(1),y(end)],[-item.H,item.H,0,item.H/2]));
    assert(strcmp(config.transport.spatialDiscretization,'high_order')&&strcmp(config.transport.transportScheme,'weno5_fd')&& ...
        strcmp(config.physics.initialCondition,'degenerate_primitive')&&config.physics.degeneratePower==8&& ...
        strcmp(config.physics.symmetryMode,'double_odd_omega')&&strcmp(config.elliptic.farBoundaryMode,'green'));
    refs=s.rescaling;
    assert(refs.enabled&&strcmp(refs.lengthGauge,'transport_anchor')&&refs.transportAnchorX==1&& ...
        strcmp(refs.cOmegaGauge,'wall_omega_quadratic_peak')&&strcmp(config.scaling.dynamicScaleGeometry,'isotropic'));
    [X,Y]=meshgrid(x,y);view=struct('X',X,'Y',Y,'nx',numel(x),'ny',numel(y),'symmetryMode',config.physics.symmetryMode);
    assert(isequaln(rho,ipm.field.initialDensity(view,config.physics)));
    Dx=ipm.mesh.fdMatrix(x,1,7);Dy=ipm.mesh.fdMatrix(y,1,7);Omega=rho*Dx';
    assert(max(abs(Omega),[],'all')==h.common.physicalRhoXInf(1));
    weights=ipm.mesh.quadrature(y)*ipm.mesh.quadrature(x);
    assert(sum(rho.*weights,'all')==s.mass0&&isequaln([min(rho,[],'all'),max(rho,[],'all')],s.rhoRange0));
    query=[x(1)+zeros(numel(y),1),y;x(end)+zeros(numel(y),1),y; ...
        x',y(end)+zeros(numel(x),1);x',zeros(numel(x),1)];
    timer=tic;
    leading=ipm_accellab_green_full_tail_trace(query,item.H,method='radial_analytic',order=reg.leadingOrder);
    remainder=zeros(size(query,1),numel(reg.remainderOrders));
    for j=1:numel(reg.remainderOrders)
        remainder(:,j)=ipm_accellab_green_full_tail_trace(query,item.H,method='target_polar', ...
            order=reg.remainderOrders(j),sourceOnly='initial_remainder');
    end
    exactDecomposed=leading+remainder(:,end);
    independentExact=ipm_accellab_green_full_tail_trace(query,item.H,method='target_polar', ...
        order=reg.independentOrder,sourceOnly='exact_initial');
    seconds=toc(timer);scale=max(item.H,abs(exactDecomposed));nonzero=query(:,1)~=0&query(:,2)~=0;
    qa=item.H*exactDecomposed(nonzero)./(query(nonzero,1).*query(nonzero,2));
    qb=item.H*independentExact(nonzero)./(query(nonzero,1).*query(nonzero,2));
    audit=struct('strictNativeSignatureValidated',true,'sourceStep',s.step,'sourceCanonicalTimeNotObserved',s.scale.canonicalTime, ...
        'observedStep',0,'observedPhysicalTime',0,'initialSnapshotExactlyAnalytic',true, ...
        'initialAxesAndBaseExactlyPreserved',true,'firstHistorySourceMaximumExact',true, ...
        'originalMassAndRangeExact',true,'savedRuntimeReferencesAvailable',true, ...
        'methodScaledDifference',max(abs(exactDecomposed-independentExact)./scale), ...
        'lastRemainderScaledChange',max(abs(remainder(:,end)-remainder(:,end-1))./scale), ...
        'nearAxisQuotientScaledDifference',max(abs(qa-qb)./max(1,abs(qa))), ...
        'remainderMaximum',max(abs(remainder(:,end))),'tailTraceMaximum',max(abs(exactDecomposed)), ...
        'allAxisValuesZero',all(exactDecomposed(~nonzero)==0)&&all(independentExact(~nonzero)==0), ...
        'quadratureSeconds',seconds,'boundaryQueryCount',size(query,1));
    audit.quadraturePassed=audit.methodScaledDifference<=reg.maximumTraceScaledError&& ...
        audit.lastRemainderScaledChange<=reg.maximumTraceScaledError&& ...
        audit.nearAxisQuotientScaledDifference<=reg.maximumNearAxisQuotientScaledError&&audit.allAxisValuesZero;
    context=struct('label',item.label,'sourceCheckpoint',item.checkpointFile,'config',config, ...
        'x',x,'y',y,'rho',rho,'Omega',Omega,'Dx',Dx,'Dy',Dy,'integrationWeights',weights, ...
        'runtimeReferences',refs,'mass0',s.mass0,'rhoRange0',s.rhoRange0, ...
        'initialNativeCL',h.common.c_l(1),'initialNativeCOmega',h.common.c_omega(1), ...
        'initialNativeCR',h.common.c_r(1),'initialPhysicalRhoXInf',h.common.physicalRhoXInf(1), ...
        'initialNativeQuadraticPeak',h.gauge.omegaGaugeQuadraticPeakValue(1), ...
        'query',query,'tailBoundary',pack(exactDecomposed,numel(x),numel(y)), ...
        'leadingBoundary',pack(leading,numel(x),numel(y)), ...
        'exactInitialRemainder',remainder,'independentExactTrace',independentExact, ...
        'audit',audit,'isNativeCheckpoint',false,'mathematicalTime',0,'LUCount',0,'PDECount',0);
    file=fullfile(out,[item.label,'_context.mat']);save(file,'context','-v7.3');
    report.cases{k}=struct('label',item.label,'contextFile',file,'audit',audit, ...
        'nativeExecutionReady',audit.quadraturePassed,'actualLUComparisonPerformed',false);
    fprintf('%s saved: quadrature gate %d.\n',item.label,audit.quadraturePassed);
    clear cp s l h context rho Omega Dx Dy X Y weights
end
profile off;profileInfo=profile('info');names={profileInfo.FunctionTable.FunctionName};
for key={'ipm.mesh.build','ipm.evolve.flow','ipm.field.velocity','ipm.field.poisson', ...
        'ipm.output.restoreCheckpoint','ipm.evolve.initializeScaling','ipm.evolve.advance','ipm.solve','ipm.remesh.transfer'}
    assert(~any(strcmp(names,key{1})),['Forbidden call: ',key{1}]);
end
report.noLUCallGraphChecked=true;report.allPreparationGatesPassed=all(cellfun(@(x)x.nativeExecutionReady,report.cases));
save(fullfile(out,'report.mat'),'report','profileInfo');write_json(fullfile(out,'report.json'),report);disp(jsonencode(report));
end
function b=pack(v,nx,ny)
b=struct('left',v(1:ny),'right',v(ny+(1:ny)),'top',v(2*ny+(1:nx))','bottom',v(2*ny+nx+(1:nx))');
end
function write_json(path,value)
fid=fopen(path,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
