function report=ipm_accellab_audit_transaction_frequency(checkpointFiles,outputDirectory)
%IPM_ACCELLAB_AUDIT_TRANSACTION_FREQUENCY Strict, array-only evidence export.
% Saved checkpoint windows are accepted-state observations, not reconstructed
% pretransaction decision windows. This function does not restore operators.
assert(maxNumCompThreads==10,'ipm:AccelerationAuditThreads','Use native ten-thread validation.');
assert(iscell(checkpointFiles)&&~isempty(checkpointFiles));
assert(~isfolder(outputDirectory),'ipm:AccelerationAuditOutput','Never overwrite an existing report.');
mkdir(outputDirectory);
registration=struct('kind','native_transaction_frequency_read_only_v1', ...
    'checkpointFiles',{checkpointFiles},'strictNativeRead',true,'threads',10, ...
    'readCheckpointImplementation',which('ipm.output.readCheckpoint'), ...
    'noLU',true,'noPDE',true,'noControllerMutation',true, ...
    'preTransactionDecisionReconstructionClaim',false);
write_json(fullfile(outputDirectory,'registration.json'),registration);
profile clear;profile on;
observations=cell(size(checkpointFiles));
previousStep=-1;
for k=1:numel(checkpointFiles)
    cp=ipm.output.readCheckpoint(checkpointFiles{k});
    v=cp.payload.state;m=v.runMetadata.autonomousMesh;
    assert(v.step>previousStep);previousStep=v.step;
    observations{k}=struct('checkpointFile',checkpointFiles{k}, ...
        'step',v.step,'canonicalTime',v.scale.canonicalTime, ...
        'physicalTime',v.scale.physicalTime,'remeshCount',v.remeshCount, ...
        'window',m.window,'lastDecision',m.lastDecision,'lastFailure',m.lastFailure);
end
profile off;prof=profile('info');
forbidden={'+mesh/build.m','+evolve/flow.m','+remesh/transfer.m', ...
    '+evolve/advance.m','+output/restoreCheckpoint.m'};
calls={prof.FunctionTable.FileName};found={};
for k=1:numel(forbidden)
    if any(endsWith(calls,forbidden{k})),found{end+1}=forbidden{k};end %#ok<AGROW>
end
assert(isempty(found),'ipm:AccelerationUnexpectedWork','Only strict read and arithmetic are allowed.');
report=struct('registration',registration,'strictNativeReadsPassed',true, ...
    'checkpointObservations',{observations},'latestStep',v.step, ...
    'latestCanonicalTime',v.scale.canonicalTime,'latestPhysicalTime',v.scale.physicalTime, ...
    'latestRemeshCount',v.remeshCount,'latestMetadata',m, ...
    'policy',v.config.remesh.autonomousMesh,'history',cp.payload.log.history, ...
    'latestWindowMatchesNativeTail',isequal(m.window.coreCells(end,:), ...
       [cp.payload.log.history.mesh.coreGridPoints(end),cp.payload.log.history.mesh.verticalCoreGridPoints(end)]), ...
    'allHistoryTrusted',all(ipm.output.trustedMask(cp.payload.log.history,v.config)), ...
    'storedSnapshotCount',numel(cp.payload.log.snapshotRho), ...
    'forbiddenProfileCalls',{found},'controllerOrPdeChanged',false);
save(fullfile(outputDirectory,'native_evidence.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'native_evidence.json'),report);
fprintf('TRANSACTION_FREQUENCY_STRICT_READ cp=%d step=%d tau=%.15g transactions=%d history=%d window=%d noLU=1\n', ...
    numel(checkpointFiles),v.step,v.scale.canonicalTime,numel(m.transactions), ...
    numel(cp.payload.log.history.common.t),numel(m.window.time));
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,'PrettyPrint',true));
end
