function chart = ipm_accellab_pullback_hermite(omega,forcing,x,y,Dx,Dy,coordinates,xi,eta)
%IPM_ACCELLAB_PULLBACK_HERMITE Derivative of one linear C1 inner observer.
%   Forcing is F_X from the unchanged PDE. Hermite jets use supplied fixed
%   native Dx/Dy. I_h[F_X] is the time derivative of I_h[omega] at fixed X,Y
%   because this I_h is linear in data; a nonlinear slope limiter is absent.
validateattributes(xi,{'numeric'},{'vector','real','finite','increasing'});
validateattributes(eta,{'numeric'},{'vector','real','finite','increasing','nonnegative'});
assert(coordinates.valid && coordinates.peak.value > 0 && ...
    coordinates.wallCoreWidth > 0 && coordinates.verticalCoreWidth > 0, ...
    'ipm:HermiteCoordinates','Valid positive exact inner coordinates are required.');
[XI,ETA] = meshgrid(xi(:)',eta(:));
queryX = coordinates.peak.x+coordinates.wallCoreWidth*XI;
queryY = coordinates.verticalCoreWidth*ETA;
interpolated = ipm_accellab_tensor_hermite(omega,x,y,Dx,Dy,queryX,queryY);
interpolatedForcing = ipm_accellab_tensor_hermite(forcing,x,y,Dx,Dy,queryX,queryY);
queryXPrime = coordinates.translationRate+coordinates.wallCoreWidthPrime*XI;
queryYPrime = coordinates.verticalCoreWidthPrime*ETA;
P = coordinates.peak.value;
U = interpolated.value/P;
G = (interpolatedForcing.value+queryXPrime.*interpolated.derivativeX+ ...
    queryYPrime.*interpolated.derivativeY)/P-(coordinates.peakPrime/P)*U;
mx = min(interpolated.fractionX,1-interpolated.fractionX);
my = min(interpolated.fractionY,1-interpolated.fractionY);
nonWall = queryY > y(1);
chart = struct('kind','read_only_linear_C1_hermite_inner_pullback','U',U,'G',G, ...
    'xi',xi(:)','eta',eta(:),'queryX',queryX,'queryY',queryY, ...
    'cellRows',interpolated.cellRows,'cellColumns',interpolated.cellColumns, ...
    'minimumMovingCellMargin',min(min(mx(nonWall),my(nonWall))), ...
    'xFractionMargin',mx,'yFractionMargin',my, ...
    'amplitudeDerivativeRetained',coordinates.peakPrime, ...
    'derivativeOfSameInterpolant',true,'fieldToObserverLinear',true, ...
    'contract','Same tensor Hermite polynomial for value/spatial derivatives; I_h[F_X] uses identical fixed linear FD jets. No PDE, C, amplitude residual or prior acceptance decision is changed.');
end
