function report=ipm_accellab_one_sided_profile_index(profilesFile,outputDirectory)
%IPM_ACCELLAB_ONE_SIDED_PROFILE_INDEX Fixed-radius finite-time observation.
% Density increments and radial derivatives come from the same fixed linear
% tensor Hermite polynomial. No spatial regularity or singularity claim.
assert(maxNumCompThreads==10 && ~isfolder(outputDirectory));mkdir(outputDirectory);
saved=load(profilesFile,'report','curves');records=saved.report.records;
r=logspace(-5,-2,81);registration=struct('kind','positive_side_fixed_physical_radius_index_v1', ...
    'profilesFile',profilesFile,'checkpointFiles',{{records.checkpointFile}}, ...
    'radiusDefinition','logspace(-5,-2,81)','physicalRadius',r, ...
    'minimumCoreWidthFactor',4,'minimumNativeKnots',8,'maximumCellToRadiusRatio',.25, ...
    'positiveFiniteDenominatorRequired',true,'samePolynomialValueAndDerivative',true, ...
    'primaryPeak','continuous Hermite peak of paired native rhoX', ...
    'secondaryPeak','native whole-field physical rhoX maximum', ...
    'negativeSide','not evaluated; not combined with the positive-side observable', ...
    'noBestWindowSelection',true,'noPDE',true,'noLU',true,'spatialHolderExponentClaim',false);
write_json(fullfile(outputDirectory,'registration.json'),registration);
profile clear;profile on
mms=check_units(r);assert(mms.passed,'ipm:ProfileIndexMms','Analytic value/derivative and physical unit checks must pass.');
samples=cell(size(records));parentFile='';parent=[];
for k=1:numel(records)
    cp=ipm.output.readCheckpoint(records(k).checkpointFile);s=cp.payload.state;h=cp.payload.log.history;
    assert(all(ipm.output.trustedMask(h,s.config)) && s.step==records(k).step && ...
        strcmp(s.config.scaling.dynamicScaleGeometry,'isotropic'));
    Dx=ipm.mesh.fdMatrix(s.x,1,7);Dy=ipm.mesh.fdMatrix(s.y,1,7);omega=s.rho*Dx';
    geometry=continuous_inner_geometry(omega,s.x,s.y,Dx,Dy, ...
        s.config.scaling.transportAnchorX*[.8,1.15]);
    assert(isequaln(geometry,records(k).geometry),'ipm:ProfileIndexPair','Saved geometry must reproduce exactly.');
    Cx=exp(s.scale.logC_l);Cw=exp(s.scale.logC_omega);a=geometry.peakX;w=geometry.wallWidth/Cx;
    center=ipm_accellab_tensor_hermite(s.rho,s.x,s.y,Dx,Dy,a,0);
    assert(isequal((s.x-a)/Cx,saved.curves{k}.physicalCenteredX) && ...
        isequal((s.rho(1,:)-center.value)/Cw,saved.curves{k}.physicalDensity) && ...
        isequal(omega(1,:)*Cx/Cw,saved.curves{k}.physicalGradient) && ...
        geometry.peak*Cx/Cw==records(k).physicalPeak && ...
        w==records(k).physicalWidths(1) && ...
        h.common.physicalRhoXInf(end)==records(k).physicalGridGradientMaximum, ...
        'ipm:ProfileIndexPair','Every saved wall sample must pair bitwise with its native field/axes/scales.');
    tau=s.scale.canonicalTime;physicalTime=s.scale.physicalTime;
    if isfield(s.runMetadata.caseMetadata,'latePhysicalBoxBranch')
        l=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
        if ~strcmp(parentFile,l.parentCheckpoint)
            parent=ipm.output.readCheckpoint(l.parentCheckpoint);parentFile=l.parentCheckpoint;
        end
        p=parent.payload.state;
        assert(~isfield(p.runMetadata.caseMetadata,'latePhysicalBoxBranch') && ...
            strcmp(p.runMetadata.caseId,l.parentCaseId) && p.step==l.parentStep && ...
            p.scale.physicalTime==l.absolutePhysicalEpoch && p.scale.canonicalTime==l.parentCanonicalTime && ...
            exp(p.scale.logC_l)==l.parentCx && exp(p.scale.logC_omega)==l.parentComega && ...
            l.canonicalCovarianceFactor==l.parentCx/l.parentComega && ...
            ~l.parentHistoryInherited && ~l.parentCheckpointModified);
        tau=l.parentCanonicalTime+l.canonicalCovarianceFactor*tau;
        physicalTime=l.absolutePhysicalEpoch+physicalTime;
    end
    assert(tau==records(k).tau && physicalTime==records(k).absolutePhysicalTime);
    qx=a+Cx*r;inside=qx>=s.x(1)&qx<=s.x(end);
    delta=NaN(size(r));radial=delta;queryCells=delta;nativeKnots=zeros(size(r));maxCell=delta;
    if any(inside)
        q=ipm_accellab_tensor_hermite(s.rho,s.x,s.y,Dx,Dy,qx(inside),zeros(1,sum(inside)));
        delta(inside)=(q.value-center.value)/Cw;
        radial(inside)=Cx/Cw*q.derivativeX;
        queryCells(inside)=q.cellColumns;
    end
    for j=1:numel(r)
        if ~inside(j),continue;end
        nativeKnots(j)=sum(s.x>=a & s.x<=qx(j));
        crossed=s.x(1:end-1)<qx(j) & s.x(2:end)>a;
        widths=diff(s.x)/Cx;maxCell(j)=max(widths(crossed));
    end
    positiveFinite=inside & isfinite(delta) & delta>0 & isfinite(radial);
    outsideCore=r>=4*w;nodesEnough=nativeKnots>=8;
    cellsEnough=maxCell./r<=.25;
    valid=positiveFinite & outsideCore & nodesEnough & cellsEnough;
    alpha=NaN(size(r));alpha(valid)=r(valid).*radial(valid)./delta(valid);
    reasons=cell(size(r));
    for j=1:numel(r)
        reasons{j}={};
        if ~inside(j),reasons{j}{end+1}='outside_native_domain';end
        if ~positiveFinite(j),reasons{j}{end+1}='density_increment_not_positive_finite_or_derivative_nonfinite';end
        if ~outsideCore(j),reasons{j}{end+1}='radius_below_four_current_core_widths';end
        if ~nodesEnough(j),reasons{j}{end+1}='fewer_than_eight_native_knots';end
        if ~cellsEnough(j),reasons{j}{end+1}='native_cell_exceeds_quarter_radius_or_unavailable';end
    end
    G=geometry.peak*Cx/Cw;gridG=records(k).physicalGridGradientMaximum;
    samples{k}=struct('checkpointFile',records(k).checkpointFile,'step',s.step, ...
        'parentEquivalentTau',tau,'absolutePhysicalTime',physicalTime,'remeshCount',s.remeshCount, ...
        'physicalPeakX',(a-s.scale.X_shift)/Cx,'physicalCoreWidth',w, ...
        'physicalContinuousPeak',G,'physicalNativeGridMaximum',gridG, ...
        'physicalDensityHermiteDerivativeAtCenter',Cx/Cw*center.derivativeX, ...
        'centerDerivativeRelativeToContinuousOmegaPeak',Cx/Cw*center.derivativeX/G, ...
        'physicalRadius',r,'radiusOverCoreWidth',r/w,'queryNativeX',qx,'queryCell',queryCells, ...
        'physicalDensityIncrement',delta,'physicalRadialDerivative',radial, ...
        'effectiveSpatialIndex',alpha,'valid',valid,'exclusionReasons',{reasons}, ...
        'insideDomain',inside,'positiveFiniteDenominatorAndDerivative',positiveFinite, ...
        'outsideFourCoreWidths',outsideCore,'nativeKnotsInInterval',nativeKnots, ...
        'maximumCrossedNativeCellPhysicalWidth',maxCell,'maximumCellToRadiusRatio',maxCell./r, ...
        'nodesEnough',nodesEnough,'cellsEnough',cellsEnough, ...
        'savedGeometryAndWallCurvesBitwisePaired',true,'nativeSignatureValidated',true);
    T=table(r(:),(r/w)',delta(:),radial(:),alpha(:),valid(:),inside(:), ...
        positiveFinite(:),outsideCore(:),nativeKnots(:),maxCell(:),(maxCell./r)', ...
        'VariableNames',{'physicalRadius','radiusOverCoreWidth','densityIncrement','radialDerivative', ...
        'effectiveSpatialIndex','valid','insideDomain','positiveFinite','outsideFourCoreWidths', ...
        'nativeKnots','maximumCellWidth','maximumCellToRadiusRatio'});
    writetable(T,fullfile(outputDirectory,sprintf('step_%07d_all_radii.csv',s.step)));
    fprintf('PROFILE_INDEX step=%d tau=%.9f eligible=%d/%d minRadius=%.7g\n',s.step,tau,sum(valid),numel(r),min(r(valid)));
end
samples=[samples{:}];temporal=cell(1,numel(samples)-1);
for k=1:numel(temporal)
    a=samples(k);b=samples(k+1);den=log(b.physicalCoreWidth)-log(a.physicalCoreWidth);
    assert(den<0 && b.parentEquivalentTau>a.parentEquivalentTau && b.absolutePhysicalTime>a.absolutePhysicalTime);
    primary=(log(b.physicalContinuousPeak*b.physicalCoreWidth)-log(a.physicalContinuousPeak*a.physicalCoreWidth))/den;
    secondary=(log(b.physicalNativeGridMaximum*b.physicalCoreWidth)-log(a.physicalNativeGridMaximum*a.physicalCoreWidth))/den;
    temporal{k}=struct('startStep',a.step,'endStep',b.step, ...
        'startTau',a.parentEquivalentTau,'endTau',b.parentEquivalentTau, ...
        'startPhysicalTime',a.absolutePhysicalTime,'endPhysicalTime',b.absolutePhysicalTime, ...
        'startWidth',a.physicalCoreWidth,'endWidth',b.physicalCoreWidth, ...
        'startContinuousPeak',a.physicalContinuousPeak,'endContinuousPeak',b.physicalContinuousPeak, ...
        'deltaLogWidth',den,'amplitudeWidthLogSlopeContinuousPeak',primary, ...
        'amplitudeWidthLogSlopeNativeGridMaximum',secondary, ...
        'remeshCountChange',b.remeshCount-a.remeshCount, ...
        'remeshAndSpatialErrorRemoved',false);
end
profile off;prof=profile('info');calls={prof.FunctionTable.FileName};forbidden={};
suffix={'+mesh/build.m','+evolve/flow.m','+evolve/advance.m','+output/restoreCheckpoint.m'};
for k=1:numel(suffix),if any(endsWith(calls,suffix{k})),forbidden{end+1}=suffix{k};end,end %#ok<AGROW>
assert(isempty(forbidden));
report=struct('registration',registration,'mms',mms,'samples',samples,'temporalScaleSlopes',[temporal{:}], ...
    'allNativePairsStrictAndExact',true,'forbiddenProfileCalls',{forbidden}, ...
    'spatialDiscretizationErrorValidated',false,'remeshJumpRemoved',false, ...
    'limitingHolderExponentEstablished',false,'strongSingularityEstablished',false, ...
    'interpretation','Finite-time positive-side density increments at fixed physical radii. Width and native-cell masks are preregistered. Temporal amplitude-width slopes are distinct observations, crossing actual remesh events; neither is a limiting regularity exponent.');
save(fullfile(outputDirectory,'indices.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'indices.json'),report);render(report,outputDirectory);
end
function report=check_units(r)
x=2*sinh(linspace(-1,1,49))/sinh(1);y=sinh(linspace(0,1,33))';
Dx=ipm.mesh.fdMatrix(x,1,7);Dy=ipm.mesh.fdMatrix(y,1,7);[X,Y]=meshgrid(x,y);
field=1+.7*X+.1*X.^2+.02*X.^3+.1*Y.^2;a=.3;
c=ipm_accellab_tensor_hermite(field,x,y,Dx,Dy,a,0);errors=[];
for Cx=[.2,1,7]
    dx=Cx*r;query=a+dx;q=ipm_accellab_tensor_hermite(field,x,y,Dx,Dy,query,zeros(size(query)));
    exactDelta=dx*(.7+.2*a+.06*a^2)+dx.^2*(.1+.06*a)+.02*dx.^3;
    exactDerivative=.7+.2*query+.06*query.^2;
    for Cw=[.3,1,10]
        value=(q.value-c.value)/Cw;derivative=Cx/Cw*q.derivativeX;
        exact=value;exact(:)=exactDelta/Cw;
        exactA=r.*(Cx/Cw*exactDerivative)./exact;
        observedA=r.*derivative./value;
        errors(end+1,:)=[max(abs(value-exact)./abs(exact)), ...
            max(abs(derivative-Cx/Cw*exactDerivative)./abs(Cx/Cw*exactDerivative)), ...
            max(abs(observedA-exactA))]; %#ok<AGROW>
    end
end
report=struct('kind','analytic_cubic_physical_unit_checks','cases',9,'radiiPerCase',numel(r), ...
    'maximumRelativeIncrementError',max(errors(:,1)), ...
    'maximumRelativeRadialDerivativeError',max(errors(:,2)), ...
    'maximumAbsoluteEffectiveIndexError',max(errors(:,3)), ...
    'tolerance',5e-9,'passed',max(errors,[],'all')<5e-9);
end
function render(report,out)
s=report.samples;colors=lines(numel(s));fig=figure('Visible','off','Color','w','Position',[50,50,1300,850]);
clean=onCleanup(@()close(fig));tiledlayout(2,2,'TileSpacing','compact');labels=compose('tau %.3f',[s.parentEquivalentTau]);
nexttile;hold on
for k=1:numel(s),semilogx(s(k).physicalRadius,s(k).effectiveSpatialIndex,'Color',colors(k,:),'LineWidth',1.4);end
set(gca,'XScale','log');xlabel('fixed physical radius r');ylabel('a_{eff}(r)');title('Admitted positive-side finite-time indices');grid on;legend(labels,'Location','best');
nexttile;hold on
for k=1:numel(s),v=s(k).physicalDensityIncrement;v(~s(k).valid)=NaN;loglog(s(k).physicalRadius,v,'Color',colors(k,:),'LineWidth',1.4);end
set(gca,'XScale','log','YScale','log');xlabel('fixed physical radius r');ylabel('rho(x_{peak}+r)-rho(x_{peak})');title('Same-polynomial physical density increments');grid on
nexttile;hold on
for k=1:numel(s),semilogx(s(k).physicalRadius,double(s(k).valid)+.12*(k-1),'Color',colors(k,:),'LineWidth',1.3);end
set(gca,'XScale','log');xlabel('fixed physical radius r');ylabel('valid (traces offset by 0.12)');title('All registered-radius inclusion masks');grid on
nexttile;t=report.temporalScaleSlopes;mid=.5*([t.startTau]+[t.endTau]);
plot(mid,[t.amplitudeWidthLogSlopeContinuousPeak],'-o',mid,[t.amplitudeWidthLogSlopeNativeGridMaximum],'--s','LineWidth',1.3);
xlabel('adjacent interval midpoint in parent-equivalent tau');ylabel('Delta log(G w) / Delta log(w)');
title('Separate temporal scale slopes; remesh jumps retained');grid on;legend('continuous peak','native grid maximum','Location','best');
sgtitle('Finite-time profile observations; no limiting regularity or singularity claim');
set(findall(fig,'Type','axes'),'Color','w','XColor',[.15,.15,.15],'YColor',[.15,.15,.15]);
set(findall(fig,'Type','text'),'Color',[.1,.1,.1]);
exportgraphics(fig,fullfile(out,'one_sided_indices.png'),'Resolution',160);
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(value,'PrettyPrint',true));
end
