function report = ipm_accellab_test_modulation()
%IPM_ACCELLAB_TEST_MODULATION Synthetic exact motion and tiny original RHS.
directory = fileparts(mfilename('fullpath'));
addpath(directory,fileparts(fileparts(directory)));
center = 0.4;
z = linspace(-1.5,1.5,49);
x = center+z+0.02*sin(2*z);
y = linspace(0,1,33)'.^1.2;
[X,Y] = meshgrid(x,y);
xi = X-center;
omega = 2-xi.^2-0.7*Y.^2-0.3*xi.^2.*Y.^2;
omegaX = -2*xi-0.6*xi.*Y.^2;
omegaY = -1.4*Y-0.6*xi.^2.*Y;
rates = [0.031;-0.65;-0.67];
forcing = -rates(1)*omegaX-rates(2)*xi.*omegaX-rates(3)*Y.*omegaY;
weights = ones(size(omega));
fit = abs(xi) <= 0.8 & Y <= 0.6;
outer = abs(xi) <= 1.2 & Y <= 0.9;
wall = false(size(omega)); wall(1,:) = outer(1,:);
problem = struct('forcing',forcing,'translation',omegaX, ...
    'scaleX',xi.*omegaX,'scaleY',Y.*omegaY,'weights',weights, ...
    'fitMask',fit,'amplitudeScale',2, ...
    'masks',struct('fit',fit,'holdout',outer & ~fit, ...
        'core',outer,'full',true(size(omega)),'wall',wall));
[free,residual] = ipm_accellab_fit_motion(problem);
found = [free.translationRate;free.logScaleXRate;free.logScaleYRate];
assert(free.valid && norm(found-rates) < 1e-12 && max(abs(residual),[],'all') < 1e-12, ...
    'ipm:MotionTestRates','The exact translation/contraction modes were not recovered.');
[~,peakIndex] = max(omega(1,:));
motion = ipm_accellab_quadratic_motion(omega(1,:),forcing(1,:),x,peakIndex);
assert(abs(motion.translationRate-rates(1)) < 1e-12, ...
    'ipm:MotionTestQuadratic','Strict nonuniform quadratic peak speed is incorrect.');
fixed = ipm_accellab_fit_motion(problem, ...
    struct('fixedTranslationRate',motion.translationRate));
assert(fixed.valid && abs(fixed.logScaleXRate-rates(2)) < 1e-12 && ...
    abs(fixed.logScaleYRate-rates(3)) < 1e-12,'ipm:MotionTestFixedPhase', ...
    'Fixed exact phase did not recover both contraction rates.');

contaminated = problem;
holdout = outer & ~fit;
contaminated.forcing(holdout) = contaminated.forcing(holdout)+0.1;
holdoutAudit = ipm_accellab_fit_motion(contaminated);
assert(holdoutAudit.metrics.fit.modulatedInf < 1e-12 && ...
    holdoutAudit.metrics.holdout.modulatedInf > 0.04, ...
    'ipm:MotionTestHoldout','Training cancellation concealed held-out error.');
degenerate = problem;
degenerate.scaleY = degenerate.scaleX;
rankAudit = ipm_accellab_fit_motion(degenerate);
assert(~rankAudit.valid && rankAudit.rank < 3,'ipm:MotionTestRank', ...
    'A rank-deficient geometric decomposition was accepted.');

opts = struct('nx',65,'ny',33,'xlim',[-4,4],'ymax',4, ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'symmetryMode','double_odd_omega','rescalingMode','dynamic', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','wall_omega_quadratic_peak', ...
    'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
    'adaptiveRemesh',false,'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
state = ipm.evolve.initialize(opts);
before = state.rho;
tiny = ipm_accellab_modulated_probe(state,struct('fitHalfWidthX',2, ...
    'fitHeightY',3,'holdoutHalfWidthX',3,'holdoutHeightY',5));
assert(isequal(before,state.rho) && tiny.originalRhsEvaluations == 1 && ...
    tiny.pdeAcceptedSteps == 0 && tiny.freeMotion.valid && tiny.fixedQuadraticMotion.valid, ...
    'ipm:MotionTestTiny','The read-only tiny original-RHS probe failed.');
report = struct('status','passed','syntheticRates',rates,'syntheticFreeFit',free, ...
    'syntheticQuadraticMotion',motion,'syntheticFixedPhaseFit',fixed, ...
    'holdoutErrorDetected',true,'rankDeficiencyRejected',true, ...
    'tinyOriginalRhsProbe',tiny,'productionPdeSteps',0, ...
    'productionModulationEstablished',false);
fprintf('MODULATED PASS: rate error %.3e; quadratic speed error %.3e; tiny condition %.3g.\n', ...
    norm(found-rates),abs(motion.translationRate-rates(1)),tiny.freeMotion.scaledCondition);
end
