function report=ipm_accellab_design_after_family_failure(projectRoot,campaignDirectory,outputRoot)
%IPM_ACCELLAB_DESIGN_AFTER_FAMILY_FAILURE Read-only late paired mesh rescue.
addpath(projectRoot,fullfile(projectRoot,'research','longtime_lab'), ...
    fullfile(projectRoot,'research','grid_lab'),fileparts(mfilename('fullpath')));
assert(maxNumCompThreads==10);
[~,token]=fileparts(tempname);out=fullfile(outputRoot,['generic_design_step4768_',token]);mkdir(out);
campaignRegistration=jsondecode(fileread(fullfile(campaignDirectory,'registration.json')));
policy=ipm.config.autonomousMeshPolicy(struct());s=policy.search;
controls=struct('targetXCoreCells',policy.targetCoreCells(1),'targetYCoreCells',policy.targetCoreCells(2), ...
    'minimumXFrontCells',policy.minimumFrontCells,'positiveFineCells',s.fineCells, ...
    'roundingCells',s.roundingCells,'coreFineCellFractions',s.coreFineCellFractions, ...
    'yEqualizationSigmas',s.ySigma,'resolutionPadding',s.xPadding,'verticalResolutionPadding',s.yPadding, ...
    'anchorWarpRadius',s.maximumWarpFraction,'maximumAxisCandidates',s.maximumAxisCandidates, ...
    'maximumFullPairScores',s.maximumPairCandidates,'includeUnchangedPair',true);
resultFile=fullfile(campaignDirectory,'stage_003','result.mat');
registration=struct('kind','same_policy_generic_design_after_registered_family_failure', ...
    'resultFile',resultFile,'initialDataFile',campaignRegistration.initialDataFile, ...
    'oldFailureDirectory',fullfile(campaignDirectory,'stage_004'),'controls',controls,'policy',policy, ...
    'outputDirectory',out,'strictNativeThreads',10,'noLU',true,'noPDE',true, ...
    'productionModified',false,'oldFailuresChanged',false,'nativeTransactionPerformed',false);
write_json(fullfile(out,'registration.json'),registration);
try
    oldFailures=cell(1,4);
    for k=1:4
        directory=fullfile(registration.oldFailureDirectory,sprintf('design_%02d',k));
        f=load(fullfile(directory,'candidate.mat'),'candidate');c=f.candidate;
        d=load(fullfile(directory,'design.mat'),'design');d=d.design;
        oldFailures{k}=struct('index',k,'candidateFile',fullfile(directory,'candidate.mat'), ...
            'controls',d.controls,'transactionReady',c.transactionReady,'frozenCandidatePassed',c.frozenCandidatePassed, ...
            'localQuadraturePassed',c.localQuadraturePassed,'resolutionPassed',c.resolutionPassed, ...
            'transferPassed',c.transferPassed,'anchorExact',c.anchorExact, ...
            'pairAdmissible',c.pairScore.admissible,'pairRejectionReasons',{c.pairScore.rejectionReasons}, ...
            'quality',c.pairScore.quality,'aggregate',c.pairScore.aggregate, ...
            'construction',c.xConstruction,'independentQualityReasons',quality_reasons(c.pairScore.quality,policy.qualityLimits));
        fprintf('OLD_FAMILY_FAILURE %d admissible=%d reasons=%s\n',k,c.pairScore.admissible,strjoin(c.pairScore.rejectionReasons,','));
    end
    save(fullfile(out,'old_failures.mat'),'oldFailures');write_json(fullfile(out,'old_failures.json'),oldFailures);
    [sourceReview,cp,contract]=fresh_profile_campaign_review(resultFile,registration.initialDataFile);
    n=cp.payload.state;assert(n.step==4768&&numel(n.x)==895&&numel(n.y)==386);
    sourceSignature=cp.signature;sourceCheckpoint=sourceReview.checkpointFile;
    reference=struct('x',contract.initialX,'y',contract.initialY, ...
        'provenance',struct('kind','strict_native_immutable_base_axes','sourceCheckpoint',sourceCheckpoint, ...
        'initialDataFile',registration.initialDataFile,'lineage',contract.lineage));
    assert(isequal(reference.x(:),n.baseX(:))&&isequal(reference.y(:),n.baseY(:)));
    anchor=n.config.scaling.transportAnchorX;
    snapshot=struct('rho',n.rho,'x',n.x,'y',n.y,'scale',struct('Cx',exp(n.scale.logC_l), ...
        'Cy',exp(n.scale.logC_l),'Comega',exp(n.scale.logC_omega)), ...
        'canonicalTime',n.scale.canonicalTime,'physicalTime',n.scale.physicalTime,'trusted',true, ...
        'provenance',struct('kind','strict_native_result_entire_history_paired_terminal', ...
        'checkpoint',sourceCheckpoint,'caseId',n.runMetadata.caseId,'step',n.step));
    save(fullfile(out,'source_eligibility.mat'),'sourceReview','sourceSignature','sourceCheckpoint','contract');
    write_json(fullfile(out,'source_review.json'),sourceReview);
    clear n cp
    timer=tic;[candidate,design]=mesh_design_paired_snapshot(snapshot,reference,anchor,controls);elapsed=toc(timer);
    nativeTransactionOptions=struct('outputFile','','tag','generic4768_same_policy_research_candidate', ...
        'minimumXCoreCells',policy.transactionMinimumCoreCells(1),'minimumYCoreCells',policy.transactionMinimumCoreCells(2), ...
        'maximumRhoXRelativeChange',policy.maximumSinglePeakJump,'maximumMassRelativeDefect',policy.maximumMassRelativeDefect, ...
        'maximumRelativeRangeViolation',policy.maximumRelativeRangeViolation, ...
        'meshLimits',rmfield(policy.qualityLimits,{'minWeightToControlWidth','maxWeightToControlWidth'}));
    invariantAudit=struct('sameBox',false,'sameNodeCount',false,'referenceAxesUnchanged',true, ...
        'anchorExact',false,'frozenCumulativePeakBudgetPassed',false,'nativeTransactionPerformed',false);
    if candidate.transactionReady
        invariantAudit.sameBox=isequal(candidate.candidateX([1,end]),snapshot.x([1,end]))&& ...
            isequal(candidate.candidateY([1,end]),snapshot.y([1,end]));
        invariantAudit.sameNodeCount=numel(candidate.candidateX)==895&&numel(candidate.candidateY)==386;
        invariantAudit.anchorExact=any(candidate.candidateX==anchor)&&any(candidate.candidateX==-anchor);
        invariantAudit.frozenCumulativePeakBudgetPassed=sourceReview.cumulativeAbsolutePeakJump+ ...
            candidate.pairScore.aggregate.worst.rhoXMaximumRelativeChange<=policy.maximumCumulativeAbsolutePeakJump;
        assert(invariantAudit.sameBox&&invariantAudit.sameNodeCount&&invariantAudit.anchorExact&&invariantAudit.frozenCumulativePeakBudgetPassed);
    end
    candidateFile=fullfile(out,'candidate.mat');
    save(candidateFile,'candidate','design','sourceReview','sourceCheckpoint','sourceSignature','contract', ...
        'nativeTransactionOptions','invariantAudit','-v7.3');
    report=struct('registration',registration,'oldFailures',{oldFailures},'sourceReview',sourceReview, ...
        'candidateFile',candidateFile,'designStatus',design.status,'candidateReadyForNativeTransaction',candidate.transactionReady, ...
        'nativeTransactionPerformed',false,'invariantAudit',invariantAudit,'elapsedDesignSeconds',elapsed, ...
        'xAxisCandidates',numel(design.xTrials),'xAdmitted',sum([design.xTrials.admissible]), ...
        'yAxisCandidates',numel(design.yTrials),'yAdmitted',sum([design.yTrials.admissible]), ...
        'pairScores',numel(design.pairTrials),'interpretation', ...
        'Frozen paired score only. Native remesh, true flow, history/prefix and continuation gates remain required; old failed candidates are unchanged.');
    save(fullfile(out,'report.mat'),'report');write_json(fullfile(out,'report.json'),report);
    write_json(fullfile(out,'design.json'),design);
catch e
    failure=struct('registration',registration,'identifier',e.identifier,'message',e.message,'stack',e.stack);
    write_json(fullfile(out,'failure.json'),failure);rethrow(e);
end
fprintf('GENERIC_4768_DESIGN %s ready=%d status=%s x=%d/%d y=%d/%d seconds=%.3f\n', ...
    candidateFile,candidate.transactionReady,design.status,report.xAdmitted,report.xAxisCandidates,report.yAdmitted,report.yAxisCandidates,elapsed);
end
function r=quality_reasons(q,limits)
r=struct();
for axis={'x','y'}
    a=q.(axis{1});bad=[a.maximumAdjacentCellRatio>limits.maxAdjacentCellRatio, ...
        a.maximumLogSpacingCurvature>limits.maxLogSpacingCurvature,a.minimumStencilRcond<limits.minStencilRcond, ...
        a.minimumQuadratureWeightRatio<limits.minQuadratureWeightRatio,~a.quadratureWeightsStrictlyPositive, ...
        a.minimumQuadratureWeightToControlWidthRatio<limits.minWeightToControlWidth, ...
        a.maximumQuadratureWeightToControlWidthRatio>limits.maxWeightToControlWidth];
    labels={'adjacent_ratio','spacing_curvature','stencil_rcond','global_quadrature','nonpositive_quadrature', ...
        'local_quadrature_min','local_quadrature_max'};r.(axis{1})=labels(bad);
end
end
function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(ipm_accellab_json_view(value),'PrettyPrint',true));
end
