function [report,fields] = ipm_accellab_compare_observers(base,rhoRejected,originalTrial)
%IPM_ACCELLAB_COMPARE_OBSERVERS Fixed observer comparison, never reacceptance.
%   Requires a parent-authorized large-grid window if BASE is large: two
%   unchanged full RHS evaluations. Original rejected decision stays frozen.
assert(~originalTrial.accepted && isscalar(originalTrial.attempts), ...
    'ipm:ObserverComparisonProtocol','Only the fixed already-rejected candidate is compared.');
assert(isequal(size(rhoRejected),size(base.rho)) && all(isfinite(rhoRejected(:))), ...
    'ipm:ObserverComparisonField','A finite complete same-grid rejected field is required.');
opts = originalTrial.options;
xi = opts.xi; eta = opts.eta; [XI,ETA] = meshgrid(xi,eta);
core = abs(XI) <= opts.trainingHalfWidthX & ETA <= opts.trainingHeightY;
weights = trap_weights(eta(:))*trap_weights(xi(:))';
ops = base.ops;
metrics = cell(1,2); fields = cell(1,2);
for k = 1:2
    state = base;
    if k == 2, state.rho = rhoRejected; end
    lastwarn('');
    [probe,data] = ipm_accellab_modulated_probe(state,struct('includeExactCoordinates',true));
    [warningMessage,warningIdentifier] = lastwarn;
    exact = probe.exactInnerCoordinates;
    assert(exact.valid,'ipm:ObserverComparisonChart','The fixed field has invalid exact coordinates.');
    linear = ipm_accellab_pullback(data.omega,data.forcing,ops.x,ops.y,exact,xi,eta);
    hermite = ipm_accellab_pullback_hermite(data.omega,data.forcing, ...
        ops.x,ops.y,ops.Dx,ops.Dy,exact,xi,eta);
    metrics{k} = struct('bilinear',norms(linear.G,core,weights,ETA), ...
        'hermite',norms(hermite.G,core,weights,ETA), ...
        'observerDerivativeDifference',norms(hermite.G-linear.G,core,weights,ETA), ...
        'observerValueDifference',norms(hermite.U-linear.U,core,weights,ETA), ...
        'nativeExactMotionMetrics',exact.metrics,'peakPrime',exact.peakPrime, ...
        'exactCoordinates',rmfield(exact,'metrics'),'poissonResidual',probe.poissonResidual, ...
        'warningIdentifier',warningIdentifier,'warningMessage',warningMessage);
    fields{k} = struct('omega',data.omega,'forcing',data.forcing, ...
        'u1',data.flow.u1,'u2',data.flow.u2,'exactCoordinates',rmfield(exact,'metrics'), ...
        'bilinear',linear,'hermite',hermite);
end
names = fieldnames(metrics{1}.bilinear);
linearRatios = struct(); hermiteRatios = struct();
for k = 1:numel(names)
    name = names{k};
    linearRatios.(name) = metrics{2}.bilinear.(name)/max(metrics{1}.bilinear.(name),realmin);
    hermiteRatios.(name) = metrics{2}.hermite.(name)/max(metrics{1}.hermite.(name),realmin);
end
tail = abs(ops.X) >= opts.tailBoxHalfWidthX | ops.Y >= opts.tailBoxHeightY;
tailWeights = ops.integrationWeights(tail); tailWeights = tailWeights/sum(tailWeights);
tailDensityScale = max(sqrt(sum(tailWeights.*base.rho(tail).^2)),realmin);
tailVelocityScale = max(sqrt(sum(tailWeights.* ...
    (fields{1}.u1(tail).^2+fields{1}.u2(tail).^2))),realmin);
tailMetrics = struct('densityRelativeL2', ...
    sqrt(sum(tailWeights.*(rhoRejected(tail)-base.rho(tail)).^2))/tailDensityScale, ...
    'sourceAbsoluteInfOverPeak',max(abs(fields{2}.omega(tail)-fields{1}.omega(tail)))/ ...
        metrics{1}.exactCoordinates.peak.value, ...
    'velocityRelativeL2',sqrt(sum(tailWeights.* ...
        ((fields{2}.u1(tail)-fields{1}.u1(tail)).^2+ ...
        (fields{2}.u2(tail)-fields{1}.u2(tail)).^2)))/tailVelocityScale);
tailMetrics.pass = [tailMetrics.densityRelativeL2 <= opts.tailDensityTolerance, ...
    tailMetrics.sourceAbsoluteInfOverPeak <= opts.tailSourceTolerance, ...
    tailMetrics.velocityRelativeL2 <= opts.tailVelocityTolerance];
reproductionError = 0;
for name = {'trainingL2','trainingInf','holdoutL2','holdoutInf','wallInf'}
    reproductionError = max([reproductionError, ...
        abs(metrics{1}.bilinear.(name{1})-originalTrial.baselineAudit.(name{1})), ...
        abs(metrics{2}.bilinear.(name{1})-originalTrial.attempts.audit.(name{1}))]);
end
report = struct('kind','fixed_field_linear_vs_C1_hermite_observer_comparison', ...
    'baseline',metrics{1},'rejectedCandidate',metrics{2}, ...
    'bilinearCandidateToBaselineRatios',linearRatios, ...
    'hermiteCandidateToBaselineRatios',hermiteRatios,'freshTailMetrics',tailMetrics, ...
    'originalBilinearMetricReproductionMaxAbsoluteError',reproductionError, ...
    'originalTrial',originalTrial,'originalDecision','rejected_unchanged', ...
    'accepted',false,'newRhsEvaluations',2,'newPdeSteps',0,'parameterScan',false, ...
    'interpretation','Observer sensitivity diagnostic only. An improvement under another observer cannot override the registered rejection or failing tail gate.');
end

function result = norms(field,core,weights,ETA)
result = struct('trainingL2',sqrt(sum(weights(core).*field(core).^2)/sum(weights(core))), ...
    'trainingInf',max(abs(field(core))), ...
    'holdoutL2',sqrt(sum(weights(~core).*field(~core).^2)/sum(weights(~core))), ...
    'holdoutInf',max(abs(field(~core))),'wallInf',max(abs(field(ETA == 0))));
end

function weights = trap_weights(axis)
weights = [diff(axis(1:2));axis(3:end)-axis(1:end-2);diff(axis(end-1:end))]/2;
end
