function report=ipm_accellab_export_growth_history(registrationFile)
%IPM_ACCELLAB_EXPORT_GROWTH_HISTORY Strict native growth evidence, no restore.
reg=jsondecode(fileread(registrationFile));assert(maxNumCompThreads==10&&~isfolder(reg.outputDirectory));
mkdir(reg.outputDirectory);profile clear;profile on;
cp=ipm.output.readCheckpoint(reg.checkpointFile);s=cp.payload.state;l=cp.payload.log;m=s.runMetadata.autonomousMesh;
assert(all(ipm.output.trustedMask(l.history,s.config))&&strcmp(s.runMetadata.caseId,reg.caseId));
report=struct('kind','actual_native_growth_history_readonly_v1','label',reg.label, ...
    'checkpointFile',reg.checkpointFile,'reader',which('ipm.output.readCheckpoint'), ...
    'step',s.step,'canonicalTime',s.scale.canonicalTime,'physicalTime',s.scale.physicalTime, ...
    'nodeCount',[numel(s.x),numel(s.y)],'levelId',m.currentLevelId,'remeshCount',s.remeshCount, ...
    'allHistoryTrusted',true,'config',s.config,'memory',m,'history',l.history, ...
    'currentAxes',struct('x',s.x,'y',s.y),'snapshotTimes',l.snapshotNormalizedTime, ...
    'snapshotCount',numel(l.snapshotRho),'snapshotsUsedToReconstructMissingSource',false, ...
    'noLU',true,'noPDE',true,'noControllerMutation',true);
profile off;profileInfo=profile('info');files={profileInfo.FunctionTable.FileName};
for suffix={'+mesh/build.m','+evolve/flow.m','+field/velocity.m','+field/poisson.m', ...
        '+evolve/initializeScaling.m','+remesh/transfer.m','+evolve/advance.m','+output/restoreCheckpoint.m'}
    assert(~any(endsWith(files,suffix{1})),['Forbidden call: ',suffix{1}]);
end
report.callGraphNoLUVerified=true;
save(fullfile(reg.outputDirectory,'evidence.mat'),'report','profileInfo','-v7.3');
fid=fopen(fullfile(reg.outputDirectory,'evidence.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report));
fprintf('STRICT_GROWTH label=%s step=%d tau=%.12g transactions=%d level=%d noLU=1\n', ...
    reg.label,s.step,s.scale.canonicalTime,s.remeshCount,m.currentLevelId);
end
