function report=ipm_accellab_jf_late_preflight(registrationFile)
% Strict actual-state geometry/config preparation; no F or candidate exists.
reg=jsondecode(fileread(registrationFile));assert(maxNumCompThreads==10&&~isfolder(reg.outputDirectory));mkdir(reg.outputDirectory);
profile clear;profile on;cp=ipm.output.readCheckpoint(reg.checkpointFile);s=cp.payload.state;h=cp.payload.log.history;
assert(s.step==9205&&all(ipm.output.trustedMask(h,s.config))&&strcmp(s.runMetadata.caseId,reg.caseId)&&s.scale.X_shift==0);
l=s.runMetadata.caseMetadata.latePhysicalBoxBranch;
parent=ipm.output.readCheckpoint(l.parentCheckpoint);ps=parent.payload.state;
assert(ps.step==l.parentStep&&strcmp(ps.runMetadata.caseId,l.parentCaseId)&&ps.scale.physicalTime==l.absolutePhysicalEpoch&& ...
 ps.scale.canonicalTime==l.parentCanonicalTime&&exp(ps.scale.logC_l)==l.parentCx&&exp(ps.scale.logC_omega)==l.parentComega&& ...
 l.canonicalCovarianceFactor==l.parentCx/l.parentComega&&~l.parentHistoryInherited&&~l.parentCheckpointModified);
Dx=ipm.mesh.fdMatrix(s.x,1,7);Dy=ipm.mesh.fdMatrix(s.y,1,7);Omega=s.rho*Dx';
g=continuous_inner_geometry(Omega,s.x,s.y,Dx,Dy,s.config.scaling.transportAnchorX*reg.peakWindowAnchorFactors(:)');
Cx=exp(s.scale.logC_l);Cw=exp(s.scale.logC_omega);xp=s.x/Cx;yp=s.y/Cx;
legacyX=linspace(-3,3,49);legacyY=linspace(0,3,25);
report=struct('kind','late_actual_JF_tail_ellipsoid_geometry_preflight_only','checkpointFile',reg.checkpointFile, ...
 'runtimeSource',reg.runtimeSource,'step',s.step,'caseId',s.runMetadata.caseId,'nativeSignatureValidated',true, ...
 'allHistoryTrusted',true,'nativeCanonicalTime',s.scale.canonicalTime, ...
 'parentEquivalentTau',l.parentCanonicalTime+l.canonicalCovarianceFactor*s.scale.canonicalTime, ...
 'absolutePhysicalTime',l.absolutePhysicalEpoch+s.scale.physicalTime,'physicalEpoch',l.absolutePhysicalEpoch, ...
 'nodeCount',[numel(s.x),numel(s.y)],'remeshCount',s.remeshCount,'physicalBox',[xp([1,end]),yp([1,end])'], ...
 'physicalPeak',g.peak*Cx/Cw,'physicalPeakX',g.peakX/Cx,'physicalWidths',[g.wallWidth,g.verticalWidth]/Cx, ...
 'nativeCoreCells',[h.mesh.coreGridPoints(end),h.mesh.verticalCoreGridPoints(end)],'geometry',g, ...
 'rescalingMode',s.config.scaling.rescalingMode,'dynamicScaleGeometry',s.config.scaling.dynamicScaleGeometry, ...
 'scalingContract',s.config.scaling.scalingContract,'wallTransportMode',s.config.transport.wallTransportMode, ...
 'transportScheme',s.config.transport.transportScheme,'transportAnchorX',s.config.scaling.transportAnchorX, ...
 'legacyPhysicalWindowCovered',xp(1)<=-3&&xp(end)>=3&&yp(end)>=3, ...
 'legacyUniformSamplesInActualWallCore',nnz(legacyX>=g.wallCrossings(1)/Cx&legacyX<=g.wallCrossings(2)/Cx), ...
 'legacyUniformSamplesInActualVerticalCore',nnz(legacyY>=0&legacyY<=g.verticalWidth/Cx), ...
 'legacySampleSpacingOverActualWidths',[diff(legacyX(1:2))*Cx/g.wallWidth,diff(legacyY(1:2))*Cx/g.verticalWidth], ...
 'legacyTailFieldArraysRetained',true,'truePDEForcingAvailable',false,'truePPrimeEvaluated',false, ...
 'freshRHSCalls',0,'candidateConstructed',false,'nativeCPWritten',false,'noLU',true,'noPDE',true);
[X,Y]=meshgrid(legacyX,legacyY);v=ipm_accellab_tensor_hermite(s.rho,s.x,s.y,Dx,Dy,Cx*X,Cx*Y);
w=ipm_accellab_tensor_hermite(Omega,s.x,s.y,Dx,Dy,Cx*X,Cx*Y);
legacy=struct('x',legacyX,'y',legacyY,'rho',v.value/Cw,'omega',w.value*Cx/Cw,'tail',abs(X)>=2.5|Y>=2, ...
 'u1',[],'u2',[],'velocityAvailability','No restore or RHS; absent, never inferred.');
[qX,qY]=meshgrid(linspace(-2,2,129),linspace(0,3,97));
U=ipm_accellab_tensor_hermite(Omega,s.x,s.y,Dx,Dy,g.peakX+g.wallWidth*qX,g.verticalWidth*qY);
inner=struct('xi',qX(1,:),'eta',qY(:,1),'U',U.value/g.peak,'actualSourceGeometry',g,'forcing',[], ...
 'interpretation','Baseline actual geometry only; no future oracle or candidate realignment has been used.');
sourceConfig=s.config;sourceScale=s.scale;sourceReferences=s.rescaling;
profile off;profileInfo=profile('info');files={profileInfo.FunctionTable.FileName};
for suffix={'+mesh/build.m','+field/poisson.m','+field/velocity.m','+evolve/flow.m','+output/restoreCheckpoint.m','+evolve/advance.m'}
 assert(~any(endsWith(files,suffix{1})),['Forbidden call: ',suffix{1}]);
end
report.noLUCallGraphVerified=true;
save(fullfile(reg.outputDirectory,'preflight.mat'),'report','legacy','inner','sourceConfig','sourceScale','sourceReferences','profileInfo','-v7.3');
fid=fopen(fullfile(reg.outputDirectory,'report.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('LATE_JF_PREFLIGHT step=%d tau=%.12g legacyCounts=%d/%d noLU=1\n',s.step,report.parentEquivalentTau, ...
 report.legacyUniformSamplesInActualWallCore,report.legacyUniformSamplesInActualVerticalCore);
end
