function report=ipm_accellab_compare_zero_initials(registrationFile)
%IPM_ACCELLAB_COMPARE_ZERO_INITIALS Strict original-t0 history, no LU or PDE.
reg=jsondecode(fileread(registrationFile));out=reg.outputDirectory;
assert(maxNumCompThreads==10 && ~isfolder(out));mkdir(out);
profile clear;profile on;
report=struct('kind','strict_native_A_B_zero_time_observation_v1', ...
    'registrationFile',registrationFile,'cases',{{}},'endpointComparison',false, ...
    'pureBoundaryAttribution',false,'PDECount',0,'LUCount',0,'restoreCount',0);
data=cell(1,2);
for k=1:2
    item=reg.cases(k);cp=ipm.output.readCheckpoint(item.checkpointFile);
    s=cp.payload.state;h=cp.payload.log.history;c=h.common;m=h.mesh;
    init=s.runMetadata.autonomousMesh.initialization;
    assert(c.acceptedStep(1)==0 && c.t(1)==0 && c.canonicalTau(1)==0 && c.physicalTime(1)==0);
    assert(init.originalStep==0 && init.originalCanonicalTime==0 && init.originalPhysicalTime==0 && ...
        init.originalRemeshCount==0 && init.audit.passed && init.audit.exactZeroTime && ...
        init.audit.initialDensityExactlyResampled && init.analyticDatumResampled && ~init.newPhysicalEpochCreated);
    [trusted,trustChecks]=ipm.output.trustedMask(h,s.config);assert(trusted(1));
    first=first_row(h);
    multiplier=c.C_l(1)/c.C_omega(1);
    obs=struct('acceptedStep',c.acceptedStep(1),'physicalTime',c.physicalTime(1), ...
        'canonicalTime',c.canonicalTau(1),'normalizedTime',c.t(1), ...
        'Cx',c.C_l(1),'Cy',c.C_y(1),'Comega',c.C_omega(1),'Xshift',c.X_shift(1), ...
        'canonicalCL',c.c_l(1),'canonicalCOmega',c.c_omega(1),'canonicalCR',c.c_r(1), ...
        'dTauDPhysicalTime',multiplier,'physicalRateCL',c.c_l(1)*multiplier, ...
        'physicalRateCOmega',c.c_omega(1)*multiplier,'physicalRateCR',c.c_r(1)*multiplier, ...
        'physicalRhoXInf',c.physicalRhoXInf(1),'physicalRhoYInf',c.physicalRhoYInf(1), ...
        'physicalGradInf',c.physicalGradInf(1),'physicalQuadraticPeak',c.physicalQuadraticPeak(1), ...
        'physicalWallOmegaPeak',c.physicalWallOmegaPeak(1), ...
        'physicalTrackedPeakX',c.physicalTrackedPeakX(1), ...
        'physicalQuadraticPeakX',(h.gauge.omegaGaugeQuadraticPeakX(1)-c.X_shift(1))/c.C_l(1), ...
        'historyCoreCells',[m.coreGridPoints(1),m.verticalCoreGridPoints(1)], ...
        'physicalWallCoreWidth',m.trackedWallCoreWidth(1)/c.C_l(1), ...
        'physicalVerticalCoreWidth',m.trackedVerticalCoreWidth(1)/c.C_y(1), ...
        'safetyFactor',m.safetyFactor(1),'initialRemeshCount',m.remeshCount(1));
    assert(isequaln([c.c_l(1),c.c_omega(1)],[c.canonicalCL(1),c.canonicalCOmega(1)]));
    pre=load(item.initialScreenFile,'sourceMeasure','candidates','row');
    actualCandidate=init.selectedCandidateIndex;
    axesMatch=isequaln(init.selectedBaseX,pre.candidates(actualCandidate).x) && ...
        isequaln(init.selectedBaseY,pre.candidates(actualCandidate).y);
    assert(axesMatch,'ipm:InitialScreenMismatch','Actual selected axes differ from registered initial proposal.');
    a=struct('label',item.label,'checkpointFile',item.checkpointFile, ...
        'strictNativeSignatureValidated',true,'initialHistoryTrusted',trusted(1), ...
        'allAvailableHistoryTrusted',all(trusted),'availableHistoryRows',numel(trusted), ...
        'checkpointReadPositionNotCompared',struct('step',s.step,'canonicalTime',s.scale.canonicalTime, ...
            'physicalTime',s.scale.physicalTime,'remeshCount',s.remeshCount), ...
        'initialObservation',obs,'firstHistory',first,'initialTrustChecks',first_row(struct('checks',trustChecks)), ...
        'initialCondition',s.config.physics,'configuredBox',[s.config.grid.xlim,s.config.grid.ymax], ...
        'configuredInitialNodes',[s.config.grid.nx,s.config.grid.ny], ...
        'transport',s.config.transport,'elliptic',s.config.elliptic,'scaling',s.config.scaling, ...
        'initializationSourceAxes',axis_summary(init.sourceBaseX,init.sourceBaseY), ...
        'initializationSelectedAxes',axis_summary(init.selectedBaseX,init.selectedBaseY), ...
        'actualSelectedCandidateIndex',actualCandidate,'actualSelectedAxesMatchRegisteredProposal',axesMatch, ...
        'initialNativeAudit',init.audit,'preflightSourceObservation',pre.sourceMeasure, ...
        'preflightSourceObservationMeaning','Analytic field/paired derivative on original unselected uniform axes; no velocity or instantaneous rates were saved here.', ...
        'sourcePreselectionRatesAvailable',false, ...
        'historyMeaning','Time zero after analytic adaptive initial-axis selection, before any accepted PDE step.');
    report.cases{k}=a;
    data{k}=struct('initialization',init,'firstHistory',first,'config',s.config, ...
        'sourceMeasure',pre.sourceMeasure,'selectedCandidate',pre.candidates(actualCandidate));
end
keys={'Cx','Cy','Comega','canonicalCL','canonicalCOmega','physicalRateCL','physicalRateCOmega', ...
    'physicalRhoXInf','physicalRhoYInf','physicalGradInf','physicalQuadraticPeak', ...
    'physicalWallOmegaPeak','physicalTrackedPeakX','physicalQuadraticPeakX', ...
    'physicalWallCoreWidth','physicalVerticalCoreWidth','safetyFactor'};
report.BminusA=struct();
for k=1:numel(keys)
    key=keys{k};a=report.cases{1}.initialObservation.(key);b=report.cases{2}.initialObservation.(key);
    report.BminusA.(key)=struct('signed',b-a,'absolute',abs(b-a), ...
        'relativeToA',abs(b-a)/max(abs(a),realmin));
end
report.selectedAxesIdentical=struct('x',isequaln(data{1}.initialization.selectedBaseX,data{2}.initialization.selectedBaseX), ...
    'y',isequaln(data{1}.initialization.selectedBaseY,data{2}.initialization.selectedBaseY));
report.analyticPhysicsConfigurationExact=isequaln(data{1}.config.physics,data{2}.config.physics);
report.scalingConfigurationExact=isequaln(data{1}.config.scaling,data{2}.config.scaling);
report.transportConfigurationExact=isequaln(data{1}.config.transport,data{2}.config.transport);
report.ellipticConfigurationExact=isequaln(data{1}.config.elliptic,data{2}.config.elliptic);
profile off;profileInfo=profile('info');names={profileInfo.FunctionTable.FunctionName};
for key={'ipm.mesh.build','ipm.evolve.flow','ipm.field.velocity','ipm.field.poisson', ...
        'ipm.output.restoreCheckpoint','ipm.evolve.advance','ipm.solve','ipm.remesh.transfer'}
    assert(~any(strcmp(names,key{1})),['Forbidden call: ',key{1}]);
end
report.noLUCallGraphChecked=true;
save(fullfile(out,'report.mat'),'report','data','profileInfo','-v7.3');
fid=fopen(fullfile(out,'report.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
disp(jsonencode(report.BminusA));
end

function first=first_row(h)
first=struct();
for g=fieldnames(h)'
    key=g{1};first.(key)=struct();
    for f=fieldnames(h.(key))'
        name=f{1};value=h.(key).(name);
        if isempty(value),first.(key).(name)=value;
        elseif iscell(value),first.(key).(name)=value(1);
        else,first.(key).(name)=value(1);end
    end
end
end

function a=axis_summary(x,y)
dx=diff(x);dy=diff(y);xm=(x(1:end-1)+x(2:end))/2;ym=(y(1:end-1)+y(2:end))/2;
a=struct('nodes',[numel(x),numel(y)],'box',[x(1),x(end),y(end)], ...
    'minimumSpacing',[min(dx),min(dy)],'maximumSpacing',[max(dx),max(dy)], ...
    'innerXMinimumSpacing',min(dx(xm>=.8 & xm<=1.8)), ...
    'innerXMaximumSpacing',max(dx(xm>=.8 & xm<=1.8)), ...
    'innerYMinimumSpacing',min(dy(ym>=0 & ym<=1)), ...
    'innerYMaximumSpacing',max(dy(ym>=0 & ym<=1)), ...
    'exactAnchorXOne',any(x==1),'exactAnchorXMinusOne',any(x==-1));
end
