function report = ipm_accellab_probe_c1_checkpoint(checkpointFile,outputRoot)
%IPM_ACCELLAB_PROBE_C1_CHECKPOINT One strict restore, instantaneous research.
% Use only in an explicitly scheduled q512 resource window. The restore
% already evaluates the fresh original Poisson/RHS; its exact cache is used.
directory = fileparts(mfilename('fullpath')); addpath(directory,fileparts(fileparts(directory)));
assert(maxNumCompThreads == 10,'ipm:C1NativeThreads','Strict native checkpoint signatures require ten threads.');
[~,token] = fileparts(tempname); destination = fullfile(outputRoot,['hermite_peak_q512_',token]);
mkdir(destination);
registration = struct('sourceCheckpoint',checkpointFile,'outputDirectory',destination, ...
    'researchEquationId','independent_hermite_C1_peak_amplitude_fixed_window_v1', ...
    'threads',10,'restoreCalls',1,'originalRhsInsideRestore',1,'extraPoissonRhsAfterRestore',0, ...
    'extraIndependentTransportAssemblies',1,'timeSteps',0,'nativeCheckpointsWritten',0, ...
    'operatorBuildCount','restore may first build configured axes then saved remeshed axes; not instrumented', ...
    'primaryPeakWindowRule','fixed positive half of the current grid: [0,x(end)]', ...
    'usesFeedback',false,'usesPeakProjection',false);
save(fullfile(destination,'registration.mat'),'registration'); write_json(fullfile(destination,'registration.json'),registration);
diary(fullfile(destination,'runtime.log')); diaryCleanup = onCleanup(@()diary('off'));
started = tic;
try
    checkpoint = ipm.output.readCheckpoint(checkpointFile);
    sourceStep = checkpoint.payload.state.step;
    state = ipm.output.restoreCheckpoint(checkpoint,struct('saveResults',false, ...
        'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false));
    clear checkpoint;
    s = state.config.scaling; ops = state.ops;
    assert(state.config.schemaVersion == 4 && state.config.frozen && ...
        strcmp(s.scalingContract,'exact_gauge_no_feedback_v1') && ...
        strcmp(s.rescalingMode,'dynamic') && strcmp(s.dynamicScaleGeometry,'isotropic') && ...
        strcmp(s.cOmegaGauge,'wall_omega_quadratic_peak') && strcmp(s.lengthGauge,'transport_anchor') && ...
        s.transportAnchorX == 1 && s.lengthScaleGain == 1 && s.widthGaugeGain == 0 && ...
        s.omegaGaugeGain == 0 && s.travelingWaveGain == 0 && ...
        strcmp(ops.symmetryMode,'double_odd_omega') && strcmp(ops.transportBoundaryMode,'open'), ...
        'ipm:C1CheckpointContract','The original exact isotropic symmetric anchor contract is required.');
    assert(isequaln(state.rhsCache.rho,state.rho) && isequaln(state.rhsCache.scale,state.scale), ...
        'ipm:C1RestoredCache','Fresh native RHS cache must match the restored field and full scale.');
    originalRhs = state.rhsCache.rhoRate; flow = state.flow;
    baseRhs = ipm.evolve.assembleRhs(state.rho,flow.u1,flow.u2, ...
        flow.c_l,flow.c_l,0,flow.c_r,ops,ops.transportBoundaryMode);
    assert(flow.c_r == 0 && isequaln(originalRhs,baseRhs+flow.c_omega*state.rho), ...
        'ipm:C1IndependentBase','Independently assembled base RHS does not reproduce the native full RHS bitwise.');
    x = ops.x; omega = flow.source(1,:); originalForcing = originalRhs(1,:)*ops.Dx';
    baseForcing = baseRhs(1,:)*ops.Dx'; window = [0,x(end)];
    observed = ipm_accellab_hermite_peak(omega,originalForcing,x,ops.Dx,window);
    legacy = ipm_accellab_hermite_peak_window_scaled_v0(omega,originalForcing,x,ops.Dx,window);
    algebra = ipm_accellab_hermite_amplitude(omega,baseForcing,x,ops.Dx,window);
    trackingWindow = [max(0,ops.rescaling.pinX-ops.rescaling.peakTrackingHalfWidth), ...
        min(x(end),ops.rescaling.pinX+ops.rescaling.peakTrackingHalfWidth)];
    tracking = ipm_accellab_hermite_peak(omega,originalForcing,x,ops.Dx,trackingWindow);
    proposed = struct(); proposedForcing = [];
    if algebra.valid
        proposedRhs = baseRhs+algebra.cOmega*state.rho;
        proposedForcing = proposedRhs(1,:)*ops.Dx';
        actualPeak = ipm_accellab_hermite_peak(omega,proposedForcing,x,ops.Dx,window);
        relativeRhsChange = norm(proposedRhs(:)-originalRhs(:))/max(norm(originalRhs(:)),realmin);
        proposed = struct('actualFullRhsPeak',actualPeak,'cOmega',algebra.cOmega, ...
            'cOmegaMinusNative',algebra.cOmega-flow.c_omega,'fullRhsRelativeL2Change',relativeRhsChange, ...
            'wallDerivativeLinearSplitError',max(abs(proposedForcing-baseForcing-algebra.cOmega*omega)), ...
            'isTimeIntegrated',false,'isAcceptedTrajectory',false);
    end
    report = struct('status','completed_instantaneous_research','registration',registration, ...
        'signatureValidated',true,'step',sourceStep,'canonicalTime',state.scale.canonicalTime, ...
        'physicalTime',state.scale.physicalTime,'gridSize',size(state.rho),'remeshCount',ops.remeshCount, ...
        'xlim',[x(1),x(end)],'ymax',ops.y(end),'nativeCL',flow.c_l,'nativeCOmega',flow.c_omega, ...
        'nativeQuadraticP',flow.omegaGaugeQuadraticPeakValue, ...
        'nativeQuadraticPPrime',flow.omegaGaugeQuadraticForcing+flow.c_omega*flow.omegaGaugeQuadraticPeakValue, ...
        'nativeQuadraticPeakX',flow.omegaGaugeQuadraticPeakX, ...
        'currentHermitePeakOnOriginalRhs',observed,'legacyWindowScaledHermitePeak',legacy, ...
        'independentAmplitudeAlgebra',algebra,'proposedInstantaneousRhs',proposed, ...
        'trackingWindowObserver',tracking,'globalAndTrackingSamePeak', ...
        observed.valid && tracking.valid && abs(observed.x-tracking.x) <= max(observed.activePositionTolerance,tracking.activePositionTolerance), ...
        'independentBaseIdentityBitwise',true,'poissonResidual',flow.poissonResidual, ...
        'poissonSolveInfo',flow.poissonSolveInfo,'elapsedSeconds',toc(started), ...
        'interpretation','Instantaneous evaluation of a new research maximum functional and algebraic rate. No trajectory, production schema, physical singularity or finite-time conservation is certified.');
    if ~algebra.valid, report.status = 'rejected_instantaneous_peak'; end
    save(fullfile(destination,'wall_fields.mat'),'x','omega','originalForcing','baseForcing','proposedForcing');
    clear state ops flow baseRhs originalRhs proposedRhs;
    save(fullfile(destination,'report.mat'),'report'); write_json(fullfile(destination,'report.json'),report);
catch exception
    failure = struct('registration',registration,'identifier',exception.identifier,'message',exception.message, ...
        'elapsedSeconds',toc(started));
    save(fullfile(destination,'failure.mat'),'failure'); write_json(fullfile(destination,'failure.json'),failure); rethrow(exception);
end
fprintf('HERMITE_PEAK_Q512_RELEASED %s\n',destination);
clear diaryCleanup;
end

function write_json(file,value)
fid = fopen(file,'w'); assert(fid >= 0); cleanup = onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,'PrettyPrint',true));
end
