function report = ipm_accellab_analyze_peak_switch(frameFile,outputRoot)
%IPM_ACCELLAB_ANALYZE_PEAK_SWITCH Field-only research on native tiny frames.
% No checkpoint restore, Poisson operator, fresh RHS or time evolution.
directory = fileparts(mfilename('fullpath')); addpath(directory,fileparts(fileparts(directory)));
[~,token] = fileparts(tempname); destination = fullfile(outputRoot,['hermite_peak_switch_',token]);
mkdir(destination);
registration = struct('sourceFrameFile',frameFile,'outputDirectory',destination, ...
    'fixedWindowRule','positive half of the saved domain, [0,x(end)]', ...
    'pathOffsets',[1e-2,1e-4,1e-6,1e-8], ...
    'scope','Independent field-only peak functional; no new PDE trajectory or production gauge change.');
save(fullfile(destination,'registration.mat'),'registration');
try
    data = load(frameFile,'frames','Dx','Dy','config','evidence');
    assert(data.evidence.terminalRhoBitwise && data.evidence.historyBitwise && data.evidence.allTrusted, ...
        'ipm:HermitePeakNativeReplay','Source must include the verified native replay evidence.');
    x = data.frames{1}.x(:)'; y = data.frames{1}.y(:);
    assert(numel(x) <= 65 && numel(y) <= 65 && x(1) < 0 && x(end) > 0, ...
        'ipm:HermitePeakTinyDomain','Only the registered tiny positive-half-domain study is allowed.');
    assert(isequal(data.Dx,ipm.mesh.fdMatrix(x,1,7)) && isequal(data.Dy,ipm.mesh.fdMatrix(y,1,7)), ...
        'ipm:HermitePeakMaintainedDx','Saved derivatives do not equal the maintained seven-point operators.');
    window = [0,x(end)]; entries = cell(size(data.frames));
    for k = 1:numel(data.frames)
        f = data.frames{k};
        assert(all(isfield(f,{'rhoX','physicalRhs','baseRhs','rhs'})) && ...
            isequal(f.x(:)',x) && isequal(f.y(:),y), ...
            'ipm:HermitePeakFrameFields','Missing independently assembled v2 RHS fields or differing grids.');
        assert(isequaln(f.rhs,f.baseRhs+f.cOmega*f.rho) && isequaln(f.rhoX,f.rho*data.Dx'), ...
            'ipm:HermitePeakSourceIdentity','Maintained full/base RHS or saved rhoX identity failed.');
        fullFX = f.rhs*data.Dx'; baseFX = f.baseRhs*data.Dx'; physicalFX = f.physicalRhs*data.Dx';
        omega = f.rhoX(1,:);
        observed = ipm_accellab_hermite_peak(omega,fullFX(1,:),x,data.Dx,window);
        algebra = ipm_accellab_hermite_amplitude(omega,baseFX(1,:),x,data.Dx,window);
        assert(observed.valid && algebra.valid,'ipm:HermitePeakRealValidity','Tiny native frame peak invalid.');
        proposedRhs = f.baseRhs+algebra.cOmega*f.rho;
        proposedFX = proposedRhs*data.Dx';
        actualCancellation = ipm_accellab_hermite_peak(omega,proposedFX(1,:),x,data.Dx,window);
        physicalPeak = ipm_accellab_hermite_peak(omega,physicalFX(1,:),x,data.Dx,window);
        splitError = max(abs(proposedFX-baseFX-algebra.cOmega*f.rhoX),[],'all');
        [~,j] = max(omega); quadratic = ipm.evolve.quadraticPeakFunctional(omega,x,j);
        oldDirectPPrime = sum(quadratic.weights.*fullFX(1,quadratic.indices));
        assert(abs(quadratic.value-f.P) < 1e-13 && ...
            abs(actualCancellation.PPrime) < 1e-11, ...
            'ipm:HermitePeakInstantCancellation','Stored old peak or proposed instantaneous cancellation failed.');
        entries{k} = struct('canonicalTime',f.canonicalTime,'oldCenter',f.center, ...
            'oldQuadraticP',f.P,'oldStoredPPrime',f.PPrime,'oldDirectPPrime',oldDirectPPrime, ...
            'oldCOmega',f.cOmega,'oldCL',f.flow.c_l,'oldCR',f.flow.c_r, ...
            'continuousPeakOnOriginalRhs',observed,'newAlgebraicRate',algebra, ...
            'physicalRhsPeak',physicalPeak,'actualFullRhsCancellation',actualCancellation, ...
            'fullDerivativeLinearSplitError',splitError, ...
            'sourceFullBaseIdentityBitwise',true,'sourceRhoXIdentityBitwise',true);
    end
    first = data.frames{1}; second = data.frames{2};
    v0 = first.rhoX(1,:); v1 = second.rhoX(1,:); vf = v1-v0;
    [~,j0] = max(v0); [~,j1] = max(v1);
    assert(j0 ~= j1,'ipm:HermitePeakPathSwitch','The first two source frames do not straddle a selector change.');
    g0 = v0(j0)-v0(j1); g1 = v1(j0)-v1(j1);
    lambda = g0/(g0-g1); offsets = registration.pathOffsets;
    assert(lambda > max(offsets) && lambda < 1-max(offsets), ...
        'ipm:HermitePeakPathBracket','Prescribed symmetric path offsets are not inside the saved-frame interval.');
    path = cell(size(offsets));
    central = ipm_accellab_hermite_peak(v0+lambda*vf,vf,x,data.Dx,window);
    for k = 1:numel(offsets)
        e = offsets(k); minus = v0+(lambda-e)*vf; plus = v0+(lambda+e)*vf;
        [~,jm] = max(minus); [~,jp] = max(plus);
        qm = ipm.evolve.quadraticPeakFunctional(minus,x,jm);
        qp = ipm.evolve.quadraticPeakFunctional(plus,x,jp);
        hm = ipm_accellab_hermite_peak(minus,vf,x,data.Dx,window);
        hp = ipm_accellab_hermite_peak(plus,vf,x,data.Dx,window);
        assert(jm == j0 && jp == j1 && hm.valid && hp.valid);
        path{k} = struct('offset',e,'minusLambda',lambda-e,'plusLambda',lambda+e, ...
            'minusOldCenter',x(jm),'plusOldCenter',x(jp), ...
            'oldQuadraticDifference',qp.value-qm.value, ...
            'hermiteDifference',hp.value-hm.value, ...
            'hermitePeakPositionDifference',hp.x-hm.x, ...
            'hermitePathDerivativeDifference',hp.PPrime-hm.PPrime, ...
            'hermiteCentralDerivativeError',abs((hp.value-hm.value)/(2*e)-central.PPrime), ...
            'minusHermitePeak',hm,'plusHermitePeak',hp);
    end
    assert(abs(path{end}.hermiteDifference) < abs(path{1}.hermiteDifference)/1e4 && ...
        abs(path{end}.oldQuadraticDifference) > 0.5*abs(path{1}.oldQuadraticDifference), ...
        'ipm:HermitePeakSelectorContinuity','The fixed field-path continuity comparison failed.');
    times = cellfun(@(e)e.canonicalTime,entries);
    hermiteP = cellfun(@(e)e.continuousPeakOnOriginalRhs.value,entries);
    hermitePPrime = cellfun(@(e)e.continuousPeakOnOriginalRhs.PPrime,entries);
    finiteDifferences = diff(hermiteP)./diff(times);
    meanEndpointDerivative = (hermitePPrime(1:end-1)+hermitePPrime(2:end))/2;
    report = struct('status','passed_field_only','registration',registration, ...
        'sourceEvidence',data.evidence,'entries',{entries},'fixedWindow',window, ...
        'linearFieldPath',struct('lambdaAtNodeTie',lambda,'fromFrame',1,'toFrame',2, ...
        'atTiePeak',central,'symmetricOffsetComparisons',{path}, ...
        'interpretation','Offline linear interpolation of saved wall Omega, with its prescribed lambda derivative. This is not a new PDE trajectory.'), ...
        'originalTrajectory',struct('times',times,'hermiteP',hermiteP,'hermitePPrime',hermitePPrime, ...
        'intervalPeakSlopes',finiteDifferences,'meanEndpointPPrime',meanEndpointDerivative, ...
        'slopeMinusEndpointMean',finiteDifferences-meanEndpointDerivative, ...
        'interpretation','The original quadratic-gauge trajectory need not conserve the new Hermite observable.'), ...
        'newRhsEvaluations',0,'newPdeSteps',0,'poissonOperatorBuilds',0,'isProductionGauge',false, ...
        'interpretation','A pure algebraic research rate and continuous field observable. No finite-step conservation, improved trajectory or singularity conclusion is asserted.');
    save(fullfile(destination,'report.mat'),'report');
    fid = fopen(fullfile(destination,'report.json'),'w'); cleanup = onCleanup(@()fclose(fid));
    fprintf(fid,'%s\n',jsonencode(report,'PrettyPrint',true)); clear cleanup;
catch exception
    failure = struct('status','failed','registration',registration, ...
        'identifier',exception.identifier,'message',exception.message);
    save(fullfile(destination,'failure.mat'),'failure');
    fprintf('HERMITE_PEAK_SWITCH_FAILED %s\n',destination); rethrow(exception);
end
fprintf('HERMITE_PEAK_SWITCH %s\n',destination);
end
