function report=ipm_accellab_run_tiny_shadow(mode,outputDirectory,baselineDirectory)
%IPM_ACCELLAB_RUN_TINY_SHADOW Run only the registered 49/65 original IPM IVPs.
assert(maxNumCompThreads==10 && ~isfolder(outputDirectory));mkdir(outputDirectory);
report=struct('kind','tiny_original_IPM_recycle_shadow_v1','mode',mode, ...
    'candidateUses',0,'maximumNodes',[65,33],'maximumInteriorUnknowns',1985, ...
    'maxStepsPerGrid',80,'canonicalEndpoint',.08,'maxDt',.001, ...
    'windows',[0,.032;.032,.08],'maximumAttemptsPerWindow',20, ...
    'memory',4,'stopPredictionsAtFirstFailedAttempt',true, ...
    'allOriginalLUSolvesRetained',true,'integrationApproved',false,'cases',{{}});
write_json(fullfile(outputDirectory,'registration.json'),report);
for nx=[49,65]
    ny=(nx+1)/2;dir=fullfile(outputDirectory,sprintf('n%d',nx));mkdir(dir);
    opts=tiny_options(nx,ny);
    if strcmp(mode,'shadow'),ipm_accellab_shadow_tap('reset',dir);end
    timer=tic;result=ipm.solve(opts);wallSeconds=toc(timer);
    if strcmp(mode,'shadow'),shadow=ipm_accellab_shadow_tap('finish');else,shadow=[];end
    save(fullfile(dir,'result.mat'),'result','-v7.3');
    [trusted,checks]=ipm.output.trustedMask(result);
    a=struct('nodes',[nx,ny],'step',result.state.steps,'canonicalTime',result.state.canonicalTime, ...
        'stopReason',result.state.stopReason,'allHistoryTrusted',all(trusted), ...
        'trustChecks',checks,'wallSeconds',wallSeconds,'shadow',shadow);
    assert(result.state.steps==80 && abs(result.state.canonicalTime-.08)<1e-14 && all(trusted));
    if strcmp(mode,'shadow')
        old=load(fullfile(baselineDirectory,sprintf('n%d',nx),'result.mat'),'result');
        groups={'state','scale','physical','history','snapshots','grid','quality','elliptic'};
        a.parity=struct();
        for k=1:numel(groups)
            key=groups{k};a.parity.(key)=isequaln(old.result.(key),result.(key));
        end
        a.allNumericalGroupsExact=all(structfun(@(v)v,a.parity));
        assert(a.allNumericalGroupsExact,'ipm:ShadowChangedTrajectory','Instrumentation changed the original trajectory.');
    end
    save(fullfile(dir,'report.mat'),'a','-v7.3');
    write_json(fullfile(dir,'report.json'),a);report.cases{end+1}=a;
    fprintf('SHADOW_CASE mode=%s nx=%d steps=%d trusted=%d seconds=%.4f\n',mode,nx,a.step,a.allHistoryTrusted,wallSeconds);
end
save(fullfile(outputDirectory,'report.mat'),'report','-v7.3');
write_json(fullfile(outputDirectory,'report.json'),report);
end

function opts=tiny_options(nx,ny)
opts=struct('nx',nx,'ny',ny,'xlim',[-4,4],'ymax',4, ...
    'gridMode','uniform','gridStretchAutomatic',false,'gridStretch',[0,0], ...
    'initialCondition',@(X,Y)-exp(-X.^2-Y.^2),'rescalingMode','dynamic', ...
    'symmetryMode','double_odd_omega','spatialDiscretization','high_order', ...
    'transportScheme','weno5_fd','timeIntegrator','ssprk54', ...
    'remeshTransferScheme','high_order','farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','open','wallTransportMode','advective_upwind', ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'saveResults',false,'makePlots',false,'livePlot',false,'writeVideo',false, ...
    'verbose',false,'storeSnapshots',true,'cfl',.5,'maxDt',.001,'maxSteps',80, ...
    'finalTime',.08,'physicalFinalTime',Inf,'outputEvery',.001, ...
    'rangeStopTolerance',.1,'minimumPeakPoints',2,'minimumLevelPoints',[2,2,2], ...
    'positiveWallNegativeTolerance',.99,'oscillationTVTolerance',10, ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','wall_omega_quadratic_peak');
end

function write_json(file,value)
fid=fopen(file,'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(value,PrettyPrint=true));
end
