function report = ipm_accellab_test()
%IPM_ACCELLAB_TEST Bounded slow-mode and unchanged-IPM-RHS checks.
directory = fileparts(mfilename('fullpath'));
addpath(directory,fileparts(fileparts(directory)));

root = [10;20];
factors = [0.9999;0.91];
historyStride = 100;
history = root+[1;0.3].*factors.^(0:historyStride:5*historyStride);
evaluate = @(x)linear_residual(x,root,factors);
[candidate,linear] = ipm_accellab_secant(history,evaluate, ...
    struct('regularization',0,'svdRelativeFloor',1e-12));
assert(linear.accepted && norm(candidate-root) < 1e-7 && ...
    linear.residualRatio < 1e-7,'ipm:AccelTestSlowModes', ...
    'Resolved slow linear modes were not eliminated.');
ordinaryIterationsForMillionFold = ceil(log(1e-6)/log(max(factors)));

[duplicate,rankGuard] = ipm_accellab_secant(repmat(root+1,1,3),evaluate);
assert(~rankGuard.accepted && ...
    strcmp(rankGuard.status,'no_resolved_secant_direction') && ...
    isequal(duplicate,root+1),'ipm:AccelTestRankGuard', ...
    'Duplicate history changed the baseline.');

[rejected,freshGuard] = ipm_accellab_secant([1.1,1],@misleading_residual, ...
    struct('regularization',0,'maxRelativeJump',2));
assert(~freshGuard.accepted && rejected == 1 && ...
    all([freshGuard.attempts.residualNorm] == 100), ...
    'ipm:AccelTestFreshResidual','A predicted-only improvement was accepted.');

[rejected,projectionGuard] = ipm_accellab_secant(history,evaluate, ...
    struct('project',@(x)root+4,'maxRelativeJump',10));
assert(~projectionGuard.accepted && isequal(rejected,history(:,end)) && ...
    all([projectionGuard.attempts.residualNorm] > linear.baselineNorm), ...
    'ipm:AccelTestProjectedResidual', ...
    'The residual was not reevaluated after nonlinear projection.');

[rejected,independentGuard] = ipm_accellab_secant(history,evaluate, ...
    struct('accept',@(trial,baseline)false));
assert(~independentGuard.accepted && isequal(rejected,history(:,end)), ...
    'ipm:AccelTestIndependentGuard','Independent acceptance was bypassed.');

opts = struct('nx',65,'ny',33,'xlim',[-4,4],'ymax',4, ...
    'initialCondition','degenerate_primitive','degeneratePower',8, ...
    'symmetryMode','double_odd_omega','rescalingMode','dynamic', ...
    'lengthGauge','transport_anchor','transportAnchorX',1, ...
    'cOmegaGauge','wall_omega_quadratic_peak', ...
    'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54','remeshTransferScheme','high_order', ...
    'adaptiveRemesh',false,'maxDt',1e-4,'finalTime',1e-3, ...
    'physicalFinalTime',1e-3,'saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false,'verbose',false);
state = ipm.evolve.initialize(opts);
states = {state};
for index = 1:3
    [state,stop] = ipm.evolve.advance(state);
    assert(isempty(stop),'ipm:AccelTestTinyStep','Tiny accepted step failed.');
    states{end+1} = state; %#ok<AGROW>
end
baselineRho = state.rho;
baselineScale = state.scale;
[rho,ipmProbe] = ipm_accellab_profile_probe(states);
[trialRho,ipmTrial] = ipm_accellab_profile_probe(states,struct('secant', ...
    struct('memory',1,'maxCoefficientNorm',1e8, ...
    'damping',[0.01,0.001,0.0001])));
assert(ipmTrial.evaluations > 2 && all(isfinite(trialRho(:))), ...
    'ipm:AccelTestFreshIpMTrial', ...
    'The bounded tiny IPM trial did not reach fresh residual evaluation.');
assert(isequal(state.rho,baselineRho) && isequal(state.scale,baselineScale), ...
    'ipm:AccelTestMutation','A profile probe mutated its source state.');
assert(all(isfinite(rho(:))) && ipmProbe.baselineAudit.valid && ...
    ~ipmProbe.isTimeTrajectory,'ipm:AccelTestTinyPde', ...
    'The genuine IPM residual probe is invalid.');
if ipmProbe.accepted
    assert(abs(ipmProbe.candidateAudit.quadraticPeak/ ...
        ipmProbe.targetQuadraticPeak-1) <= ipmProbe.profileOptions.gaugeTolerance, ...
        'ipm:AccelTestExactProjection','Accepted candidate left its gauge surface.');
end
badStates = states;
badStates{1}.config.schemaVersion = 3;
assert_throws(@()ipm_accellab_profile_probe(badStates),'ipm:AccelProfileContract');
badStates = states;
badStates{1}.ops.x(2) = badStates{1}.ops.x(2)+1e-6;
assert_throws(@()ipm_accellab_profile_probe(badStates),'ipm:AccelProfileGrid');

report = struct('status','passed','syntheticSlowModeFactor',max(factors), ...
    'syntheticHistoryStride',historyStride, ...
    'ordinaryIterationsForMillionFold',ordinaryIterationsForMillionFold, ...
    'linearProbe',linear,'rankGuardPassed',true,'freshResidualGuardPassed',true, ...
    'projectionGuardPassed',true,'independentGuardPassed',true, ...
    'tinyPdeSteps',3,'tinyGrid',[65,33],'tinyIpMProbe',ipmProbe, ...
    'tinyDampedIpMTrial',ipmTrial, ...
    'legacyContractRejected',true,'mismatchedGridRejected',true, ...
    'productionPdeSteps',0,'productionAccelerationEstablished',false);
fprintf(['Acceleration lab PASS: slow factor %.4f, ordinary million-fold ' ...
    'iterations %d, secant residual ratio %.3e; tiny PDE candidate %s.\n'], ...
    max(factors),ordinaryIterationsForMillionFold,linear.residualRatio,ipmProbe.status);
end

function [residual,audit] = linear_residual(x,root,factors)
residual = (factors-1).*(x-root);
audit = struct('valid',true);
end

function [residual,audit] = misleading_residual(x)
if x < 1, residual = 100; else, residual = x; end
audit = struct('valid',true);
end

function assert_throws(callback,identifier)
try
    callback();
catch exception
    assert(strcmp(exception.identifier,identifier), ...
        'ipm:AccelTestWrongRejection','Unexpected exception: %s.',exception.identifier);
    return;
end
error('ipm:AccelTestMissingRejection','Expected rejection: %s.',identifier);
end
