function report=ipm_accellab_retain_failed_three_cache(failureFile,outputRoot)
%IPM_ACCELLAB_RETAIN_FAILED_THREE_CACHE One fixed rejected-q transport value.
% No new rate search, tolerance change, Poisson, or time integration.
directory=fileparts(mfilename('fullpath'));addpath(directory,fileparts(fileparts(directory)));
s=load(failureFile,'failure');failure=s.failure;p=failure.registration;
assert(strcmp(failure.identifier,'ipm:CachedRateLineSearch') && numel(failure.lastQ)==3);
[~,token]=fileparts(tempname);destination=fullfile(outputRoot,['three_failed_fixed_',token]);mkdir(destination);
d=load(p.cacheFile);old=load(p.observationReportFile,'report');old=old.report;
ops=d.transportOps;rho=d.rho;q=failure.lastQ;r0=old.coordinates;w=r0.wallCoreWidth;a=r0.peak.x;
cr=q(3)*w-q(1)*a;
[F,~,u1,u2]=ipm.evolve.assembleRhs(rho,d.flow.u1,d.flow.u2,q(1),q(1),q(2),cr,ops,ops.transportBoundaryMode);
FX=F*ops.Dx';rates=ipm_accellab_continuous_inner_rates(d.Omega,FX,d.x,d.y,d.Dx,d.Dy,old.localWindow);
assert(rates.valid);
constraint=[rates.peakPrime/rates.peak.value;rates.translationRate/w;rates.logScaleXRate];
reproduction=struct('bitwiseConstraint',isequal(constraint,failure.lastResidual), ...
    'maximumConstraintDifference',max(abs(constraint-failure.lastResidual)));
assert(reproduction.bitwiseConstraint,'ipm:FailedThreeFixed','The saved rejected q did not reproduce its original residual.');
[residual,details]=ipm_accellab_continuous_residual(d.Omega,FX,d.x,d.y,d.Dx,d.Dy,rates);
rx=rho*ops.Dx';ry=ops.Dy*rho;
deltaRates=[q(1)-d.flow.c_l,q(1)-d.flow.c_l,q(2)-d.flow.c_omega,cr-d.flow.c_r];
physicalChainDefect=F-d.rhoRate+deltaRates(1)*ops.X.*rx+deltaRates(2)*ops.Y.*ry- ...
    deltaRates(3)*rho+deltaRates(4)*rx;
weight=ops.integrationWeights;lambda=d.cacheAudit.lineage.canonicalCovarianceFactor;cx0=d.cacheAudit.lineage.parentCx;
comparison=struct();
for key={'coreL2','holdoutL2','fullLocalL2'}
    name=key{1};comparison.(name)=struct('baselineParent',old.residual.gauss.G.(name)/lambda, ...
        'rejectedRateParent',residual.gauss.G.(name)/lambda,'ratio',residual.gauss.G.(name)/old.residual.gauss.G.(name));
end
report=struct('status','original_rate_solve_rejected_unchanged','sourceFailureFile',failureFile, ...
    'outputDirectory',destination,'originalFailure',failure,'fixedQ',q,'originalDecisionReplaced',false, ...
    'sourceCheckpoint',d.cacheAudit.sourceCheckpoint,'sourceWallTransportMode',ops.wallTransportMode, ...
    'reproduction',reproduction,'actualConstraintResidual',constraint,'actualContinuousRates',rates, ...
    'parentRates',struct('cl',q(1)/lambda,'cw',q(2)/lambda,'cr',cx0*cr/lambda, ...
        'gamma',rates.logScaleYRate/lambda,'PPrime',rates.peakPrime/lambda^2), ...
    'residual',residual,'residualComparison',comparison, ...
    'differentialCoordinateChainDefect',struct('wholeBoxAbsoluteInf',max(abs(physicalChainDefect),[],'all'), ...
        'relativeToNativeRhsInf',max(abs(physicalChainDefect),[],'all')/max(abs(d.rhoRate),[],'all'), ...
        'relativeToNativeRhsL2',sqrt(sum(weight.*physicalChainDefect.^2,'all')/sum(weight.*d.rhoRate.^2,'all'))), ...
    'physicalNormalWallVelocityInfinity',max(abs(d.flow.u2(1,:))),'transportNormalWallVelocityInfinity',max(abs(u2(1,:))), ...
    'newTransportAssemblies',1,'newPoissonEvaluations',0,'pdeSteps',0, ...
    'interpretation','One exact fixed-q reevaluation retains the rejected solve and its genuine shape derivative. No parameter was selected again and the original 5e-11 constraint threshold is unchanged. The coordinate-chain defect compares the rejected and native RHS after removing their continuum generator difference; WENO is not asserted to commute with that transformation. No new physical-flow solve, changed-state velocity-tail gate, or physical-time validation is performed.');
save(fullfile(destination,'fixed_fields.mat'),'F','FX','physicalChainDefect','details','u1','u2','-v7.3');
save(fullfile(destination,'report.mat'),'report','-v7.3');
fid=fopen(fullfile(destination,'report.json'),'w');assert(fid>=0);cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',jsonencode(ipm_accellab_json_view(report),'PrettyPrint',true));
fprintf('THREE_FAILED_FIXED %s gammaParent=%.9g coreRatio=%.9g holdRatio=%.9g coordinateDefectInf=%.9g\n', ...
    destination,report.parentRates.gamma,comparison.coreL2.ratio,comparison.holdoutL2.ratio,report.differentialCoordinateChainDefect.relativeToNativeRhsInf);
end
