function report = probe_outer_wall_late_branch(checkpointFile,outputFile)
%PROBE_OUTER_WALL_LATE_BRANCH Tiny in-memory alternative-gauge continuation.
% The signed source checkpoint is only read. This is not a valid new-gauge
% checkpoint chain and cannot establish a long-time trajectory from t=0.
assert(maxNumCompThreads == 10);
[state,~,~] = ipm.output.restoreCheckpoint(checkpointFile,struct());
assert(strcmp(state.config.scaling.cOmegaGauge, ...
    'wall_omega_quadratic_peak'));
ops = state.ops;
ops.rescaling.cOmegaGauge = 'outer_wall_density_window_l2';
ops.rescaling.omegaGaugeWindowRadius = 0.5;
window = ipm.evolve.outerWallDensityWindow( ...
    state.rho(1,:),ops,ops.rescaling);
ops.rescaling.referenceOuterWallDensityWindowValue = window.value;
rho = state.rho;
scale = state.scale;
[~,flow] = ipm.evolve.rhs(rho,ops);
records = repmat(struct('tau',0,'cOmega',0,'windowValue',0, ...
    'pointR',0,'peakRx',0,'condition',0,'rateResidual',0),1,4);
for k = 1:4
    records(k) = row(rho,flow,ops,scale);
    if k < 4
        [rho,flow,scale] = ipm.evolve.stepSsprk54( ...
            rho,2e-5,ops,scale);
        assert(all(isfinite(rho),'all') && ...
            isfinite(flow.canonicalCOmega));
    end
end
windowDrift = abs(records(end).windowValue/records(1).windowValue-1);
pointDrift = abs(records(end).pointR/records(1).pointR-1);
assert(windowDrift < 1e-8 && pointDrift < 1e-5 && ...
    all([records.condition] > 0.1) && ...
    max(abs([records.rateResidual])) < 1e-10);
report = struct('kind','late_outer_window_in_memory_branch_v1', ...
    'sourceStep',state.step,'sourceTau',state.scale.canonicalTime, ...
    'branchSteps',3,'stepSize',2e-5, ...
    'windowRelativeDrift',windowDrift, ...
    'pointRelativeDrift',pointDrift, ...
    'peakRelativeChange',records(end).peakRx/records(1).peakRx-1, ...
    'records',records,'sourceCheckpointModified',false, ...
    'productionTrajectoryResumed',false);
fid = fopen(outputFile,'w');assert(fid >= 0);
closer = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end

function value = row(rho,flow,ops,scale)
window = ipm.evolve.outerWallDensityWindow( ...
    rho(1,:),ops,ops.rescaling);
pointR = interp1(ops.x,rho(1,:),2,'linear');
positive = ops.x > 0;
value = struct('tau',scale.canonicalTime, ...
    'cOmega',flow.canonicalCOmega, ...
    'windowValue',window.value,'pointR',pointR, ...
    'peakRx',max(flow.source(1,positive)), ...
    'condition',window.condition, ...
    'rateResidual',flow.omegaGaugeResidual);
end
