function report = run_outer_wall_auto_smoke(outputFile)
%RUN_OUTER_WALL_AUTO_SMOKE Bounded t=0 server-gauge/autonomous-mesh run.
% Does not resume, modify, or restart any production checkpoint.
assert(maxNumCompThreads == 10);
outputDirectory = fileparts(outputFile);
if ~isfolder(outputDirectory), mkdir(outputDirectory); end
opts = ipm.config.longTimeProfile(struct( ...
    'autonomousMeshVersion',5,'initialNodeCount','auto', ...
    'amplitudeGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',0.5, ...
    'canonicalFinalTime',0.01,'maximumSteps',40, ...
    'maximumTimeStep',0.001,'outputEvery',0.002, ...
    'outputDirectory',outputDirectory,'verbose',false));
opts.saveResults = false;
opts = rmfield(opts,'checkpoint');
result = ipm.solve(opts);
gauge = result.history.gauge;
windowValues = gauge.omegaGaugeWindowValue(:);
conditions = gauge.omegaGaugeWindowCondition(:);
supportPoints = gauge.omegaGaugeWindowSupportPoints(:);
rateResiduals = gauge.omegaGaugeResidual(:);
assert(result.state.steps > 0 && ...
    result.state.canonicalTime >= 0.01-1e-12 && ...
    all(isfinite(windowValues)) && all(windowValues > 0) && ...
    all(isfinite(conditions)) && min(conditions) > 1e-3 && ...
    min(supportPoints) >= 3 && ...
    all(isfinite(rateResiduals)) && max(abs(rateResiduals)) < 1e-10 && ...
    all(gauge.omegaGaugeWindowCenter == 2));
report = struct('kind','outer_wall_auto_t0_smoke_v1', ...
    'steps',result.state.steps, ...
    'canonicalTime',result.state.canonicalTime, ...
    'stopReason',result.state.stopReason, ...
    'windowRelativeDrift',max(abs(windowValues/windowValues(1)-1)), ...
    'minimumWindowCondition',min(conditions), ...
    'minimumWindowSupportPoints',min(supportPoints), ...
    'maximumGaugeResidual',max(abs(rateResiduals)), ...
    'initialNodeCount',[opts.nx,opts.ny], ...
    'autonomousMeshVersion',5,'productionCheckpointAdvanced',false);
fid = fopen(outputFile,'w');assert(fid >= 0);
closer = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
