function report=score_registered_inner_forecast(registrationDirectory,manifestFile,windowIndex,outputDirectory)
%SCORE_REGISTERED_INNER_FORECAST Score a frozen prediction on unseen CP.
% The first native accepted checkpoint in the preregistered window is used.
assert(~isfolder(outputDirectory),'ipm:InnerForecastOutputExists');
validateattributes(windowIndex,{'numeric'}, ...
    {'real','scalar','integer','>=',1,'<=',2});
saved=load(fullfile(registrationDirectory,'registration.mat'), ...
    'registration','shape');
rule=saved.registration;shapes=saved.shape;
assert(strcmp(rule.kind,'original_zero_frozen_inner_shape_forecast_v1')&& ...
    numel(shapes)==2&&numel(rule.trainingTimes)==3&& ...
    isequal(size(rule.futureCanonicalWindows),[2,2]));
window=rule.futureCanonicalWindows(windowIndex,:);
lines=splitlines(string(fileread(manifestFile)));
selected=struct();
for k=1:numel(lines)
    line=strtrim(lines(k));if strlength(line)==0,continue;end
    row=jsondecode(line);
    if row.canonicalTime>=window(1)&&row.canonicalTime<=window(2)
        selected=row;break
    end
end
assert(~isempty(fieldnames(selected)), ...
    'ipm:InnerForecastFutureMissing', ...
    'No native checkpoint has entered the preregistered window.');
cp=ipm.output.readCheckpoint(selected.checkpointFile);
state=cp.payload.state;
assert(all(ipm.output.trustedMask(cp.payload.log.history,state.config))&& ...
    state.scale.canonicalTime==selected.canonicalTime&& ...
    state.step==selected.step&& ...
    state.scale.canonicalTime>=window(1)&& ...
    state.scale.canonicalTime<=window(2));
train=load(rule.sourceProfileData,'report');
if isfield(rule,'trainingIndices'),indices=rule.trainingIndices;
else,indices=1:3;end
assert(isequal(size(indices),[1,3])&& ...
    strcmp(char(state.runMetadata.caseId), ...
    train.report.records(indices(3)).caseId));
x=state.x(:)';y=state.y(:);
Dx=ipm.mesh.fdMatrix(x,1,7);source=state.rho*Dx';
g=cp.payload.log.history.gauge;m=cp.payload.log.history.mesh;
peakX=g.omegaGaugeQuadraticPeakX(end);
peak=g.omegaGaugeQuadraticPeakValue(end);
wx=m.trackedWallCoreWidth(end);wy=m.trackedVerticalCoreWidth(end);
assert(all(isfinite([peakX,peak,wx,wy]))&&peak>0&&wx>0&&wy>0);
[~,ix]=min(abs(x-peakX));
wall=interp1((x-peakX)/wx,source(1,:)/peak,shapes{1}.axis,'pchip');
vertical=interp1(y/wy,source(:,ix)'/peak,shapes{2}.axis,'pchip');
assert(all(isfinite(wall))&&all(isfinite(vertical)));
future=state.scale.canonicalTime;
ratio=(future-rule.trainingTimes(3))/ ...
    (rule.trainingTimes(3)-rule.trainingTimes(2));
report=struct('kind','registered_inner_shape_future_score_v1', ...
    'registrationFile',fullfile(registrationDirectory,'registration.mat'), ...
    'sourceManifest',manifestFile,'futureWindowIndex',windowIndex, ...
    'futureWindow',window,'selectionRule',rule.futureSelection, ...
    'selectedCheckpoint',selected.checkpointFile, ...
    'selectedStep',state.step,'selectedTau',future, ...
    'selectedGrid',[numel(x),numel(y)], ...
    'selectedRemeshCount',state.remeshCount, ...
    'trainingTimes',rule.trainingTimes,'horizonInLastTrainingIntervals',ratio, ...
    'wall',one_score(shapes{1},wall,ratio), ...
    'vertical',one_score(shapes{2},vertical,ratio), ...
    'fullHistoryTrusted',true,'originalTrajectoryModified',false, ...
    'physicalFieldPredicted',false);
mkdir(outputDirectory);
fid=fopen(fullfile(outputDirectory,'report.json'),'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
fprintf('REGISTERED_INNER_SCORE tau=%.9f step=%d wall carry/linear/rank=%.6g/%.6g/%.6g vertical=%.6g/%.6g/%.6g\n', ...
    future,state.step,report.wall.carryForwardRelativeL2, ...
    report.wall.linearRelativeL2,report.wall.rankOneRelativeL2, ...
    report.vertical.carryForwardRelativeL2, ...
    report.vertical.linearRelativeL2,report.vertical.rankOneRelativeL2);
end

function result=one_score(rule,heldout,ratio)
last=rule.lastShape;d=rule.lastIncrement;lambda=rule.lambda;
carry=last;linear=last+ratio*d;
rankError=NaN;coefficient=NaN;
if rule.realRankOneAvailable
    if abs(lambda-1)<1e-8
        coefficient=ratio;
    else
        coefficient=lambda*(lambda^ratio-1)/(lambda-1);
    end
    rankError=relative_l2(last+coefficient*d,heldout);
end
result=struct('carryForwardRelativeL2',relative_l2(carry,heldout), ...
    'linearRelativeL2',relative_l2(linear,heldout), ...
    'rankOneRelativeL2',rankError, ...
    'rankOneValid',rule.realRankOneAvailable, ...
    'rankOneLambda',lambda,'rankOneForecastCoefficient',coefficient, ...
    'fixedAxisNodeCount',numel(rule.axis));
end

function value=relative_l2(candidate,reference)
value=sqrt(sum((candidate-reference).^2)/sum(reference.^2));
end
