function report = test_outer_wall_density_gauge(checkpointFile,outputFile)
%TEST_OUTER_WALL_DENSITY_GAUGE Bounded exact-gauge and signed-state checks.
% This is a research test: it advances one tiny t0 step, then evaluates
% the candidate RHS at a frozen late checkpoint without advancing it.
assert(maxNumCompThreads == 10);
opts = ipm.config.resolve(struct( ...
    'nx',129,'ny',65,'xlim',[-8,8],'ymax',8, ...
    'gridMode','uniform','initialCondition','degenerate_primitive', ...
    'degeneratePower',8,'symmetryMode','double_odd_omega', ...
    'rescalingMode','dynamic','lengthGauge','transport_anchor', ...
    'transportAnchorX',1,'cOmegaGauge', ...
    'outer_wall_density_window_l2','omegaGaugeWindowRadius',0.5, ...
    'spatialDiscretization','high_order','transportScheme','weno5_fd', ...
    'timeIntegrator','ssprk54','adaptiveRemesh',false, ...
    'remeshTransferScheme','high_order', ...
    'saveResults',false,'makePlots',false,'verbose',false));
ops = ipm.mesh.build(opts);
rho = ipm.field.initialDensity(ops,opts.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
[rhs,flow] = ipm.evolve.rhs(rho,ops);
window = ipm.evolve.outerWallDensityWindow(rho(1,:),ops,ops.rescaling);
B = rhs-flow.canonicalCOmega*rho;
forcing = sum(window.normalizedWeights.*rho(1,:).*B(1,:));
formulaError = abs(flow.canonicalCOmega+forcing/window.moment);
assert(formulaError < 1e-11 && ...
    abs(flow.omegaGaugeWindowRateResidual) < 1e-11 && ...
    flow.omegaGaugeWindowCenter == 2 && ...
    flow.omegaGaugeWindowCondition > 1e-3);

scale = struct('logC_l',0,'logC_omega',0, ...
    'physicalTime',0,'X_shift',0,'canonicalTime',0);
dt = 1e-5;
[rhoAfter,flowAfter,scaleAfter] = ipm.evolve.stepSsprk54(rho,dt,ops,scale);
relativeDrift = abs(flowAfter.omegaGaugeWindowValue- ...
    ops.rescaling.referenceOuterWallDensityWindowValue) / ...
    ops.rescaling.referenceOuterWallDensityWindowValue;
assert(all(isfinite(rhoAfter),'all') && relativeDrift < 1e-5);
recordState = struct('rho',rhoAfter,'flow',flowAfter, ...
    'scale',scaleAfter,'ops',ops,'config',opts, ...
    'normalizedTime',dt,'step',1, ...
    'mass0',sum(rho.*ops.integrationWeights,'all'), ...
    'rhoRange0',[min(rho,[],'all'),max(rho,[],'all')]);
[recorded,~] = ipm.output.record( ...
    ipm.output.initializeLog(),recordState);
assert(recorded.history.gauge.omegaGaugeWindowCenter(end) == 2 && ...
    recorded.history.gauge.omegaGaugeWindowMomentOrder(end) == 2 && ...
    recorded.history.gauge.omegaGaugeReferenceWindowValue(end) == ...
    ops.rescaling.referenceOuterWallDensityWindowValue);
freshOps = ipm.mesh.build(opts);
restored = ipm.output.restoreRuntimeReferences( ...
    freshOps.rescaling,ops.rescaling,ops.x,true);
assert(restored.referenceOuterWallDensityWindowValue == ...
    ops.rescaling.referenceOuterWallDensityWindowValue);
shiftedX = ops.x + 0.005*sin(pi*ops.x/8);
[shiftedRho,shiftedOps] = ipm.remesh.transfer( ...
    rho,ops,opts,struct('x',shiftedX,'y',ops.y));
[~,shiftedFlow] = ipm.evolve.rhs(shiftedRho,shiftedOps);
assert(shiftedOps.rescaling.referenceOuterWallDensityWindowValue == ...
    ops.rescaling.referenceOuterWallDensityWindowValue && ...
    shiftedFlow.omegaGaugeWindowCenter == 2 && ...
    shiftedFlow.omegaGaugeWindowSupportPoints >= 3 && ...
    isfinite(shiftedFlow.canonicalCOmega));

[state,~,~] = ipm.output.restoreCheckpoint(checkpointFile,struct());
assert(strcmp(state.config.scaling.cOmegaGauge, ...
    'wall_omega_quadratic_peak'));
lateOps = state.ops;
lateOps.rescaling.cOmegaGauge = 'outer_wall_density_window_l2';
lateOps.rescaling.omegaGaugeWindowRadius = 0.5;
lateWindow = ipm.evolve.outerWallDensityWindow( ...
    state.rho(1,:),lateOps,lateOps.rescaling);
lateOps.rescaling.referenceOuterWallDensityWindowValue = ...
    lateWindow.value;
[lateRhs,lateFlow] = ipm.evolve.rhs(state.rho,lateOps);
lateB = lateRhs-lateFlow.canonicalCOmega*state.rho;
lateForcing = sum(lateWindow.normalizedWeights.* ...
    state.rho(1,:).*lateB(1,:));
lateFormulaError = abs(lateFlow.canonicalCOmega+ ...
    lateForcing/lateWindow.moment);
assert(lateFormulaError < 1e-11 && ...
    abs(lateFlow.omegaGaugeWindowRateResidual) < 1e-11 && ...
    lateWindow.supportPoints >= 10 && ...
    abs(lateFlow.canonicalCOmega-state.flow.c_omega) > 0.2 && ...
    abs(lateFlow.canonicalCOmega-0.001495984258746363) < 1e-9);
report = struct('kind','outer_wall_density_window_l2_bounded_test_v1', ...
    'initialFormulaError',formulaError, ...
    'initialRateResidual',flow.omegaGaugeWindowRateResidual, ...
    'initialCondition',flow.omegaGaugeWindowCondition, ...
    'historyRecorded',true,'referenceRestored',true, ...
    'remeshReferencePreserved',true, ...
    'tinyStep',dt,'tinyStepRelativeWindowDrift',relativeDrift, ...
    'lateStep',state.step,'lateTau',state.scale.canonicalTime, ...
    'lateNodeCount',[numel(lateOps.x),numel(lateOps.y)], ...
    'lateWindowSupportPoints',lateWindow.supportPoints, ...
    'lateWindowCondition',lateWindow.condition, ...
    'lateOldCOmega',state.flow.c_omega, ...
    'lateNewCOmega',lateFlow.canonicalCOmega, ...
    'lateFormulaError',lateFormulaError, ...
    'lateRateResidual',lateFlow.omegaGaugeWindowRateResidual, ...
    'lateCheckpointAdvanced',false);
fid = fopen(outputFile,'w');assert(fid >= 0);
closer = onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
