function report=test_outer_c_shadow_integration(outputFile)
%TEST_OUTER_C_SHADOW_INTEGRATION Bounded new-C t=0 run with the Y observer.
assert(ischar(outputFile) && isrow(outputFile) && ~isfile(outputFile));
outputDirectory=fileparts(outputFile);
if ~isfolder(outputDirectory),mkdir(outputDirectory);end
opts=ipm.config.longTimeProfile(struct( ...
    'autonomousMeshVersion',5,'initialNodeCount','auto', ...
    'amplitudeGauge','outer_wall_density_window_l2', ...
    'omegaGaugeWindowRadius',0.5, ...
    'canonicalFinalTime',0.01,'maximumSteps',40, ...
    'maximumTimeStep',0.001,'outputEvery',0.002, ...
    'outputDirectory',outputDirectory,'verbose',false));
opts.saveResults=false;
opts=rmfield(opts,'checkpoint');
result=ipm.solve(opts);
assert(result.state.steps>0 && result.state.canonicalTime>=0.01-1e-12 && ...
    isfield(result.metadata,'continuousVerticalShadow') && ...
    ~isfield(result.metadata,'continuousVerticalShadowFailure'), ...
    'ipm:OuterCShadowIntegration', ...
    'The new-C continuous Y observer failed during actual integration.');
shadow=result.metadata.continuousVerticalShadow;
assert(shadow.observations==result.state.steps && ...
    isfinite(shadow.latest.continuousCells) && ...
    shadow.latest.continuousCells>0);
report=struct('kind','outer_c_shadow_t0_integration_v1', ...
    'steps',result.state.steps, ...
    'tau',result.state.canonicalTime, ...
    'shadowObservations',shadow.observations, ...
    'latestContinuousCoreCells',shadow.latest.continuousCells, ...
    'differentRequests',shadow.differentRequests, ...
    'productionCheckpointAdvanced',false);
fid=fopen(outputFile,'w');assert(fid>=0);
closer=onCleanup(@()fclose(fid));
fprintf(fid,'%s\n',jsonencode(report,PrettyPrint=true));
end
