function assessment = ipm_assess_fourth_order_blowup(source)
%IPM_ASSESS_FOURTH_ORDER_BLOWUP Audit one fourth-order blow-up study result.
%   Fits use the continuous trusted prefix beginning at the initial record.
%   The prefix is a local numerical-quality contract, not by itself evidence
%   of grid, time-step, box, or far-field convergence.

result = ipm.output.validate(source);
[trusted,checks] = ipm.output.trustedMask(result);
common = result.history.common;
mesh = result.history.mesh;

trustedPrefix = ipm.output.continuousTrustedPrefix(trusted);
lastTrusted = find(trustedPrefix,1,'last');
if isempty(lastTrusted)
    trustedThroughTime = NaN;
else
    trustedThroughTime = common.physicalTime(lastTrusted);
end

wallPeak = optional_series(common,'physicalTrackedWallOmegaPeak', ...
    common.physicalWallOmegaPeak);
wallWidth = optional_series(common,'physicalTrackedWallPeakWidth', ...
    common.physicalWallPeakWidth);
trustedTimes = common.physicalTime(trustedPrefix);
trustedCanonicalTau = common.canonicalTau(trustedPrefix);
gradientFit = fit_series(trustedTimes,common.physicalGradInf(trustedPrefix));
wallFit = fit_series(trustedTimes,wallPeak(trustedPrefix));
gradientGrowthRateFit = rate_fit_series( ...
    trustedTimes,common.physicalGradInf(trustedPrefix));
wallPeakGrowthRateFit = rate_fit_series( ...
    trustedTimes,wallPeak(trustedPrefix));
gradientCanonicalGrowthFit = canonical_fit_series( ...
    trustedCanonicalTau,common.physicalGradInf(trustedPrefix));
wallPeakCanonicalGrowthFit = canonical_fit_series( ...
    trustedCanonicalTau,wallPeak(trustedPrefix));
rescaledGradientCanonicalGrowthFit = canonical_fit_series( ...
    trustedCanonicalTau,common.gradInf(trustedPrefix));
rhoXCanonicalGrowthFit = canonical_fit_series( ...
    trustedCanonicalTau,common.rhoXInf(trustedPrefix));
rhoYCanonicalGrowthFit = canonical_fit_series( ...
    trustedCanonicalTau,common.rhoYInf(trustedPrefix));
scaleRatioCanonicalGrowthFit = canonical_fit_series( ...
    trustedCanonicalTau,common.C_l(trustedPrefix) ./ ...
    common.C_omega(trustedPrefix));
wallGaugeRateCheck = wall_gauge_rate_check( ...
    result,trustedPrefix,wallPeakGrowthRateFit);
canonicalWallGaugeRateCheck = canonical_wall_gauge_rate_check( ...
    result,trustedPrefix,wallPeak,wallPeakCanonicalGrowthFit);
widthFit = positive_inverse_fit(trustedTimes,wallWidth(trustedPrefix));

coreFit = empty_fit();
inverseHorizontalCoreCanonicalFit = empty_canonical_fit();
inverseVerticalCoreCanonicalFit = empty_canonical_fit();
if any(trustedPrefix) && isfield(mesh,'trackedWallCoreWidth')
    physicalCoreWidth = mesh.trackedWallCoreWidth(:)./common.C_x(:);
    coreFit = positive_inverse_fit( ...
        trustedTimes,physicalCoreWidth(trustedPrefix));
    inverseHorizontalCoreCanonicalFit = canonical_fit_series( ...
        trustedCanonicalTau,1./mesh.trackedWallCoreWidth(trustedPrefix));
end
if any(trustedPrefix) && isfield(mesh,'trackedVerticalCoreWidth')
    inverseVerticalCoreCanonicalFit = canonical_fit_series( ...
        trustedCanonicalTau,1./ ...
        mesh.trackedVerticalCoreWidth(trustedPrefix));
end

assessment = struct();
assessment.caseId = result.metadata.caseId;
assessment.sourceMetadata = result.metadata;
assessment.stopReason = result.state.stopReason;
assessment.steps = result.state.steps;
assessment.stopTime = result.state.physicalTime;
assessment.trustedThroughTime = trustedThroughTime;
assessment.trustedThroughCanonicalTau = indexed_value( ...
    common.canonicalTau,lastTrusted);
assessment.trustedRecords = nnz(trustedPrefix);
assessment.rawTrustedRecords = nnz(trusted);
assessment.totalRecords = numel(trusted);
assessment.terminalStateTrusted = trustedPrefix(end);
assessment.rawTerminalStateTrusted = trusted(end);
assessment.gradientGrowth = growth_ratio( ...
    common.physicalGradInf,lastTrusted);
assessment.wallPeakGrowth = growth_ratio(wallPeak,lastTrusted);
if any(trustedPrefix)
    assessment.minimumSafetyMargin = min( ...
        1-mesh.safetyFactor(trustedPrefix));
else
    assessment.minimumSafetyMargin = NaN;
end
assessment.finalTrustedSafety = indexed_value( ...
    mesh.safetyFactor,lastTrusted);
assessment.finalTrustedCorePoints = optional_indexed_value( ...
    mesh,'coreGridPoints',lastTrusted);
assessment.finalTrustedVerticalCorePoints = optional_indexed_value( ...
    mesh,'verticalCoreGridPoints',lastTrusted);
assessment.finalTrustedMassDrift = indexed_value( ...
    common.physicalMassDrift,lastTrusted);
assessment.finalTrustedRescaledMassDrift = indexed_value( ...
    common.massDrift,lastTrusted);
assessment.finalTrustedRangeViolation = indexed_value( ...
    common.physicalRangeViolation,lastTrusted);
assessment.finalTrustedFarVelocityRatio = indexed_value( ...
    common.farBoundaryVelocityRatio,lastTrusted);
assessment.finalTrustedFarSourceRatio = indexed_value( ...
    common.farBoundarySourceRatio,lastTrusted);
assessment.finalTrustedDivergence = indexed_value( ...
    common.divInf,lastTrusted);
assessment.finalTrustedPoissonResidual = indexed_value( ...
    common.poissonResidual,lastTrusted);
assessment.maximumCellRatioX = indexed_value( ...
    mesh.maximumCellRatioX,lastTrusted);
assessment.maximumCellRatioY = indexed_value( ...
    mesh.maximumCellRatioY,lastTrusted);
assessment.gradientFit = gradientFit;
assessment.wallPeakFit = wallFit;
assessment.gradientGrowthRateFit = gradientGrowthRateFit;
assessment.wallPeakGrowthRateFit = wallPeakGrowthRateFit;
assessment.wallGaugeRateCheck = wallGaugeRateCheck;
assessment.gradientCanonicalGrowthFit = gradientCanonicalGrowthFit;
assessment.wallPeakCanonicalGrowthFit = wallPeakCanonicalGrowthFit;
assessment.rescaledGradientCanonicalGrowthFit = ...
    rescaledGradientCanonicalGrowthFit;
assessment.rhoXCanonicalGrowthFit = rhoXCanonicalGrowthFit;
assessment.rhoYCanonicalGrowthFit = rhoYCanonicalGrowthFit;
assessment.scaleRatioCanonicalGrowthFit = scaleRatioCanonicalGrowthFit;
assessment.canonicalWallGaugeRateCheck = canonicalWallGaugeRateCheck;
assessment.canonicalRateModelAgreement = ...
    gradientCanonicalGrowthFit.modelConsensus && ...
    wallPeakCanonicalGrowthFit.modelConsensus && ...
    strcmp(gradientCanonicalGrowthFit.consensusModel, ...
    wallPeakCanonicalGrowthFit.consensusModel);
assessment.canonicalRateEvidenceSufficient = ...
    assessment.canonicalRateModelAgreement && ...
    gradientCanonicalGrowthFit.enoughDynamicRange && ...
    wallPeakCanonicalGrowthFit.enoughDynamicRange;
assessment.rateModelAgreement = gradientGrowthRateFit.modelConsensus && ...
    wallPeakGrowthRateFit.modelConsensus && ...
    strcmp(gradientGrowthRateFit.consensusModel, ...
        wallPeakGrowthRateFit.consensusModel);
assessment.rateEvidenceSufficient = assessment.rateModelAgreement && ...
    gradientGrowthRateFit.enoughDynamicRange && ...
    wallPeakGrowthRateFit.enoughDynamicRange;
assessment.inverseFwhmFit = widthFit;
assessment.inverseCoreFit = coreFit;
assessment.inverseHorizontalCoreCanonicalFit = ...
    inverseHorizontalCoreCanonicalFit;
assessment.inverseVerticalCoreCanonicalFit = ...
    inverseVerticalCoreCanonicalFit;
assessment.trustChecks = checks;
assessment.trustedPrefixMask = trustedPrefix;
assessment.rawTrustedMask = trusted;
assessment.singleRunCandidate = gradientFit.candidate || ...
    wallFit.candidate || widthFit.candidate || coreFit.candidate;
% A single result cannot establish the cross-grid, time-step, box, and
% multi-diagnostic agreement required for a credible blow-up claim.
assessment.credibleCandidate = false;
assessment.credibilityLimitations = { ...
    'Single-run fits do not establish grid/time-step/box convergence.', ...
    'The trusted prefix does not include a far-field acceptance gate.', ...
    'A credible claim requires cross-window and multi-diagnostic agreement.', ...
    sprintf(['Trusted gradient growth spans %.3f e-folds; at least three ' ...
        'are required for rate-model classification.'], ...
        gradientGrowthRateFit.eFoldCount)};

fprintf(['Local trusted prefix t=%.9g of stop t=%.9g (%s); %d/%d records, ' ...
    'gradient growth %.6g, wall growth %.6g.\n'], ...
    assessment.trustedThroughTime,assessment.stopTime, ...
    assessment.stopReason,assessment.trustedRecords, ...
    assessment.totalRecords,assessment.gradientGrowth, ...
    assessment.wallPeakGrowth);
fprintf(['At local-prefix endpoint: safety %.6g, core x/y %.6g/%.6g, ' ...
    'mass %.3e, range %.3e, far u/omega %.3e/%.3e.\n'], ...
    assessment.finalTrustedSafety,assessment.finalTrustedCorePoints, ...
    assessment.finalTrustedVerticalCorePoints, ...
    assessment.finalTrustedMassDrift, ...
    assessment.finalTrustedRangeViolation, ...
    assessment.finalTrustedFarVelocityRatio, ...
    assessment.finalTrustedFarSourceRatio);
fprintf('Single-series candidates grad/wall/FWHM/core = %d/%d/%d/%d; credible = 0.\n', ...
    assessment.gradientFit.candidate,assessment.wallPeakFit.candidate, ...
    assessment.inverseFwhmFit.candidate, ...
    assessment.inverseCoreFit.candidate);
if assessment.gradientGrowthRateFit.valid
    fprintf(['Gradient log-rate: %.6g e-folds, endpoint gamma ' ...
        '[%.6g, %.6g], model %s, enough range %d.\n'], ...
        assessment.gradientGrowthRateFit.eFoldCount, ...
        min(assessment.gradientGrowthRateFit.finalRate), ...
        max(assessment.gradientGrowthRateFit.finalRate), ...
        assessment.gradientGrowthRateFit.consensusModel, ...
        assessment.gradientGrowthRateFit.enoughDynamicRange);
end
if assessment.wallGaugeRateCheck.available
    fprintf(['Wall scale-gauge rate contribution %.6g versus numerical ' ...
        '[%.6g, %.6g], relative RMS %.3e.\n'], ...
        assessment.wallGaugeRateCheck.finalGaugeRate, ...
        min(assessment.wallGaugeRateCheck.finalNumericalRate), ...
        max(assessment.wallGaugeRateCheck.finalNumericalRate), ...
        min(assessment.wallGaugeRateCheck.relativeRmsByBandwidth));
end
if assessment.gradientCanonicalGrowthFit.valid
    fprintf(['Canonical-tau gradient/wall models %s/%s at tau %.6g; ' ...
        'endpoint rates [%.6g, %.6g]/[%.6g, %.6g].\n'], ...
        assessment.gradientCanonicalGrowthFit.consensusModel, ...
        assessment.wallPeakCanonicalGrowthFit.consensusModel, ...
        assessment.trustedThroughCanonicalTau, ...
        min(assessment.gradientCanonicalGrowthFit.finalCanonicalRate), ...
        max(assessment.gradientCanonicalGrowthFit.finalCanonicalRate), ...
        min(assessment.wallPeakCanonicalGrowthFit.finalCanonicalRate), ...
        max(assessment.wallPeakCanonicalGrowthFit.finalCanonicalRate));
end
if assessment.canonicalWallGaugeRateCheck.available
    fprintf(['Canonical wall gauge rate %.6g versus numerical ' ...
        '[%.6g, %.6g]; local tail T %.6g.\n'], ...
        assessment.canonicalWallGaugeRateCheck.finalGaugeRate, ...
        min(assessment.canonicalWallGaugeRateCheck.finalNumericalRate), ...
        max(assessment.canonicalWallGaugeRateCheck.finalNumericalRate), ...
        assessment.canonicalWallGaugeRateCheck. ...
        terminalLocalTimeEstimate);
end
end

function fit = fit_series(t,values)
if isempty(t)
    fit = empty_fit();
else
    fit = ipm.diagnostics.blowupFit(t,values);
end
end

function fit = rate_fit_series(t,values)
if numel(t) < 16 || any(~isfinite(values)) || any(values <= 0)
    fit = ipm.diagnostics.maximumGrowthRateFit([],[]);
else
    fit = ipm.diagnostics.maximumGrowthRateFit(t,values);
end
end

function fit = canonical_fit_series(canonicalTau,values)
if numel(canonicalTau) < 16 || any(~isfinite(values)) || any(values <= 0)
    fit = empty_canonical_fit();
else
    fit = ipm.diagnostics.canonicalMaximumGrowthFit( ...
        canonicalTau,values);
end
end

function check = wall_gauge_rate_check(result,trustedPrefix,rateFit)
check = struct('available',false,'physicalTime',[], ...
    'scaleGaugeRateContribution',[],'gaugeRate',[], ...
    'numericalRate',[], ...
    'relativeRmsByBandwidth',[], ...
    'finalScaleGaugeRateContribution',NaN, ...
    'finalGaugeRate',NaN,'finalNumericalRate',[]);
scaling = result.config.scaling;
required = {'canonicalCL','canonicalCOmega','C_l','C_omega'};
common = result.history.common;
if ~rateFit.valid || ...
        ~strcmp(scaling.rescalingMode,'dynamic') || ...
        ~strcmp(scaling.dynamicScaleGeometry,'isotropic') || ...
        ~strcmp(scaling.cOmegaGauge,'wall_omega_peak') || ...
        ~all(isfield(common,required))
    return;
end
time = common.physicalTime(trustedPrefix);
time = time(:);
gaugeRate = (common.canonicalCL(trustedPrefix) - ...
    common.canonicalCOmega(trustedPrefix)) .* ...
    common.C_l(trustedPrefix)./common.C_omega(trustedPrefix);
gaugeRate = gaugeRate(:);
if any(~isfinite(gaugeRate))
    return;
end
numericalRate = rateFit.logarithmicRate;
weights = trapezoid_weights(time);
relativeRms = NaN(1,size(numericalRate,2));
for index = 1:size(numericalRate,2)
    valid = isfinite(numericalRate(:,index));
    numerator = sum(weights(valid).* ...
        (numericalRate(valid,index)-gaugeRate(valid)).^2);
    denominator = sum(weights(valid).*gaugeRate(valid).^2);
    relativeRms(index) = sqrt(numerator/max(denominator,eps));
end
check.available = true;
check.physicalTime = time;
check.scaleGaugeRateContribution = gaugeRate;
check.gaugeRate = gaugeRate;
check.numericalRate = numericalRate;
check.relativeRmsByBandwidth = relativeRms;
check.finalScaleGaugeRateContribution = gaugeRate(end);
check.finalGaugeRate = gaugeRate(end);
check.finalNumericalRate = numericalRate(end,:);
end

function check = canonical_wall_gauge_rate_check( ...
        result,trustedPrefix,physicalWallPeak,rateFit)
check = struct('available',false,'canonicalTau',[], ...
    'physicalTime',[],'gaugeRate',[],'numericalRate',[], ...
    'relativeRmsByBandwidth',[],'rescaledWallPeak',[], ...
    'rescaledWallPeakRelativeDrift',NaN,'physicalClockDerivative',[], ...
    'finalGaugeRate',NaN,'finalNumericalRate',[], ...
    'terminalLocalTimeEstimate',NaN);
scaling = result.config.scaling;
required = {'canonicalTau','canonicalCL','canonicalCOmega', ...
    'C_l','C_omega','physicalTime'};
common = result.history.common;
if ~rateFit.valid || ...
        ~strcmp(scaling.rescalingMode,'dynamic') || ...
        ~strcmp(scaling.dynamicScaleGeometry,'isotropic') || ...
        ~strcmp(scaling.cOmegaGauge,'wall_omega_peak') || ...
        ~all(isfield(common,required))
    return;
end
canonicalTau = common.canonicalTau(trustedPrefix);
canonicalTau = canonicalTau(:);
gaugeRate = common.canonicalCL(trustedPrefix) - ...
    common.canonicalCOmega(trustedPrefix);
gaugeRate = gaugeRate(:);
scaleRatio = common.C_l(trustedPrefix)./common.C_omega(trustedPrefix);
scaleRatio = scaleRatio(:);
rescaledWallPeak = physicalWallPeak(trustedPrefix)./scaleRatio;
rescaledWallPeak = rescaledWallPeak(:);
physicalClockDerivative = 1./scaleRatio;
if any(~isfinite(gaugeRate)) || any(gaugeRate <= 0) || ...
        any(~isfinite(rescaledWallPeak)) || any(rescaledWallPeak <= 0)
    return;
end
numericalRate = rateFit.canonicalLogarithmicRate;
weights = trapezoid_weights(canonicalTau);
relativeRms = NaN(1,size(numericalRate,2));
for index = 1:size(numericalRate,2)
    valid = isfinite(numericalRate(:,index));
    numerator = sum(weights(valid).* ...
        (numericalRate(valid,index)-gaugeRate(valid)).^2);
    denominator = sum(weights(valid).*gaugeRate(valid).^2);
    relativeRms(index) = sqrt(numerator/max(denominator,eps));
end
physicalTime = common.physicalTime(trustedPrefix);
physicalTime = physicalTime(:);
check.available = true;
check.canonicalTau = canonicalTau;
check.physicalTime = physicalTime;
check.gaugeRate = gaugeRate;
check.numericalRate = numericalRate;
check.relativeRmsByBandwidth = relativeRms;
check.rescaledWallPeak = rescaledWallPeak;
check.rescaledWallPeakRelativeDrift = ...
    rescaledWallPeak(end)/rescaledWallPeak(1)-1;
check.physicalClockDerivative = physicalClockDerivative;
check.finalGaugeRate = gaugeRate(end);
check.finalNumericalRate = numericalRate(end,:);
check.terminalLocalTimeEstimate = physicalTime(end) + ...
    physicalClockDerivative(end)/gaugeRate(end);
end

function weights = trapezoid_weights(t)
if numel(t) <= 1
    weights = ones(size(t));
    return;
end
spacing = diff(t);
weights = [spacing(1)/2; ...
    (spacing(1:end-1)+spacing(2:end))/2;spacing(end)/2];
end

function fit = positive_inverse_fit(t,width)
valid = isfinite(width) & width > 0;
fit = ipm.diagnostics.blowupFit(t(valid),1./width(valid));
end

function ratio = growth_ratio(values,index)
if isempty(index)
    ratio = NaN;
else
    ratio = values(index)/max(abs(values(1)),eps);
end
end

function values = optional_series(source,name,fallback)
if isfield(source,name)
    values = source.(name)(:);
else
    values = fallback(:);
end
end

function value = indexed_value(values,index)
if isempty(index)
    value = NaN;
else
    value = values(index);
end
end

function value = optional_indexed_value(source,name,index)
if isfield(source,name)
    value = indexed_value(source.(name),index);
else
    value = NaN;
end
end

function fit = empty_fit()
fit = ipm.diagnostics.blowupFit([],[]);
end

function fit = empty_canonical_fit()
fit = ipm.diagnostics.canonicalMaximumGrowthFit([],[]);
end
