function assessment = ipm_assess_lattice_refinement( ...
        coarseSource,fineSource)
%IPM_ASSESS_LATTICE_REFINEMENT Conservatively audit two lattice resolutions.
%   ASSESSMENT = IPM_ASSESS_LATTICE_REFINEMENT(COARSESOURCE,FINESOURCE)
%   accepts version-2 solver-result structures or MAT-files containing a
%   variable named result.  A fourth-order assessment is accepted only when
%   it can be traced to its original result; its saved trusted-prefix mask
%   must then exactly match a fresh reconstruction from that result.
%
%   Every history used below is first restricted to
%   IPM.OUTPUT.CONTINUOUSTRUSTEDPREFIX.  Positive maxima are compared on the
%   intersection of the two trusted physical-time intervals after linear
%   interpolation of log(maximum) onto the union of both recorded time
%   grids.  LOGRMS is physical-time weighted.  Relative differences use the
%   fine-grid interpolant as the reference.
%
%   This two-grid audit deliberately cannot certify blow-up.  It records
%   whether the available numerical evidence passes strict endpoint,
%   canonical-growth, and far-boundary gates, while retaining the missing
%   half-time-step, larger-box, and third-matched-grid studies as mandatory
%   limitations.  Consequently ASSESSMENT.CREDIBLEBLOWUP is always false.

repositoryRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
coarse = read_lattice_source(coarseSource,'coarse',repositoryRoot);
fine = read_lattice_source(fineSource,'fine',repositoryRoot);

gridPair = grid_pair_summary(coarse.result,fine.result);
commonInterval = common_physical_interval(coarse,fine);
gradientAgreement = compare_positive_series( ...
    coarse.physicalTime,coarse.physicalGradient, ...
    fine.physicalTime,fine.physicalGradient,commonInterval);
wallAgreement = compare_positive_series( ...
    coarse.physicalTime,coarse.physicalWallPeak, ...
    fine.physicalTime,fine.physicalWallPeak,commonInterval);

thresholds = struct( ...
    'gradientEndpointRelativeDifference',0.01, ...
    'wallEndpointRelativeDifference',0.002, ...
    'minimumCanonicalEFolds',3, ...
    'farBoundarySourceRatio',0.01, ...
    'farBoundaryVelocityRatio',0.01);
gradientCanonical = canonical_agreement( ...
    coarse.gradientCanonicalFit,fine.gradientCanonicalFit, ...
    thresholds.minimumCanonicalEFolds);
wallCanonical = canonical_agreement( ...
    coarse.wallCanonicalFit,fine.wallCanonicalFit, ...
    thresholds.minimumCanonicalEFolds);
canonicalJointModelAgreement = ...
    gradientCanonical.sameModelAcrossGrids && ...
    wallCanonical.sameModelAcrossGrids && ...
    strcmp(gradientCanonical.consensusModel, ...
        wallCanonical.consensusModel);
canonicalJointEvidence = canonicalJointModelAgreement && ...
    gradientCanonical.passes && wallCanonical.passes;

checks = struct();
checks.fineGridIsFiner = gridPair.fineGridIsFiner;
checks.sameDomain = gridPair.sameDomain;
checks.matchedRefinementRatio = gridPair.matchedRefinementRatio;
checks.matchedMappingProvenance = gridPair.matchedMappingProvenance;
checks.strictlyNestedGrid = gridPair.strictlyNestedGrid;
checks.matchedNumericalTuple = gridPair.matchedNumericalTuple;
checks.gradientEndpointAgreement = ...
    gradientAgreement.commonEndpointRelativeDifference < ...
    thresholds.gradientEndpointRelativeDifference;
checks.wallEndpointAgreement = ...
    wallAgreement.commonEndpointRelativeDifference < ...
    thresholds.wallEndpointRelativeDifference;
checks.gradientCanonicalEvidence = gradientCanonical.passes;
checks.wallCanonicalEvidence = wallCanonical.passes;
checks.canonicalJointModelAgreement = canonicalJointModelAgreement;
checks.canonicalJointEvidence = canonicalJointEvidence;
checks.farBoundarySource = max([ ...
    coarse.farBoundary.maximumTrustedSourceRatio, ...
    fine.farBoundary.maximumTrustedSourceRatio]) < ...
    thresholds.farBoundarySourceRatio;
checks.farBoundaryVelocity = max([ ...
    coarse.farBoundary.maximumTrustedVelocityRatio, ...
    fine.farBoundary.maximumTrustedVelocityRatio]) < ...
    thresholds.farBoundaryVelocityRatio;
checks.availableNumericalEvidence = all(structfun(@(value)value,checks));

studyCoverage = struct( ...
    'halfTimeStepPairAvailable',false, ...
    'largerBoxPairAvailable',false, ...
    'thirdMatchedGridAvailable',false, ...
    'complete',false);
limitations = { ...
    ['No half-time-step pair is included, so temporal-discretization ' ...
        'error has not been separated from spatial error.'], ...
    ['No larger-box pair is included, so domain truncation and far-field ' ...
        'sensitivity have not been converged.'], ...
    ['Only two lattice resolutions are included; a third matched grid is ' ...
        'required to establish an asymptotic spatial trend.'], ...
    ['Agreement of maxima and canonical growth models is necessary but ' ...
        'does not by itself establish a singularity.']};
if ~gridPair.matchedMappingProvenance
    limitations = [{ ...
        ['The two grids do not carry identical lattice-mapping ' ...
        'provenance and therefore are not a matched refinement pair.']}, ...
        limitations];
end
if ~gridPair.strictlyNestedGrid
    limitations = [{ ...
        ['The fine-grid nodes do not strictly nest the coarse grid, so ' ...
        'mapping-shape changes remain mixed with spatial refinement.']}, ...
        limitations];
end
if ~gridPair.matchedNumericalTuple
    limitations = [{ ...
        ['The two results do not use an identical physical/numerical ' ...
        'tuple, so their difference is not a pure spatial refinement.']}, ...
        limitations];
end

assessment = struct();
assessment.schemaVersion = 2;
assessment.analysis = 'two_grid_lattice_refinement';
assessment.definition = struct( ...
    'trustedData','continuous trusted prefix reconstructed from each result', ...
    'commonTimeGrid','union of trusted record times on their intersection', ...
    'interpolation','linear interpolation of log-positive maxima', ...
    'logRms','physical-time-weighted RMS of log(coarse/fine)', ...
    'relativeDifference','abs(coarse-fine)/abs(fine)', ...
    'canonicalFitHorizon','each complete continuous trusted prefix', ...
    'farBoundaryGate','maximum ratio over each trusted prefix');
assessment.thresholds = thresholds;
assessment.gridPair = gridPair;
assessment.coarse = public_source_summary(coarse);
assessment.fine = public_source_summary(fine);
assessment.commonPhysicalInterval = commonInterval;
assessment.physicalGradientAgreement = gradientAgreement;
assessment.trackedWallPeakAgreement = wallAgreement;
assessment.canonicalGradientAgreement = gradientCanonical;
assessment.canonicalWallAgreement = wallCanonical;
assessment.checks = checks;
assessment.studyCoverage = studyCoverage;
assessment.availableNumericalEvidencePassed = ...
    checks.availableNumericalEvidence;
assessment.credibleBlowup = false;
assessment.credibilityLimitations = limitations;

print_summary(assessment);
end

function data = read_lattice_source(source,role,repositoryRoot)
[result,savedAssessment,sourceKind,sourceLabel,sourceFile] = ...
    read_payload(source,role,repositoryRoot);
result = ipm.output.validate(result);
[rawTrusted,trustChecks] = ipm.output.trustedMask(result);
trustedPrefix = ipm.output.continuousTrustedPrefix(rawTrusted);
trustedPrefix = logical(trustedPrefix(:));
if ~isempty(savedAssessment)
    validate_saved_assessment( ...
        savedAssessment,trustedPrefix,result,role);
end
if ~any(trustedPrefix)
    error('ipm:LatticeRefinementTrustedPrefix', ...
        'The %s result has an empty continuous trusted prefix.',role);
end

common = result.history.common;
mesh = result.history.mesh;
requiredCommon = {'physicalTime','canonicalTau','physicalGradInf', ...
    'physicalTrackedWallOmegaPeak','farBoundarySourceRatio', ...
    'farBoundaryVelocityRatio'};
requiredMesh = {'coreGridPoints','verticalCoreGridPoints','safetyFactor'};
require_fields(common,requiredCommon,[role,' history.common']);
require_fields(mesh,requiredMesh,[role,' history.mesh']);

physicalTime = trusted_series( ...
    common.physicalTime,trustedPrefix,[role,' physical time']);
canonicalTau = trusted_series( ...
    common.canonicalTau,trustedPrefix,[role,' canonical tau']);
physicalGradient = trusted_series( ...
    common.physicalGradInf,trustedPrefix,[role,' physical gradient']);
physicalWallPeak = trusted_series( ...
    common.physicalTrackedWallOmegaPeak,trustedPrefix, ...
    [role,' tracked physical wall peak']);
farSource = trusted_series( ...
    common.farBoundarySourceRatio,trustedPrefix, ...
    [role,' far-boundary source ratio']);
farVelocity = trusted_series( ...
    common.farBoundaryVelocityRatio,trustedPrefix, ...
    [role,' far-boundary velocity ratio']);
coreX = trusted_series( ...
    mesh.coreGridPoints,trustedPrefix,[role,' horizontal core points']);
coreY = trusted_series(mesh.verticalCoreGridPoints,trustedPrefix, ...
    [role,' vertical core points']);
safety = trusted_series( ...
    mesh.safetyFactor,trustedPrefix,[role,' safety factor']);

require_strictly_increasing(physicalTime,[role,' physical time']);
require_strictly_increasing(canonicalTau,[role,' canonical tau']);
require_positive(physicalGradient,[role,' physical gradient']);
require_positive(physicalWallPeak,[role,' tracked wall peak']);
require_nonnegative(farSource,[role,' far-boundary source ratio']);
require_nonnegative(farVelocity,[role,' far-boundary velocity ratio']);
require_positive(coreX,[role,' horizontal core points']);
require_positive(coreY,[role,' vertical core points']);
require_nonnegative(safety,[role,' safety factor']);

data = struct();
data.result = result;
data.sourceKind = sourceKind;
data.sourceLabel = sourceLabel;
data.sourceFile = sourceFile;
data.rawTrustedMask = logical(rawTrusted(:));
data.trustedPrefixMask = trustedPrefix;
data.trustChecks = trustChecks;
data.physicalTime = physicalTime;
data.canonicalTau = canonicalTau;
data.physicalGradient = physicalGradient;
data.physicalWallPeak = physicalWallPeak;
data.coreX = coreX;
data.coreY = coreY;
data.safety = safety;
data.farSource = farSource;
data.farVelocity = farVelocity;
data.farBoundary = struct( ...
    'endpointSourceRatio',farSource(end), ...
    'maximumTrustedSourceRatio',max(farSource), ...
    'endpointVelocityRatio',farVelocity(end), ...
    'maximumTrustedVelocityRatio',max(farVelocity));
data.gradientCanonicalFit = ipm.diagnostics.canonicalMaximumGrowthFit( ...
    canonicalTau,physicalGradient);
data.wallCanonicalFit = ipm.diagnostics.canonicalMaximumGrowthFit( ...
    canonicalTau,physicalWallPeak);
end

function [result,savedAssessment,sourceKind,sourceLabel,sourceFile] = ...
        read_payload(source,role,repositoryRoot)
savedAssessment = [];
sourceLabel = [role,' source'];
sourceFile = '';
if ischar(source) || (isstring(source) && isscalar(source))
    sourceFile = resolve_file(char(source),repositoryRoot);
    if isempty(sourceFile)
        error('ipm:LatticeRefinementFileMissing', ...
            'The %s MAT-file does not exist: %s.',role,char(source));
    end
    loaded = load(sourceFile);
    [~,sourceLabel] = fileparts(sourceFile);
    if isfield(loaded,'result')
        result = loaded.result;
        sourceKind = 'result file';
        return;
    elseif isfield(loaded,'assessment')
        savedAssessment = loaded.assessment;
        sourceKind = 'assessment file traced to result';
    else
        error('ipm:LatticeRefinementFileContract', ...
            ['The %s MAT-file must contain a variable named result or ' ...
            'assessment.'],role);
    end
elseif isstruct(source) && isscalar(source)
    if is_saved_assessment(source)
        savedAssessment = source;
        sourceKind = 'assessment struct traced to result';
    else
        result = source;
        sourceKind = 'result struct';
        return;
    end
else
    error('ipm:LatticeRefinementInput', ...
        ['The %s source must be a scalar result/assessment structure ' ...
        'or a MAT-file path.'],role);
end

resultFile = assessment_result_file( ...
    savedAssessment,sourceFile,repositoryRoot);
if isempty(resultFile)
    error('ipm:LatticeRefinementAssessmentTraceability', ...
        ['The %s assessment cannot be traced to an existing source ' ...
        'result. Pass the result directly or preserve ' ...
        'sourceMetadata.resultFile.'],role);
end
loadedResult = load(resultFile,'result');
if ~isfield(loadedResult,'result')
    error('ipm:LatticeRefinementAssessmentResultContract', ...
        'The associated %s MAT-file does not contain result.',role);
end
result = loadedResult.result;
end

function fileName = resolve_file(candidate,repositoryRoot)
fileName = '';
if isfile(candidate)
    fileName = candidate;
    return;
end
rootedCandidate = fullfile(repositoryRoot,candidate);
if isfile(rootedCandidate)
    fileName = rootedCandidate;
end
end

function fileName = assessment_result_file( ...
        savedAssessment,assessmentFile,repositoryRoot)
fileName = '';
if isfield(savedAssessment,'sourceMetadata') && ...
        isstruct(savedAssessment.sourceMetadata) && ...
        isscalar(savedAssessment.sourceMetadata) && ...
        isfield(savedAssessment.sourceMetadata,'resultFile')
    fileName = resolve_file( ...
        char(savedAssessment.sourceMetadata.resultFile),repositoryRoot);
    if ~isempty(fileName)
        return;
    end
end
suffix = '_assessment.mat';
if ~isempty(assessmentFile) && endsWith(assessmentFile,suffix)
    sibling = [assessmentFile(1:end-numel(suffix)),'.mat'];
    fileName = resolve_file(sibling,repositoryRoot);
end
end

function validate_saved_assessment(saved,prefix,result,role)
if ~is_saved_assessment(saved) || ~isfield(saved,'trustedPrefixMask')
    error('ipm:LatticeRefinementAssessmentContract', ...
        'The %s assessment lacks a trustedPrefixMask.',role);
end
savedPrefix = saved.trustedPrefixMask;
if ~islogical(savedPrefix) || ~isvector(savedPrefix)
    error('ipm:LatticeRefinementAssessmentPrefix', ...
        'The %s assessment trustedPrefixMask must be logical.',role);
end
savedPrefix = savedPrefix(:);
if ~isequal(savedPrefix,prefix) || ...
        ~isequal(savedPrefix,ipm.output.continuousTrustedPrefix(savedPrefix))
    error('ipm:LatticeRefinementAssessmentPrefix', ...
        ['The %s saved trusted prefix does not exactly match a fresh ' ...
        'continuous-prefix reconstruction from its result.'],role);
end
if isfield(saved,'trustedRecords') && saved.trustedRecords ~= nnz(prefix)
    error('ipm:LatticeRefinementAssessmentCount', ...
        'The %s assessment trusted-record count is inconsistent.',role);
end
if isfield(saved,'caseId') && ...
        ~strcmp(char(saved.caseId),char(result.metadata.caseId))
    error('ipm:LatticeRefinementAssessmentCase', ...
        'The %s assessment and result case IDs differ.',role);
end
end

function valid = is_saved_assessment(value)
valid = isstruct(value) && isscalar(value) && ...
    isfield(value,'trustedPrefixMask') && ...
    (isfield(value,'gradientCanonicalGrowthFit') || ...
    isfield(value,'gradientGrowthRateFit'));
end

function summary = public_source_summary(data)
last = numel(data.physicalTime);
result = data.result;
summary = struct();
summary.sourceKind = data.sourceKind;
summary.sourceLabel = data.sourceLabel;
summary.sourceFile = data.sourceFile;
summary.caseId = result.metadata.caseId;
summary.gridSize = [numel(result.grid.x),numel(result.grid.y)];
summary.stopReason = result.state.stopReason;
summary.stopPhysicalTime = result.state.physicalTime;
summary.rawTrustedRecords = nnz(data.rawTrustedMask);
summary.trustedRecords = nnz(data.trustedPrefixMask);
summary.totalRecords = numel(data.trustedPrefixMask);
summary.trustedThroughPhysicalTime = data.physicalTime(last);
summary.trustedThroughCanonicalTau = data.canonicalTau(last);
summary.trustedPrefixMask = data.trustedPrefixMask;
summary.trustChecks = data.trustChecks;
summary.endpointCorePoints = [data.coreX(last),data.coreY(last)];
summary.minimumTrustedCorePoints = [min(data.coreX),min(data.coreY)];
summary.endpointSafetyFactor = data.safety(last);
summary.maximumTrustedSafetyFactor = max(data.safety);
summary.farBoundary = data.farBoundary;
summary.gradientCanonicalFit = data.gradientCanonicalFit;
summary.wallCanonicalFit = data.wallCanonicalFit;
end

function interval = common_physical_interval(coarse,fine)
startTime = max(coarse.physicalTime(1),fine.physicalTime(1));
endTime = min(coarse.physicalTime(end),fine.physicalTime(end));
tolerance = 128*eps(max(1,max(abs([startTime,endTime]))));
if endTime-startTime <= tolerance
    error('ipm:LatticeRefinementCommonTime', ...
        'The two trusted prefixes have no nonzero common physical interval.');
end
interval = struct('start',startTime,'end',endTime, ...
    'duration',endTime-startTime);
end

function agreement = compare_positive_series( ...
        coarseTime,coarseValues,fineTime,fineValues,interval)
tolerance = 128*eps(max(1,max(abs([interval.start,interval.end]))));
coarseNodes = coarseTime(coarseTime >= interval.start-tolerance & ...
    coarseTime <= interval.end+tolerance);
fineNodes = fineTime(fineTime >= interval.start-tolerance & ...
    fineTime <= interval.end+tolerance);
commonTime = unique([interval.start;coarseNodes;fineNodes;interval.end]);
commonTime = commonTime(commonTime >= interval.start & ...
    commonTime <= interval.end);
commonTime = unique(commonTime);
if numel(commonTime) < 2
    error('ipm:LatticeRefinementCommonSamples', ...
        'At least two common physical-time samples are required.');
end

coarseLog = interp1(coarseTime,log(coarseValues),commonTime,'linear');
fineLog = interp1(fineTime,log(fineValues),commonTime,'linear');
if any(~isfinite(coarseLog)) || any(~isfinite(fineLog))
    error('ipm:LatticeRefinementInterpolation', ...
        'A trusted maximum could not be interpolated on common time.');
end
coarseInterpolated = exp(coarseLog);
fineInterpolated = exp(fineLog);
logDifference = coarseLog-fineLog;
relativeDifference = abs(coarseInterpolated-fineInterpolated) ./ ...
    abs(fineInterpolated);
weights = trapezoid_weights(commonTime);

agreement = struct();
agreement.physicalTime = commonTime;
agreement.coarseInterpolated = coarseInterpolated;
agreement.fineInterpolated = fineInterpolated;
agreement.logDifference = logDifference;
agreement.relativeDifference = relativeDifference;
agreement.logRms = sqrt(sum(weights.*logDifference.^2)/sum(weights));
agreement.maximumRelativeDifference = max(relativeDifference);
agreement.commonEndpointRelativeDifference = relativeDifference(end);
agreement.commonEndpointCoarseValue = coarseInterpolated(end);
agreement.commonEndpointFineValue = fineInterpolated(end);
end

function agreement = canonical_agreement( ...
        coarseFit,fineFit,minimumEFolds)
agreement = struct();
agreement.coarseFit = coarseFit;
agreement.fineFit = fineFit;
agreement.coarseModelConsensus = coarseFit.modelConsensus;
agreement.fineModelConsensus = fineFit.modelConsensus;
agreement.coarseConsensusModel = coarseFit.consensusModel;
agreement.fineConsensusModel = fineFit.consensusModel;
agreement.modelConsensusOnBothGrids = coarseFit.modelConsensus && ...
    fineFit.modelConsensus;
agreement.sameModelAcrossGrids = ...
    agreement.modelConsensusOnBothGrids && ...
    strcmp(coarseFit.consensusModel,fineFit.consensusModel);
agreement.consensusModel = 'none';
if agreement.sameModelAcrossGrids
    agreement.consensusModel = coarseFit.consensusModel;
end
agreement.coarseEFoldCount = coarseFit.eFoldCount;
agreement.fineEFoldCount = fineFit.eFoldCount;
agreement.minimumEFoldCount = min( ...
    coarseFit.eFoldCount,fineFit.eFoldCount);
agreement.coarseEnoughDynamicRange = coarseFit.enoughDynamicRange;
agreement.fineEnoughDynamicRange = fineFit.enoughDynamicRange;
agreement.enoughDynamicRangeOnBothGrids = ...
    coarseFit.enoughDynamicRange && fineFit.enoughDynamicRange && ...
    agreement.minimumEFoldCount >= minimumEFolds;
agreement.passes = agreement.sameModelAcrossGrids && ...
    agreement.enoughDynamicRangeOnBothGrids;
end

function summary = grid_pair_summary(coarse,fine)
coarseIntervals = [numel(coarse.grid.x)-1,numel(coarse.grid.y)-1];
fineIntervals = [numel(fine.grid.x)-1,numel(fine.grid.y)-1];
ratios = fineIntervals./coarseIntervals;
coarseDomain = [coarse.grid.x(1),coarse.grid.x(end), ...
    coarse.grid.y(1),coarse.grid.y(end)];
fineDomain = [fine.grid.x(1),fine.grid.x(end), ...
    fine.grid.y(1),fine.grid.y(end)];
domainTolerance = 256*eps(max(1,max(abs([coarseDomain,fineDomain]))));
ratioTolerance = 256*eps(max(1,max(abs(ratios))));
[coarseMapping,coarseMappingAvailable] = mapping_signature(coarse);
[fineMapping,fineMappingAvailable] = mapping_signature(fine);
[coarseNumerics,coarseNumericsAvailable] = numerical_signature(coarse);
[fineNumerics,fineNumericsAvailable] = numerical_signature(fine);

summary = struct();
summary.coarseGridSize = [numel(coarse.grid.x),numel(coarse.grid.y)];
summary.fineGridSize = [numel(fine.grid.x),numel(fine.grid.y)];
summary.coarseIntervals = coarseIntervals;
summary.fineIntervals = fineIntervals;
summary.nominalRefinementRatio = ratios;
summary.coarseDomain = coarseDomain;
summary.fineDomain = fineDomain;
summary.fineGridIsFiner = all(fineIntervals >= coarseIntervals) && ...
    any(fineIntervals > coarseIntervals);
summary.sameDomain = all(abs(coarseDomain-fineDomain) <= domainTolerance);
summary.matchedRefinementRatio = abs(ratios(1)-ratios(2)) <= ...
    ratioTolerance;
summary.mappingProvenanceAvailable = ...
    coarseMappingAvailable && fineMappingAvailable;
summary.matchedMappingProvenance = ...
    summary.mappingProvenanceAvailable && ...
    isequaln(coarseMapping,fineMapping);
summary.coarseMapping = coarseMapping;
summary.fineMapping = fineMapping;
summary.numericalTupleAvailable = ...
    coarseNumericsAvailable && fineNumericsAvailable;
summary.matchedNumericalTuple = summary.numericalTupleAvailable && ...
    isequaln(coarseNumerics,fineNumerics);
summary.coarseNumericalTuple = coarseNumerics;
summary.fineNumericalTuple = fineNumerics;
[summary.xNesting,summary.yNesting] = ...
    nesting_summary(coarse,fine,ratios);
summary.strictlyNestedGrid = summary.xNesting.passes && ...
    summary.yNesting.passes;
end

function [xSummary,ySummary] = nesting_summary(coarse,fine,ratios)
xSummary = axis_nesting_summary(coarse.grid.x,fine.grid.x,ratios(1));
ySummary = axis_nesting_summary(coarse.grid.y,fine.grid.y,ratios(2));
end

function summary = axis_nesting_summary(coarseAxis,fineAxis,ratio)
summary = struct('available',false,'refinementFactor',ratio, ...
    'maximumNodeOffset',Inf,'maximumPairedCellRelativeError',Inf, ...
    'pairedCellLogRms',Inf,'passes',false);
roundedRatio = round(ratio);
if roundedRatio < 1 || abs(ratio-roundedRatio) > ...
        256*eps(max(1,abs(ratio))) || ...
        numel(fineAxis) ~= roundedRatio*(numel(coarseAxis)-1)+1
    return
end
coarseAxis = coarseAxis(:);
fineAxis = fineAxis(:);
sampledFine = fineAxis(1:roundedRatio:end);
coarseWidths = diff(coarseAxis);
fineWidths = diff(fineAxis);
pairedWidths = sum(reshape(fineWidths,roundedRatio,[]),1)';
nodeOffset = abs(sampledFine-coarseAxis);
relativeCellError = abs(pairedWidths-coarseWidths)./coarseWidths;
logCellError = log(pairedWidths./coarseWidths);
domainScale = max(1,abs(coarseAxis(end)-coarseAxis(1)));
absoluteTolerance = 1e-12*domainScale;
relativeTolerance = 1e-11;
summary.available = true;
summary.refinementFactor = roundedRatio;
summary.maximumNodeOffset = max(nodeOffset);
summary.maximumPairedCellRelativeError = max(relativeCellError);
summary.pairedCellLogRms = sqrt(mean(logCellError.^2));
summary.absoluteTolerance = absoluteTolerance;
summary.relativeTolerance = relativeTolerance;
summary.passes = summary.maximumNodeOffset <= absoluteTolerance && ...
    summary.maximumPairedCellRelativeError <= relativeTolerance;
end

function [signature,available] = mapping_signature(result)
signature = struct();
available = false;
if ~isfield(result,'metadata') || ...
        ~isfield(result.metadata,'caseMetadata') || ...
        ~isstruct(result.metadata.caseMetadata) || ...
        ~isfield(result.metadata.caseMetadata,'smoothGrid')
    return
end
grid = result.metadata.caseMetadata.smoothGrid;
required = {'profile','mappingKind','monitorCoordinate','mappingVersion', ...
    'strength','width','peakCenter','profileParameters'};
if ~isstruct(grid) || ~isscalar(grid) || ~all(isfield(grid,required))
    return
end
for index = 1:numel(required)
    name = required{index};
    signature.(name) = grid.(name);
end
available = true;
end

function [signature,available] = numerical_signature(result)
signature = struct();
available = false;
paths = { ...
    'transport','spatialDiscretization'; ...
    'transport','transportScheme'; ...
    'time','timeIntegrator'; ...
    'time','cfl'; ...
    'time','maxDt'; ...
    'remesh','remeshTransferScheme'; ...
    'remesh','initialAnalyticRemesh'; ...
    'remesh','adaptiveRemesh'; ...
    'physics','initialCondition'; ...
    'physics','degeneratePower'; ...
    'physics','symmetryMode'; ...
    'elliptic','farBoundaryMode'; ...
    'elliptic','greenSourceTolerance'; ...
    'elliptic','greenMaxSources'; ...
    'transport','transportBoundaryMode'; ...
    'scaling','rescalingMode'; ...
    'scaling','dynamicScaleGeometry'; ...
    'scaling','cOmegaGauge'; ...
    'scaling','lengthGauge'};
if ~isfield(result,'config')
    return
end
for index = 1:size(paths,1)
    domain = paths{index,1};
    name = paths{index,2};
    if ~isfield(result.config,domain) || ...
            ~isfield(result.config.(domain),name)
        signature = struct();
        return
    end
    signature.(name) = result.config.(domain).(name);
end
available = true;
end

function print_summary(assessment)
coarse = assessment.coarse;
fine = assessment.fine;
gradient = assessment.physicalGradientAgreement;
wall = assessment.trackedWallPeakAgreement;
fprintf(['Lattice refinement %dx%d -> %dx%d; common trusted physical ' ...
    'time [%.9g, %.9g].\n'], ...
    assessment.gridPair.coarseGridSize(1), ...
    assessment.gridPair.coarseGridSize(2), ...
    assessment.gridPair.fineGridSize(1), ...
    assessment.gridPair.fineGridSize(2), ...
    assessment.commonPhysicalInterval.start, ...
    assessment.commonPhysicalInterval.end);
fprintf(['Grid domain/refinement/mapping/nesting/numerics match = ' ...
    '%d/%d/%d/%d/%d.\n'], ...
    assessment.gridPair.sameDomain, ...
    assessment.gridPair.matchedRefinementRatio, ...
    assessment.gridPair.matchedMappingProvenance, ...
    assessment.gridPair.strictlyNestedGrid, ...
    assessment.gridPair.matchedNumericalTuple);
fprintf(['Trusted endpoints t/tau coarse %.9g/%.9g, fine %.9g/%.9g; ' ...
    'core x/y %.6g/%.6g and %.6g/%.6g; safety %.6g and %.6g.\n'], ...
    coarse.trustedThroughPhysicalTime,coarse.trustedThroughCanonicalTau, ...
    fine.trustedThroughPhysicalTime,fine.trustedThroughCanonicalTau, ...
    coarse.endpointCorePoints(1),coarse.endpointCorePoints(2), ...
    fine.endpointCorePoints(1),fine.endpointCorePoints(2), ...
    coarse.endpointSafetyFactor,fine.endpointSafetyFactor);
fprintf(['Gradient log-RMS %.3e, max relative %.3e, endpoint relative ' ...
    '%.3e (threshold %.3e).\n'],gradient.logRms, ...
    gradient.maximumRelativeDifference, ...
    gradient.commonEndpointRelativeDifference, ...
    assessment.thresholds.gradientEndpointRelativeDifference);
fprintf(['Tracked-wall log-RMS %.3e, max relative %.3e, endpoint relative ' ...
    '%.3e (threshold %.3e).\n'],wall.logRms, ...
    wall.maximumRelativeDifference,wall.commonEndpointRelativeDifference, ...
    assessment.thresholds.wallEndpointRelativeDifference);
fprintf(['Canonical gradient models %s/%s, e-folds %.6g/%.6g; wall ' ...
    'models %s/%s, e-folds %.6g/%.6g.\n'], ...
    assessment.canonicalGradientAgreement.coarseConsensusModel, ...
    assessment.canonicalGradientAgreement.fineConsensusModel, ...
    assessment.canonicalGradientAgreement.coarseEFoldCount, ...
    assessment.canonicalGradientAgreement.fineEFoldCount, ...
    assessment.canonicalWallAgreement.coarseConsensusModel, ...
    assessment.canonicalWallAgreement.fineConsensusModel, ...
    assessment.canonicalWallAgreement.coarseEFoldCount, ...
    assessment.canonicalWallAgreement.fineEFoldCount);
fprintf(['Far source endpoint/max coarse %.3e/%.3e, fine %.3e/%.3e; ' ...
    'far velocity endpoint/max coarse %.3e/%.3e, fine %.3e/%.3e.\n'], ...
    coarse.farBoundary.endpointSourceRatio, ...
    coarse.farBoundary.maximumTrustedSourceRatio, ...
    fine.farBoundary.endpointSourceRatio, ...
    fine.farBoundary.maximumTrustedSourceRatio, ...
    coarse.farBoundary.endpointVelocityRatio, ...
    coarse.farBoundary.maximumTrustedVelocityRatio, ...
    fine.farBoundary.endpointVelocityRatio, ...
    fine.farBoundary.maximumTrustedVelocityRatio);
fprintf(['Available numerical gates passed %d; half-dt/larger-box/third-grid ' ...
    'coverage 0/0/0; credible blow-up = 0.\n'], ...
    assessment.availableNumericalEvidencePassed);
end

function values = trusted_series(values,prefix,label)
if ~isnumeric(values) || ~isreal(values) || ~isvector(values) || ...
        numel(values) ~= numel(prefix)
    error('ipm:LatticeRefinementSeries', ...
        'The %s series is not aligned with the trusted mask.',label);
end
values = values(:);
values = values(prefix);
if any(~isfinite(values))
    error('ipm:LatticeRefinementSeries', ...
        'The trusted %s series contains nonfinite values.',label);
end
end

function require_strictly_increasing(values,label)
if any(diff(values) <= 0)
    error('ipm:LatticeRefinementCoordinate', ...
        'The trusted %s series must be strictly increasing.',label);
end
end

function require_positive(values,label)
if any(values <= 0)
    error('ipm:LatticeRefinementPositive', ...
        'The trusted %s series must be positive.',label);
end
end

function require_nonnegative(values,label)
if any(values < 0)
    error('ipm:LatticeRefinementNonnegative', ...
        'The trusted %s series must be nonnegative.',label);
end
end

function require_fields(value,names,context)
missing = names(~isfield(value,names));
if ~isempty(missing)
    error('ipm:LatticeRefinementField', ...
        'The %s is missing required field "%s".',context,missing{1});
end
end

function weights = trapezoid_weights(coordinate)
spacing = diff(coordinate);
weights = [spacing(1)/2; ...
    (spacing(1:end-1)+spacing(2:end))/2;spacing(end)/2];
end
