function report = verify_fourth_order_blowup_setup()
%VERIFY_FOURTH_ORDER_BLOWUP_SETUP Audit the reproducible campaign factories.

names = { ...
    'stable_limit_box_quadrant_256', ...
    'analytic_stable_limit_box_quadrant_256', ...
    'analytic_intermediate_limit_box_quadrant_256', ...
    'analytic_moderate_narrow_limit_box_quadrant_256', ...
    'analytic_strong_limit_box_quadrant_256', ...
    'analytic_ratio_limit_box_quadrant_256', ...
    'analytic_gaussian_A14_w042_c114_quadrant_256', ...
    'analytic_lorentzian_A24_w020_c114_quadrant_256', ...
    'analytic_lorentzian_A28_w020_c114_quadrant_256', ...
    'analytic_lorentzian_A32_w020_c114_quadrant_256'};
profiles = { ...
    'legacy_abs_gaussian', ...
    'analytic_double_gaussian', ...
    'analytic_double_gaussian', ...
    'analytic_double_gaussian', ...
    'analytic_double_gaussian', ...
    'analytic_double_gaussian', ...
    'analytic_double_gaussian', ...
    'analytic_double_lorentzian', ...
    'analytic_double_lorentzian', ...
    'analytic_double_lorentzian'};
versions = [1,2,2,2,2,2,2,3,3,3];
strengths = [16,16,18,16,20,24,14,24,28,32];
widths = [0.7,0.7,0.7,0.55,0.7,0.7,0.42,0.20,0.20,0.20];
peakCenters = [NaN,NaN,NaN,NaN,NaN,NaN,1.14,1.14,1.14,1.14];

for index = 1:numel(names)
    opts = fourth_order_blowup_case(names{index});
    grid = opts.caseMetadata.smoothGrid;
    assert(opts.nx == 513 && opts.ny == 257 && ...
        strcmp(opts.spatialDiscretization,'high_order') && ...
        strcmp(opts.transportScheme,'weno5_fd') && ...
        strcmp(opts.timeIntegrator,'ssprk54') && ...
        strcmp(opts.remeshTransferScheme,'high_order'), ...
        'ipm:FourthOrderCampaignTuple', ...
        'Case %s does not retain the fourth-order 256-cell tuple.', ...
        names{index});
    assert(strcmp(grid.profile,profiles{index}) && ...
        strcmp(grid.monitorCoordinate,'solver_grid_x') && ...
        grid.mappingVersion == versions(index) && ...
        grid.strength == strengths(index) && ...
        grid.width == widths(index) && grid.fineCount >= 131073, ...
        'ipm:FourthOrderCampaignMapping', ...
        'Case %s has inconsistent mapping provenance.',names{index});
    if isfinite(peakCenters(index))
        assert(abs(grid.peakCenter-peakCenters(index)) < 1e-14 && ...
            isfield(grid.profileParameters,'peakCenter') && ...
            abs(grid.profileParameters.peakCenter-peakCenters(index)) < ...
            1e-14, ...
            'ipm:FourthOrderCampaignPeakCenter', ...
            'Case %s has inconsistent peak-path centering.',names{index});
    end
    assert(all(diff(opts.customX) > 0) && all(diff(opts.customY) > 0) && ...
        max(abs(opts.customX+fliplr(opts.customX))) < 1e-11 && ...
        grid.maximumAdjacentCellRatioX <= 1.5 && ...
        grid.maximumAdjacentCellRatioY <= 1.5 && ...
        grid.minimumStencilRcondX >= 1e-9 && ...
        grid.minimumStencilRcondY >= 1e-9 && ...
        grid.minimumQuadratureWeightRatioX >= 1e-4 && ...
        grid.minimumQuadratureWeightRatioY >= 1e-4, ...
        'ipm:FourthOrderCampaignGridQuality', ...
        'Case %s does not satisfy the grid admission contract.', ...
        names{index});
end

coordinatedNames = { ...
    'coordinated_log_F80_R16_c114_quadrant_256', ...
    'coordinated_log_F80_R20_c114_quadrant_256', ...
    'coordinated_log_F80_R24_c114_quadrant_256', ...
    'coordinated_log_F80_R28_c114_quadrant_256', ...
    'coordinated_log_F90_R20_c114_quadrant_256', ...
    'coordinated_log_F92_R20_c114_quadrant_256'};
expectedRoundingCells = [16,20,24,28,20,20];
expectedFineCells = [80,80,80,80,90,92];
expectedLeftCells = [50,52,54,56,51,50];
for index = 1:numel(coordinatedNames)
    opts = fourth_order_blowup_case(coordinatedNames{index});
    grid = opts.caseMetadata.smoothGrid;
    design = grid.coordinatedDesign;
    positive = opts.customX((opts.nx+1)/2:end);
    positiveWidths = diff(positive);
    fineFirst = design.leftCells+1;
    fineLast = design.leftCells+design.fineCells;
    assert(opts.nx == 513 && opts.ny == 257 && ...
        strcmp(grid.profile,'coordinated_log_spacing') && ...
        strcmp(grid.mappingKind,'direct_rounded_log_spacing') && ...
        strcmp(grid.monitorCoordinate,'none_direct_cell_widths') && ...
        grid.mappingVersion == 5 && grid.fineCount == 0 && ...
        design.leftCells == expectedLeftCells(index) && ...
        design.fineCells == expectedFineCells(index) && ...
        design.rightCells == 256-expectedFineCells(index)- ...
            expectedLeftCells(index) && ...
        design.roundingCells == expectedRoundingCells(index) && ...
        max(abs(design.fineInterval-[0.95,1.30])) < 1e-14 && ...
        abs(positive(fineFirst)-0.95) < 1e-14 && ...
        abs(positive(fineLast+1)-1.30) < 1e-14 && ...
        max(abs(positiveWidths(fineFirst:fineLast)- ...
            0.35/expectedFineCells(index))) < ...
            1e-13 && ...
        design.asymptoticSlopeBalance >= 0.96 && ...
        design.transitionLogSpacing.halfVariationInterfaceFraction >= ...
            0.37 && ...
        grid.maximumAdjacentCellRatioX <= 1.09 && ...
        grid.maximumLogSpacingCurvatureX <= 4.5e-3 && ...
        grid.minimumStencilRcondX >= 1e-9 && ...
        grid.minimumQuadratureWeightRatioX >= 1e-4 && ...
        all(diff(opts.customX) > 0) && ...
        max(abs(opts.customX+fliplr(opts.customX))) < 1e-11, ...
        'ipm:FourthOrderCoordinatedGrid', ...
        'Coordinated case %s is inconsistent.',coordinatedNames{index});
end

dense = fourth_order_blowup_case( ...
    'analytic_moderate_narrow_quadrant_384');
denseGrid = dense.caseMetadata.smoothGrid;
assert(dense.nx == 769 && dense.ny == 385 && ...
    all(abs(dense.targetCenterSpacing- ...
    [0.0193174285333333,0.000833333333333333]) < 1e-15) && ...
    dense.physicalFinalTime == 2.05 && dense.maxDt == 2e-3 && ...
    strcmp(denseGrid.profile,'analytic_double_gaussian') && ...
    denseGrid.mappingVersion == 2 && denseGrid.fineCount >= 196609 && ...
    denseGrid.strength == 16 && denseGrid.width == 0.55 && ...
    all(diff(dense.customX) > 0) && all(diff(dense.customY) > 0) && ...
    max(abs(dense.customX+fliplr(dense.customX))) < 1e-11 && ...
    denseGrid.maximumAdjacentCellRatioX <= 1.5 && ...
    denseGrid.maximumAdjacentCellRatioY <= 1.5 && ...
    denseGrid.minimumStencilRcondX >= 1e-9 && ...
    denseGrid.minimumStencilRcondY >= 1e-9 && ...
    denseGrid.minimumQuadratureWeightRatioX >= 1e-4 && ...
    denseGrid.minimumQuadratureWeightRatioY >= 1e-4 && ...
    contains(dense.caseMetadata.gridInterpretation, ...
    '384 x 384 cells in the first quadrant'), ...
    'ipm:FourthOrderDenseCampaign', ...
    'The matched 384-cell campaign configuration is inconsistent.');

finalGridOptions = fourth_order_blowup_case( ...
    'analytic_lorentzian_A28_w020_c114_quadrant_512');
finalGrid = finalGridOptions.caseMetadata.smoothGrid;
assert(finalGridOptions.nx == 1025 && finalGridOptions.ny == 513 && ...
    all(abs(finalGridOptions.targetCenterSpacing- ...
    [0.0144880714,0.000625]) < 1e-15) && ...
    finalGridOptions.physicalFinalTime == 2.10 && ...
    finalGridOptions.maxDt == 2e-3 && ...
    finalGridOptions.maxSteps == 4800 && ...
    strcmp(finalGrid.profile,'analytic_double_lorentzian') && ...
    strcmp(finalGrid.monitorCoordinate,'solver_grid_x') && ...
    finalGrid.mappingVersion == 3 && finalGrid.strength == 28 && ...
    finalGrid.width == 0.20 && finalGrid.peakCenter == 1.14 && ...
    finalGrid.fineCount >= 262145 && ...
    all(diff(finalGridOptions.customX) > 0) && ...
    all(diff(finalGridOptions.customY) > 0) && ...
    finalGrid.maximumAdjacentCellRatioX <= 1.12 && ...
    finalGrid.maximumLogSpacingCurvatureX <= 3e-3 && ...
    finalGrid.minimumStencilRcondX >= 1e-9 && ...
    finalGrid.minimumStencilRcondY >= 1e-9 && ...
    finalGrid.minimumQuadratureWeightRatioX >= 1e-4 && ...
    finalGrid.minimumQuadratureWeightRatioY >= 1e-4 && ...
    contains(finalGridOptions.caseMetadata.gridInterpretation, ...
    '512 x 512 cells in the first quadrant'), ...
    'ipm:FourthOrderFinalCampaign', ...
    'The matched 512-cell campaign configuration is inconsistent.');

coordinatedDenseNames = { ...
    'coordinated_log_F80_R20_c114_quadrant_512', ...
    'coordinated_log_F90_R20_c114_quadrant_512', ...
    'coordinated_log_F92_R20_c114_quadrant_512'};
coordinatedCoarseNames = { ...
    'coordinated_log_F80_R20_c114_quadrant_256', ...
    'coordinated_log_F90_R20_c114_quadrant_256', ...
    'coordinated_log_F92_R20_c114_quadrant_256'};
expectedDenseFineCells = [160,180,184];
expectedActualDensePlatformCells = [164,184,188];
expectedDenseMaxSteps = [5300,4800,5300];
for index = 1:numel(coordinatedDenseNames)
    denseOptions = fourth_order_blowup_case(coordinatedDenseNames{index});
    denseGrid = denseOptions.caseMetadata.smoothGrid;
    coarseOptions = fourth_order_blowup_case(coordinatedCoarseNames{index});
    coarseGrid = coarseOptions.caseMetadata.smoothGrid;
    design = denseGrid.coordinatedDesign;
    nestedXOffset = max(abs( ...
        denseOptions.customX(1:2:end)-coarseOptions.customX));
    nestedYOffset = max(abs( ...
        denseOptions.customY(1:2:end)-coarseOptions.customY));
    positiveX = denseOptions.customX((denseOptions.nx+1)/2:end);
    positiveWidths = diff(positiveX);
    platformTolerance = 1024*eps(max(1,design.fineSpacing));
    platformMask = abs(positiveWidths-design.fineSpacing) <= ...
        platformTolerance;
    platformCells = find(platformMask);
    platformIsContiguous = ~isempty(platformCells) && ...
        all(diff(platformCells) == 1);
    platformInterval = [positiveX(platformCells(1)), ...
        positiveX(platformCells(end)+1)];
    assert(denseOptions.nx == 1025 && denseOptions.ny == 513 && ...
        denseOptions.maxSteps == expectedDenseMaxSteps(index) && ...
        strcmp(denseGrid.profile,'coordinated_log_spacing') && ...
        denseGrid.mappingVersion == 5 && denseGrid.fineCount == 0 && ...
        design.fineCells == expectedDenseFineCells(index) && ...
        design.roundingCells == 40 && ...
        design.leftCells+design.fineCells+design.rightCells == 512 && ...
        design.asymptoticSlopeBalance >= 0.96 && ...
        isequaln(denseGrid.profileParameters, ...
            coarseGrid.profileParameters) && ...
        denseGrid.maximumAdjacentCellRatioX <= 1.045 && ...
        denseGrid.maximumLogSpacingCurvatureX <= 1.4e-3 && ...
        denseGrid.minimumStencilRcondX >= 1e-9 && ...
        denseGrid.minimumQuadratureWeightRatioX >= 1e-4 && ...
        all(diff(denseOptions.customX) > 0) && ...
        nestedXOffset <= 1e-12 && nestedYOffset <= 1e-12 && ...
        platformIsContiguous && ...
        numel(platformCells) == expectedActualDensePlatformCells(index) && ...
        platformInterval(1) <= design.fineInterval(1) && ...
        platformInterval(2) >= design.fineInterval(2) && ...
        max(abs(denseOptions.customX+ ...
            fliplr(denseOptions.customX))) < 1e-11 && ...
        contains(denseOptions.caseMetadata.gridInterpretation, ...
            '512 x 512 cells in the first quadrant'), ...
        'ipm:FourthOrderCoordinatedDenseGrid', ...
        'Dense coordinated case %s is inconsistent.', ...
        coordinatedDenseNames{index});
end

largeBoxOptions = fourth_order_blowup_case( ...
    'coordinated_log_anchor_F80_R20_large_box_quadrant_512');
largeBoxGrid = largeBoxOptions.caseMetadata.smoothGrid;
largeBoxDesign = largeBoxGrid.coordinatedDesign;
assert(largeBoxOptions.nx == 1025 && largeBoxOptions.ny == 513 && ...
    isequal(largeBoxOptions.xlim,[-1e6,1e6]) && ...
    largeBoxOptions.ymax == 1e6 && ...
    min(abs(largeBoxOptions.customX-1)) <= 1e-12 && ...
    largeBoxDesign.fineCells == 160 && ...
    largeBoxDesign.roundingCells == 40 && ...
    largeBoxGrid.maximumAdjacentCellRatioX <= 1.08 && ...
    largeBoxGrid.maximumAdjacentCellRatioY <= 1.08 && ...
    largeBoxGrid.maximumLogSpacingCurvatureX <= 0.01 && ...
    largeBoxGrid.maximumLogSpacingCurvatureY <= 0.01 && ...
    largeBoxGrid.minimumStencilRcondX >= 1e-9 && ...
    largeBoxGrid.minimumStencilRcondY >= 1e-9 && ...
    largeBoxGrid.minimumQuadratureWeightRatioX >= 1e-8 && ...
    largeBoxGrid.minimumQuadratureWeightRatioY >= 1e-8 && ...
    largeBoxGrid.minimumLocalQuadratureWeightRatioX >= 0.35 && ...
    largeBoxGrid.minimumLocalQuadratureWeightRatioY >= 0.35 && ...
    largeBoxGrid.maximumLocalQuadratureWeightRatioX <= 1.65 && ...
    largeBoxGrid.maximumLocalQuadratureWeightRatioY <= 1.65 && ...
    largeBoxGrid.qualityPolicy.quadratureWarningRatio == 1e-4 && ...
    contains(largeBoxOptions.caseMetadata.gridInterpretation, ...
        '512 x 512 cells in the first quadrant'), ...
    'ipm:FourthOrderLargeBoxCampaign', ...
    'The anchor-aligned q512 large-box grid is inconsistent.');

reservedRejected = false;
try
    fourth_order_blowup_case( ...
        'analytic_stable_limit_box_quadrant_256', ...
        struct('caseMetadata',struct('caseName','forged')));
catch exception
    reservedRejected = strcmp( ...
        exception.identifier,'ipm:FourthOrderReservedMetadata');
end
assert(reservedRejected,'ipm:FourthOrderCampaignMetadata', ...
    'Reserved campaign metadata could be overwritten.');

mixtureProbe = fourth_order_blowup_case( ...
    'analytic_gaussian_A14_w042_c114_quadrant_256');
mixtureProbe = rmfield(mixtureProbe,{'customX','customY'});
[mixtureX,mixtureY,mixtureGrid] = fourth_order_smooth_peak_grid( ...
    mixtureProbe,12,0.24,'analytic_gaussian_mixture',struct( ...
    'shoulderStrength',2,'shoulderWidth',0.9,'peakCenter',1.14));
assert(all(diff(mixtureX) > 0) && all(diff(mixtureY) > 0) && ...
    strcmp(mixtureGrid.profile,'analytic_gaussian_mixture') && ...
    mixtureGrid.mappingVersion == 4 && ...
    mixtureGrid.profileParameters.shoulderStrength == 2 && ...
    mixtureGrid.profileParameters.shoulderWidth == 0.9 && ...
    mixtureGrid.profileParameters.peakCenter == 1.14, ...
    'ipm:FourthOrderCampaignMixture', ...
    'The analytic Gaussian-mixture mapping contract is inconsistent.');
badProfileParameterRejected = false;
try
    fourth_order_smooth_peak_grid(mixtureProbe,12,0.24, ...
        'analytic_double_gaussian',struct('unknownParameter',1));
catch exception
    badProfileParameterRejected = strcmp(exception.identifier, ...
        'ipm:SmoothPeakGridProfileParameters');
end
assert(badProfileParameterRejected, ...
    'ipm:FourthOrderCampaignProfileParameters', ...
    'Unknown analytic-grid profile parameters were not rejected.');
assert(isequal(ipm.output.continuousTrustedPrefix( ...
    [true,true,false,true]),[true,true,false,false]) && ...
    isequal(ipm.output.continuousTrustedPrefix( ...
    [false;true]),[false;false]), ...
    'ipm:FourthOrderCampaignTrustedPrefix', ...
    'The continuous trusted-prefix contract is inconsistent.');

report = struct('passed',true,'cases',{[names,coordinatedNames, ...
    {dense.caseMetadata.caseName,finalGridOptions.caseMetadata.caseName}, ...
    coordinatedDenseNames]}, ...
    'analyticCases',nnz(versions >= 2), ...
    'coordinatedCases',numel(coordinatedNames), ...
    'denseCases',2+numel(coordinatedDenseNames), ...
    'legacyCases',nnz(versions == 1));
fprintf(['Fourth-order blow-up setup passed: %d analytic-monitor and ' ...
    '%d coordinated 256-cell, %d dense, and %d legacy factory cases ' ...
    'audited.\n'],report.analyticCases,report.coordinatedCases, ...
    report.denseCases,report.legacyCases);
end
