function report = verify_bessel_two_scale_initial_data()
%VERIFY_BESSEL_TWO_SCALE_INITIAL_DATA Audit the smooth K_1-core datum.
%   This test uses monitorAmplitude=0, so the density trace is exactly zero.
%   IPM.SOLVE evolution cases add the separately reported tiny monitor because
%   the current physical-mode initialization requires a wall-rho_x peak.

experimentDirectory = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
    'experiments');
addpath(experimentDirectory);
config = ipm.config.resolve(bessel_two_scale_case('smoke_k1',struct( ...
    'saveResults',false,'verbose',false)));
ops = ipm.mesh.build(config);
parameters = config.output.caseMetadata.parameters;
parameters.amplitude = 1;
parameters.perturbationAmplitude = 0;
parameters.monitorAmplitude = 0;
rho = bessel_k1_two_scale_initial_data(ops.X,ops.Y,parameters);
[~,u2,psi,omega] = ipm.field.velocity(rho,ops);

centeredX = ops.X-parameters.centerX;
radius = hypot(centeredX,ops.Y);
argument = 0.5*parameters.mu*radius;
exactExterior = zeros(size(radius));
nonzero = radius > 0;
exactExterior(nonzero) = exp(0.5*parameters.mu*centeredX(nonzero)- ...
    argument(nonzero)).*besselk(1,argument(nonzero),1).* ...
    ops.Y(nonzero)./radius(nonzero);
farMask = radius >= 4 & centeredX >= 4 & centeredX <= 18 & ops.Y <= 8;
coefficient = dot(exactExterior(farMask),rho(farMask)) / ...
    dot(exactExterior(farMask),exactExterior(farMask));
farRelativeError = norm(rho(farMask)-coefficient*exactExterior(farMask)) / ...
    norm(rho(farMask));

report = struct('allFinite',all(isfinite(rho),'all'), ...
    'wallDensityInf',max(abs(rho(1,:))), ...
    'wallNormalVelocityInf',max(abs(u2(1,:))), ...
    'wallStreamfunctionInf',max(abs(psi(1,:))), ...
    'farExteriorRelativeError',farRelativeError, ...
    'densityMaximum',max(rho,[],'all'), ...
    'rhoXMaximum',max(abs(omega),[],'all'));

assert(report.allFinite,'ipm:BesselK1Finite','K1-core data are not finite.');
assert(report.wallDensityInf == 0,'ipm:BesselK1WallDensity', ...
    'The pure K1-core density must vanish exactly on y=0.');
assert(report.wallNormalVelocityInf < 1e-12,'ipm:BesselK1WallVelocity', ...
    'The half-plane Poisson solve must enforce zero wall-normal velocity.');
assert(report.farExteriorRelativeError < 1e-2, ...
    'ipm:BesselK1ExteriorError', ...
    'The regularized datum does not approach the K1 exterior accurately.');

fprintf(['Pure K1-core: wall rho %.3e, wall u2 %.3e, ' ...
    'far exterior error %.3e.\n'],report.wallDensityInf, ...
    report.wallNormalVelocityInf,report.farExteriorRelativeError);
end
