function [rhoNew,opsNew,info] = ...
    adapt(rho,ops,flow,config,amplitudeScale)
%IPM.REMESH.ADAPT Orchestrate propose-transfer-validate remeshing.

if nargin < 5
    amplitudeScale = 1;
end
validateattributes(amplitudeScale,{'numeric'}, ...
    {'scalar','real','finite','positive'},mfilename,'amplitudeScale');
if ipm.mesh.isQuadrant(ops)
    [rhoNew,opsNew,info] = ipm.remesh.directLevelSetAdapt( ...
        rho,ops,flow,config,amplitudeScale);
    return
end

context = [];
accepted = false;
firstProposal = [];
transferFailureIdentifier = '';
firstMetrics = struct('xCore',NaN,'yCore',NaN,'peak',NaN, ...
    'rangeViolation',NaN,'relativeRangeViolation',NaN);
for retry = 0:8
    [proposal,context] = ...
        ipm.remesh.propose(ops,flow,config,retry,context);
    if retry == 0
        firstProposal = proposal;
        if ~proposal.anyImproved
            rhoNew = rho;
            opsNew = ops;
            info = remesh_info(false,ops.remeshCount,context, ...
                proposal,flow,firstMetrics,transferFailureIdentifier);
            return;
        end
    elseif ~proposal.anyImproved
        break;
    end

    try
        [candidateRho,candidateOps,metrics] = ...
            ipm.remesh.transfer(rho,ops,config,proposal);
    catch exception
        if recoverable_high_order_transfer_failure(exception.identifier)
            % Reject a numerically inadmissible candidate and let the
            % existing retry damping reduce its deformation. Programming
            % and configuration errors still escape immediately.
            transferFailureIdentifier = exception.identifier;
            continue;
        end
        rethrow(exception);
    end
    if retry == 0
        firstMetrics = metrics;
    end
    validation = ipm.remesh.validate( ...
        metrics,ops,flow,config,proposal,context,retry,amplitudeScale);
    if validation.accepted
        rhoNew = candidateRho;
        opsNew = candidateOps;
        acceptedProposal = proposal;
        acceptedMetrics = metrics;
        accepted = true;
        break;
    end
end

if ~accepted
    rhoNew = rho;
    opsNew = ops;
    info = remesh_info(false,ops.remeshCount,context, ...
        firstProposal,flow,firstMetrics,transferFailureIdentifier);
    return;
end
opsNew.remeshCount = ops.remeshCount+1;
info = remesh_info(true,opsNew.remeshCount,context, ...
    acceptedProposal,flow,acceptedMetrics,transferFailureIdentifier);
end

function info = remesh_info( ...
        applied,count,context,proposal,flow,metrics,transferFailureIdentifier)
info = struct('applied',applied,'count',count,'peakX',context.peakX, ...
    'window',context.xWindow,'xWindow',context.xWindow, ...
    'yWindow',context.yWindow, ...
    'requestedAmplitude',proposal.xAmplitude, ...
    'amplitude',proposal.xAmplitude, ...
    'xAmplitude',proposal.xAmplitude,'yAmplitude',proposal.yAmplitude, ...
    'minimumSpacing',context.minimumSpacing(1), ...
    'minimumYSpacing',context.minimumSpacing(2), ...
    'oldPeakSpacing',context.oldPeakSpacing, ...
    'newPeakSpacing',proposal.newPeakSpacing, ...
    'oldWallSpacing',context.oldWallSpacing, ...
    'newWallSpacing',proposal.newWallSpacing, ...
    'oldCoreGridPoints',flow.coreGridPoints, ...
    'newCoreGridPoints',metrics.xCore, ...
    'oldVerticalCoreGridPoints',flow.verticalCoreGridPoints, ...
    'newVerticalCoreGridPoints',metrics.yCore, ...
    'rangeViolation',metrics.rangeViolation, ...
    'relativeRangeViolation',metrics.relativeRangeViolation, ...
    'xMaximumCellRatio',proposal.xAxisInfo.maximumCellRatio, ...
    'yMaximumCellRatio',proposal.yAxisInfo.maximumCellRatio, ...
    'xTargetCounts',proposal.xAxisInfo.targetCounts, ...
    'yTargetCounts',proposal.yAxisInfo.targetCounts, ...
    'xPredictedCounts',proposal.xAxisInfo.counts, ...
    'yPredictedCounts',proposal.yAxisInfo.counts, ...
    'xTargetReached',proposal.xAxisInfo.targetReached, ...
    'yTargetReached',proposal.yAxisInfo.targetReached, ...
    'transferFailureIdentifier',transferFailureIdentifier);
end

function answer = recoverable_high_order_transfer_failure(identifier)
recoverable = {'ipm:HighOrderQuadratureWeights', ...
    'ipm:HighOrderGridMetric','ipm:FiniteDifferenceScale', ...
    'ipm:HighOrderRemeshBubble','ipm:SixthOrderGridMetric', ...
    'ipm:SixthOrderQuadratureWeights', ...
    'ipm:SixthOrderQuadratureMetric', ...
    'ipm:SixthOrderGridCellRatio', ...
    'ipm:SixthOrderGridStencilCondition', ...
    'ipm:SixthOrderGridQuadratureMargin', ...
    'ipm:SixthOrderGridMetricConsistency'};
answer = any(strcmp(identifier,recoverable));
end
