function audit=auditCandidate(source,candidate,policy,priorAbsolutePeakJump)
%IPM.REMESH.AUDITCANDIDATE Measure an actual autonomous remesh before commit.
% Both arguments are complete state views with rho/ops/scale/step and clocks.
% This function builds no operators, performs no transfer, and changes no state.
validateattributes(priorAbsolutePeakJump,{'numeric'}, ...
    {'scalar','real','finite','nonnegative'});
required={'rho','ops','scale','step','normalizedTime','config','runMetadata','mass0','rhoRange0'};
assert(all(isfield(source,required)) && all(isfield(candidate,required)), ...
    'ipm:AutonomousMeshAuditInput','Complete source and candidate state views are required.');
old=source.ops;new=candidate.ops;
assert(isequal(size(source.rho),[numel(old.y),numel(old.x)]) && ...
    isequal(size(candidate.rho),[numel(new.y),numel(new.x)]), ...
    'ipm:AutonomousMeshAuditInput','Every field must pair with its own axes.');
audit=struct('version',1,'kind','autonomous_actual_candidate_audit', ...
    'passed',false,'reasons',{{}},'sourceStep',source.step, ...
    'sourceCanonicalTime',source.scale.canonicalTime, ...
    'sourcePhysicalTime',source.scale.physicalTime, ...
    'sourceRemeshCount',old.remeshCount,'coreCells',[NaN,NaN], ...
    'leftFrontCells',NaN,'relativePeakJump',NaN, ...
    'priorCumulativeAbsolutePeakJump',priorAbsolutePeakJump, ...
    'cumulativeAbsolutePeakJump',NaN,'massRelativeDefect',NaN, ...
    'relativeRangeViolation',NaN,'xQuality',struct(),'yQuality',struct(), ...
    'clocksAndReferencesPreserved',false,'sameBoxAndNodeCount',false);
variableNodes=isfield(policy,'version') && policy.version==2;
if variableNodes
    audit.version=2;
    audit.sourceLevelId=NaN;audit.targetLevelId=NaN;
    audit.sourceNodeCount=[numel(old.x),numel(old.y)];
    audit.targetNodeCount=[numel(new.x),numel(new.y)];
    audit.sourceCellFactors=[NaN,NaN];audit.targetCellFactors=[NaN,NaN];
    audit.sameBox=false;audit.registeredNodeCounts=false;
    audit.matchingReferenceMembers=false;audit.admittedLevelTransition=false;
end
if ~isreal(source.rho) || ~isreal(candidate.rho) || ...
        any(~isfinite(source.rho),'all') || any(~isfinite(candidate.rho),'all')
    audit.reasons={'nonfinite_field'};return
end
for item={source,candidate}
    v=item{1};weights=v.ops.integrationWeights;
    if ~isnumeric(weights) || ~isreal(weights) || ...
            ~isequal(size(weights),size(v.rho)) || ...
            any(~isfinite(weights),'all') || any(weights<=0,'all')
        audit.reasons={'invalid_integration_weights'};return
    end
end
if ~isequaln(source.config,candidate.config) || ...
        ~isequaln(source.runMetadata,candidate.runMetadata) || ...
        ~isequal(source.mass0,candidate.mass0) || ~isequal(source.rhoRange0,candidate.rhoRange0)
    audit.reasons={'changed_configuration_initial_invariants_or_lineage'};return
end
if ~isequal(source.scale,candidate.scale) || source.step~=candidate.step || ...
        source.normalizedTime~=candidate.normalizedTime || ...
        old.remeshCount~=new.remeshCount || ...
        ~isequaln(rmfield(old.rescaling,{'originIndex','pinIndex'}), ...
                  rmfield(new.rescaling,{'originIndex','pinIndex'}))
    audit.reasons={'changed_clocks_or_runtime_references'};return
end
[~,originIndex]=min(abs(new.x));[~,pinIndex]=min(abs(new.x-new.rescaling.pinX));
if new.rescaling.originIndex~=originIndex || new.rescaling.pinIndex~=pinIndex
    audit.reasons={'incorrect_runtime_reference_indices'};return
end
audit.clocksAndReferencesPreserved=true;
if variableNodes
    audit.sameBox=isequal(old.x([1,end]),new.x([1,end])) && ...
        isequal(old.y([1,end]),new.y([1,end]));
    audit.sameBoxAndNodeCount=audit.sameBox && ...
        isequal(audit.sourceNodeCount,audit.targetNodeCount);
    [audit,familyReason]=registered_transition(source,candidate,policy,audit);
    if ~isempty(familyReason)
        audit.reasons={familyReason};return
    end
    if ~audit.sameBox || any(diff(new.x)<=0) || any(diff(new.y)<=0) || ...
            ~isequal(new.x,-fliplr(new.x)) || new.y(1)~=0
        audit.reasons={'changed_box_or_invalid_registered_axes'};return
    end
elseif numel(old.x)~=numel(new.x) || numel(old.y)~=numel(new.y) || ...
        ~isequal(old.x([1,end]),new.x([1,end])) || ~isequal(old.y([1,end]),new.y([1,end])) || ...
        ~isequal(old.baseX,new.baseX) || ~isequal(old.baseY,new.baseY) || ...
        any(diff(new.x)<=0) || any(diff(new.y)<=0) || ...
        ~isequal(new.x,-fliplr(new.x)) || new.y(1)~=0
    audit.reasons={'changed_box_reference_or_node_count'};return
end
if ~variableNodes,audit.sameBoxAndNodeCount=true;end
anchor=old.rescaling.transportAnchorX;
if ~any(new.x==anchor) || ~any(new.x==-anchor)
    audit.reasons={'missing_exact_transport_anchor'};return
end
qx=ipm.mesh.quality(new.x,7,ipm.mesh.quadrature(new.x));
qy=ipm.mesh.quality(new.y,7,ipm.mesh.quadrature(new.y));
audit.xQuality=qx;audit.yQuality=qy;
audit.reasons=[quality_reasons(qx,policy.qualityLimits,'x'), ...
    quality_reasons(qy,policy.qualityLimits,'y')];
oldOmega=source.rho*old.Dx';newOmega=candidate.rho*new.Dx';
if ~isreal(oldOmega) || ~isreal(newOmega) || ...
        any(~isfinite(oldOmega),'all') || any(~isfinite(newOmega),'all')
    audit.reasons={'invalid_paired_gradient'};return
end
oldPeak=max(abs(oldOmega),[],'all');newPeak=max(abs(newOmega),[],'all');
assert(isfinite(oldPeak) && oldPeak>0,'ipm:AutonomousMeshAuditInput','The old peak must be positive.');
audit.relativePeakJump=abs(newPeak-oldPeak)/oldPeak;
audit.cumulativeAbsolutePeakJump=priorAbsolutePeakJump+audit.relativePeakJump;
oldMass=sum(source.rho.*old.integrationWeights,'all');
newMass=sum(candidate.rho.*new.integrationWeights,'all');
% Preserve the native grid-lab denominator even for signed cancellation.
% An L1 denominator would silently weaken the registered mass gate.
audit.massRelativeDefect=abs(newMass-oldMass)/max(abs(oldMass),eps);
lo=min(source.rho,[],'all');hi=max(source.rho,[],'all');
rangeScale=max([hi-lo,abs(lo),abs(hi),eps]);
audit.relativeRangeViolation=max([lo-min(candidate.rho,[],'all'), ...
    max(candidate.rho,[],'all')-hi,0])/rangeScale;
if any(~isfinite([audit.relativePeakJump,audit.cumulativeAbsolutePeakJump, ...
        oldMass,newMass,audit.massRelativeDefect,audit.relativeRangeViolation]))
    audit.reasons{end+1}='nonfinite_candidate_metric';return
end
% The native counts remain distinct from padded design interval predictions.
xm=ipm.diagnostics.peakResolution(max(newOmega(1,:),0),new.x,[.1,.5,.9]);
ym=ipm.diagnostics.peakResolution(abs(newOmega(:,xm.peakIndex))',new.y',[.1,.5,.9]);
audit.coreCells=[xm.gridPoints(end),ym.gridPoints(end)];
view=struct('rho',candidate.rho,'x',new.x,'y',new.y,'Dx',new.Dx, ...
    'source',newOmega,'trusted',true);
features=ipm.diagnostics.meshFeatureIntervals(view);
audit.leftFrontCells=interval_count(new.x,features.frontInterval);
if any(~isfinite([audit.coreCells,audit.leftFrontCells]))
    audit.reasons{end+1}='nonfinite_resolution_metric';return
end
tests=[any(audit.coreCells<policy.transactionMinimumCoreCells), ...
    audit.leftFrontCells<policy.minimumFrontCells, ...
    audit.relativePeakJump>policy.maximumSinglePeakJump, ...
    audit.cumulativeAbsolutePeakJump>policy.maximumCumulativeAbsolutePeakJump, ...
    audit.massRelativeDefect>policy.maximumMassRelativeDefect, ...
    audit.relativeRangeViolation>policy.maximumRelativeRangeViolation];
labels={'actual_core_floor','actual_front_floor','single_peak_jump', ...
    'cumulative_peak_budget','mass_defect','range_violation'};
audit.reasons=[audit.reasons,labels(tests)];
audit.passed=isempty(audit.reasons);
end

function [audit,reason]=registered_transition(source,candidate,policy,audit)
% Reproduce the immutable registration; candidate metadata is still the
% original precommit metadata. Runtime axes may be redistributed within a
% member, but the member's base axes and counts cannot be invented here.
reason='invalid_registered_reference_family';
if ~isfield(source.config.remesh,'autonomousMesh') || ...
        ~isequaln(source.config.remesh.autonomousMesh,policy) || ...
        ~isfield(source.runMetadata,'autonomousMesh')
    return
end
memory=source.runMetadata.autonomousMesh;
required={'version','policy','referenceFamily','currentLevelId','transactions','initialization', ...
    'cumulativeAbsolutePeakJump'};
if ~isstruct(memory) || ~isscalar(memory) || ...
        ~all(isfield(memory,required)) || memory.version~=2 || ...
        ~isequaln(memory.policy,policy) || ...
        ~isequal(audit.priorCumulativeAbsolutePeakJump,memory.cumulativeAbsolutePeakJump)
    return
end
family=memory.referenceFamily;
if ~isstruct(family) || ~isscalar(family) || ...
        ~all(isfield(family,{'rootX','rootY','anchor','members'})) || ...
        numel(family.rootX)~=source.config.grid.nx || ...
        numel(family.rootY)~=source.config.grid.ny || ...
        family.anchor~=source.config.scaling.transportAnchorX || ...
        ~isequal(family.rootX([1,end]),source.config.grid.xlim) || ...
        ~isequal(family.rootY([1,end]),[0;source.config.grid.ymax])
    return
end
expected=ipm.remesh.referenceAxisFamily( ...
    family.rootX,family.rootY,source.config.scaling.transportAnchorX,policy);
if ~isequaln(family,expected) || ...
        ~all(isfield(memory.initialization,{'selectedBaseX','selectedBaseY'})) || ...
        ~isequal(memory.initialization.selectedBaseX,family.rootX) || ...
        ~isequal(memory.initialization.selectedBaseY,family.rootY)
    return
end
id=memory.currentLevelId;
if ~isnumeric(id) || ~isreal(id) || ~isscalar(id) || ...
        ~isfinite(id) || id~=fix(id) || id<1 || id>numel(family.members)
    return
end
audit.sourceLevelId=id;oldMember=family.members(id);
audit.sourceCellFactors=oldMember.cellFactors;
matched=false(1,numel(family.members));
for k=1:numel(family.members)
    member=family.members(k);
    matched(k)=isequal(candidate.ops.baseX,member.baseX) && ...
        isequal(candidate.ops.baseY,member.baseY) && ...
        isequal(audit.targetNodeCount,member.nodeCount);
end
if sum(matched)~=1
    reason='unregistered_target_reference_or_node_count';return
end
targetId=find(matched);target=family.members(targetId);
audit.targetLevelId=targetId;audit.targetCellFactors=target.cellFactors;
audit.registeredNodeCounts=isequal(audit.sourceNodeCount,oldMember.nodeCount) && ...
    isequal(audit.targetNodeCount,target.nodeCount);
audit.matchingReferenceMembers=isequal(source.ops.baseX,oldMember.baseX) && ...
    isequal(source.ops.baseY,oldMember.baseY) && ...
    isequal(candidate.ops.baseX,target.baseX) && isequal(candidate.ops.baseY,target.baseY) && ...
    isequal(source.ops.x([1,end]),oldMember.baseX([1,end])) && ...
    isequal(source.ops.y([1,end]),oldMember.baseY([1,end])) && ...
    isequal(candidate.ops.x([1,end]),target.baseX([1,end])) && ...
    isequal(candidate.ops.y([1,end]),target.baseY([1,end]));
if ~audit.registeredNodeCounts || ~audit.matchingReferenceMembers
    reason='source_reference_member_mismatch';return
end
% Count prior accepted growths from the original ledger, not a candidate
% counter or an asserted number in its proposal.
ledger=memory.transactions;level=1;growths=0;priorJump=0;
if numel(ledger)~=source.ops.remeshCount
    reason='node_family_transaction_ledger_mismatch';return
end
for k=1:numel(ledger)
    row=ledger(k);
    fields={'version','passed','sourceRemeshCount','sourceLevelId','targetLevelId', ...
        'sourceNodeCount','targetNodeCount','sourceCellFactors','targetCellFactors','relativePeakJump'};
    if ~all(isfield(row,fields)) || row.version~=2 || ~isequal(row.passed,true) || ...
            row.sourceRemeshCount~=k-1 || ~isequal(row.sourceLevelId,level)
        reason='node_family_transaction_ledger_mismatch';return
    end
    next=row.targetLevelId;
    if ~isnumeric(next) || ~isreal(next) || ~isscalar(next) || ...
            ~isfinite(next) || next~=fix(next) || next<1 || next>numel(family.members)
        reason='node_family_transaction_ledger_mismatch';return
    end
    a=family.members(level);b=family.members(next);
    if ~isequal(row.sourceNodeCount,a.nodeCount) || ~isequal(row.targetNodeCount,b.nodeCount) || ...
            ~isequal(row.sourceCellFactors,a.cellFactors) || ~isequal(row.targetCellFactors,b.cellFactors) || ...
            ~all(b.cellFactors>=a.cellFactors) || ~a.resourceAdmitted || ~b.resourceAdmitted || ...
            ~a.qualityPassed || ~b.qualityPassed
        reason='node_family_transaction_ledger_mismatch';return
    end
    if ~isnumeric(row.relativePeakJump) || ~isreal(row.relativePeakJump) || ...
            ~isscalar(row.relativePeakJump) || ~isfinite(row.relativePeakJump) || row.relativePeakJump<0
        reason='node_family_transaction_ledger_mismatch';return
    end
    growths=growths+(next~=level);level=next;
end
if ~isempty(ledger),priorJump=sum([ledger.relativePeakJump]);end
if level~=id || growths>policy.nodeFamily.maximumAcceptedGrowthTransitions || ...
        priorJump~=memory.cumulativeAbsolutePeakJump
    reason='node_family_transaction_ledger_mismatch';return
end
audit.admittedLevelTransition=oldMember.resourceAdmitted && oldMember.qualityPassed && ...
    target.resourceAdmitted && target.qualityPassed && ...
    all(target.cellFactors>=oldMember.cellFactors) && ...
    (targetId==id || growths<policy.nodeFamily.maximumAcceptedGrowthTransitions);
if ~audit.admittedLevelTransition
    reason='unadmitted_node_family_transition';return
end
reason='';
end

function reasons=quality_reasons(q,limits,axisName)
bad=[q.maximumAdjacentCellRatio>limits.maxAdjacentCellRatio, ...
    q.maximumLogSpacingCurvature>limits.maxLogSpacingCurvature, ...
    q.minimumStencilRcond<limits.minStencilRcond, ...
    ~q.quadratureWeightsStrictlyPositive, ...
    q.minimumQuadratureWeightRatio<limits.minQuadratureWeightRatio, ...
    q.minimumQuadratureWeightToControlWidthRatio<limits.minWeightToControlWidth, ...
    q.maximumQuadratureWeightToControlWidthRatio>limits.maxWeightToControlWidth];
names={'adjacent_ratio','spacing_curvature','stencil_rcond','nonpositive_quadrature', ...
    'global_quadrature','local_quadrature_min','local_quadrature_max'};
reasons=cellfun(@(name)[axisName,':',name],names(bad),'UniformOutput',false);
end
function count=interval_count(axis,bounds)
axis=axis(:)';count=sum(max(0,min(axis(2:end),bounds(2))-max(axis(1:end-1),bounds(1)))./diff(axis));
end
