function memory = recordLevelSetFailure( ...
        flow,ops,status,previous,step,scale)
%IPM.REMESH.RECORDLEVELSETFAILURE Freeze geometry for the next retry gate.

if nargin < 4 || isempty(previous) || ...
        ~isstruct(previous) || ~isscalar(previous) || ...
        ~isfield(previous,'attemptCount')
    attemptCount = 0;
else
    attemptCount = previous.attemptCount;
end
[~,evidence] = ipm.remesh.levelSetRetryDecision(flow,ops,[]);
memory = struct('reference',evidence.current, ...
    'requiredRelativeChange',evidence.requiredRelativeChange, ...
    'status',char(status),'attemptCount',attemptCount+1, ...
    'lastAttemptStep',step, ...
    'lastAttemptCanonicalTime',scale.canonicalTime, ...
    'lastAttemptPhysicalTime',scale.physicalTime, ...
    'usesStepOrTimeForDecision',false);
end
