function family=referenceAxisFamily(rootX,rootY,anchor,policy)
%IPM.REMESH.REFERENCEAXISFAMILY Immutable, registered index-PCHIP base axes.
% Only geometry is constructed. Old knots, box endpoints, 0 and +/-anchor
% are exact. Member indices are registration indices, not execution ranks.
% A resource cap is a node budget, not an estimate of available LU memory.
identifier='ipm:AutonomousMeshReferenceFamily';
assert(isstruct(policy)&&isscalar(policy)&&isfield(policy,'version')&& ...
    isequal(policy.version,2),identifier,'A resolved version-two policy is required.');
normalized=ipm.config.autonomousMeshPolicy(policy);
assert(isequaln(normalized,policy),identifier,'Pass the normalized version-two policy.');
validateattributes(rootX,{'double'},{'row','real','finite','increasing','>=',-realmax});
validateattributes(rootY,{'double'},{'column','real','finite','increasing','nonnegative'});
validateattributes(anchor,{'double'},{'scalar','real','finite','positive'});
assert(numel(rootX)>=7&&mod(numel(rootX),2)==1&&numel(rootY)>=7&& ...
    isequal(rootX,-fliplr(rootX))&&rootY(1)==0&&rootY(end)>0&& ...
    anchor<rootX(end)&&any(rootX==anchor)&&any(rootX==-anchor), ...
    identifier,'Root axes must have exact symmetry, origin, interior anchors and at least seven nodes.');
registration=policy.nodeFamily;
assert(numel(rootX)*numel(rootY)<=registration.maximumTotalNodes, ...
    'ipm:AutonomousMeshResourceCap','The root member must fit maximumTotalNodes.');

positive=rootX(rootX>=0);
refinedPositive=pchip(linspace(0,1,numel(positive)),positive, ...
    linspace(0,1,2*numel(positive)-1));
refinedPositive(1:2:end)=positive;
refinedPositive(1)=0;
xAxes={rootX,[-fliplr(refinedPositive(2:end)),refinedPositive]};
refinedY=pchip(linspace(0,1,numel(rootY)),rootY, ...
    linspace(0,1,2*numel(rootY)-1))';
refinedY(1:2:end)=rootY;
refinedY(1)=0;
yAxes={rootY,refinedY};
xQuality=cell(1,2);yQuality=cell(1,2);
for factor=1:2
    x=xAxes{factor};y=yAxes{factor};
    assert(isequal(x(1:factor:end),rootX)&&isequal(y(1:factor:end),rootY)&& ...
        isequal(x,-fliplr(x))&&any(x==anchor)&&any(x==-anchor)&& ...
        isequal(x([1,end]),rootX([1,end]))&&isequal(y([1,end]),rootY([1,end])), ...
        identifier,'Index refinement must preserve every root knot and endpoint exactly.');
    xQuality{factor}=checked_quality(x,policy.qualityLimits,'x',factor);
    yQuality{factor}=checked_quality(y,policy.qualityLimits,'y',factor);
end
members=struct('index',{},'cellFactors',{},'nodeCount',{},'baseX',{},'baseY',{}, ...
    'resourceAdmitted',{},'qualityPassed',{},'xQuality',{},'yQuality',{});
for index=1:size(registration.cellFactors,1)
    factors=registration.cellFactors(index,:);
    x=xAxes{factors(1)};y=yAxes{factors(2)};
    members(index)=struct('index',index,'cellFactors',factors, ...
        'nodeCount',[numel(x),numel(y)],'baseX',x,'baseY',y, ...
        'resourceAdmitted',numel(x)*numel(y)<=registration.maximumTotalNodes, ...
        'qualityPassed',true,'xQuality',xQuality{factors(1)},'yQuality',yQuality{factors(2)});
end
family=struct('version',1,'generator',registration.generator,'rootX',rootX, ...
    'rootY',rootY,'anchor',anchor,'members',members);
end

function q=checked_quality(axis,limits,label,factor)
q=ipm.mesh.quality(axis,7,ipm.mesh.quadrature(axis));
values=[q.maximumAdjacentCellRatio,q.maximumLogSpacingCurvature,q.minimumStencilRcond, ...
    q.minimumQuadratureWeightRatio,q.minimumQuadratureWeightToControlWidthRatio, ...
    q.maximumQuadratureWeightToControlWidthRatio];
passed=all(isfinite(values))&&q.quadratureWeightsStrictlyPositive&& ...
    values(1)<=limits.maxAdjacentCellRatio&&values(2)<=limits.maxLogSpacingCurvature&& ...
    values(3)>=limits.minStencilRcond&&values(4)>=limits.minQuadratureWeightRatio&& ...
    values(5)>=limits.minWeightToControlWidth&&values(6)<=limits.maxWeightToControlWidth;
assert(passed,'ipm:AutonomousMeshReferenceQuality', ...
    'Registered %s reference factor %d fails original axis quality; no family may be admitted.',label,factor);
end
