function report = core()
%IPMTESTS.SIXTH.CORE Compact all-node spatial/remap certificate.
%   The test covers the complete one-sided nine-point
%   D1/D2/Poisson/velocity path on uniform and two fixed sinh grids, mapped
%   WENO-Z7 at smooth and critical fluxes (including both LF splits), the
%   constant-state transport contract, private-policy grid rejection,
%   and the width-eight interpolation/conservation primitive used by the
%   sixth-order remesh path.  Every production operator is built from the
%   grouped version-3 configuration.

threshold = 5.5;
gridSizes = [17,25,37,55];
stressGridSizes = [17,25,37,55,81];
fprintf(['Running sixth-order core verification (all-node tail order ' ...
    'at least %.1f)...\n'],threshold);

report = struct('threshold',threshold,'gridSizes',gridSizes, ...
    'stressGridSizes',stressGridSizes, ...
    'normDomain','all nodes including one-sided closures');
report.spatial.uniform = verify_spatial_family( ...
    'uniform',gridSizes,threshold);
report.spatial.mildSinh = verify_spatial_family( ...
    'mild_sinh',gridSizes,threshold);
report.spatial.stressSinh = verify_spatial_family( ...
    'stress_sinh',stressGridSizes,threshold);
report.weno7 = verify_mapped_weno7(threshold);
report.weno7.linearLimit = verify_weno7_linear_limit();
report.freeStream = verify_constant_free_stream();
report.gridGate = verify_grid_gate_rejection();
report.remap = verify_width_eight_remap();
report.integratedRemap = verify_stretched_grid_remap_mass();
report.passed = true;

spatialMinimum = min([report.spatial.uniform.tailOrders(:); ...
    report.spatial.mildSinh.tailOrders(:); ...
    report.spatial.stressSinh.tailOrders(:)]);
fprintf(['Sixth-order core verification passed: minimum spatial/WENO7 ' ...
    'tail orders %.3f / %.3f.\n'],spatialMinimum, ...
    report.weno7.minimumTailOrder);
end

function family = verify_spatial_family(mode,gridSizes,threshold)
metricNames = {'D1xL2','D1xLinf','D1yL2','D1yLinf', ...
    'D2xL2','D2xLinf','D2yL2','D2yLinf', ...
    'PoissonL2','PoissonLinf','velocityL2','velocityLinf'};
errors = zeros(numel(metricNames),numel(gridSizes));
h = 1./(gridSizes-1);
quality = cell(1,numel(gridSizes));
mappingErrors = zeros(2,numel(gridSizes));
cellRatios = zeros(2,numel(gridSizes));

for level = 1:numel(gridSizes)
    ops = sixth_order_operators(gridSizes(level),mode,'closed');
    assert(ops.derivativeStencilWidth == 9 && ...
        ops.quadratureStencilWidth == 8 && ...
        isequal(size(ops.integrationWeights),[ops.ny,ops.nx]) && ...
        all(ops.integrationWeights > 0,'all'), ...
        'ipm:SixthOrderOperatorContract', ...
        ['The sixth-order operator must expose nine-point derivatives ' ...
        'and positive width-eight all-node quadrature.']);
    quality{level} = ops.gridQuality;
    [expectedX,expectedY,isNonuniform] = ...
        expected_family_axes(gridSizes(level),mode);
    mappingErrors(:,level) = [ ...
        max(abs(ops.x-expectedX));max(abs(ops.y-expectedY))];
    cellRatios(:,level) = [ ...
        ops.gridQuality.x.maximumAdjacentCellRatio; ...
        ops.gridQuality.y.maximumAdjacentCellRatio];
    coordinateScale = max([1,max(abs(expectedX)),max(abs(expectedY))]);
    assert(all(mappingErrors(:,level) <= 100*eps(coordinateScale)) && ...
        (~isNonuniform || all(cellRatios(:,level) > 1+1e-3)), ...
        'ipm:SixthOrderMappedGridFixture', ...
        ['The %s n=%d grid does not match its analytic mapping or one ' ...
        'axis is effectively uniform; defects %s, ratios %s.'],mode, ...
        gridSizes(level),mat2str(mappingErrors(:,level),4), ...
        mat2str(cellRatios(:,level),4));

    probe = derivative_probe(ops.X,ops.Y);
    numericalD1x = probe.value*ops.Dx';
    numericalD1y = ops.Dy*probe.value;
    D2x = ipm.mesh.fdMatrix(ops.x,2,9);
    D2y = ipm.mesh.fdMatrix(ops.y,2,9);
    numericalD2x = probe.value*D2x';
    numericalD2y = D2y*probe.value;
    errors(1:2,level) = full_node_norms( ...
        numericalD1x-probe.x,ops.integrationWeights);
    errors(3:4,level) = full_node_norms( ...
        numericalD1y-probe.y,ops.integrationWeights);
    errors(5:6,level) = full_node_norms( ...
        numericalD2x-probe.xx,ops.integrationWeights);
    errors(7:8,level) = full_node_norms( ...
        numericalD2y-probe.yy,ops.integrationWeights);

    elliptic = nonzero_dirichlet_solution(ops.X,ops.Y);
    boundary = struct('left',elliptic.psi(:,1), ...
        'right',elliptic.psi(:,end), ...
        'bottom',elliptic.psi(1,:), ...
        'top',elliptic.psi(end,:));
    numericalPsi = ipm.field.poisson(elliptic.source,ops,1,boundary);
    errors(9:10,level) = full_node_norms( ...
        numericalPsi-elliptic.psi,ops.integrationWeights);

    exactFlow = ipmtests.support.mms(ops.X,ops.Y,0.137);
    [u1,u2] = ipm.field.velocity(exactFlow.rho,ops);
    velocityError = hypot(u1-exactFlow.u1,u2-exactFlow.u2);
    errors(11:12,level) = full_node_norms( ...
        velocityError,ops.integrationWeights);
end

orders = refinement_orders(errors,h);
tailOrders = orders(:,end-1:end);
assert(all(isfinite(errors),'all') && all(errors > 0,'all') && ...
    all(diff(errors,1,2) < 0,'all') && ...
    all(isfinite(orders),'all') && all(tailOrders >= threshold,'all'), ...
    'ipm:SixthOrderSpatialConvergence', ...
    ['%s all-node nine-point D1/D2/Poisson/velocity refinement failed; ' ...
    'minimum two-tail ' ...
    'order %.3f, required %.1f.'],mode, ...
    min(tailOrders,[],'all'),threshold);

if strcmp(mode,'stress_sinh')
    coarse = quality{1};
    ratios = cellRatios(:,1)';
    assert(max(ratios) >= 1.05 && ...
        all(ratios <= coarse.maximumCellRatio), ...
        'ipm:SixthOrderStressGridContract', ...
        ['The stress grid must include material stretching but remain ' ...
        'inside the private adjacent-cell policy.']);
end

family = struct('mode',mode,'gridSizes',gridSizes,'h',h, ...
    'metricNames',{metricNames},'errors',errors,'orders',orders, ...
    'tailOrders',tailOrders,'gridQuality',{quality}, ...
    'mappingErrors',mappingErrors,'cellRatios',cellRatios, ...
    'derivativeStencilWidth',9,'quadratureStencilWidth',8, ...
    'normDomain','all nodes','passed',true);
fprintf('  %-11s D1/D2/Poisson/velocity minimum two-tail: %.3f.\n', ...
    mode,min(tailOrders,[],'all'));
end

function [x,y,isNonuniform] = expected_family_axes(numberOfNodes,mode)
referenceX = linspace(-1,1,numberOfNodes);
referenceY = linspace(0,1,numberOfNodes)';
switch mode
    case 'uniform'
        stretch = [0,0];
    case 'mild_sinh'
        stretch = [0.45,0.35];
    case 'stress_sinh'
        stretch = [1.00,0.75];
    otherwise
        error('ipm:SixthOrderTestGridMode', ...
            'Unknown sixth-order test grid mode ''%s''.',mode);
end
if stretch(1) > 0
    x = sinh(stretch(1)*referenceX)/sinh(stretch(1));
else
    x = referenceX;
end
if stretch(2) > 0
    y = sinh(stretch(2)*referenceY)/sinh(stretch(2));
else
    y = referenceY;
end
isNonuniform = any(stretch > 0);
end

function probe = derivative_probe(X,Y)
ax = 0.35;
ay = 0.25;
kx = 3.1;
ky = 2.7;
theta = kx*X+ky*Y+0.31;
envelope = exp(ax*X+ay*Y);
sine = sin(theta);
cosine = cos(theta);
probe = struct();
probe.value = envelope.*sine;
probe.x = envelope.*(ax*sine+kx*cosine);
probe.y = envelope.*(ay*sine+ky*cosine);
probe.xx = envelope.*((ax^2-kx^2)*sine+2*ax*kx*cosine);
probe.yy = envelope.*((ay^2-ky^2)*sine+2*ay*ky*cosine);
end

function solution = nonzero_dirichlet_solution(X,Y)
ax = 0.3;
ay = 0.2;
kx = 2.2;
ky = 1.7;
amplitude = 0.15;
exponential = exp(ax*X+ay*Y);
oscillation = amplitude*sin(kx*X+0.37).*cos(ky*Y+0.21);
solution = struct('psi',exponential+oscillation, ...
    'source',-(ax^2+ay^2)*exponential+ ...
    (kx^2+ky^2)*oscillation);
end

function result = verify_weno7_linear_limit()
numberOfNodes = 41;
x = linspace(-1,1,numberOfNodes);
spacing = x(2)-x(1);
lineScales = [1;-0.6];
velocity = [0.75;-1.1];
idealErrors = zeros(1,8);
idealOptions = struct('lowerBoundary','extrapolate', ...
    'upperBoundary','extrapolate','extrapolationDegree',7, ...
    'epsilon',1e100,'alpha',abs(velocity));
productionOptions = idealOptions;
productionOptions.extrapolationDegree = 6;
productionErrors = zeros(1,7);
productionDegreeSevenInteriorError = NaN;
for degree = 0:7
    q = lineScales.*(x.^degree);
    idealNumerical = ipm.field.weno7FluxDerivative( ...
        q,velocity,1,spacing,idealOptions);
    if degree == 0
        derivative = zeros(size(x));
    else
        derivative = degree*x.^(degree-1);
    end
    exact = (velocity.*lineScales).*derivative;
    idealErrors(degree+1) = max(abs(idealNumerical-exact),[],'all');
    productionNumerical = ipm.field.weno7FluxDerivative( ...
        q,velocity,1,spacing,productionOptions);
    if degree <= 6
        productionErrors(degree+1) = max( ...
            abs(productionNumerical-exact),[],'all');
    else
        interior = 5:numberOfNodes-4;
        productionDegreeSevenInteriorError = max(abs( ...
            productionNumerical(:,interior)-exact(:,interior)),[],'all');
    end
end
tolerance = 1e-9;
assert(max(idealErrors) <= tolerance && ...
    max(productionErrors) <= tolerance && ...
    productionDegreeSevenInteriorError <= tolerance, ...
    'ipm:Weno7LinearLimitMonomials', ...
    ['The positive/negative WENO7 LF splits lost their ideal or production ' ...
    'polynomial linear limits: %.3e / %.3e / %.3e.'], ...
    max(idealErrors),max(productionErrors), ...
    productionDegreeSevenInteriorError);
result = struct('degrees',0:7,'idealErrors',idealErrors, ...
    'productionDegrees',0:6,'productionErrors',productionErrors, ...
    'productionDegreeSevenInteriorError', ...
    productionDegreeSevenInteriorError,'velocity',velocity, ...
    'tolerance',tolerance,'passed',true);
fprintf(['  WENO7 +/- linear-limit ideal / production errors: ' ...
    '%.3e / %.3e.\n'],max(idealErrors),max(productionErrors));
end

function result = verify_mapped_weno7(threshold)
alignments = {'node','half_node'};
criticalOrders = 0:3;
minimumTailOrder = Inf;
result = struct('threshold',threshold, ...
    'criticalOrders',criticalOrders, ...
    'alignments',{alignments},'normDomain','all nodes');
for alignmentIndex = 1:numel(alignments)
    alignment = alignments{alignmentIndex};
    if strcmp(alignment,'node')
        gridSizes = [37,55,81,121,181];
    else
        gridSizes = [38,56,82,122,182];
    end
    for criticalOrder = criticalOrders
        if criticalOrder == 0
            caseName = 'smooth';
        else
            caseName = sprintf('criticalOrder%d',criticalOrder);
        end
        caseReport = mapped_weno7_case( ...
            alignment,criticalOrder,gridSizes,threshold);
        result.(alignment).(caseName) = caseReport;
        minimumTailOrder = min(minimumTailOrder, ...
            min(caseReport.tailOrders,[],'all'));
    end
end
result.minimumTailOrder = minimumTailOrder;
result.passed = true;
end

function result = mapped_weno7_case( ...
        alignment,criticalOrder,gridSizes,threshold)
errors = zeros(2,numel(gridSizes));
h = 2./(gridSizes-1);
stretch = 0.75;
polynomialDegree = criticalOrder+1;
highDegreeCoefficient = 0.05;
options = struct('lowerBoundary','extrapolate', ...
    'upperBoundary','extrapolate','extrapolationDegree',6, ...
    'epsilon',1e-12,'alpha',1);

for level = 1:numel(gridSizes)
    numberOfNodes = gridSizes(level);
    xi = linspace(-1,1,numberOfNodes);
    x = sinh(stretch*xi)/sinh(stretch);
    metric = stretch*cosh(stretch*xi)/sinh(stretch);
    flux = 2+x.^polynomialDegree+ ...
        highDegreeCoefficient*x.^(polynomialDegree+7);
    exact = polynomialDegree*x.^(polynomialDegree-1)+ ...
        highDegreeCoefficient*(polynomialDegree+7)* ...
        x.^(polynomialDegree+6);

    % With velocity=metric and state=flux/metric, the mapped
    % Lax--Friedrichs flux is exactly the prescribed physical flux.
    numerical = ipm.field.weno7FluxDerivative( ...
        flux./metric,metric,metric,h(level),options);
    weights = ipm.mesh.quadrature6(x);
    errors(:,level) = line_norms(numerical-exact,weights);

    if strcmp(alignment,'node')
        assert(mod(numberOfNodes,2) == 1 && min(abs(x)) < 50*eps, ...
            'ipm:Weno7CriticalAlignment', ...
            'The requested critical point is not node aligned.');
    else
        middle = numberOfNodes/2;
        assert(mod(numberOfNodes,2) == 0 && x(middle) < 0 && ...
            x(middle+1) > 0 && ...
            abs(x(middle)+x(middle+1)) < 50*eps, ...
            'ipm:Weno7CriticalAlignment', ...
            'The requested critical point is not half-node aligned.');
    end
end

orders = refinement_orders(errors,h);
tailOrders = orders(:,end-1:end);
assert(all(isfinite(errors),'all') && all(errors > 0,'all') && ...
    all(diff(errors,1,2) < 0,'all') && ...
    all(isfinite(orders),'all') && ...
    all(tailOrders >= threshold,'all'), ...
    'ipm:Weno7MappedConvergence', ...
    ['Mapped WENO7 %s critical-order-%d refinement failed; minimum ' ...
    'tail order %.3f, required %.1f.'],alignment,criticalOrder, ...
    min(tailOrders,[],'all'),threshold);

result = struct('alignment',alignment,'criticalOrder',criticalOrder, ...
    'stretch',stretch,'gridSizes',gridSizes,'h',h, ...
    'metricNames',{{'L2','Linf'}},'errors',errors,'orders',orders, ...
    'tailOrders',tailOrders,'extrapolationDegree',6, ...
    'normDomain','all nodes','passed',true);
fprintf('  WENO7 %-9s critical order %d minimum tail: %.3f.\n', ...
    alignment,criticalOrder,min(tailOrders,[],'all'));
end

function result = verify_constant_free_stream()
modes = {'uniform','mild_sinh','stress_sinh'};
constantState = 2.75;
tolerance = 2e-11;
openError = zeros(size(modes));
closedError = zeros(size(modes));
for index = 1:numel(modes)
    ops = sixth_order_operators(25,modes{index},'open');
    u1 = 0.65+0.14*sin(1.2*ops.X).*cos(0.7*ops.Y);
    u2 = -0.18+0.11*cos(0.9*ops.X).*sin(1.3*ops.Y);
    rho = constantState*ones(size(ops.X));
    openRhs = ipm.field.transport(rho,u1,u2,ops,'open');
    closedRhs = ipm.field.transport(rho,u1,u2,ops,'closed');
    openError(index) = max(abs(openRhs),[],'all');
    closedError(index) = max(abs(closedRhs),[],'all');
end
assert(max([openError,closedError]) <= tolerance, ...
    'ipm:Weno7FreeStream', ...
    ['Mapped WENO7 failed to preserve a constant state; maximum ' ...
    'residual %.3e, tolerance %.3e.'], ...
    max([openError,closedError]),tolerance);
result = struct('modes',{modes},'constantState',constantState, ...
    'openError',openError,'closedError',closedError, ...
    'tolerance',tolerance,'passed',true);
fprintf('  WENO7 maximum constant-state residual: %.3e.\n', ...
    max([openError,closedError]));
end

function result = verify_grid_gate_rejection()
numberOfNodes = 17;
badStretch = 1.50;
overrides = struct('nx',numberOfNodes,'ny',numberOfNodes, ...
    'xlim',[-1,1],'ymax',1,'gridMode','stretched', ...
    'gridStretchAutomatic',false,'gridStretch',[badStretch,0], ...
    'transportBoundaryMode','closed','symmetryMode','half_plane', ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false);
config = ipm.config.resolve(ipm.config.sixthOrder(overrides));
reference = linspace(-1,1,numberOfNodes);
badX = sinh(badStretch*reference)/sinh(badStretch);
policy = ipm.mesh.sixthOrderPolicy();
quality = ipm.mesh.quality(badX,9, ...
    ones(size(badX)));
assert(quality.maximumAdjacentCellRatio > ...
    policy.maximumAdjacentCellRatio, ...
    'ipm:SixthOrderGridGateFixture', ...
    'The deliberately irregular grid does not exceed the private policy.');

identifier = '';
try
    ipm.mesh.build(config);
catch exception
    identifier = exception.identifier;
end

rollbackOverrides = struct('nx',33,'ny',25,'xlim',[-4,4], ...
    'ymax',4,'gridMode','uniform','gridStretchAutomatic',false, ...
    'gridStretch',[0,0],'adaptiveRemesh',true, ...
    'remeshMaximumCellRatio',10,'remeshConcentration',100, ...
    'initialCondition','degenerate','degeneratePower',4, ...
    'transportBoundaryMode','closed','symmetryMode','half_plane', ...
    'initialAnalyticRemesh',false,'saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false, ...
    'verbose',false);
rollbackConfig = ipm.config.resolve( ...
    ipm.config.sixthOrder(rollbackOverrides));
rollbackOps = ipm.mesh.build(rollbackConfig);
rollbackRho = ipm.field.initialDensity(rollbackOps,rollbackConfig.physics);
rollbackOps = ipm.evolve.initializeScaling(rollbackRho,rollbackOps);
[~,rollbackFlow] = ipm.evolve.rhs(rollbackRho,rollbackOps);
wallMetrics = ipm.diagnostics.peakResolution( ...
    max(rollbackFlow.source(1,:),0),rollbackOps.x, ...
    rollbackOps.rescaling.adaptiveLevels);
rollbackOps.rescaling.safetyPeakPoints = wallMetrics.areaPoints(1);
rollbackOps.rescaling.safetyLevelPoints = wallMetrics.gridPoints;
rollbackOps.rescaling.adaptiveTargetLevelPoints = 5*wallMetrics.gridPoints;
[rollbackProposal,~] = ipm.remesh.propose( ...
    rollbackOps,rollbackFlow,rollbackConfig,0,[]);
[rolledBackRho,rolledBackOps,rollbackInfo] = ipm.remesh.adapt( ...
    rollbackRho,rollbackOps,rollbackFlow,rollbackConfig);
rollbackExact = isequaln(rolledBackRho,rollbackRho) && ...
    isequaln(rolledBackOps,rollbackOps);

assert(strcmp(identifier,'ipm:SixthOrderGridCellRatio') && ...
    rollbackProposal.anyImproved && ...
    rollbackProposal.xAxisInfo.maximumCellRatio > ...
        policy.maximumAdjacentCellRatio && ...
    ~rollbackInfo.applied && rollbackExact && ...
    strcmp(rollbackInfo.transferFailureIdentifier, ...
        'ipm:SixthOrderGridCellRatio'), ...
    'ipm:SixthOrderGridGateRejection', ...
    ['The sixth-order grid gate did not reject and atomically roll back ' ...
    'an inadmissible adaptive candidate; direct/retry identifiers ' ...
    '''%s''/''%s'', exact rollback %d.'],identifier, ...
    rollbackInfo.transferFailureIdentifier,rollbackExact);
result = struct('maximumAdjacentCellRatio', ...
    quality.maximumAdjacentCellRatio,'policyLimit', ...
    policy.maximumAdjacentCellRatio,'errorIdentifier',identifier, ...
    'adaptiveCandidateCellRatio', ...
    rollbackProposal.xAxisInfo.maximumCellRatio, ...
    'adaptiveFailureIdentifier', ...
    rollbackInfo.transferFailureIdentifier, ...
    'adaptiveRollbackExact',rollbackExact, ...
    'passed',true);
fprintf('  grid gate rejected adjacent-cell ratio %.3f (> %.3f).\n', ...
    quality.maximumAdjacentCellRatio,policy.maximumAdjacentCellRatio);
fprintf('  invalid adaptive grid exact rollback: %d (%s).\n', ...
    rollbackExact,rollbackInfo.transferFailureIdentifier);
end

function result = verify_width_eight_remap()
oldAxis = smooth_custom_axis(43);
newAxis = sinh_axis(38,0.63);
powers = 0:7;
oldPolynomials = oldAxis.^powers;
exactPolynomials = newAxis.^powers;
rawOptions = struct('stencilWidth',8);
[interpolated,rawInfo] = ipm.remesh.interpolate( ...
    oldAxis,oldPolynomials,newAxis,rawOptions);
polynomialError = max(abs(interpolated-exactPolynomials),[],'all');

signals = [3.25+zeros(size(oldAxis)), ...
    exp(0.7*oldAxis).*cos(1.1*oldAxis)];
conservativeOptions = struct('stencilWidth',8, ...
    'conservation','constant');
[conservative,conservativeInfo] = ipm.remesh.interpolate( ...
    oldAxis,signals,newAxis,conservativeOptions);
massScale = max(abs(conservativeInfo.massOld),1);
relativeMassDefect = max(abs( ...
    conservativeInfo.massDefectAfter)./massScale);
constantError = max(abs(conservative(:,1)-3.25));

exactnessTolerance = 2e-10;
massTolerance = 5e-13;
assert(rawInfo.stencilWidth == 8 && ...
    rawInfo.polynomialDegree == 7 && ...
    polynomialError <= exactnessTolerance && ...
    relativeMassDefect <= massTolerance && ...
    constantError <= massTolerance, ...
    'ipm:SixthOrderWidthEightRemap', ...
    ['Width-eight remap failed polynomial/conservation contracts: ' ...
    'polynomial %.3e, relative mass %.3e, constant %.3e.'], ...
    polynomialError,relativeMassDefect,constantError);
result = struct('stencilWidth',rawInfo.stencilWidth, ...
    'polynomialDegree',rawInfo.polynomialDegree, ...
    'polynomialError',polynomialError, ...
    'relativeMassDefect',relativeMassDefect, ...
    'constantError',constantError, ...
    'exactnessTolerance',exactnessTolerance, ...
    'massTolerance',massTolerance,'passed',true);
fprintf(['  width-eight remap polynomial / relative-mass errors: ' ...
    '%.3e / %.3e.\n'],polynomialError,relativeMassDefect);
end

function result = verify_stretched_grid_remap_mass()
numberOfNodes = 25;
config = sixth_order_config(numberOfNodes,'stress_sinh','closed');
ops = ipm.mesh.build(config);
ops.rescaling.pinX = 0;
rho = 2+exp(0.35*ops.X).*(1+0.08*cos(1.1*ops.Y));

referenceX = linspace(-1,1,numberOfNodes);
referenceY = linspace(0,1,numberOfNodes)';
proposal = struct( ...
    'x',sinh(0.65*referenceX)/sinh(0.65), ...
    'y',sinh(0.50*referenceY)/sinh(0.50));
[transferred,newOps] = ipm.remesh.transfer(rho,ops,config,proposal);
oldMass = sum(rho.*ops.integrationWeights,'all');
newMass = sum(transferred.*newOps.integrationWeights,'all');
relativeMassDefect = abs(newMass-oldMass)/max(abs(oldMass),1);
gridDefect = [max(abs(newOps.x-proposal.x)); ...
    max(abs(newOps.y-proposal.y))];
gridChange = [max(abs(newOps.x-ops.x));max(abs(newOps.y-ops.y))];

expectedBoundary = ipm.remesh.interpolate( ...
    ops.x,rho([1,end],:),proposal.x, ...
    struct('sampleDimension',2,'conservation','none','stencilWidth',8));
oldBoundaryMass = rho([1,end],:)*ops.integrationHx(:);
newBoundaryMass = expectedBoundary*newOps.integrationHx(:);
expectedBoundary = expectedBoundary+ ...
    (oldBoundaryMass-newBoundaryMass)/sum(newOps.integrationHx);
boundaryResidual = oldBoundaryMass- ...
    expectedBoundary*newOps.integrationHx(:);
expectedBoundary = expectedBoundary+ ...
    boundaryResidual/sum(newOps.integrationHx);
boundaryTraceDefect = max(abs( ...
    transferred([1,end],:)-expectedBoundary),[],'all');
tolerance = 5e-13;
assert(relativeMassDefect <= tolerance && ...
    all(gridDefect <= 100*eps) && all(gridChange > 1e-3) && ...
    isequal(size(transferred),[numberOfNodes,numberOfNodes]) && ...
    all(isfinite(transferred),'all') && ...
    boundaryTraceDefect <= tolerance, ...
    'ipm:SixthOrderIntegratedRemeshMass', ...
    ['A sixth-order remesh from an analytic stretched grid violated its ' ...
    'candidate/mass/trace contract: relative mass %.3e, grid defect %s, ' ...
    'grid change %s, boundary trace %.3e.'],relativeMassDefect, ...
    mat2str(gridDefect,4),mat2str(gridChange,4),boundaryTraceDefect);
result = struct('oldStretch',[1.00,0.75], ...
    'newStretch',[0.65,0.50], ...
    'oldMass',oldMass,'newMass',newMass, ...
    'relativeMassDefect',relativeMassDefect, ...
    'gridDefect',gridDefect,'gridChange',gridChange, ...
    'boundaryTraceDefect',boundaryTraceDefect, ...
    'tolerance',tolerance,'passed',true);
fprintf(['  stretched-grid remap relative mass / boundary trace: ' ...
    '%.3e / %.3e.\n'],relativeMassDefect,boundaryTraceDefect);
end

function ops = sixth_order_operators(numberOfNodes,mode,boundaryMode)
config = sixth_order_config(numberOfNodes,mode,boundaryMode);
ops = ipm.mesh.build(config);
end

function config = sixth_order_config(numberOfNodes,mode,boundaryMode)
switch mode
    case 'uniform'
        gridMode = 'uniform';
        stretch = [0,0];
    case 'mild_sinh'
        gridMode = 'stretched';
        stretch = [0.45,0.35];
    case 'stress_sinh'
        gridMode = 'stretched';
        stretch = [1.00,0.75];
    otherwise
        error('ipm:SixthOrderTestGridMode', ...
            'Unknown sixth-order test grid mode ''%s''.',mode);
end
overrides = struct('nx',numberOfNodes,'ny',numberOfNodes, ...
    'xlim',[-1,1],'ymax',1,'gridMode',gridMode, ...
    'gridStretchAutomatic',false,'gridStretch',stretch, ...
    'transportBoundaryMode',boundaryMode, ...
    'symmetryMode','half_plane','adaptiveRemesh',false, ...
    'initialAnalyticRemesh',false,'saveResults',false, ...
    'makePlots',false,'livePlot',false,'writeVideo',false, ...
    'verbose',false);
config = ipm.config.resolve(ipm.config.sixthOrder(overrides));
assert(strcmp(config.transport.spatialDiscretization,'sixth_order') && ...
    strcmp(config.transport.transportScheme,'weno7_fd') && ...
    strcmp(config.time.timeIntegrator,'rk6') && ...
    strcmp(config.remesh.remeshTransferScheme,'sixth_order'), ...
    'ipm:SixthOrderTestTuple', ...
    'The core verifier did not resolve the complete sixth-order tuple.');
end

function values = full_node_norms(errorValues,weights)
weightSum = sum(weights,'all');
values = [sqrt(sum(weights.*abs(errorValues).^2,'all')/weightSum); ...
    max(abs(errorValues),[],'all')];
end

function values = line_norms(errorValues,weights)
weights = weights(:)';
errorValues = errorValues(:)';
values = [sqrt(sum(weights.*abs(errorValues).^2)/sum(weights)); ...
    max(abs(errorValues))];
end

function orders = refinement_orders(errors,h)
orders = log(errors(:,1:end-1)./errors(:,2:end)) ./ ...
    log(h(1:end-1)./h(2:end));
end

function axis = sinh_axis(numberOfNodes,stretch)
reference = linspace(-1,1,numberOfNodes)';
axis = sinh(stretch*reference)/sinh(stretch);
end

function axis = smooth_custom_axis(numberOfNodes)
reference = linspace(-1,1,numberOfNodes)';
axis = reference+0.08*sin(pi*reference);
axis([1,end]) = [-1,1];
end
