function report = physicalConvergence()
%IPMTESTS.SIXTH.PHYSICALCONVERGENCE Unforced production gate.
%   IPM.SOLVE advances the complete opt-in sixth-order tuple on uniform and
%   fixed sinh nested grids.  Adjacent-grid restrictions measure full-node
%   L2/Linf self-convergence without manufactured forcing or remeshing;
%   analytic coordinates, nonuniformity, and closed-boundary mass drift are
%   independently gated at every level.

threshold = 5.5;
gridSizes = [17,33,65,129];
stepCounts = [8,16,32,64];
finalTime = 0.04;
assert(all(gridSizes(2:end) == 2*gridSizes(1:end-1)-1) && ...
    all(stepCounts(2:end) == 2*stepCounts(1:end-1)), ...
    'ipm:SixthOrderPhysicalRefinement', ...
    'Physical grids and step counts must halve h and dt exactly.');

fprintf(['Running unforced sixth-order physical self-convergence ' ...
    '(required order %.1f)...\n'],threshold);
report = struct('threshold',threshold,'gridSizes',gridSizes, ...
    'stepCounts',stepCounts,'finalTime',finalTime);
report.uniform = verify_family( ...
    'uniform',[0,0],gridSizes,stepCounts,finalTime,threshold);
report.fixedSinh = verify_family( ...
    'fixed_sinh',[0.75,0.50],gridSizes,stepCounts, ...
    finalTime,threshold);
report.minimumOrder = min([report.uniform.minimumOrder, ...
    report.fixedSinh.minimumOrder]);
report.passed = report.uniform.passed && report.fixedSinh.passed;
fprintf(['Unforced sixth-order physical convergence passed; minimum ' ...
    'uniform/fixed-sinh orders %.3f / %.3f.\n'], ...
    report.uniform.minimumOrder,report.fixedSinh.minimumOrder);
end

function family = verify_family( ...
        name,stretch,gridSizes,stepCounts,finalTime,threshold)
levelCount = numel(gridSizes);
solutions = cell(1,levelCount);
grids = cell(1,levelCount);
weights = cell(1,levelCount);
levelRuntime = zeros(1,levelCount);
stepsUsed = zeros(1,levelCount);
massDrift = zeros(1,levelCount);
mappingErrors = zeros(2,levelCount);
cellRatios = zeros(2,levelCount);
stopReasons = cell(1,levelCount);
started = tic;

for level = 1:levelCount
    options = physical_options( ...
        gridSizes(level),stretch,finalTime,stepCounts(level));
    levelTimer = tic;
    result = ipm.solve(options);
    levelRuntime(level) = toc(levelTimer);
    assert_complete_tuple(result.config);

    stopReasons{level} = result.state.stopReason;
    stepsUsed(level) = result.state.steps;
    assert(strcmp(stopReasons{level},'final_time') && ...
        stepsUsed(level) == stepCounts(level), ...
        'ipm:SixthOrderPhysicalEarlyStop', ...
        ['The %s n=%d run stopped as ''%s'' after %d steps; expected ' ...
        'final_time after %d prescribed steps.'],name,gridSizes(level), ...
        stopReasons{level},stepsUsed(level),stepCounts(level));
    assert(abs(result.state.physicalTime-finalTime) <= ...
        1e3*eps(max(1,finalTime)) && result.grid.remeshCount == 0 && ...
        all(isfinite(result.state.rho),'all'), ...
        'ipm:SixthOrderPhysicalState', ...
        'The %s n=%d run violated its finite fixed-grid clock contract.', ...
        name,gridSizes(level));

    solutions{level} = result.state.rho;
    grids{level} = struct('x',result.grid.x,'y',result.grid.y);
    [expectedX,expectedY] = expected_grid(gridSizes(level),stretch);
    mappingErrors(:,level) = [ ...
        max(abs(result.grid.x-expectedX)); ...
        max(abs(result.grid.y-expectedY))];
    xFaces = diff(result.grid.x);
    yFaces = diff(result.grid.y);
    cellRatios(:,level) = [maximum_adjacent_ratio(xFaces); ...
        maximum_adjacent_ratio(yFaces)];
    coordinateScale = max([1,max(abs(expectedX)),max(abs(expectedY))]);
    assert(all(mappingErrors(:,level) <= 100*eps(coordinateScale)) && ...
        (~any(stretch > 0) || all(cellRatios(:,level) > 1+1e-3)), ...
        'ipm:SixthOrderPhysicalGridFixture', ...
        ['The %s n=%d physical grid does not match its requested ' ...
        'analytic mapping or one stretched axis is effectively uniform; ' ...
        'defects %s, ratios %s.'],name,gridSizes(level), ...
        mat2str(mappingErrors(:,level),4), ...
        mat2str(cellRatios(:,level),4));
    config = ipm.config.resolve(options);
    assert_complete_tuple(config);
    ops = ipm.mesh.build(config);
    weights{level} = ops.integrationWeights;
    assert(isequal(size(weights{level}),size(solutions{level})) && ...
        all(weights{level} > 0,'all'), ...
        'ipm:SixthOrderPhysicalWeights', ...
        'The %s n=%d all-node norm is unavailable.', ...
        name,gridSizes(level));
    massDrift(level) = result.history.common.massDrift(end);
    fprintf('  %-10s n=%3d, steps=%3d, runtime %.3fs.\n', ...
        name,gridSizes(level),stepsUsed(level),levelRuntime(level));
end

pairCount = levelCount-1;
errors = zeros(2,pairCount);
gridNestingError = zeros(2,pairCount);
roundoffFloor = zeros(2,pairCount);
for level = 1:pairCount
    coarse = solutions{level};
    restrictedFine = solutions{level+1}(1:2:end,1:2:end);
    assert(isequal(size(coarse),size(restrictedFine)), ...
        'ipm:SixthOrderPhysicalRestriction', ...
        'The %s n=%d and n=%d fields are not exactly nested.', ...
        name,gridSizes(level),gridSizes(level+1));

    coarseGrid = grids{level};
    fineGrid = grids{level+1};
    gridNestingError(:,level) = [ ...
        max(abs(coarseGrid.x-fineGrid.x(1:2:end))); ...
        max(abs(coarseGrid.y-fineGrid.y(1:2:end)))];
    gridScale = max([1,max(abs(fineGrid.x)),max(abs(fineGrid.y))]);
    assert(all(gridNestingError(:,level) <= 100*eps(gridScale)), ...
        'ipm:SixthOrderPhysicalGridNesting', ...
        'The %s n=%d and n=%d coordinates are not nested.', ...
        name,gridSizes(level),gridSizes(level+1));

    difference = coarse-restrictedFine;
    errors(:,level) = full_node_norms(difference,weights{level});
    solutionScale = max([ ...
        full_node_norms(coarse,weights{level}), ...
        full_node_norms(restrictedFine,weights{level})],[],2);
    roundoffFloor(:,level) = 1e4* ...
        eps(max(ones(size(solutionScale)),solutionScale));
end

assert(all(isfinite(errors),'all') && ...
    all(errors > roundoffFloor,'all') && ...
    all(diff(errors,1,2) < 0,'all') && ...
    max(abs(massDrift)) <= 5e-12, ...
    'ipm:SixthOrderPhysicalDecrease', ...
    ['The %s adjacent-grid differences must be finite, above ' ...
    'roundoff, and monotonically decreasing, with closed-boundary mass ' ...
    'drift at most 5e-12; observed %.3e.'],name,max(abs(massDrift)));
orders = log2(errors(:,1:end-1)./errors(:,2:end));
assert(all(orders >= threshold,'all'), ...
    'ipm:SixthOrderPhysicalOrder', ...
    ['The %s unforced physical self-convergence fell below %.1f; ' ...
    'L2/Linf rows %s.'],name,threshold,mat2str(orders,6));

family = struct('name',name,'gridStretch',stretch, ...
    'gridSizes',gridSizes,'stepCounts',stepCounts, ...
    'dt',finalTime./stepCounts,'finalTime',finalTime, ...
    'metricNames',{{'L2','Linf'}},'errors',errors, ...
    'orders',orders,'minimumOrder',min(orders,[],'all'), ...
    'gridNestingError',gridNestingError, ...
    'mappingErrors',mappingErrors,'cellRatios',cellRatios, ...
    'roundoffFloor',roundoffFloor,'stepsUsed',stepsUsed, ...
    'stopReasons',{stopReasons},'massDrift',massDrift, ...
    'levelRuntime',levelRuntime,'totalRuntime',toc(started), ...
    'normDomain','all nodes including boundaries', ...
    'comparison','adjacent nested restriction; no finest-grid oracle', ...
    'equation','unforced physical IPM','entryPoint','ipm.solve', ...
    'spatialDiscretization','sixth_order', ...
    'transportScheme','weno7_fd','timeIntegrator','rk6', ...
    'remeshTransferScheme','sixth_order', ...
    'adaptiveRemesh',false,'forcing','none','passed',true);
fprintf('  %-10s L2/Linf orders %s; minimum %.3f.\n', ...
    name,mat2str(orders,5),family.minimumOrder);
end

function [x,y] = expected_grid(gridSize,stretch)
referenceX = linspace(-1,1,gridSize);
referenceY = linspace(0,1,gridSize)';
if stretch(1) > 0
    x = sinh(stretch(1)*referenceX)/sinh(stretch(1));
else
    x = referenceX;
end
if stretch(2) > 0
    y = sinh(stretch(2)*referenceY)/sinh(stretch(2));
else
    y = referenceY;
end
end

function ratio = maximum_adjacent_ratio(faces)
ratio = max(max(faces(2:end)./faces(1:end-1), ...
    faces(1:end-1)./faces(2:end)));
end

function options = physical_options( ...
        gridSize,stretch,finalTime,stepCount)
if any(stretch > 0)
    gridMode = 'stretched';
else
    gridMode = 'uniform';
end
overrides = struct('nx',gridSize,'ny',gridSize, ...
    'xlim',[-1,1],'ymax',1,'gridMode',gridMode, ...
    'gridStretchAutomatic',false,'gridStretch',stretch, ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','closed', ...
    'wallTransportMode','conservative_flux', ...
    'symmetryMode','double_odd_omega','rescalingMode','physical', ...
    'initialCondition',@smooth_initial_density, ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'finalTime',finalTime,'physicalFinalTime',Inf, ...
    'maxDt',finalTime/stepCount,'minDt',1e-14,'cfl',0.2, ...
    'maxSteps',stepCount+2,'outputEvery',finalTime, ...
    'storeSnapshots',false,'saveResults',false,'makePlots',false, ...
    'livePlot',false,'writeVideo',false,'verbose',false);
options = ipm.config.sixthOrder(overrides);
end

function assert_complete_tuple(config)
assert(strcmp(config.transport.spatialDiscretization,'sixth_order') && ...
    strcmp(config.transport.transportScheme,'weno7_fd') && ...
    strcmp(config.time.timeIntegrator,'rk6') && ...
    strcmp(config.remesh.remeshTransferScheme,'sixth_order'), ...
    'ipm:SixthOrderPhysicalTuple', ...
    'The physical verifier did not run the complete sixth-order tuple.');
end

function rho = smooth_initial_density(X,Y)
% Smooth even density with positive odd wall source for x>0.
g = Y.*(1-Y);
H = pi^2*g+2;
rho = 2+(H/pi).*cos(pi*(X+1));
end

function values = full_node_norms(field,weights)
weightSum = sum(weights,'all');
weightedSquare = sum(weights.*abs(field).^2,'all');
assert(weightSum > 0 && weightedSquare >= 0, ...
    'ipm:SixthOrderPhysicalNorm', ...
    'The all-node weighted norm is not positive.');
values = [sqrt(weightedSquare/weightSum);max(abs(field),[],'all')];
end
