function report = time()
%IPMTESTS.SIXTH.TIME Complete RK6(5) order certificate.
%   Enumerates every non-plane rooted tree through order six (37 main
%   conditions) and every tree through order five (17 embedded conditions),
%   independently measures the main row on a nonlinear exact ODE, and
%   compares the production density/anisotropic-scale RK6 step with a
%   direct tableau oracle at nonzero dynamic rates.

threshold = 5.5;
tableau = ipm.evolve.rk6Tableau();
fprintf(['Running sixth-order time verification (nonlinear-ODE tail ' ...
    'order at least %.1f)...\n'],threshold);
report = struct('threshold',threshold,'tableauSource',tableau.source);
report.orderConditions = verify_order_conditions(tableau);
report.nonlinearOde = verify_nonlinear_ode(tableau,threshold);
report.productionCoupling = verify_production_coupling();
report.passed = true;
fprintf(['Sixth-order time verification passed: 37 main / 17 embedded ' ...
    'conditions; minimum nonlinear-ODE tail %.3f.\n'], ...
    min(report.nonlinearOde.tailOrders));
end

function result = verify_order_conditions(tableau)
A = tableau.A;
b = tableau.b(:);
bEmbedded = tableau.bEmbedded(:);
stages = tableau.stages;
tolerance = 2e-12;
assert(tableau.order == 6 && tableau.embeddedOrder == 5 && ...
    stages == 8 && isequal(size(A),[8,8]) && ...
    numel(b) == stages && numel(bEmbedded) == stages && ...
    all(abs(triu(A)) <= 50*eps,'all') && ...
    max(abs(tableau.c(:)-A*ones(stages,1))) <= 50*eps, ...
    'ipm:Rk6TableauStructure', ...
    ['The RK6 tableau must be an explicit, internally consistent ' ...
    'eight-stage 6(5) pair.']);

[trees,countByOrder] = enumerate_rooted_trees(6);
expectedCounts = [1,1,2,4,9,20];
assert(isequal(countByOrder,expectedCounts) && numel(trees) == 37, ...
    'ipm:Rk6RootedTreeEnumeration', ...
    'The rooted-tree oracle did not enumerate all 37 trees through order 6.');

[mainWeights,targets,densities,stageWeights] = ...
    elementary_weights(A,b,trees);
[embeddedWeights,~,~,~] = elementary_weights( ...
    A,bEmbedded,trees,stageWeights,densities);
mainResiduals = mainWeights-targets;
embeddedMask = [trees.order] <= tableau.embeddedOrder;
embeddedResiduals = embeddedWeights(embeddedMask)-targets(embeddedMask);
embeddedSixthResiduals = embeddedWeights(~embeddedMask)- ...
    targets(~embeddedMask);
assert(max(abs(mainResiduals)) <= tolerance, ...
    'ipm:Rk6RootedTreeConditions', ...
    ['The main RK row failed one of all 37 rooted-tree conditions; ' ...
    'maximum residual %.3e.'],max(abs(mainResiduals)));
assert(nnz(embeddedMask) == 17 && ...
    max(abs(embeddedResiduals)) <= tolerance && ...
    max(abs(embeddedSixthResiduals)) > 1e-8, ...
    'ipm:Rk6EmbeddedRootedTreeConditions', ...
    ['The embedded row must satisfy all 17 conditions through order ' ...
    'five and remain genuinely fifth order.']);

result = struct('countByOrder',countByOrder, ...
    'expectedCountByOrder',expectedCounts,'conditionCount',37, ...
    'treeCodes',{{trees.code}},'treeOrders',[trees.order], ...
    'densities',densities,'targets',targets, ...
    'mainWeights',mainWeights,'mainResiduals',mainResiduals, ...
    'maximumMainResidual',max(abs(mainResiduals)), ...
    'embeddedConditionCount',nnz(embeddedMask), ...
    'embeddedWeights',embeddedWeights(embeddedMask), ...
    'embeddedResiduals',embeddedResiduals, ...
    'maximumEmbeddedResidual',max(abs(embeddedResiduals)), ...
    'embeddedSixthResiduals',embeddedSixthResiduals, ...
    'tolerance',tolerance,'passed',true);
fprintf('  rooted-tree residuals (37 main / 17 embedded): %.3e / %.3e.\n', ...
    result.maximumMainResidual,result.maximumEmbeddedResidual);
end

function result = verify_nonlinear_ode(tableau,threshold)
% y'=1+y^2 has exact solution tan(t+atan(y0)).
initialValue = 0.2;
finalTime = 0.4;
stepCounts = [1,2,4,8];
exact = tan(finalTime+atan(initialValue));
rhs = @(state,time)1+state.^2+0*time;
errors = zeros(size(stepCounts));
for level = 1:numel(stepCounts)
    numerical = advance_fixed_steps( ...
        initialValue,finalTime,stepCounts(level),rhs,tableau);
    errors(level) = abs(numerical-exact);
end
orders = log2(errors(1:end-1)./errors(2:end));
tailOrders = orders(end-1:end);
roundoffFloor = 1e3*eps(max(1,abs(exact)));
assert(all(isfinite(errors)) && all(errors > roundoffFloor) && ...
    all(diff(errors) < 0) && all(tailOrders >= threshold), ...
    'ipm:Rk6NonlinearOdeConvergence', ...
    ['Nonlinear exact-ODE RK6 refinement failed; errors %s, orders ' ...
    '%s, required tail %.1f.'],mat2str(errors,8), ...
    mat2str(orders,6),threshold);
result = struct('equation','y''=1+y^2', ...
    'exactSolution','tan(t+atan(y0))','initialValue',initialValue, ...
    'finalTime',finalTime,'stepCounts',stepCounts, ...
    'dt',finalTime./stepCounts,'errors',errors,'orders',orders, ...
    'tailOrders',tailOrders,'roundoffFloor',roundoffFloor, ...
    'passed',true);
fprintf('  nonlinear exact-ODE tail orders: %s.\n', ...
    mat2str(tailOrders,6));
end

function result = verify_production_coupling()
% Exercise the actual density+anisotropic-scale RK6 stage packing. The
% oracle shares production spatial RHS evaluations but independently owns
% tableau assembly, scale packing, rate equations, and final reconstruction.
overrides = struct('nx',25,'ny',17,'xlim',[-2,2],'ymax',2, ...
    'gridMode','stretched','gridStretchAutomatic',false, ...
    'gridStretch',[0.7,0.5], ...
    'farBoundaryMode','dirichlet_zero', ...
    'transportBoundaryMode','open','symmetryMode','half_plane', ...
    'rescalingMode','dynamic','dynamicScaleGeometry','anisotropic', ...
    'anisotropicGaugeMode','fixed','anisotropicFixedCX',0.35, ...
    'anisotropicFixedCY',-0.2,'anisotropicFixedCOmega',0.1, ...
    'anisotropicFixedCR',0.05, ...
    'initialCondition',@(X,Y)2+exp(-((X-0.55).^2+0.7*Y.^2)), ...
    'adaptiveRemesh',false,'initialAnalyticRemesh',false, ...
    'saveResults',false,'makePlots',false,'livePlot',false, ...
    'writeVideo',false,'verbose',false);
config = ipm.config.resolve(ipm.config.sixthOrder(overrides));
ops = ipm.mesh.build(config);
rho = ipm.field.initialDensity(ops,config.physics);
ops = ipm.evolve.initializeScaling(rho,ops);
scale = struct('logC_l',0,'logC_x',0,'logC_y',0, ...
    'logC_omega',0,'physicalTime',0,'X_shift',0,'canonicalTime',0);
fixedRates = [0.35,-0.2,0.1,0.05];
[u1,u2] = ipm.field.velocity(rho,ops,1);
[closedRhs,~,~,~,closedConservativeSource] = ...
    ipm.evolve.assembleRhs(rho,u1,u2, ...
        fixedRates(1),fixedRates(2),fixedRates(3),fixedRates(4), ...
        ops,'closed');
mass = sum(rho.*ops.integrationWeights,'all');
closedMassRate = sum(closedRhs.*ops.integrationWeights,'all');
closedMassResidual = abs( ...
    closedMassRate-closedConservativeSource*mass) / ...
    max(abs(closedConservativeSource*mass),1);
dt = 0.0125;
[rhoActual,flowActual,scaleActual] = ...
    ipm.evolve.stepRk6(rho,dt,ops,scale);
[rhoOracle,flowOracle,scaleOracle] = ...
    rk6_anisotropic_oracle(rho,dt,ops,scale);

productionError = max([max(abs(rhoActual-rhoOracle),[],'all'), ...
    max(abs(pack_anisotropic_scale(scaleActual)- ...
        pack_anisotropic_scale(scaleOracle))), ...
    abs(flowActual.aspect-flowOracle.aspect), ...
    abs(flowActual.poissonSolveInfo.kappa- ...
        flowOracle.poissonSolveInfo.kappa)]);
expectedAspect = exp(scaleActual.logC_y-scaleActual.logC_l);
aspectError = max([abs(flowActual.aspect-expectedAspect), ...
    abs(flowActual.poissonSolveInfo.kappa-expectedAspect)]);
rateMagnitude = max(abs([flowActual.c_x,flowActual.c_y, ...
    flowActual.c_omega,flowActual.c_r]));
tolerance = 5e-12;
assert(productionError <= tolerance && aspectError <= 5e-13 && ...
    rateMagnitude > 1e-6 && closedMassResidual <= 5e-13, ...
    'ipm:Rk6ProductionScaleCoupling', ...
    ['The production RK6 density/anisotropic-scale stage coupling ' ...
    'or sixth-order closed source/mass contract failed: step %.3e, ' ...
    'aspect %.3e, rate %.3e, mass %.3e.'],productionError,aspectError, ...
    rateMagnitude,closedMassResidual);
result = struct('dt',dt,'productionError',productionError, ...
    'aspectError',aspectError,'rateMagnitude',rateMagnitude, ...
    'closedMassResidual',closedMassResidual, ...
    'fixedRates',fixedRates, ...
    'tolerance',tolerance,'passed',true);
fprintf(['  production RK6 anisotropic coupling / aspect errors: ' ...
    '%.3e / %.3e; closed mass residual %.3e.\n'], ...
    productionError,aspectError,closedMassResidual);
end

function [rhoNew,flow,scaleNew] = ...
        rk6_anisotropic_oracle(rho,dt,ops,scale)
tableau = ipm.evolve.rk6Tableau();
z = pack_anisotropic_scale(scale);
densityRates = cell(tableau.stages,1);
scaleRates = cell(tableau.stages,1);
for stage = 1:tableau.stages
    stageRho = rho;
    stageScaleVector = z;
    for previous = 1:stage-1
        stageRho = stageRho+dt*tableau.A(stage,previous)* ...
            densityRates{previous};
        stageScaleVector = stageScaleVector + ...
            dt*tableau.A(stage,previous)*scaleRates{previous};
    end
    stageScale = unpack_anisotropic_scale(stageScaleVector);
    [densityRates{stage},stageFlow] = ...
        ipm.evolve.flow(stageRho,ops,stageScale);
    scaleRates{stage} = anisotropic_scale_rate( ...
        stageScaleVector,stageFlow);
end
rhoNew = rho;
zNew = z;
for stage = 1:tableau.stages
    rhoNew = rhoNew+dt*tableau.b(stage)*densityRates{stage};
    zNew = zNew+dt*tableau.b(stage)*scaleRates{stage};
end
scaleNew = unpack_anisotropic_scale(zNew);
[~,flow] = ipm.evolve.flow(rhoNew,ops,scaleNew);
end

function z = pack_anisotropic_scale(scale)
z = [scale.logC_l;scale.logC_y;scale.logC_omega; ...
    scale.physicalTime;scale.X_shift;scale.canonicalTime];
end

function scale = unpack_anisotropic_scale(z)
scale = struct('logC_l',z(1),'logC_x',z(1),'logC_y',z(2), ...
    'logC_omega',z(3),'physicalTime',z(4),'X_shift',z(5), ...
    'canonicalTime',z(6));
end

function rate = anisotropic_scale_rate(z,flow)
rate = [flow.c_x;flow.c_y;flow.c_omega; ...
    flow.timeSpeed*exp(z(3)-z(1)); ...
    flow.c_x*z(5)+flow.c_r;flow.timeSpeed];
end

function [trees,countByOrder] = enumerate_rooted_trees(maximumOrder)
prototype = struct('code','','order',0,'children',zeros(1,0));
trees = prototype;
trees.code = '()';
trees.order = 1;
countByOrder = zeros(1,maximumOrder);
countByOrder(1) = 1;
for order = 2:maximumOrder
    forests = enumerate_forests([trees.order],order-1,1);
    newTrees = repmat(prototype,numel(forests),1);
    for index = 1:numel(forests)
        children = forests{index};
        childCodes = {trees(children).code};
        newTrees(index).code = ['(',strjoin(childCodes,''),')'];
        newTrees(index).order = order;
        newTrees(index).children = children;
    end
    [~,permutation] = sort({newTrees.code});
    newTrees = newTrees(permutation);
    countByOrder(order) = numel(newTrees);
    trees = [trees;newTrees]; %#ok<AGROW>
end
end

function forests = enumerate_forests(treeOrders,remaining,startIndex)
if remaining == 0
    forests = {zeros(1,0)};
    return;
end
forests = cell(0,1);
for treeIndex = startIndex:numel(treeOrders)
    treeOrder = treeOrders(treeIndex);
    if treeOrder > remaining
        continue;
    end
    tails = enumerate_forests( ...
        treeOrders,remaining-treeOrder,treeIndex);
    for tailIndex = 1:numel(tails)
        forests{end+1,1} = [treeIndex,tails{tailIndex}]; %#ok<AGROW>
    end
end
end

function [weights,targets,densities,stageWeights] = ...
        elementary_weights(A,b,trees,stageWeights,densities)
numberOfTrees = numel(trees);
numberOfStages = size(A,1);
if nargin < 4 || isempty(stageWeights)
    stageWeights = cell(numberOfTrees,1);
    densities = zeros(1,numberOfTrees);
    for treeIndex = 1:numberOfTrees
        children = trees(treeIndex).children;
        if isempty(children)
            stageWeights{treeIndex} = ones(numberOfStages,1);
            densities(treeIndex) = 1;
        else
            value = ones(numberOfStages,1);
            for childIndex = children
                value = value.*(A*stageWeights{childIndex});
            end
            stageWeights{treeIndex} = value;
            densities(treeIndex) = trees(treeIndex).order* ...
                prod(densities(children));
        end
    end
end
weights = zeros(1,numberOfTrees);
for treeIndex = 1:numberOfTrees
    weights(treeIndex) = b(:)'*stageWeights{treeIndex};
end
targets = 1./densities;
end

function state = advance_fixed_steps( ...
        initial,finalTime,stepCount,rhs,tableau)
dt = finalTime/stepCount;
state = initial;
for step = 1:stepCount
    time = (step-1)*dt;
    rates = cell(tableau.stages,1);
    for stage = 1:tableau.stages
        stageState = state;
        for previous = 1:stage-1
            coefficient = tableau.A(stage,previous);
            if coefficient ~= 0
                stageState = stageState+dt*coefficient*rates{previous};
            end
        end
        rates{stage} = rhs(stageState,time+tableau.c(stage)*dt);
    end
    for stage = 1:tableau.stages
        if tableau.b(stage) ~= 0
            state = state+dt*tableau.b(stage)*rates{stage};
        end
    end
end
end
