function window = bulkGradientWindow(rhoX,rhoY,ops,settings)
%IPM.EVOLVE.BULKGRADIENTWINDOW Fixed compact local gradient L2 functional.

expectedSize = [numel(ops.y),numel(ops.x)];
if ~isnumeric(rhoX) || ~isreal(rhoX) || ...
        ~isequal(size(rhoX),expectedSize) || any(~isfinite(rhoX),'all') || ...
        ~isnumeric(rhoY) || ~isreal(rhoY) || ...
        ~isequal(size(rhoY),expectedSize) || any(~isfinite(rhoY),'all')
    error('ipm:OmegaGaugeBulkGradient', ...
        'The bulk-gradient gauge requires finite rho_X and rho_Y arrays.');
end
centerX = settings.transportAnchorX;
centerY = 0;
radius = settings.omegaGaugeWindowRadius;
anchorTolerance = 100*eps(max(1,abs(centerX)));
if ~isfinite(centerX) || abs(centerX-1) > anchorTolerance
    error('ipm:OmegaGaugeWindowAnchor', ...
        'The fixed anchor-bulk window must be centered at X=1.');
end
if ~isfinite(radius) || radius <= 0 || ...
        centerX-radius <= 0 || centerX+radius >= ops.x(end) || ...
        radius >= ops.y(end)
    error('ipm:OmegaGaugeWindowDomain', ...
        ['The open support of the fixed anchor-bulk window must lie ' ...
        'inside x>0 and the positive y boundary.']);
end

radialSquared = ((ops.X-centerX)/radius).^2 + ...
    ((ops.Y-centerY)/radius).^2;
support = radialSquared < 1;
bump = zeros(expectedSize);
bump(support) = exp(1-1./(1-radialSquared(support)));
weightedBump = bump.*ops.integrationWeights;
weightSum = sum(weightedBump,'all');
xSupport = any(weightedBump > 0,1);
ySupport = any(weightedBump > 0,2);
supportPointsX = nnz(xSupport);
supportPointsY = nnz(ySupport);
if supportPointsX < 3 || supportPointsY < 3 || ...
        any(~isfinite(weightedBump),'all') || weightSum <= 0
    error('ipm:OmegaGaugeBulkSupport', ...
        ['The fixed anchor-bulk window must contain at least three ' ...
        'positive-weight nodes in each coordinate direction.']);
end
normalizedWeights = weightedBump/weightSum;
pointEnergy = rhoX.^2+rhoY.^2;
energy = sum(normalizedWeights.*pointEnergy,'all');
value = sqrt(energy);
localScale = sqrt(max(pointEnergy(support)));
condition = value/max(localScale,realmin);
if ~isfinite(value) || value < settings.cOmegaGaugeFloor || ...
        condition < settings.pointStrainConditionFloor
    error('ipm:DegenerateNormalization', ...
        ['The anchor-bulk gradient L2 gauge has negligible local ' ...
        'gradient energy.']);
end

window = struct('centerX',centerX,'centerY',centerY,'radius',radius, ...
    'support',support,'supportPointsX',supportPointsX, ...
    'supportPointsY',supportPointsY,'normalizedWeights', ...
    normalizedWeights,'value',value,'energy',energy, ...
    'condition',condition);
end
