function details = emptyTimestep(time,scale,activeLimiter)
%IPM.EVOLVE.EMPTYTIMESTEP Describe a state with no accepted local step yet.

if nargin < 3
    activeLimiter = 'initial';
end
physicalClockSpeed = exp(scale.logC_omega-scale.logC_l);
details = struct('dt',NaN,'rate',NaN,'dtCfl',NaN, ...
    'maxDtLimit',time.maxDt, ...
    'canonicalLimit',time.finalTime-scale.canonicalTime, ...
    'physicalLimit', ...
    (time.physicalFinalTime-scale.physicalTime)/physicalClockSpeed, ...
    'physicalClockSpeed',physicalClockSpeed,'realizedCfl',NaN, ...
    'activeLimiter',char(activeLimiter));
end
