function contract = gaugeContract(config,ops)
%IPM.EVOLVE.GAUGECONTRACT Serializable description of the active gauges.
%   This is provenance only.  It contains no state and cannot feed back into
%   the evolution.  Formula strings name the exact discrete quantities used
%   by isotropicGauge so saved results remain interpretable after a campaign.

scaling = config.scaling;
contract = struct( ...
    'schemaVersion',2, ...
    'scalingContract',scaling.scalingContract, ...
    'clock','canonical_tau_direct', ...
    'timeSpeed',1, ...
    'rateEvolution',struct( ...
        'logCl','d(log(C_l))/d(tau)=c_l', ...
        'logComega','d(log(C_omega))/d(tau)=c_omega', ...
        'physicalTime','dt/d(tau)=C_omega/C_l'), ...
    'rescaledEquation', ...
        'R_tau=-(U+(c_l*X+c_r,c_l*Y))*grad(R)+c_omega*R', ...
    'physicalGradient', ...
        'max_abs_rho_x=(C_l/C_omega)*max_abs_R_X', ...
    'feedback',struct('lengthScaleGain',1,'widthGaugeGain',0, ...
        'omegaGaugeGain',0,'travelingWaveGain',0, ...
        'rateLimiter','absent'), ...
    'length',length_contract(scaling,ops), ...
    'amplitude',amplitude_contract(scaling));
end

function value = length_contract(scaling,ops)
value = struct('name',scaling.lengthGauge,'formula','', ...
    'observable','','evaluation','discrete_algebraic', ...
    'registeredParameters',struct(), ...
    'phaseInterpretation','not_applicable', ...
    'anchorX',NaN,'nearestGridNode',NaN,'anchorNodeDistance',NaN, ...
    'anchorIsGridNode',false);
switch scaling.lengthGauge
    case 'omega_peak_location'
        value.formula = ...
            'c_l=physicalRhs_XX(X_peak)/(X_peak*R_XXX(X_peak))';
        value.observable = 'wall_omega_peak_location';
        value.evaluation = ...
            'quadratic_R_X_peak_then_linear_Dx_field_interpolation';
        value.registeredParameters = struct( ...
            'peakTrackingWidthFactor',scaling.peakTrackingWidthFactor);
        value.phaseInterpretation = ...
            'algebraic_candidate_with_recorded_full_phase_defect';
    case 'wall_omega_width'
        value.formula = 'c_l=-physical_width_rate/current_width';
        value.observable = 'wall_omega_level_width';
        value.evaluation = 'piecewise_linear_level_crossings';
        selectedLevel = max(scaling.adaptiveLevels);
        value.registeredParameters = struct( ...
            'adaptiveLevels',scaling.adaptiveLevels(:)', ...
            'selectedWidthLevel',selectedLevel, ...
            'selectionRule','maximum_adaptive_level');
    case 'symmetry_peak'
        value.formula = ...
            'c_l=-(U1(X_peak,0)-U1(0,0))/(X_peak-0)';
        value.observable = 'peak_separation';
        value.evaluation = ...
            'quadratic_R_X_peak_then_linear_velocity_interpolation';
        value.registeredParameters = struct( ...
            'peakTrackingWidthFactor',scaling.peakTrackingWidthFactor);
    case 'transport_anchor'
        anchorX = scaling.transportAnchorX;
        [distance,index] = min(abs(ops.x-anchorX));
        tolerance = 128*eps(max(1,max(abs(ops.x))));
        value.formula = 'c_l=-U1(X_anchor,0)/X_anchor';
        value.observable = 'V1(X_anchor,0)=0';
        value.evaluation = 'fixed_coordinate_linear_interpolation';
        value.anchorX = anchorX;
        value.registeredParameters = struct('transportAnchorX',anchorX);
        value.nearestGridNode = ops.x(index);
        value.anchorNodeDistance = distance;
        value.anchorIsGridNode = distance <= tolerance;
    case 'wall_density_width'
        value.formula = ...
            'c_l=-(U1(X_upper,0)-U1(X_lower,0))/(X_upper-X_lower)';
        value.observable = 'wall_density_level_width';
        value.evaluation = 'piecewise_linear_level_crossings';
        value.registeredParameters = struct( ...
            'lengthGaugeLevels',scaling.lengthGaugeLevels(:)');
    case 'local_strain'
        value.formula = 'c_l=-d_X(U1)(X_peak,0)';
        value.observable = 'wall_peak_local_strain';
        value.evaluation = ...
            'quadratic_R_X_peak_then_linear_strain_interpolation';
        value.registeredParameters = struct( ...
            'peakTrackingWidthFactor',scaling.peakTrackingWidthFactor);
end
end

function value = amplitude_contract(scaling)
value = struct('name',scaling.cOmegaGauge,'formula','', ...
    'observable','','evaluation','discrete_algebraic');
switch scaling.cOmegaGauge
    case 'gradient_energy'
        value.formula = [ ...
            'c_omega=-sum(w*(R_X*B_X+R_Y*B_Y))/' ...
            'sum(w*(R_X^2+R_Y^2))'];
        value.observable = 'global_discrete_gradient_energy';
        value.evaluation = 'fixed_grid_quadrature';
    case 'wall_omega_peak'
        value.formula = 'c_omega=-B_X(wall_peak)/R_X(wall_peak)';
        value.observable = 'wall_omega_peak';
        value.evaluation = 'active_peak_node';
    case 'wall_omega_quadratic_peak'
        value.formula = ...
            'c_omega=-Q[B_X](X_vertex)/Q[R_X](X_vertex)';
        value.observable = 'tracked_wall_omega_quadratic_peak';
        value.evaluation = ...
            'active_nonuniform_three_node_quadratic_vertex';
    case 'strain_point'
        value.formula = ...
            'c_omega=-d_X(U1[B])(0,0)/d_X(U1[R])(0,0)';
        value.observable = 'origin_strain';
    case 'anchor_wall_slope'
        value.formula = 'c_omega=-B_X(X_anchor,0)/R_X(X_anchor,0)';
        value.observable = 'fixed_anchor_wall_slope';
        value.evaluation = 'fixed_coordinate_linear_interpolation';
    case 'anchor_wall_window_l2'
        value.formula = 'c_omega=-<R_X,B_X>_w/<R_X,R_X>_w';
        value.observable = 'fixed_wall_window_l2';
    case 'anchor_wall_window_l4'
        value.formula = 'c_omega=-<R_X^3,B_X>_w/<R_X^4>_w';
        value.observable = 'fixed_wall_window_l4';
    case 'outer_wall_density_window_l2'
        value.formula = 'c_omega=-<R,B>_w/<R,R>_w';
        value.observable = 'fixed_X2_wall_density_l2';
        value.evaluation = ...
            'raised_cosine_window_X2_radius_omegaGaugeWindowRadius';
    case 'anchor_wall_template_projection'
        value.formula = 'c_omega=-<B_X,T>_w/<R_X,T>_w';
        value.observable = 'fixed_wall_template_projection';
    case 'anchor_bulk_gradient_l2'
        value.formula = ...
            'c_omega=-<grad(R),grad(B)>_W/<grad(R),grad(R)>_W';
        value.observable = 'fixed_bulk_window_gradient_l2';
    case 'none'
        value.formula = 'C_omega=1, c_omega=0 (prescribed)';
        value.observable = 'material_density_identity_scale';
        value.evaluation = ...
            'prescribed_identity_scale_with_counterfactual_peak_diagnostic';
end
end
