function cache = makeRhsCache(rho,rhoRate,flow,ops,scale)
%IPM.EVOLVE.MAKERHSCACHE Pack a transient exact accepted-state RHS cache.
%   The cache is derived data. Checkpoints deliberately omit it and rebuild
%   it from the restored accepted field, grid, and scale.

isAnisotropic = strcmp(ops.dynamicScaleGeometry,'anisotropic');
if isAnisotropic
    scaleRate = [flow.c_x;flow.c_y;flow.c_omega; ...
        exp(scale.logC_omega-scale.logC_l); ...
        flow.c_x*scale.X_shift+flow.c_r;1];
else
    scaleRate = [flow.c_l;flow.c_omega; ...
        exp(scale.logC_omega-scale.logC_l); ...
        flow.c_l*scale.X_shift+flow.c_r;1];
end
cache = struct('schemaVersion',1, ...
    'geometry',ops.dynamicScaleGeometry, ...
    'remeshCount',ops.remeshCount,'x',ops.x,'y',ops.y, ...
    'rho',rho,'scale',scale,'rhoRate',rhoRate, ...
    'scaleRate',scaleRate);
end
