function state = publishRemeshAttemptWarning(state,code,message)
%IPM.EVOLVE.PUBLISHREMESHATTEMPTWARNING Record a non-terminal mesh failure.

message = strrep(char(message),newline,' ');
row = struct('code',char(code),'metric','remesh_attempt', ...
    'value',NaN,'threshold',NaN,'message',message, ...
    'step',state.step,'canonicalTime',state.scale.canonicalTime, ...
    'physicalTime',state.scale.physicalTime, ...
    'remeshCount',state.ops.remeshCount);

if isfield(state.runMetadata,'remeshWarnings') && ...
        ~isempty(state.runMetadata.remeshWarnings)
    previous = state.runMetadata.remeshWarnings(end);
    if strcmp(previous.code,row.code) && ...
            strcmp(previous.message,row.message) && ...
            previous.remeshCount == row.remeshCount
        return;
    end
    state.runMetadata.remeshWarnings(end+1) = row;
else
    state.runMetadata.remeshWarnings = row;
end

fprintf(2,['WARNING [remesh-attempt/%s] step=%d, tau=%.8g, ' ...
    'physical t=%.8g, remesh=%d: %s. Current grid retained; ' ...
    'evolution continues.\n'],row.code,row.step,row.canonicalTime, ...
    row.physicalTime,row.remeshCount,row.message);
end
