function state = publishRemeshWarnings(state)
%IPM.EVOLVE.PUBLISHREMESHWARNINGS Persist and print post-remesh observations.
%   Diagnostic evaluation is deliberately non-terminal. Even an audit
%   implementation error is reduced to a recorded warning event.

try
    events = ipm.diagnostics.postRemeshWarnings( ...
        state.rho,state.flow,state.ops,state.scale,state.mass0, ...
        state.rhoRange0,state.config.diagnostics,state.config.remesh);
catch exception
    message = strrep(exception.message,newline,' ');
    events = struct('code','diagnostic_evaluation_error', ...
        'metric','post_remesh_audit','value',NaN,'threshold',NaN, ...
        'message',sprintf('%s: %s',exception.identifier,message));
end
if isempty(events)
    return;
end

rows = repmat(empty_row(),1,numel(events));
for index = 1:numel(events)
    rows(index) = struct( ...
        'code',events(index).code, ...
        'metric',events(index).metric, ...
        'value',events(index).value, ...
        'threshold',events(index).threshold, ...
        'message',events(index).message, ...
        'step',state.step, ...
        'canonicalTime',state.scale.canonicalTime, ...
        'physicalTime',state.scale.physicalTime, ...
        'remeshCount',state.ops.remeshCount);
    fprintf(2,['WARNING [post-remesh/%s] step=%d, tau=%.8g, ' ...
        'physical t=%.8g, remesh=%d: %s. Evolution continues.\n'], ...
        rows(index).code,rows(index).step,rows(index).canonicalTime, ...
        rows(index).physicalTime,rows(index).remeshCount, ...
        rows(index).message);
end

if ~isfield(state.runMetadata,'remeshWarnings') || ...
        isempty(state.runMetadata.remeshWarnings)
    state.runMetadata.remeshWarnings = rows;
else
    state.runMetadata.remeshWarnings(end+1:end+numel(rows)) = rows;
end
end

function row = empty_row()
row = struct('code','','metric','','value',NaN,'threshold',NaN, ...
    'message','','step',0,'canonicalTime',NaN,'physicalTime',NaN, ...
    'remeshCount',0);
end
