function peak = quadraticPeakFunctional(values,x,peakIndex)
%IPM.EVOLVE.QUADRATICPEAKFUNCTIONAL Exact local quadratic peak functional.
%   The active peak node and its two neighbours define one quadratic on a
%   possibly nonuniform grid.  The returned weights evaluate any field on
%   that same quadratic at its interior vertex.  Consequently, while the
%   active stencil is fixed, the envelope theorem gives
%       d_tau peak(values) = weights*d_tau(values(indices)).

values = values(:)';
x = x(:)';
if numel(values) ~= numel(x) || numel(x) < 3 || ...
        ~isnumeric(values) || ~isreal(values) || ...
        any(~isfinite(values)) || ~isnumeric(x) || ~isreal(x) || ...
        any(~isfinite(x)) || any(diff(x) <= 0) || ...
        ~isnumeric(peakIndex) || ~isreal(peakIndex) || ...
        ~isscalar(peakIndex) || ~isfinite(peakIndex) || ...
        peakIndex ~= round(peakIndex)
    error('ipm:DegenerateNormalization', ...
        'The quadratic wall-omega peak stencil is invalid.');
end
if peakIndex <= 1 || peakIndex >= numel(x)
    error('ipm:DegenerateNormalization', ...
        'The quadratic wall-omega peak stencil is not interior.');
end

indices = peakIndex-1:peakIndex+1;
localValues = values(indices);
hLeft = x(peakIndex)-x(peakIndex-1);
hRight = x(peakIndex+1)-x(peakIndex);
leftDifference = localValues(1)-localValues(2);
rightDifference = localValues(3)-localValues(2);
curvature = (leftDifference/hLeft+rightDifference/hRight) / ...
    (hLeft+hRight);
linearCoefficient = rightDifference/hRight-curvature*hRight;

valueScale = max(abs(localValues));
curvatureCondition = abs(curvature)*hLeft*hRight / ...
    max(valueScale,realmin);
roundoffFloor = 512*eps(1)*max(valueScale,realmin) / ...
    (hLeft*hRight);
if curvature >= 0 || abs(curvature) <= roundoffFloor || ...
        localValues(2) < localValues(1) || ...
        localValues(2) < localValues(3)
    error('ipm:DegenerateNormalization', ...
        ['The active wall-omega stencil does not define a resolved ' ...
        'concave local maximum.']);
end

vertexOffset = -linearCoefficient/(2*curvature);
vertexX = x(peakIndex)+vertexOffset;
coordinateTolerance = 128*eps(max(1,max(abs(x(indices)))));
if vertexX <= x(indices(1))+coordinateTolerance || ...
        vertexX >= x(indices(end))-coordinateTolerance
    error('ipm:DegenerateNormalization', ...
        'The quadratic wall-omega vertex is not strictly interior.');
end

xi = vertexOffset;
weights = [ ...
    xi*(xi-hRight)/(hLeft*(hLeft+hRight)), ...
    -(xi+hLeft)*(xi-hRight)/(hLeft*hRight), ...
    xi*(xi+hLeft)/(hRight*(hLeft+hRight))];
peakValue = sum(weights.*localValues);
weightCondition = 1/sum(abs(weights));
stationarityResidual = 2*curvature*vertexOffset+linearCoefficient;
stationarityScale = max([abs(2*curvature*vertexOffset), ...
    abs(linearCoefficient),realmin]);
activeNodeMargin = (localValues(2)-max(localValues([1,3]))) / ...
    max(peakValue,realmin);
vertexInteriorFraction = min(vertexX-x(indices(1)), ...
    x(indices(end))-vertexX)/(x(indices(end))-x(indices(1)));
finiteValues = [curvature,curvatureCondition,vertexX,weights, ...
    peakValue,weightCondition,activeNodeMargin,vertexInteriorFraction];
if any(~isfinite(finiteValues)) || peakValue <= 0 || ...
        weightCondition <= 0
    error('ipm:DegenerateNormalization', ...
        'The quadratic wall-omega peak functional is nonfinite or nonpositive.');
end

peak = struct( ...
    'indices',indices, ...
    'weights',weights, ...
    'x',vertexX, ...
    'value',peakValue, ...
    'curvature',curvature, ...
    'stationarityResidual',stationarityResidual, ...
    'normalizedStationarityResidual', ...
        stationarityResidual/stationarityScale, ...
    'curvatureCondition',curvatureCondition, ...
    'weightCondition',weightCondition, ...
    'activeNodeMargin',activeNodeMargin, ...
    'vertexInteriorFraction',vertexInteriorFraction, ...
    'gridValue',localValues(2), ...
    'relativeSubgridLift',(peakValue-localValues(2))/peakValue);
end
