function [rhs,flow] = rhs(rho,ops,scale)
%IPM.EVOLVE.RHS Shared physical/rescaled IPM right-hand side.

isAnisotropic = strcmp(ops.dynamicScaleGeometry,'anisotropic');
if isAnisotropic
    if nargin < 3
        error('ipm:MissingAnisotropicScale', ...
            ['Anisotropic dynamic scaling requires the current scale so ' ...
            'every stage uses its own aspect ratio.']);
    end
    aspect = exp(scale.logC_y-scale.logC_l);
else
    aspect = 1;
end

[u1,u2,psi,source,poissonResidual,poissonSolveInfo] = ...
    ipm.field.velocity(rho,ops,aspect);
physicalFlow = struct('u1',u1,'u2',u2,'psi',psi,'source',source, ...
    'poissonResidual',poissonResidual, ...
    'poissonSolveInfo',poissonSolveInfo);
% Most exact dynamic gauges assemble their own rescaled transport below and
% never consume the unscaled transport RHS.  Avoid paying for that second
% WENO evaluation unless the physical evolution or a width/peak-rate gauge
% explicitly needs it.  This is a lazy evaluation only: the algebraic gauge
% definitions, canonical clock, CFL rate, and returned RHS are unchanged.
needsPhysicalRhs = ~ops.rescaling.enabled || ...
    (~isAnisotropic && any(strcmp(ops.rescaling.lengthGauge, ...
        {'omega_peak_location','wall_omega_width'})));
if needsPhysicalRhs
    [physicalRhs,~,~,~] = ipm.evolve.assembleRhs( ...
        rho,u1,u2,0,0,0,0,ops,ops.transportBoundaryMode);
else
    physicalRhs = [];
end

if isAnisotropic
    [rates,baseRhs,details,transportU1,transportU2,extras] = ...
        ipm.evolve.anisotropicGauge(rho,physicalRhs,physicalFlow,ops);
    rateVector = [rates.cx,rates.cy,rates.comega,rates.cr];
else
    details = ipm.diagnostics.trackFeatures(rho,physicalRhs,physicalFlow,ops);
    [cL,cOmega,cR,baseRhs,details,transportU1,transportU2] = ...
        ipm.evolve.isotropicGauge( ...
        rho,physicalRhs,physicalFlow,ops,details);
    rates = struct('cx',cL,'cy',cL,'comega',cOmega,'cr',cR, ...
        'conservativeSource',2*cL+cOmega);
    rateVector = [cL,cOmega,cR];
    extras = struct();
end

if ops.rescaling.enabled
    translationScale = max(abs(ops.rescaling.pinX),1);
else
    translationScale = 1;
end
[rateMagnitude,~] = ipm.evolve.rateMagnitude( ...
    rateVector,translationScale);
% Canonical tau is the integration clock.  There is deliberately no
% state-dependent rate cap or auxiliary time reparameterization.
rhs = baseRhs+rates.comega*rho;

flow = common_flow(physicalFlow,details,rates, ...
    rateMagnitude,transportU1,transportU2,aspect);
if isAnisotropic
    flow.anisotropicGaugeMode = extras.mode;
    flow.peakTranslationResidual = extras.peakTranslationResidual;
    flow.peakTranslationRawVelocity = extras.peakTranslationRawVelocity;
    flow.peakTranslationTargetVelocity = ...
        extras.peakTranslationTargetVelocity;
    flow.canonicalPeakTranslationTargetVelocity = ...
        extras.peakTranslationTargetVelocity;
end
end

function flow = common_flow(physical,details,rates, ...
        rateMagnitude,transportU1,transportU2,aspect)
flow = physical;
flow.aspect = aspect;
flow.c_l = rates.cx;
flow.c_x = rates.cx;
flow.c_y = rates.cy;
flow.c_omega = rates.comega;
flow.c_r = rates.cr;
flow.canonicalCL = rates.cx;
flow.canonicalCX = rates.cx;
flow.canonicalCY = rates.cy;
flow.canonicalCOmega = rates.comega;
flow.canonicalCR = rates.cr;
% Retained only so result-v2 readers can verify the removed clock factor.
flow.timeSpeed = 1;
flow.canonicalRateMagnitude = rateMagnitude;
flow.conservativeSource = rates.conservativeSource;
flow.canonicalConservativeSource = rates.conservativeSource;
flow.aspectRate = rates.cy-rates.cx;
flow.canonicalAspectRate = rates.cy-rates.cx;
flow.transportU1 = transportU1;
flow.transportU2 = transportU2;

flow.c_lNominal = details.c_lNominal;
flow.canonicalCLNominal = details.c_lNominal;
flow.lengthScaleGain = details.lengthScaleGain;
flow.widthCorrection = details.widthCorrection;
flow.canonicalWidthCorrection = details.widthCorrection;
flow.widthRateScale = details.widthRateScale;
flow.widthControlMode = details.widthControlMode;

copyNames = {'peakGridPoints','supportGridPoints','coreGridPoints', ...
    'verticalPeakGridPoints','verticalSupportGridPoints', ...
    'verticalCoreGridPoints','targetPeakGridPoints', ...
    'targetSupportGridPoints','targetCoreGridPoints', ...
    'peakExpansionRatio','resolutionFactor','safetyFactor', ...
    'trackedWallPeak','trackedWallPeakWidth','trackedWallCoreWidth', ...
    'rhoXInf', ...
    'trackedVerticalPeakWidth','trackedVerticalCoreWidth', ...
    'strain','strainError','strainCondition','omegaGaugeEnergy', ...
    'omegaGaugeEnergyX','omegaGaugeEnergyY', ...
    'omegaGaugeForcingX','omegaGaugeForcingY', ...
    'omegaGaugeForcing','omegaGaugeAbsoluteForcing', ...
    'omegaGaugeForcingCancellationRatio', ...
    'omegaGaugeResidual','omegaGaugePeakX','omegaGaugePeakCondition', ...
    'omegaGaugeQuadraticPeakX','omegaGaugeQuadraticPeakValue', ...
    'omegaGaugeQuadraticForcing', ...
    'omegaGaugeQuadraticCurvature', ...
    'omegaGaugeQuadraticStationarityResidual', ...
    'omegaGaugeQuadraticNormalizedStationarityResidual', ...
    'omegaGaugeQuadraticCurvatureCondition', ...
    'omegaGaugeQuadraticWeightCondition', ...
    'omegaGaugeQuadraticActiveNodeMargin', ...
    'omegaGaugeQuadraticActiveSelectionMargin', ...
    'omegaGaugeQuadraticStencilCenterX', ...
    'omegaGaugeQuadraticVertexInteriorFraction', ...
    'omegaGaugeQuadraticRelativeSubgridLift', ...
    'omegaGaugeQuadraticRateScale', ...
    'omegaGaugeAnchorX','omegaGaugeAnchorValue', ...
    'omegaGaugeAnchorCondition','omegaGaugeReferenceAnchorValue', ...
    'omegaGaugeWindowCenter','omegaGaugeWindowRadius', ...
    'omegaGaugeWindowValue','omegaGaugeWindowCondition', ...
    'omegaGaugeWindowEnergy','omegaGaugeReferenceWindowValue', ...
    'omegaGaugeWindowMomentOrder','omegaGaugeWindowMoment', ...
    'omegaGaugeWindowSupportPoints','omegaGaugeWindowRateScale', ...
    'omegaGaugeTemplateCenter','omegaGaugeTemplateRadius', ...
    'omegaGaugeTemplateSupportPoints','omegaGaugeTemplateValue', ...
    'omegaGaugeTemplateCondition','omegaGaugeTemplateRateScale', ...
    'omegaGaugeReferenceTemplateValue','omegaGaugeBulkCenterX', ...
    'omegaGaugeBulkCenterY','omegaGaugeBulkRadius', ...
    'omegaGaugeBulkSupportPointsX','omegaGaugeBulkSupportPointsY', ...
    'omegaGaugeBulkValue','omegaGaugeBulkCondition', ...
    'omegaGaugeBulkEnergy','omegaGaugeBulkRateScale', ...
    'omegaGaugeReferenceBulkValue', ...
    'transportAnchorX','lengthGaugeStrain','trackedPeakX', ...
    'trackedPeakOffset','peakLocationRhoXX', ...
    'peakLocationRhoXXScale','peakLocationPhaseDefect', ...
    'peakLocationResponseCondition','wallDensityLowerSlope', ...
    'wallDensityUpperSlope','wallDensityLowerCondition', ...
    'wallDensityUpperCondition','wallDensityLowerBracket', ...
    'wallDensityUpperBracket'};
for index = 1:numel(copyNames)
    name = copyNames{index};
    flow.(name) = details.(name);
end

rateNames = {'strainRateResidual','omegaPeakRateResidual', ...
    'omegaGaugeQuadraticRateResidual', ...
    'omegaGaugeAnchorRateResidual','omegaGaugeWindowRateResidual', ...
    'omegaGaugeTemplateRateResidual','omegaGaugeBulkRateResidual', ...
    'pinGaugeResidual','pinTransportVelocity','transportAnchorVelocity', ...
    'lengthGaugeResidual','peakLocationFullPhaseResidual', ...
    'peakLocationNormalizedFullPhaseResidual','peakTransportVelocity', ...
    'travelingWaveResidual'};
for index = 1:numel(rateNames)
    name = rateNames{index};
    flow.(name) = details.(name);
end
flow.canonicalTransportAnchorVelocity = details.transportAnchorVelocity;
end
